### ISSUE TITLE
Spec for entity menus

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6170]
We're going to consolidate and standardize a bunch of the "top-right" icons and actions on question detail, dashboard detail, collection detail, and data reference detail pages. Menu components were implemented in https://github.com/metabase/metabase/pull/6162

Details for each page and state's buttons and menu items are as follows:

## Saved question page
**1. Edit menu:**
- [edit document icon] Edit this question
- [revision history icon] View revision history
- [move icon] Move
- [archive action icon] Archive

**2. Share menu:**
- [add to dashboard icon] Add to a dashboard
- [down arrow with bar below it icon] Download results **(Note: this means the current download button, which is currently below the query builder bar, should be removed since it's in the menu now.)**
- [embed icon] Sharing and embedding **(Note: the current sharing/embedding button below the query builder should also be removed since it's in the menu now, too.)**

**3. More menu:**
- [alerts will eventually go here]
- [console icon] View the SQL

## New question, and new-question-starting-from-x pages

**1. [new floppy disk icon] Save button**
**2. Share menu:**
- [add to dashboard icon] Add to a dashboard
- [down arrow with bar below it icon] Download results
- [embed icon] Sharing and embedding

**3. More menu:**
- (alerts will eventually go here)
- [console icon] View the SQL

## Saved question edit state
- Edit bar across the top with just `Cancel` and `Save`
- Edit, Share, and More menus should be hidden

## Dashboard normal state
**1. Edit menu:**
- [edit document icon] Edit this dashboard
- [revision history icon] View revision history
- [archive action icon] Archive

**2. Sharing and embedding (button instead of menu)**

**3. More menu:**
- [full-screen icon] Enter full-screen mode
- [clock icon] Auto-refresh (Clicking this should close the menu and open the auto-refresh options menu instead. **There will be another followup issue with a new design to represent the ticking down timer until the next refresh.**)
- (If night mode is off:) [Moon icon] Night mode
- (If night mode is on:) [Sun icon] Day mode

## Dashboard edit state
- Edit bar across the top with just `Cancel` and `Save`. `Archive` should no longer be there.
- Edit, Share, and More menus should be hidden
- `Add Card` and `Add Filter` buttons+icons should be in the place where the menus were. **Note: we'll be redesigning where these two buttons go in a separate issue soon after.**

## Collection detail page
**1. Edit menu:**
- [Edit document icon] Edit collection details
- [Move icon] Move this collection
- [Archive action icon] Archive this collection

**2. Share menu**
- [lock icon] Set permissions

## New, unsaved SQL question
**1. Save button**

**2. Share menu:**
- [add to dashboard icon] Add to a dashboard
- [down arrow with bar below it icon] Download results
- [embed icon] Sharing and embedding

**3. Variable icon/button**

The Variables button should have a vertical divider to the left of it, as depicted here (though the mock shows a More menu icon that shouldn't be there):

![new sql question](https://user-images.githubusercontent.com/2223916/31568347-b120f832-b028-11e7-89e8-663439bf25ee.png)

When clicked, the variables icon can disappear, since the side panel can be closed with the X icon, like this:

![sql - variables](https://user-images.githubusercontent.com/2223916/31568528-b61f2c36-b029-11e7-97da-6550fa383713.png)

## Saved SQL question
**1. Edit menu:**
- [edit document icon] Edit this question
- [revision history icon] View revision history
- [move icon] Move
- [archive action icon] Archive

**2. Share menu:**
- [add to dashboard icon] Add to a dashboard
- [down arrow with bar below it icon] Download results
- [embed icon] Sharing and embedding

**3. Variable icon/button**

## Saved SQL question edit state
- Edit bar with just `Cancel` and `Save`
- No menu or icons except for the Variables one, like this:

![sql - edit state](https://user-images.githubusercontent.com/2223916/31568552-d6c9ad4e-b029-11e7-81ce-5e0bde7325de.png)

## Data reference detail pages
- the current pencil+edit text buttons should be replaced with our standard just-pencil button

**Comment by mazameli** [comment]
I'd like to add this to the 0.28 milestone unless anyone objects. This got partially done in the Alerts work, but it needs to be carried out to completion in order to make sense.

**Comment by mazameli** [comment]
@kdoh you and I talked about this being not a lot of work to implement (~1/2 to 1 day) and that we thought we'd want it in the first batch of Spaces work so that there are clear places to put things like the edit, move, and permissions actions for collections, so I've added this to the [Spaces project](https://github.com/metabase/metabase/projects/4).

**Comment by MarkRx** [comment]
I think the "Add a question" icon should only show up if a dashboard is being edited. Right now it shows up as a main icon on a dashboard to the left of the edit icon.

![image](https://user-images.githubusercontent.com/17504314/50606834-1bc01580-0e95-11e9-89fb-c25a3c1747ef.png)

**Comment by salsakran** [comment]
@kdoh @mazameli what are your thoughts about this ?

**Comment by mazameli** [comment]
A bunch of the details of this spec don't really apply anymore given the QB refactor, specifically for saved questions. 

Revisiting the organization and placement of _dashboard_ buttons/icons is still really relevant, but I don't think this spec represents how I'd personally want to execute that reorganization anymore. 

I think we should try and make dashboard action button placement match up with the new placement of actions on question pages. E.g. if things like `move`, `archive`, and `revision history` are in a menu next to a saved question's title, it makes sense if that's where they are for dashboards as well.

This has been on my mind, but I've added it as a to-do in the `notebook-mode` pr to keep track of it.

**Comment by salsakran** [comment]
sounds like we should close this out then?
