### ISSUE TITLE
Don't know how to map column type 'citext'

### ISSUE THREAD

**Issue by witwall** [metabase/metabase#6172]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OS X 10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres
- Metabase version: (e.x. 0.19.3)
10
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Mac app
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
H2
- *Repeatable steps to reproduce the issue*
```
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;

-- create foreign table
CREATE TABLE customer_reviews
(
    customer_id citext,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title citext,
    product_sales_rank BIGINT,
    product_group citext,
    product_category citext,
    product_subcategory citext,
    similar_product_ids CHAR(10)[]
)
```
when using SQL to build question, it is ok.
when building custom question, get the following warning, 
-------
```
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type 'citext' to a Field base_type, falling back to :type/*.
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type 'citext' to a Field base_type, falling back to :type/*.
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type 'citext' to a Field base_type, falling back to :type/*.
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type 'citext' to a Field base_type, falling back to :type/*.
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type 'citext' to a Field base_type, falling back to :type/*.
Oct 14 08:31:46 WARN metabase.driver.generic-sql :: Don't know how to map column type '_bpchar' to a Field base_type, falling back to :type/*.
```

if possible to add 3rd column type mapping without recompiling metabase? for example support more column type through extra configuration.

**Comment by camsaul** [comment]
@witwall I'll add `citext`. I've used that one a bunch of times in the past. But what's a `_bpchar`?

**Comment by camsaul** [comment]
@witwall ?

**Comment by witwall** [comment]
@camsaul sorry,  and here is the explanation
![image](https://user-images.githubusercontent.com/3222056/33110346-3287f696-cf82-11e7-92fa-93087c868c31.png)

bpchar (“blank-padded char”, the internal name of the character data type)

**Comment by camsaul** [comment]
@witwall so it turns out we already have a mapping for `bpchar`. I added one for `citext` in #6453. It looks like `_bpchar` (with the underscore) is an *array* of `bpchar`s. Currently Metabase doesn't do anything special with arrays, which is why there's no explicit type mapping, causing the warning that you saw. We have an open issue to explicitly support arrays in DBs and do clever things like see if they contain certain values (filtering against arrays): #2974
