### ISSUE TITLE
"ID" suffix is missed in Filter suggest for field names

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6179]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a database and table with column names containing an "ID" suffix (for example: Country ID, Campaign ID, User ID, etc.)
2. Go to Custom queries window
3. Click to Filter field to enable suggest list

Fields are without "ID" suffix:
![2017-10-16 15 53 49](https://user-images.githubusercontent.com/1096609/31613958-5ca097a6-b28d-11e7-9283-07bfcd30b624.png)

4. Click onto the field name suggested

Field has an "ID" suffix:
![2017-10-16 15 54 00](https://user-images.githubusercontent.com/1096609/31614008-89ed348a-b28d-11e7-9c9c-0938e8cb3c10.png)

**Comment by ricardoekm** [comment]
+1

**Comment by flamber** [comment]
This was change in 0.40, when "Advanced" option was removed from "Friendly Names" functionality - this is 0.41.1:
![image](https://user-images.githubusercontent.com/1447303/140966066-fe9f3861-9d73-40a3-9f6a-8e4ed49a1fa9.png)
