### ISSUE TITLE
X-Rays: Show most interesting features for each field in table/segment comparison

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#6180]
Currently we show same predefined features for each field:

<img width="1396" alt="screen shot 2017-10-16 at 22 07 43" src="https://user-images.githubusercontent.com/6034928/31631882-d6b0ad8e-b2c3-11e7-9995-37714018c3fa.png">

Probably requires rethinking the whole UI of "Full breakdown" section.

**Comment by sbelak** [comment]
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.
