### ISSUE TITLE
X-Rays: Multiple UI issues with "Potentially interesting differences"

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#6181]
- For some numeral comparisons the first number is missing
- The single differences (or " contributors" in backend jargon) aren't grouped by their respective fields 
- Connected to #6180 and related to the upcoming data insights feature
<img width="1415" alt="screen shot 2017-10-16 at 22 07 34" src="https://user-images.githubusercontent.com/6034928/31635297-e852a50a-b2ce-11e7-912b-b48ef5b2624e.png">

**Comment by sbelak** [comment]
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.
