### ISSUE TITLE
X-Rays: Field-by-field comparison

### ISSUE THREAD

**Issue by attekei** [metabase/metabase#6182]
If you are on a segment/table comparison page, clicking an individual field should let you see detailed comparison for it (for instance all features of it), i.e. zoom in to it. Not sure if this would be a separate page or somehow included to the segment/table comparison page itself.

As an example, clicking Created At row here would show detailed information about it.
<img width="1373" alt="screen shot 2017-10-16 at 22 07 05" src="https://user-images.githubusercontent.com/6034928/31635466-8017f516-b2cf-11e7-909a-833634963e89.png">

If this was a separate page, then this would maybe enable also different kinds of comparisons of two fields than just being a way to zoom in to individual field in a table/segment comparison.

**Comment by sbelak** [comment]
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.
