### ISSUE TITLE
Field filter field-to-map-to selector shouldn't load every field in the whole DB

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6183]
Right now, the dropdown to choose the field to map to a field filter variable loads every single field in the selected DB, which causes major performance problems for DBs with thousands of fields.

This is a proposal to replace the current popover menu with our existing query builder data selector, with some caveats:
- the popover shouldn't ever show the databases, since the user will have already selected a database 
- the first possible step is schema selection, provided there is more than a single schema in the current DB
- the table selection step won't be the last step; field selection will be.
- each selection step should use the existing logic to determine if it has a filter search box at the top of its list

Here's how the UI should look:

**Default state:**

![01](https://user-images.githubusercontent.com/2223916/31640737-eefa863c-b294-11e7-9bd8-d09b5e4140b7.png)

**Schema selection, if there is at least 2 schemas in the DB:**

![02](https://user-images.githubusercontent.com/2223916/31640742-f4916f48-b294-11e7-828a-6fcecb42551e.png)

**Table selection, with right arrows to indicate there's a next step:**

![03](https://user-images.githubusercontent.com/2223916/34186071-5da4d6c0-e4de-11e7-9f97-a8b372f2b01f.png)

**Field selection:**

![04](https://user-images.githubusercontent.com/2223916/31640747-fdda1fb4-b294-11e7-9ebc-04ff0afec303.png)

**Selected field:**

![05](https://user-images.githubusercontent.com/2223916/31640753-025d1622-b295-11e7-978e-57092198af96.png)

**Comment by salsakran** [comment]
I think we should try to include the table name if possible in the final screen with the selected field.

**Comment by mazameli** [comment]
Cool, I went back and forth on that.

**Comment by mazameli** [comment]
I updated the mock to depict what we basically do already in the UI to show the selected field's table.

**Comment by mjalkio** [comment]
Another issue I have with the current dropdown is that it includes cruft/inactive tables. This would be fixed with the proposal, but it's a big issue on our deployment (we have a lot of temporary tables that get created during ETL).

**Comment by salsakran** [comment]
fixed via #6730
