### ISSUE TITLE
Error when I run metabase backend

### ISSUE THREAD

**Issue by qin4zhang** [metabase/metabase#6185]
### Bugs
- Your browser and the version: Chrome 61.0.3163.79
- Your operating system: Windows 10
- Your databases: Postgres 9.6.5
- Metabase version: v0.27.0-snapshot
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue*
I have pulled the master branch of metabase  and when i run the backend development server with the following scripts:

set MB_DB_TYPE=postgres
set MB_DB_DBNAME=metabase
set MB_DB_PORT=5432
set MB_DB_HOST=localhost
set MB_DB_USER=<username>
set MB_DB_PASS=<pwd>
set MB_ENCRYPTION_SECRET_KEY=<secret_key>
lein ring server-headless

after several minutes error occurs,here is the log:
10-17 13:46:00 ERROR core.ErrorLogger :: Job (DEFAULT.metabase.task.cleanup-temporary-computation-job-results.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.postgresql.util.PSQLException: ERROR:  operator does not exist: timestamp without time
zone < character varying

how can i solve it?

**Comment by salsakran** [comment]
fixed in #6196

**Comment by camsaul** [comment]
> fixed in #6196

Closing this since it was fixed
