### ISSUE TITLE
AWS Elasticbeanstalk installation fails with error 

### ISSUE THREAD

**Issue by suhair** [metabase/metabase#6186]
I am trying to launch Metabase elasticbeanstalk but getting the following error. 
Any idea why i am getting this error. Tried an older version and the same result. Please help.
![image](https://user-images.githubusercontent.com/165396/31657487-2b162b38-b337-11e7-958b-2c41d5e7ec27.png)

**Comment by sanjredfield** [comment]
I am also seeing this issue. Would very much appreciate some assistance.

**Comment by phiberjenz** [comment]
I also get this error

**Comment by suhair** [comment]
Any solutions?

**Comment by bcbob** [comment]
Same here.

**Comment by suhair** [comment]
Ahh this seems to be an error due to amazon's new design. In that page of AWS there is an option **_You can switch back to the previous version while we finalize the design_**. When used that design and go through all the steps including creating RDS, metabse installation works smoothly. Closing the issue as it is an AWS template and design issue.

**Comment by bcbob** [comment]
I don't see that option to "switch back to previous version"
