### ISSUE TITLE
A user should be able to mark an embed as "locked"

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6189]
Sometimes, you'll want to embed a dashboard that is not parameterized, but not allow someone without a server signed request to view it. 

We should allow an entire embed to be server signed without needing a parameter, and reject any embed that isn't signed

**Comment by tlrobinson** [comment]
@salsakran Isn't this already possible?

**Comment by salsakran** [comment]
nope, you need to select a parameter. Or at least that was the case in october.

**Comment by salsakran** [comment]
This seems to be working now. I've gone over my notes from the conversation that lead to this being opened, but I can't seem to reproduce the report.
