### ISSUE TITLE
Password for database are not are not saved properly

### ISSUE THREAD

**Issue by liemlyquan** [metabase/metabase#6195]
### Bugs
- Your browser and the version: Safari 11.0 and 61.0.3163.100 
- Your operating system: Mac OS High Sierra
- Your databases: MongoDB
- Metabase version: v0.26.1
- Metabase hosting environment: Ubuntu
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

  - Go to "Metabase Admin Panel"
  - Go to "Databases"
  - Select existing MongoDB 
  - The prefilled password is incorrect (difference in length compared to the original one)

In my case, I would love to disable the automatic sync since it can affect our production server, so 
  - I can input the correct password and choose "This is a large database, so let me choose when Metabase syncs and scans". 
  - However, when I want go to "Scheduling" tab, the password will reset back to incorrect prefilled one, so I can never press "Save Changes", it will cause authentication failed
  - I tried workaround by choosing the SCANNING FOR FILTER VALUES to "Never, I'll do this manually if I need to", and when back to the "Connection" to change password, but now, the SCANNING FOR FILTER VALUES is reset. So basically, tab change will change old tab data reset

**Comment by salsakran** [comment]
You shouldn't input a new password unless it's changing it.

We'll update partial details on that form, and definitely don't push the database password down to the frontend client, so the number of characters in that field is arbitrary.

**Comment by liemlyquan** [comment]
But without changing the password the password, I cannot select the "SCANNING FOR FILTER VALUES". It will always return Authentication failed.

**Comment by constantx** [comment]
This is is a problem, we can't change the MongoDB connection's scheduling, cause we always get a "AuthenticationFailed" message, even though the database connection is already saved.
<img width="1184" alt="image 2018-09-12 at 10 06 50 am" src="https://user-images.githubusercontent.com/113969/45399773-927d9c80-b673-11e8-9bc9-0012fd948918.png">

**Comment by faisaliftikhar66** [comment]
@constantx I have also a same exactly issue like that. Did you get fix on your side. I need help and support to get rid from that issue regarding mongo connection "AuthenticationFailed".

**Comment by faisaliftikhar66** [comment]
@salsakran please see above both comments and provide solution accordingly. Thanks i am waiting.

**Comment by constantx** [comment]
Still happening on the latest update of Metabase.

**Comment by gchamon** [comment]
this is preventing me from configuring sync schedule after the database has already been added. My workaround is to log directly to the database (we are using postgres), go to `public.metabase_database` and set the column `metadata_sync_schedule` to the correct cron config

**Comment by flamber** [comment]
@gchamon 
Which version of Metabase? Please post "Diagnostic Info" from Admin > Troubleshooting.
Are you also trying to edit the Scheduling for a MongoDB database - or a different database type?
Seems related to #6262.
