### ISSUE TITLE
Changes in query constructor view are not applying to SQL mode view until running query

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6198]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce 1:
1. Open Custom query constructor and set some filter for query
2. Click "Switch to SQL" button:
![question metabase 2017-10-18 15-15-16](https://user-images.githubusercontent.com/1096609/31718126-5dc2b0a2-b417-11e7-89d2-3622a440868a.png)
The question area in SQL mode is empty although it expected that query with filter will be there

Steps to reproduce 2:
1. Open Custom query constructor and set some filter for query
2. Click "Get answer" button and click "View in SQL" when results are viewd
The query will be displayed with correct filter value:
![question metabase 2017-10-18 15-21-44](https://user-images.githubusercontent.com/1096609/31718314-27bc5bc4-b418-11e7-802f-42a1dafce1ee.png)
3. Change filter value and click "View in SQL" again
The query will be displayed with incorrect not updated filter:
![question metabase 2017-10-18 15-23-58](https://user-images.githubusercontent.com/1096609/31718378-7228b694-b418-11e7-8d8f-4d54bab74e78.png)
Clicking then "Convert to SQL" button resulting the same incorrect filter is saved in SQL editor mode

**Comment by flamber** [comment]
This was fixed in 0.33, when the "View the SQL" button moved to top-right of the Notebook editor.
