### ISSUE TITLE
Impossible to switch onto query Builder view if SQL question area is not empty

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6199]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Move to SQL questions mode from Custom query view 
"Switch to Builder" button is clickable
2. Enter some question into SQL area (there is no difference correct or incorrect one)
"Switch to Builder" button is not clickable:
![2017-10-17 16 15 50](https://user-images.githubusercontent.com/1096609/31719123-0f2c553e-b41b-11e7-8e22-068b1d123776.png)

The same behavior is in case if we switched to SQL editor from query Builder and then trying to switch back.

**Comment by salsakran** [comment]
This is intentional, as we can't always transform sql query back into our query language.

You can always just hit the back button, and the last executed query will be shown
