### ISSUE TITLE
Amazon Redshift - SSL certificate expiring

### ISSUE THREAD

**Issue by gitsh84** [metabase/metabase#6200]
Hey,
We've received a mail from AWS that:
"Action Required: Amazon Redshift - SSL certificate expiring on October 23rd 2017"
More info here:
https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-transitioning-to-acm-certs.html

We have a metabase installation (great product BTW) which connect to AWS Redshift and I was wondering if this will effect us in any way and if so what should be done ?

Thanks !

**Comment by salsakran** [comment]
Our most recent version uses a driver that should be compatible. 

If you're not on 0.26, we suggest upgrading!

**Comment by gitsh84** [comment]
Thanks for your reply @salsakran.
Unfortunately upgrading to a new version never worked for me...
I tried doing it from multiple versions (I currently run various versions from 0.22.2 to 0.24 ...).
Every time I tried to upgrade to the latest version it's not going smoothly (instances is not healthy) and I end up rolling back the upgrade.

Do you maybe have any other suggestion or what can be done ? Can I ssh the instance and upgrade the driver or the CA bundle ?

Thanks again.

**Comment by gitsh84** [comment]
Ok so now I'm getting:
/api/health 503 (Service Unavailable)
when I try to access the dashboard...
Any idea what do to here ?

**Comment by nevir** [comment]
Seems like you're likely ok on older versions as well: 

* prior to 0.26 it looks like the redshift driver was using the postgres driver
* the postgres driver [explicitly disables SSL certificate checks](https://github.com/metabase/metabase/blob/7297e1ace2646484f29ebe83bd6357e557226795/src/metabase/driver/postgres.clj#L90)

**Comment by camsaul** [comment]
@gitsh84 @nevir to clarify we switched to the official Redshift JDBC driver for 0.26.2, not 0.26.0. We shipped 0.26.2 on Friday (3 days ago) so give that a try and things should work.

**Comment by nevir** [comment]
Aha!

**Comment by camsaul** [comment]
@gitsh84 does upgrading to 0.26.2 fix the issue for you?

**Comment by camsaul** [comment]
@gitsh84 ??

**Comment by gitsh84** [comment]
@camsaul Everything seems to be working, thanks !

**Comment by camsaul** [comment]
Good to hear :)
