### ISSUE TITLE
Oh, Start failed after I upgraded to v0.26.1 from v0.25.2

### ISSUE THREAD

**Issue by zhaosaisai** [metabase/metabase#6206]
I toke much time to do my upgrade, but when i start dev, the metabase occured an error so thoroughly.

my environments:

```bash
mac: 10.11.1 (15B42)
metabse: v0.25.2 -> 0.26.1
```

What error happened as below:

![error1](https://user-images.githubusercontent.com/12776545/31752747-2f79de06-b452-11e7-8464-670fd39e581e.png)

Why the foreign key `fk_rawtable_ref_database` does not exist? And  I scaned all tables in metabase . The result is I cannot found any constraint or fk named `fk_rawtable_ref_database`. And so I attemped to comment the code in `resources/migrations/000_migrations.yml` which changeSet's id is 64.

<img width="929" alt="2121" src="https://user-images.githubusercontent.com/12776545/31752948-4a9af700-b453-11e7-948b-3df744379743.png">

to ----- as below:

<img width="936" alt="222" src="https://user-images.githubusercontent.com/12776545/31752946-4a54f408-b453-11e7-8ae8-f3326f028afe.png">

And I run the command :

```bash
yarn run dev
```
Successed

![normal](https://user-images.githubusercontent.com/12776545/31753024-be069168-b453-11e7-9467-fdfde67de59b.png)

**But How did this happen?**

**Comment by 2json** [comment]
And metabase@v0.26.1 start so slow, and even serveal minutes to start my server.

**Comment by camsaul** [comment]
@2json are you still running into this issue?

**Comment by camsaul** [comment]
@2json going to go ahead and close since we haven't heard back since December. Please chime in and let us know if you're still having this issue,
