### ISSUE TITLE
Remember Me: on login page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6213]
Is the checkbox in the wrong place? Or is it just a mystery extra semicolon?

![screen shot 2017-10-19 at 9 36 34 am](https://user-images.githubusercontent.com/1455846/31798942-d419bc76-b4eb-11e7-98be-6de74e51cd73.png)

**Comment by kdoh** [comment]
It’s in the right place. I think the label just has an extra colon because our FormLabel component tends to use that (look at Email and Password). I’d actually say the bigger issue here is why are we using a bog standard check box instead of our styled checkbox.
