### ISSUE TITLE
Download button UX

### ISSUE THREAD

**Issue by zyadsherif** [metabase/metabase#6217]
Thanks for this awesome platform everyone, a very tiny request to change the download button icon. I've spent almost 2 hours searching for the query results download button and was pretty sure this icon was for some sort of `sorting` it was really confusing that I had to search the html content of the page to see if there's anything that says `Download`

Close the ticket at will
Thanks again

![screen shot 2017-10-20 at 08 24 17](https://user-images.githubusercontent.com/1159370/31807734-26d7ed96-b570-11e7-86e7-e947204e40ab.jpg)

**Comment by mazameli** [comment]
So sorry to hear that! Issue #6170, a redesign of our action buttons on questions and dashboards, should hopefully help prevent this kind of bad UX.

**Comment by mazameli** [comment]
This icon has been changed in both appearance and location as of 0.33, so I'm going to close this issue since it had to do specifically with the old placement and icon.
