### ISSUE TITLE
Dashboard grid ought to be multiple of the magic number - 12. So 24 instead of 18.

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#6218]
The subjects says it all, really. This way it is divisible into halves, thirds, quarters and fractions based on those.

I am not sure why 18 was chosen, but it looks to me that it isn't the best choice. 

I should also point out that a grid of 24 should be fully backward compatible, since 18 is only divisible by halves and thirds, while 24 is divisible in the same manner, plus quarters as well.

Please consider! Thanks!

P.S: Fantastic product, we love it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by vi-vsn** [comment]
Found #2057 in history, tried to track down follow-up issues, but did not find anything that would offer clarity on why 18 grid was chosen. Anyway, feel free to close if this isn't something you care about.

**Comment by mazameli** [comment]
I think that's an interesting suggestion. It would definitely provide a bit more flexibility and granularity in sizing cards, and you're right that 24 divides into quarters cleanly whereas 18 doesn't.

What I really love is that you're paying this much close attention to the details of Metabase! Glad you guys love it.

**Comment by mazameli** [comment]
We've implemented this, so I'm closing it.
