### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by magno32** [metabase/metabase#6232]
`lein ring server` produces the following:

Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.

The `FAQ` for lein suggests adding an exception the the project.clj file.  This is obviously being built without that though.

If I remove the redshift artifact and repository, then I get the above error mentioned in #6223.

I created a Dockerfile that reproduces this issue,
https://gist.github.com/magno32/27257944acabe98abb208a03ab27a160

Is there a Dockerfile out there that will build this project?  It would make it really easy to duplicate a build environment (I'd contribute one if I knew what was wrong with mine!)

**Comment by jornh** [comment]
Here’s the build Dockerfile: https://github.com/metabase/metabase/blob/master/Dockerfile#L1-L3

**Comment by magno32** [comment]
Thanks,

I completely overlooked that.  However, it behaves the same and gives the same error about an insecure repository as well.

**Comment by magno32** [comment]
Progress, 

Apparently lein's stable download is 2.8.0, which is 5 days old.  Downgrading to [2.7.1](https://raw.githubusercontent.com/technomancy/leiningen/2.7.1/bin/lein) gets rid of the repository TLS error.  

Once that goes away, I have the same problem as #6223

**Comment by camsaul** [comment]
@magno32 We just fixed the Leiningen 2.8.x issue on `master`
