### ISSUE TITLE
Confusing thousands separator in results table

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6237]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
![question metabase 2017-10-23 14-39-54](https://user-images.githubusercontent.com/1096609/31887295-650600b6-b800-11e7-9d79-951ce5514ae6.png)
where:

- Count – just "Count of rows" function
- Sum – sum of float values
- Sum2 – sum of integer values
- Bids – the same as Sum2, but it is saved metric created from Custom Expression

There are several problems with this image:
1) Not all columns have thousands separator. Think, it will be reasonable for user to configure this preference globally for Metabase instance.
2) Bids and Sum2 column have different separator (Sum2 haven't) although this is the equivalent metric

**Comment by flamber** [comment]
Hi @M4zD4i 
Have you tried the 0.31.2 release? It has custom formatting for each column.

**Comment by M4zD4i** [comment]
Ola, @flamber! I'm looking the 0.31.2 release now and have found the Formatting
<img width="409" alt="question metabase 2019-02-04 14-06-22" src="https://user-images.githubusercontent.com/1096609/52205275-8fd04d80-2887-11e9-829e-5696ced27758.png">
 preferences. It's awesome! My opinion – current issue it not relevat yet. Closed.
