### ISSUE TITLE
Not possible to sort by Custom Field

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6238]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create a custom field from "Add custom field" button in query Builder
2. Create some query using this field in group by section
3. Column with this field is not sortable

It seems as the similar problem with Metric columns: https://github.com/metabase/metabase/issues/5943

**Comment by flamber** [comment]
Hi @M4zD4i 
This is fixed by #6879, which I think was included in 0.28.2 - I can confirm it works on 0.31.2

**Comment by mazameli** [comment]
Yeah, this issue is no longer present.
