### ISSUE TITLE
Leiningen 2.8.0 causes `lein ring server-headless` to fail

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6249]
We were able to fix the SSL related issues in #6241, but there is another change in 2.8.0 that causes the ring server to fail to start with `No reader function for tag function`. This is being tracked on the Leiningen side as https://github.com/technomancy/leiningen/issues/2328 and has already been reverted. For now, downgrade to Leiningen 2.7.1. When 2.8.1 is released the problem should be resolved by upgrading.

**Comment by camsaul** [comment]
@senior that was a bug with leiningen 2.8.0 and upgrading to 2.8.1 fixed it for me

**Comment by camsaul** [comment]
Going to go ahead and close this out since it's fixed in 2.8.1
