### ISSUE TITLE
Feature request (datetime/timestamp variable)

### ISSUE THREAD

**Issue by Fjandin** [metabase/metabase#6251]
When creating a custom SQL card, would be nice to be able to have a datetime type variable. At the moment i can only choose: test, number and date.

**Comment by mvrabel** [comment]
Date == Datetime. Datetime if by datetime you mean Date + Time.
![last_modif](https://user-images.githubusercontent.com/12628893/31968528-b50cb548-b911-11e7-9847-ad9ac45d90bf.PNG)
If you want only time then upvote those two issues #5563 and #5319.
@Fjandin Please go through list os issues before submitting new issue. To make sure some before you didn't already create an issue for the problem you have.

**Comment by Fjandin** [comment]
Ah yes. Sorry. I'm pretty new on metabase. I'm closing this one
