### ISSUE TITLE
Virtualize items in `AccordionList`

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#6252]
As folks using Metabase start doing so with larger datasets with a ton of fields, UI elements that display unfiltered lists of content can cause DOM explosions and sluggishness that ruin people's days. One such day ruiner is `AccordionList`

Since we already use `react-virtualized` in other contexts to handle this issue, we should virtualize the contents of `AccordionLists`

**Comment by kulyk** [comment]
Seems to be done
