### ISSUE TITLE
Cannot create metric from google analytics

### ISSUE THREAD

**Issue by pwm1991** [metabase/metabase#6253]
- Chrome 62
- Windows 10, Windows 8.1, 2 networks (if that matters)
- Database: Google Analytics, columns unconfigured.
- 0.26.2
- Java
- [logs.txt](https://github.com/metabase/metabase/files/1412456/logs.txt)

I have 2 issues with a GA database:

1. It's not possible to create metabase metrics using a google analytics implementation. 
2. It is possible to query a ga metric in a Question in *limited* circumstances, which I cannot find a root cause for.

### Create metric

Method 1 failure. Am unsure of correct behaviour for GA here...

1. Go to the Metrics Editor
2. Select GA table. "Filter by" shows segments and columns
3. Selecting "Choose an aggregation" displays the Aggregation Popover but no aggregations. The box is empty and has a height of 2px.
   1. Selecting a filter and then "Choose an aggregation" does not reveal aggregations, either.

Expected behaviour:  aggregations should display?

### Query GA metrics using questions

Here I cannot find a root cause but sometimes I can query GA metrics and some other times not. Usually clearing the URL and going through New Question -> Custom brings them back.

After all of these processes I'm still unable to create a Metric.

Method 1 success

1. Go to Metrics Editor
2. Press Preview (no other values selected as it doesnt work fully) [to go to this page in new tab](/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOjh9fX0=) 
3. Select "Choose an aggregation" to display GA metrics.
4. Success, add charts etc.

Method 2 success

1. Press New Question > Custom,
 [to go to this page](question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOm51bGx9fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
2. Select GA table
3. Select "Choose an aggregation" to display GA metrics.
4. Success

Method 3 hit and miss.

1. Press Data Reference
2. Select "See all metrics" and choose a sample metric, e.g. [this one](/reference/metrics/ga:users)
   1. Background text says "Cannot read property 'table_id' of undefined".
   2. Many "undefined
   3. Pressing edit does nothing.
3. Press "see this metric" to go to Question page, which is [this url](question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOm51bGx9fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
5. Select GA table
6. Select "Choosse an aggregation"
7. Often success.

*Sometimes* this will work correctly. To fix clear URL and start from localhost. Pressing Data Reference will show no GA metrics. Follow Method 2, then go back to Data Reference and they should appear. Follow Method 3 and it should succeed.

Method 4 hit and miss

1. Save a question using Method 2
2. Go to Questions tab and select question
3. Unable to change aggregation
4. Often success

*Sometimes* this will work correctly. To fix, follow fix for Method 3

p.s. this is my 1st bug report so if its way too detailed or badly done, sorry!

**Comment by stevenleeg** [comment]
I've been seeing a similar issue on my end. I can sometimes get a populated view popover if I refresh the page but othertimes not (it's most reproducible while trying to edit existing questions). If it's relevant, I'm connected to a Google Analytics account with 30+ accounts.

**Comment by sharedphysics** [comment]
+1
Was looking to do calculations on metrics [i.e., divide (unique pageviews)/(pagviews)] to calculate % of all pageviews as unique, and other calculations, and wasn't able to a) create the calculation/custom expression, and b) create the metric.

**Comment by flamber** [comment]
Closing in favor of #5687
