### ISSUE TITLE
Designs for Alerts feature

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6261]
Designs for #1373

## Non-admin setup flow

Alerts are in the new "more" menu:

![admin setup 01](https://user-images.githubusercontent.com/2223916/32028644-86bb3ea6-b9a4-11e7-91d0-fb5d1b3adb3f.png)

The first time any user, admin or non-admin, clicks on the Alerts menu item, they'll see an educational screen letting them know what kind of alerts they can get in Metabase: a raw data query returning any results, a line/area/bar chart crossing a goal line, or a progress bar reaching or going below a goal. **If they haven't saved the question yet, they should be prompted to do so before they see this screen or the alert creation form.** Also note that the illustration(s) on this page is a WIP:

![admin setup 02](https://user-images.githubusercontent.com/2223916/32028651-8fdf8474-b9a4-11e7-8070-7ef7046a850c.png)

On the alert setup form, the only real choice the user has to make is how often we should run the query to see if the alert condition is met. Non-admins can't set up additional recipients, and can't set up Slack alerts. The scheduling option defaults to daily at 12:00 AM. Also, the raw data alert type has an additional tip box, whereas the goal line and progress bars don't currently.

![non-admin 02](https://user-images.githubusercontent.com/2223916/32028662-9c41caba-b9a4-11e7-848d-8edcdc66af1e.png)

When the user clicks done on the alert form, they should see a confirmation notification in the bottom-left of the screen. We should be able to repurpose the notification component that's currently displayed when a dashboard or question is archived.

![admin setup 04](https://user-images.githubusercontent.com/2223916/32028682-b6dccac8-b9a4-11e7-9d91-a2faef22189c.png)

## Non-admin edit flow

Once a non-admin user has set up an alert on a question, or if an admin has added them as a recipient to an alert on this question, they should see this different state for the alert item in the More menu:

![non-admin edit 01](https://user-images.githubusercontent.com/2223916/32028939-350d08c6-b9a6-11e7-8824-5c4b5370203e.png)

When they click on that item, they'll see a state like this one. If they set up their own alert, and they have been added to at least one alert on the same question, we'll highlight the one they created and make sure it's at the top. Their own alert also shows its schedule for checking, but the other alerts don't. A non-admin can edit or unsubscribe from (i.e., delete) their own alert, but they can only unsubscribe from an alert they've been added to (i.e., remove themselves as an email recipient on that alert).

![non-admin edit 02](https://user-images.githubusercontent.com/2223916/32029019-95789f68-b9a6-11e7-8f0a-5791cc52e0a8.png)

If they haven't yet created an alert of their own, but have been added to 1 or more alerts by an admin, the list looks like this, with the option to create their own alert at the bottom:

![create own alert non-admin](https://user-images.githubusercontent.com/2223916/32236140-9bae56ee-be1e-11e7-8a25-dd9f5d0a68bf.png)

Clicking Unsubscribe on an alert shows a message like this, which persists until the popover menu is dismissed:

![non-admin edit 03](https://user-images.githubusercontent.com/2223916/32029040-b3edc054-b9a6-11e7-9221-41d66efbf57c.png)

Clicking the Edit button on their own alert brings them to the edit state of the alert form:

![non-admin edit 04](https://user-images.githubusercontent.com/2223916/32029047-ba48c066-b9a6-11e7-8342-177587b9a435.png)

## Admin alert setup flow

The admin setup form looks the same, but with the addition of a box to select email recipients and/or a Slack channel to send alerts to. This component should be reused from the Pulses section. The delivery options default to email on, Slack off, with the admin's email address being included in the recipient list. 

![admin setup 03](https://user-images.githubusercontent.com/2223916/32028689-bf8f06b8-b9a4-11e7-9bde-f0c41806a39f.png)

## Admin edit flow

When a saved question has at least one alert set up on it, regardless of which user set up the alert(s), the admin should see this different state for the alert menu item:

![admin edit 01](https://user-images.githubusercontent.com/2223916/32028691-c5106528-b9a4-11e7-937a-fa61de6bb783.png)

This popover should show every alert present on the question, and an admin can edit any of them. It also gives a summary of the schedule and recipient settings for each alert:

![admin edit 02](https://user-images.githubusercontent.com/2223916/32028696-cc9ffeb6-b9a4-11e7-9524-d88829be0b96.png)

If the admin has not yet set up their own alert, but there is already at least 1 alert present on the current saved question, they'll see this state, with the ability to add their own alert at the bottom:

![create own alert admin](https://user-images.githubusercontent.com/2223916/32236207-c83a1e0a-be1e-11e7-9072-2f5542cba12b.png)

The edit form is essentially the same, but with the addition of a deletion box that is a copy/paste from the Pulse edit form:

![admin edit 03](https://user-images.githubusercontent.com/2223916/32028702-d1e0178a-b9a4-11e7-870d-4611c20ea1bd.png)

## Time series with goal lines

If a question is a line/area/bar time series with a single series and a goal line, a user can set up an alert to be sent when the goal line is crossed. They can be alerted with it goes above or below the goal line, and receive alerts only the first time this happens, or every time it happens:

This screen shows the non-admin version of the form with the additional time-series-with-goal-line options:

![time series 03](https://user-images.githubusercontent.com/2223916/32028714-dbce129c-b9a4-11e7-9be9-0868b8f68052.png)

## Progress bar

Similarly, a user can get alerts when a progress bar goes above or below a goal, the first time or every time:

![progress bar 03](https://user-images.githubusercontent.com/2223916/32028721-e26492fc-b9a4-11e7-9081-9c07b357bdf6.png)

## Stretch: alert prompts

A nice stretch addition is giving users a prompt to create a alert when they set up a goal line or a progress bar goal in the visualization settings.

Setting up a goal line:

![time series 01](https://user-images.githubusercontent.com/2223916/32028730-eebcc9ac-b9a4-11e7-881d-91097a20814d.png)

Alert prompt:

![time series 02](https://user-images.githubusercontent.com/2223916/32028733-f24f2466-b9a4-11e7-9ae0-4bc81a49682b.png)

Or setting up a progress bar goal:

![progress bar 01](https://user-images.githubusercontent.com/2223916/32028738-f738aa74-b9a4-11e7-94fa-8e1d7fe36ae9.png)

And receiving the prompt:

![progress bar 02](https://user-images.githubusercontent.com/2223916/32028745-fb7cbd00-b9a4-11e7-8278-1a148edf79fd.png)

Lastly, we could also add a small bit of text and a link prompt on questions that return no results:

![no results prompt](https://user-images.githubusercontent.com/2223916/32028757-05d0634c-b9a5-11e7-9966-dafdba6d5f6f.png)

**Open question about prompts: for goal lines and progress bars, do we show the prompt every time, or just once per session, or…?**

**Comment by mazameli** [comment]
I just added in the non-admin edit flows (I'd forgotten to put them in last night), and made some visual tweaks to a number of screens per some conversations with @kdoh.

**Comment by senior** [comment]
PR with the implementation is https://github.com/metabase/metabase/pull/6278

**Comment by mazameli** [comment]
@attekei I inserted two screens into the description above to depict what the alerts list looks like in the state where a non-admin has been added to at least 1 alert, but hasn't created their own; and the state where an admin is looking at the list of alerts but has not yet created their own alert. In both cases, an identical bottom div is added to the list with a link to "create your own alert."

**Comment by satishvarmadandu** [comment]
would this alerts feature can be part of 0.27 release (atleast with partial feature set) ?

**Comment by mazameli** [comment]
@satishvarmadandu that's the plan!

**Comment by satishvarmadandu** [comment]
@mazameli thats great to hear. So any ETA on 0.27 timelines ? I didn't see this in 0.27 release list so enquired about. But Metabase looks great and would like to try this & alerts would be a major deal breaker for us. Currently we use Elastic's watcher for this capability

**Comment by mazameli** [comment]
@satishvarmadandu I can safely say 0.27 will be out in November.

**Comment by satishvarmadandu** [comment]
Great. Thanks @mazameli.

**Comment by pavneetskapoor** [comment]
@mazameli Is it possible to include alert icons for questions that have alerts setup within the questions page when you're searching for results. Additionally, does admin have an alerts dashboard consisting of alerts being added and a generalistic overview of the alerts?

**Comment by mazameli** [comment]
@pavneetskapoor your first suggestion is something we discussed a little bit before the feature was released, but I think we should revisit it (cc @kdoh). As far as an admin dashboard or overview of all alerts, that does not currently exist — we opted for a super simple initial feature first, and then waiting to hear requests like yours before considering more robust management tools. 

Do you have a rough idea of how many alerts your team has set up? (Or is that the whole problem? hah) If we were to build an alerts overview/management page, what would you want to be able to see or do there?

**Comment by pavneetskapoor** [comment]
@mazameli I can get back to you in detail but a general alerts management page like the one similar to questions would be a nice addition to the feature. I'm not too sure how many alerts our team would set up for the future so it's kind of hard to visualize but something like a management page would definitely be helpful to larger teams in order to get a general overview of alerts.

**Comment by satishvarmadandu** [comment]
@mazameli .. Started using Metabase and so far its great. One of the big blocker is Alerts frequency.  At best, we could able to set only hourly alerts. Is there any way to trigger alerts every "few mins" like 5 mins. This is a major blocker because hourly alerts frequncy is too long and limits the usage of Metabase. Please advise if this is a better place to post this
