### ISSUE TITLE
There is no difference in URL, ImageUrl, AvatarImageUrl fields displaying

### ISSUE THREAD

**Issue by M4zD4i** [metabase/metabase#6265]
- Your browser and the version: Safari 11.0 (12604.1.38.1.7)
- Your operating system: MacOS Sierra 10.12.6
- Your databases: Apache Impala
- Metabase version: fork from 0.26.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Steps to reproduce:
1. Create some table containing urls for image, avatar and any other url
2. Mark out theses fields in Admin->Data Model panel with types according containing value
3. Build a query to view all fields

As result: we have a table with no difference in displaying method for all three fields. According type names I'm assuming that ImageUrl should be displayed as small preview of large image with underling link and AvatarUmageUrl should be displayed as it is :)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Hi @M4zD4i, we don't currently treat them any differently, but the original thinking was that eventually we'd do something like what you're describing, such as showing previews of images.

**Comment by mathieubossaert** [comment]
Good morning,
this would be really great and could offer a lot of possibilities : display product or species concerned by the report, show calculated maps sharing same parameters as the report...

**Comment by jornh** [comment]
In https://github.com/metabase/metabase/issues/6873#issuecomment-373888379 @MarkRx proposes a different but still somewhat related feature: To add support for rendering fields containing [Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by alirezastack** [comment]
@jornh  the problem is that the image will be static. When I use variable support {{like_this}} inside of the markdown in static text, it does not treat it as a variable.

Is there any solution for this?

**Comment by devmet** [comment]
Hi All,

Is there any news about this issue?

**Comment by flamber** [comment]
In version 0.31.2, you can now define formatting for table columns, but for some reason it doesn't work, when I set the Field Type to `Image URL` or `Avatar Image URL`, but if you set it to `No special type`, then the applied formatting (either defined via Data Model or via table customization) allows it to show images.
![image](https://user-images.githubusercontent.com/1447303/53824959-d2468200-3f3a-11e9-8a69-638cd2cdccbc.png)

I wouldn't call this issue resolved, but now there's a workaround. It should probably work just by defining the types for it to be resolved.

**Comment by devmet** [comment]
> In version 0.31.2, you can now define formatting for table columns, but for some reason it doesn't work, when I set the Field Type to `Image URL` or `Avatar Image URL`, but if you set it to `No special type`, then the applied formatting (either defined via Data Model or via table customization) allows it to show images.
> ![image](https://user-images.githubusercontent.com/1447303/53824959-d2468200-3f3a-11e9-8a69-638cd2cdccbc.png)
> 
> I wouldn't call this issue resolved, but now there's a workaround. It should probably work just by defining the types for it to be resolved.

Thanks for the tip, now its worked!

**Comment by kevinob11** [comment]
Should this work if the field is filled with a Base64 encoded image? It doesn't seem to format, it only tries to actually render it as an image if I add "http://" to the front of the field. Which I can do, but it breaks the decoding of the image so it doesn't render.

**Comment by flamber** [comment]
@kevinob11 No, base64 decoding is not supported.

**Comment by kevinob11** [comment]
Got it, thanks for the quick response. I'll leave my feature request open and talk to my team about if they want to prioritize this and see if we can help.

**Comment by tsmacdonald** [comment]
As of the pre-release for v48 this has been fixed, and images display strictly based on column formatting and not field metadata

![image](https://github.com/metabase/metabase/assets/784417/bcba40d5-a06f-4cfa-9a33-a0188750bd8c)


I remember @iethree doing some work on this for 46 or 47 but can't find the PR

**Comment by tsmacdonald** [comment]
Setting the milestone as 48 since it's not worth my time to bisect when it was actually fixed
