### ISSUE TITLE
Unauthorized attempting to relogin as a deleted user

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#6267]
I was playing around with LDAP group settings and deleted a user so they could log back in and get recreated with LDAP group mappings. The user that was deleted however is not able to log back in. There are 2 REST calls when attempting to login:

```
POST /api/session
RESPONSE: {id: "39dc7e30-2188-441e-919b-2d936446c997"}

GET /api/user/current
Response 401
RESPONSE Body Unauthenticated
```

I don't know if this is related to LDAP or not.

Steps to reproduce:

1. Login as an LDAP user
2. Logout
3. As an admin delete said LDAP user
4. Attempt to login as the same LDAP user. It will fail without any error messages.

Expected results:
The user would be recreated in step 4

Browser: Chrome 62.0.3202.62 (Official Build) (64-bit)
OS: Windows 7
Database: Oracle 12
Metabase: 0.26.2
Environment: linux
Internal Database: h2

**Comment by MarkRx** [comment]
Update: Looked in the database. It looks like "deleted" users are just as inactive. Something must not be handling this case and reactivating the user.

**Comment by jornh** [comment]
Related #5842

**Comment by MarkRx** [comment]
Yup. Closing in favor of #5842.
