### ISSUE TITLE
Consistently Missing Data in X-Ray

### ISSUE THREAD

**Issue by philipbjorge** [metabase/metabase#6270]
Postgres
Metabase 0.26.2

I'm performing an X-Ray on a question where we take the count of rows, grouped by day.
We are seeing bands of missing results.

![screen shot 2017-10-25 at 12 00 01 pm](https://user-images.githubusercontent.com/918891/32017636-2bf8347e-b97c-11e7-84fa-2874419bb797.png)

**Comment by sbelak** [comment]
Can you show how the original time series (card) looks?

**Comment by philipbjorge** [comment]
@sbelak -- Is this what you mean?

![screen shot 2017-10-25 at 12 22 36 pm](https://user-images.githubusercontent.com/918891/32018595-39345cdc-b97f-11e7-980b-5014f230d99f.png)

**Comment by sbelak** [comment]
Yes, thank you.
