### ISSUE TITLE
TimeZone Problem [MySQL]

### ISSUE THREAD

**Issue by futureio** [metabase/metabase#6273]
**Version**: 0.26.1
**DB type**: MySQL
**TimeZone**: +8:00
**Table**:
```SQL
CREATE TABLE IF NOT EXISTS `test` (
  `day` date NOT NULL,
  `time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
**Data**:
```SQL
INSERT INTO `test` (`day`, `time`) VALUES
('2017-10-26', '2017-10-26 11:57:33');
```
--------------------------------------------------------
I found that in metabase, no matter what time zone you set, there are always two fields that are always right, like this：
2017-10-26  2017-10-26 **19**:57:33
or
2017-10-**25 16:00:00** 2017-10-26 11:57:33

I think it's a bug. Does anyone have the same problem?

**Comment by camsaul** [comment]
@senior is this one of the Timezone things you ended up fixing recently?

**Comment by senior** [comment]
Seems to me like there's still issues on MySQL.

 In the first resultset, it looks like it's not modifying the date in anyway, just passing it through.  But the datetime it's interpreting as UTC coming from the database. It's then adjusting the time forward 8 hours for the timezone. The second resultset it looks like it's interpreting the date as a datetime that happens at midnight, then adjusting backward 8 hours.

What are the two queries you're running to give such different results? Would also be useful to have the below information:

- What is your report timezone? (it's a general setting on the admin page)
- What timezone is your Metabase instance in (system timezone or if you override it)
- What timezone is your MySQL database in

**Comment by pdiniz13** [comment]
this could be related to this issue, which was closed by now the problem has come back with version 0.26

**Comment by tlrobinson** [comment]
Related to #6636 and/or #6368?

**Comment by paoliniluis** [comment]
@evelzi can you give us more details about what's going on?
