### ISSUE TITLE
Performance issues after update

### ISSUE THREAD

**Issue by nkconnor** [metabase/metabase#6276]
We use Metabase for large production databases. To our surprise yesterday Read Ops alarms were going off on a database all day and we eventually tracked it back to the update to 26.2

Looking through queries we see lots of `SELECT COUNT(*) FROM table` queries coming from Metabase. Is this part of the X-Ray features? Why is this enabled by default?

**Comment by camsaul** [comment]
Sounds like possibly the same issue as #6209

**Comment by nkconnor** [comment]
It is, added an additional comment there

> Yes, turning off the scanning has fixed this issue for us as well. I hope this is addressed in a patch as the scans could easily take down or cripple a production database after upgrade

**Comment by camsaul** [comment]
Thanks @nkconnor 

Closing as duplicate of #6209
