### ISSUE TITLE
Not Setting Time Zone For Redshift Queries

### ISSUE THREAD

**Issue by jpulec** [metabase/metabase#6279]
It seems that Metabase isn't properly calling the SET time zone function when running queries on Redshift. The current redshift driver sets this as a nil operation, but redshift does support setting the time zone for the current session which would fix queries for things like date filters.

- Your browser and the version: Chrome 62
- Your operating system: Arch Linux
- Your databases: Redshift
- Metabase version: 0.26.2
- Metabase hosting environment: Heroku
- Metabase internal database: Postrgres

**Comment by camsaul** [comment]
@jpulec do you know what SQL query we should use to set the timezone?

**Comment by camsaul** [comment]
(Related to #6354. @senior if Redshift (or any other driver) doesn't support setting timezones do we still need to try to capture that info? Just trying to clarify what we do with it.)

**Comment by jornh** [comment]
@camsaul it’s at http://docs.aws.amazon.com/redshift/latest/dg/r_timezone_config.html 

Looks like it’s the same as Postgres use apart from that it doesn’t understand or tolerate the `[ SESSION | LOCAL ]` portion. The [Postgres docs](https://www.postgresql.org/docs/10/static/sql-set.html) says `SET` and `SET SESSION` are equivalent.

Metabase currently use `SET SESSION` for Postgres: https://github.com/metabase/metabase/blob/v0.26.2/src/metabase/driver/postgres.clj#L200

If that is adjusted to skip the SESSION word (for me not being used to Clojure) it looks like the Redshift driver can do with 2 lines _less_ of code: https://github.com/metabase/metabase/blob/v0.26.2/src/metabase/driver/redshift.clj#L102-L103

**Comment by senior** [comment]
This seems like a bug and something we should get fixed up. Maybe this was tolerated when we used the PG driver for Redshift, but not allowed with the new Redshift driver.
