### ISSUE TITLE
Wierd issues with timezones on druid

### ISSUE THREAD

**Issue by moumny** [metabase/metabase#6289]
Hi guys,
Congrats for the release of 0.26, im quite happy to see many bugfixes in it. However i catched several regressions. Here is one of them:

Database: druid
Timezone: Europe/Berlin (report, server)
Version: 0.26.2

Query:  
- timeseries of count of rows. 
- Below several combination of filter and group bys

* count of rows 
    * previous day - by hour
        * linechart - correct 12AM to 11PM
        * table view - correct 12AM to 11PM
    * previous day - by minute
        * linechart - correct 12:00AM to 11:59PM
        * table view - correct 12:00AM to 11:59PM
    * previous 24hours -  by hour (current time 12:15PM)
        * linechart - WRONG 23 data point are in local time but last datapoint is UTC (11AM shown as 9AM)
        * table view - Same as above last rows are 8AM 9AM 10AM 9AM (i.e last datapoint is UTC)
    * previous 24hours -  by minute (current time 12:15PM)
        * linechart - WRONG last 60 in UTC (rest is local time) (after 10:59AM the next data point 09:00AM till 09:59AM)
        * table view - Same as above 
    * previous 1440minutes - by hour (current time 12:30PM)
        * line chart 
            * in tool tip last two data point are wrong (in UTC) goes  8AM 9AM 10AM 9AM 10AM
            * all ticks are correct though last tick is 12PM
        * table same last two rows are wrong.
    * previous 1440minutes - by minute (current time 12:30PM)
        * same as by hour data after 10:59 is in utc (next data point is 09:00AM) in both table and linechart tooltip
    * current day -by minute as above
        * same behavior in dashboard card as in query builder
        * drag drop filter puts the right filter in local time regardless of the area selected

**Comment by moumny** [comment]
Given the number of issues with timzone, i think it would be beneficial to have some tests in the front end for such things, esp as with drillthrough there is a lot of time handling.
Perhaps changing from datetime values to a more explicit structure that contains timezone would also help instead of relying on frameworks which can lose timezone during conversions.

**Comment by moumny** [comment]
My bad, actually not a regression ^^

**Comment by tsmacdonald** [comment]
I can't reproduce this on 48
