### ISSUE TITLE
Run Metabase in Kubernetes more then one container on same Postgree

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6294]
Hi guys.

I'm trying to run Metabase on a structure in Kuerbentes with more than one container.

It runs, but I think it's giving some trouble.

Is this architecture possible? Are there risks?

**Comment by jornh** [comment]
Related #2754

In particular see https://github.com/metabase/metabase/issues/2754#issuecomment-225764248

**Comment by camsaul** [comment]
Hi @jonatasfreitasv, Metabase isn't yet designed to work with multiple instances. There are a couple challenges we need to tackle, like making sure only one instance handles background jobs like DB syncing and sending out Pulses. We're tracking that in #2754, so closing this as a duplicate.

(Thanks, @jornh!)
