### ISSUE TITLE
Maybe we should abbrev. month names on axes

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6296]
Our x-axes are starting to look better and less crowded, especially after we merge @camsaul's [PR](https://github.com/metabase/metabase/pull/6283), but I wonder if we should maybe help things even more by using the standard abbreviations for month names (Jan, Feb, Mar…), possibly only in situations where there are more than _n_ number of tick marks.

Here's an example of a case where it might decrease clutter a little bit:

![screen shot 2017-10-30 at 10 00 19 am](https://user-images.githubusercontent.com/2223916/32184499-a56d674e-bd59-11e7-876f-da847fbb839f.png)

**Comment by paulrosenzweig** [comment]
Closing since we have this feature now

![image](https://user-images.githubusercontent.com/691495/60205720-f26abb80-981f-11e9-910b-f2c4ae1161b4.png)
