### ISSUE TITLE
Wording on Mac App Download page could be improved

### ISSUE THREAD

**Issue by jakob** [metabase/metabase#6302]
The Mac App Download page (https://metabase.com/start/mac.html) contains the following instructions:

> Simply download the Metabase Installer, open it up, drag the Metabase application icon over to your Applications folder, and then launch Metabase.

This is inaccurate (the disk image is not an "Installer"), so the wording should be changed.

I'd recommend to change this to something simpler like this: 

> Download Metabase app and drag it to your Applications folder to install!

(Or just skip the instructions altogether, it's not hard to figure out.)

Mac users don't really like installers. The fact that Metabase doesn't need an installer is good, so best not to mention the word "Installer" on your website.

**Comment by camsaul** [comment]
Fixed this in our website repo, will go live with the next release
