### ISSUE TITLE
server shutdown needs to account for possible background threads

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#631]

**Comment by camsaul** [comment]
@salsakran why not? This issue has been open for 8 months and has never affected anyone, isn't is fair to ask whether this GH issue is still relevant?

**Comment by agilliland** [comment]
It should be possible to test this out fairly easily by launching some background threads for longer running jobs and then trying to shutdown the Metabase instance and seeing if it gracefully exits.  It's likely we are okay, but we'll want to validate it for sure.

The main reason we may not have seen anything on this is because it would only surface if you try to shutdown the app while background tasks are running, and we don't launch all that many background tasks.

**Comment by camsaul** [comment]
So I think we can safely close this since we've had zero issues with background threads blocking shutdown in the year since this was opened. @salsakran ?

**Comment by camsaul** [comment]
Closing this issue as No Longer Relevant.
