### ISSUE TITLE
We should add field descriptions to lists of fields in the Data Reference

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6316]
Right now we're only showing Name, Field Type, and Data Type in the `Fields in this table` sections of the Data Reference. Descriptions would be useful, wouldn't they?

![screen shot 2017-11-01 at 3 48 29 pm](https://user-images.githubusercontent.com/2223916/32301692-4226c7a6-bf1c-11e7-927e-f1325b91b5f2.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by buchanae** [comment]
Absolutely. In my field (biology + bioinformatics) it is critical to describe what the data in a column is, and there is a huge variety of fields from a huge variety of sources – on the order of dozens of data sources each with potentially a hundred fields. Having people make assumptions based on a column name is dangerous.

Metabase is really impressive, and I'm excited by the prospect that it might help us finally organize all that metadata.

Where would one start digging if they wanted to add this feature?

**Comment by buchanae** [comment]
There's quirk which is related here: at one point I discovered a page which allowed me to edit the description of a field, but now I can't find it.

The page for editing the description of a field:
<img width="1390" alt="screen shot 2018-06-08 at 2 29 18 pm" src="https://user-images.githubusercontent.com/262647/41182583-264bb7ce-6b2b-11e8-9be2-cd1b50a9105e.png">

The "Edit" page for "Fields in this table":
<img width="1385" alt="screen shot 2018-06-08 at 2 45 17 pm" src="https://user-images.githubusercontent.com/262647/41182601-35b71a96-6b2b-11e8-9362-777c85f6463e.png">

(A few minutes later I found the quirk) I think what happened was that I didn't realize I was in "Edit" mode. Maybe that persisted across pages from a time when I had clicked it in a different context?

So, lessons/ideas are:
- edit mode is too subtle, IMO
- table field edit page should include at least include the description textbox, and/or maybe also a link to the full edit page for the field

**Comment by jornh** [comment]
See [additional discussion on Discourse](http://discourse.metabase.com/t/where-can-users-view-the-field-description/4106?u=jornh) - on the "this is so hard to stumble across that even Maz didn't know the info *is actually there*" issue I think is the main pain point here.

**Comment by tschut** [comment]
In general I think it takes too many clicks to get to information in the data reference. When building a question you want to be able to access the table & field descriptions without having to leave the question (data ref menu option) or clicking (and ctrl+f'ing) a couple of times to reach it in the sidebar.

When building the question, especially when adding filters or grouping, ideally I'd want to be able to see the descriptions without leaving the filter or group building UI. Perhaps a tooltip would do the trick?

Also I'm confused as to which information I should add as an administrator. When editing a field through the data reference I can add 'why this field is interesting' and 'things to be aware of about this field', but those don't show up in the sidebar? It just doens't feel really consistent to me.

**Comment by mazameli** [comment]
Updated the title of this to reflect the fact, as Jorn pointed out, that we actually _do_ have field descriptions in the Data Reference, but they're only displayed on the field detail page. It would be nice to have field descriptions on the page that lists the fields in a table, and would also be nice if you could edit the descriptions of fields on that page.

**Comment by mazameli** [comment]
Implemented in https://github.com/metabase/metabase/pull/12508. Thanks, @rthouvenin!
