### ISSUE TITLE
Add filter to google analytics question (native queries)

### ISSUE THREAD

**Issue by glasset** [metabase/metabase#6320]
Hello,
im trying to link a filter on ga question from dashboard, but i find nothing on that. (my goal is filter by ga:pagePath from a dashboard)

I've tried this:
- add filed type 'category' on my ref (ga:pagePath)
- then try to link with category filter on my dashboard

query
```
{
  "ids": "ga:FooBar42",
  "start-date": "2005-01-01",
  "end-date": "today",
  "metrics": "ga:sessions",
  "dimensions": "ga:pagePath",
  "filters": "ga:pagePath=@trying_to_filter_this",
  "include-empty-rows": false,
  "max-results": 2000
}
```

edit: field filter work only with query builder ?

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by benjR** [comment]
+1
Variables are not accessible when dealing with native queries

**Comment by rijnhardtkotze** [comment]
Bump. 

Is this not possible, still?

**Comment by benjR** [comment]
Bump, still heavily needed.

**Comment by rebecamorais** [comment]
Bump, please, this would be a game changer!

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
