### ISSUE TITLE
AppDB: Support Oracle Application Database

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#6321]
Currently Oracle is supported as a database driver. It would be great if it was also supported as an application database backing the metabase configuration tables.

At the very least it needs to be included in spec.clj:
https://github.com/metabase/metabase/blob/68739beb62031627c16abdde073bfb9d962e33d0/src/metabase/db/spec.clj

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
This would be a lot more work than just adding a DB spec function. Oracle doesn't support SQL `LIMIT` clauses, so we'd have to rework huge chunks of the application to use `NEXT n ROWS ONLY` instead. And that itself is only supported on Oracle 12+, so Oracle 11 or older wouldn't work (and I really don't seeing us rewriting every query we have as a subselect so we can use the `SELECT ... WHERE ROWNUM < n` syntax).

**Comment by camsaul** [comment]
Testing/developing would be a little annoying as well. Most of the Metabase devs use macOS for day-to-day stuff and AFAIK the only way to run Oracle locally on it is with a Docker. It sounds like Oracle wants you to [build your own docker image](https://github.com/oracle/docker-images/tree/master/OracleDatabase) if you want to do that. So there's a few extra steps there too

**Comment by MarkRx** [comment]
Hmm. So I'll prefix this with the statement that I don't know clojure but isn't that already handled by the oracle driver here? https://github.com/metabase/metabase/blob/master/src/metabase/driver/oracle.clj#L204. From what I can tell there seems to be some internal DSL that is translated into SQL by these metabase drivers. I couldn't find raw SQL that was using limit directly in the src directory though there were a number of them in unit tests.

I can't speak to using a Mac but since oracle is already supported and presumably tested in theory it is already taken care of?

**Comment by camsaul** [comment]
The Metabase drivers only handle the sorts of custom queries you create in the GUI. We don't use them for internal queries against the application database because the use cases are so different.

**Comment by MarkRx** [comment]
I see. I'll leave this open as a stretch goal feature request. In the mean time I'll just setup another sql database flavor that can be used to back the metabase application itself.

**Comment by daveram** [comment]
One of my clients is looking at adopting Metabase Enterprise, however lack of support for Oracle as the metabase application database is a roadblock.  Figure they probably aren't the only one given Oracle is still commonly found in many enterprises. 
Given that Oracle now provides docker images out of their container registry freely available of the latest Oracle database editions, and that it's been 2+ years, might be a good time to revisit this

**Comment by michael-ameri** [comment]
Are there plans or a timeline for adding this?

Not having oracle supported as the application database is a blocker for some of our customers.

**Comment by paoliniluis** [comment]
@michael-ameri nope, nothing for now. Can you provide more context?

**Comment by michael-ameri** [comment]
They have Oracle databases set up with backups etc., so they would like to have the metabase application database in Oracle too.

Setting up a productive Postgres / MySQL database only for metabase causes a lot of overhead.

**Comment by camsaul** [comment]
Closing as not planned, we are unlikely to every implement this, it's just too much effort to maintain it

**Comment by kranskydog** [comment]
You've basically made a rod for your own backs by having your own implementations of the app for different repositories. Going to an existing JPA would overcome all these issues - see for example https://docs.spring.io/spring-data/jpa/reference/repositories/query-methods-details.html#repositories.limit-query-result answering @camsaul on LIMIT (not that I'm saying Spring JPA is necessarily the correct option, just that *any* JPA is better than what is there now, and removes all questions of  maintainability)

**Comment by kranskydog** [comment]
Also - 
https://www.virtualbox.org/wiki/Downloads
https://www.oracle.com/downloads/developer-vm/community-downloads.html

**Comment by kranskydog** [comment]
Similarly, to answer @camsaul on LIMIT, if you don't want to use a JPA
https://vladmihalcea.com/sql-query-limit-top-n-rows/
