### ISSUE TITLE
Google Analytics based queries should not show the run button until a metric is selected.

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#6325]
This happens on first run when doing a new GA based query. After selecting the GA account (which we treat as a "table") we're not popping up the aggregation popover and we show the run button which gives you the sense that things are fine and ready to go. This is exacerbated if you're popping between a DB backed and GA backed query you're used to Raw data being defaulted and being able to run the query.

We should do a better job of walking users through a properly formulated query for GA queries before we show the run button.

**Comment by mazameli** [comment]
This was fixed in the new query builders in 0.33.
