### ISSUE TITLE
We should clarify in the UI that hiding tables/columns doesn't apply to native/SQL queries

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6338]
This was brought up in #1689 a while ago, but in the Admin Panel's UI, we should clarify that when you mark a field's visibility to `Do not include` or mark a table as `Hidden` that those settings do not apply for native/SQL queries.

Either that, or we should have that conversation about parsing SQL again…

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
*Parsing SQL, Mongo, and Druid native queries 😳

**Comment by brunobergher** [comment]
We already clarify it, closing.
