### ISSUE TITLE
Date filters via variable vs static string result in different results.

### ISSUE THREAD

**Issue by RebekahHsieh** [metabase/metabase#6349]
### Bugs
Date variables are filtering out data for an unknown reason. The easy example we ran was to run a query of users who joined after a date. If you run the query via a filter at string (i.e. join_date > '2017-10-01') vs a filter using a variable (i.e. join_date > {{joinday}} where we define {{joinday}} = '2017-10-01'), it gives different # of users. 

- Your browser and the version: Happens across browsers (chrome, firefox, safari) 
- Your operating system: OS X 10
- Your databases: Redshift database
- Metabase version: v0.24.2

if you test a simple sql query such as the query below (where variable is defined as '2017-08-25'), in our case, we see that users were dropped from the output even though their join_date was within the filtered time period. 

```
With variable_type as (
select 
    userid
FROM
    your_user_table
WHERE
    join_date>={{joinday}}
group by 1
),

string_type as (
select 
    userid
FROM
        your_user_table
WHERE
    join_date>='2017-08-25'::date
group by 1
),

missing as (
select a.userid
from string_type a
left join variable_type b ON a.userid=b.userid
where b.userid is null )

select a.userid, b.joinday::timestamp
from missing a 
join your_user_table b on a.userid=b.userid
```

**Comment by camsaul** [comment]
@RebekahHsieh I think the reason you were seeing that is because we weren't accounting for timezones when you used a variable like `{{joinday}}`. We've made lots of improvements to timezone support in the last few versions. Can you try with the latest version of Metabase (0.26.2 at the time of this writing) and let me know if you're still seeing issues?

**Comment by salsakran** [comment]
@RebekahHsieh yeah, please double check this on 0.27. Lots has changed.

**Comment by flamber** [comment]
Closing, since no reply.
