### ISSUE TITLE
SQL Metabase MongoDB, clause contains in query

### ISSUE THREAD

**Issue by esaiekuitche** [metabase/metabase#6351]
I'm trying to write a SQL query to my MongoDB through Metabase, and It didn't work.

This what I'm writing:
`[{"$project":{"full_article_text":"$full_article_text"}},{"$contains" : {"full_article_text" : "USA"}},{"$project":{"full_article_text":"$full_article_text",}},{"$limit":2000}] `

I'm looking for all full_article_text which contains a word USA.

Please, can you help me?

My Metabase version is v0.26.1,
And MongoDB version is v3.2.12,
I running these two tools on ubuntu 14.

**Comment by camsaul** [comment]
Hi @esaiekuitche, the Metabase repo isn't really a good place to ask questions about how to write MongoDB Aggregation Pipeline queries because they're part of the MongoDB project, not Metabase. Take a look at [their documentation](https://docs.mongodb.com/manual/core/aggregation-pipeline/).
