### ISSUE TITLE
Can't login via Chrome in iOS (iPhone)

### ISSUE THREAD

**Issue by nutteen** [metabase/metabase#6355]
Chrome version: 62.0 last updated on 27 of oct in iPhone 7. 

To reproduce:
 1. Go to the first page of app from chrome
 2. Enter username and password so signin button show up 
 3. click sign in, this leads to nothing.

Try over and over again I can never login.

However it works in Safari application.

**Comment by salsakran** [comment]
Can't reproduce this on an chrome 62.0 on an iphone 6s.

**Comment by camsaul** [comment]
@nutteen are you still running into this issue?

**Comment by kdoh** [comment]
Going to go ahead and close this since we weren't able to reproduce it.
