### ISSUE TITLE
Missing old version on S3 bucket

### ISSUE THREAD

**Issue by gitsh84** [metabase/metabase#6357]
I am trying to make a change in my environment which was installed some time ago with version 0.25.1
Every time it fails with: 

"Unable to download from S3 location (Bucket: downloads.metabase.com Key: v0.25.1/metabase-aws-eb.zip). Reason: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; "

Which makes sense as the version package is not there anymore.
Is it possible to bring back old versions so changes won't force me to upgrade ?

I will also mention that upgrading from any version to a newer version never worked for me.
In fact I've tried it multiple times with various versions and it always bring me to a point my application is not usable anymore.

**Comment by camsaul** [comment]
Hi @gitsh84, good catch. That file was deleted accidentally. I restored it so try it again and things should work.

**Comment by gitsh84** [comment]
@camsaul thanks !
