### ISSUE TITLE
disable cumulative sum/count queries without a breakout selection

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#636]
these queries always require something to group by first, specifically a time based column.  we need to get the UI to understand that and enforce it.

**Comment by mazameli** [comment]
It would be interesting to consider hiding the cumulative sum/count options if there isn't a time field in the table; and if there is a time field, in the grouping menu only showing time fields. Maybe if the user selects a cumulative aggregation option, we either open up the grouping menu automatically to prompt them to make a selection, and/or put a message by the `get answer` button to the effect of "this question requires a time grouping."

**Comment by tsmacdonald** [comment]
@mazameli I have no idea what MB looked like in 2015, but if I'm understanding this right, in 2024:

1. if you pick cumulative sum without a breakout, it gives you the total sum as a scalar, which seems right
2. the UI makes it easy to pick a sensible breakout

therefore I think we can close this issue?

**Comment by camsaul** [comment]
Agreed. Closing as not planned
