### ISSUE TITLE
Free-text markdown boxes in dashboards

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6360]
As described in issues #3221, #6048, and probably others, it would be really useful to have the ability to create free-text fields, and even better if markdown formatting is allowed. Here's a proposal for how this feature could work.

## Basic create and edit flow

When a dashboard is in Edit mode, there's now a button that allows the addition of a text box card:

![01 edit](https://user-images.githubusercontent.com/2223916/32636737-edb9d55a-c56a-11e7-838e-3f03f88f563e.png)

A freshly added text box card appears, let's say as a 4x4 card (the grid in my designs is fake and off and not representative of the actual grid in production). These cards have a toggle to allow the switching between composing and previewing the text. When the new card is added, it should start in compose mode rather than preview mode:

![02 card added](https://user-images.githubusercontent.com/2223916/32637591-9686bf96-c56f-11e7-901f-166c4b514178.png)

When text is entered in the box it's displayed in a monospaced font (Monaco perhaps?). Markdown notation can be used for formatting (more details on that below). A small link below the box informs the user of that fact, and clicking on it opens a new browser window and takes them to the Metabase documentation about Markdown (to be written):

![03 text entered](https://user-images.githubusercontent.com/2223916/32637593-9a6a123e-c56f-11e7-9836-f110477a0bc8.png)

When the eyeball icon is pressed, the card shows how the markdown text will be rendered:

![04 preview mode](https://user-images.githubusercontent.com/2223916/32636740-ee5178c4-c56a-11e7-9c95-aaa166760409.png)

Here's how the card looks when the dashboard edits are saved:

![05 done adding](https://user-images.githubusercontent.com/2223916/32636741-ee6a4a5c-c56a-11e7-9dbf-8798ee9cc2ba.png)

### Using these as headings
Perhaps stating the obvious, but these cards can easily be used for simple headings. In order to provide enough space for the UI required for these cards' edit states, however, I think we'll want to give them a minimum height and width of 2 grid units:

![headings](https://user-images.githubusercontent.com/2223916/32636742-ee84abf4-c56a-11e7-9983-d3ebbf5ceead.png)

That should give us enough space for a minimum-sized edit and preview state:

![small box - edit](https://user-images.githubusercontent.com/2223916/32637963-ac3d2436-c571-11e7-95d8-4e69ff47f68b.png)

![small box - preview](https://user-images.githubusercontent.com/2223916/32637964-ac55cf54-c571-11e7-811d-e561f6991458.png)

### Inline images
For v1 of this feature, uploading images to Metabase to insert into text boxes won't be possible, but using markdown notation to reference a hosted image will display it inline. We'll display these images at 100% the width of the text box card, minus padding:

![inline image](https://user-images.githubusercontent.com/2223916/32636743-eec67e26-c56a-11e7-8d57-bd61f2628fa8.png)

### Scrolling

![scrolling](https://user-images.githubusercontent.com/2223916/32636744-eee663a8-c56a-11e7-8d44-990710fbdb01.png)

## Markdown spec
**Here's what I think we should support for markdown syntax:**
- Heading 1, 2, and 3 (#, ##, ###)
- Bold
- Italics
- Hyperlinks
- Strikethrough
- Unordered lists
- Ordered lists
- Blockquoted text
- Images

**Probably nice to have, but not strictly required:**
- Code blocks (```)
- Inline code (`like this`)

**Don't need:**
- Tables
- Tasks / to-do lists
- Underlined text

Here's a style sheet:

![markdown spec](https://user-images.githubusercontent.com/2223916/32637892-3fba76a6-c571-11e7-9f9c-f8b218980752.png)

**Comment by salsakran** [comment]
totally random aside, but I think tables are probably more useful than code blocks =)

**Comment by joneath** [comment]
Would updating the design of the dashboard header actions (Add a Question and Add Filter) be part of this feature work or would that occur in a separate PR before or after this text card feature request?

**Comment by mazameli** [comment]
@joneath yeah, was just going to call that out. That currently is part of #6291 ("entity menus"). So for the sake of this feature, you can ignore that aspect of the design. Until the entity menus are implemented, we'll need to add a new icon button while in edit mode to allow for adding a text box, though, so I'll quickly come up with an interim solution for that.

**Comment by mazameli** [comment]
I think this would work in the interim. The `Aa` icon is called `string` in the codebase. I reordered the icon buttons to make them make a bit more sense; I'm assuming that's a trivial change. 

![temporary-fix](https://user-images.githubusercontent.com/2223916/32678614-f0a586f8-c617-11e7-8535-131341a870e8.png)

Hover and tooltip:

![temporary-fix-hover](https://user-images.githubusercontent.com/2223916/32678620-f5848426-c617-11e7-8b20-de98518fc8f5.png)

**Comment by lbalves** [comment]
I would suggest keeping an "settings" icon, which would have the option to hide the "card background". This would be specially useful for heading cards, but this is only an aesthetic suggestion.

**Comment by camsaul** [comment]
Implemented by #6436

**Comment by collegeimprovements** [comment]
Is there any possibility that tasks/checkboxes will be added in future version ?

**Comment by tlrobinson** [comment]
@collegeimprovements It looks like checkboxes are rendered in `master` (but not v0.28), but I assume you mean you want them to be clickable? I played around with it and it's definitely possible, but we'd need to figure out when they get persisted, etc.

We can also change it to use our `CheckBox` component and hide the redundant bullet.

<img width="713" alt="screenshot 2018-04-13 01 35 42" src="https://user-images.githubusercontent.com/18193/38725068-021fdf8e-3ebb-11e8-9f3d-c107accae66b.png">

<img width="469" alt="screenshot 2018-04-13 01 35 22" src="https://user-images.githubusercontent.com/18193/38725070-02579456-3ebb-11e8-9b11-691456002138.png">

Here's a start:



```diff
diff --git a/frontend/src/metabase/visualizations/visualizations/Text.jsx b/frontend/src/metabase/visualizations/visualizations/Text.jsx
index da935310c..c30bce911 100644
--- a/frontend/src/metabase/visualizations/visualizations/Text.jsx
+++ b/frontend/src/metabase/visualizations/visualizations/Text.jsx
@@ -5,6 +5,7 @@ import ReactMarkdown from "react-markdown";
 import styles from "./Text.css";
 
 import Icon from "metabase/components/Icon.jsx";
+import CheckBox from "metabase/components/CheckBox.jsx";
 
 import cx from "classnames";
 import { t } from "c-3po";
@@ -122,6 +123,33 @@ export default class Text extends Component {
     this.setState({ isShowingRenderedOutput: true });
   }
 
+  getRenderers() {
+    return {
+      listItem: ({ checked, children, ...props }) => (
+        <li className="flex align-center">
+          <CheckBox
+            checked={checked}
+            onChange={e => {
+              const { settings: { text } } = this.props;
+              const [start] = props["data-sourcepos"]
+                .split(/:|-/g)
+                .map(s => parseInt(s) - 1);
+              const lines = text.split(/\n/g);
+              lines[start] = lines[start].replace(
+                /\[(x|\s+)\]/i,
+                checked ? "[ ]" : "[x]",
+              );
+              this.props.onUpdateVisualizationSettings({
+                text: lines.join("\n"),
+              });
+            }}
+          />
+          <span className="pl1">{children}</span>
+        </li>
+      ),
+    };
+  }
+
   render() {
     let {
       className,
@@ -156,6 +184,8 @@ export default class Text extends Component {
                 getSettingsStyle(settings),
               )}
               source={settings.text}
+              sourcePos
+              renderers={this.getRenderers()}
             />
           ) : (
             <textarea
@@ -187,6 +217,8 @@ export default class Text extends Component {
               getSettingsStyle(settings),
             )}
             source={settings.text}
+            sourcePos
+            renderers={this.getRenderers()}
           />
         </div>
       );
```

**Comment by AbdulHafez** [comment]
This is awesome man, thanks!!!
