### ISSUE TITLE
Allow Custom Expression column to be used in a chart

### ISSUE THREAD

**Issue by bfritscher** [metabase/metabase#6363]
Hi, don't know if its a Bug or a missing feature?

When I use the graphical editor to make simulate the following query:
SELECT a, SUM(b) FROM ... GROUP BY a;
Chart widget works and shows me A, SUM as available columns

But when I use a Custom Expression to multiply by a scalar (to change chart direction)
SELECT a, SUM(b * -1) FROM ... GROUP BY a;

EDIT: However, I discovered that defining a new custom field c = b* -1 and then using the SUM(c) ith works.

The result works in table mode, but chart does not list the SUM field anymore.

Otherwise I love this great product!

- Your browser and the version:  Chrome 62
- Your operating system: Windows 10
- Your databases: SQL Server
- Metabase version: 26.2
- Metabase hosting environment: Docker (metabase/metabase)
- Metabase internal database: H2 (default)

**Comment by attekei** [comment]
Seems that result columns of arithmetic expression query is completely missing type metadata (`base_type`/`special_type` are both empty). For that reason visualizations don't recognize that as a numeral result. For the following query:

```
{
  "source_table":1,
  "aggregation":[["sum",["*",["field-id",6],-1]]],
  "breakout":[["datetime-field",["field-id",1],"day"]]
}
```

I receive the following `cols` in result:

```
[
      {
        "description": "The date and time an order was submitted.",
        "table_id": 1,
        "schema_name": "PUBLIC",
        "special_type": null,
        "unit": "day",
        "name": "CREATED_AT",
        "source": "breakout",
        "remapped_from": null,
        "extra_info": {},
        "fk_field_id": null,
        "remapped_to": null,
        "id": 1,
        "visibility_type": "normal",
        "target": null,
        "display_name": "Created At",
        "fingerprint": {
          "global": {
            "distinct-count": 10000
          }
        },
        "base_type": "type/DateTime"
      },
      {
        "description": null,
        "table_id": null,
        "special_type": null,
        "name": "sum",
        "source": "aggregation",
        "remapped_from": null,
        "extra_info": {},
        "remapped_to": null,
        "id": null,
        "target": null,
        "display_name": "sum",
        "base_type": null
      }
    ]
```

You can see that the aggregation column doesn't contain any type metadata.

I _could_ default to a `Number/Type` type if `source` is `aggregation` type metadata is missing, but that feels pretty hacky. For that reason I'd prefer modifying the backend to include a type definition in the arithmetic query result column. Could @camsaul or @senior take a crack at that?
