### ISSUE TITLE
Support filters in questions on questions for fields from original question

### ISSUE THREAD

**Issue by goodfella1408** [metabase/metabase#6364]
In questions on existing questions I would expect all the filters applicable on original question to be applicable on the question on question as well.
For eg I need a dashboard which shows - for a region ,  a list of users with zero activities .Region is required as a top level filter .
So in the original question I get count of activities grouped by user .
In the question on question - I get a list of users where activity count is zero .
I should be able to apply the region filter in the question on question since the original question supports it

**Comment by flamber** [comment]
Closing in favor of #4367
