### ISSUE TITLE
Disable downloads on public links on questions

### ISSUE THREAD

**Issue by abizer** [metabase/metabase#6369]
I want to publicly distribute some graphs we've generated using Metabase by embedding them on our website, however, I'd like to prevent random people on the internet from downloading the raw data used to generate the graphs. Would it be possible to implement this feature? I don't know much about the technology used on the frontend of Metabase, but I think adding some way to toggle this line: https://github.com/metabase/metabase/blob/e9c6154b6ee8da7963e7e75fd586443fde8e3968/frontend/src/metabase/public/containers/PublicQuestion.jsx#L154 would suffice?

Thanks!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by stefanproell** [comment]
I would like to add that this feature would be great to have also internally, to prevent users from downloading data sets returned by answers to their questions. Ideally, this would be integrated into the permissions settings.

**Comment by erix920** [comment]
I would like this feature as well.

**Comment by tlrobinson** [comment]
Are you trying to prevent non-sophisticated users from casually downloading the data, or are you trying to prevent even technical people from extracting the data?

It would certainly be possible to have a way to hide the button in the UI, however it would be the equivalent of "disabling right click". Someone moderately technical will still be able to look at the network requests and figure out how to get the data, since by necessity we need to pass the data to the frontend for visualization.

The only way to completely avoid that would be to render the visualizations server-side and display a non-interactive image of the visualization, which we don't support yet (see #4701), but you could implement with something like PhantomJS or Headless Chrome.

**Comment by erix920** [comment]
In our case, the raw data users are analyzing is publicly available so security isn't a high priority. It would be more beneficial to us for users to share a link to their question/dashboard to get other users into the system. Otherwise they'll be exporting xlsx files and we'll be back to the stone age.

In short - Yes, an option to disable the button through the UI would be great.

**Comment by MarcGJA** [comment]
The option to disable the download ability on all embedded resources is DEFINATELY a good idea!  It's rather astonishing really that such an option hasn't been part of Metabase embedding from the get-go.  Most embed end users are not even remotely technically inclined, a download disable option would be quite effective.  Picture an app with embeds, for example, with three tiers of service, Free, Basic, and Premium where the Free tier does not have download ability.  That's an additional incentive to driving Basic and Premium subscriptions!

**Comment by jornh** [comment]
@abizer and @MarcGJA your use cases seem both to be with embedded or public sharing. For that a quick and simple workaround is to publish a dashboard which ([currently ](http://discourse.metabase.com/t/ability-to-download-from-dashboard/1897/11?u=jornh)) doesn't have the download option. See https://www.pursuittechnology.co.uk/products/metabase/ for a demo page where you can compare the two embedded in the same public page. And yes you can also make a dashboard with only one big question 🙂

**Comment by MarcGJA** [comment]
Thank you @jornh, that's a very good suggestion, helps me out allot!  There have been requests for downloading from individual cards in dashboards, however, so we'll have to keep a lookout for when that comes into play.  As is users wishing to download have to fish around for the corresponding chart to which can be rather frustrating so it will be nice when they can finally download directly from the dashboard cards!

**Comment by dizzydes** [comment]
> @abizer and @MarcGJA your use cases seem both to be with embedded or public sharing.
> 
> For that a quick and simple workaround is to publish a dashboard which ([currently ](http://discourse.metabase.com/t/ability-to-download-from-dashboard/1897/11?u=jornh)) doesn't have the download option. See https://www.pursuittechnology.co.uk/products/metabase/ for a demo page where you can compare the two embedded in the same public page. And yes you can also make a dashboard with only one big question 🙂

Is this still possible? It now seems that downloads are now enabled on dashboards. I guess there's still no way to turn off...

**Comment by MarcGJA** [comment]
@jornh, Would you know if a disabling downloads option is in the pipeline or is it already there and I just haven't found it?  Now that downloads can be done from dashboards (which is VERY welcome) the single-chart dashboard workaround is no longer an option.  Surely there are plenty of admins who'd make use of disabling downloads to justify having such a simple option in there somewhere.

**Comment by sethia** [comment]
Is there any plan to get this implemented?

**Comment by igisho** [comment]
Hi, this feature was abadoned? Or it is implemented somewhere in system?

**Comment by lamourj** [comment]
Any news on that ? That's actually an absolute must for us to use Metabase... :(

**Comment by MarcGJA** [comment]
There's a couple posts to the discourse site about this that advise the use of a reverse proxy and hiding the download buttons:
https://discourse.metabase.com/t/disable-downloads-for-users/6780
https://discourse.metabase.com/t/limit-what-can-be-exported-to-excel-csv/5170

With only 19 upvotes on the opening post and long gaps in discussion it's unlikely to make the <a href="https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Type%3ANew+Feature%22">highly requested items</a> list.  So unless that changes dramatically overnight or a champion for this issue emerges that's probably the best that can be done for the time being.  

Seems to me this is a very simple fix for a global solution, just provide an enable download checkbox in the Sharing>Application console, that would be good enough for now.  A more precise solution would be to tie that to some criteria such as which collection the dashboard is in, user group, etc.  It seems so natural that if I haven't shared an embedded dashboard in a while I inevitably search high and low for exactly such a checkbox only to remember, oh yeah, that doesn't exit yet!

**Comment by MarcGJA** [comment]
There's a couple posts to the discourse site about this that advise the use of a reverse proxy and hiding the download buttons:
https://discourse.metabase.com/t/disable-downloads-for-users/6780
https://discourse.metabase.com/t/limit-what-can-be-exported-to-excel-csv/5170

With only 19 upvotes on the opening post and long gaps in discussion it's unlikely to make the <a href="https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Type%3ANew+Feature%22"> highly-requested items</a> list. So unless that changes dramatically overnight or a champion for this issue emerges that's probably the best that can be done for the time being.

Seems to me this is a very simple fix for a global solution, just provide an enable download checkbox in the Sharing>Application console, that would be good enough for now. A more precise solution would be to tie that to some criteria such as which collection the dashboard is in, user group, etc. It seems so natural that if I haven't shared an embedded dashboard in a while I inevitably search high and low for exactly such a checkbox only to remember, oh yeah, that doesn't exist yet!

**Comment by askeluv** [comment]
Any news on this? Seems like a relatively low-effort feature, so wondering ~how many upvotes we'd need to get this implemented.

**Comment by AnishLushte07** [comment]
Hi Guys, 
Any update on this issue?

**Comment by jlisyc** [comment]
Hi all,
As a proposal, it will be great also the possibility to choose what type of public download we want for embeded dashboards. I mean, allow only , for example, csv, but not xls or json.
Thanks

**Comment by KhubaibQaiser** [comment]
Any update on this one? Looks like its still not possible to hide/disable the download button.

**Comment by albertoperdomo** [comment]
Today, downlads can be disabled by including the parameter `hide_download_button`in the URL. See [docs](https://www.metabase.com/docs/latest/questions/sharing/public-links#appearance-parameters). This only affects questions, not dashboards.

In 51, we are making this consistent across questions and parameters, and static embedding and public links,  and changing the parameter to downloads=true|false (true by default).

**Comment by Tony-metabase** [comment]
@albertoperdomo looking at this feature request and just to confirm that I should open another feature request if I want to share interest in disabling downloads for Dashboards?
