### ISSUE TITLE
Add "clearCheckSums" to `migrate force`

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6372]
When working on a PR, it's common to change an existing migration. This might be due to evolving the database as the feature is being worked on, or it might be due to collapsing migrations before merge. When doing this, the SHA of the changeset is different and Metabase will fail to start due to the hashes being different.

It looks like Liquibase has the ability to remove the checksums from the database and recalculate them [using the command-line utility](http://www.liquibase.org/documentation/command_line.html). It would be nice to add that to our `migrate force` call so that we don't have to manually update those databasechangelog entries (like we currently need to do).

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by whatsup1088** [comment]
Hi, I'm new to metabase, i have modified some html file in metabase.jar after decompress it, however, when i restart metabase's container after compressed it back and run metabase web, it show "SHA-256 digest error for frontend_client/index.html" on my page. Not sure if this situation is the same as you mention above:

>  When doing this, the SHA of the changeset is different and Metabase will fail to start due to the hashes being different.

If do so, how can i solve it ? 
Any advice or suggestions will be greatly appreciated !!

**Comment by senior** [comment]
@whatsup1088 this issue is different. Whenever we create a database migration, that migration is hashed and stored in the database. When that migration changes (i.e. you change an existing migration, or move to a different branch where migration 25 is different than migration 25 on the previous branch), Metabase will fail to start. This only related to database migrations and should only happen if you were using code built from topic branches of the metabase repo.

What are you wanting to change about the HTML files?
