### ISSUE TITLE
Weird vertical alignment in native query editor

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6381]
Only one with a masterful eye for design detail would catch this subtle surprise, lol. 👀  

But now that I have brought it to your attention you may well notice that the buttons in the native query editor seem to have different vertical alignments:

![screen shot 2017-11-13 at 6 06 24 pm](https://user-images.githubusercontent.com/1455846/32759587-00525ff2-c89f-11e7-8f99-a2dc1c4044bc.png)

I added some lines to make it easier to see: 

![screen shot 2017-11-13 at 6 06 24 pm](https://user-images.githubusercontent.com/1455846/32759631-37076d3a-c89f-11e7-99d1-acda815627c4.png)

It seems like the `x` is smaller than the others and trying to fly away, and the 'SAVE' is also smaller and trying to dive into the water. Just aligning the vertical centers of these would probably look 10x better but I think ideally the `x` should probably be the same size as the others

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by flamber** [comment]
Closing, since 0.34 introduced a rearranged UI:
![image](https://user-images.githubusercontent.com/1447303/82764366-72bde600-9e0e-11ea-8273-7ac7b952829a.png)
