### ISSUE TITLE
Question save button gets squashed when the window gets small

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6382]
I thought this looked weird. @salsakran says as the very least it needs some padding.

![screen shot 2017-11-13 at 6 15 46 pm](https://user-images.githubusercontent.com/1455846/32759755-ff356988-c89f-11e7-8be9-8d037ce3d037.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
I don't think my window was really "small" I think I had a width of like 1200px or something

**Comment by kdoh** [comment]
Based on that screenshot it looks like what’s happening is the save button is getting squished up against the edit inputs. Only case I can think of that would cause that is a relatively small browser viewport.

**Comment by camsaul** [comment]
ok, just tried this again and it looks like the button unsticks around 1030px for me on Chrome. So small but not crazy-small, especially for people who aren't running full-screen

**Comment by mazameli** [comment]
This is no longer relevant since the UI has changed.
