### ISSUE TITLE
Want to represent everything in percentage of distinct uuid and required total number of distinct uuid in pie chart

### ISSUE THREAD

**Issue by SrujanASK** [metabase/metabase#6384]
### Bugs
- browser and the version: - chrome Version 61.0
- operating system: Windows 10
- Metabase version: 24.1

I want to build a dashboard where one template is in pie, i am facing some issues for building the same,
data-
------
uuid    category
1           banking
1           ecomm
1           travel
2           banking
2           insurance
3          travel&hotel

my question in sql - "select category,count(distinct uuid) from data group by 1"

in metabase it is representing as a total number of rows in the middle of pie chart but I required to show the total number of distinct uuid's.

![image](https://user-images.githubusercontent.com/20420554/32773371-ee022796-c94e-11e7-9660-5fcb4dbdcf70.png)

2nd question 
Is it possible to represent everything in percentage in dashboard instead of representing in numbers

**Comment by salsakran** [comment]
If you want to display percentages, just modify the sql to generate percentages.

Or are you using the query builder for this pie chart?

**Comment by SrujanASK** [comment]
@salsakran, I am using query builder that is directly giving me the representation in number of rows as shown above but required to shown in distinct primary keys in selected data

how can i do that

**Comment by sbelak** [comment]
We've added a lot of visualization options to charts in the last couple of versions, including option to show percentage in pie charts.

The number you see in the middle is probably the sum of distinct uuids by category, which is probably not correct. I'll open a new issue more specific to this bug.
