### ISSUE TITLE
postgres query processor should better handle bad filter clauses

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#639]
if you pass in a filter clause like "filter": ["AND", [null, null], ["=", 123, "abc"]] the driver errors out because it tries to build an anded sql where clause when realistically there is only 1 valid filter.

**Comment by camsaul** [comment]
Closing as no longer relevant. These days the Query Expansion phase of the Query Processor now gives much more relevant errors, and per discussion it doesn't make sense to allow malformed query clauses like `{:filter ["<" nil nil]}`
