### ISSUE TITLE
Point tooltip for first series on line charts displays false information (Master)

### ISSUE THREAD

**Issue by ElDynamite** [metabase/metabase#6401]
On master, when creating a line chart or area chart (only tested with these two) with more than one series, mousing over a point on the first series will display information for all series, but the information for the other series will be from the next data point. 

Example: Mousing over this point should display either (N:1, X:1), as it does in 26.2, or (N:1, X:1, Y:2). Instead it displays (N:1, X:1, Y:3), with Y:3 taken from the next data point. 

![8pv8eay](https://user-images.githubusercontent.com/10265244/32863785-822faf52-ca11-11e7-9c08-06ff684a92c2.png)

When working with unsorted dates on the x-axis (and using the X-Axis: Timeseries option), the incorrect data is taken from the next data point in the unsorted dataset.

This does not occur on the 26.2 release, in which the tooltip only displays information for its own series.

**Comment by camsaul** [comment]
For future use, the SQL in the screenshot, ready for cut-and-paste, is:

```sql
WITH RECURSIVE t(n,x,y) AS (
    SELECT 1,1,2
    UNION ALL
    SELECT n+1,n+1,n+2 FROM t WHERE n < 5
)
SELECT * FROM t;
```
