### ISSUE TITLE
Guide to load balance Metabase with connection draining

### ISSUE THREAD

**Issue by 23ranjan** [metabase/metabase#6403]
Hi ,

Is there any way to match origin / host header? 

The thing is we are using 2 endpoints (endpoint-1 and endpoint-2) and we want endpoint-1 to redirect all the requests to endpoint-2.

In `admin/settings/general` we have specified site url as `endpoint-2` but still `endpoint-1` is serving traffic and is not redirecting traffic to `endpoint-2`

Thanks,

**Comment by salsakran** [comment]
In general, we assume that Metabase will be run as a single instance. We don't have any kind of controls around sticky hosts.

**Comment by salsakran** [comment]
why are you running multiple instances?

**Comment by flamber** [comment]
Closing, since horizontal scaling has been supported for multiple years.
https://www.metabase.com/learn/administration/metabase-at-scale.html
