### ISSUE TITLE
"Last x days/hours"-Filter 

### ISSUE THREAD

**Issue by majnu-campact** [metabase/metabase#6404]
Metabase has great filtering capabilities, but I found no way to select say the last 14 days **including** today in a filter. Our data is available in real-time and we have a hard time with relative date filters (like "Previous x days/hours") that mostly exclude the last day/hour, etc.

Thanks!

**Comment by Digma** [comment]
Typically what we do in our case is filter on "last 1440 minutes" to get data for the last day in real-time. However this only works in question but not in dashboard filters since metabase restricts options to "day/week/month/year"

**Comment by mazameli** [comment]
Yep, we'd really like to add this. This issue is a duplicate of https://github.com/metabase/metabase/issues/4749.
