### ISSUE TITLE
Dashboard. Filtering by ID gives error "There was a problem displaying.."

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#6405]
## Environment
Your browser and the version: Chrome 62.0
Your operating system: Ubuntu
Your databases: Postgres
Metabase version: 0.26.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

## Steps to reproduce
- Create a Question A ( related to table a). Note: This table a has a primary key --> in metabase an entity key (ID) 
- Create a Dashboard B with that Question A.
- Create in that Dashboard B a filter ID with that ID

## Observed result
- If execute the dashboard with a id (number) give error "There was a problem displaying.."
Note: Because of it's a test environment we have change in metadata, for that report_dashboard, column "parameters" of table "report_dashboard" the type to number ("type":"id" to "type":"number"), and for one value it works. But we lost the functionality to add multiple values separated by commas.

## Expected result
- Dashboard filtered by a number in that filter Id (or by a list multiple values separated by commas)

### Thanks a lot!
-------

**Comment by flamber** [comment]
Hi @jlisyc 
I cannot reproduce your issue. Are you still having issues, even in the newest Metabase version 0.31.2?

**Comment by jlisyc** [comment]
Thanks a lot again @flamber.
Tested in 0.31.2 and works OK.
