### ISSUE TITLE
Editable filters are not applied for embedded question download

### ISSUE THREAD

**Issue by nkconnor** [metabase/metabase#6407]
With an embedded question, clicking on 'download full results' will drop the filter selection and replace it with a `AND 1 = 1` clause in the query. This e.g. makes an embedded question with a date range select the entire range as opposed to the filtered view on the card.

Using the normal question interface, 'download full results' includes the filter settings as expected.

Relevant info
- Your browser and the version: Version 59.0.3071.104 (Official Build) (64-bit)
- Metabase version: 0.26.2
- Tested question is Custom SQL Expression, 1 Editable Date Range Field Filter, 1 Locked Text Filter

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
Fixed by #6503
