### ISSUE TITLE
Enable ability to apply multiple types to metabase fields

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#641]
Right now each Field in a table can only have a single type, which is very limiting.  There is a very real reason to be able to apply multiple types to each field.

Possibly move metabase types to an M2M tag

We have a very strict set of types for entities and fields. We should make them a tag based system to allow for a hierarchical ontology.

We would use this to allow multiple levels of semantic information to be carried through the system. EG. we can have things marked as both dimensions, metrics, as well as an underlying type e.g. datetime vs category (i.e. low cardinality int or string)

**Comment by salsakran** [comment]
Closing this given that there isn't a clear metadata ontology and that this was a remnant of a previous ontology.
