### ISSUE TITLE
Resizing dashboard cells does not work in Firefox browser

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#6416]
Resizing dashboard cells does not seem to work in Firefox browser.

# Environment
- Browser: Firefox 56.0,
- Operating System: Ubuntu 17.10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: 0.26.2
- Metabase hosting environment: Linux/Ubuntu
- Metabase internal database: default

# Steps to reproduce
- connect to a database
- create a simple question (e.g. counting items to output a table)
- add question to dashboard
- save dashboard
- click 'edit'
- click widget to resize (corner of widget)
- move mouse to different dashboard cell
- click to finalize resize action

# Observed result
The cell does not resize. Instead, it seems to remain elastic, like it didn't register the second click event.

# Expected result
The second click would finalize the resize action (as it does in Chrome browser).

**Comment by mazameli** [comment]
This appears to be a problem specific to Firefox **56**. I was not able to reproduce this behavior on Firefox 57 (latest).

**Comment by brylie** [comment]
OK, cool. Things are now working properly for me in Firefox 56 also. It seems like a transient bug or user error.
