### ISSUE TITLE
Mac app (0.26.2) crashing on macOS High Sierra

### ISSUE THREAD

**Issue by AlexVPopov** [metabase/metabase#6417]
OS: macOS High Sierra 10.13.1 (17B48)
Metabase version: 0.26.2
DB: PostgreSQL 9.6.5 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit

Possibly related to #6068 

I just downloaded the mac app and when I start it, the logo keeps spinning and after some time it displays a dialog "The Metabase server terminated unexpectedly".

**Comment by Rioos** [comment]
Same here!

**Comment by camsaul** [comment]
@AlexVPopov @Rioos  do you see any other error messages? Does updating to the latest version (0.27.1 at the time of this writing) fix the issues?

**Comment by Rioos** [comment]
Can't update right now, i'll check it out tomorrow.

**Comment by camsaul** [comment]
One other thing that will help me diagnose this issue. If you get a chance can you open the Terminal and run

```bash
ls ~/Library/Application\ Support/Metabase/
```

and tell me the results?

**Comment by AlexVPopov** [comment]
@camsaul With the latest version 0.27.1 the problem doesn't occur. Thank you.

**Comment by camsaul** [comment]
Thanks @AlexVPopov. Closing this since it sounds like the latest version fixed it. @Rioos if you're still running into issues please let me know.
