### ISSUE TITLE
Can't set setting in the admin

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6422]
In trying to set eg the slack api token I get the below error -

![screen shot 2017-11-17 at 3 50 23 pm](https://user-images.githubusercontent.com/107439/32973882-2072ca3e-cbaf-11e7-981b-7f0f0fa95f88.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by johnlo1992** [comment]
+1

**Comment by camsaul** [comment]
Looks like this line right here:

```
MetabaseAnalytics.trackEvent("Slack Settings", "Toggle Metabot", value);
```

**Comment by camsaul** [comment]
oh. oops

**Comment by camsaul** [comment]
I changed this code in the utils files to be this:

```
    isEmpty: function(str) {
        return (str == null || 0 === str.length || str.match(/^\s+$/) != null);
    },
```

apparently whatever `str` is, it's not a string because it doesn't have a `.match()` method

Somebody somewhere is calling Utils.isEmpty with a non-string

**Comment by camsaul** [comment]
Guessing someone is calling it with a boolean because the error happens when you try to toggles the metabot. wow
