### ISSUE TITLE
Heroku Upgrade Issues

### ISSUE THREAD

**Issue by johnlo1992** [metabase/metabase#6423]
Hi!

I deployed Metabase(v0.27.0-snapshot) from the 'Deploy to Heroku' Button.
Followed the instructions from: https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html

I tried `git clone https://github.com/metabase/metabase-deploy.git`  but received the following errors in terminal: 

```
Cloning into 'metabase-deploy'...
remote: Counting objects: 411, done.
error: RPC failed; curl 56 SSLRead() return error -9806/s       
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

So I decided to just download the files from https://github.com/metabase/metabase-deploy as .zip and create a directory called metabase-deploy.
I added the remote `git remote add heroku https://git.heroku.com/your-metabase-app.git` and build pack `heroku buildpacks:add https://github.com/metabase/metabase-buildpack`
and ran `git push -f heroku master`, but resulted in the following error:

```
Counting objects: 14, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (14/14), 14.61 KiB | 0 bytes/s, done.
Total 14 (delta 1), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://github.com/heroku/heroku-buildpack-nodejs
remote:        Node.js: package.json not found in application root
remote: 
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to 
```

There must be something simple I'm overlooking, any guidance would be appreciated! Thanks!

**Comment by salsakran** [comment]
`git clone` works for me, but the repo size has gotten monstrous. I'll clean out the old jar diffs.

**Comment by johnlo1992** [comment]
Thanks!

I did some more digging into the last error when running `git push -f heroku master`. Seems like the buildpacks are in this order:
```
1.https://github.com/heroku/heroku-buildpack-nodejs
2.https://github.com/heroku/heroku-buildpack-clojure
3.https://github.com/metabase/metabase-buildpack
4.https://github.com/heroku/heroku-buildpack-jvm-common.git
```
Removing 1 and 2, allows the update to go smoothly:
```
Counting objects: 1, done.
Writing objects: 100% (1/1), 194 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Metabase app detected
remote: -----> Downloading Metabase... from http://downloads.metabase.com/v0.27.0.RC1/metabase.jar to /tmp/build_9621a478fed69af814fdf4f837c6f77a/Desktop/metabase-dt/target/uberjar/metabase.jardone
remote: -----> JVM Common app detected
remote: -----> Installing JDK 1.8... done
remote: -----> Discovering process types
remote:        Procfile declares types -> (none)
remote: 
remote: -----> Compressing...
remote:        Done: 149.6M
remote: -----> Launching...
remote:        Released v8
```
but now there's the issue of somehow reinserting the 2 buildpacks since the procfile doesnt indicate how many dynos should be running on Heroku, which I assume was being handled by the nodejs buildpack, leading to this error, when running `heroku logs`:
`2017-11-18T00:31:23.249605+00:00 heroku[router]: at=info method=GET path="/api/activity" host=metabase-test1.herokuapp.com request_id=4bd18b06-0a25-488a-bdd0-3e4fdf113874 fwd="5.65.56.240" dyno=web.1 connect=0ms service=459ms status=200 bytes=679 protocol=https`
and running `heroku ps` to confirm:
`No dynos on ⬢ `

Hopefully I'm going in the right direction in solving this upgrade issue

**Comment by johnlo1992** [comment]
@salsakran which files are supposed to be included in metabase-deploy (https://github.com/metabase/metabase-deploy)? You mentioned the repo size has gotten monstrous, but I am only seeing 6 files (total under 15kb).

Thanks :)

**Comment by salsakran** [comment]
@johnlo1992 We've removed the old files from the index history, and it should be much faster now. Mind trying again?

**Comment by dacort** [comment]
Closing as this is an old issue and `metabase/metabase-deploy` now uses `metabase/metabase-buildpack` (https://github.com/metabase/metabase-deploy/blob/master/app.json) and repo size is manageable again.
