### ISSUE TITLE
Add documentation for field detailed types.

### ISSUE THREAD

**Issue by mjalkio** [metabase/metabase#6425]
As far as I can tell the "detailed type" for fields are not documented anywhere other than https://www.metabase.com/docs/v0.12.0/administration-guide/03-metadata-editing.html, and that page only lists the types out. It's not clear to a new user (such as myself) what changing the type does within Metabase. And in some cases, it's not clear how types are different.

For example, Category and Enum sound very similar to me, and I'm not sure what the implications are of using one or the other.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by nikolasrieble** [comment]
Any update on the documentation?

**Comment by alexberd** [comment]
Will be nice to understand how the above types could be used:

`    Avatar Image URL
    Category
    City
    Country
    Description
    Foreign Key
    Entity Key
    Image URL
    Field containing JSON
    Latitude
    Longitude
    Entity Name
    Number
    State
    URL
    Zip Code`

https://www.metabase.com/docs/v0.26.2/administration-guide/03-metadata-editing.html
Many thanks,
Alexandros

**Comment by frannietrempe** [comment]
Docs updated on [field types](https://www.metabase.com/docs/latest/users-guide/field-types.html) and [data types](https://www.metabase.com/learn/databases/data-types-overview.html).

**Comment by vanja-bertalan** [comment]
> Docs updated on [field types](https://www.metabase.com/docs/latest/users-guide/field-types.html) and [data types](https://www.metabase.com/learn/databases/data-types-overview.html).

A lot of field types don't have any explanation. Any idea on when the docs might get updated?
