### ISSUE TITLE
pre login error

### ISSUE THREAD

**Issue by seeramzan** [metabase/metabase#6428]
Hi,

I am using the latest release, but sometimes suddenly start facing an error, pre-login error. SQL server is working file, all services are up. but this error is appearing until i close the command prompt and reload the metabase.jar file.

"WARNING: ConnectionID:1523 ClientConnectionId: 33303124-edc4-4c45-8668-5f192ceb3cdb Prelogin error: host localhost port 50526 Error reading prelogin response: Connection reset ClientConnectionId:33303124-edc4-4c45-8668-5f192ceb3cdb
"

**Comment by jornh** [comment]
This sounds more like a firewall/connectivity or SQL Server configuration issue than a Metabase specific issue. Does https://stackoverflow.com/questions/11335797/problems-logging-into-mssql-server-from-java or similar results from googling for “Prelogin error: host localhost port 50526 Error reading prelogin response: Connection reset” help?

**Comment by salsakran** [comment]
This is a connectivity issue, and outside of the scope of Metabase itself. You might have some luck asking on our user forum (discourse.metabase.com)
