### ISSUE TITLE
Is there a way to have a query result, after/before CURRENT DATE (current should always be dynamic)

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6433]
There is already an option in `Metabase` for `CURRENT` that passes the current date (today) to the query and returns the result for today, which is great by the way.

But what we want to have is to select `BEFORE`/`AFTER` option and say: before/after current day. I need it to be dynamic like what `MySQL` does for us: `WHERE registration_date < NOW()`. 

![before date](https://user-images.githubusercontent.com/6417083/33006831-1dc74d08-cde1-11e7-9ec2-a9e61e572955.png)

Is it possible in Metabase now? If not is there any plan to have this feature for the next release or so?

Thank you very much for the effort.

**Comment by jornh** [comment]
Yes, see https://metabase.com/docs/latest/users-guide/04-asking-questions.html#filtering-by-dates more specific “relative dates” there.

Depending on your exact needs around “today” there are caveats and workarounds - see #6404 and the older issue it points to.

Hope that resolves your query!

**Comment by mazameli** [comment]
Actually I think Ali Reza is asking for something that is more like `After Today` or `Before this week`, as mentioned in a comment on this issue: https://github.com/metabase/metabase/issues/4083#issuecomment-283915746

**Comment by alirezastack** [comment]
@mazameli Yes that's actually what I'm looking for. Something like `After Today` or `Before this week` and so. Is there any milestone for the issue to get solved?

**Comment by moberemk** [comment]
We ran into this same use case earlier today; some of our questions, like tracking user actions by day, only make sense when totalled at the end of the current day; otherwise, depending on when you look at the question, it looks like there was a precipitous drop from the day before. The ability to limit the question window to the day before the current day (or current week for weekly-totalled values, month for monthly, etc.) would make these charts far more useful to us.

**Comment by Ucinorn** [comment]
For those who stumble upon this and are waiting for this functionality to be implemented, you can achieve this functionality using a hack of the relative date filter, like this: 

![image](https://user-images.githubusercontent.com/8098617/55530881-ab26d000-56f3-11e9-935e-e74336f58758.png)

By setting the before X days to and high number it's effectively a 'everything before today' query. 

If you don't want to have to instruct your users to do this, set it up as a custom segment, works great.

**Comment by mazameli** [comment]
Going to close this in favor of #4083. I think this is effectively a duplicate.
