### ISSUE TITLE
Connecting to postgres metabase db over ssl on Azure

### ISSUE THREAD

**Issue by viblo** [metabase/metabase#6435]
I want to use an azure hosted postgres instance as my metadata store. However, I have not been able to connect using SSL encryption. 

I think my problem is two parts
1. Since there is no public SSL option I have to use MB_DB_CONNECTION_URI as described in #3296
2. However, setting MB_DB_CONNECTION_URI does not seem to support using a username on the format `name@host`.

If I look in the azure portal it shows my connection string, something like this but with my real values:
`jdbc:postgresql://{uniquehostname}.postgres.database.azure.com:5432/{your_database}?user={username}@{uniquehostname}&password={your_password}&ssl=true`

I also tried the formatting used in #3296, but it also didnt work.

However, it works if I use the broken out version, but then I cant use SSL:
```
MB_JETTY_PORT=3000 \
MB_DB_TYPE=postgres \
MB_DB_DBNAME=mydbname \
MB_DB_PORT=5432 \
MB_DB_USER=myusername@myhostname \
MB_DB_PASS=skjlhsdf23asd \
MB_DB_HOST=myhostname.postgres.database.azure.com \
java -jar metabase.jar
```

I tried this on Metabase v0.26.2.

**Comment by camsaul** [comment]
Hi @viblo, that code assumes you have a connection string in the same format Heroku uses, which looks something like this:

```
postgres://cam@localhost.com:5432/cams_cool_db?ssl=true&password=123456
```

Try that format and let me know how it goes

**Comment by camsaul** [comment]
BTW we have an open issue for supporting SSL for application DBs that are configured with multiple env vars: #6095

If you want to add a :+1: reaction to the issue description that will help me make a case for dedicating some time to implement it

**Comment by viblo** [comment]
Note that I meant that my login name is name@host. So the full string becomes name@host@host (or something similar to that). 

I used the format you used in #3296:  `postgres://<username>:<password>@<host>:<port>/<dbname>?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory` that it ended up something like this `postgres://name@subdomain:123@subdomain.azure.com:5432/mydb?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`

**Comment by camsaul** [comment]
Try passing `user` as a query param in the connection string like this:

```
postgres://localhost.com:5432/cams_cool_db?user=cam@metabase
```

I just tried that out and it seems to be parsing it correctly

**Comment by viblo** [comment]
Thanks, putting the username as a query param fixed the issue!
