### ISSUE TITLE
Make date filters horizontal

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6443]
I'd like to propose that we rearrange the form elements in our date filters to make them horizontal so that they're easier to scan and understand. 

This also involves removing the "accordion" effect for individual selections and replacing them with standard drop downs, which has the added benefit of making it easier to tell you can click on them.

Lastly, in the designs I've imposed a min-width of 380px so that the width of the date filter popover won't change too much while switching between selections.

I'm also depicting where to put the "include today" checkbox [specced here](https://github.com/metabase/metabase/issues/4749#issuecomment-320098922) in issue #4749.

![previous](https://user-images.githubusercontent.com/2223916/33099674-7af50cfa-cec6-11e7-9f87-5d0cd57da701.png)

![current](https://user-images.githubusercontent.com/2223916/33099672-7acd4f1c-cec6-11e7-9cd7-2b66b788a841.png)

![before](https://user-images.githubusercontent.com/2223916/33099670-7aa61050-cec6-11e7-8ec7-ad079072110e.png)

![between](https://user-images.githubusercontent.com/2223916/33099671-7aba7356-cec6-11e7-8bf0-1c0d70069721.png)

![not empty](https://user-images.githubusercontent.com/2223916/33099781-f4e85c92-cec6-11e7-8018-3b39700cce9a.png)

**Comment by moumny** [comment]
Great design. I also had problems with the vertical layout.

The only thing that I think could be added is to bring back the relative and exact tabs from the old filters. I found that they help new users understand  the "relative" part esp. when making dashboards.
The second benefit would be that the dropdown would be shorter. (it takes me some time to find the right one)

**Comment by camsaul** [comment]
@kdoh @salsakran implemented by #6530?

**Comment by salsakran** [comment]
yup
