### ISSUE TITLE
scatter plot chart option

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#645]

**Comment by crearc** [comment]
+1

**Comment by tlrobinson** [comment]
Related: #1918

**Comment by salsakran** [comment]
Do we need any UI elements for this? Say an icon? @kdoh @mazameli

**Comment by bsellner** [comment]
+1.  Lack of scatter plots may kill metabase as an option for us.  On the flip side, if there aren't any giant landmines, we may be willing to contribute a patch for it.

**Comment by mazameli** [comment]
I think the only new UI element we'd need is a new icon to accompany the option in the visualization menu, which is trivial. 

Totally makes sense to add this feature, and we'd happily welcome a pull request for this, bsellner. tlrobinson would be the one to point out any landmines. Also, here are the [contributor guidelines](https://github.com/metabase/metabase/blob/master/docs/contributing.md) if you haven't seen them already, just for your reference.

**Comment by tomkanjam** [comment]
+1

**Comment by shaqq** [comment]
+1

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0
