### ISSUE TITLE
Metabase on Heroku doesnt show tables and dont save password

### ISSUE THREAD

**Issue by ilyashusterman** [metabase/metabase#6450]
This problem encountered before 2 days ago , by no change at the system.
1.heroku metabase does not save connection new password.
2.heroku metabase does not show data in tables anymore (database connection tested successfully at mysql client benchwork)

**Comment by salsakran** [comment]
@ilyashusterman any change on this? Sounds like the dyno stopped responding.

**Comment by mbvictoria** [comment]
Closing - no recent reports, seems to be fixed.
