### ISSUE TITLE
Document needed permissions for database user (if there are any)

### ISSUE THREAD

**Issue by kimroen** [metabase/metabase#6451]
Is it documented anywhere what kind of permissions the database user needs to the database? I'm trying to set up Metabase, and the database user we normally use for analytics (no write access) is denied access to the database with this error:

```
java.sql.SQLException: Access denied for user
```

The problem here could be something other than permissions, but it would be good to get that confirmed. Other database users with more permissions get access without issues.

**Comment by salsakran** [comment]
Where is that error appearing? If it is in the database addition screen, then we were not able to connect with that user to the database you supplied. 

For running queries, we just need read access to some databases and tables. There shouldn't be any exotic permissions required.

**Comment by kimroen** [comment]
We still haven't been able to set this up with a read-only user, but considering we've been able to connect to a different database on Redshift with a read-only user, I believe this is a problem on our side and not on Metabase. I'll make a new issue if it I find out otherwise.

**Comment by abcfyk** [comment]
same issue. appears in adding database panel with a read-only user. how to add a database IF I JUST WANT IT TO DO SOME ANALYTICS WORK? there's no reason for granting write access to a bi tool.
