### ISSUE TITLE
Dashboard filter not updated according to field scan schedule

### ISSUE THREAD

**Issue by rthouvenin** [metabase/metabase#6452]
## Problem
I have a dashboard to show some survey results, with a category filter which I use to pick which survey I want to look at. Because I have more than 300 surveys, I created a MySQL view that exposes the name of the latest 250 surveys and I use this view as the source "table" for the category filter.

Metabase is configured to re-scan the field values daily, yet it sometimes happens that new surveys don't show up in the dropdown, even several days after they were created. It *seems* that manually triggering a re-scan of this particular field solves the problem, at least it did the few times I did so.

Am I misunderstanding the way field scan works, or is it indeed a bug?

## Environment

- Your browser and the version: Firefox
- Your operating system: any
- Your databases: MySQL
- Metabase version: 0.26.1
- Metabase hosting environment: Linux/Ubuntu
- Metabase internal database: MySQL

## Side question

In this use case, a daily re-scan of the fields for this DB is not enough, because users usually don't want to wait for one day before looking at the results of the survey they sent. To solve this, I plan to set up a cron job that calls the metabase API to re-scan this particular field. If you think that's useful, I'll be happy to document how I did it, just let me know where/how I should contribute this (PR, wiki, other?).

**Comment by flamber** [comment]
Hi @rthouvenin 
Know this is old, but are you still seeing this "slowness" of scanning in the latest release?
My first thought is that the scan process was failing some days, but the logs should show that.

**Comment by rthouvenin** [comment]
@flamber Hard to say because this dashboard has been archived since then, and I can't think of a similar use case in my organisation that I could use to check. I have even stopped query-ing Metabase to force a scan more often than daily, so I'm fine closing the issue.

Different but related (could even be the original problem in this issue?): what I've noticed is that even after a successful scan, data may not appear right away in the UI because the browser caches the result to API calls done by the frontend. I can do a force-refresh, but not everyone in my team is techs-savvy enough to think of it.
This being said, I haven't got any complaints about that kind of problem, so I won't bother you with that yet :)

**Comment by flamber** [comment]
@rthouvenin Thank you for the info. About the cache issue, well, that's an oldie sadly. There's a handful of issues open about that in various areas: #5129 #5796 #9027 #10330 #11383 #11653
Closing this issue, since it's going to be difficult to tackle without logs.
