### ISSUE TITLE
Feature request: skip pulse if progress objective is reached

### ISSUE THREAD

**Issue by EtienneDepaulis** [metabase/metabase#6460]
We recently started to use Progress visualization for our Questions that require objective's management : 

![image](https://user-images.githubusercontent.com/639743/33174606-0bf2623c-d059-11e7-8a57-0d7793beaaa0.png)

The display is perfect on a Dashboard but we would like also to use it to its full extent in Pulses.
The "problem" is that we receive already quite a nice volume of pulses on our Slack and we would like to send it only when the objective is not reached.

Our current solution is to have 2 questions : 
- one for the dashboard which is always visible
- one for the pulse with an additional condition (in this example we have a `count_value < 250`) in order to use the "Skip if no results" option in pulses.

This second question cannot be used in dashboard as everytime the objective is met we have this message instead: 
![image](https://user-images.githubusercontent.com/639743/33174814-d69d9ff6-d059-11e7-9bf8-c1dc3372ecab.png)

We then have to update 2 questions.

Wouldn't it be nice if the "Skip if no results" could also be "Skip if objective is reached" ?

PS: thanks a lot for this awesome tool !!

**Comment by mazameli** [comment]
The new alerts feature that we merged in pull #6278, and which will be included in the upcoming version 0.27, should handled this case for you. Alerts can be set on any saved question, and lines with goals or progress bars can have special alert conditions set up relative to their goals. So in your case, you could set up an alert to repeatedly go out whenever the value of the progress bar is below the goal. Does that help?

**Comment by EtienneDepaulis** [comment]
Hello @mazameli, it looks perfect, thank you very much.
