### ISSUE TITLE
Redshift Spectrum Support.

### ISSUE THREAD

**Issue by sumit1294** [metabase/metabase#6461]
I tried executing query through Metabase but getting permission denied error:
ERROR: permission denied for schema

P.S. Have granted schema access to the Metabase user.
grant SELECT on ALL TABLES IN SCHEMA spectrum_prod to metabase_r;

Seems like it has no support for spectrum just like Redash.
https://discuss.redash.io/t/support-for-amazon-redshift-external-tables/1178

Please support this feature.

**Comment by paoliniluis** [comment]
@sumit1294 did you grant the select permission and the usage over that schema?

**Comment by sumit1294** [comment]
@paoliniluis yeah, I granted SELECT permission. 
grant SELECT on ALL TABLES IN SCHEMA spectrum_prod to metabase_r;

I also tried by granting ALL permission on the schema (my schema: spectrum_prod) to the Metabase user (metabase_r).

grant ALL on ALL TABLES IN SCHEMA spectrum_prod to metabase_r;

**Comment by paoliniluis** [comment]
@sumit1294 you should also do "grant USAGE IN SCHEMA spectrum_prod to metabase_r;" for this to work

PS: I don't remember if it's IN SCHEMA or ON SCHEMA, but try both

**Comment by sumit1294** [comment]
Thanks a ton @paoliniluis :). That's amazing, you are awesome. It (ON SCHEMA) worked. Thanks again! :)

**Comment by salsakran** [comment]
closing this since it seems like you got it to work @sumit1294
