### ISSUE TITLE
Passing database id to api/card with parameters ['f'=>'database']

### ISSUE THREAD

**Issue by iamNikitaValty** [metabase/metabase#6462]
Hello, 
I'm trying to retrieve from Metabase only the cards of a specific database. I'm using the REST API and i found that i can use the f parameter to specify database as filter. 
The problem i have is that, this parameter requires an id and i don't know how to pass it. 
I've googled the pb but found nothing interesting
I've tried passing it in the parameter array as such but, it doesn't work.
 _$ch = curl_init();
    $url = MY_METABASE_BASE_URL .'api/card';
    **$parameters = ['f'=>'database', 'id'=>'2' ];**
     curl_setopt($ch, CURLOPT_URL, $url . "?" . http_build_query($parameters));
   .....
	curl_setopt(
			$ch, 
			CURLOPT_POSTFIELDS,
			json_encode($parameters)
    	);
  ......._

I have this error message by the way: 
**{"errors":{"id":"id is required parameter when filter mode is 'database'"}}**

Please can somebody help me find out how to pass this dammit parameter ? I'm getting mad for searching. 
 - I'm accessing my Metabse hosted on Heroku from  a php app.
- My operating systemWindows 10
- My databases:  MySQL, MongoDB
- Metabase hosting environment: Heroku
- Metabase internal database:  MySQL, Postgres

**Comment by camsaul** [comment]
@iamNikitaValty sorry, it looks like the error message there was wrong for some reason. The actual param you need to pass is `model_id`, not `id`. Sorry about that.

**Comment by camsaul** [comment]
@iamNikitaValty for some reason we did have the correct param listed in the API reference [here](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#get-apicard) so I recommend taking a look at that while you're working on things

**Comment by iamNikitaValty** [comment]
@camsaul  thank you very much. It works now. You saved my live.

**Comment by mrsindhu-mindstormstudios** [comment]
Hi there!

I'm getting a card data to show on my CMS using: https://metabase.domain-name.com/api/card/23/query/json
By default I've set live DB connected for results for this card. I've 2 others DBs connected with metabase. i've to manually change the DB then hit the API. can i set database 1 in the API?

**Comment by mrsindhu-mindstormstudios** [comment]
@camsaul
