### ISSUE TITLE
The cursor in the filter label text field always jumps to the end of the input 

### ISSUE THREAD

**Issue by stefanproell** [metabase/metabase#6464]
This is just a minor inconvenience, but there is a small UX bug I noticed using Metabase 0.26.2 with Chrome Version 62.0.3202.94 on a Linux Mint 18.2

When I add variables in SQL based questions I can add filter labels for these variables. In the UI I can assign a label for each variable. The cursor of this text jumps after each key press to the end of the field, making edits of a label text cumbersome. 

![metabase_label](https://user-images.githubusercontent.com/5196286/33206991-5a90413a-d10c-11e7-83b2-3fa2910aab63.png)

**Comment by sldorman** [comment]
This is true for Firefox as well (version 57.0)

**Comment by vsusnova** [comment]
I am experiencing the same issue on Metabase v0.30.0, chrome 68.0.3440.106, postgres db.

**Comment by flamber** [comment]
Hi @stefanproell 
I cannot reproduce your issue on 0.31.2 with Firefox 65 and Chromium 71. Are you still experiencing this issue on newer versions of Metabase?
![screencast](https://user-images.githubusercontent.com/1447303/53268150-ea044780-36aa-11e9-8a6c-aa90eaf741e8.gif)

**Comment by flamber** [comment]
Closing since it hasn't been reported since and I cannot reproduce on 0.34.3
