### ISSUE TITLE
Google Analytics driver only lists tables owned by the given AccountId

### ISSUE THREAD

**Issue by magno32** [metabase/metabase#6468]
- Metabase version: master

Google Analytics allows _proxy_ users to admin and work with client data.  This requires the analytics api to be able to use different account id's, not just the one given for setup.

The `properties+profiles` function forces the view to be restricted to whatever AccountID we used to setup the database connection initially.

These 2 lines: 

https://github.com/metabase/metabase/blob/ce84557570477382419a5c7517288a4deda6df79/src/metabase/driver/googleanalytics.clj#L42-L43

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
