### ISSUE TITLE
Add "cumulative count" aggregation type

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#647]
Right now you have to sum the values from a specific column, but ideally you could just sum the count() of rows.

For example, if I want a chart of my user growth over time I would do a cumulative sum of count(*) of users grouped by day.  Right now this isn't possible.

**Comment by bmajz** [comment]
First thing I noticed when playing with the product. I want to make graphs go up and to the right!

**Comment by fjorgemota** [comment]
+1

**Comment by idris** [comment]
:+1:

**Comment by haroonm** [comment]
Come on, this is a BASIC need for all users.  PLEASE do it.

**Comment by camsaul** [comment]
Not sure that this is necessarily a "BASIC need for all users" but it would be straightforward to add this:

[Cumulative sum](https://github.com/metabase/metabase/wiki/Query-Language-'98#cumulative-sum-aggregation) is implemented by middleware that post-processes the results of a sum aggregation, so all we need to do is add similar middleware that can post-process the results of a count aggregation. We can make this a new type of aggregation called "cumulative count".

**Comment by javiercr** [comment]
:+1:

**Comment by nchudleigh** [comment]
+1

**Comment by ppawlak** [comment]
+1
