### ISSUE TITLE
Metabase and druid is not syncing after 1st sync

### ISSUE THREAD

**Issue by SrujanASK** [metabase/metabase#6472]
Druid version - 0.10
metabase version - 26.2
 
I have created a dashboard upon data which is in druid and monitored 12hrs+ it worked fine and in the next day I have seen a resync happened and then data is missing in Metabase i.e, metabase and druid are not syncing even though data is present in druid.

Please help me in this issue

**Comment by salsakran** [comment]
What exactly do you mean by "not syncing"? Is this in the query results themselves or the dashboard filters or ....?

**Comment by SrujanASK** [comment]
@salsakran 
I mean metabase is unable to fetch data from druid after sometime with 26.2 version (estimating after 24,48 hrs)
And so I tried using 24 version it is working fine till date

**Comment by mbvictoria** [comment]
Closing - has not been reported in recent versions.
