### ISSUE TITLE
Bubble color based on variable value

### ISSUE THREAD

**Issue by stefanproell** [metabase/metabase#6473]
Metabase allows setting the bubble size in scatter plots to be based upon the values of a column. It would be great, if in addition the bubble color could be set on variable values too. This would allow to easily differentiate categories of data in a scatter plot. 

Here is the selection for the bubble size. Adding a color field there too would be awesome.

![bubble](https://user-images.githubusercontent.com/5196286/33256262-a072ecd8-d351-11e7-888e-e985a8dbc825.png)

**Comment by johanbog** [comment]
It is kind-of possible now if you make a dashboard, and add several plots to the same figure, each of which has a different filter on the variable value.

**Comment by flamber** [comment]
Duplicate of #4741

**Comment by mazameli** [comment]
Closing as dupe of #4741.
