### ISSUE TITLE
Enable non admin user to share Dashboards.

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6482]
Have any way to make this permission ?

**Comment by mazameli** [comment]
You mean you'd like for non-admins to be able to enable public links for a dashboard, or at least to have a permission setting to turn that behavior on/off?

**Comment by jonatasfreitasv** [comment]
Yes @mazameli, exactly!

**Comment by socratec** [comment]
Access to a dashboard should be granted to a group of users or individual user. Depending on the type of dashboard (financial, sales, production), different audience require the information.  I am surprised that this is not implemented in the product. Individual collections provide permissions to a group of users.

**Comment by flamber** [comment]
Duplicate of #4333
