### ISSUE TITLE
How to export/import configuration and metadata

### ISSUE THREAD

**Issue by kstan79** [metabase/metabase#6485]
I'm new in metabase, I would like to check is there a way to support multiple database but same schema by export and import the configuration.

The use case as below:
1. we develop chart and dashboard at development server
2. we export all charts/dashboard/configuration and import into different server (production)
Cause we may have a few production server shared identical schema, we wish to eliminate repeated work on create chart, create dashboard cause we frequently change our work. 

Or, if metabase support multi-tenancy and allow administrator replace data source it will be much more easier.

Is there any suitable solution for my use case?

Thanks in advance.
Ks

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jornh** [comment]
A related discussion: http://discourse.metabase.com/t/managing-dev-qa-prod-environments/2225

**Comment by salsakran** [comment]
We don't currently allow you to export settings or have explicit multi-tenancy support.

You can probably do this via the rest API, however. https://github.com/metabase/metabase/wiki/Using-the-REST-API

**Comment by paoliniluis** [comment]
I would do this with an ETL between the testing and production databases (in case you use postgres or mysql). Metabase has a pretty self explanatory database!

**Comment by ijgonzalez-stratio** [comment]
Workaround.

Create a dump (just the data, not the DDLs) of your current DB using at least this tables:
public.report_card
public.report_dashboard
public.report_dashboardcard
public.collection
public.metabase_fieldvalues
public.metabase_field
public.metabase_table
public.metabase_database

Then you can import your dump file into a new Metabase clean environment.

**Comment by shmoulana** [comment]
Did any body tried and succeed on this ?

**Comment by mariofernandez-stratio** [comment]
Hi @shmoulana,

We implemented @ijgonzalez-stratio workaround and worked for us.

**Comment by mausch** [comment]
Maybe I'm missing something, but the problem I see with that workaround is that it assumes that the entries in metabase_database will be the same in the origin and destination, which isn't the case when "promoting" questions/dashboards from a dev environment to prod.

**Comment by mausch** [comment]
I ended up writing a tool to export/import SQL questions and dashboards to a JSON file

**Comment by gajus** [comment]
> I ended up writing a tool to export/import SQL questions and dashboards to a JSON file

Did you make it open-source?

**Comment by mausch** [comment]
I've just been approved to make it open source : https://github.com/elevate/elevate.metabase.tools

**Comment by RomainWilbert** [comment]
@ijgonzalez-stratio workaround does not work if the metabase database have different state i.e. already existing dashboards or questions. I have several foreign key constraints issues : 

> pg_restore: [archiver (db)] COPY failed for table "report_dashboardcard": ERROR:  insert or update on table "report_dashboardcard" violates foreign key constraint "fk_dashboardcard_ref_card_id"
> DETAIL:  Key (card_id)=(8) is not present in table "report_card".

**Comment by ijgonzalez-stratio** [comment]
@RomainWilbert You can solve the constraints issue with this two options as I did:
- Dump just the delta (your new dashboards or questions) filtering the tables. I did this.
- Clear the destionation DDBB tables before load the dumped data (this option is more risky)

Also, you've to be sure that the order of the inserts in your COPY is correct to solve the constraint issues. Based on your error, probably the report_card table wasn't populated before the report_dashboard table.

**Comment by RomainWilbert** [comment]
@josegonzalez I guess this had to do with the auto incremented ids

**Comment by anki-code** [comment]
:+1: Let's increment the related issue too - https://github.com/metabase/metabase/issues/2052

**Comment by sbelak** [comment]
Since a few versions ago, we have this functionality in the enterprise version: https://www.metabase.com/docs/latest/enterprise-guide/serialization

**Comment by anki-code** [comment]
I've solved this issue for me by this workflow/workaround:

1. I the fix version of metabase (for now it's v0.34.1)

2. I have a script witch get the `metabase.db.mv.db` file and clean it and convert it to sql file:

**metabase-db-to-sql.sh**:
```
#!/bin/bash
set -eu -o pipefail

H2_VERSION=2019-03-13

echo [Get H2]
wget https://h2database.com/h2-$H2_VERSION.zip
unzip h2-$H2_VERSION.zip
cp h2/bin/h2-*.jar ./
rm -r h2 h2*.zip

echo [Clean DB]
java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:./metabase.db -script metabase-db-clean.sql

echo [DB to sql file]
java -cp h2-*.jar org.h2.tools.Script -url jdbc:h2:./metabase.db -script metabase.db.sql

echo DONE
```

**metabase-db-clean.sql**:
```
SET DB_CLOSE_DELAY -1;
DELETE FROM "PUBLIC"."TASK_HISTORY";
DELETE FROM "PUBLIC"."ACTIVITY" WHERE "TOPIC" != 'install';
DELETE FROM "PUBLIC"."QUERY_EXECUTION";
```

3. After it I commit metabase.db.sql to the repo

4. When I need to up metabase from docker I just create database from sql like this:

**Dockerfile** (`docker build . -t local/metabase`)
```
FROM metabase/metabase:v0.34.1

# H2_VERSION is related to metabase version!
# In case of update Metabase version and get the error "NonTransientError: Unable to read the page at position”
# increase or decrease H2 version.
ARG H2_VERSION=2019-03-13

RUN mkdir -p /data
ADD metabase.db.sql /data
RUN cd /data \
  && wget https://h2database.com/h2-$H2_VERSION.zip \
  && unzip h2-$H2_VERSION.zip \
  && cp h2/bin/h2-*.jar ./ \
  && rm -r h2 h2*.zip \
  && java -cp h2*.jar org.h2.tools.RunScript -url jdbc:h2:./metabase.db -script metabase.db.sql

```
**docker-compose.yml**:
```
version: '3'
services:
  metabase:
    image: local/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /data/metabase.db
```
It works perfect :)

**Comment by smee** [comment]
@anki-code Could you please add the SQL script `metabase.db.sql` you reference in the script to your answer? Thanks!

**Comment by anki-code** [comment]
@smee The `metabase.db.sql` file is the result of `metabase-db-to-sql.sh`.

In short:
1. First of all you have metabase DB file like `metabase.db.mv.db`
2. You place this file along with `metabase-db-to-sql.sh` as described above and run sh
3. As result `metabase.db.sql` will be created
4. You can commit `metabase.db.sql` to the repo

Feel free to make the repo for this solution. I'll support to make more detailed readme.

**Comment by smee** [comment]
@anki-code Sorry, my bad. I should have read you comment more carefully. I will test it and report back.

**Comment by letientai299** [comment]
> Since a few versions ago, we have this functionality in the enterprise version: 
> https://www.metabase.com/docs/latest/enterprise-guide/serialization
@sbelak, any plan to make it available for OSS version?

**Comment by sbelak** [comment]
@letientai299 we're not sure yet where we want to take this.

**Comment by ywarnier** [comment]
Hi, just my 2 cents here.
I didn't manage to make @anki-code 's solution work, not sure why (metabase would just not restart)
Having installed my first configured Metabase with H2, I migrated to MySQL (there's a page in the official documentation about that - watch out for the index length error if you're on Debian/Ubuntu (i.e. with MariaDB 10.1.something) - you need to modify your DB config as follows and restart your db server *before* being able to migrate:
```
innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda
```

I then proceeded with @ijgonzalez-stratio 's solution to dump a few tables.

This is the command I used:
```mysqldump -u metabase -p --no-create-info --complete-insert --insert-ignore -- metabase report_card report_dashboard report_dashboardcard collection metabase_fieldvalues metabase_field metabase_table metabase_database > /tmp/tables.sql
```
Next, I send that file to the new server where I have a freshly installed Metabase instance (with no database configured to analyze juste yet, but installed using a MySQL database instead of H2), I stop Metabase and import the file into the existing Metabase database.
I then update the records in the metabase_database table manually (to point somewhere else, if this is a remote DB).

Finally, I restart Metabase and... voilà!

This all worked very well for me (although it was quite time consuming to find the right procedure, hence the share).

**Comment by anki-code** [comment]
@smee @ywarnier I've made docker file that saves/restores the database to/from SQL-file automatically - [metabase-sql-wrapper](https://github.com/anki-code/metabase-sql-wrapper) 🎉

**Comment by luthfihariz** [comment]
Facing the same issue, and decided to create a script that took advantage of Metabase REST API. Anyone feel free to use and improve it https://github.com/itmi-id/metabase-migration

**Comment by camsaul** [comment]
This conversation should be moved to https://discourse.metabase.com -- the GH issue tracker is for issues/bugs rather than question/answer threads

**Comment by Yambr** [comment]
Hi ! you can use my tool https://github.com/Yambr/metabase-ci-tool

* desktop app (configure and manual) and console (for ci/cd)
* create and update collections/cards/dashboards

nodejs (electron +vue)

Open for any MR!)
