### ISSUE TITLE
Embed to PHP Assert failed: (map? token-params)

### ISSUE THREAD

**Issue by kstan79** [metabase/metabase#6487]
I'm try to embed metabase into php application using a few reference, example:
[here](https://github.com/cyberhorse/metabase-php).

It seems connected but have error, as below 
<img width="1089" alt="screen shot 2017-11-29 at 1 28 47 am" src="https://user-images.githubusercontent.com/1889979/33334482-f57e05b0-d4a4-11e7-8e77-c4fd1ef6271f.png">

While inspect the network  it show error Assert failed: (map? token-params). I'm not use map by the way

**Comment by camsaul** [comment]
It might be a good idea to ask on https://github.com/cyberhorse/metabase-php/issues

**Comment by camsaul** [comment]
Either way it sounds like you're not passing a Parma you need to pass. Even if it's just an empty map

**Comment by elton182** [comment]
Hi @kstan79, I've got it working by doing this
```
$token = (new Builder())
        ->set('resource', [
            'dashboard' => 3
        ])
        ->set('params', [
            'param' => ''
        ])
        ->sign($signer, $metabaseSecretKey)
        ->getToken();
```

**Comment by kstan79** [comment]
ok, will try this
tq

**Comment by mansuryan** [comment]
Hi @kstan79. have You already fixed this problem or not yet?

**Comment by mansuryan** [comment]
Same issue here. Any workaround?

**Comment by LPTT** [comment]
had the same issue, @elton182 solution worked for me. Just set an empty param within params.

**Comment by dhbensmail** [comment]
When serialized to json, we need to have {} (like the Node.js example) , so casting to an object solve the issue (object)[]

**Comment by flamber** [comment]
Check this comment for how PHP handles arrays https://github.com/metabase/metabase/issues/11101#issuecomment-540147397
There's an issue open on the embed repo https://github.com/metabase/embedding-reference-apps/issues/12

**Comment by flamber** [comment]
Closing, since https://github.com/metabase/embedding-reference-apps has been updated.

**Comment by metalocator** [comment]
It's been a while, and the above by @elton182 used to work well for us, but now this was the solution:

` $token = (new \Lcobucci\JWT\Builder())
            ->set('resource', ['dashboard' => $dashboard_id])
            ->set('params', [
                'date_filter' => 'past30days'
            ])
            ->set('params', (object)[])
            ->sign($signer, $metabaseSecretKey)
            ->getToken();`

Notice the empty params needs to be an array cast to an object.

**Comment by horizontechcomhk-fai** [comment]
> When serialized to json, we need to have {} (like the Node.js example) , so casting to an object solve the issue (object)[]

it works for me too. thanks
