### ISSUE TITLE
Elastic Beanstalk launch url does not work in any region other than us-east1

### ISSUE THREAD

**Issue by sunshineo** [metabase/metabase#6490]
![region](https://user-images.githubusercontent.com/1072766/33338980-9768d98c-d42c-11e7-9dbd-a1e35d3107af.jpg)

**Comment by dolly-bi** [comment]
The easy workaround is to download the metabase install zip directly to your machine and then instead of copy and pasting the launch url upload the zip file. We're running metabase in the us-west-2 region.

**Comment by flamber** [comment]
Duplicate of #1336
