### ISSUE TITLE
Website Troubleshooting Guide Links All 404

### ISSUE THREAD

**Issue by hal58th** [metabase/metabase#6491]
For the website: [https://www.metabase.com/troubleshooting/](https://www.metabase.com/troubleshooting/) none of the links in the guide work and respond with a 404 error.

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: troubleshooting/loggingin
    RequestId: CBDC25445AEB6BB2
    HostId: ZONB/L+cLD3nBdYVrbxsFXWDqpmN5dqXe1NZvJOQ+X+BK0I6xWz9I0hcv4KmOzK09MJrmZ6Kh/4=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

**Comment by chris-griffin** [comment]
I think the website was down momentarily. Seems ok now

**Comment by kdoh** [comment]
Yup @chris-griffin is right. We had a bit of a glitch there but should be back to our regularly scheduled programming now. Thanks for reporting it and let us know if you see anything else that seems out of place.

**Comment by hal58th** [comment]
[https://www.metabase.com/troubleshooting/loggingin](https://www.metabase.com/troubleshooting/loggingin) and the rest of the links are still responding with 404.

**Comment by hal58th** [comment]
@chris-griffin Did you try any of the links on the webpage? They still don't work.

https://www.metabase.com/troubleshooting/docker
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: troubleshooting/docker
    RequestId: D2AEB6AEDE32FCFC
    HostId: SZp/05GpG77Ol+QJzgJF5rgmCsAMy/e5tQbnEqPHTqJd9ZwBndiqW6MBSNM6jSORK3xM5DLO1fY=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

**Comment by chris-griffin** [comment]
@hal58th nope I had come to report the entire website being down, and stumbled upon your issue. Looks like the same content is available here FWIW:

https://metabase.com/docs/latest/troubleshooting-guide/index.html
https://metabase.com/docs/latest/troubleshooting-guide/loggingin.html
https://metabase.com/docs/latest/troubleshooting-guide/docker.html

**Comment by camsaul** [comment]
Oh geez I must have broke something else trying to release yesterday. I'll take a look at this

**Comment by camsaul** [comment]
This is the link on the main page: https://www.metabase.com/docs/latest/troubleshooting-guide/index.html

If you go to the troubleshooting guide from there the links work as expected.

**Comment by salsakran** [comment]
Bare links eg (`https://www.metabase.com/docs/latest/troubleshooting-guide/`) work now.

It was an issue where the jekyll front matter for the guide pages hadn't been updated for the move off github pages.
