### ISSUE TITLE
Running count(*) on large tables in the background

### ISSUE THREAD

**Issue by scpike** [metabase/metabase#6492]
Database: Postgres on amazon RDS (9.3.14), size db.m3.xlarge

We have a few large-ish tables (10s of millions of rows). Whenever I look at long running queries being run against our database I commonly see the metabase user running queries like this:

```
-- Metabase
SELECT count(*) AS "count" FROM "public"."foo"
```

Also, it seems like metabase is running the queries separately on each of our web servers (there are two servers running right now, and each IP is running the exact same slow query). 

I'm checking on what's running with this query. Right now metabase has been running a count(*) for 7 minutes on one of our larger tables. 
```
SELECT pid, age(query_start, clock_timestamp()), usename, query, *
FROM pg_stat_activity
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%'
ORDER BY pid asc;
```

I've disabled all X-ray functionality (http://d.pr/i/mLntm4). Can I turn off whatever feature requires these aggregate counts or can you implement a timeout for large tables? 

*Edit*
The issue is not only related to `count(*)`. It looks like metabase is also trying to summarize each column, with queries like this:

```
-- Metabase
SELECT "public"."foo"."bar" AS "bar" FROM "public"."foo" LIMIT 10000
```
I appreciate the limit, but in this case it's `public.foo` is a database view that's very slow to query in this fashion and that's been running for 30 minutes.

**Comment by salsakran** [comment]
These are from our sync and analysis process. You can schedule/disable this as per https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis

**Comment by milgner** [comment]
Is it possible to disable analysis for individual tables? I'm seeing also problems with large tables on a read replica.

The logs look slightly differently, but I assume that the root cause is the same:

```
PSQLException:
 Message: ERROR: canceling statement due to conflict with recovery
  Detail: User query might have needed to see row versions that must be removed.
 SQLState: 40001
 Error Code: 0
02-08 08:01:07 [1mERROR generic-sql.query-processor[0m :: nil
02-08 08:01:07 [1mERROR db.metadata-queries[0m :: Error fetching table row count. Query returned:
 nil
02-08 08:01:07 [1mERROR sync.util[0m :: [31mUnable to determine row count for Table 123 'public.versions': class java.lang.NullPointerException
```
