### ISSUE TITLE
Acces Database without Permission

### ISSUE THREAD

**Issue by frodrigo** [metabase/metabase#6497]
If a question is build from one database, but if the user have access to the question but not the database, he can get the result anyway.

I was trying to run questions and dashboards with different user, each have access to different (but similar) database. But it fails.

**Comment by camsaul** [comment]
Hi @frodrigo, that's by design. We set up permissions that way so you can give someone access to a certain question (or set of questions) without giving them access to the database itself. If you don't want a user to have access to a question, you should revoke their access to it.
