### ISSUE TITLE
Timezone error in v0.27

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6499]
```
11-29 17:50:00 ERROR generic-sql.query-processor :: Failed to set timezone:
 SQLException:
 Message: Unknown or incorrect time zone: 'UTC'
 SQLState: HY000
 Error Code: 1298
```

**Comment by jornh** [comment]
It’s your database reporting it does not support the UTC timezone. Metabase just forwards this error. It sounds more like a database configuration error to me.

It would be helpful if you reported steps to reproduce the error including your environment.

Depending on your database does https://dba.stackexchange.com/questions/120945/how-do-i-resolve-this-error-error-1298-hy000-unknown-or-incorrect-time-zone help in your environment?

**Comment by jonatasfreitasv** [comment]
Right!! Thx a lot!
