### ISSUE TITLE
Bad function on add users in Question Alerts email on v0.27.

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6501]
When I add a user in alert question, add same user two times.

On Where do you want to send these alerts? (email) using registered user.

**Comment by mazameli** [comment]
Are you sure you are on version 0.27? I just tried to reproduce this on macOS Sierra on Chrome 62, Firefox 57, and Safari 11 with version 0.27 of Metabase but couldn't cause it to happen. 

Can you please provide more details about your setup and also double-check that you're on Metabase version 0.27? Thanks.

**Comment by jonatasfreitasv** [comment]
Is about my browser, sorry.
