### ISSUE TITLE
On download RAW data, columns selected dont respect

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6502]
On download csv or xlsx, selected columns not respected.

**Comment by mvrabel** [comment]
@jonatasfreitasv 
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

There are several issues addressing this
https://github.com/metabase/metabase/issues/3992
https://github.com/metabase/metabase/issues/5295
https://github.com/metabase/metabase/issues/5773

Please click the 👍  button on these issues to increase the importance of them

**Comment by jonatasfreitasv** [comment]
Thx a lot @mvrabel !!!
