### ISSUE TITLE
Bug: Goal Alerts not available when question is written as a Native query (eg. SQL)

### ISSUE THREAD

**Issue by jaredlt** [metabase/metabase#6508]
## Repeatable steps to reproduce the issue

- Write a `Native query` that is a count grouped by date
- eg. 

```
SELECT DATE(dtc), COUNT(id)
FROM orders
GROUP BY DATE(dtc)
```

 DATE(dtc) | COUNT(id)
----------- | -------------
2017-11-28 | 20
2017-11-29 | 18
2017-11-30 | 25

- Set Visualization to Line, Area or Bar Chart (any Visualization that allows you to set a goal)
- Set a Goal
- Save Question
- Click `Get alerts about this`

## What I expected to see

- Alert set up is based on a Goal Alert (`Alert me when the line…`)

## What I saw instead

- Alert set up is based on a Results alert (`This kind of alert is most useful when your saved question doesn’t usually return any results, but you want to know when it does.`)

## Notes

- Goal Alerts work as expected when using the `Custom` question builder

## My environment setup and versions

- Your browser and the version: Chrome 62, Firefox 57.0.1, Edge 40
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: 0.27.1 (via official Docker container)
- Metabase hosting environment: Docker on Ubuntu
- Metabase internal database: H2 (externally mounted)

**Comment by senior** [comment]
@attekei could you take a look at this? It looks like the UI isn't detecting the goal associated to native queries properly.

**Comment by attekei** [comment]
Addressed by #6581

**Comment by jaredlt** [comment]
@senior I think this bug fix is missing from the changelog https://github.com/metabase/metabase/releases
