### ISSUE TITLE
Feature request: Dashboards groups, like questions group.

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#6509]
Hi guys!!!!

First time, thx a lot for this tool, is very very nice!!!

Feature request: Dashboards groups, like questions group.

**Comment by mazameli** [comment]
We're thinking that we'll make it possible to save dashboards into the same collection folders as saved questions. Would that work for you?

**Comment by benjR** [comment]
I think that would be better than no group.

In my case we have split the questions by groups, and the dashboards use questions from different questions groups.

So it would be a first step but ultimately we would need to have different groups for dashboards.

**Comment by jonatasfreitasv** [comment]
Yes, dashboards per clients or squad, etc...

Have a lot of use case.

**Comment by lbalves** [comment]
@mazameli If the idea is to make general collections across metabase, it will work fine for our use case. The only "but" is that listing empty collections will be a noisy. Maybe list collections the same way as we do today if this has an item inside (dashboard or question), but list it smaller if it's empty.

**Comment by flamber** [comment]
Dashboards can now be grouped together in collections - and questions can be placed in collections too.
Read more about Collections, which got a big overhaul in version 0.30:
https://www.metabase.com/blog/0.30/index.html

**Comment by mazameli** [comment]
Closing since we implemented this last summer in 0.30 🌥 😎
