### ISSUE TITLE
Number abbreviates incorrectly when there is a multiplier

### ISSUE THREAD

**Issue by hakanensari** [metabase/metabase#6516]
The number card seems not to heed the "Multiply by a number" setting when abbreviating. See image below, where $924,171 turns into $92.4M, a fantastic boost in revenue. The underlying "Multiply by a number" is set to 0.01.

![bug](https://user-images.githubusercontent.com/31693/33483871-c4370cdc-d697-11e7-8e60-dd44bcccb53c.gif)

I'm on Safari 11 running on macOS 10.13. This is your latest Metabase 0.27.1 Docker image, hooked into Postgres.

**Comment by mazameli** [comment]
I believe you've encountered this issue: https://github.com/metabase/metabase/issues/5778

Closing as a duplicate.
