### ISSUE TITLE
Full time series charts in pulses

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6518]
One thing we've heard from users is the desire to have pulses render time series charts more faithfully rather than showing a sparkline. Here's what I'm thinking so far, with the current way we render them on the left (data blurred out to protect the innocent 😉 ):

![screen shot 2017-12-01 at 4 06 49 pm](https://user-images.githubusercontent.com/2223916/33508824-ad9e87c4-d6b1-11e7-88fe-083afc8d2872.png)

**The main differences are:**
- axes plus labels
- taller chart
- dotted horizontal lines at each y-axis tick
- thicker series line
- repositioned the current/previous values to clarify things
- made the title black instead of blue for aesthetic reasons; I think the whole card should be a link anyway.

**Optional add-on: multi-series time series in pulses**

Something else I considered was if we might be able to now render _multi_-series time series charts like the below, instead of rendering them as a table like we currently do. (The artboard on the right just shows how we'd handle longer table headings, like "This quarter.")

![screen shot 2017-12-01 at 3 57 45 pm](https://user-images.githubusercontent.com/2223916/33508763-5fbf40e8-d6b1-11e7-9012-c35e633c249a.png)

**Comment by rlotun** [comment]
This is mostly addressed in 42 - our current implementation is a bit different: we don’t show chart legends as tables with last and previous values but we addressed the other changes in this issue. We can create new issues for any other changes we want to make in this category of the product.
