### ISSUE TITLE
RedShift Driver

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#652]
We should figure out if we need to make any changes

**Comment by zachlatta** [comment]
:+1:

**Comment by RamaRoberts** [comment]
+1

**Comment by morgante** [comment]
+1

**Comment by cmcewen** [comment]
:+1:

**Comment by angusdavis2** [comment]
:+1:

**Comment by jrdi** [comment]
I don't know particular case on metabase but common postgresql drivers are working like a charm with redshift.

**Comment by xch91** [comment]
Has anyone ever stepped into any dark corners when directly replacing redshift for postgres XD

**Comment by razumau** [comment]
I'm not completely sure this is Redshift issue, but here’s what I get.
I have several schemas in my Redshift. When I connect using Metabase, I see most of the tables from various schemas. However,  when I build a question using GUI, I get “We couldn't understand your question” for any question. 
The probable reason is that names are not correct: first, underscores are stripped; second, schema name is dropped (I suppose it was done for the readability reasons). When I query using SQL and the full name (e.g., `salesforce._account`), I get correct results.

**Comment by agilliland** [comment]
@razumau , that sounds like it's due to #1306 which is already done and will be included in our next release which is coming up soon.

**Comment by camsaul** [comment]
Implemented by #1584

**Comment by salsakran** [comment]
Hey @zachlatta @RamaRoberts @morgante @cmcewen @angusdavis2 @jrdi @xch91

Just a heads up that this is live in our newest version (0.13). Would really appreciate you giving it a whirl and seeing if it works with your database.

**Comment by jrdi** [comment]
Hi,

I am just trying it again and I saw the following error:

* Seems row_count is to much for some of my tables
````
Unable to update row_count for '**obfuscated table name**': Numeric value out of range: "3203137313"; SQL statement:
UPDATE "METABASE_TABLE" SET "ROWS" = ?, "UPDATED_AT" = ? WHERE ("METABASE_TABLE"."ID" = ?) [22003-190]
````

**Comment by agilliland** [comment]
Thanks for reporting that @jrdi, just filed it as a new issue here ... https://github.com/metabase/metabase/issues/1634
