### ISSUE TITLE
Metabase does not show emojis

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#6522]
Metabase version: 0.27.1

I have table in mysql that contains `Emojis` like 🙄  . It has been stored in `MySQL` correctly and when I query it shows the desired result:
```
mysql> select * from schars;
+----+------+
| id | data |
+----+------+
|  1 | 🙄     |
+----+------+
1 rows in set (0.00 sec)
```

But in `Metabase` it is shown by `?`. Isn't there a way to set collation on database to show these values? Is this a bug?

**Comment by jornh** [comment]
Does https://www.google.com/search?q=mysql+jdbc+collation in combination with that I believe you can configure “additional JDBC properties” for Mysql just as you can for Postgres as shown in https://stackoverflow.com/questions/42239533/heroku-fail-to-connect-to-database-externaly-using-metabase help resolve you need? 

(Sorry about the obscure description above - I don’t have acces to a Metabase instance to get a better picture right now)

**Comment by alirezastack** [comment]
I'm sorry, didn't get exactly how to use `collation` in the `JDBC connection`. If it was possible please shed some light on the subject more.

**Comment by jornh** [comment]
Sorry about being a bit vague 🙁 up there in https://github.com/metabase/metabase/issues/6522#issuecomment-349096243 

I'm not using MySQL with Metabase myself (and just another user here). So I was just pointing to the fact that it seemed as more of a MySQL related issue than an actual Metabase issue/limitation - as long as Metabase has support for setting the collation via JDBC connection string options. Which it does according the screenshot below.

The MySQL + JDBC related remaining problem should then something I think (hope!) you are be able to investigate on e.g. StackOverflow. 

Hope that clarifies - and you are able to resolve from here. I'm sure other MySQL + Metabase users here might benefit from a pointer the solution if you get to it.

![image](https://user-images.githubusercontent.com/766423/33620464-305af736-d9e8-11e7-874e-eed12c4aab31.png)
