### ISSUE TITLE
URL fields not displaying at all

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#6525]
- Your browser and the version: Chrome 62
- Your operating system: OS X High Sierra
- Your databases: Redshift
- Metabase version: 0.27.1
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
Populate the database with a field that has a URL:
![image](https://user-images.githubusercontent.com/1711649/33609647-b4b1c24e-d9a7-11e7-9dfa-faff7ad0dfc1.png)

Then in Metabase I flag that field as URL
![image](https://user-images.githubusercontent.com/1711649/33609465-f9b063c4-d9a6-11e7-83ef-9063d6624971.png)

Then in the question, the data is not showing at all :(
![image](https://user-images.githubusercontent.com/1711649/33609495-1462270c-d9a7-11e7-9918-0039dfcd6bb8.png)

tried to flag the field as "no special type", nothing happens

**Comment by salsakran** [comment]
What is the underlying type? varchar? 

Also, at the risk of asking the obvious, are you sure those rows have non-null values for that field?

**Comment by paoliniluis** [comment]
@salsakran varchar(512).
If I query through a client directly to the database it shows the data :(

thanks

**Comment by paoliniluis** [comment]
@salsakran the field started appearing today in the morning... weird issue. I'm closing this
