### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#653]
The user should be able to export a backup of the metabase database to a file that can be saved or used to migrate to a new database.

**Comment by fbstj** [comment]
+1

**Comment by phalgun** [comment]
+1

**Comment by camsaul** [comment]
@agilliland @salsakran  if there are no objections I'm going to close this as won't fix. Per discussion decided to remove it from #1748

**Comment by MartinArens** [comment]
+1
