### ISSUE TITLE
Parse Driver

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#654]

**Comment by arjun-ram** [comment]
+1

**Comment by arjun-ram** [comment]
Any plans to support this soon?

**Comment by tlrobinson** [comment]
FYI, Facebook is shutting down Parse: http://blog.parse.com/announcements/moving-on/

**Comment by agilliland** [comment]
I'm going to go ahead and close this issue given that Parse is being shut down and there is very little reason to move forward with a driver for it.
