### ISSUE TITLE
v0.27.1 regression: “Saved! Add this to a dashboard” even when the card is already placed on a dashboard

### ISSUE THREAD

**Issue by jornh** [metabase/metabase#6541]
- Your browser and the version: Chrome 62.0.3202.94 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases: just the internal demo DB in H2
- Metabase version: 0.27.1
- Metabase hosting environment: Windows 10 Metabase.jar
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue*

Se description in [discussion](http://discourse.metabase.com/t/saved-add-this-to-a-dashboard-even-when-the-card-is-already-placed-on-a-dashboard/2524)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by alexanderad** [comment]
I'm sorry if this is out of question of this issue and requires a separate request to be created, but do you think we can ask for this question's answer to be remembered? 

I'm working on a query and save it from time to time. It keeps asking me every time if I want to add it to a dashboard, even though I don't even plan to do that (I'm happy with the question to be all alone... :-)

**Comment by mazameli** [comment]
@alexanderad yes, what you're describing is the core problem. The correct behavior is that a user should only be asked if they want to add it to a dashboard _the first time the question is saved_. It should not prompt the user every time an edit is saved, regardless of whether or not the question is on a dashboard.
