### ISSUE TITLE
Adding remote MySQL Databases through SSH times out.

### ISSUE THREAD

**Issue by maximedegreve** [metabase/metabase#6544]
**Setup**
- Your operating system: High Sierra
- Your databases: MySQL
- Metabase version: 0.27.1.0
- Metabase hosting environment: MacApp

**Repeatable steps to reproduce the issue**
1) Create a Mysql database
2) Fill in all details including the SSH ones
3) Click save
4) Times out

**Questions**
Where can I find raw logs for this error?

**Notes**
The same details work fine in Sequel Pro.

**Screenshots**
<img width="465" alt="screen shot 2017-12-07 at 09 28 41" src="https://user-images.githubusercontent.com/980622/33707971-12f5d900-db31-11e7-990d-265e9b1f5756.png">

**Comment by jornh** [comment]
Related: https://github.com/metabase/metabase/issues/6851?

There’s a proposed PR referenced in https://github.com/metabase/metabase/issues/6851#ref-pullrequest-297904390 you can try out.

**Comment by tlrobinson** [comment]
This should be fixed #6970 so I'm going to close it but let us know if it's not.
