### ISSUE TITLE
Area graphs flow over x axis labels with custom y-axis range

### ISSUE THREAD

**Issue by vegarsti** [metabase/metabase#6547]
First of all, thanks for a wonderful product. It has helped so much, both for the non-developers and the developers, and communication between.

In area graphs, the area flows over the labels on the x-axis when the view on the y-axis is smaller than the actual area.

I'm not sure this is a feature or a bug, but I find it hard to see the x-axis labels in these cases.

In the example below, in my mind, the area should stop when crossing the x-axis line at 10.5, where the y-axis view stops, but it does not:
<img width="1399" alt="screen shot 2017-12-08 at 16 55 18" src="https://user-images.githubusercontent.com/5699893/33773589-b8b293b2-dc38-11e7-9167-d4fcd90f9cc3.png">

**Comment by paco3346** [comment]
Having the same issue with the bar graph on 0.29.3

**Comment by wm9947** [comment]
still have issue on v0.31.2

**Comment by paulrosenzweig** [comment]
Fixed by #10396
