### ISSUE TITLE
For charts having more rows should have a scroll bar

### ISSUE THREAD

**Issue by seeramzan** [metabase/metabase#6548]
Hi,

I am really impressed with Metabase, We were working on PowerBi but now switched to Metabase. 

While using any chart like bar chart, if we have more data rows , it shows remaining data rows as "others". Why not to add a scrool bar inside the chart to see all records other than showing "others" because if we are representing the dashboard to a manager and they want to see data for all they cannot see.

**Comment by salsakran** [comment]
Thanks for the kind words!

@mazameli @kdoh any opinions on scroll bars? ;)

**Comment by mazameli** [comment]
First, I'll say that I agree that I hate how we're lumping everything that doesn't fit in the available space on a row chart into the "other" bucket; it often defeats the purpose of the chart. I think it needs to be sorted by default from most to fewest results, and then should either be scrollable or I guess paginate-able. Like, we let tables scroll; why wouldn't we do the same to be able to see all the rows in a chart like this?

**Comment by flamber** [comment]
Closing in favor of #11325

**Comment by Hritik14** [comment]
@flamber Can we reopen this ?
https://github.com/metabase/metabase/issues/11325 talks about breakout series with many breakouts and this one calls for a scroll bar when bar chart is in the dashboard
