### ISSUE TITLE
Certain Aggregate "Views" Hidden When Related Fields Available

### ISSUE THREAD

**Issue by asyncopation** [metabase/metabase#6549]
Your browser and the version: Chrome 62.0.3202.94
Your operating system: Ubuntu
Your databases: Redshift
Metabase version: 0.26.2
Metabase hosting environment: Docker
Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*

**Summary**
When a table has no fields with Metabase type "Number", you are presented with limited aggregate "Views".  The issue is when a related table contains fields you would use for aggregates, it is impossible to select these fields since the option is hidden.

**Example**
Suppose we have 2 tables: `table1` and `table2`.
These are related such that `table1.t2_id = table2.id`.
`table1` contains no fields with Metabase type "Number".  However, `table2` contains several.

We go to create a new question using the builder, and select `table1` as the data source.  We want to use an aggregate, let's say "Sum of" on one of the numeric fields in related `table2`.  However, the "Sum of" option is not present under the views!

**Workaround**
If we set any field in `table1` to "Number" we now have access to the "Sum of" aggregate view, and we can select our intended field in related `table2`.

**Comment by flamber** [comment]
Closing in favor of #12248
