### ISSUE TITLE
stuck at 0.25.1 - metabase won't update

### ISSUE THREAD

**Issue by eschultze** [metabase/metabase#6557]
Chrome 62 - MySQL with 3 tables and almost 2 million records - Metabase 0.25.1 running on Ubuntu 16.04.3 LTS

I've created a little shell script to automatically run metabase at startup:
```
#!/bin/bash

export MB_JETTY_SSL="true"
export MB_JETTY_SSL_Port="8443"
export MB_JETTY_SSL_Keystore="/home/myuser/keystore.test"
export MB_JETTY_SSL_Keystore_Password="mypassword"
java -jar metabase.jar
```
My "check for updates" settings are enabled as you can see below
![image](https://user-images.githubusercontent.com/12034548/33844516-a57fea3c-de87-11e7-8190-7385a8a454ce.png).

My issue is that either running metabase with the shell script above or manually, metabase itself wont update automatically. I'm stuck at 0.25.1 and I have no idea how to solve this. I'm not sure if this is a bug but I'have done some research and could not find any other situation that looks like mine.

**Comment by camsaul** [comment]
Hi @eschultze, Metabase doesn't update automatically. See https://metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase

**Comment by eschultze** [comment]
Hi @camsaul. I'm sorry about that. In my mind I had the idea that whilst starting metabase.jar it would automatically download the newest metabase version. Also, I'm not very familiar with java so I thought that overwriting metabase.jar would make my lose all my dashboards and configuration. Thanks for the awesome work.
