### ISSUE TITLE
Allow multiple series on a line chart

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#656]

**Comment by spectr** [comment]
+1

**Comment by jpadif** [comment]
+1 This would be a super great feature to have.

**Comment by dsager** [comment]
+1

**Comment by kamidar** [comment]
+1

**Comment by plehatron** [comment]
+1

**Comment by roblafave** [comment]
+1

**Comment by phalgun** [comment]
+1

**Comment by derek-schultz** [comment]
+1

**Comment by styts** [comment]
+1

**Comment by apaganobeleno** [comment]
+1

**Comment by snarfed** [comment]
+1!

**Comment by justnom** [comment]
Is anyone working on this - or can I safely start hacking at this?

**Comment by salsakran** [comment]
@justnom it's in our queue but no one on the core team is tackling it. 

Just to set expectations, we're generally **very** careful about changes to anything that a user sees.  We have two designers on the project, @kdoh and @mazameli, who run the process that encompasses user interviews, interaction and visual design who have final say on the design. We'd love to see what you come up with, but we can't promise to merge it. 

We're currently writing up a description of the process we'll use for contributions that touch the front end or are contentious and it'll be in our developer guide shortly.

**Comment by justnom** [comment]
@salsakran 
No problem! :)

I'll hold fire on that for now - and just start getting to grips with the code base whilst your team draws up some more concrete contributions guidelines.

**Comment by cballou** [comment]
+1, definitely the biggest feature I'd like to see at the moment.

**Comment by brenol** [comment]
:+1:

**Comment by bobey** [comment]
:+1: for this!

**Comment by jubianchi** [comment]
:+1:

**Comment by bernardosrulzon** [comment]
+1! It's the only reason why we're not using metabase for company-wide online dashboards.

**Comment by draven72** [comment]
+1

**Comment by maggit** [comment]
+1

**Comment by bnetter** [comment]
Most of the time, I'm generating charts with dates on the x-axis and would love to be able to see two different set of data on the same chart to relate them to each others. Here's an example.

![Cumulative chart](http://www.presentation-process.com/wp-content/uploads/performance-cumulative-chart-combined.jpg)

It would also solve the problem we all seem to have with bar charts (#1449).

**Comment by dsager** [comment]
There's actually a way to render multiple series in a chart (quite limited though):

- Add a new question
- Open the SQL editor
- Enter this query:
```sql
SELECT generate_series, random() "foo", random() "bar"
FROM generate_series(1, 10, 1);
```
- Hit 'run query'
- Select `line` as visualization

The result looks like this:
![screenshot from 2016-01-08 13 47 42](https://cloud.githubusercontent.com/assets/1056502/12198265/9d5f1826-b60e-11e5-86e9-269120a2f93b.png)

Maybe this helps until multi-series data get properly supported...

**Comment by robinfrick** [comment]
@dsager the problem with this solution for me is that the values are added like on a stacked bar chart. They can never cross another as the position of the upper series is the sum of the lower and the upper series values.

Another problem why the multiple lines in a line chart are less than ideal is that they are missing any kind of indication which line represents which series. So a legend or displaying the series name in the tooltip.

So ya, from my point of view it is too limited :-(

**Comment by suhastech** [comment]
@robinfrick We at @signeasy are using metabase. 

We couldn't wait for the official implementation. So, we have our own fork which supports annotations.

Feel free to use it:
https://github.com/signeasy/metabase/releases

We also have a pull request https://github.com/metabase/metabase/pull/1508 but that might take a while to get accepted.

**Comment by mhjb** [comment]
Really keen for non-stacked line charts

**Comment by kdoh** [comment]
Hey all. Thanks so much for chiming in and requesting this feature. We just released Metabase 0.15.0 which includes multiple series support in addition to a bunch of other things. Let us know what you think! 

(here's your obligatory leap day pun link)
http://www.metabase.com/blog/a-leap-forward

**Comment by ClementineVioux** [comment]
+1

**Comment by mazameli** [comment]
@ClementineVioux this feature was merged into Metabase a long time ago. Does your +1 comment indicate that there's still something missing for you regarding this feature?

**Comment by ClementineVioux** [comment]
Hi There,

Thanks for the message that is great.
Actually I was just manifesting my approval ☺
But while I am writing to you I have 2 additional questions

-          Can I do a bar graph like the screenshot attached?

-          Can I do a scatter graph?

Thanks and apologies if it is not the right channel to ask these questions.

Clementine,

[cid:image002.jpg@01D24BBA.654CD4E0]

**Comment by mazameli** [comment]
Ah, well, happy to know you approve! Typically, the convention of writing "+1" or responding to an issue with a thumbs-up means you're adding your vote for a particular feature/fix. As for your questions:

> Can I do a bar graph like the screenshot attached?

Seems like your screenshot isn't rendering, maybe because you replied via email?

> Can I do a scatter graph?

Yes, Metabase [v0.20 introduced scatterplots](http://www.metabase.com/blog/Metabase-0.20) and bubble charts as well as progress bars.

Hope that helps!
