### ISSUE TITLE
Minimum / Recommended Hardware Requirement

### ISSUE THREAD

**Issue by budakmaran** [metabase/metabase#6564]
OS: Centos 7

Hi,

May i know what is minimum and recommended hardware requirement to running metabase smoothly ?

Thanks

**Comment by salsakran** [comment]
It depends entirely on how many users you expect to serve concurrently and how large your results sets are.

We have some folks with very small installations that work ok on Heroku hobby dynos with 512M of memory. We run most of our internal instances on AWS t2.smalls.

**Comment by elmentdave** [comment]
can u help me

**Comment by mazameli** [comment]
Closing this as an answered question.
