### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to move from h2 to mysql/postgres

### ISSUE THREAD

**Issue by Leen15** [metabase/metabase#6574]
Hi guys, I'm trying to move from h2 to a production database (mysql or postgres).
I tried both, but I receive an error from the log.

Can you help me?

> 13/12/2017 11:53:4612-13 11:53:46 [1mINFO metabase.util[0m :: Loading Metabase...
 13/12/2017 11:53:59com.amazon.redshift.core.jdbc41.PGJDBC41DriverImpl
 13/12/2017 11:54:0112-13 11:54:01 [1mINFO util.encryption[0m :: DB details encryption is DISABLED for this Metabase instance. 🔓 
13/12/2017 11:54:01See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
13/12/2017 11:54:0712-13 11:54:07 [1mINFO metabase.db[0m :: [36mVerifying postgres Database Connection ...[0m
13/12/2017 11:54:0712-13 11:54:07 [1mINFO metabase.db[0m :: Verify Database Connection ...  ✅
13/12/2017 11:54:0712-13 11:54:07 [1mINFO metabase.db[0m :: Running Database Migrations...
13/12/2017 11:54:0712-13 11:54:07 [1mINFO metabase.db[0m :: Setting up Liquibase...
13/12/2017 11:54:0812-13 11:54:08 [1mINFO metabase.db[0m :: Liquibase is ready.
13/12/2017 11:54:0812-13 11:54:08 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
13/12/2017 11:54:1112-13 11:54:11 [1mINFO metabase.db[0m :: Database Migrations Current ...  ✅
13/12/2017 11:54:11com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
13/12/2017 11:54:11[34mTemporarily disabling DB constraints...[0m
13/12/2017 11:54:11[32m[OK][0m
13/12/2017 11:54:14org.h2.jdbc.JdbcSQLException: General error: "java.lang.ArrayIndexOutOfBoundsException: 50" [50000-194]
13/12/2017 11:54:14	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
13/12/2017 11:54:14	at org.h2.message.DbException.get(DbException.java:168)
13/12/2017 11:54:14	at org.h2.message.DbException.convert(DbException.java:295)
13/12/2017 11:54:14	at org.h2.table.RegularTable.removeRow(RegularTable.java:409)
13/12/2017 11:54:14	at org.h2.store.PageStore.redo(PageStore.java:1581)
13/12/2017 11:54:14	at org.h2.store.PageStore.redoDelete(PageStore.java:1554)
13/12/2017 11:54:14	at org.h2.store.PageLog.recover(PageLog.java:346)
13/12/2017 11:54:14	at org.h2.store.PageStore.recover(PageStore.java:1407)
13/12/2017 11:54:14	at org.h2.store.PageStore.openExisting(PageStore.java:368)
13/12/2017 11:54:14	at org.h2.store.PageStore.open(PageStore.java:289)
13/12/2017 11:54:14	at org.h2.engine.Database.getPageStore(Database.java:2488)
13/12/2017 11:54:14	at org.h2.engine.Database.open(Database.java:697)
13/12/2017 11:54:14	at org.h2.engine.Database.openDatabase(Database.java:276)
13/12/2017 11:54:14	at org.h2.engine.Database.<init>(Database.java:270)
13/12/2017 11:54:14	at org.h2.engine.Engine.openSession(Engine.java:64)
13/12/2017 11:54:14	at org.h2.engine.Engine.openSession(Engine.java:176)
13/12/2017 11:54:14	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
13/12/2017 11:54:14	at org.h2.engine.Engine.createSession(Engine.java:137)
13/12/2017 11:54:14	at org.h2.engine.Engine.createSession(Engine.java:27)
13/12/2017 11:54:14	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
13/12/2017 11:54:14	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
13/12/2017 11:54:14	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
13/12/2017 11:54:14	at org.h2.Driver.connect(Driver.java:69)
13/12/2017 11:54:14	at java.sql.DriverManager.getConnection(DriverManager.java:664)
13/12/2017 11:54:14	at java.sql.DriverManager.getConnection(DriverManager.java:208)
13/12/2017 11:54:14	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:358)
13/12/2017 11:54:14	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:225)
13/12/2017 11:54:14	at metabase.cmd.load_from_h2$load_data_BANG_.invokeStatic(load_from_h2.clj:143)
13/12/2017 11:54:14	at metabase.cmd.load_from_h2$load_data_BANG_.invoke(load_from_h2.clj:142)
13/12/2017 11:54:14	at metabase.cmd.load_from_h2$load_from_h2_BANG_$fn__45552.invoke(load_from_h2.clj:217)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:740)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
13/12/2017 11:54:14	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
13/12/2017 11:54:14	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invokeStatic(load_from_h2.clj:214)
13/12/2017 11:54:14	at metabase.cmd.load_from_h2$load_from_h2_BANG_.invoke(load_from_h2.clj:207)
13/12/2017 11:54:14	at clojure.lang.Var.invoke(Var.java:379)
13/12/2017 11:54:14	at metabase.core$load_from_h2.invokeStatic(core.clj:217)
13/12/2017 11:54:14	at metabase.core$load_from_h2.invoke(core.clj:210)
13/12/2017 11:54:14	at metabase.core$load_from_h2.invokeStatic(core.clj:213)
13/12/2017 11:54:14	at metabase.core$load_from_h2.invoke(core.clj:210)
13/12/2017 11:54:14	at clojure.lang.AFn.applyToHelper(AFn.java:152)
13/12/2017 11:54:14	at clojure.lang.AFn.applyTo(AFn.java:144)
13/12/2017 11:54:14	at clojure.core$apply.invokeStatic(core.clj:646)
13/12/2017 11:54:14	at clojure.core$apply.invoke(core.clj:641)
13/12/2017 11:54:14	at metabase.core$run_cmd$fn__46484.invoke(core.clj:277)
13/12/2017 11:54:14	at metabase.core$run_cmd.invokeStatic(core.clj:277)
13/12/2017 11:54:14	at metabase.core$run_cmd.doInvoke(core.clj:276)
13/12/2017 11:54:14	at clojure.lang.RestFn.invoke(RestFn.java:410)
13/12/2017 11:54:14	at clojure.lang.AFn.applyToHelper(AFn.java:154)
13/12/2017 11:54:14	at clojure.lang.RestFn.applyTo(RestFn.java:132)
13/12/2017 11:54:14	at clojure.core$apply.invokeStatic(core.clj:648)
13/12/2017 11:54:14	at clojure.core$apply.invoke(core.clj:641)
13/12/2017 11:54:14	at metabase.core$_main.invokeStatic(core.clj:291)
13/12/2017 11:54:14	at metabase.core$_main.doInvoke(core.clj:287)
13/12/2017 11:54:14	at clojure.lang.RestFn.applyTo(RestFn.java:137)
13/12/2017 11:54:14	at metabase.core.main(Unknown Source)
13/12/2017 11:54:14Caused by: java.lang.ArrayIndexOutOfBoundsException: 50
13/12/2017 11:54:14	at org.h2.index.PageBtree.getRow(PageBtree.java:171)
13/12/2017 11:54:14	at org.h2.index.PageBtreeLeaf.remove(PageBtreeLeaf.java:231)
13/12/2017 11:54:14	at org.h2.index.PageBtreeNode.remove(PageBtreeNode.java:336)
13/12/2017 11:54:14	at org.h2.index.PageBtreeIndex.remove(PageBtreeIndex.java:245)
13/12/2017 11:54:14	at org.h2.table.RegularTable.removeRow(RegularTable.java:391)
13/12/2017 11:54:14	... 55 more
13/12/2017 11:54:14[31mCommand failed with exception: General error: "java.lang.ArrayIndexOutOfBoundsException: 50" [50000-194][0m

**Comment by salsakran** [comment]
How large is your h2 database and how much memory do you have? That error is coming from the embedded database we use (H2) and not from our code itself.

**Comment by Leen15** [comment]
Hi @salsakran , the db is 72mb.
We have a dedicated host with a xeon e3 and 32gb of ram so I think memory should not be a problem.

**Comment by Leen15** [comment]
Hi, I'm trying to use SQuirreL for move the h2 db to postgres/Mysql.
Can you please explain me how to proceed? 
I selected the "H2" driver, but when I open the DB the "public" schema is empty:
![image](https://user-images.githubusercontent.com/3629071/34523800-4200d2fe-f099-11e7-8678-8cdd680d4197.png)
Please someone can help me to migrate the db?

**Comment by Leen15** [comment]
I tried also with the h2 official app (http://www.h2database.com/html/quickstart.html) but again, still empty:
![image](https://user-images.githubusercontent.com/3629071/34523994-20ed0dd4-f09a-11e7-8024-707e8041b916.png)

**Comment by jornh** [comment]
@Leen15 try changing your connection string for H2 from `...\metabase.db.h2.db` to just `...\metabase.db` - tripped me up at first as well. And I'm able to commect with blank username/password combination.

**Comment by Leen15** [comment]
finally, I used these two commands:
` java -cp metabase.jar org.h2.tools.Recover`    
`java -cp metabase.jar org.h2.tools.Script -url jdbc:h2:./metabase.db`

for generare a useful SQL dump.

Then, I created a mysql db from a new installation of metabase and populate manually every table with what I found in the SQL dump.

I still have some issues with some formatting of strings, but most of functionalities seem to work.

it was been a pain and this took about 5 hours.

**Comment by jornh** [comment]
@Leen15 great you reported info back on what you ended up doing. :smile: 

Did this resolve your issue - or is there anything actionable for the Metabase team worth doing before this issue can be closed?

**Comment by Leen15** [comment]
It should useful for future users that the migration process works better with big db (not so much, we have 250 questions)

**Comment by salsakran** [comment]
closing since this was resolved over a year and a half ago and hasn't been reported since.
