### ISSUE TITLE
Horizontal Axes for metrics can get squished

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6576]
The fix we did for dates (and I think numbers) greatly improved the situation for squished x-axis labels, but with column charts, we can get the same behavior when the y-axis is effectively mapped to the x-axis. It would be great to have that same behaviour in this situation. See below for an example

![screen shot 2017-12-13 at 1 57 35 pm](https://user-images.githubusercontent.com/107439/33964552-a2e9f74a-e00d-11e7-9b94-e50550f3ccc8.png)

**Comment by salsakran** [comment]
related to #2935

**Comment by mazameli** [comment]
Fixed by #7103
