### ISSUE TITLE
MongoDB Connector for BI support

### ISSUE THREAD

**Issue by gusgustavo** [metabase/metabase#6584]
Hi, as Metabase still doesn't have support for nested queries in MongoDB (#4946, #4098), MongoDB have a Bi Connector (Mongosqld) that can potentially help, but trying to connect errors with `ssl is required when using cleartext authentication`:

>The MongoDB Connector for BI acts as a layer that passes queries and data between a mongod or mongos instance and your reporting tool. The MongoDB Connector for BI stores no data, and purely serves to bridge your MongoDB cluster with business intelligence tools.

https://docs.mongodb.com/bi-connector/master/

all the best,
gus

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by anhdn** [comment]
Hi, now can you connect to Mongo BI connector? I try but can not connect.

**Comment by paoliniluis** [comment]
we support nested queries now, so closing
