### ISSUE TITLE
Is it possible to retrieve query results via API for a Question or MBQL query?

### ISSUE THREAD

**Issue by grokify** [metabase/metabase#6586]
I'm using Metabase and I have a Question created in the Data Explorer I want to retrieve the results for. In the web UI, I can retrieve the data as JSON from the table view. Is it possible to retrieve this JSON data via the REST API? I've looked at the [documentation](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md) and tried a few endpoints with the parameters in the Data Explorer URL as ids, but I've been unsuccessful so far.

Also, is it possible to make a MBQL query via the REST API? The docs only have one mention of MBQL for an endpoint that doesn't look like a query:

`GET /api/tiles/:zoom/:x/:y/:lat-field-id/:lon-field-id/:lat-col-idx/:lon-col-idx/`

**Comment by jornh** [comment]
It helps knowing that a Question is called a card in the API.

I believe you are looking for https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicardcard-idqueryexport-format and possibly http://discourse.metabase.com/t/passing-parameters-to-the-api/2578

Going forward questions are better asked on http://discourse.metabase.com/ Metabase GitHub issues are for bugs and enhancement requests

**Comment by grokify** [comment]
Hi @jornh That was one of the APIs I tried but I wasn't sure what to use for `:card-id`. I tried both a numeric path parameter and a alphanumeric (base64 encoded?) parameter present in the Data Explorer URL but received 404 responses. How do you get the `:card-id` for a Question? I continue this question on Discourse if there's more to this.

**Comment by jornh** [comment]
Sorry, haven’t had hands on that part. From the docs I’d expect numeric. I’m sure if you ping alantygel on Discouse he knows how.

**Comment by grokify** [comment]
Thanks @jornh!

Numeric card ID is correct as is POST /api/card/:card-id/query/:export-format. I was using GET instead of POST which resulted in the 404. Found my error by using browser network inspection which showed the browser making a request to the same URL except for using a cookie to send the session id.
