### ISSUE TITLE
Problem docker Elastic Beanstalk metabase

### ISSUE THREAD

**Issue by dker92** [metabase/metabase#6589]
Hello ,

I have installed metabase on a Elastic Beanstalk with docker, but I encountered regular issues that I don't understand  that crash metabase.
I checked my log and I notice  that the instance " i-05bc91e7e43fe0900", was not able to signal back to the Beanstalk Service.

Error : 
Error signaling CloudFormation: [Errno 403] HTTP Error 403 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires>86399</X-Amz-Expires><Expires>2017-12-15T13:04:23Z</Expires><ServerTime>2017-12-15T15:50:20Z</ServerTime><RequestId>B0595B7E3231A6D3</RequestId><HostId>t9Uewp3PMHKDZIOpR25YLgYD72yaFJszLZCdgeT+QdMC8fTSjaoUc=</HostId></Error>
[2017-12-15T15:50:20.154Z] Wait Condition Signal expired.

 I checked the IAM Instance Profile of  my Beanstalk Environment and notice that it already has the required permissions so it is not a permission issue.
 I checked the logs and CloudWatch metrics of the instance and could not see any issue with there when the error occurred.
Another thing that I noticed is that the URL Expire time mentioned in the error code is different from the instance time : <Expires>2017-12-15T13:04:23Z</Expires><ServerTime>2017-12-15T15:50:20Z</ServerTime>, which makes me suspect that there is some misconfiguration in the instance's time.
Maybe there are some time adjustment to  do at my end?
 

- Your browser and the version:  Chrome 52.1
- Your operating system:OS X 10
- Your databases:  Postgres
- Metabase version: 0.27.0
- Metabase hosting environment: Elastic Beanstalk, Docker
- Metabase internal database: Postgres

**Comment by sharuzzaman** [comment]
are you using custom AMI?

**Comment by flamber** [comment]
This looks like permission problems on AWS - not something we can fix.
