### ISSUE TITLE
add the ability to mark a Field as nullable in schema info

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#659]
as a user I don't want to deal with NULL values if I don't have to.  It would be nice if a column is not allowed to have NULL values that we avoid presenting any options relating to NULL.

ex: filtering by "is null" or "is not null" should not be selectable if the Field can never be NULL.

**Comment by flamber** [comment]
Closing, since 0.37 changed filter options to "Is empty" and "Not empty"
