### ISSUE TITLE
Custom map not view in shared Dashboards

### ISSUE THREAD

**Issue by chenlingmin** [metabase/metabase#6593]
Hello 

I added custom Map, It's worked.
But not work in my shared Dashboard.

I found `GET api/geojson/a5bc9fba-6bc6-4bbf-6304-87b9ad5d5493` api unauthenticated
![image](https://user-images.githubusercontent.com/8233283/34145035-25e0555c-e4cf-11e7-9a5d-e6d0ef44ef24.png)

**Comment by tewald** [comment]
It's a permission issue.
The /geojson route is auth protected.
I've made it work by cloning the repository and changing the line:
`(context "/geojson"         [] (+auth geojson/routes))`
to
`(context "/geojson"         [] geojson/routes)`
on the **metabase/api/routes.clj** file.

**Comment by salsakran** [comment]
Hmm. Are there any security implications to allowing custom geojson files to be downloaded from an instance without authing? Obviously, if you're using them in a public dashboard, you need to be able to get to them without authenticating, but we should probably only allow GETs and not other HTTP verbs.

**Comment by flamber** [comment]
This issue is most likely a duplicate of #5338, despite referencing embedded, since both issues are failing to get the map from the same end point `/api/geojson/:UUID`

**Comment by MarcGJA** [comment]
Metabase v0.31.2
AWS EBS 
JWT embedding w/maps

So how can I go about implementing @tewald's solution on a working EBS Metabase instance?  

The thought of editing clj code, learning how to use Docker (I haven't a clue), plus dealing with AWS's eccentricities (sans MySQL option <a href="https://github.com/metabase/metabase/issues/9021">#9021</a>) is somewhat intimidating but I'm going to have to do something soon.  

Embed custom geojson maps (totally under my control, I designed them from scratch) are a <b>must-have</b> even with "to-do" list items like <i>binning miss-categorizations</i> (<a href="https://github.com/metabase/metabase/issues/7486">#7486</a>, <a href="https://github.com/metabase/metabase/issues/9208">#9208</a>), <i>floating maps with peek-a-boo labels</i> (<a href="https://github.com/metabase/metabase/issues/7638">#7638</a>), and <i>single-color shading</i> (<a href="https://github.com/metabase/metabase/issues/9682">#9682</a>).  

Something is better than nothing which is what we've got right now (<a href="https://github.com/metabase/metabase/issues/5338">#5338</a>, <a href="https://github.com/metabase/metabase/issues/9193">#9193</a><i>closed as dup</i>).

**Comment by MarcGJA** [comment]
Metabase v0.31.2
AWS EBS 
JWT embedding w/maps

So how can I go about implementing @tewald's solution on a working EBS Metabase instance?  

The thought of editing clj code, learning how to use Docker <i>(I haven't a clue)</i>, plus dealing with AWS's eccentricities <i>(sans MySQL option <a href="https://github.com/metabase/metabase/issues/9021">#9021</a>)</i> is somewhat intimidating but I'm going to have to do something soon.  

Embed custom geojson maps (totally under my control, I designed them from scratch) are a <b>must-have</b> even with "to-do" list items like <i><b>binning miss-categorizations</b></i> (<a href="https://github.com/metabase/metabase/issues/7486">#7486</a>, <a href="https://github.com/metabase/metabase/issues/9208">#9208</a>), <i><b>floating maps with peek-a-boo labels</b></i> (<a href="https://github.com/metabase/metabase/issues/7638">#7638</a>), and <i><b>single-color shading</b></i> (<a href="https://github.com/metabase/metabase/issues/9682">#9682</a>).  

Something is better than nothing which is what we've got right now (<a href="https://github.com/metabase/metabase/issues/5338">#5338</a>, <a href="https://github.com/metabase/metabase/issues/9193">#9193</a><i> closed as dup</i>).

**Comment by MarcGJA** [comment]
Metabase v0.31.2
AWS EBS 
JWT embedding w/maps

So how can I go about implementing @tewald's solution on a working EBS Metabase instance?  

The thought of editing clj code, learning how to use Docker <i>(I haven't a clue)</i>, plus dealing with AWS's eccentricities <i>(sans MySQL option <a href="https://github.com/metabase/metabase/issues/9021">#9021</a>)</i> is somewhat intimidating but I'm going to have to do something soon.  

Embed custom geojson maps <i>(totally under my control, I designed them from scratch)</i> are a <b>must-have</b> even with "to-do" list items like <i><b>binning miss-categorizations</b></i> (<a href="https://github.com/metabase/metabase/issues/7486">#7486</a>, <a href="https://github.com/metabase/metabase/issues/9208">#9208</a>), <i><b>floating maps with peek-a-boo labels</b></i> (<a href="https://github.com/metabase/metabase/issues/7638">#7638</a>), and <i><b>single-color shading</b></i> (<a href="https://github.com/metabase/metabase/issues/9682">#9682</a>).  

Something is better than nothing which is what we've got right now (<a href="https://github.com/metabase/metabase/issues/5338">#5338</a>, <a href="https://github.com/metabase/metabase/issues/9193">#9193</a><i> closed as dup</i>).

**Comment by camsaul** [comment]
Duplicate of #5338
