### ISSUE TITLE
Obtaining a session token from /api/session/google_auth requires an id_token, rather than an access_token

### ISSUE THREAD

**Issue by ernesttan** [metabase/metabase#6594]
When getting a session token to access the REST APIs via Google authentication, the "token" parameter required is an id_token, rather than an access_token. I'm guessing that this comes from https://github.com/metabase/metabase/blob/master/src/metabase/api/session.clj - line 174.

![image](https://user-images.githubusercontent.com/34678145/34154848-13cf5584-e50b-11e7-94b3-2aae306f20d2.png)

If I'm not mistaken, an access_token should be used for API access?

**Comment by mickeyreiss** [comment]
+1 - This just caused user accounts to be inaccessible after switching the primary domain in G Suite.

**Comment by flamber** [comment]
The `id_token` is requested to get full information about the user as noted in the documentation:
https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint

Though, the implementation will be completely rewritten some time in the future #17429.

Closing this issue, until there's more information provided on why this is incorrect.
