### ISSUE TITLE
Grouping dates by semester

### ISSUE THREAD

**Issue by zedidas** [metabase/metabase#6595]
As far as I can tell, at the moment, one is able to group dates by Day, Week, Month, Quarter and Year. 

Grouping also by Semester would be very useful.

Thanks!

**Comment by salsakran** [comment]
Semester isn't really a stable grouping, as it varies by college. 

We're not going to be supporting this in the foreseeable future.

**Comment by zedidas** [comment]
Hello,

I realize now that there probably was a language misunderstanding. Sorry, my bad!

When I suggested grouping by Semester, I was referring to grouping by Half years. First half year is from January to June, and second half year from July to December.

It is exactly like the currently supported grouping by Quarter, but instead of having 4 periods of 3 months, we would have 2 periods of 6 months.

This kind of grouping is quite often required in our company as several of our KPIs are measured every half-year.

Thank you!

**Comment by flamber** [comment]
@zedidas This issue has been closed for almost three years. You're welcome to open a new:
https://github.com/metabase/metabase/issues/new/choose
