### ISSUE TITLE
Mongodb 3.6 support

### ISSUE THREAD

**Issue by bramathon** [metabase/metabase#6599]
Mongodb 3.6 changed the way the aggregate command works

"Changed in version 3.4: MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option."

**Comment by peterk** [comment]
I guess this is what now causes errors in simple grouping queries in metabase.

`Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }`

**Comment by bramathon** [comment]
Yes, it appears so

**Comment by bestphoneappsdev** [comment]
No mongodb support till now. v3.6 is the best one so far from mongodb, yet metabase doesn't support it. I'm forced to look for alternatives after such a good run.

**Comment by bestphoneappsdev** [comment]
This issue is still not fixed. Is Metabase ever going to release 0.27.3 ever for Mac OS?

Current Latest (0.27.2) doesn't work with MongoDB 3.6.
