### ISSUE TITLE
X-Rays is not showing / working

### ISSUE THREAD

**Issue by prigal** [metabase/metabase#6603]
Hello, 

I'm on lastest released version (0.27.2) and I can't make X-Rays to work. I don't know why. (Even on previous version it has never worked, I saw option only one time on a question, clicked on it and it failed on an error)

Actually, the menu doesn't offer me the X-rays option.

![capture d ecran 2017-12-20 a 08 24 17](https://user-images.githubusercontent.com/895267/34195776-87e874b0-e55f-11e7-93b1-71dea4021c3d.png)

Note : 
- I have created and saved the question after migration to 0.27.2. 
- I have tried each X-Rays option from Approximate to Extended, and right now it's on Exact. 

What can I do ?

**Comment by sbelak** [comment]
Is this on a saved question? Currently the question needs to be saved for xrays to wrok (but we intend to lift this limitation).

**Comment by prigal** [comment]
Yes, I knew this problem, as I said "I have created and **saved** the question after migration to 0.27.2"

**Comment by prigal** [comment]
Does something need to be built (index or what else) for X-Ray to work ? Can I launch some commands on server to achieve some kind of treatment ?

**Comment by sbelak** [comment]
Closing this as with 0.29 we are retiring this approach to xrays in favour of a dashboard-based one.
