### ISSUE TITLE
Keep filters when refreshing embedded dashboards

### ISSUE THREAD

**Issue by majnu-campact** [metabase/metabase#6604]
We use iFrame embedding to make a dashboard publicly visible (within our intranet). The dashboard has a filter box. In order to keep it up to date we added a simple javascript based timer that reloads the iFrame every x seconds. However, this resets the selected filter, which is not  acceptable for our users.

Is there a better way of making dashboards publicly visible that allows automatic refreshing and keeps filter box choices? 

Thanks!

**Comment by salsakran** [comment]
Any reason you can't use a public dashboard for this use case?

Put simply if you reload an iframe, you're going to be re-rendering it by definition. We're definitely not going to default an iframe rendered dashboard to the last state of its filters as that does not make sense for the usual in-application embedding case.

**Comment by majnu-campact** [comment]
@salsakran Thanks, I wasn't aware that when we publish the entire dashboard it would write filter changes as parameters to the url. That'll work fine!

**Comment by flamber** [comment]
Closing, since using Public Sharing solves this.

**Comment by xueenda** [comment]
Is there a way to keep the state of the filter? We have an iframe embed dashboard with user authentication on the top window for the privacy reason. The dashboard refresh every minutes to get up to date data. But it's very annoying to reset the filters. Like I said we can't use public dashboard for privacy reason.

**Comment by flamber** [comment]
@xueenda Sounds like you're seeing #5875. But if you are manually refreshing the iframe, then you can get the iframe src parameters and set those when refreshing the iframe.

**Comment by albertoperdomo** [comment]
Static embeds (previously known as signed embeds) can be auto-refreshed by adding a query param refresh=n where n is the number of seconds upon which the embed is refreshed. This auto-refresh feature doesn't reset selected filter values.
