### ISSUE TITLE
Don't ask for addition to dashboard if existing question is edited

### ISSUE THREAD

**Issue by c-schmitz** [metabase/metabase#6605]
When editing an existing question and the question already exists on any dashboard the question 'Do you want to add this question to a dashboard' becomes really annoying after some time.

Instead if would be better if the software offered to jump to the particular dashboard instead, like:

"The question was updated . Do you want to check out the related dashboard  <Dasboardname'>'.
If the question is used on several dashboards probably don't ask at all.

**Comment by samweber** [comment]
See #6541

**Comment by mazameli** [comment]
Yeah, closing as a duplicate of #6541. This was resolved by #6580

**Comment by c-schmitz** [comment]
Okay, thank you!
