### ISSUE TITLE
ORA-00904: Sorting references to wrong column name

### ISSUE THREAD

**Issue by peterheise** [metabase/metabase#6611]
Browser: Firefox 52.4.1
Operating System: Windows 7 on Client
Database: Oracle (with latest ojdbc7.jar, version Oracle Database 12c Release 1 (12.1.0.1))
Metabase version: 0.27.2 + 0.26.2
Metabase hosting: Redhat 7
Metabase internal database: default

Reproducable steps:

1.) I have an Oracle Database and set-up a query
2.) My query looks as follows: 
VIEW: I add any custom expression, e.g. DISTINCT("FIELD") and give it a name
GROUP BY: 1.) group by one field, 2.)

--> Till here everything works great.

![image](https://user-images.githubusercontent.com/34706662/34258652-31f60986-e65f-11e7-8bdd-ff7cebe41390.png)

SQL Code being as follows:

![image](https://user-images.githubusercontent.com/34706662/34258570-ba48bba4-e65e-11e7-8a61-289c00522e7d.png)

--> NOW

3.) If I select the field with my custom expression to select ordering, the query fails with error "ORA-00904 "count" invalid identifier". 

![image](https://user-images.githubusercontent.com/34706662/34258441-41c573e8-e65e-11e7-9b58-56fca00e425c.png)

--> What I think is happening here:
My custom view field is named "Seen on Number", not "count". But the click on order will add an "ORDER BY "count"" to the query which cannot work and Oracle generates the error message. There seems to be a bug on how the views are used together with Order by clicks.

**Comment by flamber** [comment]
Closing in favor of #6239
