### ISSUE TITLE
Can't change Google Analytics DB settings

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6613]
Reproduced this locally on master as well as on our stats instance.

If you have a GA DB connected and you try to change any of its settings in the admin panel, the form doesn't recognize that changes have been saved, and the Save button remains disabled. Navigating away discards the changes.

**Starting state: note the DB name**

![original-db-name](https://user-images.githubusercontent.com/2223916/34309017-ce7433d2-e704-11e7-9114-1949bc73b34c.png)

**Attempted to change the DB name, but the Save button stays disabled**

![cant-save-db](https://user-images.githubusercontent.com/2223916/34309039-da7a7efc-e704-11e7-92e6-dd8b1a4315b2.png)

**Same thing happens if you try changing this toggle (or any of the other connection input boxes)**

![screen shot 2017-12-22 at 10 37 53 am](https://user-images.githubusercontent.com/2223916/34309061-ecf6e8ea-e704-11e7-9918-ac02a13004ac.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Caused by the requirement of inputting Auth Code again
