### ISSUE TITLE
Custom expressions - no scroll in fields list 

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#6616]
Happening in both app and web versions. Just try to create a custom expression for a table with lots of columns. The 73 more doesn't expand on click, it doesn't scroll while using the keyboard to go down even. This hinders the ability to actually use it properly.

![screen shot 2017-12-22 at 18 37 22](https://user-images.githubusercontent.com/1330677/34316334-a0b7ed10-e747-11e7-95ec-8d9a2a7c36ba.png)

**Comment by attekei** [comment]
Fixed by #6736
