### ISSUE TITLE
Environmental Variable to specify Schema

### ISSUE THREAD

**Issue by anirudhmurali** [metabase/metabase#6622]
Currently [MB_DB_CONNECTION_URI](https://www.metabase.com/docs/latest/operations-guide/environment-variables.html#mb_db_connection_uri) needs to be used with the parameter `currentSchema=MYSCHEMA`

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
Going to go ahead and close this out as Won't Fix. As you've mentioned you can use `MB_DB_CONNECTION_URI` if you need more advanced connection options
