### ISSUE TITLE
Several Bugs when trying to export CSV via shared Metabase Questions

### ISSUE THREAD

**Issue by ElishaKay** [metabase/metabase#6629]
This problem is specific to Questions that are shared with non-metabase Users.

As a Metabase User, I can create questions with filters, and the export CSV works. However - if I share a question with a non-metabase user, several errors occur:

a) The export feature breaks when you have 'Required Variables' or more than one 'Filter' as part of the question. That means, when sharing that question with a non-metabase users, they will simply get an 'error' message when trying to export the CSV. 

b) If you include only one filter in the question, the CSV exported by the non-metabase user will ignore the user input when exporting. Meaning, the CSV will export the Query as if there was no filter at all.

**Comment by dukedave** [comment]
If I had to guess, I'd say this is where the variables come in after pressing 'Refresh' on a question page:
https://github.com/metabase/metabase/blob/1694be2932998ce12306c9735270a90c829044e7/frontend/src/metabase/query_builder/actions.js#L79

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 with a Native/SQL question with two filters (one required) via Public Sharing.
Likely fixed around 0.32.5, which included several fixes for exports.
