### ISSUE TITLE
country map showing state values when column grouping is "state"

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#663]
i honestly don't know how we prevent this reliably but its just a funny illustration of how you can get nonsensical chart renderings based on the data
<img width="1388" alt="screen shot 2015-07-12 at 5 13 48 pm" src="https://cloud.githubusercontent.com/assets/5248953/8640781/7d14a3de-28b9-11e5-9fba-29fa61fdeefd.png">

**Comment by agilliland** [comment]
@kdoh @salsakran , I motion to close this one as not being a bug.  

the truth of this situation is that there are US state codes which overlap with viable country codes, so if the user decides to apply the country map visualization to the data using state codes it's going to show up like this.  i can't see any way to prevent this from happening.

**Comment by kdoh** [comment]
@agilliland Sounds good to me. I mostly opened it originally as a funny "edge" case I noticed at the time. This is probably an area where metadata could help us. If you switch from state to country and we know its a state field we can help prevent California showing as Canada on the map. :maple_leaf:
