### ISSUE TITLE
Small i18n typos in saved question placeholder screen

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6634]
I'll fix these as well. Just an errant dollar sign and double quote.

<img width="512" alt="screen shot 2017-12-28 at 5 27 34 pm" src="https://user-images.githubusercontent.com/2223916/34504942-9d8ef2b8-efd6-11e7-9e8c-5f8f1d97b45e.png">

**Comment by salsakran** [comment]
fixed in #6635
