### ISSUE TITLE
Bug: Wrong date displayed

### ISSUE THREAD

**Issue by mokra** [metabase/metabase#6636]
prop |  val  |
--- | --- 
Browser | FF 57
OS | Windows 10
MB | 0.27.0
MB Hosting | Linux Ubuntu 16
MB internal DB | H2

As you may see on this image:
![img_0912](https://user-images.githubusercontent.com/1849512/34521199-cebe5494-f08c-11e7-9b49-cfee48b7f57d.png)
If I let MB display the date without any date formatting, MB displays the date of my data **+3 hours**. On the screenshot you can see my SQL query, where I both, use and don't use the date_format function.

Thanks!

**Comment by salsakran** [comment]
What database are you querying?

Also, what timezone is 
* your db server set to
* the server you are running metabase on
* your reporting timezone
* your browser timezone?

**Comment by mokra** [comment]
@salsakran 
My timezones:
* browser: **GMT+0100**
* server MB runs on: **Europe/Moscow (MSK, +0300)**
* reporting timezone: **Europe/Moscow (MSK, +0300)**
* MySQL DB Timezone: the only way I know how to do it, is by something like that: 
`select timediff(now(),convert_tz(now(),@@session.time_zone,'+00:00'));`
And it returns **03:00:00**

**Comment by infomofo** [comment]
@salsakran there definitely seems to be a difference between how old versions of metabase were handling time zones.

We upgraded from 0.25.2 to 0.27.2, and we immediately noticed that existing sql query cards using a filter relative to current time (i.e. created_at > SYSDATE - interval '1 hour') were off- the dates of fields in the database were treated as if they were several hours ahead, even though our database and metabase time zone were set to US/Eastern.

I reverted to 0.25.2 and the metabase cards work as expected.

**Comment by infomofo** [comment]
@salsakran for more info on my issue this is for a query like:

'select * from users where created_at > SYSDATE - interval '1 hour'

on a redshift database where created_at is of type "timestamp without time zone"

My metabase timezone is set to US/Eastern and my database timezone is GMT.

When I run the above query on metabase running 0.25.2 it only returns users created in the past hour, but when I run it on 0.27.2 it returns more than that.

**Comment by tlrobinson** [comment]
Related to #6368?

**Comment by mokra** [comment]
@salsakran I see you've been shifting this task from one milestone to another.
Do you think it's going to be part of 0.29?

Thanks a lot!

**Comment by senior** [comment]
@infomofo There's definitely changes in timezone related handling in recent versions of Metabase. I was able to fix a lot of bugs there, but we have seen issues were users were relying on the previous (broken) behavior. My guess is if you're hitting an issue with Redshift it's going to be different from this MySQL issue. Could you write up your issue separately with more information?

**Comment by mokra** [comment]
@senior Thank you very much for your explanation - could you tell me how to check the mysql `Report Timezone` setting? And if I populate the timezone tables - would this change my Data?

**Comment by senior** [comment]
I'm going to close this issue as it was related to MySQL setup. If you hit other date/time issues after getting timezone tables configured, please post the info to [our discourse](http://discourse.metabase.com/) forum.
