### ISSUE TITLE
The syntax for order-by has changed in MBQL (ascending - descending)

### ISSUE THREAD

**Issue by hexleyOlive** [metabase/metabase#6639]
Use SORT options (descending or ascending) through the Metabase UI causes some WARN in the CMD output:

```
The syntax for aggregate fields has changed in MBQL '98. Instead of [:aggregation 0], please use [:aggregate-field 0] instead.

The syntax for order-by has changed in MBQL '98. [<field> :ascending/:descending] is deprecated. Prefer [:asc/:desc <field>] instead.
```

After convert the question to SQL and refreh, WARN are gone (the ORDER BY is SQL query is DESC or ASC)

Tested on
Chrome 65
macOS 10.12.6
MySQL
Metabase 027.2
Metabase JAR file on Windows Server

**Comment by camsaul** [comment]
This is a warning and you can safely ignore it.
