### ISSUE TITLE
fixed data table performance

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#664]
both with the web inspector open and just generally the data table seems to have a fair bit of lag while scrolling (especially horizontally). i haven't been able to pinpoint any commonalities that lead to it, but it feels like it chugs a bit.

**Comment by camsaul** [comment]
does this still apply to the new stuff

**Comment by salsakran** [comment]
@camsaul yeah, think the underlying problem is that the data table component lazily loads rows but not columns, so tables lots of columns slow down

**Comment by camsaul** [comment]
As posted in #775 here's a video of slow resizing performance https://www.dropbox.com/s/rjj2b06fj0ekhvy/IMG_0354.MOV?dl=0

**Comment by tlrobinson** [comment]
https://github.com/facebook/fixed-data-table/issues/49

**Comment by tlrobinson** [comment]
Possible alternative grid, found by @kdoh: https://bvaughn.github.io/react-virtualized/

**Comment by bvaughn** [comment]
react-virtualized author here. Would love to see you guys try `Grid` for horizontal virtualization. :) Happy to help if you decide to go that route and run into any snags.

**Comment by tlrobinson** [comment]
We're using react-virtualized successfully in a few places now, we should switch the data table to it and remove the FixedDataTable dependency.

**Comment by kdoh** [comment]
👍

**Comment by bvaughn** [comment]
👍 Still happy to help answer any integration questions you run into if you choose to migrate to react-virtualized

**Comment by tlrobinson** [comment]
@bvaughn Thanks, I don't expect it to be difficult, `react-virtualized` has been great so far.

Only issue was a conflict with our own `.Grid` classes. Upgrading to 8 resolved it.

**Comment by hai-ld** [comment]
Is there any chance this issue could be fixed in 0.21 release?
