### ISSUE TITLE
Analytics.googleapis.com service no longer exists

### ISSUE THREAD

**Issue by anttonp** [metabase/metabase#6644]
When linking a new "Google Analytics" database, Metabase points at the "analytics.googleapis.com" service. This service is no longer available on the google console which makes impossible to connect. 

When following the link returned by the error (clojure.lang.ExceptionInfo: Access Not Configured. Google Analytics API has not been used in project XXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=XXXXXXXXXXXX), a google error page shows up. 

It seems like Metabase should point at the "analyticsreporting.googleapis.com" service instead. 
  
[Currently using the 0.27.2 version]

**Comment by camsaul** [comment]
@anttonp I'm also seeing that error message, but for me following the link to https://console.developers.google.com/apis/api/analytics.googleapis.com/overview?project=XXXXXXXXXXXX works and takes me to a page to enable the GA API.

Can you try the link again and see if it's working now?

@metabase/core-developers it seems like to enable GA you have to enable the API now, which seems like a recent change. I think we should add a section saying as much in the admin panel. We can infer the link based on the other input.
