### ISSUE TITLE
Bug: No Loading Ovelay or Spinner On Embeds

### ISSUE THREAD

**Issue by edmarriner** [metabase/metabase#6645]
When using an embedded question or dashboard ( through the iframe ) there is no indication of any loading or progress being made.

It is most notably an issue when you make changes to filters on an embedded question and nothing appears to happen until the results are loaded ( with some of the more complex questions this could be a few seconds ).

When using Metabase itself you commonly see the "Doing Science" loading overlay. This loader is something that I think would make sense to apply to the embedded versions of the pages as well.

**Comment by gschlect** [comment]
For longer-running queries this is particularly confusing.
