### ISSUE TITLE
Alert reaches the goal with time series

### ISSUE THREAD

**Issue by hexleyOlive** [metabase/metabase#6646]
Release 0.26 has introduced Alert feature (great feature!!).
There are three kinds of things that can be use with Alerts in Metabase:
When a time series crosses a goal line.
When a progress bar reaches or goes below its goal.
When any other kind of question returns a result.

I use the release 0.27.2, with progress bar + a goal, when an Alert is setup, 2 choices are available:
Alert me when the progress bar… (Reaches the goal OR Goes below the goal)
The first time it reaches the goal, or every time? (The first time OR Every time)

However, I cannot see same choices with time series with a Goal.

Alert with Goal is not yet available with time series? Or this is a bug (maybe already know)?

**Comment by mazameli** [comment]
Is your time series question based on a SQL or native query?

**Comment by hexleyOlive** [comment]
Tried both, see video for example.

![test alert](https://user-images.githubusercontent.com/8439893/34577968-7acb7c70-f183-11e7-893f-6197f6923b3e.gif)

**Comment by mazameli** [comment]
I think you've confused filtering by time with grouping by time. In your example, your line chart is not a time series; it's a count grouped by `Total`, i.e. by a number. So though you're _filtering_ by time, you need to _group_ by time in order for it to be a time series. (Sorry if I'm being overly simplistic. 😄 )

**Comment by hexleyOlive** [comment]
👍🏻Ok clear now, it works with only group by time.
But why it does'nt work with group by time + another value (as in example group by Total)?

**Comment by salsakran** [comment]
closing since this isn't a bug.
