### ISSUE TITLE
Webhook icon and emoji not shown

### ISSUE THREAD

**Issue by logros** [metabase/metabase#6654]
Hi,
i use zabbix - mattermost integration via script https://github.com/muokata/zabbix-mattermost-alertscript/blob/master/mattermost.sh,

All it's ok, webhook work almost full, log from console:
Входящий вебхук получен. Содержание={"icon_url": "http://a.slack-edge.com/41b0a/img/plugins/_skeleton/service_36.png", "attachments": [ {"color": "#00ff33", "text": "OK: Много выпадающих пакетов host_pinger_ул.Александра Довженка(ул.Урицкого),5,dlink dir-100"} ], "channel": "#logros", "username": "ZABBIX Informer", "icon_emoji": ":ok_hand:"}

Messages come to chat, but icon and emoji not shown.
what's wrong with my config, please help.

**Comment by salsakran** [comment]
We don't yet support mattermost (#2231 ), and definitely can't help you debug someone else's script. Please open the question at that script's repo!

Good luck, and if you figure it out, please let us know.
