### ISSUE TITLE
Sorting field filter values by name and then by table

### ISSUE THREAD

**Issue by edmarriner** [metabase/metabase#6667]
When adding a field filter to a question the values are not sorted by the table name.

It would be great it the values were sorted by the field name first and then the table name second.

This would solve the issue where you have a field name that appears in many tables. Currently when you are searching for a common field name (such as "name" or "created" etc..  )  it is difficult to find the correct table you are looking for.

In the example below, you can see that the field "Name" appears in a lot of tables, but the ordering of these values in the list is not very helpful.

![screenshot from 2018-01-09 13-17-46](https://user-images.githubusercontent.com/655769/34722703-c422f8a2-f53f-11e7-9438-5d7aa704de61.png)

**Comment by salsakran** [comment]
we've fixed this in https://github.com/metabase/metabase/pull/6730
#6183 shows the new design.
