### ISSUE TITLE
Columns are not showing for new queried field when using hidden columns

### ISSUE THREAD

**Issue by sabino** [metabase/metabase#6670]
- Your browser and the version: 58.0.3029.110 (64-bit)
- Your operating system: Manjaro
- Your databases: Postgres, BigQuery
- Metabase version: 0.27.2
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

When using SQL and editing an existing query, the column fields are not showing the newly added field.

There is a video that easily shows how to reproduce the issue.

![metabase_fields](https://user-images.githubusercontent.com/982190/34734437-ead8a8a8-f552-11e7-9c37-393201dbaa0c.gif)

If you Reset to defaults, yes it fixes the problem but I don't think thats optimal.

**Comment by paulrosenzweig** [comment]
fixed in #9592

**Comment by MchlUh** [comment]
Hi there, I encounter the exact same issue, but with the current version of Metabase (0.39.4) there is no 'reset to defaults', so I just cannot display newly added columns.
