### ISSUE TITLE
Lingering i18N strings

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6674]
Following up from https://github.com/metabase/metabase/pull/6446
there are a few places where we didn't internationalize all strings.

Let's use this issue to keep reminders.

https://github.com/metabase/metabase/pull/6446/files#diff-073dcb1ef60173723b4e237b0e7dc254L15

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/widgets/DateAllOptionsWidget.jsx#L26

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/widgets/DateAllOptionsWidget.jsx#L49

**Comment by mazameli** [comment]
I just went through @joebordes' ES translation to see what's missing, and here's an inventory of what I found. I'm not yet certain which of these strings have not be tagged versus which were not translated.

## Admin settings pages, particularly subheadings

![screen shot 2018-04-17 at 1 57 43 pm](https://user-images.githubusercontent.com/2223916/38898792-e6877dc0-424a-11e8-972f-7739dfbcc663.png)

----

![screen shot 2018-04-17 at 1 57 59 pm](https://user-images.githubusercontent.com/2223916/38898796-eb976b9a-424a-11e8-9eea-595142760d53.png)

----

![screen shot 2018-04-17 at 1 58 07 pm](https://user-images.githubusercontent.com/2223916/38898803-ef3f69aa-424a-11e8-9985-b4fcbc53b6e2.png)

----

![screen shot 2018-04-17 at 1 58 14 pm](https://user-images.githubusercontent.com/2223916/38898807-f3e454a2-424a-11e8-9a84-7577b8b29965.png)

----

![screen shot 2018-04-17 at 1 58 35 pm](https://user-images.githubusercontent.com/2223916/38898819-fb1c5d6e-424a-11e8-89c3-2ec9e74d1213.png)

----

![screen shot 2018-04-17 at 1 58 40 pm](https://user-images.githubusercontent.com/2223916/38898828-ffde210c-424a-11e8-9614-1e6151c81a4d.png)

----

![screen shot 2018-04-17 at 1 58 44 pm](https://user-images.githubusercontent.com/2223916/38898837-0463a878-424b-11e8-97b7-c1e885ba6080.png)

----

![screen shot 2018-04-17 at 1 58 51 pm](https://user-images.githubusercontent.com/2223916/38898843-07e0cad0-424b-11e8-9891-2b683b1203e6.png)

----

![screen shot 2018-04-17 at 1 58 57 pm](https://user-images.githubusercontent.com/2223916/38898855-0de6a7f6-424b-11e8-9fe2-714add274178.png)

----

![screen shot 2018-04-17 at 2 00 03 pm](https://user-images.githubusercontent.com/2223916/38898883-232bc272-424b-11e8-9eac-a0bdda35e6ff.png)

----

**The Administrator and All Users default groups:**

![screen shot 2018-04-17 at 2 04 47 pm](https://user-images.githubusercontent.com/2223916/38898923-3c7d9020-424b-11e8-987e-da5386bf15fd.png)


## Admin pages that didn't load

![screen shot 2018-04-17 at 1 59 12 pm](https://user-images.githubusercontent.com/2223916/38898875-1eb6d614-424b-11e8-8e35-a0a598b97aa7.png)

----

![screen shot 2018-04-17 at 2 05 38 pm](https://user-images.githubusercontent.com/2223916/38898929-41433b0a-424b-11e8-87f6-1b286a0f0472.png)

----

**Database scheduling:**

![screen shot 2018-04-17 at 2 00 28 pm](https://user-images.githubusercontent.com/2223916/38898890-28e27f94-424b-11e8-9828-8d52d02b9047.png)

## User-land

![screen shot 2018-04-17 at 2 05 59 pm](https://user-images.githubusercontent.com/2223916/38898945-4c571d68-424b-11e8-8e7d-ecaa04bb311c.png)

----

![screen shot 2018-04-17 at 2 07 48 pm](https://user-images.githubusercontent.com/2223916/38898955-514ffd6c-424b-11e8-8ed3-bcfe1769c7c3.png)

----

![screen shot 2018-04-17 at 2 09 35 pm](https://user-images.githubusercontent.com/2223916/38898960-55fb0de8-424b-11e8-832c-cbfcb9904544.png)

----

![screen shot 2018-04-17 at 2 09 50 pm](https://user-images.githubusercontent.com/2223916/38898967-59db4b9e-424b-11e8-8dd4-b84f95880216.png)

----

![screen shot 2018-04-17 at 2 10 05 pm](https://user-images.githubusercontent.com/2223916/38898970-5d46d0b4-424b-11e8-8b1d-89a4e6c96cd5.png)

----

![screen shot 2018-04-17 at 2 10 11 pm](https://user-images.githubusercontent.com/2223916/38899045-9470f862-424b-11e8-91a5-1c208fb843eb.png)

----

![screen shot 2018-04-17 at 2 10 19 pm](https://user-images.githubusercontent.com/2223916/38899058-9ad77aaa-424b-11e8-99bb-e94231a9edea.png)

![screen shot 2018-04-17 at 2 10 26 pm](https://user-images.githubusercontent.com/2223916/38899066-a2281e9a-424b-11e8-89d2-5d49803ea38d.png)

----

![screen shot 2018-04-17 at 2 11 23 pm](https://user-images.githubusercontent.com/2223916/38899087-b6dc7836-424b-11e8-87d2-17c12335f7b0.png)

----

![screen shot 2018-04-17 at 2 11 48 pm](https://user-images.githubusercontent.com/2223916/38899091-ba61196c-424b-11e8-8bc8-e7a58f5e12cd.png)

----

![screen shot 2018-04-17 at 2 12 24 pm](https://user-images.githubusercontent.com/2223916/38899097-be00c75c-424b-11e8-8200-bcc6f2187df3.png)

----

**Aggregation tooltips:**

![screen shot 2018-04-17 at 2 12 42 pm](https://user-images.githubusercontent.com/2223916/38899189-0354e91e-424c-11e8-972d-8781e7bdce77.png)

----

**Dashboard action tooltips:**

![screen shot 2018-04-17 at 2 13 16 pm](https://user-images.githubusercontent.com/2223916/38899210-11b977ea-424c-11e8-9592-0a2ff5486b1f.png)

----

![Uploading Screen Shot 2018-04-17 at 2.13.28 PM.png…]()

----

**Dashboard filter mapping dropdown on cards:**

![screen shot 2018-04-17 at 2 13 59 pm](https://user-images.githubusercontent.com/2223916/38899244-239f9958-424c-11e8-94e9-586609d2b623.png)

----

**Cancel/Archive/Save dashboard**

![screen shot 2018-04-17 at 2 14 06 pm](https://user-images.githubusercontent.com/2223916/38899266-32d9ad96-424c-11e8-93ab-71e008455789.png)

----

**Dashboard editing bar**

![screen shot 2018-04-17 at 2 14 12 pm](https://user-images.githubusercontent.com/2223916/38899279-3d53c1c6-424c-11e8-8069-fe94e6cac755.png)

----

**Empty dashboard message**

![screen shot 2018-04-17 at 2 14 24 pm](https://user-images.githubusercontent.com/2223916/38899291-46ce221e-424c-11e8-865b-6ade109f66d0.png)



## Visualization settings in general

Example:

![screen shot 2018-04-17 at 2 10 42 pm](https://user-images.githubusercontent.com/2223916/38899082-b0be81ce-424b-11e8-802e-496040a2bc33.png)

**Comment by joebordes** [comment]
I updated the es file so you can validate it again. I looked at most of the screens above and almost all of them have been fixed. I attach next some of the issues I found

![i18nmb_0001](https://user-images.githubusercontent.com/1237191/39089423-23804b60-45c7-11e8-9983-670081f72245.png)
![i18nmb_0002](https://user-images.githubusercontent.com/1237191/39089424-23a43516-45c7-11e8-8d5e-9b3201ec45c7.png)
![i18nmb_0004](https://user-images.githubusercontent.com/1237191/39089425-23c5b308-45c7-11e8-9cad-6447a5a30113.png)
![i18nmb_0005](https://user-images.githubusercontent.com/1237191/39089426-23e7fddc-45c7-11e8-8b11-d4c612ade3c4.png)
![i18nmb_0006](https://user-images.githubusercontent.com/1237191/39089427-2408b180-45c7-11e8-9a26-71ce5940c093.png)
![i18nmb_0007](https://user-images.githubusercontent.com/1237191/39089428-242c3858-45c7-11e8-9567-434cf653f270.png)
![i18nmb_0008](https://user-images.githubusercontent.com/1237191/39089429-24dd67fe-45c7-11e8-9486-b494f7599356.png)
![i18nmb_0011](https://user-images.githubusercontent.com/1237191/39089430-2511f456-45c7-11e8-9e21-aad913478a62.png)
![i18nmb_0013](https://user-images.githubusercontent.com/1237191/39089431-25502f78-45c7-11e8-8ffb-bfe629bafb41.png)
![i18nmb_0015](https://user-images.githubusercontent.com/1237191/39089432-25830b3c-45c7-11e8-9bf5-618e9a2457a7.png)
![i18nmb_0016](https://user-images.githubusercontent.com/1237191/39089433-26386f22-45c7-11e8-80b4-940d63e01bd6.png)

**Comment by joebordes** [comment]
**NOTE:** The above images are not blocking, they would be nice to have but I would prefer to have a 0.29 release with spanish version as it is now and have the users inform of errors instead of trying to track them all down.

**Comment by joebordes** [comment]
**Blocking issues**: I only found two issues that are blocking and must be fixed befor releasing: I cannot access SETUP nor AUTHENTICATE in settings.

Let me know how I can help

**Comment by salsakran** [comment]
the first will need to be translated, but we need to figure out how to pull them out of YAML (paging @sbelak )

The latter is going to be dropped from 0.29

**Comment by mazameli** [comment]
@flamber I think we should close this issue. It's 2.5 years old, many or most of these are already fixed, and there are screenshots from parts of the product that don't even exist anymore (hey there, old x-rays 👋).

Moving forward, I'm in favor of i18n issues more like #8964, which is scoped to translations in a particular area of the product, or with a particular theme. I think mega issues like this one (6674) are almost inherently uncloseable, which feels bad.
