### ISSUE TITLE
Translation How To

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#6680]
Hi

I would like to propose adding a "Translation How To" section in the [developer's guide](https://www.metabase.com/docs/latest/developers-guide.html).

I am willing to create an initial version of the text as I walk through the steps of translating to ES but I will need some hand-holding.

I have tried the steps defined in #5803 

```
> ./bin/i18n/update-translations
SyntaxError: frontend/src/metabase/admin/databases/components/CreatedDatabaseModal.jsx: You can not use BinaryExpression '${"/admin/datamodel/database/" + databaseId}' in localized strings
  23 |                 <div className="Form-inputs mb4">
  24 |                     <p>
> 25 |                         {jt`We're analyzing its schema now to make some educated guesses about its
     |                          ^
  26 |                         metadata. <Link to=${"/admin/datamodel/database/"+databaseId}>View this
  27 |                         database</Link> in the Data Model section to see what we've found and to
  28 |                         make edits, or <Link to=${Urls.question(null, `?db=${databaseId}`)}>ask a question</Link> about
```

and 

```
> yarn run extract-translatable-strings
yarn run v1.3.2
error Command "extract-translatable-strings" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is the code ready for this?

**Comment by qin4zhang** [comment]
How to use i18n? I would like to translate english to chinese,however, I don't kown how to use it? I have added locales/cn.po and resources/frontend_client/app/locales/cn.json,next??

**Comment by joebordes** [comment]
HI @salsakran,

I received an email inviting us to translate the strings but I get the error above, so I cannot generate the language strings.

Can you please help me fix that error?

**Comment by joebordes** [comment]
Hi,

I made this change to the file I am getting the error on:

```
diff --git a/frontend/src/metabase/admin/databases/components/CreatedDatabaseModal.jsx b/frontend/src/metabase/admin/databases/components/CreatedDatabaseModal.jsx
index d69deb0..433f312 100644
--- a/frontend/src/metabase/admin/databases/components/CreatedDatabaseModal.jsx
+++ b/frontend/src/metabase/admin/databases/components/CreatedDatabaseModal.jsx
@@ -15,6 +15,8 @@ export default class CreatedDatabaseModal extends Component {
 
     render() {
         const { onClose, onDone, databaseId } = this.props;
+        const link2db = <Link to={`/admin/datamodel/database/${databaseId}`}>{t`View this database`}</Link>
+        const link2q = <Link to={Urls.question(null, `?db=${databaseId}`)}>{t`ask a question`}</Link>
         return (
             <ModalContent
                 title={t`Your database has been added!`}
@@ -22,11 +24,9 @@ export default class CreatedDatabaseModal extends Component {
             >
                 <div className="Form-inputs mb4">
                     <p>
-                        {jt`We're analyzing its schema now to make some educated guesses about its
-                        metadata. ${<Link to={`/admin/datamodel/database/${databaseId}`}>View this
-                        database</Link>} in the Data Model section to see what we've found and to
-                        make edits, or ${<Link to={Urls.question(null, `?db=${databaseId}`)}>ask a question</Link>} about
-                        this database.`}
+                        {t`We're analyzing its schema now to make some educated guesses about its
+                        metadata. ${link2db} in the Data Model section to see what we've found and to
+                        make edits, or ${link2q} about this database.`}
                     </p>
                 </div>
 
```
and now it passes that file but gives me the same error in PeopleListingApp.jsx. In fact there seems to be about 40 more issues like this.

I do not know if the change I made is correct, but if you can confirm it is I will make that change in all the others and propose a PR for your revision.

Please let me know how I can help.

**Comment by joebordes** [comment]
@salsakran I see translations popping up for various languages which are wrong due to this limitation blocking us.

#6921 #6916 #6831

**Comment by joebordes** [comment]
another one: #6923

I think this is getting to be important

**Comment by joebordes** [comment]
Hi @salsakran 

I read [the conversation](https://github.com/c-3po-org/c-3po/issues/95) going on at c3po and it seems to me that it is going to be a long while before we will be able to continue. I am willing to extract and convert the jsx strings to const if you will accept that PR so we can move forward faster.

This is really important to us and a total show stopper.

Do you want me to do that work and submit a PR?

**Comment by salsakran** [comment]
@tlrobinson  what do you think we should do to get this moving again?

**Comment by tlrobinson** [comment]
@salsakran I've asked the c-3po team if they want help with adding expression support. I'm not sure how much work it would be but it might be worth helping them.

**Comment by AlexMost** [comment]
started work on that here - https://github.com/c-3po-org/babel-plugin-c-3po/pull/100/files. Going to finish in soon.

**Comment by AlexMost** [comment]
You can try preminor version of - `babel-plugin-c-3po@0.8.0-0`.

I have added the new configuration option -  `numberedExpressions`. 

With `{ numberedExpressions: true }` babel plugin should allow using any expression inside template literals.

@salsakran  Looking forward for the feedback. Let me know if that works for you.

**Comment by tlrobinson** [comment]
PR here #7045

**Comment by AlexMost** [comment]
@tlrobinson glad to hear that it works for you. Need to check ternary operator case, can you please submit issue with the reproduce example here - https://github.com/c-3po-org/c-3po/issues? Going to make `0.8.0` release soon and update the docs. 

Need to think about `xgettext` compatibility (created separate issue - https://github.com/c-3po-org/c-3po/issues/99).

**Comment by salsakran** [comment]
I've added https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#internationalization and verified that the commands run properly!

**Comment by joebordes** [comment]
I get the same error
Do I have to update something besides "git pull upstream master"

**Comment by salsakran** [comment]
the fix is in #7045 and will be merged in a just a second.

**Comment by joebordes** [comment]
Merging off that branch I get this error:

```
joe@joecasa /space/reps/metabase $ bin/i18n/update-translations
Error: frontend/src/metabase/App.jsx: data should NOT have additional properties
    at new ConfigValidationError (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/errors.js:22:131)
    at new C3poContext (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/context.js:79:19)
    at PluginPass.extractOrResolve (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/plugin.js:24:23)
    at newFn (/space/reps/metabase/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitQueue (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:156:21)
    at TraversalContext.visitSingle (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:192:19)
```

**Comment by salsakran** [comment]
What do you mean `merging off that branch`? What are you merging it with?

**Comment by salsakran** [comment]
I literally just ran that command on that branch and it was clear.

**Comment by joebordes** [comment]
I  executed:

```
git checkout -b i18n001 upstream/i18n-fixes
```

**Comment by joebordes** [comment]
I tried this too:

```
joe@joecasa /space/reps/metabase $ git checkout -b i18n002
Switched to a new branch 'i18n002'
joe@joecasa /space/reps/metabase $ git merge upstream/i18n-fixes
Merge made by the 'recursive' strategy.
 .babelrc                                                              |    3 +-
 bin/i18n/build-translation-frontend-resource                          |   36 +-
 frontend/src/metabase/lib/i18n.js                                     |   13 +
 frontend/src/metabase/query_builder/components/QueryVisualization.jsx |   13 +-
 locales/de.po                                                         | 7673 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 locales/metabase.pot                                                  | 7531 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 package.json                                                          |    4 +-
 resources/frontend_client/app/locales/de.json                         |  456 +++++++++-
 resources/locales.clj                                                 |    2 +-
 src/metabase/routes.clj                                               |    6 +-
 yarn.lock                                                             |  123 ++-
 11 files changed, 15681 insertions(+), 179 deletions(-)
joe@joecasa /space/reps/metabase $ bin/i18n/update-translations
Error: frontend/src/metabase/App.jsx: data should NOT have additional properties
    at new ConfigValidationError (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/errors.js:22:131)
    at new C3poContext (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/context.js:79:19)
    at PluginPass.extractOrResolve (/space/reps/metabase/node_modules/babel-plugin-c-3po/dist/plugin.js:24:23)
    at newFn (/space/reps/metabase/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/space/reps/metabase/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitQueue (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:156:21)
    at TraversalContext.visitSingle (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/space/reps/metabase/node_modules/babel-traverse/lib/context.js:192:19)
```

**Comment by joebordes** [comment]
Maybe I am missing a "yarn update" or something like that???

**Comment by salsakran** [comment]
did you update the yarn dependencies? eg `yarn install`? 
There was a fix in the upstream c3p0 library that  we're using.

**Comment by joebordes** [comment]
A little better. Now I get a whole bunch of translation strings in both .po files but the process doesn't seem to finish correctly. I see this:

```
joe@joecasa /space/reps/metabase $ bin/i18n/update-translations
sed: can't read : No such file or directory
```

**Comment by joebordes** [comment]
what locale should I use to create the .po file?  es, es_ES, es_es...

In order to distinguish es (Spain) from es (Mexico) (for example)

**Comment by salsakran** [comment]
I get 
```
Sameers-MacBook-Pro:metabase-init sameer$ ./bin/i18n/update-translations
...................................................................................................................................................................... done.
Sameers-MacBook-Pro:metabase-init sameer$ 
```

**Comment by joebordes** [comment]
I had to eliminate the empty string in the sed command to get it working:

```
diff --git a/bin/i18n/update-translation-template b/bin/i18n/update-translation-template
index a7d2a71..0c2220e 100755
--- a/bin/i18n/update-translation-template
+++ b/bin/i18n/update-translation-template
@@ -48,7 +48,7 @@ find src -name "*.clj" | xgettext                   \
   --add-comments --sort-by-file                     \
   -o $POT_BACKEND_NAME -f -
 
-sed -i "" -e 's/charset=CHARSET/charset=UTF-8/' "$POT_BACKEND_NAME"
+sed -i -e 's/charset=CHARSET/charset=UTF-8/' "$POT_BACKEND_NAME"
 
 # merge frontend and backend pots
 msgcat "$POT_FRONTEND_NAME" "$POT_BACKEND_NAME" > "$POT_NAME"
```

I am running on linux mint

**Comment by joebordes** [comment]
I have a .po file with 1655 strings to translate. Look like I have a looong weekend ahead of me :-)

Please let me know what the name of the locale should be when you can.

thanks.

**Comment by joebordes** [comment]
I think there is something wrong

I started translating. The second string is:

```
"We're analyzing its schema now to make some educated guesses about its\n"
"metadata. ${ 0 } in the Data Model section to see what we've found and to\n"
"make edits, or ${ 1 } about\n"
"this database."
```

I have not context about what ${0} and ${1} are. So I go to the code and see that they are:

```
<Link to={`/admin/datamodel/database/${databaseId}`}>
View this database
</Link>
```

and 

```
<Link to={Urls.question(null, `?db=${databaseId}`)}>
ask a question
</Link>
```

So I search for those two strings in my es.po file: the first one is not there and the second one is there but with different capitalization. I searched for the "View this database" string in the main metabase.pot file and it isn't there either.

Just to confirm that I actually got the right result.

**Comment by salsakran** [comment]
That's the issue noted in the linked PR.

I'd start with the pure strings first.

**Comment by joebordes** [comment]
got it!  thanks

**Comment by mokra** [comment]
@joebordes if you've got it working, could you please describe step by step what you had to updated and do and which branch you had to pull in order to get it working? Many thanks

**Comment by tlrobinson** [comment]
@mokra see #7045. Check out that branch `i18n-fixes` then follow the instructions in the PR.

Let me know if you have any issues in that PR.

**Comment by AlexMost** [comment]
FYI. To provide more context on the translated strings you may also use comments https://c-3po.js.org/translator-comments.html or skip `numberedExpressions` mode.

**Comment by joebordes** [comment]
The steps I followed are all above but I will detail them again all together:

```
git checkout master
git checkout -b your_translation_branch
git merge upstream/i18n-fixes
yarn install
```

Now I had to edit bin/i18n/update-translation-template to eliminate the empty string in the sed command:

```
diff --git a/bin/i18n/update-translation-template b/bin/i18n/update-translation-template
index a7d2a71..0c2220e 100755
--- a/bin/i18n/update-translation-template
+++ b/bin/i18n/update-translation-template
@@ -48,7 +48,7 @@ find src -name "*.clj" | xgettext                   \
   --add-comments --sort-by-file                     \
   -o $POT_BACKEND_NAME -f -
 
-sed -i "" -e 's/charset=CHARSET/charset=UTF-8/' "$POT_BACKEND_NAME"
+sed -i -e 's/charset=CHARSET/charset=UTF-8/' "$POT_BACKEND_NAME"
 
 # merge frontend and backend pots
 msgcat "$POT_FRONTEND_NAME" "$POT_BACKEND_NAME" > "$POT_NAME"
```

this probably depends on your operating system, so you may not need to do that.

Now launch

```
bin/i18n/update-translations
bin/i18n/update-translation your_locale
bin/i18n/update-translations
```

You should now have the translation file ready to start in the locales directory.

HTH

**Comment by tlrobinson** [comment]
@joebordes `i18n-fixes` branch should be up to date with `master` now so you can just branch off that. I also think I fixed the `sed` issue, could you try the latest from the `i18n-fixes` branch?

**Comment by joebordes** [comment]
latest master branch is working fine. Thanks!!

**Comment by mokra** [comment]
@joebordes how do you set the default language?

**Comment by joebordes** [comment]
Metabase uses the language detected in your browser. Personally, I think it is better that each user selects the language they want to work with, but that is what we have at the moment.

In my case, chrome directly brought up the site in Spanish.

I just launched the [instructions on the wiki page](https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#internationalization)

```
chrome://settings/?search=language
chrome://settings/?search=idioma
```

and Spanish is first on the list of available languages in my browser, so make sure that list is in the order you want.

**Comment by mokra** [comment]
thx

**Comment by sumiodz** [comment]
@joebordes  how i can translate metabase in spanish without setting the default language
Please reply asap i need very urgently

**Comment by joebordes** [comment]
I'm sorry but you can't, that is the way it works.  I know, it should be user based but it isn't.
