### ISSUE TITLE
Problem with calendar picker

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6683]
On our stats instance and on master, when using any of our calendar pickers in filters, I can't seem to go back before January 1 2018 with the arrows. If I manually type in a date within 2017, the picker correctly refreshes, but then trying to use the arrows again will eventually result in the same weirdness as depicted in the attached gif.

![picker](https://user-images.githubusercontent.com/2223916/34790637-2d2659ea-f5f7-11e7-86a8-056fdb287aa4.gif)

**Comment by tlrobinson** [comment]
@mazameli I believe I've fixed this in #6530

**Comment by mazameli** [comment]
@tlrobinson just recently? When I spun it up yesterday, that's where I first encountered it.

**Comment by tlrobinson** [comment]
@mazameli Just a couple hours ago. See the last commit in #6530
