### ISSUE TITLE
Postgres array_agg function

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6686]
Does anyone have any recommendations on using an aggregated array function with Metabase?

I tried using Postgres' "array_agg", but Metabase doesn't seem to recognize it.

**Comment by salsakran** [comment]
Are you referring to the calculated expressions in the GUI query builder or in the native SQL editor?

**Comment by ACPK** [comment]
@salsakran - Native SQL views. A number of our views uses an array_agg function.

**Comment by salsakran** [comment]
I don't follow. Do you mean a view you create via `CREATE VIEW blah blah` or our native SQL editor? 

Can you share your schema and the actual error you're hitting?

**Comment by ACPK** [comment]
@salsakran - The views WERE NOT added to Metabase. We're trying to read our database views rather than tables due to joins, but Metabase can't due to the array_agg error.

**Comment by flamber** [comment]
Closing, since without the stacktrace or more details it's difficult to take action.
Possibly the same problem as #11995
