### ISSUE TITLE
Allow export/download from Public Shared dashboard

### ISSUE THREAD

**Issue by starantino** [metabase/metabase#6687]
### Feature Request | Download .csv from Publicly Shared Dashboard Link
Add the ability to download the related .csv to the specified question on the shared dashboard.
I have users who are really bad about logging into system and downloading a .csv export if they need it. It would be nice to have the ability for them to download this from the shared dashboard link if they need it so they don't have to log in. Maybe a download .csv link on the top right of each question or something like that.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
related to (and possibly eventually fixed by) #6322

**Comment by nawar** [comment]
Is it possible to get an update on this, it's really useful to have this for clients who have no interest in singing with yet another thing just to view useful data.

**Comment by flamber** [comment]
@nawar 
It is implemented in embedded dashboards - but currently not in shared dashboards. If you create an embedded dashboard, then there will be a download icon on each card:
![](https://user-images.githubusercontent.com/2223916/34311359-151e9a90-e712-11e7-87d1-cfc6417177cb.png)

**Comment by GabiAlifraco** [comment]
UP please! It is a very important functionality!

**Comment by ravikiranpapthimar** [comment]
Any update on this?

**Comment by jins-agridigital** [comment]
Any chance this will be a feature that will be made available soon?

**Comment by neilrobert** [comment]
does embedded include iframe embedding on a webpage (as opposed to embedding in a web app) ? Thx

**Comment by flamber** [comment]
@neilrobert It only applies to signed embedding: https://www.metabase.com/docs/latest/administration-guide/13-embedding.html

**Comment by albertoperdomo** [comment]
This is implemented and will be included in the 51 release. Export PDF and result download on dashboard cards are present by default and can be hidden by adding a `downloads=false parameter` in the URL.

**Comment by darkmirrors** [comment]
Any progress ? When will 51 version be released? 
Thanks for your dedication @albertoperdomo

**Comment by rbucks** [comment]
I'm looking forward to this as well!

**Comment by albertoperdomo** [comment]
@darkmirrors @rbucks It's already released. It went live at the end of October. Metabase Cloud is already on 51.
 https://www.metabase.com/releases/metabase-51
