### ISSUE TITLE
2-Auth

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6688]
Has anyone successfully integrated two-auth with Metabase?

**Comment by jornh** [comment]
If you as admin setup Metabase to use [Google Sign-in](https://metabase.com/docs/v0.27.2/administration-guide/10-single-sign-on.html) and your Google accounts are set up with 2-factor-Auth I guess you have it?

**Comment by ACPK** [comment]
@jornh - Using a third-party that uses 2-auth wouldn't meet the security requirement especially since most people leave their Gmail accounts available (don't sign out every day). 

We've already locked Metabase down so you must be using our company's VPN, but are still interested in 2-auth.

**Comment by jornh** [comment]
Found the existing request #3729

**Comment by kdoh** [comment]
Going to go ahead and close this since as @jornh noted this has an existing open issue.
