### ISSUE TITLE
Pulses and permission

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#6689]
I have 2 users (foo and bar) who are in 2 groups (Commercial and Management) different. Then I have two collections (col1 and col2) in which I have arranged 1 different questions in each collection. The foo user has access to the col1 and bar collection at the col2 collection. With foo when I look at the questions page I only see the col1 collection and bar only sees the col2 collection. With the user bar I created a pulses that uses a question from the collection col2, I share it by mail with a 3rd user of the group Direction.

It's over for the context, now the problem:
With the user foo I go to the page pulses and I see appear the one that was created by the user bar. I can see the title, the description but I can not change it. In my opinion it should not be visible since not being intended for another group than Direction.

Another problem: with bar I created a pulse this time mixing a question from the Commercial group and another from the Direction group. With foo I can edit and modify pulses, certe I do not see the question for the group Direction. In my opinion not being the creator of the pulse foo should not be able to edit it.

**Comment by jornh** [comment]
With pulses now being in collections in version 0.30 to just got out (see the blog) I’d imagine your use cases should be covered.

Please check and report back here if you see any gaps 🙂
