### ISSUE TITLE
Add option to filter Previous Business Day

### ISSUE THREAD

**Issue by aleks5ka** [metabase/metabase#6690]
I am creating a filter for showing the result for Previous 1 Day. From Tuesday till Friday it is fine. It gives me the result from the Previous Business Day. But the problem is on Monday will give me results from Sunday. I don't want that. I want to be able to see the result from previous Friday or previous business day.

**Comment by mazameli** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/7079 as that issue encompasses this one and elaborates on the problem in more detail.
