### ISSUE TITLE
Export csv/xlsx from saved question

### ISSUE THREAD

**Issue by tomasonjo** [metabase/metabase#6694]
I am using v0.27.1 Metabase.

When I try to download a csv from a saved question i get returned "Not found.".

I have a saved question made by native SQL query, but same error occurs when I try to download a csv from a question with simple filter. 

Basically CSV export works when I am checking the existing question, but when I go to "Saved questions" and try to download it there it doesn't work.

**Comment by mazameli** [comment]
Hmm, so are these the steps to reproduce?
1. Go to Saved Questions
2. Click on a saved question made by a SQL query
3. Filter the question using a parameter filter widget
4. Click the download button and select CSV

If so, I am unable to reproduce this on master.

**Comment by tomasonjo** [comment]
Yes this are the steps to reproduce...
When editing existing question download CSV works, but when I click under saved questions category and select an existing question without playing around with parameter or grouping widget I get `Not found` text return

need to update to the latest version of Metabase and try again...

Will update you if error persists or not

**Comment by jescorotero** [comment]
Hi there
Do you think is the same issue as #6125 ? 
Regards

**Comment by tomasonjo** [comment]
Yes, we have upgraded the metabase to latest version 0.28.1 and issue persists....

We have the same issue as in the issue https://github.com/metabase/metabase/issues/6125.

Cheers

**Comment by kristiejfocht** [comment]
We are also having this same issue. We are new to using Metabase, version v0.29.3.  Any fixes on the horizon? Our users rely on the ability to export so they can link to other files.

**Comment by jescorotero** [comment]
Hi I guess this problem was solved with last release v0.30.1

**Comment by nautilus28** [comment]
We are using v0.31.2 and still experiencing this issue.

**Comment by flamber** [comment]
Metabase version 0.32.6 was released yesterday and I cannot reproduce this issue on that version.
Related/duplicates: #6125 #9280

**Comment by nautilus28** [comment]
@flamber we upgraded to v0.32.5 and got some issues when dashboards stopped loading, so we have rollbacked to v0.31.2. Would you mind addressing some commits which are relevant to the fix?

**Comment by flamber** [comment]
@nautilus28 Pretty sure #9872 fixed this. But it's fixed in 0.32.6+, not 0.32.5

**Comment by tomasonjo** [comment]
Works for me, so I will just close it.
