### ISSUE TITLE
Chart and map messages when no results available

### ISSUE THREAD

**Issue by tewald** [metabase/metabase#6696]
Hi!

When there's no data available, the messages on charts and maps are confusing and/or irrelevant for final users.

Showing a "Select columns" or similar message is not very user friendly.

A default message of "No results", like is shown on query editing, would be more clear.

Your browser and the version: Chrome 63.0.3239.132
Your operating system: Fedora 27
Your databases: Postgres
Metabase version: 0.28.0-snapshot, hash: aa4728e
Metabase hosting environment: Fedora (running with java -jar)
Metabase internal database: H2

- Create a new question like below:
![bugged_01](https://user-images.githubusercontent.com/1534061/34889937-1ae5049a-f7b7-11e7-8a4c-778443904003.png)

- Add it to a new dashboard:
![bugged_02](https://user-images.githubusercontent.com/1534061/34889943-1e748cfc-f7b7-11e7-8270-74d8cb75bf7c.png)

- Limit results to 0, to simulate an empty result:
![bugged_03](https://user-images.githubusercontent.com/1534061/34889954-289e1e00-f7b7-11e7-9f4b-72a5589dde96.png)

- Save to update the query, and see the message on dashboard:
![bugged_04](https://user-images.githubusercontent.com/1534061/34889969-2f0394a0-f7b7-11e7-8f28-9672c9e94e6e.png)

- Example using pie chart:
![bugged_05](https://user-images.githubusercontent.com/1534061/34890179-0b625620-f7b8-11e7-9126-86314815c586.png)

**Comment by floushee** [comment]
Any updates on this?

**Comment by flamber** [comment]
Just to confirm on 0.33.6. This is specific to Native/SQL questions and maps on dashboard.
When the question is returning an empty result, then on the dashboard it give the following error:
`Please select region and metric columns in the chart settings`
I cannot reproduce the issue for pie chart anymore.

**Comment by flamber** [comment]
On 0.35.4 it now shows "No results!" on the dashboard for maps too - not sure when it was fixed.
![image](https://user-images.githubusercontent.com/1447303/83659252-937efc00-a5c3-11ea-8ed6-20e5f1949329.png)
