### ISSUE TITLE
[CrateDB driver] foreign keys is not supported

### ISSUE THREAD

**Issue by on99** [metabase/metabase#6699]
### Bugs
- Your browser and the version: Chrome
- Your operating system: mac os
- Your databases: crate
- Metabase version: 0.27
- Metabase hosting environment: docker
- Metabase internal database: MySQL

![image](https://user-images.githubusercontent.com/13196393/34904448-32ba8e1c-f881-11e7-9a54-d13e6ab9b452.png)

this issue is similar to the BigQuery one #2472

**Comment by on99** [comment]
Steps to reproduce

* Run crate `docker run -d -p 4200:4200 -p 4300:4300 -p 5432:5432 crate crate -Cnetwork.host=_site_`
* Create table and insert data
    * open admin console panel in `localhost:4200`
    * `create table a ( dimension_id string primary key, metric int );`
    * `create table b ( guid string primary key, name string );`
    * `insert into a (dimension_id, metric) values ('id', 1);`
    * `insert into b (guid, name) values ('id', 'human readable name');`
* Run metabase `docker run -p 3000:3000 -v ~/.metabase:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" --name metabase metabase/metabase`
* Setup crate in metabase by setting hosts to `172.17.0.3:5432/?user=crate` (ip address can be retrieved by `docker inspect --format '{{ .NetworkSettings.IPAddress }}' crate_container_name`)
* Setup data model in metabase of `doc` schema that table `a.guid` as foreign key to `b.guid`
* Ask question in metabase that view by `dimension`, it will throw exception

![image](https://user-images.githubusercontent.com/13196393/34907591-2172e358-f8bc-11e7-86d6-b6f7c8df1be4.png)

![image](https://user-images.githubusercontent.com/13196393/34907585-0ee1aabc-f8bc-11e7-9de8-0ba53ead5701.png)

**Comment by on99** [comment]
sorry i mistakenly closed the issue but it is not resolved

**Comment by on99** [comment]
ping @camsaul can you please take a look?

**Comment by salsakran** [comment]
paging @mikethebeer

**Comment by mikethebeer** [comment]
@on99 In short... CrateDB does not support foreign keys because of its eventual consistent approach. In general we recommend to use a denormalized table schema to avoid the approach of using foreign keys to connect two or more tables.

@salsakran If possible I would recommend to disable the ability to specify a `foreign key` type mapping in the Data Model in Metabase since this setting leads to this problem.

**Comment by on99** [comment]
@mikethebeer Yes I know that cratedb does not support foreign key, but what we want here is just `join`, not `foreign key`.

 I've also tried to enable `foreign key` feature just like the pull request did in #2569 but no luck, I got

```
02-02 22:42:27 ERROR sync.util :: Error syncing fields for Table 19 'doc.b': Output of table-metadata does not match schema:

	   {:fields #{{:database-type missing-required-key}}}
```

However, I am new to clojure, still reading metabase source code and trying to resolve this issue, though tough. 🤦‍♂️

**Comment by mikethebeer** [comment]
@on99 of course you are welcome to contribute this feature. Probably it might be also possible that you'll get some support from the Metabase engineering team. I would recommend to file up a PR with your feature enhancement so that they can take a look at your code and support you.

**Comment by on99** [comment]
@mikethebeer 🤦‍♂️ I just changed only one line of code to enable `foreign key` feature, and do not really know what the error log is about.

**Comment by on99** [comment]
ping @salsakran

**Comment by camsaul** [comment]
Hi everyone, starting with Metabase 0.32.0 we're removing the CrateDB driver from the core Metabase project and instead making it available as a community-supported driver. When you upgrade to Metabase v0.32.0+, you can download the Crate driver and see instructions to install it here: https://github.com/metabase/crate-driver. 

If you're still having problems with CrateDB, please open an issue at https://github.com/metabase/crate-driver/issues
