### ISSUE TITLE
Dropped columns not updated in data model after synching schema

### ISSUE THREAD

**Issue by key88sf** [metabase/metabase#6702]
Metabase 0.27.2
Postgresql 9.5.9

* Issued a "Sync database schema now" command.
* Metabase logfile indicated sync was completed (in 5 seconds)
* Tables in the "Data Model" section do not reflect columns that have been dropped. They only seem to pick up newly added columns.

**Comment by mvrabel** [comment]
@key88sf I have good news. See last comment of https://github.com/metabase/metabase/issues/6108
Quoting @senior "This issue was fixed by #6601 and will be included in the next release (probably 0.28.0 RC1)."

**Comment by salsakran** [comment]
we believe this was fixed in #6601 if you can try the RC at http://downloads.metabase.com/v0.28.0-RC2/metabase.jar
