### ISSUE TITLE
Error on visualization change of a question with SQL queries view only permission

### ISSUE THREAD

**Issue by lbalves** [metabase/metabase#6718]
First of all, thanks a lot for the project. I'm not a java developer, but I'll try to learn it so I can help you guys in the future. Until then, I'll try to help reporting bugs and discussing proposals. Great job!

### Context
As an metabase user, I want to explore questions which I have access to

### Problem
Changing the visualization on SQL questions raise an error, if the user has read only permission to SQL queries

### Steps to reproduce the error

- create a SQL question (mine uses parameters)
- create a user which is not an admin
- change the all users permission to that database to "can view raw queries" for SQL Queries
- access metabase with this user
- access the question
- change the visualization (the question is displayed on the new visualization without a problem)
- hit the "refresh" button
- receive an error ("You do not have read permissions for /db/2/native/." or "Sorry, you don’t have permission to see that.")

### Complementary info
Your browser and the version: Google Chrome 63.0.3239.132 (Official Build) (64-bit)
Your operating system: OSX 10.13.2 (17C88)
Your databases: MySQL and PostgreSQL
Metabase version: v0.27.2
Metabase hosting environment: Linux
Metabase internal database: H2

**Comment by camsaul** [comment]
Fixed by #15424
