### ISSUE TITLE
Saved Questions drop-down in Question interface shows archived questions

### ISSUE THREAD

**Issue by achesnais** [metabase/metabase#6727]
## Description

Currently, archived questions show up in the Saved Questions section of the Data drop down of the question builder.

I assume this is not intended behaviour, since as a result the Saved Question list becomes cluttered quite quickly. If this *is* intended behaviour, then we need a way to delete questions (#2783)  to ensure people can get to what they're looking for easily.

The above bug was reproduced both on the local Metabase Mac App as well as our hosted instance.

## System Info
Browser: Chrome 63/Mac App
OS: Ubuntu/OSX
Database: MySQL
Metabase v. 0.27.2 on both
Host: EC2/my computer
Internal DB: H2 on both

## Steps to reproduce – using sample datasets:

1. Create two questions.
2. Archive one of the questions
3. Go to the question builder -> Data -> Saved Questions and see both questions displaying equally without indication of one being archived.

See below screenshots from me reproducing with the sample dataset:

<img width="1112" alt="screen shot 2018-01-19 at 11 21 48" src="https://user-images.githubusercontent.com/6626105/35143724-0fadac0e-fd0b-11e7-9be3-c4dd068934c0.png">
<img width="1112" alt="screen shot 2018-01-19 at 11 21 53" src="https://user-images.githubusercontent.com/6626105/35143728-10fcf362-fd0b-11e7-8839-eb849e68d9f7.png">
<img width="1112" alt="screen shot 2018-01-19 at 11 21 58" src="https://user-images.githubusercontent.com/6626105/35143729-1255a164-fd0b-11e7-86ff-124ab229b29a.png">

**Comment by mazameli** [comment]
Reproduced this on the latest macOS app, as well as on master.
