### ISSUE TITLE
Grouping by Month generates broken SQL query for BigQuery

### ISSUE THREAD

**Issue by pshishkin** [metabase/metabase#6729]
- Your databases: BigQuery
- Metabase version: v0.27.2
- Metabase hosting environment: Docker
- Metabase internal database: i don't know

How to reproduce:
1. Use any BigQuery table with datetime field.
2. Try to create a question and use grouping by that field.
3. Change grouping mode to Month.
4. Query will fail (expected: not fail).

Example:
![2018-01-19_16-17-51](https://user-images.githubusercontent.com/14850937/35152993-b8b5b66e-fd35-11e7-91b2-907722f82582.png)

Broken code example:
`-- Metabase:: userID: 1 queryType: MBQL queryHash: 84312c35be2599726c0af83cbea31aa7a2f67c53fd0528b723c964221a9b1bef
SELECT count(*) AS [count], CAST(strftime_utc_usec(timestamp_to_usec([ds.mongo_facebook_page.col_date_added]), '%Y-%m-01') AS timestamp) AS [ds.mongo_facebook_page.col_date_added] FROM [ds.mongo_facebook_page] WHERE [ds.mongo_facebook_page.col_enabled] = TRUE GROUP BY [ds.mongo_facebook_page.col_date_added] ORDER BY [ds.mongo_facebook_page.col_date_added] ASC`

PS. Working good for Week grouping.

**Comment by camsaul** [comment]
This was fixed a while back, I can't find the exact PR, but verified it's working. Closing as unable to repro
