### ISSUE TITLE
Metabase -- Druid native query, can't use  Date Range filter:  'No valid fields'

### ISSUE THREAD

**Issue by IL-87** [metabase/metabase#6732]
I use Native query to create question in metabase to Druid:
I get all results correctly, but when I try to add **Date Range** filter to dashboard it just can't find timestamp and says: 'No valid fields'

Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Operating system: Windows 10
Metabase version: Metabase 0.27.2
Metabase hosting environment: Windows 10, java version "1.8.0_131"
Metabase internal database: mysql-5.6.38-winx64

My **Druid** query:

```
{
	"intervals": ["1900-01-01/2100-01-01"],
	"granularity": {
		"type": "period",
		"period": "P1D",
		"timeZone": "UTC"
	},
	"context": {
		"timeout": 60000
	},
	"queryType": "timeseries",
	"dataSource": "DCampaign",
	"aggregations": [{
		"type": "javascript",
		"name": "sum",
		"fieldNames": ["numOpens"],
		"fnReset": "function() { return 0 ; }",
		"fnAggregate": "function(current, x) { return current + (parseFloat(x) || 0); }",
		"fnCombine": "function(x, y) { return x + y; }"
	},
	{
		"type": "javascript",
		"name": "sum2",
		"fieldNames": ["numUniqueOpens"],
		"fnReset": "function() { return 0 ; }",
		"fnAggregate": "function(current, x) { return current + (parseFloat(x) || 0); }",
		"fnCombine": "function(x, y) { return x + y; }"
	}
	],
	"descending": false
}
```
Same problem even when I convert any working question in native query. 
**'No valid fields'**  for Date Range filter occurs too.
![metabase_native_q](https://user-images.githubusercontent.com/2452744/35169312-e9c31dbc-fd7d-11e7-990f-d08e85288b2e.png)

**Comment by qweed00** [comment]
any updates on this?

**Comment by flamber** [comment]
Metabase currently don't support filter variables for Native queries made in Druid.
#9184 - upvote by clicking :+1: on the first post
