### ISSUE TITLE
 Nested questions does not work with [with clause]

### ISSUE THREAD

**Issue by deFang** [metabase/metabase#6734]
Wherever there is a [with clause] in the sql, I simply cannot apply it to nested questions.

Example:
question looks like this:
with tmp_table as
(
select * from table_name
)
select * from tmp_table

-------

**Comment by flamber** [comment]
Hi @deFang 
I cannot reproduce your issue on 0.31.2 with MariaDB 10.2 or Postgres 11.2

**Comment by deFang** [comment]
Since it has been a long time, I don't have the environment now. You may just close this issue.
