### ISSUE TITLE
Newly added databases should be created with "No self-service" permissions - default permissions risks in strict data isolation contexts

### ISSUE THREAD

**Issue by achesnais** [metabase/metabase#6735]
Hi all :)

My organisation enforces some fairly strict data isolation, where it's really important for people to see only what they're supposed to see.

A few of Metabase's default behaviours have been proving a bit tricky to work with at times, so I figured I'd leave a note here to see if there was any way to remedy them in future releases:

1. ~~If a dashboard is empty, it is available to all users. I understand this is due to dashboards using the permissions of their Questions, but this leads to a slight information leak risk. For example, if I give my dashboard the name of a new client account, which is not supposed to be known to other teams (NDAs, etc) and save before adding a question, there is a small window of time when this information is available to everyone. Right now the only counter measure is to teach all MB users not to do this.~~ Fixed in 0.30 by the new Collection permissions

2. New databases available to all users by default. Same problem as above. If I add a database connection, there is a small window of time between its creation and my setting new permissions for it where theoretically anyone can access its data. My current workaround is to first set up the connection to a dummy database, set its permissions and then update the database connection information to the actual datasource. I'm okay with this for now, but wanted to raise as it could bite someone in the future. It would be nice to have a button in the New Database wizard where we can choose whether to make the database available to the All Users group, or better even, directly choose which groups should have permissions for it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Point 1 is not relevant anymore (0.30+), since dashboards follow the permissions of the collection.

**Comment by nemanjaglumac** [comment]
@flamber - can I simply reproduce this in Cypress by logging in as a normal user and asserting that (by default) Sample Dataset **shouldn't** be visible?

**Comment by xgdgsc** [comment]
Can non-admin users add their own database connections? Why do I have to be administrator to add database connections for now?

**Comment by xgdgsc** [comment]
If  you allow the permission of connecting to databases to normal users. Provide a permission model like https://github.com/star7th/showdoc does. There would be no problem.

**Comment by flamber** [comment]
@xgdgsc Your request is unrelated to this issue. You are probably looking for #6799 or #13091, otherwise open a new request.

**Comment by Leen15** [comment]
Any update on this?

**Comment by luizarakaki** [comment]
We resolved this on v50. The solution is not exactly the proposed by OP.
Our approach:
When new databases and new groups are added, they inherit the minimum permission level of all other databases or groups.

If any database is `blocked` for a group, the new database is also `blocked`.
If all databases are `unrestricted` for a group, the new database is also `unrestricted`
