### ISSUE TITLE
Can't rename or archive collections with dashes in name

### ISSUE THREAD

**Issue by achesnais** [metabase/metabase#6737]
## Situation:

It seems that using em dashes (–)  in Collection names prevents the curation buttons from appearing, making it impossible to rename or archive the collection.

## Steps to reproduce (using the Metabase Mac app):

1. Create a collection containing an em dash in the name, e..g "Collection – 1"
2. Open the Collection, and notice the name of the collection isn't showing, nor are the curation buttons. See screens below:

- Collections:
<img width="1084" alt="screen shot 2018-01-22 at 11 43 48" src="https://user-images.githubusercontent.com/6626105/35214467-ee389e6a-ff69-11e7-9eef-5a3f5bca7efc.png">

- Normal name:
<img width="1112" alt="screen shot 2018-01-22 at 11 43 52" src="https://user-images.githubusercontent.com/6626105/35214481-f76a9182-ff69-11e7-9cc8-424ee6a931c7.png">

- Hyphen:
<img width="1112" alt="screen shot 2018-01-22 at 11 43 54" src="https://user-images.githubusercontent.com/6626105/35214486-fc191b86-ff69-11e7-8933-cffd1c9a897f.png">

- em dash:
<img width="1112" alt="screen shot 2018-01-22 at 11 43 56" src="https://user-images.githubusercontent.com/6626105/35214489-00583cfe-ff6a-11e7-9301-f5199ffffe23.png">

## System information – reproduced both on Mac App and our hosted instance:

Browser: Chrome and Mac App
OS: Ubuntu / OSX
DB: MySQL/NA
Version: 0.27.2
Hosting env: EC2/Mac App
Internal DB: H2

**Comment by camsaul** [comment]
Confirmed this is no longer an issue on Metabase 0.32.0-SNAPSHOT. The various Collection views have changed quite a bit since 0.27.x and the new ones don't seem to have this issue any more

**Comment by briedis** [comment]
Sorry, I'm not sure if this is related. I'm unable to rename a personal collection. A user changed their name, but the collections name is the old one and there is no way to rename it.
![image](https://user-images.githubusercontent.com/500491/58476411-5afb4580-8159-11e9-9b8e-96c6088beae9.png)

I'm an admin and I can't seem to find a place where to do it.
