### ISSUE TITLE
Restrict emails that can be scheduled to receive pulses

### ISSUE THREAD

**Issue by thalesmello** [metabase/metabase#6744]
I have interest on using Metabase, particularly for its capacity of scheduling pulses to deliver reports to specific e-mail adresses. That's great.

However, I'd like to whitelist my users to only schedule deliveries to email addresses that match certain criteria.

For example, if work at megacorp.code,

user john@megacorp.code should be able to schedule a pulse to ann@megacorp.code, but not to another@competitor.com

Is there any feature that allows this that I'm missing? I couldn't even find options to restrict who can create alerts or pulses. Couldn't find any other issue talking about this, so I decided to create this one.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jornh** [comment]
> I couldn't even find options to restrict who can create alerts or pulses. 

Current thinking on this briefly mentioned in: http://discourse.metabase.com/t/improve-user-permission-dashboard/2766/4

**Comment by luizarakaki** [comment]
@flamber is this closed by https://github.com/metabase/metabase/pull/17897?
