### ISSUE TITLE
Display original schema and human version

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#6745]
on the page "datamodel", when editing a table, is it possible to display the original name of a field and the name "translated" next to each other?

**Comment by flamber** [comment]
Hi @Philippe-M 
This is a duplicate of #1611 - but was really difficult to find, since says "metadata" instead of "data model".
But definitely something I would really like - please go and upvote by clicking :+1:

**Comment by mazameli** [comment]
Closing as duplicate
