### ISSUE TITLE
Change jointure type

### ISSUE THREAD

**Issue by Philippe-M** [metabase/metabase#6747]
I have two tables, SINVOICE and SINVOICEV. SINVOICEV is linked to SINVOICE by SINVOICEV.NUM and SINVOICE.INVNUM. In the "datamodel", for sinvoicev I said that the invnum is a foreign sinvoice key.

When I create a question starting from sinvoicev, I give the filter conditions and I want to add a sum to the sinvoice.amtnot field.

The query obtained is
```
SELECT sum("SINVOICE__via__NUM_0"."AMTNOT_0") AS "sum"
FROM "xxxx"."SINVOICEV"
LEFT JOIN "xxxx"."SINVOICE" "SINVOICE__via__NUM_0" ON "xxxx"."SINVOICEV"."NUM_0" = "SINVOICE__via__NUM_0"."INVNUM_0"
WHERE ("xxxx"."SINVOICEV"."REP_0" = ?
   AND trunc("xxxx"."SINVOICEV"."INVDAT_0", 'dd') BETWEEN trunc(?, 'dd') AND trunc(?, 'dd'))
```

The problem is that I get no results while there are. Moreover the left join is not suitable in this case. I should be able to do an inner join. Is it possible to modify this directly from the visual editor?

**Comment by salsakran** [comment]
We don't offer joins within the visual editor https://www.metabase.com/blog/Joins/index.html
We suggest that if your end users need to see joined data you create a sql question with the appropriate data and then let them use the visual interface on that as a nested question as described in https://www.metabase.com/blog/Nested-Queries/index.html
