### ISSUE TITLE
Field Filter not working with View

### ISSUE THREAD

**Issue by lucasloami** [metabase/metabase#6748]
Hi, first of all, thanks for the amazing application! I'm using Metabase in a professional project and I'm loving it. Really want to see this project get bigger and bigger. 

Second, here's my problem. I created a small data mart in a PostgreSQL database and it has a dimensional table called **dim_discipline**, that contains 15 items. I would like to use a subset of this table in a Field Filter, but metabase always returns the entire values of the table. 

My solution was to create a View in PostgreSQL with the subset of data from **dim_discipline** and use this View (called **vw_discipline**) as a Field Filter in my query. In this solution, my query became:

```sql
SELECT AVG(ft.ranking) AS average, dt.year AS year 
FROM my_fact_table ft
LEFT JOIIN vw_discipline vd ON vd.id  = ft.dim_discipline_id
WHERE 1=1
[[AND vd.name LIKE CONCAT('%', {{discipline_name}}, '%')]]
GROUP BY dt.year
ORDER BY dt.year ASC
```

The variable {{discipline_name}} is used as Field Filter and display properly the subset of data I wanted. However, when I select some value in the Filter and try to "Get Answer" again, Metabase returns the error "ERROR: missing FROM-clause entry for table 'vw_discipline'. Hint: [...]"

I thought the problem was the syntax in my query, however, when I changed it to the version below (without filter) it worked:

```sql
SELECT AVG(ft.ranking) AS average, dt.year AS year 
FROM my_fact_table ft
LEFT JOIIN vw_discipline vd ON vd.id  = ft.dim_discipline_id
WHERE 1=1
AND vd.name LIKE '%DISCIPLINE_NAME%'
GROUP BY dt.year
ORDER BY dt.year ASC
```

I investigated the Metabase logs but it only displays this error. Is there some validation Metabase is doing that is not clear for me? Is also tried to find some answer in this forum and in the `Metabase discourse` but nothing seemed to help me =/

**Comment by doodlebro** [comment]
>LEFT JOIIN vw_discipline vd ON vd.id  = ft.dim_discipline_id

Is something adding an extra 'I' to JOIIN here?

**Comment by salsakran** [comment]
What do you mean by `I would like to use a subset of this table in a Field Filter, but metabase always returns the entire values of the table.`? 

What SQL is being generated (this should be in the server logs) from that template? 

Also, field filters are intended to be used to replace the entire filter clause, eg 
```
SELECT AVG(ft.ranking) AS average, dt.year AS year 
FROM my_fact_table ft
LEFT JOIIN vw_discipline vd ON vd.id  = ft.dim_discipline_id
WHERE 1=1
[[AND {{discipline_name}}]]
GROUP BY dt.year
ORDER BY dt.year ASC
```
is the expected usage, where you would then use our string filter widgets to let your users filter things. If you want to get just a string inserted, you should use the Text type and not the Field Filter type.

**Comment by salsakran** [comment]
related #6820

**Comment by lucasloami** [comment]
I figured out the problem. It seems Metabase can’t understand very well table aliases when they are used without double quotes. This only happens when using Field Filters. So, my solution was to change my query to contain all the information about the table, considering the Schema, Table Name, Column Name and put everything between double quotes.

Hope this can help other people with similar issue =)

**Comment by corytu** [comment]
My Metabase version is v0.30.3. I am encountering the same problem, but double quotes are not solving it. My query now looks like:

```sql
SELECT count(distinct "public"."dashboard_demographic_view"."id") AS "count"
FROM "public"."dashboard_demographic_view"
WHERE {{clinic_name}}
```

You can see from my screenshot that the field filter doesn't appear even though the double quotes are added (the url and the query result are masked):

![2018-10-16 15 08 48](https://user-images.githubusercontent.com/19487370/46998725-fd7c3080-d155-11e8-90d1-2a5d9edbb858.png)

**Comment by shanemgrey** [comment]
One factor in the issue is that it seems Metabase requires the table that is the source of the options available in the selection box of the filter to be the same as the table that will be filtered by the selection.

I'll restate what @lucasloami suggests, when referencing a table (or maybe only view, since I'm also running into this with a view and haven't tested with a table) using the Field Filter

The error from postgres suggests to reference the alias that you are using in the SQL.  But since there is no way to reference by alias in the selection process for setting the Field Filter, a workaround is to simply do away with the alias in the SQL code and instead use the full table name.

It doesn't seem to be necessary to put the schema and double quoting in place.  Just to not use an alias.


``` sql
SELECT
    pv.*
FROM
    person_view pv
WHERE   
    {{active}}
```

becomes 

``` sql
SELECT
    person_view.*
FROM
    person_view
WHERE
    {{active}}
``` 

And then when you choose the source of your field filter, you choose the person_view table, and the active field.

I'd consider this a bug since the error is not suggesting a solution that is possible in the UI.

I think the issue should be reopened. Pinging @salsakran 

While removing aliases does allow it to work, having aliases is pretty useful for readable SQL.

A working solution would allow aliases to be used, and the field filter functionality in the background would understand the link between the alias used in the SQL, and the full table name in the widget selection box.  It would then query the DB correctly to avoid the error.

**Comment by agoud1993** [comment]
I'm experiencing the same issue of not able to create a field filters for some columns. I'm unable to create a field filter for column "projectalias" in this particular query. Please view the image with the code I've written to fix this Bug. 
Are there any suggestions to fix this Bug?
Thanks in Advance!
![metabase error filter](https://user-images.githubusercontent.com/45699622/49673014-0c3ae180-fa3b-11e8-8a5a-a4288f20a88d.PNG)

**Comment by agoud1993** [comment]
> One factor in the issue is that it seems Metabase requires the table that is the source of the options available in the selection box of the filter to be the same as the table that will be filtered by the selection.
> 
> I'll restate what @lucasloami suggests, when referencing a table (or maybe only view, since I'm also running into this with a view and haven't tested with a table) using the Field Filter
> 
> The error from postgres suggests to reference the alias that you are using in the SQL. But since there is no way to reference by alias in the selection process for setting the Field Filter, a workaround is to simply do away with the alias in the SQL code and instead use the full table name.
> 
> It doesn't seem to be necessary to put the schema and double quoting in place. Just to not use an alias.
> 
> ```sql
> SELECT
>     pv.*
> FROM
>     person_view pv
> WHERE   
>     {{active}}
> ```
> 
> becomes
> 
> ```sql
> SELECT
>     person_view.*
> FROM
>     person_view
> WHERE
>     {{active}}
> ```
> 
> And then when you choose the source of your field filter, you choose the person_view table, and the active field.
> 
> I'd consider this a bug since the error is not suggesting a solution that is possible in the UI.
> 
> I think the issue should be reopened. Pinging @salsakran
> 
> While removing aliases does allow it to work, having aliases is pretty useful for readable SQL.
> 
> A working solution would allow aliases to be used, and the field filter functionality in the background would understand the link between the alias used in the SQL, and the full table name in the widget selection box. It would then query the DB correctly to avoid the error.
@shanemgrey I'm facing this issue with using a table from postgres dataset. I've tried using "double quotes", chema, and table name in the query. But, I didn't fix the issue. 
Are there any upcoming releases to address this issue?

I'm currently using 0.30.1 version. Please give suggestions to address this issue

**Comment by MchlUh** [comment]
> I figured out the problem. It seems Metabase can’t understand very well table aliases when they are used without double quotes. This only happens when using Field Filters. So, my solution was to change my query to contain all the information about the table, considering the Schema, Table Name, Column Name and put everything between double quotes.
> 
> Hope this can help other people with similar issue =)

Hi @lucasloami I think I am encountering the same issue as you did.
I would like to add information about the table, but I don't really see how to do it technically, do you put it in the {{}}.
Ex : {{table_name."columnName"}} ? 
I tried that but am not successful.

**Comment by flamber** [comment]
Metabase does not support table aliases, when using Field Filters - #3324 upvote by clicking :+1: on the first post
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by ahmoura** [comment]
I had the same issue, somehow Metabase (v0.47.6) was not supporting my query with Field Filter.
I had a query like:
```sql
SELECT * 
FROM mytable 
WHERE 
  TRUE 
  [[AND {{ff}}]]
```

Somehow it worked when I set it with `WITH` clause:
```sql
WITH mysubq AS (
  SELECT * 
  FROM mytable 
  WHERE 
    TRUE 
    [[AND {{ff}}]]
)
SELECT * FROM mysubq
```
