### ISSUE TITLE
Remove unused DB tables from schema

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#675]
We don't use this model anymore so let's make our schema slightly cleaner. Check the other tables too I think there's one or two others we're not using any more

**Comment by salsakran** [comment]
is the old table for segments still in the code base?

figure we should either delete it or if we're reusing the name, we should close this.

**Comment by camsaul** [comment]
@salsakran there's lots of old tables (12 or so) in the DB that go unused, like `core_organization`, `core_userorgperm`, `report_dashboardsubscription`, `report_emailreport`, etc.

**Comment by camsaul** [comment]
I think all of the following can be deleted:

*  `annotation_annotation`
*  `core_organization`
*  `core_permissionsviolation`
*  `core_userorgperm`
*  `metabase_foreignkey` 
*  `metabase_tablesegment`
*  `query_query`
*  `report_dashboardsubscription`
*  `report_emailreport`
*  `report_emailreport_recipients`
*  `report_emailreportexecutions`

I'm sick of looking at them in pgAdmin 4, removing them should be pretty easy, and they confuse potential contributors (e.g. #2225).
