### ISSUE TITLE
connectionAttributes issue with MySQL.

### ISSUE THREAD

**Issue by Neeks00** [metabase/metabase#6751]
Hi,

I tried to use:
 
![image](https://user-images.githubusercontent.com/35530650/35286259-c5e7f478-005f-11e8-9722-1471975c9b26.png)

in the JDBC connection string cause i want to have all date in French format.
It didn't work and i don't know if i do something wrong or if it's a bug from Metabase.

I tried many other things like:

enableSsl:true 

which did nothing too.
I'm out of solution, any advice ?

- Your browser and the version: Chromium 63.0.3239.84 and Firefox 57.0.4
- Your operating system: Ubuntu 16.04 LTS
- Your databases: MySQL 5.5
- Metabase version: Metabase 0.27.2
- Metabase hosting environment: Docker
- Metabase internal database: H2

**Comment by flamber** [comment]
The correct connection string would be `sessionVariables=lc_time_names='fr_FR'`
