### ISSUE TITLE
Don't remove non-locked filters on embedded dashboards when value comes from JWT token

### ISSUE THREAD

**Issue by tewald** [metabase/metabase#6752]
Hi,

I have an embedded dashboard with 3 filters, one is locked and receives a string value.
The other 2 are date values, enabled (editable), and should come preset with a default value (last 30 days, 90 days, so on).
The problem is that filter values coming via JWT token are removed from the dashboard, but I like to give the user the option to change the dates afterwards.

I did get a look at the code, but my clojure skills are nil. :-(

**Comment by tlrobinson** [comment]
I'm pretty sure you can accomplish the same thing by passing an initial value in the URL query string. e.x. in the sample code instead of

```javascript
var iframeUrl = METABASE_SITE_URL +
  "/embed/dashboard/" + token +
  "#bordered=true&titled=true";
```

you'd do something like

```javascript
var iframeUrl = METABASE_SITE_URL +
  "/embed/dashboard/" + token +
  "?parameter_name=" + encodeURIComponent(parameterValue) +
  "#bordered=true&titled=true";
```

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4, but it's likely the same problem as #7120 with default value is only applied to the last editable filter.
