### ISSUE TITLE
Master is loading extremely slowly on Elastic Beanstalk

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6755]
Seeing really slow initial page load times on AWS Elastic Beanstalk

![screen shot 2018-01-23 at 5 28 27 pm](https://user-images.githubusercontent.com/107439/35310098-993ea87c-0064-11e8-842b-a8ff4fc4b544.png)

Older versions on heroku seem pretty performant

![screen shot 2018-01-23 at 5 28 27 pm](https://user-images.githubusercontent.com/107439/35310101-a1d96d8c-0064-11e8-950a-ca0a2da2fd29.png)

**Comment by salsakran** [comment]
This seems intermittent. I'm inclined to think it's an ec2 or beanstalk issue rather than the codebase. Will test w/ Heroku and a fresh beanstalk install later today to try to narrow down possible causes.

**Comment by camsaul** [comment]
@salsakran any updates on this?

**Comment by mbvictoria** [comment]
Closing - no longer an issue.
