### ISSUE TITLE
Line/Area visualization improperly maps columns when returning results (Redshift backend)

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#6760]
Hi Team,

I run Metabase over a redshift instance and have recently run into a strange bug.

I created a monthly view with 3 metrics. Querying the view directly using the simple "Table" visualization in Metabase works as I expect:
![screen shot 2018-01-24 at 10 08 35 am](https://user-images.githubusercontent.com/7634378/35346406-683c5d4c-00ef-11e8-93b6-db22fe5e4c0c.png)

When I adjust the visualization type to "Line" or "Area," the bug starts happening...

Line Example 1 (churn percent is correct for the displayed date, however other values are not):
![screen shot 2018-01-24 at 10 09 19 am](https://user-images.githubusercontent.com/7634378/35346450-836257ca-00ef-11e8-912f-3c807bf57035.png)

Line Example 2 (churn percent is correct for the displayed date, however other values are not):
![screen shot 2018-01-24 at 10 09 30 am](https://user-images.githubusercontent.com/7634378/35346521-b43cd492-00ef-11e8-856f-8fb308a8c021.png)

Area Example (churn percent still correct, other values appear to map slightly differently than in the line examples):
![area_example](https://user-images.githubusercontent.com/7634378/35346565-d1e62322-00ef-11e8-871a-500429a7ff3b.png)

When I switch to "Bar," things look good again...

Bar Example 1:
![screen shot 2018-01-24 at 10 09 58 am](https://user-images.githubusercontent.com/7634378/35346646-0d742d8a-00f0-11e8-9b68-eecefc18b02c.png)

Bar Example 2:
![screen shot 2018-01-24 at 10 10 05 am](https://user-images.githubusercontent.com/7634378/35346674-19c45d9e-00f0-11e8-935c-171ccd66561f.png)

Let me know if more information/examples are needed to track this down. Thanks.

**Comment by salsakran** [comment]
What version of Metabase are you on? We fixed something like this in 0.27

**Comment by doodlebro** [comment]
@salsakran: 0.27.2 currently

**Comment by jornh** [comment]
@doodlebro Try taking 0.28.0-RC3 from either https://hub.docker.com/r/metabase/metabase/tags/ or http://downloads.metabase.com/v0.28.2-RC3/metabase.jar for a spin and see if it’s the same problem as reported in https://github.com/metabase/metabase/issues/6401

**Comment by doodlebro** [comment]
Not sure what changed, but I'm on 0.28.1 now and this bug appears to be gone. Thanks for working to get those two versions out @salsakran!
