### ISSUE TITLE
Inconsistent bar width

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6763]
When there is only one bar the width is inconsistent with the width implied by the axis markers.
<img width="495" alt="screenshot 2018-01-23 15 24 33" src="https://user-images.githubusercontent.com/178038/35350439-cbb85d46-00f2-11e8-9095-9f7c27f99fa6.png">

**Comment by flamber** [comment]
I'm fairly sure this has been fixed several versions ago, but not sure how to reproduce...
