### ISSUE TITLE
Heatmap legend is not binned and can overflow

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6766]
<img width="413" alt="screenshot 2018-01-23 14 58 54" src="https://user-images.githubusercontent.com/178038/35351220-1b376ea0-00f5-11e8-9067-c9e4116677ab.png">
Ideally this would use the same bin rounding approach we use elsewhere and sensibly truncate the values (eg. 8.4k, 120k, 0.5M, ...)

Related issue, when the upper bound = lower bound, the value should not be written as a range:
<img width="405" alt="screenshot 2018-01-24 10 58 10" src="https://user-images.githubusercontent.com/178038/35351386-9946a248-00f5-11e8-9263-d4e206779a6f.png">

**Comment by salsakran** [comment]
this is a strange regression and is really annoying.

**Comment by paulrosenzweig** [comment]
Resolved by #10654
