### ISSUE TITLE
World map doesn't work with GA data

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6768]
The heatmap range is calculated correctly, but no countries are coloured:
<img width="1262" alt="screenshot 2018-01-24 11 15 13" src="https://user-images.githubusercontent.com/178038/35352144-e016982a-00f7-11e8-9411-4dfa4613812e.png">
The data looks to be in correct shape (might be that the `(not set)` is tripping it up)
<img width="725" alt="screenshot 2018-01-24 11 16 38" src="https://user-images.githubusercontent.com/178038/35352202-12a5ceb4-00f8-11e8-88fd-b5d9c4bf0058.png">

If ISO codes are used it works, but that is somewhat unintuitive.

**Comment by jornh** [comment]
Dupe of #4897 

... but this one has better title and a illustrative screenshots, OTOH in #4897 @salsakran seem to have figured out the problem

**Comment by dudduss** [comment]
Has this been resolved yet

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
