### ISSUE TITLE
Area chart incorrectly displays nil values

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6770]
<img width="1259" alt="screenshot 2018-01-24 14 24 39" src="https://user-images.githubusercontent.com/178038/35360377-62f06d7e-0112-11e8-92b6-2d3fb3287b04.png">
<img width="533" alt="screenshot 2018-01-24 14 25 57" src="https://user-images.githubusercontent.com/178038/35360424-81a31d8e-0112-11e8-98db-44bc56d9fcdd.png">

**Comment by alxnddr** [comment]
It seems to be fixed
<img width="1438" alt="Screen Shot 2021-06-18 at 17 05 09" src="https://user-images.githubusercontent.com/14301985/122573332-5911c100-d057-11eb-8a39-ccc95286631e.png">
