### ISSUE TITLE
Minute of Hour display seems broken

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6772]
For the sample dataset all the "minute of the hours" are being displayed as `Midnight Thursday Jan 1, 1970`

![screen shot 2018-01-24 at 2 53 29 pm](https://user-images.githubusercontent.com/107439/35361516-7fb0c8ba-0116-11e8-9753-bc8c85f50469.png)

**Comment by flamber** [comment]
Hi @salsakran 
I cannot reproduce this issue on 0.31.2 - even tried with a Saved Question from SQL on Postgres.

**Comment by flamber** [comment]
Closing, since I cannot reproduce on 0.34.3 either
