### ISSUE TITLE
[Bug] Sorting on date defaults to day granularity ( regression of #2531 ? )

### ISSUE THREAD

**Issue by coussej** [metabase/metabase#6780]
- Your browser and the version: (Chrome 63.0)
- Your operating system: (OSX 10.13)
- Your databases: (Postgres)
- Metabase version: (0.27.2)
- Metabase hosting environment: (Ubuntu 16.04)
- Metabase internal database: (h2)

=> possible regression of #2531

**Steps to reproduce** : Ask a question with a datetime field in the result and try to sort on that field. The granularity defaults to day and there is no way to change that, while the field itself has a higher precision. There are no filters on that field and no group by's:

**Expected behaviour**: To be able to just sort on the field without a specific granularity, or to be able to change the granularity.

![image](https://user-images.githubusercontent.com/9944663/35403475-204ad056-0200-11e8-82b7-178d4c80e57a.png)

**Comment by valtlfelipe** [comment]
I'm having the same issue. Any update on this ?

**Comment by collegeimprovements** [comment]
Same issue for us as well.

**Comment by themodio** [comment]
I'm having the same issue. Strangely, I 'tricked' a question grouped by month to sort by month, but have no idea now I did it or how to recreate it.

Sorting by days is my only options on date related grouping.

**Comment by dideler** [comment]
Having the same issue with v0.29.3 and v0.30.1.

Cannot select granularity when sorting results via the ellipsis button. It defaults to "Day", which causes errors when the grouping has a different granularity (e.g. "Hour").

One time I was able to select granularity, but I don't know what I did differently. After editing the Question, I was no longer able to select granularity anymore.

**Comment by Crusader4Christ** [comment]
Same error. Why I can`t select granularity on order?

**Comment by flamber** [comment]
I cannot reproduce this on 0.31.2 with Postgres 11.2. Are you still having this issue?

When selecting the field, I get no options of granularity, as expected.
![image](https://user-images.githubusercontent.com/1447303/53277543-006dcb80-36ca-11e9-8652-cd94fbed370e.png)

And clicking "View the SQL" doesn't do any casting/formatting:
```SQL
ORDER BY "sampledata"."orders"."created_at" ASC
```

**Comment by mazameli** [comment]
I also can't reproduce this on postgres or otherwise in 0.33. I'll reopen if folks are still hitting this.

![image](https://user-images.githubusercontent.com/2223916/67523885-600ae500-f664-11e9-9f9c-786026e2a91d.png)

![image](https://user-images.githubusercontent.com/2223916/67523897-6731f300-f664-11e9-9fc1-f166528ce3fb.png)
