### ISSUE TITLE
i18n regressions for 0.29

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6781]
A collection of places where we mucked up the tags that should be fixed

- [x] Setup process sync controls
![screen shot 2018-01-25 at 11 03 23 am](https://user-images.githubusercontent.com/107439/35407046-72fc0e6e-01bf-11e8-89e8-9adb421b57aa.png)

**Comment by salsakran** [comment]
Viz Settings Modal tabs are being generated from some wacky code path I couldn't trace. 

![screen shot 2018-01-30 at 7 17 47 pm](https://user-images.githubusercontent.com/107439/35603446-4629dda8-05f2-11e8-9af0-1ea1f1892414.png)

**Comment by salsakran** [comment]
Row colors (and presumably others) aren't internationalized

![screen shot 2018-01-30 at 7 18 24 pm](https://user-images.githubusercontent.com/107439/35603471-5d8ddcce-05f2-11e8-990a-20ab77224549.png)

**Comment by salsakran** [comment]
Pulse create/edit form has some stragglers
![screen shot 2018-01-30 at 7 19 23 pm](https://user-images.githubusercontent.com/107439/35603506-865ae7a0-05f2-11e8-8ae4-b524e63d155e.png)

**Comment by salsakran** [comment]
Pulse list has some stragglers as well 
![screen shot 2018-01-30 at 7 20 13 pm](https://user-images.githubusercontent.com/107439/35603539-a4c74774-05f2-11e8-864a-0b507e5a8ad3.png)

**Comment by salsakran** [comment]
Humanized names aren't internationalized 
![screen shot 2018-01-30 at 7 20 47 pm](https://user-images.githubusercontent.com/107439/35603557-b8753998-05f2-11e8-95fc-5f411fde8641.png)

**Comment by salsakran** [comment]
Question Archive heading
![screen shot 2018-01-30 at 7 21 16 pm](https://user-images.githubusercontent.com/107439/35603567-c7b5549c-05f2-11e8-971a-2f06e71dd6da.png)

**Comment by salsakran** [comment]
- [x] collections create modal cancel button

![screen shot 2018-01-30 at 7 23 24 pm](https://user-images.githubusercontent.com/107439/35603636-14dd4f0e-05f3-11e8-887b-4d9d7cc0f629.png)

**Comment by salsakran** [comment]
PermissionsGrid Column header gets the group via some convoluted code path
![screen shot 2018-01-30 at 7 31 13 pm](https://user-images.githubusercontent.com/107439/35603857-305340f8-05f4-11e8-9877-3c90ab89d58f.png)

**Comment by salsakran** [comment]
"None" collection target for moving collections isn't internationalized
![screen shot 2018-01-30 at 7 32 28 pm](https://user-images.githubusercontent.com/107439/35603875-584c9762-05f4-11e8-84a1-b00716029491.png)

**Comment by salsakran** [comment]
Number of tables in data collection sidebar not internationalized
![screen shot 2018-01-30 at 7 33 57 pm](https://user-images.githubusercontent.com/107439/35603911-8ecd9426-05f4-11e8-8b00-66f10c2be5a0.png)

**Comment by salsakran** [comment]
admin checklist entries on home page not internationalized 
![screen shot 2018-01-30 at 7 35 23 pm](https://user-images.githubusercontent.com/107439/35603953-c1bece5e-05f4-11e8-838e-f5e152ae397f.png)

**Comment by salsakran** [comment]
user settings password hints 
![screen shot 2018-01-30 at 7 35 59 pm](https://user-images.githubusercontent.com/107439/35603974-d5e1a546-05f4-11e8-82d9-85a484e63dba.png)

**Comment by mazameli** [comment]
Note to self that we'll also want to double check tooltips.

**Comment by camsaul** [comment]
are all these things that aren't done yet regressions? (meaning they were done at some point?)

**Comment by salsakran** [comment]
I'm mixing metaphors. Originally it was for things like tags that stopped working, now I'm just using this as a dumping ground of missing i18n .

**Comment by mazameli** [comment]
Dangling dollar sign in the add person confirmation dialog:

<img width="496" alt="add-person" src="https://user-images.githubusercontent.com/2223916/35706309-1e949ad0-075a-11e8-8048-efe84b518da6.png">

**Comment by salsakran** [comment]
related: #6837 #6759

**Comment by salsakran** [comment]
@tlrobinson the # of tables in the data reference is being capitalized via `inflection.inflect`
What do you think we should be doing wrt to internationalized plurals?

**Comment by salsakran** [comment]
Expired invites -

![screen shot 2018-02-13 at 5 30 42 pm](https://user-images.githubusercontent.com/107439/36183586-b6a81616-10e3-11e8-9d10-c6c0dda0e11b.png)

**Comment by tlrobinson** [comment]
Found a few more with this regex:

```
(`[^{}]+<\w+|\w+>[^{}]+`)
```

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/tutorial/QueryBuilderTutorial.jsx#L88
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/tutorial/QueryBuilderTutorial.jsx#L110
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/tutorial/QueryBuilderTutorial.jsx#L138
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/tutorial/QueryBuilderTutorial.jsx#L155
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx#L61

**Comment by tlrobinson** [comment]
New question empty state for metrics:

<img width="459" alt="screen shot 2018-02-15 at 4 33 18 pm" src="https://user-images.githubusercontent.com/18193/36249668-f82e0362-126d-11e8-95a4-2080a8c96e89.png">

**Comment by salsakran** [comment]
closing since most of these are done, and we'll treat regressions as they come.
