### ISSUE TITLE
Dashboard listing probably has an N+1 query somewhere

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6782]
Seeing 
`Jan 25 20:31:49 DEBUG metabase.middleware :: GET /api/dashboard 200 (2 s) (120 DB calls)` 
on a dashboard listing for 37 dashboards.

**Comment by camsaul** [comment]
@salsakran this should have been fixed by #6945. Can you verify that you're no longer seeing this issue?

**Comment by mbvictoria** [comment]
Closing - fixed.
