### ISSUE TITLE
Editable dashboard parameters causing 400 when embedding

### ISSUE THREAD

**Issue by alvaroc1** [metabase/metabase#6783]
I have a dashboard with 2 parameters:
- equipment: int (locked)
- 7_days_ending_on: date (editable)

The dashboard works fine when using it within the metabase UI.

When embedding (previewing), the charts inside it say: 
`Unknown parameter 7_days_ending_on`.

I can see a couple of http requests going out to this URL producing a 400 with the same "Unknown param..." response:
https://metabase.rovitracker.com/api/preview_embed/dashboard/eyJh.../dashcard/19/card/14?7_days_ending_on=2018-01-10

Same thing is happening when I actually embed the report in our own site. 

Embedding works fine all the way through if I make both parameters **locked**.

- Your browser and the version: Chrome 63
- Your operating system: OSX
- Your databases: Redshift
- Metabase version: 0.27.2 and 0.28.0.RC1
- Metabase hosting environment: jar file on EC2 instance
- Metabase internal database: MySQL

**Comment by camsaul** [comment]
Turns out our middleware that automatically converts query GET params to a map only makes the keys keywords if they pass some sort of "looks like it should be a keyword test", and keys that start with numbers do not. So this only affects parameters whose name starts with a number.

**Comment by alvaroc1** [comment]
@camsaul I have confirmed that removing the number works as a workaround in the current version until the fix makes it in. Thanks!

**Comment by salsakran** [comment]
fixed via #6856
