### ISSUE TITLE
Circle tests fail with memory limits exceeded

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6790]
These errors appear to be happening more frequently lately making it difficult to get a green build before or after a PR merge. An example of the error can be found [here](https://circleci.com/gh/metabase/metabase/15557#tests/containers/5).

**Comment by camsaul** [comment]
To clarify this is with the browser-based tests, right?

**Comment by senior** [comment]
@camsaul I think so. It's always cell 5 if it happens and Circle includes the error "Your build has exceeded the memory limit of 4G on 1 container". The link in the description has a typical example.
