### ISSUE TITLE
Questions List Performance sucks with very large numbers of Questions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6792]
Eg for an instance with 9000 saved questions, it takes 15 seconds to download the list, and then rendering locks up the browser for a significant time. 

We should at the very least virtualize this list and the search results, and in an ideal world move to some sort of paging.

**Comment by attekei** [comment]
Yeah, some notes about the data loading:
- `/api/card` endpoint is super slow, and it seems that the time it takes is pretty much the same regardless of the active filtering (according to server logs, ~500ms per endpoint call on https://stats.metabase.com/ which doesn't even have that many questions). It doesn't really make sense to me why it takes so long.
- `/api/card` response can be huge, and it contains lots of information that is completely irrelevant for rendering the questions list. There should be a separate endpoint for getting fewer information or maybe the frontend should be able to define in the API call which fields it needs. Do we currently have any plans on which approach to take? @salsakran @camsaul 
- All other endpoint calls on the questions page are really fast, so I think that they don't need to be considered

And rendering:
- Probably using `react-virtualized` or similar for the questions list would be a pretty quick win and that's something I can definitely work on! I can pair on this with @tlrobinson who has worked with the library more than me

**Comment by salsakran** [comment]
Let's definitely fix rendering, since the lack of pagination + no virtualization is imo more embarrassing.

**Comment by camsaul** [comment]
> /api/card endpoint is super slow
>
> /api/card response can be huge

Those two are probably related ;)

@attekei if you can give me a list of the things that we don't need that you noticed in that endpoint I can take them out and see if we get a noticeable performance boost.

**Comment by attekei** [comment]
@camsaul Yeah somewhat related but even if the endpoint result is just `[]` (for instance in the case that you fetch a list of questions that don't belong to any collection but there aren't any) then the loading time can be long.

>  if you can give me a list of the things that we don't need that you noticed in that endpoint I can take them out and see if we get a noticeable performance boost.

For instance `dataset_query`, `result_metadata` and `visualization_settings`are unneeded (but notice that dashboard page needs at least `dataset_query` so for that reason it's good to have a separate endpoint).

**Comment by camsaul** [comment]
let me look into this

**Comment by tlrobinson** [comment]
@metabase/core-developers Is this still a problem?

**Comment by flamber** [comment]
Seems like most of the things here are listed in #5504 - as well as a few more.

**Comment by flamber** [comment]
Closing, since there has been many performance improvements in 0.34 and 0.35
See #5504 and #11806 for outstanding things

**Comment by camsaul** [comment]
This is really the same issue as #10134 or #5504
