### ISSUE TITLE
Ability to create raw Queries shows up for all users

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6793]
When a new user with zero permissions first logs in, they're able to go to:

1. Add Questions
2. Native Query

They're only redirected to a page that says "Sorry, you don’t have permission to see that." AFTER they start typing a query.

**Comment by salsakran** [comment]
Can you please share which version of Metabase (and ideally the rest of the information we ask for in the issue template) this is happening on?

**Comment by camsaul** [comment]
@ACPK ?

**Comment by mbvictoria** [comment]
Closing - has needed more info for over a year and no new reports.
