### ISSUE TITLE
New users see whole feed even if they don't have permissions to something

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6794]
When a new user signs up, they see the full activity feed even with questions that they don't have permissions to. When they click on one of the activity links, they get:

    Sorry, you don’t have permission to see that.

**Comment by salsakran** [comment]
Can you please share which version of Metabase (and ideally the rest of the information we ask for in the issue template) this is happening on?

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 - think this was fixed in 0.30, with the big Collection change.
