### ISSUE TITLE
PERMISSIONS ISSUE

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6796]
In the admin's permissions section, a test user has zero permissions to the database and "Saved Questions".

However, they can still see the questions if they go to:

1. meta_url.com/questions
2. "Ask a question"
3. "New Question"
4. "Saved Questions" on the top-left drop-down list *
5. They can SEE all of the saved questions' titles.
6. If they click on one, they'll be redirected to a screen that says "Sorry, you don’t have permission to see that.".

*  Please note, that the user was given NO ACCESS to "Saved Questions" via the admin's permission dashboard.

**Comment by salsakran** [comment]
Can you please share which version of Metabase (and ideally the rest of the information we ask for in the issue template) this is happening on?

**Comment by ACPK** [comment]
@salsakran  - I installed it the day I wrote this story, so it should be the latest version.

**Comment by camsaul** [comment]
This is a duplicate of #5617. Saved Permissions aren't supposed to show up on the Edit Permissions page; we fixed that in 0.25.1.
