### ISSUE TITLE
Whitelabeling

### ISSUE THREAD

**Issue by ACPK** [metabase/metabase#6798]
Similar to Gmail where admins can upload their company's logo, how would a Metabase admin add their company's logo to the Metabase header?

**Comment by jornh** [comment]
I believe https://www.metabase.com/docs/latest/administration-guide/13-embedding.html#premium-embedding is what is there for whitelabeling

**Comment by ACPK** [comment]
@jornh - That's embedding charts; not white-labeling the dashboard.

**Comment by hugocar** [comment]
Hi,
The metabase team has a program for white-label:  
https://www.metabase.com/blog/White-Label-Metabase/index.html

**Comment by salsakran** [comment]
@ACPK (or anyone else interested) send me a message via https://www.metabase.com/services/ and I'll let you know the things we're planning on releasing soon on that front, in case it's interesting to you. 

However, we're not going to be providing a ton of white labeling options in the open source application itself.  We're trying to make a name for ourselves, and think it's a reasonable trade to offer free software in exchange for people knowing that they're using Metabase. Note that in GMail's case, business accounts are a paid version.

**Comment by romainlaisne** [comment]
Hi @salsakran, 

Any progression on the white label options?
We use Metabase quite a bit and are ready to pay to get white labeling when we use Metabase with clients.

Thanks in advance for your feedback.

Regards,
