### ISSUE TITLE
Questions to complete Cloudron support

### ISSUE THREAD

**Issue by marbetschar** [metabase/metabase#6804]
I'm currently adding Metabase as package to [Cloudron](https://cloudron.io). I've managed to setup mail and ldap support without big headaches. Only two questions left:

#### 1. Skip setup form

Now, to complete I'd love to skip the setup form since user management is integrated with the Cloudron environment via LDAP. How is this possible?

#### 2. Retrieve isSuperuser via LDAP

The user management is done in Cloudron. And within Cloudron it's possible to grant superuser status. This information is [exposed via the `isadmin` LDAP property](https://cloudron.io/documentation/developer/addons/#ldap). How can we use this information to grant superuser access within Metabase?

**Comment by marbetschar** [comment]
Any feedback on the questions?

**Comment by marbetschar** [comment]
How can we take the next steps to finish up the Cloudron support? https://cloudron.io

**Comment by wwwiiilll** [comment]
From the docs I found here https://cloudron.io/developer/addons/#ldap, you could use LDAP group mappings to map the DN `cn=admins` to the MB admin group.

**Comment by paoliniluis** [comment]
Hi, you are able to setup Metabase via it's API, would this be a solution to the first problem? second one can also be solved with group mappings in LDAP

**Comment by marbetschar** [comment]
sorry guys, I'm no longer using Cloudron at work - but here's the current state of work: https://git.cloudron.io/mandelkind/metabase-app

Feel free to take over!

**Comment by paoliniluis** [comment]
Thanks, this is achievable by inserting in the start.sh a few lines for setting up Metabase with the API as stated in https://www.metabase.com/learn/developing-applications/advanced-metabase/metabase-api.html and then by group mappings in LDAP.

**Comment by flamber** [comment]
Closing as questions and troubleshooting like this is better suited for the forum: https://discourse.metabase.com/
