### ISSUE TITLE
Friendly table names won’t turn off

### ISSUE THREAD

**Issue by rodrigortz** [metabase/metabase#6805]
I tried to turn off the friendly names option and rescan the schemas, but it won’t turn off.

Running via java -jar metabase.jar in Windows 7 64bit.

**Comment by VikramTiwari** [comment]
@rodrigortz How did you try this?

**Comment by rodrigortz** [comment]
Via the settings menu...

**Comment by jornh** [comment]
Please try out http://downloads.metabase.com/v0.28.0-RC2/metabase.jar

It should contain the fix to #5751

**Comment by salsakran** [comment]
Can you be more specific about where you're seeing friendly names? I.e. is this fields, tables, and where in the product are they not being turned off?

**Comment by tlrobinson** [comment]
Fixed by #6708
