### ISSUE TITLE
USA Map view settings don't correspond correctly when country included at beginning of select 

### ISSUE THREAD

**Issue by Tim-The-Third** [metabase/metabase#6807]
Hi,
The names of fields when setting up the Map view settings don't correspond correctly when the country is included in the select.
So I currently have the below, 
select 
Backend_Country.name as "Country",
Backend_subdivision.Name "State",
Count(backend_engine.name) "No. Sources"

Configerd as 
![image](https://user-images.githubusercontent.com/34242653/35512121-849d0e72-04f6-11e8-8f8c-a625754800d6.png)

Gives me 
![image](https://user-images.githubusercontent.com/34242653/35512148-9d3d6fee-04f6-11e8-8b40-794532cc2489.png)

As you can see the fact that the country name is included it is pushing the data into the next section, removing the Country from the query (or just moving it to the end for the select) fixes this issue, Is this intended ?

Your browser and the version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Your operating system: Mac OS High Sierra 10.13.2 
Your databases: Postgres
Metabase version: v0.27.2
Metabase hosting environment: Postgres

**Comment by salsakran** [comment]
No, that looks like a bug =(

**Comment by paulrosenzweig** [comment]
It looks like this is working now when both state and country columns are queried.

![image](https://user-images.githubusercontent.com/691495/58831883-a9a65500-861b-11e9-8a51-60d80dace421.png)

I'll close this for now, but if you're still seeing it or it recurs please reopen.
