### ISSUE TITLE
Return relevant FK dest fields automatically in "rows" queries

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#681]
User Story: as a user looking at row level data I would like to see human readable identifiers in my data rather than cryptic id values (numbers, hashes) so that I can better understand what I'm looking at.

Example if pulling up the list of Invoices from a db I would want to see the name of the User or Customer the invoice is related to instead of a user_id or customer_id value.

**Comment by camsaul** [comment]
This is the same issue as #2657 but that has more activity so closing this one as a duplicate
