### ISSUE TITLE
Fixing empty dashboard problem - Redux help

### ISSUE THREAD

**Issue by kristynrb** [metabase/metabase#6813]
I have started working on the empty dashboard issue. We want to make it so that all users don't have access to any empty dashboards that are created. Instead, they should be able to see an empty dashboard only if they've created it.

This would help to close the following issues:
#4194 
#6735 

What I want to do to solve this:
- Accessing the dashboard creator id
- Accessing the current user id
- Determining if the dashboard is empty
- Creating logic to determine whether to show the dashboard. If the dashboard is empty and the current user is not the dashboard creator, don't show the dashboard. 

Relavent file: `frontend/src/metabase/dashboards/components/DashboardList.jsx`

**I need help getting access to two values**
I need to access the current user id in the `DashboardList.jsx` file listed above. I'm new to Redux and I'm having a tough time getting this to happen. Can someone help me out with that?

Also, I'm able to access the dashboard's length (to determine if it is empty) when I look at the value of `root.ordered_cards.length` in the file: `frontend/src/metabase/dashboard/dashboard.js`, but I have yet access this value in `DashboardList.jsx` file.

Any help with this would be greatly appreciated!

File to go to: frontend/src/metabase/dashboards/components/DashboardList.jsx

**Comment by salsakran** [comment]
Hello @kristynrb --

Really appreciate you helping out. The team agrees the current means of filtering dashboards doesn't work on empty ones, and this is something we want to fix.

That said, any kind of permissions based filtering should happen on the backend. By removing these dashboards from the rendering process, we still have them lingering in the api responses and potentially leaking information. Additionally, we're in the process of trying to make the frontend cleaner and generally pushing logic towards a testable place (read: the backend.)

**Comment by kristynrb** [comment]
Okay, thanks @salsakran I appreciate you looking into this. I'll have to learn more about Clojure before I can try tackling that job.

**Comment by salsakran** [comment]
@kristynrb thank you so much for offering to pitch in! We really appreciate it, and hope that us being OCD bastards on PRs and issues is taken as we intend it (us trying to maintain a code + product quality bar for our users) and not us just being difficult.
