### ISSUE TITLE
display when software updates are available on the admin pages

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#682]
An admin should be able to tell if there are updates available from their current version.

We should phone home (probably to an S3 bucket) and see what newer versions are available, and display to the user the release notes for the versions between their currently running version and the latest stable version.

Also, a link to relevant upgrade instructions should be displayed.

**Comment by salsakran** [comment]
Crate does this in a really elegant way but providing a notification stream, which includes release notes as notifications.

**Comment by holtkamp** [comment]
After receiving news about ```0.19.0``` and spinning up our Metabase ```0.18.1``` installation that was sleeping on Heroku, I was kind of surprised to see this: 

<img width="891" alt="screen shot 2016-08-03 at 14 45 41" src="https://cloud.githubusercontent.com/assets/776405/17365987/2655c116-5989-11e6-9ed6-d890faa12b57.png">

The discussion at https://github.com/metabase/metabase/pull/2535 mentions that the 'check for updates is ran automatically', but maybe a manual 'check for updates now' button would be useful for Heroku instances (which tend to go sleeping). 

Additional question: is auto-update supported on Heroku? Should I wait or just install a brand new version. Maybe some notes in the [Heroku deployment docs](https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-metabase-on-heroku.md) about this would help a bunch of people. I can provide a PR for that, just don't know what the advised way of updating is  😄
