### ISSUE TITLE
Designs for using a saved question to populate options for SQL text/number variable filters

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6820]
**Goal(s)**
I should be able to use the results of a column in a saved question to define the list of selectable values for a SQL text or number filter widget.

**Scope restrictions**
I can only choose from saved questions which have only a single column in their result.

**Basic UX flow**
1. I create and save a new question with a single column (arbitrary number of rows) in its result.
2. I go make a new SQL query and add a variable to it.
3. In the variables panel, I set my variable’s type to “Text” or “Number”
4. I then see an option to pick a saved question to populate the filter widget’s dropdown, (effectively turning the filter widget from an input box into a dropdown).
5. I click the select and I get a popup which first asks me to pick a collection, then a question within that collection. (We can reuse the component from Pulses which allows the picking of a question.)

**Questions and notes**
- Does there need to be a button to refresh the results of the linked question? I.e., presumably we cache the results of the linked question so we’re not rerunning that query every time the filter is clicked, but how often do we check for new/changed values?
- Should a user be able to input a value that's not in the list of results? Should that be an option surfaced to the variable creator?
- We should respect the ordering of the linked question's results when displaying them in the filter dropdown.
- The person adding the template variable should have permissions to run the linked question.

**Designs**

New variable created: 

![01_new_variable](https://user-images.githubusercontent.com/2223916/35543071-f9533a4a-0517-11e8-8d37-04b0ebe8b214.png)

Variable type chosen:

![02_var_type_chosen](https://user-images.githubusercontent.com/2223916/35543072-f9681438-0517-11e8-8ade-a09f41f86df8.png)

Click to open up the collection selector:

![03_pick_collection](https://user-images.githubusercontent.com/2223916/35543073-f97c24c8-0517-11e8-84e3-92aa49a9a359.png)

Pick a question:

![04_pick_question](https://user-images.githubusercontent.com/2223916/35543074-f98fa08e-0517-11e8-8c10-66edad1ca0d5.png)

The question's selected: 

![05_question_selected](https://user-images.githubusercontent.com/2223916/35543075-f9a45768-0517-11e8-815d-929d423b5434.png)

The question's results are now used to populate the filter widget:

![06_values_in_filter](https://user-images.githubusercontent.com/2223916/35543076-f9b7fc28-0517-11e8-828e-a8d33e77ec04.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by edmarriner** [comment]
Will it be possible for the saved questions that populate the list to use any of the parameters passed when embedding? 

This will solve the biggest issue we are having with Metabase. We can filter down the results that are displayed per client, but currently, the dropdown list filters will show data that they should not be able to see and we have no way of controlling this. Until we can control what data is shown in the dropdown lists we cannot use the embedding functionality for many of the areas we would love to.

An example is where we show sales results for each of our clients when they log in. We restrict the rows that are returned to just those that belong to the client. However when we embed the question and use a category filter for a list of "order channels" they would be able to see a list of channels that belong to other clients. Being able to use a parameter in these saved questions would allow the dropdown list of channels to only show channels that belong to each client.

**Comment by joneath** [comment]
@mazameli is this the question picker component in pulses that you're referring to? 
<img width="492" alt="screen shot 2018-02-25 at 12 52 31" src="https://user-images.githubusercontent.com/163979/36638569-1ca2d76c-1a2b-11e8-83d8-90fe8a0b8e67.png">

**Comment by joneath** [comment]
@mazameli I was worried about the design differences but it turns out that I didn't have any collections made. Looks great!

**Comment by matotias** [comment]
We would love this functionality too!

**Comment by ashalitkin** [comment]
That would be really nice to have it. My case is that I need to define a unit of time for a date_trunc like a day or a month as a parameter of the query and end users really don't want just type it in.

**Comment by SushantFc** [comment]
Wouldn't it be better, if I could do the it using the segments?, so each segment that I create of a table goes into the table list in the field filter.

**Comment by gvisniuc** [comment]
This would definitely be awesome to have. Redash is currently adding the query results as a separate dataset (https://redash.io/help/user-guide/querying/query-results-data-source).

You can then do cross database joins from the result sets, even across database types (i.e. Elasticsearch + Mongo + Postgres).

**Comment by paoliniluis** [comment]
This should be closed with 46 release, right @mazameli ?

**Comment by mazameli** [comment]
@paoliniluis yep, good call. We shipped this in [version 46: "Customize filter dropdown menus."](https://www.metabase.com/releases/metabase-46?from_page=blog)
