### ISSUE TITLE
Entering a pulse name longer than 70 characters causes the edit button to disappear

### ISSUE THREAD

**Issue by dannybisby** [metabase/metabase#6821]
Entering a pulse name longer than 70 characters causes the edit button to disappear, was testing to see if there was a maximum pulse name

- Your browser and the version: Firefox 58.0.1
- Your operating system: Windows 10
- Your databases: postgress
- Metabase version: 0.27.2
- Metabase hosting environment: ubuntu
- Metabase internal database: default

### Bug
*Repeatable steps to reproduce the issue*
- Create a new Pulse
- Give it a name that's longer than 70 characters

**Comment by kdoh** [comment]
This was closed by #6931.
