### ISSUE TITLE
Spelling Error in the Administration Guide

### ISSUE THREAD

**Issue by grahovam** [metabase/metabase#6829]
[https://www.metabase.com/docs/v0.20.1/administration-guide/06-segments-and-metrics.html](url)

> Here your presented with a slightly different version of the query builder, which only lets you select filters and aggregations

your != you're

**Comment by hugocar** [comment]
Hi
(i'm not a member of metabase team)
Nice catch! you should submit a pull-request. It's very easy and rewarding.

**Comment by salsakran** [comment]
good catch! fixed in #6849
