### ISSUE TITLE
Count not shown for all series in Bar Chart Stack -100%

### ISSUE THREAD

**Issue by JBrame** [metabase/metabase#6832]
Only the first (bottom) series shows the count for the series along with the %, all others just show the %.

![image](https://user-images.githubusercontent.com/6168847/35631779-b3e84122-069c-11e8-818e-b7ba41fc6cd9.png)

![image](https://user-images.githubusercontent.com/6168847/35631796-c5b8f946-069c-11e8-8a77-b2dce8dbd410.png)
---
- Your browser and the version:  Chrome 63.0.3239.132, Edge
- Your operating system: Win 10
- Your databases: MySQL 5.7.19
- Metabase version: 0.27.2
- Metabase hosting environment: Win10 Powershell jar
- Metabase internal database: H2 (default)

**Comment by TheCondorman** [comment]
This has been fixed in v0.28.0 (5678c98 release-0.28.0)

**Comment by TheCondorman** [comment]
Disregard my previous comment. It's an inconsistent behaviour.

**Comment by paulrosenzweig** [comment]
@TheCondorman it's been a while and I can't seem to reproduce this, but you did mention it happens inconsistently. Are you still seeing this at all?

**Comment by flamber** [comment]
@paulrosenzweig 
On 0.32.8 I cannot make it show the count - only the percentage. I know you've done a lot of work on master, so this might have been fixed.
But then something strange is happening if I don't group by day, where the total percentage of each stack is the percentage of the all the stacks.
I think this is related to #8685 
![Screencast 2019-06-05 11 11 31](https://user-images.githubusercontent.com/1447303/58975732-eb054480-8782-11e9-933e-b4513a57af1e.gif)

**Comment by TheCondorman** [comment]
@paulrosenzweig as @flamber mentioned I can also only get it to display the percentage now not the counts. So I guess it's 'fixed' but it's useful to be able to see both the percentage and the counts

**Comment by flamber** [comment]
Closing in favor of #8463, which has more upvotes - this isn't a down-prioritization, just trying to cleanup multiple issues.
