### ISSUE TITLE
Create computed field using MongoDB

### ISSUE THREAD

**Issue by marbetschar** [metabase/metabase#6834]
How may I create a custom field (e.g. a calculated field) using MongoDB? I'd love to do a SUM(a) - SUM(b). But I can't figure out how to do it using the query builder.

See http://discourse.metabase.com/t/mongodb-how-to-subtract-two-sums/2839/2 for details.

**Comment by salsakran** [comment]
I've answered in that thread. Closing this  as questions about how to use Metabase aren't really within the scope of what this issue tracker is used for.

Hope that answer helps!

**Comment by marbetschar** [comment]
@salsakran understood. However I thought this feature is not supported with MongoDB at all, therefore this issue here on GitHub.

As you can see in my answer provided, there is no such thing like "Calculated Expression" showing up anywhere.

**Comment by quique0194** [comment]
Custom fields are not available for mongoDB. It is really really important to have this feature to have a fully functional environment for mongoDB
