### ISSUE TITLE
com.google.api.services.bigquery vs com.google.cloud.bigquery

### ISSUE THREAD

**Issue by abelliae** [metabase/metabase#6836]
Are there any plans to move to the newer com.google.cloud.bigquery Java library for BQ support?

The documentation for the older com.google.api.services.bigquery (the one currently imported) is sometimes cumbersome, making it difficult to tune parameters like https timeouts.

Looking forward to your feedback. Thanks for the great work.

**Comment by salsakran** [comment]
What's the difference between the two drivers? We're definitely planning on switching over to StandardSQL and will update drivers as we go.

**Comment by abelliae** [comment]
Hey @salsakran , thanks for getting back to me.

Here's a brief description of the differences:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1514

## Background Story
We are getting a "Query took too long" error even though everything is running fine on the DB and the query length is under the threshold set in Metabase.

We think it's coming from 

`(defn- ^Bigquery credential->client [^GoogleCredential credential]
  (.build (doto (Bigquery$Builder. google/http-transport google/json-factory credential)
            (.setApplicationName google/application-name))))`

https://github.com/metabase/metabase/blob/3be5e9500320134593c22ed4ab78e1932ee63363/src/metabase/driver/google.clj#L18 

We tried thinkering around with the library's configs as in https://stackoverflow.com/questions/43584201/google-bigquery-socket-timeout/44560665#44560665
without much success. It seems the new library better exposes these types of configs, I was just wondering if any porting is planned.

**Comment by jeff303** [comment]
The new BigQuery driver coming in `x.41` uses the `com.google.cloud.bigquery` SDK.
