### ISSUE TITLE
AWS EBS - Cannot Connect to External MySQL

### ISSUE THREAD

**Issue by johnsercel** [metabase/metabase#6838]
I've been running a local MB jar instance connected to a remote mysql server for a few months now. Today I'm trying to configure a production MB instance on AWS EBS and point it to my existing mysql server / db.

EBS setup completes using the default postgres RDS instance, I'm able to configure HTTPS, all is well, until I try to switch to my external mysql server. Then it cannot connect and will not start.

<img width="646" alt="screen shot 2018-01-31 at 15 34 51" src="https://user-images.githubusercontent.com/742654/35649107-a390576e-069d-11e8-9a47-266ac4940330.png">

I've temporarily disabled the firewall on that mysql instance and confirmed I can connect from any IP. The credentials are confirmed correct, the same config I'm using with my jar MB instance.

01-31 15:32:51 [1mINFO metabase.db[0m :: [36mVerifying mysql Database Connection ...
01-31 15:32:56 [1mERROR metabase.driver[0m :: Failed to connect to database: Timed out after 5000 milliseconds.
java.lang.AssertionError: Assert failed: Unable to connect to Metabase mysql DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
01-31 15:32:56 [1mERROR metabase.core[0m :: Metabase Initialization FAILED: Assert failed: Unable to connect to Metabase mysql DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
01-31 15:32:56 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
Etc

Is there some known issue preventing the connection from the EBS MB instance?

**Comment by hugocar** [comment]
Hi,
(i'm not a member of MB team, running MB on .jar on EC2)
You have disable the firewall/security-group of the mysql instance, did you open the security-group of the EBS instance as well to accept 3306 tpc inbound ?

**Comment by salsakran** [comment]
Not really. We have multiple connected MySQL databases internally.

This is a network issue where Metabase can't connect to your MySQL database. It's out of scope for this issue tracker, but I'd suggest checking out our trouble shooting guide (https://www.metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html) or asking on our discussion forum (discourse.metabase.com) with more specifics. 

If you find an actual but in Metabase, please re-open this issue.
