### ISSUE TITLE
Filter for changing certain field in multiple questions in a dashboard at once

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#6841]
Hello everyone!

I have been using Metabase for quite a while now and I am very happy with its features. However, throughout my daily routine, I came up with a few ideas which might be useful for all of its users. 

I am currently working as a software developer at a Call Center and I am using Metabase to query our database. A few days ago I created personalized dashboards for each operator that we have. There, each employee can track his monthly sales, progress and many other useful statistics.

However, I stumbled upon the following problem:

I am interested in tracking the information for each month separately (since salaries are paid monthly and so on). Therefore once the month has ended, if I want to allow the employees to look back at the previous results I would have to create a whole new dashboard and add each and every question again and just attach "+ interval '-1 month'" to each. Instead of doing that, it would be awesome if we have a "multi-filter" for certain fields which contain the same data (eg. dates). Therefore once we click "previous month" it would automatically load up all the questions with info from the previous month. However, this might be a little bit tricky since bringing info for the previous month for different questions might not be made with the same change but I am pretty sure that there is a way to overcome this issue too.

Anyways, thank you for the great software! I look forward to seeing that feature in action!

All the best,
Ivan

**Comment by petar777** [comment]
PS. That feature is available in competitor software, therefore with would be of great importance to have this implemented.

**Comment by hugocar** [comment]
Hi,
(i am not a member of metabase team)

I think the feature you are describing already exists.

On questions you can add variables.
On a dashboard you can "add filter" in the editing mode.
When adding a filter, you choose zero or one variable per questions on the dashboard. 
The chosen variable will be linked to the filter. Any value given to the filter will be passed to all the questions that have they variable linked.

Works very well when using the optional variables ( declared with [[ ]] )

**Comment by salsakran** [comment]
@petar777 https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html will let you solve the underlying problem (per-user dashboards that can be looked at filtered down to certain months).
