### ISSUE TITLE
Tooltip missing field data in 0.28

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#6842]
It seems tooltips in 0.28 no longer show data for all columns from a SQL query. I was trying 0.28 to see if it would fix an issue with the tooltip showing the wrong values (possibly #6401). Not sure if this intentional or not but I liked the feature :)

SQL:
```
select distinct aja_jb_number as "Build Number", 
    ACQE_COVERAGE_PCT as "Coverage Percent", 
    ACQE_COVERAGE_COVEREDLINES || '/' || ACQE_COVERAGE_TOTALLINES as "Coverage",  
    ACQE_TESTS_PASSED || '/' || ACQE_TESTS_TOTAL as "Passing Unit Tests", 
    ACQE_QUALIFIES as "Qualifies",
    case when ACQE_QUALIFIES = 'true' then 1 else 0 end as "Q",
    case when ACQE_QUALIFIES = 'true' then 0 else 1 end as "NQ"
from mbase.V_ARTIFACTORY_ACQE
where 
ACQE_COVERAGE_PCT > 0 and 
{{job_name}}
order by aja_jb_number desc
```

0.27.2:
![mbase_coverage_027](https://user-images.githubusercontent.com/17504314/35692581-c236f61c-0749-11e8-97a9-c40f6e9353c7.png)

0.28.0.RC2:
![mbase_coverage_028](https://user-images.githubusercontent.com/17504314/35692593-c95a4caa-0749-11e8-8ded-8a834ac97d26.png)

Browser: Chrome 64.0.3282.119
OS: Windows 7
Databases: Oracle 11g
Version: v0.28.0.RC2
Host Env: Windows 7
Internal Database: MySql 5.7

**Comment by salsakran** [comment]
@kdoh + @camsaul You guys worked on the scrubbing/tool tips changes. 

I personally don't have a ton of attachment to either version. 

Opinions?

**Comment by camsaul** [comment]
Yeah showing all values was nice I think the fix in #6401 might have broken it?

**Comment by MarkRx** [comment]
The weird thing is it happens for a few random data points. Not sure what the pattern is. Most are missing the data.

**Comment by camsaul** [comment]
Got it. I wrote the code that adds the extra column info after the first two, but it was a little tricky determining exactly which point to add each set of extra info to. In cases where we can't figure out which point to add them to doesn't add them rather than guess wrong and give you wrong data.

In all the cases I tried it seemed to work reliably but I guess here's a case where it doesn't. Could you share with us a few rows from the chart above so we can try to reproduce this?

**Comment by MarkRx** [comment]
It looks like the data that shows up for build 1533 on the first image from 0.27.2 is incorrect (possibly issue #6401). The data it is showing (minus the coverage percent) appears to come from build 1578.

Here are sample records. There are 189 total records.

Since there is only a single record per each x value I would expect the auxiliary data to still show.

Build Number, Coverage Percent, Coverage, Passing Unit Tests, Qualifies, Q, NQ

> 1579	53.396	17824/33381	4549/4558	true	1	0
> 1578	53.399	17824/33379	4549/4558	true	1	0
> 1577	53.39	17796/33332	4543/4552	true	1	0
. . .
> 1550	53.168	17646/33189	4497/4506	true	1	0
> 1547	53.178	17646/33183	4497/4506	true	1	0
> 1546	51.872	16834/32453	4223/4232	true	1	0
> 1545	53.179	17649/33188	4489/4498	true	1	0
> 1537	52.89	17539/33161	4471/4480	true	1	0
> 1536	52.89	17539/33161	4471/4480	true	1	0
> 1535	52.887	17534/33154	4471/4480	true	1	0
> 1534	51.84	17187/33154	4400/4409	false	0	1
> 1533	51.84	17187/33154	4400/4409	false	0	1
> 1532	51.837	17185/33152	4396/4405	false	0	1
> 1531	51.825	17181/33152	4381/4390	false	0	1
> 1530	51.825	17181/33152	4381/4390	false	0	1
> 1529	51.825	17181/33152	4381/4390	false	0	1
> 1528	51.825	17181/33152	4381/4390	false	0	1

**Comment by salsakran** [comment]
@MarkRx I'm reading your last comment as:
the data in 0.28 is correct but not as complete/useful as the incorrect data in 0.27

@kdoh @mazameli I'm wondering if a more generous amount of data in the tooltips makes sense?

**Comment by MarkRx** [comment]
Yes. The data is correct but a feature where the tooltip displayed more information about the records based on the fields in the result in 0.27 is missing in 0.28.

**Comment by paulrosenzweig** [comment]
This has been fixed.
