### ISSUE TITLE
New Question Modal is fetching data

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6843]
A fresh pageload of the New Question modal pulls in:
```
02-01 11:47:22 DEBUG metabase.middleware :: GET /api/segment 200 (7 ms) (2 DB calls)
02-01 11:47:22 DEBUG metabase.middleware :: GET /api/metric 200 (10 ms) (3 DB calls)
02-01 11:47:22 DEBUG metabase.middleware :: GET /api/setting 200 (381 µs) (0 DB calls)
02-01 11:47:22 DEBUG metabase.middleware :: GET /api/database 200 (758 ms) (5 DB calls)
```
While these calls are fast on my empty development machine, they introduce several server hits to render a page with 3 images on it. 

![screen shot 2018-02-01 at 11 47 38 am](https://user-images.githubusercontent.com/107439/35699741-cc4262da-0745-11e8-9899-5bbc70481efa.png)

I don't suppose we're doing this on purpose to prefetch things that are useful on the next click, but not blocking image rendering?
@tlrobinson @attekei

**Comment by flamber** [comment]
Closing, since this was fixed long ago and 0.34 many performance improvements in this area.
