### ISSUE TITLE
Dropdowns sometimes get truncated

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6844]
Depending on scroll position dropdowns (at least dashboard filter dimension picker) sometimes get truncated without a scrollbar:
<img width="422" alt="screenshot 2018-02-01 11 46 49" src="https://user-images.githubusercontent.com/178038/35699862-2d281586-0746-11e8-8c74-00315b11b6c6.png">
<img width="401" alt="screenshot 2018-02-01 11 42 44" src="https://user-images.githubusercontent.com/178038/35699868-337e8460-0746-11e8-87d6-aacc487dd050.png">
<img width="397" alt="screenshot 2018-02-01 11 42 57" src="https://user-images.githubusercontent.com/178038/35699872-36de8664-0746-11e8-8abd-9134879826bd.png">
(these are all for the same table)

OS X, Chrome 64

**Comment by mazameli** [comment]
This appears to be fixed in master to me. Can you verify @sbelak?

**Comment by sbelak** [comment]
👍 Can't reproduce any longer.

**Comment by sbelak** [comment]
👍 Can't reproduce any longer.
