### ISSUE TITLE
How to disable auto load queries when open dashboard

### ISSUE THREAD

**Issue by imiskolee** [metabase/metabase#6846]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your databases: Oracle,Sql Server
- Metabase version: 0.26.2

i has a large query of a question by default param value, i dont want auto load query when its very large.

let me know how to disable or other way.

**Comment by jornh** [comment]
I don’t think there’s a way around that you have to run the query once to get a result. 

If it’s for dashboards with a filter maybe you can set a default filter returning less data?

Depending on your situation maybe https://www.metabase.com/docs/latest/administration-guide/14-caching.html is helpful. We use that for displays on the floor.

If none of this is helpful please give more info on your situation

**Comment by imiskolee** [comment]
@jornh  thanks for you reply.

i think we need a `search button` feature and  allow configure when we create question better than default filters.

sometime, we don't need show anything by default. 

and,

if question has a lot of filters, dashboard will reload(call query API) when i changed any filters now.

its not good idea when work on large table/view.

**Comment by hugocar** [comment]
Hi @imiskolee 
(i'm not a member of metabase team)

1/
Maybe you can change the default param value so the number of results is small or null

2/
You can also take advantage of metabase's cache system
https://github.com/metabase/metabase/blob/master/docs/administration-guide/14-caching.md

3/
Maybe you can do a materialized view of the query results . And in metabase, you query the view in order to apply filters.

**Comment by salsakran** [comment]
@imiskolee we load all cards when a dashboard is displayed, and we don't offer a way to disable that. We suggest that you change the default value of a filter to keep the initial load manageable.

**Comment by mewc** [comment]
a "RUN" button would be nice - submitting on every query at the start can lead to overages

**Comment by sabyasachinandy** [comment]
Did anyone manage to crack this? And Run button will be a boon. In my use case, there are plenty of users who have pinned dashboards. Everyday this tabs get auto loaded and run in the background when anyone starts there work. It would we great if we had a run button, this would significantly reduce load on the actual querying engine.

**Comment by timorkal** [comment]
why is this closed?? so needed !!!

**Comment by dragonsahead** [comment]
@timorkal @sabyasachinandy please upgrade to the latest version, this has been there since version 50 or even before
