### ISSUE TITLE
Current Period Occasionally behaves weirdly

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6862]
When mixing granularities, sometimes I get weird results -- 
For the sample dataset, when looking at weekly count of rows for  the previous 5 months, without the current period  the last weeks numbers are incorrect. Here it's 41
![screen shot 2018-02-05 at 2 59 12 pm](https://user-images.githubusercontent.com/107439/35833233-3490dc94-0a85-11e8-9811-d6281c0617fe.png)

When looking at that week including the current month, it's 78
![screen shot 2018-02-05 at 2 59 05 pm](https://user-images.githubusercontent.com/107439/35833234-34a41840-0a85-11e8-9ab7-fc733e9f7ec1.png)

78 is the correct number when looking at that week in isolation.
![screen shot 2018-02-05 at 2 59 21 pm](https://user-images.githubusercontent.com/107439/35833232-347de350-0a85-11e8-810e-8f2a5e476023.png)

**Comment by salsakran** [comment]
Technically, the query processor is "doing the right thing" with the truncated week when it spans the end of a month. I'm torn as to whether this should be changed.

Thoughts @mazameli @ryrobes  @paulrosenzweig ?

**Comment by paulrosenzweig** [comment]
I think this is the right behavior.

If people are getting confused by this, maybe we could nudge them to match the filter and grouping granularity? Seems like automatically changing "5 months" to "24 weeks" would be too aggressive though.

**Comment by ryrobes** [comment]
Yeah, that's a tough one. The counts make sense, but have the potential to be confusing.  

Personally, best case - give an option to include / exclude truncated periods (like we do with "today").

**Comment by salsakran** [comment]
closing this since I'm the only person to have found this weird.
