### ISSUE TITLE
Allow Hyperlink Text Value To Be Specified

### ISSUE THREAD

**Issue by edmarriner** [metabase/metabase#6873]
Hi

It would be most helpful if we could specify the text that is displayed when generating a hyperlink in the results of an SQL query. Currently, it shows the full URL which while works it is often very long and gives no way of suggesting to the user what will happen when they click on the link.

The example below shows a link to a page in an app where the user could go to view more details about the item in the report:
![blur](https://user-images.githubusercontent.com/655769/35853326-1c49d9ce-0b25-11e8-9018-5fdf7c8acbf5.jpg)

To generate this URL I am doing the following:

![screenshot from 2018-02-06 09-54-08](https://user-images.githubusercontent.com/655769/35852820-c93c23fa-0b23-11e8-937d-9c46e37f11a4.png)

What i would propose would be a small change in the syntax to allow the link text to be provided. This could be as simple as:

"https://url.com/app/123/details||LINK_TEXT_HERE" 
or 
"https://url.com/app/123/details[[LINK_TEXT_HERE]]"
or
"https://url.com/app/123/details{{LINK_TEXT_HERE}}"

Example of how it would work in the SQL editor:

![screenshot from 2018-02-06 09-54-32](https://user-images.githubusercontent.com/655769/35852819-c9274700-0b23-11e8-9f84-afd09103f144.png)

The expected results:

![screenshot from 2018-02-06 09-58-15](https://user-images.githubusercontent.com/655769/35853120-9b20c4f2-0b24-11e8-8848-281c6f5f93a3.png)

- Your browser and the version: Chrome 52.1
- Your operating system: Ubuntu
- Your databases: MySQL
- Metabase version: 27.2
- Metabase internal database: MySQL

**Comment by jornh** [comment]
Admittedly nitpicking here, but:

Since Markdown has already been introduced on [Text Cards](https://github.com/metabase/metabase/pull/6860/commits/e46651a3391235393a321093d08497353ca5636a#diff-6836d69b2d4320ea5d7a400a864f78eeR35) let’s stick with `[link text](URL)` for link syntax consistency.

**Comment by edmarriner** [comment]
@jornh Ah good point! That would seem to make perfect sense to me 👍

**Comment by MarkRx** [comment]
This would be great and shouldn't be too hard to implement. It could potentially even support using images in cells on a table as a stretch goal.

**Comment by jlisyc** [comment]
https://github.com/metabase/metabase/issues/8482

**Comment by flamber** [comment]
Hi @edmarriner 
This was added in 0.31 as part of the big formatting features, which are available under Visualization :gear:
For those wanting to have different text values for each link should vote for #7188 and/or #8461
On 0.31.2 it looks like this:
![image](https://user-images.githubusercontent.com/1447303/53273547-e7f5b500-36b9-11e9-8383-c603b8d0b220.png)

**Comment by satya-lalam** [comment]
Is it possible to open the link in a new tab instead of the same tab, something similar to target="_blank" in <a> tag?

**Comment by flamber** [comment]
@satya-lalam #10370 - upvote by clicking :+1: on the first post
