### ISSUE TITLE
Embed this dashboard in an application Error

### ISSUE THREAD

**Issue by MixMe** [metabase/metabase#6878]
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
**iFrameResizer resizer already defined.**
EmbedFrame.jsx:56:16
XML Parsing Error: syntax error
Location: https://metabase.xxxxxxx.com/api/embed/dashboard/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvdXJjZSI6eyJkYXNoYm9hcmQiOjI0Mn0sInBhcmFtcyI6W119.FvEHlpQMNJHw44Y__HBDYIrNEeHEAc4xuD3XmVCioro/dashcard/950/card/946
Line Number 1, Column 1:

**Comment by MixMe** [comment]
v0.28.0-RC3

**Comment by MixMe** [comment]
![capture](https://user-images.githubusercontent.com/3535911/35871838-ef81888a-0b6d-11e8-965f-ac4266c978d0.PNG)
Logs

**Comment by salsakran** [comment]
can you confirm this was working in a previous version?

**Comment by MixMe** [comment]
**Changing:** 

 ->set('resource', ['dashboard' => 338])
                        **->set('params', ['])**
                        ->sign($signer, $METABASE_SECRET_KEY)
                        ->getToken();

**To:** 

 ->set('resource', ['dashboard' => 338])
                        **->set('params', ['param' => ''])**
                        ->sign($signer, $METABASE_SECRET_KEY)
                        ->getToken();

**Fixed !**
