### ISSUE TITLE
Re-write Druid filter implementations to avoid using Javascript

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#6882]
In newer versions of Druid (0.10.0+) you have to opt-in to the ability to use Javascript filters by editing `common.runtime.properties` and setting `druid.javascript.enabled=true`. In older versions of Druid, including the ones we initially wrote the driver against (0.8.0), Javascript was enabled by default.

It seems like Druid adds new filters that replicate SQL equivalents in almost every release, so there's several places where we could replace ones we wrote in JavaScript a year or two ago with these new filters that didn't exist back then. In #6864 I replaced a few JavaScript filters with the new `"like"` filter, which behaves like a SQL `LIKE` clause (this was added about a year ago).

Based on a quick audit of our code it looks like the following MBQL filter clauses still use JavaScript implementations:

*  `inside`
*  `between`
*  `<`
*  `>`
*  `<=`
*  `>=`

It seems like all six of these can be replaced by the new [`bound` filter](http://druid.io/docs/latest/querying/filters.html), which looks like it was added way back in `0.9.0`.

Rewriting these filter clauses should be pretty simple and would likely provide a nice performance boost.

**Comment by camsaul** [comment]
Actually these are all super simple so I went ahead and implemented them in #6864.

**Comment by moumny** [comment]
Druid sql driver is pretty close to postgres. Ive seen it working in production on tableau by impersonating postgres. Perhaps would make things easier for supporting druid in the future

**Comment by camsaul** [comment]
Implemented by #6864
