### ISSUE TITLE
Scroll bar shadows in Text cards 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6883]
Latest version of Chrome on Mac OS X

![screen shot 2018-02-06 at 4 12 05 pm](https://user-images.githubusercontent.com/107439/35891408-ef7508ae-0b58-11e8-9bd2-9d6f728cb046.png)

**Comment by kdoh** [comment]
@salsakran Anything specific about that text card / dash? Looks like possibly tiny screen dimensions? Wasn't able to obviously reproduce it.

**Comment by jornh** [comment]
I experience similar-ish disabled bars on Win10 with Chrome 63 (see http://discourse.metabase.com/t/markdown-support/2906/2)

I found a CSS tweak by setting visiblilty to `auto` ... or something ... not currently handy what I did. Can find it again if you want me to.

**Comment by lindsay-stevens** [comment]
The inner markdown textbox has `overflow: scroll` which puts the scrollbars there all the time. If it's changed to `overflow: auto`, the scrollbars only show up when the content is bigger than the card.

**Comment by salsakran** [comment]
closed via #6926 
@lindsay-stevens  + @jornh 0.28.1 was just released, which fixes this.
