### ISSUE TITLE
Dragging date-based bar chart cards in dashboard edit mode triggers drag-to-filter

### ISSUE THREAD

**Issue by reidab** [metabase/metabase#6888]
When editing a dashboard, most cards are draggable from anywhere on the card. Bar charts with a date-based x-axis are only effectively draggable by the edges of the card because dragging anywhere inside the chart triggers a drag-to-filter behavior in addition to the layout drag. (The cards actually seem to be moveable, but the drag-to-filter fires on mouse up and navigates away from the dashboard page without saving the change.)

### Repro

1. Create a bar chart with a date on the x-axis (a bar chart with binned values doesn't seem to trigger this problem, but there may be other drag-to-filter-able types than date)
2. Add it to a dashboard
3. Drag it around in edit mode
4. When releasing the drag, find yourself navigated away from the dashboard to the detail page for the bar chart question

### Environment

- Safari 11.0.3
- Mac OS 10.13.3
- Metabase versions: 0.27.2, 0.28.0

**Comment by paulrosenzweig** [comment]
Resolved by #10931
