### ISSUE TITLE
how to enable filter panel of  a shared dashboard to an application

### ISSUE THREAD

**Issue by imiskolee** [metabase/metabase#6890]
Metabase Version:
0.27.0

How to enable filter panel of a shared dashboard to application ?

1. shared dashboard  from feature `Embed this dashboard  in an application`
2. not included filter panel in  iframeurl.
3. why we need it? beacuse we need integration Metabase Dashboard to Myself dashboard platform and editable from anyone.

Can metabase accept the request if i create a PR for configure filter panel  enable/disable when publish shared dashboard ?

**Comment by kdoh** [comment]
Hi @imiskolee. If I'm understanding you properly you're saying dashboard filters aren't properly showing up in embeded dashboards? This should already be possible. If you take a look at our [Embedding reference app repo](https://github.com/metabase/embedding-reference-apps) You should be able to see an example that looks like this:

![screen shot 2018-02-09 at 11 19 19 am](https://user-images.githubusercontent.com/5248953/36045613-1c29df12-0d8b-11e8-8945-56c17736319c.png)


If that's not what you're talking about would you mind expanding your explanation of the issue you're encountering? We should gather more info and have a discussion to set expectations before you write any code.

**Comment by mbvictoria** [comment]
Closing - has needed more info for over a year, not reported by other users.
