### ISSUE TITLE
SqlServer 'format' is not a recognized built-in function name, on group by date

### ISSUE THREAD

**Issue by ilkosta** [metabase/metabase#6892]
Hello,

I'm trying to build a `custom` question on a SqlServer db by using a `group by` on a date field. 
I would like to group by month.

When I run the run the question I got the error:
```
'format' is not a recognized built-in function name.
```
The same when I use the button `Break out by time`.

- databases: SqlServer 2008R2 connected by using SqlServer auth
- Metabase version: v0.27.2 (Latest) 
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

**Comment by jornh** [comment]
see https://github.com/metabase/metabase/issues/5983#issuecomment-332032431

**Comment by salsakran** [comment]
@ilkosta as per the comment @jornh links to,  we don't support SQL Server 2008. It mostly works, but we can't support every version of every database indefinitely, and it's been 10 years since 2008 =)
