### ISSUE TITLE
Change beanstalk  DB URL

### ISSUE THREAD

**Issue by Glathrop** [metabase/metabase#6893]
How can you change the reference to the db that holds metabase setup info. Our AWS instance will not reboot. Data in db is fine. I made a new metabase instance but need to point it to old db for setup. AWS snapshots can only be restored to a NEW instance so we are in a loop where I cannot restore my snapshot to a new Beanstalk env, you cannot manually repoint the db reference and you cannot add a db to a new beanstalk instance where a RDS is not generated.

**Comment by salsakran** [comment]
@Glathrop this is not really an appropriate question for the issue tracker. 

I suggest trying either our discussion forum (discourse.metabase.com) or the AWS docs and support forum.

**Comment by Glathrop** [comment]
Since Google is a thing and folks will find this here's how you can use Elastic Beanstalk & a snapshot to handle this. 

- Make sure you have a recent snapshot of the database containing your metabase config
- Goto the Elastic Beanstalk homepage
- Click on the failed application
- Under the "Actions" dropdown select "Save Configuration"
- Give your saved configuration a name & description
- Go back to the Elastic Beanstalk dashboard
- Under the "Actions" dropdown select "View saved configurations"
- Select your saved configuration
- Click "Launch Environment"
- Select "Web server environment"
- Give it a name
- Select "existing application" and select the metabase version you were using previously.
- IMPORTANT: Select the "Configure more options" button.
- Find the Database card and click "Modify"
- You will finally see an option to "Restore a snapshot"
- Select the snapshot you want to use from the dropdown. 
- The rest of the configuration settings should match the original. 
- Get back to the Configuration page with all the cards.
- Click "Create Environment"
- Follow the instructions below if you're setting up the load balancer.
