### ISSUE TITLE
Duplicated X-axis labels for date "x-of-y" groupings

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#6894]
<img width="1274" alt="screenshot 2018-02-07 10 34 49" src="https://user-images.githubusercontent.com/178038/35934468-944c0ae6-0bf2-11e8-8122-bf5070c99fd0.png">
<img width="977" alt="screenshot 2018-02-07 10 35 55" src="https://user-images.githubusercontent.com/178038/35934519-b16e866c-0bf2-11e8-8fef-143fea509f16.png">
Same thing happens with line charts.

**Comment by flamber** [comment]
Hi @sbelak 
I cannot reproduce this issue on 0.31.2.
![image](https://user-images.githubusercontent.com/1447303/52980042-de104100-339d-11e9-9a98-6f3abbdc2efa.png)

**Comment by sbelak** [comment]
Agree. Looks to be fixed.
