### ISSUE TITLE
Bar Charts in Pulses not rendering with user-defined X/Y axis

### ISSUE THREAD

**Issue by senior** [metabase/metabase#6895]
Pulses with cards that have a row chart and user-defined X and Y axis don't render their graph correctly. It looks like I missed it [here](https://github.com/metabase/metabase/commit/53e9a48f5039cdeec0ecc072de91e2a4457d7d7d). I'm not sure if the bar chart code just needs to be updated to use the new column functions or if there's a problem with the X/Y axis code as well.

**Comment by salsakran** [comment]
fixed via #6897
