### ISSUE TITLE
Update tab in Admin panel not rendering correctly

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#6896]
![image](https://user-images.githubusercontent.com/1711649/35944493-6447f690-0c3b-11e8-849d-a9cec6212b62.png)

- Your browser and the version: Chrome Latest
- Your operating system: MacOS
- Your databases: PostgreSQL
- Metabase version: latest (0.28)
- Metabase hosting environment: Docker container
- Metabase internal database: PostgreSQL

- *Repeatable steps to reproduce the issue*
Click on your name --> admin panel --> Updates

**Comment by paoliniluis** [comment]
closing as fixed

**Comment by salsakran** [comment]
@paoliniluis  0.28.1 was just released which fixes this.
