### ISSUE TITLE
Feature Request - Related/Linked Filters - Drill Down FIlters

### ISSUE THREAD

**Issue by deadlocks** [metabase/metabase#6899]
Is there any way in which all filters on Dashboard can be linked. For example I have a tree structure with 3 levels and I create 3 filters (one for each level)

So if anything is selected in Level 1 filter, Level 2 and 3 will display values corresponding to value selected in Level 1.

It's like drill down but for filters 

![rq](https://user-images.githubusercontent.com/2733405/35964815-e0d6b022-0cde-11e8-9dd4-fed5b1ad045b.png)

**Comment by jornh** [comment]
Sounds like a duplicate of #5540

**Comment by deadlocks** [comment]
@jornh Yes, Thanks. Closing this one and upvoting the original issue.
