### ISSUE TITLE
Bug at https://metabase.com/ "Setup Guide" button

### ISSUE THREAD

**Issue by lucassabreu** [metabase/metabase#6900]
Hello, when I click the button "Setup Guide" the link is redirected to "http://localhost:4000/docs/latest". If I change the URL to "https://metabase.com/docs/latest/" then I get to the docs.

![image](https://user-images.githubusercontent.com/3457213/35970276-e3e85bf4-0cb0-11e8-89af-3f5131928caf.png)

**Comment by kdoh** [comment]
Thanks for reporting this. Should be all fixed.
