### ISSUE TITLE
Fatal Error on Mac with Previous and Latest Version

### ISSUE THREAD

**Issue by kudwitt** [metabase/metabase#6902]
I've tried uninstalling and reinstalling and end up in the same place:

The Metabase server terminated unexpectedly.

Messages:
INFO metabase.core :: Starting Metabase in STANDALONE mode
INFO metabase.core :: Launching Embedded Jetty Webserver with config:
{:port 13452}
INFO metabase.core :: Starting Metabase version v0.27.2 (35acf6e HEAD) ...
INFO metabase.core :: System timezone is 'America/New_York' ...
WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
INFO metabase.db :: Verifying h2 Database Connection ...
ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-194]
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))at metabase.db$verify_db_connection.invokeStatic(db.clj:334)
at metabase.db$verify_db_connection.invoke(db.clj:327)
at metabase.db$verify_db_connection.invokeStatic(db.clj:330)
at metabase.db$verify_db_connection.invoke(db.clj:327)
at metabase.db$setup_db_BANG_.invokeStatic(db.clj:382)
at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at metabase.core$init_BANG_.invokeStatic(core.clj:108)
at metabase.core$init_BANG_.invoke(core.clj:87)
at metabase.core$start_normally.invokeStatic(core.clj:

**Comment by salsakran** [comment]
@kudwitt Your h2 database file is corrupted. 

The issue tracker isn't really an appropriate place for things like this (common problems with solutions found in our docs)

 https://www.metabase.com/docs/latest/troubleshooting-guide/application-database.html has more information about how to recover from this situation.
