### ISSUE TITLE
Proposal: rethinking collections

### ISSUE THREAD

**Issue by lbalves** [metabase/metabase#6907]
I was rethinking about questions and dashboards organization (based on https://github.com/metabase/metabase/issues/6509), and I came across one possible solution. What if we had distinct permission and tagging controls for dashboards and questions?

Permissions would be responsible for setting "which user group should have access to that resource".

Tags, in other hand, would "categorize the resource", allowing us to create more flexible categorization of the resources (today, collections allow only one level of categorization). My company currently have 150 employees and something around 10 areas. Also, we have three main business units and this is kind of hard to find out one category hierarchy common for grouping questions.

Here's a low level mockup about the tag proposal: https://docs.google.com/presentation/d/1a-n7e82c3bCpyoXDzAd0C7HW3XEYbQU0kYCNdskIPvk/edit?usp=sharing

Another benefit from tagging, is that it may help us infer relationship between questions and dashboard (from Zen of Metabase: Structure things so that we can automagically infer things for the user) helping users to categorize future resources, suggest related questions and things like that.

If it's considered a good proposal (or even if it's not clear enough), I can expend more time refining the idea, helping with the design and testing.

**Comment by mazameli** [comment]
The product has changed so much since this issue was opened that I don't think it's relevant any longer.
