### ISSUE TITLE
Text cards don't scroll in Firefox

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6910]
This is the case either with a laptop touchpad or the scroll wheel on a mouse.

First reported by a Discourse user here: http://discourse.metabase.com/t/version-0-28/2900/8?u=maz

I was able to reproduce this, and it seems to be strictly a Firefox issue. Safari and Chrome work fine, and the Discourse user confirmed that IE and Chrome on Windows work fine as well.

![screen shot 2018-02-08 at 3 51 42 pm](https://user-images.githubusercontent.com/2223916/36004532-068d655a-0ce8-11e8-9590-ad26992b2187.png)

**Comment by flamber** [comment]
Duplicate of #8333 (seems to be an issue on all browsers now) - still exists on 0.31.2

**Comment by salsakran** [comment]
should be closed in #9919
