### ISSUE TITLE
metabase   user level permission issue

### ISSUE THREAD

**Issue by Justmfree** [metabase/metabase#6922]
how can be done to set metabase  user level permission  to restrict add a question and edit dashboard ?
i have metabase updated server.

**Comment by jornh** [comment]
Generally questions are better asked - or searched for - on the Metabase discussion forum. So if the below does not fully help let's continue talking over there! 🙂 

Depending on at what level you need this it might [already be possible](http://discourse.metabase.com/t/improve-user-permission-dashboard/2766/3?u=jornh)   - or [planned but not yet](http://discourse.metabase.com/t/improve-user-permission-dashboard/2766/4?u=jornh) implemented.

**Comment by kdoh** [comment]
Yup, thanks @jornh. If a tangible issue comes out of this we can continue this or have the discussion on the appropriate issue.

**Comment by Justmfree** [comment]
please give me simple answer :) it is possible now ? or you are working to add this user permission feature ?  especially only view permission
