### ISSUE TITLE
SSL on Java?

### ISSUE THREAD

**Issue by felixsim** [metabase/metabase#6934]
I’ve managed to generate a jks file with the crt files issued by my SSL provider. Also managed to startup metabase successfully with the correct environment variables. 

However when I try to access my site through HTTPS chrome returns an error saying cipher mismatch. 

Where should I look to debug this problem?

**Comment by jornh** [comment]
@felixsim (or a core team member) please close this. 

I believe this is more a matter of config af https outside Metabase - not a MB issue. And already being discussed in http://discourse.metabase.com/t/ssl-for-java-installation-to-access-through-https/2926/11
