### ISSUE TITLE
Row Charts should support goal lines

### ISSUE THREAD

**Issue by jornh** [metabase/metabase#6938]
Just as goal lines are available in Bar/Line/Area charts etc. it would be useful to have the same in Row Charts.

For additional context see #6937 

⬇️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by flamber** [comment]
@jornh Is this a dupe or related to #4588

**Comment by jornh** [comment]
Yes a dupe! Good catch, I even :+1: #4588 already - closing this.
