### ISSUE TITLE
Documentation of Row Charts is missing in the Users Guide

### ISSUE THREAD

**Issue by jornh** [metabase/metabase#6940]
The super useful *Row Chart* (aka 📊 +90° for added category label reading comfort 😉) implemented in #4317 apparently never got any honorable mention in [the users guide](https://metabase.com/docs/latest/users-guide/05-visualizing-results.html)

Apart from the obvious advantage that you don't have to turn your head and halfway break your neck to read the labels as you do on a bar chart (if it has vertical labels) I think it also deserves pointing out that by default it also adds an `Others` bin. This works really well if you apply "Sort by count, descending" in the `...` menu as it, like the pie chart highlights the "long tail" 🦕 of your data. It includes auto-magic responsive adjustment of the number of categories to fit the available space.

 ![rowyourboat](https://cloud.githubusercontent.com/assets/18193/22679397/be0c47bc-ecb6-11e6-9f00-98437ad28bfb.png)

**Comment by mazameli** [comment]
Fixed in https://github.com/metabase/metabase/pull/7382

**Comment by jornh** [comment]
https://github.com/metabase/metabase/pull/7382 is short sweet and to the point. 

Closing!
