### ISSUE TITLE
Move Table Count out of Sync and into Analysis

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#6941]
We shouldn't be doing a `select count(*)` for each table in the sync process.

The sync process is meant to be a pretty lightweight process that can run quickly and with minimal load on a data warehouse.

**Comment by mfpinhal** [comment]
My 2 cents on this one:
- Indeed the hourly check should not be so heavy for the DW.
- Wouldn't row count estimates ([example](https://wiki.postgresql.org/wiki/Count_estimate) for Postgres), be enough? (I'm not aware what this number is used for in Metabase).
+ Per-table configurations:
  - Be able to tweak settings for the 2 types of syncs - lightweight/hourly and the daily/intensive analysis - configure whether to use precise count sync or opt by estimated count instead. For large tables, we may opt to use estimates only, or:
  - Choose the schedule for the in-depth intensive analysis sync - hourly, daily, weekly, monthly?.
  - Automate: We could use count estimates and additionally the last Metabase sync run times for each table to decide whether to perform a full count. Different settings could 

Also, linking this to https://github.com/metabase/metabase/issues/6492.

**Comment by salsakran** [comment]
dropping this from a p1 since we commented it out in #7061

**Comment by camsaul** [comment]
I don't think Table row count is coming back any time soon. #12797 will remove the commented out code entirely. Closing this issue as No Longer Relevant
