### ISSUE TITLE
Kitten break link broken

### ISSUE THREAD

**Issue by Tim-The-Third** [metabase/metabase#6946]
### Bugs
When directed to the     
![image](https://user-images.githubusercontent.com/34242653/36145662-f714af96-10a9-11e8-9b5e-f0fe75268199.png) screen however was then met with crushing disapointment 

![image](https://user-images.githubusercontent.com/34242653/36145691-0a323a58-10aa-11e8-8290-d9f7dad9ddd1.png)

Your browser and the version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Your operating system: Mac OS High Sierra 10.13.2
Your databases: Postgres
Metabase version: v0.28
Metabase hosting environment: Postgres

**Comment by mazameli** [comment]
![cat](https://media2.giphy.com/media/gCL5fOMAVijWE/giphy.gif)

**Comment by mazameli** [comment]
Looks like Giphy changed how Giphy TV works.
