### ISSUE TITLE
make the table visualization work normally on mobile

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#695]
currently if you run a query on a mobile phone and display it as a table the grid shows up fine, but you can't scroll within the table itself and see all the rows.  lets figure out why that's happening and fix it so the user can access all the rows on mobile.

**Comment by agilliland** [comment]
@tlrobinson is it safe to close this one as fixed after all the latest visualizations updates?

**Comment by kdoh** [comment]
Closing as no longer relevant.
