### ISSUE TITLE
Dashboard Filters - Unable to select date range spanning over multiple years

### ISSUE THREAD

**Issue by kurbar** [metabase/metabase#6952]
I'm trying to add a date range filter to my dashboard that by default would start since Sept 1 2017, however I'm unable to set it. When I select a range within a year (e.g. Jan 1 2018 - Feb 2 2018) it works but when it crosses to another year (be it before or after) (e.g. Dec 30 2017 - Jan 2 2018), it fails to set the date range, it resets it.

-------

Your browser and the version: Chrome 63.0.3239.132
Your operating system: Mac OS X Sierra 10.12.6
Your databases: Postgres
Metabase version:  0.28.1
Metabase hosting environment: Docker
Metabase internal database: H2 (default)

**Repeatable steps to reproduce the issue**
1. Create a dashboard
2. Add a filter to the dashboard
3. Try to set a date range that spans at least two years (e.g. Dec 30 2017 - Jan 3 2018)

**Comment by salsakran** [comment]
I don't think it has anything to do with the date crossing a year boundary. 

I'm seeing it when I use a full date filter on a dashboard with a single card. The card is just count of orders in the sample dataset. 

Steps to reproduce:
1. try to set a date two years in the future
2. Select a new start date
3. Click the end date, and use the `>` to move forward in months. 
4. At some point the `>` doesn't cause the calendar to advance.

**Comment by jescorotero** [comment]
Same behaviour here
