### ISSUE TITLE
Moving/Trailing Average grouping option

### ISSUE THREAD

**Issue by joevandyk** [metabase/metabase#6954]
We are looking to setup a pulse that shows a graph of past weekly averages, but the week starts on the current day. 

So if today is Wednesday, I’d like the grouping to be last Wednesday to today, two Wednesdays ago to last Wednesday, etc. Right now grouping by week means only Monday-Sunday grouping. 

I think this is called Moving Average?

**Comment by aroff** [comment]
This would be useful for me too!

**Comment by markpaygo** [comment]
Any update on this or potentially an SQL workaround in the meantime?

**Comment by sbelak** [comment]
I've opened #9393 to consolidate all design considerations around windowing functions and eventually implement them. Mind moving the discussion there.

@markpaygo in terms of SQL you probably want something along the lines of https://mode.com/sql-tutorial/sql-window-functions/

**Comment by markpaygo** [comment]
thanks for the link!
