### ISSUE TITLE
Removed metrics still show up in data reference

### ISSUE THREAD

**Issue by sedough** [metabase/metabase#6958]
I created/retired/replaced several metrics (because I didn't know what I was doing), but now the "Data Reference" section is cluttered with retired metrics that aren't being used for anything.

Metabase version v0.28
Google Chrome  64.0.3282.167 running on Mac
Postgresql 10 database
Hosted on Linux/Docker using H2 database

**Comment by paulrosenzweig** [comment]
It looks like we're correctly filtering out retired metrics in the data reference now. I'm guessing this was inadvertently fixed sometime since this issue was opened. I'll close it, but feel free to reopen if it recurs.
