### ISSUE TITLE
Failing to install on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#6961]
- Metabase version: latest
- Metabase hosting environment: Elastic Beanstalk, Docker
- Metabase internal database: Postgres?

# Steps to reproduce
1. go to https://www.metabase.com/start/aws.html
2. click 'Launch Metabase on AWS'
3. fill in details according to [operations guide](https://www.metabase.com/docs/v0.28.1/operations-guide/running-metabase-on-elastic-beanstalk.html)
4. **Note**: the **Application code** defaults to *sample application*:
![screenshot from 2018-02-15 11-40-20](https://user-images.githubusercontent.com/17307/36250012-3b51bd92-1245-11e8-8735-c4810974a902.png)
5. click **Upload your code** under Application code section

The operations guide says that the 'upload your code' should already be selected:

> If you reached this screen from the Metabase start page at www.metabase.com/start/aws.html the application code settings will have already been set and you don’t need to do anything.

What image or file should I upload under the upload your code section? If I don't provide a file here, the installer seems to get stuck on:

> createEnvironment is starting.

**Comment by billy-bacon** [comment]
I found this doc which is from an earlier version of metabase version docs, but it points to a zip file you can point the configuration to: https://www.metabase.com/docs/v0.12.0/operations-guide/running-metabase-on-elastic-beanstalk.html

**Comment by xaviershay** [comment]
I thought I hit this issue, because "Upload your code" was not ticked and I was assuming pressing "Upload" would take me to a file selection dialog .. but actually it opens a window where S3 details are pre-filled.

**Comment by flamber** [comment]
This was likely caused by a bad redirect, which was fixed since 0.33.4
For reference, here's a link to latest documentation:
https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html
