### ISSUE TITLE
SSL encryption for default deployment?

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#6962]
We have deployed Metabase to Elastic Beanstalk using the Docker image. The default deployment has no SSL encryption, so poses a security risk out of the box.

Please consider including the [Certbot Docker image](https://hub.docker.com/r/certbot/certbot/) in the default deployment, so Metabase deployments are secure by default.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by paoliniluis** [comment]
We have deprecated shipping the Beanstalk artifacts, so this is no longer relevant. Users will have to build their own beanstalk artifacts from now on
