### ISSUE TITLE
Printed Dashboard is missing Color Indicators in the Legend

### ISSUE THREAD

**Issue by dgleba** [metabase/metabase#6963]
Printed graph is missing the green and blue dots in the legend. See the two screen shots below. The first is printed, the second is the dashboard on the screen.

![image](https://user-images.githubusercontent.com/4622715/36264983-2fc39a12-123c-11e8-9b87-bbbc9474054c.png)

![image](https://user-images.githubusercontent.com/4622715/36264937-0b44dfca-123c-11e8-85a3-3a8907455c50.png)

- Your browser and the version: Chrome Version 63.0.3239.108 (Official Build) (64-bit)
- Your operating system: Windows 7, Win 10
- Your databases:  MySQL
- Metabase version: 0.25.2
- Metabase hosting environment:  Linux/Ubuntu 14.04
- Metabase internal database: MySQL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by maajesus** [comment]
+1. I'm facing the same issue. Any Workaround?

**Comment by maajesus** [comment]
Hi @dgleba make sure you have the option **Backgrounds Graphics** checked, for me is working fine.


![image](https://user-images.githubusercontent.com/17711622/48701199-40ff0a00-ebee-11e8-998f-ece297af3e44.png)

![image](https://user-images.githubusercontent.com/17711622/48701355-9509ee80-ebee-11e8-9d4b-a25bb3915243.png)

Hope this Help!!!

**Comment by ycaruso** [comment]
> Hi @dgleba make sure you have the option **Backgrounds Graphics** checked, for me is working fine.
> 
> ![image](https://user-images.githubusercontent.com/17711622/48701199-40ff0a00-ebee-11e8-998f-ece297af3e44.png)
> 
> ![image](https://user-images.githubusercontent.com/17711622/48701355-9509ee80-ebee-11e8-9d4b-a25bb3915243.png)
> 
> Hope this Help!!!

Thank you so much, you have helped me enormously.

**Comment by tlrobinson** [comment]
It sounds like this CSS property will work in Chrome/Safari:

```
  -webkit-print-color-adjust: exact !important;
```

Some other solutions: http://maxlapides.com/forcing-browsers-print-backgrounds/
