### ISSUE TITLE
Slack Pulses don't work anymore

### ISSUE THREAD

**Issue by benjR** [metabase/metabase#6964]
Hi there!

I can't get Slack updates to work anymore.
The email updates (pulses or alerts) are working correctly, activating slack on the same alerts/pulses does not work. 
I've checked the token and created a new one just in case, metabot is on slack and responding to commands, but when trying `metabot list`, this is the message I get: `Heres your {0} most recent cards:
{1}`
When testing slack in the pulse creation page, I get the following errors in metabase logs:

```
02-15 17:04:55 DEBUG metabase.middleware :: GET /api/pulse 200 (183 µs) (1 DB calls)
02-15 17:04:56 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (516 ms) (0 DB calls)
02-15 17:04:57 DEBUG metabase.middleware :: GET /api/user 200 (493 µs) (1 DB calls)
02-15 17:04:57 DEBUG metabase.middleware :: GET /api/pulse/preview_card_info/33 200 (35 ms) (9 DB calls)
02-15 17:04:57 DEBUG metabase.middleware :: GET /api/card 200 (84 ms) (6 DB calls)
02-15 17:04:57 DEBUG metabase.middleware :: GET /api/pulse/form_input 200 (904 ms) (0 DB calls)
02-15 17:05:22 DEBUG metabase.middleware :: GET /api/pulse/preview_card_info/37 200 (53 ms) (10 DB calls)
02-15 17:05:55 DEBUG metabase.middleware :: GET /api/session/properties 200 (776 µs) (1 DB calls)
02-15 17:05:55 DEBUG metabase.middleware :: GET /api/user/current 200 (446 µs) (1 DB calls)
02-15 17:05:55 DEBUG metabase.middleware :: GET /api/user/current 200 (225 µs) (1 DB calls)
02-15 17:05:55 DEBUG metabase.middleware :: GET /api/setting 200 (149 µs) (0 DB calls)
02-15 17:05:55 DEBUG metabase.middleware :: GET /api/database 200 (101 ms) (5 DB calls)
02-15 17:06:01 ERROR metabase.middleware :: POST /api/pulse/test 500 (646 ms) (10 DB calls)
{:message "Can't create output stream!",
 :type javax.imageio.IIOException,
 :stacktrace
 ["pulse.render$render_to_png.invokeStatic(render.clj:241)"
  "pulse.render$render_to_png.invoke(render.clj:216)"
  "pulse.render$fn__23305$render_html_to_png__23310$fn__23314.invoke(render.clj:251)"
  "pulse.render$fn__23305$render_html_to_png__23310.invoke(render.clj:243)"
  "pulse.render$render_pulse_card_to_png.invokeStatic(render.clj:709)"
  "pulse.render$render_pulse_card_to_png.invoke(render.clj:706)"
  "pulse$create_slack_attachment_data$iter__32475__32479$fn__32480$fn__32481$fn__32484.invoke(pulse.clj:69)"
  "pulse$create_and_upload_slack_attachments_BANG_$iter__32498__32502$fn__32503$fn__32504.invoke(pulse.clj:80)"
  "pulse$create_and_upload_slack_attachments_BANG_$iter__32498__32502$fn__32503.invoke(pulse.clj:79)"
  "pulse$create_and_upload_slack_attachments_BANG_.invokeStatic(pulse.clj:78)"
  "pulse$create_and_upload_slack_attachments_BANG_.invoke(pulse.clj:75)"
  "pulse$fn__32586.invokeStatic(pulse.clj:201)"
  "pulse$fn__32586.invoke(pulse.clj:199)"
  "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:214)"
  "pulse$send_notifications_BANG_.invoke(pulse.clj:212)"
  "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:240)"
  "pulse$send_pulse_BANG_.doInvoke(pulse.clj:231)"
  "api.pulse$fn__32756$fn__32759.invoke(pulse.clj:155)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
  "api.pulse$fn__32756.invokeStatic(pulse.clj:147)"
  "api.pulse$fn__32756.invoke(pulse.clj:147)"
  "middleware$enforce_authentication$fn__33152.invoke(middleware.clj:123)"
  "api.routes$fn__46126.invokeStatic(routes.clj:80)"
  "api.routes$fn__46126.invoke(routes.clj:80)"
  "routes$fn__46856$fn__46857.doInvoke(routes.clj:106)"
  "routes$fn__46856.invokeStatic(routes.clj:101)"
  "routes$fn__46856.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33251$fn__33253.invoke(middleware.clj:342)"
  "middleware$log_api_call$fn__33251.invoke(middleware.clj:341)"
  "middleware$add_security_headers$fn__33201.invoke(middleware.clj:255)"
  "core$wrap_streamed_json_response$fn__47651.invoke(core.clj:66)"
  "middleware$bind_current_user$fn__33156.invoke(middleware.clj:144)"
  "middleware$maybe_set_site_url$fn__33205.invoke(middleware.clj:279)"]}
```

Any help would be appreciated! :)

### Bugs

- Your browser and the version: Chrome 64.0.3282.167
- Your operating system: MacOS 10.13.2
- Your databases: MySQL
- Metabase version: 0.28.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*
 - Go to Pulses, create a pulse
 - Name your pulse
 - Filter on a question (number type for example)
 - Deactivate the email in "Where should this data go?"
 - Activate slack, select a channel or a nickname, select sent hourly
 - Click on Send to Slack now

**Comment by marcoruggine** [comment]
I have the same exact thing. 
I used to get several automatic pulses every morning but since the update I have to manually send them every time.
Please fix it because it's a matter of my mental sanity 🤯

**Comment by senior** [comment]
@benjR Unfortunately the real error behind the one you're seeing is hidden due to #7024. Would you be able to run the code in the [debug-pulse-slack-sends](https://github.com/metabase/metabase/tree/debug-pulse-slack-sends)? I made a small change that will log the exception (along with the root cause) before throwing it and hitting the issue causing #7024.

**Comment by benjR** [comment]
@senior I could... if there there a way to do that with docker ?

**Comment by benjR** [comment]
Ok so I copied the metabase files, started docker from your branch on the same host, pulses are working.
Copied files again and started the same version (0.28.1) where I have the issue, working....

**Comment by benjR** [comment]
Confirmed, I don't have the issue anymore.
I think it was due to the directories I was mapping : I was mapping the /tmp folder to a local folder on the host and files were being kept here between instances, when copying data to another container I was copying only the main .db file, the newly launched instance didn't have access to those files and was starting fresh.

**Comment by senior** [comment]
@benjR That makes sense, what made this issue more difficult is the real cause of the error wasn't known. I've created a PR #7059 to at least include the full exception in the log until we can fix the root issue here.
