### ISSUE TITLE
Select popover scrolling weirdness

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6969]
The title of this description reads like a tag cloud, but what I'm seeing is that when you go to map a dashboard filter to a field in a saved question, when the scroll down a bit, and then try to scroll up just a little bit, the scroll bar jumps all the way back up to the top of the list:

![scrolling problems](https://user-images.githubusercontent.com/2223916/36326569-62b8d62e-1310-11e8-89b0-b2459fd57b9f.gif)

**Comment by mazameli** [comment]
I'm actually also seeing this for long lists of fields in the query builder, and it sometimes results in this wacky extra space at the top once it's scrolled back up:

![screen shot 2018-02-16 at 4 49 11 pm](https://user-images.githubusercontent.com/2223916/36336069-7837e0f2-1339-11e8-9036-57c684ac15d1.png)

**Comment by flamber** [comment]
This is still an issue with the new Select (upcoming 0.35). But because it's now being used more places, it's a lot easier to encounter this annoyance.
It feels like when you scroll up, it focuses the search input, which makes it jump to the top.
I haven't seen the extra white space ever.
