### ISSUE TITLE
Questions using Nested Questions with Aggregate columns fail

### ISSUE THREAD

**Issue by timmclaughlin** [metabase/metabase#6971]
(using Postgres on Heroku)
1) Create a Question with an aggregate column such as Count or Sum (named Q1).
2) Create a Question (named Q2) using Q1 as it's Data.  Everything works so far with Grouping & View columns.
3) Failure occurs when a Filter is used in Q2.  Error is as follows regardless of if the filter is on an aggregate column or grouped. 

Error detail: Input to compound-filter does not match schema: [0;33m [nil (named (named (not (matches-some-precondition? nil)) "Valid filter clause") subclause)] [0m

From logs:
FETCHED SOURCE QUERY FROM CARD 69 :
{:source_table 165,
:filter ["AND" ["SEGMENT" 6]],
:breakout [["fk->" 2098 1799] ["fk->" 2098 1818]],
:aggregation [["count"]],
:expressions {:Total ["+" ["field-id" 2101] ["field-id" 2099]]},
:database 4}

Feb 16 20:27:52 WARN metabase.query-processor.middleware.expand :: It doesn't make sense to use `field-literal` forms inside `field-id` forms.
Instead of [field-id [field-literal ...]], just do [field-literal ...].
Feb 16 20:27:52 WARN metabase.query-processor.middleware.expand :: It doesn't make sense to use `field-literal` forms inside `field-id` forms.
Instead of [field-id [field-literal ...]], just do [field-literal ...].
Feb 16 20:27:52 WARN metabase.query-processor.middleware.expand :: It doesn't make sense to use `field-literal` forms inside `field-id` forms.
Instead of [field-id [field-literal ...]], just do [field-literal ...].
Feb 16 20:27:53 WARN metabase.query-processor :: {:status :failed,
:class clojure.lang.ExceptionInfo,
:error "Input to compound-filter does not match schema: \n\n\t [nil (named (named (not (matches-some-precondition? nil)) \"Valid filter clause\") subclause)] \n\n",
:stacktrace

**Comment by flamber** [comment]
Hi @timmclaughlin 
I cannot reproduce your issue on 0.31.2 with Postgres 11.2 - could you try again with a newer Metabase?
1. Created a question (TEST 6971):
![image](https://user-images.githubusercontent.com/1447303/52977318-71437980-3392-11e9-80d5-9d830fbd3536.png)
2. Then selected "TEST 6971" from "Saved Questions":
![image](https://user-images.githubusercontent.com/1447303/52977196-02feb700-3392-11e9-91c2-7f4b147b21bb.png)
