### ISSUE TITLE
Option to hide the header (title) for embedded questions

### ISSUE THREAD

**Issue by nevir** [metabase/metabase#6972]
Hey, I'd like to be able to hide (or at least greatly compress) both the header and footer of iframe-embedded questions (`/public/question/:uuid`)

Possibly something to specify via URL params? `/public/question/:uuid?header=hide&footer=hide`

**Comment by mazameli** [comment]
Sounds like you're trying to embed a few charts in a relatively small space? By the header, do you just mean the title of the question? As for the footer with the "Powered by Metabase" logo, you can purchase a license to remove that here: https://store.metabase.com/product/embedding

**Comment by nevir** [comment]
> Sounds like you're trying to embed a few charts in a relatively small space? By the header, do you just mean the title of the question?

Yeah, and already have titles w/ some extra description (inlining charts into a document)

> As for the footer with the "Powered by Metabase" logo, you can purchase a license to remove that here: store.metabase.com/product/embedding

Aha! 👍

**Comment by boltronics** [comment]
Similar use case here. We have a browser running fullscreen on a Raspbery Pi connected to a TV to display a dashboard to the office. Unfortunately about 1/10th of the screen is wasted on the name of the dashboard, and the bottom labels of our graphs won't fit.

It's possible to install ublock to have the header removed, but it would be much nicer to be able to control this from within Metabase.

**Comment by flamber** [comment]
It is possible to remove the title on Public question with anchor `#titled=false`, similar to Embedding.
```
/public/question/:uuid#titled=false
```
Not sure when it was added (think it has always been there), but this is how it looks in 0.35.4:
![image](https://user-images.githubusercontent.com/1447303/83877744-5d648800-a73b-11ea-8393-df35ef8c43ef.png)
For comparison without the anchor in the URL (the default):
![image](https://user-images.githubusercontent.com/1447303/83877855-8422be80-a73b-11ea-84b5-d60b1bf09df1.png)
