### ISSUE TITLE
Drill through from table selects wrong year

### ISSUE THREAD

**Issue by rkotkiewicz** [metabase/metabase#6985]
Metabase version: v0.28.1.
It can be reproduced on the sample data set.

Custom question:
DATA: Orders
GROUPED BY: Created At: Year, Quantity, User -> Name 

How to reproduce:
1) Click any year in the 'Created At: Year' column, then click  '='. The filter will get an unknown year.
2) Pivot the table, click any name, and then click 'View these Orders'. The filter will get a wrong year.

**Comment by salsakran** [comment]
Reproduced.

Think it's related to #6988

**Comment by salsakran** [comment]
this should be fixed in #7011 and will be in our next release (0.29)
