### ISSUE TITLE
Group by Quarter showing incorrect labels on bar graph.

### ISSUE THREAD

**Issue by jmwohl** [metabase/metabase#6987]
When creating a bar graph from quarterly data, the X-axis 'quarter' labels are incorrect. The hover-state labels are correct.

To reproduce, create a question that sums data grouped by quarter. Look at the X-axis quarter labels, i.e. 'Q1 - 2017' — in my case, these labels are incorrect, with the first label being repeated for the first two bars.

![Screenshot](https://i.imgur.com/KrYbwFs.png)

OS X 10.11
MySQL
Metabase v0.28.1.0
Mac app env

**Comment by tlrobinson** [comment]
@jmwohl @tkopets I believe we have a fix for this in #7247. Please give it a try and let me know if it does or doesn't fix this for you (and hopefully doesn't make things worse...)
