### ISSUE TITLE
Allow putting dashboard filter value in text boxes.

### ISSUE THREAD

**Issue by wvengen** [metabase/metabase#6991]
It would be great to support substituting dashboard filters in text boxes (available since #6436). Most important use-case would be generating URLs to external systems. This would allow one to make the URL specific to the selected filter parameters.

E.g. with a dashboard filter called _Source_, one would be able to use a text like the following in a text box:

    See [all {{source}}'s products](https://products.example.com/products?q[source_eq]={{source}}).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jornh** [comment]
Oh boy that's a sweet idea! 😍 ... Just to add a bit of 🍋 complexity to the matter (+ *one* possible - way to handle it?):

Another nice feature just added in v0.28: https://metabase.com/blog/Metabase-0.28/index.html#multi-select-dashboard-filters would mean that those should need a pinch of `forEach()` salt?

**Comment by mickaelmarchese** [comment]
Any progress on this nice feature?

**Comment by flamber** [comment]
A workaround is to use a SQL question to create a table using variable filters - see this example:
https://discourse.metabase.com/t/pass-filter-between-dashboards/7307/4?u=flamber
Related to #9080 and #4392

**Comment by koe-n** [comment]
After the [announcement](https://github.com/metabase/metabase/releases/tag/v0.38.0) that pulses will eventually be replaced by dashboard subscriptions, this issue would really bring that concept to a next level. 

We put a lot of effort in storytelling in our dashboards, and would love our stories in Metabase to become dynamic. Having the ability to include dropdown values (P1) and card results (P2) in our text boxes, would really help to steer our end users to the right conclusions from the data in the graphs.

Next to that, we build dashboards for several brands. This functionality would make it possible to show a different image/log based on a value in a dropdown menu which would make dashboards a lot more appealing.

**Comment by levinemi** [comment]
Any update on this feature. It would be a big add for my company's dashboards too.

**Comment by brywhi** [comment]
This is done now, right?
