### ISSUE TITLE
Follow-up polish for filter search widget

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#6995]
Follow-up items for https://github.com/metabase/metabase/pull/4241

**Quriks**
- [ ] If an existing query builder category filter uses an operator other than `Is`, the operators list should be expanded by default when clicking on the filter to modify it.
- [ ] The operators being hidden under Options was only intended to be the behavior for categoric fields, not numeric ones. The filter popover for numeric fields should be unchanged.
- [x] If I've clicked on Options to show the logical operators, but then I click to go back to the list of fields and select a different field to filter on, the options have stayed opened, which I did not expect.
- [ ] Finite lists of options incorrectly display `Including every option in your filter probably won’t do much…` if you enter in a search parameter that doesn't match any value in the list.
- [ ] In the case of FK fields where I can search by an entity name _or_ enter an ID, if I start typing an ID I get the "no matching results found" message. This is correct in that it's trying to search the list of entity names, but it makes me feel like I'm typing in an incorrect ID. My current dumb idea for a solution would be to change the no-results message in this case to include the entity name, like, "No matching Last Names found," to clarify a little that it's searching on the entity name, and that the ID you're typing isn't wrong.

**Visuals**
- [ ] Get a max-width in place so that the popovers don't change in size as more options are selected and added to the token box
- [ ] Implement the design for the default state for search widgets, with the magnifying glass
- [ ] After `Options` is clicked, it should either go away or change to `Hide options`
- [ ] The `Options` button can get really close to long field names. This will be fixed somewhat by the width of the popover getting extended and fixed, but the Options link itself also needs some extra padding-left.
- [ ] Dashboard category filters widgets are missing `cursor-pointer`, as is our hallowed tradition. Not talking about the popover, but the filter widget itself, both when the filter is inactive as well as active.

**Comment by salsakran** [comment]
is this just a result of my weird wireless mouse again?

![screen shot 2018-02-21 at 11 33 26 am](https://user-images.githubusercontent.com/107439/36501118-20b515b4-16fb-11e8-9c9d-1c92e887e8b9.png)

**Comment by mazameli** [comment]
@salsakran no, I noted that as a to-do item in the CSS polish branch, but I mistakenly thought it got fixed because I turned off the macOS setting that causes that behavior. @kdoh can correct me if I'm wrong, but I believe this is the same issue that was happening with dashboard text cards, and should have the same relatively simple solution. Good catch.

**Comment by jornh** [comment]
@mazameli said:
> but I believe this is the same issue that was happening with dashboard text cards, and should have the same relatively simple solution. Good catch.

Guys, I realize this stuff is still pending, so I shouldn't assume this polishing is completed with a `master` build as of "right now" (but I just couldn't help it wanting to kick the tires on what's cooking for 0.29). So in place of creating a separate issue I'll just add to the conversation here. Basically it's just a confirmation of the above finding in https://github.com/metabase/metabase/issues/6995#issuecomment-367443975 as seen on my Win 10/Chrome 63 - that with a CSS correction from `overflow: scroll` to `overflow: auto` (as I just quickly added manually in the DevTools shot below) I only get scrollbars when they are needed - like it was the case in #6926:

The new filter widget is awesome BTW! 😸 

![developer tools - httplocalhost3000question1](https://user-images.githubusercontent.com/766423/36606468-17b788aa-18c4-11e8-92a6-69bddfba836e.jpg)
:
