### ISSUE TITLE
Slack API Issues with Alerting Feature 

### ISSUE THREAD

**Issue by pavneetskapoor** [metabase/metabase#6996]
I've made a local version of Metabase to test out some of the new Alerting features with a backup of production Metabase config (stored in Postgres) and currently have issues with getting alerts to send over to Slack. I've entered the correct Slack API token (for which the entry field allows for) and I've tested for it through the "Send to Slack Now" through the Pulses setup page (for which it does correctly send over to Slack). Any setup for hourly, daily, weekly Alerts or Pulses are not showing up within Slack ( through 'Metabase_files' channel or anything else) which is confusing to me. Are there any obvious things that I'm missing with the new Alert feature?

Browser: Chrome 
OS: OS x 10.13.1
Database: AWS Athena (custom added in)
Metabase Version: 0.28.0
Metabase Hosting Environment: LocalHost testing
Metabase Internal Database: Postgres

**Comment by jornh** [comment]
I guess my comments/questions/link in [this discussion topic](http://discourse.metabase.com/t/pulses-dont-display-results-in-slack-anymore-in-v0-28-0/2941/3?u=jornh) apply to you as well.

**Comment by pavneetskapoor** [comment]
Hi @jornh, thanks for replying. It seems to me that the topics are a little unrelated since I'm not even able to see any Slack updates within my pointed-to channel. I've done so for about10 different questions that were pre-existing. However, when I'm in initial setup for Pulses and click the "Send to Slack Now", it works. It does not mention anything within the logs which makes it hard to find out the issue.

**Comment by salsakran** [comment]
Are you able to reproduce this on a build of master or a release?

Are you certain the server is running when you expect it to trigger?

**Comment by pavneetskapoor** [comment]
@salsakran  I'm not too sure if I can reproduce this issue but I can point out that alerts were initially working with H2 as the default internal Metabase and then stopped working once I changed to Postgres for config. The server seems to be running at the hourly points that I've specified the alerts for yet no response to Slack.

**Comment by pavneetskapoor** [comment]
Seems like this was some server lag like you mentioned before. I restarted the Postgres server on localhost and it's working now! Thank you for your help @salsakran @jornh.
