### ISSUE TITLE
New Question - will not load tables. 

### ISSUE THREAD

**Issue by Shubedobedo** [metabase/metabase#6997]
New Question - will not load tables. On a fresh install using Docker. I am at this point just trying to query the sample data. 

Browser : Chrome Version 63.0.3239.132
Metabase : version v0.28.1

![image](https://user-images.githubusercontent.com/22240748/36502162-0133435c-1717-11e8-8e5d-23fad4aff93c.png)

**Comment by jornh** [comment]
How are you starting the docker container?

Please take a look at the Metabase error log - is it similar to [this log in the discussion](http://discourse.metabase.com/t/sample-data-failed-to-install-ubuntu-vm-on-azure/2973) which will result in the same problem, though the environment (Ubuntu on Azure) is different?

**Comment by salsakran** [comment]
What's in the javascript or server logs?

Is the server still up?

**Comment by Shubedobedo** [comment]
I started docker container on windows using the Metabase tutorial. I am guessing this is solved now. It starting working after 3-4 hours. I was expecting at least the sample data to start working on spin up but I guess it needs to index or something. On a side note once I added real data with a few tables that have a few million rows they showed within minutes.

**Comment by georgiraychev** [comment]
I've experienced this problem and what have worked for me is to do a cache refresh - ctrl+F5 for Chrome.

**Comment by xeloader** [comment]
I had the same problem with the MacOS application.

I solved it by doing a "Shift+Cmd" at the same time while clicking the refresh button (see image).

![image](https://user-images.githubusercontent.com/2003998/40355596-261cfeb0-5db7-11e8-9480-9bf32a6d52e7.png)

**Comment by mbvictoria** [comment]
Closing - solutions provided.
