### ISSUE TITLE
Collections Administrator

### ISSUE THREAD

**Issue by abelliae** [metabase/metabase#6999]
Would it make sense to have a "Collection Admin" role able to curate a collection and also set permissions for that collection (adding groups or individuals)?

Use case: in our use case this would allow, once a user is onboarded to Metabase (account created), to delegate the management of collections (we divide them by business area) to the different departments.

**Comment by jornh** [comment]
Duplicate of #6799?

 If you agree please close this and add further needed details from here over there, or just give a 👍 upvote to it!

**Comment by abelliae** [comment]
Sorry for the late reply. Good to close.

Thanks for triaging.
