### ISSUE TITLE
Unable to display card on sent pulses

### ISSUE THREAD

**Issue by mfpinhal** [metabase/metabase#7001]
- Your database: `Postgres`
- Metabase version: `v0.28.1`
- Metabase hosting environment: `Docker`
- Metabase internal database: `Postgres`

Metabase displays following image on pulses sent to email/slack, nothing is shown in logs:
![image](https://user-images.githubusercontent.com/2720934/36546424-4b38c770-17e3-11e8-84fd-b4f4a5ff86e1.png)

_We were unable to display this card._
_Please view this card in Metabase._

After consulting the code base, I have no clue of what could be the reason for this.
It does not happen always:

<img src="https://user-images.githubusercontent.com/2720934/36546710-ff6365ca-17e3-11e8-8e8d-52dfe9cefe21.png" height="350">

Refs https://github.com/metabase/metabase/blob/master/src/metabase/pulse/render.clj#L583-L591.

**Comment by snarfed** [comment]
this also started happening to some of our pulses when we upgraded from 0.27.0 to 0.28.1. let me know if you want any details!

**Comment by salsakran** [comment]
this is being fixed in #7022

**Comment by mfpinhal** [comment]
I confirm this was fixed in v0.28.2 release.
