### ISSUE TITLE
Metabase Deploy is Out of Date (version 0.27.1)

### ISSUE THREAD

**Issue by uhrohraggy** [metabase/metabase#7005]
There isn't an issues for https://github.com/metabase/metabase-deploy but it's out of date with current version, making in place heroku update more difficult.

**Comment by brnt** [comment]
bump

**Comment by matthewford** [comment]
-----> Building with Leiningen
       Found bin/build; running it instead of default lein invocation.
       Running: bin/build
       fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       fatal: Not a git repository (or any parent up to mount point /tmp)
       Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
       Tagging uberjar with version 'v0.30.1   '...
       Running './bin/i18n/build-translation-resources' to build translation resources...
       internal/modules/cjs/loader.js:583
           throw err;
           ^
       
       Error: Cannot find module 'gettext-parser'
           at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
           at Function.Module._load (internal/modules/cjs/loader.js:507:25)
           at Module.require (internal/modules/cjs/loader.js:637:17)
           at require (internal/modules/cjs/helpers.js:20:18)
           at Object.<anonymous> (/tmp/build_0bde652d3f270d45b701085b0eb7e9f7/bin/i18n/build-translation-frontend-resource:8:17)

When using the Heroku button in readme

**Comment by dacort** [comment]
Closing this as the the process has changed a little and we need to update the docs (#11759).
