### ISSUE TITLE
Logged queued requests in the Jetty threadpool

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7012]
When Jetty hits the max threads for it's threadpool (currently set to 50) requests get enqueued. This could cause a significant delay in responding to the request depending on how deep the queue is and how long the currently processing requests will take.

It would be good to know when this happens. We should be able to instrument the threadpool and before en-queuing the request, write a log message that would let the user know they will be experiencing a delay, maybe suggest bumping the max threads.

**Comment by sabino** [comment]
Hey @senior any plans about this?
We have max threads always to the limit.
```
05-30 13:56:36 DEBUG metabase.middleware :: GET /api/public/dashboard/3e646ee8-4374-49d1-a783-d0a9620a82cc 200 (35 ms) (17 DB calls). Jetty threads: 8/50 (50 busy, 0 idle, 12 queued)
```

**Comment by senior** [comment]
@sabino It's on my TODO list, just not very high priority at the moment. This ticket would be in place of the log message you have pasted in, but it wouldn't change your situation. If you sometimes hit the maximum threads, you'll find HTTP requests to be much slower. If you have some extra memory, bumping the thread limit to something higher is a good fix. To change the maximum number of threads you can set the `MB_JETTY_MAXTHREADS` environment variable to something higher than 50 before you launch Metabase. Assuming you have some extra memory, 200 is a good value. It's Jetty's default, though we set ours lower, to 50.

**Comment by sabino** [comment]
@senior thank you for this information.
I've changed the value but the queries are now getting dropped when running inside metabase.

Do you know how good it would be if I can increase the jetty maxthreads even more?
Metabase is running on AWS, the instance is a **m4.4xlarge** 


| Model      | vCPU | Mem (GiB) | SSD Storage (GB) | Dedicated EBS Bandwidth (Mbps) |
|------------|------|-----------|------------------|--------------------------------|
| m4.4xlarge | 16   | 64        | EBS-only         | 2,000                          |

https://aws.amazon.com/ec2/instance-types/

**Comment by paoliniluis** [comment]
we're already logging the queued requests in the log, closing
