### ISSUE TITLE
Cancel timed out queries to BigQuery

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7013]
When querying BigQuery, if the query passes the timeout threshold, a timed out response is returned. Even though the query has timed out, it continues to run in the background. The results are then available later via a different endpoint.

We don't currently have any logic to follow up a timed out query with polling the other endpoint for the results. Since we're not interested in the results after a time out, we should cancel the query. The timed out query will include it's query id which is all we need to be able to cancel the query and stop waisting BigQuery cycles.

**Comment by jeff303** [comment]
This is handled in the new BigQuery driver coming in 41.
