### ISSUE TITLE
MySQL DB qith SSL on Heroku - Error

### ISSUE THREAD

**Issue by smauricioj** [metabase/metabase#7014]
I deployed the Metabase no Heroku to test it’s use, and the first time I connected to the MySQL DB it worked just right. For other reasons, I had to delete de access and add it again. This time the error below came. Same data, same DB, host, user and pass.
![](http://discourse.metabase.com/uploads/default/original/2X/9/939b05b1a9e8d47c282badf7681fd0ff2516324c.png)
Any idea why? I know that the --require_secure_transport = ON means that SSL is needed, but Metabase Docum. tells that SSL is no problem.

UPDATE : The problem seems to persist even when I'm using the jar file, in my pc. The first time it tries to connect to the DB, it works. If the connection is deleted, then it can't connect again.

UPDATE2 : Ok, there is no connection with deleting the connection to the DB. Every time I try to add a DB after the setup, the error occurs. The only time it does not, is on the setup page.

**Comment by salsakran** [comment]
which version are you on?

**Comment by salsakran** [comment]
also, what is in the server logs?

**Comment by xxwas** [comment]
![image](https://user-images.githubusercontent.com/30733529/36911420-3e934596-1e22-11e8-9503-2c80351d133a.png)

This is the log for the event of adding the new DB.

In regard of the Metabae version, in Admin -> Updates, it says: 'You're running Metabase 0.28.1 which is the latest and greatest!'... so I assume it's good, right?

**Comment by flamber** [comment]
A lot has changed since, and I believe it was fixed around 0.29 if I remember correctly.
