### ISSUE TITLE
Designs for rotated x-axis labels

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7015]
[Sketch file](https://drive.google.com/file/d/1ujQmH-5aosW_kDN4K1SQT4YXFkJYOWnf/view?usp=sharing) (Metabase core team only)

These are designs for https://github.com/metabase/metabase/issues/6937, which is related to https://github.com/metabase/metabase/issues/2935.

There's nothing new about this approach, but for discontinuous x-axes (i.e. not dates or continuous number ranges), I'm proposing we rotate the labels 45 degrees once there get to be too many to display without them colliding.

This is an example with 50 distinct x-axis values:

![50 labels - 45 degrees](https://user-images.githubusercontent.com/2223916/36622584-cc4c0d66-18b2-11e8-9e5a-2ce772ab5a27.png)

I'm also proposing that once we get to a certain threshold of distinct x-axis values (TBD what that exact number is), we go ahead and rotate the labels 90 degrees to get them to fit. This really probably has more to do with the width of the bars, i.e. the relationship to the number of distinct values vs. the amount of space in the current viewport. Here's an example with 100 labels at 1440px width:

![100 labels - 90 degrees](https://user-images.githubusercontent.com/2223916/36622587-ce8a296e-18b2-11e8-9b0f-56ff678c7481.png)

Beyond this level of density, there will probably be a point where we should honestly just not show the x-axis marks at all, i.e. once the 90-degree-rotated labels start colliding.

**Comment by SboissonPoligma** [comment]
Hello @mazameli ,
I would like to know how you succeeded to move X-axis labels from horizontal position to vertical and 90-degree-rotated position in your graph ? Is this feature in METABASE is working ? 
I will be very glad to have your answer. Thanks a lot

**Comment by mazameli** [comment]
Hi, @SboissonPoligma. Open issues that are labeled with `Designs` means that they are specifications for features that have not yet been built. We are looking to implement this x-axis rotation feature in the next version of Metabase.

**Comment by SboissonPoligma** [comment]
Hi, @mazameli thanks a lot for your answer, I know that open issues means features haven't been built yet. But I would like to know how you succeeded designing the dataviz in your messages above. Did you use your own CSS ? In spite of everything, I will wait impatiently next update.

**Comment by mazameli** [comment]
Implemented in #7103
