### ISSUE TITLE
Universal search functionality (metadata, SQL, dashboards etc)

### ISSUE THREAD

**Issue by EvilPuppetMaster** [metabase/metabase#7019]
We have a lot of people using Metabase at our company and loving it. It's great to be able to browse around the tables and columns in the 'data reference', and the ability to mark up the metadata with descriptions and so on takes this tool almost to the verge of being a bonafide data dictionary/catalog/glossary. However the one thing missing to make this dream a reality is the ability to search the metadata itself. When you have large numbers of tables and columns, simply finding the data you need and understanding what it means is quite a challenge.

So the ability to search the table names, column names and descriptions would really help.

I couldn't find any feature requests asking for this, however I did find a few asking for the ability to search the SQL of the questions and so on as well. And it occurred to me, why not just go the whole hog, pull the search box out of the 'questions' page and up into the main navigation, and have it be able to search ALL the data in the metabase database? This way you could search for say 'customer' and find all questions, tables, columns, descriptions, queries, dashboards etc that reference 'customer' in some way.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by MartinArens** [comment]
+1

**Comment by schaganti1** [comment]
+1

**Comment by ahoman** [comment]
Very difficult to discover content of other users without this functionality.  Please implement!

**Comment by jornh** [comment]
This now seems to be on the drawingboard for the v0.30 timeframe with @mazameli drafting up a “[Spaces, Search and Entity Pages](https://github.com/metabase/metabase/projects)” project  at https://github.com/metabase/metabase/projects/4 

There’s the first step of fronted work in https://github.com/metabase/metabase/issues/7472 and the full Monty in bullet form in https://github.com/metabase/metabase/issues/7473. In addition apparently a replacement/next-gen of ‘Data Reference’ in https://github.com/metabase/metabase/issues/7477 🎉 

@EvilPuppetMaster I was wondering on the technical side regarding relying on the H2 fulltext indexing - that would leave out the MySQL and Postgres options. They seem to have . Oh well

**Comment by flamber** [comment]
Just for reference, this depends on #3222/#4227. And #4227 has a hack workaround.

**Comment by tsmacdonald** [comment]
@mazameli we don't currently search fields at all. The only UX for this that would make any sense to me is if only admins had fields included in search results, and the field itself linked to the appropriate table in `/admin/datamodel/database/:id/table/:id`. It still seems weird to me to have search results link to `/admin`.

Maybe it makes more sense to extend this search box to include fields and not just tables?

![image](https://user-images.githubusercontent.com/784417/106060693-f759b600-60b9-11eb-91b3-dc0c71633521.png)


Or maybe there's some other solution?

**Comment by tsmacdonald** [comment]
Addressed by #14583
