### ISSUE TITLE
Update category classifier to account for search widget

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7025]
Prior to the search widget, people were (ab)using the category field type to provide select boxes for high cardinality fields. 

We should update the classifier to:
1. Only mark as a `category` something with < 30 labels
2. Mark a field as `list` if it has < 100 labels and `search` if it has more than 100 labels

**Comment by tlrobinson** [comment]
The `list` and `search` criteria is more complicated than that, right? It takes into account the `special_type` (and `base_type`?), etc.

**Comment by salsakran** [comment]
yes, implied in the above is that it would keep the same logic otherwise, but just change the constant.

**Comment by MarkRx** [comment]
Will list and search criteria allow for multiple selections? Or should we just use text fields with regular expressions?

**Comment by salsakran** [comment]
This is in master. 

@MarkRx yup, they definitely make multiple selections easy.
