### ISSUE TITLE
Metabase Docker keeps shutting down

### ISSUE THREAD

**Issue by Shubedobedo** [metabase/metabase#7028]
I have metabase running with docker. It works great for a while but then the docker container will just go down. I do a docker ps and the container is down but all the other docker services I have are still up and running. I can restart the docker service easy enough but it flakes out at least once a day. Been happening for over a week. It has been part of my daily routine to ssh into my server and restarts the metabase service. Currently, I only have one simple dashboard running.

**Comment by VikramTiwari** [comment]
I normally start any docker servers with the ability to restart automatically with ` --restart=always` flag in `docker run` command.

More info: https://docs.docker.com/engine/reference/commandline/run/#restart-policies-restart

**Comment by sviterok** [comment]
@Shubedobedo I'd start with checking the logs (`docker logs <metabase_container_id>`).
There must be a reason why it's shutting down.

I had a similar issue when I was running Metabase as a service on ECS.
The reason in my case was in memory consumption, so I had to tweak JVM params (set `JAVA_OPTS` env variable to `-Xmx2048m` to match the _soft memory limit_ that was set for my containers)

**Comment by salsakran** [comment]
Can you please share the information we request in the issue template? 

It's next to impossible to help without specifics like what version you're on, where you're running things, etc.

**Comment by Shubedobedo** [comment]
Sure
- Your browser and the version: All because the server is not running.
- Your operating system: Ubuntu 16.04
- Your databases: (e.x. MySQL, Postgres, MongoDB, …) Postgres
- Metabase version: (e.x. 0.19.3): 0.28.1 build 2018-2-09
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12) Docker
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)H2

**Comment by Shubedobedo** [comment]
After @sviterok comment, I increased the ram on my VM and I haven't had a crash in 2 days :) I look into the logs but I they I could find anything going back to my last crash. SO I'm guessing it was memory consumption issues. Still seems like a bug if it is using to much ram and crashing. I was running on a very small vm. I am now running on a slightly larger vm with 1gb of ram.

**Comment by mbvictoria** [comment]
Closing - appears resolved.
