### ISSUE TITLE
{"message":null,"stacktrace": exporting to xls or csv, json appears empty

### ISSUE THREAD

**Issue by ivancarrancho** [metabase/metabase#7030]
I'm getting this error, just trying export to xls or csv, a list of users
I don't know if is wrong  my data. 

{"message":null,"stacktrace":["api.dataset$datetime_str__GT_date.invokeStatic(dataset.clj:85)","api.dataset$datetime_str__GT_date.invoke(dataset.clj:81)","api.dataset$swap_date_columns$fn__33299$fn__33300.invoke(dataset.clj:90)","api.dataset$swap_date_columns$fn__33299.invoke(dataset.clj:89)","util.export$export_to_xlsx.invokeStatic(export.clj:28)","util.export$export_to_xlsx.invoke(export.clj:27)","api.dataset$as_format.invokeStatic(dataset.clj:115)","api.dataset$as_format.invoke(dataset.clj:107)","api.dataset$fn__33317$fn__33318.invoke(dataset.clj:136)","api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)","api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:248)","api.dataset$fn__33317.invokeStatic(dataset.clj:129)","api.dataset$fn__33317.invoke(dataset.clj:129)","middleware$enforce_authentication$fn__33151.invoke(middleware.clj:123)","api.routes$fn__46097.invokeStatic(routes.clj:66)","api.routes$fn__46097.invoke(routes.clj:66)","routes$fn__46855$fn__46856.doInvoke(routes.clj:106)","routes$fn__46855.invokeStatic(routes.clj:101)","routes$fn__46855.invoke(routes.clj:101)","middleware$log_api_call$fn__33250$fn__33252.invoke(middleware.clj:342)","middleware$log_api_call$fn__33250.invoke(middleware.clj:341)","middleware$add_security_headers$fn__33200.invoke(middleware.clj:255)","core$wrap_streamed_json_response$fn__47650.invoke(core.clj:66)","middleware$bind_current_user$fn__33155.invoke(middleware.clj:144)","middleware$maybe_set_site_url$fn__33204.invoke(middleware.clj:279)"]}

**Comment by senior** [comment]
@ivancarrancho What version of Metabase are you running? This looks like an bug we had in 0.28.0 but included a fix (#6909) for in 0.28.1.

**Comment by senior** [comment]
Closing this as it was fixed in 0.28.1. If this error occurs on a newer release, please open up a new issue.
