### ISSUE TITLE
Returning Ip Address instead of DNS

### ISSUE THREAD

**Issue by Pedroglp** [metabase/metabase#7037]
Browser and the version: Any
Operating system: Any
Your databases:  Postgres
Metabase version: v2.8.4 
Metabase hosting environment:  Elastic Beanstalk
Metabase internal database:  Postgres

While clicking to share a dashboard, pulse or new password, all urls are coming with ip address instead of DNS, which is not support by amazon EBS. I don't know if this is any configuration issue, if it is, it's not intuitive how to configure.

**Comment by jornh** [comment]
What’s your **Site URL** setting on that server currently: https://www.metabase.com/docs/latest/administration-guide/08-configuration-settings.html

I guess it could just be what you are looking for?

**Comment by Pedroglp** [comment]
I'm sorry, My mistake. 
Thank you guys for the awesome tool.
