### ISSUE TITLE
get all options for metadata from api (remove hard coding)

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#704]
there are a lot of things like permissions options and metadata types which are used by the frontend client and are currently hard coded.  this creates a syncing issue where it's possible for the frontend and back to get mismatched.

lets tidy this up and create a way where all the relevant options are maintained in 1 spot in the backend and exposed to the frontend via api.

**Comment by camsaul** [comment]
motion to close, we're doing this in some places and I don't think there's any need / desire to do it anywhere else right now

**Comment by camsaul** [comment]
Closing as Won't Fix since the appropriate things that can change are being returned by the public settings endpoint and there's no need or desire to do this for other things
