### ISSUE TITLE
Revoke access to query builder

### ISSUE THREAD

**Issue by glasset** [metabase/metabase#7041]
hello, are there a way to revoke access on query builder like custom query? 

thanks

**Comment by salsakran** [comment]
No there isn't.

**Comment by glasset** [comment]
hello thanks for the answer @salsakran 

im gonna add some informations about use case

***

> My use case is we have some external partner with an access to metabase but i don't want him to request to my db but only viewing already existing  collections/questions.

Today i can just block `Raw query` or revoke access to the db but he can't consult query from this db.

my proposal:
- Add an option to revoke access on  both (`Query builder` **and** `Raw query`)
<img width="276" alt="screenshot 2018-03-05 11 06 05" src="https://user-images.githubusercontent.com/6317714/36969263-4b3a8774-2065-11e8-9b99-7d02980ccf0e.png">

**Comment by jornh** [comment]
> We have some external partner with an access to metabase but i don't want him to request to my db but only viewing already existing collections/questions.

With that scenario it sounds like embedding - or public links could *maybe* cover what you need: https://www.metabase.com/docs/latest/administration-guide/13-embedding.html

**Comment by glasset** [comment]
nice one, thanks :)
