### ISSUE TITLE
Failed to connect to database: org.h2.jdbc.JdbcSQLException

### ISSUE THREAD

**Issue by agentscript** [metabase/metabase#7046]
So my linux server crashed and now when I restart I get this error

 Failed to connect to database: org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-193]
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))

There are some hs_err_pid****.log getting created at the same time. I ahev two instances one is running fine  but can't get this one to start. I had some important quereis saved. 

Any suggestions would be greatly appreciated

**Comment by jornh** [comment]
I already gave you an - admittedly a bit cheeky - answer in the [Metabase discussion forum](http://discourse.metabase.com/t/failed-to-connect-to-database-org-h2-jdbc-jdbcsqlexception/3051/2?u=jornh). I hope it's still helpful though and which you good luck 🍀 with salvaging your important questions! (good questions are just as important as answers)

I think this issue should just be labelled `Running Metabase` and be left as a pointer over to the forum.

**Comment by salsakran** [comment]
I also suggest checking out our troubleshooting guide -

https://www.metabase.com/docs/latest/troubleshooting-guide/application-database.html

Sounds like you have a corrupted database file.

**Comment by mbvictoria** [comment]
Closing - solved.
