### ISSUE TITLE
"Show x-axis" setting doesn't have any effect on small dashboard questions

### ISSUE THREAD

**Issue by brylie** [metabase/metabase#7058]
I have created a bar chart that counts values by day. On the 'Question' page, the chart has X-axis labels:
![screenshot from 2018-03-02 16-40-18](https://user-images.githubusercontent.com/17307/36904123-71a2ab82-1e38-11e8-98a7-23867c7a4a52.png)

However, when adding the chart to a dashboard, the X-axis labels disappear:
![screenshot from 2018-03-02 16-37-18](https://user-images.githubusercontent.com/17307/36904080-50e4a418-1e38-11e8-9c3e-be1d6e0ffb0b.png)

Here are the chart settings for the dashboard widget:
![screenshot from 2018-03-02 16-41-14](https://user-images.githubusercontent.com/17307/36904159-94cbd17e-1e38-11e8-9598-36c9d58dd775.png)

# Environment
- Metabase version: 0.28.1
- Metabase hosting environment: AWS
- Metabase internal database: Postgres

**Comment by tlrobinson** [comment]
I believe this behavior is intentional. If the question is 3 or fewer grid units tall we hide the X axis labels because there's not enough room to show them.

We should probably either hide that setting on dashboards or make it override the defaults based on the size.

**Comment by brylie** [comment]
OK, thanks for your response. In the case of timeseries charts, the date labels are actually really important. Whereas the axis label is not so important, and could probably be hidden instead.

**Comment by flamber** [comment]
I think this was fixed in 0.40 - this is 0.41.2:
![image](https://user-images.githubusercontent.com/1447303/141136776-9752e8ff-ce78-45f8-83e3-732b82289d13.png)
