### ISSUE TITLE
404 if I log in after clicking a link to a Query

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7078]
If @salsakran posts a link to a Metabase query in Slack like https://mymetabaseinstance.mycompany.com/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoxNSwidHlwZSI6InF1ZXJ5IiwicXVlcnkiOnsic291cmNlX3RhYmxlIjoxMjU5LCJmaWx0ZXIiOlsiQU5EIixbIj0iLFsiZmllbGQtaWQiLDc3NjVdLCJBbm5pZSJdXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0= and I click it and have to log in, it redirects me to a 404 page rather than the Question I was desperately hoping to see. Instead I have to re-click the original link *after* I logged in.

**Comment by mazameli** [comment]
https://github.com/metabase/metabase/issues/6317

**Comment by camsaul** [comment]
Duplicate of #6317
