### ISSUE TITLE
Question Filter Business Days in Metrics Mode

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7079]
In the metric mode, sometimes we need to filter only business days to get a proper time series, there is some planning in this direction?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
Practically speaking, this is locale dependent and we'd need some way to look up business days. Also, even within a given country, different businesses have different definitions of business day.

**Comment by dannyeuu** [comment]
@salsakran Maybe a config in `admin/settings/general` can help with this feature, what do you think?

**Comment by flamber** [comment]
Coming in 0.43 - possible to include/exclude day of week, month of year, hour of day and quarter of year
![image](https://user-images.githubusercontent.com/1447303/164934407-f4ede0b7-8f2a-4fd9-85af-8b627a6f71df.png)

**Comment by seidnerj** [comment]
This done allow filtering non-business days but in conjunction with "yesterday" after the weekend, one ends up with no results because on Monday, "yesterday" is "Sunday" and that is excluded. So, the question is, how can we have a filter that is "Previous 1 non-excluded days" as opposed to simply "Previous 1 days"?

**Comment by flynfish** [comment]
> This done allow filtering non-business days but in conjunction with "yesterday" after the weekend, one ends up with no results because on Monday, "yesterday" is "Sunday" and that is excluded. So, the question is, how can we have a filter that is "Previous 1 non-excluded days" as opposed to simply "Previous 1 days"?

I need to solve for the same thing here. Any insight from the metabase team?
