### ISSUE TITLE
Ability to access fields in JSON Dicts in Postgres driver

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#708]
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by kfarr** [comment]
Yes, similar need here. We have user-supplied metadata stored as json blob. The schema / format is consistent across the entire DB but the data is not "important" enough for us to create columns for each of these items. But of course the customers still want to be able to query on this data. We have been able to get raw postgres SQL queries on JSON working fine, the next prize is allowing non-technical end-users to be able to construct these queries through the UI instead.

**Comment by LukeAbell** [comment]
+1

**Comment by elfet** [comment]
+1

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions. So instead of leaving `+1` comments, please just upvote by adding a reaction.

**Comment by ryanleland** [comment]
👍

**Comment by camsaul** [comment]
@ryanleland, one way we prioritize issues is by sorting them by the number of 👍 *reactions*. So instead of leaving `+1` or 👍  *comments*, please just upvote by adding a reaction.

**Comment by avkonst** [comment]
I have got similar use case when SQLite database stores json text in string based column. Would be good to have it supported too.

**Comment by lsh-0** [comment]
we convert article xml documents into json for feeding downstream services. one of these downstream services is a reporting system hooked up to metabase and maintains a copy of these article-json files. some of our powerusers would love to just bypass my carefully denormalised tables and query the json directly

**Comment by spencermwatts** [comment]
This would be so helpful and allow more users to query data.

**Comment by alfonsolzrg** [comment]
+1. Although we'd love to have full JSON structured query support, in most of our use cases, we can work with a simple "contains".

**Comment by conanbatt** [comment]
Same, only having a plain contains would be of great use.

**Comment by brylie** [comment]
@alfonsolzrg are you able to get a 'contains' query to work with a JSONB field? I tried using 'contains' on a JSONB field and got the following error:

```
ERROR: operator does not exist: jsonb ~~ character varying Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 983
```

**Comment by lukabirsa** [comment]
Please at least add contains support to jsonb fields. Full jsonb support would be perfect.

Our use case:

We store device telemetry data in jsonb field. These include device id, device parameters (booleans), device sensors (integers, floats). It would be great if we could unpack the values to perform queries such as "what is the average of humidity sensor for devices that have heating enabled".

Right now all we can do is take the data and export it via CSV to analyze it somewhere else.

**Comment by brylie** [comment]
Contains support seems like a great start. However, we have queries that also do other comparisons such as greater than.

Since many of our tables contain JSONB colums, due to various pragmatic decisions during development, we are struggling with SQL syntax (e.g. "->" vs.  "->>") any time we want to use JSONB data.

**Comment by lukabirsa** [comment]
Just a follow-up: we're currently addressing this issue by creating a stored question that contains SQL which unpacks the values in a tabular form (normalizes data). 

You can then use the stored question for people to run queries on. Right now there is an issue with metadata re: column types loss for stored queries (so many aggregations do not work), but this should solve the issue short term.

It would be even better if the question engine would be able to handle this.

**Comment by brylie** [comment]
Hey @lukabirsa, would you mind providing a generic example of your query that unpacks the JSON(B) field? I would like to try your approach.

**Comment by conanbatt** [comment]
@brylie 

SELECT "your_table"."id" AS "id",
  "your_table"."json_field"->'location' as "locatoin",
  "your_table"."json_field"->'type' as "type",
  "your_table"."json_field"->'date' as "date"
FROM "your_table"
LIMIT 2000

After this, you can go to metabase and get a "saved question" and query that. Works like a charm!

**Comment by sethia** [comment]
> @brylie
> 
> SELECT "your_table"."id" AS "id",
> "your_table"."json_field"->'location' as "locatoin",
> "your_table"."json_field"->'type' as "type",
> "your_table"."json_field"->'date' as "date"
> FROM "your_table"
> LIMIT 2000
> 
> After this, you can go to metabase and get a "saved question" and query that. Works like a charm!

@conanbatt I am unable to extract the value using your method from JSONB column

**Comment by flamber** [comment]
@sethia Are you using MySQL 5.7.9+ ? Otherwise the shorthand does not work and you would need to use the regular functions like `JSON_EXTRACT()`

**Comment by sethia** [comment]
oh, using Postgres

**Comment by zygopleural** [comment]
Any update on this?

**Comment by bvallelunga** [comment]
Any update on this? @tlrobinson would love your thoughts on this?

**Comment by jayzalowitz** [comment]
+1

**Comment by Overbryd** [comment]
@jayzalowitz please refrain from using +1 responses at Github. Use the 👍or 👎 emojis. This behaviour is every annoying for all the 18 participants having notifications turned on for this issue, myself included. Others now are free to scold me for replying as well on this horrendous off-topic. But people will not learn unless told. Enjoy.

**Comment by bvallelunga** [comment]
@camsaul super excited this is being worked on. Our team deeply needs this feature!

**Comment by cabintech** [comment]
Our entire business schema is in Postgres JSONB fields (customers, products, addresses, costs, pricing, ...) - there are only a few primary keys at the table level. Any chance this feature could be moved up? If we have to write SQL queries (and get all the arrow notation just right) then most of the value of metabase is lost for us...

**Comment by flamber** [comment]
@cabintech The workaround until this is implemented is to create database views, so Metabase just sees those "tables".

**Comment by cabintech** [comment]
> @cabintech The workaround until this is implemented is to create database views, so Metabase just sees those "tables".

I did see some reference to doing this in earlier comments. Looks fine for simple 1 level JSON objects, but not really practical for deeply nested objects with nested collections and arrays. Basically you have to re-create the entire business 'schema' in traditional tables, foreign keys, etc.

I see from the master plan that this is targeted for 0.39, but no idea how far out that is... weeks, months, years?

**Comment by gtaylor** [comment]
With this being an open source project, it can happen immediately with your
contribution.

**Comment by cabintech** [comment]
> With this being an open source project, it can happen immediately with your contribution.

If this were written in Java I would be right there, but with zero experience in the implementation language its not practical (and you would not want a newbie doing something this involved).

**Comment by alxndrsn** [comment]
> With this being an open source project, it can happen immediately with your
contribution.

@gtaylor any thoughts on where the code would go or how it would be structured?  Looking at the [contribution guide](https://github.com/metabase/metabase), should this have a [Design Needed](https://github.com/metabase/metabase/labels/.Design%20Needed) or [Help Wanted](https://github.com/metabase/metabase/labels/.Help%20Wanted) tag?

**Comment by jeff303** [comment]
A similar feature is coming to Redshift [soon](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-redshift-announces-support-native-json-semi-structured-data-processing/).

**Comment by bvallelunga** [comment]
@flamber what's the best way to ask for this feature to be prioritized? My company really needs the ability to query JSON. I am nervous that since this feature PR has been up since 2015, the feature will never be shipped.

**Comment by cma1kep** [comment]
Hello,
I'm looking forward to this PR

**Comment by anayib** [comment]
You can do a native query . In my case I have a column with an hstore (json format ) . I needed to filter by the "format" key in the json so here is an example for you to follow:

`select  info -> 'format', email, first_name, last_name FROM applicants WHERE type='TopApplicant' AND info -> 'format' = 'partial';`

**Comment by persand** [comment]
We at [Odd Camp](https://www.oddcamp.com) would be happy to hire someone that could help solve this feature request.

The result would of course be contributed back to the project.

Location: Anywhere
When: As soon as possible

Interested? Email me at per@oddcamp.com.
Do you know someone you think be interested? Please share this post with them.

Thanks,
Per

**Comment by luizarakaki** [comment]
Postgres semi-structured records (as known as maps and dictionaries) are now supported in Metabase version 43.

We are planning to extend support for other databases in 44.
Arrays are not yet supported.

**Comment by lourencogui** [comment]
Is there any docs showing how to use this feature?

**Comment by lukas-at-harren** [comment]
@lourencogui Write some SQL?
https://www.postgresql.org/docs/9.3/functions-json.html

**Comment by luizarakaki** [comment]
If you have `json` or `jsonb` fields in your Postgres databases, we will try to parse them and extract keys. There are no additional steps. The parsed keys behave like any other field.

From 43.1 we parse the first 500 rows of each JSON field to extract keys. If a key is not appearing in the data model, make sure that the key is available in the first 500 rows (can be null).

**Comment by ivanspog** [comment]
@luizarakaki 
> From 43.1 we parse the first 500 rows of each JSON field to extract keys. If a key is not appearing in the data model, make sure that the key is available in the first 500 rows (can be null).

We run `43.1 ` with PostgreSQL DB but I don't see Metabase extracting any keys from JSON column. Are there any steps we need to do to make it happen?

**Comment by caleb15** [comment]
Same issue, I don't see this feature working in any of our tables that have JSON. We have key/value pairs in the first 500 rows but it's still appearing the same way as before. We're on metabase v0.43.2

![image](https://user-images.githubusercontent.com/46505081/172703853-3ff958a1-62d2-44cb-ab72-2237afba298f.png)

I used the metabase GUI to construct the query, the raw SQL looks something like this:

```sql
SELECT "myschema"."my_table"."id" AS "id", "myschema"."my_table"."json_column" AS "json"
FROM "myschema"."my_table"
ORDER BY "myschema"."my_table"."id" DESC
LIMIT 1048575
```

**Comment by flamber** [comment]
Make sure that your Postgres column is the type `JSON` or `JSONB`.
Do a manual sync of your Postgres database via Metabase > Admin > Databases > (postgres) > Sync database schema now.
Then check the log if there's errors during sync - if there's errors, then that's likely why it's not showing.

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by caleb15** [comment]
@flamber This is less "I need help" and more "I want to report a bug". Regardless, I tried creating an discourse account and it didn't work.

> Make sure that your Postgres column is the type JSON or JSONB.

We have a jsonb field, but I don't see any JSON parsing.
I tried a manual sync, same issue. I saw an error in the logs, but it was with a different table. Besides that, no issues.

> From 43.1 we parse the first 500 rows of each JSON field to extract keys

Is the first 500 rows the first 500 rows sorted by ID asc or simply the first 500 rows that appear in the query?

I checked a different table of ours and the JSON feature works there, so it looks like this feature does have some functionality, albeit buggy and limited. Better than nothing! Note that if you use raw SQL `select * FROM ...` then the JSON parsed fields do not appear. Also note that there are errors with [uppercase tables](https://github.com/metabase/metabase/issues/23026) or schemas with [system characters](https://github.com/metabase/metabase/issues/23026) as well.

**Comment by howonlee** [comment]
I added the JSON parsing behavior toggle in https://github.com/metabase/metabase/pull/22997 but it seems that the default option for existing DB is that the new option that we instantiate isn't defined in DB settings, therefore the parsing doesn't get triggered.

Separately solved on master with https://github.com/metabase/metabase/pull/23136, backport incoming. I will file separate bug

**Comment by flamber** [comment]
@caleb15 Great if you want to report a bug, then please open a [new issue](https://github.com/metabase/metabase/issues/new/choose) with steps-to-reproduce. Otherwise it's going to be impossible for us know what the cause is and how to fix it.

@howonlee #22997 was only added to master, so that is irrelevant and defaults to true anyway.

**Comment by nodesocket** [comment]
Can I also request SQLite support? Maybe a way to de-construct JSON into fields? My schema is:

<img width="238" alt="Screenshot 2022-11-17 at 8 27 47 PM" src="https://user-images.githubusercontent.com/523312/202602822-0583cbcc-dd89-4281-88ab-3b04dae7e02d.png">

**Comment by flamber** [comment]
@nodesocket No, only Postgres and MySQL are currently supported.

**Comment by nodesocket** [comment]
@flamber actually I got this working with SQLite. Essentially, I used a raw SQL query to build a Metabase Model.

The raw SQL query looks like:

```sql
SELECT
    id,
    added,
    JSON_EXTRACT(data, '$.purchase_date') AS purchase_date,
    JSON_EXTRACT(data, '$.asset') AS asset,
    JSON_EXTRACT(data, '$.size') AS size,
    ROUND(JSON_EXTRACT(data, '$.fill_price'), 2) AS fill_price,
    JSON_EXTRACT(data, '$.exchange') AS exchange,
    ROUND(JSON_EXTRACT(data, '$.size') * JSON_EXTRACT(data, '$.fill_price'), 2) AS cost
FROM positions
ORDER BY purchase_date ASC
```

Then, I converted that to a Metabase **Model**. Still working through all the details but this seems to work so far. I now can filter on `asset` for example or `fill_price`. Excited to discover what else I can do with Metabase.
