### ISSUE TITLE
[Bug] Issue with the metabase browser cache

### ISSUE THREAD

**Issue by kkhaitan** [metabase/metabase#7083]
Issue: With two different set of people part of two independent groups. Each of the group having access to different set of database thereby different set of datasets and fields when log after another end up seeing the others databases, datasets and dashboard despite not having permission. This issue is also happening even if one is using private browsing.

- OS: 10.12.6
-Metabase version: tag: v0.26.2
-Metabase internal DB: mysql
-Database type: Rest
-Browsers on which issue is reproducible:
a. Chrome: 64.0.3282.186
b. Safari: 11.0.3 
c. Firefox: 58.0.2 

Steps to reproduce:
1. Create two different databases, with different datasets and fields. 
2. Assign them each a different group with different user by giving them permission accordingly on the db and tables.
3. Create separate dashboard for each one of them.
4. Login using the user created one after another you would see the data interfering often but not always even in the private browsing mode. 

Please let me know if you would need any additional information.

**Comment by flamber** [comment]
Related to or duplicate of #5202 - but I'm not able to reproduce this on 0.31.2 (Firefox 65 Chromium 71)

**Comment by flamber** [comment]
This was fixed in 0.30
