### ISSUE TITLE
Log system and report timezone information on startup

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7085]
This should show up in the log by default always and would give users the following information:
* System timezone
* Was `user.timezone` specified?
* Is there a report timezone specified?

Might be interesting to include the detected timezones for the configured databases as well. This would be a one time message, on startup, so it seems like it'd be good to include more information for debugging timezone related issues.

**Comment by camsaul** [comment]
Looks like we already log `user.timezone`: https://github.com/metabase/metabase/blame/master/src/metabase/core.clj#L137

I can tweak this to log everything

**Comment by camsaul** [comment]
@senior It looks like `user.timezone` gets populated whether you actually set it or not. Do you know of any way to tell whether it was manually overriden by the user?

**Comment by senior** [comment]
#5640 is definitely a better solution, but it's a decent chunk of work. so not sure when it'll be done. I think moving the `user.timezone` log would be ok. Maybe when we spin up the connection pool we log both in a single line or something.

**Comment by salsakran** [comment]
fwiw I think the PR for  #5640 (#5658) should be in a reasonable place to just add lines of info to.

**Comment by senior** [comment]
Closing this after some discussions. We already log user.timezone and we're headed toward the debug page.
