### ISSUE TITLE
When "Custom Question" uses "Native Question" as a source - it doesn't inherit filters. It should.

### ISSUE THREAD

**Issue by vi-vsn** [metabase/metabase#7089]
So this situation is composed of two problems:

1.
I end up doing the following often - building a new "Custom Question" and picking another question, usually "Native Question" as a source. The reason - is because my users really like the filtering, sorting, pivoting that comes with "Custom Questions", features that are not available when using "Native Questions". Can't this be made to behave the same way without having  to create additional questions? 

2.
And when i build those "derived" "Custom Questions" - i run into a different problem: "Custom Questions" don't show the filters that were defined on the underlying "Native Questions". So if my underlying "Native Question" has a mandatory filter - I can't build a derived question on top of it.

So I guess what I am asking - is it possible to solve my problem by either addressing the Problem 1 or Problem 2?

Thanks!

**Comment by eyalfir** [comment]
This sounds like a dup of #6449

**Comment by vi-vsn** [comment]
It does! Though this explanation is a bit better broken down, I think. 

But most importantly, I just wanted to bump this to the top of the list - it's been a while since this one been posted, and it's pretty much the only thing that comes up pretty regularly on the "why does this work like this" list.

If you can make native (sql based) questions to have the same UI capabilities (Sorting, Filtering, Grouping, in that order of importance ) that Simple Builder questions have - it would be really handy.

Congratulations on releasing 0.30 - it certainly looks like a major chunk of work!

**Comment by flamber** [comment]
Closing in favor of #4367/#6449

**Comment by mayank924** [comment]
has this been resolved? I can't seem to build a custom query (with the pre-defined field filters) using a native query with that field filter
