### ISSUE TITLE
MongoDB support Custom Column and Custom Expression

### ISSUE THREAD

**Issue by aviggiano** [metabase/metabase#7097]
### Feature requests and proposals

It seems that MongoDB "Custom" questions do not offer support for "Custom Expressions". 

Here's what I see when I use my PostgreSQL database:

![screenshot from 2018-03-08 18-52-51](https://user-images.githubusercontent.com/3029017/37178713-12e05648-2302-11e8-90c8-1e6740297cbd.png)

And these are the options for MongoDB:

![screenshot from 2018-03-08 18-53-14](https://user-images.githubusercontent.com/3029017/37178708-0f977ffc-2302-11e8-8d93-993b96f5dce7.png)

Since MongoDB's aggregation pipeline is essentially a JavaScript function, I believe it should be possible to include custom expressions for this database as well. Maybe even allowing arbitrary expressions instead of just `+`, `-`, `*`, `/`.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by alirezastack** [comment]
Is this issue by any chance related to [MongoDB variable support](https://github.com/metabase/metabase/issues/3653)?

**Comment by camsaul** [comment]
related but not exactly the same. Their implementations will probably share a lot of code however so when tackling one we might as well tackle the other at the same time

**Comment by alexpluto** [comment]
Hi there, is there any idea of when this might be implemented or available? :)

**Comment by camsaul** [comment]
@flamber did you mean to reopen this? We do offer custom expression support for MongoDB, Howon added it in #17117. If we didn't support custom expressions, how could #24315 even be an issue?

**Comment by flamber** [comment]
@camsaul While there's Custom Columns in Mongo 5+, there's no Custom Expression in metrics:
![image](https://user-images.githubusercontent.com/1447303/206401220-d2e86d25-aa3f-403e-8fa1-2d31117dcb25.png)

**Comment by camsaul** [comment]
Gotcha. Using expressions in aggregations is an order of magnitude harder to support for MongoDB than adding columns that we don't aggregate on. So we do support custom columns at this time, but don't support aggregating on custom expressions yet.

**Comment by camsaul** [comment]
More discussion on implementing custom expressions for aggregations was had here https://metaboat.slack.com/archives/C04DN5VRQM6/p1673022009111879

**Comment by metamben** [comment]
Fixed by #28061.

**Comment by Clemog** [comment]
Hi ! I am digging into custom expression with mongo database. The option is here and work for custom aggregation but the custom column is not showing in the editor ? I can see here it should be fixed but i don't know what i am doing wrong
<img width="1048" alt="image" src="https://github.com/metabase/metabase/assets/55186402/ce5bbea3-417c-4d81-b17d-1f8b3071e539">
