### ISSUE TITLE
Text Boxes in Dashboard not showing properly

### ISSUE THREAD

**Issue by marcoruggine** [metabase/metabase#7099]
Hi guys,

I have this odd issue with all of my text boxes in all of my dashboards: text is stuck to the first 1/3 of the card.
Is it something that I'm doing wrong?
<img width="2260" alt="schermata 2018-03-09 alle 10 56 09" src="https://user-images.githubusercontent.com/20041428/37201760-d1c0f410-2388-11e8-8c8b-2105b2e77453.png">

**Comment by mazameli** [comment]
There was an errant max-width on the paragraph element of text cards. There's a fix in https://github.com/metabase/metabase/pull/7102
