### ISSUE TITLE
Ldap Auth

### ISSUE THREAD

**Issue by izav** [metabase/metabase#7105]
This is a bug report about LDAP authentication once enabled.

- The server version is the last up to date Docker one (0.28.1).
- The bug is not browser related as met with any.
- The database is the H2 embedded by default within Docker image.
- The LDAP server is an OpenLdap

I've configured the LDAP authentication and done some tests to make it working without success. Below some clues.

The communication to the LDAP server works (as seen within tcpdump).

Every time i try to authenticate with few different accounts, i can see wihtin tcpdump captures that the LDAP authentication is done every time against only one existing account (obtained and existing within the LDAP), which is not this one used and given through the authentication form. 

Obviously the authentication does not work as the given password is not the good one for that account sorted/filtered by the Metabase ldap querier.

For example if you give "toto", "tutu", "momo" and the according password within the authentication form, the tcpdump will show only one matching result/existing account within ldap filtered by Metabase let's say "zaza". As a result the password will never be the good one and never authenticated.

**Comment by wagnereliakim** [comment]
@izav I have the same problem here

**Comment by artemkamolodets** [comment]
Hello.
In my case the LDAP auth was configured to unexisting LDAP server.
At now i cannot login because app ignores local users and cannot connect to LDAP server.
How can i disable LDAP in this situation (there is no configuration files. . .)?
Please help.

**Comment by reinhardt** [comment]
Does anyone have a workaround for this issue? I'm currently fighting the same problem. It doesn't matter what I enter as the user name - I can even put some random gibberish in there - as long as I enter the password for the account that metabase has "chosen", I'm authenticated as that account. I can't log in as anyone else, not even the local admin user. That makes the LDAP feature useless.

@wagnereliakim, I think your problem is distinct from this one. I've also seen this error before. It happened with one of my test LDAP servers but went away when switching to another, so I suspect it has to do with the server configuration, but I haven't analyzed it further yet.

**Comment by flamber** [comment]
@reinhardt Seems like it is specific to certain types of LDAP - I was trying to help someone with the same problem last month:
https://discourse.metabase.com/t/ldap-cant-login/10315

**Comment by reinhardt** [comment]
Thank you so much @flamber, you saved my day! That link led me to [another post](https://discourse.metabase.com/t/ldap-debugging/2741/2), specifically this bit:

```User Filter - (&(mail={login}))```

This made me realize that I had misunderstood the user filter setting. In my world a user filter should return *all* users, e.g. `(objectClass=inetOrgPerson)`, but metabase needs a filter that returns *one specific* user. So, I would actually have been fine by keeping the default, but for some reason I didn't even look at it but set my own broken user filter.

This also explains the behaviour that the same user is used regardless of the supplied login. The search returns all users and the first (or maybe last) result is used to authenticate.

Thanks again, it's now working for me!

**Comment by paoliniluis** [comment]
Just went through this one, user attributes are mandatory for the authentication to work, so if users in LDAP don't have a mail, givenName and sn, Metabase will return a {:errors {:password "did not match stored password"}} which is not true, but it's the error that the middleware is throwing. I'll update the documentation accordingly

**Comment by camsaul** [comment]
@paoliniluis can we close this issue out now that you've added it to the dox?

**Comment by paoliniluis** [comment]
@camsaul if the middleware error is ok since we do that in order to hide the real error from bad actors, then it's ok for me. @flamber what do you say?

**Comment by flamber** [comment]
Closing as fixed by #14771 - in this documentation section: https://www.metabase.com/docs/latest/administration-guide/10-single-sign-on.html#enabling-ldap-authentication
