### ISSUE TITLE
 Error running sync step: [Amazon](500310) Invalid operation: relation "information_schema.sql_implementation_info" does not exist;

### ISSUE THREAD

**Issue by adamhaney** [metabase/metabase#7109]
DB Type:  Amazon Redshift
Metabase Version: 0.28.1 (using the docker image)

I've had an issue for the past few months with metabase not synching schema changes (new tables / columns). When I look through the logs they're full of the following error:

```
metabase_1  | 03-12 22:03:26 ERROR sync.util :: Error running sync step: [Amazon](500310) Invalid operation: relation "information_schema.sql_implementation_info" does not exist;
metabase_1  | ("driver.generic_sql$describe_database.invokeStatic(generic_sql.clj:363)"
metabase_1  |  "driver.generic_sql$describe_database.invoke(generic_sql.clj:359)"
metabase_1  |  "driver$fn__25431$G__25369__25438.invoke(driver.clj:51)"
metabase_1  |  "sync.fetch_metadata$fn__35644$db_metadata__35649$fn__35650.invoke(fetch_metadata.clj:13)"
metabase_1  |  "sync.fetch_metadata$fn__35644$db_metadata__35649.invoke(fetch_metadata.clj:10)"
metabase_1  |  "sync.sync_metadata.tables$fn__36774$db_metadata__36779$fn__36780.invoke(tables.clj:127)"
metabase_1  |  "sync.sync_metadata.tables$fn__36774$db_metadata__36779.invoke(tables.clj:124)"
metabase_1  |  "sync.sync_metadata.tables$fn__36834$sync_tables_BANG___36839$fn__36840.invoke(tables.clj:144)"
metabase_1  |  "sync.sync_metadata.tables$fn__36834$sync_tables_BANG___36839.invoke(tables.clj:139)"
metabase_1  |  "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870$fn__36871.invoke(sync_metadata.clj:26)"
metabase_1  |  "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
metabase_1  |  "sync.util$do_with_error_handling.invoke(util.clj:119)"
metabase_1  |  "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
metabase_1  |  "sync.util$do_with_error_handling.invoke(util.clj:119)"
metabase_1  |  "driver$fn__25602.invokeStatic(driver.clj:226)"
metabase_1  |  "driver$fn__25602.invoke(driver.clj:226)"
metabase_1  |  "driver$fn__25526$G__25357__25535.invoke(driver.clj:51)"
metabase_1  |  "sync.util$sync_in_context$fn__34128.invoke(util.clj:115)"
metabase_1  |  "sync.util$with_db_logging_disabled$fn__34125.invoke(util.clj:106)"
metabase_1  |  "sync.util$with_start_and_finish_logging$fn__34120.invoke(util.clj:92)"
metabase_1  |  "sync.util$with_sync_events$fn__34117.invoke(util.clj:75)"
metabase_1  |  "sync.util$with_duplicate_ops_prevented$fn__34108.invoke(util.clj:54)"
metabase_1  |  "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
metabase_1  |  "sync.util$do_sync_operation.invoke(util.clj:139)"
metabase_1  |  "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869$fn__36870.invoke(sync_metadata.clj:23)"
metabase_1  |  "sync.sync_metadata$fn__36864$sync_db_metadata_BANG___36869.invoke(sync_metadata.clj:20)"
metabase_1  |  "api.database$fn__37519$fn__37520$fn__37521.invoke(database.clj:505)")
metabase_1  | 

```

A quick search of the codebase finds (https://github.com/metabase/metabase/search?utf8=%E2%9C%93&q=information_schema&type=) finds:

https://github.com/metabase/metabase/blob/10244686ff9c1be9ddb3e2ff834c5b68b22805fb/src/metabase/driver/redshift.clj#L40 

which appears to indicate that the redshift driver should never use the information_schema table, there are a few more references to information_schema, is it possible that this database is being loaded using the incorrect driver somehow?

**Comment by camsaul** [comment]
@adamhaney is your database set as Redshift? I've seen that error before with Redshift databases that were set as Postgres

@Kyeongrok when you run what query? Either way, Metabase doesn't use the Hibernate ORM, and Metabase doesn't allow you to do `INSERT` operations either. Are you sure this is a problem you're having with Metabase?

**Comment by adamhaney** [comment]
@camsaul it's set to Postgres /now/ but it's been set to both at one time or another, I'm going to try setting up an entirely new source that has been redshift for its entire life time to check if I have the same problem.

**Comment by jpramos123** [comment]
Any news on that? I have exactly the same issue @Kyeongrok faced.

**Comment by camsaul** [comment]
Seems like there's a few things going on here, I'll try to address them:

*  As previously mentioned, Redshift databases won't work if you set them as Postgres. Make sure you set them to Redshift. Feel free to open a new issue if you're having issues with the Redshift driver.
*  Metabase also only does read-only access, so `INSERT` and other DDL statements are going to work. Also, I think you're opening an issue in the wrong project, because we don't use the Hibernate ORM, so these error messages:
    ```
    Hibernate: insert into user_event3 (name) values (?) Hibernate: select currval('user_event3_id_seq')
    ```
    aren't from us. Feel free to open a new issue if you find a bug with Metabase.
