### ISSUE TITLE
AutoUpdate Metabase

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#711]
We should provide a way for the instance to check for an updated version and transparently upgrade for the user

**Comment by luiscape** [comment]
+1!

On this note, what I can do to update to the newest version using a Docker image without losing all my configuration?

**Comment by agilliland** [comment]
Hi @luiscape , our documentation provides some examples on how to run Metabase on docker with persistent data storage ... http://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html

If you have already launched the app without any persistent storage then you'll have to do a little work to copy the Metabase H2 database files outside of the container first.  Something like this ... http://stackoverflow.com/questions/22049212/docker-copy-file-from-container-to-host

Just make sure you copy all of the `metabase.db.*` files and you should be g2g.

**Comment by luiscape** [comment]
Got it! I'll give it a try. Thank you!

**Comment by salsakran** [comment]
closing since it's highly unlikely to happen given how the docker ecosystem has shaken out
