### ISSUE TITLE
Why Metabase does not show image fields with type of Image URL?

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#7113]
I came across to link below:

[Show external images](http://discourse.metabase.com/t/how-to-show-an-external-image-in-the-dashboard/2404)

It was mentioned how to change the field type. I changed the field type to `Image URL`. But when I query the result, image link is shown in dashboard/question result.

One of the valid `Image URLS` is google logo:
`https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png`

Why is that happening? How to display images on Metabase?

**Comment by pfeiffer** [comment]
See: https://github.com/metabase/metabase/issues/6265

**Comment by flamber** [comment]
Hi @alirezastack 
This was added in version 0.31, which supports a lot of different formatting options.
![image](https://user-images.githubusercontent.com/1447303/52982562-6ac1fb80-33ac-11e9-9910-038f20f2524b.png)

**Comment by mbvictoria** [comment]
Closing - support for this feature added in 0.31.

**Comment by NicolasMarlier** [comment]
Hi guys, looks so cool but I can't make it work -> [See on Stackoverflow](https://stackoverflow.com/questions/63959872/image-urls-wont-display-as-image-in-metabase-table)

**Comment by flamber** [comment]
@NicolasMarlier Because it's not an URL to a `JPG`, `GIF` or `PNG` file?
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by NicolasMarlier** [comment]
@flamber thanks for your response, I tried with both SVG and PNG files. I created a a topic in the forum: [https://discourse.metabase.com/t/image-urls-wont-display-as-image-in-table/11670](https://discourse.metabase.com/t/image-urls-wont-display-as-image-in-table/11670)
