### ISSUE TITLE
Designs for conditional table and column formatting

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7122]
Designs and specs for #4121. 

## Summary
This is a feature to add the ability to change the background color of table cells based on some logical condition. This will provide a way to create retention charts or tabular heat maps, and make it easier to spot outlier values/rows in a table.

## Scope
- Only works on numeric columns for now.
- You can set conditional formatting on one or more columns at a time. (Removed the notion of a table-wide rules, as this really only applied to 1-metric + 2-dimension pivot tables, in which case you're still just applying a rule to the one metric column.)
- You can optionally highlight the whole row with a tint of the selected color if a column meets the condition.
- You can choose between a color gradient (e.g., for a retention chart) or a single color (e.g., profits were negative at this store, so turn this cell/row red).
- Multiple rules can be set on a table and/or columns. The order of the rules is significant, they can be reordered, and in the event that two conditions are met on the same cell, the topmost rule wins.
- **Formatting should be reflected in tables when they're included in Pulses**

## How this works
Chart settings for tables will have a tab bar now: `Data`, and `Formatting` (tab styles have been updated)

![start](https://user-images.githubusercontent.com/2223916/39950744-60ee5ed0-5538-11e8-959e-a21048404ceb.png)

The formatting view has a button to create a new rule and space for a preview of the table. There is also space for a vertical list of rules once they're created; each rule will be represented as a draggable/reorderable card.

![formatting tab](https://user-images.githubusercontent.com/2223916/39950753-8188a5b0-5538-11e8-89e9-aaf86acf0630.png)

Clicking on the new rule button shows a new view for the rule's settings, and automatically opens up a checkbox select to pick the column(s) the rule should apply to:

![select field s](https://user-images.githubusercontent.com/2223916/39950769-ad2c7098-5538-11e8-9330-f0470b9c5494.png)

The user can pick between single color formatting, or a color range (i.e. a gradient). They have a few options on the left, and on the right they'll see a preview of the table. (It will be important in the case of the user setting a rule on a single column that the preview is horizontally scrolled to the relevant column so that it's visible.)

The dropdown of conditions should be the same as the list of options available when filtering on a number in the query builder (greater than, equal to, etc.). The color picker could be our standard palette, but tinted back to a maximum alpha of about 60% so that the colors will be light enough to preserve cell content legibility.

![single color - input value](https://user-images.githubusercontent.com/2223916/39950817-13a428e8-5539-11e8-9cf1-3228ae9e6ca4.png)

For single-color rules, once they've entered a condition, we'll show them a preview of the formatting.

![single color - preview](https://user-images.githubusercontent.com/2223916/39950823-19e10eec-5539-11e8-800c-ddda3f23586b.png)

For single-color rules, the user can also click a toggle to highlight any rows that meet the condition, like this:

![single color - row highlight](https://user-images.githubusercontent.com/2223916/39950837-339f03ac-5539-11e8-96f7-e0f3604038e2.png)

If the color range option is selected, there are a different set of options: a gradient palette, beginning value for the range, and the ending value for the range. The beginning and ending values can either be set to the smallest and largest values present in the column/table, respectively, or can be set to a static custom value. Clicking the custom value radio option reveals an input box to enter the value.

![color range](https://user-images.githubusercontent.com/2223916/39950842-47b5dd5c-5539-11e8-8c4d-807f955a3ee5.png)

Once the rule is added, the user is returned to the conditional formatting tab of chart settings, with the new rule present as a card. Rules can be removed by clicking the X icon. When multiple rules are present, they can be clicked and dragged to reorder. When multiple rules apply to a cell, the top-most rule takes precedence.

![rules list](https://user-images.githubusercontent.com/2223916/39950846-55fa6752-5539-11e8-8147-6952324d2204.png)

## Pulses
This is just calling out that, especially because we've now shipped a feature that allows for tables to be included in emails and slacked pulses, that tables included in pulses will need to respect any conditional formatting that has been applied. Here's a mockup example:

![formatted table in emailed pulse](https://user-images.githubusercontent.com/2223916/37420377-e7f506b0-2773-11e8-80a7-05af8913dc9b.png)

## Remaining design to-dos:
- [ ] Specify selectable colors and gradients

**Comment by MarkRx** [comment]
In the future (probably out of scope for this) it would be great to support text as well. Use case - text that has the status or health of some set of data. Ranges wouldn't be applicable in this case.

**Comment by crunchtoinfo** [comment]
The described design is good and complete. The hierarchy/prioritization of rules is important and could be highlighted by numbering. I think "Highlight the whole row" should be available even when the whole table is being formatted. This will help with reading sparse tables. It is important to preserve conditional formatting rules when copying questions. This will be as if the user can save sets of rules.
I am curious about the example rules which highlight subtotals - is it possible to show subtotals of some kind?
I will write if I think of more comments.

**Comment by jornh** [comment]
> I am curious about the example rules which highlight subtotals - is it possible to show subtotals of some kind?

The subtotals column are simply part of the Metabase `Orders` example table, so no magic there. Related to total calculations there is the #5308 proposal with the https://github.com/metabase/metabase/pull/5310 a bit dated WIP work.

**Comment by mazameli** [comment]
I've updated these designs after talking through things with @tlrobinson:

- We've simplified rules so that there's no longer a notion of a table-wide rule. That only really applied in the case of pivot tables, and that same effect can be achieved by simply adding a rule to the metric column whose values are inside the pivot table.
- A rule can now be applied to multiple columns at once.
- Changed the layout and some details of the design for the rules list to make them more like the designs for summary/pivot tables that we've been working on.
- I've updated the tab styles, because I hated the old ones immensely. This style should be applied to all chart setting modals.

**Comment by doctor** [comment]
When will this feature be ready for use? Can't wait!

**Comment by crunchtoinfo** [comment]
Hi @doctor, I can see on top of the thread that it is targeted for release 0.30. We're currently on 0.29.3. Don't know how to estimate the time, though.

**Comment by tlrobinson** [comment]
Resolved by #7644

**Comment by Soni03** [comment]
It's exactly the feature I need, but I'm using Metabase with .jar ... Is it impossible to have the final merge branch as a .jar ? Can't find it on the metabase site... ! Sorry for this noob question, I'm a little bit new on github / metabase.

**Comment by Soni03** [comment]
Hi @mazameli and @others, It's exactly the feature I need, but I'm using Metabase with .jar ... Is it impossible to have the final merge branch as a .jar ? Can't find it on the metabase site... ! Sorry for this noob question, I'm a little bit new on github / metabase.

**Comment by tlrobinson** [comment]
@Soni03 This feature will be in the next release. We'll have a RC very soon and hopefully release it within the next week. In the meantime you can use our automatic Docker builds with `docker run metabase/metabase-head`. If you just want the jar instead of the Docker image you can extract it (if you have Docker installed) by running `docker run -d --name tmp metabase/metabase-head:latest && docker cp tmp:/app/target/uberjar/metabase.jar metabase.jar && docker rm -f tmp`

**Comment by vladortegab** [comment]
Hola, estoy en la version  v0.45.1, y este cambio no lo percibo, por ejemplo si tengo un histograma y deseo que cada columna tenga un color diferente no tiene esa funcion
