### ISSUE TITLE
Average of integer values is automatically rounded

### ISSUE THREAD

**Issue by Gabriel-Macena** [metabase/metabase#7124]
When averaging integer values, the result is always rounded. Even if we use a Number visualization to add the missing precision, the original result is lost. Shouldn't averages be set as floats by default, leaving it up to the user to define their precision?

**Comment by sbelak** [comment]
Do you mean when using AVG, or by manual division? The latter is tracked in #8783

**Comment by sbelak** [comment]
Since there has been no reply for 6 months, I'm assuming fixed via #11116
