### ISSUE TITLE
Support calculated columns in questions

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#713]
Goal: The goal of this feature is to decrease the number of important queries in the system that need to be expressed in SQL.

User Stories:
* A user should be able to ask questions that are expressed using add, subtract, multiply, or divide operators
* A user should be able to calculate net profit from a cost and expense field

**Comment by mazameli** [comment]
Here's a design prototype of where we're headed with this:
https://invis.io/PK6LYRCM3
