### ISSUE TITLE
Sec_to_time problem

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7132]
Hello,

I am currently experiencing the following issue- I am working on a MySQL DB and when I write the following code: `select sec_to_time(3600)`  the expected output is 01:00:00. However, I receive an error 'invalid date'.  I tried using date_format function to convert it to the desired output like so `date_format(sec_to_time(3600), '%H:%i:%s')` but then the result I get is 00:00:00. Am I doing something wrong or it is not working as expected?

Thank you in advance!

**Comment by flamber** [comment]
I cannot replicate this on 0.31.2 with MySQL 5.7
Are you still seeing this problem, then please give more details on version of Metabase, MySQL, OS, hosting environment, ...

**Comment by BenjaminGK** [comment]
@flamber 
I am experiencing the same issue as mentioned above.
Using the following:
Metabase 0.32.10
MySQL 5.7
SELECT SEC_TO_TIME(3600)
Gives me an error like this
![image](https://user-images.githubusercontent.com/23311430/63531056-e9514e80-c531-11e9-831d-df99ccffab08.png)
it seems as if metabase can't handle sec_to_time / time_to_sec functions

**Comment by BenjaminGK** [comment]
**Update**:
upon further investigation, it does work when you combine it with time_format 

Example:
TIME_FORMAT(SEC_TO_TIME(duration_seconds),'%h:%i')

But the following does not work:
SEC_TO_TIME(duration_seconds)

Hope this helps

**Comment by t3hfr3ak** [comment]
Just wanted to provide an update that this issue is still persisting. See screenshot for comparison between phpmyadmin/sql console and metabase
![time_to_sec](https://user-images.githubusercontent.com/8204943/67951436-ddcd7400-fbc1-11e9-87f5-219e42e4803c.png)

**Comment by flamber** [comment]
I cannot reproduce any of the problems on 0.35.4 - all of these work:
```
select sec_to_time(3600)
select date_format(sec_to_time(3600), '%H:%i:%s')
select current_time
select sec_to_time(QUANTITY*1000) from ORDERS limit 1
select time_to_sec(CREATED_AT) from ORDERS limit 1
select sec_to_time(1923)
```
The only problem I see if that `AM`/`PM` cannot be changed, but that's #11398
