### ISSUE TITLE
Drilldown feature breaks public dashboard

### ISSUE THREAD

**Issue by lucasloami** [metabase/metabase#7137]
Hi, I created a dashboard in Metabase in I have questions built using pure SQL and using the Custom Option of Metabase. This dashboard was set as public in my configuration. 

When my users access the public link and click over the questions built using pure SQL, everything stays OK, but when they click in the Custom Built Questions the chart freezes. My guess is that it's trying to perform the drilldown action and returns a error. The image below shows what the browser's console displays:

![metabase error](https://user-images.githubusercontent.com/2198270/37546948-dba736a4-294d-11e8-8332-74c9f8e34070.png)

- Browsers: Google Chrome and Firefox
- Operating System: Windows and Ubuntu 17.10
- Metabase version: 0.28.1
- Metabase hosting environment: local docker instalation
- Metabase internal database: PostgreSQL

**Comment by augustoferronato** [comment]
I have the same problem here, with metabase 0.31.1

Browsers Firefox (63.0.3 (64-bit)) and Google Chrome  70.0.3538.110
Operating System Windows 10
Metabase Version 0.31.1
Metabase hosting environment: local docker instalation
Metabase internal database: H2

![error_drilldown](https://user-images.githubusercontent.com/13663686/49555738-0e405b80-f8e8-11e8-9aae-d14d34e3c6a3.PNG)

**Comment by flamber** [comment]
Hi @lucasloami 
Looks like you're having the same problem as #7641 - do you still see this problem on 0.31.2?

Hi @augustoferronato 
Your problem is different - you're seeing this: #8971

**Comment by lucasloami** [comment]
Hi @flamber I didn't have time to test it in this v0.31.2. But in the previous versions ` < 0.30.x` I still had this issue.

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
