### ISSUE TITLE
1 question with two date variables

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7142]
Hey there!

I am having the following problem. I have to make the following query in a MySQL DB. If I simplify it- it would look like this:

`select`
`(select count(*) from table1 where date1 = 'yyyy-mm-dd')`
 `+ `
`(select count(*) from table2 where date2 = 'yyyy-mm-dd')`

Both of the above-mentioned dates must be equal to one another. Since the two dates are from two different tables I have to create two separate variables. Things work perfectly but I need to add this question to a dashboard. When I add a filter to this dashboard I am able to select only one of the two date variables since I am allowed to use only one per question. I was wondering because both of the dates must be identical is it possible to do it with just one variable in order to control the whole question with just one filter from the dashboard? 

I tried using `set @date = {{date}}`  and then setting the dates to equal to it but it does not work. 
I also tried to structure my query like `... date1 = {{date}} ... date2 = {{date}} ...` but the problem is that if I write it like this I am able to choose only a single date rather than a period because I have to set the variable type to "Date". 

Any help will be highly appreciated :)

**Comment by flamber** [comment]
Closing in favor of #4509/#3156. Related to #3324
