### ISSUE TITLE
Test against JDK 8 and JDK 9 in CI

### ISSUE THREAD

**Issue by tirkarthi** [metabase/metabase#7145]
Does the project support running on JDK 8 and JDK 9? I could see JDK 8 being reverted to JDK 7 at https://github.com/metabase/metabase/blame/master/circle.yml#diff-29944324a3cbf9f4bd0162dfe3975d88L6 . I could also see some issues that were fixed with developers trying to set metabase up under JDK 8 or 9. Would it make sense to JDK 8 and JDK 9 targets to the CI config so that there are less issues with respect to latest JDK?

Thanks

**Comment by flamber** [comment]
A lot has changed the past two years, so closing this.
CI is being tested with latest LTS release, [currently version 11](https://github.com/metabase/metabase/blob/master/.circleci/config.yml).
