### ISSUE TITLE
Pie 0 result, page freezes

### ISSUE THREAD

**Issue by tsarenkotxt** [metabase/metabase#7146]
We encountered a problem/bug when we filter by fields and the result is 0 in the Pie, then the page freezes, details:

Table output:

ID Discipline Count
1         d1             0
1         d2             0
1         d3             0
1         d4             0

Pie - the entire dashboard/page freezes
(but if in the Pie one field is more or less zero then the Pie works)

- Browser and the version: (Safari)
- Operating system: (mac OS Sierra)
- Metabase version: (v0.28.1)
- Metabase hosting environment: (Docker)
- Metabase database: (Postgres)

**Comment by regenerat85** [comment]
This seems to be related to #5300, an issue we reported a few months ago and that was identified as bug. Unfortunately, it seems that there has been no progress there.

**Comment by tsarenkotxt** [comment]
thank you
