### ISSUE TITLE
Use of result of one question as a variable of other

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7160]
Hello,

It would be great if we can use the result of one question as a variable for another.

In my current situation, I have access to two different databases- one is a database of the CRM of the company and the other is the database which collects information about employees work sessions.  I can't calculate the number of sales divided by the work hours because the two are in different databases. However, I can create two questions to retrieve them. If only I could use the result of one of them as a variable for the other I would be able to write something like `sales / {{result of other query}}` and get the desired result.

**Comment by flamber** [comment]
It's possible to do in SQL since 0.35.0 with the sub-query variable:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#using-an-existing-question-as-a-sub-query
But it's not possible to do across databases - #3953 - upvote by clicking :+1: on the first post
