### ISSUE TITLE
Titles have up/down arrows when zooming out in Chrome

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7164]
When making the chrome zoom 90% up/down arrows appear by titles.

Example:
![image](https://user-images.githubusercontent.com/17504314/37676028-28eb73b0-2c4d-11e8-82a6-d266f93275cf.png)

Browser: Chrome 64.0.3282.119
OS: Windows 7
Databases: Oracle 12.2
Version: 0.28.1
Host Env: Windows 7
Internal Database: MySQL 5.7

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 with Chrome 83 or Firefox 76 scaled to 90% on Ubuntu
