### ISSUE TITLE
"Filtering on this field" setting for some fields getting set incorrectly on master

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7167]
As discussed in Slack, it seems recently (maybe because of the sync 3.9 work?) that some fields with lots of values which previously had been set to show a search box when looking up field values in filters, had been set to show up incorrectly as a list of all values.

Example: the Product.Title field in the sample dataset was incorrectly set o `a list of all values`. This broke the search/autocomplete widget when trying to filter on that field, and also, it did not show a list of all values. Presumably that's because we have a cutoff hardcoded when there are more than n distinct values, but then it feels like the UX is broken if someone manually sets the setting to `a list of all values`. We might need to add some explanatory copy there.

![screen shot 2018-03-20 at 2 01 58 pm](https://user-images.githubusercontent.com/2223916/37682690-7f1b0580-2c47-11e8-9d2a-733a14de861d.png)

**Comment by mazameli** [comment]
I could not reproduce this on master with a fresh MB instance. Both with the Sample Dataset and with another DB I connected, every field I tried filtering on gave me the field value UI I expected.

Separately, I did notice a few funny non-blocking things about the initial metadata categorization of some fields in both the sample DB and my other DB, but I'll elaborate on that in another issue.

Has anyone else been able to repro this recently?

**Comment by camsaul** [comment]
@mazameli I've also tried this with a new instance on `master` and it's also Search Box

**Comment by mazameli** [comment]
@camsaul yeah, as I mentioned above, this seems like it's been resolved from what I can tell.

**Comment by salsakran** [comment]
ok, closing since this was apparently a transitional failure of some kind. Will re-open if it shows up agian.
