### ISSUE TITLE
Dependent Filters

### ISSUE THREAD

**Issue by sranes** [metabase/metabase#7172]
Can we have the ability to define dependent filters?

Consider a situation where we have dependent fields like Category and Subcategory.
Category "C1" has Subcategory "SC1" and "SC2"
Category "C2" has Subcategory "SC3" and "SC3"

Now, when we use the Category and Subcategory field in the filters, it shows all the values (C1, C2 for Category and SC1, SC2, SC3, SC4 for Subcategory)

When we select C1 as the category, the matching records are returned but the subcategory values in the filter still shows all the possible values (SC1, SC2, SC3, SC4).

Will it be possible to update one filter values based on the other filter? In this case, when C1 is selected for the Category filter, the expectation is only SC1 and SC2 to be available for Subcategory filter.

**Comment by jornh** [comment]
Sounds like a duplicate of #5540

**Comment by sranes** [comment]
Closing this issues as duplicate of #5540
