### ISSUE TITLE
Default table naming convention is capitalizing 'I'

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7173]
Why is this happening? It's almost like the developers like Macs or something :)

![image](https://user-images.githubusercontent.com/17504314/37717282-8fcc195a-2cf6-11e8-94e0-778035caa9b9.png)

Browser: Chrome 64.0.3282.119
OS: Windows 7
Databases: Oracle 12.2
Version: 0.28.1
Host Env: Windows 7
Internal Database: MySQL 5.7

**Comment by jornh** [comment]
It’s working “according to spec” Artifactory is not a word (yet) but Art I and Factory are so it’s just Metabase trying to be a bit too clever. You’ll probably be pleased to know that the “spec it’s working according to” has been broadened a bit and already merged for the next release - see https://github.com/metabase/metabase/pull/6708 and related issues

**Comment by MarkRx** [comment]
Ah that makes sense. We use some terminology that may not be defined in some standard dictionary. I'll change that setting. Thanks.

Closing.
