### ISSUE TITLE
We should get rid of the remove-card confirmation when editing a dashboard

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7174]
My general rule-of-thumb is to have a confirmation when doing something "destructive," but in this case it gets pretty annoying. Also, you can always cancel the edits, or revert the dashboard in case you made a mistake. Removing this confirmation will also make the process of cleaning up an automagic dashboard a lot easier.

![screen shot 2018-03-21 at 10 12 22 am](https://user-images.githubusercontent.com/2223916/37725699-c697be22-2cf0-11e8-8e3a-0672484b3a2d.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
Done at some point, handled with a toast + undo.
