### ISSUE TITLE
If the "automatically generated questions" collection is archived, subsequently saved questions from autodashboards get saved into it anyway

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7177]
Steps to repro:
1. Archive your "automatically generated questions" collection
2. Go generate a new automagic dashboard
3. Save that dashboard
4. Instead of a new "automatically generated questions" collection getting created, the cards belonging to the newly saved automatic dashboard get saved into the _archived_ collection.
5. To see those questions, go _un_archive the collection and then click into it to see the new questions.

**Comment by sbelak** [comment]
Should a new collection be created or we take it that the user doesn't want this collection being populated and subsequently not use a collection at all?

**Comment by mazameli** [comment]
@sb I really think a new collection should be created in this case.

**Comment by sbelak** [comment]
Fixed in #7169
