### ISSUE TITLE
https://aws.amazon.com/blogs/startups/analytics-is-simpler-than-you-think-with-metabase/

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#7179]
Hi guys,

at the end of the article mentioned in the subject there is a link to this page:

https://www.metabase.com/start/aws

Unfortunately it refers to a 404 page.

Best

**Comment by jornh** [comment]
Good catch - that URL could probably redirect to https://metabase.com/start/aws.html

**Comment by salsakran** [comment]
good catch. this involved some pretty horrific Jekyll fiddling, but it should be fixed now.
