### ISSUE TITLE
Feature requests and proposals

### ISSUE THREAD

**Issue by kilonzi** [metabase/metabase#7182]
Ability to join 2 tables in some field. Similar to Inner, Left, Right,Outer Join in MySQL

**Comment by jornh** [comment]
It’s already possible - with two different options:
* either through some admin config 
* or the more flexible/geeky native SQL
for the basics see this discourse thread about [Data Modelling](http://discourse.metabase.com/t/data-modeling/3162)

**Comment by salsakran** [comment]
dupe of #1173 which we've decided is best handled via nested queries https://www.metabase.com/blog/Nested-Queries/index.html
