### ISSUE TITLE
dashboards are visible to everyone

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7189]
- Metabase version: 0.28.2
- Metabase internal database: MySQL

Since the migrations listed here (https://github.com/metabase/metabase/pull/6945#issuecomment-374690433) did not happen properly, the list of dashboards at `/dashboards` is visible to everyone. Though they can't really see results of questions in individual dashboards, the question heading is visible.

This is propagated across all other views where permissions from cards form up the basis for the view.

**Comment by salsakran** [comment]
Thank you @VikramTiwari for reporting this.

I'll be looking into this immediately.

**Comment by salsakran** [comment]
closed via #7193

**Comment by salsakran** [comment]
This should be fixed in 0.28.3, which we just released.
