### ISSUE TITLE
Allow non-zero Y-axis auto range

### ISSUE THREAD

**Issue by rfriedr1** [metabase/metabase#7196]
When setting the y-axis of a graph to auto-range, the range alway includes the value "0" (zero).
E.g. my data are all around -27 (-27.1 to -27.6). When Auto-range is used, the range goes from 0 to -27.x which means that the data are basically only visible as a line without being bale to see the variation in the data.

See the following example. The left y-axis is holding the data with values around -27. Those are plotted in blue at the bottom of the graph.

<img width="949" alt="screen shot 2018-03-24 at 4 56 50 pm" src="https://user-images.githubusercontent.com/4603154/37866071-99e60c66-2f85-11e8-9a16-f723827e5942.png">

A better auto-range would be to use min(y) and max(y) as the range boundaries.

Thanks!

- my browser and the version: Chrome, Safari
- my operating system: OS X 10 and Windows 10
- my databases: MySQL
- Metabase version: 0.28.2
- Metabase hosting environment: jar
- Metabase internal database: H2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
Starting the Y-axis at values other than zero is a bit controversial as it can easily lead to misleading visualizations, especially for charts where the size of the element represents the value, i.e. bar charts (and area charts?), but we do already allow you to set it manually, so I don't see why we shouldn't allow it to auto-range as well (as long as it's not the default behavior).

However, I wonder if we should disable starting the Y-axis at non-zero values (both manual and automatic) for bar charts (and area charts?)

**Comment by nodesocket** [comment]
I created an question on the forums (https://discourse.metabase.com/t/auto-y-axis-range-minimum-always-uses-0/6207/2) and was directed here.

I would actually prefer and love auto to use min Y-axis value. Maybe you could add an additional checkbox `[ ] use min value` when `Auto y-axis range` is checked.

**Comment by MarcGJA** [comment]
This would probably solve it when implemented:
https://github.com/metabase/metabase/issues/3061

**Comment by notrom** [comment]
@flamber This ticket is pretty old, but does seem to have quite a few thumbs up. Any chance this might get some attention?

A bunch of our charts just look like a straight line despite them having quite a bit of variation within a relatively high range. We can't set the range manually as there are no explicitly known high and low values that we can enter for that range.

I agree with @tlrobinson about non zero possibly being misleading, but by forcing it to be 0 my charts are loosing almost all their expressive power, it's just a straight line.

Would be great to have "auto min value" as an off by default option for the y-axis.

**Comment by ohld** [comment]
Some other BI tools have an 'unpin from zero' option for liner graphs (e.g. Looker). I think it is quite easy to implement this on the Metabase frontend side. And this small update can drastically prettify the dashboards with linear graphs. @flamber @mazameli

**Comment by mkaze** [comment]
I don't understand why there is still no option to unpin the charts from zero after ~4 years!

We have a lot of charts where this feature is absolutely needed, but currently they have become useless to look at. Consider this chart which is almost a straight line:

![image](https://user-images.githubusercontent.com/8656825/198968104-562848b4-52f5-4115-94f3-18ece09c7d9e.png)


And the same chart but with y-range manually set to better visualize the variations:

![image](https://user-images.githubusercontent.com/8656825/198967467-9e49c50f-0e42-46b6-a014-1e60464a3182.png)

The former chart tells you almost nothing in terms of visual information, whereas the second chart conveys the variations in visual format in a much better way.

**Comment by nodesocket** [comment]
This is a must have. Perhaps just a new dropdown when `Auto y-axis range` is toggled that specifies start at `0` or start at `the minimum Y value`. I don't know how complicated it is to calculate the minimum Y value, but this feature would be a huge addition. Currently I have to constantly adjust the min and max Y-Axis for each of my graphs which is a huge time waste.

**Comment by nodesocket** [comment]
auto y-axis range defaulting to `0` is a bit ridiculous. Especially when graphing time series data. I have to constantly update the min and max value manually.

Shouldn't the logic just be find the `min` and `max` value in the given time range and set those as the y-axis min and max?

**Comment by OnlineChampion** [comment]
> auto y-axis range defaulting to `0` is a bit ridiculous. Especially when graphing time series data. I have to constantly update the min and max value manually.
> 
> 
> 
> Shouldn't the logic just be find the `min` and `max` value in the given time range and set those as the y-axis min and max?

My company is considering finding alternatives due to this missing feature.

**Comment by nodesocket** [comment]
> > auto y-axis range defaulting to `0` is a bit ridiculous. Especially when graphing time series data. I have to constantly update the min and max value manually.
> > Shouldn't the logic just be find the `min` and `max` value in the given time range and set those as the y-axis min and max?
> 
> My company is considering finding alternatives due to this missing feature.

If this feature can be implemented, my company would STRONGLY consider buying Pro.

**Comment by joshbricel** [comment]
This feature is critical for being able to show meaningful insights of many time series charts.

**Comment by OlexaSkoryk** [comment]
Omg.. in 2023 people cannot implement autoscaling based on min/max values passed to of the chart.. Really?? :) 
Throwing metabase into a window and looking for other solutions which can handle such a simple thing

**Comment by enobayram** [comment]
You keep marking "How could you not implement this simple and essential feature in 5 years!!!" comments as spam, but that's the most relevant kind of comment in this thread. The lack of this extremely simple feature is a show-stopper for Metabase adoption.

**Comment by gonchik** [comment]
Any plans around that?

**Comment by gonchik** [comment]
thank you! %)

**Comment by cdeweyx** [comment]
This is merged for Metabase 50 and available now if you try out the [Release Candidate 1](https://github.com/metabase/metabase/releases/tag/v0.50.0-RC1). If you give it a spin, drop us a note with how it goes.

**Comment by notrom** [comment]
@cdeweyx this looks great to me, I've only messed around with it so far but it's working pretty much as expected. I thought it would work on bars/rows/area but I guess it was intentional to to allow that.

I think this does highlight a small pre-existing frustration I've had around split y-axis in Metabase though, you can't configure the left and right separately (scale, title, unpin from zero etc.), settings are applied to both.

Happy with this unpin from 0 feature though! Looks good.

**Comment by cdeweyx** [comment]
> @cdeweyx this looks great to me, I've only messed around with it so far but it's working pretty much as expected. I thought it would work on bars/rows/area but I guess it was intentional to to allow that.
> 
> I think this does highlight a small pre-existing frustration I've had around split y-axis in Metabase though, you can't configure the left and right separately (scale, title, unpin from zero etc.), settings are applied to both.
> 
> Happy with this unpin from 0 feature though! Looks good.

@notrom Thanks for the feedback! 🙌 We have plans to follow up with separate configuration in split axes cases in the next release, so stay tuned for that.
