### ISSUE TITLE
Not possibile to change / delete mail smtp settings

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#7213]
Hi Guys,

I cannot modify or change smtp settings I wrongly saved.

If I try to modify a red message comes: "Sorry, something went wrong. Please try again."

If I try to delete all settings, I cannot push the button "Save changes"

Is there anything I can do?

Thanks

**Comment by senior** [comment]
@robertobitbond When you see the "something went wrong" it's usually accompanied by a message in the log. One way to get at those log messages is from the top right of the page. For example, if you entered an SMTP server that doesn't exist, you'd see that "Sorry, something went wrong" message but then in the log you'd see the can't connect to SMTP server, or something similar.

We don't currently have a way to remove all email settings.

**Comment by mazameli** [comment]
[Designs for this here](https://github.com/metabase/metabase/issues/7287#issuecomment-379912385)

**Comment by senior** [comment]
Closing this as we've merged a fix to allow clearing of email settings that will be included in 0.29 (to be released soon). If you find that there's some issue updating settings that is not related to a test connection failure, please open up a new issue with details about the failure.

**Comment by ACPK** [comment]
I'm also having the same issue despite my credentials being correct.

**Comment by jpldev** [comment]
I have the same issue... and because of that I cant clear a password of a user because is failing the email configuration. 

How i can delete email settings?
