### ISSUE TITLE
A dashboard open in multiple places submits the same query to the database multiple times.

### ISSUE THREAD

**Issue by jaslo** [metabase/metabase#7217]
A single dashboard open from multiple browsers submits duplicates of the queries on it, causing database (and metabase) peformance issues.

**Comment by salsakran** [comment]
Do you have caching enabled?

**Comment by salsakran** [comment]
`there is not a valid cache entry` is this due to the query being too large for the cache or because it runs in under the minimum time or another scenario?

**Comment by jaslo** [comment]
Because the cache entry is old.  It seems like the cache entry is not created until the query completes.
So if the cache is expired, and two dashboards refresh at (almost) the same time, the query is sent to the database twice.

**Comment by flamber** [comment]
Closing this in favor of #11199
