### ISSUE TITLE
multiple errors in the console while creating custom expression

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7219]
- Your browser and the version: Chrom 65.0
- Your operating system: OSX latest
- Your databases: BigQuery
- Metabase version: 0.28.2
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
While trying to create custom expressions, the UI is trying to do typeahead but is throwing a lot of errors in the console log during that process. At times it even hangs up if there are a lot of fields in the table.

Screenshot of sample errors:
![screen shot 2018-03-27 at 15 58 02](https://user-images.githubusercontent.com/1330677/37999465-c99966f2-31d7-11e8-86f6-a22b1c8940ec.png)

**Comment by VikramTiwari** [comment]
Also, at times UI becomes totally unresponsive and hangs up the browser while the console is only giving these warnings.

![img](https://user-images.githubusercontent.com/1330677/38002675-80e98b74-31e8-11e8-9752-abc4ee76f073.png)

**Comment by tlrobinson** [comment]
@VikramTiwari How many fields does your table have?

**Comment by VikramTiwari** [comment]
Hey @tlrobinson, most of the times, the range is 20-30 but for ~10% of tables its above 80-100.

**Comment by flamber** [comment]
Hi @VikramTiwari 
Are you still seeing this on the latest 0.32.9? I cannot reproduce - even with a table with 124 fields.

**Comment by salsakran** [comment]
closing since there was only one report, and we can't reproduce it on a current version. 

@VikramTiwari if you see this again, we'll re-open and get to the bottom of things.
