### ISSUE TITLE
Pulses appending extra time strings to DATE fields

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#7224]
I'm noticing that date fields are having their formats changed when they're sent via Pulse attachment vs when they're downloaded directly from a question.  For example, when I write a native SQL query that queries a MySQL DATE field, I get a format like `Wednesday, July 24, 2019 12:00 AM` in my results (the time gets appended and set to midnight automatically when using DATE fields instead of DATETIME, which isn't awesome but also not a big deal).  When I download that data from the question (either as CSV or XLS), it downloads in normal SQL date format `2019-07-24`, as I'd expect.  

However, if I have the same dataset sent as a pulse attachment, it appends a time string on the end: `2019-07-24T00:00:00.000Z`.  This makes it hard for users who receive these pulses to be able to use this date field effectively without some additional manual text-to-columns work or something like that.

Thanks for your help and please let me know if you need more info!

My stack:
Chrome 63.0.3239.84 running on OSX 10.12.6
Metabase v0.28.1 running in Docker using H2 internal db connected to MySQL datasources running in AWS Aurora

**Comment by nickhamlin** [comment]
Oh, and I forgot to mention, the workaround I'm using for this as a moment is to manually cast those DATE fields into strings in the SQL layer, which seems to work so far

**Comment by morrison999** [comment]
Same issues as @nickhamlin. Running version 0.03.4. I used date_format() as a work around (MySql).

**Comment by nickhamlin** [comment]
Hi everyone - any update on the ETA around this? At the moment, all the folks on our team who are not using SQL-based questions in their pulses are having pulses sent to themselves, where they're manually removing these time stamps via text to columns in Excel before forwarding on to their final destination. This has turned into a quite a substantial time drain when it's multiplied across lots of reports, so we'd love to be able to remove that burden as quickly as possible. Thank you!

**Comment by flamber** [comment]
Closing in favor of #10803, since the behavior is the same for downloads from a saved question and attachments in a Pulse. There's a different behavior for downloads from unsaved question.
