### ISSUE TITLE
"No matching name" found when it clearly has been found

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7231]
This is with 0.28.3

When I use the search widget for a User ID in a SQL query it tells me "No matching first name found":

![screen shot 2018-03-28 at 4 13 56 pm](https://user-images.githubusercontent.com/1455846/38061192-32f510da-32a3-11e8-8332-06ec3f74e3a4.png)

but when I hit enter the first name clearly *was* found because it shows up on the screen.

![screen shot 2018-03-28 at 4 14 01 pm](https://user-images.githubusercontent.com/1455846/38061198-378c9ee2-32a3-11e8-9ddb-10efc7bc49f4.png)

Steps to repro:

1.  Connect the Metabase database (I'm using Postgres) 
2.  Create new SQL question using this SQL:
     ```sql
     SELECT COUNT(*)
     FROM core_user
     WHERE {{user}}
     ```
3.  Wire up `user` param as Field Filter on `core_user.id` with Filter Widget Type of `ID`. No default value
4.  Try to use `User` search widget and type in the ID of a User
5.  "No First Name Found" pops up in widget
6.  Hit enter to choose ID
7.  First name shows up

**Comment by romeovs** [comment]
I can't reproduce this as far as 0.40.1 so I'm assuming this is fixed.
