### ISSUE TITLE
Bug is messing up display of bar charts sorted weekly

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#7236]
Displaying questions as bar or line chart written in Big Query standard SQL and grouped/sorted by week is not displayed correctly (weeks are written as "2018-13"):
![image](https://user-images.githubusercontent.com/24734846/38076348-a15d3484-3335-11e8-87a5-756afc869bc5.png)

Trying to find the pattern of what Metabase groups/sorts in these charts:
The week is displayed as day with monthly frequency on the axis (e.g. week 1 in 2018 "2018-01" is shown as "Monday, January 1, 2018 12:00 AM"). It ends with December (i.e. Saturday, December 1, 2018 12:00 AM"), and adds additional data from week 2018-13 in December. 
In case of two or more series, the additional ones are fully summed up and shown in the last bar ("December") and none in prior bars. 
It seems that as soon as there are only weeks in 2018 included - starting form "2018-01" - the chart interprets this as a month, despite having "2018-13". 
The question checks a 12-week interval from the current date, so the last 2017 week dropped out of results this week. With the week "2017-52" included in results it was still correctly grouped and sorted in charts.
It does not make a difference whether I am using timeseries or ordinal axis.

If the question is switched to table instead of bar/line, the data is shown and sorted correctly and as intended:

![image](https://user-images.githubusercontent.com/24734846/38077226-9316fb0a-3338-11e8-905a-ad0afe848695.png)

Unfortunately, dashboards with weekly charts are looking useless like this.
Thanks!

Your browser and the version: Chrome Version 63.0.3239.132 (64-Bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.28.3
Metabase hosting environment: Heroku

**Comment by MarcGJA** [comment]
Similar problem, appears unrelated to date format, however, in this case it's just plain old numbers.  And it happens only on certain combinations of limiting by X axis values with no discernable pattern.  In this example of Tons by Price Category limiting on Price works fine in the first instance and totally messes up on the second instance just by changing the lower bound from 3000 to 2000 yet table and row chart equivalents of both indicate results are returned as they should be:
WHERE ...
AND PRICE>={{MNP}}
AND PRICE<={{MXP}}
![image](https://user-images.githubusercontent.com/38047661/38265403-a7e11962-372a-11e8-897c-c3463c6e8cda.png)
![image](https://user-images.githubusercontent.com/38047661/38265479-e67c28ba-372a-11e8-9264-88deae299681.png)
Your browser and the version: Firefox 52.7.3 (32-bit)
Your operating system: Windows 6 (Vista)
Your databases: MS SQL
Metabase version: v0.28.1
Metabase hosting environment: Local

**Comment by HelenMertes** [comment]
In my case above, the problem seems to be that the graph interprets anything with a year, a dash and a number from 1-12 as a month, e.g. "2018-01". As soon as the first week is "2018-13" it works. 
If I remove the dash (using format_date) or add a "/" instead of "-" it works as well.
So yes, playing around with custom formatting can help. But the underlying problem does not seem major, maybe you guys can find a fix!
Thanks!

**Comment by flamber** [comment]
Metabase would not know if you're trying to display a year-month or year-week, when using SQL.
To help Metabase understand, add a `W` in front of the week, like `2020-W02`
Related to #3842
