### ISSUE TITLE
How do you capture errors/stracktraces?

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7238]
This is more of a question. If there's nothing in place, I would suggest using Sentry (https://sentry.io/welcome/). They have a great free package and are open source.

An easy integration is to just add it to the index.html and hope it catches all the errors but a good way would be to make sure that it's integrated well with React and Clojure. It would be even better if it was a setting that you can set it from settings.

Thoughts? @salsakran

**Comment by salsakran** [comment]
I think my preference would be to just log them to a lambda service and dogfood Metabase.
