### ISSUE TITLE
Doesn't really make sense to show field value search when doing "contains" or "does not contain"

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7239]
If I'm filtering on a field with a lot of values, like a full name field, and I want to see everyone whose last name is something like "smith," the current behavior where the search widget tells me that no matching names are found makes me think that they're aren't any people who match. 

I think in case of "contains" or "does not contain," all you really want actually is just an input box to type the string you want to match — you don't really need to select from or search field values.

<img width="678" alt="screen shot 2018-03-29 at 4 53 49 pm" src="https://user-images.githubusercontent.com/2223916/38119520-2e1cd69a-3377-11e8-8f75-826b722585b9.png">

**Comment by flamber** [comment]
Closing, since the little autocomplete is not shown in 0.39.0 - guessing it was PR #15477
