### ISSUE TITLE
Feature Request to have Dashboards as a group

### ISSUE THREAD

**Issue by sandeepbathina** [metabase/metabase#7240]
Hi,

We started using metabase and it looks great for us. Currently we are having multiple dashboards and its becoming difficult for us to identify a particular dashboard of a group. It would be nice if you could provide dashboards as a group option similar to one we have for questions.

**Comment by jornh** [comment]
Duplicate of #6509 ... which in turn I think is a duplicate of #6081.

**Comment by salsakran** [comment]
closing this in favor of 6509 which has the most upvotes.
