### ISSUE TITLE
Memory issue: Java process eats up all the memory, but query doesn't even get run in db engine

### ISSUE THREAD

**Issue by JoeSham** [metabase/metabase#7243]
Hi,
since upgrading to 0.28.3 (from 0.28 I think), we are having some weird memory issues. 

We are running Metabase in a Docker container in Rancher, everything hosted in AWS. Currently the container has 7 GB of memory available. We also use JAVA_OPTS='-Xms6700m -Xmx6700m -XX:MaxPermSize=256m'.

And after the upgrade it happens very often that the java process eats up all the available memory and the container crashes (and gets auto-restarted).

Before the upgrade we had only 4 GB memory and didn't set JAVA_OPTS at all, and while there were some crashes still, they were much less frequent.

Regarding our use-case: we are using Metabase very intensively, with several dashboards being run 24/7 with an auto-refresh timer (1, 5 or 10 minutes), and tens of users using Metabase simultaneously a lot of the time. We have a rather large PostgreSQL db instance for this and the db is mostly fine regarding usage of resources.

The weird thing is, that most of the time when Metabase container crashes, it is when some more difficult query (or queries) is executed, but the query doesn't even make it to the db engine. **What happens is that the Java process starts eating more and more memory, but the query is not being run in the db at all**. Then it just crashes when it passes the 7 GB of the container. It happens consistenly with at least 1 of our queries that used to work just fine before the upgrade (eventhough it took quite a while to finish). Also, running the query in question directly in the db, it works just fine and finishes usually under 30s.

- Your browser and the version: (Chrome Version 65.0.3325.162)
- Your operating system: OS X El Capitan
- Your databases: PostgreSQL 9.6.6 (AWS RDS db.t2.large) for Metabase_internal_db, PostgreSQL 9.6.6 (AWS RDS db.r4.4xlarge) as the db we query
- Metabase version: 0.28.3
- Metabase hosting environment: run in a docker container (managed with Rancher), container and both dbs in AWS
- Metabase internal database: PostgreSQL 9.6.6 (AWS RDS db.t2.large)

Ps: I know the issue is a bit vague, but we have been trying to pinpoint/solve this for quite a while now and we are a bit out of ideas what else to do. Except maybe moving the whole thing to a host with much more memory. So any help or ideas are very welcome.

**Comment by JoeSham** [comment]
Possibly similar to https://github.com/metabase/metabase/issues/7197.

**Comment by JoeSham** [comment]
Thank you guys for making this P1, appreciate it!

Just a few questions:
1. What's the ETA of this (0.29 release)?
2. We probably will want to roll back from 0.28.3 to 0.28.0 (or 0.27.2) until 0.29 with this fix is released. Should that go without problems or do we have to do something for that rollback to work? Thanks!
@salsakran @camsaul @senior

**Comment by salsakran** [comment]
Hey @JoeSham 
This might be a regression caused by our use of instaparse (a library we use to support SQL templates).

Could you share the queries you're running?  We've found one specific place where instaparse is inefficient (big query uses `[` and `]` a lot). It would be really helpful to find other examples of queries that break instaparser.

**Comment by salsakran** [comment]
0.29 is blocking on this, so it'll go out when we get to the bottom of this. 
Rollbacks should be fine.

**Comment by JoeSham** [comment]
Hey, thx for taking care of this issue so fast! We will test whether 0.28.5 solved our problems and report back. Thank you!
