### ISSUE TITLE
Auto-refresh doesn't work for Dashboards if redirected after login

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7244]
If you click a link like `https://<host>/dashboard/30#refresh=1` and then have to log in, you'll be redirected to `https://<host>/dashboard/30#refresh=1%23refresh%3D1` after log in. Refresh doesn't work and the refresh interval will be:

![screen shot 2018-03-30 at 11 32 31 am](https://user-images.githubusercontent.com/1455846/38149207-82266bc4-340e-11e8-9369-ef6dfc715034.png)

Or maybe it does work: as @senior said 

> NaN just takes a while, that's all

**Comment by flamber** [comment]
Fixed by #12425
