### ISSUE TITLE
Settings button in dashboard edit view not working

### ISSUE THREAD

**Issue by alexezimm** [metabase/metabase#7246]
Button to adjust settings in dashboard edit view appears dead.

![image](https://user-images.githubusercontent.com/36081808/38153312-0c80fdc2-343a-11e8-9781-5762119e3ed4.png)

- Your browser and the version: Chrome version 64.0.3282.186
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.28.1
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
Create dashboard, add question to dashboard, attempt to click gear icon to adjust settings

**Comment by alexezimm** [comment]
As an update, this appears to be occurring for the delete button as well.

**Comment by raulprivate** [comment]
Same issue for me; any config button within dashboards dead (including delete button). 
Your browser and the version: Chrome Version 66.0.3359.139 
Your operating system: Windows 10
Your databases: Postgres
Metabase version: 0.29.3 (the latest, today is 14/05/2018)

**Comment by mazameli** [comment]
Does this happen for you guys on other browsers in Windows as well, e.g. Firefox, Edge, IE, etc.?

**Comment by alexezimm** [comment]
Working fine in IE and Firefox for me

**Comment by raulprivate** [comment]
True! just tried with Firefox and Edge and works fine

**Comment by notrom** [comment]
This looks related to #2187 which has some more details and a javascript console work around.

For me it's consistent across all dashboards in chrome, but Firefox is fine even on the same dashboards.

Nothing shown in javascript console when this happens.

It feels like something is overriding the click event on the buttons, could be the drag event maybe?

I'll try clearing caches tomorrow and update but from memory it made no difference.

**Comment by TurkerTunali** [comment]
I've realized that first click doesn't work but the second click works as expected. I think that there should be 500ms delay nearly.

(Windows, Firefox)

**Comment by notrom** [comment]
Clearing Chrome caches made no difference.

All works fine in Firefox. (Windows 7)

**Comment by ashishnirvana** [comment]
I am also facing this issue.

To me it seems that the drag feature is overriding the click.

This issue got fixed for me .. when I added a new card to the dashboard.. and at the same time changed some other card or removed it.

**Comment by akalankadesilva** [comment]
Hi,
I'm facing the same issue with 0.31.2 using Chrome 73.0.3683.75 on Windows 10. The reason appears to be that the pointer events are disabled when dragging. Commenting it out solved the problem.
File: app/dist/styles.bundle.css
Comment it out like this:
/* ensure action buttons do not respond to events when dragging */
.Dash--editing.Dash--dragging .DashCard-actions {
  /*pointer-events: none !important;*/
}
Only downside is if you click on a edit/remove/add series button and drag, it triggers the button click. No big deal.  cheers!

**Comment by mbvictoria** [comment]
Closing - should be fixed with #10206
