### ISSUE TITLE
Support multiple datasets in one BigQuery database

### ISSUE THREAD

**Issue by satyadeepk** [metabase/metabase#7250]
**UPDATE November 2021**: It is now on the roadmap: https://www.metabase.com/roadmap/

----

## Usecase
We are currently using Redash as our BI tool and are planning to migrate to Metabase to better support our non-tech users with zero knowledge of SQL. 

We use BigQuery as our data warehousing solution to load data from various sources. 
They are loaded into different datasets based on their source (Mysql, Mongodb, Mixpanel, Branch, Appsflyer etc) as below.
<img src="https://user-images.githubusercontent.com/478578/38170585-2e28ee44-35a7-11e8-9557-b7c189fbda21.png" width=240/>

This gives us the advantage of joining data across multiple sources like 
```mysql.users JOIN mixpanel.event ON mysql.users.id = mixpanel.event.user_id```
(Note mysql and mixpanel are Bigquery datasets here).

## Current limitations
Currently the BigQuery database in Metabase only supports one dataset id. So it limits the foreign key mappings in Metabase query builder to a single dataset only. In order to join foreign keys across multiple datasets, we have to resort to using raw SQL in Metabase.

An alternate way to achieve this currently is to load all sources into a single dataset in BigQuery with a prefix. But it requires significant change to our ETL pipeline and also defeats the structure of datasets.

<img src="https://user-images.githubusercontent.com/478578/38170728-26f23b1e-35aa-11e8-9505-0120736a437d.png" width=250 />

## Proposal 
It would be great if Metabase allows multiple dataset ids in Bigquery database settings. May be as a comma seperated string. 

Another idea is to make dataset id field optional to fetch tables from all datasets. Bigquery has an API to fetch all datasets.
The table names in the Data Model can be fully qualified names like `mysql.users` instead of just `users` in this case.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sabino** [comment]
Hey @satyadeepk 
I have a WIP for a driver that is currently using the JDBC to do the introspection but the queries are still being executed by the API (the current way). Since I couldn't make it fully work with JDBC as I get this error whether I try to enable/disable autocommit. It is possible to simulate the error using, for instance, [datagrip](https://i.stack.imgur.com/qjCj9.png)

But it is working as you described.

I even tried to make possible to connect to multiple projects, but metabase is not ready for this apparently. I'm not a clojure developer and this was my first attempt to make something in clojure, so there might be a better way of doing this.

https://github.com/metabase/metabase/pull/6754

The driver is being used at @ContaAzul but I'm not working there anymore, still looks like it is usable. I might write tests I just don't know if this was the write approach. @renanleme can confirm if the driver is being used.

Also you need to setup a service account and a json key file for authetication. But as I said it is still using the same way of querying as the current driver so you need the same (project/client key) to be able to authenticate.

**Comment by satyadeepk** [comment]
Hey @sabino. Thanks for letting me know! 
So I copied your file `bigqueryjdbc.clj` from your PR into my local drivers folder and ran `./bin/build`. The compilation went find and bigqueryjdbc also got compiled as below.
But when I run the jar file, I don't see the field for service key in the UI.
```
...
Compiling metabase.db
Compiling metabase.driver.bigquery
Compiling metabase.driver.bigqueryjdbc
...
```
<img src="https://user-images.githubusercontent.com/478578/38453062-0e220868-3a6d-11e8-9899-fa3494a99199.png" width=500 />

Am I missing something, I have downloaded the simba bigquery jar file but not sure how to include it in the build.

**Comment by sabino** [comment]
@satyadeepk sorry for not being clear about adding the jar files.

As stated in the metabase documentation you need to put all custom drivers files in the `plugins` folder.
https://github.com/metabase/metabase/wiki/Writing-A-Driver#shipping-a-driver-as-a-plugin-jar

If you are using Docker you could set a mount point to `/plugins` and set the MB_PLUGINS_DIR env variable to this same folder.

You can grab the driver files from [here](https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.1.5.1005.zip) or [here](https://cloud.google.com/bigquery/partners/simba-drivers/)

**Comment by satyadeepk** [comment]
@sabino Based on your instructions, I have placed the downloaded jar files in the plugins folder and set MB_PLUGINS_DIR to it.
When I run the compiled jar, the plugin is loaded as shown in log, but I still can't see "Bigquery jdbc" in the database selector in UI.
 
**metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/GoogleBigQueryJDBC42.jar... **

```
04-07 22:42:11 INFO metabase.util :: Loading Metabase...
04-07 22:42:15 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓 
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.amazon.jdbc.classloader.JarInJarClassLoader (file:/Users/satyadeep/projects/metabase/target/uberjar/metabase.jar) to field java.net.URL.factory
WARNING: Please consider reporting this to the maintainers of com.amazon.jdbc.classloader.JarInJarClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
04-07 22:42:21 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-07 22:42:21 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

04-07 22:42:21 INFO metabase.core :: Starting Metabase version v0.29.0-snapshot (e9cdecf master) ...
04-07 22:42:21 INFO metabase.core :: System timezone is 'Asia/Kolkata' ...
04-07 22:42:21 INFO metabase.plugins :: Loading plugins in directory /Users/satyadeep/projects/metabase/plugins...
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/google-api-client-1.22.0.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/google-api-services-bigquery-v2-rev355-1.22.0.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/google-http-client-1.22.0.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/google-http-client-jackson2-1.22.0.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/google-oauth-client-1.22.0.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/GoogleBigQueryJDBC42.jar... 🔌
04-07 22:42:21 INFO metabase.plugins :: Loading plugin /Users/satyadeep/projects/metabase/plugins/jackson-core-2.1.3.jar... 🔌
04-07 22:42:23 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-07 22:42:23 INFO metabase.db :: Verifying h2 Database Connection ...
04-07 22:42:23 INFO metabase.db :: Verify Database Connection ...  ✅
04-07 22:42:23 INFO metabase.db :: Running Database Migrations...
04-07 22:42:23 INFO metabase.db :: Setting up Liquibase...
04-07 22:42:23 INFO metabase.db :: Liquibase is ready.
04-07 22:42:23 INFO metabase.db :: Checking if Database has unrun migrations...
04-07 22:42:25 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
04-07 22:42:25 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
04-07 22:42:25 INFO db.migrations :: Finished running data migrations.
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
04-07 22:42:25 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
04-07 22:42:25 INFO metabase.task :: Loading tasks namespace: metabase.task.cleanup-temporary-computation-job-results 📆
04-07 22:42:25 INFO metabase.task :: Loading tasks namespace: metabase.task.follow-up-emails 📆
04-07 22:42:25 INFO metabase.task :: Loading tasks namespace: metabase.task.send-anonymous-stats 📆
04-07 22:42:25 INFO metabase.task :: Loading tasks namespace: metabase.task.send-pulses 📆
04-07 22:42:26 INFO metabase.task :: Loading tasks namespace: metabase.task.sync-databases 📆
04-07 22:42:26 INFO metabase.task :: Loading tasks namespace: metabase.task.upgrade-checks 📆
04-07 22:42:26 INFO metabase.core :: Looks like this is a new installation ... preparing setup wizard
04-07 22:42:26 INFO metabase.core :: Please use the following url to setup your Metabase installation:

http://localhost:3000/setup/


04-07 22:42:26 INFO metabase.core :: Metabase Initialization COMPLETE
```

**Comment by satyadeepk** [comment]
@sabino It works finally. Thanks a lot for your driver.

Realised the plugins are not loading into classpath with Java 9 even after adding JVM option `--add-opens=java.base/java.net=ALL-UNNAMED` as mentioned in [docs here](https://github.com/metabase/metabase/blob/master/docs/administration-guide/databases/oracle.md#enabling-plugins-on-java-9).

So I switched to Java 8 and the plugins are loaded now.

**Comment by te-chris** [comment]
Is this in the roadmap? Bit of a deal-breaker for us at the moment.

**Comment by luizarakaki** [comment]
We are currently running a DW on Postgres and moving to BigQuery. This issue is really a deal-breaker... Is it on the roadmap? It would be awesome to have all the datasets.

**Comment by affsantos** [comment]
Any news about this?

**Comment by cidiomar-jr** [comment]
Forking the current, official driver, I was able to get BigQuery working with multiple datasets.
The code still needs some refactoring, but everything has been working so far, even Custom Questions.

The driver is being versioned there: https://github.com/pipefy/metabase-bigquery
Any help with testing and refactoring is will be very appreciated.

**Comment by django23** [comment]
Dear @metabaseops,
Do you have an update for us on this? There are quite some people who added examples and code. Could you help me understand what is holding back why we are not implementing/merging it.

Cheers,

**Comment by calvingiles** [comment]
This [3rd party driver](https://github.com/pipefy/metabase-bigquery) is great for doing this, but has since become out of date relative to the official one, particularly in that is does not have the security fix from the latest patch applied. Could the work done there be incorporated into the official driver? I am happy to help with testing, but I don't know any java-like languages so will struggle to do the actual porting.

**Comment by ldeboer** [comment]
Also would love support for this.

**Comment by lucaslrolim** [comment]
The inclusion of this feature in the official version will be a big improvement for the usage that we have at Hurb.com.

**Comment by gajus** [comment]
Unless I am missing something, there is no way to connect two datasources even using plain SQL.

**Comment by csaroff** [comment]
My boy @iRunner was able to update the third-party driver to be up-to-date with the latest version of metabase (0.38.0) - https://github.com/pipefy/metabase-bigquery/pull/3

@camsaul It would be super cool if this could be pulled in and supported upstream. Looks like there's at least 57 people who'd appreciate this feature

**Comment by MarkMacArdle** [comment]
I really struggled to build the community driver for this, but did eventually manage it. So others don't have to go through the same struggle I've added the jar file to this [release page](https://github.com/MarkMacArdle/metabase-bigquery/releases). It was made from a repo which merges @iRunner's addition of using a service account with @blucz's updates to 0.39.

Also I deployed this on Heroku using the button in [this repo](https://github.com/MarkMacArdle/metabase-deploy) which I modified to include the jar of the updated BigQuery driver.

Thanks so much to everyone in this thread! I would not have been able to make a community driver on my own and I don't believe I'd have be able to justify using Metabase without it. I'm so grateful!!! 🙇

**Comment by AnatolePledg** [comment]
Hi @flamber,

Any update on this one ? We cannot use the community driver as we are using Metabase Cloud.

Thanks

**Comment by flamber** [comment]
It is now on the roadmap: https://www.metabase.com/roadmap/
I cannot tell you if it will arrive in v42 or later. Or when the exact date for releases will be.
Follow this issue by clicking Subscribe in the sidebar of the issue. When this issue closed, it will have a milestone, and clicking that milestone will show a tentative release date.

**Comment by camsaul** [comment]
@jeff303 didn't you implement this?

**Comment by jeff303** [comment]
Yes, this is coming in 42 via #19547.
