### ISSUE TITLE
FATAL: database "..." does not exist

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#7252]
I'm using metabase v0.28.4 docker image, and got an error repeating a lot (For example, I counted 3 error messages in the same timestamp `Apr 02, 2018 1:53:43 AM org.postgresql.Driver connect`)

![screen shot 2018-04-02 at 9 26 40 am](https://user-images.githubusercontent.com/2088055/38180960-66a49cb0-365a-11e8-8d4a-ec83a6757219.png)

Please help

**Comment by jornh** [comment]
This error could happen due to e.g. networking issues. I see the issue is at 2 o’clock does it affect your normal use?

The Troubleshooting Guide has steps to try out when you experience database connectivity issues: https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html

**Comment by salsakran** [comment]
@thucnc that is an error coming back from the database we're trying to connect to.

I'm going to guess that it means that the server + user + pass combination at that point in time doesn't have or can't see the database name. Debugging this is outside the scope of the issue tracker, but please open a thread on our user forum, and we can try to help you (with the end goal of adding to that troubleshooting guide).

**Comment by thucnc** [comment]
@salsakran you are right, as I can see this error persists on older version.
