### ISSUE TITLE
Proposal: Able to clone dashboard's

### ISSUE THREAD

**Issue by jonatasfreitasv** [metabase/metabase#7254]
# Proposal
A simple function to clone Dashboard's.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by bcbob** [comment]
Yes this will be super useful

**Comment by MarkRx** [comment]
## Implementation Details
- A copy of a dashboard will duplicate all filters and cards including card settings overrides
- A copy of a dashboard will not duplicate questions - all cards will reference the same underlying question
- (stretch) an option when copying a dashboard could be added to do a "deep copy" of questions
- The creator of the copied dashboard will be the user that initiated the copy
- The create / update timestamps of the new dashboard will be the time the copy was made (though I can see a case where those would remain the same as that is an approach software sometimes takes)
- A dashboard can only be copied if the user can read the source dashboard and can write to the target collection. A copy should not be prevented if the dashboard contains cards that the user cannot view - the new dashboard would simply also have a corresponding card that cannot be viewed.

## UI
A "Copy this item" dropdown should be added to the collections page:
![collection_single_copy_dropdown](https://user-images.githubusercontent.com/17504314/47045554-14745000-d161-11e8-99c3-b82a3cc57beb.PNG)

Copying a single dashboard will open up a dialog with a default of 
```
Name: <name> - Copy, 
Description: <description>, 
Collection: <current collection>
```
![copy_dashboard_modal](https://user-images.githubusercontent.com/17504314/47046230-ad579b00-d162-11e8-8b76-39bc7359c32d.PNG)

Copying multiple dashboards at once should also be supported. It should reuse the same dialog as moving multiple items. All copies will have - Copy appended to their names.
![dashboard_multi_copy_dialog](https://user-images.githubusercontent.com/17504314/47045625-44bbee80-d161-11e8-8f22-798d769fad8e.PNG)
![dashboard_multi_copy](https://user-images.githubusercontent.com/17504314/47045651-530a0a80-d161-11e8-8265-b735c4519fbd.PNG)

Copying a dashboard should also be available from the dashboard itself.
![dashboard_copy_from_dashboard](https://user-images.githubusercontent.com/17504314/47045679-64531700-d161-11e8-8b24-d26c0124e263.PNG)

**Comment by camsaul** [comment]
Implemented by #8975

**Comment by mchip22** [comment]
Awesome new feature!

**Comment by nawar** [comment]
Awesome feature! It'll be great if the possibility of doing a "deep copy" for the questions is available.
