### ISSUE TITLE
Can't edit table metadata

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7256]
On master, trying to edit the name or description of a table in the Data Model section results in a 400 error. Same thing if trying to edit those fields or the "why this table is interesting," "things to be aware of about this table" sections in the Data Reference. 

Editing _field_ names and types seems to work just fine. 

The error is:

```
04-03 14:16:16 DEBUG metabase.middleware :: PUT /api/table/5 400 (9 ms) (0 DB calls).
{:errors {:entity_type "value may be nil, or if non-nil, value must be one of: `event`, `person`, `photo`, `place`."}}
```

When doing this in the Data Model, the UI initial appears to correctly change the name or description, but then navigating away and then back again shows the previous value for the field(s), showing the change wasn't actually made.

![table-name](https://user-images.githubusercontent.com/2223916/38276647-8152e2ba-374a-11e8-9035-e87769816475.gif)

**Comment by sbelak** [comment]
This one is due to me reusing entity_type for automagic dashboards. I was under the impression that we never use it.
