### ISSUE TITLE
Maximum Callstack Exceeded on card rendering

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#726]
Getting an error message on executing what seems to be a valid card.

Canary card for reproduction here: 
https://staging.metabase.com/card/16

**Comment by agilliland** [comment]
@salsakran you mind trying to reproduce this one more time and seeing if this is still happening?  i'm not able to reproduce this any longer.

**Comment by camsaul** [comment]
Motion to close since we can't reproduce this anymore (the issue is ~7 months old) and the original poster hasn't responded to requests asking whether they're still seeing it

**Comment by agilliland** [comment]
sure :+1:
