### ISSUE TITLE
category filter is showed different between user account 

### ISSUE THREAD

**Issue by Wind-hunter** [metabase/metabase#7264]
Hi, everyone.

I find out an issue with category filters. 
with admin account, i setup a category filter show a list but in the others account type (without query permission), they can't see the list and must input text/number to a box to filter data.

I'm a dummy user and I don't know where the issue come from. Is that a bug? Can you fix it, please.
Thank you very much. :D 

db: amazon redshift (postgreSQL 8.0.2)

**Comment by mazameli** [comment]
Could you tell us which version of Metabase you're using, please?

**Comment by Wind-hunter** [comment]
We use metabase version 0.28.1

**Comment by salsakran** [comment]
closing this in favor of #9270 since that has a reproduction scenario. Bumping that to a P1 to match this.
