### ISSUE TITLE
Proposal : Saving a question into multiple collection

### ISSUE THREAD

**Issue by CsClement** [metabase/metabase#7265]
### Feature proposal : Put question in multiple collection
Hello everyone,
currently (version 0.28.1) any saved question can be placed in one and only one collection. Should it be possible to enable a question to be put into several (2 or more) collections ?
In my company there are several different departments but they sometime use the same question. We wish we could put a same question into different collection. The only way to do this for now is to duplicate the question and that is kind of heavy when we already have lots of report in Metabase. Having a hierarchy/tree would be good too, but not necessary.
Thanks

**Comment by mazameli** [comment]
Our current thinking is to go forward with the "folders" approach to organization, allowing sub-collections to be put in any collection, and allowing dashboards, pulses, metrics, segments, and questions to all be saved in collections.

**Comment by salsakran** [comment]
closing this since we went with the folders approach.

**Comment by mukgupta** [comment]
What exactly is this folders approach ? @salsakran @mazameli

**Comment by flamber** [comment]
@mukgupta Currently the Collections works just like folders on your computer. You can create sub-collections etc.

**Comment by mazameli** [comment]
@mukgupta Docs about collections (folders) are here: https://www.metabase.com/docs/latest/administration-guide/06-collections.html
