### ISSUE TITLE
ObjectJSON fields have no max-width

### ISSUE THREAD

**Issue by davidRichards39** [metabase/metabase#7268]
When viewing a record that contains a JSON column, there is no max-width applied to the display of the value. If the field happens to contain very long strings, it will cause the entire display to stretch, requiring horizontal scrolling to view any other table values. Local testing shows applying a `max-width` to the ObjectJSON class makes this much more readable

Before:
![json_field](https://user-images.githubusercontent.com/17985578/38325107-1734cee0-3810-11e8-9ff5-bebcdf14a017.png)

After applying `max-width:600px` (on a 1080p resolution screen):
![json_after](https://user-images.githubusercontent.com/17985578/38325233-6e34bec6-3810-11e8-85e5-dab1166c89e6.png)

- My browser and the version: Version 65.0.3325.181 (Official Build) (64-bit)
- My operating system: Ubuntu 17.10
- My databases: Postgres
- Metabase version: v0.28.3
- Metabase hosting environment: Elastic Beanstalk

**Comment by flamber** [comment]
Fixed by #12442 in 0.35.4
