### ISSUE TITLE
Pulses should be sent serially not concurrently

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7278]
This issue arises when you have many pulses schedule to go out at the same time. As an example, if you have 10 pulses scheduled to go out at midnight, we will spin up 10 threads and try to send all 10 at the same time. This can cause issues if the pulses share resources (like a connection pool) and can cause memory issues depending on how many pulses are being sent at the same time.

We had an issue similar to this with sync that was fixed in https://github.com/metabase/metabase/pull/6612/files. We should apply a similar fix to pulse sending. Using that same logic, if 10 pulses were all schedule to send at midnight, they would be sent single threaded, serially rather than concurrently.

**Comment by camsaul** [comment]
We've been sending pulses serially for a while not, I don't remember when exactly we made the change but it's this way now.
