### ISSUE TITLE
New field value search/list doesn't seem to show values for Google Analytics

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7284]
This is on our stats instance.

I tried this with a few different types of fields, some with only a few values, some with many values, and I verified they were set to Categories, double checked their search settings in the admin panel field settings, and then rescanned their field values. It appears that the field values aren't showing up in any of these cases, but the problem seems specific to GA.

<img width="792" alt="ga-list" src="https://user-images.githubusercontent.com/2223916/38392165-68ec8874-38db-11e8-92d0-9e6a82166a7e.png">

<img width="747" alt="ga-search" src="https://user-images.githubusercontent.com/2223916/38392168-6bfe0722-38db-11e8-9b08-cab43d432a55.png">

**Comment by salsakran** [comment]
did it used to show up in the old widget?

**Comment by flamber** [comment]
This is likely a limitation, since GA require a metric for doing fingerprinting - see #12595

**Comment by FranzBusch** [comment]
Would be really useful to get field values working for GA

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
