### ISSUE TITLE
Query builder - Can't search multi-word columns from custom expressions

### ISSUE THREAD

**Issue by sapansanu** [metabase/metabase#7291]
Your browser and the version: Chrom 65.0

Your operating system: OSX latest

Your databases: BigQuery

Metabase version: 0.28.5

Metabase internal database: MySQL

Repeatable steps to reproduce the issue:
Search multi-word columns from custom expressions (it breaks when you hit space)

@mazameli @kdoh @tlrobinson @attekei For debugging when I try to console.log in "frontend/src/metabase/query_builder/components/expressions/TokenizedInput" inside "onKeyDown" function, the console.log never executes. Am I doing something wrong?

Also, please give your suggestions to fix this bug.

Screenshot:
![analytics_issue_183](https://user-images.githubusercontent.com/14345483/38437074-3aa84376-398b-11e8-9a9b-23d4e8ec84d2.gif)

**Comment by lindsay-stevens** [comment]
I came across this too, with MB v.0.28.6, Chrome 68, Postgres 10 for app & target.

There does seem to be a workaround, namely to put your multi-word column name / alias inside of double quotes. However it seems that if you try to type this quoted expression into the UI control in Metabase, you'll will summon a flood of "sad sad panda" parsing errors that will lock up your chrome tab. Seriously! (see below). The flood of errors starts after the first space in the quoted name. But, you can write out the full expression in a text editor and paste it in, and it works.

What I was actually trying to do was to use a "Max" aggregation for a text field, which is valid in Postgres for any sortable type but the QB only offers numeric columns for aggregates like min, max, sum, etc.

Typing it in, which causes the chrome tab to lock up completely (had to close it):

![sad sad panda](https://user-images.githubusercontent.com/6345269/44511479-0c68d880-a6fb-11e8-9d0c-82580bb27370.PNG)

Pasting in the expression:

![not a sad panda in sight](https://user-images.githubusercontent.com/6345269/44511492-17236d80-a6fb-11e8-8703-125b82890897.PNG)

**Comment by flamber** [comment]
Fixed by #11868.
