### ISSUE TITLE
Is it possible to embed iFrames in Metabase-Markdown Cards ?

### ISSUE THREAD

**Issue by collegeimprovements** [metabase/metabase#7297]
Is it possible to embed iframes in Markdown cards on Dashboard? That way we can embed various D3 and other visualizations on dashboard!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by rburhum** [comment]
This would be amazing

**Comment by trixel** [comment]
+1

**Comment by kangjianhua** [comment]
I want  it !

**Comment by e-gaulue** [comment]
Another important use case would be to integrate HTML forms that could modify the database gathered by the dataware house.

We can do it with embedded iframe, but it's not so nice.

**Comment by e-gaulue** [comment]
Well it's not so hard to let Metabase accept HTML code in Markdown. Metabase use different tools certainly for different purpose : react-markdown (for html rendering), flex-mark (maybe for internal).

Once done, you're stop by `child-src` in:

> Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-eval' https://maps.google.com https://accounts.google.com    'sha256-K2AkR/jTLsGV8PyzWha7/ey1iaD9c5jWRYwa++ZlMZc=' 'sha256-ib2/2v5zC6gGM6Ety7iYgBUvpy/caRX9xV/pzzV7hf0=' 'sha256-isH538cVBUY8IMlGYGbWtBwr+cGqkc4mN6nLcA7lUjE='; child-src 'self' https://accounts.google.com; style-src 'self' 'unsafe-inline' https://accounts.google.com; font-src *; img-src * 'self' data:; connect-src 'self' https://accounts.google.com metabase.us10.list-manage.com   ; manifest-src 'self';  frame-ancestors 'none';

This is set in `src/metabase/server/middleware/security.clj`.

So, this also could be done, but to keep it secure, this means add a place in the BO to store those URL you want to accept. Note that public embed metabase is not concerned.
