### ISSUE TITLE
Greyed out filtered by and grouped by when creating new custom questions

### ISSUE THREAD

**Issue by whitemark** [metabase/metabase#7299]
Hello 

When trying to create custom questions I have Greyed out filtered by and grouped by 

Environment
metabase 0.28.5, JRE 8 Update 16, Windows 2012 R2, Chrome 65.0.3325.181, internal DB H2, Datasource is GreenPlum 4.3.9

The issue
When trying to create custom questions I have Greyed out filtered by and grouped by 

See below picture
![image](https://user-images.githubusercontent.com/13211752/38480621-e747ba6e-3c09-11e8-9550-d6e793135383.png)

Normal behavior should be like below
![image](https://user-images.githubusercontent.com/13211752/38480640-fd24fb94-3c09-11e8-9e71-c04847fc8ff7.png)

I noticed some errors when I try to do a scan fields  
04-09 15:24:27 ←[1mERROR sync.util←[0m :: Error syncing fields for Table 25008 '
tablename': ERROR: relation "pg_enum" does not exist
  Position: 32
("driver.postgres$enum_types.invokeStatic(postgres.clj:217)" 

I'm not sure that is the issue, anyway, to clarify GreenPlum does not have the table pg_enum

Thanks!

Best regards
Mark

**Comment by whitemark** [comment]
A bit more about the error om 0.28.5, please note that 0.26.2 works fine, just slow to sync because the db is big

04-09 21:44:29 ←[1mERROR sync.util←[0m :: Error syncing fields for Table 33671 '
pg_aoseg.pg_aovisimap_1066648': ERROR: relation "pg_enum" does not exist
  Position: 32
("driver.postgres$enum_types.invokeStatic(postgres.clj:217)"
 "driver.postgres$enum_types.invoke(postgres.clj:210)"
 "driver.postgres$describe_table.invokeStatic(postgres.clj:229)"
 "driver.postgres$describe_table.invoke(postgres.clj:223)"
 "driver$fn__25758$G__25590__25767.invoke(driver.clj:51)"
 "sync.fetch_metadata$fn__36311$table_metadata__36316$fn__36317.invoke(fetch_met
adata.clj:18)"
 "sync.fetch_metadata$fn__36311$table_metadata__36316.invoke(fetch_metadata.clj:
15)"
 "sync.sync_metadata.fields$fn__36872$db_metadata__36877$fn__36878.invoke(fields
.clj:294)"
 "sync.sync_metadata.fields$fn__36872$db_metadata__36877.invoke(fields.clj:290)"

 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909$fn__369
12$fn__36913.invoke(fields.clj:307)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909$fn__369
12.invoke(fields.clj:306)"
 "sync.sync_metadata.fields$fn__36900$sync_fields_for_table_BANG___36909.invoke(
fields.clj:301)"
 "sync.sync_metadata.fields$fn__36938$sync_fields_BANG___36943$fn__36944.invoke(
fields.clj:318)"
 "sync.sync_metadata.fields$fn__36938$sync_fields_BANG___36943.invoke(fields.clj
:314)"
 "sync.sync_metadata$fn__37507$sync_db_metadata_BANG___37512$fn__37513$fn__37514
.invoke(sync_metadata.clj:28)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:124)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:122)"
 "sync.util$do_with_error_handling.invoke(util.clj:119)"
 "driver$fn__25838.invokeStatic(driver.clj:235)"
 "driver$fn__25838.invoke(driver.clj:235)"
 "driver$fn__25773$G__25580__25782.invoke(driver.clj:51)"
 "sync.util$sync_in_context$fn__35025.invoke(util.clj:115)"
 "sync.util$with_db_logging_disabled$fn__35022.invoke(util.clj:106)"
 "sync.util$with_start_and_finish_logging$fn__35017.invoke(util.clj:92)"
 "sync.util$with_sync_events$fn__35014.invoke(util.clj:75)"
 "sync.util$with_duplicate_ops_prevented$fn__35005.invoke(util.clj:54)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:142)"
 "sync.util$do_sync_operation.invoke(util.clj:139)"
 "sync.sync_metadata$fn__37507$sync_db_metadata_BANG___37512$fn__37513.invoke(sy
nc_metadata.clj:23)"
 "sync.sync_metadata$fn__37507$sync_db_metadata_BANG___37512.invoke(sync_metadat
a.clj:20)"
 "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:36)")

**Comment by jornh** [comment]
> A bit more about the error om 0.28.5, please note that 0.26.2 works fine, just slow to sync because the db is big.

I think it’s very likely that the `pg_enum` query is the culprit here. It got introduced in version 0.28 with https://github.com/metabase/metabase/pull/6444 so I’d bet you can successfully go to v0.27.x but currently not further when you use the Postgres driver with Greenplum.

**Comment by mazameli** [comment]
Is this error still occurring for folks in the new query builders in 0.33+?

**Comment by vvaezian** [comment]
Not sure if this is related. 
I had a column named "product_description", which the "Update filter" button was greyed out for it:

![err1](https://user-images.githubusercontent.com/15974735/68433915-91a7a400-016c-11ea-9c7e-a8e5aac00a53.png)

Also the column name was not in the list of columns shown when pressing "filter" button at top right. I mean the following button:

![err2](https://user-images.githubusercontent.com/15974735/68433996-b7cd4400-016c-11ea-82f2-c3f22c0b2572.png)


I checked the data model. Metabase had automatically set that column's type to "description". When I changed the type to "No Special Type". The problem was fixed.

[v 0.33.3]

**Comment by jsonyin** [comment]
> Is this error still occurring for folks in the new query builders in 0.33+?
The same thing happened to me
Environment
metabase 0.33.4, JRE 8 ,  centos7, internal DB Mysql5.6, Datasource is GreenPlum 6.0

**Comment by flamber** [comment]
@jsonyin Are you still seeing this problem in latest release, 0.35.4?

Can you please post "Diagnostic Info" from Admin > Troubleshooting.
Manually run a sync+scan in Admin > Databases > (your-database) and then post any errors from the log (Admin > Troubleshooting > Logs) and browser developer console.

Please note that Metabase required MySQL 5.7.7+ for it's application database.
How are you connecting to GreenPlum? With a third-party driver or just the integrated Postgres?

@vvaezian There's an issue for that now - #11721

**Comment by flamber** [comment]
Closing, since a lot have changed. Please comment with "Diagnostic Info" and logs if you're still seeing this.
