### ISSUE TITLE
Pulse default with both csv and xls attachments

### ISSUE THREAD

**Issue by looric** [metabase/metabase#7302]
Metabase version v0.28.4 (1e06979 release-0.28.4)
tested with the latest Firefox and Chrome.

If I create a question with the following native query:

> select * from orders

then create pulse from the question, add attachments, I'll get both  csv and xls attachments from email.
2 Attachments is a trouble.

I just want only xlsx format attachment.  I can't select csv or xlsx from the front end.

**Comment by looric** [comment]
Metabase version v0.28.5 (fa5cb8a release-0.28.5)
tested, same result.

**Comment by mazameli** [comment]
@senior It looks like we're not automatically selecting `csv` when adding raw data questions to pulses. Should be an easy enough fix.

![screen shot 2018-04-10 at 3 03 05 pm](https://user-images.githubusercontent.com/2223916/38585873-524db4e6-3cd0-11e8-8d3b-63e0941894a1.png)

**Comment by looric** [comment]
it select csv and xls at the same time. better to select xlsx as default only.

**Comment by mazameli** [comment]
Trying to remember, @senior — did you have a fix for this going?

**Comment by senior** [comment]
@mazameli We talked about this, but I haven't worked on a fix for it

**Comment by looric** [comment]
waiting for fix.

**Comment by senior** [comment]
I have a fix for this in https://github.com/metabase/metabase/pull/8844. If nothing is selected it will default to CSV, same as before. If the user has selected XLS, it won't automatically include the CSV anymore, so you will just get the XLS attachment. The UI doesn't currently allow selecting both the CSV and the XLS, but the backend does support it if we want to add it sometime in the future.

**Comment by bennaang** [comment]
I still have the issue for #7302 when I add raw data question and choose only xls as attachment, the pulse email attached both of csv and xls but when I choose only csv format, only csv attached on the email. I need just xls format on pulse email

**Comment by looric** [comment]
tested, v0.31.2 fixed this issue. thanks.
