### ISSUE TITLE
Optional Locked Parameter for JWT Embedding

### ISSUE THREAD

**Issue by brunolopesr** [metabase/metabase#7306]
- Your browser and the version: Chrome 67.0.3390.0 canary
- Your operating system: OS X 10.13.4
- Your databases: MySQL
- Metabase version: 0.28.5
- Metabase hosting environment: CentOS 6.8
- Metabase internal database: MySQL

I am using Metabase to create reports of an application, which runs a MySQL database.

So I created a question with an optional parameter in a question, so if it is not null, it will filters the MySQL query, like the example below that show all users registered:

```mysql
SELECT * FROM users
WHERE TRUE
[[AND {{ user_id }}]]
[[AND {{ user_role }}]]
```

Where the user_id variable is of **Field Filter** type, linked to users.id field and the user_role variable if of **Field Filter** type, linked to users.role field.

As I want to embed the Metabase to the admin panel of the application, I set the parameters to **locked**, to hide them in the iframe, because I want to provide my own inputs.

But, I want it to starts empty, or a **null** value, as they are optional in the MySQL query and when I create the JSON Web Token, if I try passing null to the parameter in the payload, the iframe reports:

**You must specify a value for :user_id in the JWT.**

That's the way I am creating the token, using `firebase/php-jwt`:

```php
$payload = [
	'resource' => [
		'question' => 10,
	],
	'params' => [
		'user_id' => null,
		'user_role' => null,
	]
];

$token = JWT::encode($payload, $this->metabaseSecretKey);

$iframeUrl = 'http://'. $this->metabaseSiteUrl . '/embed/question/'. $token . '#bordered=true';
```

Passing all users IDs and roles as default value is impossible, as it throws a 414 Request-URI Too Large.

Am I doing something wrong? Optional variables cannot or should not be locked?

Thanks.

**Comment by salsakran** [comment]
"locked" means you must include a parameter, allowing nulls there would allow someone to bypass this requirement. 

I'd suggest creating two cards, one "global" and one "locked" to keep things sane.

**Comment by drorm** [comment]
We ran exactly into this problem. I don't think that allowing nulls would allow someone to bypass this since the it's part of the payload that's encrypted with the key.

**Comment by Bockit** [comment]
Would you be open to considering this again? We have a use case for optional parameters that we want to hide from the users. We have 4 different hidden optional parameters depending on UI state so duplicating dashboards isn't a feasible long term strategy for us. We would need many duplications for the different parameter states and if we add any more it becomes ridiculous.

I understand the idea that Locked is supposed to mean required, so is there room for a 4th `hidden` state? (`disabled`, `locked`, `editable`, `hidden`)

**Comment by dallerup** [comment]
for me, this is also a minimum requirement of embedding. I don't understand how it can be closed. The short version for us is that we just found out of this huge limitation and are now moving away from Metabase primarily do to the lack of hidden fields in embed.

**Comment by nitzien** [comment]
Can this be opened? We will need this as well.

**Comment by mazameli** [comment]
I don't believe we've documented this well, or perhaps at all, but a while ago [we did add a way to hide parameters via URL options](https://github.com/metabase/metabase/pull/9395). I'm gonna go create a PR to add this to the embedding documentation in a moment, but for now here are some examples:

E.x., this will set the id parameter to "1" and hide it in the UI:

```
/dashboard/42?id=1#hide_parameters=id
```

Multiple parameters can be specified by comma separating them, `#hide_parameters=slug1,slug2`:

```
/dashboard/42?id=1#hide_parameters=id,name
```

**Comment by PoeticPete** [comment]
@mazameli thanks for the workaround. That's helpful. Would it be possible to re-open this for discussion? Setting a filter parameter to null is a use case for us as well.

**Comment by samuelsabel** [comment]
IMO, there needs to be ability to preload filter, but still show filter box.  This is connected with these suggestions. Please reopen,

**Comment by nitzien** [comment]
@samuelsabel If you want to show filter box, then it is not locked. You can acheive this today with unlocked parameters. This is how url with pre-filled unlocked parameters will look.

`<metabase_base_url>/embed/dashboard/<signed_token>?unlocked_parameter1=val1&unlocked_parameter2=val2}#bordered=false&titled=true`

**Comment by samuelsabel** [comment]
> @samuelsabel If you want to show filter box, then it is not locked. You can acheive this today with unlocked parameters. This is how url with pre-filled unlocked parameters will look.
> 
> `<metabase_base_url>/embed/dashboard/<signed_token>?unlocked_parameter1=val1&unlocked_parameter2=val2}#bordered=false&titled=true`
 thanks you @nitzien, this is what I was looking for.

**Comment by karakanb** [comment]
this is still a problem, and here's a simplified use-case:
- we have two types of users: admin and a member
- we have a filter called "Team"
- we want admins to be able to filter all teams
- we want members to see data for only their teams

it is not possible to do this via URL parameters because that means the token is not scoped, so the users can just change the URL and get other filters. What we need in this case is to be able to filter a dashboard by locked filters, but also allow that lock to be bypassed with a special parameter for an embed so that the filter can be used if there was no value given.

As far as I know, this is not possible today, but maybe I am missing something, so I would be happy to be corrected.

**Comment by paoliniluis** [comment]
@karakanb please use the forum for questions :)

**Comment by karakanb** [comment]
hi @paoliniluis I was not asking a question actually, this is to reopen the issue because this is a feature request and it was closed. I can create a new issue if that's what you'd recommend, but my goal was to give an example of the problem so that the issue can be reopened.

**Comment by toedio** [comment]
@salsakran Could u repoen this? We having the same problem

**Comment by maximepvrt** [comment]
@flamber Could you reopen this ?

**Comment by flamber** [comment]
You can have optional Locked parameters by sending the value `[]` instead of `null` in the JWT payload - example:

Question:
```sql
select count(*) from some_table
where true
[[and {{locked_parameter}}]]
```
JWT payload:
```json
{
  "resource": {
    "question": 123
  },
  "params": {
    "locked_parameter": []
  }
}
```

Or setting the embedding parameter to Editable, while still including a value in the JWT payload, which will not show the filter widget:
```json
{
  "resource": {
    "question": 123
  },
  "params": {
    "locked_parameter": ["some value", "another value"]
  }
}
```

If you are looking for something more/different than this, then open a new feature request with clear description of use-case: https://github.com/metabase/metabase/issues/new/choose

**Comment by MirilTerolli** [comment]
Thank you @flamber ! That's helpful!
