### ISSUE TITLE
Can't change user's email to the email of a deleted (deactivated) user with the same email

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7312]
Howdy,

it seems you cannot change the email address of a user to an email address that has already been used by another user where the other user was subsequently deactivated/deleted. I'm aware that users are never really *deleted*, so it's likely a result of that user record being retained.

## Metabase
* Metabase version: 0.26.2
* Metabase hosting environment: Elastic Beanstalk
* Metabase internal database: Postgres

## Steps:
1. Create a user with with the email address example1@email.com (user 1)
2. Create a user with the email address example2@email.com (user 2)
3. Delete user 1.
4. Attempt to change user 2's email to example1@email.com.

## What happened:
* The edit profile dialog closes, no error is displayed, but the PUT request fails. Presumably this is a uniqueness constraint in effect.

## What should happen?
* At a minimum, an error message should be displayed explaining why the email address cannot be (re)used.
* Better still, allow the email address to be reused where a deactivated user has the same email address.

## Other info:
* Reactivating the deactivated user then becomes problematic. The email address cannot be reused if another user has come along and claimed it.
* Not sure how you would then reactivate the deactivated user, if using only email addresses, other than never allowing a deactivated user to be reactivated (as is the case when you sign up a user with an existing deactivated account - the user account belonging to that email is *reactivated*).

**Comment by camsaul** [comment]
This is fundamentally the same issue as #7337, which has already been resolved by #7481. Since users are archived rather than deleted the expectation is that you shouldn't be able to create a new user with the email address of an existing user, you'd have to reactivate the old one instead.
