### ISSUE TITLE
Numbers in pulse are not rendering after upgrading to 0.28.5

### ISSUE THREAD

**Issue by img22** [metabase/metabase#7317]
Numbers appear as `metabase.pulse.render.NumericWrapper` on pulse reports for existing questions

**Comment by senior** [comment]
This is a confirmed bug in 0.28.5 (https://github.com/metabase/metabase/issues/7210) and has been fixed https://github.com/metabase/metabase/pull/7074. The fix will be included in the 0.29.0 release which should be soon.
