### ISSUE TITLE
X axis values overlapping in dashboards/charts

### ISSUE THREAD

**Issue by alexezimm** [metabase/metabase#7318]
When row charts are decreased in size horizontally, numbers overlap with each other rather than the scale adjusting to fit the size of the chart:
![image](https://user-images.githubusercontent.com/36081808/38576775-18855424-3ccd-11e8-96eb-b410eba1f28a.png)

Your browser and the version: Chrome version 64.0.3282.186
Your operating system: Windows 10
Your databases: Postgres
Metabase version: 0.28.1
Metabase hosting environment: Heroku
Metabase internal database: Postgres
Repeatable steps to reproduce the issue: Create dashboard, add question in Row Chart format to dashboard, squeeze chart horizontally

**Comment by mazameli** [comment]
Thanks, @alexezimm. This has been fixed in master by https://github.com/metabase/metabase/pull/7103 and will be included in Metabase version 0.29.
