### ISSUE TITLE
Monitoring of user logged

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7320]
There is something that I can out at each dashboard to monitor the users use? Something like Google Analytics or Piwik/Matomo? Anywhere to put a tag/pixel.

**Comment by MarkRx** [comment]
Not sure if this is what you are asking but there is a view_log table in the configuration database that tracks usage. I don't know if there any APIs that expose this but the information is there in the database.

```
select * from view_log order by timestamp desc;
-- id, user_id, model, model_id, timestamp
2248	4	dashboard	5	2018-04-13 12:09:28.0
2247	4	dashboard	5	2018-04-13 12:09:21.0
2246	4	card	81	2018-04-13 12:01:47.0
2245	4	card	77	2018-04-13 12:01:34.0
2244	4	dashboard	4	2018-04-13 12:01:30.0
2243	4	dashboard	4	2018-04-13 12:01:24.0
2242	7	dashboard	17	2018-04-13 12:00:12.0
```

**Comment by dannyeuu** [comment]
@MarkRx Will be good to track embedded in other tools or public site. with pixels e.g. Snowplow, Google Analytics, Matomo.

**Comment by flamber** [comment]
Closing in favor of #5462, since there's Audit: https://www.metabase.com/docs/latest/enterprise-guide/audit.html
