### ISSUE TITLE
X Days Ago Time Filter

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#7336]
I may have missed a trick here, but I need to generate reports for `x days ago`, not after or before x days, but I need to look at exactly 4 days from today.

Without writing this as an SQL query, is this achievable?

**Comment by petar777** [comment]
I think you can only do it with an SQL query:

`SELECT *`
`FROM sampe_table`
`WHERE cast(sample_date as date) = cast(now()1 + interval '-5 days' as date)`

**Comment by jbrooksuk** [comment]
You can, but it feels like it should be something Metabase supports as part of the question builder.

**Comment by flamber** [comment]
Hi @jbrooksuk 
Sounds like you're looking for what is described in #4083 - go and upvote by clicking the :+1:

**Comment by jbrooksuk** [comment]
Done!

**Comment by mazameli** [comment]
Closing as duplicate of #4083
