### ISSUE TITLE
Metabase container out of memory [v0.28.5]

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#7350]
I'm aware of docjure issue causing out of memory. But recently, I often got "out of memory issue" without any download activity (check on metabase activity log). Below is the memory log of my metabase container v0.28.5:

```
2018-04-14 10:20:01 1.33GiB / 15.67GiB
2018-04-14 10:25:01 1.381GiB / 15.67GiB
2018-04-14 10:30:01 4.42GiB / 15.67GiB
4.42GiB / 15.67GiB
restart here
metabase
2018-04-14 10:35:01 845.8MiB / 15.67GiB
2018-04-14 10:40:01 916MiB / 15.67GiB
2018-04-14 10:45:01 2.608GiB / 15.67GiB
2018-04-14 10:50:01 2.679GiB / 15.67GiB
2018-04-14 10:55:01 2.879GiB / 15.67GiB
2018-04-14 11:00:01 3.038GiB / 15.67GiB
2018-04-14 11:05:01 3.098GiB / 15.67GiB
2018-04-14 11:10:01 3.345GiB / 15.67GiB
2018-04-14 11:15:01 3.426GiB / 15.67GiB
2018-04-14 11:20:01 3.426GiB / 15.67GiB
2018-04-14 11:25:01 3.426GiB / 15.67GiB
```
So there are 2 symptoms: the first one is a sudden jump from 1.38GB to 4.42GB, triggered the auto-reset cmd. The second one is a smaller jump from 916MB to 2.608GB but kept increasing memory to 4.xGB.

From the metabase activity log, I don't see any download during the 1st time range; while in the second time window, the download volume is very small.

I know these symptoms are vague to diagnose, but I list here so that if you have any idea/clue to trace and get more info on this issue, please guide me.

**Comment by senior** [comment]
There are many things that could potentially cause Metabase to run out of memory. Docjure is one, but even executing a query with a resultset that is too large to fit into memory will cause an out of memory error. The best thing to do is to get a heap dump when the out of memory error occurs and then examine the heap to figure out what's consuming so much memory. I have written up instructions on how to do that in the [Diagnosing memory issues causing OutOfMemoryErrors](https://metabase.com/docs/latest/troubleshooting-guide/running.html) section of the Troubleshooting guide.

I can help you diagnose the memory issue, but I will need a copy of the heap dump, which can be pretty big and not something you want to post publicly. If you want to email me after you have the heap dump, I can send you a non-public place to upload that heap and I can take a look. My email address is my first name at metabase.com.

**Comment by thucnc** [comment]
Thank you @senior for your advice. I will try your approach and get back to you then. I close this ticket here.
