### ISSUE TITLE
Notify about sensitive fields in database

### ISSUE THREAD

**Issue by ad-m** [metabase/metabase#7352]
### Feature requests and proposals

After scan new database I suggest add notification about hide sensitive fields eg. ```password```, ```pass```, ```email``` in data model. Such a notification could be displayed permanently until it closes notification manually or the field is hidden by the administrator.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Closing in favor of #1694
