### ISSUE TITLE
Use scan query by default for "Raw Data" queries

### ISSUE THREAD

**Issue by Digma** [metabase/metabase#7355]
Druid Select queries are quite expensive as they require a sort on the whole dataset. For that reason, making "Raw Data" query in metabase over large interval can be quite slow.

Druid developers are aware of this issue (see info message: http://druid.io/docs/latest/querying/select-query.html) and that is why since Druid 0.11, a new query "the scan query" (http://druid.io/docs/latest/querying/scan-query.html) has been moved to core Druid and is now officially part of the Druid API.  The scan query is much faster in cases when one want to return Druid rows in a streaming fashion with no time ordering

The difference between "Select" and "scan" query are the following:
* No time odering in "scan" query
* No pagination in "scan" query

In the SQL-like Druid API, this logic is implemented by the developers as described:

> Queries without aggregations will use Druid's Scan or Select native query types. Scan is used whenever possible, as it is generally higher performance and more efficient than Select. However, Select is used in one case: when the query includes an ORDER BY __time, since Scan does not have a sorting feature.
(http://druid.io/docs/latest/querying/sql.html)

In our case, we think than scan query should be the default one used by "Raw Data" unless the user explicitely select an ordering by the "time" dimension. 

Open questions to metabase/community:
* Do you think that the performance trade-off worth it (but losing default sort by time ordering in "Raw Data" unless explicitely specified)?
* The change was brought in Druid 0.11 so older version of Druid do not support it natively. Should the code be retro-compatible for older Druid versions?
* This logic is implemented in the Druid SQL driver already (which brings other developer friendly features: semi-join, HLL used automatically if they exist for a given field, ...), is there anyone working already on creating a SQL driver for Druid in Metabase (or that successfully did so already)?

**Comment by petit-pois** [comment]
Any update on this proposal ? Heavy select queries from Metabase is making our Druid ingestion tasks crash with OOM error

**Comment by kkalyan** [comment]
select query has been removed in Druid 0.17.0 this resulting in error page on metabase.

![image](https://user-images.githubusercontent.com/391567/75941296-1fa64980-5e44-11ea-9fcc-89e8475ec843.png)


java.lang.Exception: Cannot construct instance of `org.apache.druid.query.select.SelectQuery`, problem: The 'select' query has been removed, use 'scan' instead. See https://druid.apache.org/docs/latest/querying/select-query.html for more details. at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 32] Error class:

**Comment by sbelak** [comment]
Fixed via #11992
