### ISSUE TITLE
[Bug] Cannot see full Pulse email list

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#7362]
In Metabase 0.28.4 it's impossible to see the full distribution list of a Pulse.

![image](https://user-images.githubusercontent.com/246103/38868792-4a312a02-4240-11e8-98a7-44d33aa254a4.png)

This Pulse contains myself and two other people, but I cannot see them unless I remove myself (without saving).

**Comment by mazameli** [comment]
Closing as duplicate of https://github.com/metabase/metabase/issues/7043, which has been fixed in master.

**Comment by jbrooksuk** [comment]
Ah, thanks. I couldn't find anything that described this.

**Comment by mazameli** [comment]
No worries!
