### ISSUE TITLE
Dark theme in fullscreen shows white background

### ISSUE THREAD

**Issue by zhangdoudou** [metabase/metabase#7366]
### Bugs
Click on the full screen, select dark, the page will turn white and the background will be white

**Comment by tlrobinson** [comment]
I'm not able to reproduce this on `master`, though I did notice if you scroll down the background "below the fold" is white.

We might be able to use the `withBackground` higher order component to fix that.

**Comment by zhangdoudou** [comment]
browser:Google Chrome 65.0.3325.181
version:master

**Comment by zhangdoudou** [comment]
![image](https://user-images.githubusercontent.com/28778859/38969934-445c1fb6-43c5-11e8-9768-1f77dc28ddc1.png)

**Comment by kdoh** [comment]
Just looked into this again and I can't reproduce either situation mentioned here off our our latest version.
