### ISSUE TITLE
Custom Expression not working properly depending on column name

### ISSUE THREAD

**Issue by lucasloami** [metabase/metabase#7373]
Hi, 

I'm using Metabase v0.28.5 and I have a PostgreSQL database with a table X with a column called `sum_profit`. I'm trying to create a "Custom" question in which I use the option `Custom Expression` to calculate the value I should return in my query. This calculation is:

* `SUM(sum_profit * request_index)`

However I receive the following error message **Expected field name, number, or expression but found  'sum'** and I'm not able to save this expression. When I replace `sum_profit` with another Number column (such as `cost`), the calculation seems to be correctly performed. 

I noticed that this error appear whenever my column name starts with some SQL keyword, such as "count", "sum", "avg" and so on. Not sure if it's an expected behavior of Metabase, but to me it's really weird.

I also checked this behavior in the newest versions, v0.28.6 and v0.29.0-RC1

**Comment by senior** [comment]
@tlrobinson This looks to be a UI validation issue, not sure why but it looks like we're trying to parse the expression, maybe to fine the operation and getting confused with the column name. It's easy to recreate this if you disable humanization of column names.

**Comment by senior** [comment]
Looks like this might be related https://github.com/metabase/metabase/issues/7291

**Comment by flamber** [comment]
A workaround is the enclose the column in quotes, which allows you the leave the field without the error message, but the field still has a red border and the field content is auto-corrected. If you focus the field again, then you get the error message and have to redo it again. Tested on 0.31.2
```
sum("123number"*"sum_test")
```
- After inputting expression, but before leaving (blur/unfocus) the field:
![screenshot_00000](https://user-images.githubusercontent.com/1447303/53061634-cf9c5500-3483-11e9-9fb2-7f18a8c2ab59.png)
- After leaving the field to input name:
![screenshot_00001](https://user-images.githubusercontent.com/1447303/53061672-ec388d00-3483-11e9-9c74-744e12cc82b5.png)

**Comment by flamber** [comment]
Fixed by #11868.
