### ISSUE TITLE
Idea to fix a problem with chart labels

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7379]
When we plot data in charts we sometimes stumble upon the following problem:

If the labels of the x axis values are long - they will stack up on each other like below.

![problem1](https://user-images.githubusercontent.com/16069308/38987801-b3451806-43d9-11e8-8e3e-2450731ec906.png)

In Microsoft Excel this problem is avoided in a very simple way - just by tilting the names to one side:

![2](https://user-images.githubusercontent.com/16069308/38987846-dcffb5fc-43d9-11e8-8d29-0886d1286628.png)

Maybe think of implementing something like this in some of your future updates. :)

**Comment by lucasloami** [comment]
@petar777  #7103 already implemented this idea. I believe this feature will come with v0.29.0 =)

**Comment by petar777** [comment]
@lucasloami Thats awesome, thank you!

**Comment by mazameli** [comment]
Yep, this issue has been fixed in master and is included in version 0.29. There's a [release candidate](https://github.com/metabase/metabase/releases/tag/v0.29.0-RC1) that you can test out if you're so inclined, too.
