### ISSUE TITLE
Not Empty/Is Empty for dates return error

### ISSUE THREAD

**Issue by jakobholmelund** [metabase/metabase#7381]
This was working back in 0.28.1 and broke when i updated to 0.28.5 and is still broken in 0.29 RC

I use PostgreSQL and i'm trying to query a view created with Native Query

the error i get is

(not (instance? java.sql.Timestamp nil))

It seems to still work in other places, so i might have run into an edge case :/ If anyone could through a hint from the Closure error it would be nice.

**Comment by senior** [comment]
@jakobholmelund I would like to try and reproduce this. Can you give the steps needed along with the query/queries you're using?

**Comment by senior** [comment]
@jakobholmelund nevermind, I was able to reproduce it. I'll put together a fix tomorrow. Thanks for reporting the issue!

**Comment by jakobholmelund** [comment]
Sorry for the late reply and PROPS for fixing it so fast
