### ISSUE TITLE
Fix the Pulse/Alert/Notification confusion

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7383]
When we added Alerts we added them as a new type of Pulse. Now there are two types of "Pulses": traditional, timed "Pulses", and condition-triggered "Alerts"; a new term, "Notifications", is used in some places in the codebase to refer to either type of Pulse collectively. However this term is only used in a handful of places, leading to extremely confusing codepaths, for example

`create-alert!` calls `create-notification!` which calls `create-pulse-cards!`. Furthermore the renamed "notification" functions still use "pulse" as function parameters.

There's not really a lot of documentation explaining the terminology used here. I've been working on adding some in #7358 and cleaning some stuff up there while I work on other stuff. But we need to actually go in and make everything consistent, and probably even go as far as changing the word `Pulse` to `Notification` in the DB call code

**Comment by dannyeuu** [comment]
@camsaul This was merged into some other milestone?
