### ISSUE TITLE
When updating anything in a Pulse [Notification] it always deletes/recreates all PulseCards

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7384]
When updating a Pulse [Notification], the code originally checked the sequence of Cards IDs passed in and compared them to the sequence of CardIDs for that Pulse [Notifcation] in the DB, and if the sequence changed, it would toss all the existing PulseCards and save the new sequence. In #6556 when we added the option to have Pulses [Notifications] return XLS/CSV as well; we switched over most of the code to work with sequences of maps like 

```clj
{:card_id <id>, :include_csv <bool>, :include_xls <bool>}
```

instead of sequences of Card IDs. However there seem to be a handful of places we missed, such as https://github.com/metabase/metabase/blob/master/src/metabase/models/pulse.clj#L309. This code checks that a sequence of maps like the above is equal to a map of Card IDs, which will never be true.

I will attempt to fix some of these things in #7358

**Comment by tsmacdonald** [comment]
AFAICT this has been fixed (the [specific issue linked to](https://github.com/metabase/metabase/blob/f3631c4920969f931bc7a93c11711d46b60e7fb8/src/metabase/models/pulse.clj#L309) isn't a problem any more) but I'll keep my eyes open as I continue to spend time in the code.
