### ISSUE TITLE
Multiple date filters fail on Google Analytics

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7387]
Reproduction 
- Create a dashboard with a GA based card
- Add a dashboard date filter
- Filter down the dashboard to eg past 12 months
- click on "View these X" drill-through action 
![screen shot 2018-04-19 at 8 30 23 pm](https://user-images.githubusercontent.com/107439/39029420-91966520-4410-11e8-8f45-fade99249a71.png)

- See the error

**Comment by camsaul** [comment]
Partially fixed by #9904. Not yet 100% fixed AFAIK

**Comment by flamber** [comment]
Closing in favor of #4766
