### ISSUE TITLE
Can't create a collection with the same name even if previous collection was archived

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#7397]
I'm not sure it makes sense to have a unique constraint on the collection name.

**Comment by flamber** [comment]
Hi @tlrobinson 
I cannot reproduce this problem in 0.31.2 - I can even create multiple active collections with same name.

**Comment by tlrobinson** [comment]
Yes I think we stopped using slugs in the collection URLs so there's no longer a uniqueness constraint.
