### ISSUE TITLE
GA dimensions not allowed in this [GA] version

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#7400]
A list of dimensions that return:
```
Dimension(s): [this] are not allowed in this API version.
For details see https://developers.google.com/analytics/devguides/reporting/core/dimsmets
```
ga:acquisitionSource
ga:acquisitionSourceMedium
ga:acquisitionTrafficChannel
ga:acquisitionMedium
ga:acquisitionCampaign
ga:cohort

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by menjp26** [comment]
yes, I found this problem too, I am using rga package to extract ga data, but I failed on this dimention

**Comment by floriankapaun** [comment]
Did you find any solution to this problem?

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
