### ISSUE TITLE
Adding "not" variants for starts with and end with filters

### ISSUE THREAD

**Issue by mmollick** [metabase/metabase#7402]
I just started using Metabase, and it's been working great. However, I do have a couple of cases where it'd be nice to have "Does not start with" and "Does not end with" options for filtering strings. The latter would be particularly useful for filtering out specific domains in email addresses when querying a users/customers table.

I've never worked with Clojure before so I thought I'd give implementing these two additional filters a shot, which was pretty painless. The only drawback I see is that the list of available filters for strings ends up producing a scrollbar with two options out of view.
![screen shot 2018-04-21 at 7 29 40 pm](https://user-images.githubusercontent.com/2349344/39089635-67d4fb58-459a-11e8-9666-c178934b2402.png)

Let me know if I should send a PR or if some UI tweaks are needed.

**Comment by EBoisseauSierra** [comment]
For future reference, #11397 was very similar, but suggested to add a "reverse filter" checkbox (i.e. something similar to adding a NOT gate) in all types of filters, rather that keep expanding the list.

**Comment by sbelak** [comment]
You can achieve this by using `NOT` in a `Custom expression` for the filter.
