### ISSUE TITLE
Row charts - too big digits for x axis

### ISSUE THREAD

**Issue by pfranck** [metabase/metabase#7403]
I spotted a little bug in the axis x of the rendering row charts. If the figure are to big and the graph to small the numers are not print correctly 
![image](https://user-images.githubusercontent.com/28459801/39096408-ec782ad2-464f-11e8-84f0-071076e3c706.png)

Can we correct the bug (maybe complicated to know the size of the digits...) or add the possibility to remove the axis?

If you need more information let me know

**Comment by jornh** [comment]
What version of Metabase do you see this in? There are changes for this in the upcoming 0.29 (with column charts at least - unsure if it covers row charts as well)

**Comment by pfranck** [comment]
I'm on Metabase : 0.28.5

**Comment by EvaSchreyer** [comment]
to add to this issue this behaviour (I use v0.28.1) appears in chrome as well as in firefox, so does not seem to be a browser visualisation issue.

**Comment by lucasloami** [comment]
A possible temporary solution would be format your X axis values in your question. What do your think?

**Comment by mazameli** [comment]
Thanks all. This is fixed in master and 0.29.

![x-axis](https://user-images.githubusercontent.com/2223916/39141692-56ab44ec-46dd-11e8-9506-8eb61b80cf30.gif)

**Comment by qin4zhang** [comment]
how about Bar? It's also the same question.

**Comment by mazameli** [comment]
Yep, all x-axis will behave this way in 0.29.
