### ISSUE TITLE
Request: Support literals when defining a custom field formula

### ISSUE THREAD

**Issue by alvaroc1** [metabase/metabase#7411]
I should be able to use a formula like: `= 20` or `= total * .2`, etc

Currently it just disables the [Done] button for the first (no indication of what is wrong) and it adds a red outline on the field for the second.

Also it would be nice to have boolean expressions: 
`= "requests" < "transactions"` where it would show a check mark or an "x".

**Comment by flamber** [comment]
Hi @alvaroc1 
It seems like the field requires you to at least one operator.
These works for me on version 0.31.2: `= 20 + 0` and `= ColumnName * 0.2`

As for having a Custom Field returning a boolean value, I can see the use-case. Not sure if this would be too advanced to handle in GUI, but it would be fairly easy to do in SQL.

**Comment by dannydulai** [comment]
I'd like to be able to write any sql in here... CASE statements for example

**Comment by flamber** [comment]
@dannydulai It sounds like you're looking for #6331 - go and upvote by clicking :+1:

**Comment by flamber** [comment]
Since 0.35.0, it is now possible to use a lot of expressions - including comparing columns:
https://www.metabase.com/docs/latest/users-guide/expressions.html
