### ISSUE TITLE
Support time in date parameters

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7418]
Hello,

When I create a custom question I am capable of setting not only the date but the time in my date filter too. To be more precise- I choose the date column which I want to use. Then select "Between" from the drop-down menu where the user chooses the options of the date filter. Once there, I can set the date but beneath of the date, I can see an "Add Time" option. This feature works perfectly and is very useful...

However, if I want to create a more complex query and add a date variable or field filter, which I will later on control via the dashboard filter- I am not able to see the "Add Time" option no matter what I select from the drop-down menu. 

Is it possible to manually select time from a dashboard filter or SQL field filter?

All the best :) 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
Thanks for pointing this out, @petar777. The "All Options" Date filter widget on dashboards should be exactly the same as the graphical query builder date filter, but it isn't:

![screen shot 2018-04-24 at 10 03 32 am](https://user-images.githubusercontent.com/2223916/39202512-f8557000-47a6-11e8-8114-6938ea08c797.png)

![screen shot 2018-04-24 at 10 03 47 am](https://user-images.githubusercontent.com/2223916/39202519-fe1a670c-47a6-11e8-821e-e37ee03e7a7e.png)

**Comment by tlrobinson** [comment]
This is primarily because we haven't come up with a way to serialize times in the query string. Ideally we'd only use "url safe" characters, i.e. `a-zA-Z0-9._~-`. Currently we use `2018-01-01` for dates, `2018-01-01~2018-02-01` for date ranges, etc.

Maybe something like `2018-01-1_1200` (noon, for example)

**Comment by jalada** [comment]
> This is primarily because we haven't come up with a way to serialize times in the query string. Ideally we'd only use "url safe" characters, i.e. `a-zA-Z0-9._~-`. Currently we use `2018-01-01` for dates, `2018-01-01~2018-02-01` for date ranges, etc.
> 
> Maybe something like `2018-01-1_1200` (noon, for example)

Genuine question, I'm probably missing some context; isn't that what percent encoding is for?

**Comment by ChristineChetty11** [comment]
Is this feature coming still, has someone come up with a solution?

**Comment by simon3p** [comment]
I would love to make a filter to select all lines if the DATETIME match AM or PM. If anyone have a convenient workaround I'll take it.

**Comment by cwilby** [comment]
A common approach I've seen is to base64 encode the parameters.  Then you can use whatever transport format you like.

**Comment by jdmaresco** [comment]
Is this still under consideration? Would really like a time option in filters.

**Comment by mngr** [comment]
This works at least in the last versions
