### ISSUE TITLE
file:// URLs should be clickable to follow

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#7419]
When presenting a table with a URL, if the URL starts with http:// , Metabase knows to make it clickable and open the URL. However if the URL starts with file:// then clicking it does not follow the link. We could use file:// in the enterprise and I think metabase should make file:// URLs also clickable.

**Comment by flamber** [comment]
Hi @eladeyal-intel 
There are quite a few security implications surrounding `file:///` and every modern browser doesn't allow clicks to `file:///` from a page hosted on `http(s)://`. I think IE might be the only one, where you can lower the security level to allow it.
https://stackoverflow.com/questions/2087894/can-google-chrome-open-local-links
