### ISSUE TITLE
General operator selector is lighter than Date operator selector

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7429]
I looked at both `DateOperatorSelector.jsx` and `OperatorSelector.jsx` as well as `SelectButton.jsx` but I couldn't figure out why OperatorSelector isn't correctly rendering the darker text when it `hasValue`. I'd like it to be the darker text so that it's consistent and so that it's easier to see.

![lighter](https://user-images.githubusercontent.com/2223916/39215576-3c224832-47cd-11e8-88d2-1606fd99feb8.png)

![darker](https://user-images.githubusercontent.com/2223916/39215579-3e5cdb9e-47cd-11e8-863e-034020f4a1d6.png)

**Comment by flamber** [comment]
Hi @mazameli 
It looks like `.text-medium` is overruling the color and I fixed it by moving it to the child, which doesn't seem to have any negative impact. Maybe once I'm done :walking_man: through all the open issues, I can start doing smaller PR like this - just need to learn Git, React, JSX, ... - should be easy, right :rofl:
https://github.com/metabase/metabase/blob/28c1687ed7b504d78a866912e1cd3399cdfc0c24/frontend/src/metabase/query_builder/components/filters/FilterPopover.jsx#L344-L346
Should be:
```JSX
            <div className="FilterPopover-header border-bottom p1 flex align-center">
              {showFieldPicker && (
                <div className="flex text-medium py1">
```
