### ISSUE TITLE
Unable to view table from custom query

### ISSUE THREAD

**Issue by i2cute** [metabase/metabase#7436]
- Your browser and the version: Opera 52.0.2871.64
- Your operating system: Windows 10
- Your databases: Postgres 10
- Metabase version: Metabase 0.28.6
- Metabase hosting environment: Linux Redhat
- Metabase internal database: Postgres 10

- *Repeatable steps to reproduce the issue*
1. Removed database and added again. Result still same
2. Test with different user ID which is read_only in DB and super user in DB. Result still same
3. Able to query by using native query but unable to select / display tables from schema. There are no respond after click / select on the schema
4. Same setup in another server with version 0.27.2 and have no issue 

![image](https://user-images.githubusercontent.com/38716433/39232210-19c4a712-489f-11e8-9a60-ba3d834c81d7.png)

**Comment by i2cute** [comment]
Suddenly my metabase able to view table a view. After go into Admin Panel and come back then cannot already. Please refer to below log

![image](https://user-images.githubusercontent.com/38716433/39295404-edf2ea72-4970-11e8-99d8-55ae4b49c20e.png)

**Comment by i2cute** [comment]
Issue resolved after downgrade to 0.27.2

**Comment by salsakran** [comment]
this sounds like a situation where the metadata for the database on the client isn't in a coherent state.

does the problem remain if you do a hard refresh of the browser?

**Comment by i2cute** [comment]
Yes... I still having the same problem... But after downgrade to 0.27 it
working perfectly. Let me know after resolved, would like to upgrade back..
thanks so much

**Comment by flamber** [comment]
Closing, since there hasn't been other reports. This was likely fixed in version 0.29.0
#7303 is the only other issue with that warning log:
`Specifying :rows as the aggregation type is deprecated in MBQL '98. This is the default behavior, so you don't need to specify it.`
