### ISSUE TITLE
Cannot Use Chinese?

### ISSUE THREAD

**Issue by totogo** [metabase/metabase#7438]
I am trying to input Chinese as title of Dashboard, Questions or etc. But after it's saved, it shows me some question mark. ```???```

Multilingual are not supported yet?

Here is the database I'm using for Metabase:
* MySQL 5.7.17
* Default collation: utf8_unicode_ci

I also tried to update the Dashboard's title directly in MySQL with Chinese, then it can show Chinese correctly in Metabase interface. But if I change it again in Metabase interface, I still get ```???```.  I feel when Metabase interface send the characters to MySQL, it does not use UTF8?

**Comment by jornh** [comment]
Which database are you using as Metabase application database?

Please fill in the issue template given with your configuration.

It could maybe be the configuration of your database as e.g. this suggests for Mysql: https://forums.mysql.com/read.php?132,578240,579233

**Comment by totogo** [comment]
@jornh I have updated my description of the issue.  I think the database can accept Chinese characters, but somehow when Metabase writes it to MySQL it does not use UTF8?

**Comment by jornh** [comment]
Good so far. To further isolate the issue it would be good to know if it’s a frontend or backend problem. Try posting through the API documented in the wiki here on the GitHub project.

**Comment by salsakran** [comment]
not technically i18n related, but this should be sorted out as we get our internationalization story down

**Comment by totogo** [comment]
Thanks @jornh! I have the same test result, it is OK without using MySQL. 
I'm now trying to figure out what is the proper MySQL configuration.

**Comment by totogo** [comment]
It is OK now. As @jornh you expected, it's simply DB configuration issue. 
I was using the default value of MySQL in AWS RDS, some of them were ```latin1```. Now I updated all of them to ```utf8mb4```

Name | Values
-- | --
character_set_server | utf8mb4
character_set_results | utf8mb4
character_set_filesystem | utf8mb4
character_set_database | utf8mb4
character_set_connection | utf8mb4
character_set_client | utf8mb4

**Comment by jornh** [comment]
Great @totogo! Guess you can close this as not being an issue with Metabase then. It’s still here to search for as a resolved issue if others stumble into it again.

**Comment by lynnfi** [comment]
@totogo Hi,I have some quetions,when I change mysql from latin1 to utf8mb4.
When I run the metabase.jar, some error like below:
`com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes`
Do you meet this problem，or have any idea for this.
Thanks。
Metabase version:0.29.3
mysql version:5.6.38

**Comment by totogo** [comment]
@lynnfi Sorry for the late feedback.
I am running metabase with Docker container. I never had this problem. Do you see this issue with a fresh new database, or you got this issue after you converted existing DB to utf8?

**Comment by totogo** [comment]
I will close this issue. Thanks for the help!
