### ISSUE TITLE
Proposal: permission for assigned tables to write raw queries

### ISSUE THREAD

**Issue by qin4zhang** [metabase/metabase#7439]
In admin panel, I grant data access to the user group, when I choose Limit access, then **some tables** should be chosed.When I grant SQL QUERIES , if I choose Write raw queries , it's showed below:
>  This will also change this group's data access to Unrestricted for this.

I just want to grant some tables to user group to write raw queries, not all tables.So how could I do it ?
Best wishes!

**Comment by salsakran** [comment]
We don't offer the ability to do that, nor will we in the near future. It's sort of on our roadmap, but dealing with parsing SQL for tablenames in the face of an adversarial user is probably not going to get good enough for us to promote it as a way to limit access.

I'd suggest using database level permissions for that and creating database users and metabase Database connections for each level of security you need (eg, a different DB for "normal users" without read permissions to sensitive tables and a  different db connection for admins).

**Comment by qin4zhang** [comment]
Thanks a lot.
