### ISSUE TITLE
Change Feed on nodejs

### ISSUE THREAD

**Issue by tschnoelzer** [metabase/metabase#7440]
Hi team,

is there a way to use change feed in a nodejs environment? 
We need a nodejs BOT subscribing to change events in a cosmosDB with mongoDB Api.

best
Timo

**Comment by jornh** [comment]
By “change feed” are you referring to the feed of events displayed in the web user interface of Metabase or something else?

**Comment by salsakran** [comment]
Not sure why you're asking for that in this repo, but we're a clojure BI application, not a framework to create bots.

It is firmly outside of scope for the project to expose raw database  changelogs to clients
