### ISSUE TITLE
We shouldn't re-format Entity or Foreign Key fields (IDs)

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7447]
Got a report from a user of a situation where they have unique numeric entity keys (IDs) for each row in a table, e.g. 7483721. The problem is that Metabase is adding commas to this field when it's shown in query results, even though the metadata type is set to Entity Key, presumably because the underlying ID field is stored as an integer.

Seems to me that if any field is marked in the data model as being an ID, we shouldn't touch the way it's present at all.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by restyler** [comment]
Even if I set "100000.00" separator style in admin/settings/formatting for numbers, I still get the same issue - user id is rendered as "100,233" which makes it difficult to work with.

**Comment by flamber** [comment]
I cannot reproduce on latest release 0.39.4. Think it was fixed around 0.36. Please comment with steps-to-reproduce and "Diagnostic Info" from Admin > Troubleshooting, if you are still seeing this issue.
