### ISSUE TITLE
New visualization type: Progress Bar

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#745]
Basically a replacement for simple "scalar" display, where the user can set a maximum number, and the scalar value is displayed as a progress bar towards that max.

Could be great for live dashboards, especially quotas).

**Comment by rNianios** [comment]
Thanks @salsakran for referencing my request. +1 vote for a gauge or progress bar chart!

**Comment by underyx** [comment]
Does this also include Slack pulses? This chart type would be awesome for our daily report on progress towards our company goals.

**Comment by mariosergioti** [comment]
+1 vote for a gauge or progress bar chart!

**Comment by edmarriner** [comment]
+1

**Comment by thilokonzok** [comment]
+1

**Comment by cagiraudo** [comment]
+1

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0
