### ISSUE TITLE
We should fingerprint and classify cols in :result_metadata

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#7453]
This would enable us to treat nested questions much more equally. Concrete use-case are xrays where we use both fingerprints and inferred types heavily. Since fingerprinting needs result values this is something that should probably done as we return the result.

**Comment by senior** [comment]
@sb Is extracting a fingerprint from the results (i.e. scanning the results to compute a new fingerprint) valuable enough to be worth the cost vs. just including the fingerprint from the original column?

**Comment by sbelak** [comment]
Good question. Probably not, just flowing values through should suffice for now. But what about native queries? There the mapping to db columns is not that clear?

**Comment by senior** [comment]
We would not have mappings for the columns on native queries to flow through. If we needed that we'd have to compute it. I don't know that it would be a performance problem with the algorithm as-is, but I'd be suspicious. With today's code, I'd have to make at least one pass over every row, for every column (n x m), maybe more. I think in order to do that efficiently, it would need to be more flexible. Something more along the lines of a transducer/reducer i.e. `#(max previous-max %)` vs. `(apply max all-the-things)`

**Comment by sbelak** [comment]
Can we do it just for the native questions that are used as sources for other cards?

The biggest pain point is not having types and cardinalities for category field. While both use field values, it does somewhat cheapen the calculation (especially if we use something like hyperloglog).

**Comment by sbelak** [comment]
Also this feels like something that could be done async with the main code path as the results will never be needed for the originating query/question.

**Comment by senior** [comment]
Async could work, but I'd like to avoid it if possible. Returning query results already consumes too much memory. Having a process around holding onto that memory even after the results have been returned is asking for problems in my opinion. With a good algorithm (one that reduces row by row vs. the entire resultset) would help, but I'd still want to build in back pressure an other things to avoid the computation causing runtime issues. We could avoid all of that entirely if we had a fast way to compute what we want.

Certainly narrowing what we have to compute (maybe native only, maybe just category etc) would greatly improve that.

**Comment by sbelak** [comment]
Implemented in #8037
