### ISSUE TITLE
Can't remove sort from table output Question

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7457]
When ordering is applied to a Question's table output (i.e. sorting a Count column), that ordering can never be removed. It can be changed from DESC to ASC, and vice-versa, but it can never be removed.
This causes problems when you need to remove it (for work-arounds - see #7456)

- Your databases: MSSQL
- Metabase version: 0.28.5

**Comment by flamber** [comment]
Hi @hagen 
When using the table columns, you can make simple sorting, but if you want to remove the sorting or do multi-sort, then you have to use `...` (Additional Options) - located all the way to the right:
![image](https://user-images.githubusercontent.com/1447303/53066027-abe10b00-3493-11e9-9298-dea830df9d41.png)

**Comment by mazameli** [comment]
The Custom notebook editor now lets you explicitly remove sort steps that are added when using column heading sorts. Closing this as fixed.

![image](https://user-images.githubusercontent.com/2223916/66614222-0347fe80-eb7d-11e9-8c04-3ae64b33e720.png)
