### ISSUE TITLE
Status bar in Metabase

### ISSUE THREAD

**Issue by ebressert** [metabase/metabase#7458]
Feature Request: It would be great to have a status bar in Metabase. In my case - it would be helpful to show data freshness and ETL status at the bottom of the Metabase view for end consumers.

**Comment by kdoh** [comment]
I'm going to go ahead and say at least at this point in time the specifics of the request here are outside of our current product vision. Indications of data "freshness" as an overall area of exploration is definitely interesting and I'd be down to explore that with a little more information on use cases but until we hear more I'm going to close this. If we get to a point where there's something tangible we can re-open.
