### ISSUE TITLE
Question about permissions per user groups

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#7461]
Is it possible to assemble the user permissions in such way so that you can create a group of users that can only VIEW dashboards and created questions?

I don't want to allow them to create questions or view the SQL code behind them. All I want is to simply allow those users to look at the already created dashboards and export some of the questions if needed.

A partial solution to avoid doing this is to share the dashboards via public links but if I share a dashboard it is not possible to export different questions. (Sharing each question separately is not a solution either because I would need 100+ links.)

**Comment by salsakran** [comment]
Not yet. 

This will be possible in 0.30 described in #7515

Closing this since it's effectively a dupe of that new tracking issue.
