### ISSUE TITLE
Custom Mapping is not available on Mongodb collections' fields

### ISSUE THREAD

**Issue by istvano** [metabase/metabase#7462]
Metabase version: 0.28.6
Metabase hosting environment: Linux
Metabase internal database: MySql

Steps to reproduce:
Add a Mongodb Collection
Go to Table Edior
Pick a field that has numeric values. 
Select a field as Number
Scroll Down to Display values
The option "Custom mapping" never appears for Views, but in MySQL Tables they appear.

This issue is related to #6065

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
We're doing this under the hood as a join in many cases, so it was shipped without mongo support.

**Comment by istvano** [comment]
Hi,
thanks for replying. Since it is not possible to join SQL tables with a MongoDb collection. It would be fantastic to have this to be able to show lookup values. 

What does this need? Is it difficult to add? Can you give me some pointers?

**Comment by istvano** [comment]
Hi
This would be a great addition and I am happy to implement it. Can someone point me to the right direction to the package or classes this could be done in ?

**Comment by istvano** [comment]
> We're doing this under the hood as a join in many cases, so it was shipped without mongo support.

Hi
This would be a great addition and I am happy to implement it. Can someone point me to the right direction to the package or classes this could be done in ?

**Comment by flamber** [comment]
Not sure when remapping was added, perhaps very recently, but this is 0.41.1 with MongoDB remapped Ratings column, but the same restrictions apply as for other database - currently only integer columns can be remapped.
![image](https://user-images.githubusercontent.com/1447303/141195493-7cd4a6df-412d-48fb-9ac9-1ebd75c49232.png)
