### ISSUE TITLE
Global search should search across all entity types by their names

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7473]
This is the first step for global search.

This includes:
- Collections
- Dashboards
- Pulses
- Saved questions
- Metrics
- Segments

**Comment by ahoman** [comment]
Great to see this!  Will this step also include descriptions of entities (specifically saved questions) or do you see that as a separate item?

**Comment by mazameli** [comment]
@ahoman Right now we're breaking things down pretty granularly, but we definitely foresee Search looking through descriptions and other metadata in entities in a subsequent step.

**Comment by mazameli** [comment]
Mockups:

**Starting a new search**
Recent searches for each user would be nice to have, but not a strict requirement for the very initial cut of this.

![search_new](https://user-images.githubusercontent.com/2223916/40384874-b24ae2d8-5db9-11e8-91e9-f6b67e85ec63.png)

**Typed in my search term**
In future phases down the road we'll want to put typeahead suggestions in the fly out panel below the search bar, but that's not expected yet.

When I hit enter/return, my search is performed.

![search_term_typed](https://user-images.githubusercontent.com/2223916/40384969-ff1d8af2-5db9-11e8-8c18-c8314e4055d4.png)

**Search results**
A list of entities whose **titles** match my search term somewhere in their title. The ordering the results in this mockup is extremely likely to change, i.e. we might want to put dashboards first, then collections, then tables or something, and might want to also weight results based on whether the user has favorited them, or if they've been pinned in their collection.

Notice there's also a filter dropdown to filter for now on the type of the entities:

![search_results](https://user-images.githubusercontent.com/2223916/40385065-4ba5a47c-5dba-11e8-873e-018102cef74d.png)

**Comment by mazameli** [comment]
Implemented for everything but metrics and segments.
