### ISSUE TITLE
In Collections 2.0, I should be able to bulk move/archive items

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7474]
Ability to select/check multiple questions, dashboards, pulses, or collections and click on a Move or Archive action to move/archive them all at once.

**Comment by mazameli** [comment]
Implemented in master, though I'll call out it isn't implemented for pinned items or collections.

**Comment by MarkRx** [comment]
How exactly is this done? I can't seem to find the way to do it.

**Comment by mazameli** [comment]
A GIF is worth a thousand words. Maybe we need to make this feature more obvious.

![bulk-move](https://user-images.githubusercontent.com/2223916/46684718-84ef0000-cba8-11e8-83a7-87bb3902d7d5.gif)

**Comment by MarkRx** [comment]
Ah there it is. Yes I agree it could use some tuning. I would have never guessed that I could click on the icon to multi-select.

**Comment by Sire** [comment]
@mazameli Great feature, but I agree you should really considering making the checkbox more visible. Users can't expect to hover over all icons to see if they have more functionality, this doesn't feel like a common UI concept.

I did not think this feature existed at all, and would not have found it unless I searched Github.

**Comment by suzetteclr** [comment]
Wow. This needs to be way less secret.
