### ISSUE TITLE
Multiple instances send multiple pulse emails

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#7488]
I have metbase installed in docker in enterprise environment. In the interest of performance I scaled it up so I have three identical deployments of metabase (both using same postgres database) and users visiting the metabse URL get directed to one of them via  a load balancer.

It seems that in this setup, each instance sends the pulse e-mails seperately so since I have 3 instances, users got 3 copies of the same e-mail.

I think this should be resolved so that even if there are multiple isntances only one e-mail will be sent.

**Comment by salsakran** [comment]
dupe/has a root cause in #2754 

As of now, we strongly suggest you scale up or tweak the threadpool settings for performance. We're expecting to run as a single server.
