### ISSUE TITLE
In the new Collections 2.0 UI, I should be able to set permissions on a collection

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7493]
Even if it's just the same lock icon for now, that's fine. Eventually we'll want to implement the spec for entity pages #6170.  

![missing-permissions-butotn](https://user-images.githubusercontent.com/2223916/39443457-8de2a478-4c69-11e8-9878-89d5b58f6d08.png)

**Comment by camsaul** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/1455846/39442242-68db6d4e-4c65-11e8-9e07-dd71936032f8.png)

**Comment by mazameli** [comment]
Hah, yeah, I'm getting granular with the project, and what's going on is that currently the UI doesn't have a button to open up that modal.

**Comment by mazameli** [comment]
As we just discussed IRL, you're going to see a number of issues that are about the new "Spaces" UI (i.e. redesign to collections and general navigation) which are just here to help us keep track of the features and UI that we need to make sure we're carrying over from the existing Metabase layout.

I've updated the description to show you what I'm talking about.

**Comment by mazameli** [comment]
Fixed
