### ISSUE TITLE
Date columns formatted as timestamp

### ISSUE THREAD

**Issue by jens-plause** [metabase/metabase#7494]
When using native SQL queries or using custom queries on existing tables, it appears that metabase displays columns of datatype `date` as `timestamp` instead. 

E.g. when running this query in Postgres or H2 
```
SELECT cast('2018-05-01T00:00:00Z'::timestamp as date) 
```

the output that I'm getting in a metabase table is 

```
date
Tuesday, May 1, 2018 12:00 AM
```

The expected result would be 

```
date
Tuesday, May 1, 2018
```
or this (the output I get when running this using an sql shell such as pgAdmin)
```
date
2018-05-01
```

The timestamp output is shown regardless of if I query a table with a date column or cast a timestamp column to date in the SELECT statement. Is there a way of getting metabase to display the correct formatting?

- Your browser and the version: reproduced with Chrome Version 65.0.3325.181, Firefox 59.0.2
- Your operating system: macOS 10.13
- Your databases:  reproducable with Postgres 10, default H2
- Metabase version: 0.28.6
- Metabase hosting environment: (Mac app
- Metabase internal database:  H2

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by danieltanfh95** [comment]
Tested on Ubuntu 16.04, same result.

**Comment by milesmatthias** [comment]
I can't tell if this fix is included in v0.29.3 or not. I've updated to that version and am having a similar issue.

When I use the query builder and get the date output to the format of "%Y-%m" / "February 2018", I look at the SQL and copy it to my own query, but get the full datetime: "February 2, 2018 12:00:00 UTC"

Here's the sql:

```sql
str_to_date(concat(date_format(t.created_at, '%Y-%m'), '-01'), '%Y-%m-%d')
```

**Comment by gitvikram** [comment]
I am also getting same issuer with sqlserver 2012 . trying to get date only from datetime and it shows like Wednesday, June 27, 2018 12:00 AM

**Comment by Siddarth434** [comment]
Hi @gitvikram 

Have you found any solution to this? I am facing the same challenge

**Comment by danieltanfh95** [comment]
@Siddarth434 @gitvikram you can update metabase with this : https://github.com/danieltanfh95/metabase/commit/4c748cf056de1c52489814203d24544b554e429e and it will show the correct date format. I haven't got the time to write unit tests for it, but it should show the expected result

**Comment by Siddarth434** [comment]
@gitvikram , if you are using Mysql use Date_Format and it worked
