### ISSUE TITLE
Custom aggregations can't handle fields with names that start with a number

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7498]
The screenshot shows an example, but you can also imagine columns named things like "1st Tier" or "2nd Quarter Sales" etc. Basically, Metabase thinks you're trying to do multiplication.

<img width="544" alt="screen shot 2018-04-30 at 12 38 02 pm" src="https://user-images.githubusercontent.com/2223916/39448035-87254564-4c78-11e8-87b0-2135c930cf4d.png">

**Comment by flamber** [comment]
Hi @mazameli 
Very likely a duplicate of #7373 - similar workaround by adding quotes around the column.

**Comment by mazameli** [comment]
Closing as dupe
