### ISSUE TITLE
Mobile view of breakout filters is a little borked

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7501]
Looking at the dashboard in a small viewport, the dimension selector in the drill-through breakout action is clipped.

This is 0.29.0 on chrome. 

![screen shot 2018-04-30 at 2 50 26 pm](https://user-images.githubusercontent.com/107439/39452124-fd07c768-4c85-11e8-8162-ef67ab1e27a4.png)

**Comment by flamber** [comment]
Hi @salsakran 
I cannot reproduce this on 0.31.2 with Firefox 65 or Chromium 71 on many different viewports. Even if the card is at the bottom of the screen, when the popover appears, it extends the page.

**Comment by flamber** [comment]
Still cannot reproduce on 0.35.3, but I'm seeing an overflow problem #12440
