### ISSUE TITLE
"Clear email settings" button should cause a confirmation modal to be displayed

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7504]
As [depicted in the design](https://github.com/metabase/metabase/issues/7287#issuecomment-379912385), when an admin clicks the button to clear out their email settings, we should ask them to confirm this since it's a destructive action that they can't undo.

Currently in master this doesn't happen.

**Comment by mazameli** [comment]
This issue by itself does not warrant a 0.29.1 release, but it would be great to include a fix for this if there ends up being a dot release.

**Comment by brunobergher** [comment]
Not applicable anymore.
