### ISSUE TITLE
Post API For creating new user at initial setup showing 

### ISSUE THREAD

**Issue by amanmalkar** [metabase/metabase#7512]
curl -X POST -H "Content-Type: application/json" -d '{"email": "amanmalkar@gmail.com", "first_name": "aman", "site_name": "MetabasTest", "password": "xyz7030", "token": "56dd2a37-8383-4d07-b634-10ce7afb4835", "last_name": "malkar"}' http://localhost:3000/api/setup/

{"errors":{"site_name":"value must be a non-blank string."}}

**Comment by camsaul** [comment]
Hi @amanmalkar, for that endpoint you need to use nested maps

* `name` engine details is_full_sync is_on_demand schedules

**Comment by camsaul** [comment]
Hi @amanmalkar, for that endpoint you need to use nested maps

* `token` can go under top level
* under `database`: `name engine details is_full_sync is_on_demand schedules`
* under `user`: `first_name last_name email password`
* under `prefs`: `allow_tracking site_name`

**Comment by amanmalkar** [comment]
Thanks a lot for responding! 
I'm very new, could you please let me know if this is the correct way 

curl -X POST -H "Content-Type: application/json" -d '{
	"token": "56dd2a37-8383-4d07-b634-10ce7afb4835",
	"database": {
		"name": "",
		"engine": "",
		"details": "",
		"is_full_sync": "",
		"is_on_demand": "",
		"schedules": "",
	} ,
	"user": {
		"first_name": "",
		"last_name": "",
		"email": "",
		"password": ""
	},
	"prefs": {
		"allow_tracking": "",
		"site_name": ""
	}
}'

And if it is, since I can skip setting up a db during launch and use sample database what do I fill in in the database portion of the above curl command? Thanks.

**Comment by amanmalkar** [comment]
@camsaul I did it.

For anyone struggling with the REST API Initial setup:

If you're not integrating db at launch you can do:

curl -X POST -H "Content-Type: application/json" -d '{ "token": "56dd2a37-8383-4d07-b634-10ce7afb4835", "user": {"first_name": "xyz", "last_name": "abc", "email": "xyabzc@gmail.com", "password": "xzy7030"},"prefs": {"allow_tracking": false, "site_name": "yyzz"}}' http://localhost:3000/api/setup

**Comment by manugarri** [comment]
awesome, thanks!

**Comment by tmck-code** [comment]
> @camsaul I did it. Thanks for the help.
> 
> For anyone struggling with the REST API Initial setup:
> 
> If you're not integrating db at launch you can do:
> 
> ```shell
> curl -X POST -H "Content-Type: application/json" -d '{ "token": "56dd2a37-8383-4d07-b634-10ce7afb4835", "user": {"first_name": "xyz", "last_name": "abc", "email": "xyabzc@gmail.com", "password": "xzy7030"},"prefs": {"allow_tracking": true, "site_name": "yyzz"}}' http://localhost:3000/api/setup
> ```

You are a stone-cold legend

**Comment by flamber** [comment]
Closing in favor of #11440 and #9033
