### ISSUE TITLE
Collections 2.0 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7515]
This is a master tracking issue for our new permissions and organization as laid out in https://github.com/metabase/metabase/projects/4

TL;DR: you can put dashboards and pulses in collections. Collection permissions and visibility rules apply to those.

**Comment by ryanfoxsquire** [comment]
i'm confused -- it seems like these issues are closed/resolved (including https://github.com/metabase/metabase/pull/7358 ) ... but how do I add dashboards to collections? 
Is this still in development or do I just not understand how to use the feature? I can't find any better documentation/instructions from googling.

**Comment by salsakran** [comment]
closed in 0.30
