### ISSUE TITLE
In collections 2.0, "Edit this collection" shouldn't return a 404

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7519]
It should open up the modal to edit the collection's name and description.

![screen shot 2018-05-02 at 11 12 15 am](https://user-images.githubusercontent.com/2223916/39541152-b14825a0-4df9-11e8-97da-1b076de12709.png)

**Comment by kdoh** [comment]
Should be fixed by fa3aaffd8cb95f538599e49442e791f63fe815fe now.

**Comment by mazameli** [comment]
Fixed
