### ISSUE TITLE
Collections 2.0: the New menu should close after I make a selection

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7530]
![new-menu](https://user-images.githubusercontent.com/2223916/39553918-d479906a-4e24-11e8-9a1c-8ec9275654bb.gif)

**Comment by tlrobinson** [comment]
@mazameli @kdoh This is fixed in `add-collection-id-to-dashboards-and-pulses`

**Comment by mazameli** [comment]
Fixed indeed
