### ISSUE TITLE
random blue bar

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7537]
- Your browser and the version: Chrome Latest
- Your operating system: OS X latest
- Metabase version: 0.29.0

- *Repeatable steps to reproduce the issue*
Go to Data Model you should see this on the right.

![screen shot 2018-05-02 at 22 29 06](https://user-images.githubusercontent.com/1330677/39561147-9ad35470-4e58-11e8-9665-2626747d1d9d.png)

**Comment by salsakran** [comment]
That's meant to show you how well filled out your metadata is. 

For some reason it's being compressed.
