### ISSUE TITLE
Row chart - data hidden in the "others" category

### ISSUE THREAD

**Issue by marcodaureliopeivm** [metabase/metabase#7544]
Hello everyone,
I am using the row chart to plot these data in decreasing order:
![table](https://user-images.githubusercontent.com/38955778/39587505-fbe83ae0-4ef9-11e8-979e-9cb6c9be22a6.PNG)
However, the generated plot aggregates data from second to last in a large "others" row, and it's not possible to drill down the row,
![row chart](https://user-images.githubusercontent.com/38955778/39587521-0536e326-4efa-11e8-8098-e7507e4939cf.PNG)
I think that the condition for using the "others" category should not be triggered when the relative difference between rows is so small, and, possibly, there should be the option to select the "others" threshold.

**Comment by flamber** [comment]
Hi @marcodaureliopeivm 
I can reproduce this on 0.31.2 with sample data - possibly related to #6548
![image](https://user-images.githubusercontent.com/1447303/53108031-ed0d0580-34fb-11e9-9523-aa286b1be69b.png)

**Comment by RobertLowe** [comment]
Same issue:

![Screen Shot 2019-03-31 at 12 50 56 AM](https://user-images.githubusercontent.com/601141/55284959-22a0dc00-534f-11e9-8e0d-b02c4f561a60.png)

And after switching to Bar

![Screen Shot 2019-03-31 at 12 51 10 AM](https://user-images.githubusercontent.com/601141/55284960-32202500-534f-11e9-86c5-fa5865d01286.png)

**Comment by kafran** [comment]
I don't see this as an Enhancement, it seems a bug to me, since this does not happens in Chrome.

**Comment by flamber** [comment]
@kafran I agree. Just for reference:
Firefox 69:
![image](https://user-images.githubusercontent.com/1447303/67148858-a4137980-f261-11e9-9394-d26d1907d47b.png)
Chromium 76:
![image](https://user-images.githubusercontent.com/1447303/67148872-c1484800-f261-11e9-9f4c-c0278582cb39.png)
