### ISSUE TITLE
User Friendly Tags

### ISSUE THREAD

**Issue by pnewell** [metabase/metabase#7563]
I am currently testing with Postgres but have not settled on a final DB yet. I am wondering what the most user friendly way to handle tags is currently? It doesn't look like array types are supported in any of the databases yet? Is there any way to setup a system allowing people to filter for multiple comma separated tags?

Examples:

Field: tags
Value: tag1, tag2, tag3

SELECT * FROM table_name WHERE _((( tags contains tag1 OR tag 3)))_

Note: I realize the italic part is not valid SQL, just for illustrative purposes

**Comment by salsakran** [comment]
Hello @pnewell - 

We try to limit conversation on the issue tracker to specific problems that need to be solved or features. This kind of question is better posed on our use discussion forum - http://discourse.metabase.com/
