### ISSUE TITLE
Support for service account google credentials

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [metabase/metabase#7564]
Currently metabase supports an "auth code" based workflow as per [Working with Google BigQuery in Metabase](https://metabase.com/docs/latest/administration-guide/databases/bigquery.html). Unfortunately that workflow does not seem to allow granular control on a service account level -- at least we were not able to find a way to do so. The way this is often done in google cloud api clients is via the JSON key that you get when creating a service account.

Looking at `google-auth-library-java`, it supports reading the `GOOGLE_APPLICATION_CREDENTIALS` environment variable and creating a `GoogleCredential` object via:

```
// warning: this is not clojure
import com.google.auth.oauth2.GoogleCredentials

GoogleCredentials.getApplicationDefault()
```

I believe one way of supporting this would be by patching `database->credential` to return `GoogleCredentials.getApplicationDefault()` if the `GOOGLE_APPLICATION_CREDENTIALS` env var is set.

I'd be interested in contributing this feature, but I am not sure what the process is. I also may have missed stuff -- perhaps none of the above is needed. :)

Thanks!

**Comment by snarfed** [comment]
dupe of #4634?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Indeed, I'll close in favour of that one. :)

**Comment by snarfed** [comment]
@igorwwwwwwwwwwwwwwwwwwww did you ever try making this change to the metabase code? i'm about to try it myself, so i figured i'd check first.

**Comment by Saurabh-Shrivastava-Narvar** [comment]
@snarfed were you able implement this - we also need service account level setup for bigquery and metabase.

**Comment by snarfed** [comment]
@Saurabh-Shrivastava-Narvar yes! i did, in #7907. doesn't apply to head cleanly now though, sorry, but probably a straightforward resolve.

also see #4634.
