### ISSUE TITLE
Ldap group sync wipes non-ldap group membership upon user login

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7571]
If ldap group sync is enabled and a user is added to a group in the UI that membership is lost when the user logs out and logs back in. This appears to be because the ldap group membership syncing is being too aggressive when trying to determine what group membership to add and remove. LDAP syncing should not remove user memberships from any groups that are not used in any ldap group mappings.

Due to the aggressive syncing it is not possible to modify any user permissions when ldap group syncing is enabled. This is unfortunate as it requires a LDAP group per every group in Metabase.

**Steps to Reproduce**
1. Hook Metabase up to LDAP. Setup group syncing. Setup a group G in the UI. This group should not have any ldap mappings setup.
2. Have a ldap user log in (so they exist in the system) then add them to group G
3. Have the user log out and then back in. Their membership in G is wiped

**Expected Result**
Since the group G is not mapped to any ldap groups membership should not change when attempting to resync ldap permissions for a user

**Actual Result**
The users memberships in groups not hooked in to LDAP are wiped

Metabase version 0.29.0

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by DoctorOgg** [comment]
this has become a real problem, im not having to manually re-add users to groups every 30min for my users.

**Comment by DoctorOgg** [comment]
actually worse, i may have to disable LDAP auth as this is not supportable

**Comment by vvaezian** [comment]
One workaround is to use the user's DN to define a group mapping. In other words instead of manual assigning a group to a user that is affected by LDAP group mappings, add another group mapping specifically for that user.

I use [AdFind](http://www.joeware.net/freetools/tools/adfind/) for querying Active Directory.  
To Find the person's DN you can run this command:
```
./adfind.exe -b "DC=example,DC=com" -f "CN=John Doe" -dn
```

**Comment by Hank45** [comment]
I was about to open a new report but I see this is open. I am experienced the same symptoms.

**Comment by wagnerflores11** [comment]
Enfrento o mesmo problema!

**Comment by gonchik** [comment]
Met with that on 0.48.7
