### ISSUE TITLE
Collections 2.0: new collection modal JS errors

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7575]
When I go to make a new collection, if I try to enter a description or change the color, or basically click anywhere other than the primary Create button, I get a JS error about props and the modal closes without creating the collection. (If I click the Create button right away after entering a title, the collection is correctly created, but I have to refresh the page to see it.)

![create-collection-problems](https://user-images.githubusercontent.com/2223916/39715331-c48a4530-51e1-11e8-85ad-50c36fb97b88.gif)

```
warning.js:33 Warning: Unknown props `initialValue`, `autofill`, `onUpdate`, `valid`, `invalid`, `dirty`, `pristine`, `error`, `active`, `touched`, `visited`, `autofilled` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by Input)
    in Input (created by CollectionEditorForm)
    in div (created by FormField)
    in FormField (created by CollectionEditorForm)
    in div (created by CollectionEditorForm)
    in div (created by ModalBody)
    in div (created by ModalBody)
    in ModalBody (created by ModalContent)
    in div (created by ModalContent)
    in ModalContent
    in div
    in OnClickOutsideWrapper
    in div
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup
```

**Comment by tlrobinson** [comment]
@kdoh it appears this is because `CollectionEdit`/`CollectionEditorForm` itself contains a modal, so you've got a modal in a modal which it doesn't seem to like. We should probably change it so `CollectionEditorForm` uses `ModalContent` and the consumer of those components decides what sort of modal to put it in.

**Comment by tlrobinson** [comment]
@mazameli @kdoh This is fixed in `add-collection-id-to-dashboards-and-pulses`

**Comment by mazameli** [comment]
Yup, fixed
