### ISSUE TITLE
Where does metabase store super user details ( Email / Password ) etc.

### ISSUE THREAD

**Issue by amanmalkar** [metabase/metabase#7580]
Hey guys, wanted to know where is the super info stored during account creation. Is it stored internally within the app or on the db? And can I port it to db? Thanks.

**Comment by jornh** [comment]
See the documentation: https://metabase.com/docs/latest/operations-guide/start.html#configuring-the-metabase-application-database

In general questions are better asked on the [discourse](http://discourse.metabase.com) forum. GitHub issues are for bug reporting and enhancement requests.

**Comment by tlrobinson** [comment]
Information like user accounts and database connection details are all stored in the application database, which can be H2, PostgreSQL, or MySQL.

FYI you can also encrypt the database connection details using the `MB_ENCRYPTION_SECRET_KEY` environment variable: https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest

**Comment by silvertiplabs** [comment]
By default (as of 7/24/23), metabase appears to create an H2 database in the current working directory from which it's started. The name of the file is metabase.db.mv.db.
