### ISSUE TITLE
UX for selecting field types in data model isn't great

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7586]
There are now a bunch more metadata types a field can be marked with in this dropdown, but there's no real discernible sort order, grouping, or separation between them, making it really annoying to find the type you're looking for. There also isn't a filter box to aid in searching for a specific type.

At minimum, it would be nice if we added some additional subsections (maybe e.g. "Numeric," "Location" or "Geographic" etc.) to group similar types together, and sorted the types alphabetically within those subgroups. A filter box would be nice as well, especially if the focus was put into it when the dropdown is opened so that you can start typing right away.

![metadata](https://user-images.githubusercontent.com/2223916/39773045-b4d8faf8-52ab-11e8-96ff-8f826d4757e5.gif)

**Comment by Arrowofdarkness** [comment]
Can I super-like this in addition to just a thumbs up?

We've always had was a lack of clear definitions on what the original types were for other the briefest of mentions in older docs that they existed, not a breakdown of what they are and what effects applying them have outside of basic tagging. 

Now that x-rays are much more mature and the amount of types has exploded in size its even more of a guessing game. I've largely had to learn by trial and error when and when not to apply types based on their effects on x-rays or options in the query builder.

**Comment by walterl** [comment]
I also find it confusing to choose a type: I see _Cancellation timestamp_, _Creation timestamp_ and _Join timestamp_, but no indication as to how they differ.

Seeing as the list of types is quite significant, it would be useful to add a quick search filter to the list.

**Comment by mazameli** [comment]
I added a search/filter box in https://github.com/metabase/metabase/pull/11912, and am now working on a proposed reorganization of the items within the special type popover.
