### ISSUE TITLE
LDAP authentication fails with emails that include plus sign (+)

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7592]
- Metabase version: 0.26.2 (any really - LDAP code hasn't changed up to 0.29.0)

* Set up LDAP authentication and ensure it's binding and able to query the user search base
* You'll need two test users in Metabase and the LDAP directory - one of the user emails will contain a plus sign - e.g. hagen+tag@email.com
* Log in with the user that _does not include_ a plus sign (+) in the email - works
* Log in with the user that _does include_ a plus sign (+) in the email - no log in

This comes down to the + sign being a reserved character in LDAP land, typically for adding multiple values into an attribute (e.g. filtering on email and phone number: **cn=hagen@email.com + 411234987**)

I think to resolve this, Metabase just needs to escape the + sign in the email addy before trying to search/bind to the LDAP server. Escaping is done with a backslash, e.g **hagen\+tag@email.com**
[IETF LDAP character escaping](https://tools.ietf.org/html/rfc4514#section-4)
@wwwiiilll this seems to be your domain? Are you able to confirm this?

**Comment by wwwiiilll** [comment]
Oh, I handled the special characters from the LDAP filter specs, but forgot about the others. Just adding them to the current escaping function should fix this.

**Comment by hagen** [comment]
Neat, that's super easy.
Except I have **no idea** what this Clojure code means!
```clojure
(defn- escape-value
  "Escapes a value for use in an LDAP filter expression."
  [value]
  (str/replace value #"[\*\(\)\\\\0]" (comp (partial format "\\%02X") int first)))
```
https://github.com/metabase/metabase/blob/master/src/metabase/integrations/ldap.clj#L98

Maybe this?
```clojure
(defn- escape-value
  "Escapes a value for use in an LDAP filter expression."
  [value]
  (str/replace value #"[\+\*\(\)\\\\0]" (comp (partial format "\\%02X") int first)))
```
