### ISSUE TITLE
Feature request: Default value Category widget to support multiple default values

### ISSUE THREAD

**Issue by hagen** [metabase/metabase#7593]
Category filters allow selection of multiple values. They same should be possible in the default value for the filter.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by x670** [comment]
Also this would be useful for text filters. They can inherit multiple filters from dashboard filter if it depends on field filter from another query too, but in basics you can't set this multiple values to default

**Comment by MarcGJA** [comment]
Add to that the ability to use SQL in the widget default to get those multiple default values.  Somewhere there is a related proposal to populate a filter using SQL in the widget if I remember correctly.  Some common use cases would be to set the default filter selection to the most recently released financials, statistical reports, new products, etc.

**Comment by MarcGJA** [comment]
Set the category filter widget default value to a simple sql such as: 

<b>=(select current_year from year_control_table)</b>

Use case example: A question based on a dataset containing historical, current, and forecast annual report values with a category filter widget that must always default to the most recent annual report year as it becomes available (i.e. not anchored to now() as a relative date as seems to be the case in #3156).  

See the illustration and discussion from the discourse forum:
https://discourse.metabase.com/t/default-filter-widget-value-set-to-a-simple-sql/7453

For the time being the most viable option in this case is to write an update query to change the following within Metabase as suggested by @flamber: 
<b>report_card table > dataset_query column > template-tags statement > default value indicator</b> and change the default value.

**Comment by flamber** [comment]
This was included in 0.38.0 for dashboards, and will be part of 0.39.0 for native queries.

**Comment by brunolnetto** [comment]
I came to this issue by asking myself about multiple options in the category field: if possible, what is the right syntax? My intuition says: option1, option2 . Is it right?

**Comment by flamber** [comment]
@brunolnetto Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You select the values in the dropdown
![image](https://user-images.githubusercontent.com/1447303/116786683-5e637e00-aaa0-11eb-919e-0267c899447b.png)

**Comment by brunolnetto** [comment]
Nice. The question default value should have some note about this possibility.

**Comment by flamber** [comment]
@brunolnetto The default filter now works exactly how regular filter widgets work:
https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html#choosing-between-a-dropdown-or-autocomplete-for-your-filter
