### ISSUE TITLE
Passing customer ID to metabse Dashboard in Drupal

### ISSUE THREAD

**Issue by majdnmaz** [metabase/metabase#7594]
Hello,
I have a Drupal website that is integrated with Microsoft Active Directory.
Also, I have created a metabase dashboard and embedded it in the Drupal website where it doesn't display any data unless a customer ID is passed to it.
My challenge is how can I pass the customer ID to the embedded filtered dashboard once the customer logs in with Microsoft AD credentials to display just the data for that specific customer?

I would really appreciate you help

Thank you in advance

**Comment by salsakran** [comment]
Hello @majdnmaz -

This isn't the appropriate forum for questions about threading user attributes through Drupal. 

I'd suggest opening a thread in http://discourse.metabase.com/ and seeing if anyone in our community has done something similar.
