### ISSUE TITLE
Metabase should not default port in SQL Server database connection - prevents use of dynamic ports

### ISSUE THREAD

**Issue by sldorman** [metabase/metabase#7597]
In version 0.26, the SQL Server driver was changed from the jTDS driver to Microsoft's JDBC driver (#3821).  Since then, there have been problems connecting to SQL Server for various reasons.  The history of these problems are in #6056 .  One of the problems is related to dynamic ports which I will detail here.

In SQL Server, the default instance listens on TCP port 1433, named instances use dynamic ports.  When using dynamic ports, an available port is selected whenever the SQL Server service is started or restarted - this means the port number can't be known ahead of time.

If the instance uses dynamic ports and a port is specified in the connection string, the jTDS driver ignores the supplied port and gets the port from the SQL Server Browser service (which runs on port 1434).  That is not true for the Microsoft driver - if a port is specified, that value is used.  If a port is not specified, the driver asks the SQL Server Browser service and the appropriate port is used.

Metabase is defaulting the port to 1433 even when a port is not supplied in the Admin Panel.  This means there is no way to connect to SQL Server using dynamic ports.  Dynamic ports are not just reserved for named instances, they are preferred from a security stand point.

Metabase should not set a default value for the port, the user should have to set it in the Admin Panel.  If a value is not entered, the port should not be in the connection string.

To confirm this, I created a Java program that connects to SQL Server using the Microsoft driver.  I experimented with fixed and dynamic ports. In summary, I experienced the following:

Works with Fixed port 1433, port in connection string
Works with Fixed port 1433, port not in connection string
Works with Fixed port 16000, port in connection string
Fails with Fixed port 16000, port not in connection string
Fails with Dynamic ports, port in connection string as 1433
Works with Dynamic ports, port not in connection string

I tried these same settings in Metabase and got the same result except for the last test.  Even though a port was not supplied in the Admin Panel, I still got an error.  The field has a grayed out "1433" which is apparently being used in the connection.

Here is a helpful article on how to make ports fixed or dynamic in SQL Server:

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-2017

This discourse discussion is related:

http://discourse.metabase.com/t/adding-sql-server-with-named-instance-as-source/1334/6

Your browser and the version: Firefox 59.0.2 (64-bit)
Your operating system: Windows 7
Your databases: SQL Server 2012
Metabase version: 0.24.1 (works), 0.26 (doesn't work), 0.28.6 (doesn't work)
Metabase hosting environment: jar on Win 7 - SQL Server, jar, and browser all on same local host
Metabase internal database: H2 (default)

**Comment by sldorman** [comment]
Any idea when this issue can be addressed?  It's a critical problem for SQL Server environments.  The Metabase team has been putting out a lot of important fixes and features but I can't upgrade until this bug is fixed.

**Comment by verydxz** [comment]
me too here, have to stay at v0.25.0.RC2. keep watching this issue...

**Comment by camsaul** [comment]
@sldorman @verydxz can you try my PR #8107? If I can confirm it fixes the issue then I think we can include it in our upcoming release

**Comment by sldorman** [comment]
Hi @camsaul, I would love to help but I don't have the proper system requirements to set up Metabase for development/compilation.  Is there a way I can get a jar with your changes?

**Comment by jornh** [comment]
@sldorman said:
> Is there a way I can get a jar with your changes?

Yes, I built one and put it up at https://github.com/jornh/metabase/releases/tag/8e365e8

I have only tested it towards an Azure SQL exposed on port 1433 and confirmed that worked as before when I gave it a 1433 port - and timed out on setup without any port. (It's entirely possible that other ports on that endpoint are blocked, I really haven't dug into it)

**Comment by sldorman** [comment]
Hi @camsaul, I have been testing this and it does seem to be working but there was one scenario that allowed the connection to work when I thought it shouldn't.  I am still looking into it and I'm hoping to have a definitive answer some time today.  I think it's okay to go ahead with a release since it does solve the problem of connecting with dynamic ports.  I just want to make sure a new problem wasn't introduced.

**Comment by sldorman** [comment]
Thank you @jornh for providing the jar and thank you @camsaul for fixing the problem.  I was able to test and verified that all scenarios worked correctly.

I tested the following in Metabase:

SQL Server Fixed port 1433, port 1433 set in MB Admin Panel - works - as expected
SQL Server Fixed port 1433, port not set in MB Admin Panel - works - as expected
SQL Server Fixed port 16000, port set to 16000 in MB Admin Panel - works - as expected
SQL Server Fixed port 16000, port not set in MB Admin Panel - works - as expected
SQL Server Dynamic port, port set to 1433 in MB Admin Panel - fails as expected since the port is not 1433
SQL Server Dynamic ports, port not set in MB Admin Panel - works - as expected  - *** this is the scenario that needed the fix , it works now ***

Note that the SQL Browser service must be running to pick up the proper port if the port is not specified in the MB Admin Panel (i.e. the connection string).

**Comment by PatSeewald** [comment]
Many thanks to the previous speakers.

We still have the problem with us:

- Sql server browser is running
- Sql Server 2017 is running
- TCP / IP is enabled
- Dynamic ports are activated
- we use a named instance 
- and a sql server login
- no ssl

If you now enter the dynamic port permanently in Metabase, the connection works wonderfully.
However, if you leave the Port field empty, which means that the dynamic port should be automatically recognized by the Sql Server Browser, a timeout occurs and a connection cannot be established.

Does anyone have any tips / ideas why this could be?
