### ISSUE TITLE
Date or time in composite primary key break filtering

### ISSUE THREAD

**Issue by jens-plause** [metabase/metabase#7599]
We have a use case where a primary key is made up of two columns, one of them being a date or timestamp, such as in this example for Postgres:
 
```
CREATE TABLE test
(
person_id integer NOT NULL,
created date NOT NULL,
PRIMARY KEY(created, person_id)
);

INSERT INTO test VALUES 
(1, '2018-05-01'), (2, '2018-05-01'),
(3, '2018-05-02'), (4, '2018-05-02'), (5, '2018-05-02'),
(6, '2018-05-03'), (7, '2018-05-03'), (8, '2018-05-03'), (9, '2018-05-03');
```

When exploring this table in MetaBase using "New Question -> Custom" and then setting a filter to e.g. "ON  2018-05-03, then the result does not show a list of 4 entries. Instead, the first individual entry is shown and there's a right arrow on the right of the screen to show the next entry. Clicking that arrow results in an error `Invalid value '2018-05-031': expected a DateTime.`

The same bug happens when the column uses a timestamp instead of a date type.

Expected behaviour:
The filter should show a table with 4 entries (for 2018-05-03).
```
6, 2018-05-03
7, 2018-05-03
8, 2018-05-03
9, 2018-05-03
```

A similar bug happens when grouping by day. The result is a list of 3 days, which is correct. But when clicking one of the days, an individual entry is shown instead of a list of values.

It appears that MetaBase gets tripped up by the column being part of the primary key. When the date or timestamp columns are not part of the primary key, the behaviour is as expected.

-  Your browser and the version: reproduced with Chrome Version 65.0.3325.181, Firefox 59.0.2
-  Your operating system: macOS 10.13
-  Your databases: reproducable with Postgres 10
-  Metabase version: v0.29.0
-  Metabase hosting environment: Mac app
-  Metabase internal database: H2

**Comment by flamber** [comment]
Hi @jens-plause 
I'm not sure, but it seems to related to #5648.
And I did a quick test on Postgres 11.2 and MariaDB 10.3 - and I could only reproduce on Postgres.
But it seems a workaround would be to change `created` from an "Entity Key" to "Created date" in Data Model.
