### ISSUE TITLE
New Question screen done gone and went weird

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7602]
This is on master on Chrome and Safari as of this afternoon. Firefox looks fine.

![screen shot 2018-05-09 at 5 32 50 pm](https://user-images.githubusercontent.com/2223916/39846165-12af0cfe-53af-11e8-90ed-f50588acefeb.png)

**Comment by tlrobinson** [comment]
Possibly #7489. Try `git revert -n 626be95`

**Comment by tlrobinson** [comment]
@kdoh Can we go ahead and revert that change to flex.css? Clearly we need something more nuanced.

**Comment by kdoh** [comment]
@tlrobinson I think we were overusing that class in a few places and the resulting cleanup is probably a good thing overall. If we find a few more spots then I'd say revert and turn that into an IE specific fix, but the changes in https://github.com/metabase/metabase/pull/7610 are mostly a negative diff and small enough that I'm not too worried.
