### ISSUE TITLE
Field Filter restricted number of values in drop down [intended behavior?]

### ISSUE THREAD

**Issue by jyotipatel** [metabase/metabase#7603]
Hi,

First of all thanks a lot for this platform, it is very useful for my organization. Only problem and major problem I am facing is the limitation on the drop down values in field filter. My column in redshift table has more than 1000 distinct values , which I need as drop down in the filters. Is there any hack , I can do to make it possible, any parameter in the code or whatever. Any help will be appreciated.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jornh** [comment]
What Metabase version are you on? v0.29 got enhanced quite a bit in this area: https://twitter.com/metabase/status/992090696956854275

**Comment by mazameli** [comment]
Hi, @jyotipatel. As Jorn asked, which Metabase version are you using?

If you are using Metabase 0.29 (the latest), when filtering on that field, you should be seeing a search box that will show you autocomplete suggestions as you start to type.

If you are not experiencing this behavior, you can go to the Admin Panel, then the Metadata section, then find the field you're using and click the gear icon on the far right to open up the options for that field. You'll see an option there to choose how to filter on that field; just make sure to set it to "Search box."

There is a current issue in 0.29.0 where if you set a field with many values to "A list of values" in that setting, it doesn't correctly show you a list of all the values. We'll be including [a fix for this in 0.29.1](https://github.com/metabase/metabase/pull/7556) shortly, but as I mentioned above, the current fix is to set the field to "Search box," which you might find to be a preferable experience to a super long list of values anyway.

**Comment by jyotipatel** [comment]
Hi, @mazameli, thanks for the quick reply. I am using 0.29 version of metabase. Search box feature is amazing, I was not aware of the data model in admin panel, its working fine for almost all filters but what if a field is number? I set the data type to 'category' in metadata and 'search box' in filter but still when I am starting to type in the search box it is not showing values for auto completion.

**Comment by ni-rgranger** [comment]
Hi everyone, 

Also, thanks a lot for the big work and the amazing platform that is Metabase! 

Same, I have a field that has 381 distinct values, but doesn't display even when 
"Has field values" is set to “list”

{“global”:{“distinct-count”:381,“nil%”:0.0},“type”:{“type/Text”:{“percent-json”:0.0,“percent-url”:0.0,“percent-email”:0.0,“average-length”:32.7531}}}

I didn't clearly understand how the limit is set on Metabase side? 

We use BigQuery and Metabase version v0.34.2

Thanks a lot for your answer and time,

Romain

**Comment by flamber** [comment]
@ni-rgranger If my memory serves me correct, when you have more than 300 distinct values, then the dropdown list is not shown even when set to List, but then the widget gets into a strange state, where it kinda looks like the search box, but no autocomplete is shown. If you set it to Search, then you have autocomplete, but no dropdown list. It's the same behavior in the QB interface.

By the way, latest release is 0.35.3

**Comment by camsaul** [comment]
Not sure this is a bug... we have the 300/1000 values limits in there on purpose

**Comment by flamber** [comment]
Closing in favor of several of the dropdown issues I've created, since this is getting outdated and confuses:
https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+author%3Aflamber+in%3Atitle+dropdown
