### ISSUE TITLE
Error: <rect> attribute height: A negative value is not valid. 

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7604]
Seeing these in the console logs of a dashboard. It appears to be from the horizontal row chart. I don't know if it is an issue or not. It seems some boundary is a little fidgety. By zooming in and out in chrome I can make different close-to-zero values show up.

> 385Error: <rect> attribute height: A negative value is not valid. ("-0.5744363636363635")
> 55Error: <rect> attribute height: A negative value is not valid. ("-0.5857999999999999")
> 55Error: <rect> attribute height: A negative value is not valid. ("-0.581145454545455")
> 220Error: <rect> attribute height: A negative value is not valid. ("-1.1266000000000005")
> 55Error: <rect> attribute height: A negative value is not valid. ("-1.134545454545454")
> 110Error: <rect> attribute height: A negative value is not valid. ("-1.8618181818181818")
> 55Error: <rect> attribute height: A negative value is not valid. ("-1.8538727272727271")
> 55Error: <rect> attribute height: A negative value is not valid. ("-1.119890909090909")
> 220Error: <rect> attribute height: A negative value is not valid. ("-2.119890909090909")
> 110Error: <rect> attribute height: A negative value is not valid. ("-0.3084181818181822")
> 55Error: <rect> attribute height: A negative value is not valid. ("-0.3017090909090908")

Example Stack Trace:

```
  | attrConstant | @ | d3.js:663
-- | -- | -- | --
  | (anonymous) | @ | d3.js:962
  | d3_selection_each | @ | d3.js:968
  | d3_selectionPrototype.each | @ | d3.js:961
  | d3_selectionPrototype.attr | @ | d3.js:652
  | updateElements | @ | dc.js:8737
  | drawChart | @ | dc.js:8695
  | _chart._doRender | @ | dc.js:8639
  | _chart.render | @ | dc.js:1691
  | rowRenderer | @ | RowRenderer.js:133
  | renderChart | @ | CardRenderer.jsx:78
  | componentDidUpdate | @ | CardRenderer.jsx:39
  | notifyAll | @ | CallbackQueue.js:74
  | close | @ | ReactReconcileTransaction.js:78
  | closeAll | @ | Transaction.js:207
  | perform | @ | Transaction.js:154
  | perform | @ | Transaction.js:141
  | perform | @ | ReactUpdates.js:87
  | flushBatchedUpdates | @ | ReactUpdates.js:170
  | closeAll | @ | Transaction.js:207
  | perform | @ | Transaction.js:154
  | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:60
  | enqueueUpdate | @ | ReactUpdates.js:198
  | enqueueUpdate | @ | ReactUpdateQueue.js:22
  | enqueueSetState | @ | ReactUpdateQueue.js:216
  | ReactComponent.setState | @ | ReactBaseClasses.js:62
  | _this._updateSize | @ | ExplicitSize.jsx:12
  | (anonymous) | @ | ExplicitSize.jsx:30
```

Browser: Chrome 66.0.3359.139
OS: Windows 7
Databases: Oracle 12.2
Version: 0.29.0
Host Env: Windows 7
Internal Database: MySQL 5.7

**Comment by wxiaoguang** [comment]
Same problem here.

Resize the Chrome's window, and plenty of such error occurs.

**Comment by flamber** [comment]
I haven't seen these errors for a very long time and cannot reproduce on 0.41.2

**Comment by MuhamadMaulana99** [comment]
how to fixs?
