### ISSUE TITLE
We should make "friendly field names" way less aggressive

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7606]
"Friendly field names" has been a persistent source of confusion and annoyance for our users. In too many cases, it guesses wrong and produces results that look very broken, even when table/field names are in English.

I think we should refactor the behavior of this setting to only capitalize the first letter of each word in table/field names, and replace underscores with spaces. If that's all it did, I could see it being okay for it to be on by default.

@metabase/core-developers — any different opinions?

**Comment by drewblas** [comment]
I very much agree.   This "smart" friendly name is constantly corrupting field names way more often than it helps.  For example any company name that ends in "-ify":  "paid_to_sparkify" becomes "Paid To Spark If Y" and there's no way to fix it.

**Comment by xjzhou** [comment]
Is there a way to cancel the "Friendly field names" function ?

**Comment by paubelsan** [comment]
Admin Panel -> Genereal -> "Friendly Table and Field Names" -> Disabled

**Comment by emetselaar** [comment]
I like the feature - it often helps. But it is indeed too aggressive. Abbreviations are also interpreted as words. For example CPI (Cost Per Install) - "I" is an English word so it becomes "Cp I". An abbreviation like CTR is also interpreted as in need for capitalise and becomes "Ctr".

**Comment by whiteboardmonk** [comment]
Would be ideal to set the default as 'Only replace underscores and dashes with spaces'. This would avoid confusion and save time.

**Comment by nkconnor** [comment]
Another example `uniques` --> 'Uni Ques'

**Comment by opensas** [comment]
> Would be ideal to set the default as 'Only replace underscores and dashes with spaces'. This would avoid confusion and save time.

I agree, it was very confussing for me the first time I used metabase with tables with field names in spanish, the results were really confusing, and it wasn't that easy to find the way to turn that feature off.

BTW, I think that another option that could be added is the following:  'Only replace underscores, dashes and case changing (like in camelCase words) with spaces'

**Comment by paulrosenzweig** [comment]
I think we should take another pass at the logic and/or data backing this feature. It's still too aggressive:

e.g. "Github" becomes
![image](https://user-images.githubusercontent.com/691495/108523293-bc533880-729b-11eb-96e4-8e0c35148b5b.png)

– https://twitter.com/danokhlopkov/status/1362683231284428800

**Comment by paulrosenzweig** [comment]
I haven't assessed how severe this is, but I downgraded from P1 to P2 it on the (maybe wrong) assumption that the last past fixed many of the issues.

**Comment by flamber** [comment]
Or just not have it enabled by default - #5878

**Comment by mazameli** [comment]
If it's on by default, my 3-year old opinion remains the same I think: it should `only capitalize the first letter of each word in table/field names, and replace underscores with spaces`

**Comment by camsaul** [comment]
# Current plan from Notion

Let's remove the advanced functionality and stick with just:

- Replacing dashes and underscores with spaces
- Uppercasing the first letter of each word, leaving the rest of the words untouched.

Examples:

- last_modified_at → Last Modified At
- MAU_aggregate → MAU Aggregate
- 123_why_do_this → 123 Why Do This
- github_issues → Github Issues

In Admin > Settings > Friendly Table and Field Names, let's use this copy:

> To make table and field names more human-friendly, Metabase will replace dashes and underscores in them with spaces. We’ll capitalize each word while at it, so ‘last_visited_at’ will become ‘Last Visited At’.

And the UI widget should become a toggle, default on:

![image](https://user-images.githubusercontent.com/1455846/115777531-42f2c780-a36a-11eb-97af-13538dedbcec.png)

As part of the transition we should migrate instances which have the current setting configured as "Enabled" or "Only replace underscore and dashes..." with Enabled, and keep Disabled as Disabled.

**Comment by rlotun** [comment]
closed by https://github.com/metabase/metabase/pull/16119
