### ISSUE TITLE
Add ability to require values for field filter variables

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7607]
It is possible to require a value for the "Text", "Number", and "Date" variable types. There is no corresponding configuration to require a value for field filters. This would come in handy as it will prevent users from running expensive unfiltered queries that are otherwise fast when selecting a subset of data.

![image](https://user-images.githubusercontent.com/17504314/39879557-2271eef0-5449-11e8-8182-0d9a2e023793.png)

![image](https://user-images.githubusercontent.com/17504314/39879568-2a8726fa-5449-11e8-952f-0aa8a0c5de51.png)

![image](https://user-images.githubusercontent.com/17504314/39879578-3202e504-5449-11e8-962f-82304d83a218.png)

![no_required](https://user-images.githubusercontent.com/17504314/39879748-a6ae85e8-5449-11e8-923b-2e37012aea76.PNG)

**Comment by jsdtaylor** [comment]
This is causing us problems too. Love the power of Field Filters but they're often useless when reports just run automatically across massive datasets.

**Comment by MarkRx** [comment]
@cgopalan has a PR for it - #8653

**Comment by MarkRx** [comment]
This was added in 0.30.0
