### ISSUE TITLE
Table names and column names are constistenly wrong when they contain double underscore

### ISSUE THREAD

**Issue by edmondo1984** [metabase/metabase#7608]
Our database contains double underscore in both table and column names, and the structure extracted by metabase was completely wrong. We are happy to submit you a PR if you tell us which part of the code manage the naming

**Comment by mazameli** [comment]
In the Admin Panel, under the Settings > General, there's an option called "friendly table and field names" which you can set to "Disabled" to turn this behavior off. I believe you may need to re-sync the database after you change this setting.

Relatedly, I just opened issue #7606 where we're discussing either turning this behavior off by default, or making the default less drastic of a change.

**Comment by tlrobinson** [comment]
AFAICT double underscores don't have an effect on humanization. I created a table like `create table foo__bar (baz__buz_bar int);` and it named the table `Foo Bar` and `Baz Buz Bar` as expected.

@edmondo1984 if you're seeing something other than overly aggressive humanization (covered by #7606) please give me more details and I'll reopen this.
