### ISSUE TITLE
After re-ordering table columns newly added columns don't appear

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#7612]
Originally identified in #7343 by @mazameli.

This is because the `table.columns` setting is an ordered list of column names and we don't reset it when the query changes to add new columns.

**Comment by flamber** [comment]
Related to #6670
The workaround (as of 0.31.2) is to click the `Reset to defaults` in the table settings :gear:

**Comment by convoy-lb** [comment]
We are also experiencing a similar issue using Snowflake with our Metabase deployment (v0.36.4).

A new column was added to an existing table and the column order was changed for the last n columns. Through the custom question / builder UI, the newly added column is not available and using the Native Query UI, the column is available using `select * from schema.table`.

**Comment by flamber** [comment]
@convoy-lb This is specific to existing question. From your description it sounds like you're seeing a different issue.
Could it be that the sync process hadn't completed or failed?
Also, you might need to do a browser refresh, depending on which pages you have view because of cache.
