### ISSUE TITLE
Allow filtering on components of datetimes

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#7614]
For segmentations it would be useful to be able to filter by day of week (eg. weekends vs. weekdays), hour of day, month of year, ...

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ValdarT** [comment]
It seems that this is only a UI limitation because you can filter by day of week if you drill down (e.g., "View these Orders") from a graph that has used day of week in grouped by.

**Comment by Mrmiffo** [comment]
Would be neat to have this as an option in Dashboard filters as well. Currently resolving this in native/SQL with `[[and find_in_set(WEEKDAY(OrderDate)+1, replace({{Weekdays}}, " ", "")) > 0]]` and creating a dashboard filter accepting the user to input weekdays as a comma separated list of numbers 1-7.

**Comment by EBoisseauSierra** [comment]
I was about to raise the following issue before I noticed it's a dup:

## Feature request
Currently, date columns can only be filtered by date range-ish criteria. 

I would like to be able to **filter dates by day-of-week** (just like it's already possible to aggregate by day-of-week for date columns). I envision having a Category column-like filter, allowing me to (un)select each one of the 7 days of the week.

## Example use case
I have daily records, that follow a weekly pattern (i.e., Monday's values are different from Tueday's, but all Monday's values are more or less the same).
I am plotting the following graph:

- x-axis: week number
- y-axis: my KPI
- series: day-of-week

![Screenshot from 2020-03-18 12-59-39_shadow](https://user-images.githubusercontent.com/37387755/76963316-bb41ba80-6918-11ea-8535-12a7e7e86d79.png)

Filtering by day-of-week would allow me, for example, to exclude Saturday's and Sunday's records that are — in my case — only noise.

## Alternative
Well, I still have SQL as a fallback… but that would be a nice feature 

## Importance
It's only a nice-to-have feature.

**Comment by flamber** [comment]
Related to #7079

**Comment by flamber** [comment]
Coming in 0.43 - possible to include/exclude day of week, month of year, hour of day and quarter of year
![image](https://user-images.githubusercontent.com/1447303/164934407-f4ede0b7-8f2a-4fd9-85af-8b627a6f71df.png)
