### ISSUE TITLE
Collection permissions not working properly

### ISSUE THREAD

**Issue by arpitaks502** [metabase/metabase#7623]
After upgrading from Metabase 0.28.1 to Metabase 0.29.1 we are facing a new issue where all questions from a collection are not visible to the users having access to the collections. 

This has become a big issue as we cannot find the exact reason why this is happening. Also the problem is that this is happening for a few questions in a collection and not all. 

- *Repeatable steps to reproduce the issue*
Make a collection and add a user to it. Now some questions in the collection will not be visible to the user. Please help us solve this issue.
-------

**Comment by ipeevski** [comment]
Still have this issue with the latest 0.31.2 version.

Has anyone found a work around for the time being? Recreating collection or questions?

**Comment by flamber** [comment]
I cannot reproduce this in 0.31.2 - can you give detailed steps to reproduce the problem?
Are the questions using datasources, which the user doesn't have access to? Or are the questions Native Queries? Or Saved Questions (aka Nested Queries)?
Do you see any errors in the Metabase log or browser console?

**Comment by ipeevski** [comment]
All the queries are native.
They all existed before collections was a thing. Then assigned permissions to a group to a particular collection. The users in that group can see all queries but get permissions denied when clicking on half of them.

I'll chase up answers to the other questions asap.

**Comment by flamber** [comment]
There has been several fixes to permissions, but please comment with steps-to-reproduce or error messages from the log. I cannot reproduce on latest release 0.35.4
