### ISSUE TITLE
"hour of day" grouping ignores "reporting timezone" (PostgreSQL)

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#7629]
I have a table with dated records in it. I'm trying to analyze them by time of day and day of week. In this case they represent online sales.  When I use "group by" with "hour of day" the hours are UTC, even though my Metabase instance is configured to use EST for reporting. Other views on the date express them in UTC.

prerequisites:
  - postgresql database and table with records including a datetime with time zone (data in UTC)
  - metabase configured with "reports timezone" not UTC (e.g. EST)

Steps:
  1. New question
  2. no filter
  3. "count of rows"
  4. grouped by datetime field -> hour of day

Expected:
  hours are in reporting timezone

Result:
  hours are in data timezone (in this case UTC)

Environment:

User:
 - Chrome 66.0.3359.139
  - Mac OS X High Sierra

Data:
- PostgreSQL 9.6.6

Metabase:
- v0.29.2 (also 0.28)
- Elastic Beanstalk
- PostgreSQL 9.6.6

**Comment by senior** [comment]
Can you provide more information about the schema you are querying against and specifically the datatypes you are using? This is working correctly for me when I use a `TIMESTAMP WITH TIMEZONE` datatype for the column. For my setup, my database is in the pacific timezone (`America/Los_Angeles) and I've tried the report timezone in central time, eastern time and UTC. All seems to give correct results.

**Comment by flamber** [comment]
I cannot reproduce on 0.41.1
