### ISSUE TITLE
Don't know how to map column type 'bigint identity' to a Field base_type, falling back to :type/*.

### ISSUE THREAD

**Issue by Azd325** [metabase/metabase#7632]
- Your browser and the version: latest chrome
- Your operating system: latest macos
- Your databases: Microsoft SQL Server
- Metabase version: 0.29.2
- Metabase hosting environment: Ubuntu jar
- Metabase internal database: mysql

Don't know how to map column type 'bigint identity' to a Field base_type, falling back to :type/*.

**Comment by salsakran** [comment]
Closing, as this is a warning - there shouldn't be any negative impacts on using the field. If you are finding that field is missing or being treated  incorrectly, please provide examples and I'll re-open.

**Comment by htccccccc** [comment]
2025-01-16 08:07:48,170 WARN sync.describe-table :: Don't know how to map column type 'bigint identity' to a Field base_type, falling back to :type/*.
