### ISSUE TITLE
LDAP Auth accepting old password

### ISSUE THREAD

**Issue by marcusit** [metabase/metabase#7635]
**Problem:** When using LDAP authentication to Active Directory, and the user changes their password, they are still able to authenticate to Metabase with their old password.

**Variables:**
User Browser: Chrome 66
User OS: Windows 10
Metabase version v0.29.0
Metabase hosting: Official Docker image
Metabase internal database: MySQL
LDAP server: Active Directory

**Steps to replicate:**
1. User LDAP authentication to Active Directory (Settings: [https://i.imgur.com/56RzC9f.png](url))
2. Log in to Metabase with current AD credentials, then log out of Metabase.
3. Change Active Directory password. If using multiple domain controllers make sure the password change has synced between all.
4. Log in to Metabase using the old AD password.

**Notes:**
From looking in the Metabase config database, the table: 'core_user' appears to be storing AD password hashes. Comparing the password hash for a user that reported this issue with their password value in an older backup of the config database I saw that the password hash was the same.
I tested changing my own password and after logging in a few times to Metabase with both my old and new password I saw that my password hash had been updated in the config database, and I was no longer able to log in with my old AD password.

Based on this behavior I am guessing that the current authentication works as follows:
_User tries to log in.
  If username/password matches what is in the 'core_user' table accept the login.
  Else do a LDAP lookup to validate the credentials._

If this is the case it might make more sense to always to a LDAP lookup, and only rely on the local database if the LDAP server is unavailable.
Better yet, do not store the password hash for accounts tied to LDAP authentication.

**Comment by senior** [comment]
@marcusit I open https://github.com/metabase/metabase/pull/7913 to fix this issue. Could you test it and confirm that it fixes your issue?

**Comment by marcusit** [comment]
I am still able to authenticate with both the old and the new password using an existing user account.
I also tested to remove my account from the "core_user" table and log in, verifying that my user account was recreated, and I was still able to log in with both the old and the new LDAP password.

Does it make any difference that I am using a MySQL database for the Metabase config?
Java variables used:
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=TEST-mydb-per
export MB_DB_PORT=3306
export MB_DB_USER=metabase_test
export MB_DB_PASS=
export MB_DB_HOST=
export MB_PASSWORD_COMPLEXITY=strong
export MB_PASSWORD_LENGTH=8
export MB_ENCRYPTION_SECRET_KEY=

Version running:
![image](https://user-images.githubusercontent.com/15941905/41722273-f4d32a96-7535-11e8-813c-acb974596e15.png)

**Comment by senior** [comment]
@marcusit one thing you brought up in your most recent comment that I want to call out is that you your existing users did not have their password cleared. I think it's a good idea to clear those (and I will add that) but the code does not currently modifying existing user's passwords right now.

**Comment by marcusit** [comment]
I seems like the issue is with Active Directory. That being said I think it is still a good idea to not store the LDAP password hash.

I fired up Wireshark to get more information. I am not using encryption so the LDAP auth traffic is in plain text.
Test passwords used:
SecretPa$$w0rdOld
SecretPa$$w0rdNew

I changed my password and logged in with my new password. We can see the LDAP request come across with the new password:
![image](https://user-images.githubusercontent.com/15941905/41782016-fdcbe7c4-7606-11e8-9c78-c17dbed9d5a7.png)

Response from the domain controller:
![image](https://user-images.githubusercontent.com/15941905/41782045-1250df10-7607-11e8-9214-b739d6933c6a.png)

Login with old password shortly after:
![image](https://user-images.githubusercontent.com/15941905/41782100-3ed73886-7607-11e8-8f9b-8e65aaea145d.png)

Response from DC:
![image](https://user-images.githubusercontent.com/15941905/41782122-5707667e-7607-11e8-9371-633c4dca1648.png)

**Comment by senior** [comment]
@marcusit Thanks for the update! I agree that it's still a good change to not store those passwords and will work on getting #7913 after I get the code in place to remove those passwords from existing users.

If you figure out the problem could you add a comment to the issue to help other Active Directory users in the future? One thing you might check is if there's any anonymous bind behavior going on with Active Directory. I don't have a lot of experience with AD, but I have heard that can cause issues like this.

**Comment by wwwiiilll** [comment]
Just saying that the password saving was intended to be a feature, just like JIRA does with the "Hybrid Directory" or , so that if the DC is down, users aren't locked out.

But from what I understand here, the issue is rather AD that is wrongly returning "success" even though the password is wrong and not MB storing the password.

**Comment by wwwiiilll** [comment]
Apparently it's a "feature" of Active Directory, the old password still stays valid for 1 hour after change. See: http://support.microsoft.com/kb/906305

**Comment by salsakran** [comment]
@wwwiiilll how strongly do you feel about that password caching in your own running of Metabase internally?

From our perspective, it opens up security surface area (read: someone will still have a valid account even after they are removed from AD, and eg be able to log in after being fired). Without some sort of call-back (which to my knowledge doesn't exist in AD), there's no real way to tell other than polling LDAP anyway and if it's up, and deny's the user, then locking their account. 

Not a huge fan of this behaviour, and we'd like to remove it. But if you have strong feelings we should talk it through.

**Comment by senior** [comment]
Two more things to add to what @salsakran said. It could be confusing behavior. If the user hasn't logged to Metabase since they've changed their password and LDAP goes down, their password "won't work" because it will expect the old password.

It also increases the surface area of attack on the LDAP system. My guess is people will approach securing their LDAP system differently than their Metabase system. If someone was to steal the Metabase application database, it wouldn't just be Metabase that was compromised, but the LDAP system too. They would have the password of every LDAP user that logged into Metabase system. Those passwords would be encrypted but once cracked would have access to everything else.

**Comment by wwwiiilll** [comment]
I was mainly explaining the reasoning behind the current behavior.
I wouldn't mind too much if we removed the password caching. After all, should LDAP go down for a while, users would have the option of resetting that random password to set a temporary one.

But still, we won't be able to do anything about AD keeping the old password active.

**Comment by marcusit** [comment]
From an operations perspective, AD being down is a much larger issue in itself than users not being able to log into Metabase due to AD being down.
For what is is worth I think it makes more sense to leave all authentication to LDAP and not store any cached credentials for security reasons.

**Comment by senior** [comment]
Thanks @marcusit and @wwwiiilll. I just merged #7913 which avoids storing passwords for LDAP users. It should be included in 0.30.0 which should be released soon.
