### ISSUE TITLE
crate 2.3.3 does not work with metabase v0.29.3

### ISSUE THREAD

**Issue by on99** [metabase/metabase#7636]
### Bugs

- Your browser and the version: Firefox Quantum 60.0
- Your operating system: OS X 10
- Your databases: crate 2.3.3
- Metabase version: 0.29.3
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue*

```bash
$ docker pull crate:2.3.3
$ docker pull metabase/metabase:v0.29.3
$ docker run -d -p 4200:4200 -p 4300:4300 -p 5432:5432 crate --name crate -Cnetwork.host=_site_
$ docker run -d -p 3000:3000 -v ~/.metabase:/metabase-data -e "MB_DB_FILE=/metabase-data/metabase.db" --name metabase metabase/metabase
$ docker logs -f metabase
```

Add a crate database in metabase admin panel, and every time click Sync database schema now button from the admin panel, you can see the error log from console.

refs https://github.com/crate/crate/issues/6976

**Comment by camsaul** [comment]
Hi @on99, starting with Metabase 0.32.0 we're removing the CrateDB driver from the core Metabase project and instead making it available as a community-supported driver. When you upgrade to Metabase v0.32.0+, you can download the Crate driver and see instructions to install it here: https://github.com/metabase/crate-driver. 

If you're still having problems with CrateDB, please open an issue at https://github.com/metabase/crate-driver/issues

**Comment by on99** [comment]
@camsaul Thanks for notifying!
