### ISSUE TITLE
Query failure: Error writing file '/rdsdbdata/tmp/MYJ8sDcA' Errcode: 28 - No space left on device

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7637]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 66.0.3359.139
- Your operating system: Ubuntu 18.04
- Your databases: MySQL, Postgres, SQL Server
- Metabase version: v0.29.3
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: Postgres

- This is appearing on Logs from metabase:
`
May 14 15:47:26 WARN metabase.query-processor :: Query failure: java.sql.SQLException: Error writing file '/rdsdbdata/tmp/MYJ8sDcA' (Errcode: 28 - No space left on device)
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:211)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:204)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:244)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:237)"
"query_processor$fn__31515$process_query_and_save_execution_BANG___31520$fn__31521.invoke(query_processor.clj:283)"
"query_processor$fn__31515$process_query_and_save_execution_BANG___31520.invoke(query_processor.clj:269)"
"api.card$run_query_for_card.invokeStatic(card.clj:608)"
"api.card$run_query_for_card.doInvoke(card.clj:594)"
"api.card$fn__41349$fn__41352$fn__41353.invoke(card.clj:615)"
"api.card$fn__41349$fn__41352.invoke(card.clj:614)"
"api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)"
"api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)"
"api.card$fn__41349.invokeStatic(card.clj:610)"
"api.card$fn__41349.invoke(card.clj:610)"
"middleware$enforce_authentication$fn__38606.invoke(middleware.clj:118)"
"api.routes$fn__49681.invokeStatic(routes.clj:65)"
"api.routes$fn__49681.invoke(routes.clj:65)"
"routes$fn__49772$fn__49773.doInvoke(routes.clj:108)"
"routes$fn__49772.invokeStatic(routes.clj:103)"
"routes$fn__49772.invoke(routes.clj:103)"
"middleware$log_api_call$fn__38705$fn__38707.invoke(middleware.clj:349)"
"middleware$log_api_call$fn__38705.invoke(middleware.clj:348)"
"middleware$add_security_headers$fn__38655.invoke(middleware.clj:251)"
"core$wrap_streamed_json_response$fn__55123.invoke(core.clj:67)"
"middleware$bind_current_user$fn__38610.invoke(middleware.clj:139)"
"middleware$maybe_set_site_url$fn__38659.invoke(middleware.clj:275)"]
`

The server host of Beanstalk is only 19% used of the disk.

-------

**Comment by senior** [comment]
Although the error is coming from Metabase, it looks to me like it is your MySQL instance that is out of disk space. Metabase is trying to connect, or run a query and it can't due to the disk on the MySQL instance being full (or maybe out of inodes or something similar). You should check the MySQL RDS Instance's `/rdsdbdata` filesystem has space on it.

**Comment by salsakran** [comment]
Yeah, closing this since the error seems pretty clear. 

I'd suggest checking out the disk space remaining on your application database (the RDS DB for metabase) and the database you're trying to query.

**Comment by dannyeuu** [comment]
@senior and @salsakran As you see in my bug reference, I use for Metabase backend database an RDS Postgres that has 8GB Free

**Comment by uni4online** [comment]
We are having the same error with MEtabase connecting to one of our RDS instances and we have over 100Gb free on the RDS instance.

**Comment by flamber** [comment]
@uni4online 
You need to check if there's space left on `/rdsdbdata` or `/rdsdbdata/tmp` depending on how your file system is sliced.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by egovedarov** [comment]
Maybe you can check this article:
https://aws.amazon.com/blogs/database/best-practices-for-configuring-parameters-for-amazon-rds-for-mysql-part-1-parameters-related-to-performance/
Search for `tmp_table_size`. 
Also this might be of help:
https://stackoverflow.com/questions/66172397/mysql-temp-table-location
