### ISSUE TITLE
Floating maps in public links & embeds

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#7638]
Though not without a certain esthetic charm, geojsons acquire a distinct superiority complex over all other elements floating above hovertags and filters.  This mischief appears limited to public links & embeds for "Questions", geojsons are (so far) well behaved for Dashboards and within Metabase itself.  Please patch along with related issue ticket <a href="https://github.com/metabase/metabase/issues/7486">#7486</a>, users will surely expect functional maps.

An anonymized illustration appears below; reproduce the bug with this <a href="https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/california-counties.geojson">raw github geojson</a> and the following array of values:

NAME, Alameda, Amador, Calaveras, Colusa, Contra Costa, El Dorado, Fresno, Glenn, Humboldt, Kern, Kings, Lake, Los Angeles, Madera, Mariposa, Mendocino, Merced, Monterey, Napa, Nevada, Placer, Riverside, Sacramento, San Benito, San Bernardino, San Diego, San Joaquin, San Luis Obispo, San Mateo, Santa Barbara, Santa Clara, Santa Cruz, Shasta, Siskiyou, Solano, Sonoma, Stanislaus, Sutter, Tehama, Trinity, Tulare, Tuolumne, Ventura, Yolo, Yuba
AGE, 18.6, 19, 15.5, 22.8, 18, 18, 15.8, 23, 17.8, 21.8, 11.5, 19.1, 17.9, 20.2, 15.2, 20.7, 20.7, 17.8, 18.8, 23.9, 10.9, 18, 17.6, 15, 21, 12.1, 18.3, 17.3, 13, 17.1, 16.3, 18.1, 22, 14, 18, 20, 18.2, 17, 15, 12.6, 14.7, 17, 8, 17.4, 19
![floatingmapproblemanon](https://user-images.githubusercontent.com/38047661/40009161-1c67c092-5756-11e8-9450-3834ac2ed51e.jpg)

Metabase: 0.29.2
Java: 1.8.0_45
Databases: H2 internal default
Host: Localhost:3000
OS: Microsoft Windows [Version 6.0.6002]
Browser: Firefox 52.8.0

**Comment by salsakran** [comment]
That's breathtakingly beautiful. Sadly, we should fix it and remove its glory from this world.

**Comment by flamber** [comment]
Fixed by #9916 in 0.32.6
