### ISSUE TITLE
send admin an email when a user invite is accepted

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#764]
just a nice way to confirm for admins when the users they invite to the application actually accept and start using Metabase.

**Comment by mazameli** [comment]
Should we send this email to all admins or just the admin that did the inviting? I'm thinking the latter.

**Comment by salsakran** [comment]
Good question. 

The reason this is coming up is for situations where a new user logs in and the account is created, as via SSO. 

My hunch is everyone, as there won't necessarily be a single admin doing the inviting. Should this be YetAnotherKnob?

**Comment by kdoh** [comment]
My inclination would be:
- For non SSO send the email to the user who created that account - "So and so accepted your invite, warm fuzzies abound"
- For SSO account creations my gut says send those to all admins and figure out a clean way to opt out of emails.

**Comment by kdoh** [comment]
For the opting out I'm imagining we could add a setting to the user profile where if you're an admin you can see the option to unsubscribe from "new user emails" since that'd work fairly nicely with a more broad email preferences scheme as the app starts to send more and more email for different types of activity.

**Comment by mazameli** [comment]
;)

![artboard](https://cloud.githubusercontent.com/assets/2223916/16426040/40232a0e-3d1c-11e6-911f-6a0395033932.png)

But yes, good call re: SSO, and I like the idea that it's a per-admin setting rather than a global one. I think this is a single setting though, i.e. for all invite emails, SSO or not, because otherwise you're really getting into Knob Town (entirely different meaning if you're from the UK), with a separate setting for invites you send vs. SSO enrollments.

Far in the future, we can also explore batching together a summary email of new users or something if you're dealing with really large deployments.

**Comment by salsakran** [comment]
Is this the point where the user profile/settings page is actually a useful piece of real estate vs a hairball of antiquated css?

**Comment by mazameli** [comment]
Yeah, makes sense, though let's make that a separate issue and revisit the design of that section in the context of "Add ability to manage notification preferences in `Account Settings`."

**Comment by mazameli** [comment]
In addition to the regular invite notification, I also started thinking through what we should do when people join Metabase via SSO (i.e. notify admins that a new user has joined), and also what might an admin want to do regarding that user's permissions. If an admin invites a single user, they'll have the opportunity to set all their permissions during the process of inviting; but if a user joins via SSO, probably the only thing we can do automatically is assign them to the default permission group — hence the button link to go to the user's settings.


Invite accepted:

![invite accepted](https://cloud.githubusercontent.com/assets/2223916/16507799/9d9a3da0-3ee1-11e6-9409-9e9d1afc3318.png)


Joined via SSO:

![joined via sso](https://cloud.githubusercontent.com/assets/2223916/16507803/a3e79284-3ee1-11e6-8405-aa7facf24a95.png)

**Comment by kdoh** [comment]
As I'm looking at these something about the treatment of "See <name>'s settings" makes it feel very black box-y and so I'm inclined to be a bit worried. In a world of permissions and possible groups it seems like the better approach would be to show the default group(s) a user was added to in the email itself, that way if everything's ok I can rest easy and if I think Kyle is an untrustworthy fella then I can do something about it.

**Comment by mazameli** [comment]
Totally. I honestly forgot that I'd thought to include the groups — moving too fast! Thanks.

**Comment by mazameli** [comment]
Something like this, methinks. If we get to this issue before Permissions, then of course we'd just leave out the list of permission groups:

![invite accepted](https://cloud.githubusercontent.com/assets/2223916/16532058/5b7ba08c-3f84-11e6-872d-ce4390542ce6.png)

![joined via sso](https://cloud.githubusercontent.com/assets/2223916/16532060/5e6da588-3f84-11e6-91c6-e78928b8b4e3.png)

**Comment by salsakran** [comment]
I'm ok with the last, though I'd change "GoogleAuth" to "their Google Account" or something similar. GoogleAuth sounds excessively techy, even for admins

**Comment by mazameli** [comment]
Agreed. "kyle.lastname@googlebizacct.com joined with their Google account at 1:03 PM, 6/28/2016"

**Comment by salsakran** [comment]
@mazameli is this ready to be be implemented?

**Comment by mazameli** [comment]
Yep, I think it's good to go. We obviously don't have permission groups yet, so we'll need to omit that section. And we'll need to confirm that the `Edit [user]'s settings` button can open up the relevant modal in the People section of the admin panel (if it can't, the button can just go to the People section).

**Comment by camsaul** [comment]
I emailed kyle.lastname@googlebizacct.com yesterday to confirm he got the email but I haven't heard back :/

**Comment by camsaul** [comment]
Implemented in #2927

**Comment by snarfed** [comment]
hi all! i noticed the old discussion here around letting admins opt out of new SSO user emails. what's the current thinking on that? we'd like it. :P want me to file an issue?
