### ISSUE TITLE
running multiple metabase containers on single VM

### ISSUE THREAD

**Issue by VikramTiwari** [metabase/metabase#7643]
I was running multiple metabase containers on a single VM instance I noticed multiple issues. Here they are:

- During container startup and `cache_field_values_schedule`, each container tries to use 100% of the CPU thus slowing down all the running containers. This also makes anything else running on that VM to be stopped.

- At very few times while starting up a container it would suddenly start using a lot of disk IO operations thus causing the whole machine to just stop responding until VM was reset.

One possible solution to these issues is to limit the resource utilization. This can be done via docker (https://docs.docker.com/config/containers/resource_constraints/). But there are times when this doesn't work, for example, while running metabase as a standalone JAR file or using docker in old operating systems which do not support cgroups.

Are there any best practices from team's side on this?

**Comment by flamber** [comment]
A lot has changed since this issue was created, and scheduling is handled differently now - with the ability to change time:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#choose-when-metabase-syncs-and-scans
