### ISSUE TITLE
Field filter mapping dropdown gets cut off

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7647]
I saw [this issue](http://discourse.metabase.com/t/tables-list-not-properly-displayed-in-field-filter/3564) reported on Discourse and recalled that I've seen it before myself.

Very often, when trying to select a table or field in the field filter mapping popover menu, its contents get too tall and it gets chopped off at the top of the screen, making it impossible to select tables at the top. 

To reproduce, I've found that it happens reliably when my viewport is _shorter_ than ~750px, and when dealing with a DB with more than 10 tables.

**Discourse users's example:**

![image](https://user-images.githubusercontent.com/2223916/40082137-f31ab722-5844-11e8-8895-b10df1ba5572.png)

**My example on master using Chrome on macOS:**

![screen shot 2018-05-15 at 1 40 43 pm](https://user-images.githubusercontent.com/2223916/40082375-a9df7772-5845-11e8-86e7-3114ff0cee44.png)

**Comment by flamber** [comment]
Hi @mazameli 
I cannot reproduce this issue on 0.31.2 with Firefox 65 and Chromium 71 on small viewport.
But it now creates a double scroll, which means, when you scroll to the bottom, then you have to scroll one more time to the bottom.
![image](https://user-images.githubusercontent.com/1447303/53125519-d24e8700-3523-11e9-9e60-f2d719173fe0.png)

**Comment by regiohelden-dev** [comment]
Same here.
![image](https://user-images.githubusercontent.com/3070722/67572022-a2e8bd80-f735-11e9-83da-974770ac9812.png)
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit) on Ubuntu 19.04

**Comment by flamber** [comment]
@regiohelden-dev That's a different type of dropdown. There's an issue open about making interface better, when handling many columns - #10460 - upvote by clicking :+1: on the first post.

**Comment by mazameli** [comment]
Can't reproduce this on 0.33.5 anymore.

**Comment by mazameli** [comment]
@flamber, issue for double scrollbars here (originally was about data selection, but I'm also seeing it when setting up field filters as you mentioned): https://github.com/metabase/metabase/issues/5829
