### ISSUE TITLE
Feature request : Update data model daily

### ISSUE THREAD

**Issue by KyFly-ESIEA** [metabase/metabase#7651]
Hello everyone,

*I searched with the "New Feature" and "Enhancement" tag, I think I'm the first to ask this.*

Today, for large DB, we can whether choose if Metabase syncs data model by itself. If the sync is set to "auto", Metabase syncs the data model hourly.

I would like to be able to choose the uptime for this auto sync.

This is particularly useful if a DB contains a large view (12 min to load) and when Metabase does a "COUNT(*)" on it. My data do not change a lot during a day, this feature would be very useful.

Cheers.

**Comment by hagen** [comment]
Admin Panel > Databases > toggle "This is a large database, so let me...."
![image](https://user-images.githubusercontent.com/5161952/40149928-f0bf1f1a-59b9-11e8-86c2-e2140aa493ed.png)

Save.
Up top, you'll see a schedule tab appear. Go to that tab. Enter your preferred cron schedule.
![image](https://user-images.githubusercontent.com/5161952/40149921-e7228348-59b9-11e8-84dd-26f942c84ee4.png)

**Comment by KyFly-ESIEA** [comment]
This is what i wanted, thank you for your responses

**Comment by mazameli** [comment]
Sweet. I'll go ahead and close this issue then.
