### ISSUE TITLE
iframed dashboard breaks Category filter 

### ISSUE THREAD

**Issue by seventrust** [metabase/metabase#7653]
Hi everyone,

I have to report a bug, it happens that when selecting a category filter option the dashboard that is iframed ends up exceeding the iframe, for reference the following GIF:
![reportes-en-linea-m1_-normativa-y-regulacion-nacional-pa](https://user-images.githubusercontent.com/1132539/40143533-adf9579e-5929-11e8-9140-78ba082536e5.gif)

This problem occurs for Firefox browser latest version 60.0

**Comment by programwar** [comment]
Hello everyone,

I'm facing also this issue. There is any workaround to solve it?

**Comment by flamber** [comment]
I cannot reproduce on 0.41.2, but there has been a lot of changes to embedding and filters.
