### ISSUE TITLE
Is Metabase really free?

### ISSUE THREAD

**Issue by numediaweb** [metabase/metabase#7657]
I'am confused about the licensing scheme adopted by Metabse. 
While it is Open Source which means I can do whatever I want with it including the change of logo, design, branding texts.. I found this confusing text in the [Embedding License](https://www.metabase.com/license/embedding/)  that states:

> 3. Ownership. The copy of the Software is licensed, not sold. You own the media on which the Software is recorded, but Metabase retains ownership of the copy of the Software itself, including all intellectual property rights therein. The Software is protected by United States copyright law and international treaties. **You will not delete or in any manner alter the copyright, trademark, and other proprietary rights notices or markings appearing on the Software as delivered to you. This includes the removal of the Metabase’s name or logo in the iframe that is embedded in your application**

Also checking the forums I found that [a licence must be purchased](http://discourse.metabase.com/t/can-we-used-metabase-commercially/3192/4) for custom branding.
So this is confusing: I want to alter the code and brand Metabase and include it into my existing app? according to the embeeding licence I cannot do that for free.. Or am I missing something?

Thanks

**Comment by joebordes** [comment]
Open source does not mean you can do whatever you want. There are an enormous plethora of different licenses out there that will permit you to do more or less with the code the producer shares with you. Some may prohibit you from doing anything!

In this case, Metabase does not permit you to rebrand without some restrictions. If you need to rebrand you have to buy a token to do so (at least). You should contact them for exact details.

**Comment by numediaweb** [comment]
It states in [Premium embedding](https://www.metabase.com/docs/latest/administration-guide/13-embedding.html#premium-embedding): 

> If you’d like to embed Metabase dashboards or charts in your application without the “Powered by Metabase” attribution, you can purchase premium embedding from the Metabase store. 

But once you go to the [Premium Embedding](https://store.metabase.com/product/embedding) page and check [the licence](https://www.metabase.com/license/premium_embedding/) you see the opposite! and you cannot change the logo even if you payed for.

**Comment by salsakran** [comment]
@numediaweb 
There are a couple of things going on - 
1. The Metabase application is open source (under the APGL) and free. You can use it as you desire, so long as you abide by the APGL. Note that AGPL licensed code is very different from "Open Source which means I can do whatever I want with it" code, which is more what MIT or other more permissive licenses allow.   
2. If you want to embed our widgets in your application you can either
  a. Embed them using our free license (https://github.com/metabase/metabase/blob/master/LICENSE-EMBEDDING.txt) which applies to the embedding Javascript you call from your application.  This is free, but we ask that you leave our logo and url in the div
  b. Embed them using our paid license (https://www.metabase.com/license/premium_embedding), which is really the same as (a), but our server will drop the attribution logo + url. 
  c. Modify/etc, but abide by the AGPL. Note that a+b above are specifically  _optional_ _exemptions_  from the APGL. 

License details aside, philosophically, what we're trying to do is:
Give anyone a free, open source way to power their company's internal analytics.

For cases where you make money off of Metabase, or power you own product (that makes money) off of Metabase, we ask that you support the project by purchasing a commercial license. The core team has written over 100,000 lines of code, in 15,000 commits over three years, and is giving the product to anyone who wants to use it, while similar competing commercial products cost 10s or 100s of thousands of dollars. We ask that if you intend to make money from all of the work we put into the project, you support it.

**Comment by numediaweb** [comment]
Thanks @salsakran 
I totally agree that Metabase should get financial support depending on the initial business plan.
From my understanding of AGPL if i make change to the code then I have to share it with the community back:

> The Affero GPL is designed to close the so-called "application service provider loophole" in the GPL, which lets ASPs use GPL code without distributing their changes back to the open source community. Under the AGPL, if you use code in a web service, you required to open source it.

However this doesn't answer the branding question and couldn't find anything about that in AGPL license.

You also said:  
> which is really the same as (a), but our server will drop the attribution logo + url..
In my case Metabase is hosted on MY own servers so I really don't understand your statement.

So still not really crystal clear all this licensing scheme: lot of confusion regarding white labelling and Embedding that I hope someone would make it clear and easy to understand.

**Comment by salsakran** [comment]
I've updated my comment to clarify the previously ambiguous use of "server" (not "Metabase application server").

@numediaweb what exactly are you trying to accomplish here? 

We've answered your questions, and while you might not like the answers, I think they've been pretty clear. Note that while you can definitely remove the branding via convoluted things like nginx re-writing rules, our intention for the embedding feature is pretty clear. I'll close with saying one last time that we've put a lot of work into the product, and ask that if you want to use our work, you use it in the spirit in which we've released it.

**Comment by salsakran** [comment]
Closing this since it's not really a topic of conversation for the issue tracker, which is intended to be used to play work around features, bugs, etc.

@erix920 I believe I responded to your email, but if that wasn't you, please reach out to us via https://www.metabase.com/services/ and I'l reply right away.
