### ISSUE TITLE
Metabot cannot retrieve questions that are saved in collections

### ISSUE THREAD

**Issue by sturgill** [metabase/metabase#7660]
Metabase is self-hosted on an EC2 instance. We are using an RDS MySQL server instead of H2. Metabase connects to a single Redshift cluster.

I have enabled Metabot with the appropriate Slack token. When I save a question, I can run the command `metabot show 2` and it works as expected. However, if I move that question to a collection, I get the nefarious `You don't have permission to do that.` message in Slack.

Moving the question back out of the collection resolves the issue and it can be access by Metabot again.

![metabot](https://user-images.githubusercontent.com/1447882/40205073-517b01f8-59f0-11e8-80d3-24ded94451d3.png)

![metabot-permissions](https://user-images.githubusercontent.com/1447882/40205084-5f51848c-59f0-11e8-81eb-d0219da98b73.png)

**Comment by sturgill** [comment]
Okay, this problem is resolved if I give the MetaBot user curation privileges for the collection. Doesn't feel like the "right" solution, but it will work.

**Comment by dgilouz** [comment]
Thank you @sturgill. That worked!!

**Comment by lp-lima** [comment]
"Workaroundable", but yet worthy of some attention, I guess. Just stumbled into the same issue.

**Comment by flyingmachine** [comment]
might be related to #6303

**Comment by camsaul** [comment]
This is by design, you have to give MetaBot view permissions for the Collection a Saved Question is in in order for it to be able to display them
