### ISSUE TITLE
metabase with large Databases issues

### ISSUE THREAD

**Issue by Sieboldianus** [metabase/metabase#7663]
I read a couple of threads and there exist some reports that x-rays and general work with metabase and large Databases is problematic. I was wondering if there is a guide somewhere on how to setup metabase, so that it works (perhaps with reduced functionality) with large Databases.

We just set up metabase, and it looks great! But it takes forever to load. The initial x-ray Count(*) of our largest table takes about 7 hours - not surprising given a size of 350 Million rows. Our total database with 7 tables is currently about 300GB, we expect it to increase by 1-2 TB in the next months. We do have a lot of indexes and regular auto-vacuum etc., but it is impossible to get these distinct counts any faster on Postgres currently (we are aiming for HyperLogLog structure, but that is still far ahead). We usually substitute Distinct Counts with Estimates, which is much faster and totally enough for us as far as general statistics/overview.

I saw this picture:
[http://d.pr/i/mLntm4](http://d.pr/i/mLntm4) referenced somewhere, but I can't find the respective setting in our metabase setup. Is this gone in the newest version of metabase?

Are there any recommendations on how to setup metabase, based on experiences with other large data structures?

Many thanks!

### Database support

- we currently run Postgres 10.0 on a dedicated Server with 16GB RAM/QuadCore
- metabase in newest version, runs on a separate Virtual Machine with 8GB/DualCore

**Comment by lindsay-stevens** [comment]
Some ideas for the Postgres side of things - if the questions of interest:

- involve more than one column, evaluate the "Multivariate N-Distinct Counts" extended statistics type: https://www.postgresql.org/docs/current/static/planner-stats.html
- involve a subset of the table(s), evaluate declarative table partitioning https://www.postgresql.org/docs/current/static/ddl-partitioning.html
- involve data that never (or rarely) changes again, consider creating roll-up tables that store computed historical summaries, such that something like the following query could be executed in Metabase:

```sql
SELECT 
  live.field,
  count(DISTINCT live.field) FILTER (
    WHERE live.timestamp > stored.max_timestamp
  ) + coalesce(stored.count, 0) AS total_count
FROM (
  SELECT
    field, 
    timestamp
  FROM live_table
) AS live
LEFT JOIN (
  SELECT
    field,
    count,
    max_timestamp
  FROM stored_counts
) AS stored
  ON stored.field = live_table.field
GROUP BY
  live.field,
  stored.count
```

Also: 

- check that the Postgres GUCs are making full use of the available 16GB RAM. Many GUCs can be set per-user e.g. the Metabase connection user could be allowed loads of work_mem, but regular connections could get a smaller amount. https://www.postgresql.org/docs/current/static/runtime-config-resource.html
- consider other index types, if only B-Tree (default) are being used - BRIN or Hash might deliver faster results https://www.postgresql.org/docs/current/static/indexes-types.html
- if an approximate count is acceptable, specifying the query with a `TABLESAMPLE` percentage (with type `SYSTEM`) might help https://www.postgresql.org/docs/current/static/sql-select.html

**Comment by Sieboldianus** [comment]
Many thanks Lindsay-stevens, these suggestions sounds promising and I don't remember seeing any of these solutions when we were working on optimizing out Postgres db for speed, I will definitely try those out.

In the meantime, is there any setting in Metabase where I can turn off automatic parsing of the whole database (eg. no hourly/daily checks at all, no clickable links that trigger those super-long taking queries)? Then we could still try out Metabase interface for some smaller questions/ecplicit SQL queries where we know that they work on our current setup.

**Comment by jornh** [comment]
You can turn off [Database Sync and Analysis](https://metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis) under database config

**Comment by Sieboldianus** [comment]
Thanks @jornh! I already turnded this off. However, I finally found the X-Rays setting under Admin/X-Rays. For some reason, I believed to find this as a sub-setting for each database-connection and not for the whole Metabase. It would be awesome if we could select wheather Metabase is doing Approximate, Exact or Extended statistics for each database-connection individually. Then we could choose "Approximate" for the giant big db, and if we need more exact statistics, we extract a subset to a db-partition, link it to Metabase as a separate database, and choose "Extended".

Many thanks for comments, overall my Metabase learning curve was quite steep and it feels well-thought through, kudos!

**Comment by sbelak** [comment]
Note that starting with .29 we have retired this version of xrays in favour of the next generation that pushes most of the computation into the DB and works more like how you'd use MB manually (ie. making questions and dashboards). See this blog post for more: https://www.metabase.com/blog/metabase-0.29/index.html

**Comment by salsakran** [comment]
closing this issue since as @sbelak mentioned, we changed the entire approach.
