### ISSUE TITLE
Use the same hover effect and click target for table cells in dashboards as we do elsewhere

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7668]
It's currently hard to tell that cells in tables on dashboards are clickable:

![dash-card-hover](https://user-images.githubusercontent.com/2223916/40254482-82eb028a-5a98-11e8-8625-17473b731c83.gif)

Compare this to tables in questions, where the whole cell's area is a click target:

![normal-table-hover](https://user-images.githubusercontent.com/2223916/40254502-8ec796ea-5a98-11e8-8cab-9f08263d3ae2.gif)

**Comment by brunobergher** [comment]
Done at some point.
