### ISSUE TITLE
Segment's Tooltip Description and Definition is not showing in Create Custom Question View when hovering

### ISSUE THREAD

**Issue by joboyx** [metabase/metabase#7689]
## Bug
- Your browser and the version: Chrome (Ubuntu) Version 66.0.3359.170 (Official Build) (64-bit)
- Your operating system: Ubuntu 17.10
- Your databases: Oracle XE 11g
- Metabase version: v0.29.3
- Metabase hosting environment: Ubuntu 17.10 (localhost)
- Metabase internal database: MySQL

- Tried to search for "segment tooltip" in issues but nothing is related with this issue.

## How to Replicate
- When creating a new Question
- And when you hover to a Segment's Tooltip, no description and definition is being displayed.

![image](https://user-images.githubusercontent.com/920888/40401061-58334330-5e77-11e8-9e6a-e2c66872e7c5.png)

- From the image above, you can see that the menu was hovered but no data inside the element with `class = QuestionTooltipTarget`

## More Info
- Tooltip for Segment was still working on v0.28.1
- Also tooltip for Metric works fine in metabase v0.29.3

---

Thanks!!!
Keep it up guys! :)

**Comment by jornh** [comment]
Not surprising there’s a similar issue with segments as well: http://discourse.metabase.com/t/question-mark-on-segments-not-displaying-info/3600

**Comment by jornh** [comment]
@joboyx did you have a chance to test this on version 0.30.0 by now? 

If it works for you I think you can close this issue.

**Comment by joboyx** [comment]
@jornh, it's working now in 0.30

![image](https://user-images.githubusercontent.com/920888/44974583-b3b6fc80-af92-11e8-90b7-7d7673c9beda.png)

But the enclosing rounded box was truncated. Just a UI issue and not a deal breaker. Just nitpicking. :smiley:

**Comment by flamber** [comment]
Closing in favor of #10476
