### ISSUE TITLE
why there are only 2 database type

### ISSUE THREAD

**Issue by xjzhou** [metabase/metabase#7690]
![image](https://user-images.githubusercontent.com/1255410/40402913-f86a12c6-5e80-11e8-8659-01acc2479234.png)

Metabase version: v0.29.3
Metabase hosting environment: Metabase jar file
Metabase internal database: MySQL (migrate from H2 to MySQL)

**Comment by salsakran** [comment]
what version of java are you on?

**Comment by camsaul** [comment]
@xjzhou ?

**Comment by kdoh** [comment]
I'm going to go ahead and close this since we haven't received more info. @xjzhou if you are able to provide us with steps to replicate the issue in more detail or if others report similar behavior we can reopen this.
