### ISSUE TITLE
Error 500 whilst working

### ISSUE THREAD

**Issue by bruskiza** [metabase/metabase#7691]
### Occasional error 500

Intermittently on metabase 0.28.6, I get this 500 error:

```
Problem accessing /. Reason:

    General error: "java.lang.IllegalStateException: Reading from nio:/var/xxxx/metabase.db.mv.db failed; file length -1 read length 384 at 46605471 [1.4.194/1]"; SQL statement:
SELECT "ID" FROM "METABASE_DATABASE" WHERE "IS_SAMPLE" = TRUE LIMIT 1 [50000-194]
```

Restarting the process fixes it... and I will try upgrade to latest metabase.
I was just wondering if there's a a more "scientific" explanation than: "Hello IT, have you tried turning it off and on again? :)"

p.s. thanks for one of the coolest open source projects out there 🥇🥇we use it every day!

**Comment by salsakran** [comment]
can you fill out the information in the bug template?

this is a filesystem read error, and it's pretty much impossible to say anything more useful without knowing how you're running the server process and what the underlying filesystem is...

**Comment by mbvictoria** [comment]
Closing - has been marked as Needs More Info for almost a year.
