### ISSUE TITLE
Label displayed in dashboard card combining several questions does not change

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#7692]
Hi,
I have combined several questions in one card in a dashboard, e.g. displaying them as series in a line chart.
In the "customize this chart" setting of this card, I can change the series labels, but there are issues:
1. I have 4 series, but only 3 series label boxes are shown 
2. the change is not reflected in the chart, i.e. the series are still labeled as the orginial questions are called.

This looks like a bug to me.
Thanks for looking into this!

Your browser and the version: Chrome Version 66.0.3359.181 
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.0
Metabase hosting environment: Heroku

**Comment by salsakran** [comment]
Can you reproduce this with the sample dataset and share the questions you used?

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3 - please comment with steps to reproduce with Sample Dataset if you're still seeing this issue.
