### ISSUE TITLE
Only user with curate permissions should be able to see the edit icon or pin a dashboard to a collection

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7698]
If I have the curate/edit bit for a collection, I should be able to pin a dashboard to the collection.

**Comment by mazameli** [comment]
Current state of things:
- Non-admins with curate permissions for a collection are currently correctly allowed to pin/unpin things in that collection :clap:
- We’re incorrectly showing the pin icon to users who do not have curate perms, though, and clicking on it gives you a permissions error :(
- You can’t set permissions on the root collection yet, so anyone can currently pin/unpin things there.

**Comment by salsakran** [comment]
updated to reflect the current state of things
