### ISSUE TITLE
Pinned cards should have the same height

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7710]
These cards should have a fixed height that is tall enough to accommodate 95% of titles of saved items. A good litmus test is that titles of x-ray dashboards should almost always fit.

![pinned](https://user-images.githubusercontent.com/2223916/40510101-797dc72a-5f50-11e8-88a0-fd309da96e1b.png)

**Comment by brunobergher** [comment]
Fixed a long time ago.
