### ISSUE TITLE
Sharing modal got funky

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7717]
This is on master, and might be a result of those flex-full problems we'd been seeing?

![sharing](https://user-images.githubusercontent.com/2223916/40513683-58b19692-5f5b-11e8-9e99-0e8a68d1492f.png)

**Comment by tlrobinson** [comment]
There are a few other cases of this like #7426. We should collect them all in one place since the fix is probably similar for all of them.

**Comment by mazameli** [comment]
Duplicate of #7759, which was fixed and closed.
