### ISSUE TITLE
Add option for row count limit on Pulses

### ISSUE THREAD

**Issue by iamnotafatso** [metabase/metabase#7721]
Just noticed, the latest version of Metabase limits the result to a max of 10K rows.

Is it possible to have an option in the settings to change this hard cap, or to add an option to remove it completely?

**Comment by jornh** [comment]
Related: #7622 (I'd propose closing #7721 as a dupe and consolidate over on #7622)

**Comment by mazameli** [comment]
Agreed. (Thanks as always, @jornh.)
