### ISSUE TITLE
Bug: Months repeat on horizontal axis when data is grouped by month

### ISSUE THREAD

**Issue by lukabirsa** [metabase/metabase#7722]
I'm preparing some questions that include data grouping by month, but I have a problem with date (Y) axis. It seems that month labels are duplicated for a specific month. Hover data is OK!

See here:
![image](https://user-images.githubusercontent.com/534469/40547363-fd515c92-6031-11e8-9e1a-e2f602bb5610.png)

These are put together just like other questions where I do not experience this issue. I do not know how to reproduce this issue. 

A couple of data points:
- This is not related to browser.
- This happens on a postgresql database, but it looks like it happens on only one specific table
- The issue is the same if I have a custom SQL query or if I use the query editor. 
- If I change to weekly view the same happens - March gets repeated, while hover data is correct.
- We've noticed this somewhere around 0.27.x, and is still present in 0.29.3
- We run Docker with H2

**Comment by jornh** [comment]
Related: https://github.com/metabase/metabase/issues/5916 (is #7722 simply a dupe?)

There's this fairly recent related un-merged fix: https://github.com/metabase/metabase/pull/7247 (It would be pretty cool if you could verify it - by taking the [`timezone-tests`](https://github.com/metabase/metabase/tree/timezone-tests) branch for a test drive)

**Comment by tlrobinson** [comment]
Yeah I think this is a dupe, and should be fixed by #7247, but so far I haven't been able to find anyone to verify it (@lukabirsa if you've got a few minutes to pull down that branch and try it that would be great!)

**Comment by lukabirsa** [comment]
@tlrobinson I'm on the docker install, is there a simple way to deploy this?
