### ISSUE TITLE
Native query fails with commented-out parameter

### ISSUE THREAD

**Issue by Woodz** [metabase/metabase#7742]
*Environment*:
- Your browser and the version: 66.0.3359.139
- Your operating system: OSX 10.13.3
- Your databases: Sample dataset
- Metabase version: v0.28.5
- Metabase hosting environment: Unknown
- Metabase internal database: Redshift

*Repeatable steps to reproduce the issue*:
1. Create a new native SQL query
2. Enter query `SELECT * FROM REVIEWS WHERE PRODUCT_ID = 1 -- {{target_product_id}}`
3. Run query
4. Observe the error message `Unable to substitute 'target_product_id': param not specified. Found: ("target_product_id")` or `Cannot run the query: missing required parameters: #{"target_product_id"}`

The issue seems to be that the parser for detecting parameters is not aware of comments, so will pick up parameters that are commented out.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by dawnho** [comment]
+1

Got error: `org.postresql.util.PSQLException: The column index is out of range ...`

**Comment by salsakran** [comment]
For the moment, we're not parsing templates as full SQL before trying to inject template variables.

Until we do, you'll need to actually remove template variables and not just comment them out.

**Comment by andrewdibiasio6** [comment]
This may block adoption of our driver from existing client.
