### ISSUE TITLE
Having multiple databases as filters/or something different in a dashboard

### ISSUE THREAD

**Issue by hassannihal** [metabase/metabase#7745]
I have multiple databases for information on multiple facilitites. Is it possible to create a dashboard with questions where I can switch between different databases to check the performance of each of these facilities? The purpose of this is to avoid creating duplicate dashboards.

For example, by changing the URL can I view all the data in the dashboard where questions have already been framed?

**Comment by jornh** [comment]
This sounds a lot like https://github.com/metabase/metabase/issues/6496 - or are you asking for something different not covered by the existing feature request?

**Comment by salsakran** [comment]
We don't have a way to do that. Right now each question is tied to a specific database and table.

Honestly, it sounds like you should have a unified data warehouse with information about all your facilities.

**Comment by earonesty** [comment]
Depends.  Unifying data between dev/prod facilities, for example is a good idea.

**Comment by flamber** [comment]
Closing in favor of #6496
