### ISSUE TITLE
Can not able to connect to MongoDb which has ssl enabled

### ISSUE THREAD

**Issue by Sujay-shetty** [metabase/metabase#7756]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------
Hi,

It is really a nice tool for data visualization, thanks for building such a good tool.

With Local MongoDb it makes a connection and it is possible to visualize data in Metabase.

I'm facing issue in connecting to MongoDb which involves ssl authentication with certificate file.
![sample1](https://user-images.githubusercontent.com/7508108/40712935-7cdbf574-641c-11e8-95d2-cfd3ba233add.JPG)

Tried below link for SSL connection setup for MongoDb.
https://github.com/metabase/metabase/issues/3877

But that also did not worked it was throwing error :
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=bdtv2300.os.amadeus.net:27000, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]"} 

Could anyone please help me with this issue.

Thanks,
Sujay

**Comment by ShayChris** [comment]
Can you tell me how do you solve this problem?Thank you very much!
