### ISSUE TITLE
UI for nested collections

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7762]
Now that #7451 got merged (nice work, @camsaul!), we need:

- [x] UI to allow for saving new collections within another collection (just add the same selector for where the new collection should be saved as we've added to the new dashboard modal)
- [x] UI for moving a collection into/out of another collection (same move modal as with dashboards).
- [x] The UI for where to save/move artifacts will also need to allow for navigating down/up through the collections tree structure. I believe @kdoh had worked on designs for this already.

There's also an existing issue about how the collections permissions grid needs to support nested collections: https://github.com/metabase/metabase/issues/7471

**Comment by tlrobinson** [comment]
I think this is essentially complete.

**Comment by mazameli** [comment]
This is all functionally implemented and working in master now, though we'll need to do some small polish which I'll note in a separate issue.
