### ISSUE TITLE
Filter empty values of data columns and get error

### ISSUE THREAD

**Issue by MrPortra** [metabase/metabase#7765]
I use filters to filter null values of data columns in my question. 

Steps:
1) Choose data columns
2) use filters `is` or `is not`
3) Choose checkbox of `Empty` 

Then I get error like this:

`There was a problem with your question
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.
`
show error details:

`Valid value (must be nil, boolean, number, string, or a relative-datetime form)`

I tried to choose one empty unit in tables then use `=` or `!=`  to filter data columns and get same errors.

This problem appears on Druid, seems like get error on splicing the query statement.

*browser and the version:   Chrome 66.0
operating system:  OS X 10.11.16
databases:  Druid
Metabase version: 0.28.1
Metabase hosting environment:   Linux/Ubuntu 
Metabase internal database:  MySQL*

**Comment by flamber** [comment]
I'm pretty sure this was solved in version 0.32, but I haven't tested with Druid - https://github.com/metabase/metabase/issues/5299#issuecomment-463781960

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4
