### ISSUE TITLE
Displaying a bar chart with a nested json

### ISSUE THREAD

**Issue by javixeneize** [metabase/metabase#7774]
Hi

I have a mongoDB where i have nested JSON, it is, i have an structure like this:

{'car': 'carMaker', data: { 'date': 11-01-2001', 'value': '1000'}

I am trying to display a bar chart where i use data.date and data.value as the fields for the axis. However, when i select the axis, i can only select the first level data (car and data fields) and i cant access to the second level fields (date, value)

How can i access to that data to display the information i need?

Thanks

**Comment by flamber** [comment]
Closing in favor of #4098
