### ISSUE TITLE
"@" in Username is converted to "mailto:" HTML output

### ISSUE THREAD

**Issue by Sieboldianus** [metabase/metabase#7775]
### Bugs
- Your browser and the version: Version 66.0.3359.181
- Your operating system: Windows 7
- Your databases: PostgresQL 10.0
- Metabase version: Metabase 0.29.3
- Metabase hosting environment: Docker

We're working with Postgres, Flickr Data and Metabase and the Flickr-Usernames (e.g. `2054270181130@N00`) are interpreted as Mailadresses by Metabase. This is not a browser or database issue, as far as I can tell. I confirmed it is hardcoded in the Metabase HTML output:

```html
<div class="cellData"><a href="mailto:2054270181130@N00" class="link" target="_blank" rel="noopener">2054270181130@N00</a></div>
```
The Usernames are stored as Strings in our Postgres Database.

**Comment by jornh** [comment]
It’s probably just Metabase trying to be (in this case *too*) clever about sniffing types on data read from the database. Try looking at [metadata settings](https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html) and see if you can’t force your Flickr username field to a better type for your use.

**Comment by Sieboldianus** [comment]
Apologies for incorrect reference: its not the Username, its the `UserGUID` that has this `@` in the name. The `UserGUID` column is correctly identified as `Entity Key` in Metabase. The configuration further says User `original value` under `Display Values` (and I can select nothing else).

Should I use the Type `User`? But then, the `UserGuid` cannot be used as an Entity Key anymore?

**Comment by jornh** [comment]
Ah, well that paints a different picture then. I guess if you need it as an entity key type then you’re stuck with a very particular combination of things that probably is a bug. Not sure what workaround could be feasible then, e.g. duplicating the field to a non-entity key field. Depends on what you want to achieve?

At least the case for reproduction and fix  is now better described (so this wasn’t all waste) 😉

**Comment by tlrobinson** [comment]
It looks like in `formatValue` we're using `formatStringFallback` for columns that *do* have a `special_type` that weren't previously handled, despite the comment that it's used for `fallback for formatting a string without a column special_type`

I think we should change:

https://github.com/metabase/metabase/blob/59ec3f6121074688565716e4a5dae35ee7bea66b/frontend/src/metabase/lib/formatting.js#L369-L371

to something like this:

```javascript
  } else if (typeof value === "string") {
    if (column && column.special_type != null) {
      return value;
    } else {
      return formatStringFallback(value, options);
    }
  } else {
```
