### ISSUE TITLE
Unable use custom sql as saved question in new question page

### ISSUE THREAD

**Issue by sumanmaity112** [metabase/metabase#7776]
Hi,
I am new to metabase. My requirement is to join two table and do some visualization on top of that. To achieve this I saved custom sql as a question, named as *patient_state_fstg_details_view*. I can see the saved question on **Questions** page. But when I am trying to do some visualization, I am unable to find it (patient_state_fstg_details_view) under *Saved Question* dropdown. I am adding the screenshot below

- **Questions** page

<img width="1403" alt="screenshot 2018-06-01 17 50 58" src="https://user-images.githubusercontent.com/15261043/40840491-8907e46c-65c4-11e8-8bdc-4c971e33e0d8.png">

- **New Question** page
<img width="684" alt="screenshot 2018-06-01 17 50 38" src="https://user-images.githubusercontent.com/15261043/40840555-dfafde46-65c4-11e8-9d7d-c6c210d0e33f.png">

Can anyone help me?

**Comment by mazameli** [comment]
Can you tell us please:
- Your Metabase version
- How and where you're running Metabase
- The type of database you're querying
- Your browser and operating system type and version

**Comment by mbvictoria** [comment]
Closing - has been needs more info for over a year, not reported by any other users.

**Comment by flamber** [comment]
@mbvictoria This is still an issue - even on master - but probably better described in #9027

**Comment by mbvictoria** [comment]
@flamber Thanks! Let's keep #9027 the canonical one.
