### ISSUE TITLE
Multiple filters are not visible in "filtered by" area (if I add more than 2-3)

### ISSUE THREAD

**Issue by ashalitkin** [metabase/metabase#7777]
If I add many filters (e.g. 4 and more) they become hidden somewhere. I can't see them, can't edit, can't delete.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/3977931/40848061-c46b62b6-65c6-11e8-92c1-bcdeec0850d2.png)

- Your browser and the version: Version 62.0.3202.94 (Official Build) (64-bit)
- Your operating system: Ubuntu 16:04
- Your databases: Redshift
- Metabase version: v0.29.3
- Metabase hosting environment:  Beanstalk, Docker
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
1. Create any question
2. Add 4-5 filters

**Comment by jornh** [comment]
The grey bar you have under `May 15` and `true` should work as a scroll-bar. What happens if you try dragging it?

**Comment by ashalitkin** [comment]
Right. Thank you, it  works! 
I don't know why but I expected the filter area size to be changed automatically or a vertical scroll :). Closing it.
