### ISSUE TITLE
X-Axis Labels Vanish On Resizing

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#7780]
Browser: Firefox 52.8.0
OS: Microsoft Windows [Version 6.0.6002]
Databases: H2 internal default, Server SQL external (joined in)
Metabase: 0.29.2
Host: Localhost:3000

Consolidation of values along the x-axis on resizing would be VERY helpful with time-series.  As is they just vanish on resizing in a dashboard or resizing the browser window.  Applies to charts & dashboards both native and embedded.
![image](https://user-images.githubusercontent.com/38047661/40856454-cfcb21d0-658c-11e8-9c23-b069e7da014f.png)
![image](https://user-images.githubusercontent.com/38047661/40856464-d6a12018-658c-11e8-90f9-40dbeb58837f.png)

**Comment by jornh** [comment]
If you look in  [metadata settings](https://www.metabase.com/docs/latest/administration-guide/03-metadata-editing.html) what type is your Year field set to? Try setting it to number if it’s not already.

To me it doesn’t look like your years are getting interpreted as dates/numbers and hence a time series but rather as a categorical type. I’m basing this on the vertical display of years which was a feature that got added in v0.28 or v0.29.

What’s the underlying data type in the database. If you can have it as a date type Metabase takes hints from that.

**Comment by MarcGJA** [comment]
Thanks for pointing that out @jornh, the field was changed to text in the custom query to permit each year to show.  And yes the text fix permitting labels to rotate was a massive improvement over the way it was before with all the labels running into each other.  As a date along with verifying the underlying table metadata for the field is "Number", however, the problem remains... At some point in resizing the values vanish.  For the time being the workaround is to reduce the time-span shown (3rd illustration).  But that too can only tolerate so much before the x-axis values disappear again on resizing.  At the root of the problem I suspect there that there are at least two problems: 1) number values do not rotate like text labels do and 2) whatever binning-type algo is being used to manage axis values doesn't have a requirement for at least 2 anchor values regardless of resizing.
![image](https://user-images.githubusercontent.com/38047661/40878482-cde66202-6646-11e8-9fc2-d565e8d94265.png)
![image](https://user-images.githubusercontent.com/38047661/40878486-d6bed742-6646-11e8-8c7b-d84df71afd8d.png)
![image](https://user-images.githubusercontent.com/38047661/40878492-f9cfeb7c-6646-11e8-8f63-1ddf3bfd75be.png)

**Comment by flamber** [comment]
Hi @MarcGJA 
Can you provide steps to reproduce with Sample Dataset?
In the upcoming 0.36.0, the x-axis ticks have better spacing - #11268
Looks almost like a duplicate of #7058

**Comment by MarcGJA** [comment]
Thanks @flamber, This issue is solved, time-series chart cards half the width of a dashboard have good x-axis labeling now for my purposes, my version is 0.34.3.  Understandably by the time a card gets down to a quarter the size of a dashboard, x-axis values disappear which is fine.  So I'm closing out this issue as solved.
