### ISSUE TITLE
Document grid maps

### ISSUE THREAD

**Issue by mausch** [metabase/metabase#7787]
I see there's a "grid map" visualisation but it's not documented in https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html .

I found some screenshots in https://github.com/metabase/metabase/pull/7348 but I have no idea how to get that "latitude 1 degree" binning/grouping option.

**Comment by flamber** [comment]
There has been a lot of changes, and there's now some documentation: https://www.metabase.com/learn/visualization/maps.html
Though, some known issues still exists #7782
