### ISSUE TITLE
Duplicate database reference in report_card

### ISSUE THREAD

**Issue by mausch** [metabase/metabase#7788]
Hi, I was looking into potential workarounds for #6485 and while browsing the Metabase database I found that the `report_card` table has both a `database_id` column and a `database` property in the `dataset_query` json column which seem to be duplicate.
Just wondering if there's a reason for this?

**Comment by salsakran** [comment]
We use database_id to route things in the query processor, but leave the query dictionary unaltered.

Closing this since it isn't really actionable and is imo a fairly trivial bit of redundant data.
