### ISSUE TITLE
Force metabase to show table columns as specified

### ISSUE THREAD

**Issue by alamoot** [metabase/metabase#7791]
Reasking [SO question](https://stackoverflow.com/questions/50684077/force-metabase-to-show-table-columns-as-specified?noredirect=1#comment88379836_50684077) here.

I'm using metabase for analytics visualizations with my data being loaded in Google's BigQuery (BQ).

I would like to see the table column names exactly as I specify them in my queries, but metabase was constantly changing them to be "more human readable". So I turned off the FRIENDLY TABLE AND FIELD NAMES flag on the admin setting. Disabling the flag removed bunch of unnecessary spaces and change in the case (upper to lower case and vice versa) of some letters, but I still don't see the headers as I specify them.

For example, consider this sample query:

```
#standardSQL
select 2 as num, "hello" as MESSAGE;
```
It shows up properly on BQ.

![screen shot 2018-06-04 at 11 11 44 am](https://user-images.githubusercontent.com/12401354/40931472-3b37cf54-67f9-11e8-933a-397aedcbb0f6.png)

Note that it kept the word MESSAGE in the same case as I had written in the query.

But metabase changes the case on the table columns:

![screen shot 2018-06-04 at 11 13 32 am](https://user-images.githubusercontent.com/12401354/40931459-2bc9dae4-67f9-11e8-948a-c27acbe0e909.png)

It changes MESSAGE to Message and num to Num. It always only keeps the first letter capitalize.

Is there any way to force metabase to show column names exactly as specified in the queries?

**Comment by TurkerTunali** [comment]
Did you try setting "Admin"-"Settings"-"General" "Friendly Table And Field Names" to "Disabled"?

**Comment by alamoot** [comment]
@TurkerTunali Yes this is mentioned in the post. To add more info, I'm using metabase version 0.27.1

**Comment by jornh** [comment]
@alamoot https://github.com/metabase/metabase/pull/6708 with 3 options in the dropdown was added in 0.28. So upgrading may improve. If that does not give you a result you can live with in all cases the Admin Guide mentions this:

> To manually fix field or table names if they still look wrong, you can go to the Metadata section of the Admin Panel, select the database that contains the table or field you want to edit, select the table, and then edit the name(s) in the input boxes that appear.

**Comment by tashiritzy** [comment]
If you are writing questions as native queries, write them as follows:

select 2 as "num", "hello" as "MESSAGE"; 
You need to put the aliases in quotes. I have done this in Postgres.

You then need to disable "FRIENDLY TABLE AND FIELD NAMES" in the metabase admin.

**Comment by tlrobinson** [comment]
Closed by #6708

**Comment by xgdgsc** [comment]
Why isn' t "replace underscore with space" the default? I don' t have any database that works with current default.

**Comment by flamber** [comment]
@xgdgsc There's an issue open for changing the Enabled (aka Advanced) to be less "smart" - #7606
