### ISSUE TITLE
Dashboards with maps running out of memory

### ISSUE THREAD

**Issue by JMGGarcia** [metabase/metabase#7809]
Hello everyone. I'm having a few issues running dashboards with a region map. The problem is that, whenever I change a filter, the memory increases, until it reaches a point that the browser restarts the tab that is running that dashboard. I'm using an imported dashboard, for Portuguese regions ( [url](https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/portugal.geojson) ). It doesn't seem like the problem would be the performed query, as it isn't that large and metabase has no problem dealing with it on other, non-map, charts. Anyone has any idea what can be the problem? Thanks. 

- Your browser and the version: Safari v11.1.1, Chrome v66.0.3359.181
- Your operating system: OS X 10.12.6
- Your databases: Postgres
- Metabase version: 0.28.6
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by tlrobinson** [comment]
@JMGGarcia Thanks for reporting this. I've created a PR at #7812. It would be great if you could verify it resolves this for you.

**Comment by JMGGarcia** [comment]
@tlrobinson thanks for the quick fix, it indeed does work! The memory consumption remains stable.
