### ISSUE TITLE
Follow-on work for Root collection permissions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7815]
Follow-on work for #7509

- [ ] Other *New* Tests
    - [x] Tests for updated `GET /api/collection/root` behavior
    - [x] Tests around the new Root Collection Permissions path
    - [ ] Tests for API endpoints for updating Root Collection perms
    - [ ] Tests for creating objects that will go in the Root Collection
- [x] Do we need to do a migration to remove all native read path permissions entires? Or otherwise what will happen if the current user has them (will validation throw an Exception?)

**Comment by camsaul** [comment]
Fixed in #7847 and a few other PRs
