### ISSUE TITLE
Personal Collections spec

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7816]
This is being worked on in #7800, but here are some details brought over from the google doc spec:

**Summary**
- Each user has their own personal collection, which always shows up as the first collection in the root level, called out visually in some way.
- A user implicitly has Curate access to her own personal collection. Admins have curate permissions for all personal collections.
- Personal collections can’t be moved, archived, or have their permissions changed.
- Personal collections should not show up in the collection permissions grid.
- But items that are saved in a personal collection can be moved and archived, and items can be saved/moved into personal collections.
- Non-admins have No Access to items saved in others' personal collections. So if they try to open a link to e.g. a question saved in someone else's personal collection, they should see a 403 access denied page.
- Admins can view links to items that are saved in personal collections, and can also edit those entities.
- Admins should have a way to navigate somehow to other users’ personal collections: the current idea is to have the admin’s own personal collection appear at the top of the root level’s collections list, and then there should be another ~top-level collection called~ link labeled “Everyone else’s personal collection” that displays a list of each other user’s personal collection. ~That parent collection should be a special folder that can't be written to, edited, moved, or have its permissions changed.~
- The layout for a personal collection is the same as for other collections. Items in a personal collection can be pinned. Users can create sub-collections in their personal collection.
- If a user has Curate permissions for another collection, then they can move items from it to their personal collection, and vice-a-versa.

**Questions**
1. What happens to the permissions of a sub-collection in a personal collection when a non-admin moves it to another collection? Current hypothesis is that it inherits the permissions of the parent collection it’s moving into.
2. What happens to the personal collection of a deactivated user? It gets archived? If the user is reactivated, I think the expectation is that their personal collection and its contents would be unarchived.
3. Should contents of other users’ personal collections show up in admin search results? Bias = no.

**Rough mocks**
My personal collection is at the top. If I'm an admin, I see the special collection containing other users' collections:

![personal_collection_in_list](https://user-images.githubusercontent.com/2223916/41064280-f6d105cc-698f-11e8-9823-8ff4b6b1377d.png)

My personal collection, empty state:

![personal_collection_empty](https://user-images.githubusercontent.com/2223916/41064293-042849ce-6990-11e8-83bc-dc530b40076d.png)

The collection containing all other personal collections. This can be a specialized layout since this collection will only ever contain personal collections (can't save anything else in here):

![image](https://user-images.githubusercontent.com/2223916/41065921-073514a8-6995-11e8-8946-c4d4be760475.png)

**Comment by salsakran** [comment]
`Admins should have a way to navigate somehow to other users’ personal collections: the current idea is to have the admin’s own personal collection appear at the top of the root level’s collections list, and then there should be another top-level collection called “Everyone else’s personal collection” that displays each other user’s personal collection. That parent collection should be a special folder that can't be written to, edited, moved, or have its permissions changed.`

sounds a little too cute... why not just have a list of every user by name and the ability to see their collections? What's the upside of tacking on "personal collection" onto each of these folders?

**Comment by mazameli** [comment]
Yeah, good point. You mean sort of like this?

![everyone else s personal collections](https://user-images.githubusercontent.com/2223916/41065234-d690544a-6992-11e8-8ac7-a08ab0879cf3.png)

**Comment by salsakran** [comment]
pretty much

**Comment by mazameli** [comment]
Implemented by #7800
