### ISSUE TITLE
Can't edit the created question or dashboard

### ISSUE THREAD

**Issue by Ryosuke-Sasaki** [metabase/metabase#7822]
Hello. I'm new to metabase.

I have questions about authority. I'm a author who was creating a question or dashboard, and I'm in trouble because I do not have the authority to edit my question or dashboard even though I am an administrator. This problem is similar to # 5605, # 5610, # 5617, # 6796, but I do not seem to have solved the problem. How can you give the administrator authority to edit it?

The environment is as follows.
* Metabase version: 0.29.3
    - The same problem occurs with version 0.25.1, 0.27.1 as well.
* Hosting environment: Running the metabase.jar Ubuntu 16.04.2 LTS with Java 8 (AWS)
* Metabase internal database: MySQL

## Procedure for Reproducing Permission Error
1. Click New Question on the Home screen
2. On the New Question screen, generate a query similar to "Getting started" in the official document using Sample Dataset and save the Question
     - https://www.metabase.com/docs/latest/getting-started.html
3. Follow the steps to create a new dashboard corresponding to Question
4. Change the size of the view obtained from question on the dashboard screen and save it
5. After that, after the screen transition, you will see "Sorry, you don’t have permission to see that." as shown in figure 1
     - You can see the dashboard, but the saved changes you made on the dashboard screen are not reflected
* figure 1
![2](https://user-images.githubusercontent.com/28972530/41086465-1cb38644-6a75-11e8-8506-86d7fcbe0ae9.PNG)

## Steps to reproduce the problem that can not edit question or dashboard
1. Click the "Question" or "Dashboard" button on the Home screen
2. Select Question or Dashboard created by you
3. Since there is no authority to change the created question and dashboard, the display "It's okay to play around with saved questions" appears as shown in figure 2
    - As shown in figure 3, the authority of Saved Questions has not been given even by Administrators, so I can understood that the above display is shown. However, I do not understand why this setting is default
    - Furthermore, I can't change the administrator's authority
    - Moreover, Although "Sorry, you don’t have permission to see that." is displayed on the screen after pressing "Okey" on the figure 2 screen, you can see the question and dashboard. I think it is a bug.
* If you try to create a new question after the error of the above permission warning occurs, "It's okay to play around with saved questions" is displayed, and there are occasional problems that I can't proceed with processing
    - If you reload the page several times, I'll be able to create new questions, but I don't know the cause.

* figure 2
![default](https://user-images.githubusercontent.com/28972530/41086388-e4bb396c-6a74-11e8-8a38-0a30891757b5.PNG)
* figure 3
![3](https://user-images.githubusercontent.com/28972530/41087707-4b0e8f2c-6a78-11e8-865c-8b98bab74a00.PNG)

If this problem is solved, I think that we can consider using metabase as a visualization tool.

Thank you.

**Comment by mazameli** [comment]
Hmm, I couldn't reproduce that permissions error using the Metabase 0.29.3 jar on macOS in Chrome. I tried this with the default admin account plus with a second admin account I added with both a mysql and a postgres db. I also tried this with Docker. Can you verify you're using Metabase version 0.29.3? What do the server logs say when you hit that error?

The saved questions "database" should no longer be present in the permissions grid in 0.29.3, but I actually was able to reproduce a state where it does show up momentarily when viewing the grid the very first time, but disappears on refresh and never comes back:

<img width="1326" alt="screen shot 2018-06-07 at 10 32 34 am" src="https://user-images.githubusercontent.com/2223916/41116225-8dc9410c-6a3e-11e8-996e-5a832e5d67ef.png">

<img width="1326" alt="screen shot 2018-06-07 at 10 32 45 am" src="https://user-images.githubusercontent.com/2223916/41116238-90e45a0c-6a3e-11e8-8f62-cfac36083183.png">

**Comment by Ryosuke-Sasaki** [comment]
I am sorry that the reply was delayed. Thank you for letting me know about you couldn't reproduce this issue. I will answer your question.

>  Can you verify you're using Metabase version 0.29.3?

Certainly I am using version 0.29.3. Like this.
![metabase](https://user-images.githubusercontent.com/28972530/41219172-7ed30d10-6d98-11e8-8503-8be32100e53d.PNG)

> The saved questions "database" should no longer be present in the permissions grid in 0.29.3, but I actually was able to reproduce a state where it does show up momentarily when viewing the grid the very first time, but disappears on refresh and never comes back:

I confirmed the authority item, and I certainly found that the same phenomenon occurred.There was a temporary disappearance of "saved questions" that existed before.However, if I do something, "Saved Questions" will redisplay.

> What do the server logs say when you hit that error?

The server log shows as follows (Total 4 logs).

### Log of the process from creation of question by Add new question to dashboard creation and saving
1. Click the "Add new question" button, create a question using Sample Dataset and save it
2. Create a new dashboard linked to the Question
3. After editing the dashboard, if I save it, I get the message "Sorry, you do not have permission to see that." and it becomes inoperable.

```
Jun 08 11:50:20 DEBUG metabase.middleware :: GET /api/metric 200 (292 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:50:20 DEBUG metabase.middleware :: GET /api/segment 200 (332 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:50:37 DEBUG metabase.middleware :: GET /api/table/2/query_metadata 200 (3 ms) (9 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:50:37 DEBUG metabase.middleware :: GET /api/table/3/query_metadata 200 (7 ms) (7 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued)
Jun 08 11:50:37 DEBUG metabase.middleware :: GET /api/table/1/query_metadata 200 (8 ms) (7 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued)
Jun 08 11:50:37 DEBUG metabase.middleware :: GET /api/table/2/fks 200 (1 ms) (4 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:51:09 DEBUG metabase.middleware :: POST /api/dataset 200 (24 ms) (15 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:51:20 DEBUG metabase.middleware :: GET /api/collection 200 (336 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:51:40 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:51:40 INFO metabase.api.card :: Card results metadata passed in to API is VALID. Thanks!
Jun 08 11:51:40 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:51:40 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:51:40 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:51:40 DEBUG metabase.middleware :: POST /api/card 200 (28 ms) (21 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:00 DEBUG metabase.middleware :: GET /api/dashboard 200 (4 ms) (13 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:20 DEBUG metabase.middleware :: POST /api/dashboard 200 (13 ms) (2 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:24 DEBUG metabase.middleware :: GET /api/dashboard/4 200 (2 ms) (3 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:24 DEBUG metabase.middleware :: GET /api/card 200 (2 ms) (5 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:28 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:52:28 DEBUG metabase.middleware :: POST /api/card/5/query 200 (28 ms) (16 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:52:49 DEBUG metabase.middleware :: POST /api/dashboard/4/cards 200 (8 ms) (14 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
```

### Log outputted when confirming question
1. Confirm the created question
2. I get the message "It's okay to play around with saved questions".
3. When clicking the "Okey" button displayed on the previous screen, I get the message "Sorry, you do not have permission to see that." and it becomes inoperable.
```
Jun 08 11:54:10 DEBUG metabase.middleware :: GET /api/collection 200 (405 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:10 DEBUG metabase.middleware :: GET /api/card 200 (4 ms) (5 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:14 WARN metabase.api.label :: Labels are deprecated, and this API endpoint will be removed in a future version of Metabase.
Jun 08 11:54:14 DEBUG metabase.middleware :: GET /api/label 200 (381 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:26 DEBUG metabase.middleware :: GET /api/database 200 (3 ms) (4 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:31 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:54:31 DEBUG metabase.middleware :: GET /api/card/5 200 (9 ms) (10 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:31 DEBUG metabase.middleware :: GET /api/table/2/fks 200 (1 ms) (4 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:31 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 11:54:31 DEBUG metabase.middleware :: POST /api/card/5/query 200 (18 ms) (16 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 11:54:35 DEBUG metabase.middleware :: GET /api/alert/question/5 200 (379 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
```

### Log output when editing dashboard
1. Browse the created dashboard
2. Click the Edit icon, save it after editing
3. I get the message "Sorry, you do not have permission to see that." and it becomes inoperable.
```
Jun 08 12:03:16 DEBUG metabase.middleware :: GET /api/dashboard 200 (9 ms) (16 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 12:03:20 DEBUG metabase.middleware :: GET /api/dashboard/4 200 (6 ms) (6 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 12:03:20 DEBUG metabase.middleware :: GET /api/database/1/metadata 200 (4 ms) (8 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 08 12:03:20 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 08 12:03:20 DEBUG metabase.middleware :: POST /api/card/5/query 200 (19 ms) (16 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
```

### Log output when I accessed metabase's home screen
* It is unknown whether this log information relates to this issue, but I am concerned about the output "Card X does not have cached read_permissions."

```
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/user/current 200 (306 µs) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/session/properties 200 (1 ms) (1 DB calls). Jetty threads: 8/50 (3 busy, 5 idle, 0 queued)
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/activity 200 (2 ms) (6 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued)
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/activity/recent_views 200 (451 µs) (1 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
Jun 11 04:53:00 INFO metabase.models.card :: Card 7 does not have cached read_permissions.
Jun 11 04:53:00 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/setup/admin_checklist 200 (13 ms) (10 DB calls). Jetty threads: 8/50 (5 busy, 3 idle, 0 queued)
Jun 11 04:53:00 DEBUG metabase.middleware :: GET /api/setting 200 (163 µs) (0 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)
Jun 11 04:53:00 INFO metabase.models.card :: Card 6 does not have cached read_permissions.
Jun 11 04:53:00 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 11 04:53:00 INFO metabase.models.card :: Card 5 does not have cached read_permissions.
Jun 11 04:53:00 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 11 04:53:00 INFO metabase.models.card :: Card 3 does not have cached read_permissions.
Jun 11 04:53:00 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
Jun 11 04:53:00 INFO metabase.models.card :: Card 4 does not have cached read_permissions.
Jun 11 04:53:00 WARN metabase.query-processor.middleware.expand :: You shouldn't specify an :and filter with only one subclause.
```

Just now, I used docker on AWS and started metabase. However, I also confirmed that I can not obtain the editing or browsing authority of the question or dashboard. I am afraid that AWS's environment affects metabase adversely. Hmm, it may be that AWS settings are bad. 

If you understand something, I would be happy if you could answer it.

**Comment by Ryosuke-Sasaki** [comment]
As a result of examination, it seemed that the above problem occurred because the proxy was set to play PUT method during HTTP communication. This trouble was avoided by devising a method of communication so that this PUT method is not blocked. 

Thank you for your efforts.

**Comment by amarcovich** [comment]
@Ryosuke-Sasaki  I have the same issue, how you solve?

**Comment by x670** [comment]
I believe, it is not Metabase bug, but this issue is not clear and have some security reasons.
Tested environment
Browser: Firefox 67.0.2
client OS: Ubuntu 18.04 
server OS:  Debian 9.9
all databases are: Postgres 9.5
Metabase: 3.23 - 3.29 jar
Metabase running behind Cloudflare. Https set through Cloudflare without any changes in Metabase.
Step: Edit  and save sql question
Expectation: Question editing allowed according to Metabase security settings
Reality: Some sql questions edited and saved well, some - not. Sorry, I can not provide real sql query that blocked by Cloudflare. User see same screen, as in this issue. In browser console we can see that Cloudflare (possibly any another security barrier) blocks `PUT` request to `api/card/nn` cause it has sql query inside it.
![изображение](https://user-images.githubusercontent.com/29977642/59611920-e185c000-9124-11e9-96ce-29bfaf1591a6.png)

Metabase behavior `Sorry, you dont have permission to see that`, showed on abnormal responses does not reflect real problem. So may be at least change it to another.
Also "encrypting" sql query, at least XORing it will help to properly use Metabase when only external security service with its https and sql injection protection, such as cloudflare is available

**Comment by x670** [comment]
I believe, it is not Metabase bug, but this issue is not clear and have some security reasons.
Tested environment
Browser: Firefox 67.0.2
client OS: Ubuntu 18.04
server OS: Debian 9.9
all databases are: Postgres 9.5
Metabase: 3.23 - 3.29 jar
Metabase running behind Cloudflare. Https set through Cloudflare without any changes in Metabase.
Step: Edit and save sql question
Expectation: Question editing allowed according to Metabase security settings
Reality: Some sql questions edited and saved well, some - not. Sorry, I can not provide real sql query that blocked by Cloudflare. User see same screen, as in this issue. In browser console we can see that Cloudflare (possibly any another security barrier) blocks PUT request to api/card/nn cause it has sql query inside it.
![изображение](https://user-images.githubusercontent.com/29977642/59613981-8786f980-9128-11e9-96f9-136f96e95c15.png)
Metabase behavior Sorry, you dont have permission to see that, showed on abnormal responses does not reflect real problem. So may be at least change it to another.
Also "encrypting" sql query, at least XORing it will help to properly use Metabase when only external security service with its https and sql injection protection, such as cloudflare is available

**Comment by x670** [comment]
@mazameli here is some new info, I suppose, this issue may be reopened

**Comment by nickNaniviaa** [comment]
> I believe, it is not Metabase bug, but this issue is not clear and have some security reasons.
> Tested environment
> Browser: Firefox 67.0.2
> client OS: Ubuntu 18.04
> server OS: Debian 9.9
> all databases are: Postgres 9.5
> Metabase: 3.23 - 3.29 jar
> Metabase running behind Cloudflare. Https set through Cloudflare without any changes in Metabase.
> Step: Edit and save sql question
> Expectation: Question editing allowed according to Metabase security settings
> Reality: Some sql questions edited and saved well, some - not. Sorry, I can not provide real sql query that blocked by Cloudflare. User see same screen, as in this issue. In browser console we can see that Cloudflare (possibly any another security barrier) blocks PUT request to api/card/nn cause it has sql query inside it.
> ![изображение](https://user-images.githubusercontent.com/29977642/59613981-8786f980-9128-11e9-96f9-136f96e95c15.png)
> Metabase behavior Sorry, you dont have permission to see that, showed on abnormal responses does not reflect real problem. So may be at least change it to another.
> Also "encrypting" sql query, at least XORing it will help to properly use Metabase when only external security service with its https and sql injection protection, such as cloudflare is available

I've been googling this issue for so long and couldn't find a answer. How frustrating to realize that it is only due to a CloudFlare instance that I had no knowledge that it was running on my metabase instance.

Thanks for the help

**Comment by stockarea** [comment]
How to Solve this issue?? I am also getting blocked by cloudflare but what settings to change in cloudlfare to allow it? Is it even right to allow this for security measures?
