### ISSUE TITLE
Table join in settings makes some filter dropdown options disappear

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#7824]
I joined two tables defining a foreign key in the data model settings - using the field "sku" as foreign key. "Sku" then appears in the query builder allowing access to the second table, however the filter dropdown does not show all options anymore (like "is", "is not", etc), for example, "contains" is just gone.

Your browser and the version: Chrome Version 66.0.3359.181
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.3
Metabase hosting environment: Heroku

**Comment by rlotun** [comment]
Closed by https://github.com/metabase/metabase/pull/16238
