### ISSUE TITLE
Bar chart randomly switched showing sums instead of categories as series

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#7825]
I have a stacked bar chart showing daily revenues by channel: the x-axis shows the day and the y-axis the different series (channels). Today when checking the dashboard, the chart had switched with no apparent reason, kicked out all series, adding one random field to the x-axis and leaving only one series on the y-axis -> the chart does not make sense at all like this:

![image](https://user-images.githubusercontent.com/24734846/41096058-b0d2d8c4-6a53-11e8-89c1-d910558b1c6f.png)

There is no change in underlying data, nor a change in settings, seems like a bug.
This happened to a couple of charts, somewhat annoying as I would have to go into each of them and re-add the series one by one.
Thanks for looking into it!

Your browser and the version: Chrome Version 66.0.3359.181
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.3
Metabase hosting environment: Heroku

**Comment by salsakran** [comment]
This seems really odd ... did anyone edit that question?  Can you check the audit log and verify that it wasn't edited by a human somehow?
