### ISSUE TITLE
Support MySQL functions in Custom Field Formula

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#7827]
- Your browser and the version: Firefox 60
- Your operating system: FreeBSD
- Your databases: MySQL
- Metabase version: 0.29.3
- Metabase hosting environment:  Linux/Debian
- Metabase internal database: MySQL

Allow custom field formula to use function such as DATEDIFF to calculate the difference in dates between to DATETIME or TIMESTAMP columns.

**Comment by georgiraychev** [comment]
What stops you from using this function in your SQL code?

**Comment by salsakran** [comment]
perhaps a dumb question, but what happens if you subtract a datetime from a timestamp?

**Comment by flamber** [comment]
Closing in favor of #16870
