### ISSUE TITLE
Add a Deploy Button from WeDeploy

### ISSUE THREAD

**Issue by zenorocha** [metabase/metabase#7830]
I noticed you have a Heroku button and I thought it would be nice to have a WeDeploy button too.

Here's the a live demo of Metabase running on WeDeploy: https://metabase.wedeploy.io
And here's the source code to run it: https://github.com/wedeploy-examples/metabase-example

The button would look like this: 
<img src="https://user-images.githubusercontent.com/398893/41131085-99ed1a5a-6a6e-11e8-9ede-c3c034ab2a24.png" width="230" />

And the source code to add it to the README file would look like this:

```
[![Deploy](https://cdn.wedeploy.com/images/deploy.svg)](https://console.wedeploy.com/deploy?repo=https://github.com/wedeploy-examples/metabase-example)
```

Let me know what you think.

**Comment by salsakran** [comment]
The demo link is throwing 503's.

Also a large part of what makes hosting MB tricky is the application database needs to be somewhere durable. I don't see anything that sets up a persistent DB for our application database.

**Comment by zenorocha** [comment]
Thanks for the feedback. I just added a persistent storage, now even if the container gets destroyed we won't lose the data: https://github.com/wedeploy-examples/metabase-example/commit/fa6cf9093662232361b559c9aee7732b001a0f11

**Comment by salsakran** [comment]
With all due respect, the fact that you asked us to put up a deploy button _before_ having a version with persistent storage makes me believe that you haven't hosted Metabase on your own or other people's behalf for very long.

We're actively looking for easier options than beanstalk and heroku for our users, but given the nature of how people use MB, we need something fairly production hardened. If we're going to point a bunch of people towards you, we want to feel fairly confident that they're going to have a good experience. I'd suggest running us for your internal analytics on your own platform for a while and getting used to the kinds of issues that hosting MB produces, and checking back in in a few months of production usage.

**Comment by zenorocha** [comment]
I totally understand. Thank you for your time.
