### ISSUE TITLE
Driver: Redshift spectrum not available in custom questions

### ISSUE THREAD

**Issue by lysimon** [metabase/metabase#7833]
Hello,

# Problem
I am using metabase with a redshift connection. Everything is working fine.

Then, I want to create questions for it.
If I select Native SQL, i can queries all my tables in redshift, even the spectrum ones.

If I select Custom questions, I only have access to my redshift database / tables.

Is there anything I did wrong or is it the expected behaviour?

# Guesses of the problem
After checking:
https://github.com/metabase/metabase/issues/6461
https://discuss.redash.io/t/support-for-amazon-redshift-external-tables/1178

I never wrote any clojure, so, this might be wrong.
I guess the problem is coming from the drivers, with:
src/metabase/driver/generic_sql.clj
and
src/metabase/driver/redshift.clj

We are using the default syntax from generic_sql.clj and so, we do not list the external schemas?

# Specification
- Your operating system: Mac OS
- Your databases: Redshift
- Metabase version: 0.29.3
- Metabase hosting environment: Linux/Debian/Stretch
- Metabase internal database: Postgres

# How to reproduce:
- Create new datasource connection to redshift, with redshift spectrum available.
- create a new Custom question
- Schema/table for redshift spectrum does not appear.

Thanks a lot, congratulation on this great tool!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by lysimon** [comment]
So, something like that is working in redshift.clj (once again, first time i write clojure)
but now, I have the problem that all the redshift spectrum tables cannot be identified by tag.


Code to have redshift spectrum table, will commit if i managed to have something with column type as well:

> 06-11 12:00:55 WARN driver.generic-sql :: Don't know how to map column type 'string' to a Field base_type, falling back to :type/*.

Trying a bit to override the mapping now.

`(defn- describe-database
  "Custom implementation of `describe-database` for Redshift."
  [database]
  (let [output (set (for [fk (jdbc/query (sql/db->jdbc-connection-spec database)
                            ["SELECT DISTINCT table_name,table_schema
                                    FROM svv_columns
                                    WHERE table_schema NOT IN ('pg_internal','pg_catalog','information_schema');"])]
         {:name   (:table_name fk)
          :schema   (:table_schema fk)}
          )
          )]
    output
    {:tables output}
    ))`

**Comment by salsakran** [comment]
thanks for doing some legwork @lysimon !

**Comment by paulovasconcellos-hotmart** [comment]
+1 for this problem. I can't see external tables in Metabase Custom Question, but I can access it via native query. I wanna let my users explore some external tables.

**Comment by gpodevijn** [comment]
Bumping this issue

**Comment by marcioibm** [comment]
I was able to run Redshift Spectrum tables by changing the get-tables function on the sql-jdbc.sync file. You can see the commit here:

https://github.com/marcioibm/metabase/commit/f280c239e004fc98fb553eafbe9e50148246b395
