### ISSUE TITLE
CouchDB and cockroachdb

### ISSUE THREAD

**Issue by gkarthiks** [metabase/metabase#7834]
### Database support

I am looking for the [CouchDB](http://couchdb.apache.org/) and /or [CockroachDB](https://www.cockroachlabs.com/) support with Metabase.

**Comment by camsaul** [comment]
Hi, don't forget that you can use the search bar to see if an issue is already open. We already have an issue open for this: #2436

**Comment by gkarthiks** [comment]
sorry about that @camsaul . I was not aware that the search is case-sensitive.

**Comment by camsaul** [comment]
@gkarthiks it's not, you just have to click on `Issues`. e.g.

https://github.com/metabase/metabase/search?q=couchdb&type=Issues

**Comment by gkarthiks** [comment]
@camsaul I meant no disrespect, what i meant is *I was lazy and didn't do the proper search*. I searched for just `couch` string. like this. https://github.com/metabase/metabase/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+couch
