### ISSUE TITLE
BUG: Filter in query builder returns just one line instead of several

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#7843]
Filtering our Fact table, where one line is a sold article, by order number should return all lines with this order number (i.e. if a respective order contained more than one article).
However, since a couple of days, the result shown is just one item, the other lines seem to be "cut off". (and the data is available in the table, if I for example filter by customer ID, all articles in all orders are returned.)
 
Thanks for looking into this and fixing it! 
 

Your browser and the version: Chrome Version 66.0.3359.181
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.29.3
Metabase hosting environment: Heroku

**Comment by salsakran** [comment]
@HelenMertes you have a number of situations where something changed a couple days ago.... can you verify if the schema we captured for your table, or the questions themselves were changed?

it's _extremely_ unlikely that the query processor changed how it compiles queries and started returning different results unless something changed -- either the query itself, the metadata model or the underlying table. Without knowing what changed, we can't really do much to help.

**Comment by HelenMertes** [comment]
I had already checked this, and I cannot find anything that has been changed on our side. 

The simple query (basically just filtering by order number) described above actually does return the correct set of results when switched to SQL from the query builder (where it incorrectly showed only one row). This would be a hint that it has to do with the query builder?

**Comment by HelenMertes** [comment]
Hi,
I continued to have this problem in all the last versions, but used the workaroud to switch to SQL when having used the query builder - so just one click and then the result showed all relevant rows. 
Now in 0.33 the problem is the same, but I cannot find a way to switch to SQL, so the proven workaround does not work anymore. Is there a way to still switch, or even better, can you have a look into this display bug?
Thanks!

Your browser and the version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.33.0
Metabase hosting environment: Heroku

**Comment by flamber** [comment]
@HelenMertes The "Switch to SQL" is now located in top-right, when you click the Editor-button.

**Comment by flamber** [comment]
@HelenMertes 
Are you still having this problem on the latest release - 0.35.4?
Can you provide any additional information, screenshots, or anything that will help figuring out what is going on, which can assist us in reproducing this?

**Comment by sbelak** [comment]
Can you show /api/field/:id where :id is the ID of your order ID field. I'm guessing it's marked as PK and I believe we still have that bug where we jump to item view if filtering on PK regardless of number of results.
