### ISSUE TITLE
Canceling a question query doesn't kill the query

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#7849]
Metabase version v0.29.3
MySQL version 5.7

I open a question, click the `Cancel` button, then I view running queries in MySQL with `show processlist` and it's still there. Sometimes question with no default params can take a long time to run and there's no knowing what a question looks like before opening it.

**Comment by mausch** [comment]
Same thing happens in Postgres. If a query times out according to Metabase, the corresponding Postgres backend is not canceled/terminated.

**Comment by wvengen** [comment]
Related: #2399, #7270 and PR #2519.

**Comment by nickcarenza** [comment]
Dang, sorry. #7270 is even my own issue. And again, I only searched open issues. But now that feature was supposed to go out with 0.29 and I'm on 0.29.3 and it still doesn't work.

**Comment by salsakran** [comment]
What's in the server logs? We attempt to cancel queries when you hit "cancel", but not all databases deal gracefully with cancelling queries.

**Comment by nickcarenza** [comment]
Nothing about the cancelation is in the log. I can see the query running in the mysql processlist when I open the card and after I cancel it in metabase I can see it still running in mysql. when i runn `kill query X` in mysql it is removed from the processlist.

**Comment by davehowell** [comment]
Doesn't work in Redshift either, and Redshift certainly handles cancelling queries gracefully, as I can do it with a few different client tools e.g. DBeaver.

**Comment by flamber** [comment]
@davehowell Which version of Metabase? Do you see `Request canceled before finishing.` in the log, when cancelling the query?

**Comment by davehowell** [comment]
Currently on v0.32.9, checking the logs
