### ISSUE TITLE
[Hardware] For production environment

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7855]
I think this can be in the official docs:

What is a "typical" hardware for Clojure at production enviroment? I'm using 2 AWS EC2 m3.xlarge, but when our team started using at the same time (e.g.: 15 people), the starts servers shut down the service returning 503.

**Comment by jornh** [comment]
I think there’s already a pretty good recent answer in the forum here:

http://discourse.metabase.com/t/best-setup/3727

It’ll always be a moving target and nowadays you simply just pick a different scale hardware if your your initial guess was wrong or your needs change which they will over time.

**Comment by salsakran** [comment]
The biggest thing you need to do is make sure you're setting the threadpool and the JVM memory high enough. 15 people using it at once should be trivial on an m3.xlarge

**Comment by mbvictoria** [comment]
Closing - answered.
