### ISSUE TITLE
New UI 0.30 - Bring Back Menu Bar

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#7865]
The 0.30 release removed the Dashboard / Questions buttons from the menu bar. Please bring them back!

Here is why:
1) It's not user friendly and makes finding a dashboard hard
2) Only having a search bar is not a mobile-first UI. Mobile UI's should avoid typing whenever possible
3) I've had a bunch of people complain to me about it

The old menu buttons should be restored. The search feature should be kept. The final product could look like this:

![merger](https://user-images.githubusercontent.com/17504314/43723440-ab625fcc-9965-11e8-883d-a0469a7d4668.PNG)

**Comment by salsakran** [comment]
Thanks for the feedback!

Note that master is in flux and should not be considered final yet.

**Comment by MarkRx** [comment]
Thinking more about it ... I understand why those were removed. I suggest at the very least adding a button that navigates to <instance>.com/collection/root. I should not have to go to the middle of the home page to get there.

**Comment by kulyk** [comment]
Should be solved with a nav change coming in 43
