### ISSUE TITLE
Automagic Dashboards Candidates call is too slow

### ISSUE THREAD

**Issue by senior** [metabase/metabase#7866]
I hit this on a fresh Meatabase instance (from master) with only the sample dataset and the Redshift database our internal stats instance uses. Specifically it's the `/api/automagic-dashboards/:id/candidates` call that appears to be issuing one query per redshift table to `metabase_fields` table. The frontend currently calls that endpoint 5 times concurrently and appears to repeat those 5 concurrent calls until it has called the candidates endpoint 30 times total. This caused my Metabase instance to be very slow, until it got passed the 30 calls.

**Comment by sbelak** [comment]
Fixed in #7882
