### ISSUE TITLE
Exiting admin panel broken in master

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#7868]
When I go to the admin panel and then exit the content of the page doesn't change, only the nav bar.

![image](https://user-images.githubusercontent.com/1455846/41366008-c481dbd6-6eef-11e8-85f9-73367b220740.png)

#### Steps to repro:

1.  Go to http://localhost:3000
2.  Click `Admin Panel` from the menu
3.  Click `Exit Admin` from the menu

**Comment by dvanrijswijk** [comment]
Experiencing this same issue in 0.32.9 (screenshots as older issue above) with one additional note.

If I then click on any side tab (such as 'Setup' or 'General'), the nav bar turns back to the Admin nav bar, at which point, clicking the 'Exit admin' works as expected (returns to main page).

**Comment by paulrosenzweig** [comment]
@dvanrijswijk what browser are you using? Do you see it consistently when you exit admin or just some times?

**Comment by dvanrijswijk** [comment]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Experienced on:
IE 11.0.9600.19377
Iron Version 69.0.3600.0 (Official Build) (32-bit)
Chrome Version 75.0.3770.142 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Windows XP, etc)
Windows 7 

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Postgres 9.6

- Metabase version: (e.x. 0.19.3)
0.32.9

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Ubuntu 16.04.6 LTS

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres

**Comment by dvanrijswijk** [comment]
Pinned dashboard in our analytics as mentioned in #10191 and the behavior no longer appears.
