### ISSUE TITLE
Enforce collection permissions throughout new collections UI

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#7881]
(Some of these may already be implemented, but we should verify)

* [x] editing
  * [x] FE: I should only see the `Edit Permissions` menu option if I'm an admin.
* [ ] moving
  * [x] FE: only show "move" buttons if user has `can_write` on current collection
  * [ ] drag-and-drop
    * [ ] BE: need `GET /api/collection/:id/items` to include `can_write` on `collection` objects
    * [x] FE: only allow drag and drop if both current and target collection have `can_write`
  * [ ] collection picker
    * [ ] BE: need `GET /api/collection` to return `root` collection with `can_write` #7880 
    * [ ] FE: only show collections with `can_write`, or having descendants with `can_write`, and only allow selection of collections with `can_write`
* [x] archiving
  * [x] FE: only show "archive" buttons if user has `can_write` on current collection
* [x] pinning
  * [x] FE: only allow show "pin" icon if user has `can_write` on current collection
  * [x] FE: only allow dragging into or out of pin area if if user has `can_write` on current collection
* pulses
  * [ ] BE: `/api/pulse/:id` needs to return `can_write`
  * [ ] read only view?
* dashboards
  * [x] BE: `/api/dashboard/:id` needs to return `can_write`

**Comment by tlrobinson** [comment]
If a user doesn't have write permissions we might want to show a different empty state than this:

![image](https://user-images.githubusercontent.com/18193/41395451-9ce06ab6-6f62-11e8-8343-08c609292502.png)

**Comment by mazameli** [comment]
I'll test this out.

**Comment by mazameli** [comment]
One missing checkbox: I should only see the `Edit Permissions` menu option if I'm an admin.

**Comment by mazameli** [comment]
> FE: only allow drag and drop if both current and target collection have `can_write`

This works correctly in that in prevents the action from taking place, but the UX could be improved: instead of showing a permissions error page, it would be preferable to have a different, disabled-style treatment for collections and breadcrumbs into which I am not allowed to drop something while dragging.

**Comment by mazameli** [comment]
> FE: only show collections with can_write, or having descendants with can_write, and only allow selection of collections with can_write

I'm seeing some cases where I'm being shown a collection that I don't have `can_write` for, nor do I for any of its children, though I do have View permission for some of its children:

<img width="673" alt="screen shot 2018-07-20 at 11 48 52 am" src="https://user-images.githubusercontent.com/2223916/43011967-07bd0db8-8c13-11e8-88de-b7ec3d600628.png">

**Comment by mazameli** [comment]
> FE: only show "archive" buttons if user has can_write on current collection

Logic on this is a little off: I should only see the archive button if I have `can_write` for the current collection and its parent. (The backend correctly shows me a permissions error if I try to archive a collection when I have `can_write` for it, but _not_ for its parent.)

**Comment by tlrobinson** [comment]
@camsaul pulse endpoint needs to include `can_write` so we know if the user can update a pulse.

@metabase/core-developers If a user can't update a pulse maybe we should have a read-only view? Should they also be able to remove themselves from the recipients even if they can't edit the rest of the pulse?

**Comment by salsakran** [comment]
I'm a 👍 on users being able to unsubscribe without being able to edit the pulse

**Comment by tlrobinson** [comment]
@camsaul Dashboard endpoint also needs `can_write`

**Comment by mazameli** [comment]
Is this still relevant?

**Comment by salsakran** [comment]
I think we should verify them and if not implemented consider whether they're still necessary. These are cases where the BE is more strict than the FE and things a user has buttons for might result in a BE permissions error.
