### ISSUE TITLE
Numeric category filter values aren't transferred when moving from a dashboard to a question or vice versa

### ISSUE THREAD

**Issue by gkhairulina** [metabase/metabase#7891]
- Your browser and the version: Firefox 60.0.2
- Your operating system: macOS Sierra 10.12.6
- Your databases: Postgres
- Metabase version: 0.28.1, 0.29.3, 0.30.0-snapshot
- Metabase hosting environment: Docker, Jar
- Metabase internal database: H2 (default), Postgres

- *Repeatable steps to reproduce the issue*
1. Create a question with category filter that filters by a numeric column and add it to a dashboard
2. Add dashboard category filter that filters by a numeric column
3. Select values in dropdown checklist in dashboard filter
<img width="1045" alt="screen shot 2018-06-15 at 14 18 31" src="https://user-images.githubusercontent.com/35559523/41463439-802d846c-70a7-11e8-9157-3d0a9f6a769f.png">
4. Click on question

(5. The same behavior when go back from question to dashboard page – numeric category filter values convert to strings)

*Expected result:* There is the question filtered by values selected in dashboard filter

*Actual result:* There was a problem displaying this chart.
<img width="1059" alt="screen shot 2018-06-15 at 14 18 45" src="https://user-images.githubusercontent.com/35559523/41463465-9fc2dd72-70a7-11e8-8c58-8921209727a3.png">
*Stack trace:*
<img width="1140" alt="screen shot 2018-06-15 at 14 24 04" src="https://user-images.githubusercontent.com/35559523/41463540-de135926-70a7-11e8-82fa-1bc670f516f9.png">

**Comment by salsakran** [comment]
what are the types of your dashboard parameters?

**Comment by gkhairulina** [comment]
they are mapped to fields of type int, like id but not id

**Comment by matthieu-foucault** [comment]
I'd like to help with fixing this. We're having the same issue with our dashboard filters. 

- Your databases: Postgres
- Metabase version: 0.33.0-snapshot (10294b1)
- Metabase hosting environment: Docker, Jar
- Metabase internal database: H2 (default), Postgres

- Have a table where a column has the Category type, and the values are of numeric type
- Create a question on that table and add it to a dashboard
- Add a filter on the aforementioned numeric category column
- Save the dashboard
- Set a value for the filter using the parameter widget (everything's fine)
- Refresh the page (the value you set before should be in the URL query string)
- :boom: There was a problem with displaying this chart

When set via the ParameterWidget, the parameter is serialized as a numbers array. When refreshing the page, it is sent as a string, and it the backend does not convert it, making Postgres unhappy. H2 seems fine with it, so I don't know if there is driver-specific code that takes care of that conversion, or it's just that H2 is fine with implicit casts.

I tried the fix pending in #7987, but it doesn't seem to apply to my issue as the query isn't written in SQL. It is a simple question.

If you give me pointers I'm happy to help and work on fixing that! :)

**Comment by flamber** [comment]
I can reproduce this on 0.32.8 - but only with Postgres - other datasources doesn't trigger this.
And there seems to be several people still encountering this, but because all the error messages are images, then it's impossible to find when doing a search.
`ERROR: operator does not exist: integer = character varying Hint: No operator matches the given name and argument types. You might need to add explicit type casts.`
Referencing other issues for visibility: https://github.com/metabase/metabase/issues/5632#issuecomment-489165061 , https://github.com/metabase/metabase/issues/2854#issuecomment-409295946

**Comment by walterl** [comment]
I'm unable to reproduce this on current master with Postgres. #10103 probably fixed it. Thanks @matthieu-foucault!
