### ISSUE TITLE
'Time' is the only filter that works for Google Analytics on dashboards

### ISSUE THREAD

**Issue by buren** [metabase/metabase#7892]
First of all thank you for an amazing product! 🙌

---

I'm trying to filter a Google Analytics (GA) question (_not_ a native one), on a dashboard, but I found that the only filters that work are the `Time` filters. When trying to use the other filters `Location`/`ID`/`Other categories` there are "No valid fields" to choose from.

It would be awesome to be able to filter using either `Location` and/or `Other categories`. In my particular case I have a table with a country iso code that I'd like to filter next to a GA question and the current GA driver supports filtering on country (with and without iso) in the regular query builder, but not on dashboards.

Again, thank you!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by lp-lima** [comment]
Please vote this up, so metabase team can prioritize this feature.

Related community post:
https://discourse.metabase.com/t/filter-dashboard-by-google-analytics-column/6167

**Comment by bayurzki** [comment]
Hello, do you can adding filter date In dashboard metabase with Google Analytics data?

**Comment by camsaul** [comment]
Closing as not planned due to dropping GA support
