### ISSUE TITLE
Controlled Field Filters

### ISSUE THREAD

**Issue by SelvaP** [metabase/metabase#7898]
Thanks for the wonderful product.

My doubt is ,can Field Filter field values be controlled?

For example I have a table that has products different types.If suppose I want a Field Filter with a particular product type alone how should I do it?

Thanks in advance.

**Comment by salsakran** [comment]
hello, this is the wrong forum to ask questions about how to use the product. please ask these kinds of questions on the user discussion forum - http://discourse.metabase.com/
