### ISSUE TITLE
I can't understand why Metabase still not support Gauge?

### ISSUE THREAD

**Issue by mnlbox** [metabase/metabase#7901]
### Feature requests and proposals
Guys I really love Metabase and using this awesome tools these days but I can't understand why Metabase still not support Gauge. I saw that @mazameli done some work on this but I can't find this in Metabase display types.
Community request this feature from 2016. :thinking: 
Related issues and PR:
#6721 
#4500 
#2989 
#3149 

Excuse me for re issue. I comment on related issue and PR but nobody answer me and I post this feature request again because I think that **Gauge** is most important data visualization in many BI and data analysing project.

**/CC:** @tlrobinson, @senior, @camsaul, @kdoh

**Comment by tlrobinson** [comment]
This should be pretty easy to add and I talked with @mazameli about the design of it, so I'll try to implement it when I have a few hours.

But we've got multiple issues for it already so I'm going to close this one.

**Comment by mnlbox** [comment]
Thanks @tlrobinson, Can you tell me when you want add this feature to Metabase? I ask it because I need select my BI tools now and I really want choose Metabase if it's support Gauge chart type.
Can you explain Metabase short term roadmap?

**Comment by tlrobinson** [comment]
@mnlbox I've started working on this in PR #7938. We will try to get it in this release or the one after.
