### ISSUE TITLE
Fields included in Pulses even if excluded from question

### ISSUE THREAD

**Issue by ehk20** [metabase/metabase#7918]
Not sure if this is a bug or a 'feature' but I find it counter-intuitive:

1) Create a question with raw data output
2) Customize the table to include a subset of fields
3) Create a Pulse based on this question and it includes all fields rather than limiting the output to the fields selected in 2.

 v0.29.3

**Comment by mazameli** [comment]
Reproduced this. I would consider this a bug.

**Comment by joebordes** [comment]
I have a related issue: if you reorder the columns in the question, the pulse does not respect that column order.

Do you prefer that I open another issue?

**Comment by senior** [comment]
This has been fixed for new (or updated) questions via https://github.com/metabase/metabase/pull/8004. The issue that @joebordes mentioned is also fixed. I tested this out on current master, removing all of the columns in a result except for 3 and changing their order. Both the reduced set of columns and the new order show up in pulses. https://github.com/metabase/metabase/pull/8004 will be included in the 0.30.0 release which should be out soon.

@metabase/core-developers This fix will only apply to questions that the user has touched (created or updated) after upgrading to 0.30.0. Should we be migrating existing questions to the `fields` query clause used in https://github.com/metabase/metabase/pull/8004?

**Comment by tlrobinson** [comment]
I think the conclusion of our in-person conversation was it isn't worth migrating old questions. If you want to manually migrate a question the easiest way is to open the question, open the visualization settings, make any change to the settings (e.x. add or remove a column), click "Done" (then optionally undo that setting change) and save the question.

**Comment by jornh** [comment]
According to https://github.com/metabase/metabase/issues/7918#issuecomment-408911475 above this can be closed as fixed in 0.30.0

Related [Discourse topic](http://discourse.metabase.com/t/0-30-done-how-to-specify-column-order-in-pulse-question/4273)

**Comment by flamber** [comment]
Fixed in 0.30.0, though ordering isn't preserved #11936
