### ISSUE TITLE
compile error if using hyphen(-) in locale

### ISSUE THREAD

**Issue by tonny1983** [metabase/metabase#7924]
Environment:
1. Browsers: Chrome 63.0, Firefox 60.0, Safari 11.1
2. OS(for compile): macOS 10.13
3. Metabase version: 0.29.3
4. Java version: 1.8.0_152

Background:
The listed browsers are all using hyphen(**-**) but underscore(**_**) in the head of `Accept-Language`, e.g.
1. Chrome:  `Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7`
2. Firefox:  `Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7`
3. Safari:  `Accept-Language: zh-cn`

Thus, I try to add the locale of `zh-cn`

*Repeatable steps to reproduce the issue*
1. `./bin/i18n/update-translations`
2. `./bin/i18n/update-translation zh-cn`
3. `./bin/i18n/build-translation-resources`

ERROR:
`/var/folders/dy/qr4zzhk550x069q4_hhl9fqc0000gn/T/msg32g2A3/metabase/Messages_zh-CN.java:3: ERROR: Need'{'
public class Messages_zh-CN extends java.util.ResourceBundle {`

I know it is because hyphen is an illegal character in the definition of Java class, but how to create a new locale with hyphen?

**Comment by mauricio-sonegatti** [comment]
For PT-BR I just created PT for now.

**Comment by camsaul** [comment]
@senior could use your help on this. Would this be an issue with the puppet i18n library? Or do you think it's something else

**Comment by senior** [comment]
Best I can tell from reading the code in the i18n library we are using and trying some things out, adding a country code after the locale doesn't work :disappointed:. My suggestion would be similar to want @mauricio-sonegatti has recommended. 

`msgfmt` which is the `xgettext` command we're using to create the translation files requires an underscore, i.e. `en_US`. I don't see anything that swaps the `_` for a `-`.  Using the example from the original post `zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7`, the locale negotiation code creates a list of possible locales that looks like `["zh-CN" "zh" "en" "ja"]`. The i18n code is attempting to match that via a string comparison with locales that it knows. In my test setup, I had a `#{"zh_CN","en"}` locales. It doesn't match `zh-CN`, there was no `zh` but it does match on `en`.

The locale negotiation code in the i18n library (found [https://github.com/puppetlabs/clj-i18n/blob/master/src/puppetlabs/i18n/core.clj#L342](here)) doesn't seem correct. I've done some local testing with https://docs.oracle.com/javase/8/docs/api/java/util/Locale.LanguageRange.html, which seems more correct. It separates the locale and the country code, ignores case etc. The best bet might be to move that library to something derived from the JDK Locale code.

**Comment by tonny1983** [comment]
@mauricio-sonegatti @senior , Sorry for my late reply. The problem is that Safari cannot match only the `zh` locale due to it has only one `Accept-Language` of `zh-cn`. If I use `ZH` just as `PT` you mentioned, Safari will still show the default language of English.

**Comment by jornh** [comment]
In relation to https://github.com/puppetlabs/clj-i18n/blob/master/src/puppetlabs/i18n/core.clj#L342 @senior shared above I noticed they already have an unmerged proposed PR supposed to fix it:

https://github.com/puppetlabs/clj-i18n/pull/44 

May be worth giving them a nudge or forking somehow... unless, what you mention @senior 
is even more viable:
> It separates the locale and the country code, ignores case etc. The best bet might be to move that library to something derived from the JDK Locale code.

**Comment by flamber** [comment]
Closing, since this got fixed in #12193. Metabase 0.35+ now supports language variants.
