### ISSUE TITLE
Ability for admin to hide certain tables within all questions and native query builder as well

### ISSUE THREAD

**Issue by hansyson** [metabase/metabase#7925]
### Feature requests and proposals
 Need ability for admin to be able to hide certain tables at the new question level within native query builder.  Doesn't seem to work as is.  either the user can see everything or nothing.

**Comment by flamber** [comment]
Very similar to #1689 and related to #6338 (also to #10525)

**Comment by flamber** [comment]
Closing in favor of the above issues.
