### ISSUE TITLE
Drill-through is broken when user doesn't have access permissions to all FKs in a table

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#7928]
Seeing the below error
![screen shot 2018-06-22 at 12 56 32 pm](https://user-images.githubusercontent.com/107439/41796530-ce0eff3e-761b-11e8-88c4-0e4c9bf4ef75.png)

when I try to click into a state on a dashboard generated for the orders sample table under a user with only access to that table (and no others) in the sample dataset.

**Comment by camsaul** [comment]
@salsakran I think what is happening here is we're not returning info for those Tables that you don't have access to. We probably need to check and see whether the Table exists / has read permissions before showing the drill-thru options

**Comment by salsakran** [comment]
my read is that the frontend needs to not try to get table data for tables an FK links to if you don't have access to it?

**Comment by tlrobinson** [comment]
@salsakran To clarify:

1. a user who has data permissions for all `Sample Dataset` tables saves an xray for the `Orders` table to a collection
1. a different user who only has data permissions for `Orders` table and the same collection above tries to view that saved xray
1. previously: they could view the dashboard but when they drilled into one of the questions (which one? by clicking the title?) they got a permissions error
1. currently (`master`? my PR?): they get a permissions error as soon as they try to view the saved xray

**Comment by salsakran** [comment]
I think there is another permissions bug that is masking this for me -- #10656 I can't even get the orders x-ray dashboard to render now on either master or branch `fix-7928`.

**Comment by camsaul** [comment]
Fixed by #10655
