### ISSUE TITLE
field filter not giving option for filter widget type in redshift table

### ISSUE THREAD

**Issue by sar009** [metabase/metabase#7930]
I am unable to see filter widget type in variables when querying from redshift.

<img width="534" alt="screen shot 2018-06-24 at 1 05 44 pm" src="https://user-images.githubusercontent.com/3882922/41817105-141d8760-77b2-11e8-9ed9-821fd88fd918.png">
<img width="295" alt="screen shot 2018-06-24 at 1 05 59 pm" src="https://user-images.githubusercontent.com/3882922/41817108-1d1bf9dc-77b2-11e8-8a84-c50a53825dfe.png">

- browser: Firefox 60.0.2
- operating system: OS X 10.13.5
- databases: Redshift
- Metabase: 0.29.3
- Metabase hosting environment: Linux/Ubuntu 16.04
- Metabase internal database: H2 (default)

**Comment by sar009** [comment]
I am facing the same issue in both MySQL and Postgres. The column in question(campaign) is `character varying(64)`

**Comment by salsakran** [comment]
does it work on other columns types on that table? I.e. is the issue solely with that column, or any column in that table?

**Comment by Siddarth434** [comment]
Facing the same issue, i think if the variable has large data to list out, then it does not appear

**Comment by pagoda6644** [comment]
Seeing the same issue here on mysql.  There's 2 columns in the same table, one works fine, the other does not. They have the same date type (varchar 64). 
Metabase version: v0.30.4
DB: mysql 5.7
Browser: chrome
OS: MacOS 10.14.3

**Comment by flamber** [comment]
@pagoda6644 
That's a fairly old version you're using. Version 0.32.4 was released a couple of days ago.
You need to make sure that the Field Type is set correctly in your Data Model:
Settings > Admin > Data Model > (database) > (table) > (column) :gear:

**Comment by doubler84** [comment]
I have the same problem with Oracle database.
I have metabase version  v0.31.2

**Comment by flamber** [comment]
@doubler84 It's really difficult to help with such an old version (0.31.2 is one year old). There has been many changes since. But the Field Type in the Data Model has to be one as [listed in the documentation](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables).
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by flamber** [comment]
Closing, since this was likely because a wrong Field Type in the Data Model:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#creating-sql-question-filters-using-field-filter-variables
