### ISSUE TITLE
First SQL in a pulse after a longer period leads to error message

### ISSUE THREAD

**Issue by Steff81** [metabase/metabase#7931]
We created several pulses which will be send via email to a group of users. 
The first SQL in this pulse is never executed properly and leads to the error message:

An error occurred while displaying this card.

The SQLs after the first one are fine. When executing the SQL without the pulse everything is fine. 
But sometimes after for a longer period no SQLs / Questions have been executed there also occurs an error. In this case I had to execute the question again then it works fine. I think these two things belong together. 

For me it looks like that the first SQL that is executed cannot be processed properly, maybe because of some initial connections problem to the database. 

Any idea about that?

**Comment by salsakran** [comment]
what's in the server logs?

**Comment by Steff81** [comment]
Here is the log entry: 

07-09 22:00:00 ERROR generic-sql.query-processor :: nil
07-09 22:00:00 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.Exception,
 :error "Communications link failure\n\nThe last packet successfully received from the server was 88,135 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.",
 :stacktrace
 ["driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:505)"
  "driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:497)"
  "driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:555)"
  "driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:551)"
  "driver$fn__25845$G__25652__25852.invoke(driver.clj:61)"
  "query_processor$execute_query.invokeStatic(query_processor.clj:51)"
  "query_processor$execute_query.invoke(query_processor.clj:45)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__30118.invoke(mbql_to_native.clj:30)"
  "query_processor.middleware.annotate_and_sort$annotate_and_sort$fn__28510.invoke(annotate_and_sort.clj:41)"
  "query_processor.middleware.limit$limit$fn__30073.invoke(limit.clj:15)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__29929.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.cumulative_aggregations$cumulative_aggregation$fn__29929.invoke(cumulative_aggregations.clj:58)"
  "query_processor.middleware.format_rows$format_rows$fn__30063.invoke(format_rows.clj:26)"
  "query_processor.middleware.binning$update_binning_strategy$fn__28589.invoke(binning.clj:172)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__31470.invoke(results_metadata.clj:89)"
  "query_processor.middleware.resolve$resolve_middleware$fn__28118.invoke(resolve.clj:424)"
  "query_processor.middleware.expand$expand_middleware$fn__29818.invoke(expand.clj:605)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__28202.invoke(add_row_count_and_status.clj:14)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__29949.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__31481.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__28670.invoke(cache.clj:146)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__29866.invoke(catch_exceptions.clj:58)"
  "query_processor$process_query.invokeStatic(query_processor.clj:130)"
  "query_processor$process_query.invoke(query_processor.clj:126)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:243)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:237)"
  "query_processor$fn__31515$process_query_and_save_execution_BANG___31520$fn__31521.invoke(query_processor.clj:283)"
  "query_processor$fn__31515$process_query_and_save_execution_BANG___31520.invoke(query_processor.clj:269)"
  "query_processor$fn__31539$process_query_and_save_with_max_BANG___31544$fn__31545.invoke(query_processor.clj:304)"
  "query_processor$fn__31539$process_query_and_save_with_max_BANG___31544.invoke(query_processor.clj:300)"
  "pulse$execute_card.invokeStatic(pulse.clj:37)"
  "pulse$execute_card.doInvoke(pulse.clj:29)"
  "pulse$pulse__GT_notifications$iter__32477__32481$fn__32482.invoke(pulse.clj:219)"
  "pulse$fn__32423.invokeStatic(pulse.clj:155)"
  "pulse$fn__32423.invoke(pulse.clj:150)"
  "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495$fn__32496.invoke(pulse.clj:230)"
  "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495.invoke(pulse.clj:228)"
  "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:214)"
  "pulse$send_notifications_BANG_.invoke(pulse.clj:213)"
  "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:241)"
  "pulse$send_pulse_BANG_.doInvoke(pulse.clj:232)"
  "task.send_pulses$send_pulses_BANG_$fn__55777.invoke(send_pulses.clj:97)"
  "task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:94)"
  "task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:82)"
  "task.send_pulses.SendPulses.execute(send_pulses.clj:59)"],
 :query
 {:type "native",
  :native
  {:query
   "REMOVED BECAUSE OF DATA SECURITY REASONS!",
   :template_tags {}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :info
  {:executed-by 2,
   :context :pulse,
   :card-id 313,
   :pulse-id 4,
   :query-hash [75, 22, -111, -111, 37, -18, 50, 124, -11, -93, -73, 49, -9, 39, -118, -31, 46, -50, 69, 37, -74, -66, 92, 29, -4, -37, 16, 54, -126, -108, 84, 5],
   :query-type "native"}},
 :expanded-query nil}

07-09 22:00:01 WARN metabase.query-processor :: Query failure: Communications link failure

The last packet successfully received from the server was 88,135 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:211)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:204)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:244)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:237)"
 "query_processor$fn__31515$process_query_and_save_execution_BANG___31520$fn__31521.invoke(query_processor.clj:283)"
 "query_processor$fn__31515$process_query_and_save_execution_BANG___31520.invoke(query_processor.clj:269)"
 "query_processor$fn__31539$process_query_and_save_with_max_BANG___31544$fn__31545.invoke(query_processor.clj:304)"
 "query_processor$fn__31539$process_query_and_save_with_max_BANG___31544.invoke(query_processor.clj:300)"
 "pulse$execute_card.invokeStatic(pulse.clj:37)"
 "pulse$execute_card.doInvoke(pulse.clj:29)"
 "pulse$pulse__GT_notifications$iter__32477__32481$fn__32482.invoke(pulse.clj:219)"
 "pulse$fn__32423.invokeStatic(pulse.clj:155)"
 "pulse$fn__32423.invoke(pulse.clj:150)"
 "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495$fn__32496.invoke(pulse.clj:230)"
 "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495.invoke(pulse.clj:228)"
 "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:214)"
 "pulse$send_notifications_BANG_.invoke(pulse.clj:213)"
 "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:241)"
 "pulse$send_pulse_BANG_.doInvoke(pulse.clj:232)"
 "task.send_pulses$send_pulses_BANG_$fn__55777.invoke(send_pulses.clj:97)"
 "task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:94)"
 "task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:82)"
 "task.send_pulses.SendPulses.execute(send_pulses.clj:59)"]

07-09 22:00:01 ERROR pulse.render :: Pulse card render error java.lang.Exception Card has errors: Communications link failure

The last packet successfully received from the server was 88,135 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago. 
 ["pulse.render$fn__24029$render_pulse_card_body__24034$fn__24038.invoke(render.clj:774)"
 "pulse.render$fn__24029$render_pulse_card_body__24034.invoke(render.clj:770)"
 "pulse.render$fn__24062$render_pulse_card__24067$fn__24068.invoke(render.clj:797)"
 "pulse.render$fn__24062$render_pulse_card__24067.invoke(render.clj:793)"
 "pulse.render$fn__24089$render_pulse_section__24094$fn__24100$fn__24104.invoke(render.clj:819)"
 "pulse.render$fn__24089$render_pulse_section__24094$fn__24100.invoke(render.clj:818)"
 "pulse.render$fn__24089$render_pulse_section__24094.invoke(render.clj:815)"
 "email.messages$render_message_body$fn__25149$fn__25150.invoke(messages.clj:228)"
 "email.messages$render_message_body$fn__25149.invoke(messages.clj:228)"
 "email.messages$render_message_body.invokeStatic(messages.clj:226)"
 "email.messages$render_message_body.invoke(messages.clj:225)"
 "email.messages$render_pulse_email.invokeStatic(messages.clj:243)"
 "email.messages$render_pulse_email.invoke(messages.clj:240)"
 "pulse$fn__32423.invokeStatic(pulse.clj:159)"
 "pulse$fn__32423.invoke(pulse.clj:150)"
 "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495$fn__32496.invoke(pulse.clj:230)"
 "pulse$pulse__GT_notifications$iter__32490__32494$fn__32495.invoke(pulse.clj:228)"
 "pulse$send_notifications_BANG_.invokeStatic(pulse.clj:214)"
 "pulse$send_notifications_BANG_.invoke(pulse.clj:213)"
 "pulse$send_pulse_BANG_.invokeStatic(pulse.clj:241)"
 "pulse$send_pulse_BANG_.doInvoke(pulse.clj:232)"
 "task.send_pulses$send_pulses_BANG_$fn__55777.invoke(send_pulses.clj:97)"
 "task.send_pulses$send_pulses_BANG_.invokeStatic(send_pulses.clj:94)"
 "task.send_pulses$send_pulses_BANG_.invoke(send_pulses.clj:82)"
 "task.send_pulses.SendPulses.execute(send_pulses.clj:59)"]

07-09 22:00:01 ERROR generic-sql.query-processor :: Failed to set timezone:
 SQLException:
 Message: Unknown or incorrect time zone: 'Europe/Berlin'
 SQLState: HY000
 Error Code: 1298

**Comment by flamber** [comment]
There has been many connection handling improvement, but I think this was fixed in 0.34.2
