### ISSUE TITLE
Empty space at the sides of the graph

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#7935]
<img width="869" alt="screenshot 2018-06-25 v 18 19 45" src="https://user-images.githubusercontent.com/1764151/41862528-70d1ed8c-78a4-11e8-916d-40e5a952da05.png">
Hello, 
I have the following issue: 

I have some sales data filtered from 2016-01-01 to 2018-10-31, grouped by month. 
When I want to chart that data I always end up with a graph that starts one month earlier and ends one month later than my date range specifies.

In every graph I create I end up with one empty grouping unit before and one after my range. 

These empty units take unnecessary space. That is a problem especially on dashboards where the space is scarce. 

Or am I doing something wrong? 

Beginner MB user here. 

Metabase version 0.29.3
Chrome 67.0.3396.79 (behaves the same way in Firefox)
macOS High Sierra
MSSQL2016
hosted in Docker on private server running Ubuntu 18.04
H2 database

Thx a lot.

**Comment by salsakran** [comment]
are those empty cells present in the table view of just the chart?

**Comment by dfx413** [comment]
They are present just in the chart. The table starts with Jan2016, and end with Oct2018.
