### ISSUE TITLE
GUI Nested Questions do not refresh available schema on SQL question update 

### ISSUE THREAD

**Issue by racewright** [metabase/metabase#7939]
Scenario: 
- User creates an SQL question of in the long form: WITH x AS ( ), y AS ( ) ... SELECT * FROM k. 
- User creates a GUI question referencing SQL question. 
- User makes a change to the SQL question such that a column is added to the final SELECT *. (issue occurs whether columns are explicitly enumerated or not). 

Expected Behaviour: 
- New column / field is available in the GUI question. 

Observed Behaviour:
- New column / field is not available in the GUI question. 

Comments:
This may be related to Issue: [#5507](https://github.com/metabase/metabase/issues/5507). If I had to guess, it seems as though the GUI question retrieves the schema for the nested query once when it's created, and then doesn't recheck it. Having it poll the nested query to get the latest schema on edit might be an easy way to fix.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome: Version 66.0.3359.181 (Official Build) (64-bit)
- Your operating system: OSX 10.12.6 (16G29)
- Your databases: Postgres
- Metabase version: v0.28.1
- Metabase hosting environment: Not sure, probably Elastic Beanstalk.
- Metabase internal database: ?? Not sure. 

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment]
I cannot reproduce this on 0.35.3, but if columns on GUI question are rearranged, then it might be needed to manually add new columns back (or reset to defaults), but that's issue #7612
