### ISSUE TITLE
[ERROR] Front console when trying to load fonts

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7941]
### Bug

- Your browser and the version: Chrome 67.0.3396.62 (64-bits)
- Your operating system: Linux/Ubuntu
- Your databases: Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Linux/Debian
- Metabase internal database: Postgres

![screenshot from 2018-06-26 11-49-50](https://user-images.githubusercontent.com/6808348/41920577-6597ba12-7937-11e8-8a8b-72272568a04e.png)

I'm keeping getting this error at front-end console.

Does anyone have to get this?

**Comment by salsakran** [comment]
is anything rendering?

**Comment by dannyeuu** [comment]
@salsakran The content is blocked by Metabase Content Security Policy that don't allow load Font by base64, second [this doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src).

**Comment by salsakran** [comment]
yes .... but is anything rendering? i.e. is it just a white browser window or is the app rendering but without the right font?

**Comment by fffaraz** [comment]
Is there a way to completely disable content-security-policy header by setting an env var?

**Comment by kdoh** [comment]
@fffaraz There is not to my knowledge a way to disable / remove the CSP header at this time via env var. I'm going to go ahead and close this until @dannyeuu replies with more info on the original issue.
