### ISSUE TITLE
TTFB waiting to long

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#7942]
### Bug

- Your browser and the version: Chrome 67.0.3396.62 (64-bits)
- Your operating system: Linux/Ubuntu
- Your databases: Postgres
- Metabase version: v0.29.3
- Metabase hosting environment: Linux/Debian
- Metabase internal database: Postgres

The endpoint `/api/dashboard?f=all` are with waiting TTFB almost 40 seconds. There are any Bug?

![screenshot from 2018-06-26 12-15-09](https://user-images.githubusercontent.com/6808348/41922095-ba1189f8-793a-11e8-8a0f-a839d2f3ad96.png)

**Comment by tlrobinson** [comment]
@dannyeuu How many dashboards do you have? Regardless, that seems excessive.

**Comment by dannyeuu** [comment]
Thanks, @tlrobinson for your answer! I have 53 dashboards, but this is just a query at the Metabase DB, right? it does not retrieve the dashboards the questions data?

**Comment by salsakran** [comment]
this seems really weird. 

how long is that api call taking in the server logs?

**Comment by dannyeuu** [comment]
We are not having this problem since new releases, so I'm closing this issue, thx!
