### ISSUE TITLE
Way to other data in map "Region field"

### ISSUE THREAD

**Issue by gglebq** [metabase/metabase#7947]
From what I know so far Metabase supports ISO 3166-1 alpha-2 and geoJson data to populate data in map chart.

I was wondering if there is another way to populate the map chart,
My Mongo data consists primary from cell phone data which from all of them you can know the location of the call.
[Im using the World map chart]
1. PLMN
2. MSIN
3. MCC
4. MNC

Metabase version : v0.29.3
Database : MongoDB

**Comment by salsakran** [comment]
You would need to use a custom geojson file with the values your columns have. 

Closing since this is not the appropriate forum for product support. Please ask in our discussion forum http://discourse.metabase.com/
