### ISSUE TITLE
Filter user data logged in

### ISSUE THREAD

**Issue by cmregazzo** [metabase/metabase#7949]
Good afternoon,

I would like to know if it is possible to create "automatic" filters in Metabase.

We are making some inquiries for my sales staff, but each salesperson should only have access to your information.

Is there a way, to make filters through the user that is logged into Metabase?

Thank you.

Cristian Regazzo

**Comment by salsakran** [comment]
@cmregazzo that is not possible in the open source version of Metabase, though we are building a commercial edition of metabase with that feature. If you're interested, we have a beta signup at https://metabase.us10.list-manage.com/track/click?u=869fec0e4689e8fd1db91e795&id=b4ac7d0a0f&e=33e750893d
