### ISSUE TITLE
Record the timestamp when a query is executed

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#7954]
Dear All,
since the number of query saved in the company I work for is now more than 1000, we are thinking to clean Metabase removing old, not useful or not relevant queries.

This is not a simple exercise without knowing when was the last time a query has been executed.

It would be great to have a filed "last_execution_at" in the table ReportCard.
At the moment only "created_at" and "updated_at" are available.

Thanks in advance.

**Comment by flamber** [comment]
Hi @robertobitbond 
You should be able to find the last time the card was executed via `query_execution` - like this:
```SQL
SELECT MAX(started_at) AS last_execution_at, report_card.*
FROM report_card
LEFT JOIN query_execution ON query_execution.card_id=report_card.id
GROUP BY report_card.id
ORDER BY last_execution_at ASC
```
