### ISSUE TITLE
Proposal: get rid of automatic filter widgets in x-rays

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7956]
<img width="749" alt="screen shot 2018-06-28 at 1 22 16 pm" src="https://user-images.githubusercontent.com/2223916/42059026-01953354-7ad7-11e8-8b87-f02b476d2795.png">

After playing with x-rays a bunch, I find these automatic filters to mostly just be getting in the way, especially now that we have drill-through x-rays on charts which feel like they take the place of these filters and promote the browsing UX that we're going for with x-rays. 

I think these filters also make x-rays feel heavier than necessary, and they're often kind of goofy, like in the above screenshot where I'm looking at an x-ray of a segment that is filtered where gender = F, and yet the x-ray includes a filter for gender (if I change it to anything other than F, I obviously get no results). If the filters are unwanted or unhelpful, then they're also yet another thing you have to remove if you've saved the x-ray as a dashboard and are trying to clean it up.

Does anyone else disagree, or find these useful?

**Comment by sbelak** [comment]
On thinking this through, I agree for the most part. Still think we should retain a time-dimension filter where appropriate as there's no easy way to do things such as look at the last 30 days. Drill through x-rays need to become better though as right now what you get using a filter is often more useful than the drill through. Based on this I've opened #10658.

**Comment by brunobergher** [comment]
More of a discussion than an issue, closing.
