### ISSUE TITLE
UndoListing.jsx is throwing errors on update-translations

### ISSUE THREAD

**Issue by mauricio-sonegatti** [metabase/metabase#7957]
https://github.com/metabase/metabase/blob/d24e7006abce7d3c2573238825d564599d36af4d/frontend/src/metabase/containers/UndoListing.jsx#L38

Syntax Error :  Can not translate  '${capitalize(verb)} ${count} ${inflect(subject, count)}'

**Comment by tlrobinson** [comment]
This is a bit tricky since strings that have no non-variable can't be translated in `c-3po`: https://c-3po.js.org/validation.html#format-validation

I'm not sure "${verb} ${count} ${subject}" (e.x. "modified 1 item") could even be reliably translated into every language?
