### ISSUE TITLE
X-raying a nested question results in an error

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7962]
On the `xray-copy-tweaks` branch, if I try to x-ray question based on a saved question, like this:

![screen shot 2018-06-29 at 12 23 14 pm](https://user-images.githubusercontent.com/2223916/42110838-5f463b9a-7b97-11e8-8f4e-aab53eede8de.png)

…then I get this error:

`Don't know how to create ISeq from: metabase.automagic_dashboards.core$eval54505$make_context__54510$fn__54511$fn__54514$fn__54515`

![screen shot 2018-06-29 at 12 24 59 pm](https://user-images.githubusercontent.com/2223916/42110862-763ffb06-7b97-11e8-97e3-19a2311d4401.png)

**Comment by sbelak** [comment]
fixed

**Comment by mazameli** [comment]
Verified this is fixed
