### ISSUE TITLE
Can't do a drill-through x-ray from an official metric x-ray

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7963]
On the `xray-copy-tweaks` branch, if I'm looking at an x-ray for an official metric, e.g. `/auto/dashboard/metric/1`, and then try to do a subsequent x-ray by clicking on a bar/point in a chart, I see an error page with this error:

`Don't know how to create ISeq from: java.lang.Integer`

Here's the definition of my official metric:

![screen shot 2018-06-29 at 12 44 27 pm](https://user-images.githubusercontent.com/2223916/42111711-33fc9b2a-7b9a-11e8-8401-55a58cf289f0.png)

**Comment by sbelak** [comment]
Fixed

**Comment by mazameli** [comment]
Yup, fixed
