### ISSUE TITLE
Cards in segment x-rays should use the segment in their filter definitions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7965]
Clicking through on cards in a segment x-ray reveals that the card is just copying the same filters that are used to define the segment, rather than actually applying the segment as the filter. 

The problem with this is that if and when you save this x-ray, those saved questions don't use the segment, so if the segment ever gets updated/edit, these questions won't be correctly updated as well.

Example:

![segment-x-ray-cards](https://user-images.githubusercontent.com/2223916/42118797-3a64bce2-7bbb-11e8-8c34-cc2f5b2b997c.gif)

**Comment by sbelak** [comment]
fixed

**Comment by mazameli** [comment]
Closing as this was fixed back in July (just verified again).
