### ISSUE TITLE
Date filter is not working correctly [MySQL]

### ISSUE THREAD

**Issue by igisho** [metabase/metabase#7968]
Date filter is filtering also days one day before or one day after day selected in filter. It is same when filtering in sql questions via variables

### Versions and etc.

- Your browser and the version: (Chrome 67)
- Your operating system: (Windows 10)
- Your databases: MySQL
- Metabase version: (0.29.3)
- Metabase hosting environment: (Linux/Ubuntu)
- Metabase internal database: (Postgres)

![screenshot_10](https://user-images.githubusercontent.com/5149231/42152362-2cf71754-7de0-11e8-8531-07afd78bfbef.png)

-------

**Comment by jornh** [comment]
This sounds like it could easily be a time zone related issue. Please check the troubleshooting guide first to see if there’s a known solution:

https://www.metabase.com/docs/latest/troubleshooting-guide/timezones.html

Would be useful for others to know what you ran into — or if the guide didn’t fix it for you of course additional timezone setup you did so it’s possible to try to reproduce and fix the problem. 🙂

**Comment by salsakran** [comment]
@igisho what timezones are your browser, reporting timezone, server timezone and database timezones set to?

**Comment by cemsbr** [comment]
I'm having this issue and this is probably an inconsistent and unexpected behavior. If we use date and time, it is correctly translated from local timezone to UTC (used in MongoDB). However, when we use only dates, it will be considered as UTC instead.

For example, see what actually happens with the timezone -03:00:
- Correct: **July 1, 2018 00:00:00** in Metabase -> **2018-07-01 03:00:00** in MongoDB UTC
- Inconsistent: **July 1, 2018** in Metabase -> **2018-07-01** in MongoDB UTC (implicit time is **00:00:00**)
