### ISSUE TITLE
Save question dialog list of collections goes off the screen and won't scroll all the way down

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#7969]
- Your browser and the version: (Chrome 67.0.3396.99)
- Your operating system: (OS X 10.12.6)
- Your databases: (MySQL)
- Metabase version: (0.28.3)
- Metabase hosting environment: (Docker)
- Metabase internal database: (H2 (default))

- *Repeatable steps to reproduce the issue*
I tried to describe this to @mazameli during our phone call today, but have only just now remembered out how to reproduce it.
1.) From the question GUI, try to save a question
2.) In the dialog that pops up, try to choose a collection in which to save the new question
3.) If there are more collections available to the user than will fit on the screen, the questions towards the end of the alphabet will be cut off by the bottom of the browser window. 
4.) You CAN scroll down to see more options, but the scrolling will not allow the bottommost items to be shown.

Attached is a (redacted) screenshot of our instance showing this problem.  I've scrolled as far down as I'm allowed in the list of collections. There are at least 2-3 more that we have that aren't showing up.  Any thoughts?

<img width="1281" alt="screen shot 2018-07-02 at 3 39 17 pm" src="https://user-images.githubusercontent.com/4392097/42183189-def83770-7e0e-11e8-8f67-0e2d7b61873f.png">

**Comment by salsakran** [comment]
we've changed that component in 0.30, and my guess is that it'll change (and hopefully be fixed). If you can, try to reproduce this with a build from the current master branch.

**Comment by nickhamlin** [comment]
Thanks @salsakran, I spun up a copy of the master branch and confirmed this is fixed there. Feel free to resolve accordingly!
