### ISSUE TITLE
Feature Request - Allow syncing of database more regularly than one hour

### ISSUE THREAD

**Issue by luketainton** [metabase/metabase#7973]
I have a script that imports data from a REST API and places it into a MySQL database every minute. I need to see this update on my dashboard in real-time, and can't as the database is rescanned once an hour at minimum. 

Can we have an option to enter a custom time, instead of selecting from a dropdown list?

**Comment by luketainton** [comment]
Right, OK. It's the data itself that doesn't appear to be queried correctly. I'll keep an eye on it to make sure it's not just me, and update this issue accordingly.

**Comment by jornh** [comment]
@luketainton to me it sounds like you maybe could have been confused over the concept of sync versus that of [dashboard auto refresh](https://www.metabase.com/docs/latest/users-guide/07-dashboards.html#auto-refresh) (which BTW has a drop down to set with refresh times down to 1 minute)? 

Also note if — and with what settings — you configured [caching](https://www.metabase.com/docs/latest/administration-guide/14-caching.html) it could affect if data gets refreshed.

**Comment by salsakran** [comment]
`It's the data itself that doesn't appear to be queried correctly` is possible but unlikely unless as @jornh mentioned you have caching set up.

We always execute each query against the data in the DB you've connected. I'm closing this issue unless you find something working incorrectly in Metabase. Debugging ETL flows and data freshness is way outside of the scope of this issue tracker.
