### ISSUE TITLE
All users can see questions that are in collections with "No access" permissions for "All Users"

### ISSUE THREAD

**Issue by dhinus** [metabase/metabase#7974]
There seems to be something broken with the collection permissions. Users that are not part of any group can still view some questions that are part of collections with "No access" permissions set for the "All Users" group.

![screen shot 2018-07-03 at 12 35 34](https://user-images.githubusercontent.com/474311/42215090-b29c64f8-7ebd-11e8-93c5-9666e639c19d.png)

We have been running this instance of Metabase for a few years now, and upgraded it a few times, so it's possible there is something weird in our Metabase db. Any hint on what I should check? The `permissions` table has no line with `group_id=1`, which is the ID of the "All Users" group.

- Metabase version: 0.29.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres (RDS)

**Comment by seeramzan** [comment]
I am also facing same error but on embedded dashboard.

**Comment by salsakran** [comment]
when you say "still view" do you mean that they can copy+paste the question url into their browser and get to the question, or that the question is visible in a list of questions somewhere?

**Comment by gabro** [comment]
@salsakran the user can see some of the dashboards (not all of them, the logic is unclear) and when they click on a dashboard they can see some of the questions (again, not all of them and it's not immediately clear which ones are allowed).

**Comment by dhinus** [comment]
@salsakran some additional info: the questions that we expect not to be accessible are **not** visible on the `/questions` page, but are visible if you add their id, i.e. `/question/92`.

**Comment by gabro** [comment]
Hi @salsakran, I see the bug has been marked with a high priority, do you have any time span for when it will be addressed? Thank you!

**Comment by mazameli** [comment]
I was unable to reproduce this locally on master. Have not yet tried on version 0.29.3.

I set a non-admin user to be a part of only the All Users group, and tried navigating to a collection for which they had No Access, but I didn't see the collection listed. Trying to go directly to the collection's url or to the url of a qustion in it (e.g. /collection/18 or /question/20) resulted in a permissions error. Searching for the question by name resulted in no search results.

**Comment by dhinus** [comment]
Possibily related: https://github.com/metabase/metabase/issues/7505

**Comment by jornh** [comment]
@dhinus @gabro and @seeramzan  did you guys have a chance to take v0.30 for a test spin and see if it resolves the issue on your particular configurations?

Note: As mentioned in https://github.com/metabase/metabase/issues/7505#issuecomment-385819817 v0.30 contains big changes to permissions. Make sure to read up, test and plan accordingly.

@dhinus you mentioned #7505 as “possibly related” above. Would be interesting to know if the cases you have experienced e.g. your `/question/92` have been publicly shared or not. Though depending on if v0.30 mentioned above resolves this might now only be of “academic” interest by now.

**Comment by dhinus** [comment]
> Would be interesting to know if the cases you have experienced e.g. your /question/92 have been publicly shared or not.

Yes I think they were all publicly shared.

> I've managed to test this on 0.30 and it seems to be working as expected now!

I double checked and I confirm upgrading to 0.30 have fixed the issue.

**Comment by jornh** [comment]
@dhinus and @gabro thanks for following through - and the extra info. Makes it worth it for me to spend time on triage/pinging people. Thanks!
