### ISSUE TITLE
Bin continuous values into discrete bins in breakout histograms and filters

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#798]
When filtering by a continuous variable in a field, say price, it would be useful to be filter on a range. Similarly it would be useful to have a breakouts of a continuous variable (say age) be available as a histogram instead of a line chart of every possible value. 

This is especially useful for fields like latitude or longitude where there is a clear min, and max but there are a large number of values that are very close together. In this case a chart where every single latitude is it's own value on the dimension axis is much less useful than one where they are binned intelligently.

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by CTres** [comment]
:+1: histograms would be incredible!

**Comment by tlrobinson** [comment]
+1

**Comment by MartinBohman** [comment]
+1

**Comment by tlrobinson** [comment]
@metabase/core-developers What needs to be designed for this?

* I imagine we'd have something similar to the date granularity picker in the grouping popover?
* Do we allow the user to select a bin size, or the number of bins (can that be done in SQL etc?)

**Comment by moumny** [comment]
Im not sure this is related. But the UI should work as well for special types like approximate histograms. For example Druid has http://druid.io/docs/latest/development/extensions-core/approximate-histograms.html

**Comment by tlrobinson** [comment]
Hexagonal binning for 2D would be super nifty but obviously more difficult, especially without "composite" dimensions.

![image](https://cloud.githubusercontent.com/assets/18193/25327011/5aa39718-2887-11e7-8f9c-e5c20069e294.png)

https://www.mapbox.com/blog/binning-alternative-point-maps/
http://www.meccanismocomplesso.org/en/hexagonal-binning/

**Comment by nickhamlin** [comment]
+1, would love histograms!

**Comment by camsaul** [comment]
Hey everyone, one way we prioritize issues is by sorting them by the number of 👍 reactions on each issue's description. So instead of leaving `+1` or 👍  comments, please just upvote by adding a reaction to the issue description.

**Comment by mazameli** [comment]
@nickhamlin and everyone else who was interested in histograms: the latest version of Metabase includes histograms in GUI-created questions. Just break out an aggregation by a continuous numeric field, and choose the Bar visualization:

<img width="1404" alt="screen shot 2017-10-10 at 12 07 23 pm" src="https://user-images.githubusercontent.com/2223916/31405381-be97948e-adb3-11e7-8237-ab6f524a4f45.png">

You can adjust the binning settings by clicking on the grouping field like this:

<img width="1418" alt="screen shot 2017-10-10 at 12 07 35 pm" src="https://user-images.githubusercontent.com/2223916/31407476-ec44a240-adb9-11e7-9fce-e994e869cf9c.png">

SQL/native query histograms aren't quite there yet, (unless I'm missing something):

<img width="1363" alt="screen shot 2017-10-10 at 12 52 22 pm" src="https://user-images.githubusercontent.com/2223916/31407505-ff8ca55a-adb9-11e7-89d7-a02aa397dfc8.png">

**Comment by nickhamlin** [comment]
Thanks @mazameli! This is great.  We finally got a chance to upgrade to the latest version today (0.26.2).  I went to test this out, but I'm not getting the bin options to appear.  I've checked that the field is set as a number in the schema and I'm using the bar visualization.  Is there anything in particular I need to do to enable this functionality?  Screenshot is here:

![image](https://user-images.githubusercontent.com/4392097/32568626-da5d6f14-c48c-11e7-8e12-a74610aa0d10.png)

Many thanks!

**Comment by camsaul** [comment]
@salsakran @senior was this implemented by PRs #5331/#5342?

**Comment by senior** [comment]
@camsaul yes. #5342 was merged into #5331, so that's the right place to look. The image above looks like it's our sample dataset. We don't have binning options on our sample dataset. It's a known issue, written up as https://github.com/metabase/metabase/issues/6003. The sync process doesn't run on the sample data, so min/max values don't get collected. We only allow binning on columns we know the min/max values for.

**Comment by nickhamlin** [comment]
Thanks @senior, if it's helpful, I wasn't seeing the binning options on any of my other datasets either.  I also tried rerunning the sync process for each of database beforehand, but didn't see a change.  Since it looks like the bin options appeared in @mazameli 's screenshot above (which AFAIK is also using the sample dataset), I figured I'd try to recreate that as closely as possible.

**Comment by camsaul** [comment]
Implemented in #5331

**Comment by MarkRx** [comment]
How does this work with custom SQL?
