### ISSUE TITLE
Organize x-ray suggestions sidebar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7983]
This is a simple idea for adding some structure to the x-ray suggestions sidebar.

Here's the information architecture that this layout assumes. For any given x-ray a user is viewing, there can be up to four sections of suggested x-rays in the sidebar. I think we could still limit the sidebar to having 6–8 suggestions total, allowing other sections to display more suggestions if there are 0/1 suggestions in other section(s).

- "Compare"
  - Compare this segment to another segment
  - Compare this segment to the whole dataset
  - See a comparison of a different, related segment vs. the whole dataset
- "Zoom In"
  - Field of the current table
  - Transaction table by dimension 
  - (Future) Zoom in to a specific interesting time range
- "Zoom Out"
  - X-ray of the table the current x-ray uses/is based on
  - X-ray of the field the current x-ray uses/is based on
- "Related"
  - X-ray of an official metric related to the current thing being x-rayed
  - X-ray of a segment of the current table
  - X-ray of another table in this DB that's linked by FK
  - X-ray of another table in this DB
  - Saved questions that use the same table or metric currently being x-rayed

We could use other icons in place of the current bolt icon in the sidebar to help differentiate different types of x-rays from each other, and add section headings like this:

![sidebar-1](https://user-images.githubusercontent.com/2223916/42350621-274aee6a-8066-11e8-929e-a10f034541b4.png)

A separate additional idea would be to have each section include a refresh icon to show different suggestions of that type of x-ray:

![sidebar-2](https://user-images.githubusercontent.com/2223916/42350625-2a35e7d8-8066-11e8-831d-591b9c18d830.png)

**Comment by sbelak** [comment]
What about something like "more" instead of refresh?

**Comment by sbelak** [comment]
BE implemented in #8142

**Comment by mazameli** [comment]
Closing, since we did this last year.
