### ISSUE TITLE
Collection breadcrumbs are wrong after moving a collection

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7989]
This is on our Stats instance.

- Create a few levels of sub and sub-sub collections
- Move one of the nested subcollections up a few levels
- Notice that when you go to the detail view for the moved subcollection, it's breadcrumb path remains the same as when it was initially created. It doesn't update with its new correct path.

Example after I've moved some collection:

![collection-breadcrumbs](https://user-images.githubusercontent.com/2223916/42396465-a415bab4-8116-11e8-9e48-05a987a69e82.gif)

**Comment by mazameli** [comment]
@tlrobinson Mentioned this to @kdoh, but I'm still seeing this issue on master. Simplified description of the behavior is that whenever you move a collection through any means, its breadcrumb path doesn't update until you hard refresh.

**Comment by tlrobinson** [comment]
Fixed in #8120
