### ISSUE TITLE
Document new features and changes in 0.30

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7995]
- [ ] Changes to collections:
  - [ ] Overworld
  - [ ] Data browsing
  - [ ] Creating new collections, dashboards, pulses
  - [ ] Sub-collections
  - [ ] Pinning
  - [ ] Personal collections
  - [ ] Updated permissions grid
- [ ] Search
- [ ] Conditional formatting for tables
- [ ] Comparison x-rays
- [ ] Adding available fields to a table

Anything else I'm forgetting?

**Comment by xjzhou** [comment]
looking forward to ^_^
