### ISSUE TITLE
Unable to use the question builder

### ISSUE THREAD

**Issue by MitchSaad** [metabase/metabase#7997]
Hey guys,

I've just finished setting up Metabase, and i'm currently experiencing the following issue with the question builder.

![screen shot 2018-07-09 at 12 18 44 pm](https://user-images.githubusercontent.com/32118205/42427604-bd16303a-8372-11e8-9574-87cb92595ac8.png)

Initially the table dropdown was stuck loading, but upon refresh of the page, the schema names became available. Now the table selector is stuck open, and i can't access any of the tables from either schema. Trying to use anything in the builder throws a react error, one of which seems to indicate it can't find the schema properties (DataSelector.jsx:767). Running queries in the raw SQL tool works just fine.

Any help would be appreciated.

- Your browser and the version: Chrome 67.0.3396.99
- Your operating system: OS X 10.13
- Your databases: Postgres
- Metabase version: 0.29.3 
- Metabase hosting environment: Docker/kubernetes
- Metabase internal database: Postgres

**Comment by salsakran** [comment]
Can you share the table names of one of the schemas you're using?

**Comment by alfonsostratio** [comment]
Hi,

I've just tested metabase 0.29.4 with a Postgres database with 2 schemas (public, public2) and replicate the same issue. It seems is not getting correctly the schema name. I've verified the metabase table 'metabase_table', and the column 'schema' is correct (paste 2 rows):

"15";"2018-08-01 10:03:05.226+00";"2018-08-01 10:03:07.237+00";"test2";;"";"";"entity/GenericTable";TRUE;2;"Te St2";"";"public2";;"";"";FALSE
"16";"2018-08-01 10:03:05.232+00";"2018-08-01 10:03:07.232+00";"test1";;"";"";"entity/GenericTable";TRUE;2;"Tes T1";"";"public";;"";"";FALSE

**Comment by MitchSaad** [comment]
@salsakran sorry i missed this - the public schema contains all the metabase tables, `metric` for example. In order to meet a deadline i ended up dropping the DB and starting again, that seemed to fix the issue. Not sure what caused it originally, but it's been smooth sailing since then.

**Comment by salsakran** [comment]
it sounds like for some reason the sync process didn't complete successfully, but only pulled out the schema names from your database. This might be a situation where we should harden the sync process, but it _should_ have caught the tables on the next sync in any event.

**Comment by camsaul** [comment]
@salsakran keep in mind the only place we store schemas are as part of Tables, not as first-class objects themselves. So there's no way we could have a schema without it having any Tables. Rereading the issue description it sounds like this might be an issue with the Table drop-down.

@alfonsostratio how are you using Metabase 0.29.4? The latest release is 0.29.3

**Comment by salsakran** [comment]
ahh, yes. What Cam Said =)

**Comment by MitchSaad** [comment]
@alfonsostratio @camsaul https://ae01.alicdn.com/kf/HTB1YXEVMVXXXXcZaXXXq6xXFXXXi/Doctor-Who-Tardis-Bath-Towel-Microfiber-Beach-Towel-serviette-de-plage-toalha-Sport-Drying-Travel-Towels.jpg_640x640.jpg

**Comment by mbvictoria** [comment]
Closing - resolved.
