### ISSUE TITLE
Color consolidation cleanup

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#8002]
Hover for user actions not visible 

![screen shot 2018-07-09 at 1 51 09 pm](https://user-images.githubusercontent.com/107439/42475343-3629d4d4-837f-11e8-8c7e-ba27b43c96e9.png)

Whites/Greys feel out of balance
![screen shot 2018-07-06 at 6 07 00 pm](https://user-images.githubusercontent.com/107439/42475376-4da1261c-837f-11e8-9074-26391713cfde.png)

dashboard filters look washed out
![screen shot 2018-07-09 at 1 45 57 pm](https://user-images.githubusercontent.com/107439/42475396-5c1114be-837f-11e8-9f0f-844aa11b6804.png)

**Comment by kdoh** [comment]
Is this still a thing? If so can we get some TODOs going in this issue or link to other issues?

**Comment by tlrobinson** [comment]
These all seem resolved to me.
