### ISSUE TITLE
Personal collection weirdness on a fresh install

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8019]
This is on master in Chrome. 

On a fresh install, my personal collection is just floating around like a regular ol' dumb normie collection. If I click on the true `My personal collection` link, I get an `API endpoint does not exist` error. Weirdly, if I move my bizzarro personal collection into the real personal collection, the former one vanishes, never to be seen again, like Keyser Söze.

![fresh-install](https://user-images.githubusercontent.com/2223916/42541821-e0c7e2a8-8458-11e8-8358-e3372cbcacc4.gif)

**Comment by salsakran** [comment]
what's interesting is that if you refresh, it goes away

**Comment by tlrobinson** [comment]
This is due to `/api/user/current` having a `personal_collection_id` of `null` the first time it's called for new users.

**Comment by camsaul** [comment]
Fixed by #8036
