### ISSUE TITLE
metabase reports different results than psql

### ISSUE THREAD

**Issue by josh-m-sharpe** [metabase/metabase#8029]
ffx 60
PostgreSQL 9.6.8 on x86_64-pc-linux-gnu (Ubuntu 9.6.8-1.pgdg14.04+1), compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4, 64-bit
metabase v0.29.3
Elastic Beanstalk
internal db: good question... I used the beanstalk docker image.

`mb_states_reacheds` is a view.  It is *not* materialized.  As far as I know there's no caching anywhere.

<img width="933" alt="3__psql_and_question_ _metabase" src="https://user-images.githubusercontent.com/39473/42588721-9e5c1bfa-850c-11e8-99b2-0fc45da958b0.png">

**Comment by salsakran** [comment]
Can you share the view definition? 

At the risk of sounding obvious, are you sure you're pointing at the same database? Does everything work normally for other tables?

**Comment by josh-m-sharpe** [comment]
It's definitely pointing to the same DB.

```
WITH
  time_mapping_last_state (name, start, _end, _order) AS
  ( SELECT *
    FROM ( VALUES
      ('Current Queue', (DATE_TRUNC('month', CAST('2018-05-01' AS date))),                    NOW(), 1),
      ('Last Hour',     (NOW() - INTERVAL '1 hour'),                                          NOW(), 2),
      ('Last 24 Hours', (NOW() - INTERVAL '1 day'),                                           NOW(), 3),
      ('1 day ago',     (DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-1 day')),  DATE_TRUNC('day', (NOW() at time zone 'EST')), 4),
      ('2 days ago',    (DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-2 day')),  DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-1 day'), 5)
    ) t
  )

SELECT
  name,
  state,
  COUNT(state) as _count,
  utm_campaign,
  utm_source,
  utm_medium,
  utm_term,
  utm_content

FROM (
  SELECT
    name,
    (array_agg(state ORDER BY timestamp DESC))[1] AS state, -- the last state for this token in the given timeframe
    visitor_token,
    utm_campaign,
    utm_source,
    utm_medium,
    utm_term,
    utm_content,
    _order

  FROM
    time_mapping_last_state

  LEFT JOIN
    mb_visit_state_changes
  ON
    mb_visit_state_changes.timestamp BETWEEN time_mapping_last_state.start AND time_mapping_last_state._end

  GROUP BY
    time_mapping_last_state.name,
    mb_visit_state_changes.visitor_token,
    utm_campaign,
    utm_source,
    utm_medium,
    utm_term,
    utm_content,
    _order
) s1

GROUP BY
  name,
  state,
  utm_campaign,
  utm_source,
  utm_medium,
  utm_term,
  utm_content,
  _order

ORDER BY
  _order


```

**Comment by jsharpe-mr** [comment]
The few other tables I've tried all seem to report the same info.

**Comment by salsakran** [comment]
Ok, I'm 90% sure this is timezone related, though it's strange you only get this with a view. 

Couple questions to help narrow down exactly what's happening:
1. If you run the view definition as a native sql question in MB (eg `select count(*) from <view query>`, what do you get?
2. What are your: database timezone, metabase server timezone, browser timezone, and the timezone on the machine you're running psql on?
3. Which of those two numbers is correct?

**Comment by josh-m-sharpe** [comment]
Interesting.  I updated the query to correctly offset those NOW() calls to EST... and that seems to have cleared it up.  Still kinda odd, right?  

My laptop and browser are set to EST.
I launch psql with `heroku pg:psql` - which I believe just wraps local psql.
From that, `show timezone` shows UTC.
I'm not sure how to figure out what metabase is running in.  I originally launched this instance on Beanstalk via https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html and I'm not sure I set up ssh access correctly to verify from within.  Timestamps in the Beanstalk log dumps seem to be all over the place.  Some UTC (nginx) others seem to be in EST.  The instance was setup in EST.  Can the metabase UI tell me?

Updated query: 
```
WITH
  time_mapping_last_state (name, start, _end, _order) AS
  ( SELECT *
    FROM ( VALUES
      ('Current Queue', (DATE_TRUNC('month', CAST('2018-05-01' AS date))),                    (NOW() at time zone 'EST'), 1),
      ('Last Hour',     ((NOW() at time zone 'EST') - INTERVAL '1 hour'),                     (NOW() at time zone 'EST'), 2),
      ('Last 24 Hours', ((NOW() at time zone 'EST') - INTERVAL '1 day'),                      (NOW() at time zone 'EST'), 3),
      ('1 day ago',     (DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-1 day')),  DATE_TRUNC('day', (NOW() at time zone 'EST')), 4),
      ('2 days ago',    (DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-2 day')),  DATE_TRUNC('day', (NOW() at time zone 'EST') + INTERVAL '-1 day'), 5)
    ) t
  )

SELECT
  name,
  state,
  COUNT(state) as _count,
  utm_campaign,
  utm_source,
  utm_medium,
  utm_term,
  utm_content

FROM (
  SELECT
    name,
    (array_agg(state ORDER BY timestamp DESC))[1] AS state, -- the last state for this token in the given timeframe
    visitor_token,
    utm_campaign,
    utm_source,
    utm_medium,
    utm_term,
    utm_content,
    _order

  FROM
    time_mapping_last_state

  LEFT JOIN
    mb_visit_state_changes
  ON
    mb_visit_state_changes.timestamp BETWEEN time_mapping_last_state.start AND time_mapping_last_state._end

  GROUP BY
    time_mapping_last_state.name,
    mb_visit_state_changes.visitor_token,
    utm_campaign,
    utm_source,
    utm_medium,
    utm_term,
    utm_content,
    _order
) s1

GROUP BY
  name,
  state,
  utm_campaign,
  utm_source,
  utm_medium,
  utm_term,
  utm_content,
  _order

ORDER BY
  _order
```

**Comment by salsakran** [comment]
We have a PR that would show you, but we don't have a way to surface the server/jvm timezone in the UI.

These kinds of things occur because there are 4-5 timezones at play that can all result in a weird timezone cast along the way. 

Glad to hear that an explicit tz set fixes this. I'm going to close this you got it to work, and it's not something completely broken in MB. We've got a batch of TZ changes made in a PR, and I expect that this will be cleaned up in that.
