### ISSUE TITLE
Migrate dashboards, pulses, and questions not in a collection when upgrading to 0.30

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8031]
In 0.30 dashboards and pulses will be saved in collections rather than on separate list pages. Additionally, there will no longer be any notion of saved questions existing outside of a collection (i.e. in the weird "Everything Else" area where they can currently be saved).

Consequently we'll need to move existing dashboards, pulses, and questions-not-in-a-collection to a new location when users upgrade their instance to 0.30 from a previous version.

**The user feedback we've received points to a UX that would do the following:**
1. Set permissions to the root `Our analytics` collection to `View` access for all user groups.
2. Create three new collections within the root collection: "Migrated dashboards," "Migrated pulses," and "Migrated questions." 
3. The permissions settings for these new collections should be set to No Access for all user groups except Administrators.
4. Existing dashboards, pulses, and questions from the "Everything Else" area should now be present within these new collections.

**The reasoning for this is:**
- It's the safest route from a permissions perspective. Nothing will be accidentally exposed.
- It's very easy to instantly change things to be open to all users by simply changing the permissions settings on the migrated collection(s).
- It will help prompt administrators to place dashboards and pulses into new logical places.

**Comment by jinchener** [comment]
Wondering when will the 0.30 version be released.

**Comment by camsaul** [comment]
Implemented in #8162
