### ISSUE TITLE
Oracle DB not listed when running Metabase as Service on Centos

### ISSUE THREAD

**Issue by kumardharm2007** [metabase/metabase#8042]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Chrome Version 67.0.3396.99 (Official Build) (64-bit), Firefox Quantum 61.0.1 (64-bit)
- Your operating system: Windows 10 
- Your databases: Oracle Database 11g
- Metabase version: v0.29.3 (0de4585 release-0.29.3)
- Metabase hosting environment: Centos7
- Metabase internal database: H2 (default)

When metabase is ran via terminal with direct command like 
/home/bkmetabase/jdk1.8.0_171/bin/java -jar metabase.jar > logger_metabase.log
Metasbase starts and during setup Oracle as a Database is listed in Database drop down, but when we create a service to run metabase as a background process we are unable to find Oracle in DB list
- *Repeatable steps to reproduce the issue*

Directory Structure of  Deployment
---------------------------------------
1. Copy metabase jar along with plugin directory (with oracle driver) 
[bkmetabase@BK01 MetaBase]$ pwd
/home/bkmetabase/MetaBase
[bkmetabase@BK01 MetaBase]$ ll
total 119488
-rw-rw-r-- 1 bkmetabase bkmetabase      3975 Jun  28 07:52 logger_metabase.log
-rw-rw-r-- 1 bkmetabase bkmetabase   7503872 Jun  28 07:52 metabase.db.mv.db
-rw-rw-r-- 1 bkmetabase bkmetabase       187 Jun  28 12:12 metabase.db.trace.db
-rw-rw-r-- 1 bkmetabase bkmetabase 114839203 Jun  28 13:10 metabase.jar
drwxrwxr-x 2 bkmetabase bkmetabase      4096 Jun  28 12:05 plugins
[bkmetabase@BK01 MetaBase]$ cd plugins/
[bkmetabase@BK01 MetaBase]$ ll
total 3320
-rw-rw-r-- 1 bkmetabase bkmetabase 3397734 Jun  28 17:13 ojdbc7.jar

2. Setup MB_PLUGIN_DIR as a environment variable 
[bkmetabase@BK01 MetaBase]$ echo $MB_PLUGINS_DIR
/home/bkmetabase/MetaBase/plugins

3. Create a service with below information 
SERVICE_NAME=Metabase
METABASE_DIR=/home/bkmetabase/MetaBase
METABASE_JAR=$METABASE_DIR/metabase.jar
METABASE_PORT=6767
METABASE_DB=$METABASE_DIR/metabase.db
METABASE_PID=$METABASE_DIR/metabase-pid

JAVA_PATH=/home/bkmetabase/jdk1.8.0_171/bin/java  

4. Start the service
5. Start metabase setup and select Database drop-down 
6. Check if Oracle is present or not

![2e4c34df63d6bc390add422bb67d17aec3c17f7c](https://user-images.githubusercontent.com/10600818/42610193-e25848ec-857f-11e8-8eb4-85da44254f6e.png)

-------

**Comment by jornh** [comment]
Discussion of this already happening in this Metabase discource topic:

http://discourse.metabase.com/t/oracle-db-not-listed-when-run-as-service-on-centos/3824

**Comment by salsakran** [comment]
This is a classpath problem with how you are setting up the service running Metabase. 

Closing this as it's outside the scope of the issue tracker. If you discover something in the discourse topic that is either a bug in Metabase or a need for better documentation please chime in and I will re-open.
