### ISSUE TITLE
Resizing a region map causes weirdness

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8046]
This is on master on Chrome. Resizing the browser window when looking at a region map can allow it to collide with the query builder bar:

![screen shot 2018-07-12 at 11 52 25 am](https://user-images.githubusercontent.com/2223916/42653390-3279d7c4-85ca-11e8-9a21-a288a31d9377.png)

It can also cause a situation where the white background of the page ends, and gray page background is revealed (a little hard to see in this downsampled gif), while the Explore bauble button is no longer pinned to the bottom-right corner of the page:

![region-map](https://user-images.githubusercontent.com/2223916/42653453-5e191b88-85ca-11e8-91c6-455571acf1d4.gif)

**Comment by flamber** [comment]
I don't remember when this was fixed, but I think it was part of 0.33 redesign - this is 0.35.3:
![image](https://user-images.githubusercontent.com/1447303/82742700-a55dd500-9d61-11ea-9e38-6bcab50ecee1.png)
