### ISSUE TITLE
Dashboard filter - drilldown to foreign keyed entity record fails

### ISSUE THREAD

**Issue by littlegoblin9876** [metabase/metabase#8055]
- Your browser and the version:  Chrome 49.0.2623.75 (64-bit) & Firefox 62.0b7 (64-bit)
- Your operating system: Ubuntu
- Your databases:  Postgres 9
- Metabase version: v0.29.3
- Metabase hosting environment: CentOS 6
- Metabase internal database: Postgres 9

- *Repeatable steps to reproduce the issue*

1. Create data source tables : 1. Sales table w/ ProductID column & Customer ID column FK'd to  2. Customer table
2. Define Entity ID  for each table and define FK relationship in Metabase datamodel
3. Create question using Sale Table grouping by customer id and reporting count(sales)
4. Embed in dashboard
5. Add Product filter to dashboard
6. Add customer filter to dashboard
7. Save dashboard
8. Set values for both filters
9. Click on "Customer ID" in table and select "View Details"
10. Throws error: **Query expansion failed: could not find table 149 (FK ID = 1507). Resolved tables ([fk-id table-id]): ([nil 151])**
11. Remove ProductID from filter - refresh - customer details displays

It appears when drilling down to view the details of an entity displayed in the dashboard, it applies all the filters irrespective of whether the associated column exists for that entity

-------
:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
This was encountered in the forum too on 0.33.2:
https://discourse.metabase.com/t/error-on-drilldown-table-is-not-present-in-the-query-processor-store/7272

Steps to reproduce:
1. Ask a simple question on Orders and save it.
2. Add the question to a dashboard.
3. Add a filter - i.e. Time:All options and connect to "Created At" column - and save dashboard.
4. Define the filter - i.e Past 30 days.
5. Click field in a FK-column - i.e "User ID" - and select "View details".
6. Errors with `Error: Table 11 is not present in the Query Processor Store.` - the number might change depending on the table ID.

**Comment by andreychirikba** [comment]
I now get the same very error when applying a dashboard filter to an aggregated query:
![image](https://user-images.githubusercontent.com/30152071/75710553-10e55880-5cc5-11ea-8b05-c4427b60d209.png)
The "Datum tussen" ("Date between") bit was added by a dashboard date filter. When I open the editor and run the query again (with the same filter), it does show the results. However, not when called with the filter from the dashboard.

**Comment by ferarnoled** [comment]
This happened to me also when I changed the source of the underlying question.
For example Question 1 was using table 1 as the source. Changed Question 1 to use Table 2.
After that the dashboard started throwing `Error: Table 11 is not present in the Query Processor Store.` error. After removing and adding back the filters it started working
