### ISSUE TITLE
SparkSQL in Metabase Mac app not working

### ISSUE THREAD

**Issue by narenreddycs** [metabase/metabase#8058]
Hi,
I am new to Metabase and trying to connect to SparkSQL database in Metabase Mac app. I followed the below steps (mentioned here - https://www.metabase.com/docs/latest/administration-guide/databases/spark.html)

1. Downloaded the required SparkSQL JDBC jar
2. Copied the jar to - /Users/nsan/Library/Application Support/Metabase/Plugins/
3. Restarted the Metabase

After the Restarting the Metabase - I am trying to add a new Database but still not seeing SparkSQL as one of the Database types in Metabase. Not sure what I am missing here.  I am using Metabase 0.29.3.0

**Comment by vedantja** [comment]
Running into the exact same issue as above. Any resolution?

**Comment by narenreddycs** [comment]
I couldn't make it work with Mac app, so I am running Metabase jar along with SparkSql jar.

**Comment by vedantja** [comment]
Did you need the Spark jdbc driver (one provided by Simba) also?

**Comment by narenreddycs** [comment]
no need, jar from https://www.metabase.com/docs/latest/administration-guide/databases/spark.html should suffice.

**Comment by JoyinZhang** [comment]
> no need, jar from https://www.metabase.com/docs/latest/administration-guide/databases/spark.html should suffice.

Have you solved your problem?My latest version (0.31.1) also has this problem

**Comment by JoyinZhang** [comment]
> > no need, jar from https://www.metabase.com/docs/latest/administration-guide/databases/spark.html should suffice.
> 
> Have you solved your problem?My latest version (0.31.1) also has this problem

version (0.31.0) works fine

**Comment by vietvudanh** [comment]
Anyone has solution?
Tried on MacOS, Ubuntu on both metabase.jar and MacApp, both not showing.

The loading log showed that the plugins loaded though:

```
12-15 16:49:36 INFO metabase.plugins :: Loading plugins in directory /Users/vietvu/Documents/runnable/metabase/plugins...
12-15 16:49:36 INFO metabase.plugins :: Loading plugin /Users/vietvu/Documents/runnable/metabase/plugins/metabase-sparksql-deps-1.2.1.spark2-standalone.jar... 🔌
```

**Comment by prmdsharma** [comment]
Same issue on Mac with 0.31.1. Any solution ??

**Comment by vietvudanh** [comment]
@prmdsharma you can check #9113 , for me just compile plugins by myself solved it.

**Comment by prmdsharma** [comment]
Any idea why I am getting this warning  - 

/Applications/Metabase.app/plugins/metabase-sparksql-deps-1.2.1.spark2-standalone.jar... 🔌
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?

**Comment by prmdsharma** [comment]
> @prmdsharma you can check #9113 , for me just compile plugins by myself solved it.

Thanks now its working for me after building the jar from source.

**Comment by wjoel** [comment]
Seems the SparkSQL-deps .jar and the Metabase .jar are no longer signed with the same key.

Building both from source and not signing either .jar file works. The fact that just building the SparkSQL-deps .jar from source makes me suspect that the latest release of Metabase simply wasn't signed.

**Comment by flamber** [comment]
Closing, since the required dependency is no longer needed since 0.32
