### ISSUE TITLE
Central div of email not lined up with title + footer

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#806]
This is in hotmail on chrome. Haven't tested it on other browsers/etc. 
![screen shot 2015-07-30 at 2 47 39 pm](https://cloud.githubusercontent.com/assets/107439/8996027/09dadbe4-36ca-11e5-8a14-7a681773e997.png)

**Comment by salsakran** [comment]
no idea what's up but I just visited the same email in chrome (probably updated) and it looks like
![screen shot 2015-11-25 at 1 54 27 pm](https://cloud.githubusercontent.com/assets/107439/11410397/edc2cef8-937b-11e5-8403-2d059ed8a7c9.png)

**Comment by tlrobinson** [comment]
Ok, closing.
