### ISSUE TITLE
Variable filter work invert of choice

### ISSUE THREAD

**Issue by jiremek** [metabase/metabase#8062]
Hello,
When the request is eddited with SQL editor, the variable checked not work.
for me, if i Choose normal then the "ocr_nok' result will be displayed.
All work normaly if I choose "not in({{variable}})" ... but it's anormal.

![image](https://user-images.githubusercontent.com/3496127/42726995-52c549c0-879e-11e8-9f79-1ee981a62d17.png)

MySQL.
Metabase 0.29.3

**Comment by salsakran** [comment]
Does this also occur in 0.30.4? 

And how are you defining `type__camp` here?

**Comment by flamber** [comment]
Closing, since no reply. If `type__camp` is a Field Filter, then use a sub-query:
https://discourse.metabase.com/t/dashboard-filter-to-exclude-values/9983
