### ISSUE TITLE
Can't create Metabase App on AWS Elastic Beanstalk: The following resource(s) failed to create: [AWSEBRDSDBSubnetGroup, AWSEBLoadBalancerSecurityGroup].

### ISSUE THREAD

**Issue by gitsh84** [metabase/metabase#8064]
I've been trying to create an AWS elastic beanstalk app but keep getting this error and creation is aborted:

Stack named 'awseb-e-htmw99zsqj-stack' aborted operation. Current state: 'CREATE_FAILED' Reason: The following resource(s) failed to create: [AWSEBRDSDBSubnetGroup, AWSEBLoadBalancerSecurityGroup].

->

Creating security group named: sg-2188486b failed Reason: Resource creation cancelled.  
  
The error is consistent, meaning it happens every time I try to create the app.
Note that I have successfully created multiple apps on my AWS account (they are currently running).  
  
The configuration used is exactly as stated here:  
https://metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html#running-metabase-on-aws-elastic-beanstalk

**Comment by gitsh84** [comment]
It seems that the problem is the limit on RDS Subnet groups. I've requested to increase my limit.
I will update once this is approved if it helped.

**Comment by Chipandcharge** [comment]
Hey, seems that i experience the same issue. Do you have any improvements or solutions?

**Comment by jornh** [comment]
Same topic in [this Discourse topic](http://discourse.metabase.com/t/cannot-setup-on-aws-in-vpc/2166?jornh)

**Comment by salsakran** [comment]
@gitsh84 did this issue get resolved? It sounds like it was an issue with your AWS account limits. 

Or was there something specific to our beanstalk recipe?

**Comment by flamber** [comment]
Closing, since it seems to be AWS limits - out of our control:
https://discourse.metabase.com/t/cannot-setup-on-aws-in-vpc/2166/2?u=flamber
https://stackoverflow.com/questions/44723601/elastic-beanstalk-fails-to-create
https://stackoverflow.com/questions/50835402/unable-to-create-elastic-beanstalk-environment-with-rds-in-aws
