### ISSUE TITLE
"Cannot read property 'show_in_getting_started' of undefined" when saving Data Reference "Start here."

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [metabase/metabase#8066]
I see similar issues with charts here but not specifically with Data Reference.
I cannot save "Start here." page in Data Reference.

When trying to save /reference/guide I receive the following error:
Cannot read property 'show_in_getting_started' of undefined

Metabase is installed in a Heroku dyno.
macOS High Sierra 10.03.5
Google Chrome 67.0.3396.99

**Comment by salsakran** [comment]
What version of metabase are you on?

**Comment by salsakran** [comment]
We've removed the getting started guide in our latest version, so you shouldn't be seeing this. If you are on a version prior to 0.30, then we won't be fixing bugs in a feature we removed in a subsequent version

**Comment by mbvictoria** [comment]
Closing - deprecated feature.
