### ISSUE TITLE
Password reset with expired/used token doesn't show an error message or 404

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#808]
When I reuse a password reset URL, I get the password reset form.

When I click "Save new password" button, I don't get any error message. In the console, there is a 400 logged. We should 404  on invalid password reset tokens.

**Comment by agilliland** [comment]
This was actually done at some point in the past.  If you put in an invalid token now you are sent to a page which gives you a clear message that the token is expired.

<img width="1548" alt="screen shot 2015-11-25 at 3 27 27 pm" src="https://cloud.githubusercontent.com/assets/1987787/11411803/2589cd7a-9389-11e5-9ca3-917c1cb2fa78.png">
