### ISSUE TITLE
Feature - Possibility to save and import sub queries

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#8082]
Most of the time I copy and paste small sub-queries into bigger queries.
This provokes a lot of duplicated code difficult to maintain and to keep up to date.
It would be amazing to have a feature to import a sub query already saved somewhere else, for example.

__________________________________________________
WITH test_sub_query AS (
    SELECT *
    FROM **sub_query_saved_somewhere_else**
)
SELECT *
FROM test_sub_query
__________________________________________________

Thanks a lot.

**Comment by salsakran** [comment]
dupe of #1825
still a great idea, though =)
