### ISSUE TITLE
Automatic Exploration lists lots of syncobj tables

### ISSUE THREAD

**Issue by Genmutant** [metabase/metabase#8083]
- Your browser and the version: Chrome 67
- Your operating system: Windows 7
- Your databases: SQL Server 11
- Metabase version: 0.29.3
- Metabase hosting environment: jar file
- Metabase internal database: H2

When using the automatic exploration feature with are replicated database (on the receiving side) about half the tables which are displayed are syncobject tables. It would be great to exclude them, because they contain just internal replication data.

![image](https://user-images.githubusercontent.com/1914202/42808875-81aa55f6-89b4-11e8-897b-5cc8542a452e.png)

**Comment by salsakran** [comment]
is "syncobj*" a SQL server convention or something you've setup specifically? We have a notion of "technical cruft" tables that we automatically hide. If that's a common pattern of table names, we should add those to our lists.

**Comment by Genmutant** [comment]
Yes, they are system-views (Sichten = Views, Systemsichten = System Views):

![image](https://user-images.githubusercontent.com/1914202/42930225-b8e304da-8b3c-11e8-8c79-be3e2a6907d5.png)
I don't think you would ever want to query them in metabase. The name is always "syncobj_0x*".

**Comment by Genmutant** [comment]
They also have the IsMSShipped property set, like other system tables and views:
`SELECT * FROM sys.objects
WHERE objectproperty(object_id,'IsMSShipped') = 1`

![image](https://user-images.githubusercontent.com/1914202/42930549-95d9da76-8b3d-11e8-8cbb-33329dcdeb86.png)

**Comment by sbelak** [comment]
Added to the list of cruft tables via #10659
