### ISSUE TITLE
Coping config from existing Metabase for New Metabase servers

### ISSUE THREAD

**Issue by harsh-narvar** [metabase/metabase#8087]
We are replacing existing Metabase Elastic Beanstalk with the Metabase on EC2 instances through metabase.jar file. Our concern is that the existing configurations and the account setups on the Metabase Elastic Beanstalk should be copied for the new Metabase running on ec2. (configurations like Signal Sign On, metabase user accounts, permissions etc) so where are all this configurations stored on Beanstalk ?Is it there on metabase datastore( RDS) or the instance of Elastic Beanstalk ? FOr the new set-up's datastore we have restored DB from snapshot of the RDS running for Beanstalk. 

Whats the best way to copy the configurations ?

**Comment by salsakran** [comment]
Hello @harsh-narvar -

This isn't a place to ask questions about how to operate Metabase. Please open a thread on our user discussion forum.

But short form: the application database stores all the things you've mentioned, so if you snapshot then restore the beanstalk rds instance it should work.
