### ISSUE TITLE
Deprecated delete endpoints?

### ISSUE THREAD

**Issue by mausch** [metabase/metabase#8096]
I see that the DELETE endpoints for card and dashboard have been deprecated a while ago e.g. in https://github.com/metabase/metabase/commit/d621c3f5f7a51cb7f3e42b8a28a1c74f60c07dd1#diff-5f8bc44102374df480b0377d8efc0ba5R294 .

Would it be possible to un-deprecated them? 

I'm using them in https://github.com/elevate/elevate.metabase.tools/issues/6  and having to switch to archiving would mean that after a few import operations the Metabase database would become full of garbage.

Thanks

**Comment by flamber** [comment]
Closing, as it's still possible to delete questions and dashboards, though the recommendation is to archive instead:
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#delete-apicardid
https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#delete-apidashboardid

**Comment by mausch** [comment]
I just wanted to confirm what "deprecated" means in this case.
For me it usually means that something deprecated will be eventually removed.
But it seems that in this case it just means it's discouraged? Can you confirm? Thanks.

**Comment by flamber** [comment]
@mausch Yes, in this case it was. Most other deprecated messages are normal deprecation.
But removing the functionality here would also mean that it wouldn't be possible to delete question/dashboard via the Archive.
