### ISSUE TITLE
Dashboard Filtering - Not Related Cards no more greying out

### ISSUE THREAD

**Issue by tomonetml** [metabase/metabase#8110]
Hi Everyone,

As previously reported on [discourse](http://discourse.metabase.com/t/dashboard-filtering/3877)

We are running Metabase 0.29.3 on ubuntu 14LTS as service with mysql db and use firefox as browser.
To reproduce the difference between versions i've launched metabase on a rpi so it's a fresh basic install with H2 and tested on chromium browser.

Here metabase 0.26.0 dashboard design

![0 26 0 01](https://user-images.githubusercontent.com/34745293/42930373-19f09e68-8b3d-11e8-97dd-b69f66ca5aab.PNG)

![0 26 0 02](https://user-images.githubusercontent.com/34745293/42930380-215c7726-8b3d-11e8-87fa-a94818de5fb5.PNG)

![0 26 0 03](https://user-images.githubusercontent.com/34745293/42930390-25856416-8b3d-11e8-92ac-4025932333fe.PNG)

Here metabase 0.29.3 dashboard design

![0 29 3 01](https://user-images.githubusercontent.com/34745293/42930407-32f51ac4-8b3d-11e8-880b-e0213ac0f552.PNG)

As you can see the result is still showed on the card even if the card has no active filters on it.

have a nice day
Matteo

**Comment by salsakran** [comment]
@mazameli did we decide to stop greying things out? I know there was a lot of back and forth on this and whether it was confusing.

**Comment by mazameli** [comment]
@salsakran Yes, my recollection is that that got changed almost a year ago. I think the voices who were aggravated by the fading behavior were louder than the ones that liked it. 

The current behavior needs addressing because it lacks clarity. Solutions we've talked about in the past are groupings of cards + filters, or some kind of visual indications on cards that are being filtered.

**Comment by tomonetml** [comment]
Thank you for considering this

Maybe the

"no results"
![no results](https://user-images.githubusercontent.com/34745293/47918070-bdce7c00-deab-11e8-97c6-b655fa62b9d4.png)

could be recycled for this situation

bye
Matteo

**Comment by flamber** [comment]
I'm going to close this, since I don't see us reverting to faded cards.
