### ISSUE TITLE
Field filter in SQL query is incorrectly substituted if the filter is not used

### ISSUE THREAD

**Issue by maliayas** [metabase/metabase#8112]
- Your databases: MySQL
- Metabase version: (e.x. 0.29.3)
- Metabase internal database: MySQL

Create an SQL query with an optional parameter:

````sql
select *
from items
left join categories on items.category_id = categories.id
[[ where not {{excluded_categories}} ]]
````

`excluded_categories` above is a field filter that maps to the column `categories.name`.

Now when I run the query by selecting at least one item from the filter, query works fine. However, if I leave the filter blank, then the below query is executed, which is incorrect and returns empty result set.

````sql
select *
from items
left join categories on items.category_id = categories.id
where not 1 = 1
````

Instead, I'd expect Metabase to completely remove the `where` clause if the filter is not used. I guess this is also the documented behaviour.

P.S: I'm not sure but this bug may be related to #4581.

**Comment by maliayas** [comment]
I've searched a little bit more and found #5541. I think these are the same bugs.

You can close this issue. On the other hand, my usecase is a nice example that shows the current Metabase approach may lead to bugs.

Cheers!

**Comment by salsakran** [comment]
closing since this is a dupe
