### ISSUE TITLE
Emails are not sent

### ISSUE THREAD

**Issue by identigral** [metabase/metabase#8119]
I have two different on-premises SMTP servers. I can telnet to both servers (plaintext, port 25) and conduct a SMTP conversation (EHLO, MAIL FROM, RCPT TO, DATA ...). Email is successfully sent and received by the recipient.

Configuring either server in Metabase 0.29.3 leads to emails not being sent. The first server is just plain MTA on the same host where Metabase resides. It's a Postfix service that ships with RHEL, as vanilla as it gets. This specific host cannot be reached using its FQDN or its non-localhost IP/hostname. Metabase config:

```
server host: localhost (also tried 127.0.0.1)
port: 25
SMTP Security: None
SMTP username/password: none, left blank
```

Clicking Send Test Email yields this line in Metabase logs (on stdout)

`07-20 12:33:22 DEBUG metabase.middleware :: POST /api/email/test 200 (24 ms) (1 DB calls). Jetty threads: 8/50 (6 busy, 2 idle, 0 queued)`

There are no errors in the log and no stack trace...but the email is not sent.  Unfortunately I can't check the MTA logs to see if the connection by Metabase was even attempted.

The second SMTP server is a more traditional service running on a remote host (still on-premises). Metabase config:

```
server host: somehost
port: 25
SMTP Security: None
SMTP username/password: none, left blank
```

Clicking Send Test Email yields a stack trace in the logs with this smoking gun

`Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.1 Relaying denied`

This would be expected if SMTP server denied relaying but it doesn't. It allows relays from internal IPs where Metabase resides and I have confirmed it via a plain SMTP session (see 1st para). It sounds as if Metabase is trying to authenticate and since the SMTP credentials are not supplied, SMTP server complains.

We've been running earlier versions of Metabase and this used to work.

**Comment by jornh** [comment]
Does the local dev setup documented in the wiki yield the same result with 0.29.3?

https://github.com/metabase/metabase/wiki/Setting-up-email-in-development

Note it has a comment regarding `sudo` for port 25

**Comment by identigral** [comment]
I can't replicate the setup in https://github.com/metabase/metabase/wiki/Setting-up-email-in-development , don't have privileges on the host.

**Comment by jornh** [comment]
Sorry, didn’t pay enough attention to your “no MTA log access” comment (and can relate to your pain). It actually got to the point here where I, in anger, built a very simple Clojure tester .jar on top of the SMTP lib Metabase use! Can probably dig it up if you want.

Maybe you can try out on a different host, try with port 1025 (if you have shell, but no sudo on the host) or team up with one who has at least shell there.

I just tested on my localhost Ubuntu with both sudo port 25 and without sudo port 1025 using the wiki’s python fake server - works! (And it’s with a setup with no username/password as yours)

There’s also a section in the Metabase Troubleshooting Guide on SMTP setup.

HTH

**Comment by identigral** [comment]
I was able to run python smtpd on localhost, port 1025. Metabase has no issues with that service. What else can I do to help troubleshoot the issue on my SMTP services? I might be able run a wire trace.

**Comment by luthervdh** [comment]
@identigral , have you been able to work around the issue?  I'm having smtp setup issues, trying to connect metabase to talk to our internal smtp  service - message transfer agent (ESMTP Exim).

Weirdest part is that "SMTP SECURITY" is "none" and there is no username and password.
I can send an email from the metabase server if I telnet to the smtp server and use smtp commands to send a test email.

Extract from Metabase Log below, please advise if you have any inputs.

Sep 19 13:57:37 DEBUG metabase.middleware :: GET /api/setting 200 (432 µs) (0 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued)
Sep 19 13:57:41 WARN metabase.email :: Failed to send email
Sep 19 13:57:41 WARN metabase.api.email :: Problem connecting to mail server: Invalid Addresses
Sep 19 13:57:41 ERROR metabase.middleware :: POST /api/email/test 500 (11 ms) (1 DB calls).
{:errors {:email-smtp-username "Wrong username or password", :email-smtp-password "Wrong username or password"}}

**Comment by identigral** [comment]
@lutvdh We haven't been able to find a workaround, unfortunately. We've upgraded to the latest (0.30.3) and still no dice. The incident signature in our log is different from yours. In our case Metabase log does **not** say that it can't connect, the log looks clean when local MTA is used for SMTP.
