### ISSUE TITLE
Dashboard cards' add data modal should display nested collections

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8122]
Currently the add data modal shows a flat list of saved questions that are compatible with the current question. It should probably instead show a list of collections and allow you to navigate through them to pick a compatible saved question.

<img width="1036" alt="screen shot 2018-07-20 at 3 59 19 pm" src="https://user-images.githubusercontent.com/2223916/43041204-e991ce0e-8d26-11e8-8de2-e355afb5292a.png">

**Comment by flamber** [comment]
Duplicate of #4202
