### ISSUE TITLE
What's the way to add Oracle DB support to the docker image?

### ISSUE THREAD

**Issue by bkbonner** [metabase/metabase#8125]
I checked for an existing issue and couldn't find any.

I saw this post:  https://www.metabase.com/docs/v0.20.1/administration-guide/databases/oracle.html  but I'm wondering how to add this without creating a new image from scratch.  Has someone done this already?

I went through the following steps.  The driver is definitely there, but it doesn't appear to recognize it in the setup.  Help?

1.  Create a new folder name it whatever you want and 'cd' to that directory
2.  Copy the database driver there.  (i.e. ojdbc6.jar)
3.  Create a file called Dockerfile and enter the contents below:
```# dockerfile
FROM metabase/metabase
COPY ./ojdbc6.jar /app/plugins/ojdbc6.jar
ENTRYPOINT ["/app/run_metabase.sh"]
```

4.  ls the directory to see:
```brians-air:metabase bbonner$ ls -al
total 5312
drwxr-xr-x    4 bbonner  staff      136 Jul 22 12:53 .
drwxr-xr-x+ 120 bbonner  staff     4080 Jul 22 12:38 ..
-rw-r--r--@   1 bbonner  staff      116 Jul 22 12:58 Dockerfile
-rw-r--r--    1 bbonner  staff  2714189 Jul 22 12:53 ojdbc6.jar
```

5.  build the docker image and give it a tag:  (i.e. optmetabase) using:
`docker build . -t optmetabase`

6.  run the image:
`docker run -d -p 3000:3000 --name metabase optmetabase`

7.  if desired, verify the plugins are installed with:
`docker exec -it metabase ls -lR /app/plugins`

```brians-air:metabase bbonner$  docker exec -it metabase ls -lR /app
/app:
total 112164
-rw-r--r--    1 root     root     114839203 May 12 18:31 metabase.jar
drwxr-xr-x    2 root     root          4096 Jul 22 16:58 plugins
-rwxr-xr-x    1 root     root          4984 Nov 28  2017 run_metabase.sh

/app/plugins:
total 2652
-rw-r--r--    1 root     root       2714189 Jul 22 16:53 ojdbc6.jar
```

**Comment by bkbonner** [comment]
I'm trying it with ojdbc7.jar.   I'm hoping (suspecting) that maybe there's an API change that metabase is using to inspect the drivers.  I'll report here.

**Comment by jornh** [comment]
See if this discourse post helps: 
http://discourse.metabase.com/t/oracle-doesnt-show-up-on-my-database-menu/1525/8

**Comment by bkbonner** [comment]
ok, I was able to modify the docker image as follows and it worked:

```
# Dockerfile
FROM metabase/metabase

COPY ./ojdbc6.jar /app/plugins/ojdbc7.jar
ENV MB_PLUGINS_DIR /app/plugins2
ENTRYPOINT ["/app/run_metabase.sh"]
```

and starting it with: 
```
docker run -d -p 3000:3000 -v /Users/bbonner/plugins:/app/plugins2 --name metabase optmetabase
```
