### ISSUE TITLE
Metabse out of memory issues - 0.29.3

### ISSUE THREAD

**Issue by swatisinghi** [metabase/metabase#8141]
My metabase server keeps running out of memory and stopping. Following are the memory settings.

`java -Xms14336m -Xmx14336m -jar metabase.jar`

This is happening too often. My underlying database is Redshift.

Stack trace
```
Exception in thread "qtp156797912-1379" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at sun.misc.IOUtils.readFully(IOUtils.java:60)
        at java.util.jar.JarFile.getBytes(JarFile.java:425)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:193)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
```

**Comment by jornh** [comment]
@swatisinghi that stack trace looks like a quite low level thing, so not much to go by. To nail something like your issue it would be helpful to know under what circumstances it happens and possibly get some profiling like described in https://github.com/metabase/metabase/issues/7197#issuecomment-377267523.

@drorwr I noticed you also commented on #7197 (an already fixed issue with a specific user interaction and trace) so same would apply to you. Your root cause could be the same as @swatisinghi — or something completely different. No one will really know before you guys can share more.

**Comment by urjitbhatia** [comment]
@jornh fwiw I am also seeing this behaviour. I have some additional information: It happens hourly so I am guessing its the DB sync leaking memory (We are on redshift too).

**Comment by salsakran** [comment]
There are a couple of improvements to sync memory usage in 0.30. 

We're hoping to cut an RC shortly, it would be great if you could test out whether it mitigates these memory errors.

**Comment by camsaul** [comment]
@swatisinghido you have a more detailed stacktrace? Or any other context as to when you are seeing that happen?

**Comment by urjitbhatia** [comment]
Here is some more profiling info for a heapdump after an OOM if this helps.

![screen shot 2018-07-25 at 6 54 57 pm](https://user-images.githubusercontent.com/1226567/43236963-65337b94-903c-11e8-907e-da0a83ea23ab.png)

![screen shot 2018-07-25 at 6 56 38 pm](https://user-images.githubusercontent.com/1226567/43236981-836ef43a-903c-11e8-98b7-b7bb4ac03ec4.png)

**Comment by ChrisTerBeke** [comment]
We're running Metabase in a Docker container on Kubernets, and we also see a big memory issue over time:

![image](https://user-images.githubusercontent.com/1134120/43459911-5919993c-94cf-11e8-88be-d019d33307b2.png)

We're using a postgres database in Cloud SQL (fully managed), which is not giving any issues by itself. Our other services on Kubernetes (self written) also perform fine, so we've isolated the issue to the Metabase container.

**Comment by ChrisTerBeke** [comment]
That's memory usage (from 0 in the bottom to about 1.5Gb on the top).

I'll have a look at the RC, is that known to fix some memory issues?

**Comment by senior** [comment]
@urjitbhatia The heap snapshot you are showing there looks like you're running a query with a lot of results. I haven't seen the `com.amazon.jdbc.communications.InboundMessagesContainer` class before, are you maybe querying a Redshift database?

**Comment by senior** [comment]
@ChrisTerBeke I'm not sure I understand what "big memory issue" you're referring to. Is Metabase running out of memory? Do you feel it's consuming more memory than it should? There is no key for the graph you included, but it appears to show memory consumption going down over time, so I'm confused.

**Comment by ChrisTerBeke** [comment]
Every now and then, there's a spike (when doing a larger query I guess?) and Metabase doesn't recover from that. We have to restart the container to get it responsive again.

The memory drops you see in the graph are when we actually restart the container, after which is goes back up again.

Here's an improved graph:

![image](https://user-images.githubusercontent.com/1134120/43470566-2840d450-94e9-11e8-9ba3-6dd7018dee11.png)

So each drop is a manual restart to get operational again.

**Comment by senior** [comment]
Do you see an out of memory error in the log that can be correlated with the unresponsiveness?

**Comment by ChrisTerBeke** [comment]
This line might be interesting:

```
07-31 09:23:31 [1mWARN metabase.query-processor[0m :: [31mQuery failure: org.postgresql.util.PSQLException: ERROR: value out of range: overflow
```

**Comment by marcelmfs** [comment]
I've kinda sorted out all my memory issues creeping the JVM by adding `-XX:+UseConcMarkSweepGC` to JAVA_OPTS.

**Comment by flamber** [comment]
There has been a lot of improvements in performance+memory usage in later version (latest 0.35.4).
Please comment back with details if you're still experiencing problems. Related #12060

**Comment by rkist** [comment]
This same behavior keeps happening in 0.35.4.
