### ISSUE TITLE
Field filter on SQL question: "The column index is out of range: 1"

### ISSUE THREAD

**Issue by danpelota** [metabase/metabase#8144]
When running a new question using a field filter variable, I'm receiving the following error message:

```org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.```

Steps to reproduce:

- Generate a new table with the following SQL:
```
CREATE TABLE test_variables (text_column TEXT);
INSERT INTO test_variables VALUES ('blue'), ('red'), ('green');
```
- Create a new native query question with the following SQL:
```
select * FROM test_variables where text_column = '{{color}}';
```
- In the Variables panel, select "Field Filter" as the variable type. Select "Text Column" as the "field to map to"
- Select `green` from the dropdown list of filter values above the query pane
- Returned error:
```org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.```

------
Note that the following works:

- Hardcoding the color value:
<img width="566" alt="0hardcoded_value" src="https://user-images.githubusercontent.com/724968/43209629-2031b164-8ffb-11e8-8b5f-1498df4335ab.png">

- Creating a text variable and typing `green` into the filter box:
<img width="720" alt="1text_value" src="https://user-images.githubusercontent.com/724968/43209653-30b18866-8ffb-11e8-85d5-447b5e3ff127.png">

The query fails with quotes and without quotes around the variable name:
<img width="725" alt="2error_no_quotes" src="https://user-images.githubusercontent.com/724968/43209687-428852cc-8ffb-11e8-8e80-06f324b6375d.png">
<img width="700" alt="3error_quotes" src="https://user-images.githubusercontent.com/724968/43209699-4a5b8082-8ffb-11e8-8296-b452e7fea2d4.png">

------
Some pertinent information from the PostgreSQL log, with the error included:
```
duration:   0.081 ms  bind <unnamed>: INSERT   INTO "query_execution" ("hash", "result_rows",   "started_at", "executor_id", "native",   "pulse_id", "card_id", "context",   "error", "running_time", "dashboard_id") VALUES   ($1, 0, $2, 2, TRUE, NULL, NULL, $3, $4, 109, NULL)   RETURNING *

parameters: $1 =   '\x82eeaef9c7506d9e9210d275287ad92f70bde35f38668dd393eea26516a8edcf', $2 =   '2018-07-25 14:51:01.352', $3 = 'ad-hoc', $4 =   'org.postgresql.util.PSQLException: The column index is out of range: 1,   number of columns: 0.'
```
Full PostgreSQL CSV log:
[logs.txt](https://github.com/metabase/metabase/files/2228501/logs.txt)

----
- Browser: Chrome 67.0.3396.99
- OS: Ubuntu 16.04
- Database: PostgreSQL 10.4
- Metabase version: 0.29.3
- Metabase hosting environment: metabase.jar file executed on an EC2 instance
- Metabase internal database: PostgreSQL 10.4

**Comment by jornh** [comment]
Seems field filter and variables are slightly different. 

What happens if you try with `select * FROM test_variables where {{text_column}}`?

See 
https://metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

I think others have been bitten by this before, and reported as issues. So maybe this points to some UX that could be more intuitive (maybe just caught and given a better error message, like “did you mean ... “ 😄)? OTOH it *is* in SQL mode, where people are already quite on their own.

**Comment by danpelota** [comment]
You're absolutely right @jornh – apologies for missing that in the docs. My oversight stemmed from the fact that I started with a text filter with multiple optional clauses and worked backwards from there.

While it may be useful to have an indication that there's a syntax issue before the query gets to the database and returns an obscure Postgres error, I do appreciate the fact that the user is on their own when it comes to custom queries. Perhaps a simple sentence in the docs highlighting this nuance in syntax would be helpful.

**Comment by jornh** [comment]
Great it got sorted!
> Perhaps a simple sentence in the docs highlighting this nuance in syntax would be helpful.

Sounds like a simple improvement. I’m sure the Metabase core team wouldn’t mind a doc update contribution. Scroll to the bottom of the doc page click `source` then ✏️ ... and you’re well on your way ... 🙂

**Comment by espadrine** [comment]
Another way to get bitten by this is through the double-comment:

```sql
SELECT * FROM table
WHERE date >= [[{{start}} --]] now()::date
AND date < [[{{end}} --]] [[{{start}} + integer '1' --]] now()::date + integer '1'
```

_“If we don’t have a start date, pick today. Otherwise, pick the end date as the next day. Otherwise, pick the given end date.”_

**Comment by flamber** [comment]
@espadrine Another way to do what you're doing is by using `coalesce`:
```
SELECT * FROM table
WHERE date >= coalesce([[{{start}},]] now()::date)
AND date < coalesce([[{{end}},]] [[{{start}} + integer '1',]] now()::date + integer '1'
```

**Comment by cosmith** [comment]
If you're importing from redash like me, you need to remove the quotes around the variable.
So `select * FROM test_variables where text_column = '{{color}}';` in redash becomes `select * FROM test_variables where text_column = {{color}};` in metabase.
