### ISSUE TITLE
Cannot decrypt encrypted credentials error.

### ISSUE THREAD

**Issue by Globegitter** [metabase/metabase#8151]
- Your browser and the version: Chrome 67
- Your operating system: Ubuntu  16.04
- Your databases: Redshift
- Metabase version: 0.30-rc
- Metabase hosting environment: official Docker image
- Metabase internal database: posgrs

- I upgrade metabase to 0.30-rc and now on start seeing the error:

```
Cannot decrypt encrypted credentials. Have you changed or forgot to set MB_ENCRYPTION_SECRET_KEY? Assert failed: (ivlength? iv 16) ["util.encryption$decrypt.invokeStatic(encryption.clj:62)"
 "util.encryption$decrypt.invoke(encryption.clj:54)"
 "util.encryption$maybe_decrypt.invokeStatic(encryption.clj:83)"
 "util.encryption$maybe_decrypt.invoke(encryption.clj:76)"
 "util.encryption$maybe_decrypt.invokeStatic(encryption.clj:79)"
 "util.encryption$maybe_decrypt.invoke(encryption.clj:76)"
 "models.setting$restore_cache_if_needed_BANG_.invokeStatic(setting.clj:209)"
 "models.setting$restore_cache_if_needed_BANG_.invoke(setting.clj:193)"
 "models.setting$db_value.invokeStatic(setting.clj:254)"
 "models.setting$db_value.invoke(setting.clj:248)"
 "models.setting$get_string.invokeStatic(setting.clj:268)"
 "models.setting$get_string.invoke(setting.clj:258)"
 "models.setting$get.invokeStatic(setting.clj:328)"
 "models.setting$get.invoke(setting.clj:322)"
 "core$init_BANG_.invokeStatic(core.clj:194)"
 "core$init_BANG_.invoke(core.clj:138)"
 "core$start_normally.invokeStatic(core.clj:245)"
 "core$start_normally.invoke(core.clj:239)"
 "core$_main.invokeStatic(core.clj:265)"
 "core$_main.doInvoke(core.clj:260)"
 "core.main(Unknown Source)"]
```

To be honest I do not think this is related at all to the upgrade, we also changed how we store our own secrets, so maybe somehow the encryption key has now actually changed but if so we would have now way of retreiving the old one. My question is more, how can I get rid of this error? Is there any way to reset things? I did already resave the db credentials but that did not change anything about the error. Funnily enough also nothing seems to be impacted. I can still make some queries etc.

**Comment by senior** [comment]
@Globegitter Thank you for reporting this issue, I have been able to reproduce the problem. With 0.30.0 we have added support for encrypting all Metabase settings (via https://github.com/metabase/metabase/pull/4341). If you were using `MB_ENCRYPTION_SECRET_KEY` to encrypt database connection information before 0.30.0, when you upgrade, we assumed that all of your settings were encrypted. When we try to decrypt a plaintext setting, it fails, then assumes the text wasn't encrypted and returns it.

Everything should still be working correctly, but on startup you'll see a bunch of error messages as it tries to decrypt those values. I'll work on getting a fix for this, but you can safely ignore those error messages for now.

**Comment by Globegitter** [comment]
@senior thanks for the response and the quick fix - yeah it sounds like it was that that hit us.
