### ISSUE TITLE
Allow configuration of logging level in Docker 

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#8158]
https://metabase.com/docs/latest/operations-guide/start.html#configuring-logging-level

Right now the only way to configure logging level is to create a custom docker file and redeploy. This is operationally a pain. We should have a way to pass in logging level into an image.

**Comment by eladeyal-intel** [comment]
environment variable(s) which don't require files would be nice.

**Comment by shinebayar-g** [comment]
In the [documentation](https://www.metabase.com/docs/latest/operations-guide/start.html#configuring-logging-level) it says we can start metabase with `java -Dlog4j.configuration=file:/path/to/custom/log4j.properties -jar metabase.jar` command. However this is not the case for docker installation. If I override docker entrypoint would may break. I've tried to look at [dockerfile](https://github.com/metabase/metabase/blob/release-0.32.x/Dockerfile) however looks like it's not correct one, at least not the one used for docker hub.

@tlrobinson 's method worked like a charm. Thank you. Mounting config volume and passing this file path as ENV is definitely doable. But it wasn't mentioned anywhere but here.

**Comment by shinebayar-g** [comment]
@tlrobinson 's method worked like a charm, thank you. That wasn't mentioned anywhere but here.
