### ISSUE TITLE
Permissions menu - Infinite flickering of scrollbars

### ISSUE THREAD

**Issue by ceyhunkerti** [metabase/metabase#8165]
Chrome: Version 68.0.3440.75 (Official Build) (64-bit)
Ubuntu mate 18.04
Metabase  0.29.3
Hosting env: Linux

Clicking Permissions in Admin panel causes infinite flickering of scrollbars (horizontal and vertical) so the 
main menu on the top-right

It's ok in firefox 61.0.1 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by elmentdave** [comment]
so how do we solve the issue

**Comment by flamber** [comment]
@elmentdave Try resizing your browser window. That should prevent it from getting stuck flickering.

**Comment by ceyhunkerti** [comment]
> @elmentdave Try resizing your browser window. That should prevent it from getting stuck flickering.

which we can't tell end users to do so :)

**Comment by elmentdave** [comment]
yeah that is not a solution to the problem
i mean resizing the browser

well i didn't see this issue in the earlier versions i used

**Comment by nemanjaglumac** [comment]
Linking this to a #14391, because it's exactly the reason why Cypress tests failed after React upgrade.
