### ISSUE TITLE
Amazon SES SMTP Compatability

### ISSUE THREAD

**Issue by sjlu** [metabase/metabase#8166]
Hey guys,

It looks like there's a compatibility issue when using Amazon SES. When using the provided SMTP credentials, it can properly send emails from the same domain to the same domain. For example. I can send an email to interseller.io but cannot send one to gmail.com.

The issue lies within requiring the following SMTP headers:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-delegate-sender-tasks-email.html

Specifically:
> When you use the Amazon SES SMTP interface for cross-account sending, you have to include the X-SES-SOURCE-ARN, X-SES-FROM-ARN and X-SES-RETURN-PATH-ARN headers in your message. Pass these headers after you issue the DATA command in the SMTP conversation.

These identity headers need to be passed over in order to send emails to other domains.

**Comment by senior** [comment]
We use Amazon SES internally and don't have the issues you describe. I'm able to send emails in the same domain and to other domains with Metabase not having those headers.

The documentation you linked to seems to be referencing sending emails as a delegate for another Amazon account. Are you trying to use that delegate sending feature of SES? If not, maybe you've got an authorization policy setup that doesn't allow sending emails outside of the domain.

It would be good to run a test outside of Metabase on this. You could connect a local mail client to the SES SMTP server and try to send emails using the same credentials you configured Metabase with.

**Comment by sjlu** [comment]
Agh, I keep forgetting that Amazon SES requires you to message them to get you out of sandbox mode. Had a revelation earlier today. Sorry for the troubles.

**Comment by sjlu** [comment]
Reference for anyone else that encounters this issue.

> https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html
