### ISSUE TITLE
Adding a new question to a dashboard causes odd scrolling behavior

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8171]
Create a new question and save it. When it asks about adding it to a dashboard, add it to a new dashboard. I see something like 
![yay_im_editing](https://user-images.githubusercontent.com/215910/43414591-cce598de-93f8-11e8-84c3-e35c342b12f2.png)
After I click save I see
![how_did_i_get_here](https://user-images.githubusercontent.com/215910/43414597-d79b828e-93f8-11e8-9d7c-040e4db1dd58.png)
It's on the correct page but scrolls down automatically just a bit to hide the header, making it a bit confusing to get back to the home page.

**Comment by flamber** [comment]
I cannot reproduce on 0.35.3, but I remember this problem a long time ago.
