### ISSUE TITLE
Error page has broken layout

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8182]
Saw this on our stats instance in Chrome (when trying to x-ray a point on a google analytics chart):

![screen shot 2018-07-31 at 11 09 43 am](https://user-images.githubusercontent.com/2223916/43478289-59931c02-94b2-11e8-8615-06d98ca66eda.png)

![screen shot 2018-07-31 at 11 09 53 am](https://user-images.githubusercontent.com/2223916/43478295-5baa2788-94b2-11e8-8908-61038c27c8c7.png)

**Comment by kdoh** [comment]
Fixed in #8187
