### ISSUE TITLE
Tooltip is hidden below the region map on publicly shared question 

### ISSUE THREAD

**Issue by ewinsutriandi** [metabase/metabase#8188]
I am running metabase (0.30.0-rc) inside docker container.
I encountered  this problem where my publicly shared region map has its tooltip buried below the map like the screenshot below.

![screenshot_20180801_191810](https://user-images.githubusercontent.com/1428472/43518894-0b8b17d0-95c0-11e8-8a3a-a3fc969aa5b9.png)

The problem is not appear on the question editor, only in publicly shared region map
I'm using chrome (Version 63.0.3239.84 (Official Build) (64-bit)) under kubuntu 17.10

note : I encounter this problem first in version v0.29.1, then try to update to see if the problem persist

**Comment by notrom** [comment]
Same for me on v0.31.0.

Also note issue #8993 if you've not already logged onto Metabase directly.

**Comment by paulrosenzweig** [comment]
@ewinsutriandi & @notrom, I can't seem to reproduce this. I made a very simple custom map with a few squares and the tool tip appears on top for an embed.

If this is still occurring for you, can you post the GeoJSON and some sample data to help reproduce this? Thanks!

![image](https://user-images.githubusercontent.com/691495/57388673-afc52500-7186-11e9-83f2-32ec5c851fa8.png)

**Comment by flamber** [comment]
I can reproduce this with both Public and Embed on 0.32.5 with Firefox 66
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/57392345-c0bd6880-717d-11e9-954c-9f36bb32fa11.png)
Tested with this map: `https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/california-counties.geojson`
And just using Sample Dataset Product_ID's to populate it:
![image](https://user-images.githubusercontent.com/1447303/57392056-0af21a00-717d-11e9-9bb2-d7d6ac52c0bb.png)

**Comment by paulrosenzweig** [comment]
Thanks, @flamber! I was looking at it in a dashboard embed 🤦‍♂. Just opened a PR.
