### ISSUE TITLE
If you are using VirtualBox on a Mac make sure to map the container port on your VM ;)

### ISSUE THREAD

**Issue by cottrell** [metabase/metabase#8190]
Anyone have any details or a link on this note? Hitting db connection errors i.e. the backend is not able to connect to external db. Probably just some docker port opening but would expect everyone is hitting the same issue.

org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by jornh** [comment]
The GitHub issues on this project are used for bug reports or enhancement requests on Metabase itself. 

Configuration issues are better posted on https://discourse.metabase.com - happy to try to help out over there with your setup 🙂 

But to give you a starting point there's a nice step-wise section of the troubleshooting guide for databases here: https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html
