### ISSUE TITLE
i18n almost repeated string

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#8194]
I think these two should be only one string:

https://github.com/metabase/metabase/blob/master/frontend/src/metabase/components/CollectionList.jsx#L77
https://github.com/metabase/metabase/blob/master/frontend/src/metabase/containers/UserCollectionList.jsx#L26

one of the two should be converted to the other

**Comment by joebordes** [comment]
These two in src/metabase/models/collection.clj are also candidates to be merged:

"You cannot archive a Personal Collection."
"You cannot archive a Personal Collection!"

**Comment by joebordes** [comment]
src/metabase/models/setting.clj
msgid "Error inserting new Setting:"
msgid "Error inserting a new Setting:"

**Comment by mazameli** [comment]
Fixed by #8227
