### ISSUE TITLE
Translate IDs referenced from another tables to values

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8197]
Hi everyone,
I do not know if this issue/feature req. is not duplicate but I was not able to find anything useful.

Problem is that nearly all of our tables have columns refering via DI to another table to get additional data, like names of goods, tags and so on. In many cases even this secondary table is refering to another table to get properties of tags listed in frist one via ID from third table and so on.

Is there any feature to interlink these referals, these data and allow users to see instead of good_id = 15 good name like "oak tree" and instead tags = {9,7,4} to see tags like "Deciduous,NothernHemisphere" with possibility to choose their filter and another functions bind to these values?

I have to try using separate tables to translate that but I am suspicious that it wont work.

Anyway - I am mostly using native SQL queries but for question configuration by common user (not DB specialist) (e.g. question flexibility) I want to give them another approach.

Please let me know ASAP, this (and even another feature problems) issue is taken like Metabase disadvantage during hunt to get proper (and hopefully opensource) BI tool for our fast growing company. I really do not want to feed costly commercial products were it is not inevitable.

**Comment by jornh** [comment]
You want to look at setting up Foreign Key mapping - see this blog post under the "Friendlier Fields" heading: https://metabase.com/blog/Metabase-0.25/index.html - and the Admin Guide under metadata: https://metabase.com/docs/v0.29.3/administration-guide/03-metadata-editing.html

**Comment by salsakran** [comment]
as @jornh mentioned, this is a feature that is described in our docs.

**Comment by lwqcz** [comment]
@jornh @salsakran thank you a lot 👍
