### ISSUE TITLE
In `add question to dashboard` modal, we should only show collections that contain dashboards, or have children that do

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8198]
![screen shot 2018-08-02 at 10 28 53 am](https://user-images.githubusercontent.com/2223916/43600690-27283650-9640-11e8-9c49-d5183108342e.png)

Unless I'm missing something, I don't think it makes sense in this modal to show collections that don't have any dashboards in them, unless they have child collections which _do_ have dashboards in them.

If someone has a good reason why we _should_, then we need a better empty state for the case when there are no dashboards or subcollections, e.g. one that maybe is a large CTA for creating a new dashboard in that collection.

(The only reason I could think of is the case where I'd want to navigate to the place where I want to put a new dashboard, but the `create new dashboard` button lets you choose where you want your new dashboard to go.)

**Comment by tlrobinson** [comment]
The main reason for this is currently we don't load the children until you click on a collection, and thus know which collections *have* children until then.

Fixing that is probably non-trivial so at least for 0.30 I'd suggest just putting an empty state in.

**Comment by brunobergher** [comment]
Handled by entity picker and questions in dashboards.
