### ISSUE TITLE
i18n: missing translations on screen

### ISSUE THREAD

**Issue by joebordes** [metabase/metabase#8203]
After updating the es translation file to 0.30 here are a set of screenshots that didn't translate.

![mbi18n00](https://user-images.githubusercontent.com/1237191/43615095-6dc93cbe-96b6-11e8-9591-e36935788ff8.png)
![mbi18n01](https://user-images.githubusercontent.com/1237191/43615098-6eaa3160-96b6-11e8-9f7e-c5febf40ed14.png)
![mbi18n02](https://user-images.githubusercontent.com/1237191/43615099-6fac1f6a-96b6-11e8-8901-40a010e62855.png)
![mbi18n03](https://user-images.githubusercontent.com/1237191/43615100-70c9544e-96b6-11e8-8755-10033bb03e40.png)
![mbi18n04](https://user-images.githubusercontent.com/1237191/43615102-71f1edfe-96b6-11e8-8857-0746b7d4dc75.png)
![mbi18n05](https://user-images.githubusercontent.com/1237191/43615104-732ac592-96b6-11e8-8ea2-7129425e5f7a.png)
![mbi18n06](https://user-images.githubusercontent.com/1237191/43615106-746cf74a-96b6-11e8-876d-db0294629c90.png)
![mbi18n07](https://user-images.githubusercontent.com/1237191/43615108-75b13f62-96b6-11e8-8432-66e37bf7161d.png)
![mbi18n08](https://user-images.githubusercontent.com/1237191/43615109-76759ede-96b6-11e8-82d8-246fc5ee9233.png)
![mbi18n09](https://user-images.githubusercontent.com/1237191/43615114-7b439948-96b6-11e8-844b-8489537991de.png)
![mbi18n10](https://user-images.githubusercontent.com/1237191/43615116-7c6b5d06-96b6-11e8-8d94-52cc00b4e2f5.png)
![mbi18n11](https://user-images.githubusercontent.com/1237191/43615120-7e011d22-96b6-11e8-8e30-dc9b9b72243f.png)
![mbi18n12](https://user-images.githubusercontent.com/1237191/43615124-7f17c1a2-96b6-11e8-9ceb-35431a50091b.png)

**Comment by senior** [comment]
@tlrobinson The first screenshot is related to database driver details. I found where that comes from on the backend and have put together a fix.

I'm wondering if the next set of screenshots is maybe related to https://github.com/metabase/metabase/issues/8209. Taking the first screenshot as an example, I think it's coming from https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/core.js#L244, which looks right (and that was not changed recently). Some other missing translations look like they're coming from https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/schema_metadata.js, maybe that is affected too?

**Comment by tlrobinson** [comment]
Yeah I wouldn't be surprised if a lot of these were fixed with #8209 by #8223.

**Comment by senior** [comment]
These should have been taken care of now with https://github.com/metabase/metabase/issues/8209 and https://github.com/metabase/metabase/pull/8223 that @tlrobinson mentioned and the backend i18n fixes from https://github.com/metabase/metabase/pull/8452. If that's not the case, please reopen.
