### ISSUE TITLE
After upgrading to Metabase 0.30 RC1 the Slack bot integration is throwing a permission error

### ISSUE THREAD

**Issue by gajus** [metabase/metabase#8210]
Log:

```
Gajus Kuizinas [12:52 PM]
metabot list

MetaBot APP [12:52 PM]
Uh oh! :cry:
> Input to perms-objects-set-for-parent-collection does not match schema:

     [0;33m  [(named {:collection_id missing-required-key} this) nil] [0m

Gajus Kuizinas [12:54 PM]
metabot list

MetaBot APP [12:54 PM]
Uh oh! :cry:
> Input to perms-objects-set-for-parent-collection does not match schema:

     [0;33m  [(named {:collection_id missing-required-key} this) nil] [0m

```

I have tried regenerating the Slack API token. That did not fix the issue.

**Comment by senior** [comment]
@gajus Could you paste in the full stacktrace from the log?

**Comment by gajus** [comment]
Logs from where?

Typing `metabot list` command in Slack does not produce any logs in the container itself.

**Comment by senior** [comment]
@gajus There should have been a stacktrace in the server log, but I don't need that anymore. I was able to reproduce this on an instance we have running internally. I have a fix for the issue in https://github.com/metabase/metabase/pull/8230.

Thanks for trying out our RC build and reporting the bug!
