### ISSUE TITLE
Sort data legend by measure in pie charts

### ISSUE THREAD

**Issue by abmj1979** [metabase/metabase#8211]
- Your browser and the version: Chrome  68.0.3440.84
- Your operating system: Windows 10
- Your databases: Mysql, Oracle, Postgre
- Metabase version: 0.29.3
- Metabase hosting environment: Ubuntu 16.04
- Metabase internal database: Mysql

On the pie chart, would be a nice feature if we can sort the data legend by measure

![image](https://user-images.githubusercontent.com/22889283/43648769-bd8057c8-9711-11e8-879f-7772da1fa91b.png)

**Comment by jornh** [comment]
Sorting is on the Question page, see: 
https://metabase.com/docs/latest/users-guide/04-asking-questions.html#additional-options

**Comment by abmj1979** [comment]
Thanks @jornh

I thought this sorting works only on table questions. my mistake!

**Comment by jornh** [comment]
No worries, the UX on this has tricked me on this as well 😉
