### ISSUE TITLE
Field <Field name> from table <table_name> is not a leaf field.

### ISSUE THREAD

**Issue by bobbui** [metabase/metabase#8218]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
chrome
- Your operating system: (e.x. OS X 10, Windows XP, etc)
mas os x
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
Bigquery
- Metabase version: (e.x. 0.19.3)
 0.29.3
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Google cloud Kubernetes Engine
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres
- *Repeatable steps to reproduce the issue*
    - go to <domain>/admin/datamodel/segment/create
    - create metric 
    - preview
    - got this error:
<img width="553" alt="screen shot 2018-08-03 at 2 13 54 pm" src="https://user-images.githubusercontent.com/5661982/43666155-7d59b8fe-9727-11e8-8ef7-82c85a8b6d80.png">

The extra field schema is as follow:
<img width="319" alt="screen shot 2018-08-03 at 2 14 33 pm" src="https://user-images.githubusercontent.com/5661982/43666180-96afa5d4-9727-11e8-8a15-0b9290d864ea.png">

I think the problem may be with the handling of records type.
Please help to advise on this issue.
Thank you

**Comment by thangbn** [comment]
i think **extra** is included in the result

**Comment by flamber** [comment]
Closing in favor of #2662 / #10185
