### ISSUE TITLE
Filter using "contains" rather than "begins with"

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#8219]
Metabase: 0.30.0-rc (previously 0.29.2)
Host: Localhost:3000
Databases: H2 internal default, Server SQL external (joined in)
Browser: Firefox 52.9.0
OS: Microsoft Windows [Version 6.0.6002]

Change or give the option for Question and Dashboard filters to "Search the list" using "contains" rather than "begins with" functionality.  That way everything containing a key word will come up making for more natural filtering.  Easy fix with big impact for overall usability! See <a href="https://github.com/metabase/metabase/pull/7951">Pull Request #7951</a>, is this the same?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Tbodewes** [comment]
I've duplicated this issue in https://github.com/metabase/metabase/issues/11428. I'll close that issue, but if necessary, it provides additional details for the problem.

**Comment by MarcGJA** [comment]
Easy fix, use the same code as in "Question>Variables panel>Field to map to", noticed it does exactly what is described in this issue.

**Comment by elburro1887** [comment]
Is this getting fixed? 
Or could you at least add it as an optional setting?

**Comment by MarcGJA** [comment]
Not sure when this will get changed, only the Metabase team can address that.  Judging from the amount of upvotes (11 as of today), however, it's way down on the list of <a href="https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3A%22Type%3ANew+Feature%22">highly requested items</a>.  But seeing as that's the way the in "Question>Variables panel>Field to map to" works maybe they'll slip it into an upcoming release.

**Comment by chrishaegner** [comment]
I would also be very interested in this feature, since not having "contains" filters in Dashboard really kills usability

**Comment by transistormuncher** [comment]
I agree, this feature would be more than welcome!

**Comment by f1dz** [comment]
This feature will be very helpful or at least give us an option to turned on/off this feature so let us choose which one suitable for our environment.

**Comment by duc-ctm-jacobins-digital** [comment]
We really need this feature. We are a retail company, and we have over 10K SKUs. End-users can not remember the first words of all SKUs.

**Comment by Olaktal** [comment]
Hello ! It's a must have feature !

**Comment by JayJayM** [comment]
@daltojohnso @flamber  It seems like this works on Dashboard filters but not on Questions filters... So not sure this is really closed.

**Comment by tsmacdonald** [comment]
@JayJayM good catch; addressed in #15879 and will go out in the next 39 point-release
