### ISSUE TITLE
Adopt same multiple-selection filter standard for Questions & Dashboards [SOLVED]

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#8220]
Metabase: 0.30.0-rc (previously 0.29.2)
Host: Localhost:3000
Databases: H2 internal default, Server SQL external (joined in)
Browser: Firefox 52.9.0
OS: Microsoft Windows [Version 6.0.6002]

CORRECTION -- CLOSE this Issue: Dashboard filters are all widgets as they should be now.  It apparently took more time to complete the migration as something seems to have "clicked" into place.  So normally there shouldn't be any problem at all for those with numerous dashboards.
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
SOLVED: Appears to be an artifact from a previous version.  Rebuilding Dashboards from scratch brings the filters up to date from checkboxes to widgets.  No big deal, in my case there are only a handful and I have to revamp them anyway!  But for those with numerous dashboards this could be tedious...
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Dashboards currently use filter checkboxes for multiple-selection while Questions use widgets.  Either give the option of which to use or adopt one for consistency (easier).  Checkboxes give a dated impression, widgets feel more modern, perhaps widgets are better suited to Metabase's overall theme.

**Comment by mazameli** [comment]
Could you let us know which Metabase version you're on, what browser you're using, and what kind of database you're querying? Dashboards and questions should be using the same kind of filter widgets, and that's what I'm seeing on master:

![screen shot 2018-08-06 at 9 40 16 am](https://user-images.githubusercontent.com/2223916/43729328-cc1b6dca-995c-11e8-8465-d7f6f1db96b9.png)

**Comment by MarcGJA** [comment]
My apologies @mazameli, that was very careless of me to not include the version and other info (oops).  Updated the issue description (solved, for me anyway).  Thanks for your patience!

**Comment by mazameli** [comment]
No worries! 

You wrote that "rebuilding dashboards from scratch" seems to fix it, but does just removing your filter and readding it fix the filter? Or even just editing the filter? We definitely don't want folks to have to rebuild all their dashboards to get the correct filtering widgets! Are you seeing this on _all_ of your pre-existing dashboards? And is this happening with Location and ID filters, or just Category filters?

**Comment by MarcGJA** [comment]
@mazameli, All is as it should be, updated the Issue accordingly, it can be closed!  The migration process must not have been quite complete when the behaviour was observed yesterday (after about 30 minutes or so of re-running the jar file).  Going back into all the migrated dashboards this morning there isn't a single checkbox in sight!  Well, I'm feeling rather sheepish!  I must not have been able to contain myself and in my excitement to evaluate v0.30.0-rc I just didn't wait long enough for the cake to rise so-to-speak!  I'll be sending in my evaluation feedback survey form soon!  Thanks!

**Comment by salsakran** [comment]
cool, closing

**Comment by MarcGJA** [comment]
@mazameli, Believe it or not the problem is real but it's not really a Metabase problem, it's a bizarre side-affect of mixing and matching Question sources on the same Dashboard.  Updated accordingly with images in case anyone else runs across the same problem.
