### ISSUE TITLE
Bug: 0.30 RC1 Admin LDAP Configuration Broke

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8222]
There are a few issues with the Authentication > LDAP settings in 0.30 RC1 that don't happen in 0.29.3.

Issues:
1. An error shows up when trying to save that says "Looks like we ran into some problems". There is nothing in the server log or client log to indicate what that is for.
2. Typing in the group search base field does not seem to enable the save button
3. The group search base field is not persisting
4. Group membership mappings are not persisting

Steps to reproduce
1. Launch a fresh metabase and setup Authentication > LDAP.
2. Attempt to save after filling in ldap settings (without group settings). An error will pop up and say "Looks like we ran into some problems." Despite this it appears to persist.
3. Log out and back in. Add a Group Search Base string. Despite changing the field the save changes will not become enabled
4. Toggle something else to get the save button to enable and save. The error "Looks like we ran into some problems" will show up again but this time the group search base will not persist.
5. Attempt to add group membership mappings. The save button in the dialog does not work (clicking it does nothing).

Here are the settings I used in this test (works in 0.29.3):
> LDAP Host: adldap.foo.com
> LDAP Port: blank (default 389)
> LDAP username/password
> User Schema: DC=foo,DC=com
> User Filter: (&(uid={login})(objectClass=organizationalPerson))
> Email Attribute: userPrincipalName
> First Name Attribute: name

- Your browser and the version: Chrome 67
- Your operating system: Windows 7
- Your databases: N/A
- Metabase version: 0.30.RC1
- Metabase hosting environment: Local Windows 7
- Metabase internal database: H2

**Comment by senior** [comment]
I am able to reproduce this and I think there are several issues here.

Following steps 1 and 2 above, I see `Looks like we ran into problems`. Checking out the network traffic from the browser, the backend gave all 200 responses. Looks like there's a PUT followed by 2 GETs, all 3 were good. Looks like the frontend must be interpreting something in the successful response as an error.

Step 3, I can confirm this too. The group search is part of a toggle enabled section of the page, it could be that the section's events aren't correctly hooked up to that save button.

The group membership mappings looks like it's broken in a different way as well. When adding a mapping and clicking save, I see the successful PUT of the mapping (and it's in the database). Clicking Cancel after the save, then opening back up the mappings doesn't show the mapping that was just added. It is in the database though, so maybe the cancel is clearing some in-memory state or something, but it's also something that needs to be fixed.
