### ISSUE TITLE
Execute command denied to user

### ISSUE THREAD

**Issue by kristiejfocht** [metabase/metabase#8235]
Browser version Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Operating system Windows 10
Database MySQL 5.6.34-log
Metabase version v0.29.3
Hosting environment Elastic Beanstalk 

I have several native queries in Metabase that use the count function. But for whatever reason, it will not generate this query without giving a 'command denied to user' error: 

select wk.hospitalId, wk.departmentId, count (al.activityLogId) AS Events7Days 
from activity_log al 
JOIN worksite wk  
ON 
al.userId = wk.userId 
where wk.deleted is null 
and al.clientId in (0,1)
and al.activityId = 6
and DATE(CONVERT_TZ(al.created, 'utc', '-7:00')) > DATE(CONVERT_TZ(NOW(), 'utc', '-7:00')) - INTERVAL 7 DAY
group by 1,2

I receive the following error message:

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: execute command denied to user 'ngread'@'%' for routine 'nursegrid_prod.count'

When I run the query in PopSQL, it runs fine. In Metabase, it will not run due to that error. 

Browsing through issues in Github, I found reference to foreign keys - I removed foreign keys from both tables but it did not work.

I don't think it's a permission issue, because I can generate this query with 'count' without any errors:

SELECT DATE(CONVERT_TZ(activity_log.created, 'utc', '-7:00')) AS 'date', COUNT(userId) AS actives
FROM activity_log
WHERE activity_log.clientId != 3 AND DATE(CONVERT_TZ(activity_log.created, 'utc', '-7:00')) > DATE(CONVERT_TZ(NOW(), 'utc', '-7:00')) - INTERVAL 7 DAY
GROUP BY 1
ORDER BY 1 DESC

Here is a query that also runs, and also joins activity_log and worksite:

SELECT DATE(CONVERT_TZ(activity_log.created, 'utc', '-7:00')) AS 'date', worksite.hospitalId, COUNT(activity_log.userId) AS actives
FROM activity_log
join worksite on 
activity_log.userId = worksite.userId 
WHERE activity_log.clientId != 3 AND DATE(CONVERT_TZ(activity_log.created, 'utc', '-7:00')) > DATE(CONVERT_TZ(NOW(), 'utc', '-7:00')) - INTERVAL 7 DAY
GROUP BY 1
ORDER BY 1 DESC

I've tried re-naming the table alias' and re-ordering the join conditions, neither have worked.

Appreciate any help anyone could provide!

**Comment by salsakran** [comment]
are you using the same user in both cases? 

do you have any stored procedures (including one named .... `count` ;) on that database?

**Comment by kristiejfocht** [comment]
Yes, I am using the same user in both cases. I only have access to one user login.
There aren't any stored procedures on that database. And wondering why I can use the function on one query but not the other? Thank you for your assistance!

**Comment by bashopman** [comment]
@kristiejfocht I have had the same problem.
In my case, the function was defined by another user than which is used by Metabase. When I changed de `DEFINER` in the create statement of the function to be the same user as used for Metabase, it started working.

**Comment by josedavca** [comment]
You write "count (" is count( without a white space.

**Comment by flamber** [comment]
Closing, since it was a problem with function spacing.
