### ISSUE TITLE
Change request: display database scheduling tab inline

### ISSUE THREAD

**Issue by mausch** [metabase/metabase#8236]
When editing a database, the "scheduling" tab is only visible when the "This is a large database, so let me choose when Metabase syncs and scans" option is enabled.

I think this rather has discoverability issues... i.e. you have to:

1. check the "This is a large database" option
1. click Save
1. Scroll up (even on a 1920x1080 monitor!) and notice there's a "scheduling" tab now.

As anecdotal evidence, I've been using Metabase for months now with this option enabled and never realised there was a separate "scheduling" tab until a couple of days ago when our database started restarting itself running out of memory every day around 1:20 AM, caused by the Metabase scan and apparently some bug in Postgres FDW. It took me quite a bit of time to realise this was caused by the Metabase scan as I was sure I had disabled it.

I think these scheduling options would be best displayed right below the "this is a large database" checkbox when the user enables it.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by brunobergher** [comment]
The copy for this setting changed a while ago and made it clearer.
