### ISSUE TITLE
Backend strings defined at load time not localizing properly

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#8245]
Any backend strings run through `tru`/`trs` at load time are not localized correctly. This includes

* all `defsetting` description strings, shown in the admin settings 
* most (all?) schema error strings, defined in `src/metabase/util/schema.clj` e.x. "Insufficient password strength"

Please comment with others you come across with.

**Comment by senior** [comment]
I've spent some time looking at this and think I understand the problem, When we use the `tru`/`trs` form, it basically creates a `printf` type of call where the original text is swapped for internationalized text. The `trs`/`tru` literal form is what the string externalization tool looks for to create its translation dictionaries.

If we have something like 
```clojure
(def my-string (trs "The text to translate"))
```
The `trs` is acting like a `printf`, so when the app first starts up it figures out the system locale, looks up the translation for that string using the system locale, then returns that string. That translated string is what is def'd. So the value of `my-string` is just a string. This kind of form is fine for the system locale as it's global and we don't support changing that locale at runtime. It'll get translated in the system locale on startup and if the locale changes it needs a restart anyway. I think we're good on `trs` calls.

That same code using the user locale, or the `tru` call is not good:
```clojure
(def my-string (tru "Other text to translate"))
```
At load time that `printf` style function runs, but the user's locale that comes from the browser is not set as we're just starting up (we get that from https://github.com/puppetlabs/clj-i18n/blob/master/src/puppetlabs/i18n/core.clj#L342). The default behavior is, if no translated version of the string is found, use the original. That format function just returns the string "Other text to translate". Now when a user HTTP request comes along later, `my-string` is the string literal "Other text to translate".

I'd love to hear more ideas, but right now with `puppetlabs/i18n`, it seems to me that the only way to support user translated strings for things like settings, schemas etc is to wrap the `tru` invocation in a thunk, i.e.
```clojure
(def my-string #(tru "Other text to translate"))
```
Although that is a small code change, I think it'll have a big ripple affect. We could make another macro that does the same wrapping in a thunk, i.e. 
```clojure
(def my-string (truf "Other text to translate"))
```
if we change the gettext invocation. I'm not sure that would save a lot of effort as utlimately that would still return a function which would cause the rippling change.

**Comment by tlrobinson** [comment]
I think even `trs` calls are a problem because the system locale is stored in the database and thus not available when those `trs` calls are evaluated at load time.

I agree an extra macro won’t help that much.

Is there some way to create some sort of lazy evaluated string?

**Comment by senior** [comment]
I didn't realize that we set our [locale at runtime](https://github.com/metabase/metabase/blob/master/src/metabase/core.clj#L194) rather than via JVM arg. You're right @tlrobinson, `trs` calls are broken too.

I'm not aware of a way to create an alternative string that looks up the translation. You wouldn't want it to be lazy as you would want it evaluated each time (i.e. multiple user locales, different runtime changing system locales etc).

**Comment by camsaul** [comment]
@senior could we just define a new record type that implements `Object/toString` and looks up its translation there ?!?!?! Something like

```clj
(defrecord LocalizedString [text
                            args]
  java.lang.Object
  (toString [_]
    (apply i18n/translate (i18n/user-locale) text args)))

(defn lstr [text & args]
  (LocalizedString. text args))

(lstr "Number of Collections")
```

**Comment by camsaul** [comment]
or maybe call it `untru`

**Comment by camsaul** [comment]
@senior WRT

> We could make another macro that does the same wrapping in a thunk

wouldn't that break the code that picks up `tru` and `trs` calls?

**Comment by senior** [comment]
@camsaul correct on the new macro, that's why right after the example I said

    if we change the gettext invocation

The gettext invocation specifically looks for the `tru` and `trs` forms, we'd need to include whatever new form we created along with that (not sure it's worth it though).

Creating a defrecord and a toString method is another approach and might look nicer, but unless everything that uses those strings explicitly calls `str`/`.toString` at runtime, each time, I think you're just trading an invocation of a thunk with a `str` invocation. As an example, schema validation errors would look like:
```
(def PositiveNum2
  "Schema representing a numeric value greater than zero. This allows floating point numbers and integers."
  (with-api-error-message
      (s/constrained s/Num (partial < 0) (lstr "Number greater than zero"))
    (lstr "value must be a number greater than zero.")))

Value does not match schema: (not
   (#metabase.util.schema.LocalizedString{:text "Number greater than
   zero", :args nil} -3))
```

**Comment by sbelak** [comment]
How about we tag all the strings via metadata and then define a new JSON encoder for strings that checks if it's tagged as translatable and if so, runs it through `tru` or whatever.

**Comment by senior** [comment]
@sbelak Not entirely sure I'm following how the metadata with JSON encoder would be used. Can you give an example? Also keep in mind that the gettext code that externalizes the strings into the pot file isn't very sophisticated. It's basically grepping for the `tru`/`trs` form and grabbing the string inside it. Anything that is generated at runtime or is not a literal in the code would mean we have to create our own pot file for the externalized strings.

**Comment by sbelak** [comment]
If gettext is just grepping we can easily use our own version:
```
(defn trs
  [s]
  (with-meta s {:translate :user}))
```
then just catch all such strings on the BE-FE boundary. A convenient spot to do this JSON serialization which already walks the results and has plugin-able encoders.

Downside: it turns out you can't attach metadata to strings :(

**Comment by camsaul** [comment]
@senior. We can just implement the Schema protocol.

```clj
(defrecord LocalizedString [text
                            args]
  java.lang.Object
  (toString [_]
    (apply i18n/translate (namespace-munge *ns*) (i18n/user-locale) text args))
  schema.core.Schema
  (explain [_]
    text))
```

```clj
(s/validate PositiveNum2 -1)
;; -> ExceptionInfo Value does not match schema: (not ("Number greater than zero" -1))
```

**Comment by camsaul** [comment]
@sbelak You can't attach metadata to strings, but you could easily dispatch off of a custom class in the JSON serializer (we already do for a few things anyway). Maybe something like a `LocalizedString` class or something.

**Comment by hztyzhq** [comment]
table.clj I18N is incorrect，as below:
[[(tru "Minute") "minute"]
                   [(tru "Hour") "hour"]
                   [day-str "day"]
                   [(tru "Week") "week"]
                   [(tru "Month") "month"]
                   [(tru "Quarter") "quarter"]
                   [(tru "Year") "year"]
                   [(tru "Minute of Hour") "minute-of-hour"]
                   [(tru "Hour of Day") "hour-of-day"]
                   [(tru "Day of Week") "day-of-week"]
                   [(tru "Day of Month") "day-of-month"]
                   [(tru "Day of Year") "day-of-year"]
                   [(tru "Week of Year") "week-of-year"]
                   [(tru "Month of Year") "month-of-year"]
                   [(tru "Quarter of Year") "quarter-of-year"]]

**Comment by senior** [comment]
@camsaul that looks to me like it would work. I think if we go the `LocalizedString` route, we'll just need to come up with workarounds for our various scenarios like the Schema protocol extension and the new JSON encoder. We'll also need to make sure it works with `defsetting` and other areas that we bubble up strings make that late binding `.toString` call.
