### ISSUE TITLE
discourse.metabase.com doesn't redirect to HTTPS

### ISSUE THREAD

**Issue by danlamanna** [metabase/metabase#8247]
~~Hi, I wanted to use the support section of the discourse for metabase. Unfortunately it requires signing up/logging in which currently transmits credentials in the clear.~~

~~Both Chrome and Firefox warn against entering credentials on this site.~~

It appears there is a valid SSL certificate, but the plain HTTP version does not redirect to HTTPS. Search results for "discourse metabase" from duckduckgo index the plain HTTP version.

**Comment by jornh** [comment]
In addition the common top menu on the other parts of https://metabase.com like https://metabase.com/blog/before-upgrading-to-0.30/index.html point to http - nowadays https rulez. And particularly since we login there!

**Comment by flamber** [comment]
And all the Discourse notification emails have links as HTTP instead HTTPS.

**Comment by paoliniluis** [comment]
Re-checked this one and everything is https by default
