### ISSUE TITLE
Hide x-rays on homepage (alternatively: make it possible to select which database is shown)

### ISSUE THREAD

**Issue by tschut** [metabase/metabase#8255]
Couldn't find an existing issue, so creating one :)

With the new homepage in 0.30, x-rays are always shown on top. In our case we have separate databases, some are more interesting to users than others. By default, metabase shows one of the less useful databases.

Would like to be able to either completely hide the x-ray section from the homepage (often our users use really specific questions and the x-rays are too generic). Or at the very least, be able to select which database is shown in this section.

**Comment by jornh** [comment]
As Admin you wan't to "pin" a few important daskboards (or even questions/pulses to the `/root` aka "Our Data" collection). See https://metabase.com/docs/v0.30.0/users-guide/01-what-is-metabase.html#the-home-page

Even as an experienced Metabase admin I find that with v0.30 you want to re-read the Users Guide as well to understand, plan, and prepare your environment for you daily users. You probably also want to give them some kind of guidance around the new features, based on what's relevant for your org found in the two v0.30 blog posts + the Github v0.30.0 release page. 

The hardest part is not even learning the *new* stuff - it's *UNlearning the old stuff* 😜 

----

Does that resolve the issue for you guys?

**Comment by tschut** [comment]
Ok, so I had to pin a dashboard in the 'our analytics' folder in order for the default xrays to go away. It works, but I think it's really counter-intuitive. Would love to have some more flexibility in what's shown to users on the homepage. For instance, if I could put whatever there, I'd put up some text describing some basic guidelines how metabase is to be used internally first, and then include perhaps some curated list of questions/dashboards. 

For anyone else wondering, pinning questions alone didn't do the trick, only dashboards. 

I'll reread the user guide, thanks for the tip 👍

**Comment by MarkRx** [comment]
I would like to be able to hide/disable x-rays for a different reason - they may result in expensive queries being run if tables are very large and not intended to be used for arbitrary field correlation.

**Comment by MarkRx** [comment]
The ability to disable xrays was removed in 0.30 - see #8411.

**Comment by mazameli** [comment]
As of version 0.31, the General tab of the admin Settings page now has a global toggle to turn x-rays and comparisons off entirely. Closing this issue as fixed.
