### ISSUE TITLE
"No data." result when downloading/exporting Question from a Saved Question

### ISSUE THREAD

**Issue by joboyx** [metabase/metabase#8256]
### INFO
- Your browser and the version: Version 68.0.3440.84 (Official Build) (64-bit)
- Your operating system: Ubuntu 17.10
- Your databases: H2 (default Sample Dataset)
- Metabase version: v0.30
- Metabase hosting environment: Ubuntu 17.10
- Metabase internal database: H2

### STEPS TO REPRODUCE
- Create a question and save it, any query will do
- Create another question again, and set `DATA` source using the previously saved question (Saved Question)
![screenshot from 2018-08-09 16-58-35](https://user-images.githubusercontent.com/920888/43889307-66517d6c-9bf6-11e8-97e8-0bb87fce9231.png)
- Download the result of the Saved Question either as CSV, XLSX, or JSON
- Download will result to a 404 response with `Not found.` as the html body
![screenshot from 2018-08-09 16-59-14](https://user-images.githubusercontent.com/920888/43889314-69cfb058-9bf6-11e8-946b-47c866fe5493.png)

### WORKAROUND
- Save the Question querying from a Saved Question
- Download as CSV, XLSX, or JSON
- Everything should work fine
![screenshot from 2018-08-09 17-06-36](https://user-images.githubusercontent.com/920888/43889423-b6a1e11c-9bf6-11e8-8788-6ae5a58f1998.png)

**Comment by joboyx** [comment]
I do think this should be a P1 or P2 issue since it hinders the users capability to extract data from Metabase which is one of its main use cases.

However, I've already stated a workaround, but this results to crowded collection since all users are saving temporary questions.

**Comment by jornh** [comment]
@joboyx maybe to as an add-on to reduce cluttering form your workaround with people having to save to download extracts you can either:
* If these users don't need to be able to save in that collection - remove their right to do so. And I *think* it should default to that it gets saved in their personal collection. Alternatively make a common "junkyard" collection.
* If they *do* need to be able to save in that collection - *instruct them* (yeah - I know it's sad) to save in their personal collection - or a "junkyard" collection.

**Comment by mazameli** [comment]
Reproduced this on master: can't download data from unsaved/ad hoc nested queries

**Comment by joboyx** [comment]
@jornh, good idea to have the "Junkyard" collection for everybody. We're currently not in v0.30, so no personal collection yet. Will transition soon.

Thanks for the response guys!

**Comment by joboyx** [comment]
Thanks for the quick turn around!
