### ISSUE TITLE
Feature request: Formatting and filters for pulses

### ISSUE THREAD

**Issue by feliksg** [metabase/metabase#8258]
It would be great to be able to format card data (for example: cards that display numbers, we already have formatting options to prepend and append things, scope decimal places, etc...).

For filters, it would be great to have dashboard like filters so that questions can be scoped to a particular date or other parameters.

I'm happy to contribute to the FE part but i'm not familiar with clojure for the BE work.

**Comment by jornh** [comment]
Related: https://github.com/metabase/metabase/issues/5771 for filters

Pretty sure a number pulse already reference an existing number card. So it shouldn’t require any backend work. I’d say have a go at that part 😄 

If you didn’t already, then have a look at the API with starting point for documentation in the wiki. Figure out what gaps you see on the BE. If it’s small I think I have the knowledge required.

**Comment by flamber** [comment]
Closing in favor of #3735 (formatting) and #5770/#5771 (filters)
