### ISSUE TITLE
No collection rename function (when using non-ascii collection names)

### ISSUE THREAD

**Issue by hztyzhq** [metabase/metabase#8259]
Metabase version: v0.29.3

When I use the Chinese name, the system is wrong，For details, see below

http://discourse.metabase.com/t/no-collection-rename-function-when-using-non-ascii-collection-names-solved/4087/7
![collection_good](https://user-images.githubusercontent.com/1948015/43901021-014cbb48-9c19-11e8-8d2f-55197e4a0d04.png)
![collection_bad](https://user-images.githubusercontent.com/1948015/43901036-0a138c8e-9c19-11e8-82c0-9456352f1a7a.png)

**Comment by mazameli** [comment]
@hztyzhq It looks like you mentioned in that Discourse thread that this issue has been resolved for you in version 0.30. If you can confirm that that's correct, we can go ahead and close this issue as resolved. Thanks!

**Comment by hztyzhq** [comment]
@mazameil but 0.29.3 version does not suppor chinese collection name.

**Comment by hztyzhq** [comment]
@mazameli @salsakran I have fixed the bug locally, the code is as follows：
frontend/src/metabase/questions/containers/CollectionPage.jsx line 19
`slug: props.params.collectionSlug,`
change
`slug: encodeURI(props.params.collectionSlug),`

How can I submit these codes?

**Comment by flamber** [comment]
Closing, since Metabase uses IDs not slugs since version 0.30
