### ISSUE TITLE
0.30 data passed by filter

### ISSUE THREAD

**Issue by tomonetml** [metabase/metabase#8262]
Hi,

We upgraded this morning from 0.29.3 to 0.30
running Metabase as service on ubuntu 14 lts.

We noticed that data passed by data-filters in query builder is offset by -1 day on mysql servers

the filter works fine on H2 and MS SQL

I am reproducing the error on a fresh brand new install of 0.30 on rpi

![h2](https://user-images.githubusercontent.com/34745293/43902986-ad79f08a-9beb-11e8-8868-df624d338789.PNG)

data returned by filter from h2 db

![mysql](https://user-images.githubusercontent.com/34745293/43903013-bbda0d90-9beb-11e8-99a6-734136bd66b0.PNG)

data returned by filter on mysql (and mariadb)

everything was fine on 0.29.3

ty
bye
Matteo

**Comment by jornh** [comment]
Hey Matteo,

Just another Metabase user here. I guess it could help in narrowing down this issue - and make sure it's reproducible elsewhere - if you could look over https://metabase.com/docs/latest/troubleshooting-guide/timezones.html and provide whatever additional info that page talks about you think is relevant. 

It may even help yourself get closer to it ... as I see you already started doing comparisons across different setups.

**Comment by calfzhou** [comment]
in v0.29.3 these is no such `cast`. Which was added in commit https://github.com/metabase/metabase/commit/550b19f401a4772470c15d209fae02b43cf57bcf#diff-2c948433821c84692a773139794871be

**Comment by calfzhou** [comment]
The problem not found in v0.29.3:

![image](https://user-images.githubusercontent.com/3761553/44037190-46e3c52c-9f46-11e8-9144-9546bb2765a1.png)

**Comment by calfzhou** [comment]
now i could temporarily fix the issue by remove the following new code in `src/metabase/driver/mysql.clj`:
![image](https://user-images.githubusercontent.com/3761553/44037687-852b8bca-9f47-11e8-8c2c-44631c2bb242.png)

![image](https://user-images.githubusercontent.com/3761553/44037871-036836d2-9f48-11e8-9b05-c3cc6dd5c2c2.png)

**Comment by calfzhou** [comment]
This new method doesn't respect our `useJDBCCompliantTimezoneShift=false` options set in JDBC connection string!

**Comment by dapaishan** [comment]
Yes, we have encountered the same problem.

**Comment by senior** [comment]
@calfzhou What is the report timezone setting for your Metabase instance?

**Comment by calfzhou** [comment]
@senior we are using Asia/Hong_Kong. But set to other timezone also have the similar issue.

**Comment by tomonetml** [comment]
@senior 
In Production site on 0.29.3 we have Europe/Berlin. Mysql timezone is set to System and System has CEST.
don't know how to check java timezone while MB is running.

on 0.30 we tried both Europe/Berlin and Database Default but nothing changed so we rolled back.

bye
Matteo

**Comment by calfzhou** [comment]
looking for that, many thanks @senior 👍

**Comment by tomonetml** [comment]
Ty @senior
We are gonna test it on week 35. I'll give you a feedback.
