### ISSUE TITLE
Migrating to 0.30 Mysql issue 

### ISSUE THREAD

**Issue by m4ex** [metabase/metabase#8266]
We have tried to run new version 0.30 with MySQL backend and it fails to start with the following error: 
08-09 18:24:25 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.DatabaseException: Column 'MD5SUM' cannot be null [Failed SQL: UPDATE metabase.DATABASECHANGELOG SET MD5SUM = NULL]

Our global variables:
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase
export MB_DB_PORT=3306
export MB_DB_USER=metabase
export MB_DB_PASS=XXX
export MB_DB_HOST=XXX
export MB_DB_SSL="false"
export MB_JETTY_PORT=3001
export MB_JETTY_HOST=127.0.0.1
export MB_EMOJI_IN_LOGS="false"
export MB_PLUGINS_DIR="/usr/local/metabase/plugins/" 

You can find full log in attach
[metabase.log](https://github.com/metabase/metabase/files/2274863/metabase.log)

**Comment by salsakran** [comment]
what version are you upgrading from?

**Comment by m4ex** [comment]
Version v0.29.0 Built on 2018-05-01, maybe we should try to upgrade to 0.29.3 first. We will check it today.

**Comment by m4ex** [comment]
We have installed 0.29.3 without any problem. But when we try to run 0.30.0 we have the same error.

**Comment by senior** [comment]
I am not able to reproduce this problem. I think what is strange is that your `MD5SUM` column appears to be not nullable. When I setup a Metabase instance, the `DATABASECHANGELOG.MD5SUM` column is nullable. I've checked this on v0.29.0 and v0.30.0. Also checked with MySQL 5.5.5.6 and PostgreSQL, all have nullable `MD5SUM` columns.

I think liquibase needs to be able to clear that MD5SUM column, so what might be easiest is just altering that column to be nullable, i.e. `alter table DATABASECHANGELOG modify column MD5SUM varchar(35);`

**Comment by m4ex** [comment]
It was my fault. Sorry for wasting your time.

We are using MySQL cluster with master-master replication, and it has a requirement: "All tables must have a primary key". So when I deployed metabase I have changed a type of  "MD5SUM" column in "DATABASECHANGELOG" table to not nullable and set it as the primary key. I forget about it.

As Workaround, I changed "MD5SUM" back to nullable and set "ORDEREXECUTED" column as primary key. After that version 0.30 starts successfully.

You can close this issue, but it would be nice if you change schema in future versions and add the primary index to this table by default. I am not sure is it a good idea to use  "ORDEREXECUTED" as primary key, but it works for me. Maybe better to create a new column for the primary index. Column "ID" looks like a good candidate for the primary index, but it's not unique, so I used "ORDEREXECUTED".

**Comment by senior** [comment]
The `DATABASECHANGELOG` table was created/used by Liquibase which is a library we use to manage database migrations. It looks like that table had a composite key at one point, but it was removed, more info on that [here](https://liquibase.jira.com/browse/CORE-1909). The suggestion is a composite key on (ID,AUTHOR,FILENAME). It looks like it was removed because some databases couldn't index over the 3 columns without the size being too big. We only run the application database on MySQL, PostgreSQL and H2, so as long as those three support it, seems like it would be easy to get included.

**Comment by senior** [comment]
@m4ex thanks for reporting this issue, the fix in #8537 was just merged and will be included with the `0.31.0` release
