### ISSUE TITLE
Redshift password field missing

### ISSUE THREAD

**Issue by Tonkonozhenko** [metabase/metabase#8267]
Hi,

I use latest docker image and do not see password when I try to create a redshift connection. When I used previous image (~2 month old) such field was present there.

![image](https://user-images.githubusercontent.com/1307646/43912674-99f512ae-9c0b-11e8-9444-09a312f79bfa.png)

**Comment by mazameli** [comment]
Confirmed that I'm seeing this on master in Chrome.

**Comment by tlrobinson** [comment]
Fixed in #8268 and will be in v0.30.1

**Comment by Tonkonozhenko** [comment]
Thanks! 👍
