### ISSUE TITLE
Download filename should contain question name

### ISSUE THREAD

**Issue by alexwais** [metabase/metabase#8280]
Currently, the download filenames read:
* query_result_2018-08-10T09_28_39.768Z.xlsx

Better:
* {name_of_question}_2018-08-10T09_28_39.768Z.xlsx

Reason: a describing default name is more readable, esp. when having multiple of those files in your download folder.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by alexwais** [comment]
Reason: a describing default name is more readable, esp. when having multiple of those files in your download folder.

**Comment by zbrowne** [comment]
We use metabase for generating reports to download and bill clients with and this would be super helpful!

**Comment by paoliniluis** [comment]
Adding to this feature request: can we add the filters used to the file name?

**Comment by Nencor** [comment]
We can make it better by exporting filename according to filter name

1. Create filter filename = "this is filename text"
2. export file in xlsx
3. filename would be "this is filename text.xlsx"
4
