### ISSUE TITLE
Not scrollable popover

### ISSUE THREAD

**Issue by Tonkonozhenko** [metabase/metabase#8281]
Hi,

When I try to drill down through answer, I'm not able to scroll list.

![image](https://user-images.githubusercontent.com/1307646/43955217-d8e95302-9ca7-11e8-8a0f-e2b5318fc063.png)

**Comment by jornh** [comment]
With #8296 resolved in 0.30.2 I’m wondering if this one got squashed as well?

Please retest with 0.30.2 just out. Thanks! 🙂

**Comment by mazameli** [comment]
Reproduced this on our stats instance just now. To repro, make your window about 800 or 900px tall, do e.g. a count of rows GUI query on the Orders table, and click on the number to open the actions menu, then click on the Category breakout. You won't be able to see all of the possible breakout fields, and the popover doesn't scroll.

**Comment by kdoh** [comment]
#9046 shipped in yesterdays 0.31.2 update and should resolve this.
