### ISSUE TITLE
uberjar build failed due to error related to UglifyJs- Need help

### ISSUE THREAD

**Issue by iamfool** [metabase/metabase#8293]
- Your operating system: (OS X 10)

uberjar build failed with following error ,

ERROR in 0.bundle.js?4ed2a0d634f26da75635 from UglifyJs
DefaultsError: `except` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/metabase/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
    at Function.buildError /metabase/node_modules/uglifyjs-webpack-plugin/dist/index.js:329:56)

**Comment by salsakran** [comment]
did you install all the frontend dependencies as described in https://github.com/metabase/metabase/blob/master/docs/developers-guide.md?

**Comment by iamfool** [comment]
Thanks for the pointer, I was able to build the uberjar successfully.

**Comment by iamfool** [comment]
Please help me close this issue.
