### ISSUE TITLE
The sum line and the average  line is Inverted

### ISSUE THREAD

**Issue by zhangdoudou** [metabase/metabase#8294]
### Bugs
The sum line and the average  line is Inverted  at dashboard

browser and the version: (Chrome 52.1)
operating system: (OS X 10)
databases: MySQL
Metabase version:  0.30
Metabase internal database:  H2   #@(default)

**Comment by jornh** [comment]
Can you please share a screenshot?

**Comment by zhangdoudou** [comment]
![image](https://user-images.githubusercontent.com/28778859/44018195-981a98dc-9f0d-11e8-8df5-8ba1a23c2ef2.png)
