### ISSUE TITLE
 Map does not appear in drop down menu of VISUALIZATION.

### ISSUE THREAD

**Issue by sexycommando** [metabase/metabase#8296]
I want to display data with latitude and longitude on a map, but map does not appear in the drop down menu of VISUALIZATION.

The operating environment is as follows.

Microsoft Edge 42.17134.1.0
Chrome 68.0.3440.106
Firefox 61.0.2

Use the latest metabase downloaded from the URL below.
http://downloads.metabase.com/v0.30.0/metabase.jar

Latest version (v. 0.30.0)

**Comment by jornh** [comment]
Can you share a screenshot of how the dropdown looks?

Does the Map work in your environment with the People table on the Metabase sample Dataset? (so we can rule out rendering problems - and look at if it’s related to your data instead)

**Comment by sexycommando** [comment]
As there is no scroll bar in the dropdown list, probably there is a problem with rendering.
If you set the screen size to 1080 * 1920, you will see all the items in the dropdown list.
I will attach a screen shot of my screen.
![query_visualization_dropdownlist](https://user-images.githubusercontent.com/5687915/44072224-7d8f8cfa-9fc8-11e8-9ec2-30cf015b7fe0.jpg)

**Comment by jornh** [comment]
Another example reported on [Discourse](http://discourse.metabase.com/t/pie-chart-in-metabase/4174/8?jornh)

**Comment by salsakran** [comment]
closed via #8434
