### ISSUE TITLE
Data Model Admin - input field width error

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8301]
Hi there,
I've just discovered a bug in Data Model Admin, where every div.flex.flex-column.flex-full in page have width of 999952px.
I have 27" 4K display but these pixels are quite useless even for me 😄 

There is printscreen of this bug:
![metabase_admininput_flex_error](https://user-images.githubusercontent.com/39486334/44032559-ba25fb84-9f07-11e8-9237-6970c7633965.jpg)

I've tried two browsers Chrome 68.0.3440.106 and Vivaldi 1.15.1147.52 (User agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52) but the shape of input fields are the same.

There is a workaround but it is quite annoying - user can scrool all way to the right and then access page elements there but... (AFAIK there is no keyboard shortcut to jump to right border of page directly)

Hope that this description is clear - otherwise do no wait to ask me 😉 

BTW: DIV element of MetadataEditor-table-list AdminList flex-no-shrink have also a slight issue in width - our DB table names are so long to overflow this graphical column.

**Comment by lwqcz** [comment]
@salsakran That was version 0.29-snapshot. After upgrade to 0.30 few minutes ago I found thi bug resolved. You can close this if you wish. Thanks.

**Comment by mazameli** [comment]
Closing as fixed in 0.30.
