### ISSUE TITLE
Feature request: filter sidebar data ref based on current db/table selection

### ISSUE THREAD

**Issue by tschut** [metabase/metabase#8307]
Feature request: would like the sidebar data reference to synchronize to the database and/or table a user has selected in a question.

The problem we currently face is that we have *a lot* of tables/saved questions. Tables mostly because of bigquery daily analytics, but the reason doesn't really matter. This means that if you're building a question and want to open up the data reference, it will take a huge amount of scrolling to reach the table you're actually interested in.

Proposed behaviour: have the sidebar datarefernce filter based on the db/table selection in the question. If you're just starting the question and have no database selected, behaviour should be the same as it is now (you see everything). As soon as a database is selected, the data ref is filtered to just show what's in this database. As soon as a table is selected, the data ref is filter to just show what's in this table.

This would make the sidebar immensely more useful :)

**Comment by mazameli** [comment]
Those of you who have upvoted this, do you ever use the data reference panel when creating questions with the graphical editor, or only when writing SQL? Do you ever use any of the "potentially interesting questions" in it?

**Comment by mazameli** [comment]
Closing this since we now:
- got rid of the data reference side panel for GUI questions
- automatically open the SQL data reference to the selected database

**Comment by Somtom** [comment]
@mazameli just came across this issue. Do you remember what the reasons where for removing the data reference from the custom questions? For a lot of people in our company this would actually be really helpful

**Comment by flamber** [comment]
@Somtom Can you explain what the idea is to have users looking in a sidebar instead of just starting to create questions in GUI?
It sounds like you are looking for this #14596

**Comment by Somtom** [comment]
@flamber yeah sure.
We started proposing the explore data feature more and more. Our team also tries to make sure that the table and column descriptions are populated within Metabase. We (the data science team) usually know the data pretty well so we would not need any description at hand **while analyzing the data**. However, our business users lack of the possibility to directly see information (like column and table descriptions) within the question GUI. So what some of them do is having two windows side by side (one with the question builder and one with the data documentation). 

I think for those business users it would be nice to have a possibility to see all relevant information for the data they are analyzing. Not only at the starting point but also while doing the analysis or exploring using the GUI. 

Thanks for linking the issue. I think it would be a great start. However, I think it would be beneficial to have the docs available during the whole analysis and not only when selecting the data.

Whether it is a sidebar or a different solution doesn't matter too much to me. I thought the sidebar might be nice - similar to the SQL questions where we have this, too.

I hope this clarifies our use case a bit more. Let me know if you have further questions or if we can support a bit (we are not proficient in Clojure but we would be willing to learn :D) .
