### ISSUE TITLE
Data Model Admin - FK select popup search-box

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8309]
Hi there,

we have quite large schema used in Metabase and currently I am working on foregin key setup for tables where I want to used them in Custom Queries.

I found that search-box on top of DIV ColumnarSelector OR ColumnarSelector-column scroll-y scroll-show would be great for schemas including hundereds of tables like ours.

Thank you.

- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52
- Your operating system: Win10
- Your databases: Postgres
- Metabase version: 0.30.0
- Metabase hosting environment: Linux/Ubuntu
- Metabase internal database: H2

**Comment by flamber** [comment]
Duplicate of #4408
