### ISSUE TITLE
Queries not running

### ISSUE THREAD

**Issue by Tonkonozhenko** [metabase/metabase#8311]
I have a bug with querying to redshift.
I want to get a simple result - get 25 rows from a table.

After running metabase for some time it stops performing queries and returns 504. If I relaunch metabase, it will start working.

How can I fix it? Probably I gave a small amount of CPU/memory? Currently, the app has up to 3.5G RAM on t2.medium instance.

- Your browser and the version: Chrome 68.0.3440.84
- Your operating system: OSX 10.12.6
- Your databases: Redshift
- Metabase version: 0.30.0
- Metabase hosting environment: Docker at ECS
- Metabase internal database: Postgres

![image](https://user-images.githubusercontent.com/1307646/44089393-46731a6e-9fcf-11e8-8437-1a561be803cf.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Tonkonozhenko** [comment]
I think yes. Also cancelling running not-saved query triggers issue.

**Comment by jornh** [comment]
With #8312 resolved in 0.30.2 I’m wondering if this one got squashed as well?

Please retest with 0.30.2 just out. Thanks! 🙂

@Tonkonozhenko I’m noticing in your screenshot you’re running https, so seems this has most of the criteria mentioned in https://github.com/metabase/metabase/issues/8312#issuecomment-417326691

**Comment by Tonkonozhenko** [comment]
It seems to be fixed by #8428
