### ISSUE TITLE
Group selection menu not scrollable anymore (in v0.30)

### ISSUE THREAD

**Issue by thalesmello** [metabase/metabase#8316]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

Chrome Version 67.0.3396.99 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Windows XP, etc)

Mac OS X Sierra (10.12.6)

- Metabase version: (e.x. 0.19.3)

v 0.30

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)

Docker

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

Postgres

- *Repeatable steps to reproduce the issue*

1. Have many groups of users such they don't fit on the screen
2. Click the group selection for a particular user
3. The list is not scrollable anymore

Gifs:

![](https://media.giphy.com/media/2aHsi82cXiFq8SJzB1/giphy.gif)

![](https://media.giphy.com/media/SLpZdb3dyU81jdCsho/giphy.gif)

**Comment by thalesmello** [comment]
I've traced the issue down to this property:

https://github.com/metabase/metabase/blob/04836dc70c7bbe1f7567da0c3e182e300ab26287/frontend/src/metabase/components/Popover.css#L23

**Comment by jornh** [comment]
Possibly related issue: https://github.com/metabase/metabase/issues/8296 (also something that reportedly started from v0.30)

**Comment by rjurado01** [comment]
Into people list, in last elements I have observe the same bug: 
![image](https://user-images.githubusercontent.com/1703608/45948199-4fb6af80-bff7-11e8-913c-0cf139c34451.png)

**Comment by kdoh** [comment]
#9046 shipped in yesterdays 0.31.2 update and should resolve this.
