### ISSUE TITLE
Cannot connect to Redshift -- No place to enter redshift password?

### ISSUE THREAD

**Issue by valuearb** [metabase/metabase#8324]
I'm unable to connect Metabase to our Redshift warehouse.

On the "Add Database" page, there is no place to even enter the password for Redshift.  

Here is the error message I get after inputting all the required credentials:

`java.sql.SQLNonTransientConnectionException: [Amazon][JDBC](10100) Connection Refused: [Amazon][JDBC](11640) Required Connection Key(s): PWD; [Amazon][JDBC](11480) Optional Connection Key(s): AccessKeyID, AuthMech, AutoCreate, BlockingRowsMode, ClusterID, DbGroups, DisableIsValidQuery, DriverLogLevel, EndpointUrl, FilterLevel, IAMDuration, Language, loginTimeout, plugin_name, profile, Region, SecretAccessKey, SessionToken, socketTimeout, sslcert, sslfactory, sslkey, sslpassword, sslrootcert, SSLTruststore , SSLTrustStorePath, tcpKeepAlive, TCPKeepAliveMinutes, unknownLength`

My current suboptimal workaround --
When the Redshift connection was unsuccessful, I then chose the PostgreSQL connection setup. I inputted the same credentials into this, and the connection seems to work. However, none of the tables show up in Metabase, and I cannot use the Question Builder to create any questions (instead I can only write my own raw SQL queries and get results). 

Here is a screenshot of the Redshift connection setup page:

![image](https://user-images.githubusercontent.com/10795307/44123038-4e362a78-9fdb-11e8-8d77-b51f8280b48c.png)

**Comment by jornh** [comment]
Duplicate of #8267 

Fix created in https://github.com/metabase/metabase/pull/8268 to be released within some days as part of upcoming v0.30.1

**Comment by senior** [comment]
The fix for this has just been merged and will be released soon, please re-open if you observe the issue in 0.30.1.
