### ISSUE TITLE
Use mongodb without auth

### ISSUE THREAD

**Issue by levimm** [metabase/metabase#8325]
Hi guys, Just wondering if it's possible to add mongo database without auth. Thanks.

**Comment by drenout** [comment]
Got the problem as well after upgrade to v0.30.0 - cannot add mongo db without providing username and password

**Comment by LucasR93** [comment]
Hack: Simply do not add username/password, go into site source code and remove the disabled flag from the submit button. That way you can add the database for now.

**Comment by AddoSolutions** [comment]
Lol, nice
![image](https://user-images.githubusercontent.com/3859209/45649999-ec7ac980-ba9a-11e8-8c22-91d4f36e3123.png)

**Comment by AngusWaller** [comment]
> Hack: Simply do not add username/password, go into site source code and remove the disabled flag from the submit button. That way you can add the database for now.

That's soo busted, I love it

**Comment by drenout** [comment]
Inspect the Inspector (undock first one and press) Cmd + Opt + J

**Comment by patelprayag1990** [comment]
awesome, works for me also
