### ISSUE TITLE
Useless GET/POST queries between frontend and middleware API

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8329]
Hi there,

I've found one behaviour of Metabase web front end which looks to me like unnecessary and pointlesly using server resources.

When I open a detail for data piece from Custom Query it open detail page including connection of that data piece to other tables (as we have hundreds of tables) this action creates a lots of GET and POST queries to middleware API. This is perfectly OK, but if user will leave this detail page before queries for data in connected tables ends it will have consequence of a lots of useless queries send from middleware as POST data stream to web interface which do not need these data anymore, as a user is not on detail page anymore.
This running queries with no change to be shown occupies server resources.

I would consider a mechanism to detect when user is no longer viewing/using detail page and stop there queries. If this is possible in GET/POST API interface. I would imagine a GET command to API to kill these still running queries.

What do you think? Am I just misunderstanding something or is this possible optimalistation?

Thank you.

- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52
- Your operating system: Win10
- Your databases: Postgres
- Metabase version: 0.30.0
- Metabase hosting environment: Ubuntu Linux
- Metabase internal database: H2

**Comment by flamber** [comment]
This was fixed in 0.35.0 - together with a lot of other performance improvements.
