### ISSUE TITLE
The function for format sql

### ISSUE THREAD

**Issue by dapaishan** [metabase/metabase#8330]
We hope to increase the functionality of formatting sql, which will bring great convenience to the work of data analysts.

**Comment by yuemanly** [comment]
Strongly support！！！！

**Comment by yuemanly** [comment]
It will be an excellent and useful function that make our work simplely and efficiently !

**Comment by lwqcz** [comment]
Guys, you mean indentation and so on in native SQL question input form?

**Comment by dapaishan** [comment]
I mean here is a function button, its role is to format the sql we entered, so that sql looks clearer and easier to understand.
<img width="510" alt="wx20180816-094201 2x" src="https://user-images.githubusercontent.com/29752433/44182321-14dc7480-a139-11e8-9abb-8a2c73749025.png">
<img width="1369" alt="wx20180816-094247 2x" src="https://user-images.githubusercontent.com/29752433/44182325-1b6aec00-a139-11e8-9db3-381dedeab546.png">

**Comment by yuemanly** [comment]
Yes, we just need a function no matter it is through a website's button or press a keyboard button that can format the sql that we code.

**Comment by dapaishan** [comment]
We just want the metabase function to be more complete, let users get more convenience, and put more energy into analyzing the data. I hope to see this feature in future versions.

**Comment by salsakran** [comment]
dupe of #9142 (using the more recent just because that one follows our issue format more closely.)
