### ISSUE TITLE
Enhance Number Chart To Support More Types

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8332]
The Number chart can be enhanced to support showing arbitrary values. Currently it only supports showing a single value that is a number. This would be useful to show states (strings), links (strings) and dates (like a due date).

The chart would be renamed to something else.

**Comment by jornh** [comment]
And ... it would also be useful to be able to handle multiple of those values in the same card, probably just restricted to that the values should come from the same record. Think of it as the mini version of the existing detail record view that you can also pin to a dashboard.

Oh, looking for documentation/a picture of that detail view instead I found that there’s already a request exactly for “pin a record to a dashboard” in #4392. To not get too many details, by default, the fields to show on the mini dashboard card should adhere to metadata settings about hiding.

Also, if the values data type set through metadata is an Image URL, it could display the image in the card (and while at it, that would also be nice to have on the already existing record detail view)

**Comment by MarkRx** [comment]
Interesting. My use case is to display status text (Pass, Fail, Error, etc) or a deadline date with a prefix to indicate the context in a small form factor. This should be pretty easy to build into the existing "Number" card. Displaying images could easily be added as well once that functionality exists.

If you wanted to go further with more details something along the lines of the text card could be expanded to allow for substitution of parameters to build text in any format using markdown. - See https://github.com/metabase/metabase/issues/4392#issuecomment-413859101

**Comment by flamber** [comment]
Related #7356

**Comment by flamber** [comment]
It has been possible to use a string for the Number visualization for a long time
