### ISSUE TITLE
Dashboard text cards aren't scrolling

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8333]
Originally [reported on discourse](http://discourse.metabase.com/t/issue-with-text-boxs/4170). This is on our stats instance: 

![text-box-scroll](https://user-images.githubusercontent.com/2223916/44159435-33286e80-a06c-11e8-9a5e-ddb5c871f0d7.gif)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by jornh** [comment]
@mazameli it's probably just a situation that has gotten worse since #7159 got reported. 

Was just about to report additional findings over there when I saw your Discourse response.

**Comment by salsakran** [comment]
closed in #9919

**Comment by maxbergmark** [comment]
I'm still having this issue on v0.35.3. I'm able to manually add scroll boxes through the browser console, where I can see that `overflow` is set to `hidden` for the text box. As soon as I update it to `auto`, the scroll bar appears correctly. However, this only solves the problem locally for me, not for other clients which are using the dashboards. 

![image](https://user-images.githubusercontent.com/1706486/83494049-fa15f400-a4b5-11ea-9a86-a5ea8169295e.png)

**Comment by flamber** [comment]
Looks like it broke in 0.33.0

**Comment by ameensom** [comment]
Still broken on v 0.35.4

**Comment by flamber** [comment]
Fixed since 0.37.0
