### ISSUE TITLE
Post-login Dashboard page now missing

### ISSUE THREAD

**Issue by jkowtko** [metabase/metabase#8334]
Where is the default post-login page that shows all of the Dashboards that are available? Can any page do this anymore?

In our company we have developers preparing dashboards for managers ... so the manager is expecting to go to a default URL and seeing whatever dashboards we have made available for general consumption. The manager can then view a dashboard and drill into Questions on that dashboard as they like.

By removing that initial post-login page showing all available dashboards, you have just eliminated the primary means of presenting data to the managers, and turned this into a "power-user only" tool.  (You cannot expect non power-users to build their own post-login screen content).

Was that the intent?

If not, then please do something like -- add a "public" collection that gets displayed as the default starting page for all users post-login ... where we can place all of our dashboards. Then you can add a User personalization setting to choose their starting page.

Thanks. John

**Comment by salsakran** [comment]
@jkowtko the intention is that you pin dashboards to the root collection that are starting points. These will be at the top of the post-login page.

In addition, different groups can have permissions onto to a specific folder, which becomes their "root" collection, and the pinned dashboards on that collection becomes the top of their post-login page, eg the marketing department can be given permissions only to the marketing folder and its subfolders, and they then see the pinned dashboards at the top of their post login screen.

Overall, the intent was to allow you to organize questions in a more natural way (by subfolders) and make it easy for users to find dashboards and questions.
