### ISSUE TITLE
Online H2 DB backup strategy

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8342]
Hi there,

I've an issue of corrupted H2 file of internal Metabase DB.
I followed steps written in [documentation](https://www.metabase.com/docs/latest/troubleshooting-guide/application-database.html) and there is mentioned that is good to have H2 DB backuped.

Is there any offcial backup guide for that?

What I managed to form based on H2 [documentation] is this command to get (http://www.h2database.com/html/tutorial.html#upgrade_backup_restore)

```java -cp ./metabase.jar org.h2.tools.Script -url jdbc:h2:`pwd`/metabase.db -script metabase.db.bkp```

But unfortunately this command cannot be used when DB is in use by Metabase as DB file is locked.
I've had stard searching for another solution for online backup but no luck yet.

The only possible solution for me now is to stop Metabase, run command shown above, start Metabase again to provide service with as small offline time as possible, compress file like `tar -cJf metabase.db.bkp.tar.xz metabase.db.bkp` and finaly upload it with rsync on backup-server.

Is there any possibility to have scheduled automated online backups directly in Metabase app (even without autoupload, rsync is managed easily and everyone can have different backup upload scenario)? 😉 

Thank you a lot!

BTW: Everyone interested in feature like written above please give 👍  to this post, thank you!

EDIT: Offline backup approach means for our instance about 2 minutes offline time. It is OK yet.

EDIT: I have just submitted a pull-request including my offline backup script, hope it will be useful for someone 🤞

**Comment by flamber** [comment]
Closing, because we encourage everyone to migrate away from H2 in production. This is partly due to the file lock, but mostly corruption of H2 is more likely than other databases.
https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
