### ISSUE TITLE
Login Password Recovery

### ISSUE THREAD

**Issue by murilo-campaner** [metabase/metabase#8346]
Hello everyone,

I'm with following problem: I logged in metabase, created some questions/dashboard, then I created new user to access the platform, but I clicked in ok without see the password. 

Then I clicked in "reset password" button, copied the new password, logged out from metabase and tried to access with new user, but it gives me "did not match stored password" error.

When I tried to access with my first admin user/password, I get the same error, now I cant access metabase.

It's a bug or Im doing anything wrong?

* I tried to access my old user with new generated password without success, then i didnt clicked in "reset password" for my old user 🥇 

Thanks in advance,

**Comment by tlrobinson** [comment]
@murilo-campaner Are you sure you reset the password for the correct user? Try the password you copied for both accounts.

**Comment by murilo-campaner** [comment]
Now I dont know more @tlrobinson 😂

I made new fresh install and tried to replicate the “bug” but it worked as expected, then I think I did something wrong... But thanks for your help!
