### ISSUE TITLE
Feature request: change rules for automatic metadata search

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8349]
Hi there,
I would be pleased to have feature to change rules for automatic metadata search.
Now (with version 0.30) I spend quite significant amount of time telling Metabase that table/view column labeled "state" is really not "state" like the United States but "state" like "status" or "status flag" or "status category".

I think that these can be interesting especialy for non-english native speakers.

Everyone interested in this feature, please give 👍  (NOT +1 comment as it is SPAM!) thank you.

**Comment by sbelak** [comment]
Mind explaining a bit more how you envision this feature. Would you like end-user control of the heuristics that do classification (instead of just manually correcting their output)?
