### ISSUE TITLE
Metabase doesn't show pivot tables on Slack.

### ISSUE THREAD

**Issue by Fleksas** [metabase/metabase#8358]
Metabase version 0.30.
![screen shot 2018-08-19 at 15 09 32](https://user-images.githubusercontent.com/9058128/44309668-081e8180-a3c2-11e8-99b2-5431f1fd4c06.png)
![screen shot 2018-08-19 at 15 09 28](https://user-images.githubusercontent.com/9058128/44309669-094fae80-a3c2-11e8-81e8-82fac4c2777e.png)

**Comment by gajus** [comment]
@tlrobinson How are the Slack reports generated?

You could use something like [Puppeteer](https://github.com/GoogleChrome/puppeteer) to simply load the table in a web app and take a screenshot of the div containing the graph. This way you would only have one codebase and consistent representation of the content across the web UI and other channels.

Now you never know what you are going to get with Slack reports.

**Comment by salsakran** [comment]
for pulses and slack attachments we render html directly on the backend. we don't use puppeteer (or similar js engines) due to complexity/load, but unifying the rendering of charts on the frontend and in pulses/slack is definitely a conversation we've had a lot.

**Comment by flamber** [comment]
Related to #5493

**Comment by flamber** [comment]
Closing this in favor of #5493/#3735

**Comment by MchlUh** [comment]
Hello Here !
I see that this topic was closed, is there a way to share pivot tables with Metabase now ? 
Thanks for the work !
