### ISSUE TITLE
[FEATURE REQUEST] Conditional formatting for Number visualization

### ISSUE THREAD

**Issue by m4ex** [metabase/metabase#8361]
You make a great feature "Conditional formatting for tables" in the last release. Is it possible to add the same feature for Number visualization?

PS. I have tried to use search but didn't found the same issue.

**Comment by mazameli** [comment]
I think this old issue is effectively the same; it references changing the _background_, but it's effectively the same idea: https://github.com/metabase/metabase/issues/3168

Going to close this one as a duplicate if that's cool with you, only because the other one already has so many upvotes.
