### ISSUE TITLE
deleted tables and schemas visible in the 'our data' section accessed through the landing page

### ISSUE THREAD

**Issue by CyrilVinot** [metabase/metabase#8363]
------
Error
-----
Even after forcing a re-sync of the schema ("sync database schema now" button), some old tables and schemas are visible from the 'our data' section 

*N.B. :  from the  /reference/databases/X/tables path, the old schemas and tables are not visible*

### Context

- databases: PostgreSQL 9.6.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit - RDS instance on AWS
- Metabase version: 0.30.0

*Repeatable steps to reproduce the issue*

- browse to the landing page >> our data >> old schemas are visible
- browse to the landing page >> our data >> pick a schema >> old tables are visible

-------

**Comment by chharland** [comment]
This may be the same issue I reported here http://discourse.metabase.com/t/data-model-changes-and-inconsistencies-in-0-30-0/4199/2. In my case, not only are old tables visible, but some recently added tables and views are missing and do not show up regardless of what I do. A side effect of this is that questions written against missing tables/views no longer work.
