### ISSUE TITLE
Admin - Data Model - Segment Preview not working

### ISSUE THREAD

**Issue by lwqcz** [metabase/metabase#8369]
Hi there,

I've noticed some blank page (actually HTTP404) followed after click on "Preview" button on Segment administration page. Please see *.gif posted below:

![metabase_segment_404](https://user-images.githubusercontent.com/39486334/44386335-86923500-a522-11e8-9b12-dd6a93224ebd.gif)

- Your browser and the version: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.52
- Your operating system: Win10
- Your databases: Postgres
- Metabase version: 0.30.1
- Metabase hosting environment: Linux/Ubuntu
- Metabase internal database: H2

**Comment by flamber** [comment]
Hi @lwqcz 
I cannot reproduce your issue on 0.31.2 - do you still see this issue on newer versions?
Also, it looks like you're doing some reverse proxy, which one are you using? Could the error come from that setup? What do you see in the logs of Metabase and the reverse proxy?

**Comment by lwqcz** [comment]
Hi @flamber 
Sorry but I am not using Metabase anymore, as my contract regarding it expired.
