### ISSUE TITLE
Cannot scroll in table list after upgrading to version 0.30.1 (Chrome & Firefox)

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#8370]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: 
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Firefox Quantum: 61.0.2 (64-bit)
- Your operating system: OS X 10.13.2
- Your databases: MySQL
- Metabase version: 0.30.1
- Metabase hosting environment: Debian9
- Metabase internal database: MySQL

When I I want to see the other tables in the list I cannot scroll to the end. When I search for the table by entering the table name in search box, I can see it.

![metabase-bug](https://user-images.githubusercontent.com/6417083/44397432-90815b80-a555-11e8-9edd-7c30aa3a774b.png)

**Comment by tlrobinson** [comment]
@alirezastack were you using 0.30.0 previously? i.e. is this a new bug in 0.30.1?

**Comment by alirezastack** [comment]
@tlrobinson yes I've upgraded from 0.30.0 to 0.30.1

**Comment by jornh** [comment]
With #8296 resolved in 0.30.2 I’m wondering if this one got squashed as well?

Please retest with 0.30.2 just out. Thanks! 🙂

**Comment by kdoh** [comment]
Should be resolved via #8857 and #9046
