### ISSUE TITLE
When deleting a database, typing localized "DELETE" won't work

### ISSUE THREAD

**Issue by vitorhirota** [metabase/metabase#8372]
Hey guys, awesome job with the localization! Just trying the Pt-BR version, went on to delete a database. A pop-up shows up asking to type in "REMOVER" to confirm the deletion, which is pt-Br localized and did not work. Worked when I typed DELETE instead.

- Metabase version: 0.30.1

- *Repeatable steps to reproduce the issue*
1. Update localization to Pt-BR
1. Delete a database
1. Enter REMOVER in the confirmation pop-up input box. Red button won't go active.
1. Enter DELETE, red button will go active.

**Comment by mrdeds** [comment]
The same in Spanish version `ELIMINAR` is displayed and it just works with `DELETE`

**Comment by tlrobinson** [comment]
PR #8395. I think it just makes sense to allow English or the localized string.

**Comment by jornh** [comment]
> I think it just makes sense to allow English or the localized string.

Love that thinking & attention to detail. Always having a default EN fallback means all things i18n can burst into 🔥 - you still have a sane backdoor.

**Comment by salsakran** [comment]
re-opening since #8588 reports it.

**Comment by flamber** [comment]
Not sure when it was fixed, but on 0.34.3 it's possible to write the translation or just `DELETE`.
Note, that the Portuguese version uses a translation string called "DELETE" instead of "REMOVER". Probably a legacy hack, when this wasn't functioning properly.
> Se tiver a certeza, por favor digite: **DELETE** nesta caixa:
