### ISSUE TITLE
Information icon not visible in Nighttime Mode

### ISSUE THREAD

**Issue by brendankilkenny** [metabase/metabase#8380]
When viewing a dashboard in 'Nighttime mode', the information icon that displays beside the question title remains black and is difficult for users to see. 

[See image](https://www.dropbox.com/s/1p038ixv8zxh59w/Metabase%20Information%20Icon%20-Daytime%20%26%20%20Nighttime.PNG?dl=0) with nighttime and daytime mode for comparison. 

Chrome 68.0
Windows 10
MySQL
Metabase version: v0.30.0
Metabase hosting environment: Heroku

**Comment by brendankilkenny** [comment]
This seems to be only happening on questions displayed as a Number

**Comment by kdoh** [comment]
Fixed by #8777, will show up in 0.31 when that gets released soon.
