### ISSUE TITLE
"Virtual columns" aren't imported

### ISSUE THREAD

**Issue by tnorth** [metabase/metabase#8381]
Importing a SQLite database, view with "virtual columns" are not imported.

CREATE TABLE `Foo` ( `bar` INTEGER, `foobar` INTEGER )
CREATE VIEW view_foo AS SELECT bar*1.0 / foobar AS foo_over_bar, * FROM Foo
INSERT INTO `Foo`(`bar`,`foobar`) VALUES (2, 3);

![screenshot_20180822_141558](https://user-images.githubusercontent.com/228861/44462929-5a57e080-a616-11e8-9f00-82bc126deec2.png)

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10) 
Independent (FF 61)

- Your operating system: (e.x. OS X 10, Windows XP, etc)
Fedora Linux 28

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
SQLite

- Metabase version: (e.x. 0.19.3)
v0.30.1

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Debian 9

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres) 
default

- *Repeatable steps to reproduce the issue*
- Create the database described above
- Import it to Metabase
- Browse the data model and notice that the view is empty.

Is that an expected behavior?

**Comment by flamber** [comment]
Hi @tnorth 
This issue looks like a duplicate of #9276 - normally I would always refer to the oldest issue, but the newer issue has more details and is already assigned.

**Comment by tnorth** [comment]
Hello @flamber 
Thanks for the update - still doesn't work for me in 0.32, but good to know it's assigned!

**Comment by flamber** [comment]
@tnorth Yes, issue #9276 is still open and assigned, so it's not part of 0.32.1 - hopefully it will be in 0.33
But please close this issue, so it's easier to overview open issues - and go and upvote by clicking the :+1:  on the issue and click Subscribe to get notifications, when there's changes to that issue.

**Comment by tnorth** [comment]
Ok, thanks!
