### ISSUE TITLE
Custom field can be created but not used

### ISSUE THREAD

**Issue by tnorth** [metabase/metabase#8382]
When creating a custom field, the following error occur when an operator (here division, "/") is selected.
expression error: [NoViableAltException]
onExpressionChange @ ExpressionEditorTextfield.jsx:238
onSuggestionAccepted @ ExpressionEditorTextfield.jsx:135
notifyAll @ CallbackQueue.js:74
close @ ReactUpdates.js:57
closeAll @ Transaction.js:207
perform @ Transaction.js:154
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
ExpressionEditorTextfield.jsx:238 expression error: [NoViableAltException]

The custom field is created, but selecting it leads to an error: 
ReactErrorUtils.js:49 Uncaught TypeError: field.operator is not a function
    at FilterPopover._updateOperator (FilterPopover.jsx:138)
    at setField (app-main.bundle.js?a31b279c771622cf2718:45687)
    at Object.FieldList._this.onChange (app-main.bundle.js?a31b279c771622cf2718:27624)
    at AccordianList.onChange (AccordianList.jsx:187)
    at Object.invokeGuardedCallback (ReactErrorUtils.js:24)
    at executeDispatch (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at executeDispatchesAndRelease (EventPluginHub.js:41)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)

And the item cannot be selected.
The selected columns are INTEGERS

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Firefox 61, Chromium 67

- Your operating system: (e.x. OS X 10, Windows XP, etc)
Fedora Linux 28

- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
SQLite

- Metabase version: (e.x. 0.19.3)
 v0.30.1

- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Linux Debian 9

- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
default

- *Repeatable steps to reproduce the issue*
- Create a new question
- Click "Add custom field"
- Select a column (defined as "number" in the data model)
- Select an operator (first error occurs in the JS console)
- Select another column (defined as "number" in the data model)
- Pick a name for the custom field
- In "filtered by", select the newly created custom field. Field can't be selected.

**Comment by flamber** [comment]
_From Discourse thread: https://discourse.metabase.com/t/custom-field-filtering-not-working/5112_

I can’t use Custom Fields in the “Filtered By” sections. Clicking on the custom field in the “Filtered By” list does nothing.

I can’t find a Github issue or forum discussion. I’ve tried on 0.31.2 and 0.29.4. How can I use Custom Fields on the “Filtered By” section ?

![image](https://discourse.metabase.com/uploads/default/optimized/2X/a/ada1e90e787903ee7f2091e5ea3ae79176d63641_1_690x366.gif)

Seeing this in the console, when trying to click on newly create custom filter in the Filtered By:
```
TypeError: n.operator is not a function[Learn More] app-main.bundle.js:5:786028
	value https://metabase/app/dist/app-main.bundle.js:5:786028
	a/this.setField https://metabase/app/dist/app-main.bundle.js:5:790531
	t/r.onChange https://metabase/app/dist/app-main.bundle.js:5:471718
	value https://metabase/app/dist/app-main.bundle.js:5:500604
	value self-hosted:1019:17
	i https://metabase/app/dist/vendor.bundle.js:96:13543
	s https://metabase/app/dist/vendor.bundle.js:96:11742
	executeDispatchesInOrder https://metabase/app/dist/vendor.bundle.js:96:12473
	h https://metabase/app/dist/vendor.bundle.js:94:21526
	f https://metabase/app/dist/vendor.bundle.js:94:21654
	forEach self-hosted:262:13
	t.exports https://metabase/app/dist/vendor.bundle.js:139:30246
	processEventQueue https://metabase/app/dist/vendor.bundle.js:94:23058
	handleTopLevel/< https://metabase/app/dist/vendor.bundle.js:145:109626
	handleTopLevel https://metabase/app/dist/vendor.bundle.js:145:109595
	f https://metabase/app/dist/vendor.bundle.js:145:131746
	perform https://metabase/app/dist/vendor.bundle.js:94:39368
	batchedUpdates https://metabase/app/dist/vendor.bundle.js:145:131224
	batchedUpdates https://metabase/app/dist/vendor.bundle.js:83:102005
	dispatchEvent https://metabase/app/dist/vendor.bundle.js:145:132527
	dispatchEvent self-hosted:1019:17
```

Your browser and the version: Firefox 64, Vivaldi 2.3 (Chrome71.0)
Your operating system: Windows 7, Windows Server 2012
Your databases: SQL Server 2012
Metabase version: 0.29.4, 0.31.2
Metabase hosting environment: Windows Server 2012
Metabase internal database: H2

**Comment by psrawke** [comment]
Hey 
I am also unable to apply filter on custom fields, I am using the latest version of Metabase i.e. 0.31.2.
Thanks,
Prasanna
