### ISSUE TITLE
[TRANSLATION] Missing Phases in pt-BR

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#8390]
At Homepage, we found a piece of phase that is not translated and has not candidate at POEditor.
![screenshot from 2018-08-23 15-47-01](https://user-images.githubusercontent.com/6808348/44545650-07505d00-a6ec-11e8-84bd-5f6f25cb98a5.png)

Look at this model **Your team's most important dashboards go here**

**Comment by jornh** [comment]
Should be fixed in 0.30.2. See [related Discourse topic](http://discourse.metabase.com/t/0-30-2-done-portuguese-translation/4323/4?u=jornh).

Please retest with 0.30.2 just out. Thanks 🙂

**Comment by dannyeuu** [comment]
Resolved by 0.30.2 version
