### ISSUE TITLE
[PT-BR] When deleting a database it is necessary to write "Delete" to enable delete button.

### ISSUE THREAD

**Issue by fbarbalho** [metabase/metabase#8393]
![image](https://user-images.githubusercontent.com/10852953/44582208-3069ff80-a777-11e8-9676-295c0c9da979.png)
![image](https://user-images.githubusercontent.com/10852953/44582219-37910d80-a777-11e8-8883-7958eae8e04e.png)

**Comment by jornh** [comment]
Duplicate of https://github.com/metabase/metabase/issues/8372

If you agree, please close this and add your 👍 vote over there.

**Comment by camsaul** [comment]
Duplicate of #8372
