### ISSUE TITLE
SAML Integration / Support ?

### ISSUE THREAD

**Issue by iamfool** [metabase/metabase#8394]
Hello Everyone,

How to implement SAML Integration of metabase with other identity provider. Has any one achieved this ? please help.

**Comment by jornh** [comment]
There’s already an existing request https://github.com/metabase/metabase/issues/4308 asking for SAML support.

Please just 👍 vote for that instead of opening yet another issue.

**Comment by mazameli** [comment]
Closing as duplicate of #4308
