### ISSUE TITLE
metrics are not migrated from v0.29.3 to v0.30.1

### ISSUE THREAD

**Issue by on99** [metabase/metabase#8399]

**Comment by on99** [comment]
![image](https://user-images.githubusercontent.com/13196393/44614221-346b4f80-a853-11e8-9881-9ca9fe7be9d3.png)

I don't see any migration error log in metabase, but the metrics are not migrated. I am not sure if it's related to Chinese characters in metrics.

**Comment by on99** [comment]
The migration process may potentially archive the metrics.

I figure out that this sql `UPDATE metric SET archived = 0` helps getting all my metrics back

**Comment by tlrobinson** [comment]
Duplicate of #8277
