### ISSUE TITLE
Column reference is ambiguous 

### ISSUE THREAD

**Issue by muriloht** [metabase/metabase#8400]
Hi,

I have some simple questions created on metabase and PostgreSQL, and after the migration for the latest version i'm getting the following error:

![selecao_046](https://user-images.githubusercontent.com/5605206/44621730-c722e300-a881-11e8-8f10-a7e9cfbccee3.png)

I found the generated query on postgresql logs as the following:

`select
	count(*) as "count"
from
	"brerp"."r_request"
left join "brerp"."r_category" "r_category__via__r_category_id" on
	"r_category_id" = "r_category__via__r_category_id"."r_category_id"
where
	(
		cast(
			"brerp"."r_request"."created" as date
		) = cast(
			now() as date
		)
		and "r_category__via__r_category_id"."name" = $1
	)`

i guess that the left join condition should be like:

`left join "brerp"."r_category" "r_category__via__r_category_id" on
		"brerp"."r_request"."r_category_id" = "r_category__via__r_category_id"."r_category_id"
`

**Comment by lwqcz** [comment]
Looks like the same as reported by me there : https://github.com/metabase/metabase/issues/8371

PS: Search first, always ... 😉

**Comment by Arrowofdarkness** [comment]
Getting that too here as well!

**Comment by muriloht** [comment]
closing as the issue was already reported at #8371
