### ISSUE TITLE
Field Filter variable from BigQuery doesn't use standard SQL

### ISSUE THREAD

**Issue by setyven** [metabase/metabase#8404]
Browser: Chrome 53.0
OS: Ubuntu 16.04
Databases: BigQuery
Metabase version: 0.30.1
Metabase hosting environment: Linux/Ubuntu 16.04 on Kubernetes 1.10
Metabase internal database: Postgres

Field filter variable queries BigQuery using legacy SQL even though the default in 0.30 onward is Standard SQL. Adding `#standardSql` also doesn't help. 
Following is a query example run from Metabase:
`select * from dataset_name.table_name
where {{status}}`
which will fail, and query history in BigQuery will log this:
``select * from dataset_name.table_name
where status IN `dataset_name.table_name`.`status` IN ('status1','status2')``

**Comment by setyven** [comment]
Found out that adding backtick to the dataset's name fixes this, because metabase replaces `{{status}}` to be ```dataset_name.table`.`status` IN ('status1','status2')``, and bigquery requires the `FROM` clause to use backtick as well if it's present in the `WHERE` clause, otherwise the column's name won't be recognized.
Closing this issue.

**Comment by SrancsikAtBitrise** [comment]
Adding backtick before and after the dataset_name.table_name is the solution.

`select * from `dataset_name.table_name` where {{status}}`

**Comment by asantibanez** [comment]
Thanks for this one @setyven! It works with the backticks. Saved my day! 👍

**Comment by MagdalenaDeschner** [comment]
@setyven @SrancsikAtBitrise I am facing a pretty similar issue. Running this query 1) 
```WITH temp AS (SELECT col_a FROM `dataset_name`.`table_name`) SELECT col_a FROM temp WHERE {{col_a}}```. <br>

If I execute this query directly in BigQuery and exchange the curly brackets with an IN statement by myself, it works ```WITH temp AS (SELECT col_a FROM `dataset_name`.`table_name`) SELECT col_a FROM temp WHERE `temp`.`col_a` IN ("value_a")``` but somehow Metabase translates query 1) to ```WITH temp AS (SELECT * FROM `dataset_name`.`table_name`) SELECT * FROM temp WHERE `dataset_name`.`table_name`.`col_a` in ("value_a")``` and claims to not be able to find ```dataset_name`.`table_name```.

Do you have any clue how I am able to use field filters in combination with the ```WITH AS``` statement?

**Comment by flamber** [comment]
@MagdalenaDeschner You cannot use table aliases with Field Filters - #3324, upvote by clicking :+1: 
And when using Field Filters on BigQuery you need to tick the dataset and table: `dataset.table`
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

**Comment by setyven** [comment]
Adding to what @flamber mentioned

1. you need to add backtick to your table name in your `FROM` clause, as Metabase will translate your filter to use backticked table name in your `WHERE` clause. Use backticked table in your `SELECT` statements too in case you're joining with other tables with same column names.
2. the way Metabase works is that everytime it encounters a filter, say `{{country}}`, it will append your table's name before the column, and becomes something like `` `mytable`.`country` ``. **BUT**, the caveat here is that you can apply your filter in your `WITH` statements instead. That happens to be best practice anw with BigQuery, as you'll reduce the size of data that travels across subqueries.

So in your case, it should've been this
```
WITH temp AS (
    SELECT `table_name`.col_a FROM `dataset_name`.`table_name`
    WHERE {{col_a}}
) 
SELECT col_a FROM temp
```

**Comment by hobailey** [comment]
@setyven forgive me for rekindly an old thread, but I'm trying to work out if I'm doing something wrong, or if I've actually found a bug - but either way, I'm struggling to make this work. My code is
```
with temp as (
    select
        `mobile_app_events`.event_text
    from
        `dbt_prod`.`mobile_app_events`
    where
        {{event_text}}
)
select event_text from temp
```
And here's my variable info:
![image](https://user-images.githubusercontent.com/1564439/85059436-8b19ea00-b19b-11ea-978c-8e24893a0ff0.png)

I've Googled alot and tried a bunch of different solutions (mainly referring to these infamous backticks!) but just not getting anywhere :-(

I'm running Metabase v0.35.4

**Comment by flamber** [comment]
@hobailey You need to do this: ``FROM `dbt_prod.mobile_app_events` ``
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
