### ISSUE TITLE
Unable to share sub-collections from Personal Collection

### ISSUE THREAD

**Issue by adriank-convoy** [metabase/metabase#8406]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 68.0.3440.106
- Your operating system: OS X 10
- Your databases: Redshift
- Metabase version: 0.30.1
- Metabase hosting environment: ECS/Docker 
- Metabase internal database: Postgres

## Repro Steps:
1. Create a sub-collection in your Personal Collection
2. Navigate into the sub-collection, hit Edit the permissions for this collection - at this point no one has access to this collection:  
![image](https://user-images.githubusercontent.com/40185566/44677427-bcd02880-a9ea-11e8-93bf-226b18175b9f.png)

3. Make a change granting another group view access: 
![image](https://user-images.githubusercontent.com/40185566/44677438-c5c0fa00-a9ea-11e8-8c0a-64dae8c28760.png)

4. **Issue 1:** Get message about All Users already having greater access? Doesn't make much sense... 
![image](https://user-images.githubusercontent.com/40185566/44677469-d5404300-a9ea-11e8-93e8-5d69d12a7a95.png)

5. **Issue 2:** Hit Revoke access, then Save, get this message: 
![image](https://user-images.githubusercontent.com/40185566/44677497-f012b780-a9ea-11e8-8ab9-a915b59131a8.png)

6. Logs show: 
```PUT /api/collection/graph 500 (71 ms) (7 DB calls).
{:message "You cannot edit permissions for a Personal Collection or its descendants.",
:type java.lang.Exception,
:stacktrace
["models.permissions$check_not_personal_collection_or_descendant.invokeStatic(permissions.clj:474)"
"models.permissions$check_not_personal_collection_or_descendant.invoke(permissions.clj:461)"
"models.permissions$revoke_collection_permissions_BANG_.invokeStatic(permissions.clj:479)"
"models.permissions$revoke_collection_permissions_BANG_.invoke(permissions.clj:476)"
"models.collection$fn__27294$update_collection_permissions_BANG___27299$fn__27300.invoke(collection.clj:878)"
"models.collection$fn__27294$update_collection_permissions_BANG___27299.invoke(collection.clj:870)"
"models.collection$fn__27319$update_group_permissions_BANG___27324$fn__27325.invoke(collection.clj:887)"
"models.collection$fn__27319$update_group_permissions_BANG___27324.invoke(collection.clj:884)"
"models.collection$fn__27360$update_graph_BANG___27369$fn__27370$fn__27374.invoke(collection.clj:914)"
"models.collection$fn__27360$update_graph_BANG___27369$fn__27370.invoke(collection.clj:912)"
"models.collection$fn__27360$update_graph_BANG___27369.invoke(collection.clj:902)"
"api.collection$fn__46474.invokeStatic(collection.clj:304)"
"api.collection$fn__46474.invoke(collection.clj:299)"
"middleware$enforce_authentication$fn__55250.invoke(middleware.clj:116)"
"api.routes$fn__55392.invokeStatic(routes.clj:62)"
"api.routes$fn__55392.invoke(routes.clj:62)"
"routes$fn__55477$fn__55478.doInvoke(routes.clj:108)"
"routes$fn__55477.invokeStatic(routes.clj:103)"
"routes$fn__55477.invoke(routes.clj:103)"
"middleware$catch_api_exceptions$fn__55379.invoke(middleware.clj:424)"
"middleware$log_api_call$fn__55356$fn__55358.invoke(middleware.clj:351)"
"middleware$log_api_call$fn__55356.invoke(middleware.clj:350)"
"middleware$add_security_headers$fn__55304.invoke(middleware.clj:253)"
"core$wrap_streamed_json_response$fn__60666.invoke(core.clj:67)"
"middleware$bind_current_user$fn__55255.invoke(middleware.clj:140)"
"middleware$maybe_set_site_url$fn__55308.invoke(middleware.clj:277)"]}
```

I'm really hoping the intention is that we're able to share sub-collections from our Personal Collection with different groups (assuming that's why the option exists in the UI). There's already been a lot of confusion about this after we upgraded this morning, right now everyone is just saving everything in the 'Migrated Questions' collections to get around this.

**Comment by cparaskeva** [comment]
Hello Metabase team! Any update this issue? It's very important to many admin and users of metabase.

**Comment by nemanjaglumac** [comment]
IMO, it's a mistake that there is an option to change permission level for a sub-collection in one's personal collection to begin with. It shouldn't be possible to do that, so backend reacts appropriately. The problem is UI. 
The [documentation](https://www.metabase.com/docs/latest/administration-guide/06-collections.html#personal-collections) clearly says:
> A personal collection works just like any other collection except that its permissions can’t be changed. If a sub-collection within a personal collection is moved to a different collection, it will inherit the permissions of that collection.

**Comment by flamber** [comment]
@nemanjaglumac Things were different before 0.30 - but it should not show lock-icon on PC sub-collections.

**Comment by adriank-convoy** [comment]
Chiming back in here after a couple of years to add some additional perspective... While 
> IMO, it's a mistake that there is an option to change permission level for a sub-collection in one's personal collection to begin with. It shouldn't be possible to do that, so backend reacts appropriately. The problem is UI.

might be correct according to the current documentation, I still think the overall idea of not being able to share from your personal collection is bad. Personal collections just aren't really useful as is - I want to be able to share interesting data that I discover, and right now my only option is to move a question into some public folder. Frequently these questions are one-offs that I don't intend to "maintain", so they don't get cleaned up. As evidence I offer some stats from our Metabase instance:

Personal collections with < 5 cards: 46%
Personal collections with < 10 cards: 70%
Number of questions in our "Random" collection: **over 19,000**

When you can't use your personal collection to share questions, they just end up cluttering up public collections
