### ISSUE TITLE
Should we get rid of the permissions changes summary modal?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8408]
This thing feels like an ugly, hard-to-read, unnecessary speed bump. I'm also not sure I believe in a world where people are dialing in a bajillion permissions changes for all their groups in one go, but more likely making smaller chunks of changes and saving those periodically — thus decreasing the need for something like this.

Removing it would also make the flow for setting up sandboxed permissions less clicky feeling.

![screen shot 2018-08-15 at 2 38 03 pm](https://user-images.githubusercontent.com/2223916/44175306-a517ac80-a09a-11e8-9351-3d0f3af8832d.png)

**Comment by brunobergher** [comment]
Not relevant anymore.
