### ISSUE TITLE
Sample Dataset needs to be forced to the bottom of all Database lists

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#841]
currently the lists appear to be alphabetical and the end result is that if a db has a name which is alphabetically after "Sample Database" then the sample data always shows up first in the list.

**Comment by camsaul** [comment]
Is this really a bug?

**Comment by agilliland** [comment]
That was the requirement from the original design, but at this point it doesn't seem to be causing any issues so i think this can be safely closed.
