### ISSUE TITLE
pulse attachment file(question name) Korean support problem

### ISSUE THREAD

**Issue by kuil09** [metabase/metabase#8410]
I'm using metabase version: v0.30.1 on docker.
My problem is metabase pulse attachment files never shown my email.

I found out the cause.
file never shown problem happend when I create question in "Korean".
But I created question name to English. It works well.

I want to crete question to my own langauge. I need help.

**Comment by SirTomme** [comment]
I have a similar problem when using german Umlaute (like ä, ö, ü) in question names that I want to attach as a file to my pulse. An attachment for the question named "Totalausfälle" (total outages) will show up in Outlook 2016 as: `=?ANSI_X3.4-1968?Q?More_results_for_'Totalausf=3Flle'?=.xlsx`.
Outlook will save the file as `Totalausflle.xlsx`

![metabase-bug](https://user-images.githubusercontent.com/16371904/52710124-d6602f00-2f8e-11e9-92de-cd6fb7f9f25b.png)

**Comment by FlyingDriver** [comment]
I have been meet the problem too when use Chinese question name and my version is v0.34.0, hope this bug will sove quickly. Thanks a lot

**Comment by tsmacdonald** [comment]
Should be fixed now:

![image](https://user-images.githubusercontent.com/784417/97455082-73026600-1905-11eb-87a6-8bf9c65a25d7.png)
