### ISSUE TITLE
Embedded dashboard scrollbar

### ISSUE THREAD

**Issue by gMoZzY** [metabase/metabase#8412]
Hello,

I'm currently trying to find a BI solution that fit our needs and have put some extra time into Metabase due to some functionality that others were lacking.

At version 0.26.2 the embedded dashboard looked fine, now I used 0.30.1 and a scrollbar appeared. 

![selection_089](https://user-images.githubusercontent.com/4875087/44707992-42fd7500-aaa6-11e8-92f4-8990949b8f23.png)

If I scroll down the "Powered by Metabase" footer is there.

0.26.2 had scrollbar problems with embedded questions.
0.30.1 have scrollbar problems with embedded dashboards.

Worst case we'll have to downgrade but would prefer a solution/workaround.

Chart type or iframe height have no impact what I could see.

This could be related to #7903 

Browser/os
Firefox ESR 52.9.0
Debian GNU/Linux 9.5 (stretch)

Chrome 68.0.3440.91, Firefox 61.0.2
Android 6.0.1

Metabase info:
Connected to database: Bigquery
Metabase versin: 0.30.1
Host: Debian (local machine for now)
Metabase internal database: default

**Comment by bedej** [comment]
Hi @gMoZzY, did you find a solution to this problem? I'm on 0.30.4 and I'm seeing the same thing. All embedded dashboards I've tried have scrollbars.

**Comment by bedej** [comment]
Confirmed that if I manually edit the CSS in browser (via Chrome debugger), to remove the 100vh as linked in #7903, this problem goes away. Not sure how to persist that as a change to make this usable in production though.

**Comment by gMoZzY** [comment]
Hello @bedej, I ended up doing a custom build where I merged #7639 with the current version at that time (0.30.1), to be able to add custom css to the embed which worked fine. Could probably do a custom build with some css changes too.

This however is not optimal if one wants to keep up to date with versions, which often is a good thing to do.

**Comment by flamber** [comment]
I cannot reproduce on 0.41.2
