### ISSUE TITLE
Goals are out of sync between question and dashboard

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#8414]
We have a question setup to display as a Progress bar. In this question we have set a goal value to `128` which is displaying fine:

[![Image from Gyazo](https://i.gyazo.com/6f6562cd16c0f2e70cebf81a678a47a0.png)](https://gyazo.com/6f6562cd16c0f2e70cebf81a678a47a0)

When we then go into the dashboard which is showing this question, the goal value has reset to a different number.

[![Image from Gyazo](https://i.gyazo.com/69d1ddb03c912543273d889c9e511f6f.png)](https://gyazo.com/69d1ddb03c912543273d889c9e511f6f)

But what's weird is if we edit the question within the dashboard and reset the values, it sets it to 0 rather than what the question itself has set.

This is on Metabase v0.30.1

**Comment by flamber** [comment]
Hi @jbrooksuk 

I've tried to replicate your issue on 0.31.2 without success. Could you try that version?

When modifying settings in the card, it will lock the settings of the card, so updating via the question doesn't change anything until you edit the card and select `Reset to defaults`.
It sounds like, that was what you were seeing...?
