### ISSUE TITLE
Incorrect display time by +5hr 30 mins 

### ISSUE THREAD

**Issue by bishu05** [metabase/metabase#8415]
The report displays incorrect time which is 5 Hrs and 30 mins ahead of the time stored in DB. However, the report displays the correct time as stored in DB if the timezone is set to UTC, which we currently use as a workaround.
Our systems default timezone is Asia/Calcutta

Here follows the DB and timezone settings detail.
Chrome: 68+, Mozilla: 61
OS: Ubuntu 16.04, 18.04, Mac - 10.13.6, Win- 10
Metabase: 0.30.1
Metabase hosting: Centos 7, custom installation
Metabase time zone tried: Asia/Calcutta, Database Default
DB: Mysql 5.7.19 
DB timezone: Asia/Calcutta

**Comment by jornh** [comment]
Try following the steps in 
https://metabase.com/docs/latest/troubleshooting-guide/timezones.html

There are unfortunately more moving parts involved when it comes to configuration of time zones.

**Comment by bishu05** [comment]
Hi Sameer,

It was some db connectivity issue, which was resolved after restarting the
app.

Thanks & Regards,

Bishu
