### ISSUE TITLE
Store task success/failure status with task history

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8416]
https://github.com/metabase/metabase/issues/7611 added some historical information for our background tasks. It would also be useful to know if the tasks were successful. If there was some sort of failure, it would be good to include the error message and the stacktrace. This would provide some context for failures, how frequently they happen and would have a longer life than log files.

**Comment by calherries** [comment]
@qnkhuat I believe this was closed by https://github.com/metabase/metabase/pull/9372

see
https://github.com/metabase/metabase/blob/3c71e3a473a440e17c5fb0e90e35c5ab2e55aeee/src/metabase/models/task_history.clj#L98-L103

**Comment by qnkhuat** [comment]
yes, you're right. But like I said in [here](https://www.notion.so/metabase/Improve-Pulse-performance-and-debuggability-caa4921e7376452f8c721d30eb3a7bb9?pvs=4#2c3d49d2cfa44f5f93e0c14f2838e357), this way of storing data is not apparent for people to know, thus discovering it.

One example is that @piranha used to debug https://github.com/metabase/metabase/issues/37459, and I'm pretty sure he doesn't know that we store info for failed tasks.

So I want to leave this open so we can come up with a design that makes this info more apparent to users.

**Comment by calherries** [comment]
> So I want to leave this open so we can come up with a design that makes this info more apparent to users.

Surfacing the data to users better is more like https://github.com/metabase/metabase/issues/12084 

I would argue this issue's title and description is more about storing the data, which we already do.

**Comment by qnkhuat** [comment]
agreed
