### ISSUE TITLE
Store task history information for pulses and other background processes

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8417]
https://github.com/metabase/metabase/issues/7611 added storage of metadata for our sync process and added the table and coded needed to instrument our pulses process in a similar way. We should include that task metadata for any of our backgorund processes that we might want to debug.

For pulses, knowing that they were sent out and the status was a success/failure might help in troubleshooting issues like https://github.com/metabase/metabase/issues/7389 and https://github.com/metabase/metabase/issues/7682

**Comment by flamber** [comment]
This looks like it was by #9372, which is in 0.31.3

**Comment by camsaul** [comment]
Thanks @flamber. Closing as fixed by #9372
