### ISSUE TITLE
 Unable to differentiate between fields in new table vis UX if same table joined between two separate FK fields

### ISSUE THREAD

**Issue by jrosenthal** [metabase/metabase#8418]
- Your databases: MySQL (5.0 :( )
- Metabase version: 0.30.1
- Metabase hosting environment: CentOS 7, jar
- Metabase internal database: Postgres
Given two tables, outage and event, where outage has fields outage.start_event_id and outage.end_event_id that are both FK pointing at the event table.  The new visualization UX for tables lets you add joined fields from the event table as visible fields (which is awesome).  However, because there are two FK to the event table, there are two sets of event fields, each titled with the table name: ie: Event.  There is no visual differentiation between the Event fields from start_event_id and the event fields from end_event_id.

Perhaps in the list we could add the key field name after the table name?  
eg: 
Event - start_event_id

**Comment by mazameli** [comment]
Totally agree. @tlrobinson, I think this is something we talked about implementing but that we let slip.

**Comment by flamber** [comment]
Not sure when this changed, but on 0.35.3, the linked table would be `Start Event` and `End Event`, since it generates the name from normalizing the FK column name.
This causing some other issues, like #11452
