### ISSUE TITLE
Bug v0.30+ Docker MySQL internal database: startup loop

### ISSUE THREAD

**Issue by tarcisioN** [metabase/metabase#8419]
I'm trying to load a new metabase instance with internal MySQL database, but it loops between "Loading Metabase..." and "Checking if Database has unrun migrations...".

Checking the database, I saw that metabase migrated only DATABASECHANGELOG and DATABASECHANGELOGLOCK tables.

I'd reproduced the same steps with v0.29 and it worked fine.

I'm using the clean docker-hub image.

**Comment by doodlebro** [comment]
This bug is effecting a lot of us, but Metabase's devs don't seem to care a whole lot about it.

**Comment by tarcisioN** [comment]
Hi, Ryan.
Im using MySql 5.6.40.
Thanks!

Em ter, 25 de set de 2018 14:28, Ryan Senior <notifications@github.com>
escreveu:

**Comment by tarcisioN** [comment]
@senior No, there is no error messages.

**Comment by senior** [comment]
Maybe the lock is in place and that's causing the looping? What are the results of running `select * from DATABASECHANGELOGLOCK` on your database? If there's not a locked row there, I think next I'd want to see what the output looks like before it loops.

**Comment by tarcisioN** [comment]
@senior Okay, I apologize for this. I could only reproduce the looping behavior by deploying the metabase in Tsuru (tsuru.io). So I guess it's not a problem that you should worry about. Despite this, I can paste the console output if it's still interesting.

**Comment by tarcisioN** [comment]
Finally, the problem seems to be the memory limitation of 1GB. I changed this limitation to 2GB and it works fine. My apologies again.
