### ISSUE TITLE
Different markers with Map view and group by

### ISSUE THREAD

**Issue by iGitScor** [metabase/metabase#8424]
Hi folks,

I would like to make an improvement proposal

### Feature requests and proposals
- Display markers on map with different colors based on `group by`

Example:
SELECT * FROM Address WHERE zipcode = '75010' GROUP BY residenceType;

Address table has latitude and longitude fields and residenceType are INT values

**Comment by jornh** [comment]
Sounds an awful lot like a duplicate of https://github.com/metabase/metabase/issues/5973

If you agree this is the same (just that you want it to be generalized from `group by "2 kinds"` to `group by residenceType` - INT's) then please close this issue and 👍 vote with an emoji (+ add your -  nice - additional suggestion to the requirements) over there.

**Comment by iGitScor** [comment]
Yep, I didn't find it with map keyword, thank you and sorry for this awful duplication
