### ISSUE TITLE
Display seconds when displaying a date

### ISSUE THREAD

**Issue by guylando** [metabase/metabase#8439]
Currently postgresql timestamp field is displayed as 
Tuesday, August 28, 2018 2:53 PM

How can we configure it to display the seconds also and not only hours and minutes?

**Comment by guylando** [comment]
anybody?

**Comment by iamniks** [comment]
I am having the same issue.

**Comment by BrianMehrman** [comment]
I might be miss understanding the question but this is how I format the timestamp.

`SELECT to_char(current_timestamp, 'Day, Month DD, HH12:MI:SS AM')`

which will give me this

`Wednesday, December 12, 11:04:58 PM`

Checkout the [Postgresql docs](https://www.postgresql.org/docs/9.1/functions-formatting.html) for more details on formatting at date.

**Comment by guylando** [comment]
The question and feature request was about metabase interface. Many of the metabase features can be done using sql and yet the whole point of some of the metabase features like this one is to improve the UX for everybody, especially non-developers

**Comment by mazameli** [comment]
There are two ways to do this without SQL:

1. On your question, click the gear to open the visualization options, then find the date column in question and click the gear next to it. On the settings page that appears, select the `HH:MM:SS` option under "Show the time:"

![screen shot 2018-12-17 at 9 59 56 am](https://user-images.githubusercontent.com/2223916/50105820-b4db0500-01e2-11e9-8b01-02f3a99c914b.png)

2. If you _always_ want this behavior for a specific column in a table, go to the Admin Panel, then the Data Model. Find the table that contains the column in question, and click the gear to the far right of where that column is listed on the data model page. Choose the Formatting tab on the next page, and pick `HH:MM:SS` under the "Show the time" option.

![screen shot 2018-12-17 at 10 03 55 am](https://user-images.githubusercontent.com/2223916/50105946-19965f80-01e3-11e9-806c-31a13dca5625.png)

I tested this specifically on a Postgresql DB to confirm that it works in version 0.31.2. Are you having troubles getting this to work, @guylando? Please go ahead and close this issue if this resolves things for you.

FYI, this doc page has more details about formatting your tables and charts: https://www.metabase.com/docs/latest/users-guide/05-visualizing-results.html

**Comment by guylando** [comment]
@mazameli Thanks for the detailed answer
