### ISSUE TITLE
New queries take longer to save in version 30 

### ISSUE THREAD

**Issue by greallye** [metabase/metabase#8442]
Hi,

We have switched to version 30 and since this change we have noticed that if we are creating a new question and we click get answer and the results return. But then during saving it will rerun the query again during saving. 

This means if it is a long running query it will take a long time to save. 

We are using postgres as our data warehouse. 

Is this an known issue? Is there someway around this?

Thanks,
Evan

**Comment by flamber** [comment]
Hi @greallye 
Are you still having the same issue on newer versions, like 0.31.2?
If yes, then can you check the Metabase logs for signs of trouble - and fill out this information:
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

**Comment by evangreally** [comment]
Hi @flamber,

Just tested this and it is not occurring anymore. Must have been fixed with updates after version 30. 

Many Thanks,
Evan Greally

**Comment by mbvictoria** [comment]
Closing - last comment says has been fixed in newer versions.
