### ISSUE TITLE
Trying to add info about database in Reference cannot be Saved

### ISSUE THREAD

**Issue by emetselaar** [metabase/metabase#8443]
There seems to be an issue with adding info about databases and tables in the "Reference" part of the UI.

- Your browser and the version: Safari 11.1.2
- Your operating system: OS X 10.13.6
- Your databases: MySQL
- Metabase version: 0.30.1
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres
---
Replicate the issue by doing this:

- Go to https://YourMetabaseURL/reference/databases
- Click on one of your databases and Edit, change the description
- Click 'Save'
- You get error: "undefined is not an object (evaluating 'database.actions.update')"
- There are no error messages in the log

**Comment by jornh** [comment]
I noticed that as well for database. AFAIK it worked for tables when I tried. 

A workaround is to update it through `Admin > Metadata Setup`

**Comment by jornh** [comment]
Sorry, should have checked properly the path was: ⚙️ `Setting > Admin > Data Model ... ` BUT even worse 😢 you're right and I remembered wrongly: It's only possible to set description for tables - *not* databases there.

Apologies for the confusion ... the original issue described under steps to reproduce stands - tor me as well...

**Comment by nickhamlin** [comment]
Same issue appearing when using MySQL as Metabase internal database as well instead of Postgres

**Comment by denispavliha** [comment]
v0.31 - still there.

**Comment by denispavliha** [comment]
Guys, could we please get an update when anyone will even take a look at this and decide if it is an issue worth resolving? I am not sure if this classified as major or minor.

I've once read "Friends don’t let friends have undocumented DBs" (remember, @sbelak? well I wasn't there, I've read it afterwards). Unfortunately, this issue prevents me/us to nicely fill in metadata in /reference/databases :cry:

**Comment by denispavliha** [comment]
Also, I am totally manually editing directly on the DB ... metabase_databases (.description, .points_of_interest and .caveats). :laughing:

**Comment by enqueue** [comment]
I see a different error message in 0.33.0-RC1: "e.actions is undefined"

**Comment by mazameli** [comment]
Relatedly, if you already have content for a table in the "interesting" or "thing to be aware of" content sections, if you try completely deleting that content and saving, your changes aren't saved. (Edits can be saved, but not if they result in an empty string.)

**Comment by paulrosenzweig** [comment]
Fixed by #10940
