### ISSUE TITLE
NullPointerException when using native query on Google Big Query

### ISSUE THREAD

**Issue by alirezastack** [metabase/metabase#8445]
- Your operating system: OS X 10
- Your databases: Google Big Query (BQ)
- Metabase version: 0.30.1
- Metabase hosting environment: Linux Debian
- Metabase internal database: MySQL

- *Repeatable steps to reproduce the issue*
Click on one of your BQ tables, click on `get answer` and finally it prints the result. Now click on `View the SQL` and then on `Convert this question to SQL`. Now it gives the error I mentioned in title. If I change the query to:

`select * from MY_DATASET.MY_TABLE`

It gives the same error:

```

09-04 07:02:01 WARN metabase.query-processor :: Query failure: java.lang.NullPointerException
["query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:217)"
 "query_processor$assert_query_status_successful.invoke(query_processor.clj:210)"
 "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:250)"
 "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
 "query_processor$fn__36989$process_query_and_save_execution_BANG___36994$fn__36995.invoke(query_processor.clj:289)"
 "query_processor$fn__36989$process_query_and_save_execution_BANG___36994.invoke(query_processor.clj:275)"
 "query_processor$fn__37013$process_query_and_save_with_max_BANG___37018$fn__37019.invoke(query_processor.clj:310)"
 "query_processor$fn__37013$process_query_and_save_with_max_BANG___37018.invoke(query_processor.clj:306)"
 "api.dataset$fn__43466$fn__43469.invoke(dataset.clj:45)"
 "api.common$fn__20623$invoke_thunk_with_keepalive__20628$fn__20629$fn__20630.invoke(common.clj:433)"]
```

**Comment by senior** [comment]
I can't reproduce this issue on master or on `0.30.1`. Do you consistently get this error? Can you paste in the query that was generated? Also if you have any other information from the log like other stacktraces/errors or warnings that might be helpful.

I was able to convert the question to SQL and run that without issues. I also was able to modify the native query it generated and run that query successfully.

**Comment by camsaul** [comment]
Since we can't reproduce this on 30.1+ and haven't heard back in 6 months going to close as resolved. Feel free to reopen if you're still running into this issue
