### ISSUE TITLE
Stacked Bar Charts With Percentage And Counts

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8463]
Currently stacked charts will show counts (normal) or percentages (stacked 100%). I think each should show both.

Stacked (shows count... should also show percentage)
![image](https://user-images.githubusercontent.com/17504314/45117336-4d151880-b123-11e8-94b5-18065ca50521.png)

Stacked 100% (shows percent... should also show count)
![image](https://user-images.githubusercontent.com/17504314/45117374-69b15080-b123-11e8-94c7-7b717a37a023.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Related to #6832 (possible duplicate)

**Comment by paulrosenzweig** [comment]
@mazameli & @kdoh what do you think of this?

IMO it makes sense to be able to view the raw count (or sum, etc) for that bar when you hover. The downside is that it's more visual clutter in the tool tip if you're focused on assessing relative proportion rather than the raw value.

**Comment by benirose** [comment]
Any likelihood of this being revisited?

**Comment by alxnddr** [comment]
We will ship this in 46:
<img width="1359" alt="Screen Shot 2023-02-20 at 7 36 26 PM" src="https://user-images.githubusercontent.com/14301985/220208067-cc22b0e1-7bbd-442b-8e34-28792f974c5f.png">

**Comment by tanuj0905** [comment]
can  i display mean on hover?
