### ISSUE TITLE
Fail fast on application database connection issues

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8466]
Currently when there's some issue with the connection URI of the application database, Metabase will fallback to `H2` automatically. We should fail fast if the user provided connection doesn't work.

**Comment by flamber** [comment]
Not sure when this was changed, but I have never seen a fallback from the Postgres/MySQL appdb even when they were non-reachable. And now it follows `MB_DB_CONNECTION_TIMEOUT_MS`
