### ISSUE TITLE
[French translation] Bug - Some apostrophes are missing after translation

### ISSUE THREAD

**Issue by flegastelois** [metabase/metabase#8468]
Hi Metabase team :hand: @tlrobinson 

When we build Metabase (master branch) with French translation, some apostrophes don't appear in the interface, wheras they are valid in the translation tool and in the fr.po file.

**POEditor project**
![image](https://user-images.githubusercontent.com/470612/45140056-002c5300-b1b2-11e8-8e50-5d76ab5857a0.png)

**fr.po file**
![image](https://user-images.githubusercontent.com/470612/45140092-10443280-b1b2-11e8-8f29-2d3b25160ad1.png)

**Metabase UI**
![image](https://user-images.githubusercontent.com/470612/45140097-13d7b980-b1b2-11e8-8286-362d927e6118.png)

Regards,
François

**Comment by losrebellos** [comment]
Related to #15531.
