### ISSUE TITLE
[French Translation] Admin/Data Model : Layout of field setup button

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#8469]
Hi, concerning v0.30.1 in French,  there is a problem in the Admin/Data Model panel, in the layout of the field setup button, that does not follow the field type dropdown list :

![image](https://user-images.githubusercontent.com/31401884/45147220-c31d8c00-b1c4-11e8-8f5f-a1ecef7b5c7c.png)

The problem is also visible in Spanish and Portuguese.

Cannot wait to see Metabase translated in French !

Thank you all for this great piece of software.

**Comment by atranel** [comment]
I have same problem in English, but in Firefox. In Vivaldi or Chrome or Edge it is ok.
![screenshot_2](https://user-images.githubusercontent.com/42370527/45154775-fec25100-b1d8-11e8-9e51-34aaf4492a73.png)

**Comment by fetanchaud** [comment]
My mistake, I did not try another browser... does not seem to be related to translation. Closing.
