### ISSUE TITLE
Error on line 15, col 6: Incorrect syntax near 'WHERE'. Expected:),

### ISSUE THREAD

**Issue by TAJohnson36** [metabase/metabase#8473]
I'm using Toad MySQL "MariaDB" and I can't seem to figure out this syntax error in my Where Clause. Here's the error message it returning: 

_Lookup Error - MySQL Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE tm.TIMEMAST_ACTION_DATE  BETWEEN '2017-01-01 00:00:00' AND '2017-12-31 at line 15_

SELECT tm.TIMEMAST_STAFF,
       tm.TIMEMAST_CLIENT,
       tm.TIMEMAST_TIME_TAKEN,
       tm.TIMEMAST_ACTION_DATE,
       sn.SECTION_NAME,
       sn.SECTION_DESCRIPTION,
       tm.TIMEMAST_CONTRACT,
       tm.TIMEMAST_SECTION,
       con.CONTRACT_NAME
FROM (intellitime.timemast tm
     LEFT JOIN intellitime.contract con
       ON tm.TIMEMAST_CONTRACT = con.CONTRACT_ID
     LEFT JOIN intellitme.section sn
       ON tm.TIMEMAST_SECTION = sn.SECTION_ID
     WHERE tm.TIMEMAST_ACTION_DATE = calendar__gregorian__last_year__)) vw1
INNER JOIN (SELECT sn2.SECTION_NAME FROM intellitime.section sn2
             WHERE sn2.SECTION_NAME IN
                   ('Jury Duty', 'Funeral', 'Holiday', 'CIM Closed')) vw2
   ON vw1.SECTION_NAME = vw2.SECTION_NAME

-----
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by MarkRx** [comment]
Unless MariaDB has special syntax

> FROM (intellitime.timemast tm

should be

> FROM (SELECT * FROM intellitime.timemast tm

**Comment by TAJohnson36** [comment]
@MarkRx  Thanks, I ended up figuring it out and another way...to get the results I needed.

SELECT tm.TIMEMAST_STAFF,
       tm.TIMEMAST_CLIENT,
       tm.TIMEMAST_TIME_TAKEN,
       tm.TIMEMAST_ACTION_DATE,
       sn.SECTION_NAME,
       tm.TIMEMAST_CONTRACT,
       tm.TIMEMAST_SECTION,
       con.CONTRACT_NAME
FROM (intellitime.timemast tm
      LEFT OUTER JOIN intellitime.contract con
         ON (tm.TIMEMAST_CONTRACT = con.CONTRACT_ID))
     LEFT OUTER JOIN intellitime.section sn
        ON (tm.TIMEMAST_SECTION = sn.SECTION_ID)
WHERE     (tm.TIMEMAST_ACTION_DATE = calendar__gregorian__current_year__)
      AND (   (   (   (    tm.TIMEMAST_ACTION_DATE =
                           calendar__gregorian__current_year__
                       AND sn.SECTION_NAME = 'Holiday')
                   OR sn.SECTION_NAME = 'Jury Duty')
               OR sn.SECTION_NAME = 'Funeral')
           OR sn.SECTION_NAME = 'CIM Closed')
