### ISSUE TITLE
Table Color Formatting - Equals Not Working

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8478]
Looks like the "equal to" and "not equals to" condition for formatting colors on a table isn't working. All of the others conditions appear to work.

Example:
```
create table mbase.number_test (
    str VARCHAR(3) PRIMARY KEY,
    val NUMBER(3)
);

insert into mbase.number_test values ('1', 1);
insert into mbase.number_test values ('2', 2);
insert into mbase.number_test values ('3', 3);
insert into mbase.number_test values ('10', 10);
insert into mbase.number_test values ('20', 20);
insert into mbase.number_test values ('30', 30);
insert into mbase.number_test values ('100', 100);
insert into mbase.number_test values ('200', 200);
insert into mbase.number_test values ('300', 300);

commit;
```

![image](https://user-images.githubusercontent.com/17504314/45184871-40152980-b1f6-11e8-99b7-2ef1833db6c4.png)

All Options:

![table_color_equals](https://user-images.githubusercontent.com/17504314/45184780-ff1d1500-b1f5-11e8-9282-2967202e66bd.gif)

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: 68.0.3440.106 (Official Build) (64-bit)
- Your operating system: Windows 7
- Your databases: Oracle
- Metabase version: 0.30.0
- Metabase hosting environment: RHEL 7
- Metabase internal database: MySQL

**Comment by tlrobinson** [comment]
Looks like we're storing the number as a string and the rest of the operators cast it to a number, but not `===`. We should probably explicitly convert the string to a number, or we could just use `==`.

**Comment by MarkRx** [comment]
Since <, <=, >=, and > perform type coercion implicitly I think == and != should be used to be consistent. It may have to be revisited when handling other types (like coloring cells based on string values).

Seems like a low hanging fruit to get fixed for a 0.30.x release if there is another one in the works.

https://github.com/metabase/metabase/blob/c962904e69ab37d8fd643ffd94da95c6d6c5b51d/frontend/src/metabase/visualizations/lib/table_format.js#L138

**Comment by olivercrask** [comment]
I am experiencing this exact issue in 0.40.2. Greater than and less than works fine, but equals and not equals does not.

**Comment by flamber** [comment]
@olivercrask You are seeing some different problem.
Create a new issue with details or try the forum for troubleshooting: https://discourse.metabase.com/
![image](https://user-images.githubusercontent.com/1447303/129387323-fa0e6355-5d97-46bd-b54e-7c962f4292d2.png)
