### ISSUE TITLE
Can't save the initial card when clicking through a table name

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#848]
#### Expected:
User can click a Table from the main page and save the resulting query

#### Actual
'Save' button is hidden

#### Notes
The save button doesn't appear until the query becomes "dirty". Clicking a Table will take you to a new query builder page and run a "bare rows" query but this card cannot be saved until you modify the query in some way.

**Comment by salsakran** [comment]
there is not longer a table list and so this is no longer a problem.
