### ISSUE TITLE
URL in a table. When type column is URL, add in metabase datamodel a "box" to write what to see instead of the url.

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#8482]
## URL in a table. When type column is URL, add in metabase datamodel a "box" to write what to see instead of the url.

-------
Your browser and the version: (Firefox 60.0.1,)
Your operating system: (ubuntu 16.04)
Your databases: (Postgres)
Metabase version: (0.28.6)
Metabase hosting environment: (Linux/Ubuntu)
Metabase internal database: (Postgres)

---
When type column is URL, add in metabase datamodel a "box" to write what to see instead of the url.
Could be an image or a text.
![image](https://user-images.githubusercontent.com/33416503/45212889-5bd00c80-b296-11e8-8bb7-bf55c108e11a.png)

![image](https://user-images.githubusercontent.com/33416503/45212522-6e961180-b295-11e8-9d46-1bdfca58229f.png)

We will see a text or an image (always the same), but not all the url .
![image](https://user-images.githubusercontent.com/33416503/45212680-caf93100-b295-11e8-97ff-c2f4bbc09024.png)

THANKS!

**Comment by jlisyc** [comment]
Related issue. 
Allow Hyperlink Text Value To Be Specified. https://github.com/metabase/metabase/issues/6873

**Comment by jornh** [comment]
Also related issue: "Associate URL templates with tables in data model" #8461

Yes there are many ways to skin the same cat! 😉 

One *could argue* that the example you give above @jlisyc is just a (quite common) special case of the URL template being one-to-one just the same of the field  

Also, the label shown could be:
* A static text - as you propose above `Voir URL`
* a reference/lookup on another field in the same row - e.g. like a text template reference `Voir '{{shortname}}' details`

**Comment by Go2ClassPoorYorick** [comment]
Perhaps I'm misunderstanding the intention of this feature/how it's used, but currently the "Link Text field" currently does nothing other than replace a url with the "Link text" Text, correct? 

If so, it would be nice to have an additional option for constructing the appearance of the url (ie, In this picture, have "test" actually appear as "test 12", a combination of the first two columns with an unrelated hyperlink. I'm not sure if this is implemented or where I can read about it, as the usage documentation does not currently even mention the "link text" field.

![image](https://user-images.githubusercontent.com/33301123/49893250-010bfb00-fe19-11e8-8bc3-e317cf5576a7.png)

**Comment by Go2ClassPoorYorick** [comment]
@asusmsk

I believe it only formats when it sees data in the format of "http://sometexthere"

I simply queried:

Select "http://exampleurl.com", 12, 133

I did not pull from a database as I was simply testing the new url formatting.

**Comment by MarkRx** [comment]
For the example given in the screenshot you would also need to be able to use a dynamic value from another column. It can't just be static.

**Comment by Go2ClassPoorYorick** [comment]
> For the example given in the screenshot I think you would also need to be able to use a dynamic value from another column. It can't just be static.

I believe that was the point I was attempting to make? I'd like to be able to make the Text that appears appear as some combination of values from other columns or custom text. For example, if I was referencing an external database that was a combination of 2 and 3, I'd have the first column have a url of "http://mydatabase.com/id/12133", but I'd want the text just be the id "12133" with the previous url as a hyperlink.

**Comment by flamber** [comment]
Hi @jlisyc 
This was added in 0.31 as part of the big formatting features. On 0.31.2 it looks like this:
![image](https://user-images.githubusercontent.com/1447303/53272804-e3c89800-36b7-11e9-8e2f-8a0c8150d9d0.png)
![image](https://user-images.githubusercontent.com/1447303/53272835-f5aa3b00-36b7-11e9-9e22-4f178daf07dc.png)

**Comment by MarkRx** [comment]
To be complete it needs to be possible to have the text be dynamic (such as the link having a value based on another field). In the above example the link text could be the value of the name column in the corresponding row. Not sure if there is a separate issue somewhere for that.

**Comment by flamber** [comment]
@MarkRx 
This was was a request for changing the text based on column. To have a different value for each row, that's covered by #7188 and/or #8461
