### ISSUE TITLE
Display value on foreign key is ignored after reordering columns

### ISSUE THREAD

**Issue by zedidas** [metabase/metabase#8485]
When using a table to display a question results, if I change the order of any column, the display values previously configured in Foreign Keys are ignored and the Foreign Key is displayed instead.

**Steps to reproduce:**
- Data Model Setup:
  - Make sure the 'Sample Dataset' is available
  - Go to the 'Admin' page
  - Click 'Data Model'
  - Select the 'Orders' table
  - Go to the 'Product ID' properties page
  - In the 'Display Values' section, set 'Use foreign key' --> 'Title'
  - Leave the 'Admin' page
- Steps to reproduce:
  - Start a new question
  - Select the 'Orders' table and click 'Get Answer'
  - Check that the column 'Product ID' shows the product name, as expected:
![image](https://user-images.githubusercontent.com/5529181/45233375-791ece00-b2ca-11e8-83a6-36d32f37515c.png)
  - Now configure the table and change the order of any column
  - Close and hit 'Refresh'. The 'Product ID' shows the product ID instead of the product name.
![image](https://user-images.githubusercontent.com/5529181/45233431-a2d7f500-b2ca-11e8-8d6d-80eeb6c489e0.png)

**Expected result:**
- Modifying the orders of columns should not affect any of the previously configured display values.

**Environment:**
- Google Chrome 68.0.3440.106 (64 bits)
- Windows 10
- Postgres
- Metabase version 0.30.0
- Hosting env: Docker
- Internal dabatase: Postgres

**Comment by tlrobinson** [comment]
I think this is fixed in v0.30.1 via #8375

**Comment by zedidas** [comment]
Today we have deployed version v0.30.3 and I can confirm that the problem is fixed.

![image](https://user-images.githubusercontent.com/5529181/45812622-2ed51e00-bcc8-11e8-9d17-5d4f551e899b.png)

I can't tell in which previous version it was fixed.

Thank you!
