### ISSUE TITLE
Repeated Strings / Arrays of Strings don't work with standardSQL dialect

### ISSUE THREAD

**Issue by elm-** [metabase/metabase#8488]
Since the new standard SQL dialect migration we have an issue with our array columns on Google BigQuery (Repeated field of type String). In the legacy version those worked, i.e. were correctly un nested when querying for in auto completion for filters and also for search in questions.

For standard SQL there seems to be no support for this anymore and I was wondering if this was planned to reduce functionality or is a bug. The version this is with is 0.30.2.

Below an  example that errors created for the drop down auto completion. The field code_types is an array of strings.
```
  -- Metabase
SELECT
  `active_user_accounts_info_mat`.`code_types` AS `active_user_accounts_info_mat___code_types`
FROM
  `active_user_accounts_info_mat`
WHERE
  (LOWER(`active_user_accounts_info_mat`.`code_types`) LIKE 'c%')
GROUP BY
  `active_user_accounts_info_mat___code_types`
ORDER BY
  `active_user_accounts_info_mat___code_types` ASC
LIMIT
  100
```

Error is 

```
Error: No matching signature for function LOWER for argument types: ARRAY<STRING>. Supported signatures: LOWER(STRING); LOWER(BYTES) at [2:185]
```

There are several ways to achieve this and also the support on generated queries to support this in standard SQL. 

To reproduce this define a repeated string field in any BigQuery table and create a custom question using this as a filter.

If there are no plans yet / its not a bug, any hints where to find an example how this is solved for another database dialect would be helpful, would be happy to work on providing a PR to introduce this functionality into BigQuery dialect, but could not find any.

**Comment by jeff303** [comment]
The fact that this happened to work in some version pre `x.30` was something of a happy accident.  We don't have intentional and comprehensive support for working with complex types (which includes the `mode=REPEATED` BigQuery columns).  Once we tackle that project in earnest, we will support this type and others in the way outlined in the description here.
