### ISSUE TITLE
SSL w/ Elastic Beanstalk Leads to blank page (408/time outs)

### ISSUE THREAD

**Issue by cycomachead** [metabase/metabase#8489]
I've got an issue I can't track down. So far this has happened on 0.30.1 and 0.30.2.

My metabase app is running at snap-analytics.cs10.org

When I visit http://snap-analytics.cs10.org, things are fine, but visiting with an https:// connection leads to a time out and a white page.

* Happens on v0.30.1 (new install) and v0.30.2
* No errors in any of the cloud watch log buckets
* The ELB has port 443 enabled and is serving a cert generated by AWS, the domain is on Route 53.
* `NGINX_SERVER_NAME` is set to `snap-analytics.cs10.org`.
* When the timeout happens the browser still gets the correct cert, and says it's valid. 

I realize that's not much to go on, but any help would be appreciated. :)

**Comment by cycomachead** [comment]
this is still happening with 0.30.3

**Comment by drew887** [comment]
Same here, brand new install today everything works fine till we try the https version 🤔

**Comment by drew887** [comment]
Ah my issue was with the load balancer rule. I accidentally set both the listener port and the instance port to be 443, however the instance port needs to be http since the load balancer is handling the https side

**Comment by cycomachead** [comment]
Thanks for the comments. Hmm, I thought my configuration was set that way but perhaps I’m misunderstanding. I am a bit new to ELB. :)

Would you mind sharing a screenshot? 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by drew887** [comment]
This is the config that worked for me

![screen shot 2018-09-25 at 2 50 02 pm](https://user-images.githubusercontent.com/2347730/46035970-641baa80-c0d2-11e8-8259-fb3c3bf96392.png)

**Comment by cycomachead** [comment]
Ah ha! Now I get it. That is indeed working for me. 

Thanks much for the help! :)

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by a0th** [comment]
I am facing the same issue.

I didnt have the `NGINX_SERVER_NAME` variable set in the console, but setting it didn't change anything.
The `website.metabase.com` is set inside the admin menu.

Just setting the Load Balancer to 80 HTTP -> 80 HTTP will work, but with complaints of no SSL.
As long as I still have this rule, I can still access the `website.metabase.com` address.

I tried all combinations of 443 HTTPS -> 80/443 HTTP(S) with  the SSL certificate, except for having two rules pointing to 80 HTTP, as ELB will not allow it. All the combinations result in the visit to `https://website.metabase.com` giving a white screen, timeout.

Letting only the HTTPS 443 -> HTTP 80 with the SSL certificate will also make `website.metabase.com` to give a timeout too.

Cant find any errors in the Load Balancer log or the instance log.

The admin->general menu allows me to choose between HTTP and HTTPS,  but  once you set it to HTTPS, it starts to "Checking HTTPS..." and it never gives any result.

**Comment by a0th** [comment]
I dont know what happened, but after leaving just the 443 HTTPS -> 80 HTTP overnight, its now working, and the admin->general entry to force SSL is responding too
