### ISSUE TITLE
Deleting database fails with foreign key violation between `report_card` and `card_label`

### ISSUE THREAD

**Issue by stig** [metabase/metabase#8492]
I'm trying to delete two obsolete databases from our installation. When hitting delete I get the below error just below the "Add database" button and above the table of available databases. We've archived all the questions we can find that reference these DBs, though the messaging on the modal DELETE dialogue implies this should not be necessary.

    ERROR: update or delete on table "report_card" violates foreign key constraint "fk_card_label_ref_card_id" on table "card_label" Detail: Key (id)=(79) is still referenced from table "card_label".

The full stack trace is here:

    Sep 10 17:41:03 ERROR metabase.middleware :: DELETE /api/database/4 500 (49 ms) (9 DB calls).
    {:message
     "ERROR: update or delete on table \"report_card\" violates foreign key constraint \"fk_card_label_ref_card_id\" on table \"card_label\"\n  Detail: Key (id)=(79) is still referenced from table \"card_label\".",
     :type org.postgresql.util.PSQLException,
     :stacktrace
     ["models.database$pre_delete.invokeStatic(database.clj:78)"
      "models.database$pre_delete.invoke(database.clj:76)"
      "api.database$fn__47282.invokeStatic(database.clj:484)"
      "api.database$fn__47282.invoke(database.clj:479)"
      "middleware$enforce_authentication$fn__55250.invoke(middleware.clj:116)"
      "api.routes$fn__55396.invokeStatic(routes.clj:64)"
      "api.routes$fn__55396.invoke(routes.clj:64)"
      "routes$fn__55477$fn__55478.doInvoke(routes.clj:108)"
      "routes$fn__55477.invokeStatic(routes.clj:103)"
      "routes$fn__55477.invoke(routes.clj:103)"
      "middleware$catch_api_exceptions$fn__55379.invoke(middleware.clj:424)"
      "middleware$log_api_call$fn__55356$fn__55358.invoke(middleware.clj:351)"
      "middleware$log_api_call$fn__55356.invoke(middleware.clj:350)"
      "middleware$add_security_headers$fn__55304.invoke(middleware.clj:253)"
      "core$wrap_streamed_json_response$fn__60666.invoke(core.clj:67)"
      "middleware$bind_current_user$fn__55255.invoke(middleware.clj:140)"
      "middleware$maybe_set_site_url$fn__55308.invoke(middleware.clj:277)"],
     :sql-exception-chain
     ["PSQLException:"
      "Message: ERROR: update or delete on table \"report_card\" violates foreign key constraint \"fk_card_label_ref_card_id\" on table \"card_label\""
      "Detail: Key (id)=(79) is still referenced from table \"card_label\"."
      "SQLState: 23503"
      "Error Code: 0"]}

| Metabase Version | 0.30.1                   |
| Database         | AWS RDS PostgreSQL 9.6.6 |

I tried to restart the installation, in case there was something cached, but it didn't make a difference. We've also retired a metric in the Data Model tab, in the hope that this would let us delete the DB, but no such luck.

Any help appreciated!

**Comment by senior** [comment]
I'm wondering if this is some vestigial data from an older version of the code as it looks like that table isn't referenced anymore.

@camsaul Do you have any back story on this? Seems like we maybe need to follow up with a migration to get rid of that old data?

**Comment by designandcopy** [comment]
@camsaul @senior If you've had a chance to look at this issue, could you point us in the right direction, please? :)

**Comment by stig** [comment]
Having done a bit more digging I think this commit might be the source of our problem: https://github.com/metabase/metabase/pull/7752/commits/c249269f83da9196be70e383e534ed38f681468e 

That commit removes API and models for updating `card_label` and `label` DB tables, but doesn't remove the underlying DB tables. Could you perhaps ship a migration that removes the `card_label` and `label` tables? That should fix our issue, I think. If that is too drastic, how about letting deletes cascade to the `card_label` table? There doesn't seem to be a reason not to remove entries there, since nothing appears to read it.

This is becoming more urgent for us, because we had to remove the underlying databases (despite us not being able to remove them from Metabase yet) and it's causing a lot of exceptions in the logs that causes Metabase to fill its disk and become unresponsive.

**Comment by anazapata** [comment]
Hi there, this is an issue for us right now, I was able to Delete one database we no longer use, just fine but we have another which we cannot delete and we get this same error, can someone please let me know how I can resolve this?

ERROR: update or delete on table "report_card" violates foreign key constraint "fk_card_label_ref_card_id" on table "card_label" Detail: Key (id)=(4) is still referenced from table "card_label".

**Comment by flamber** [comment]
Make a backup of your application database, then go and truncate the tables `label` and `card_label`

**Comment by anazapata** [comment]
> Make a backup of your application database, then go and truncate the tables `label` and `card_label`

can you please provide more details of where to go and what to run when you say "truncate the tables `label` and `card_label`" I have other database connections there, would those be affected by running this?

**Comment by flamber** [comment]
@anazapata 

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

Post "Diagnostic Info" from Admin > Troubleshooting.

The Metabase application database is what you configured, when you setup Metabase:
https://www.metabase.com/docs/latest/operations-guide/configuring-application-database.html

If you are using the same database for Metabase and other applications, then they might be polluting the same tables, which could be what you're seeing this problem. The Metabase application database should not share database with other applications.

**Comment by anazapata** [comment]
Below I am posting "Diagnostic Info", please let me know if you have any questions and how I can proceed with the Deletion of this Database Connection.
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.4.23-31.54.amzn1.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "mysql"
    ],
    "hosting-env": "elastic-beanstalk",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2020-01-13",
      "tag": "v0.34.1",
      "branch": "release-0.34.x",
      "hash": "265695c"
    },
    "settings": {
      "report-timezone": "US/Mountain"
    }
  }

**Comment by flamber** [comment]
@anazapata Go to the Postgres RDS that is configured as your application database and truncate the two tables there.
If you need further help, then use the forum.

**Comment by camsaul** [comment]
This was fixed in Metabase 0.36.0

**Comment by camsaul** [comment]
Fixed by #12946
