### ISSUE TITLE
Data Model page layout broke after upgrade to 0.30.2

### ISSUE THREAD

**Issue by edbizarro** [metabase/metabase#8494]
After upgrading to 0.30.2 all data model pages looks weird

![modelo de dados administrador metabase](https://user-images.githubusercontent.com/84926/45327776-475a7100-b52f-11e8-8287-7fe76e42cdd0.png)

---

- Your browser and the version: Chrome 69.0.3497.81
- Your operating system: Linux (Arch linux)
- Your databases: Postgres
- Metabase version: 0.30.2
- Metabase hosting environment: Docker on ubuntu 16.04
- Metabase internal database: H2 (default) i'm not sure

**Comment by mazameli** [comment]
I did not see this in Chrome 68, but I can now reproduce this immediately on Chrome 69.

Also seeing this in Firefox v62.

_Not_ seeing it in Safari v11.

**Comment by kdoh** [comment]
Did a fix for this in #8480 which is in master. We should try to add it to our next point release too.

**Comment by edbizarro** [comment]
Nice!

**Comment by edbizarro** [comment]
fixed in v0.30.3  :)
