### ISSUE TITLE
BigQuery connectivity issues after upgrading to v0.30

### ISSUE THREAD

**Issue by hden** [metabase/metabase#8495]
### Bugs

- Your browser and the version: Chrome 69.0.3497.81
- Your operating system: java:openjdk-8-jre-alpine
- Your databases: BigQuery
- Metabase version: v0.30.1, v0.30.2
- Metabase hosting environment: Docker
- Metabase internal database: MySQL (Google Cloud SQL)

Repeatable steps

1. Upgraded Metabase from v0.28 to v0.30.
1. Everything works for a while.
1. After ~24 hrs the new questions become irresponsive and the following errors appears within the log stream.

```
09-11 13:33:06 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__57161@2ed1af30: The job encountered an internal error during execution and was unable to complete successfully.
09-11 13:33:54 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__57369@1fd9f75e: The job encountered an internal error during execution and was unable to complete successfully.
09-11 13:35:03 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__57369@47266c30: The job encountered an internal error during execution and was unable to complete successfully.
09-11 13:35:53 WARN metabase.util :: auto-retry metabase.driver.google$execute$fn__57161@4a02c61f: The job encountered an internal error during execution and was unable to complete successfully.
```

**Comment by salsakran** [comment]
@hden is this still a problem?

**Comment by flamber** [comment]
Closing, since this has most likely been fixed by several connection handling changes in later versions.
Related to #4086
