### ISSUE TITLE
Missing field MongoDB query

### ISSUE THREAD

**Issue by pollyannagoncalves-hotmart** [metabase/metabase#8500]
Hi everyone, how are you?

I’m facing an issue on Metabase v0.30.1. I have a MongoDB query where I project a few fields, however one the these fields is inside a nested column, and not always exist. When I run the query this field does not come, even when there are some registers where this field is not null.

Anybody have any ideas what could fix it?

Thankss!

**Comment by priyankinfinnov** [comment]
+1

**Comment by flamber** [comment]
Duplicate of #4946 ?

**Comment by priyankinfinnov** [comment]
Yes.

**Comment by salsakran** [comment]
closing as a dupe
