### ISSUE TITLE
[Question] - View Records of Raw Queries

### ISSUE THREAD

**Issue by peterkrieg** [metabase/metabase#8502]
Metabase Version:  0.30.2

I've seen various posts about how to access raw queries run, but nothing definitive, or on the metabase docs.   We use metabase for our company and are looking to see data on which users are running what queries (among other things).

I've run the metabase database transition from h2 => postgres, and I see there is a `query_execution` table, which is perfect for what I'm looking for - includes the user, timestamp, etc.  It can join with the `query` table, but is there any way to see what the original query executed was?  As in, the raw SQL or whatever language involved in querying.

If this isn't possible to view in metabase database, is this something that can be configured through log4j config?

Thanks for any help!

**Comment by flamber** [comment]
Hi @peterkrieg 
It sounds like you're looking for audit logging, which is requested in #8234 - go and upvote :+1:

**Comment by peterkrieg** [comment]
@flamber  just upvoted that issue, thanks!

**Comment by flamber** [comment]
Closing, since [Audit Logging](https://www.metabase.com/docs/latest/enterprise-guide/audit.html) has been available in [Enterprise Edition](https://www.metabase.com/enterprise/) for a long time.
