### ISSUE TITLE
/api/user/current/ is giving response as Unauthenticated and is not logging into my metabase. Until yesterday it was all fine. Today its down and says password does not match with stored password. I am the only user and no administrator to contact

### ISSUE THREAD

**Issue by Siddarth434** [metabase/metabase#8508]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by jornh** [comment]
Please see if the workaround with clearing browser cookies proposed in
http://discourse.metabase.com/t/credentials-ok-but-cant-log-in/4352 gets you in again.

**Comment by camsaul** [comment]
Hi @Siddarth434, you have to be logged in for the API request to work. Sometimes the frontend app will call this endpoint to check whether you're logged in, which might be why you're seeing that. Are you experiencing any problems other than the failed API call?

**Comment by Siddarth434** [comment]
Yes i am trying to login and metabase throws that error. I am sure password is correct. I am facing only failed API call.

**Comment by Siddarth434** [comment]
Yes i am trying to login and metabase throws that error. I am sure password is correct. I am facing only failed API call.

**Comment by Siddarth434** [comment]
Restarted Server, cleared cookies. It worked. I guess its a bug.

**Comment by symantec-shailendersingh** [comment]
I am running Metabase in Openshift under POD. I have postgres container + metabase server and today i upgraded from 0.29.0 to 0.30.4 and i am not getting login page and in logs i can see same un authenticated error. Cookie clear did not fixed my issue and unable to see page.
Error:

09-28 12:09:40 DEBUG metabase.middleware :: GET /api/session/properties 200 (3 ms) (1 DB calls). Jetty threads: 8/50 (6 busy, 3 idle, 0 queued)
--

**Comment by Siddarth434** [comment]
@symantec-shailendersingh , office metabase latest version is 0.30.3

Better to downgrade your version and try again

**Comment by symantec-shailendersingh** [comment]
Tried with 30.3 but docker build is failing

$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning gitbook-plugin-atoc@1.0.3: The engine "gitbook" appears to be invalid.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error jest-localstorage-mock@2.2.0: The engine "node" is incompatible with this module. Expected version ">=6.11.3". Got "6.7.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1

**Comment by halitsever** [comment]
<p align="center"><br>
Same, i tried remove cookies, remove cloudflare cache and restarting docker stack multiple times, it didn't worked.
<br>
<br>

<img width="351" height="616" alt="Image" src="https://github.com/user-attachments/assets/88a07ade-e428-440b-a9e3-c47c68cd59b8" />

</p>

**Comment by halitsever** [comment]
**Update:**
Upgrading 0.45.2 to 0.46.6.2 worked for me, right now i can access again metabase.

**Comment by nmspackman** [comment]
Upgrading from 0.45.3 to 0.45.4.2 worked as well...don't know why auth failed to work previously though 🤷 

Thanks @halitsever for confirming!

**Comment by joy2323** [comment]
Ran metabase on docker and I can't login. How do I fix this @halitsever @nmspackman 

[
<img width="547" alt="metabase sigin error" src="https://github.com/metabase/metabase/assets/43809841/4385b0be-8075-4ca2-a64e-e80955be4194">
](url)

**Comment by nmspackman** [comment]
> Ran metabase on docker and I can't login. How do I fix this @halitsever @nmspackman
> 
> [ <img alt="metabase sigin error" width="547" src="https://user-images.githubusercontent.com/43809841/285188684-4385b0be-8075-4ca2-a64e-e80955be4194.png"> ](url)

I was able to resolve the issue by changing my version, but I knew our authentication worked previously. If you're sure your authentication is correct, you could try updating your docker file to use a different version of metabase (see versions above).

**Comment by rocketsciencenerd** [comment]
This looks like it was solved by a version bump but there are other reasons this could fail. I ran into this today when switching from a cloud hosted version of metabase to a self-hosted version. It isn't exactly the same issue as the original poster's question but it's the first hit on google so wanted to share in case it helps someone else. 

My setup is running the metabase-enterprise docker container behind an [AWS Cloudfront distribution](https://aws.amazon.com/cloudfront/). I am authenticating against the metabase self-hosted instance using a JWT token [as shown in this guide](https://www.metabase.com/docs/latest/people-and-groups/authenticating-with-jwt). 

After making sure that all your JWT settings are correct (you may want to set these using the [env vars](https://www.metabase.com/docs/latest/configuring-metabase/environment-variables) to keep deployments consistent). And also make sure you've verified your returned JWT token is correct (you can use [jwt.io](https://www.jwt.io/)). The last thing to check is that your SESSION cookie is being set correctly (browser network tab -> <your-app-domain-not-the-metabase-domain>/sso endpoint API request -> cookies tab). 

If you're not seeing a SESSION cookie that means your distribution may be blocking it. Be sure to check your Origin Request policy that it is set correctly and allowing this cookie to pass through. Without that SESSION cookie (there are also DEVICE and TIMEOUT cookies that will not authenticate you on their own) you will be "unauthenticated". You can check that the cookie is set properly using browser network tab -> application -> cookies. Also be sure to check your "issues" tab in the browser tools as there may be errors there as to why your cookie is not being set.

Hope that helps someone!
