### ISSUE TITLE
Nested queries should disambiguate their projections

### ISSUE THREAD

**Issue by senior** [metabase/metabase#8511]
While working on a fix for https://github.com/metabase/metabase/issues/8371 I wrote up a test with a nested query that included ambiguous names for fields (via remappings). On non-nested queries, we let the `clojure.java.jdbc` library handle ambiguity and it will give us a disambiguated column names. With nested queries it gets wrapped in a `select *`so `clojure.java.jdbc` doesn't see the abiguity. The database then handles the ambiguity, which will fail.

A test I originally wrote in `metabase.query-processor-test.remapping-test`
``` clojure
;; Will fail on H2 with an ambiguous column SQL exception from the DB backend
(data/with-data
    (data/create-venue-category-fk-remapping "Foo")
    (qp/process-query
           {:database (data/id)
            :type :query
            :query {:source-query {:source-table (data/id :venues)}
                    :order-by [[(data/id :venues :name) :ascending]]
                    :limit 5}}))
```

I'm betting this is broken on all backends but I only tested this on H2.

**Comment by senior** [comment]
Might be related to https://github.com/metabase/metabase/issues/8510

**Comment by sbelak** [comment]
This has been fixed in one of the nested queries fixes in the last few months.
