### ISSUE TITLE
Feature request: Show line graph pointer label on double click

### ISSUE THREAD

**Issue by NicoleSiapno** [metabase/metabase#8512]
When two points overlap on a multi series line chart it isn't possible to get the overlapped point label to appear. I know the info can be inferred on hover, but for the sake of UX are we able to show the labels of all points on double click (or via some other action)?

see for example: http://recordit.co/qS22NmJhH3

**Comment by jornh** [comment]
Related: https://github.com/metabase/metabase/issues/4263

@AnnSiapno you mentioned:

> show the labels of all points on double click (or **via some other action**)?

So maybe this should just be closed as a duplicate - and then you can add your 👍 vote on #4263
