### ISSUE TITLE
Embed dashboard url exceed length limit

### ISSUE THREAD

**Issue by duke2012** [metabase/metabase#8517]
Metabase Version: 0.30.2
I embed dashboard with locked param employee names in my own app, everything works fine at first. yet, when the params with over 100 emp_names, the return url exceed length limit which leads to errors and can not show report correctly. Does anyone meet same problem?

**Comment by flamber** [comment]
Hi @duke2012 
Similar to this issue in the forum: https://discourse.metabase.com/t/http-post-preference-from-ui/5419
What is returning the error, Metabase (Jetty) or a reverse proxy? Check the logs.

**Comment by flamber** [comment]
Closing, since I guess it was hitting the Jetty default 8192 request header limit, which can be configured with a environment variable from 0.36.0 - `MB_JETTY_REQUEST_HEADER_SIZE=8192`
Fixed by #12683
