### ISSUE TITLE
Filter values are shown on published dashboard

### ISSUE THREAD

**Issue by Tonkonozhenko** [metabase/metabase#8520]
All filter values are shown on the published dashboard. 

- Your databases: Redshift
- Metabase version: 0.30.2
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres

Screenshot:

![image](https://user-images.githubusercontent.com/1307646/45547026-02348880-b828-11e8-91a5-04dd409f6d66.png)

In datamodel I set "Filtering on this field" to "Plain input box". I'm pretty sure that it worked in 0.30.0

**Comment by timabdulla** [comment]
Somewhat divergently, I think this feature could help to prevent the exposure of private category data in the filter select list when the dashboard is embedded elsewhere for use by a user that should only have a limited scope of access to the dataset, and thus should not have access to a complete enumeration of all possible categories across the dataset. For instance, if your dashboard has a locked filter (e.g. Customer ID) and a category filter (e.g. Employee Department), the latter filter will give as options *all* Employee Departments for *all* Customers. What I would like is for the locked filter to restrict the options in the category filter to those that exist only in the filtered dataset.

Correct me if I'm wrong, but I believe that the only workaround here is to switch to a plain input box for the filter, which results in an inferior experience for the user of the dashboard.

**Comment by paulrosenzweig** [comment]
@Tonkonozhenko are you still seeing this? I'm unable to reproduce it on the current build.

If you do still see this, are you able to reproduce it on the sample dataset included with Metabase? Having reproduction steps on public data will make it easier for us to fix.

Another thought:
Do you have this filter connected to multiple different fields that have the same values? For example maybe two tables both have a "domain" column. If this happens, we merge the values, so you'd need to set both fields to "Plain input box" in the data model.

**Comment by Tonkonozhenko** [comment]
Hi @paulrosenzweig 

> Do you have this filter connected to multiple different fields that have the same values? For example maybe two tables both have a "domain" column. If this happens, we merge the values, so you'd need to set both fields to "Plain input box" in the data model.

Most likely it's because of this. Unfortunately, I'm not able to reproduce it anymore. We decided to switch to a self-developed solution.

**Comment by paulrosenzweig** [comment]
@Tonkonozhenko ah that makes sense. I'll close this assuming that was the cause. Though we should probably make this behavior more clear. Thanks!

**Comment by mazameli** [comment]
> We decided to switch to a self-developed solution.

Hey, @Tonkonozhenko. Can I ask if this bug was the reason you decided to move to a self-developed solution, or were there other primary reasons? Thanks in advance for any feedback you have.

**Comment by Tonkonozhenko** [comment]
@mazameli 
Our main use-case was the embeddable dashboard.

When we tried to setup metabase we faced several bugs. You can see that I created 9 issues at that time. For some of them, we found workarounds (e.g. we modified questions directly in DB or we created copies of your widgets, modified them and built metabase from source code), for some not.

The main reason was that we understand that we want a very customizable solution and using any of the existing BI-tools with embeddable dashboards will not work for us.

**Comment by mazameli** [comment]
@Tonkonozhenko Thanks for the feedback, Alex. I appreciate it. If I can ask one more question, was there a particular area of customizability in embeddable dashboards that you found especially lacking (for example, filter widgets), or was it just customizability across the board?

**Comment by Tonkonozhenko** [comment]
@mazameli 

In our product, we have users and each of them can have multiple domains.
We had a dashboard with userId parameter. One thing that was critical for us was showing only the user's domains in filter suggestion. 

One more thing was that we understood that it's very hard to customize widgets according to other UI and dashboard does not look native.

Also, I remember, there were some issues with setting up mapping for enums, but honestly I don't remember what exactly happened.
