### ISSUE TITLE
Table visualization: have to exclude columns one by one

### ISSUE THREAD

**Issue by danielerapati** [metabase/metabase#8523]
Before upgrading to 0.30.3 we were on 0.29.3.
When using a table visualization we were able to select only the columns we wanted, now we have to exclude them one by one.
This missing feature becomes particularly painful when using the "Custom Question" query builder on massive Redshift fact tables with 100+ columns. 
The SQL-less "Custom" query builder was getting a lot of traction with the non-technical users but now I fear a bit of a backlash.

- Browser: verified this on Chrome and Firefox 62
- OS: verified this on MacOs
- DB: verified this on Redshift
- Metabase version: 0.30.3
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: RDS Postgres

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by codenamesubho** [comment]
Yep facing the same, we have some transpose tables generated via ETL that has some 1500 columns , firstly this UI becomes too slow trying to display such a huge number of column, secondly if you need say 20-30 columns its a very painful exercise for non technical users using the custom UI to remove the columns one by one. Currently as a workaround we are running a sql query and saving the question for them but its alot of to and fro everytime they want to add some new columns. Would greatly help if this behaviour can be changed. Thanks!

**Comment by flamber** [comment]
Closing in favor of #3266 - related to #10460
