### ISSUE TITLE
Dashboard or question migration 

### ISSUE THREAD

**Issue by Siddarth434** [metabase/metabase#8529]
Hi

I want a way to migrate all dashboard or question from one instance to other. I use H2 database.

We first work on local environment, once Tested we move it to production which is a different instance. Please let me know a easy way of migration.

**Comment by jornh** [comment]
Duplicate of https://github.com/metabase/metabase/issues/6485

**Comment by salsakran** [comment]
we're working on this in #8845

**Comment by flamber** [comment]
Closing in favor of #6485. The [Enterprise Edition](https://www.metabase.com/enterprise/) has [Serialization](https://www.metabase.com/docs/latest/enterprise-guide/serialization.html), which can do a lot of migration.
