### ISSUE TITLE
Multi series line chart not working using native query

### ISSUE THREAD

**Issue by KarthiAru** [metabase/metabase#8533]
I'm using Metabase version: v0.30.2.

I'm getting a warning that the date field isn't aggregated and that values will be summed. I'm expecting five line series, but I get just one.

<img width="1277" alt="screen shot 2018-09-17 at 10 42 05 pm" src="https://user-images.githubusercontent.com/8588253/45638500-fcaa9d00-baca-11e8-829a-edb9cb713719.png">

Query:
`SELECT CAST(event_time AS date) AS "event_time", version_name, count(distinct user_id) AS "count"
FROM amplitudelogs
WHERE event_type LIKE '%app_login%'
OR event_type LIKE '%app_launch%'
AND (CAST(event_time AS date) BETWEEN CAST({{start_date}} AS date) AND CAST({{end_date}} AS date))
GROUP BY CAST(event_time AS date), version_name`

However this seems to be working fine with the query builder.

<img width="1274" alt="screen shot 2018-09-17 at 10 25 20 pm" src="https://user-images.githubusercontent.com/8588253/45637838-13e88b00-bac9-11e8-97d9-3c9831e0fc23.png">

Is this because the results of my query isn't a pivot table?

**Comment by tlrobinson** [comment]
@KarthiAru Did you try going into the chart settings (the gear icon) and seeing if you could click "Add a series breakout..." to add the second breakout column?

**Comment by KarthiAru** [comment]
@tlrobinson I ran the same query again after a browser refresh and it worked. Not sure what changed.

<img width="1276" alt="screen shot 2018-09-17 at 11 05 35 pm" src="https://user-images.githubusercontent.com/8588253/45639692-48127a80-bace-11e8-8789-eeba56d695ee.png">
