### ISSUE TITLE
v0.30.3 inconsistent tagging

### ISSUE THREAD

**Issue by sturgill** [metabase/metabase#8534]
All other versions of Metabase are tagged with the `v` prefix (e.g., `v0.30.0`). This recent version was tagged as `0.30.3` (instead of `v0.30.3`). This broke our automated update script as the tag name found [here](https://api.github.com/repos/metabase/metabase/releases/latest) did not match the download URL.

**Comment by tlrobinson** [comment]
@sturgill It looks like we do have both git and docker tags for `v0.30.3`. There was also a tag called `0.30.2` but it wasn't the correct commit, so I've deleted it.

**Comment by tlrobinson** [comment]
@sturgill Ok I see now, the GitHub release was using the `0.30.3` tag. I've updated it to `v0.30.3`
