### ISSUE TITLE
Notification about archived Question does not show which one is

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#8535]
### Notification about archived Question does not show which one is

- Your browser and the version: Chrome 69.0.3497.81
- Your operating system: Ubuntu 18.04 TLS
- Your databases: MySQL, Postgres, MongoDB, and SQL Server
- Metabase version: v0.29.3 (We are planning to migrate to v0.30.3 this next weekend, cuz we have to spend a time to create a training on Collection 2.0)
- Metabase hosting environment: Debian 9 / Nginx Proxy SSL
- Metabase internal database: Postgres

When someone archives a question that has a Pulses attached on it, the e-mail notification does not show which on it is, look above:
![screenshot from 2018-09-17 15-06-39](https://user-images.githubusercontent.com/6808348/45641603-4d4ed580-ba8c-11e8-8de4-cbd5bf1d0917.png)

How do you think about including a link to the question, or name, or Id?

**Comment by flamber** [comment]
Coming in 0.42: #19814
