### ISSUE TITLE
Metabase is not using the BigQuery cache by question

### ISSUE THREAD

**Issue by bern4rdelli** [metabase/metabase#8539]
The Metabase is not using the BigQuery cache by question, instead, it is used by the user / question.

BigQuery generates a hash for each SQL (including the comments), when Metabase injects the user id in a query, the hash changes and the BigQuery caches the SQL result per user/question.

This increases the expenses a lot, especially for the companies that have many active users.

[SQL user id injection](https://github.com/metabase/metabase/blob/master/src/metabase/driver/bigquery.clj#L539)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by hellupline** [comment]
I agree it increases cost, but It helped me to mitigate some problems with our queries

I dont mind removing it tho,

**Comment by bern4rdelli** [comment]
@hellupline Could you share how do you mitigate problems using the `user id`? For me the `question id` is more interesting than the `user id`. With the `question id` you can easily go to the question and mitigate the problem.

We have ~250 active users,  and the cost can increase ~250 times with this comment.

Tks :)

**Comment by hellupline** [comment]
@bern4rdelli I was able to inspect who was doing some weird queries ( not saved )

**Comment by hellupline** [comment]
@bern4rdelli but I do agree with you, it can turn bigquery into something really expensive for no reason

**Comment by camsaul** [comment]
Fixed by #9275 and #13923
