### ISSUE TITLE
Is there a way to disable ""Too many attempts! You must wait %d seconds before trying again." ?

### ISSUE THREAD

**Issue by robertobitbond** [metabase/metabase#8548]
I am trying to find a way to solve this annoying limitation, since we run several queries in short time, this block affects our productivity.
Thanks in advance.

**Comment by alantygel** [comment]
hi @robertobitbond 

Are you trying to authenticate repeatedly? Could you please specify which situation is causing this message to show?

**Comment by robertobitbond** [comment]
Ehy @alantygel 

I create an an API endpoint which serves several small programmes.

This API endpoint is able to connect with Metabase API, it extracts data and it returns them. 
It takes three parameters: _query_id_, _query_parameters_, _session_id_. 
If _session_id_ is null, the endpoint creates a new session_id.

The programmes that call this endpoint are not connected to each other, and they are triggered or every few minutes, or based on some external events.
If the interval between a call and the next one is too short, I receive the error message.

Is it something I could solve managing session_id differently?

**Comment by alantygel** [comment]
Hi @robertobitbond ,

I have the same issue. In my case, it is only one website accessing the API. After the first access, session_id is kept as a cookie. However, if several users access it simultaneously , the message arrives.

In my case the solution would be simple: I'm using `/api/card/card_id/query/json ` for a public question, so theoretically it wouldn't need an authentication at all.

**Comment by jornh** [comment]
Resolved by https://github.com/metabase/metabase/pull/8574 (it seems)

**Comment by mbvictoria** [comment]
Closed - last comment says resolved.
