### ISSUE TITLE
Add file verification for JAR download

### ISSUE THREAD

**Issue by booth23** [metabase/metabase#8555]
Would it be possible to use a GPG signature or a checksum so we can verify the Metabase JAR file? I looked on the website and in the issues and haven't seen anything related to file verification.

**Comment by tlrobinson** [comment]
@booth23 We should document this better, but we do sign the released jars. Here's how to verify it:

https://github.com/metabase/metabase/issues/3993#issuecomment-269018716

**Comment by flamber** [comment]
This seems to be fixed by #9639, which will now have SHA1 checksum on Github release note and tweet.
I'm not sure if we should add a note to the second paragraph of the [documentation](https://www.metabase.com/docs/latest/operations-guide/running-the-metabase-jar-file.html) before closing this?

**Comment by camsaul** [comment]
#9693 isn't a PR but we'll be sure to include checksums in the future. I think going forward we'll do SHA-256 checksums

**Comment by camsaul** [comment]
I will add this to our build script. Consider this fixed going forward
