### ISSUE TITLE
Metabase dashboard keeps loading|NSURLConnection finished with error - code -1003

### ISSUE THREAD

**Issue by predator44** [metabase/metabase#8557]
i have just downloaded the application on mac and it keeps loading without any result 
i am connected over the internet without any problem below are some details :

- browser and the version: (Chrome Version 69.0.3497.100 (Official Build) (64-bit))
- operating system: (Mac High Sierra OS 10.13.6 (17G65))
- databases: ( MySQL)
- Metabase version: (Latest 'v0.30.3 (Latest))
- Metabase hosting environment: (Mac app)
- Metabase internal database: (MySQL)

**Below is the console filtered to the Metabase** 
default	20:08:52.248542 +0300	Metabase	😷
default	20:08:52.758845 +0300	Metabase	TIC TCP Conn Start [239:0x60c00017cbc0]
default	20:08:52.758968 +0300	Metabase	Task <C79C9A61-A99F-40C2-B64A-9C0396E6409E>.<0> setting up Connection 239
default	20:08:52.758995 +0300	Metabase	[239 <private> <private>] start
default	20:08:52.762291 +0300	Metabase	TIC TCP Conn Event [239:0x60c00017cbc0]: 3
error	20:08:52.762333 +0300	Metabase	TIC TCP Conn Failed [239:0x60c00017cbc0]: 12:8 Err(-65554)
default	20:08:52.762433 +0300	Metabase	TIC TCP Conn Cancel [239:0x60c00017cbc0]
default	20:08:52.762767 +0300	Metabase	[239 <private> stream, pid: 307, url: http://localhost:13126/api/health] cancelled. Events:
default	20:08:52.762862 +0300	Metabase	0.000s [239 A558431F-9AFA-455F-B8E6-E4F704810BD2 <private> resolver] path:start
default	20:08:52.762934 +0300	Metabase	0.000s [239 A558431F-9AFA-455F-B8E6-E4F704810BD2 <private> resolver] path:satisfied
default	20:08:52.763077 +0300	Metabase	0.000s [239 A558431F-9AFA-455F-B8E6-E4F704810BD2 <private> resolver] resolver:start_dns
default	20:08:52.763146 +0300	Metabase	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
default	20:08:52.763228 +0300	Metabase	0.002s [239 A558431F-9AFA-455F-B8E6-E4F704810BD2 <private> resolver] path:trigger
error	20:08:52.763304 +0300	Metabase	Task <C79C9A61-A99F-40C2-B64A-9C0396E6409E>.<0> HTTP load failed (error code: -1003 [12:8])
default	20:08:52.763401 +0300	Metabase	0.003s [239 A558431F-9AFA-455F-B8E6-E4F704810BD2 <private> resolver] resolver:receive_dns Error Domain=kNWErrorDomainDNS Code=-65554 "DNS failed due to NoSuchRecord" UserInfo={NSDescription=DNS failed due to NoSuchRecord}
default	20:08:52.763533 +0300	Metabase	0.003s [239] path:cancel
error	20:08:52.763889 +0300	Metabase	NSURLConnection finished with error - code -1003
default	20:08:52.764047 +0300	Metabase	😷
default	20:08:53.887985 +0300	Metabase	TIC TCP Conn Start [240:0x60c00017aa00]
default	20:08:53.888153 +0300	Metabase	Task <CC5034CC-ECA2-4150-866A-D8E5BED52581>.<0> setting up Connection 240
default	20:08:53.888187 +0300	Metabase	[240 <private> <private>] start
default	20:08:53.892115 +0300	Metabase	TIC TCP Conn Event [240:0x60c00017aa00]: 3
error	20:08:53.892250 +0300	Metabase	TIC TCP Conn Failed [240:0x60c00017aa00]: 12:8 Err(-65554)
default	20:08:53.892365 +0300	Metabase	TIC TCP Conn Cancel [240:0x60c00017aa00]
default	20:08:53.892819 +0300	Metabase	[240 <private> stream, pid: 307, url: http://localhost:13126/api/health] cancelled. Events:
default	20:08:53.892890 +0300	Metabase	0.000s [240 9432EE3F-1CFF-4264-AF95-F776E5719180 <private> resolver] path:start
default	20:08:53.892974 +0300	Metabase	0.000s [240 9432EE3F-1CFF-4264-AF95-F776E5719180 <private> resolver] path:satisfied
default	20:08:53.893098 +0300	Metabase	0.000s [240 9432EE3F-1CFF-4264-AF95-F776E5719180 <private> resolver] resolver:start_dns
default	20:08:53.893176 +0300	Metabase	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
default	20:08:53.893235 +0300	Metabase	0.003s [240 9432EE3F-1CFF-4264-AF95-F776E5719180 <private> resolver] path:trigger
error	20:08:53.893318 +0300	Metabase	Task <CC5034CC-ECA2-4150-866A-D8E5BED52581>.<0> HTTP load failed (error code: -1003 [12:8])
default	20:08:53.893387 +0300	Metabase	0.003s [240 9432EE3F-1CFF-4264-AF95-F776E5719180 <private> resolver] resolver:receive_dns Error Domain=kNWErrorDomainDNS Code=-65554 "DNS failed due to NoSuchRecord" UserInfo={NSDescription=DNS failed due to NoSuchRecord}
default	20:08:53.893490 +0300	Metabase	0.004s [240] path:cancel
error	20:08:53.893821 +0300	Metabase	NSURLConnection finished with error - code -1003
default	20:08:53.894049 +0300	Metabase	😷

**Comment by predator44** [comment]
@camsaul  @kdoh  @senior @tlrobinson 
appreciate your help on this as its just the start and i am stuck !

thanks

**Comment by predator44** [comment]
any feedback ?

**Comment by flamber** [comment]
Closing, since we are deprecating the Mac App: https://www.metabase.com/blog/Metabase-0.41/#other-news-at-metabase
