### ISSUE TITLE
Searches should show the collection a Dashboard / Question / Pulse / Collection belongs to

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8559]
The search results screen should show the collection each result belongs to. This is needed to be able to differentiate between items if they have the same name but belong to different collections. Showing the creator may also be helpful.

**Comment by mazameli** [comment]
Closing as this has been implemented for everything except for sub-collections.

![image](https://user-images.githubusercontent.com/2223916/73390961-f5cd9600-428b-11ea-9c78-34989d18f97c.png)

![image](https://user-images.githubusercontent.com/2223916/73391021-11d13780-428c-11ea-8e84-597d1748a633.png)
