### ISSUE TITLE
Metabase LDAP Authentication login problem after removal

### ISSUE THREAD

**Issue by an33shk4tl4** [metabase/metabase#8566]
Metabase version  v0.29.0

1. Enabled LDAP Authentication
2. Restarted metabase application
3. New User (**U1**) signed up on metabase instance using LDAP 
4. **U1** successfully logged in and added to default group
5. Admin logged in 
6. Removed U1 (LDAP auth) 
7. Asked **U1** to log in again using LDAP credentials.
8. **U1**  unable to log in

**Comment by MarkRx** [comment]
Is this the same as #7571?

**Comment by flamber** [comment]
Closing in favor of #7571
