### ISSUE TITLE
datetime SQL parameters big [MySQL]

### ISSUE THREAD

**Issue by Dog-Lee** [metabase/metabase#8567]
```
select count(*) from user where DATE_FORMAT(reg_time, '%Y-%m-%d') = '2018-09-07'
```
in mysql client, the correct result is 70. but i got the different result.

<img width="796" alt="wx20180921-122141 2x" src="https://user-images.githubusercontent.com/20838671/45860403-94dda600-bd99-11e8-999b-8befd44ace4b.png">

<img width="1650" alt="wx20180921-122841 2x" src="https://user-images.githubusercontent.com/20838671/45860464-ed14a800-bd99-11e8-8b8e-f5f68f5deb42.png">

the first result is correct, the second is wrong. they have the same date September 7, 2018

**Comment by salsakran** [comment]
ugh. What are your timezones? Can you share the information we go over in https://metabase.com/docs/latest/troubleshooting-guide/timezones.html?
