### ISSUE TITLE
Parse server's mongodb _User collection '_id' of each document are treated as fields

### ISSUE THREAD

**Issue by sunshineo** [metabase/metabase#8573]
Parse is a popular application stack with features like REST, push notifications, etc https://parseplatform.org/
Our parse system's backend is MongoDB v3.6.6
Parse itself creates a mongodb collection called '_User' with a generated _id . It looks like this:
![_user](https://user-images.githubusercontent.com/1072766/45924398-26413b00-beb4-11e8-84b5-b7e66af6aa8e.jpg)
I started metabase using the latest docker image v0.30.3
```
docker run -d -p 3000:3000 --name metabase metabase/metabase
```
I give metabase the mongodb and most things works great except the _User collection
The _id of every user is treated as fields when I inspect in the data model tab
![user-schema](https://user-images.githubusercontent.com/1072766/45924416-73bda800-beb4-11e8-92b4-8ebc3ce3a3e1.jpg)

Might be some edge case or something special about that collection
Thanks in advance

**Comment by ozgurozkan123** [comment]
Hi there,
We have the same problem as well. I realized that it's because acl json object field. Under acl each parse user has it's id again :) I searched if I can omit specifically json objects but I couldn't find neither.

**Comment by camsaul** [comment]
You can change the visibility if you do not want to see the Field

**Comment by ozgurozkan123** [comment]
We have 10.000 columns because of 10.000 different users. Metabase doesn't respond. It's impossible to delete them one by one. I think I will try to migrate to postgres and edit db records to solve it.

**Comment by ozgurozkan123** [comment]
I migrated to postgres and edited specified columns’ active field to false

**Comment by sunshineo** [comment]
@ozgurozkan123 Thank you for the workaround

@camsaul Any way to prevent this from happening under Mongo DB?

**Comment by flamber** [comment]
Closing in favor of #3174/#5191
