### ISSUE TITLE
prevent flex based layouts from squishing past sm breakpoint

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#858]
right now at certain breakpoints content can squish to the point where it is unusable.

**Comment by agilliland** [comment]
@kdoh where are we at on this one?  can we commit to fixing this one?

**Comment by kdoh** [comment]
@agilliland I think what might make sense is since this is such a general issue based on our over use of flex box without certain layout constraints we should close it and instead document and open issues for specific places where we encounter it so we can start to make progress. from my looking at it previously it doesn't seem like there's an elegant one off fix.

**Comment by agilliland** [comment]
yeah, i think that makes more sense, this really isn't actionable in its current form.  i'm going to close this then and we'll file separate issues for the specific places we want to address this.
