### ISSUE TITLE
please compress the js file

### ISSUE THREAD

**Issue by Dog-Lee** [metabase/metabase#8580]
the largest js file is vendor.bundle.js(1.7M) and app-main.bundle.js(900k). these file take a lot time for download in the small network VPS.

i think it will be better to compress it, or use http cache. i saw `Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate` from chrome dev tool, it mean every time we refresh the page need download these js file again.

**Comment by jornh** [comment]
Duplicate of https://github.com/metabase/metabase/issues/8327

**Comment by tlrobinson** [comment]
Closing as a duplicate of #8327
