### ISSUE TITLE
database deletion and translations

### ISSUE THREAD

**Issue by orthagh** [metabase/metabase#8588]
- Your browser and the version: Firefox 60 ESR
- Your operating system: Win 7
- Your databases: Mysql
- Metabase version: 0.30.3
- Metabase hosting environment: Linux/Centos6.7
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue: 

I'm using french translation.
When deleting a database in administration, we got a message asking to confirm deletion.
The word DELETE needed to confirm is translated in french as SUPPRIMER.

![image](https://user-images.githubusercontent.com/418844/46065864-2ae34900-c16b-11e8-9d87-8fb19c3e4ab8.png)

I'm not sure it's a translation issue (and be managed on poeditor), i think the string DELETE should be passed as '%s' in gettext string.

Regards

**Comment by orthagh** [comment]
Hum, i didn't find any report previously but in fact duplicate #8372
Sorry.

**Comment by orthagh** [comment]
Just tested with **0.30.4**, still the same error.
The red button stays fadded:

![image](https://user-images.githubusercontent.com/418844/46067578-14d78780-c16f-11e8-82fe-192464e5c12c.png)

**Comment by ChrisADR** [comment]
Same here, es translation does not enable the Delete button.

**Comment by salsakran** [comment]
closing this in favor of the original issue
