### ISSUE TITLE
Hiding a column that was previously used in questions results in errors

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#8592]
Steps to reproduce:
1. Create a question filtering on a field from a table
2. Hide said field in the UI ("do not include")
3. Rerun the question and get an error

At the very least a more user friendly error could be given. Alternatively the old questions could continue to function while new questions would not be allowed to use the field.

> No implementation of method: :parse-value of protocol: #'metabase.query-processor.middleware.resolve/IParseValueForField found for class: metabase.query_processor.interface.FieldPlaceholder

> 09-26 10:42:23 WARN metabase.query-processor :: {:status :failed,
>  :class java.lang.IllegalArgumentException,
>  :error
>  "No implementation of method: :parse-value of protocol: #'metabase.query-processor.middleware.resolve/IParseValueForField found for class: metabase.query_processor.interface.FieldPlaceholder",
>  :stacktrace
>  ["query_processor.middleware.resolve$fn__32353$G__32348__32360.invoke(resolve.clj:218)"
>   "query_processor.middleware.resolve$value_ph_resolve_field.invokeStatic(resolve.clj:272)"
>   "query_processor.middleware.resolve$value_ph_resolve_field.invoke(resolve.clj:266)"
>   "query_processor.middleware.resolve$fn__32259$G__32241__32266.invoke(resolve.clj:83)"
>   "util$rpartial$fn__12941.doInvoke(util.clj:172)"
>   "query_processor.middleware.resolve$resolve_fields.invokeStatic(resolve.clj:338)"
>   "query_processor.middleware.resolve$resolve_fields.invoke(resolve.clj:321)"
>   "query_processor.middleware.resolve$resolve.invokeStatic(resolve.clj:478)"
>   "query_processor.middleware.resolve$resolve.invoke(resolve.clj:475)"
>   "query_processor.middleware.resolve$resolve_middleware$fn__32471.invoke(resolve.clj:490)"
>   "query_processor.middleware.expand$expand_middleware$fn__31795.invoke(expand.clj:613)"
>   "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__32660.invoke(add_row_count_and_status.clj:15)"
>   "query_processor.middleware.driver_specific$process_query_in_context$fn__33308.invoke(driver_specific.clj:12)"
>   "query_processor.middleware.resolve_driver$resolve_driver$fn__35602.invoke(resolve_driver.clj:15)"
>   "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32994$fn__32995.invoke(bind_effective_timezone.clj:9)"
>   "util.date$call_with_effective_timezone.invokeStatic(date.clj:82)"
>   "util.date$call_with_effective_timezone.invoke(date.clj:71)"
>   "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32994.invoke(bind_effective_timezone.clj:8)"
>   "query_processor.middleware.cache$maybe_return_cached_results$fn__33169.invoke(cache.clj:149)"
>   "query_processor.middleware.catch_exceptions$catch_exceptions$fn__33219.invoke(catch_exceptions.clj:58)"
>   "query_processor$process_query.invokeStatic(query_processor.clj:135)"
>   "query_processor$process_query.invoke(query_processor.clj:131)"
>   "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:249)"
>   "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:243)"
>   "query_processor$fn__37100$process_query_and_save_execution_BANG___37105$fn__37106.invoke(query_processor.clj:289)"
>   "query_processor$fn__37100$process_query_and_save_execution_BANG___37105.invoke(query_processor.clj:275)"
>   "api.card$run_query_for_card.invokeStatic(card.clj:582)"
>   "api.card$run_query_for_card.doInvoke(card.clj:568)"
>   "api.card$fn__41732$fn__41735.invoke(card.clj:589)"
>   "api.card$fn__41732.invokeStatic(card.clj:588)"
>   "api.card$fn__41732.invoke(card.clj:584)"
>   "middleware$enforce_authentication$fn__54761.invoke(middleware.clj:107)"
>   "api.routes$fn__54905.invokeStatic(routes.clj:61)"
>   "api.routes$fn__54905.invoke(routes.clj:61)"
>   "routes$fn__55705$fn__55706.doInvoke(routes.clj:108)"
>   "routes$fn__55705.invokeStatic(routes.clj:103)"
>   "routes$fn__55705.invoke(routes.clj:103)"
>   "middleware$catch_api_exceptions$fn__54894.invoke(middleware.clj:422)"
>   "middleware$log_api_call$fn__54872$fn__54874.invoke(middleware.clj:350)"
>   "middleware$log_api_call$fn__54872.invoke(middleware.clj:349)"
>   "middleware$add_security_headers$fn__54814.invoke(middleware.clj:239)"
>   "core$wrap_streamed_json_response$fn__56558.invoke(core.clj:67)"
>   "middleware$bind_current_user$fn__54766.invoke(middleware.clj:131)"
>   "middleware$maybe_set_site_url$fn__54824.invoke(middleware.clj:276)"
>   "middleware$add_content_type$fn__54817.invoke(middleware.clj:248)"],
>  :query
>  {:type "query",
>   :query
>   {:source_table 28,
>    :breakout [["field-id" 293]],
>    :aggregation [["count"]],
>    :filter
>    ["AND"
>     ["=" ["field-id" 281] "HRO"]
>     ["time-interval" ["field-id" 282] -7 "day" {:include-current false}]
>     ["CONTAINS" ["field-id" 273] "Events_Regression" {:case-sensitive false}]
>     ["DOES_NOT_CONTAIN" ["field-id" 269] "Sandbox" {:case-sensitive false}]]},
>   :constraints {:max-results 10000, :max-results-bare-rows 2000},
>   :parameters [],
>   :middleware nil,
>   :cache_ttl nil,
>   :info
>   {:executed-by 69,
>    :context :question,
>    :card-id 232,
>    :dashboard-id nil,
>    :query-hash [109, -106, 102, -13, -6, -120, -42, 76, -72, 10, 23, 46, -75, 76, -18, -127, 64, -109, 67, -52, 63, 111, -104, -9, -44, -32, 55, -123, -90, -34, -119, 15],
>    :query-type "MBQL"}},
>  :expanded-query nil}

Your browser and the version: 69.0.3497.100 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.30.3
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by mbvictoria** [comment]
Closing - this issue no longer appears in recent versions.
