### ISSUE TITLE
Update BigQuery Driver to respect regions

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#8605]
BigQuery has added the notion of regions

https://cloud.google.com/bigquery/docs/dataset-locations

Jobs.cancel, jobs.get, jobs.getQueryResults require a location parameter for all regions except
for US and EU.

There is auto-detection, but if we don't add support for locations we'll stop working with BigQuery in the Tokyo region or new regions as they get added.

**Comment by camsaul** [comment]
Luckily we're not using any of these API methods

**Comment by salsakran** [comment]
Awesome.

@sb are you using anything that this impacts in the ML side of things?

**Comment by flamber** [comment]
This was fixed in 0.37.0.2
