### ISSUE TITLE
Dashboard  Filters fail on cards with a foreign key referencing another table

### ISSUE THREAD

**Issue by joebi3** [metabase/metabase#8608]
- Your browser and the version:Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Your operating system :Windows 10 
- Your databases:  MySQL
- Metabase version: v0.30.3
- Metabase hosting environment: jar on ubuntu 16.04 LTS
- Metabase internal database :MySQL

- *Repeatable steps to reproduce the issue*

1.have a question built from two tables linked with a foreign key. 
2.Display this question on a dashboard and add a date filter on the first table. 
3.Filter the question on any date range. 

The question displays correctly when filtering using a between filter inside the question itself, it also displays correctly when no filter is applied on the dashboard, however, if you apply a date filter on the dashboard you get an error. 

Drilling down into the question whilst in error state gives the following error message:

Query expansion failed: could not find table 80 (FK ID = null). Resolved tables ([fk-id table-id]): ([nil 108])

This does not occur on questions without a foreign key in the table but removing the foreign key from the table within Metabase does not resolve this.

**Comment by joebi3** [comment]
Okay I'm a bit of an idiot.

If you change the table that your question was using after it has been added to a dashboard with a filter, you have to re-add the filter to the question, otherwise metabase is still looking for the old table when it tries to filter the card.

Might be worth adding some logic to disassociate cards from filters if the source table of the question is changed.

**Comment by flamber** [comment]
Closing in favor of #8055
