### ISSUE TITLE
French Guiana labelled as France in Map figures

### ISSUE THREAD

**Issue by nathan-fps** [metabase/metabase#8609]
French Guiana seems to get labelled with the name and value of data from France in map figures.

![maps-france](https://user-images.githubusercontent.com/35743870/46302474-036ef080-c55e-11e8-97f6-3ad008a1a2dd.gif)

Browser: Firefox 62
OS: Fedora Linux 28
Metabase: 0.30.3
Hosting: Docker / Kubernetes
Internal Database: H2
Data Source: BigQuery

**Comment by nathan-fps** [comment]
More info:

Data is labelled with ISO-3166 country codes. While French Guiana is part of France, it as a separate country code (GF) so I expected it to have its own label and value show up.

**Comment by vvaezian** [comment]
To reproduce:
- Create a native question:
```select 'FR', 1```
- Choose Visualzation -> Map

![fr](https://user-images.githubusercontent.com/15974735/69287300-97f54180-0baa-11ea-8c6c-913ff9512613.png)
