### ISSUE TITLE
[Feature] Search by card id at global search

### ISSUE THREAD

**Issue by dannyeuu** [metabase/metabase#8610]
### Search by card_id 
Will be really good if the global search can search over IDs too, like a dashboard Id or a Question Id.

**Comment by tlrobinson** [comment]
@dannyeuu If you know the question/dashboard ID can't you just go directly to `/question/:id` or `/dashboard/:id`?

**Comment by kdoh** [comment]
I;m going to close this issue to reflect the fact we're not likely to support this in search.  In general we try to prioritize search features that are accessible and useful to the largest number of Metabase users and this seems like too specific a use case.
