### ISSUE TITLE
Make absolute-max-results configurable (large dataset support)

### ISSUE THREAD

**Issue by lukegalea** [metabase/metabase#8622]
In some cases, we want to use metabase for large (>10 million rows) queries. 

We ([precision nutrition](https://www.precisionnutrition.com)) would love to fund development of a feature to better support these queries.

Our current solution is to add a LIMIT to the query and save it in metabase. If a user needs the full response, they have to ask us to manually run it in a tool that can handle exporting a large csv. 

The proposed feature is:

* Automatically limit result sets
      In admin, allow "maximum rows" to be set so that a query that accidentally returns too many rows doesn't crash the server (which it definitely does now). Perhaps this should default to 10,000 rows because that's all the UX will display currently?

* When there are more rows than "maximum rows", the UX should reflect that it's a subset of the complete result

* When a subset of the result is being displayed, the export to csv/xls, etc feature should include the full, non-limited result set

**Comment by MarkRx** [comment]
Similar to #8322

**Comment by MarkRx** [comment]
I plan to investigate this. I'm not sure what the UX should look like though for questions builders (SQL and UI) as well as cards on a dashboard to indicate there are more records. Here is a thought:

- For cards on dashboards it could show a + at the end of the number if there are more. For example "Rows 1-10 of 2000+"
- For the SQL/UI builders the text could be changed to "Showing rows 1-X of MAX+" where X can be an overridden limit in the case of the UI query builder (click ... row limit)

**Comment by lindsay-stevens** [comment]
@lukegalea I think this could be helped using the existing [SQL template feature](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html), e.g. (for Postgres)

```sql
SELECT * FROM "mytable" ORDER BY "mytable"."pk" LIMIT {{limit}} OFFSET {{offset}}
```

Where you configure a SQL template variables `limit` and `offset` to both be a Number, which is Required, and has a default of whatever it needs to be i.e. limit=10000 and offset=0. Then the user can change these parameters themselves, but by default it wouldn't destroy your database performance. And if the table is too big to get all at once, then they can adjust the offset to paginate.

If downloading or transferring huge amounts of data, going via Metabase is going to get slow after a few million rows anyway - I tried this once with some ultra-sized `generate_series` queries and it seems that serialisation becomes a bottleneck eventually, even if the query execution is reasonably quick. In that case (for postgres), a server-side `COPY` would be much faster.

**Comment by mazameli** [comment]
Was this resolved via https://github.com/metabase/metabase/issues/35428, @luizarakaki ?

**Comment by luizarakaki** [comment]
Yes!
