### ISSUE TITLE
Adding a second grouping to a saved question should automatically break out the series

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8623]
Previously if you had a saved question with a single series and a single grouping, and then you added a second grouping, the chart would automatically break out into multiple series. Currently on stats, that doesn't happen; you have to manually add the breakout, which sucks. @tlrobinson believes this has to do with a change we made in 0.30 to persist visible columns (at least I think that's what he said 😬 ).

![2nd-dimension-should-break-out](https://user-images.githubusercontent.com/2223916/46432140-584b6c00-c702-11e8-9293-72ae15d469c9.gif)

**Comment by tlrobinson** [comment]
I suspect but have not confirmed it goes back much further than v0.30: https://github.com/metabase/metabase/commit/8dc9e6938a3ed3816e75a464b667514dc183a96b

**Comment by brunobergher** [comment]
Can't repro.
