### ISSUE TITLE
API output of large data set (full data download) is missing rows

### ISSUE THREAD

**Issue by apinstein** [metabase/metabase#8625]
I have a question that returns a large data set. 13 columns x 1.3M rows. Simple query...

`select * from foo`

If I run `select count(*) from foo` I get 1335526.

If I use the "download" feature of the web app, or use the HTTP API (which is used by my `metabaser` project), I only get 1048579 rows.

I verified the correct row count by doing an export from the db console directly and confirmed that 1335526 rows are exported. 

This is on metabase version  0.30.3 running on docker.
This is a question that hits a postgres server.

I haven't had time to try to create a reproducible test case yet (faking a large data set). I am hopeful this rings a bell for someone.

**Comment by salsakran** [comment]
We cap the number of rows returned to keep large queries from killing the server with an OutOfMemory error.

We strongly suggest not using Metabase for really large downloads if you can. We're not optimized for moving large tables around. If you need to, you can build a custom binary with a higher limit. Not sure if we're exposing that limit as an admin setting at this point.

**Comment by apinstein** [comment]
Thanks for the quick reply! Now I don't feel like I'm going crazy :)

I had assumed that due the clojure underpinnings that streaming large data sets wouldn't be problematic from a memory perspective. I figured they'd be treated as streaming effectively. I can certainly appreciate that there might be tons of middleware for managing all of the different data sources and normalizing things, though, which could complicate that.

If memory issues are a real concern, might I suggest that error'ing out would be better than returning an arbitrarily truncated data set? It took me hours before I realized that I had errors in my data that were due to missing rows...

**Comment by lukegalea** [comment]
This is similar to https://github.com/metabase/metabase/issues/8622

I think exposing the upper limit to admin would be good, because on a t3.small instance we find that a query with enough columns will still crash the server with whatever the default limit is set to.

**Comment by allanbatista** [comment]
Hi, this have any var configuration to permit download from large results?

**Comment by sudoaza** [comment]
Confirm

**Comment by paoliniluis** [comment]
This can now be overriden by https://www.metabase.com/docs/latest/configuring-metabase/environment-variables#mb_download_row_limit
