### ISSUE TITLE
Sync not detecting SQLite foreign keys

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#8630]
It seems like sync is not correctly detecting SQLite foreign keys.

I added this database: https://san-francisco.datasettes.com/food-trucks-921342f (see `Download SQLite DB: food-trucks.db`)

The `Mobile_Food_Facility_Permit` table has several columns marked as foreign keys:

```
FOREIGN KEY ("Applicant") REFERENCES [Applicant](id),
    FOREIGN KEY ("FacilityType") REFERENCES [FacilityType](id),
    FOREIGN KEY ("Status") REFERENCES [Status](id),
    FOREIGN KEY ("block") REFERENCES [block](id));
```

but they are not detected by Metabase:

![screenshot 2018-10-04 10 00 04](https://user-images.githubusercontent.com/18193/46490396-bfc5f200-c7bc-11e8-8f09-652c92898c20.png)

Full sync logs and schema here: https://gist.github.com/tlrobinson/adff143829a33d6aa5da4c248c718c31

**Comment by schuon** [comment]
Same for us with a Postgres backend
