### ISSUE TITLE
When viewing column settings, you can't tab over to conditional formatting

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8633]
This is on our stats instance

![conditional-formatting-tab](https://user-images.githubusercontent.com/2223916/46503993-70de8380-c7e1-11e8-9099-aff8ac677b8e.gif)

**Comment by kdoh** [comment]
I can't seem to reproduce this on master as of today. Can you remember if there was a specific scenario where you noticed this?

**Comment by mazameli** [comment]
Hmm, yeah, weird — seems to have gotten fixed somehow. I'll reopen if I see it again.
