### ISSUE TITLE
Gradient conditional formatting does not work when using custom defined ranges

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8636]
If you set a custom range for a gradient rule, it doesn't render at all. This is on master in Chrome:

![conditional-formatting](https://user-images.githubusercontent.com/2223916/46508195-37157900-c7f1-11e8-8d1a-7df792c489c2.gif)

**Comment by FallenChromium** [comment]
Actually it breaks even without custom conditions in Safari sometimes.

**Comment by tlrobinson** [comment]
@FallenChromium The Safari issue is covered in #8578
