### ISSUE TITLE
Strange raw data output for some questions

### ISSUE THREAD

**Issue by santaux** [metabase/metabase#8638]
Hi guys!

On the most of the questions with simple filtering (without grouping or anything else) I see a strange output instead of simple table list:

![image](https://user-images.githubusercontent.com/943697/46539995-c342a180-c8c0-11e8-828c-63dc1f338114.png)

But if I click on "View SQL" button, I see normal table with results:

![image](https://user-images.githubusercontent.com/943697/46540075-fab14e00-c8c0-11e8-91b5-737d26e04ca9.png)

Why does thing happen? What I am doing wrong?

Thanks

**Comment by tlrobinson** [comment]
@santaux What database are you using?

If Druid you're probably seeing #6290. We should revive one or more of the fixes in #6726.

**Comment by tlrobinson** [comment]
@santaux You can also check to see if the "Date" field is marked as a primary key in the admin data model. If so change it something else (like "No special type" at the bottom)

**Comment by salsakran** [comment]
closing this as a dupe of #6290
