### ISSUE TITLE
Expanding multiple optional clauses to include JOIN

### ISSUE THREAD

**Issue by synweap15** [metabase/metabase#8640]
The [documentation regarding optional clauses](https://metabase.com/docs/latest/users-guide/13-sql-parameters.html#optional-clauses) states that:

`
To use multiple optional clauses you must include at least one regular WHERE clause followed by optional clauses, each starting with AND.
`

Is there a reason why the optional clauses are limited to that scope? My idea is that they could be used to build conditional joins. For example something like 

`[[JOIN study_year study_year_used ON (study_year_used.id = fscyp.study_year_id AND {{study_year}})]]` 

could boost performance of some queries with optional heavy drilldowns requiring lots of joins.

**Comment by salsakran** [comment]
it should work in that situation.

**Comment by synweap15** [comment]
But it unfortunately does not work, checked with v0.31.2. When the join is conditional as in example above, the variable is of `filter` type, the join occurs whenever a value is given for this field or not. Any thoughts?

**Comment by flamber** [comment]
Hi @synweap15 
When using the Field Filter and you haven't defined anything in the parameter, then it's replaced with `1=1`, which is why the `JOIN` is included all the time.

@salsakran Is there any way to avoid the join, when there's no parameter value? I've tried playing around with "complex default value" without success:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#default-value-in-the-query

**Comment by synweap15** [comment]
Hey @flamber
Correct, and documentation doesn't point Field Filter type as a special type that would allow the optional clause to be rendered even if it's empty (1=1).

I imagine my case (don't join unless the join is filtered) isn't the only out there where an improvement to the optional clause logic would help :-)

**Comment by MassimilianoCuccia** [comment]
it does not work

**Comment by petragianlu** [comment]
Hi, 
I've the same issue, 
When the variable is left empty, what I expect is that the whole condition inside the brakets [[]] is ignored, instead the variable is replaced with value '1=1'; 
So the join subqueries inside the [[]] don't work as expected.
How can I fix this?

**Comment by flamber** [comment]
@camsaul Looks like there's problems with Optional Clauses - can you reopen this?

**Comment by prigal** [comment]
Same problem for me, as discussed here 
https://discourse.metabase.com/t/default-value-in-field-filter-date-variable-to-now/5605/2, I'm not able to set a default as long as variable is valuated (1=1).

That issue should be reopened.

**Comment by flamber** [comment]
Possibly related to #5541
