### ISSUE TITLE
Add support for Decimal128 MongoDB type

### ISSUE THREAD

**Issue by cwilby** [metabase/metabase#8646]
*Info* 
Browser/version: `Chrome 69.0.3497.100`
Operating system: `OS X 10.13.6`
Metabase version: `0.30.4`
Metabase hosting environment: `Docker`
Metabase internal database: `MySQL`
Metabase external database: `MongoDB`

*Repeatable steps to reproduce the issue*
- [ ] Create a MongoDB collection and document including a field with `Decimal128` type.
- [ ] Create an instance of Metabase in Docker
- [ ] Connect MongoDB to Metabase and ask a question for that collection.

*Error*
> Detected unknown BSON type "\x13" for fieldname "total_price". Are you using the latest driver version?

*Screenshot*
![image](https://user-images.githubusercontent.com/13686317/46562724-6c35d000-c8b2-11e8-9f81-84ac44f15f8f.png)

*Temporary workaround*
I'm using a native query like the following to exclude this field for now:
```js
[
  {"$project":{ "foo": 1, "bar": 2 }},
  {"$limit":2000}
]
```

AFAIK, metabase is using the latest mongo drivers for Clojure.

**Comment by cwilby** [comment]
Seems to be a dependency issue.  Metabase uses [com.novemberbrain/monger](https://github.com/michaelklishin/monger/tree/3.1.x-stable) version 3.1.0, which uses [org/org.mongodb/mongodb-driver](https://github.com/michaelklishin/monger/blob/3.1.x-stable/project.clj#L8) version 3.3.0, which predates support for Decimal 128 data type - released in [version 3.4.0](http://mongodb.github.io/mongo-java-driver/3.4/whats-new/).

For this bug to be fixed, `com.novemberbrain/monger` needs to bump their version of `mongodb-driver` to >3.4.0, then Metabase can leverage the fix.

**Comment by flamber** [comment]
Looks like it's detecting fine in 0.41.2 - guess it was added a long time ago.

**Comment by cwilby** [comment]
Yep, `monger` PR got merged, upstream benefits 🎉
