### ISSUE TITLE
Metabase not responding

### ISSUE THREAD

**Issue by nikkjirnexu** [metabase/metabase#8648]
Metabase Version: 0.29.3
Server: AWS m5.xlarge ( 4 Vcpu , 16 GB RAM)
RDS :  Mysql on AWS db.m4.large

I am having this weird problem with metabase where it starts to consume all my CPU to max 100% randomly when no one is even using it , no queries being running and RDS time to time showing hitting max CPU.

Seems like metabase is processing something in background, but nothing usefull in logs.

We use metabase for our internal reporting , and only accessible in our VPC enviroment.

The data source used with metabase is Presto.

CPU Consumption 
![image](https://user-images.githubusercontent.com/42370282/46601778-ce940800-cb20-11e8-811c-20134d303213.png)

Entries in Logs file
![image](https://user-images.githubusercontent.com/42370282/46601789-d5bb1600-cb20-11e8-8514-a35baee1c301.png)

Logs entry:

10-08 09:17:43 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/user/current 200 (1 ms) (1 DB calls). Jetty threads: 8/50 (7 busy, 3 idle, 0 queued)^[[0m
10-08 09:17:43 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/session/properties 200 (2 ms) (1 DB calls). Jetty threads: 8/50 (6 busy, 4 idle, 0 queued)^[[0m
10-08 09:18:40 ^[[1mWARN api.label^[[0m :: ^[[33mLabels are deprecated, and this API endpoint will be removed in a future version of Metabase.^[[0m
10-08 09:18:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/label 200 (2 ms) (1 DB calls). Jetty threads: 8/50 (8 busy, 2 idle, 0 queued)^[[0m
10-08 09:18:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/collection 200 (9 ms) (2 DB calls). Jetty threads: 8/50 (7 busy, 2 idle, 0 queued)^[[0m
10-08 09:18:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/card 200 (51 ms) (7 DB calls). Jetty threads: 8/50 (6 busy, 3 idle, 0 queued)^[[0m
10-08 09:19:10 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/collection 200 (4 ms) (2 DB calls). Jetty threads: 8/50 (9 busy, 2 idle, 0 queued)^[[0m
10-08 09:19:23 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/collection 200 (3 ms) (2 DB calls). Jetty threads: 8/50 (7 busy, 4 idle, 0 queued)^[[0m
10-08 09:19:23 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mPUT /api/card/226 200 (27 ms) (9 DB calls). Jetty threads: 8/50 (6 busy, 5 idle, 0 queued)^[[0m
10-08 09:19:40 ^[[1mWARN api.label^[[0m :: ^[[33mLabels are deprecated, and this API endpoint will be removed in a future version of Metabase.^[[0m
10-08 09:19:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/label 200 (1 ms) (1 DB calls). Jetty threads: 8/50 (8 busy, 2 idle, 0 queued)^[[0m
10-08 09:19:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/collection 200 (3 ms) (2 DB calls). Jetty threads: 8/50 (7 busy, 3 idle, 0 queued)^[[0m
10-08 09:19:40 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/card 200 (35 ms) (8 DB calls). Jetty threads: 8/50 (6 busy, 4 idle, 0 queued)^[[0m
10-08 09:21:25 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/session/properties 200 (2 ms) (1 DB calls). Jetty threads: 8/50 (11 busy, 0 idle, 0 queued)^[[0m
10-08 09:21:25 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/permissions/group 200 (7 ms) (2 DB calls). Jetty threads: 8/50 (9 busy, 2 idle, 0 queued)^[[0m
10-08 09:21:25 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/permissions/membership 200 (2 ms) (1 DB calls). Jetty threads: 8/50 (8 busy, 3 idle, 0 queued)^[[0m
10-08 09:21:25 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/user 200 (2 ms) (1 DB calls). Jetty threads: 8/50 (8 busy, 3 idle, 0 queued)^[[0m
10-08 09:21:38 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/permissions/group 200 (2 ms) (2 DB calls). Jetty threads: 8/50 (9 busy, 3 idle, 0 queued)^[[0m
10-08 09:21:38 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/setting 200 (338 µs) (0 DB calls). Jetty threads: 8/50 (8 busy, 4 idle, 0 queued)^[[0m
10-08 09:21:38 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/permissions/group/5 200 (2 ms) (2 DB calls). Jetty threads: 8/50 (8 busy, 4 idle, 0 queued)^[[0m
10-08 09:21:56 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/permissions/group 200 (2 ms) (2 DB calls). Jetty threads: 8/50 (10 busy, 2 idle, 0 queued)^[[0m
10-08 09:21:56 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/user 200 (3 ms) (1 DB calls). Jetty threads: 8/50 (10 busy, 2 idle, 0 queued)^[[0m
10-08 09:21:56 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/setup/admin_checklist 200 (31 s) (10 DB calls). Jetty threads: 8/50 (10 busy, 2 idle, 0 queued)^[[0m
10-08 09:21:56 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mPOST /api/permissions/membership 200 (9 ms) (5 DB calls). Jetty threads: 8/50 (6 busy, 5 idle, 0 queued)^[[0m
10-08 09:23:08 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/card/226 200 (7 ms) (7 DB calls). Jetty threads: 8/50 (8 busy, 3 idle, 0 queued)^[[0m
10-08 09:24:02 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/alert/question/226 200 (1 ms) (1 DB calls). Jetty threads: 8/50 (9 busy, 1 idle, 1 queued)^[[0m
10-08 09:24:51 ^[[1mWARN api.label^[[0m :: ^[[33mLabels are deprecated, and this API endpoint will be removed in a future version of Metabase.^[[0m
10-08 09:25:21 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/label 200 (29 s) (1 DB calls). Jetty threads: 8/50 (13 busy, 1 idle, 12 queued)^[[0m
10-08 09:29:07 ^[[1mDEBUG metabase.middleware^[[0m :: ^[[32mGET /api/collection 200 (2 mins) (2 DB calls). Jetty threads: 8/50 (17 busy, 0 idle, 21 queued)^[[0m

**Comment by jornh** [comment]
I'd suggest upgrading to latest 0.30.x version and see if improves the situation. Quite a few different performance related issues were fixed since 0.29.3

**Comment by nikkjirnexu** [comment]
@jornh  Sure , let me give it a try and monitor for one day , whether it helps or not , but i find it very weird as metabase logs doesn't show much what actually its processing , making it like a blackbox.

**Comment by nikkjirnexu** [comment]
@jornh Tried v0.30.3 , and it seem to be consuming my CPU as well on random interval, and not responding back to the requests, response is very delayed.

**Comment by flamber** [comment]
From the log, it seems like the application database was slow to respond, which caused Jetty to be bogged down. There has been several fixes, but I'm fairly sure all of that is fixed in 0.35.3.
Please comment if this is still causing problems.
