### ISSUE TITLE
Metabase extremely slow. pooler's getConnection() taking too much time

### ISSUE THREAD

**Issue by vintageplayer** [metabase/metabase#8649]
We have been facing high latency in loading of the website as well as slow query results.
We installed and configured new relic APM, attaching screenshot of the stats shown.
![new_relic](https://user-images.githubusercontent.com/17234935/46604298-61c64100-cb13-11e8-89b1-7abdcbb3555e.png)

It looks crp0 module getConnection() is causing slowness. Also, we notice the pool size restricted to 15. Can this be the cause of slowness, and increasing pool size speed up the application?

We are running the latest docker image (0.30.4) with postgres db. (This issue was seen even in 0.30.3)

**Comment by senior** [comment]
I'm assuming that you are running PostgreSQL as the application database for Metabase. What databases do you have configured for your warehouse databases? 

You are correct that we currently set the connection pool to 15 and that is not currently configurable. What you will see if you have used all 15 connections, when the 16th comes in, it will block on that `getConnection()` method until a connection becomes available. It seems likely that waiting for a connection is a cause for the time spent there. Are you running a lot of queries at once that take a long time? Or maybe there are some queries hung that are consuming a connection?

**Comment by vintageplayer** [comment]
Yes, we are running PostgreSQL as the application database.
We have multiple data sources though, based on Redshift, BigQuery, Mysql DBs. We can have 
Can you guide me about the following:

1. Is the connection pool unique for each data source, or is one maintained for any data source and/or the metabase applicaton DB?
2. Incase the edit the source code to increase connections and compile the metabase, will it have any side affects? (Meaning is there a reason for hard coding the value to 15)
3. Any other possible way to tackle this situation?

**Comment by senior** [comment]
> Is the connection pool unique for each data source, or is one maintained for any data source and/or the metabase applicaton DB?

Connection pools are per data source, so 15 each.

> Incase the edit the source code to increase connections and compile the metabase, will it have any side affects? (Meaning is there a reason for hard coding the value to 15)

I don't think that 15 is the only possible number there, but increasing it could impact your instance. For example, by default a Metabase instance will allow 50 concurrent web requests. If all 50 are used, the next request goes into a queue and will execute when a thread is available. If you query a database maybe that database is very slow to respond. For example, it takes 2 minutes. One of those 50 threads will be unavailable for 2 full minutes. Maybe you change the max number of connections per database to 25. Two slow databases could fully consume your 50 available web request threads. The requests will all then go to the queue and the Metabase instance will appear hung. You can increase the number of threads for web requests along with the database connection pool, but there is balance between this as they consume memory. More concurrent database connections also consumes memory on the database server.

> Any other possible way to tackle this situation?

I think it would be better to start with the problem. This issue jumps to a solution, "Why is so much time being spent getting a connection, we should fix that". To take a step back. What problem were you having that caused you to look at the time spent getting a connection?

**Comment by flamber** [comment]
Closing, since there has been many connection improvements in the latest releases, 0.35.3.
It's possible to modify maximum connection pool:
https://github.com/metabase/metabase/blob/6f271dbe7ec7598b6878dcdede88ffdfc68dcaac/docs/operations-guide/environment-variables.md#MB_JDBC_DATA_WAREHOUSE_MAX_CONNECTION_POOL_SIZE
Please comment with details if you're still experiencing this issue.
