### ISSUE TITLE
Embed this Question Not Working

### ISSUE THREAD

**Issue by jsdcglobal** [metabase/metabase#8652]
Embed this question in an application button not working for no apparent reason.

- Your browser and the version: Chrome 69.0.3497.100 64-bit, Firefox 62.0.3 64-bit, IE 11.2189.14393.0 Update Version: 11.0.60
- Your operating system: Windows 10
- Your databases: SQL Server 2008 R2
- Metabase version: v0.28.1
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

- *Repeatable steps to reproduce the issue* - as far as repeatable steps go I don't have any. I don't log into Metabase every day to make updates. It happens more like once every 2-3 months. Sometimes when I log in the embed button suddenly works again and sometimes it doesn't. At first we thought it was based on who the 1st person who logged in after a restart was. It seemed as if that 1st admin to log in received the golden "embed baton" but even that theory ended up proving to be wrong. I'm the only user who logs into Metabase on a regular basis and we haven't restarted in months.

**Comment by salsakran** [comment]
is there anything in the javascript console?
