### ISSUE TITLE
Search bar focus, can't scroll filter list

### ISSUE THREAD

**Issue by FallenChromium** [metabase/metabase#8656]
- Safari 12.0.1
- macOS Mojave 10.14.1
- Metabase 0.30.4-0.31.2

Reproduce:
- New question > custom > open any table with 10+ columns to filter (or zoom the interface to make it bigger). Try to scroll when search bar is active.

![](https://user-images.githubusercontent.com/2223916/49307328-ade59000-f489-11e8-8b7b-87dce26e93e7.gif)

P.S As far as I can say it's not a problem in Chrome

P.P.S I want to say thank you guys, your project helping many people around the world to be a successful company and you should be proud of it ❤️ 

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by FallenChromium** [comment]
Just a friendly ping it's STILL a problem, and while I understand WebKit is not the main platform here, the decent part of users are on it and they're experiencing problems. Sadly enough I'm not frontend developer so I can't provide pull request to fix that.

**Comment by joshhopkins** [comment]
I'm guessing this is the same issue.

![](https://dsh.re/79f332)

**Comment by flamber** [comment]
@joshhopkins Are you also using Mac+Safari? I cannot reproduce this on Linux+Firefox/Chromium.

**Comment by joshhopkins** [comment]
@flamber Seeing this in both Safari and the MacOS app. Can't reproduce it consistently though. This was using the test data that ships with Metabase.
