### ISSUE TITLE
Series labels reset to default if results don't include all series (on dashboard)

### ISSUE THREAD

**Issue by jwarshaw** [metabase/metabase#8661]
When I filter a dashboard, any question with custom series labels could revert to the default setting if the filtered results do not include all series.

### Before
![before](https://user-images.githubusercontent.com/16521280/46696994-360d8e80-cbd9-11e8-97b0-4c48f17ba8ea.png)

### After
![after](https://user-images.githubusercontent.com/16521280/46697082-6f45fe80-cbd9-11e8-998e-d8877e3ed93b.png)

Chrome Version 69.0.3497.100
Ubuntu 18.04.1 LTS
MySQL
Metabase version v0.28.5
Elastic Beanstalk RDS DB

Repeatable steps:
Create and save a question displayed as a bar graph with multiple series
Customize the series names
Add the question to a dashboard
Add a filter to the dashboard
Filter the dashboard so that the results do not include all series
The series labels will revert to default

**Comment by tlrobinson** [comment]
This should be fixed in `master` with the addition of "series settings". Please give it a try if possible. You can use the `metabase/metabase-head:latest` Docker image.

**Comment by salsakran** [comment]
@jwarshaw can you verify if this was fixed? Closing this since we believe it to be fixed, but will re-open if you're still seeing this.
