### ISSUE TITLE
Cannot auto-sort by columns on individual queries.

### ISSUE THREAD

**Issue by sunny-t** [metabase/metabase#8662]
It would be nice to be able to sort columns on individual question pages. 

This can only be done when the question is added to a dashboard or if you are only using the query builder.

**Comment by salsakran** [comment]
This is a bit trickier than it sounds --

If a limit is applied, this will only sort the rows available on the client, which is not what most people would expect.

**Comment by sunny-t** [comment]
@salsakran I found a way around this by simply just using the "Analyze Results" option.

**Comment by flamber** [comment]
Closing in favor of #11329
