### ISSUE TITLE
Query builder should have horizontal scrolling with many metrics or dimensions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8669]
When adding many metrics or group-bys, the query builder used to have a max width and would scroll the overflow. But now on master on Chrome I'm seeing this:

![screen shot 2018-10-10 at 11 03 13 am](https://user-images.githubusercontent.com/2223916/46756420-4460b680-cc7c-11e8-850e-83ceb00d6b8f.png)

**Comment by flamber** [comment]
Hi @mazameli 
This looks like a duplicate of #6566

**Comment by notrom** [comment]
I'm seeing the exact same thing in Firefox too.

**Comment by salsakran** [comment]
dupe of #5325!
