### ISSUE TITLE
Nullpointerexception for empty query

### ISSUE THREAD

**Issue by egrinstein** [metabase/metabase#8673]
Hello,

I am using your wonderful product to query my Postgresql database.

I've got a table called Users, which has lots of columns with lots of foreign keys. It has less than 1000 entries, which I assume to be small.

When I ask a custom query without filters with view as 'raw data', that is, without writing anything, I get an error saying that "There was a problem with your question 
Most of the time this is caused by an invalid selection or bad input value. Double check your inputs and retry your query.". 

If I click to see full error message, I get a `java.lang.NullPointerException`.

Now here's the kicker: If I write an SQL query saying `SELECT * FROM users`, which I assume is what the raw query does, I get the full result. 

Any Ideas?

Cheers,

Eric

**Comment by mazameli** [comment]
Hmm, which version of Metabase are you running, and where/how are you running it?

**Comment by egrinstein** [comment]
Version 0.30.0

**Comment by egrinstein** [comment]
Sorry, didn't see the last part.

I am running it from a Heroku server.

**Comment by egrinstein** [comment]
I have upgraded metabase to version 0.31.0, and the issue seems to be solved.
