### ISSUE TITLE
How to create a driver plugin

### ISSUE THREAD

**Issue by Nikos410** [metabase/metabase#8676]
Hello there!

A while ago, I wrote a driver for using FirebirdSQL databases in metabase, but there didn't seem to be any interest in including it in metabase, so I'm trying to package the driver as a plugin. However, I did not find any documentation on how to package a driver as a plugin.
I've already tried packaging the firebird .class files in `/target/uberjar/classes` using the command `jar cvf FirebirdDriver.jar firebird* firebird/FirebirdDriver.class`. 
When I put this jar into the plugins/ directory and run the metabase.jar file, metabase displays `10-11 17:02:08 INFO metabase.plugins :: Loading plugin /srv/nepping/projects/metabase-develop/metabase-run-jar/plugins/FirebirdDriver.jar... 🔌`, but after that, it doesn't register the driver.

What am I doing wrong? I hope you can help me :)

--
Edit: my .jar file looks like this:

```
# jar tf FirebirdDriver.jar
META-INF/
META-INF/MANIFEST.MF
metabase/driver/firebird/
metabase/driver/firebird/FirebirdDriver.class
metabase/driver/firebird$_init_driver.class
metabase/driver/firebird$append_connection_args.class
metabase/driver/firebird$apply_limit.class
metabase/driver/firebird$can_connect_QMARK_.class
metabase/driver/firebird$connection_details__GT_spec.class
metabase/driver/firebird$date.class
metabase/driver/firebird$date_trunc.class
metabase/driver/firebird$firebird__GT_spec.class
metabase/driver/firebird$fn__57923.class
metabase/driver/firebird$fn__57926$__GT_FirebirdDriver__57938.class
metabase/driver/firebird$fn__57926$map__GT_FirebirdDriver__57940.class
metabase/driver/firebird$fn__57926.class
metabase/driver/firebird$fn__57950$iter__57946__57951$fn__57952$fn__57953.class
metabase/driver/firebird$fn__57950$iter__57946__57951$fn__57952.class
metabase/driver/firebird$fn__57950$iter__57946__57951.class
metabase/driver/firebird$fn__57950.class
metabase/driver/firebird$format_step.class
metabase/driver/firebird$format_timestamp.class
metabase/driver/firebird$get_unit_name.class
metabase/driver/firebird$get_unit_placeholder.class
metabase/driver/firebird$loading__6434__auto____57921.class
metabase/driver/firebird$replace_timestamp_part.class
metabase/driver/firebird$string_length_fn.class
metabase/driver/firebird$unix_timestamp__GT_timestamp.class
metabase/driver/firebird__init.class
metabase/driver/firebird.clj
```

Since the wiki article on how to write a driver says 

> Drivers are expected to live in a namespace that matches the form metabase.driver.\<driver-name>

I would expect this to work.

**Comment by salsakran** [comment]
@camsaul @senior any suggestions here?

**Comment by Nikos410** [comment]
Resolved with the new plugin system. Thanks for your work!

**Comment by Nikos410** [comment]
Resolved with the new plugin system. Thanks for the good work!
