### ISSUE TITLE
NullPointerException on BigQuery with aggregate SUM function

### ISSUE THREAD

**Issue by mdonnellyli** [metabase/metabase#8677]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

Client: Chrome (69.0.3497.100)
Client : macOS (0.13.3)
Deployed to Kubernetes on Google Cloud Platform(GKE)
Database: BigQuery
Internal Database : H2 (default) 
Metabase version :0.30.1

I have a table that I am able to see the raw data without issue. But when I apply an expression to it - get a nullpointerexception - wondering what I can do to diagnose?

Raw Data from below works but the rest dont.

![image](https://user-images.githubusercontent.com/1457654/46817046-79800e00-cd3b-11e8-89f1-952ac2a84e0f.png)

Here is a copy of the query I am trying

![image](https://user-images.githubusercontent.com/1457654/46817062-843aa300-cd3b-11e8-9f0c-294338fc2250.png)

Attached are the logs
[error.log](https://github.com/metabase/metabase/files/2469700/error.log)

**Comment by flamber** [comment]
Closing in favor of #6615, since this is happening during sorting and the data likely contains `null`s
