### ISSUE TITLE
Graph ranges are calculated differently for each dataset

### ISSUE THREAD

**Issue by etcook** [metabase/metabase#8683]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Version 69.0.3497.100
- Your operating system: (e.x. OS X 10, Windows XP, etc
OSX
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
PostgreSQL
- Metabase version: (e.x. 0.19.3)
0.30.4
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Docker
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
PostgreSQL

Create a bar or line graph with multiple custom expressions the ranges are calculated independently for each large set, which makes visual comparison impossible.

<img width="1444" alt="image 2018-10-12 at 10 32 06" src="https://user-images.githubusercontent.com/2329397/46879092-abac7100-ce0a-11e8-8b61-bcd74cb89815.png">
<img width="1462" alt="image 2018-10-12 at 10 32 14" src="https://user-images.githubusercontent.com/2329397/46879097-aea76180-ce0a-11e8-8749-27d741383e58.png">

<img width="1242" alt="image 2018-10-12 at 10 43 09" src="https://user-images.githubusercontent.com/2329397/46879540-f24e9b00-ce0b-11e8-8110-c5e4102ab5cf.png">
<img width="1495" alt="image 2018-10-12 at 10 43 37" src="https://user-images.githubusercontent.com/2329397/46879546-f5498b80-ce0b-11e8-9cca-3a974b6d918c.png">

**Comment by mazameli** [comment]
I believe this is just the split y-axis setting, which is automatically applied when you have multiple metrics/series that are very different in their respective min/maxes. You can turn this behavior off with this toggle in the `Axes` tab of your chart settings (it's the bottom toggle in this screenshot):

![screen shot 2018-10-12 at 10 28 16 am](https://user-images.githubusercontent.com/2223916/46884337-8bc87d80-ce09-11e8-8dbc-50acf21bed7d.png)

The upcoming next version of Metabase will give you even more control over which series should go on which y-axis:

![screen shot 2018-10-12 at 10 29 07 am](https://user-images.githubusercontent.com/2223916/46884396-bb778580-ce09-11e8-8120-236134f6d583.png)

**Comment by etcook** [comment]
@mazameli that's absolutely what it was. Sorry for the false alarm and thank you for the clarification.

**Comment by mazameli** [comment]
@etcook No worries! That's valuable feedback to know the behavior was unexpected to you.
