### ISSUE TITLE
Not all the requested fieds are not shown in a tooltip

### ISSUE THREAD

**Issue by drenout** [metabase/metabase#8685]
- Browsers: Chrome 69.0.3497.100, Firefox 62.0.3 (64-bit), EDGE 38.14393.2068.0)
- Operating system:  Windows 10
- Your databases, MongoDB
- Metabase version: 0.30.4
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

**Steps to repro:**
1. Request 4 fields from your mongodb table. In my case I had the next query:  
`[{"$project":{"_id": 1, "name":"$test_name", "TPS":"$tps", "Status": "$test_status"}}]`
2. Create a bar chart like in attached screenshot: 
![settings](https://user-images.githubusercontent.com/26801119/46888177-950b1780-ce14-11e8-9a69-8ac70d2bc56c.JPG)
3. Hover mouse over the several bars

**Actual results:**
Test name is not shown in a tooltip for several bars.  
Bar with all the requested fields: 
![testname](https://user-images.githubusercontent.com/26801119/46888392-35613c00-ce15-11e8-980c-7b91c0da35bd.JPG)
Tooltips without name field:
![no test name](https://user-images.githubusercontent.com/26801119/46888427-575abe80-ce15-11e8-8f32-9792209c4b8a.JPG)
![no test name 2](https://user-images.githubusercontent.com/26801119/46888482-79544100-ce15-11e8-92f8-796c849dbdf5.JPG)

__Expected results:__
Tooltip for the every bar should display the test name

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by mazameli** [comment]
Are the results correct when you view this query as a table?

**Comment by drenout** [comment]
Yes, results in table are correct: 
![image](https://user-images.githubusercontent.com/26801119/46889995-43658b80-ce1a-11e8-8eea-64320ab49e54.png)

**Comment by flamber** [comment]
Hi @drenout 
Are you still seeing this issue on 0.31.2? This might be fixed by #9416, which should be in 0.32.0

**Comment by drenout** [comment]
HI @flamber 
Unfortunately the issue was critical for me and I switched from metabase, so cannot verify the fix

**Comment by githublivier** [comment]
Hi @drenout,

Does it work now after upgrading ?
I have the same issue (V0.31.8). I've upgraded to V0.32.8 but it doesn't work. 

Thanks in advance

**Comment by flamber** [comment]
I've been able to reproduce this on 0.32.8 with Sample Dataset (Firefox 67).
Discussed here too: https://discourse.metabase.com/t/histogram-colum-and-pop-up/6286
@tlrobinson From the forum, sounds like it got worse between 0.31 and 0.32 (problem with #9416?)

Stacked Bar:
![Screencast 2019-05-22 10 25 32](https://user-images.githubusercontent.com/1447303/58192776-cdae8180-7c7e-11e9-8670-861ff5e2c5d1.gif)
Default Area:
![Screencast 2019-05-22 10 40 14](https://user-images.githubusercontent.com/1447303/58192829-e6b73280-7c7e-11e9-9271-3fe43926633f.gif)

**Comment by drenout** [comment]
Hi @githublivier,

Unfortunately I stopped to use metabase and cannot verify the issue

**Comment by githublivier** [comment]
Hi @drenout 

Thanks for your answer.
Do you use some other open source solution ?

**Comment by drenout** [comment]
@githublivier I used python and plotly module to create a dashboard with different types of charts

**Comment by paulrosenzweig** [comment]
Resolved by #10555
