### ISSUE TITLE
Public embed filter do not work. I get "No results" on my web page.

### ISSUE THREAD

**Issue by KurmetK** [metabase/metabase#8689]
------
I added iframe of dashboard to my web site. And when i do filter i get no results in my table.
In metabase site, in dashboard my filter work and i get result by my fitler
-----

[DASHBOARD - Public link. Filter work](http://reports.wf.bein.tech/public/dashboard/96ee8d81-f99f-45de-a5c8-f9c105872b20)
[MY WEB SITE - filter do not work](https://test.wf.bein.tech/task-list/report/3)

- Your browser and the version: Chrome 69, Firefox 62
- Your operating system: OS X 10.12
- Your databases: Postgres
- Metabase version: 0.30.3
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment]
@KurmetK I can't access the "My web site" link.

Can you share server logs from when you make a request for that dashboard?
