### ISSUE TITLE
Metabot links to question using private IP

### ISSUE THREAD

**Issue by xaviershay** [metabase/metabase#8695]
- Metabase version: 0.30.4
- Metabase hosting environment: Elastic Beanstalk inside a VPC
- Metabase internal database: Postgres

When metabot posts a question to slack, when I click on the link to view the question in metabase it links to a URL like: `http://10.0.0.1/question/5`. I would like to configure the hostname but cannot find out where.

Thank you!

**Comment by xaviershay** [comment]
... if this is configuration we'd like to add, I'd be open to trying to do so if someone can point me in roughly the right direction!

**Comment by xaviershay** [comment]
note to self: metabot code introduced in https://github.com/metabase/metabase/pull/2088/files

**Comment by tlrobinson** [comment]
@xaviershay If your "site url" in the admin settings set correctly? `/admin/settings/general`

**Comment by xaviershay** [comment]
no :( Missed that one, fixed. Thanks!
