### ISSUE TITLE
Code editor: protect against CTRL-R

### ISSUE THREAD

**Issue by fulldecent** [metabase/metabase#8712]
# Test case

1. Ask a question
2. SQL
3. Type `SELECT`
4. Press <kbd>CTRL</kbd>-<kbd>R</kbd>

# Expected outcome

A dialog pops up:

> Are you sure you want to leave this page?

# Actual outcome 

Page refreshes and query is lost.

# Discussion

<kbd>CTRL</kbd>-<kbd>R</kbd> is the default "run query" shortcut for many other software programs. But the same sequence is disastrous in this software.

**Comment by mazameli** [comment]
Good thought. In Metabase, the shortcut to run a native query is cmnd/ctrl-return/enter, but I don't know if that's documented or hinted at anywhere, and we should fix that.

**Comment by cdeweyx** [comment]
Just waiting for backport: https://github.com/metabase/metabase/pull/31986
