### ISSUE TITLE
JRE or JDK

### ISSUE THREAD

**Issue by fulldecent** [metabase/metabase#8713]
The document https://github.com/metabase/metabase/blob/master/docs/operations-guide/running-the-metabase-jar-file.md states that MetaBase is compatible with JDK.

However the console output shows the software running on JRE.

I understand that requiring JDK is more restrictive than requiring JRE. Because the JDK includes the JRE but the JRE does not include the JDK.

If only the JRE is required then I request the documentation explain this.

---

P.S. clearly, I know nothing about running Java or setting up Java production environments, thankfully.

**Comment by fulldecent** [comment]
Context: this is the install step choice that stopped me and caused me to post this question:

https://www.digitalocean.com/community/tutorials/how-to-install-java-on-centos-and-fedora

**Comment by camsaul** [comment]
You only need the JRE, Java 8 or higher. I will fix documentation.
