### ISSUE TITLE
user belonging to more than one group both with sandboxed access results in error : "Found more than one group table access policy for user xxx@yyyy"

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#8715]
- Your browser and the version: Mozilla 62.0.3
- Your operating system: Win7
- Your databases: mySQL
- Metabase version:  v1.0.0
- Metabase hosting environment: Win7
- Metabase internal database: postgres

Define two sandboxed access for one table for two distinct groups.
Add a user to the two groups
Then that user cannot access the table's data, and gets the following message  

"Found more than one group table access policy for user xxxx@yyyyy"

Does that mean that sandboxed access implies monogroup users ?
If so, data permission panel should be updated to prevent admin from defining more than one sandboxed access for a given table.

Would it be difficult to keep the rights additive ?

**Comment by mazameli** [comment]
Thank you for pointing this out, @fetanchaud. When you say, "Would it be difficult to keep the rights additive?" is your expectation that both of the sandboxes' filters would be applied for this user?

For example, if one sandbox is defined as `where user_id = user_id_attribute` and the other is `where team_name = team_attribute`, would you expect that user to only be able to see rows where _both_ of those conditionals are true?

**Comment by fetanchaud** [comment]
Sorry I mixed apples and oranges... this is not an OSS issue.
