### ISSUE TITLE
Some comparison and x-ray charts not rendering

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8717]
This is on master in Chrome. I created a comparison by clicking on this bar in this question:

![screen shot 2018-10-17 at 2 47 17 pm](https://user-images.githubusercontent.com/2223916/47118266-a50f6680-d21b-11e8-9cc0-904d73e3bf52.png)

These charts seem to not know which fields to use for the x/y axes:

![screen shot 2018-10-17 at 2 46 46 pm](https://user-images.githubusercontent.com/2223916/47118378-e99b0200-d21b-11e8-84fa-1987d9615b7c.png)

And these two have hit our 20-series limit (which @kdoh is looking into removing or changing how we handle it):

![screen shot 2018-10-17 at 2 47 04 pm](https://user-images.githubusercontent.com/2223916/47118414-08999400-d21c-11e8-9eff-7f0feab80a4a.png)

The same thing happens when doing a comparison when the breakout is a lower-cardinality field like this one:

![screen shot 2018-10-17 at 2 49 30 pm](https://user-images.githubusercontent.com/2223916/47118441-194a0a00-d21c-11e8-94c6-8edd0cc093d8.png)

If I do an x-ray rather than a comparison for one of these bars, I see similar problems:

![screen shot 2018-10-17 at 2 54 46 pm](https://user-images.githubusercontent.com/2223916/47118657-d3da0c80-d21c-11e8-81f3-429c5122ddfc.png)

**Comment by sbelak** [comment]
Fixed via #8724
