### ISSUE TITLE
i18n on date filters

### ISSUE THREAD

**Issue by elecay** [metabase/metabase#8723]
Some literals are not being translated.

![captura de pantalla de 2018-10-18 18-16-19](https://user-images.githubusercontent.com/1318127/47168836-378a3580-d302-11e8-910e-5bcbdac0d399.png)
![captura de pantalla de 2018-10-18 18-16-43](https://user-images.githubusercontent.com/1318127/47168837-378a3580-d302-11e8-868a-e25eff92fab7.png)

I don't even see any **msgid** for months on locale files (.po), so, this depends on MomentJS?

**Update**: just for testing purposes I added this lines:

```
import moment from "moment";
moment.locale("pl");
```

to **app-main.js** and now it's working (for the calendar). Make sense to add this lines to **lib/i18n.js**?

![captura de pantalla de 2018-10-18 18-32-38](https://user-images.githubusercontent.com/1318127/47169601-3eb24300-d304-11e8-869c-42b04237e693.png)

**Update2**: I found this class: **DateUnitSelector**, which isn't handling translation correctly:

```
<Option value={period} key={period}>
    {capitalize(pluralize(formatter(intervals) || 1, period))}
</Option>
```

**Comment by RamazanBIYIK** [comment]
@elecay thanks you very much.I had the same issue. Thanks to @elecay 's suggestion inside app-main.js i figure it out.My language is Turkish.  I hope this bug goes to a solution ASAP.

**Comment by tlrobinson** [comment]
FYI there's a PR in progress at #9050

**Comment by salsakran** [comment]
@tlrobinson do you mind checking to see if #9050 fixed this specific issue?

**Comment by salsakran** [comment]
or rather #9071
