### ISSUE TITLE
Feature Request : Restrict user access to everything but dashboards

### ISSUE THREAD

**Issue by fetanchaud** [metabase/metabase#8730]
Hi !

Not all companies are ready to deliver data as a service yet.

So what about restricting registered user access to everything but dashboards ?
This could be a per group configuration.

Dashboard in that mode should behave like when shared with a public link (no way to see the underlying records)

Thank you !

**Comment by fetanchaud** [comment]
Hi @mazameli, 

Our use case is : 

- No corporate web site
- Will to provide access to only a subset of company data or aggregates - yes, it still happens :-( 

So we are looking for a way to disable any discovery possibility, but you are right, giving access only to dashboard sounds much too restrictive.

Maybe an interesting feature could be to prevent user from editing the question itself (table, filter, view, group, columns in raw mode), but to let him choose the right rendering (bar, pie...).

That way user could create copies of predefined questions with the right rendering,
and even create dashboards based on these copies and any other available question. 

These tailored questions and these dashboards could be saved only in personal collection.

This could be achieved with a group's attribute disabling all the discovery features,
and altering the 'View Collection '  right accordingly ?

But It might be a lot of work. What do you think about this idea ?

> 
> 
> **To clarify, I'm assuming this would also mean:**
> 
>     * hiding the `Ask a question` button
> 
>     * hiding the `Our Data` section on the homepage
> 
>     * hiding the `Data Reference`, so that users couldn't navigate to tables from there
> 
> 
> **Additional questions:**
> 
>     * Would users be able to click on a question in a dashboard to see it in greater detail? If so, I assume you'd expect the query builder bar (or SQL editor) to be hidden?
> 

NO

>     * Some dashboards might contain saved questions that are raw data. Would you expect those questions/cards to be hidden?
> 

NO

>     * Should users be allowed to browse collections, but only see dashboards? Or would you expect them to be able to view saved questions and pulses, too, as long as they couldn't modify the saved questions or see the underlying records? Would you want them to be able to see saved questions that are raw tables?
> 

YES, ONLY DASHBOARDS

>     * Relatedly, would you expect Search results to be limited to just dashboards?
> 
>     * Would you also want to prevent users from creating _new_ dashboards (or pulses)?
> 
> 

YES

> Thanks for your thoughts!

**Comment by fetanchaud** [comment]
Could be related to #8773

**Comment by tlrobinson** [comment]
If I understand correctly, this is already possible by creating a group with no "Data permissions". Make sure to revoke all permissions from the "All Users" group too. You can also just give the group "View" access to specific collections if you want to restrict them to a subset of dashboards/questions.

We even do hide the buttons/sections @mazameli mentioned in his first comment if the user doesn't have any Data permissions:

<img width="836" alt="screen shot 2018-11-12 at 10 14 21 am" src="https://user-images.githubusercontent.com/18193/48366836-d7b64e80-e663-11e8-8b11-2559c1eb4628.png">

As far as not allowing the user to click into a question from a dashboard, I don't really see the purpose of that as it doesn't expose any new data, it's just showing a fullscreen version of one question. We already hide the query builder bar too.

**Comment by mbvictoria** [comment]
Closing - main purpose of this ticket resolved, auxiliary ticket is #8700
