### ISSUE TITLE
Too many attempts when repeatedly logging in with correct password

### ISSUE THREAD

**Issue by jasongi-actu** [metabase/metabase#8736]
- Your browser and the version: N/A
- Your operating system: Mac OSX
- Your databases: Postgres
- Metabase version: (e.x. 0.30.4)
- Metabase hosting environment: Docker
- Metabase internal database: Postgres
-------

I am currently automating some metabase things with the API, which includes logging in with the api/session endpoint. I have noticed that eventually if I run the script too many times sequentially, my account gets locked even though I've logged in with the correct password each time. A suggested fix would be to only increment the login attempt counter if the password is incorrect.

**Comment by senior** [comment]
I added an environment variable [`MB_DISABLE_SESSION_THROTTLE`](https://github.com/metabase/metabase/pull/8574/files#diff-4749fc04c2fa4d280c75a64dd5ecb54bR77) to disable that session throttling. It's not exactly what you are asking for, but I used to to help in load testing, as a part of https://github.com/metabase/metabase/pull/8574. It has been merged and will be included with `0.31.0`.

**Comment by mazameli** [comment]
@senior Can we say this is resolved by #8574?

**Comment by salsakran** [comment]
@jasongi-actu How many times are you running the script and why don't you cache session credentials?

I'm inclined to think this is a pretty niche issue, and that for development `MB_DISABLE_SESSION_THROTTLE` should suffice.

**Comment by jasongi-actu** [comment]
I'm not sure `MB_DISABLE_SESSION_THROTTLE` solves the issue. I'm assuming that will disable throttling even for incorrect logins? Not really acceptable on a production instance. I can (and probably will) end up caching the session token between runs of the script, however I still think this is a bug that should be fixed.

**Comment by camsaul** [comment]
I would definitely recommend caching session credentials and then only logging in again when you get Unauthorized response codes

**Comment by Swizz** [comment]
I am in the same situation as @jasongi-actu. 
Working on scripts to manage multiple metabase instant. 
To make the things properly we log on then log out, once the script is done.

`MB_DISABLE_SESSION_THROTTLE` seem to do not solve the issue.

I understand the security concerns, but the `POST /api/session` must not throttle  requests on succeed.

**Comment by tlrobinson** [comment]
It definitely seems like only failed logins should count towards the limit. If an entire office shares an IP address it's effectively limited to 50 logins per hour.

**Comment by tlrobinson** [comment]
As pointed out in an offline discussion, it's even worse if you use load balancers since all requests appear to come from the same IP address, effectively limiting your instance to 50 logins per hour regardless of user IP address.

We should ignore sucessful logins, and allow admins to opt into using `X-Forwarded-For` (or an arbitrary header?), and maybe allow more configuration of the limits.

**Comment by walterl** [comment]
Fixed in #10593

**Comment by jasongi-actu** [comment]
> Fixed in #10593

Thanks @walterl, much appreciated!
