### ISSUE TITLE
Instructions incorrect for adding to "Our Analytics"

### ISSUE THREAD

**Issue by fulldecent** [metabase/metabase#8747]
On this main page it states:

> Save dashboards, questions, and collections in "Our analytics"

<img width="1769" alt="screen shot 2018-10-23 at 11 19 53 am" src="https://user-images.githubusercontent.com/382183/47371369-ab875d80-d6b5-11e8-8e2d-717768c0125a.png">

This implies that adding something to "Our analytics" will make it appear in this section. However adding something to "Our analytics" does not cause it to appear on the homepage.

The current behavior is misleading.

**Comment by mazameli** [comment]
Setting aside that text for the moment, I'm interested to know what you would ideally _want_ on the homepage. Our vision for the homepage is that it would be a fast way to get to your most important dashboards, your top-level collections, and your data, and that the page would naturally adapt as you create dashboards and collections, and as you pin important dashboards.

**Comment by fulldecent** [comment]
Thank you. I just want to see the denormalized view for my customer order fact table. Then I open it open and drill down. This is the basis for most of my analysis. Maybe a few other data tables.

For me, Metabase is a competitor to Sequel Pro. If there is a very important report I will publish it with PHP+MySQL+Datatables.js on our intranet. I'm not quite at the point yet where I will give employees access to this tool. Any button or option that they do not understand will result in a phone call to me. It is not locked down or customizable enough yet. So maybe I am not the ideal customer :-p

**Comment by jgarber** [comment]
For me, right now "Our Analytics" only shows other collections. I can only see the questions and dashboards when I click "Browse all items." I would like that section of the home page to show all items in the "Our Analytics" collection, regardless of type.

**Comment by mazameli** [comment]
@jgarber I see. Thanks for the feedback. Just so you know, if you pin any dashboards in the "Our Analytics" collection, those appear at the top of the homepage. 

On another note, do you use the "Our data" section on the homepage often to get directly to a table?

**Comment by doodlebro** [comment]
>if you pin any dashboards in the "Our Analytics" collection, those appear at the top of the homepage.

I think the point OP is making is that this functionality is not obvious to the user unless they happen upon the pinning feature and use it. Ideally the text on the homepage should say "Pin your most important dashboards/questions and they will show up here!" Right now, the way it's worded makes it seem like you only have to add a collection to "Our Analytics" to get it to show up on the homepage.

**Comment by fulldecent** [comment]
@doodlebro Thank you, you said it much better.

@mazameli I do not access tables like that. I will set up a few denormalized views and create a few queries against them. The people in my company don't even know what a database is. Once my production environment is set up I will probably tell them "open Metabase and click the customers Excel file on the top".

**Comment by stevewritescode** [comment]
Several of our users have asked about starring/pinning dashboards to show up just on their own homepage - is that something that is possible in the current release? It's unclear to me from the helper text and user guide if it can be done.

**Comment by robertsosinski** [comment]
Hey again,

I guess I'm running into some confusion here too.  I see pinning dashboards makes them pop up in the "Start Here" part of the home page.  However, I do not see any way to get Dashboards, Questions or Collections to show up in the "Our Analytics" part of the home page.  If I understand this correctly, after being pinned Metabase will just kinda "learn" what people are using most often and they will sooner or later pop up in that part of the home page?

I would agree, something more configuration based (either pinning or just marking with a star or something) will make it show up would be a lot easier to communicate to others on a team.

Thanks!

-Robert

**Comment by robertsosinski** [comment]
Hey again,

So after tooling around a bit, it makes more sense and it squares with what @jgarber said.  You have to make a new Collection in Our Analytics, and then the Collection will show up in the Our Analytics section of the home page.  Guess, based on the wording I expected Questions and Dashboards to show up there too.

This works for me now, but indeed maybe making the wording "new Sub-Collections created within the 'Our Analytics' Collection will show up here!" would make more sense?

Appreciate all the work on Metabase (its awesome), hope this feedback helps make it even easier to use for others!

-Robert

**Comment by kulyk** [comment]
Closing because of the homepage + nav revamp coming in 43
