### ISSUE TITLE
All collections and sub-collections are all displaying identical contents

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8748]
On master, `release-0.31.0`, and our stats instance, we're seeing that all collections are displaying the same pinned collections, sub-collections, and saved items. The only exception seems to be that the `my personal collection` and `all personal collections` links are only showing up in the "our analytics" collection (correctly). Saved questions and dashboards appear to be correctly displaying which collection they're actually saved in.

I also tested this on a different app db that had no collections or dashboards saved yet, and the behavior was that when I created a new dashboard + collection and questions by saving an x-ray, all of those new items now appear in every collection I navigate to. Pinning a dashboard in `our analytics` is also not correctly displaying that dashboard on the homepage.

**Comment by FallenChromium** [comment]
Yep, I can confirm too, faced this when tried some 0.31 PRs with a database which was used in 0.34.0 before.
