### ISSUE TITLE
Reordering columns in aggregated results causes errors

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8760]
In master, reordering columns in the result of an aggregation query, either by dragging the column heading, or by reordering in the visualization settings modal results in an error.

For these two gif examples, the error returned is: 
```
Query processor error: mismatched number of columns in query and results. 
Expected 5 fields, got 4 
Expected: ["STATE" "count" "sum" "sum" "STATE"] 
Actual: ["count" "sum" "sum_2" "STATE"]
```

![reorder-qp-error](https://user-images.githubusercontent.com/2223916/47398643-d4294a80-d6e9-11e8-9115-5bc0e545d9f4.gif)

![reorder-viz-settings](https://user-images.githubusercontent.com/2223916/47398696-1783b900-d6ea-11e8-9fa7-dfadcf927a7d.gif)

For this next screenshot, the error is different:

![screen shot 2018-10-23 at 5 38 45 pm](https://user-images.githubusercontent.com/2223916/47398802-9ed12c80-d6ea-11e8-9bfa-330fe082b655.png)

```
org.h2.jdbc.JdbcSQLException: Column """PRODUCTS__via__PRODUCT_ID"".CREATED_AT" must be in the GROUP BY list; 
SQL statement: -- Metabase:: userID: 2 queryType: MBQL queryHash: a271ae086986b0a88d6b9f0d02a586d29ecc7288811aa96ad7a9a6f9821397c3 
SELECT CAST("PRODUCTS__via__PRODUCT_ID"."CREATED_AT" AS date) AS "CREATED_AT", count(*) AS "count", "PRODUCTS__via__PRODUCT_ID"."CREATED_AT" AS "CREATED_AT", "PEOPLE__via__USER_ID"."SOURCE" AS "SOURCE" 
FROM "PUBLIC"."ORDERS" 
LEFT JOIN "PUBLIC"."PRODUCTS" "PRODUCTS__via__PRODUCT_ID" ON "PUBLIC"."ORDERS"."PRODUCT_ID" = "PRODUCTS__via__PRODUCT_ID"."ID" LEFT JOIN "PUBLIC"."PEOPLE" "PEOPLE__via__USER_ID" ON "PUBLIC"."ORDERS"."USER_ID" = "PEOPLE__via__USER_ID"."ID" 
GROUP BY CAST("PRODUCTS__via__PRODUCT_ID"."CREATED_AT" AS date), "PEOPLE__via__USER_ID"."SOURCE" 
ORDER BY CAST("PRODUCTS__via__PRODUCT_ID"."CREATED_AT" AS date) ASC, "PEOPLE__via__USER_ID"."SOURCE" ASC [90016-197]
```

**Comment by camsaul** [comment]
fixes verified

**Comment by mazameli** [comment]
@camsaul I just pulled master, restarted my server, and I'm still getting an error:

![reorder-error](https://user-images.githubusercontent.com/2223916/47528416-fcd05200-d859-11e8-8a5f-264a0d402fd1.gif)

`
org.h2.jdbc.JdbcSQLException: Column "PUBLIC.ORDERS.CREATED_AT" must be in the GROUP BY list; SQL statement: -- Metabase:: userID: 1 queryType: MBQL queryHash: e78222ebefe6959d3b811bb1d56bc3629f151d13a553aaf4a88f86a7ac8608be SELECT CAST("PUBLIC"."ORDERS"."CREATED_AT" AS date) AS "CREATED_AT", count(*) AS "count", "PUBLIC"."ORDERS"."CREATED_AT" AS "CREATED_AT" FROM "PUBLIC"."ORDERS" GROUP BY CAST("PUBLIC"."ORDERS"."CREATED_AT" AS date) ORDER BY CAST("PUBLIC"."ORDERS"."CREATED_AT" AS date) ASC [90016-197]
`
