### ISSUE TITLE
Datetime filter not working correctly (on mysql)

### ISSUE THREAD

**Issue by borisholzer** [metabase/metabase#8762]
Not sure if this is a duplicate of #7968 or #8567. Syptoms are equal (filter does not work), but cause may differ.
I run a metabase jar, metabase v0.30.4, Built on 2018-09-26 
mysql 8.0.12 on Windows 10

Steps to reproduce
- Create a query on a table that has a datatime column without a filter 
-> metabase returns all rows :heavy_check_mark:
- Create a filter on datetime column by clicking a cell in query's result table and choose the "=" option ![define filter](https://user-images.githubusercontent.com/6178049/47409456-12168500-d763-11e8-8bfd-33b98ea72f8b.PNG)
-> metabase filters correctly :heavy_check_mark:
- Adjust the filter manually by adding a adding a time
-> result set is always empty  :x:

![noresult](https://user-images.githubusercontent.com/6178049/47410480-3cb60d00-d766-11e8-8cb2-60cdc5537a65.PNG)

**Comment by mazameli** [comment]
Reproduced this, but interestingly only through the exact steps specified. But if you start with a raw data query and then manually add a date filter with a specific hour+minute added, you correctly see results.

I encountered this on both MySQL as well as Postgres, but not on Redshift.

**Comment by borisholzer** [comment]
cannot confim: Startubg with a raw data query and adding a "minute" filter manually does not work;
 Result Set is empty

**Comment by ranquild** [comment]
Fixed in `mlv2-fe-filters/chill-mode` branch only. Can be reproduced on master.

**Comment by likeshumidity** [comment]
@ranquild this supposed to be tagged with 0.48 milestone?

**Comment by darksciencebase** [comment]
@likeshumidity no, we won't be merging the `mlv2-fe-filters/chill-mode` branch to master to go out in 48, we'll let it bake
