### ISSUE TITLE
Should we hide the SQL editor entirely if you don't have write-SQL permission?

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8773]
This goes way back to issue https://github.com/metabase/metabase/issues/1689, and has also been [discussed on Discourse](http://discourse.metabase.com/t/remove-or-permanently-hide-sql-query-string-on-questions-written-in-sql/2376). 

Now that we have collection permissions to let people selectively see saved SQL questions, and we have permissions settings that let you turn off SQL editing for certain user groups, does it make sense anymore to expose the read-only view of the SQL editor on a saved question if the user doesn't have SQL editing access for that database?

If I'm not allowed to write SQL, what use is there in letting me see the SQL query? As others have commented, this feels like unfortunate surface area where we're exposing more complexity and potentially sensitive information in a case where we really don't need to.

The only additional UI considerations would be making sure SQL question filter widgets remain visible, and making sure the saved question page generally looks right without that bar. Or we go an even dumber, simpler route and just hide the `show query` button on that bar, but that feels a bit like half-assing it to me.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by crwheelr** [comment]
Not exposing the SQL for viewing has additional benefit to protect the IP of the programmer.   Understood that their might be other ways to extract the SQL, maybe from the MB database directly, but for most customers, protecting SQL code from view would give some protection.
Looking at a basic model someone wanting to generate and market a library of reports for a specific software product, if the query code is not hidden then any customer can simply replicate the queries and distribute them freely.

**Comment by crwheelr** [comment]
Has the Metabase development team considered a ACL that completely suppresses users ability to modify questions.   Giving user ability to execute and view the questions?   This would be even more effective for developers preparing packages for uses that do not have computer experience, but want to see canned report data.

Chuck

**Comment by flamber** [comment]
@crwheelr 
You can disable permissions to Data and SQL, and then give viewing permissions to specific collections. This will prevent the user from modifying the questions.

**Comment by crwheelr** [comment]
Hi @flamber,

If user had disabled permissions to data, then the canned reports cannot use that data, is this the correct way to interpret what you are saying?  I guess i am asking, how does disabling data access deny permissions to modify content in a collection?
Chuck

**Comment by flamber** [comment]
@crwheelr 
Denying data permissions just makes the user not able to make their own queries to the database.
If you only want the user to have view-access to a collection, then set it as such.
Admin > Permissions - check the Data and Collection tabs.

**Comment by crwheelr** [comment]
Thanks its clear now.   will give that a go.

appreciated,
Chuck

**Comment by crwheelr** [comment]
@flamber 
I found the solution to my issue.  Issue being that i do not want my customers to see the construction and SQL of reports/questions.    The answer is by me publishing Public Reports.    This precisely address this problem.   I just ran across Public reports yesterday.  tried it out and works beautifully to meet my needs.

Chuck

**Comment by johanjvrens** [comment]
Public reports will work in some cases, but they are sharable and you have no control over who sees them once they have been shared and reshared to people outside your Metabase users.
This may potentially leak sensitive information to the outside world.

It would be nice to hide queries for users that do not have edit permissions.

**Comment by crwheelr** [comment]
Agreed.  that was my original point.    public reports achieve this but as
noted, have insufficient security.
Chuck

**Comment by MortezaAbrari** [comment]
hi
is there any updates to hide the query of question for people who don't have permission to edit it's collection?
i don't see the point of showing the query to people...

**Comment by satya-lalam** [comment]
Is there any update on hiding the query editor, looks like there are not enough upvotes to prioritize this issue but there is a potential risk of leaking the sensitive information to non-permitted users. I hope it gets some attention.

**Comment by flamber** [comment]
@satya-lalam 
Hiding the editor is one thing, but if you have sensitive information, then you should be using `views` on your database, so Metabase doesn't see the query at all, since the query is included in all requests.

_Originally posted by @tlrobinson in https://github.com/metabase/metabase/issues/4237#issuecomment-275484332_
> We shouldn't expose SQL (both in `card.dataset_query.query` and `result.data.native_form`) to users who aren't able to write SQL questions, and likewise we shouldn't expose queries (`card.dataset_query.query`) to users who don't have sufficient data permissions to execute that query from scratch.
> 
> There will be some trickiness around the filter widgets we generate based on SQL `template_tags`, but as part of embedding the backend will need to be aware of those, and could generate `card.parameters`.
