### ISSUE TITLE
Make new native queries default to using the last-selected database

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8780]
Opening this on behalf of a user who [proposed this](https://twitter.com/dotpem/status/1055586084246056960). I think the behavior would simply be that when you click on new question -> native/sql, that it would default to whichever database you last selected in that database dropdown. This would remove a click if you tend to query the same database most of the time. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
It would probably easiest to just use the browser's `localStorage` for things like this, unless we want to add some sort of user preferences JSON object that gets persisted on the users table. The only downside of `localStorage` is it wouldn't persist for the user across multiple browsers/devices, but that seems like a pretty minor inconvenience.

**Comment by mazameli** [comment]
I totally agree. I think this is mostly about reducing friction within the context of a browser session.

**Comment by kdoh** [comment]
If we're trying to reduce friction we could also just add a user setting for "Default ask a question to SQL" so if you hit the new question button you go right to the sql editor. I'd imagine if you're writing a lot of SQL both the "SQL" choice and which DB selection are both frequent friction points.

**Comment by cshort-easyagile** [comment]
any update on this?
