### ISSUE TITLE
Dividing integers not working using Custom Expression

### ISSUE THREAD

**Issue by lenn4rd** [metabase/metabase#8783]
We work with a few metrics which involve ratios between values, e.g. the click-through rate for visitors coming to our website through paid ads. In some cases I compute these in data pipelines but in some cases it's not feasible to compute all potential derived metrics; I want our analysts to do this when they need them.

I found that when asking questions in Metabase using the custom builder it doesn't handle dividing integer values, e.g. the click-through rate defined as number of clicks over number of impressions. Adjusting the data model and defined types for these fields (e.g. Number) doesn't make a difference. If I look at the SQL generated, it looks like this:

```sql
SELECT
  (sum("table"."integer") / sum("table"."another_integer")) AS "sum / sum"
FROM "table"
```

This won't work in e.g. Postgres. Multiplying with 100 and dividing by 100 in the Custom Expressions works as intended, because the value is actually converted to a float:

```sql
SELECT
  ((sum("table"."integer") * 100.0 / sum("table"."another_integer") / 100.0) AS "(sum * ) / sum / "
FROM "table"
```

This produces the correct result. We're using Metabase v0.30.1 but I ran the same query on the most recent v0.30.4, without luck.

I don't want to change all attributes in all tables to `float`s because it feels weird to go with that type just in cause someone wants to run a division on this field at some point.

My suggestion would be that Metabase casts the affected fields to a float if it's a division (or any computation?). Let me know what you think or if there's an easier way to achieve the same result.

- Your browser and the version: Safari 12.0
- Your operating system: macOS High Sierra 10.13.6
- Your databases: Postgres 10.4
- Metabase version: v0.30.1
- Metabase hosting environment: AWS ECS
- Metabase internal database: Postgres 10.4

**Comment by ValdarT** [comment]
Also encountered this but I would classify this as a bug. This behavior does not make any sense to non-technical users. What is worse, even if you are aware of this, there doesn't seem to be a good workaround as you can't multiply the integer by 1.0 (editor will convert it to 1 for some reason) nor is there a way to cast the fields into a different type.

**Comment by lenn4rd** [comment]
I agree, it's non-intuitive. I noticed when I multiply with 1, Metabase converts it to 1.0 internally and this produces the correct result. It's shown as an integer but if you display the SQL query you can see it's a float.

**Comment by ValdarT** [comment]
The multiply with 1 trick doesn't work for me; it works when I use, e.g., 1.00000001 but not with 1.0.

**Comment by lenn4rd** [comment]
That's weird. I defined a metric using the multiplying with 1 workaround in the data model section:

![metric](https://user-images.githubusercontent.com/44819/48421916-bf2a5f00-e75d-11e8-854e-ab837091acf2.png)

which generates the following SQL query:

```sql
SELECT ((sum("public"."conversions_by_day"."qualified_leads") * 1.0) / sum("public"."conversions_by_day"."raw_leads")) AS "Conversion Rate 2"
FROM "public"."conversions_by_day"
```

Before I discovered `* 1` works (at least for me), I was multiplying with 100 and dividing by 100 for a sufficient precision, e.g. `(Sum("Form Submitted") * 100) / Sum(Sessions) / 100`.

**Comment by ValdarT** [comment]
Version difference? I'm on v0.31.0 and the query has checks agains division with 0 and multiplication with 1.
`((sum("foo"."something") * 1) / CASE WHEN sum("foo"."something_else") = 0 THEN NULL ELSE sum("foo"."something_else") END)`

**Comment by lenn4rd** [comment]
Yes, we're running on v0.30.1 still. Good to know that our current workaround won't work anymore once we upgrade.

**Comment by PauloHFM** [comment]
Same here, was working a CUSTOM question multiplying for 1 on v0.30.3 and upgraded to v0.31.1 to found this issue: all the **sum/sum** return 0

**Comment by dannyeuu** [comment]
@salsakran There is any fix on this planned? Sorry for my points, here no one knows Clojure =(

**Comment by juanjoLenero** [comment]
I can confirm that multiplying by `1.000001` works in version ( v0.31.0).

**Comment by camsaul** [comment]
Everyone here's using Postgres, right? I'm guessing when you say things "don't work" you mean 

Something like `1 / 2` is coming back as `0` instead of `0.5`, like you'd expect. Is that correct?

IIRC we're always converting divisors to floating-point before applying division if you type in numeric literals. In English: If you write a "custom expression" like `my_field / 2` we'll generate SQL like `my_field / 2.0`. For the same reasons.

So the fix is to apply a cast to float for any fields serving as the divisor of a division expression. e.g. generate SQL like `my_field / my_other_field::float` (for Postgres).

Fix should be a one-liner not counting the tests. Confirm with me that's what you guys want and I will fix.

**Comment by ValdarT** [comment]
Yes, exactly @camsaul. But I was using Redshift not Postgres. Thank you for fixing it!

**Comment by mazameli** [comment]
Do you still think this is a one-liner, @camsaul? Looks like ~4 folks have confirmed the behavior you wrote out is indeed what they're looking for.

**Comment by patricktrainer** [comment]
@mazameli @camsaul 

Ran into this scenario today as well. 

Database: Redshift
Metabase version: v0.32.4
Metabase hosting environment: AWS EB
Metabase internal database: Postgres 10.4

Workaround is to use: `((my_field * 1.1) / 1.1)` 

Looking at the generated sql from the query builder is in line with what @ValdarT experienced.
`((sum("foo"."something") * 1) / CASE WHEN sum("foo"."something_else") = 0 THEN NULL ELSE sum("foo"."something_else") END)`

**Comment by PauloHFM** [comment]
> Everyone here's using Postgres, right? I'm guessing when you say things "don't work" you mean
> 
> Something like `1 / 2` is coming back as `0` instead of `0.5`, like you'd expect. Is that correct?
> 
> IIRC we're always converting divisors to floating-point before applying division if you type in numeric literals in custom expressions. In English: If you write a custom expression like `my_field / 2` we'll generate SQL like `my_field / 2.0`. For the same reasons.
> 
> So the fix is to apply a cast to float for any fields serving as the divisor of a division expression. e.g. generate SQL like `my_field / my_other_field::float` (for Postgres) instead of `my_field / my_other_field` as we do now.
> 
> Fix should be a one-liner not counting the tests. Confirm with me that's what you guys want and I will fix.

Casting as Float fixedin raw queries that we can do. But in custom questions we have to  multiply by 1.00001 to work in a custom expression!

Thanks @camsaul!

**Comment by EBoisseauSierra** [comment]
For what it's worth, I've found that it has to do with the data type of the metrics you want to divide. 
So a quick fix is to [change the definition of your table](https://github.com/metabase/metabase/issues/10905#issuecomment-532328342) — what is, I concede, not always possible.

**Comment by lenn4rd** [comment]
For me the more important aspect of changing data types is their semantics: when I see an integer or a float or a numeric attribute on the database level, I know what to expect. I don't like the idea to change data types to something more forgiving (in terms of rounding in this case) because their meaning gets diluted and more fuzzy.

For someone who's just working with the data through e.g. Metabase that's probably not a concern though.

**Comment by EBoisseauSierra** [comment]
@lenn4rd I do agree with you — the fix is quick… and dirty I concede.

**Comment by pengfei-xue** [comment]
which release will include this fix?
