### ISSUE TITLE
Can't display a pie chart with a binned numeric dimension

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8788]
Just pulled master to make sure this hasn't been fixed recently. The error reads `Cannot read property ``getHostNode`` of null`. Breaking out by a binned date seems to work fine, and the problem seems to only be with Pie charts.

![binned-pie](https://user-images.githubusercontent.com/2223916/47584830-92c6b400-d910-11e8-8f90-796b9fcd9705.gif)

**Comment by tlrobinson** [comment]
I think this is basically the same problem as #8784. I'll fix it in #8789
