### ISSUE TITLE
Isolate series by selecting

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#8798]
Highlighting series by hovering is nice, but there are cases where completing isolating is useful. As a user, I'd like to be able to isolate series within a visualisation, by clicking on the line/bar legend, so that I can better navigate the chart and/or dashboard.

**Comment by flamber** [comment]
Hi @joshhopkins 
It sounds like you're looking for a series visibility toggle? Then this issue is a duplicate of #2697

**Comment by joshhopkins** [comment]
Appears so! Closing in favour of
https://github.com/metabase/metabase/issues/2697
