### ISSUE TITLE
Field filters don't show with view (previous issue referred)

### ISSUE THREAD

**Issue by corytu** [metabase/metabase#8800]
> I figured out the problem. It seems Metabase can't understand very well table aliases when they are used without double quotes. This only happens when using Field Filters. So, my solution was to change my query to contain all the information about the table, considering the Schema, Table Name, Column Name and put everything between double quotes.

This is related to #6748 but is probably caused by different problems. According to my recent experiences, it's not about the double quotes. Some columns serve as field filters quite well even when I don't use double quotes at all. In addition, I don't use table aliases because I don't need joins in my query to the view. This phenomenon can happen when the to-be-filtered-filed is numerical (`clinic_id`) or categorical (`locale` and `os`), so it's not about data types either.

I am running Metabase on v0.30.3, and my query which creates the view is written below:

```sql
create or replace view dashboard_demographic_view as
select
    u.id, (current_date - u.birthyear)/365 as age, u.gender,
    upper(split_part(u.locale, '_', 2)) as locale, u.lang,
    split_part(u.device_info::json ->> 'os', ' ', 1) as os,
    concat_ws('.', split_part(u.device_info::json ->> 'os', '.', 1), split_part(u.device_info::json ->> 'os', '.', 2), split_part(u.device_info::json ->> 'os', '.', 3)) as os_version,
    concat_ws('.', split_part(u.device_info::json ->> 'app_version', '.', 1), split_part(u.device_info::json ->> 'app_version', '.', 2), split_part(u.device_info::json ->> 'app_version', '.', 3)) as app_version,
    u.diabetes_type, u.diabetes_duration, u.diabetes_medication,
    c.id as clinic_id, cc.created_at as connected_at, cc.updated_at as connect_updated_at, cc.status as connect_status,
    uc.last_api_access_at, uc.last_bg_recorded_at
from health_user as u
join care_connect as cc
on u.id = cc.user_id
join clinic as c
on cc.clinic_id = c.id and c.status = 'active'
join user_cache as uc
on u.id = uc.user_id
where not u.is_tester
```

I have uploaded some screenshots also in #6748. Is more information needed? How can I provide a reproducible example in this case? Thanks.

_Originally posted by @corytu in https://github.com/metabase/metabase/issues/6748#issuecomment-433346111_

**Comment by MarkRx** [comment]
I have also seen field filters sometimes not show up in the question editor. I have not played with it enough to reproduce it. There probably is an edge case where the UI isn't handling filter additions correctly.

**Comment by corytu** [comment]
@MarkRx Thanks for your feedback. I am not sure whether the problem comes from UI or somewhere else, but like I showed in another comment https://github.com/metabase/metabase/issues/6748#issuecomment-430127260, this problem does not happen randomly. It's reproducible on my end, but I wonder how to make it reproducible to everyone here.

Only some specific columns cannot be used as field filters in my view no matter how I put them in a query. As you can see from my screenshots there,

1. When the column is selected as a field filter ("field to map to") during creating questions, there's neither "filter widget type" for me to select, nor a filter appearing above the query.
2. On a dashboard, even if the questions are not asked with SQL, metabase cannot find applicable filters for the questions.

I suspect that there may be some cases that metabase is not able to recognize the data types in a view to make those columns field filters.

**Comment by joebi3** [comment]
I am currently experiencing this issue when creating questions in the UI editor. 
I've added a new view to my database to get a subset of data and triggered a rescan of the database schema. 
The new view shows up as a data source, but the "Filtered by" and "Grouped by" drop downs are blank. 
![image](https://user-images.githubusercontent.com/29917166/48146590-38810800-e2ad-11e8-9126-ba91e7f7b2f6.png)

It appears ( according to the logs) that metabase thinks that there are no fields in the table, despite being able to display results when running a question with no filters applied. Here are the relevant sections from the log:
```
Nov 07 16:43:57 WARN metabase.query-processor.middleware.add-implicit-clauses :: Table 'stokers_conversion_history' has no Fields associated with it.
Nov 07 16:43:57 WARN metabase.query-processor.annotate :: There are fields we (maybe) weren't expecting in the results: #{:no_transactions :Conversion_Rate :dateonly :store_id :PeopleIn}
Expected: #{}
Actual: #{:no_transactions :Conversion_Rate :dateonly :store_id :PeopleIn}
```
Edit to add: this is on version v0.30.4 using chrome Version 70.0.3538.77 on Windows 10, with using mysql for the metadata and (a different server's) mysql for the data source.

**Comment by shanemgrey** [comment]
This can be easily duplicated with the Sample Database.  Simply try to use a Field Filter on Rating.  There will be no selection box showing at the top of the query.

```sql
SELECT products.* 
FROM products
WHERE {{Rating}}
```

**Comment by agoud1993** [comment]
I'm experiencing the same issue of not able to create a field filters for some columns. Please view the image with the code I've written to fix this Bug. 
Are there any suggestions to fix this Bug?
Thanks in Advance!
![metabase error filter](https://user-images.githubusercontent.com/45699622/49672739-1d372300-fa3a-11e8-9dd3-b7c0e9808483.PNG)

**Comment by flamber** [comment]
There's now a selector and a note if it isn't possible to set "Filter widget type":
![image](https://user-images.githubusercontent.com/1447303/76956628-b67b0780-6914-11ea-8167-ca5497e5f4ed.png)
For reference, the documentation explains which field types are supported:
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
