### ISSUE TITLE
qb not displaying proper join in filter section

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#882]
<img width="638" alt="screen shot 2015-08-12 at 12 29 22 pm" src="https://cloud.githubusercontent.com/assets/5248953/9234470/dbe44bac-40ed-11e5-9bd8-b18c706b134d.png">

displaying field instead of showing order -> product id

https://staging.metabase.com/q/eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2VfdGFibGUiOjgsImFnZ3JlZ2F0aW9uIjpbInJvd3MiXSwiYnJlYWtvdXQiOltdLCJmaWx0ZXIiOlsiQU5EIixbIj0iLDIyNyw2Ml1dLCJvcmRlcl9ieSI6W1syMjksImRlc2NlbmRpbmciXV19fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319

**Comment by tlrobinson** [comment]
This is fixed in master 
![screenshot 2015-10-30 14 48 25](https://cloud.githubusercontent.com/assets/18193/10858846/51d27554-7f15-11e5-87cb-50a17da8484e.png)
