### ISSUE TITLE
Conditionally show the available option from the table when using field filter

### ISSUE THREAD

**Issue by jie970326** [metabase/metabase#8821]
Can I conditionally show the list of the available options (maybe 5) for the dropdown while using field filter that map to a table column which have 20 available options?

- Current Metabase version v0.30.4

**Comment by jornh** [comment]
Is what you want similar to the enhancement request in https://github.com/metabase/metabase/issues/5540?

**Comment by walterl** [comment]
Yes, @jornh, I think it is. Closing this one as a duplicate of #5540.
