### ISSUE TITLE
Table not found: relation does not exist in SQL

### ISSUE THREAD

**Issue by listentojohan** [metabase/metabase#8823]
Hi, 
I suddenly started getting an error when running a sql query against our redshift DW. 
I get: "[Amazon](500310) Invalid operation: relation "dataset.made_up_table" does not exist".
I could query the same table a few hours ago, rescanning schema doesn't work. I can still see the table if I build a custom question however.

**Comment by salsakran** [comment]
@listentojohan the issue template includes a number of questions. If you don't mind, can you please answer them so we at least know what version you're on, etc? 

As it is, there's not nearly enough information to figure out whether there is a problem or not, let alone having an actionable bug report.

**Comment by listentojohan** [comment]
Hi @salsakran the issue got resolved, and was a mistake on my end, sorry for not including more information. This issue can be closed or deleted.
