### ISSUE TITLE
Adding Premium License Fails with 400 (0.30.4 only)

### ISSUE THREAD

**Issue by codyjroberts** [metabase/metabase#8832]
Premium key was purchased earlier today.

- Your browser and the version: Chrome 69.0.3497.100 on MacOS 10.13.6
- Your operating system: Container-Optimized OS
- Your databases: Postgres
- Metabase version: 0.30.4
- Metabase hosting environment: GKE (1.10.7-gke.2) via Helm chart v0.4.3
- Metabase internal database: Postgres 9.6 on CloudSQL

Reproduce:
1. Enter Token
![image](https://user-images.githubusercontent.com/6867961/47744312-0806f180-dc4f-11e8-814a-a262c57ba1da.png)
2. Receive Error
![image](https://user-images.githubusercontent.com/6867961/47744363-28cf4700-dc4f-11e8-90df-3f0f58c861c2.png)

We are getting a 400 from `api/setting/premium-embedding-token`. It appears the `valid_thru` and `trial` keys in the token validity request are unexpected keys.  Alas I'm not familiar with clojure.

This seems to be a more appropriate place than discourse. If not I'm happy to repost there. Thanks in advance.

**Comment by camsaul** [comment]
Hi @codyjroberts, I'm super sorry you ran into this issue. This issue only affects 0.30.4 so you can use Metabase 0.30.3 in the meantime or wait for our 0.31.0 release which should be shipping in the next week or so.

**Comment by codyjroberts** [comment]
Excellent thanks for the quick response. I'll try that now.
