### ISSUE TITLE
Dashboard / Embed Filters Failing in SQL and Query Builder

### ISSUE THREAD

**Issue by iredmedia** [metabase/metabase#8837]
- Database: Postgres
- Metabase version: 0.31.0-RC1
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

I'm using the UI to create a dashboard with filters on IDs, which result in an error when I try to query by an ID. The query JSON is as follows:

```error: "ERROR: column "field" does not exist↵  Position: 65"```

I was previously using 0.27.x and was having no trouble filtering by IDs or related entities. I've rescanned the fields and synced the schema, as well as checked the data model and all looks good. 

I've looked online and through the issues for this error but do not see it. If this is an existing issue please link and close!

Thank you

**Comment by iredmedia** [comment]
I tested in v0.31.0-RC1 and v0.27.2.

0.27.2 seems to have no problem doing filters SQL params, but when using the builder i'm getting ERROR: operator does not exist: bigint = character varying when comparing an ID. This is sort of unexpected. 

When using the UI builder for a question, I get the above error, however when using sql i get `"Error: (not (matches-some-precondition? nil))"`

I'm able to use 0.27.2 as long as I convert to SQL, but 0.3x.x is not working for me at all. Have there been changes to the Postgres integration?

**Comment by lisandrop** [comment]
I can confirm this exact issue occurs when updating from 0.30.4 to 0.31.0. Individual Questions work fine but do not load in Dashboards.

**Here is the full stacktrace:**

`Nov 11 14:49:21 WARN metabase.query-processor :: {:status :failed,
 :class org.postgresql.util.PSQLException,
 :error "ERROR: column \"field\" does not exist\n  Position: 65",
 :stacktrace
 ("org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)"
  "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)"
  "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)"
  "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)"
  "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)"
  "org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)"
  "org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)"
  "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:353)"
  "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1002)"
  "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:996)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1025)"
  "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1005)"
  "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1099)"
  "clojure.java.jdbc$query.invoke(jdbc.clj:1056)"
  "toucan.db$query.invokeStatic(db.clj:275)"
  "toucan.db$query.doInvoke(db.clj:271)"
  "clojure.lang.RestFn.invoke(RestFn.java:410)"
  "toucan.db$simple_select.invokeStatic(db.clj:379)"
  "toucan.db$simple_select.invoke(db.clj:368)"
  "toucan.db$simple_select_one.invokeStatic(db.clj:405)"
  "toucan.db$simple_select_one.invoke(db.clj:394)"
  "toucan.db$select_one.invokeStatic(db.clj:606)"
  "toucan.db$select_one.doInvoke(db.clj:599)"
  "clojure.lang.RestFn.applyTo(RestFn.java:139)"
  "clojure.core$apply.invokeStatic(core.clj:659)"
  "clojure.core$apply.invoke(core.clj:652)"
  "toucan.db$select_one_field.invokeStatic(db.clj:615)"
  "toucan.db$select_one_field.doInvoke(db.clj:608)"
  "clojure.lang.RestFn.invoke(RestFn.java:464)"
  "--> query_processor.middleware.parameters.mbql$parse_param_value_for_type.invokeStatic(mbql.clj:22)"
  "query_processor.middleware.parameters.mbql$parse_param_value_for_type.invoke(mbql.clj:13)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062$fn__33072.invoke(mbql.clj:56)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062.invoke(mbql.clj:38)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062$fn__33072$iter__33077__33081$fn__33082$fn__33083.invoke(mbql.clj:45)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062$fn__33072$iter__33077__33081$fn__33082.invoke(mbql.clj:44)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062$fn__33072.invoke(mbql.clj:44)"
  "query_processor.middleware.parameters.mbql$fn__33057$build_filter_clause__33062.invoke(mbql.clj:38)"
  "query_processor.middleware.parameters.mbql$expand.invokeStatic(mbql.clj:71)"
  "query_processor.middleware.parameters.mbql$expand.invoke(mbql.clj:58)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:18)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:12)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:43)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:49)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:46)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32507.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35249.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31708$fn__31709.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31708.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__37454$fn__37455.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:34)"
  "query_processor.store$do_with_new_store.invoke(store.clj:30)"
  "query_processor.middleware.store$initialize_store$fn__37454.invoke(store.clj:10)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:98)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:96)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:110)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:106)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__32130.invoke(cache.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__32178.invoke(catch_exceptions.clj:64)"
  "query_processor$process_query.invokeStatic(query_processor.clj:213)"
  "query_processor$process_query.invoke(query_processor.clj:209)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:322)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
  "query_processor$fn__37627$process_query_and_save_execution_BANG___37632$fn__37633.invoke(query_processor.clj:354)"
  "query_processor$fn__37627$process_query_and_save_execution_BANG___37632.invoke(query_processor.clj:340)"
  "api.card$run_query_for_card.invokeStatic(card.clj:580)"
  "api.card$run_query_for_card.doInvoke(card.clj:566)"
  "api.card$fn__42330$fn__42333.invoke(card.clj:587)"
  "api.card$fn__42330.invokeStatic(card.clj:586)"
  "api.card$fn__42330.invoke(card.clj:582)"
  "middleware$enforce_authentication$fn__55497.invoke(middleware.clj:113)"
  "api.routes$fn__55643.invokeStatic(routes.clj:62)"
  "api.routes$fn__55643.invoke(routes.clj:62)"
  "routes$fn__56385$fn__56386.doInvoke(routes.clj:108)"
  "routes$fn__56385.invokeStatic(routes.clj:103)"
  "routes$fn__56385.invoke(routes.clj:103)"
  "middleware$catch_api_exceptions$fn__55632.invoke(middleware.clj:436)"
  "middleware$log_api_call$fn__55610$fn__55612.invoke(middleware.clj:364)"
  "middleware$log_api_call$fn__55610.invoke(middleware.clj:363)"
  "middleware$add_security_headers$fn__55552.invoke(middleware.clj:252)"
  "core$wrap_streamed_json_response$fn__57236.invoke(core.clj:67)"
  "middleware$bind_current_user$fn__55502.invoke(middleware.clj:137)"
  "middleware$maybe_set_site_url$fn__55562.invoke(middleware.clj:290)"
  "middleware$add_content_type$fn__55555.invoke(middleware.clj:262)"),
 :query
 {:type :query,
  :query {:source-table 16, :aggregation [[:count]], :breakout [[:datetime-field [:field-id 7] :day]]},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters [{:type "date/relative", :target ["dimension" ["field-id" 75]], :value "past7days"} {:type "id", :target ["dimension" ["fk->" 7 8]], :value ["1" "3"]}],
  :middleware nil,
  :cache-ttl 18,
  :info
  {:executed-by 1,
   :context :question,
   :card-id 19,
   :dashboard-id nil,
   :query-hash [94, 55, 116, -112, 127, -49, 13, -41, -45, 105, 123, -29, 82, 94, -35, 86, 2, 55, 76, -108, -47, -37, 5, -52, -6, 37, 1, 3, 43, -13, -33, -45],
   :query-type "MBQL"}},
 :preprocessed nil,
 :native nil}`

**Comment by hanchang** [comment]
+1, having the same problem.

**Comment by brunocapelao** [comment]
+ 1

**Comment by eladeyal-intel** [comment]
I have the same here (Metabase v0.31.0; App database is psql ; data warehouse is mariaDB)

The query works but when put in a dashboard it fails with ```WARN metabase.query-processor :: Query failure: ERROR: column "field" does not exist Position: 65```

I tried recreating the question and the dashboard (in case it is  a migration bug) but it's still the same.

To clarify this is not SQL query in my case, it's from the GUI.

**Comment by manoloah** [comment]
+1

**Comment by camsaul** [comment]
Same issue as #9017.

Fixed by #9025

**Comment by eladeyal-intel** [comment]
I tested it on docker metabase/metabase-head and it seems OK too. thanks

**Comment by eladeyal-intel** [comment]
testing on docker metabase/metabase-head. The version I have version v0.32.0-snapshot (d119217 master)

**Comment by camsaul** [comment]
@eladeyal-intel it's fixed in the `release-0.31.2` branch, we haven't merged that into metabase-head yet

**Comment by brainsbucket** [comment]
Sorry for the duplicate issue, thanks for your fix.

**Comment by eladeyal-intel** [comment]
tested in v0.31.2, seems OK to me. thanks
