### ISSUE TITLE
Metabase server terminated unexpectedly "database may already be in use: null"

### ISSUE THREAD

**Issue by wollerman** [metabase/metabase#8839]
Running Mac OS (10.13.6) with the Mac app (version is downloaded from the website yesterday) connecting to a Postgres database using H2 internal. I was running some queries just fine until Metabase froze and then crashed. On restart I got the following error:
> The Metabase server terminated unexpectedly.
> 
> Messages:
> INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
> {:port 13976}
> INFO metabase.core :: Starting Metabase version v0.30.4 (8bf182f release-0.30.4) ...
> INFO metabase.core :: System timezone is 'America/Los_Angeles' ...
> WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
> INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
> INFO metabase.db :: Verifying h2 Database Connection ...
> ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-197]
> ERROR metabase.core :: Metabase Initialization FAILED
> java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
> (binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
> at metabase.db$verify_db_connection.invokeStatic(db.clj:387)
> at metabase.db$verify_db_connection.invoke(db.clj:380)
> at metabase.db$verify_db_connection.invokeStatic(db.clj:383)
> at metabase.db$verify_db_connection.invoke(db.clj:380)
> at metabase.db$setup_db_BANG_.invokeStatic(db.clj:449)
> at metabase.db$setup_db_BANG_.doInvoke(db.clj:443)
> at clojure.lang.RestFn.invoke(RestFn.java:421)
> at metabase.core$init_BANG_.invokeStatic(core.clj:162)
> at metabase.core$init_BANG_.invoke(core.clj:139)
> at metabase.core$start_normally.invokeStatic(core.clj:246)
> at metabase.core$start_normally.invoke(core.clj:240)
> at metabase.core$_main.invokeStatic(core.clj:266)
> at metabase.core$_main.doInvoke(core.clj:261)
> at clojure.lang.RestFn.invoke(RestFn.java:397)
> at clojure.lang.AFn.applyToHelper(AFn.java:152)
> at clojure.lang.RestFn.applyTo(RestFn.java:132)
> at metabase.core.main(Unknown Source)
> INFO metabase.core :: Metabase Shutting Down ...
> INFO metabase.core :: Metabase Shutdown COMPLETE

If I choose `Quit` or `Restart` I get the same message. I can't seem to get the app to make a good connection. Is there a way for me to kill the current connection that the exception states is already in use?

Here's a screenshot for completeness:
![image](https://user-images.githubusercontent.com/1610241/47865645-f726bf00-ddb9-11e8-88d9-de39ba31e740.png)

**Comment by wollerman** [comment]
I just did some `ps` searching and found the application that was running headless:

```
> ps -ef | grep meta
  501 17609     1   0  8:17AM ??         2:09.75 /Applications/Metabase.app/Contents/Resources/jre/bin/java -Djava.awt.headless=true -client -Xverify:none -jar /Applications/Metabase.app/Contents/Resources/metabase.jar
```

Which then can be killed (` kill -9 17609`) and metabase opens fine afterwards. Hopefully the searchable error will be helpful to others in the future!

**Comment by yb66** [comment]
Thanks for this. Just to add, I had a very similar error but found this after I'd fixed it and my "fix" may be more for people who are unsure about using a terminal.

Open `Activity Monitor` and search for "java" in  If there's more than one then click `Info` > `Open Files and Ports` and check that it's for Metabase (you'll see it listed as the parent process and in the fuller listing) and then press the `Quit` button to kill the process.


![Screenshot 2020-09-15 at 11 34 21](https://user-images.githubusercontent.com/326444/93158696-35060580-f6fc-11ea-8940-115fa43f46d9.png)


Both methods (hopefully!) end up at the same place, a working Metabase.

Regards,
iain

**Comment by flamber** [comment]
Related to #11616
