### ISSUE TITLE
Clicking on a primary key link in a table should take me straight to the detail view

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8840]
It's annoying that you have to click on the `View details` link to go to the detail view instead of just going straight there when clicking on a PK cell. 

I'm pretty sure the current behavior is a consequence of my dumb idea that this should be consistent with other cell actions, but it's a case of consistency for consistency's sake instead of ideal UX/IX.

<img width="274" alt="screen shot 2018-11-01 at 9 54 06 am" src="https://user-images.githubusercontent.com/2223916/47866507-2c341100-ddbc-11e8-991e-2ef04570c494.png">

**Comment by paulrosenzweig** [comment]
Resolved by #8860
