### ISSUE TITLE
Unable to click "Get started" label on website

### ISSUE THREAD

**Issue by mattryall** [metabase/metabase#8843]
Steps to reproduce:

- Go to https://metabase.com
- Try to click on the first "Get started" button.
- The text in the button is not clickable. You have to click on the space around the text to go to the next page.

See screencast here: https://cl.ly/f3768867d16f

Reproduced in latest versions of Chrome and Firefox.

**Comment by kdoh** [comment]
Yeesh. Thanks for reporting @mattryall. We've got a fix that should be deploying right now.
