### ISSUE TITLE
Bar chart datetime display not in order although result table already ordered in ascending

### ISSUE THREAD

**Issue by jie970326** [metabase/metabase#8847]
Inside my sql query I want to get the counting result that group by month year and order in ascending order along the time. The result table was in ascending order but when turn into bar chart it is not in order.

![1](https://user-images.githubusercontent.com/42488559/47973684-bb089c80-e0e0-11e8-9568-58a8efafa221.PNG)
![2](https://user-images.githubusercontent.com/42488559/47973685-bb089c80-e0e0-11e8-8796-e038a828c3e0.PNG)

- Chrome Version 70.0.3538.77
- Windows 10
- Metabase internal database: SQL Server
- Metabase version: v0.30.4

**Comment by jie970326** [comment]
> If you are returning a string, it will be sorted as a string.
> 
> @tlrobinson @camsaul what's the response format for months from MBQL queries?

In my query the sorting of the data is sort by the datetime

**Comment by flamber** [comment]
I cannot reproduce this on 0.35.3 unless the raw results is also in mixed order and using "X-axis scale"=`Ordinal`.
Please comment if you're still experiencing this - and please provide steps to reproduce, preferably with Sample Dataset if possible.
