### ISSUE TITLE
Report Embed Export Failed

### ISSUE THREAD

**Issue by Siddarth434** [metabase/metabase#8848]
https://github.com/metabase/metabase/pull/8629

This issue is regarding pull request Fix public/embed downloads when mounted at non-root context #8629

I have verified this issue in Metabase 0.31 RC1 and the exports for dashboard embedding works super fine but when the report is embedded the export fails. 

@tlrobinson @senior @camsaul , could you please look into this issue?

Thank you

**Comment by tlrobinson** [comment]
@Siddarth434 is this just broken for "application embedding" or also "public links"?

**Comment by Siddarth434** [comment]
Only for application embedding

**Comment by Siddarth434** [comment]
Hey guys
Any update
Im eagerly waiting for this fix

**Comment by Siddarth434** [comment]
@tlrobinson, i have many reports to be embedded but not doing for this reason. Can you please look into this

**Comment by Siddarth434** [comment]
Hi,

Is this not working only for me or others too? I am now looking for other options to Metabase. Please let me know if we are fixing this soon

**Comment by tlrobinson** [comment]
@Siddarth434 I have a fix in #9336 if you'd like to try it out.
