### ISSUE TITLE
X-rays weirdness when running jar with java -jar

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8853]
When running the 0.31 RC jar (downloaded from our site, not built locally) via the terminal with `java -jar` (vs. right-clicking on the jar file and clicking `Open`), I'm seeing some odd behavior with x-rays. **But these problems seem to go away when adding a `sudo`, like `sudo java -jar`.** The directory from where I was running the jar has these permission settings: `drwxr-xr-x  6 maz  staff  192 Nov  5 11:57 /Users/maz/Downloads/Testing 0.31-RC1`

**The observed problems:**

No x-rays or comparisons seem to be able to load. They instead show an error page with a message like `Can't create dashboard for People table`. @sbelak's working theory is that x-rays aren't getting loaded from their specification .yaml files.

I'm also seeing that some x-ray related content is not showing up on a fresh install (again, only when running the jar via java -jar):

![screen shot 2018-11-05 at 11 55 55 am](https://user-images.githubusercontent.com/2223916/48023555-062bab00-e0f3-11e8-8881-f11e089e8c81.png)

When running the jar by clicking `Open`, I see the correct content:

![screen shot 2018-11-05 at 12 00 24 pm](https://user-images.githubusercontent.com/2223916/48023573-12b00380-e0f3-11e8-93c6-082a81d2cc79.png)

**Comment by sbelak** [comment]
I still can't reproduce this. What I've tried so far:
* our RC jar and making my own
* java 1.8 and 1.10
* different starting directories 
* I've verified that read permissions in the build JAR are in place

I'm on OS X same as you

**Comment by tlrobinson** [comment]
I *am* able to reproduce this

```
java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by mazameli** [comment]
My Java setup is the same as @tlrobinson's:

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by mazameli** [comment]
Well, I just tried this again, downloading the RC from our releases page, but saving it into a different directory, `~/workspace/metabase-rc-31-testing`, instead of my Downloads folder.

X-rays would load, but the cards in them wouldn't:

![screen shot 2018-11-07 at 2 31 16 pm](https://user-images.githubusercontent.com/2223916/48165660-17172080-e29b-11e8-83bd-676434572de0.png)

I also wasn't able to query the Sample Dataset — couldn't get "connections from the underlying database" when trying to do a simple query on the sample dataset.

Worryingly, it appears like either my app db wasn't persisted, or it couldn't create one in the directory (I didn't notice which), because when I shut down the `java -jar` process and then tried running `sudo java -jar` I had to set up the instance again.

Again, running with `sudo` solved both the x-rays issue as well as the sample dataset issue.

**Comment by camsaul** [comment]
@tom @maz what directory are you running the JAR from? It sounds like maybe it doesn't have the right permissions to create files or do whatever it needs to do in that directory

That would explain why using `sudo` fixes it for maz

**Comment by mazameli** [comment]
@camsaul The first time I was running it from `~/Downloads/Testing 0.31-RC1`, second time in a new directory I created as I was downloading the jar, `~/workspace/metabase-rc-31-testing`.

If I do `ls -l` for the downloads subfolder I get: 
```
➜  Testing 0.31-RC1 ls -l
total 248392
-rw-r--r--@ 1 maz  staff  123346255 Oct 30 14:51 metabase-0.31-RC1.jar
-rw-r--r--  1 maz  staff    1347584 Nov  5 13:56 metabase.db.mv.db
-rw-r--r--  1 maz  staff        187 Nov  5 11:54 metabase.db.trace.db
```

If I do `ls -l` for `~/workspace/metabase-rc-31-testing`, I get:
```
➜  metabase-rc-31-testing ls -l
total 265016
-rw-r--r--  1 root  staff     491520 Nov  7 14:58 metabase.db.mv.db
-rw-r--r--  1 root  staff        187 Nov  7 14:38 metabase.db.trace.db
-rw-r--r--@ 1 maz   staff  123346255 Nov  7 14:25 metabase.jar
```

**Comment by sbelak** [comment]
@mazameli can you try with an older version, say 29, and see if the same happens (both in terms of xrays, and internal db)

**Comment by mazameli** [comment]
@sbelak Tried it with the 0.30.4 jar downloaded from metabase.com, ran it with java -jar, and everything worked correctly, no sudo required.

**Comment by salsakran** [comment]
@sbelak I believe this was resolved? Can you confirm, @mazameli

**Comment by mazameli** [comment]
Confirmed that I can no longer reproduce this on 0.32.10.
