### ISSUE TITLE
Support NUMERIC type for BigQuery

### ISSUE THREAD

**Issue by lmatsuura** [metabase/metabase#8855]
Hi,

[BigQuery announced a new NUMERIC data type](https://cloud.google.com/bigquery/docs/release-notes#august_20_2018) but when trying to create questions through the query builder the columns marked as NUMERIC don't show up as available fields for aggregations (Sum of..., Average of..., etc).

- Database: BigQuery
- Metabase version: v0.31.0
- Metabase internal database: H2

*Repeatable steps to reproduce the issue*
- Create a table on BigQuery with the following DML statement:
```
#standardSQL
CREATE OR REPLACE TABLE test_dataset.test_table
(
 string_col STRING,
 numeric_col NUMERIC,
 float_col FLOAT64
) AS 
SELECT *
FROM (SELECT "a", CAST(123.123 AS NUMERIC), 123.123 UNION ALL
      SELECT "b", CAST(456.456 AS NUMERIC), 456.456)
```
- Connect Metabase to the `test_dataset` dataset and try to build  a query on `test_table` via the query builder

**Comment by camsaul** [comment]
Implemented by #8898
