### ISSUE TITLE
Consolidate logic for getting a "field reference" from a result column

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#8859]
We currently have 3 similar but slightly different functions to try to guess the MBQL corresponding to a `cols` object:

* `fieldRefForColumn ` [metabase/lib/dataset](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/dataset.js#L46)
* `getFieldRefFromColumn` [metabase/modes/lib/actions](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/modes/lib/actions.js#L61)
* `StructuredQuery`'s `fieldReferenceForColumn` [metabase-lib/lib/queries/StructuredQuery](https://github.com/metabase/metabase/blob/master/frontend/src/metabase-lib/lib/queries/StructuredQuery.js#L736)
  

We should consolidate these functions, but even better would be if the backend just returned `field_ref` property containing the exact MBQL clause to refer that column on every column (except native queries, of course). It would be used for things like drill through / actions, sort indicators on column headers, identifying columns for column settings, etc. I'm not sure whether they should be wrapped in the `binning-strategy`/`datetime-field`/etc clauses (probably). For aggregations it may also be useful to have both the `["aggregation", ...]` reference, and a reference to the underlying aggregated field (maybe?)

**Comment by camsaul** [comment]
@tlrobinson as of the QP refactor all the columns are always returned in a predicatable order based on the query. That order is:

*  all `:breakout` columns, in order
*  all `:aggregation`s, in order
*  all `:field`s, in order. 

So what you could do is just add breakout + aggregation + fields and then get the field with a matching index as your col

**Comment by camsaul** [comment]
Closing as fixed by #28689
