### ISSUE TITLE
BUG: "CONTAINS" and "ENDS WITH" filter autocomplete does not work

### ISSUE THREAD

**Issue by dfx413** [metabase/metabase#8910]
Let's say I want to return total revenues of clients who bought a package, whose name contains the letters "**omf**". 
Since there is a package called "**Comfort**" the query returns desired results. 
But as you can see from the figure below, the autocomplete helper returns no results. 

![image](https://user-images.githubusercontent.com/1764151/48262173-d4cc1b80-e421-11e8-8c2e-db3d6e61f0b0.png)

When I type "Comf" the autocomplete feature returns the right result. 
![image](https://user-images.githubusercontent.com/1764151/48262578-553f4c00-e423-11e8-985d-036ee1a2fa9f.png)

That means the autocomplete feature actually always uses the "begins with" filter regardless of what filter behavior you select. (Also tested with "ends with" mode, autocomplete behaves the same).

It is a confusing behaviour because the user would expect to see values relevant to the filter setting.
Also the user is not able to see which values would actually be included in the filter when using "contains" or "ends with" mode.

**Env:**
Metabase 0.30.4
MSSQL 2016
Ubuntu 18.04.1

**Comment by flamber** [comment]
Closing, since the little autocomplete is not shown in 0.39.0 - guessing it was PR #15477
