### ISSUE TITLE
Adding a filter in native queries

### ISSUE THREAD

**Issue by ChrystynaLviv** [metabase/metabase#8911]
------
I have a problem in native query, when i select variables in where. There is no opportunity to filter it

SELECT a
FROM A 
WHERE {{c}}
![untitled](https://user-images.githubusercontent.com/44898046/48265319-e7038500-e434-11e8-9c21-1b486cfcc2a2.png)

**Comment by FallenChromium** [comment]
But you're doing it wrong way. What do you expect from this query? You wrote the filter that way so you only can choose the column that should be filtered by WHERE condition. Try WHERE *field you need to filter* = {{c}}, this should work. Should be closed though.

**Comment by salsakran** [comment]
hello @ChrystynaLviv , this is the wrong forum to ask for questions on how to use Metabase. Please look through our docs https://metabase.com/docs/latest/users-guide/13-sql-parameters.html or ask for help on our user forum (discourse.metabase.com)
