### ISSUE TITLE
Saved Questions: Uncaught Error: getFieldRefFromColumn expects non-null fieldId or column with non-null id

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#8922]
- Your browser and the version: Chrome, FF, Chrome for Android
- Your operating system: Windows 10, Android
- Your databases: MySQL, MSSQL
- Metabase version: 0.31 (Works as intended on 0.30.4, however I first noticed it in .31-RC1 snapshot!)
- Metabase hosting environment: Windows Server (Jar), Windows WSL environment 
- Metabase internal database: MySQL

- Use any saved question as data for a new question, then group and view count of rows. Try drilling down and nothing happens, you get an Uncaught Error in your console. Previously this would present either the option to view those records or to x-ray them, but that would throw an error and complain about the card_id in 0.30.4

Chrome:
![image](https://user-images.githubusercontent.com/802527/48328307-749bcc00-e611-11e8-94b5-237b66c74966.png)

Firefox
![image](https://user-images.githubusercontent.com/802527/48328332-82e9e800-e611-11e8-96d9-f31702679a26.png)

Seems possibly related to another issue: #8854 but I decided this needed its own separate issue after thinking it over. 

Link to the code in question (I think!): https://github.com/metabase/metabase/blob/master/frontend/src/metabase/qb/lib/actions.js#L61

**Comment by camsaul** [comment]
Duplicate of #8854

I'm taking a look at this @RMMSecurity
