### ISSUE TITLE
`On` Date filter broken in v0.31 for Datetime fields with visual query builder?

### ISSUE THREAD

**Issue by sherbondy** [metabase/metabase#8927]
Hey there,

We just upgraded Metabase to v0.31 from v0.30, and it seems the behavior of Date filters broke, or at least changed in an unexpected way.

Our underlying database is PostgreSQL (v9.6), and we are trying to filter a Datetime field (e.g. *created*) by the Day.

E.g.
`Order filtered by Created *on* 11/09/2018`

Returns no results, but if we use *between* 11/09/2018-11/10/2018, the results for 11/09 are successfully returned.

**On 11/09 fails** (used to work):
<img width="1023" alt="on day fails" src="https://user-images.githubusercontent.com/193187/48350403-0e389d00-e655-11e8-82ea-e053b48b3e38.png">

**Between 11/09-11/09 fails** (think this used to work too):
<img width="1072" alt="between same day fails" src="https://user-images.githubusercontent.com/193187/48350424-23adc700-e655-11e8-8703-60e448c6ef76.png">

**Between 11/09-11/10 works** (but only returns the results for 11/09, think it used to return the results for 11/09 *and* 11/10:
<img width="1398" alt="between works" src="https://user-images.githubusercontent.com/193187/48350442-36280080-e655-11e8-997c-280917d6daa4.png">

FWIW, we have the reporting time zone set to "US/Eastern" rather than UTC the system default.

**Comment by mazameli** [comment]
Reproduced this with the Orders sample table.

1. Do a new custom question using the Orders table
2. First did a raw query to see some rows and their dates to verify their presence
3. Add a filter on the Created At field using the `On` option and enter a date 
4. Run the query and you won't see any results

However, if you manually add the _time_ (hour + minute) in the filter, you will correctly see the rows. Can you verify that, @sherbondy?

**Comment by tlrobinson** [comment]
@camsaul AFAICT this is a backend issue (maybe from the query processor refactor?)

In v0.30.4:

![screenshot 2018-11-16 11 05 55](https://user-images.githubusercontent.com/18193/48641839-e7999f80-e98f-11e8-8f0d-0d5d541fc370.png)

Same (saved) question in v0.31.0

![screenshot 2018-11-16 11 06 44](https://user-images.githubusercontent.com/18193/48641851-f2eccb00-e98f-11e8-87f5-ea222659d38c.png)

Recreating a new version of the same question in v0.31.0

![screenshot 2018-11-16 11 07 15](https://user-images.githubusercontent.com/18193/48641874-01d37d80-e990-11e8-9926-8c490ca98376.png)

**Comment by camsaul** [comment]
Fixed by #8973
