### ISSUE TITLE
metabase 0.31 can't delete card in dashboard 

### ISSUE THREAD

**Issue by mengrayan** [metabase/metabase#8933]
I click the delete button but no response

**Comment by mengrayan** [comment]
![](https://blog-rayan-cc-1252204459.cos.ap-shanghai.myqcloud.com/20181113105240.png)
Firefox is OK,chrome have no response.

**Comment by mazameli** [comment]
@mengrayan Assuming you are also using Windows, this is indeed a duplicate of #2187. Closing as such.
