### ISSUE TITLE
v0.31.0 Jar is not compatible with Java 7: Start page text needs updating

### ISSUE THREAD

**Issue by aonic** [metabase/metabase#8936]
https://www.metabase.com/start/jar.html says Java 7+ is required to run the JAR file.

> Metabase requires that you have Java 7 or higher available on your system. We have run Metabase with both the OpenJDK and Oracle JDK, so feel free to use either.

However, the new JAR results in an "invalid or corrupt jarfile" error when using Java 7: _(as a point of reference, the previous JAR I was using - v0.29.2 - did work on Java 7_)

```[rajak@ip-172-xx ~]$ java -version
java version "1.7.0_181"
OpenJDK Runtime Environment (amzn-2.6.14.8.80.amzn1-x86_64 u181-b00)
OpenJDK 64-Bit Server VM (build 24.181-b00, mixed mode)

[rajak@ip-172-xx ~]$ java -jar metabase.jar
Error: Invalid or corrupt jarfile metabase.jar
```

Works correctly on Java 8:

```[rajak@ip-172-xx ~]$ /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

[rajak@ip-172-xx ~]$ /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java -jar metabase.jar
11-13 21:35:21 INFO metabase.util :: Loading Metabase...
```

**Comment by lp-lima** [comment]
I happened to me literally right now. I had metabase running on java 7 for like 3 days, since monday. All of a sudden, today, it crashed. I try to run it, and I get same error message.

**Comment by lp-lima** [comment]
I happened to me literally right now. I had metabase running on java 7 for like 3 days, since monday. All of a sudden, today, it crashed. I try to run it, and I get same error message.

**Comment by aonic** [comment]
> I happened to me literally right now. I had metabase running on java 7 for like 3 days, since monday. All of a sudden, today, it crashed. I try to run it, and I get same error message.

It was running v0.31 on Java 7 for 3 days?

**Comment by lp-lima** [comment]
Actually, it is still running right now. I don't know what - or even if - did I do, but it is running again. Gonna check it again when I get home, but yeah, running fine on Java 7.

**Comment by dfornika** [comment]
I've also got the "invalid or corrupt jarfile" error message when running v0.31.0 on Java 7 on Windows 7 Enterprise.

```
> "C:\Program Files (x86)\Java\jre7\bin\java.exe" -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) Client VM (build 24.80-b11, mixed mode, sharing)
```
```
> "C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar metabase.jar
Error: Invalid or corrupt jarfile metabase.jar
```

**Comment by camsaul** [comment]
@dfornika Metabase requires Java 8

**Comment by aonic** [comment]
@camsaul it appears 0.31 does require 8. I was previously running java 7 for older versions. This is the point of this issue, that the website needs to be updated to mention java 8+ as the required version.

**Comment by lp-lima** [comment]
How comes that my metabqse is running on Java 7, then?

**Comment by camsaul** [comment]
@lp-lima because you're using an older version of Metabase?

**Comment by lp-lima** [comment]
No... I updated mine a few days ago, straight from metabase site, using wget... I'm gonna pick a a few screenshots

**Comment by lp-lima** [comment]
![image](https://user-images.githubusercontent.com/22321989/48901989-4bafde00-ee3e-11e8-9e27-ba815a571c27.png)
![image](https://user-images.githubusercontent.com/22321989/48902044-7e59d680-ee3e-11e8-8cf4-fdf13f3c1160.png)


Am I missing something? Isn't this java 7?

**Comment by camsaul** [comment]
I guess maybe it works with OpenJDK. It didn't work for me at least with the Oracle JDK 7. 

Either way we are officially only supporting Java 8+ so it's probably not a bad idea to upgrade, especially seeing how [Java 7 was EOL'ed in April 2015](https://java.com/en/download/faq/java_7.xml)

**Comment by camsaul** [comment]
@kdoh or @salsakran can we update the webpage so it says you need Java 8?

**Comment by kdoh** [comment]
Just cut a branch to do that. Should be reflected on our next deploy once it's merged.

**Comment by camsaul** [comment]
Ok. Closing as fixed
