### ISSUE TITLE
Not Equals quick filter doesn't work

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#895]
Tried to add a "!="  quick filter on a column with a '0', and got the following error 
![screen shot 2015-08-19 at 7 26 58 pm](https://cloud.githubusercontent.com/assets/107439/9374212/6899e254-46a8-11e5-9722-cf7bdf0c9589.png)

**Comment by tlrobinson** [comment]
This is actually true of all Not Equals quick filters because we're using `≠` instead of `!=` as the operator. Ooops.
