### ISSUE TITLE
MongoDB duplicate columns

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#8950]
I'm not sure how this happened but I have a MongoDB database where Metabase has synced a bunch of duplicate/identical columns:

<img width="1653" alt="screenshot 2018-11-15 12 16 42" src="https://user-images.githubusercontent.com/18193/48579079-544d6500-e8d0-11e8-876a-b70829e1419a.png">

No matter which column I select (to breakout) the native query is identical:

```javascript
[
  { "$project": { entity_id: "$entity_id" } },
  { "$project": { _id: "$_id", ___group: { entity_id: "$entity_id" } } },
  { "$group": { _id: "$___group" } },
  { "$sort": { _id: 1 } },
  { "$project": { _id: false, entity_id: "$_id.entity_id" } },
  { "$sort": { entity_id: 1 } },
  { "$limit": 2000 }
]
```

Many of the other columns in the same table are also duplicated:

<img width="1618" alt="screenshot 2018-11-15 12 22 48" src="https://user-images.githubusercontent.com/18193/48579400-36343480-e8d1-11e8-9964-1e787221d96c.png">

**Comment by camsaul** [comment]
I think this is one of those places where if we had #669 in place we could at least catch sync in the act of trying to add duplicate columns in 

I made some tweaks to how we run migrations so we can actually selectively run them based on preconditions, e.g. we can add the constraint for people who don't have duplicates so it won't happen to people in the future

**Comment by camsaul** [comment]
Anyways, don't think this is Mongo specific. I've seen this before (e.g. #2837 and thought I had it fixed but perhaps not). I'll investigate
