### ISSUE TITLE
incubator-superset comparisson

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#8954]
Hi my pals, pls tell me if u have comparisson with incubator-superset
Stay alert

**Comment by salsakran** [comment]
We're both open source projects you can download and try out for yourself. 

I suggest you do so, the differences will be clear in about 90 seconds. 

Closing as the issue tracker is not the appropriate forum for questions like this. We use this strictly for bug reports, technical discussions etc. The user forum at http://discourse.metabase.com is a better forum for free-form questions like this.
