### ISSUE TITLE
Ensure that time series breakouts have continuous grouping values

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#896]
*User Story*: as a user performing queries that are grouped by a time granularity/extract (day, month, day-of-week, etc) I want to ensure that all possible groupings are reflected in my query result so that I don't misinterpret the data or chart the wrong trend.

This applies specifically to time based groupings, either by time granularity (hour, day, week, month) or by time extract (day-of-week, hour-of-day).  In all of these groupings there is an expectation that the result of the query will include a value for each of the continuous grouping values.

For example, if grouping by day for the last 30 days it would be expected that the query would result in 30 rows of data, one for each of the days.  If it turns out that the underlying data does not have values for a given grouping we should correct for that and supply an empty value.  The same is true for time extract groupings such as day-of-week where it would be strange to run a query grouped by day-of-week and only get back 4 rows of data for (Tuesday, Wednesday, Friday, Sunday).

**Comment by camsaul** [comment]
I have a feeling this will be ultra-hairy trying to deal with all the different possible date bucketing options we have and making it work correctly for different timezomes

**Comment by salsakran** [comment]
Yeah, sounds messy. It is something a lot of people are working around with left joins to date tables, etc.

**Comment by salsakran** [comment]
Would this be easier to deal with at the charting level? 

I'm assuming it'd be easier to do via post processing query results rather than modifying the query, but it sounds hairy either way.

**Comment by camsaul** [comment]
how many people is a lot of people?

**Comment by salsakran** [comment]
It seems like the most efficient place to do this is in the dimension definition in cross-filter. 

https://stackoverflow.com/questions/31699747/how-to-deal-with-missing-data-with-crossfilter-and-dc-js

**Comment by tlrobinson** [comment]
Implemented in #3149, will be released in v0.20.0
