### ISSUE TITLE
"Unpin" pin needs a tooltip

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#8960]
this pin-shaped icon which is used to unpin needs at least a tooltip explaining what it does.

metabase v0.31.0
running Chrome 70.0.3538.102

![image](https://user-images.githubusercontent.com/20379005/48663836-8dd3cb00-ea9e-11e8-9bb6-99f93ef06e9e.png)

**Comment by mazameli** [comment]
Pinned items don't look like this anymore, so I'm closing this.
