### ISSUE TITLE
I want to let one A user searchs only his own company's  oracle sql view, and the other user B searchs B's company view

### ISSUE THREAD

**Issue by gclsoft** [metabase/metabase#8961]
The "All Users" group has a higher level ofaccess than this, which will override thissetting. You should limit or revoke the "All Users" group's access to this item.
![image](https://user-images.githubusercontent.com/1269898/48668236-8dc9de80-eb23-11e8-860a-f56c1df26cb1.png)

I want to let one A user searchs only his own company's  oracle sql view, and the other user B searchs B's company view. But metabase likely not support this, the `All Users` must be set to a user, I can't set only my group to a user.

**Comment by FallenChromium** [comment]
Uhm... Actually issues is no right place to ask questions like this, the answer would be found faster if you'll do it there:  http://discourse.metabase.com/ . What i did in your situation is completely revoked the "All Users" privileges and created as many groups as I needed, giving each permissions for people and assigning this people to appropriate groups afterwards, that's how it should work. So just revoke everything from "all users" group.

**Comment by gclsoft** [comment]
@FallenChromium Thanks so much! It works well. 
Do you know the other question: Background running analyze data, how to stop the other users, such as `SYSMAN`,`USERNAME_BK` to analyze data, because I only need one username.

 https://github.com/metabase/metabase/issues/8955

**Comment by gclsoft** [comment]
@FallenChromium But the new group can't have `SQL QUERIES` if I only give only one table to it's `DATA ACCESS`, how can I give all the `SQL QUERIES` to it?
![image](https://user-images.githubusercontent.com/1269898/48669917-45bdb280-eb49-11e8-8afd-cca3cd86b320.png)

**Comment by salsakran** [comment]
@gclsoft please use the discussion forum to ask questions about how to use Metabase. The issue tracker is if you think you have found a bug or have a feature request.
