### ISSUE TITLE
Calendar — Missing translations

### ISSUE THREAD

**Issue by regrepl** [metabase/metabase#8964]
The Callendar is not translated on charts and tables. That means months name and days. The default setting it's to print name of the month. I know that default format can be globally changed in settings. But still it supposed to be translated.

When editing a table.
![2018-11-18 15_06_20-pytanie metabase](https://user-images.githubusercontent.com/39137187/48673692-456ee880-eb44-11e8-9900-67a490ccb978.png)

And also functions related to sorting by data on charts.
![2018-11-18 15_24_24-](https://user-images.githubusercontent.com/39137187/48673845-10fc2c00-eb46-11e8-9b88-283240003007.png)

I use Polish translation.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by ccasado-asac** [comment]
I notice the same problem too.
We also see it when asking a new question, on grouping for example:
![image](https://user-images.githubusercontent.com/47207163/52039867-f545d680-2535-11e9-8956-9bd30bbb0966.png)

I check the poe for pending texts to translate but there is none. Maybe is a date locale thing?

**Comment by flamber** [comment]
There's a lot of missing i18n - most of it is shown in issue #6674

**Comment by jlisyc** [comment]
In "formatting options" add possibility to use calendar filters dates starting on monday (now it start always a week on sunday). 

![image](https://user-images.githubusercontent.com/33416503/65748177-9b68d100-e103-11e9-925f-fa2390f50e25.png)

**Comment by flamber** [comment]
All calendar widgets (containing month names) are now English, which is a regression since 0.37.0
Fixing this, still needs to address Chinese translations too https://github.com/metabase/metabase/issues/8964#issuecomment-459365108
On 0.36.8:
![image](https://user-images.githubusercontent.com/1447303/107116794-fec94e00-6875-11eb-96e7-0aacf6211e24.png)
On 0.37.0:
![image](https://user-images.githubusercontent.com/1447303/107116827-3afcae80-6876-11eb-800d-54d74b115122.png)

**Comment by zqycn** [comment]
Calendar has not been translated into Chinese. If I want to translate in the source code, what do I need to do?

**Comment by flamber** [comment]
@zqycn The calendar has been translated, but there's a problem with Metabase and MomentJS using different `locale-dialect` - see comment https://github.com/metabase/metabase/issues/8964#issuecomment-459365108
