### ISSUE TITLE
Alerts/pulses do not work anymore after upgrade

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#8967]
Following the upgrade to 0.31.0 some alerts completelty disappeared. 
And I get the following error when trying to set up a new altert:
![image](https://user-images.githubusercontent.com/24734846/48701681-53c60e80-ebef-11e8-8f6b-d5ef134b77e2.png)

Your browser and the version: Chrome  Version 70.0.3538.77 (64-Bit)
Your operating system: Windows 10
Your databases: BigQuery
Metabase version: v0.31.0
Metabase hosting environment: Heroku

**Comment by camsaul** [comment]
I think Slack is rate-limiting us

**Comment by HelenMertes** [comment]
This is actually what the existing pulse looks like when I try to edit it:
![image](https://user-images.githubusercontent.com/24734846/48791841-ff0bbc00-ecf2-11e8-8d30-59854f3f3649.png)

The query works, but this error displayed in the pulse.

**Comment by tlrobinson** [comment]
We think this change to `bin/start` should fix this: https://github.com/metabase/metabase-deploy/commit/c8147a7af6d135e72f00e4c4ed7d34193d4829a4

You can redeploy from scratch or modify the `bin/start` in your Heroku app

**Comment by camsaul** [comment]
Fixed by #9032
