### ISSUE TITLE
Minus sign disappears in table when currency displayed in column heading

### ISSUE THREAD

**Issue by HelenMertes** [metabase/metabase#8968]
Hi,
Seems to be a bug, minus signs are not shown anymore when the column includes a currency symbol (the following numbers are negative in our table and should show a minus):
![image](https://user-images.githubusercontent.com/24734846/48712983-7ec05a80-ec0f-11e8-9b9f-42be1b50ff86.png)

When I include the € sign in every table cell, the minus is shown, but it should be there in any case!

![image](https://user-images.githubusercontent.com/24734846/48713036-a283a080-ec0f-11e8-8093-06d7adf2ee69.png)

This is the query builder view, not SQL. The minus also shows again when summing up the separate rows, so that it shows just one number.

Thanks for looking into this!

Browser and the version: Chrome Version 70.0.3538.77 (64-Bit)
Operating system: Windows 10
Databases: BigQuery
Metabase version: v0.31.0
Metabase hosting environment: Heroku

**Comment by camsaul** [comment]
Fixed by #9022
