### ISSUE TITLE
Cross-Origin Request, how to use the REST API ?

### ISSUE THREAD

**Issue by Arkellys** [metabase/metabase#8970]
I am running Metabase on a local environment using the .jar file.

When I try to make a GET or a POST request to the API (local), I get a `Cross-Origin Request` error:

> CORS header 'Access-Control-Allow-Origin' missing

I have searched everywhere either in the issues list or on the website and from what I have found I still can't understand if this problem is due to the local environment or if it is just not possible to make requests like this ? If so, how I am supposed to use the REST API ?

I would simply like to show embded dashboards on an application for a specific user using `.../api/dashboard/` and `.../api/session`. I am missing something ?

**Comment by tlrobinson** [comment]
Browsers are subject to the ["same origin policy"](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) for security reasons.

Server-side HTTP clients don't have that restriction so you could have your server-side code call those endpoints. You almost certainly don't want to include Metabase credentials in your client-side JavaScript code anyway.

Can you tell me a little more about your use-case? Are you trying to show a list of dashboards a specific user has access to, then embed them within your application when clicked on?

Currently to embed dashboards you either need to enable a ["public link"](https://metabase.com/docs/latest/administration-guide/12-public-links.html) or ["application embedding"](https://metabase.com/docs/latest/administration-guide/13-embedding.html) for that dashboard.

**Comment by Arkellys** [comment]
Hello @tlrobinson, thank you for your answer !

Yes that's excatly what I am trying to do. I am using a fetch on the client-side for the tests. I didn't think that the problem was due to the fact that I am calling the endpoints from there. Since I am doing that only for the tests, I guess the problem is not a problem finally.

Thank you so much for the explanations ! :)
