### ISSUE TITLE
Starting new Question from Saved Question with JOINs doesn't work

### ISSUE THREAD

**Issue by nickhamlin** [metabase/metabase#8972]
Your browser and the version: Chrome 70.0.3538.67 (Official Build) (64-bit)
Your operating system: OS X 10.12.6
Your databases: MySQL
Metabase version: 0.31.0
Metabase hosting environment: Docker
Metabase internal database: MySQL

I discovered this one while writing up https://github.com/metabase/metabase/issues/8971. 

_Repeatable steps to reproduce the issue_
1.) Use the query builder to make a sample question that references a joined table. I used Orders as the data source and applied a filter where `Product -> Category is Doohickey`
2.) Save the question
3.) In a new query builder window, choose the saved question as the data source and run the question to get the following error message

```
Column "PRODUCTS__via__PRODUCT_ID.CATEGORY" not found
```
When I saw this, I wanted to see if the issue was because of the joined table and found another error

1.) Use the query builder to make another sample question that applies a filter within the chosen data source. I used Orders again, and this time applied the filter `Created At in Previous 30 Days`
2.) Save the question
3.) In a new query builder window, choose the saved question as the data source and run the question to get the following error message
```
No method in multimethod '->honeysql' for dispatch value: [metabase.driver.h2.H2Driver :time-interval]
```
This one is particularly interesting because we're using MySQL for our metabase metadata store rather than the default H2 option.

Please let me know if there's any other info I can share!

**Comment by camsaul** [comment]
Fixed by #8981
