### ISSUE TITLE
0.31 "cumulative sum of" aggregation doesn't render on saved questions

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#8978]
When I open a saved question with a "cumulative sum of" aggregation, the aggregation appears as "Choose an aggregation". I can add a new one, then delete the old one, but I can't change it.

![image](https://user-images.githubusercontent.com/82608/48745236-75d78500-ec1f-11e8-8d07-823fd694044e.png)

browser: Chrome 70.0
os: Mac OS X
database: PostgreSQL
metabase: 0.31.0
hosting env: Elastic Beanstalk
internal db: PostgreSQL

**Comment by camsaul** [comment]
@bcherry do you see any error messages in the server logs or in the browser console?

**Comment by bcherry** [comment]
@camsaul nope - nothing that I can see

**Comment by bcherry** [comment]
This is still occurring in 0.31.1, if that's helpful.

**Comment by camsaul** [comment]
@bcherry can you add steps to repro with the sample dataset?

**Comment by camsaul** [comment]
Fixed by #9031

**Comment by bcherry** [comment]
I verified the issue is fixed in 0.31.2. Thanks!
