### ISSUE TITLE
Saved questions add-to-dashboard modal should be aware of dashboard permissions

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8996]
If I don't have Curate access to a dashboard it shouldn't be an option for me when using the add-to-dashboard modal from a saved question.

Currently I can pick a dashboard from that modal for which I only have View access, which takes me to the Edit mode for that dashboard, but then I get a permissions error if I try to save.

**Comment by flyingmachine** [comment]
@mazameli should the user be able to add questions directly to a collection (as opposed to a dashboard in the collection) if they only have View access?
