### ISSUE TITLE
"previous 7 days" + "include today" seems to not work around UTC midnight

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#9003]
I have a question on a dashboard that does a 7-day count, including today. I just noticed a discrepancy appear after UTC midnight. I'm viewing in Pacific time but our data is all in UTC. Our reporting timezone is set to US/Eastern.

Here is the raw data in table, sorted by date descending (all identifying info removed)
![image](https://user-images.githubusercontent.com/82608/48875417-d1377d80-edad-11e8-9550-fc2d0ce8de88.png)

And here is what comes back when using "previous 7 days including today":
![image](https://user-images.githubusercontent.com/82608/48875426-d694c800-edad-11e8-8b19-f5060a026ae0.png)

Notice that the entries following midnight UTC do not make it into the "previous 7 days" query. I would expect this query to essentially mean `NOW() + interval '-7 days'`.

Metabase 0.31.0 in Elastic Beanstalk, internal DB is PostgreSQL.

Our data is stored in PostgreSQL, with all times in UTC.

Bug reported from Chrome 70 on Mac OS X.

**Comment by MarkRx** [comment]
Try 0.31.1 which has a fix for include today not working (#8073)

**Comment by mbvictoria** [comment]
Closing - fixed in newer versions.
