### ISSUE TITLE
Pie chart legend follows same custom display style, instead of remaining a percentage

### ISSUE THREAD

**Issue by vitorhirota** [metabase/metabase#9004]
When setting the custom display style for a series in a pie chart, the percentage value in the legend follows the same configuration, instead of remaining as a percentage.

![image](https://user-images.githubusercontent.com/1316133/48905353-7acb4d00-ee48-11e8-8208-6307eaae53b7.png)

It changes percentages when:
- multiplying by a number
- changing minimal number of digits after decimal point
- adding suffixes

- Metabase version: 0.31.1

**Comment by paulrosenzweig** [comment]
Fixed in #10962
