### ISSUE TITLE
Proposed X-rays - switch database or turn off

### ISSUE THREAD

**Issue by RadoslawDo** [metabase/metabase#9008]
"TRY THESE X-RAYS BASED ON YOUR DATA" are based only on first (alphabetical) database connected to metabase. In our case this is not the "main" database, so all the proposed X-rays are not very relevant for us. Additionally, I can't turn them off...

**Comment by mazameli** [comment]
Turning x-rays off is supported as of 0.31 — it's a setting in the General tab. I think we can keep this issue open though to keep track of the proposal to be able to switch which DB the suggested x-rays use.

**Comment by flamber** [comment]
Closing, since it's both possible to disable X-rays completely and remove the "Try these" section.
