### ISSUE TITLE
Mysql encoding latin1, jdbc option characterEncoding=latin1 not working

### ISSUE THREAD

**Issue by etiennecallies** [metabase/metabase#9010]
- Your browser and the version:  Chrome 68.0.3440.106
- Your operating system: Debian 9
- Your databases: mysql 14.14 Distrib 5.7.24
- Metabase version: 0.30.3
- Metabase hosting environment: Ubuntu 18.04.1
- Metabase internal database: H2

Hello,
I've got a mysql database with latin1 encoding. I tried to add this jdbc option `characterEncoding=latin1` in my database settings.

Before I had:
![image](https://user-images.githubusercontent.com/7634514/48942020-05ca4700-ef1e-11e8-94a1-d271859d77a9.png)
After I have:
![image](https://user-images.githubusercontent.com/7634514/48942036-17abea00-ef1e-11e8-9604-ee3d9d06fc57.png)

But in both case, I have this kind of encoding error when I do a simple select:
![image](https://user-images.githubusercontent.com/7634514/48942070-41fda780-ef1e-11e8-8f01-8aeaebd13676.png)
And when I artificially convert result to utf-8, it's fine:
![image](https://user-images.githubusercontent.com/7634514/48942110-5a6dc200-ef1e-11e8-8d2b-6299530de44e.png)

Did I miss a configuration somewhere?
Many thanks

**Comment by camsaul** [comment]
Same underlying issue as described in #10691, merging into that
