### ISSUE TITLE
"Getting Started" steps are missing.

### ISSUE THREAD

**Issue by exSOUL** [metabase/metabase#9013]
Thank you for making great software.
I ran the installation with reference to https://www.metabase.com/docs/latest/.
Select Docker as the installation method, Version is `v0.31.0`.
 
Next, I followed "Getting Started", and I encountered an undocumented screen with choices: "Metrics", "Custom" and "Native query".
As a result of trial and error, selecting 'Custom' allowed me to reach the same screen image('images/Orders.png') as the document.

I think it would be better to add a screen missing in this document to the "Getting Started" "Asking a new question" section. Attach a screenshot of "Choose one from three" screen.

<img width="1277" alt="2018-11-24 16 07 08" src="https://user-images.githubusercontent.com/844642/48965583-5b2c5400-f003-11e8-9615-91f6115b53d8.png">

**Comment by flamber** [comment]
Closing, since this was fixed in 0.33 (I think)
