### ISSUE TITLE
Your question took too long

### ISSUE THREAD

**Issue by milesalex** [metabase/metabase#9015]
I have a query that take longer than a minute to run and the website times out when running. Is there a way to run the query and have it email me the results or have it run over night and not inside a web request?

**Comment by tlrobinson** [comment]
Metabase itself doesn't (or shouldn't) have any timeouts itself, typically this means the load balancer or some other piece of infrastructure timed out: https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html#how-to-detect-this-3

> Is there a way to run the query and have it email me the results or have it run over night and not inside a web request?

Pulses: https://metabase.com/docs/latest/users-guide/10-pulses.html

Alerts: https://metabase.com/docs/latest/users-guide/15-alerts.html
