### ISSUE TITLE
Beanstalk MySQL RDS not working when using metabase-aws-eb.zip

### ISSUE THREAD

**Issue by MarcGJA** [metabase/metabase#9021]
Metabase: ... 0.29.3, 0.30.0, 0.30.1, 0.30.2, 0.30.3, 0.30.4, 0.31.0, 0.31.1 (i.e. universal)
Hosting: AWS Elastic Beanstalk

Attempts at installing Metabase on AWS Elastic Beanstalk with MySQL fail in every case while PostgreSQL succeeds in every case w/ identical configurations.  Sizes of the Metabase EC2 and PostgreSQL/MySQL RDS instances (t2.small or t2.micro) do not affect the outcome.

Health: <b>Severe</b>
Events: Environment health has transitioned from Warning to Severe. ELB health is failing or not available for all instances.
Enhanced Health Overview - Instance Status Severe: Instance ELB health state has been "OutOfService" for 4 minutes: Instance has failed at least the UnhealthyThreshold number of health checks consecutively.

The issue is mentioned in at least one other recent GitHub post:
<a href="https://github.com/metabase/metabase/pull/8953"> "...only pgsql is supported" (GitHub Pull Request) #8953 </a>

||||||||||||||||||||||||||||||||||||||||
This is not something most users can diagnose on their own.  Unless AWS customized their MySQL versions behind the scenes there does not appear to be any logical reason why MySQL would fail while PostgreSQL succeeds with identical configurations.  Metabase team and or expert community confirmation is requested to diagnose by repeating the following steps:
||||||||||||||||||||||||||||||||||||||||

For a helpful tutorial see<a href="https://www.youtube.com/watch?v=wmJ02K8LIFk"> Build Your Analytics in 1 Hour or Less with Metabase (Youtube by Tim Abraham)</a>.  Thanks Tim!

<b>FIRST</b>, setup a VPC per <a href="https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html"> Scenario 2: VPC with Public and Private Subnets (NAT)</a>.  Only the two Public and Private Subnets on CIDR blocks 10.0.0.0/16 and 10.0.1.0/16 are necessary for this exercise with the NAT Gateway in the Private Subnet as outlined in the documentation.  

<b>SECOND</b>, follow the <a href="https://metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html">Metabase Documentation - Running Metabase on AWS Elastic Beanstalk</a>. NOTE if launching from the provided link change the AWS region in the upper right taskbar dropdown from N. Virginia to the desired region.  

<b>THIRD</b>, for AWS regions outside N. Virginia download<a href="https://downloads.metabase.com.s3.amazonaws.com/v0.31.1/metabase-aws-eb.zip"> metabase-aws-eb.zip </a> manually at the first Elastic Beanstalk screen (by the way the security certificate to this link appears expired, by-pass browser security to make an exception then download).  This is a necessary step because the file exists in AWS region us-east-1 (N. Virginia) and cannot be automatically downloaded to another region.  After selecting Docker click the Upload button to expose the link "https://downloads.metabase.com.s3.amazonaws.com/v0.31.1/metabase-aws-eb.zip" (v0.31.1 in this case, change the number for another version).  Copy-paste that into another window to download locally, select local option, and upload the zip file from your local drive (or S3 storage or wherever if not the local drive). 

<b>FOURTH</b>, at the configuration stage set the Database (red box) BEFORE setting the Network otherwise VPC selections for the Database (last two checkboxes) will be reset!  The safest thing to do is to leave that as the last modification before launching to avoid this little gotcha!  Normally for a PostgreSQL the EC2 Metabase instance is automatically setup in the Public Subnet and the RDS PostgreSQL instance is automatically setup in the Private Subnet.  With a MySQL rather than a PostgreSQL RDS configuration the MySQL RDS installation fails on the Private Subnet such the entire Metabase application fails to launch in each and every case (hence the problem).

<b>FIFTH</b>, don't forget to terminate the environment (Actions button) to avoid additional charges!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Important caveats regarding the VPC configuration for those intending to make use of a successful installation with PostgreSQL:

1) For production purposes in cases not requiring high NAT availability & provisioning offered by the costly NAT-Gateway substitute the far cheaper NAT-Instance instead (on a t2.micro to take advantage of AWS Free-tier) using the latest AMI for this purpose (at the time of this writing: amzn-ami-vpc-nat-hvm-2018.03.0.20181116-x86_64-ebs),

2) Know that this setup works well apparently because it satisfies two key criteria set out in the <a href="https://metabase.com/docs/latest/operations-guide/running-metabase-on-elastic-beanstalk.html"> Metabase Documentation - Running Metabase on AWS Elastic Beanstalk </a>namely that "<i>...the Load Balancer cannot be in more than one subnet per availability zone, and the database requires subnets in at least two availability zones.</i>".  That is because this configuration is deliberately setup to have the Public Subnet in one Availably Zone and the Private Subnet in another Availability Zone.  Although this works very well the AWS recommended pattern most often seen elsewhere for production ready high-availability configurations is to have both Public and Private Subnets in the SAME Availability Zone and have a duplicate configuration in one or more additional Availability Zones.  The intention is for the Load Balancer to distribute traffic between them in case services in one Availability Zone fail then those in another Availability Zone can pick up the load without interruption.  Perhaps someone with more expertise can clarify more precisely why the former setup works in Elastic Beanstalk in seeming contraction to AWS recommended practice.

3) VPC Peering for some AWS services is only available using the Default VPC that comes with an AWS account.  Lightsail, for example, functions as a simplified abstraction of well known AWS services within it's own custom VPC which as yet can only directly access other AWS services added on as extensions setup within a Default VPC via VPC Peering (mentioned in this <a href="https://www.youtube.com/watch?time_continue=1356&v=By8y9HFUGPM"> webinar </a> @28:45 a few months ago, documentation sought).  That means custom CIDR block VPC configurations such as the above <a href="https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html"> Scenario 2: VPC with Public and Private Subnets (NAT) </a> cannot be used in coordination with specialized AWS managed VPCs.  In such a case the custom VPC Public/Private Subnet configuration setup using CIDR blocks 10.0.0.0/16 and 10.0.1.0/16 must be duplicated manually in the Default VPC using the Default Subnets in each Availability Zone.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by MarcGJA** [comment]
MySQL v5.6.40 is the AWS default.  Could it be that the Metabase Docker image in the <a href="https://downloads.metabase.com.s3.amazonaws.com/v0.31.1/metabase-aws-eb.zip"> metabase-aws-eb.zip </a>file requires a higher or lower version on the MySQL totem pole or does that not matter?

**Comment by MarcGJA** [comment]
Additional observations:

1) MySQL RDS does in fact deploy (correction to FOURTH step above).

2) PostgreSQL RDS default configuration incorrect when launching from the documentation's link "Launch Metabase on Elastic Beanstalk" (http://downloads.metabase.com/v0.31.1/launch-aws-eb.html).  EBS Engine dropdown shows 5.6.40 which is a MySQL not a PostgreSQL version.  It still works but it's not right.  Clearing the browser's cache just in case some ghost value was to blame has no effect.  Solve by switching the DB dropdown to an sqlsever choice, for example, then select postgresql again and the default Engine version updates to 10.4 which makes more sense (some kind of fluky-ness going on here).

3) Comparing the successful PostgreSQL vs the failed MySQL deployments side by side there is no apparent difference in the Security Groups automatically set up, they follow the same exact pattern (Route Tables & ACLs play no role in the default setups).

This is going to take a Metabase team member and or an AWS Elastic Beanstalk super-user to diagnose.

**Comment by MarcGJA** [comment]
Here's a better way to reproduce this issue.  Setup an AWS approved VPC with Private/Public Subnets from their own template designed for Elastic Beanstalk per below and you'll see MySQL consistently fails whereas PostgreSQL succeeds under identical conditions:
<a href="http://downloads.metabase.com/v0.31.2/metabase-aws-eb.zip">v0.31.2  zip file</a>
<a href="https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/vpc.html">Using Elastic Beanstalk with Amazon Virtual Private Cloud (VPC with Private and Public Subnets)</a>
<a href="https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/cfn-templates/README.md">GitHub awsdocs/elastic-beanstalk-samples (vpc-privatepublic.yaml template)</a>

**Comment by ongzexuan** [comment]
Not sure if directly related, but I did run into some of the problems here. I've been trying to setup a MySQL RDS for Metabase. I believe I have resolved the VPC subnet issue, however Metabase still fails to load. I have attached the log below. The log seems to show that Postgres is still the selected driver of choice even though I had selected MySQL. The protocol error is likely due to the fact that the RDS instance is a MySQL one (I checked), while Metabase has somehow been configured to look for a Postgres one.

```-------------------------------------
/var/log/eb-docker/containers/eb-current-app/eb-7ab5b24375a6-stdouterr.log
-------------------------------------
06-13 06:33:20 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sparksql...[0m
06-13 06:33:20 [1mINFO metabase.driver[0m :: [34mRegistered driver :sparksql[0m (parents: #{:hive-like}) ðŸšš
06-13 06:33:21 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :google...[0m
06-13 06:33:21 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :google[0m  ðŸšš
06-13 06:33:21 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
06-13 06:33:21 [1mINFO plugins.dependencies[0m :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
06-13 06:33:21 [1mDEBUG plugins.initialize[0m :: [33mDependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver" "Metabase BigQuery Driver"][0m
06-13 06:33:21 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :googleanalytics...[0m
06-13 06:33:21 [1mINFO metabase.driver[0m :: [34mRegistered driver :googleanalytics[0m (parents: #{:google}) ðŸšš
06-13 06:33:21 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :bigquery...[0m
06-13 06:33:21 [1mINFO metabase.driver[0m :: [34mRegistered driver :bigquery[0m (parents: #{:sql :google}) ðŸšš
06-13 06:33:28 [1mINFO metabase.driver[0m :: [34mRegistered driver :h2[0m (parents: :sql-jdbc) ðŸšš
[32mLoad driver :h2 took 188 ms[0m
06-13 06:33:29 [1mINFO metabase.driver[0m :: [34mRegistered driver :mysql[0m (parents: :sql-jdbc) ðŸšš
[32mLoad driver :mysql took 286 ms[0m
06-13 06:33:29 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
06-13 06:33:29 [1mINFO metabase.db[0m :: [36mVerifying postgres Database Connection ...[0m
06-13 06:33:29 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql...[0m
06-13 06:33:29 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql-jdbc...[0m
06-13 06:33:29 [1mINFO metabase.driver[0m :: [33mInitializing driver :postgres...[0m
06-13 06:33:29 [1mERROR metabase.core[0m :: Metabase Initialization FAILED
java.lang.Exception: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:34)
	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.lang.Var.invoke(Var.java:393)
	at metabase.db$verify_db_connection$fn__16148.invoke(db.clj:403)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:401)
	at metabase.db$verify_db_connection.invoke(db.clj:394)
	at metabase.db$verify_db_connection.invokeStatic(db.clj:397)
	at metabase.db$verify_db_connection.invoke(db.clj:394)
	at metabase.db$setup_db_BANG_$fn__16165.invoke(db.clj:467)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:676)
	at metabase.util$do_with_us_locale.invoke(util.clj:662)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:77)
	at metabase.core$init_BANG_.invoke(core.clj:56)
	at metabase.core$start_normally.invokeStatic(core.clj:123)
	at metabase.core$start_normally.invoke(core.clj:117)
	at metabase.core$_main.invokeStatic(core.clj:143)
	at metabase.core$_main.doInvoke(core.clj:138)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at clojure.core$deref_future.invokeStatic(core.clj:2302)
	at clojure.core$future_call$reify__8439.deref(core.clj:6974)
	at clojure.core$deref.invokeStatic(core.clj:2324)
	at clojure.core$deref.invoke(core.clj:2306)
	at metabase.util$deref_with_timeout.invokeStatic(util.clj:328)
	at metabase.util$deref_with_timeout.invoke(util.clj:324)
	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:29)
	... 24 more
Caused by: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:701)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:454)
	at org.postgresql.Driver.connect(Driver.java:256)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1093)
	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1142)
	at clojure.java.jdbc$query.invoke(jdbc.clj:1126)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:123)
	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:118)
	at metabase.driver.sql_jdbc$fn__62839.invokeStatic(sql_jdbc.clj:39)
	at metabase.driver.sql_jdbc$fn__62839.invoke(sql_jdbc.clj:38)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at metabase.driver.util$can_connect_with_details_QMARK_$fn__18037.invoke(util.clj:30)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
06-13 06:33:29 [1mINFO metabase.core[0m :: Metabase Shutting Down ...
06-13 06:33:29 [1mINFO metabase.server[0m :: Shutting Down Embedded Jetty Webserver
06-13 06:33:30 [1mINFO metabase.core[0m :: Metabase Shutdown COMPLETE
06-13 06:34:11 [1mINFO metabase.util[0m :: Loading Metabase...
06-13 06:34:11 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 483.4 MB
06-13 06:35:13 [1mINFO metabase.util[0m :: Loading Metabase...
06-13 06:35:13 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 483.4 MB
06-13 06:35:21 [1mINFO util.encryption[0m :: Saved credentials encryption is DISABLED for this Metabase instance. ðŸ”“ 
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
06-13 06:35:29 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :sql[0m  ðŸšš```

**Comment by ongzexuan** [comment]
Switching over to the Postgres RDS did resolve the issue. In fact no additional VPC configuration was needed. The additional observations on 1 Dec are still apparent.

I'm not tied down to MySQL, my codebase is small enough to port some parts over to Postgres, but I would imagine this being an annoying issue for many

**Comment by MarcGJA** [comment]
Thank you @ongzexuan for posting the log, that's what I should have done in the first place!  Question is what's throwing this: 
<b>Caused by: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.</b>

Is it within Metabase itself or does it have to do with the Docker script guiding it's installation?  It'll take a Metabase team-member to figure that out.

Annoying for some, but for me it means I have to run a Postgres RDS in addition to existing MySQL& SQL Server RDS instances to get what I need to do done.  That's extra overhead, maintenance, and cost.  Plus extra hoopty-hoops to get the Metabase Postgres instance to share it's internal table data with MySQL.  All totally unnecessary if only Metabase worked based on MySQL as expected.

Yes, for me this isn't simply annoying it's a real point of pain!

**Comment by MarcGJA** [comment]
Oh, and @ongzexuan, please upvote the original post if you're so inclined so it has at least one to show up on the radar! The Metabase team uses upvotes to prioritize issues.  Thanks again for your insights!

**Comment by MarcGJA** [comment]
Proposed solution, change the AWS <a href="https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/cloudformation-elasticbeanstalk.json.template">JSON</a> CloudFormation template on line 71 from:
<b>"Value": "postgres"</b> to <b>"Value": "mysql"</b> or other supported db engine.

Those wanting to install Metabase on AWS EBS would have to create their own Docker file with the above modification, zip it up, and upload that instead.

That or the Metabase team would have to figure a way of making that line variable somehow in a way that AWS CloudFormation can understand.  An <b>if-when-then-else</b> type of statement perhaps?  

Alternatively Metabase could provide a Docker zip file for each supported db engine.

There is also a <a href="https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/launch-aws-eb.html.template">redirect</a> file that appears to be an html template setting the defaults in the ensuing AWS setup page.  If so that's of no consequence, the user can simply use the AWS dropdowns to select MySQL rather than Postgres.  

What appears to be happening on installation is once the <a href="https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/launch-aws-eb.html.template">redirect</a> html template brings up the ensuing AWS setup page if any other db engine other than Postgres is chosen using the provided dropdowns that conflicts with the AWS <a href="https://github.com/metabase/metabase/blob/master/bin/aws-eb-docker/cloudformation-elasticbeanstalk.json.template">JSON</a> CloudFormation template and the installation fails!

Thanks to @flamber for pointing us in the right direction on the Metabase discourse forum in response to this post:
<a href="https://discourse.metabase.com/t/protocol-error-for-metabase-postgres-installation-on-elastic-beanstalk/6544/2">Protocol error for Metabase Postgres installation on Elastic Beanstalk</a>

**Comment by salsakran** [comment]
The intent behind having an AWS quickstart option is to let folks that don't have strong feelings about how to set up a JVM application on AWS get sometime up and running that works.

While it's totally valid to want to use MySQL instead of PostgreSQL, at that point, you should probably roll your own beanstalk environment. 

We're going to be revisiting our hosting recommendations, but even then our goal is _not_ to provide a large number of options, but rather to make the process as simple and streamlined as possible. In an ideal world, end users never touch the application database other than to click "snapshot" before upgrading for insurance.

**Comment by salsakran** [comment]
Since this is only being talked about by 2 people, and it's not a blocker, dropping this to a P2.

**Comment by muhammedbasilsk** [comment]
+1 Same issue

**Comment by MarcGJA** [comment]
This is an issue that's more involved than what most users are technically capable of.  Theoretically MySQL will work with Beanstalk but in practice PostGres is the only option.  There are most likely several key pieces of code that would have to be modified.  It does not appear to be a simple matter of rolling out a custom deployment as noted here:
https://discourse.metabase.com/t/modify-ebs-for-mysql-rather-than-postgres/9052/4

**Comment by davidbehan** [comment]
+1 Also experiencing this and a pain now to have to set up PostgreSQL database when I could have used one of my existing MySQL ones.

**Comment by flamber** [comment]
Writing a `+1` comment makes no difference. Upvote the first post of the issue by clicking :+1:

**Comment by camsaul** [comment]
We only support MySQL 5.7+, so 5.6.x isn't going to work. RDS MySQL will work if you set it up manually, so it sounds like the issue is that `metabase-aws-eb.zip` might not work with anything other than Postgres

**Comment by camsaul** [comment]
@paoliniluis, do you know how to fix this?
