### ISSUE TITLE
Crate driver removed?

### ISSUE THREAD

**Issue by sugengsuprayogi** [metabase/metabase#9023]
Why Crate driver removed?

**Comment by camsaul** [comment]
@sugengsuprayogi the Crate driver is still available in Metabase 0.31.1. For our next major release we're considering either packaging it up as a separate plugin or rewriting it to work with our new driver architecture

**Comment by camsaul** [comment]
Hi @sugengsuprayogi, starting with Metabase 0.32.0 we're removing the CrateDB driver from the core Metabase project and instead making it available as a community-supported driver. When you upgrade to Metabase v0.32.0+, you can download the Crate driver and see instructions to install it here: https://github.com/metabase/crate-driver.
