### ISSUE TITLE
Duplicate Dashboards

### ISSUE THREAD

**Issue by diegolingokids** [metabase/metabase#9039]
Add functionality that enables to duplicate dashboard (and therefore the questions included in it) to be able modify.

ie. I have a sales dashboard for September 2018. I would love to be able to just duplicate the dashboard and then change the questions contained in it to do a October 2018 dashboard (preserving the September 2018 ones).

---> Other solution: it would be nice to just be able to change variables at a dashboard level. (this way I could duplicate dahsboard and just change variables associated with questions within dashboard)

**Comment by FilippoPetroli** [comment]
The duplicate dashboard was introduced on the last release and your other solution, change variables at a dashboard level, maybe can be done in Edit Dash > Add Filter

**Comment by kdoh** [comment]
Yup, as noted by others this was added by @MarkRx and released in 0.31.1 so you'll need to be running that version to use the feature. For your dashboard level variables point, if I understand what you're asking for @FilippoPetroli's suggestion to use dashboard should work for you. You can read more about that here. https://metabase.com/docs/latest/users-guide/08-dashboard-filters.html

**Comment by manoloah** [comment]
I have a strange error when trying to duplicate dashboard. See image attached, anyone have an idea why this error could be happening? 
<img width="557" alt="screen shot 2019-01-15 at 2 21 33 pm" src="https://user-images.githubusercontent.com/15304558/51207663-11f4d400-18d1-11e9-93eb-7667b624a307.png">

**Comment by flamber** [comment]
@manoloah 
You're probably seeing issue #8917 - which was thought to be fixed in 0.31.2, but later found that the issue you're describing was still there, so it got another fix and will be fixed in 0.32.0
