### ISSUE TITLE
Snowflake DB Data Sources are case sensitive

### ISSUE THREAD

**Issue by johnnykarate321** [metabase/metabase#9041]
### Snowflake DB Datasource Case Issue - per my notes yesterday for Cam.

A new data source is created but does not actually work. The metadata loading process fails at the Snowflake database layer but Metabase will run the "Explore this data" process infinitely. 

When I created the initial data source connection to Snowflake, it saved and pops a message that says "Your Database has been added". Upon selecting the "Explore this data" button, I believe Metabase begins to catalog all of the metadata for the data source, in this case the environment is simple and consists of 1 very large table with 1.4 billion rows.

At this point the browser windows shows scrolling messages about "doing science" with the main message saying "We’ll show you some interesting explorations of your data in just a few minutes." but this process runs forever.

Metabase is running 2 queries (from what I can see) to catalog the metadata. (From viewing History within the Snowflake environment)
![metabase case issue](https://user-images.githubusercontent.com/43764034/49169737-590e1200-f2ef-11e8-8c67-a308635d4952.png)
![metabasesnowflake](https://user-images.githubusercontent.com/43764034/49169746-5f03f300-f2ef-11e8-9447-d7904802c1a1.png)

:
1) show /* JDBC:DatabaseMetaData.getTables() */ objects in schema "taxi"."PUBLIC"
2) show /* JDBC:DatabaseMetaData.getSchemas() */ schemas like 'PUBLIC' in database "TAXI"

The first query against the show objects in schema "taxi"."PUBLIC" failed and then is re-run a second time which also fails due to the lower case database name. If I manually run the query with upper-case "TAXI", within the Snowflake environment, it will run without issue.

After modifying the database name to be UPPER case, the metadata loading process completed within 2 minutes without issue.

- Browser and the version: ( Firefox 63.0.3)
- OS:  (Windows 10 Pro)
- Databases: ( Snowflake )
- Metabase version: (V31.1)
- Metabase hosting environment: ( Elastic Beanstalk )
- Metabase internal database: (Postgres)

Attached are pics of the data source setup within Metabase and the Snowflake database error during the metadata loading process.

**Comment by camsaul** [comment]
Hey @johnnykarate321, I'm not a Snowflake expert by any means, I could use some help figuring out what the right fix is here.

Are Snowflake database names always uppercase? If so, I can add some code to always convert them to uppercase before use. If not, I think it makes sense to change the connection property label to something like `Database name (case-sensitive):`

**Comment by johnnykarate321** [comment]
Hey @camsaul 
Thanks for the note... this is my first Snowflake implementation so I think we are on even ground here, but I do have some thoughts. You'll probably have a much better idea on how to implement any changes but totally agreed on the connection property label which would easily be the easiest solution. But also note for future reference, Snowflake is currently doing an UPPER for all new data warehouse, database, tables and field names.

Other thoughts:
- Process: After reviewing a bunch of articles on the Snowflake website, it appears there is enough demand (and they're already working on changes) for implementing case insensitivity, since this is a fairly standard feature across all of the other database products out there. So short story long, if we call out a notation on the data source page for Snowflake admins to validate case sensitivity settings and compare to the Metabase setup? Since case sensitivity will probably change soon, I'd think it would be fair to make this a part of the setup process wizard and documentation.
- Data Source Validation: (Thinking out loud here) On Metabase when setting up the datasource, could a routine simply compare the value of the database names from both systems along with their cases? i.e. In my scenario if it was grabbing the database name from both systems and compared taxi : TAXI? When a new data source is created, would it be able to perform that logic during the save/validation routine?
-  metadata collection: When the Metabase "Exploring" mode is running, my expectation would have been it failed when Snowflake rejected the query, ( show /* JDBC:DatabaseMetaData.getTables() */ objects in schema "taxi"."PUBLIC" ) Any chance you know how the logic is handled to accommodate SQL Server or Oracle since both of those platforms support almost any type of case sensitivity / collation scenario. (this may be a really easy route if there is already logic supporting other platforms)

Just let me know if that makes any sense?
Much appreciated!

**Comment by camsaul** [comment]
With other DBMSes we specify the database name as parameter of the connection itself, so with something like Oracle or SQL Server won't even let you save the database if the database name is wrong. The Snowflake JDBC driver seems to ignore the `db` parameter -- see the thread I started [here](https://support.snowflake.net/s/question/0D50Z00008WTOMCSA5/jdbc-driver-bug-db-parameter-is-ignored-queries-return-error-this-session-does-not-have-a-current-database-call-use-database-or-use-a-qualified-name) -- so what happens is it connects to the warehouse regardless of what database you specify. 

When we sync the database schema, Snowflake's implementation of `DatabaseMetaData.getTables()` returns system tables and other unwanted things so we pass that database name in as the `catalog` parameter which restricts the results to that database. So this would be why none of the tables would show up if the database name is wrong.

I think the right thing to do here is to use something like `SHOW OBJECTS IN <database>` as a test when validating a connection. Let me see what I can do
