### ISSUE TITLE
MySQL Multiple Tables and Multiple Columns

### ISSUE THREAD

**Issue by goyaladitya** [metabase/metabase#9048]
Metabase Version: v0.31.1 
MySQL Version: 5.6.39

I'm getting multiple instances of a single table and inside the table multiple instances of a single column.

The tables:
![image](https://user-images.githubusercontent.com/17539148/49197297-613a8000-f3c9-11e8-94b1-79d87efcb7df.png)

The columns in one table:
![image](https://user-images.githubusercontent.com/17539148/49197387-a3fc5800-f3c9-11e8-89ff-c7f711d35863.png)

I've tried this on 2 versions of metabase: v0.29.3 and v0.31.1 but this problem persists.
I've also tried to sync database schema and re-scan field values so many times but it doesn't help.

**Comment by tlrobinson** [comment]
Possibly related to #8950.

**Comment by camsaul** [comment]
Fixed by #9220
