### ISSUE TITLE
PostgreSQL boolean values are parsed as numeric

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [metabase/metabase#9058]
Metabase version 0.31.1: PostgreSQL boolean type values are represented as numeric 0/1.
Former versions handled boolean values properly, presenting them as false/true.

**Comment by camsaul** [comment]
I'm not able to reproduce this

@SrancsikAtBitrise can you open the browser console and include the full API response when you run the query? It will include that native query that was generated.

**Comment by SrancsikAtBitrise** [comment]
Nor am I. Unfortunately, I cannot find the original example. I set up some test data, booleans are booleans, integers are integers. Thanks for looking into it.
![image](https://user-images.githubusercontent.com/39155393/50637896-111c8380-0f5c-11e9-8b03-b1ee96034fc1.png)
