### ISSUE TITLE
Limit iframe origin // referrer

### ISSUE THREAD

**Issue by JulianNorton** [metabase/metabase#9060]
Currently the iframe being generated is publicly available. The graphs can contain sensitive data and I don't want someone to be able to take the URL without being logged in.

Is it possible to restrict the Metabase iframe URL to only be allowed on certain IP addresses or domains?

For example, here is how Google does it with some of their APIs:
![screen shot 2018-11-30 at 2 25 56 pm](https://user-images.githubusercontent.com/2412992/49310327-fdd54e80-f4ab-11e8-8936-20dda957c017.png)

**Comment by MarcGJA** [comment]
@JulianNorton, Is this related to the following iframe embed issue? If so upvote it, that way the Metabase team can prioritize.
https://github.com/metabase/metabase/issues/8111

**Comment by JulianNorton** [comment]
Yes! Thank you, I must have missed the keywords to find it. I'll close it out and follow that ticket.

**Comment by tlrobinson** [comment]
@JulianNorton This might be something we eventually do, but in the meantime you could implement it in a HTTP proxy. Here's an example for Caddy https://github.com/tlrobinson/metabase-proxy-examples/blob/master/caddy-restricted/Caddyfile

**Comment by MyckeTap** [comment]
are there any near future plans to improve security in the given context?
