### ISSUE TITLE
ELK alternative

### ISSUE THREAD

**Issue by mhf-ir** [metabase/metabase#9061]
Thank you for great project.
If you consider how hard to use ELK platform you see the blank place as mongodb instead of elastic will be awesome but there is no alternative for kibana.

Some of few changes will be great for infrastructure tools.
1. Add webhook instead of hardcoding email or slack alerting.
   a. telegram also is popular platform
2. More visualize tools for infrastructure like heatmap or etc.

For collect and aggregate layer we can use fluentbit or fluentd.

More info about elk problems: [Resource eater monster :cry: ]
https://www.reddit.com/r/devops/comments/76kasy/lighter_weight_alternative_to_elk_or_graylog_stack/
https://medium.com/@abhidrona/elasticsearch-deployment-best-practices-d6c1323b25d7

**Comment by paoliniluis** [comment]
@flamber this could be closed as it relates to https://github.com/metabase/metabase/issues/1300, https://github.com/metabase/metabase/issues/14146, https://github.com/metabase/metabase/issues/2298, https://github.com/metabase/metabase/issues/5474
