### ISSUE TITLE
still issue about table names and field names mysql

### ISSUE THREAD

**Issue by johnfelipe** [metabase/metabase#9062]
in my phpmyadmin i see this:

![snag-0043](https://user-images.githubusercontent.com/428820/49331273-739ef000-f568-11e8-8177-861061653fc2.png)

Bu in my metabase spanish instance i see this:

![snag-0044](https://user-images.githubusercontent.com/428820/49331282-90d3be80-f568-11e8-97da-c52fb5d02139.png)

And not only about table names, about field names to:

phpmyadmin:
![snag-0045](https://user-images.githubusercontent.com/428820/49331300-c678a780-f568-11e8-8f20-fe34aae69be7.png)

metabase spanish instance:
![panoramica-0003](https://user-images.githubusercontent.com/428820/49331333-21120380-f569-11e8-9f7b-9312fdd66f46.png)

related:
https://github.com/metabase/metabase/issues/2490#issue-151985301

**Comment by flamber** [comment]
Hi @johnfelipe 
Go to /admin/settings/general and disable the feature "Friendly Table and Field Names", since that function currently only works with English.

**Comment by johnfelipe** [comment]
@flamber then for spanish table will be working correct?

**Comment by flamber** [comment]
@johnfelipe Unless your table/fields are in English, then it will not work correctly and should be disabled.

**Comment by johnfelipe** [comment]
is working for spanish, tnks
