### ISSUE TITLE
Corrupt H2 database

### ISSUE THREAD

**Issue by jobevers** [metabase/metabase#9063]
When trying to run metabase after an upgrade, the application pops up this error
```
The Metabase server terminated unexpectedly.

Messages:
INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
{:port 13461}
INFO metabase.core :: Starting Metabase version v0.31.1 (490b1f5 release-0.31.1) ...
INFO metabase.core :: System timezone is 'America/New_York' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
INFO metabase.db :: Verifying h2 Database Connection ...
ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: Row not found when trying to delete from index """"".I63: ( /* key:74 */ X'd12791f74bac084350e1f0206adf2cd1c56bf6a841834435b6e2035ed175dfb7', 1122, SPACE(358 /* table: 61 id: 20587 */))" [90112-197]
ERROR metabase.core :: Metabase Initialization FAILED
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
```

- Your operating system: OSX Sierra
- Your databases: postgres
- Metabase version: 0.31.1
- Metabase hosting environment: Mac app
- Metabase internal database: H2 (default)

**Comment by asyncopation** [comment]
I ran into the same issue using Postgres as the Metabase internal database.  It happened when I attempted to upgrade from 0.30.4 to 0.31.2 directly.

Workaround is to first upgrade to 0.31.0, let those migrations run, then upgrade to the latest patch release.

Hope this helps someone!

**Comment by jobevers** [comment]
When I tried to run 0.31.0, I get:
```
Messages:
INFO metabase.core :: Starting Metabase in STANDALONE mode
INFO metabase.core :: Launching Embedded Jetty Webserver with config: 
{:port 13190}
INFO metabase.core :: Starting Metabase version v0.31.0 (adf9a89 release-0.31.0) ...
INFO metabase.core :: System timezone is 'America/New_York' ...
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
INFO metabase.db :: Verifying h2 Database Connection ...
ERROR metabase.driver :: Failed to connect to database: org.h2.jdbc.JdbcSQLException: Row not found when trying to delete from index """"".I63: ( /* key:74 */ X'd12791f74bac084350e1f0206adf2cd1c56bf6a841834435b6e2035ed175dfb7', 1122, SPACE(358 /* table: 61 id: 20587 */))" [90112-197]
ERROR metabase.core :: Metabase Initialization FAILED
java.lang.AssertionError: Assert failed: Unable to connect to Metabase h2 DB.
(binding [*allow-potentailly-unsafe-connections* true] (require (quote metabase.driver)) ((resolve (quote metabase.driver/can-connect-with-details?)) engine details))
at metabase.db$verify_db_connection.invokeStatic(db.clj:390)
at metabase.db$verify_db_connection.invoke(db.clj:383)
at metabase.db$verify_db_connection.invokeStatic(db.clj:386)
at metabase.db$verify_db_connection.invoke(db.clj:383)
at metabase.db$setup_db_BANG_.invokeStatic(db.clj:452)
at metabase.db$setup_db_BANG_.doInvoke(db.clj:446)
at clojure.lang.RestFn.invoke(RestFn.java:421)
at metabase.core$init_BANG_.invokeStatic(core.clj:
```

**Comment by asyncopation** [comment]
Hmm... it looks like you've already completed part of the migration and your db is in a corrupted state:

`JdbcSQLException: Row not found when trying to delete from index """"".I63: ( /* key:74 */ X'd12791f74bac084350e1f0206adf2cd1c56bf6a841834435b6e2035ed175dfb7', 1122, SPACE(358 /* table: 61 id: 20587 */))`

Actually a nearly identical error is mentioned under the application database troubleshooting guide [here](https://github.com/metabase/metabase/blob/97f15d4e487957217623d8591e13872cfb1bef7f/docs/troubleshooting-guide/application-database.md#metabase-h2-application-database-gets-corrupted).  I would make a backup and give the recovery method in that guide a try.

In the docs it is recommended to switch from H2 to something more stable for your app database (like Postgres or MySQL).  Good luck!

**Comment by salsakran** [comment]
closing this since the honest answer is "H2 corruption happens and there's not a ton we can do about it". We suggest at the very minimum, backing up your h2 database before migrating.
