### ISSUE TITLE
Query expansion failed - Display custom foreign key value

### ISSUE THREAD

**Issue by Arkellys** [metabase/metabase#9064]
**Your browser and the version:** Firefox 63.0.3 (64 bits)
**Your operating system:** Windows 10
**Your databases:** MySQL
**Metabase version:** 0.30.4
**Metabase hosting environment:** Local ? Running the jar file from cmd.
**Metabase internal database:** H2

**Steps to reproduce the issue:**

1. Create 3 tables (*Table 1*, *Table 2*, *Table 3*)
2. Create a foreign key between *Table 1* -> *Table 2*
3. Create a foreign key between *Table 2* -> *Table 3*
4. On Metabase, configure the foreign key of *Table 2* to display another value than the ID
5. Create a new question using the Table visualization, display any fields from *Table 1* and the field from *Table 2* which has the foreign key

> Query expansion failed: could not find table 22 (FK ID = 175). Resolved tables ([fk-id table-id]): ([nil 23] [197 21])

**Step 4** is causing the problem, if I set back the displayed value to default (ID) I don't get the error.

**Comment by camsaul** [comment]
@sbelak This is almost certainly fixed by now since we reworked how to join stuff is done and added hundreds of new tests in 0.32.0. So it should be a simple matter of verifying that it's fixed

**Comment by sbelak** [comment]
Indeed. This seems to be fixed.
