### ISSUE TITLE
It says mongodb host is unreachable

### ISSUE THREAD

**Issue by ChaoLiou** [metabase/metabase#9069]
- Your browser and the version: Chrome 70
- Your operating system: CentOS
- Your databases: MongoDB
- Metabase version: v0.31.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

-------

Hi! I am facing mongodb connection problem.

```
com.mongodb.MongoTimeoutException: Timed out after 3000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=x.x.x.x:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.NoRouteToHostException: Host is unreachable (Host unreachable)}}]
```
* x.x.x.x is not localhost

I can connect with mongoose in node.js, and can connect through http on browser.(but it says "It looks like you are trying to access MongoDB over HTTP on the native driver port.")
What should I do next? thanks!

**Comment by jornh** [comment]
A better place to ask for help with configuration of database connections is https://discourse.metabase.com.

But to give you a starting point see this section in the troubleshooting guide 
https://metabase.com/docs/latest/troubleshooting-guide/datawarehouse.html

**Comment by salsakran** [comment]
as @jornh mentioned, this isn't a good place to get help with database connections. Please use our discussion forum.
