### ISSUE TITLE
"Invalid expression: Infinity" error when enabling trend lines

### ISSUE THREAD

**Issue by sbeca** [metabase/metabase#9070]
When I try and enable trend lines for the following graph:
![screen shot 2018-12-05 at 11 57 11 am](https://user-images.githubusercontent.com/1635228/49482992-980b0d00-f885-11e8-8162-fa9f1c4b4ba5.png)

I get the following:
![screen shot 2018-12-05 at 11 57 20 am](https://user-images.githubusercontent.com/1635228/49482998-9fcab180-f885-11e8-826d-a4562011c8ec.png)

My details:
- Browser and the version: Chrome 70.0.3538.110
- Operating system: macOS 10.13.6
- Database: Postgres
- Metabase version: 0.31.1
- Metabase hosting environment: App in Amazon Elastic Beanstalk and database in Amazon RDS

The raw data of this graph can be found in this CSV file: 
[query_result_2018-12-05T00_57_31.240Z.txt](https://github.com/metabase/metabase/files/2646728/query_result_2018-12-05T00_57_31.240Z.txt)

The error shown in Chrome's console is: 
[error.txt](https://github.com/metabase/metabase/files/2646730/error.txt)

**Comment by sbelak** [comment]
Fixed via #10502. Thanks (& double thanks fora report with data to reproduce, made my life much easier).
