### ISSUE TITLE
Global formatting not applied to dates in Native questions or unless `special_type` is defined in Simple/Custom questions

### ISSUE THREAD

**Issue by mlrabbitt** [metabase/metabase#9079]
Setting the global formatting settings works on the sample dataset but not for SQL Server 2008 data I'm examining:

Global formatting settings
![image](https://user-images.githubusercontent.com/11557879/49606326-0ec90880-f961-11e8-97a9-994557855d96.png)

Sample dataset
![image](https://user-images.githubusercontent.com/11557879/49606286-ed681c80-f960-11e8-8029-dde704600b0e.png)

SQL Server 2008 sample
![image](https://user-images.githubusercontent.com/11557879/49606221-c3aef580-f960-11e8-9e87-d40a34aece81.png)

Browser: Chrome latest (Win10)
DB: SQL Server 2008
Metabase: v0.31.1 JAR (Ubuntu 18.04 openjdk version "1.8.0_191")
Metabase DB: Postgres

**Comment by abmj1979** [comment]
The same thing happens in pie charts too

**Comment by tlrobinson** [comment]
I haven't tracked it down yet, but it's likely we're only looking at the `special_type` rather than `base_type` when applying the global settings.

**Comment by flamber** [comment]
This seems to be fixed - it's working on all databases with QB on 0.32.9
But requires the "Field Type" to be "Creation/Join date/timestamp", and isn't applied for SQL.
