### ISSUE TITLE
Support template variables for number question results in text boxes

### ISSUE THREAD

**Issue by bcherry** [metabase/metabase#9080]
I would love the ability to use number questions as template variables within text boxes.  Combined with the markdown support, this would add incredible power to dashboards.

Something like `{{123}}` or something which would reference a saved question with a number result.

Example usage

```
# Sales Report
**{{101}}** sales today ({{102}} yesterday)
- **{{103}}** red
- **{{104}}** blue

*{{105}} YTD*
```

**Comment by bcherry** [comment]
@tlrobinson wow, thanks! 

Using data series on the text card itself is a better idea, it's easier to organize and would probably be easier for non-technical people too.  That way you don't need to build any new question search UI to make it easy to work with, you'd just need a little help thing in the text composer that could list the available variables.

**Comment by flamber** [comment]
Closing in favor of #4392 and #6991
