### ISSUE TITLE
TypeError: "t.native['template-tags'] is undefined"

### ISSUE THREAD

**Issue by operman18** [metabase/metabase#9086]
One of my dashboard broke suddenly broke today, I've edited a few questions. This dashboard contains Smart Number so I don't want to downgrade it. The console shows me that
`
TypeError: "t.native['template-tags'] is undefined" 
`
I'm using metabase 0.31.1 (i've also tried 0.31.0 and 0.31.2) with elasticbeanstalk.

**Comment by salsakran** [comment]
can you share more information about what's on the dashboard? Is there a specific card which if removed makes the dashboard work again?

**Comment by camsaul** [comment]
My guess is what's happening here is it's looking for native query template tags in a non-native (i.e., MBQL) query, which has no `native` field

**Comment by lachesis** [comment]
I also had this problem after upgrade from 0.28 to 0.32.8. I was able to resolve it by re-assigning cards in the database. I created a new dashboard and binary-searched the cards until I found the one that was causing the error. If anyone from @metabase is interested in troubleshooting this, I can dump the relevant entries from the database.

```
select * from report_dashboardcard where dashboard_id = 44;
update report_dashboardcard set dashboard_id = 70 where id IN (271,274,278,299,90,277,304);
```

**Comment by flamber** [comment]
Closing in favor of #9299, since `t.native['template-tags'] is undefined` is the Firefox error of Chrome's `Cannot read property 'filter' of undefined`
