### ISSUE TITLE
Access Level Control malfunction

### ISSUE THREAD

**Issue by rostammi** [metabase/metabase#9088]
Hi,
I've set up Metabase in a local server in our company and so the access level control of metabase is useful for us. But there is a malfunction here:
When someone logs in and then changes his ip (by using a proxy or vpn), Metabase shows unuthorized access message, but then the Metabase uses 100% of server  CPU (for an unknown reason) and we have to kill the process. 
This will happen whenever a logged in user of Metabase changes his ip

**update:**
here are the processes of the server that are consuming 100 % of CPU
![image 1](https://user-images.githubusercontent.com/4462780/50040683-8bdd3780-005d-11e9-9cfb-3434ecf680f4.png)

**Comment by rostammi** [comment]
Any response?

**Comment by flamber** [comment]
A lot has changed since this issue was created, but without more details it's not possible to reproduce.
