### ISSUE TITLE
Mongodb: supports Joins

### ISSUE THREAD

**Issue by rjurado01** [metabase/metabase#9095]
### Feature requests and proposals

Mongodb aggregate supports joins operation through `$lookup` operator ([doc](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/)).

When you tray to filter by foreing key model attribute Metabase show this error:

```
Dec 10 12:26:11 WARN metabase.query-processor :: Query failure: foreign-keys is not supported by this driver.
```
It would be great to support this feature.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by RobertLowe** [comment]
Not sure about this as mongodb provides the BI connector which maps mysql queries in which you can use joins, under the hood it uses the `$lookup` operator which is TERRIBLY inefficient.

MongoDB and Joins don't make sense. Embedded documents are joins in a manor. 

Instead I suggest using something like https://stitchdata.com to sync mongo to postgres or which ever engine you prefer. You can use SQL Views to make for great collections of data to report from or tap into the collections directly. Stitch comes with the cost of sync delay, but to over come that you could use a mix of mongodb and postgres in metabase. `SELECT concat('https//example.com/", thing) from things` may be particularly useful in linking around. MongoDB for realtime no joins, postgres for delayed joinable analytics.

Aggregation, the lookup operator are bunk.

**Comment by diegopamio** [comment]
Any news on this? Otherwise unfortunately Metabase won't be suitable for us :(

**Comment by beingyash** [comment]
Is this issue anywhere on the metabase dev team's road map or are you still looking for more demand for this from the community?

**Comment by ishkabirkumar** [comment]
Is this feature implemented now for the lookup part??

**Comment by luizarakaki** [comment]
MongoDB $lookup:
- It behaves always like a `left outer join` in SQL ([doc link](https://www.mongodb.com/docs/manual/reference/operator/aggregation/lookup/#:~:text=Performs%20a%20left%20outer%20join%20to%20a%20collection%20in%20the%20same%20database%20to%20filter%20in%20documents%20from%20the%20%22joined%22%20collection%20for%20processing)). This should be fine as we have feature flags for each join type.
- Lookup is only available in Aggregate (pipeline) operations. This looks fine too as all our queries are pipelines.
- $lookup adds an array to the pipeline output. We need to flat this array into the table (using `$unwind`?).
- We can join nested queries by using the `pipeline` field. [Nested joins are possible](https://stackoverflow.com/questions/66031972/how-can-i-perform-nested-joins-joining-3-or-more-collections-in-a-mongodb-ag).

**Comment by stygmate** [comment]
+1 for this one ! MongoDB is a real killer when it come to push unknown datas to DB. And Metabase can be the real killer to instantly gain insight on this unknown datas... (but we got errors everywhere when it come to join :..(

**Comment by dpk89** [comment]
update?

**Comment by luizarakaki** [comment]
? This was shipped on v47
