### ISSUE TITLE
Custom mapping bug

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#9115]
- Your browser and the version: Chromium Version 70.0.3538.77 (Official Build) 
- Your operating system:  Ubuntu 16.04 (64-bit)
- Your databases: MySQL
- Metabase version: v0.30.3 Built on 2018-09-13
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

-------

- autosync is disabled, schedulling is set to hourly (big MySQL database)
- table has many FK
- `status UNSIGNED INTEGER NOT NULL`
- custom mapping status number to text name
- save
- after 1 hour custom mapping is empty, in drop down I can choose only 'original value', if I click discard and resync - I will get original values in mapping.

I expected: resync shouldn't delete my custom mapping.
schedule resync shouldn't hide custom mapping and values from drop down

![selection_010](https://user-images.githubusercontent.com/929827/49873478-05421380-fe2d-11e8-86ec-d4b447075e93.png)

**Comment by flamber** [comment]
This might be related to #8116
