### ISSUE TITLE
Field Filter that worked in v0.29.3 fails in v0.31.2

### ISSUE THREAD

**Issue by Go2ClassPoorYorick** [metabase/metabase#9118]
I am using versions v0.31.2 and v0.29.3. v0.29.3 is hosted on a docker image, v0.31.2 is run in a java jar for testing. I'm not sure this should matter, as you would expect a duplicated query to act the same across versions/platforms.

I have a query built in v0.29.3 that allows me to field filter properly, while the v0.31.2 version does not provide a box (nor an error) for the field filter.

`select 
   name,
   sum(Act_Run_Labor_hrs) as Labor_Hours, Hours_worked, 0-(sum(Act_Run_Labor_hrs)-Hours_worked) as 
   Variance, work_date
  
 from 
    (select concat(employee.First_Name,' ',employee.last_name) as Name, 
    Job_Operation_time.Act_Run_Labor_hrs, attendance.Regular_Minutes/60+OT_Minutes/60 as 
    Hours_worked, 
    Job_Operation_time.work_date from Job_Operation_time
    left join Employee on employee.employee = Job_Operation_time.employee
    left join attendance on attendance.work_date = Job_Operation_time.work_date and attendance.employee = job_operation_time.employee
where 1=1 [[and {{workday}}]] and employee.shift = 'shift-day' [[and concat(employee.First_Name,' ',employee.last_name) like {{employee}}]] and {{i}})a
group by name, Hours_worked, work_date
order by Variance`

The left image below is the query on the old version, the image on the right is the query on the new version.

![image](https://user-images.githubusercontent.com/33301123/49890127-4f1d0080-fe11-11e8-9649-4821010821f1.png)

_Originally posted by @Go2ClassPoorYorick in https://github.com/metabase/metabase/issues/6748#issuecomment-446691811_
(I created a new issue because the old one is closed, and this obviously appears to be some sort of bug/change that's not documented)

**Comment by salsakran** [comment]
are any of the tables being selected from views?

**Comment by AdamOpen** [comment]
I believe I'm having a similar issue. I'm running metabase v0.31.2 in the docker image. My query works when the variable type = 'number'. When I flip it to be field filter I get the error as follows:
![image](https://user-images.githubusercontent.com/2438526/50566794-82192c80-0d0b-11e9-8f40-bb740f19c335.png)

If I simply flip the variable type to "number", it works:
![image](https://user-images.githubusercontent.com/2438526/50566799-a6750900-0d0b-11e9-84b2-26b97326ff64.png)

If it helps, here's the log for this error:
Dec 31 19:52:36 WARN metabase.query-processor :: {:status :failed,
:class java.util.concurrent.ExecutionException,
:error "org.postgresql.util.PSQLException: ERROR: syntax error at or near \"=\"\n Position: 241",
:stacktrace
("java.util.concurrent.FutureTask.report(FutureTask.java:122)"
"java.util.concurrent.FutureTask.get(FutureTask.java:192)"
"clojure.core$deref_future.invokeStatic(core.clj:2292)"
"clojure.core$future_call$reify__8097.deref(core.clj:6894)"
"clojure.core$deref.invokeStatic(core.clj:2312)"
"clojure.core$deref.invoke(core.clj:2298)"
"--> driver.generic_sql.query_processor$cancellable_run_query.invokeStatic(query_processor.clj:620)"
"driver.generic_sql.query_processor$cancellable_run_query.invoke(query_processor.clj:612)"
"driver.generic_sql.query_processor$run_query.invokeStatic(query_processor.clj:637)"
"driver.generic_sql.query_processor$run_query.invoke(query_processor.clj:632)"
"driver.generic_sql.query_processor$do_with_auto_commit_disabled.invokeStatic(query_processor.clj:675)"
"driver.generic_sql.query_processor$do_with_auto_commit_disabled.invoke(query_processor.clj:664)"
"driver.generic_sql.query_processor$do_in_transaction$fn__57914.invoke(query_processor.clj:680)"
"driver.generic_sql.query_processor$do_in_transaction.invokeStatic(query_processor.clj:679)"
"driver.generic_sql.query_processor$do_in_transaction.invoke(query_processor.clj:678)"
"driver.generic_sql.query_processor$run_query_without_timezone.invokeStatic(query_processor.clj:696)"
"driver.generic_sql.query_processor$run_query_without_timezone.invoke(query_processor.clj:695)"
"driver.generic_sql.query_processor$execute_query$fn__57938.invoke(query_processor.clj:723)"
"driver.generic_sql.query_processor$do_with_try_catch.invokeStatic(query_processor.clj:659)"
"driver.generic_sql.query_processor$do_with_try_catch.invoke(query_processor.clj:654)"
"driver.generic_sql.query_processor$execute_query.invokeStatic(query_processor.clj:720)"
"driver.generic_sql.query_processor$execute_query.invoke(query_processor.clj:716)"
"driver$fn__29943$G__29750__29950.invoke(driver.clj:106)"
"query_processor$execute_query.invokeStatic(query_processor.clj:66)"
"query_processor$execute_query.invoke(query_processor.clj:60)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__32477.invoke(mbql_to_native.clj:36)"
"query_processor.middleware.annotate$add_column_info$fn__31198.invoke(annotate.clj:300)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__31939.invoke(cumulative_aggregations.clj:57)"
"query_processor.middleware.limit$limit$fn__32430.invoke(limit.clj:17)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__37552.invoke(results_metadata.clj:87)"
"query_processor.middleware.format_rows$format_rows$fn__32420.invoke(format_rows.clj:26)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__30542.invoke(add_dimension_projections.clj:234)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__30830.invoke(add_row_count_and_status.clj:15)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__32181.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__35350.invoke(resolve_driver.clj:15)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31376$fn__31377.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
"util.date$call_with_effective_timezone.invoke(date.clj:77)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31376.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.store$initialize_store$fn__37567$fn__37568.invoke(store.clj:11)"
"query_processor.store$do_with_new_store.invokeStatic(store.clj:34)"
"query_processor.store$do_with_new_store.invoke(store.clj:30)"
"query_processor.middleware.store$initialize_store$fn__37567.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__31798.invoke(cache.clj:127)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__31846.invoke(catch_exceptions.clj:64)"
"query_processor$process_query.invokeStatic(query_processor.clj:213)"
"query_processor$process_query.invoke(query_processor.clj:209)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:322)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737$fn__37738.invoke(query_processor.clj:354)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737.invoke(query_processor.clj:340)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761$fn__37762.invoke(query_processor.clj:373)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761.invoke(query_processor.clj:369)"
"api.dataset$fn__44259$fn__44262.invoke(dataset.clj:45)"
"api.common$fn__23158$invoke_thunk_with_keepalive__23163$fn__23164$fn__23165.invoke(common.clj:435)"),
:query
{:native
{:template-tags
{:fiscal_year_var
{:widget-type "category",
:default "2019",
:name "fiscal_year_var",
:type "dimension",
:id "0ef0b3be-7319-7abd-4479-b9922e5dc908",
:dimension ["field-id" 1026],
:display-name "Fiscal Year",
:display_name "Fiscal year var",
:required true}},
:query "SELECT SUM(billing.charge.charge) FROM billing.charge WHERE billing.charge.fiscal_year = {{fiscal_year_var}};"},
:type "native",
:parameters [],
:constraints {:max-results 10000, :max-results-bare-rows 2000},
:info
{:executed-by 1,
:context :ad-hoc,
:card-id nil,
:nested? false,
:query-hash [-53, 44, -58, -6, 15, -26, -100, -10, 85, 58, 3, 74, -90, -66, 2, -62, 9, 33, -111, 80, 99, -1, -50, 53, -29, -93, -68, 5, 85, 85, 63, 49],
:query-type "native"}}}

Dec 31 19:52:36 WARN metabase.query-processor :: Query failure: org.postgresql.util.PSQLException: ERROR: syntax error at or near "="
Position: 241
("clojure.core$ex_info.invokeStatic(core.clj:4739)"
"clojure.core$ex_info.invoke(core.clj:4739)"
"--> query_processor$assert_query_status_successful.invokeStatic(query_processor.clj:285)"
"query_processor$assert_query_status_successful.invoke(query_processor.clj:277)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:323)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:316)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737$fn__37738.invoke(query_processor.clj:354)"
"query_processor$fn__37732$process_query_and_save_execution_BANG___37737.invoke(query_processor.clj:340)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761$fn__37762.invoke(query_processor.clj:373)"
"query_processor$fn__37756$process_query_and_save_with_max_BANG___37761.invoke(query_processor.clj:369)"
"api.dataset$fn__44259$fn__44262.invoke(dataset.clj:45)"
"api.common$fn__23158$invoke_thunk_with_keepalive__23163$fn__23164$fn__23165.invoke(common.clj:435)")

**Comment by flamber** [comment]
Hi @AdamOpen 
When using the variable type Field Filter, then you should not include the column in the query.
It should just look like this:
```
SELECT SUM(billing.charge.charge) FROM billing.charge WHERE {{fiscal_year_var}};
```

**Comment by AdamOpen** [comment]
Thank you @flamber .
The query works better, but now I'm hitting a casting/type error (and I can't see any documentation on how to fix this):
![image](https://user-images.githubusercontent.com/2438526/50608353-7314b480-0e9a-11e9-9b65-6d5af761da0f.png)

**Comment by flamber** [comment]
@AdamOpen You should use https://discourse.metabase.com/ for discussing problems.
It looks like a problem where your "Fiscal Year" data type (see Admin > Settings > Data Model) is not matching.

**Comment by camsaul** [comment]
Field filters are replaced with an entire expression, e.g. `{{x}}` is replaced with `my_field = 100`. Other variable types like "number" are replaced by a single literal, e.g. `{{x}}` is replaced with `100`. So you can't just switch types back and forth without reworking your SQL query.

**Comment by Go2ClassPoorYorick** [comment]
`select name, sum(Act_Run_Labor_hrs) as Labor_Hours, Hours_worked, 0-(sum(Act_Run_Labor_hrs)-Hours_worked) as Variance, work_date from (select concat(employee.First_Name,' ',employee.last_name) as Name, Job_Operation_time.Act_Run_Labor_hrs, attendance.Regular_Minutes/60+OT_Minutes/60 as Hours_worked, Job_Operation_time.work_date from Job_Operation_time
left join Employee on employee.employee = Job_Operation_time.employee
left join attendance on attendance.work_date = Job_Operation_time.work_date and attendance.employee = job_operation_time.employee
where 1=1 [[and {{workday}}]] and employee.shift = 'sanitizedID [[and concat(employee.First_Name,' ',employee.last_name) like {{employee}}]] and {{i}})a
group by name, Hours_worked, work_date
order by Variance`

My query as entered in both systems is as above.

I do not believe this to be similar to @AdamOpen's issue, as I never explicitly get an error, the field for my last filter just never appears.

@salsakran I do not believe so, no. The entirety of the query is included in my original post, re-iterated here. The "id" field is a filter on employee, which is actually attendance.employee, which is joined without an alias above.

Is there any help to be had here? This is the only thing holding me up from updating to the newer metabase version.

**Comment by flamber** [comment]
@Go2ClassPoorYorick 
From the looks of it, you're missing "Filter widget type", so that sounds like a problem with data model.
Settings > Admin > Data Model > (your database) > Attendance (table) > Employee (column)
What's the Type for the column? Maybe try to click the cog-icon and re-scan or discard cache?

**Comment by Go2ClassPoorYorick** [comment]
@flamber 

This seems to be exactly my issue. Thank you for helping me identify the issue. I don't recall having manually set the field type in the past, but it's possible a co-worker might have made that change.

Big thanks!

**Comment by flamber** [comment]
@Go2ClassPoorYorick 
So everything is working now? If yes, then please close this issue :-)

**Comment by agoud1993** [comment]
I'm facing the same issue of not able to create a field filters for some columns. I'm unable to create a field filter for column "projectalias" in this particular query. Please view the image with the code I've written to fix this Bug. 
Are there any suggestions to fix this Bug?
Thanks in Advance!
![metabase error filter](https://user-images.githubusercontent.com/45699622/49673014-0c3ae180-fa3b-11e8-8a5a-a4288f20a88d.PNG)

**Comment by Go2ClassPoorYorick** [comment]
> @Go2ClassPoorYorick
> So everything is working now? If yes, then please close this issue :-)

I can't seem to find where to close this issue, am I even able to? I'm not sure this was a bug as much as user error, so I imagine it should be closed.
