### ISSUE TITLE
LDAP Users Defaulting to "Default" Group When LDAP Group Sync Enabled

### ISSUE THREAD

**Issue by kconti** [metabase/metabase#9122]
Environment:
- Your browser and the version: IE 11, FF 60.3.0
- Your operating system: Windows 7 64bit
- Your databases: Postgres
- Metabase version: 31.2
- Metabase hosting environment: Linux
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*
1. Set up LDAP User Sync in *Authentication* tab. (this is working great)
2. Enable "synchronize group memberships" and map accordingly to ldap groups.
     1. Distinguished Name: "cn=Project Manager,ou=ExampleGroups,dc=hq,dc=exampledomain,dc=com"
     2. Groups: "Project Manager".  (at this part it would show Project Manager and All Users are both selected
3. Add Group Search Base as we don't currently have the 'memberOf' overlay.
     1. ou=ExampleGroups,dc=hq,dc=exampledomain,dc=com
4. Save.
5. Add new user to LDAP group in LDAP system.  Have user login with LDAP credentials.
6. User shows up appropriately in People tab in Metabase, but group shows up as "Default".
7. Manually change the user's group in the dropdown in People -> Groups to something other than default or Admin
8. Have user log out and back in (if already logged in)

It seems that on login, the groups switches back from whatever I set it to to "Default.

I checked the logs and I don't see any specific errors.  What could be wrong here?

I recommend in a future release to have some sort of "LDAP test" feature to make sure the system is configured appropriately to use Users and Groups.

Any support for this current issue would be very much appreciated.

**Comment by nguyenlong89** [comment]
Me too, same issue. After change group manual, next login back to "Default" setting.

**Comment by rafalcieslak** [comment]
I have observed the same problem - some LDAP users loose their group associations when they log in. I cannot blame this on LDAP configuration, because some users do not expose this problem, even though they share identical LDAP memberships. This is difficult to troubleshoot as logs do not provide anything that seems relevant to this issue.

**Comment by mvandewouw** [comment]
Yes, observed the same issue as well

**Comment by mvandewouw** [comment]
This issue is also appearing with the new version of metabase v0.32.4

**Comment by steinmann321** [comment]
Approved. metabase v0.32.4

**Comment by kconti** [comment]
Confirmed this is still a problem in v0.32.5

**Comment by nicolasterral** [comment]
Still no support on this issue ?
I'm wondering if there are Metabase users for whom LDAP group sync is working.
The only workaround at the moment is to disable group sync (what adds a manual operation in metabase for every new user)
