### ISSUE TITLE
Wrong BigQuery SQL generated for Date when add another filter (Query Builder) - 0.31.2

### ISSUE THREAD

**Issue by anandabudi** [metabase/metabase#9127]
Hi all, there's a bug when I'm using Metabase Query Builder with BigQuery. 

At first, when I only put one date filter with `on`, everything is working correctly. Below is the screenshot.

![screen shot 2018-12-14 at 14 01 54](https://user-images.githubusercontent.com/8414151/49988409-29c2fa80-ffa9-11e8-8326-5654cd987d52.png)

And this is the SQL generated by Metabase

```sql
SELECT `mapan_data_prod_view.supply_chain_performance_view`.`arisan_group_name` AS `arisan_group_name` 
FROM `mapan_data_prod_view.supply_chain_performance_view`
WHERE timestamp_trunc(CAST(`mapan_data_prod_view.supply_chain_performance_view`.`status_date` AS timestamp), day) 
    = timestamp_trunc(CAST(timestamp('2018-12-12T00:00:00.000Z') AS timestamp), day)
LIMIT 2000
```

But, when I added another filter, I got this error.

![screen shot 2018-12-14 at 14 02 22](https://user-images.githubusercontent.com/8414151/49988417-30ea0880-ffa9-11e8-9d7a-9454e254e7da.png)

I realized that this is an error from Google BigQuery when it failed to process the query. So, I take a look at the log, and  I got this SQL snippet generated by Metabase.

```sql
SELECT `mapan_data_prod_view.supply_chain_performance_view`.`arisan_group_name` AS `arisan_group_name` 
FROM `mapan_data_prod_view.supply_chain_performance_view` 
WHERE (`mapan_data_prod_view.supply_chain_performance_view`.`status_date` 
     = timestamp('2018-12-12T00:00:00.000Z') 
  AND `mapan_data_prod_view.supply_chain_performance_view`.`status` = 'SUDAH DITERIMA KA') 
LIMIT 2000
```
And yes, when I added another filter, the syntax changes from

```sql
  timestamp_trunc(CAST(`mapan_data_prod_view.supply_chain_performance_view`.`status_date` AS timestamp), day) 
= timestamp_trunc(CAST(timestamp('2018-12-12T00:00:00.000Z') AS timestamp), day)
```

to 

```sql
 `mapan_data_prod_view.supply_chain_performance_view`.`status_date` = timestamp('2018-12-12T00:00:00.000Z')
```

Based on the example: `status_date` data type is a DATE and not a timestamp. This is not a problem if the data type is in TIMESTAMP, but isn't supposed to be handled ? 🤔 

Right now, I need to rollback again to 0.30.5, since this is a basic function, and most of my dataset is in GBQ.

Looking forward for the fix in the next release, Thanks & keep being awesome guys !

Note: 
- I'm not too sure if this issue related to this one: #9090 but I think this problem is a different problem.

**Comment by anandabudi** [comment]
@ans-4175 can you tell me the `dirty hack` that you made ? and can you please tell me which files do I need to modify ? Thanks !

**Comment by MarkRx** [comment]
Looks like a bug. The query that is generated should use the proper date type of the column. Unfortunately this is non trivial to do correctly as different databases have different date types and different ways of dealing with timezones. Even worse it isn't always correct to relay on auto cast behavior as this may sometimes confuse the optimizer.
