### ISSUE TITLE
Getting Exception while connecting to Mongo

### ISSUE THREAD

**Issue by arunkumar-vn** [metabase/metabase#9128]
Getting the following exception while trying to connect with MongoDB

 POST /api/database 400 (38 ms) (0 DB calls).
{:valid false, :dbname "java.lang.IllegalArgumentException: username can not be null", :message "java.lang.IllegalArgumentException: username can not be null"}

username and password has been specified and authMechanism=SCRAM-SHA-1 is set in AdditionalMongoConnectionStringOptions. We are using Mongo 3.6.4

**Comment by camsaul** [comment]
Hi, the username you set is passed to Mongo as a `user` property, not `username`. Can you try adding `username`  in the additional connection string options as well?

**Comment by arunkumar-vn** [comment]
> Hi, the username you set is passed to Mongo as a `user` property, not `username`. Can you try adding `username` in the additional connection string options as well?

Tried that.. not working

**Comment by salsakran** [comment]
@arunkumar-vn debugging data warehouse connectivity and credentials is outside the scope of this issue tracker. 

If you think you've found a bug, we can re-open this, but you will probably get more help on our user discussion forum (discourse.metabase.com)
