### ISSUE TITLE
Pie Chart Legends shouldn't overlap the pie chart

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#913]
See attached.
![screen shot 2015-08-26 at 12 51 29 pm](https://cloud.githubusercontent.com/assets/107439/9504395/418aabf0-4bf1-11e5-983a-0af592081381.png)

**Comment by vdhpieter** [comment]
+1

**Comment by tlrobinson** [comment]
This will be resolved when we implement the new scalable card designs from @kdoh.
