### ISSUE TITLE
MIME type error when execute script from text.js

### ISSUE THREAD

**Issue by amyuki** [metabase/metabase#9140]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version:  Chromium 71.0.3578.98 Manjaro Linux 64
- Your operating system:  Manjaro Linux
- Your databases:  Postgres
- Metabase version:  v0.31.1
- Metabase hosting environment:  Docker
- Metabase internal database:  H2 (default)

1. create a new question
2. open web dev tools and select console section, it shows "Refused to execute script from 'https://metabase.xxx.com/snippets/text.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled."

![screenshot_20181217_183659](https://user-images.githubusercontent.com/6037977/50082105-16bf5d00-022b-11e9-8fd4-b6d399c27adf.png)

**Comment by flamber** [comment]
Confirmed in 0.31.2 in Firefox. It only displays the error when selecting Native Query.

**Comment by salsakran** [comment]
are there any bugs in the native query editor as a result? I.e. is it just logging an error (which we should fix), or is something broken (which is more urgent)?

**Comment by flamber** [comment]
@salsakran No, everything seems like it should. Low priority. Could it be a legacy reference?

**Comment by amyuki** [comment]
@salsakran PR#9146 was already fix this issue.
