### ISSUE TITLE
Javascript CSP Block while running the metabase

### ISSUE THREAD

**Issue by SeethirajuGokulSaiChandan** [metabase/metabase#9141]
Hello all,

I am new to metabase. I have downloaded the metabase source code and hosted it in the Ubuntu 16.04 LTS server.When I am starting the Metabase server with the "lein ring server" command, I get "java.awt.HeadlessException". I have read some where in the github issues only that it can be ignored. Front end is built with "yarn run build-hot" command. When accessing the front end from the browser, I get the following errors

> Refused to load the script 'http://locahost:8080/app/dist/vendor.hot.bundle.js?222bfa78ab06d868cbf4' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com localhost:8080".

> Refused to load the script 'http://locahost:8080/app/dist/styles.hot.bundle.js?222bfa78ab06d868cbf4' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com localhost:8080".

> Refused to load the script 'http://locahost:8080/app/dist/app-main.hot.bundle.js?222bfa78ab06d868cbf4' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com localhost:8080".

I am attaching the snapshot from the developers tool. I have tried by adding 'unsafe-line' and meta tag with CSP permissions. But still it is not working. I am also attaching the java.awt.HeadlessException snapshot.

![developers_tool](https://user-images.githubusercontent.com/22162858/50083362-875d7e00-0219-11e9-9d45-d1ea8d44ca2b.PNG)
![run_time_exception_java_awt](https://user-images.githubusercontent.com/22162858/50083363-875d7e00-0219-11e9-816e-c9f0adaad502.PNG)

Thanks and Regards,
SGSC

**Comment by salsakran** [comment]
There's a lot going on in your error messages.

First off, what are you using as the application database? Just a local h2 filesystem? If so, do you have write permissions to that folder? 

any ideas @camsaul  or @tlrobinson ?

**Comment by camsaul** [comment]
The `HeadlessException` is thrown when it tries to open a browser window for you but can't because of the graphical environment (or lack thereof) Metabase is running in. I see it too when running on the Linux Subsystem for Windows. You can ignore that error.

Not sure why the Content Security Policy errors are popping up. The CSP explicitly allows `localhost:8080`. What browser are you using?

**Comment by SeethirajuGokulSaiChandan** [comment]
> What browser are you using?

This isn't any browser specific. I tried in Google Chrome and Mozilla Firefox and got the same error.

**Comment by flamber** [comment]
I might be missing something, but the host is not `localhost` - it's `locahost` (missing an `L` in the middle).
Doesn't that affect the CSP?

**Comment by SeethirajuGokulSaiChandan** [comment]
> I might be missing something, but the host is not `localhost` - it's `locahost` (missing an `L` in the middle).
>I might be missing something, but the host is not localhost - it's locahost (missing an L in the middle) Doesn't that affect the CSP?

Yes it affect the CSP. Actually I got Connection refused error when i used localhost:8080 initially. So i have changed the local host to my static ip(not a recommended practice), then back to localhost. While changing it back to localhost may be i have missed "l" at one place which is the reason for my error. 
Sorry for not looking at this in the first place. Now I am facing a new error "Connection Refused".  I am attaching the image with also.

Sorry and Thanks,
SGSC

![connection_refused](https://user-images.githubusercontent.com/22162858/50506183-b4255700-0a9d-11e9-8b9c-762a5d9d106c.PNG)

**Comment by flamber** [comment]
I'm not getting much information from Network - what does the Console say?

**Comment by SeethirajuGokulSaiChandan** [comment]
![connection_refused_details](https://user-images.githubusercontent.com/22162858/50509520-3b79c700-0aac-11e9-9776-ff308a7ad1cb.PNG)
![connection_refused_console](https://user-images.githubusercontent.com/22162858/50509522-3c125d80-0aac-11e9-8b29-299442bf861e.PNG)

**Comment by tlrobinson** [comment]
Where is the misspelled `locahost` coming from?

**Comment by flamber** [comment]
Closing issue because of no reply and it doesn't look like an issue with Metabase, but rather setup.
