### ISSUE TITLE
Proposal: Format SQL Query option in the Native Query Editor 

### ISSUE THREAD

**Issue by sowrabh** [metabase/metabase#9142]
## Proposal

One minor annoyance today in using the Native Query Editor in Metabase is the lack of an option to format/prettify queries.

So I propose to add a `Format Query` option to the Native Query Editor(See screenshot below for a mockup). If this is something that is of interest to the community, I can help contribute to the same.

![screenshot 2018-12-17 at 4 43 19 pm](https://user-images.githubusercontent.com/644434/50083850-0ef7bc80-021b-11e9-8f2a-f180952afab9.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by sowrabh** [comment]
Sure. I'll share a PR for an implementation for this. Let me know if that works.

**Comment by gvisniuc** [comment]
Hi there, any updates on this? Would be great to be able to format the query in the browser! 

Currently I copy paste it in the IDE the format it using an extension but that breaks when you are using variables like `{{ variable }}`.

**Comment by tbillington** [comment]
👀

**Comment by ajubin** [comment]
Hey, 

I'm writing a lot of sql queries for custom dashboard and reports, I'd love to see a "format SQL"  button to clean my mess 🧹

I've started to look at the possibilities, from my understanding we should modify this file `frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx` to add a library like this one https://github.com/sql-formatter-org/sql-formatter

The main issue here, is to support the placeholders like `{{some_input}}`, `{{#ref_to_another_table}}`, `[[AND optionnal_condition]]`

Does anyone has more info on this ?

**Comment by samuelT2** [comment]
Thumb up of for this one!

**Comment by lucasgadams** [comment]
Any update on this? Would be really nice!
