### ISSUE TITLE
Can't add linked columns to a table

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#9144]
This is on master on our stats instance. The expected behavior is that I click the plus and the column gets added to my list of visible columns in the modal, and gets added to the far right of my table. Instead, nothing happens. Not seeing any JS console errors, and the logs don't seem to have anything to say on the matter either.

![fk-cols](https://user-images.githubusercontent.com/2223916/50106845-d093da80-01e5-11e9-8dca-5a63b8ce6c72.gif)

**Comment by Yangzhaopan** [comment]
只显示9行，再说这是product的列，无法添加到order上

**Comment by MarkRx** [comment]
This is broke in 0.31.2.

**Comment by RobertLowe** [comment]
Yea, still broken in 0.32 / 0.33

Additionally, small request, but could the more column table name show the name of the foreign key its from, sometimes a table may have multiple references to the same table from different keys. It's makes the column selector even more defunct.

**Comment by RobertLowe** [comment]
Adding comment from duplicate #9672 

---

### Bug

- Your browser and the version: Latest Chrome, Latest Firefox
- Your operating system: OS X 10.13.6
- Your databases: Postgres, *mongo
- Metabase version: 31.2 & 3.2.1 & 3.3 snapshot affected
- Metabase hosting environment: Heroku /  MacOS / Remote Linux Server
- Metabase internal database: Postgres

Steps to reproduce:

Collection with foreign key:

![Screen Shot 2019-04-02 at 5 48 29 AM](https://user-images.githubusercontent.com/601141/55393688-bae3c000-550b-11e9-8869-b0977d0b6e43.png)

Get answer:

![Screen Shot 2019-04-02 at 5 48 41 AM](https://user-images.githubusercontent.com/601141/55393723-ca630900-550b-11e9-9ed8-046a740d2799.png)

Open column settings:
![Screen Shot 2019-04-02 at 5 48 57 AM](https://user-images.githubusercontent.com/601141/55452419-9f2cf800-55a5-11e9-97c5-bb11f794068c.png)

Add column
![Screen Shot 2019-04-02 at 5 49 15 AM](https://user-images.githubusercontent.com/601141/55452442-bec42080-55a5-11e9-94aa-c1c6928e2e66.png)

Expected: Column to be added.
Actual: Column not added.

Click reset defaults:

![Screen Shot 2019-04-02 at 5 49 26 AM](https://user-images.githubusercontent.com/601141/55452425-a9e78d00-55a5-11e9-825c-4e340722378a.png)

Expected: Columns to be reset to defaults
Actual: Previously selected columns added

Click more columns and reset again:
![Screen Shot 2019-04-02 at 5 49 50 AM](https://user-images.githubusercontent.com/601141/55452516-ffbc3500-55a5-11e9-98d1-58613bb448a3.png)

Expected: Columns to be reset to defaults
Actual: Previously selected columns added, even multiples of the same field

**Comment by tdsimpro** [comment]
Any update ? It's a pretty major issue

**Comment by RobertLowe** [comment]
Ping, any chance on raising this to P1?

**Comment by notrom** [comment]
This is a big issue for use too, it's hindering Metabase acceptance in our org. Agree with @RobertLowe, thanks for logging #9672, it's almost exactly the issue I was about to log.

**Comment by ejhayes** [comment]
Seeing this same issue with MySQL and Metabase Enterprise v1.1.4

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
