### ISSUE TITLE
adding a new collection to the saved questions as data source

### ISSUE THREAD

**Issue by cindybbzou** [metabase/metabase#9154]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------
I am new to metabase, I am having trouble figuring out how to add a new collection to the saved questions as data source, any ideas?

**Comment by mazameli** [comment]
Right now there are a few limitations to which saved questions can be used as a data source:

```
- Druid questions
- Google Analytics questions
- Mongo questions
- questions that use Cumulative Sum or Cumulative Count aggregations
```
If your collection only contains saved questions like the above, then that collection won't show up in the data source selector. Does this seem to be your issue?

[More about nested questions here](https://metabase.com/docs/latest/users-guide/04-asking-questions.html).

**Comment by cindybbzou** [comment]
No, my questions have simple joins, will that be a problem?

**Comment by mazameli** [comment]
No, shouldn't be a problem. Could you elaborate on what exact steps you're taking, and what you're expecting to see vs. what you're actually seeing? I'm assuming from what you've written that you're starting a new Custom question, and then in the Data dropdown you're trying to find one of your saved questions, but it's not appearing there. Is that right? Sometimes you just have to refresh the page to get them to appear.

**Comment by cindybbzou** [comment]
My problem is that I have started new collection and I need to use questions in the new collection to create reports as a data source , but it doesn't seem the new collection will automatically show up in the Data dropdown, I am assuming I need to somehow add it to the "Saved Questions", but I couldn't figure out how,  is my assumption correct? how should I do it?

**Comment by salsakran** [comment]
@cindybbzou this is not the best place to ask questions about how to use Metabase. You would probably get more eyes and help on it in our discussion forum (https://discourse.metabase.com)
