### ISSUE TITLE
UI - Group By for datetime with long names, can't change period

### ISSUE THREAD

**Issue by notrom** [metabase/metabase#9161]
- Your browser and the version: Chrome v70.0.3538.110 (Official Build) (64-bit) (but also Firefox)
- Your operating system: Windows 7
- Your databases: SQL Server
- Metabase version: v0.30.3
- Metabase hosting environment: jar file, Windows server
- Metabase internal database: Postgres

*Repeatable steps to reproduce the issue*
- Create a datetime column with a long name, for me about 36 chars the trick
- Start a new question with that field
- Add a "Group By" for that field
- Try to change it to "by month" but the entire "by ..." button on the far right is not visible so not possible
![image](https://user-images.githubusercontent.com/4504437/50319242-36a49880-052b-11e9-9cdc-06c266493df1.png)

Would probably be sufficient if the "by ..." button simply right aligned to the end of the field name, even if it obscures the field name itself. I see the "by ..." button gets "squashed" as the field name grows, maybe it could be fixed and the field name could get squashed?

Instead of this:
![image](https://user-images.githubusercontent.com/4504437/50319672-65237300-052d-11e9-8e9d-6c15d6a1cc37.png)

Maybe do this:
![image](https://user-images.githubusercontent.com/4504437/50319811-27731a00-052e-11e9-8a7b-6f8c61ae8c7a.png)

I assume it's the same with the binning on number too but have not verified.

Thanks

**Comment by MarkRx** [comment]
You might be able to zoom out in your browser to work around this.

**Comment by exabrial** [comment]
Browser zooming doesn't seem to work as a workaround. But if you right click and inspect the text of the grouping selector, then set it to 5px, you can see the whole thing and set it correctly. :)
