### ISSUE TITLE
Metabase is continuously firing up table scan queries

### ISSUE THREAD

**Issue by ayush-chauhan** [metabase/metabase#9163]
Hi,

Metabase is continuously firing up queries like this 

```
-- Metabase
SELECT "dbName"."tableName"."columnName" AS "columnName" 
FROM "dbName"."tableName" 
GROUP BY "dbName"."tableName"."columnName" 
ORDER BY "dbName"."tableName"."columnName" ASC LIMIT 5000
```

Even though my settings for the database are these

- I have turned on the toggle "This is a large database, so let me choose when Metabase syncs and scans"
- I have selected the scan option "Only when adding a new filter widget"

I am on metabase version - 0.31.1

**Comment by flamber** [comment]
Hi @ayush-chauhan 

I would guess that's the X-ray feature you're seeing - you can disable that, if you want.
Admin > Settings > General > scroll down to the bottom.

**Comment by sbelak** [comment]
As of 0.29 x-rays are completely explicit and run only when you x-ray something. This query looks like it's trying to determine field values. 

Note: there were a couple bugs in fingerprinting heuristics which caused queries to run when they shouldn't. #9116 fixes that.

**Comment by salsakran** [comment]
is this instance active? I.e. is it possible that people are adding filter widgets?

**Comment by sbelak** [comment]
@ayush-chauhan are you still plagued by this?

**Comment by shitoushuoxiangni** [comment]
i truned off the x-ray,but not work. the version is 0.34.3

**Comment by flamber** [comment]
@shitoushuoxiangni 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And which database are you seeing the table scans on?
Can you also post the log of a scan? Admin > Troubleshooting > Logs
Metabase does sync+scan your database according to the schedule:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis

**Comment by shitoushuoxiangni** [comment]
> @shitoushuoxiangni
> Please post "Diagnostic Info" from Admin > Troubleshooting.
> And which database are you seeing the table scans on?
> Can you also post the log of a scan? Admin > Troubleshooting > Logs
> Metabase does sync+scan your database according to the schedule:
> https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis

i tried to see logs ,but the page crash. so i delete the database which is scanned

**Comment by shitoushuoxiangni** [comment]
i tried upgrade the version , but it's still continuously firing up table scan queries;is there someone solve the problem

**Comment by flamber** [comment]
@shitoushuoxiangni 
Please post "Diagnostic Info" from Admin > Troubleshooting.
And which database are you seeing the table scans on?
Can you also post the log of a scan? Admin > Troubleshooting > Logs

**Comment by LoicEm** [comment]
Hello, 

I am also having the same issue, metabase (v 0.34.3) is constantly firing requests in the same fashion as originally described, some of them not even close to possibly finishing ever (group by and order by on a non-indexed text field on a table with more than 2 billion records)

I attached the logs and the diagnostic info just below
[metabase_logs.txt](https://github.com/metabase/metabase/files/4633327/metabase_logs.txt)
[metabase_diagnostic_info.txt](https://github.com/metabase/metabase/files/4633328/metabase_diagnostic_info.txt)

I might be mistaken, but it seems like these heavy requests started around the same time I also integrated a bigquery database in Metabase (bigquery scans and requests work fine though)

**Comment by jainanuj07** [comment]
I am also facing the same issue Metabase keep firing scan queries to presto cluster.

**Comment by flamber** [comment]
@jainanuj07 Post "Diagnostic Info" from Admin > Troubleshooting. And logs from Admin > Troubleshooting > Logs.
Metabase will sync once every hour and scan once every day - unless the defaults are changed:
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis

**Comment by jainanuj07** [comment]
We already set it to sync daily at 12 am but still its keep firing queries throughout the day

**Comment by flamber** [comment]
@jainanuj07 Post "Diagnostic Info" from Admin > Troubleshooting. And logs from Admin > Troubleshooting > Logs.

**Comment by adityamertia** [comment]
Is this issue fixed? We are seeing this even in the latest version v0.39.4.

**Comment by aprada9** [comment]
Same is happening for us in the v0.38.1, we have all the scanning disabled and the needed ones are scheduled at night, but we are constantly seeing Metabase automatic scan queries like the one from the first message at every hour during the day. Is there anyway to disable this scanning process? Or at least avoid it for some schema (the issue is with one schema with a huge amount of tables)
Thanks,

**Comment by aprada9** [comment]
In case you need my diagnostic info or any details:
```
{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.10+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.10",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.10+9",
    "os.name": "Linux",
    "os.version": "4.14.232-177.418.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "sqlserver",
      "postgres",
      "redshift-spectrum"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "11.11"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.2.18"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-03-03",
      "tag": "v0.38.1",
      "branch": "release-x.38.x",
      "hash": "79ef63a"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```
As commented, we have identified that Metabase is automatically launching +2.000 queries every hour of this kind (query have been anonymized): 
```
-- /* partner: "metabase",  
 {"dashboard_id":null,"chart_id":null,"optional_user_id":null,"optional_account_id":"XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX","filter_values":{}} */ Metabase 
  SELECT "schema"."table"."field" AS "field"   
  FROM "schema"."table"  
  GROUP BY "schema"."table"."field"  
  ORDER BY "schema"."table"."field" ASC LIMIT 5000      
```
As you can see in the screenshot all the scanning processes are disabled, and the 2 main ones that are enabled are scheduled at night (around 2am UTC)
![image](https://user-images.githubusercontent.com/32163083/124465175-61773500-dd95-11eb-9494-1c916bb12577.png)

But we are still having thousands of these kind of queries at every hour of the day.
As said, we have a schema with a huge amount of tables which is responsible for almost 90% of these automatic queries, so if we at least can be able to avoid that automatic scanning process in that schema it will help a lot. 

Thanks!

**Comment by flamber** [comment]
@aprada9
1. Which database are you seeing this problem with? Only on the "redshift-spectrum" driver? Metabase has supported external tables since 0.36.3 (#7833). So if the problem only occurs with the third-party driver, then perhaps it's a bug in that.
2. Have you tried the latest release? https://github.com/metabase/metabase/releases/latest
3. By toggling "This is a large database..." does not disable sync/scan. It only allows you to modify the time via the Scheduling-tab
https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#choose-when-metabase-syncs-and-scans
4. Check the application database - specifically the table `metabase_database`, which has a cron-style format for the columns `metadata_sync_schedule` and `cache_field_values_schedule`. Post them here - together with a screenshot of the Scheduling-tab

**Comment by aprada9** [comment]
Thanks for your help @flamber 
We have followed your suggestion; move from the "redshift-spectrum" to the native one as it already supports Spectrum. Based on the data of the last couple of days, it seems that this have solved our issue.

Thanks!

**Comment by flamber** [comment]
This is very likely the root cause #16101 - workaround in description

**Comment by luizarakaki** [comment]
We shipped several improvements to the scanning process since 31. If someone can still repro this issue, I'll reopen it.
