### ISSUE TITLE
When saving to Execl - The maximum length of cell contents (text) is 32,767 characters

### ISSUE THREAD

**Issue by danilvoe** [metabase/metabase#9164]
When saving to Execl
Version 0.31.0

{"message":"The maximum length of cell contents (text) is 32,767 characters","type":"class java.lang.IllegalArgumentException","stacktrace":["org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:440)","org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:421)","dk.ative.docjure.spreadsheet$fn__26646.invokeStatic(spreadsheet.clj:231)","dk.ative.docjure.spreadsheet$fn__26646.invoke(spreadsheet.clj:228)","clojure.lang.MultiFn.invoke(MultiFn.java:233)","dk.ative.docjure.spreadsheet$add_row_BANG_.invokeStatic(spreadsheet.clj:262)","dk.ative.docjure.spreadsheet$add_row_BANG_.invoke(spreadsheet.clj:255)","dk.ative.docjure.spreadsheet$add_rows_BANG_.invokeStatic(spreadsheet.clj:271)","dk.ative.docjure.spreadsheet$add_rows_BANG_.invoke(spreadsheet.clj:265)","dk.ative.docjure.spreadsheet$create_workbook.invokeStatic(spreadsheet.clj:289)","dk.ative.docjure.spreadsheet$create_workbook.invoke(spreadsheet.clj:279)","--> util.export$export_to_xlsx.invokeStatic(export.clj:28)","util.export$export_to_xlsx.invoke(export.clj:27)","api.dataset$as_format.invokeStatic(dataset.clj:106)","api.dataset$as_format.invoke(dataset.clj:98)","api.dataset$fn__42008.invokeStatic(dataset.clj:128)","api.dataset$fn__42008.invoke(dataset.clj:120)","middleware$enforce_authentication$fn__55497.invoke(middleware.clj:113)","api.routes$fn__55651.invokeStatic(routes.clj:66)","api.routes$fn__55651.invoke(routes.clj:66)","routes$fn__56385$fn__56386.doInvoke(routes.clj:108)","routes$fn__56385.invokeStatic(routes.clj:103)","routes$fn__56385.invoke(routes.clj:103)","middleware$catch_api_exceptions$fn__55632.invoke(middleware.clj:436)","middleware$log_api_call$fn__55610$fn__55612.invoke(middleware.clj:364)","middleware$log_api_call$fn__55610.invoke(middleware.clj:363)","middleware$add_security_headers$fn__55552.invoke(middleware.clj:252)","core$wrap_streamed_json_response$fn__57236.invoke(core.clj:67)","middleware$bind_current_user$fn__55502.invoke(middleware.clj:137)","middleware$maybe_set_site_url$fn__55562.invoke(middleware.clj:290)","middleware$add_content_type$fn__55555.invoke(middleware.clj:262)"]}

**Comment by salsakran** [comment]
Out of curiousity, why are you saving something with a cell larger than 32k to an excel spreadsheet?

**Comment by danilvoe** [comment]
Data from DB. :)

In some cases, there are records in which data is more than 32k

**Comment by lindsay-stevens** [comment]
This is a long-standing limit of Excel: https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 i.e. a program that complies with Excel's spec won't allow more than 32,767 characters in a cell. Maybe use CSV or JSON instead?

**Comment by flamber** [comment]
Since this is a limitation of Excel, then Metabase cannot fix that. Thanks @lindsay-stevens for the info
