### ISSUE TITLE
Custom Field not selectable in Filtered By

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#9167]
_This is opened from Discourse thread: https://discourse.metabase.com/t/custom-field-filtering-not-working/5112_

I can’t use Custom Fields in the “Filtered By” sections. Clicking on the custom field in the “Filtered By” list does nothing.

I can’t find a Github issue or forum discussion. I’ve tried on 0.31.2 and 0.29.4. How can I use Custom Fields on the “Filtered By” section ?

![image](https://discourse.metabase.com/uploads/default/optimized/2X/a/ada1e90e787903ee7f2091e5ea3ae79176d63641_1_690x366.gif)

Seeing this in the console, when trying to click on newly create custom filter in the Filtered By:
```
TypeError: n.operator is not a function[Learn More] app-main.bundle.js:5:786028
	value https://metabase/app/dist/app-main.bundle.js:5:786028
	a/this.setField https://metabase/app/dist/app-main.bundle.js:5:790531
	t/r.onChange https://metabase/app/dist/app-main.bundle.js:5:471718
	value https://metabase/app/dist/app-main.bundle.js:5:500604
	value self-hosted:1019:17
	i https://metabase/app/dist/vendor.bundle.js:96:13543
	s https://metabase/app/dist/vendor.bundle.js:96:11742
	executeDispatchesInOrder https://metabase/app/dist/vendor.bundle.js:96:12473
	h https://metabase/app/dist/vendor.bundle.js:94:21526
	f https://metabase/app/dist/vendor.bundle.js:94:21654
	forEach self-hosted:262:13
	t.exports https://metabase/app/dist/vendor.bundle.js:139:30246
	processEventQueue https://metabase/app/dist/vendor.bundle.js:94:23058
	handleTopLevel/< https://metabase/app/dist/vendor.bundle.js:145:109626
	handleTopLevel https://metabase/app/dist/vendor.bundle.js:145:109595
	f https://metabase/app/dist/vendor.bundle.js:145:131746
	perform https://metabase/app/dist/vendor.bundle.js:94:39368
	batchedUpdates https://metabase/app/dist/vendor.bundle.js:145:131224
	batchedUpdates https://metabase/app/dist/vendor.bundle.js:83:102005
	dispatchEvent https://metabase/app/dist/vendor.bundle.js:145:132527
	dispatchEvent self-hosted:1019:17
```

Your browser and the version: Firefox 64, Vivaldi 2.3 (Chrome71.0)
Your operating system: Windows 7, Windows Server 2012
Your databases: SQL Server 2012
Metabase version: 0.29.4, 0.31.2
Metabase hosting environment: Windows Server 2012
Metabase internal database: H2

**Comment by MarkRx** [comment]
Happens to me too. Looks like a bug.

**Comment by flamber** [comment]
This is actually a duplicate of #8382 - not sure how I missed that
