### ISSUE TITLE
Smart number projected values

### ISSUE THREAD

**Issue by nfm** [metabase/metabase#9170]
Feature request/enhancement.

We have an internal page that we've built to track month-on-month revenue growth. The newly introduced Smart Number visualization takes us a step closer to being able to remove this page and replace it with Metabase.

The page has rows for each calendar month, and columns for 'Total revenue' and 'Month-on-month growth'. The current month has a projected value based on revenue to date, and how far through the current month we are.

A quick example:

Month | Total revenue | Month on month growth
-------- | ----------------- | -------------------------------
January 2018 | 100 | -
February 2018 | 120 | 20%
March 2018 | 120 | 0%
April 2018 | 115 | -4.1%
May 2018 | 140 | 21.7%

Lets say the current month is June 2018, and we're exactly half way through the calendar month (UTC), and revenue to date is 80. The next row would show projected growth of (2*80/140) = 14.2%.

With the current smart number visualization, at the beginning of a calendar month when revenue is 0, growth starts out at -100%. The deficit slowly decreases as revenue comes in and as the month progresses. However, showing a -50% deficit for the current partial month is not very meaningful.

It would be great if the Smart Number visualization had a setting to project a growth rate based on how far through the current period we are.

**Comment by camsaul** [comment]
Implemented as part of #40313 via the new `Offset()` expression in 50

**Comment by martin-knap** [comment]
how do you achieve this in Month over month comparison using offset on a Trend visualisation? (i guess this is referred as smart number)
