### ISSUE TITLE
Pie chart fails to show 100% for single value.

### ISSUE THREAD

**Issue by danishpatelcex** [metabase/metabase#9174]
Please find the attachment, where pie chart with Tag (Low) should show 100% against percentage but currently showing 1.

Please find details below:
- Your browser and the version: Chrome 71.0.3578.80 (Official Build) (64-bit)
- Your operating system: Windows 10
- Your databases: MySQL
- Metabase version: v0.32.0
- Metabase hosting environment: Linux/Ubuntu
- Metabase internal database: MySQL

![metabasepieissue](https://user-images.githubusercontent.com/13693154/50443394-3d674d00-0929-11e9-80b9-7a90f9b3e0d4.png)

Please check.

Thanks & Regards
Danish Patel
Senior Software Engineer.

**Comment by danishpatelcex** [comment]
Hi @flamber 
I used master branch.
Please find attached table formated data.
![tabledata](https://user-images.githubusercontent.com/13693154/50467964-9c7d9e00-09cb-11e9-9cf0-988e5e758518.png)

**Comment by flamber** [comment]
@danishpatelcex 
Ahhh...now I see. I can replicate with this query:
```
SELECT 2 AS 'TAG'
UNION ALL
SELECT 0 AS 'TAG'
```
![image](https://user-images.githubusercontent.com/1447303/50489553-ebc4ce00-09cd-11e9-9213-e5b4fb56a80a.png)
