### ISSUE TITLE
Nested Queries drill-downs are broken - getFieldRefFromColumn

### ISSUE THREAD

**Issue by RMMSecurity** [metabase/metabase#9176]
- Your browser and the version: Chrome (71.0.3578.98), Firefox (64.0), Chrome for Android
- Your operating system: Windows 10, Android
- Your databases: Sample Dataset, MySQL, MSSQL
- Metabase version: master (v0.32.0-snapshot) 
*_Works as intended on 0.30.4, I first noticed it in .31-RC1 snapshot!_*

- Metabase hosting environment: Windows Server (JAR), Windows WSL environment 
- Metabase internal database: MySQL/H2
__________________

**Repeatable steps to reproduce the issue**
1. Create or use an existing saved question
2. Create new question with the saved question as a datasource
3. Group By/Create an aggregate 
4. Left click on a cell should give us the action menu with drill-down options *_**however**_* this is broken and has been broken for months!   
   
   
### Just to show what it should look like
![image](https://user-images.githubusercontent.com/802527/50486831-cb931000-09c9-11e9-828b-a5939719c722.png)   
    
    
### Step 1
![image](https://user-images.githubusercontent.com/802527/50486926-3ba19600-09ca-11e9-9eaf-5c41c5fb64dc.png)   
    
    
### Step 2/3/4
![image](https://user-images.githubusercontent.com/802527/50487045-a94dc200-09ca-11e9-83ba-e146c34496a7.png)

    
    
 
### Check console to see lots errors like the following:
> Uncaught Error: getFieldRefFromColumn expects non-null fieldId or column with non-null id
   
     
![image](https://user-images.githubusercontent.com/802527/50487058-b4085700-09ca-11e9-9dd3-abe43bef08ee.png)

Related to #8922, #8854, [8971](https://github.com/metabase/metabase/issues/8971#issuecomment-440429079)

**Comment by mazameli** [comment]
I reproduced this on our stats instance:

![nested-drill-through](https://user-images.githubusercontent.com/2223916/50490642-080f3d80-09c3-11e9-82cb-aa8bd4d5dbbb.gif)

**Comment by RMMSecurity** [comment]
Since the bug was introduced in 0.31.0-RC1 and 0.30.4 worked I went back through the commits and found it was introduced in a2573388cbb75e9a95855b10efea4d47eaeaba3b

https://github.com/metabase/metabase/commit/a2573388cbb75e9a95855b10efea4d47eaeaba3b

**Comment by camsaul** [comment]
I think this might be a duplicate of #8971

**Comment by RMMSecurity** [comment]
@camsaul Possibly, that's why at the bottom I referenced it. It wasn't the original issue that was open and instead referenced in another comment down below the original. Since this impacts my ability to go past 0.30.4 I wanted to expand upon it since it affects more than what was mentioned.

It seems as though since the QP refactoring/MBQL changes the aggregate of a nested query from dataset api calls no longer provide a column id. So if you create the additional id variable and set it to what the resulting id number should be then the drilldown works.

**Comment by RMMSecurity** [comment]
I hope this can get patched in time for the 0.32 release! 

Right now my users can't use Metabase since the database provided by a vendor requires complex joins, a data dictionary, and resorting to SQL for almost everything. 

I made datasets for them to build questions off of, however with the breaking changes they've stopped finding answers and instead defaulted back to asking me. Unfortunately there was some bugs in FK remapping in < 0.31 so I can't revert either without unmapping a ton of FKs on ~20+ tables.

**Comment by mazameli** [comment]
Seeing this in the JS console when I click on a bar in an aggregated nested query chart:

`Uncaught Error: getFieldRefFromColumn expects non-null fieldId or column with non-null id`

**Comment by Crusader4Christ** [comment]
Here is the stack for Metabase 0.32.4
Uncaught Error: getFieldRefFromColumn expects non-null fieldId or column with non-null id
    at t.getFieldRefFromColumn (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at t.drillFilter (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at t.drillUnderlyingRecords (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at e.value (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at Object.url (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at t.ChartClickAction (app-main.bundle.js?b4d1fbde3b5fca6c1555:5)
    at u._constructComponentWithoutOwner (vendor.bundle.js?b4d1fbde3b5fca6c1555:1)
    at u._constructComponent (vendor.bundle.js?b4d1fbde3b5fca6c1555:1)
    at u.mountComponent (vendor.bundle.js?b4d1fbde3b5fca6c1555:1)
    at Object.mountComponent (vendor.bundle.js?b4d1fbde3b5fca6c1555:1)

**Comment by RMMSecurity** [comment]
With some of the recent PRs referenced in #8859 specifically #10242 is all that's needed is a PR to normalize it back to field-id(s) over in [actions.js#L61](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/modes/lib/actions.js#L61) ?

**Comment by RMMSecurity** [comment]
This looks fixed in master and release-0.33.x @mazameli I know you found a few more things in your testing, but I think it's been fixed. Let me know if that checks out!

**Comment by mazameli** [comment]
@RMMSecurity Yep, looks like this is fixed in `release-0.33.x` 👍
