### ISSUE TITLE
Fail to generate sql with multiple group by condition

### ISSUE THREAD

**Issue by link89** [metabase/metabase#9179]
Fail to generate sql with multiple group by condition

- Your browser and the version: chrome 71
- Your operating system: osx
- Your databases:Postgres
- Metabase version: 0.31.1
- Metabase hosting environment: Docker
- Metabase internal database:  H2 
- Reproduce steps: create a question with two condition in group by, and click get answer

**Comment by salsakran** [comment]
Can't reproduce this.

Can you share the question you're trying to create, the schema of the table and any errors in the JS and Server logs?

**Comment by camsaul** [comment]
Can't reproduce this either. @link89 ?

**Comment by mbvictoria** [comment]
Closing - have been unable to reproduce and has needed for info for 6 months.
