### ISSUE TITLE
when some dashboard with lot of questions it is embedded, page (only in IE11) freezes

### ISSUE THREAD

**Issue by jlisyc** [metabase/metabase#9181]
## Environment
Your browser and the version: IE11
Your operating system: Windows10
Your databases: Postgres
Metabase version: 0.31.2 (in 0.30.4 works ok)
Metabase hosting environment: Docker
Metabase internal database: Postgres

## Steps to reproduce
- Embedded dashboard

## Observed result
Note: It happends in 0.31.2 , but not in 0.30.4.
when some dashboard with lot of questions it is embedded, page (only in IE11) is freeze and it shows next advice
![image](https://user-images.githubusercontent.com/33416503/50441345-8eac1800-08fa-11e9-8d40-ab23f11c64b7.png)

### Thanks a lot!
-------

**Comment by jlisyc** [comment]
That happends in a _test environment_ and we have went back to 0.30.4 (in this version works ok).
I tried  in a _local environment_ with 0.31.2, but it has worked ok...  
I will try to reproduce in that _local environment_ (ram, ...) and I will answer as soon as possible.

**Comment by jlisyc** [comment]
Hi All,
Still happends in 0.32.4.

**Comment by jlisyc** [comment]
Great . I which version it will be available?

**Comment by flamber** [comment]
Closing, since Metabase dropped support for IE11 in version 0.40
https://www.metabase.com/blog/Metabase-0.40/index.html#upgrade-now
