### ISSUE TITLE
Metabase MB_DB_AUTOMIGRATE does not work as expected

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9183]
We are nervous about how Metabase will handle database migrations when it is horizontally scaled on multiple instances. Based on the documentation it says we can set MB_DB_AUTOMIGRATE=false to force Metabase to quit and display SQL to run to manually handle the migration.

The documentation seems to imply that once the SQL has been run and there are no more migrations Metabase will start up normally with that variable set:

> You can then take the supplied SQL script and apply it to your database manually. Once that’s done just restart Metabase and everything should work normally.

However after trying this and looking at the code (https://github.com/metabase/metabase/blob/master/src/metabase/db.clj#L419-L434) it seams setting MB_DB_AUTOMIGRATE=false will always cause the program to exit even if there are no migrations to run.

So either the documentation is wrong or the code should not exist if there are no migrations to run.

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.30.1 -> 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by camsaul** [comment]
In that code you've linked it runs `migrate!` if `auto-migrate?` is `true`, otherwise if false it runs `print-migrations-and-quit!`.

**Comment by camsaul** [comment]
@MarkRx I think you're reading the code wrong. In Lisp `if` statements look like

```clj
(if condition
  then-form
  else-form)
```

**Comment by MarkRx** [comment]
Yes that's what I said. The code indicates it always exits if that setting is set while the documentation implies that the program will continue to start up if there are no database changes to apply.

**Comment by camsaul** [comment]
Ok I see what you’re saying. Totally a bug. I will fix.
