### ISSUE TITLE
Support parameters for native Druid query

### ISSUE THREAD

**Issue by kkalyan** [metabase/metabase#9184]
Question/Feature request

Is it possible to define [SQL params](https://www.metabase.com/docs/v0.19.2/users-guide/12-sql-parameters.html) for Native Druid JSON query? I'm particularly interested in relative time filters (like last N days) in a custom Druid query, which will be configured for sending alerts. As of now, if we switch to Native druid query, the dates remain hardcoded. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @kkalyan 

I guess you're talking about variables used by filters? You need to be using the Field Filter to have the relative date features. There's an issue open for adding relative date to Date variable type.
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type

Not using Druid, so don't know if Variables are functional together with Druid. There should be an X-button to the right, above the SQL editor.

**Comment by kkalyan** [comment]
thanks @flamber for the reply. my question is specifically for Druid native query.

instead of hard coding
`"intervals": "{2018-12-22T00:00:00+00:00/2018-12-29T22:38:35+00:00}", `

I tried

`"intervals": "{{{date}}}", `

but It did not work.

**Comment by kkalyan** [comment]
@camsaul is it possible to support relative dates in the native druid queries?

**Comment by pantaoran** [comment]
It doesn't look like Druid native query language supports that at the moment.
See https://github.com/apache/incubator-druid/issues/6023 for an open issue about this.

**Comment by robo220** [comment]
Any idea if ability to use variables will be supported for druid?

**Comment by pantaoran** [comment]
Don't think people here would know, you should ask in the Druid github issues, for example in the issue that I linked...

**Comment by BeyondEvil** [comment]
Almost three years. When will we see support for this?

**Comment by snrbrnjna** [comment]
This feature here is still desperately needed for using metabase with druid. Filter Widgets can't be used with native druid queries and that's a pity.

**Comment by snrbrnjna** [comment]
there's also an open and already quite old question on [SO for that](https://stackoverflow.com/questions/48355106/metabase-date-range-filter-to-dashboards-created-by-native-query)

**Comment by snrbrnjna** [comment]
@flamber why are my comments ⬆️ marked as outdated?

**Comment by flamber** [comment]
They are marked as duplicate, since it doesn't add any additional details besides "I want this too", so just click :+1: instead.

**Comment by luizarakaki** [comment]
This is now possible using the Druid JDBC driver
