### ISSUE TITLE
Three or more averages with default name forget their labels

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#9189]
I start with a question. I group by something (time by week for example). I pick the columns I want to see: Average of col1, average of col2, average of col3. I do not use "Custom Expression" which seem to resolve the problem.

![image](https://user-images.githubusercontent.com/20379005/50599919-17f1ba80-0eb8-11e9-8a13-c3cdb948ac85.png)

I want to show this on a bar graph. It seems the columns are called "Average" "avg" and "avg"; and it's impossible to change the label or the color of the second avg. It is missing from the cogwheel -> Display menu

![image](https://user-images.githubusercontent.com/20379005/50600149-eaf1d780-0eb8-11e9-946e-70f0ee5e3e91.png)

![image](https://user-images.githubusercontent.com/20379005/50600175-f7763000-0eb8-11e9-88b6-266ae48e1c46.png)

- Your browser and the version: Chrome 71.0.3578.98 (Official Build) (32-bit)
- Your operating system: Windows 10
- Your databases: DWH=MySQL
- Metabase version: You're on version v0.31.2 Built on 2018-12-05
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

**Comment by eladeyal-intel** [comment]
maybe related to https://github.com/metabase/metabase/issues/1851 ?

**Comment by neilmitchell-goodson** [comment]
Exactly the same issue here; only noticed when upgrading from  0.29 to 0.30.
