### ISSUE TITLE
About Metabase 'X' button focus off

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9190]
The clickable region on the close ('X') button on the "About Metabase" dialog is off and does not correspond to the icon location. Observe the the mouse icon and click actions in the gif below.

![x_button_focus_off](https://user-images.githubusercontent.com/17504314/50606056-53798e00-0e92-11e9-9c1e-bacd0f4f5cc4.gif)

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by flamber** [comment]
Confirming on Firefox too. I think I noticed it since at least 0.30 - cannot remember checking earlier.

**Comment by tlrobinson** [comment]
Looks like this is due to the close button being absolutely positioned and behind the modal content. Changing the z-index would fix it, I think.
