### ISSUE TITLE
Dashboard collection information slow to load on large dashboards

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9194]
When a large dashboard is loading for some reason the collection it belongs to takes forever to load. It seems to only finish once all the questions on the dashboard load. Annoyingly this causes the top of the dashboard to take up a lot of space. 

I would expect that this would be the first thing to load. Perhaps it is being placed at the end of some loading queue instead of at the front?

![slow_collection_load2](https://user-images.githubusercontent.com/17504314/50662010-e853b880-0f72-11e9-80b4-4ae4ae7d6c66.gif)
(Sped up)

Chrome shows that the fetch to pull in collection information comes after all of the query calls.

![image](https://user-images.githubusercontent.com/17504314/50660889-4da5aa80-0f6f-11e9-8a69-ce67fdfa0353.png)

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by MarkRx** [comment]
It looks like it happens in Firefox as well. I can't get IE to load the page for some reason.

Logs:
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/user/current 200 (2 ms) (2 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/session/properties 200 (7 ms) (1 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/database 200 (2 ms) (3 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/dashboard/147 200 (28 ms) (18 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/setting 200 (401 ╡s) (0 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:26 DEBUG metabase.middleware :: GET /api/database/3/metadata 200 (76 ms) (9 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:49 DEBUG metabase.middleware :: POST /api/card/43/query 200 (22 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:49 DEBUG metabase.middleware :: POST /api/card/43/query 200 (23 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:49 DEBUG metabase.middleware :: POST /api/card/43/query 200 (23 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:49 DEBUG metabase.middleware :: POST /api/card/43/query 200 (23 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:49 DEBUG metabase.middleware :: POST /api/card/43/query 200 (23 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:39:50 DEBUG metabase.middleware :: POST /api/card/43/query 200 (23 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:07 DEBUG metabase.middleware :: POST /api/card/43/query 200 (18 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:07 DEBUG metabase.middleware :: GET /api/collection/root 200 (1 ms) (2 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:07 DEBUG metabase.middleware :: POST /api/card/43/query 200 (18 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:08 DEBUG metabase.middleware :: POST /api/card/43/query 200 (18 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:08 DEBUG metabase.middleware :: POST /api/card/43/query 200 (18 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:08 DEBUG metabase.middleware :: POST /api/card/43/query 200 (19 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)
> 01-03 16:40:08 DEBUG metabase.middleware :: POST /api/card/43/query 200 (18 s) (13 DB calls). Jetty threads: null/null (null busy, null idle, null queued)

**Comment by flamber** [comment]
How many cards do you have in the dashboard? I'm using Firefox and with 23 cards, I'm just seeing a slight delay, which seems like it's because of a lot of javascript setinterval/timeout on my not-so-new computer.
Not sure if this is making a difference, but I'm connecting through Nginx as reverse proxy, which is setup as http/2 over https with LE.

**Comment by MarkRx** [comment]
I want to say my example had 12 cards (which were all the same). 

It is indeed related to a connection limit (#6385). The debug above shows queries being launched in chunks of 6 calls to the long query at a time (with other calls spread out).

What is happening is a queue is built up of calls that need to be made to the REST API. The requests to run the queries for cards are added before the request to get information about the collection. Hence the call to get the collection name is not run until the last batch and sits around with the loading icon until then.

If possible the order in code could be changed to guarantee that the collection information call is fired off before card queries. A more complete approach could be to refactor how REST calls are made.

**Comment by flamber** [comment]
Closing, since a lot has changed and 0.34/0.35 added a lot of optimizations to connection handling.
