### ISSUE TITLE
[BigQuery] Problem when a column name is nearly 128 characters long

### ISSUE THREAD

**Issue by andikacsui** [metabase/metabase#9204]
Hi all,

We are now developing a BigQuery table for monitoring sales metrics. Unfortunately, each column has unique and complicated calculation, and we would like the user to understand the meaning of each column by providing descriptive naming, thus resulting a long column name, nearly 128 chars (the BQ maximum limit for column name).

When we tried to pilot the table on our Metabase, an error occurred;

> Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.

Then we realize it is about how Metabase build a column name alias from the query builder;
`table_name___column_name`

This results the column name to be more than 128 characters long and cannot be proceed by BigQuery.

Could this be fixed? Or do anyone have any other solution for this problem?

Thank you :)

Andika

**Comment by salsakran** [comment]
I'd strongly suggest using shorter column names. 

Think about the fact that in any tabular display, the column name will determine the rendered column width.

**Comment by sbelak** [comment]
You also can (and should) add descriptions to fields in the "data model" section.

**Comment by flamber** [comment]
Aliasing was completely redone in the new BigQuery driver in 0.41
