### ISSUE TITLE
i18n Text Box

### ISSUE THREAD

**Issue by jbrooksuk** [metabase/metabase#9214]
![image](https://user-images.githubusercontent.com/246103/50684453-8eec9780-100d-11e9-885f-f20812ca52fc.png)

The placeholder is showing double apostrophes.

**Comment by flamber** [comment]
Just for reference:
https://github.com/metabase/metabase/blob/07081bc435abaaa74f5dc191cde233b9b32aa150/frontend/src/metabase/visualizations/visualizations/Text.jsx#L167
