### ISSUE TITLE
Dashboard Textbox Formatting

### ISSUE THREAD

**Issue by rkr00t** [metabase/metabase#9223]
------
Dashboard Textbox Formatting 
-----

### Feature requests and proposals
Text formatting in Dashboard Textbox like HTML editor

**Comment by flamber** [comment]
Hi @rkr00t 
It sounds like you are requesting a WYSIWYG editor, so you don't have to write markdown?
Formatting via markdown is already supported since version 0.28
![](https://user-images.githubusercontent.com/5248953/36441533-ccd656ca-1627-11e8-9d84-ad169f405bf7.gif)

**Comment by kdoh** [comment]
I’ll be up front and say I don’t think we’re likely to implement a rich text editor inside of dashboard text cards, at least not any time soon. For cases where you need formatting to get your point across in text cards we do support Markdown as @flamber noted which can get you pretty far.
