### ISSUE TITLE
Just lost entire database when upgrading to Metabase v0.31.2

### ISSUE THREAD

**Issue by paladini** [metabase/metabase#9225]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 71.0
- Your operating system: MacOS
- Your databases: MySQL
- Metabase version: 0.31.2
- Metabase hosting environment: Amazon Linux on AWS EC2
- Metabase internal database: PostgreSQL

### Problem
I was upgrading my Metabase 0.30.1 that was running connected to a PosgreSQL instance on AWS RDS. The upgrade was made to 0.31.2 and we're using the JAR file in order to run Metabase (on a AWS EC2 instance. Amazon Linux as Operating System).

After killing the service (for Metabase 0.30.1), I've put the new JAR file on another folder and then run the following commands on the Terminal (connected via SSH to the instance):

```
export MB_DB_TYPE=postgres
export MB_DB_DBNAME=metabase
export MB_DB_PORT=5432
export MB_DB_USER=<username>
export MB_DB_PASS=<password>
export MB_DB_HOST=localhost
```

Of course, replacing the default values by my own values. They're correct because I tried to access the database using PSequel and it worked fine. Only then I tried to run Metabase:

```
java -jar metabase.jar 
```

When I access my Metabase on our address, everything works fine, but it's asking me to Setup Metabase again. I've made this process in the past and our Metabase has a lot of questions, database connections, users created, etc. We do not want to setup a new Metabase, we just wanted to upgrade the old metabase server keeping the same data. We do not want to lost any data.

How can we proceed?

**Comment by salsakran** [comment]
@paladini , the issue tracker is not a good place for these sorts of questions. You should ask on our discussion forum.

As a starting point- the symptoms suggest that the database name or connection info is _not_ the same, as the new server is finding no previous installation at that connection information.
