### ISSUE TITLE
SQL Server connector apparently using wrong port

### ISSUE THREAD

**Issue by JohnAtFenestra** [metabase/metabase#9226]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Metabase version: 0.31.2
- Metabase hosting environment: Elasticbeanstalk and local Windows
- Metabase internal database: SQL Server

- *Repeatable steps to reproduce the issue*

We attempted to connect to an SQL Server RDS instance. We received a timeout error. I replicated the issue on a Windows Server box using metabase.jar where I knew the server had access to the RDS.

I noticed that the default port for SQL Server is showing as 1433.

In utter desperation, I hand entered 1433 into the field. The server connected immediately.

Apparently, what is showing in the port field as the placeholder text is not identical to what is being used by Metabase as the connection string for SQL Server.

**Comment by camsaul** [comment]
We only set port if you specify it, this change was because of #7597. If you want to submit a PR to remove the `1433` suggestion (because it seems easy to assume it is a default) I will merge it.

**Comment by JohnAtFenestra** [comment]
I would suggest changing the placeholder to be a real instruction rather than appearing to be a default. 

Port: Example: 1433. Leave blank for dynamic ports.

**Comment by camsaul** [comment]
@JohnAtFenestra mind submitting a PR?

**Comment by camsaul** [comment]
You just need to change the YAML file in `modules/drivers/sqlserver/resources`

**Comment by thom-nic** [comment]
I just spend 3 hours trying to figure out why I couldn't connect until I found this 🤦
