### ISSUE TITLE
Display value is not honored when there are more than one foreign key to the same table

### ISSUE THREAD

**Issue by zedidas** [metabase/metabase#9236]
**Problem:**

When a table has multiple foreign key attributes to the same table, the Display Values of these attributes are not correctly honorred. It appears that only one of them is correctly handled.

**Expected behaviour:**

I would expect that both columns display values to show the foreign key name.

**Steps to reproduce:**

- Create the following tables and data:
```
CREATE TABLE Products (
    id int,
    name varchar(255),
    family int,
    sub_family int,
    PRIMARY KEY (id)
);

CREATE TABLE Family (
    id int,
    name varchar(255),
    PRIMARY KEY (id)
);

INSERT INTO Family VALUES (1,'Vegetable');
INSERT INTO Family VALUES (2,'Orange');
INSERT INTO Family VALUES (3,'Banana');
INSERT INTO Family VALUES (4,'Meat');
INSERT INTO Family VALUES (5,'Pork');
INSERT INTO Family VALUES (6,'Chicken');

INSERT INTO Products VALUES (1,'Orange Juice', 1, 2);
INSERT INTO Products VALUES (2,'Banana pie', 1, 3);
INSERT INTO Products VALUES (3,'Chicken nuggets', 4, 6);
```

- Then configure the Products table in Metabase so that it looks like this:
![image](https://user-images.githubusercontent.com/5529181/50837975-ddbf6780-1354-11e9-9556-209ce6278ff3.png)

- Configure both Family and SubFamily attributes so that the Display Value is obtained through the foreign key:
![image](https://user-images.githubusercontent.com/5529181/50837999-ec0d8380-1354-11e9-9440-ca1b1c03624d.png)

- Now perform a question on the Products table. The output is as follow:
![image](https://user-images.githubusercontent.com/5529181/50838026-f760af00-1354-11e9-906e-c8c77dfd1af6.png)

For some reason the Family attribute is showing the ID instead of showing the foreign key name. This only occurs if the foreign key table for both attributes is the same. If I disable one of the column or the other, it will correctly show the display value. However, when both columns are visible in the query, only one of them is correctly showing the values:
![image](https://user-images.githubusercontent.com/5529181/50838067-10696000-1355-11e9-9e88-e9a9fd1653cd.png)
![image](https://user-images.githubusercontent.com/5529181/50838075-14957d80-1355-11e9-8173-9dce1b7f9815.png)

**Additional info:**
- Your browser and the version: Chrome  71.0.3578.98
- Your operating system: Windows 10
- Your databases: Postgres
- Metabase version: 0.31.2
- Metabase hosting environment: Linux
- Metabase internal database: Postgres

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Luckymethod** [comment]
I can confirm we can reproduce this in our instance.

**Comment by Crusader4Christ** [comment]
Any updates?

**Comment by salsakran** [comment]
bumping priority since it seems to be getting hit by a number of people

**Comment by daawen** [comment]
same , When a table has multiple foreign key attributes to the same table, the Display Values of these attributes are not correctly...

**Comment by chad250** [comment]
I too also have had this issue (not been very active on here given Metabase seems pretty good at handling most of my queries!) - I'm getting a "Distinct, non-empty sequence of Field clauses" error when I try to run a question displaying the data, having set the Display value in Admin for the relevant DB table to the correct field for 6 separate fields which need the link. Is there any update on when this is likely to be resolved? :)

**Comment by YuriAndreoli** [comment]
Any update about that?

**Comment by magnusfagerlund** [comment]
We are starting to face this issue quite frequently now... Would love to see this issue being bumped in priority.

**Comment by mtucker** [comment]
This is a big one for us as well - we end up having to include the desired display name as well as the FK in our underlying warehouse tables to get the result we want in Questions. It's a little extra work on the warehouse side and we also lose the ability to link from display names in Questions to their detail record.

**Comment by etcook** [comment]
Bumping this just to make sure, two years later, this is still on the radar. Having to create a custom view every time we want to get around this issue isn't a great solution.

**Comment by adryanm2m** [comment]
Hi, This is a problem for us also

3 Lookups to the Same table
![image](https://user-images.githubusercontent.com/16917687/119552797-d7e64780-bd92-11eb-8c7f-6be810807c2b.png)
set to display Foreign Value
![image](https://user-images.githubusercontent.com/16917687/119552947-ffd5ab00-bd92-11eb-827e-60fda91f7097.png)
Does not show in the table

**Comment by rcronin** [comment]
@flamber - any update on this being worked on. This issue is coming across every single table that has multiple references to the same foreign key table.

**Comment by camsaul** [comment]
So after investigating this a bit both columns are actually coming back in the API response, but they have duplicate `remapped_to` and `remapped_from` metadata, which is why it's not rendering properly. Should be easy enough to fix
