### ISSUE TITLE
Filtering issue for date on x-axis with postgres data "No Valid Fields"

### ISSUE THREAD

**Issue by jeznag** [metabase/metabase#9237]
- Your browser and the version: using MetaBase for Mac
- Your operating system: MacOS 10.13.6
- Your databases: Postgres
- Metabase version: (e.x. 0.19.3) v0.31.2
- Metabase hosting environment: Mac app
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

With this table:
![image](https://user-images.githubusercontent.com/1034890/50884100-eb442280-1424-11e9-8025-c50cfb8f7f08.png)

When I initially create this question, it works fine:
![image](https://user-images.githubusercontent.com/1034890/50883977-9b655b80-1424-11e9-8eb0-e7f5ba6c2454.png)

If I then use my mouse to filter the data, I get this:
![image](https://user-images.githubusercontent.com/1034890/50884006-aae4a480-1424-11e9-95e2-64e38c366582.png)

If I try to choose fields, it shows No Valid Fields:
![image](https://user-images.githubusercontent.com/1034890/50884032-b932c080-1424-11e9-8237-410ef2484baf.png)

I also can't use X-Ray on this table. It freezes as soon as I open it up and eventually goes back to the dashboard.

Here is the data: https://s3-ap-southeast-2.amazonaws.com/data-export-cozero-test/measurement_data.sql.zip

**Comment by salsakran** [comment]
The difference between screenshot 1 and 2 is the addition of a breakout dimension in the second query. What this does is only return the values of that column (because of the "raw data" in the aggregation). This is a single column, which can't be put on a line chart because there is no x and y axis.

When you say "filter by using my mouse" what exactly do you mean?

**Comment by jeznag** [comment]
> The difference between screenshot 1 and 2 is the addition of a breakout dimension in the second query. What this does is only return the values of that column (because of the "raw data" in the aggregation). This is a single column, which can't be put on a line chart because there is no x and y axis.

Ok I'm not sure why that happens when I'm just trying to zoom in on a certain part of the dataset.

> When you say "filter by using my mouse" what exactly do you mean?

Through a pinch and drag action to zoom in on 2 days worth of data

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4
