### ISSUE TITLE
Stripping underscores in column names is dangerous. Please reconsider

### ISSUE THREAD

**Issue by cottrell** [metabase/metabase#9239]
Removing underscores in between words might be fine. But stripping beginning/end yields collisions for things like: Memo_ and Memo. And metabase doesn't behave well in those cases.

**Comment by cottrell** [comment]
It appeared that it was not working but maybe you are right and it was just difficult to see anything popping up. If i remember correctly the string matching "contains" was not autopopulating with typeahead

**Comment by mazameli** [comment]
Based on the last comment, I'm actually guessing this is a duplicate of https://github.com/metabase/metabase/issues/8910, where the `Contains` autocomplete isn't behaving as expected. Closing as such, but please let me know if this is wrong @cottrell.
