### ISSUE TITLE
date range and period selectors feature suggestion

### ISSUE THREAD

**Issue by cottrell** [metabase/metabase#9240]
Don't listent to me but the date period selectors should really be range sliders. There are good tools from the js world there. "Last week" is just a button on top of that. It seems there is a lot of work on the UI side just for creating defaults/admin. Probably not needed. Date period groupby selectors should go there too. If you have date, you can do an period of groupby optionally. 

------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by salsakran** [comment]
There's a big difference between relative and absolute dates. Eg a range slider would be either "7 days ago to today" or "1/1/2001 to 1/7/2001", and when a query is re-run there are different results. 

Closing this as we're not to change this to just a slider, but appreciate the input and we'll take a note of it. We're actually re-examining filters right now. Thanks for taking the time to comment!
