### ISSUE TITLE
Retention for user

### ISSUE THREAD

**Issue by eladeyal-intel** [metabase/metabase#9249]
Should metabase forget users which were not active for some time in order to meet GDPR?

**Comment by flamber** [comment]
@eladeyal-intel 

Are you sure this is related to GDPR? I don't see why it would be.
Just because I don't visit my dentist for a long time, doesn't mean that they'll delete my records and forget me - at least I don't hope :-)

**Comment by tlrobinson** [comment]
While I think providing tools to help with GDPR compliance is a good idea, I don't think automatically deleting inactive users is something we'll want to do. If you want behavior like this it's pretty easy to connect directly to the application database and delete users / user data according to your own logic.

**Comment by eladeyal-intel** [comment]
I'm really not that knowledgeable with GDPR; but the wikipedia article say "A processor of personal data must clearly disclose any data collection, declare the lawful basis and purpose for data processing, and state how long data is being retained". If I want to use metabase and it forces me to write "forever" then I think the lawyers will not be happy.

@tlrobinson I can just delete lines from core_user? Will it not affect history records? Instructing users to edit the database directly sounds like a disaster waiting to happen. I would think an opt-out control to delete users after 2 years of inactivity or such would be easy to implement and have a soothing effect.

**Comment by salsakran** [comment]
This isn't something we're going to do.

As Tom mentions, even if a user is inactive, they still have artifacts (cards/dashboards) that other people might use. Deleting this doesn't make sense just because someone moved to another project in the company.

Also note that Metabase is primarily an internal tool for companies, and GDPR is primarily concerned with companies collecting data about their users. Employees by my read do not fall under GDPR.

**Comment by eladeyal-intel** [comment]
@salsakran  Take a quick look in https://globaldatahub.taylorwessing.com/article/changes-to-employee-data-management-under-the-gdpr for example. Employee data is certainly in scope for the GDPR . It seems that currently there is no way to implement "the right to be forgotten" with metabase so maybe this should be considered. maybe it can be as simple as changing the username, email and real name  to "forgotten user 1" "forgotten user 2" etc
