### ISSUE TITLE
Excel download format

### ISSUE THREAD

**Issue by looric** [metabase/metabase#9251]
to download as excel, suggest the cell width being auto expanded.
the header row frozen, and enable auto filter.

This will save users' time.

Thanks,

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by looric** [comment]
if it's using apache poi , here is some sample code

// Auto size the column widths
for(int columnIndex = 0; columnIndex < 10; columnIndex++) {
     spreadSheet.autoSizeColumn(columnIndex);
}

//easiest way of adding filter on header :

sheet.setAutoFilter(new CellRangeAddress(0, 0, 0, numColumns));
sheet.createFreezePane(0, 1);

**Comment by tmaso-tiqueteo** [comment]
Totally agree. 
And custom header with question name and creation time it would be great.
First Row: Question name
Second Row: Download time
Then data!

**Comment by RMMSecurity** [comment]
Another thing that could use work on the Excel exports is how it currently
exports datetimes. Currently it exports it as a string, not as a date.
Unusable for anything beyond a few rows directly to Excel.

**Comment by flamber** [comment]
@RMMSecurity That's #10803
