### ISSUE TITLE
MongoDB date range filter performance issue

### ISSUE THREAD

**Issue by smohsensh** [metabase/metabase#9256]
**In Summary:** 
The way query generation is done when filtering date ranges in MongoDB prevents using index on these fields. So when using on large collection the query always fails. This is because an unnecessary `$project` stage is done before the `$match` stage on the date field.   

**More Detailed:**
Consider a question with date range filter that just counts the documents. something like this:
<img width="657" alt="screen shot 2019-01-13 at 5 29 38 pm" src="https://user-images.githubusercontent.com/5060107/51086201-da631c00-1758-11e9-9ea4-d54e463d5e28.png">
the aggregation query generated by Metabase to perform this query is this:
```
[
    {"$project":{"date~~~day":{"$let":{"vars":{"column":"$date"},"in":{"___date":{"$dateToString":{"format":"%Y-%m-%d","date":"$$column"}}}}}}},
    {"$match":{"date~~~day":{"$gte":{"___date":"2019-01-10"},"$lte":{"___date":"2019-01-12"}}}},
    {"$group":{"_id":null,"count":{"$sum":1}}},
    {"$sort":{"_id":1}},
    {"$project":{"_id":false,"count":true}}
]
```
The project stage here runs is the first stage (and because the field ```date~~~day``` defined by it is referenced in the next `$match` stage, MongoDB query planner cannot swap these two) so the project stage is ran on all documents. This causes the query to timeout on a pretty large collection. 
However if the query started with a `$match`, it could take advantage of a possible index defined on `date` field and run significantly faster.

**Solution:** 
This can be achieved by using MongoDB's `ISODate()` constructor to avoid the `$project` stage.  The query below works on my collection while the query above generates a timeout error:

```
[
    {"$match":{"date":{"$gte":ISODate("2019-01-10"),"$lte":ISODate("2019-01-12")}}},
    {"$group":{"_id":null,"count":{"$sum":1}}},
    {"$sort":{"_id":1}},
    {"$project":{"_id":false,"count":true}}
]
```

**Comment by flamber** [comment]
Hi @smohsensh 
It looks like a duplicate of #7007

**Comment by smohsensh** [comment]
yes @flamber, they point to the same problem. I will close this so. 
It's worth saying though, that this is not merely a performance issue, it is practically impossible to run the `$project` stage on whole documents if the collection is large.

**Comment by flamber** [comment]
@smohsensh 
Please write that as a comment in 7007 - and any other information that you feel will help.
We want the most informative bugs - but just as few duplicates as possible :-)
