### ISSUE TITLE
Serialization: user credentials flow

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9259]
Handling credentials feels the most rough part of (de)serialization. Currently the workflow is:
1) Upon creating a dump, you specify an [admin] user
2) This user gets added to the dump along with his personal collection [is this correct/needed]
3) Upon deserialization, this user is added with a default hardcoded password "changeme"
4) The first/oldest admin user on the instance into which the dump is being loaded is used as the owner of all the entities.

This is kludgey, conflates (de)serialization of the user with ownership, slightly state-dependent, and potentially creates unneeded aretefacts. Assuming we don't want to store credentials in the dump*, I see the following options:

1) As is. This is rather ghetto, has the downsides outlined above, and introduces a potential attack vector.

2) Pass in the password as an argument during deserialization. This is probably a strict improvement over 1) as the password is at least not googlable/same across different companies and can be seeded with different values in a multi-tenancy environment. 

3) Same as 2), but have the fallback user be completely ephemeral and only passed in upon deserialization. This can be somewhat cumbersome, as you need to pass in first and last name, email, and password. Plus is that it removes coupling between dumping and loading.

4) Add a "reset-password" flag to the user model and have the user enter change password flow upon the first login. This feels the most elegant, but has a potential first-come-first-serve problem as we can't really protect that initial setup flow. To allow fully headless restores, this should probably incorporate 2) as well.

*5) Somewhere Tom suggested that we could also pass in an encryption key and dump passwords encrypted

Since presumably we'll be wanting to serialize users sooner or later anyway, I'm drawn to solutions that (re)use part of that functionality, rather than having a separate code-path. 

We'll also probably want to support partial loads so a selectable owner would be good as well.

**Comment by tlrobinson** [comment]
I don't think we should optimize for the single user case too much, since we plan on eventually being able to serialize/deserialize multiple users. I think we'll want to be able to dump and restore people's passwords (or rather hashes since we don't store raw passwords).
