### ISSUE TITLE
Multiple values on locked params for embedded question?

### ISSUE THREAD

**Issue by Poggen** [metabase/metabase#9266]
- Your browser and the version: Chrome 71.0.3578.98
- Your operating system: MacOS Mojave
- Your databases: MySQL, SQL Server, Google Analytics
- Metabase version: 31.1
- Metabase hosting environment: Ubuntu 14.04
- Metabase internal database: MySQL

I've setup a dashboard that I want to share with my client, by embedding it in an application my client logs in to. This isn't a problem at all and the client really appreciates it. However, I'm now in a position where I'd like to add a couple of business generic questions to this embedded dashboard along with a couple of dashboard filters with client specific default values in them in order to ensure the client only sees data relevant to them.
![skarmavbild 2019-01-15 kl 16 48 55](https://user-images.githubusercontent.com/5216834/51192324-99990d80-18e6-11e9-92f6-f9e2dc31816d.png)
One of these filters needs to have multiple values in order to only show client relevant data. Multiple default values can easily be added in the dashboard filter settings.
![skarmavbild 2019-01-15 kl 16 56 14](https://user-images.githubusercontent.com/5216834/51192507-f399d300-18e6-11e9-8be8-1e7642c7fa60.png)
However, when I try to edit the sharing and embedding settings, I need to replicate the settings from the dashboard filters to the relevant filters/parameters:
![skarmavbild 2019-01-15 kl 17 03 26](https://user-images.githubusercontent.com/5216834/51192781-9baf9c00-18e7-11e9-9aee-f51361531d82.png)
but the type of input field does not allow for the "type a value and press tab to add another value" behaviour that you'd expect, rendering the user unable to properly replicate the desired dashboard state in an embedded setting. 

When passing the params I've tried tons of ways of passing multiple values in the json object:
As one string with comma separated values
```
  "params": {
    "key": "value A, value B"
  }
}
``` 
As an array of values:
```
  "params": {
    "key": [
      "value A",
      "value B"
      ]
  }
}
``` 
..and by passing the same key on two separate rows:
```
  "params": {
    "key": "Value A",
    "key": "Value B"
  }
}
``` 

Either way I try, I get a `Token is missing value for keypath [:resource :dashboard]` error.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by komyg** [comment]
Hi @Poggen,

We had the same problem and my boss managed to create a good work around. What he did was create a query using native SQL and add a variable to a SQL list. This way it is possible to pass multiple values to it when the question is embedded with a locked variable.

Here is an example:

```
SELECT sum("public"."my_column"."total") AS "sum"
FROM "public"."my_table"

WHERE TRUE
[[AND field1_id in ({{ field1_id }})]]
[[AND {{date}}]]
```

In this example, we created two variables: `field1_id` and `date`. If we embed this question and lock the `field1_id` parameter, we will still be able to pass several values to it, because it is inside a list.

I believe that under the hood Metabase does something like this:  `WHERE TRUE AND field1_id IN (1, 2, 3, 4)`.

Hope this helps,
Komyg

**Comment by Poggen** [comment]
Hi @komyg,

I'm well aware of how to use multiple variables in the query itself – that is not the problem. The problem arises only when trying to pass multiple values to a field filter variable (i.e. like the `{{date}}`-variable in your example above) as an embedded question. This is what my embed object looks like:

```
{
  "resource": {
    "dashboard": dashboardId
  },
  "params": {
    "keyA": ["value"],
    "keyB": ["value,value1"],
    "keyC": ["value,value1"]
}}
```

**Comment by synweap15** [comment]
Similar case, I'm on v.0.30.4

What @komyg seems to have missed is to note that his variable is of type `Text`, and you @Poggen expect `Field filter`. The latter replaces placeholders with explicit `column_name IN (value1, value2, ..)`, and therefore you can't have multiple values in locked parameters. But if you can transform it into `Text` type, @komyg 's approach will work. 

It's also possible to bend the system and combine the approaches - have `Field filter` type for viewing the dashboard directly in the panel and have the locked `Text` only for the embedding.

**Comment by Poggen** [comment]
When I try to pass in a separate `Text` variable as @synweap15 suggests, I only get the `com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@P2'.` error. Are you able to use the technique on version 30+, @synweap15?

**Comment by Poggen** [comment]
I managed to solve it, probably user error on my part.

**Comment by lutvdh** [comment]
@Poggen , would you mind sharing how you resolved.  Hoping to learn from your lessons.  Thank you.

**Comment by slickrock22** [comment]
We are struggling with a very similar issue. Would love to know how you solve this problem.  @komyg Thank you so much for your solution on including the variable in the SQL where clause.  Well this is an awesome solution and allowed us to continue to move forward with our implementation it decreases the likelihood that a non-technical end-user would be able to build dashboards for their end-users an embed them in the Application. If we can find a way to pass in multiple variables into a field value then we would be able to allow end-users to be able to create their own reports, use database driven drop-down filters in the embedded process and possibly lock those for restricting access to only the relevant data for those users.  Any help is greatly appreciated

**Comment by flamber** [comment]
Sounds similar to #7593 - multiple default values on Field Filter in Native/SQL questions.
But since this is specific to Embedding, it should have it's own issue - and a workaround isn't a fix.
@Poggen Can you reopen this?

**Comment by Poggen** [comment]
Sorry for my lack of response, but I managed to solve it using the array method described above, e.g:

```
  params: {
    "key": [
      "value1",
      "value2"
    ]
  },
```
The question(s) in question needs to have field filters in order to use this, e.g:
```
...
WHERE {{filter}}
```
Using a regular variable wont work:
```
WHERE column_name IN {{filter}}
```
However, since this issue originally referred to the "Locked parameters" input and the inability to input multiple values there, I agree that this should be addressed and I'll therefore reopen the issue.

**Comment by harshmaur** [comment]
Is there a better way to address this now?

**Comment by rthouvenin** [comment]
@Poggen Do you still use this workaround in a more recent version of Metabase? I tried it, but doesn't work for me. I do have a field filter.
