### ISSUE TITLE
Remove Query Metadata in Big Query SQL Statement

### ISSUE THREAD

**Issue by shahzadbykea** [metabase/metabase#9275]
`-- Metabase:: userID: 1 queryType: MBQL queryHash: 189547725a8426930d081e203f97712fb492037d4f0fea28f6b04c0bfd6c0037
`
This is a part of the SQL Statement on Big Query. On similar Queries, it keeps changing the **queryHash** and resend the Query to Big Query.
This can become costly in the long run. Big Query Provides Caching on Repeating Queries. In order to avail that we require an option where we choose to send the Hash Comment Along with out SQL Query.

This feature would be really helpful if implemented.

Thanks

**Comment by PerThoresson** [comment]
#8547 Same as this one right? Also waiting for this fix

**Comment by flamber** [comment]
Closing in favor of #8539
