### ISSUE TITLE
Native SQL Variable Select Field disappears when saving question.

### ISSUE THREAD

**Issue by Nikos410** [metabase/metabase#9284]
Hey there. 

When we tested the firebird driver I wrote (#9252) we noticed that variables in native SQL queries no longer work. We can configure the variable without issues, but as soon as we click on save, the selection field for that variable disappears: https://gfycat.com/YellowishExemplaryIridescentshark . This happens with Postgres Databases as well.

- Browser: Chrome version 71.0.3578.98 / Firefox version 64.0.2
- OS: Windows
- Databases: Firebird / Postgres
- Metabase version: I just pulled the current state of the master branch and compiled it as uberjar to test the firebird driver.
- Hosting: Running the uberjar on a Linux machine.
- Internal DB: H2

How to reproduce: 
* Create a new native SQL question
* Add a variable
* Save the question

Expected behaviour: The question gets saved and I can select values for that variable.
Actual behaviour: The question gets saved but the field for selecting a value disappears.

**Comment by salsakran** [comment]
Closing this since it is an issue with the code in a PR. 

If/when the firebird gets merged, we can re-open this if it's still a problem. In the meantime all issues caused by the specific work in the PR should be handled within it.

**Comment by salsakran** [comment]
Ooops, just noticed you are reporting it for PG as well.

**Comment by Nikos410** [comment]
Hey there! I just pulled the latest changes from the repo and tried this again, and now this issue no longer happens. This was probably fixed in some commit during development :)
