### ISSUE TITLE
Inconsistent behavior building queries with date filters

### ISSUE THREAD

**Issue by eduavencama** [metabase/metabase#9288]
I'm seeing a strange behavior in Metabase when I use fields with dates.  

If I build a query using a field kind "timestamp", Metabase use "CAST to DATE", but If I add another field to the filter, Metabase remove the CAST.

Steps: 

1. Create a Query and add a Fylter by date (Range).
![image](https://user-images.githubusercontent.com/13947710/51391885-4e0e7b80-1b01-11e9-84c7-6478456b6903.png)

**Result**: This create a SQL query with a "CAST to DATE".
![image](https://user-images.githubusercontent.com/13947710/51390977-db9c9c00-1afe-11e9-93b3-da2543b6bdb0.png)
Return "**n**" registers.

2. Add a new filter by another field (This field is always present, is the ID):
![image](https://user-images.githubusercontent.com/13947710/51391281-a6dd1480-1aff-11e9-8ed9-f2da154f27f2.png)

**Result**: This create a SQL query without the CAST over the field date .
![image](https://user-images.githubusercontent.com/13947710/51391516-45697580-1b00-11e9-874a-724d30a18a09.png)
Return **0** registers.

### Information

- My browser: Chrome 71.0.3578.98
- Your operating system:  Windows 10
- Your databases: Postgres 9.6
- Metabase version: 0.31.2
- Metabase hosting environment: Docker (Runing on Ubuntu 18.04)
- Metabase internal database: Postgres 9.6

**Comment by salsakran** [comment]
when you say "Return "n" registers." do you mean that that query returns results while the second query where `id_cita` is not null returns 0 rows?

**Comment by eduavencama** [comment]
> when you say "Return "n" registers." do you mean that that query returns results while the second query where `id_cita` is not null returns 0 rows?

Yes!  I think that Metabase should do the cast always or don't!

**Comment by Usiel** [comment]
We are seeing the same issue (same setup). As soon as an additional filter is added the behavior for the date filter changes and looses the date cast.

We faced the issue after upgrading from 0.30.4 to 0.31.2. In 0.30.4 timestamps were always casted to date, regardless of any additional filters.

**Comment by Crusader4Christ** [comment]
All date filter now do not work with "On date" value. Broken after update from 0.30.3 to 0.31.2.
Now with selected date in filter where clause become this: ``WHERE (`table`.`created` = convert_tz('2019-03-17T21:00:00.000', '+00:00', '+03:00')``

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4
