### ISSUE TITLE
Changelog for releases

### ISSUE THREAD

**Issue by tordans** [metabase/metabase#9289]
I wonder if it where possible to auto-create a `CHANGELOG.md` for every release (github tag).

As far as I can see neither the github wiki, root-directory nor the docs have a changelog.

For us, this would help a lot to review the changes before we install a new release.

AFAIK there are automated tools to create a basic changelog based on the closed github issues. Another pattern I see is to have the change-log entry a requirement in PRs before merging.

https://keepachangelog.com/en/1.0.0/ seems to be a good starting point for more about this.

--

Thanks for this great tool!

**Comment by tordans** [comment]
Thanks, that is perfect.

I wonder if we could link to this page a little better.
What would make most sense?

a. Add a changelog-headline to the github readme?
b. Add a changelog.md in the repo's root with a link to the page?
c. Add a changelog-headline to the [developer docu](https://www.metabase.com/docs/latest/developers-guide.html) at the end where licence is?
d. Extend the readme to something like "For more information check out metabase.com and the releases page for a changelog."
e. other?

**Comment by salsakran** [comment]
Yeah, I think we should move to a work where the release notes aren't manually generated.

**Comment by jeff-bruemmer** [comment]
Closing this issue, as now have both the [Github release notes](https://github.com/metabase/metabase/releases) with autogenerated notes, and the fancier [https://www.metabase.com/releases](https://www.metabase.com/releases) to summarize what's new in major releases.
