### ISSUE TITLE
Pulses use case: notify new rows only

### ISSUE THREAD

**Issue by incyclum** [metabase/metabase#9298]
If in my previous Pulse I seen data like:

| id | name |
| ---| ------- |
| 1 | Foo |
| 2 | Bar |
| 3 | Buzz |

Then I want to see in the current Pulse to contain :

| id | name |
| ---| ------- |
| 4 | Baz |

If query returns :

| id | name |
| ---| ------- |
| 1 | Foo |
| 2 | Bar |
| 3 | Buzz |
| 4 | Baz |

**Comment by incyclum** [comment]
Or we may want to keep all rows but highlight new data since last seen.

**Comment by bastians** [comment]
@incyclum Can't you already do this with a related `WHERE` statement?

**Comment by bastians** [comment]
@incyclum For example, I have a `WHERE` statement based on `date_create` and/ or `date_changed` columns and I check if there are new and or changed entries yesterday. Then I have a pulse sent daily that is skipped, if there are no new results.

**Comment by incyclum** [comment]
Good point. In my case for the table I'm looking at there's no date-related column but we may be able to add one in DB schema for that purpose.

**Comment by bastians** [comment]
@incyclum The only problem with my proposed solution is, that will have only new or edit data, old data is missing.

**Comment by flamber** [comment]
Related to #7198

**Comment by flamber** [comment]
Closing in favor of #7198
