### ISSUE TITLE
How do I do performance testing？

### ISSUE THREAD

**Issue by exceedzhang** [metabase/metabase#9301]
I want to use the Jmeter tool for a performance test of Metabase. Has anyone done that?

**Comment by salsakran** [comment]
Hello @exceedzhang -

This sort of question is better asked on our discussion forum (discourse.metabase.com). We try to limit the issue tracker to bug reports and actual issues. 

As a starting point, however, you should make sure you properly model the mix of query latencies you'll be seeing in production. We generally use a mix of `SELECT pg_sleep(X);` for a range of values of X.

**Comment by exceedzhang** [comment]
@salsakran Thank you for your quick reply.
