### ISSUE TITLE
Version 0.31.2 bar chart multiple views issue

### ISSUE THREAD

**Issue by DannyK85** [metabase/metabase#9302]
Wasn't able to find this "bug" yet, but using version 0.31.2 it seems like barcharts have a limit of 2 series using a custom question on a native SQL question, no custom expression available.

Version 0.30.4:
![1](https://user-images.githubusercontent.com/5367750/51542788-5dbcf580-1e5c-11e9-8e8a-81ec3cf29ed7.png)

Version 0.31.2:
![2](https://user-images.githubusercontent.com/5367750/51542807-657c9a00-1e5c-11e9-846a-5b744118f287.png)

- Your browser and the version: Chrome 71.0.3578.98
- Your operating system: OS X 10
- Your databases: Postgres
- Metabase hosting environment: Docker
- Metabase internal database: Postgres

To reproduce: use a barchart with more then 3 summed views. In display there are only visual options and legend for the first 2.

**Comment by flamber** [comment]
Hi @DannyK85 
Does this sound similar to issue #9189 ?

**Comment by DannyK85** [comment]
Yes it is

**Comment by flamber** [comment]
This was fixed in 0.32.0
