### ISSUE TITLE
support compound aggregations (e.g. average count of users per day)

### ISSUE THREAD

**Issue by agilliland** [metabase/metabase#931]
_User Story_: as a user asking questions of my data I often want to know how values relate across a breakout which requires that I first do a breakout with an aggregation, then apply another analysis on those results such as averaging them or calculating percentages of the total.

Examples:
- average number of photos per user
- percent of reservations by venue

**Comment by camsaul** [comment]
Related: #647 

@agilliland We don't currently support calculating percentages so compound aggregations or not you still won't be able to do the second query.

**Comment by sbelak** [comment]
You can get pretty far using nested questions https://www.metabase.com/blog/Nested-Queries/. As for the aggregations, we're in the process of adding percentage, therefore closing this issue in favour of a more specific one.
