### ISSUE TITLE
Edit / rename labels for single-series with only one group in pie charts

### ISSUE THREAD

**Issue by madmaddin** [metabase/metabase#9312]
Hi there,

this is my first issue here and I am mor or less a "normal user" of metabase...please be forgiving.

My problem is:
I have data fromated as numbers.
Each number represents an answer from a question form... i.e. "0" is the first answer, "1" is the second answer, etc.

![pie1](https://user-images.githubusercontent.com/46958568/51617187-01c1a200-1f2c-11e9-8413-72852df27f17.png)

Now I want to show the represented answer and not the number.
Instead of "0" >> Yes
Insetad of "1" >> No
Instead of "2" >> I dont know

This is only possible in line charts and even in block charts, when I use more than two groups but not in pie charts...

![linewith2groups](https://user-images.githubusercontent.com/46958568/51617694-0dfa2f00-1f2d-11e9-806e-665099265bbf.png)

Or is there a way to edit the labels even in pie charts and other charts with only one data group?

Thanks in advance and greetings from Germany
mad

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by abbosjon-kudratov** [comment]
Please can you solve this issue ? I'm having trouble on this pie chart type of reports

**Comment by Stekino** [comment]
There is a way to do it directly in SQL ? while waiting for a fix

**Comment by flamber** [comment]
@Stekino Yes, you can give an alias to your columns or your data (case) in SQL, which are then used as the Labels.

**Comment by blazetango** [comment]
> Hi there,
> 
> this is my first issue here and I am mor or less a "normal user" of metabase...please be forgiving.
> 
> My problem is: I have data fromated as numbers. Each number represents an answer from a question form... i.e. "0" is the first answer, "1" is the second answer, etc.
> 
> ![pie1](https://user-images.githubusercontent.com/46958568/51617187-01c1a200-1f2c-11e9-8413-72852df27f17.png)
> 
> Now I want to show the represented answer and not the number. Instead of "0" >> Yes Insetad of "1" >> No Instead of "2" >> I dont know
> 
> This is only possible in line charts and even in block charts, when I use more than two groups but not in pie charts...
> 
> ![linewith2groups](https://user-images.githubusercontent.com/46958568/51617694-0dfa2f00-1f2d-11e9-806e-665099265bbf.png)
> 
> Or is there a way to edit the labels even in pie charts and other charts with only one data group?
> 
> Thanks in advance and greetings from Germany mad
> 
> ⬇️ Please click the 👍 reaction instead of leaving a `+1` or `update?` comment

I m trying the same  in pie chart not able to  get it right, did u find any solution to it.  i m not ok to use the line chart

**Comment by samuelT2** [comment]
This one would be cool. Upvoted!

**Comment by blazetango** [comment]
Yes, I faced a similar problem as i used enum, wanted to replace number with status.
