### ISSUE TITLE
Saving failed when adding a new category filter to existing dashboard

### ISSUE THREAD

**Issue by o-rayer** [metabase/metabase#9313]
Hi,  here is my config :
- Chrome Version 71.0.3578.98
- Mac OS X 10.14.2
- DB Postgres
- Metabase version v0.31.1
- Metabase internal database Postgres

I have an existing dashboard with about 15 cards in it, two filters (1 category, 1 date). I am trying to : 
1) Add a new category filter
2) Set one or several cards with this category filter
3) Save the dashboard
4) Saving fails with following error 500 in the console

![capture d ecran 2019-01-23 a 17 16 06](https://user-images.githubusercontent.com/36108313/51620414-9b8c4d80-1f32-11e9-8f53-8a8c80d218ff.png)

5) The same happens if I try to duplicate the dashboard

![capture d ecran 2019-01-23 a 17 19 24](https://user-images.githubusercontent.com/36108313/51620620-0fc6f100-1f33-11e9-9303-ed6e1e8555a9.png)

6) If I try to rebuild completely the same dashboard, everything seems to work fine and saving works.

It seems that the error is related to the dashboard itself, any clues ?

Thanks a lot !

**Comment by salsakran** [comment]
closing as a duper of #8917  since as @flamber points out it had that error message.

if you can, please see if the current state of the master branch fixed this for you.
