### ISSUE TITLE
Pin map - Draw Box to Filter not working

### ISSUE THREAD

**Issue by binaryduke** [metabase/metabase#9314]
I have pin maps working successfully. Selecting 'draw box to filter' starts drawing a rectangle at the first click on the map. The second click however resets the rectangle start point. It does not seem possible to specify a selection using this function.

**Comment by salsakran** [comment]
Can you share the information regarding how you're running Metabase, browser/OS/Metabase versions, etc that was in the bug report template?

**Comment by binaryduke** [comment]
Metabase v0.31.0 Docker running on 64 bit Amaon Linux/2.10.0
Metabase database: PostgreSQL v10.4
Database: MariaDB 10.2.11

Browser/OS combinations
Mac Safari 12.0.2 / OS X 10.13.6
Mac Chrome 71.0.3578.98 / OS X 10.13.6
Windows Microsoft Edge 42.17134.1.0 / Windows 10 Pro N 64 bit v1803 build 17134.523

**Comment by mazameli** [comment]
Reproduced this on `release-0.33.x` in Chrome.

**Comment by paulrosenzweig** [comment]
Fixed by #10917
