### ISSUE TITLE
to_date(SYSDATE,'dd.mm.yy') does not give same result as to_date(SYSDATE,'dd.mm.yyyy') - Oracle

### ISSUE THREAD

**Issue by punnerud** [metabase/metabase#9318]
Running this gives the same date on Oracle, but not on Metabase connected to Oracle:
```
select to_date(SYSDATE,'dd.mm.yyyy') from DUAL --Different answer on Oracle and Metabase
select to_date(SYSDATE,'dd.mm.yy') from DUAL --Same on Metabase and Oracle
```
Metabase version
![metabase](https://user-images.githubusercontent.com/1153515/51667186-c2dd2c00-1fbf-11e9-8427-2e3e24e2d8ab.JPG)

Oracle version
![oracle](https://user-images.githubusercontent.com/1153515/51667187-c2dd2c00-1fbf-11e9-89e0-b18b4ffca144.JPG)

Could not fint any good answer to this here:
https://github.com/metabase/metabase/blob/master/docs/troubleshooting-guide/timezones.md

**Comment by salsakran** [comment]
can you share the timezones listed in that troubleshooting guide?

**Comment by camsaul** [comment]
Might be something to do with the implementation of the Oracle JDBC driver. How is this issue affecting you?

**Comment by flamber** [comment]
I cannot reproduce on Metabase 0.41.2 with ojdbc8.jar 19.3 querying Oracle 18c.
