### ISSUE TITLE
Use connection metadata for SQL Connection using jdbc

### ISSUE THREAD

**Issue by rdehouss** [metabase/metabase#9319]
Refering to the issue https://github.com/metabase/metabase/issues/2386.

Could this be considered?
Today, without setting this, we see for example for Postgresql : `PostgreSQL JDBC Driver` which is not really convenient.

This feature is typically **not** done using comments, but using connection metadata, which is a easy to query via separate column(s) and typically preserved in logs and performance reports

**ORACLE** uses concept of DBMS_APPLICATION_INFO with CLIENT_INFO / MODULE / ACTION which are for the most part preserved in AWR/ASM reports and take almost no time to setup/change per JDBC call
https://docs.oracle.com/cd/B28359_01/appdev.111/b28419/d_appinf.htm

**POSTGRES** has a concept of APPLICATION_NAME which can be set during or anytime after connection and is preserved in the logs and stored as a column in pg_stat_activity
https://www.postgresql.org/docs/9.5/static/runtime-config-logging.html#GUC-APPLICATION-NAME

**SQL SERVER** (it changed a lot since I was deep in it) has similar concept https://social.msdn.microsoft.com/Forums/sqlserver/en-US/6dacb63d-7eb4-449e-b747-a23ac67237ef/equallent-application-dbmsapplicationinfoin-sql-server?forum=sqlgetstarted

_Originally posted by @CzechJiri in https://github.com/metabase/metabase/issues/2386#issuecomment-225627373_

**Comment by flamber** [comment]
This was added across several versions depending on the database type. Some references: #15678 #15679
