### ISSUE TITLE
Question Builder Built-in Joins not Working

### ISSUE THREAD

**Issue by Go2ClassPoorYorick** [metabase/metabase#9334]
- Your browser and the version: Chromium Version 71.0.3578.98 (Official Build) snap (64-bit), tried firefox
- Your operating system: Ubuntu 18.04
- Your databases: Sql Server
- Metabase version:  v0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: H2 (default)

When trying to use custom views on a question to show a "joined table" (using foreign keys), clicking the plus button does not add the column to the table and creates a browser console error.

- Build Custom Question using query builder on a table with one or more foreign keys
- To make it easier to see, hide all but one column from original table
- try to add column from secondary table
- Background page should reload and you should see an error in console, column will not be added.

[notworkingaddcolumn.log](https://github.com/metabase/metabase/files/2803204/notworkingaddcolumn.log)
![screenshot from 2019-01-28 08-34-22](https://user-images.githubusercontent.com/33301123/51840238-84a27e00-22d9-11e9-9d32-78c3320fab92.png)

**Comment by flamber** [comment]
Hi @Go2ClassPoorYorick 
Those errors are not related to Metabase, but Evernote extension in Chrome.
But you're seeing issue #9144

**Comment by Go2ClassPoorYorick** [comment]
My bad, didn't realize there was an active issue. Will close. Pretty odd on the evernote front, sorry I didn't notice that.
