### ISSUE TITLE
feature request:combine number request and other question

### ISSUE THREAD

**Issue by vincentsjtu** [metabase/metabase#9335]
I tried to combine two builder generated questioned number together, e.g. combine two numbers into a pie chart, but can not find the 'add' label on the number cart in edit model of dashboard. it would be great if i can combine two numbers into a pie char, or use a  number as  input of other question

**Comment by mazameli** [comment]
Yep, the problem of not being able to find the Add button is issue #8948, which has been fixed in master. And #5122 is the issue tracking the request to be able to combine two number questions together into a pie chart. Closing this as a duplicate.
