### ISSUE TITLE
Smart numbers need relative time grouping

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9337]
Smart numbers can display data and a basic trend when data is grouped by time. The problem is time ranges are statically aligned to the calendar and there is no way to make them relative. As a result someone looking at a smart number at the start of the time grouping will see a very negative trend while someone looking at the number at the end of the time grouping will see a more complete picture.

Example (bin by week):
January 20, 2019 – January 26, 2019: 14,566
January 27, 2019 – February 2, 2019:  8,258

Looking at this on Tuesday morning January 29 is misleading:
![image](https://user-images.githubusercontent.com/17504314/51915533-58eec900-23a9-11e9-8eed-0961e7e2b23d.png)

What I should see is -7 and -7 to -14 days like this:
Last 7 days (168 hours): 22,824
7-14 days ago: 20,531

**Comment by sbelak** [comment]
Would you consider whats suggested in to be a solution as well #9170

**Comment by MarkRx** [comment]
That seems to have the same issue but it is suggesting a different solution to the problem. I'm looking for real data instead of projecting to attempt to estimate. I don't like projecting data because no formula will ever be right for everyone.

**Comment by ValdarT** [comment]
Similar to #8977

**Comment by MarkRx** [comment]
Closing since this is a duplicate of #8977
