### ISSUE TITLE
Metabase 0.31.2 migration breaks some table color formatting

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9338]
It seems questions that had formatting on columns that were numbers had their formatting wiped after upgrading to 0.31.2. The issue may be related to the fact that values are now saved as actual numbers instead of a string representation of a number.

**Before (Load question right after migration)**
```
"table.column_formatting": [{
	"columns": ["COLOR_CODE"],
	"type": "single",
	"operator": "=",
	"value": "2",     <-----------
	"color": "#509EE3",
	"highlight_row": true
},
```

**After (delete and re-add formatting)**
```
{
	"columns": ["COLOR_CODE"],
	"type": "single",
	"operator": "=",
	"value": 2,       <-----------
	"color": "#509EE3",
	"highlight_row": true
}],
```

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by MarkRx** [comment]
Use this to find out what questions are broke:

```
select concat('[',name,'](/question/',report_card.id,')') "Question", report_card.updated_at "Last Update", core_user.email "Creator"
from report_card
left join core_user on report_card.creator_id = core_user.id
where visualization_settings regexp '"value":"\[\[:digit:\]\]+"'
and archived = false
```

**Comment by MarkRx** [comment]
Hello,

We are still running 0.31.2. We have already corrected any questions that broke because of this. Since this will only happen to people that were using colors in 0.30 that upgrade it might not be worth investing in fixing it. Instead just note it in some release notes and move on.

**Comment by flamber** [comment]
We're working on migration cleanup and while we would like to have included this, it is deemed too dangerous to try to fix this now and it seems like relatively few people experienced this issue, so closing issue.
In the future, if we make similar changes to visualization_settings, then we will do migrations to avoid problems like this.
