### ISSUE TITLE
The input field of the Number Filter should not accept numbers with comma

### ISSUE THREAD

**Issue by wxiaoguang** [metabase/metabase#9339]
### Bugs
- Metabase version: (e.x. 0.31.2)
- *Repeatable steps to reproduce the issue*

The input field of the Number Filter can accept value like this: "1,234", however this value will be set in the generated SQL's parameter incorrectly like this:  "SELECT xxx FROM yyy WHERE field >= 1".

How to reproduce: I copied the value `10,485,760` from clipboard to metabase, then it becomes one value with comma, then result in wrong query, which is difficult to figure out.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/2114189/51928250-71ee8d00-2430-11e9-951f-6bda729e13e4.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2114189/51951792-e9441100-2470-11e9-8ec7-16c59cbffc8b.png">

**Comment by flamber** [comment]
Related to #3849
