### ISSUE TITLE
Unable to use metabase

### ISSUE THREAD

**Issue by anthonymm1999** [metabase/metabase#9347]
I have recently installed a version of metabase onto two different machines.
On one machine I had gotten it to the setup whereas on another I keep getting errors and I'm not sure why as I have followed the same steps.
1. updated java 
2. initialized in command prompt
3. went to localhost:3000 and it came up saying that the ip wasn't found
After seeing this I had looked around and had changed settings on my firewall proxy cleared my dns cache and even changed the DNS server address to 8 . 8 . 8 .8/ 8 . 8 . 4 . 4 eventually I had turned my router off convinced restarting it would fix it but it didn't
After this I had tried to get to the localhost:3000 with no internet connection and instead of saying it could not find the ip address it said that it had refused to connect and I am unsure why.
Any help is appreciated thanks a lot

**Comment by dannyeuu** [comment]
try remove DNS, try http://127.0.0.1:3000
