### ISSUE TITLE
Show database connection error details alongside their relevant fields during setup

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#935]
right now in setup we just show errors by the save button. it would be more helpful for the user to highlight and mark the relevant fields they need to fix to connect to their data.
<img width="675" alt="screen shot 2015-09-03 at 11 26 28 am" src="https://cloud.githubusercontent.com/assets/5248953/9667247/a0f5db2a-522f-11e5-9264-1592fab1542c.png">

**Comment by mazameli** [comment]
Fixed by https://github.com/metabase/metabase/pull/22804
