### ISSUE TITLE
The particular column value is shifted to previous column in Raw Data view

### ISSUE THREAD

**Issue by gowshalinirajalingam** [metabase/metabase#9353]
In meta base row data view the values of a column is displayed in previous column.
It can be viewed in the screen shot given below clearly.
![image](https://user-images.githubusercontent.com/31157711/52033202-16b0bd80-254a-11e9-87fc-a2a8a974eb00.png)

Please help to fix this issue a as soon as possible.

**Comment by tlrobinson** [comment]
@gowshalinirajalingam Can you please include the information requested in the issue template? In particular which database is this using?

If it's Druid or Mongo then it's likely fixed by https://github.com/metabase/metabase/pull/9343

**Comment by gowshalinirajalingam** [comment]
Data base is Druid

**Comment by gowshalinirajalingam** [comment]
This issue is not regarding to column value sorting problem as you said to refer #9343.
Actually as you can see in the screen shot given above the 'category' column values are shifted to 'timestamp' column and 'cell_id' column values are shifted to 'category' column and so on.

Data Base is Druid.

If any clarification is needed we are ready to clarify.

Thanks

**Comment by camsaul** [comment]
Columns were shifted because they were sorted wrong. Fixed by #9343
