### ISSUE TITLE
Chromium and Firefox-ESR  Dashboard Night-mode in Fullscreen perpetually hangs browser

### ISSUE THREAD

**Issue by philippmayrth** [metabase/metabase#9359]
Dashboard Night-mode in Fullscreen perpetually hangs browser.

Might relate to #9322

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chromium, Firefox-ESR
- Your operating system: Raspbian 9.4 (Raspbian Stretch with desktop 2018-11-13 kernel 4.14 sha: a121652937ccde1c2583fe77d1caec407f2cd248327df2901e4716649ac9bc97)
- Your databases: MariaDB, MongoDB
- Metabase version: 0.31.2
- Metabase hosting environment: Docker on Ubuntu18.04
- Metabase internal database: H2 in docker volume mapped to host

Reproduce on a fresh Raspbian install (Pi3 Model B)
Starting the browsers with the following command wont work:
- ```chromium-browser --incognito --kiosk "https://somedahsboard#fullscreen"```
- ```chromium-browser --incognito --kiosk "https://somedahsboard#theme=night"```
- ```chromium-browser --incognito --kiosk "https://somedahsboard#refresh=900&theme=night"```
- ```chromium-browser --incognito --kiosk "https://somedahsboard#refresh=900&fullscreen &theme=night"```
- ```chromium-browser --fullscreen "https://somedahsboard#theme=night"```
- ```chromium-browser --fullscreen "https://somedahsboard#theme=night"```

Also not working:
- ```firefox-esr "https://somedahsboard```
- Then maximizing the window
- Then clicking on the fullscreen symbol on the website in the bottom right corner
- Same as every command above with chromium leads to browser hanging

Additional notes:
- It does not matter if "anonymous tracking" is enabled or not in metabase.
- The refresh parameter works perfectly

Looking at the Metabase and Apache access logs it appears that the browser does download every card located on the board so I assume its a problem with the JS code.

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment]
When using public dashboard, and having `fullscreen` hash set, I can see that it generates an error in console:
```
Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.request (vendor.bundle.js?78262faa1c529a733077:139)
    at n.r.setFullscreen (app-public.bundle.js?78262faa1c529a733077:5)
    at n.r.loadDashboardParams (app-public.bundle.js?78262faa1c529a733077:5)
    at n.value (app-public.bundle.js?78262faa1c529a733077:5)
    at u.performInitialMount (vendor.bundle.js?78262faa1c529a733077:145)
    at u.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at Object.mountComponent (vendor.bundle.js?78262faa1c529a733077:83)
    at u.performInitialMount (vendor.bundle.js?78262faa1c529a733077:145)
    at u.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at Object.mountComponent (vendor.bundle.js?78262faa1c529a733077:83)
```
When using regular dashboards (requiring login first), it generates similar error, but then `theme=night` hash is not set either.

A work-around is to not set the `fullscreen` hash, but starting the browser in full screen instead:
`chromium-browser --incognito --start-fullscreen "https://metabase.example.com/public/dashboard/39e60b6e-b02d-44a1-9d51-d69c4749365f?date=thismonth#theme=night&refresh=900"`

**Comment by RMMSecurity** [comment]
Sounds #9019

The timer is polling way too often it seems. CPU skyrockets with it checking far too frequently.

**Comment by philippmayrth** [comment]
@RMMSecurity  agree it sounds a lot like that.

**Comment by paulrosenzweig** [comment]
@philippmayrth I just opened PRs for #9322 and #9019. I'm not sure how the fullscreen bug could have hung the browser, so I'd suspect the culprit was #9019. However, if that was the issue, then it's odd that you were seeing the issue even without a refresh query param. Is it possible for you to check if this branch fixes it for you? `fix-9019`

**Comment by paulrosenzweig** [comment]
Both #9322 and #9019 have been resolved, so I'll go ahead and close this. If you're still seeing issues though, please let us know!
