### ISSUE TITLE
How to expose filters, like datepicker, numberpicker, and so on, when embedding a question in application?

### ISSUE THREAD

**Issue by pedrofurtado** [metabase/metabase#9360]
Something like this:

![capture](https://user-images.githubusercontent.com/10530520/52086107-33bab000-258d-11e9-9b5d-4fa483e12663.PNG)

**Comment by salsakran** [comment]
hello @pedrofurtado this is not an appropriate forum to ask questions about how to use the product.

Please refer to our docs or our user forum - discourse.metabase.com
