### ISSUE TITLE
Stacked Percentage Bar Chart Breaks When Only One Series Shown

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9362]
If a stacked bar chart was created when multiple series existed but due to a filter changing, a filter's value being dynamic, or data changing only one series shows the bar chart fails to function as expected. In a real world example this happens when using "past 7 days" and the past 7 days happens to no longer have data for more than one series.

## Steps To Reproduce
1. Create a question with the following data. Setup a status text filter and give it a value of "foo". Make the bar chart a stacked bar chart.
```
select * from (
select to_date('2019-01-28', 'yyyy-mm-dd') "Date", 'SUCCESS' "Status", 12 "Count" from dual
union select to_date('2019-01-28', 'yyyy-mm-dd') "Date", 'SUCCESS' "Status", 3 "Count" from dual
union select to_date('2019-01-29', 'yyyy-mm-dd') "Date", 'SUCCESS' "Status", 3 "Count" from dual
union select to_date('2019-01-30', 'yyyy-mm-dd') "Date", 'SUCCESS' "Status", 4 "Count" from dual
union select to_date('2019-01-31', 'yyyy-mm-dd') "Date", 'SUCCESS' "Status", 4 "Count" from dual
union select to_date('2019-01-31', 'yyyy-mm-dd') "Date", 'FAILURE' "Status", 1 "Count" from dual
) where "Status" != {{status}}
```
![image](https://user-images.githubusercontent.com/17504314/52090708-1f23eb00-2580-11e9-877a-47c604355e0b.png)

2. Change the filter to be "FAILURE". The bar chart will no longer be a stacked percentage bar chart

Result:
![image](https://user-images.githubusercontent.com/17504314/52090673-0d424800-2580-11e9-8ee4-04147524783b.png)

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by notrom** [comment]
Can confirm that I've seen the same issue in v0.30.3.
