### ISSUE TITLE
Metabase v.0.30.4 download problem when using BigQuery as the data source

### ISSUE THREAD

**Issue by anandabudi** [metabase/metabase#9368]
Just found out another bugs within Metabase 0.30.4 when downloading card as CSV if the data source is Google BigQuery. I can only download the file smaller - equal than 5MB. But this is not a problem if the data source is PostgreSQL.

Is this a known problem with Metabase if we want to download CSV from BigQuery as the data source ?

Metabase version: 0.30.4
Error Log: `there is no error or log from the console, the download is completed without an error`

Related to this issue: https://github.com/metabase/metabase/issues/6960

**Comment by flamber** [comment]
Closing in favor of #6960, since that issue has more activity and higher priority already.
