### ISSUE TITLE
[feature request] Adding druid datasource security

### ISSUE THREAD

**Issue by RestfulBlue** [metabase/metabase#9369]
Hello!
Metabase is beatiful project, but sadly, it has not have configuration for druid security :( 
Will be beatiful to have possibility to configure druid credentials( kerberos/ http auth).
Druid already support such things : http://druid.io/docs/latest/design/auth.html

**Comment by salsakran** [comment]
closing as a dupe

**Comment by Ray33** [comment]
> closing as a dupe

I don't think it is duplicated to #7235 . #7235 is about missing cookie via tunneling. This ticket is about enabling authentication, such as "basic authentication".  i.e. to secure direct calls to Druid.
Please open this ticket. it is highly important for security.
