### ISSUE TITLE
Mongo Native Query Multiple Collections

### ISSUE THREAD

**Issue by chirag-shah1** [metabase/metabase#9381]
Is it possible to use lookup in native queries for mongodb? My query looks like, but metabase is not able to find data. 

`[
  {
    "$unwind": "$lookedup_event"
  },
  {
    "$lookup": {
      "from": "events",
      "localField": "distinct_id",
      "foreignField": "user_id",
      "as": "lookedup_event"
    }
  },
  {
    "$project": {
      "props": "$lookedup_event.properties",
	  "distinct_id": "$distinct_id"
    }
  }
]`

**Comment by flamber** [comment]
Hi @chirag-shah1 
Questions are better suited for the forum: https://discourse.metabase.com/
And you should probably give more information, like version numbers and error messages (or logs), ... .
