### ISSUE TITLE
Support "Custom Column" for BigQuery

### ISSUE THREAD

**Issue by awoehrl** [metabase/metabase#9382]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome 71.0.3578.98
- Your operating system: (e.x. OS X 10, Windows XP, etc)
Windows 10
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
BigQuery, Snowflake
- Metabase version: (e.x. 0.19.3)
0.31.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
Heroku
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
Postgres

*Repeatable steps to reproduce the issue*

When connecting to a Big Query database and asking a question, the custom fields option is missing. The popup just contains "Sort" and "Row Limit"

See #4896 for more info.

Cheers
Andreas
![2019-02-06 08_51_00-question metabase](https://user-images.githubusercontent.com/44875496/52327420-59f8a980-29ec-11e9-8b4b-2f9fbf8d48cb.png)

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by eugene-yaroslavtsev** [comment]
Any plan to address this?

**Comment by flamber** [comment]
"Custom Field" is now called "Custom Column" (since 0.33 I think).
For databases that support it, the option would be available here in Custom question (Notebook):
![image](https://user-images.githubusercontent.com/1447303/80260897-38cfb780-8689-11ea-953f-e0391506fcd1.png)

**Comment by bbeghtol1** [comment]
Is there any plans to have this custom column option added for BigQuery?

**Comment by tamvm** [comment]
@flamber 

The option "Custom column" is just available with PostgresSQL connection but it's not available with BigQuery connection

**Comment by Somtom** [comment]
Hey guys,
we just updated to the latest version (0.41.0) today. It seemed that @howonlee added the feature recently but the custom columns are still not there for our BigQuery tables
![image](https://user-images.githubusercontent.com/29712801/136375984-1abb8870-cc0d-4b5f-9331-7f070cc3c0a4.png)

Are we missing something or does it still need to be added to the UI?
