### ISSUE TITLE
SQL not supported when creating a question

### ISSUE THREAD

**Issue by marbelaid** [metabase/metabase#9383]
I would like to create a question using SQL but whenever I try, I can only use the usual query maker.
When I try to switch to be in SQL mode with the button on the top right corner, i can't click and it says not supported. Has anybody an idea of how to resolve this issue?

![screenshot 2019-02-06 at 17 56 37](https://user-images.githubusercontent.com/47394803/52358992-49225500-2a39-11e9-90eb-872274e22941.png)

Thank you in advance.

**Comment by flamber** [comment]
Hi @marbelaid 
Which version of Metabase? Which database do you connect type?
So you're saying that when you're using the Query Builder (aka Custom), and you've started filling out the question, then you cannot click the `Switch to SQL`?
If you want to use SQL directly, click the `Ask a question` button in the top and then `Native query`.

**Comment by marbelaid** [comment]
Hi,

I am on v0.31.2. I only have classic tables in my database.
Yeah that is my problem.
Even when I click the Ask a Question button, I don't have the choice between Native Query or the automatic mode.

**Comment by marbelaid** [comment]
Ok, the problem has been handled by the admin of my database. I did not have some access. Sorry for the inconvenience and thank you.

**Comment by flamber** [comment]
@marbelaid Great that you solved it. Can you please close this issue?
