### ISSUE TITLE
User Interface issue: Lengthily named timestamp fields grouping can't be adjusted because group by day/hour/minute/month/etc isn't rendered

### ISSUE THREAD

**Issue by exabrial** [metabase/metabase#9384]
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
71.0.3578.98 
- Your operating system: (e.x. OS X 10, Windows XP, etc)
OSX Mojave latest as of current date
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
mysql
- Metabase version: (e.x. 0.19.3)
latest as of date v0.31.2
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
digital ocean debian 18.04
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
h2? we didn't change this

- *Repeatable steps to reproduce the issue*
See this screenshot and note the red box:

<img width="411" alt="screen shot 2019-02-06 at 11 20 15 pm" src="https://user-images.githubusercontent.com/1392297/52392371-18f1ab00-2a67-11e9-94f6-9a0b417a5074.png">

1) create a database table named `loan_payment_transactions`
2) add a timestamp column called `loan_payment_transaction_created_at`
3) insert a few rows with different months
4) goto metabase. 
5) ask a new question, attempt to group by month instead of the default day
6) you'll see there is no way to change it from day to month
7) rename column to `lpt_at`
8) refresh schema in metabase
9) repeat step 5
10) win, with data, together
11) we'd love to pay for support for Metabase, per cpu core per gig ram or something. We're a ~50 person company, but you guys don't have that option. Make it happen for a fair price and we'll mail you checks!

* Thanks for being part of the Metabase project!
Thank you for a great open source product!
-------

**Comment by flamber** [comment]
This looks like a duplicate of #9161 

Re: 11. There's different services available, like Paid Support, which would be one way to support.
https://www.metabase.com/services/

**Comment by exabrial** [comment]
most definitely a dupe, thank you!!

**Comment by salsakran** [comment]
@exabrial If you're interested in support, reach out to us via the contact form Flamber suggested.
