### ISSUE TITLE
Combine two parametrized saved questions at a dashboard chart

### ISSUE THREAD

**Issue by stk183** [metabase/metabase#9385]
I am trying to combine two parametrized saved questions at a dashboard chart in order to see the combined results. The questions are written with SQL. The problem is when I am trying to add the second parametrized questions to the chart I am having a "That question is not compatible" error. Is there any trick that I can apply or this kind of combination is not supported yet?

**Comment by flamber** [comment]
Hi @stk183 

Questions are better suited for the forum: https://discourse.metabase.com/

But SQL questions can be difficult to combine, so it would be easier to help if you post both queries.
https://www.metabase.com/docs/latest/users-guide/09-multi-series-charting.html#a-quick-note-about-sql-based-questions

**Comment by flamber** [comment]
Hi @stk183 
Can you please close this issue? I can see that you found the solution yourself :+1: 
https://discourse.metabase.com/t/combine-two-parametrized-saved-questions-at-a-dashboard-chart/5375
