### ISSUE TITLE
Azure Web App AD Authentication causes - Request Header Fields Too Large

### ISSUE THREAD

**Issue by jburke1203** [metabase/metabase#9386]
I'm using Metabase Azure Web App with the metabase/metabase docker image. We have enabled prelogin with Azure Active directory which attaches a cookie to the request. This often results in:

Bad Message 431
reason: Request Header Fields Too Large

I'm not 100% sure, but I presume this is configured on the metabase side to increase the header size.

![image](https://user-images.githubusercontent.com/20659641/52441187-55351200-2b20-11e9-930a-f21413be4953.png)

- Your browser and the version: Chrome
- Your operating system: macOS (mine)/system (whatever Azure use)
- Your databases: MySQL
- Metabase version: v0.31.2/latest
- Metabase hosting environment: Azure Web App container - Docker Hub (metabase/metabase)
- Metabase internal database: H2 (default)

**Comment by TheRusskiy** [comment]
getting the same error :-(
cc @camsaul 
latest version, chrome, postgres, docker inside kubernetes

**Comment by flamber** [comment]
It sounds like you're hitting the default `1k` limit of `client_header_buffer_size` ([nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size)), but then it should automatically use `large_client_header_buffers` which defaults to `4 8k` ([stackoverflow](https://stackoverflow.com/questions/17524396/400-bad-request-request-header-or-cookie-too-large/19285146))
Azure [feedback post](https://feedback.azure.com/forums/217313-networking/suggestions/36087544-support-for-header-content-size-configuration) about the issue. Stackoverflow [answer](https://stackoverflow.com/questions/48964429/net-core-behind-nginx-returns-502-bad-gateway-after-authentication-by-identitys).
@TheRusskiy You're also auth'ing with Azure? And with a cookie above `1024b`?

**Comment by TheRusskiy** [comment]
@flamber no, using nginx and kubernetes on google cloud

**Comment by gauravjaini** [comment]
i landed up with the similar issue.
Getting this error after enabling Azure Active directory authentication. :
Bad Message 431
reason: Request Header Fields Too Large.

Did someone got a solution for this?

**Comment by gauravjaini** [comment]
@jburke1203  - did you manage to find a solution for this?
I am also using a similar setup with Metabase Azure Web App and metabase/metabase docker image

**Comment by peregrinius** [comment]
@gauravjaini unfortunately not.

**Comment by juahan** [comment]
I'm also experiencing this.

If it is indeed the header size, could we go to "/master/src/metabase/server.clj" and add the following options to "(defn- jetty-config []" part:

:request-header-size  - the maximum size of a request header (default 8192)
:response-header-size - the maximum size of a response header (default 8192)

(listed in https://ring-clojure.github.io/ring/ring.adapter.jetty.html)

I could test this, but really don't know how. Dockers, Clojure and Jetty and all this is very far from my skill set.

I think we would just need to compile this somehow, repackage it to docker image and then test it with different header sizes.

**Comment by juahan** [comment]
I have now made a test version which is available at Docker Hub, in that version I have exposed the Jetty header variables as command line parameters MB-JETTY-MAXREQUESTHEADER and MB-JETTY-MAXRESPONSEHEADER. Location of the image in Docker Hub is juahan/metabase_test1.

Let me know if increasing the header max size fixed the problem. You can try for example with -e "MB-JETTY-MAXREQUESTHEADER=16384", which should double the default max header size (8K) accepted by Jetty.

**Comment by jslucas** [comment]
Experiencing this with multiple App Services, an express app and a React app. Chrome and Firefox seem to fail if the header is > 1.5k.

**Comment by flamber** [comment]
Fixed by #12683

**Comment by thl3538** [comment]
Hello, if the parameters of the report query Get request exceed the maximum length limit of the browser, how to solve this problem, can the Get request be converted into a Post request?
