### ISSUE TITLE
Error when running query with BigQuery dataset whose name starts with a number

### ISSUE THREAD

**Issue by dav376** [metabase/metabase#9388]
We are using Metabase to connect to multiple BigQuery datasets. The names of the datasets are auto-generated by a service. We are able to connect to all of our datasets and view the tables/views in each dataset. However we have just discovered that when we ask a Question against a dataset with a long name (32 characters) that the operation fails with the following error message:

Assert failed: (valid-bigquery-identifier? %)

With some engineering effort we can re-create the offending datasets with shorter names, but we are concerned that this problem may re-occur, especially given the way metabase constructs the sql (every column in the sql statement selected is qualified by dataset and table name).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Don't know if this is a known limitation, but #9204 might be related.

**Comment by camsaul** [comment]
Hi, can you copy the stacktrace from the logs? It should also be in the API response in the network tab on your browser Inspector

**Comment by dav376** [comment]
Stacktrace attached, thanks.

[response.json.txt](https://github.com/metabase/metabase/files/2844843/response.json.txt)

**Comment by tkoyama1988** [comment]
@camsaul 
Thanks for your reply on Metabase Discuss.
http://discourse.metabase.com/t/cant-get-rows-from-bigquery/5454/7

Please deal with the matter below.

> I guess that must not apply to dataset names if you have one that starts with a number. Please open a GitHub issue and ping me and I will tweak the Metabase validation code to allow dataset identifiers that start with numbers

**Comment by chasers** [comment]
Me too!!

**Comment by tomekmazur87** [comment]
Would be great to fix that 👍

**Comment by minikomi** [comment]
First time contributor here, would like to take a shot at this.

According to the [bigquery documentation](https://cloud.google.com/bigquery/docs/datasets#dataset-naming): 

> Naming datasets
> 
> When you create a dataset in BigQuery, the dataset name must be unique per project. The dataset name:
> 
> May contain up to 1,024 characters
> Can contain letters (upper or lower case), numbers, and underscores

I'm able to change [the regex](https://github.com/metabase/metabase/blob/master/modules/drivers/bigquery/src/metabase/driver/bigquery.clj#L43-L49) to reflect this, and write a test to confirm the `BigQueryIdentifierString` (possible name change -- `BigQueryDatasetName` ?) spec definition, but I'm not well versed in BigQuery.

Any advice for further testing against a BigQuery data source would be welcome.

**Comment by flamber** [comment]
Fixed by #16746
