### ISSUE TITLE
It's possible to use only the last date from a date interval?

### ISSUE THREAD

**Issue by henriqueschmidt** [metabase/metabase#9392]
Hi, I have a dashboard with graphics filtered by date interval, there is a way to use only the last date from interval in the graphic with red arrow?
Dashboard: 
![_b](https://user-images.githubusercontent.com/30303963/52479496-f1e2c880-2b8f-11e9-8e5e-ea67f1e0a232.png)

Result of query:
![_1](https://user-images.githubusercontent.com/30303963/52479569-3e2e0880-2b90-11e9-87b2-0c1d90f3fb7b.png)

**Comment by flamber** [comment]
Hi @henriqueschmidt 
You should use the forum for questions: https://discourse.metabase.com/
But yes, if you create a Native Query (SQL) for that, you should be able to do something like this:
```
SELECT * FROM `table` WHERE {{date_filter}} ORDER BY `dt` DESC LIMIT 1
```

**Comment by henriqueschmidt** [comment]
Hi @flamber
Thanks, I think that this filter don't worked on a dashboard!
