### ISSUE TITLE
Feature request: Get Link Text from other column

### ISSUE THREAD

**Issue by kogaba** [metabase/metabase#9397]
If we could refer to other column in Link Text.
We could easily create links with dynamic text. (with hide that other column)

Another desires related to links:
Ability to Make a link to spread to the whole row in a table.
Ability to enable/disable "open in new window". (Now on desktop links always opens in new window)

Thanks for the great work!

**Comment by flamber** [comment]
Hi @kogaba 
This sounds like #8482 - or maybe one of the several referenced issues?

**Comment by kogaba** [comment]
indeed
I hope it is easier to implement as I described :)

**Comment by flamber** [comment]
Closing in favor of #8461 (or #7188)
