### ISSUE TITLE
Images specified in CSS files aren't rendering correctly

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#9405]
Images specified in our CSS such as the "No Results" illustration are currently not rendering. Changing ` background-image: url("../app/assets/img/no_results.svg");` to `background-image: url("../assets/img/no_results.svg");` appears to fix this, but it's currently unclear why this broke.

**Example:**

![image](https://user-images.githubusercontent.com/2223916/52592730-01fee000-2dfc-11e9-81ba-f1da73dde2f9.png)

**Comment by RMMSecurity** [comment]
The plot thickens ... I checked out master, created a blank dashboard and it looks like the grid when editing doesn't show either. Nothing has changed on GridLayout.jsx and this is a very recent bug (< 2 weeks)

![image](https://user-images.githubusercontent.com/802527/52635578-3c1dbf80-2e98-11e9-89a9-6132d42e1a15.png)

Broken on Chrome/FF

**Comment by tlrobinson** [comment]
@RMMSecurity that's a distinct issue, resolved by #9423
