### ISSUE TITLE
Chart axis and series label settings not reflected in tooltips

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#9407]
This is on our stats instance. If I modify the title of a series or e.g. my y-axis label, these changes don't appear to take effect in tooltips:

![labels-in-tooltips](https://user-images.githubusercontent.com/2223916/52602558-fde0bb80-2e17-11e9-973a-4bdc7d6d43ac.png)

**Comment by tlrobinson** [comment]
I kind of feel like we shouldn't allow renaming of breakout series since the name comes from the actual data vs. multiple metric series where it's from the aggregation name. If this were handled via remappings then it should just work as expected. It looks like we don't allow manual remappings for strings though, only numbers?

Also why did you highlight the Y-axis label? Isn't that set in the axis labels and doesn't have anything to do with series labels? We only show a Y-axis label automatically if all series on that axis have a matching name, I believe.

**Comment by mazameli** [comment]
> I kind of feel like we shouldn't allow renaming of breakout series since the name comes from the actual data vs. multiple metric series where it's from the aggregation name.

I dunno, I think there are cases where the data will send back grossly formatted data or abbreviations that you might want to clarify if you're curating and polishing this chart.

> It looks like we don't allow manual remappings for strings though, only numbers?

Yeah, I believe that's right.

> Also why did you highlight the Y-axis label? Isn't that set in the axis labels and doesn't have anything to do with series labels? We only show a Y-axis label automatically if all series on that axis have a matching name, I believe.

I confused things by using a chart with a secondary breakout and showing the Display tab. Here's a simpler example below. If I change the y-axis label from `Sum of Subtotal` to `Dollars`, I think that should be reflected in the tooltip, but it is not currently (in this example, it's `Sum`):

![image](https://user-images.githubusercontent.com/2223916/52603478-d2f86680-2e1b-11e9-979d-315f0abcdcde.png)

**Comment by tlrobinson** [comment]
> I dunno, I think there are cases where the data will send back grossly formatted data or abbreviations that you might want to clarify if you're curating and polishing this chart.

Isn't that the point of remappings? Clean it up once in the data model so you don't have to do it in every query.

**Comment by tlrobinson** [comment]
> If I change the y-axis label from `Sum of Subtotal` to `Dollars`, I think that should be reflected in the tooltip, but it is not currently (in this example, it's `Sum`):

Hmm if there's a single series on a Y-axis then the Y-axis label and series name are redundant. We should probably keep them synchronized or hide one.

**Comment by flamber** [comment]
@tlrobinson 
> Hmm if there's a single series on a Y-axis then the Y-axis label and series name are redundant. We should probably keep them synchronized or hide one.

Series name is not always redundant. I have charts, where I display a missing tasks grouped by place, but when there's only a single place, then I have no idea which it is. Having the tooltip would be helpful. I understand that you don't want to show legend if there's only a single series.
![image](https://user-images.githubusercontent.com/1447303/52605546-f8459e80-2e34-11e9-9d45-49b75e42c578.png)
![image](https://user-images.githubusercontent.com/1447303/52605583-1b704e00-2e35-11e9-8752-b88c86ddb5d3.png)
