### ISSUE TITLE
provide a named set of mb colors as CSS vars for use throughout the app

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#942]
having our colors set explicitly as variables will help keep things nice and explicit and easy to find.

currently in use through out the app but not named
- [ ] mb blue
- [ ] mb green
- [ ] mb purple
- [ ] mb yellow
- [ ] mb red

we may want / require

- [ ] mb blue --saturated
- [ ] mb green --saturated
- [ ] mb purple --saturated
- [ ] mb yellow --saturated
- [ ] mb red --saturated

- [ ] mb blue --desaturated
- [ ] mb green --desaturated
- [ ] mb purple --desaturated
- [ ] mb yellow --desaturated
- [ ] mb red --desaturated

**Comment by agilliland** [comment]
@kdoh is this done?

**Comment by kdoh** [comment]
These exist here in JS, but not 100% sure there are CSS variable equivalents. https://github.com/metabase/metabase/blob/master/frontend/src/lib/colors.js 
Would be pretty fast to add.

**Comment by salsakran** [comment]
@kdoh this still live?

**Comment by kdoh** [comment]
Gonna close this as we've made a fair number of changes to how colors work since I opened this almost a year ago and this no longer really reflects the state of reality.
