### ISSUE TITLE
Cause "WHERE table LIKE %%" from a variable filter

### ISSUE THREAD

**Issue by JoaquinMontesinos** [metabase/metabase#9427]
------
 WHERE table LIKE %%
-----
I am trying to make a mysql select consult "WHERE table LIKE '%example%' ".

### If I make it static, it WORK, but is not my objetive.

SELECT * FROM table 
WHERE 1=1
[[ AND table LIKE CONCAT('%',"example",'%') ]] 

SELECT * FROM table 
WHERE 1=1
AND table LIKE '%example%'

### If I make it dependent on a filter, it DOESN'T WORK.

SELECT * FROM table 
WHERE 1=1 
[[ AND table LIKE CONCAT('%',{{variable_filter}},'%') ]] 

SELECT * FROM table 
WHERE 1=1 
[[ AND table LIKE '%'||{{variable_filter}}||'%' ]] 

SELECT * FROM table 
WHERE 1=1 
AND table LIKE {{variable_filter}}

### Previusly

I saw that to other users this worked them, but not for me. 
CONCAT ('%', {{variable_filter}}, '%')
'%'||{{variable_filter}}||'%'

### Using
* Browser version: Chrome version
* Database: MySQL 5.6
* Metabase version: v v0.31.2

**Comment by flamber** [comment]
Hi @JoaquinMontesinos 
What's the Variable Type set to? When I try to replicate, then it works fine:
![image](https://user-images.githubusercontent.com/1447303/52872752-eb65cb00-3112-11e9-8b41-3c7f9361bfe0.png)
Also, questions are better suited for the forum: https://discourse.metabase.com/

**Comment by JoaquinMontesinos** [comment]
Hi @flamber, thanks for your answer!
variable_filter is reading from a table column. The filter is type "search box" to help users search.

![image](https://user-images.githubusercontent.com/17361407/52878183-4ec81b00-315c-11e9-8195-4e8ce05d4386.png)

I tried like you and it works but it's not the goal. 

I will write this question in the forum. I hope that after being solved.

**Comment by flamber** [comment]
@JoaquinMontesinos 
You cannot use Field Filters like that. You should not define the column.
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
Without knowing your full query, it's difficult to guess how you should handle it.

**Comment by JoaquinMontesinos** [comment]
@flamber 

SELECT * FROM table 
WHERE 1=1 
[[ AND table.column LIKE CONCAT('%',{{variable_filter}},'%') ]]

**Comment by flamber** [comment]
@JoaquinMontesinos 
But if you're using Field Filters, then you would make use of the List or Search functionality, which you define in the Settings > Admin > Data Model > (database) > (table) > (column) click the gear-icon.
```SQL
SELECT * FROM table
WHERE 1=1
[[ AND {{variable_filter}} ]]
```

**Comment by JoaquinMontesinos** [comment]
@flamber 
My intention was to use both at the same time in same "variable filter". Search functionality and plain text. I understand that you can not make it in the same "variable filter".
Thanks a lot!

**Comment by flamber** [comment]
@JoaquinMontesinos 
Ahhh okay, then you are probably better off with two different filters. If you feel this is answer enough, then please close the issue :+1:
