### ISSUE TITLE
Add schema environment variable for Postgres

### ISSUE THREAD

**Issue by mnlbox** [metabase/metabase#9442]
Hi guys,
I want to integrate Metabase with Hasura and consider to split Metabase tables with other part of my app through Postgres schema. Now Metabase did not support `schema` as an environment variable.
Can you add this feature?

Related issue in Hasura repo: https://github.com/hasura/graphql-engine/issues/1615

**Comment by flamber** [comment]
Hi @mnlbox 
This looks like a duplicate of #6622 ?
I think the current solution would be to as described here: https://github.com/hasura/graphql-engine/issues/1615#issuecomment-464981975

**Comment by salsakran** [comment]
closing as a dupe
