### ISSUE TITLE
Problem when exporting custom question

### ISSUE THREAD

**Issue by petar777** [metabase/metabase#9443]
Hello everyone,

I am wondering whether there is a chance to export a custom question with custom mapping of the values the way it is represented in metabase. It seems that when I try to export it it neglects that mapping. Moreover the format of the date is completely different too.

What I expect is:
![expected](https://user-images.githubusercontent.com/16069308/52997519-7273b580-3429-11e9-8f81-765fb69f920e.png)

What I get in the csv is:
![wrong](https://user-images.githubusercontent.com/16069308/52997532-79022d00-3429-11e9-81b8-26d769f2862a.png)

**Comment by flamber** [comment]
Closing in favor of #17422
