### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by pschaub** [metabase/metabase#9444]
Is there a simple way to help fixing translation issues?

for example this headline on the dashboard is wrong: (German)
"Wie ist es gehen, {name}?"

The project is currently only partially translated and some of the translations are wrong.

**Comment by flamber** [comment]
Hi @pschaub 
You can help with translations via https://poeditor.com/join/project/ynjQmwSsGh

**Comment by jrvidotti** [comment]
When (and how) added translations are merged and made available in docker image? I've just made 3 hundred portuguese translations there... lol

**Comment by flamber** [comment]
Hi @jrvidotti 

When a translation is completed at the time a release is being build, then it's automatically added. There might still be a few changes or new strings to translate before 0.32 is released.

> We have scripts to fetch completed languages from POEditor so there’s no need to open a PR yourself
https://discourse.metabase.com/t/new-language-italian-100/5350/3
