### ISSUE TITLE
Questions should not be clickable when editing a dashboard

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9445]
When in dashboard edit mode if you do a long click (but only if the mouse is down for a while) on a question, you jump to that question which is very annoying, doubly so because you also loose any (unsaved) changes you've made to the dashboard until this point.

**Comment by flamber** [comment]
That just happened to me (twice), when I was trying to reproduce 6765 :disappointed: 
Related to #6888

**Comment by tlrobinson** [comment]
@sbelak I'm unable to reproduce the long click issue. Which type of chart is it and where are you clicking?

I am able to reproduce #6888. We should disable brushing when editing, and probably prompt if trying to navigate away without saving.

**Comment by paulrosenzweig** [comment]
Resolved by #10931
