### ISSUE TITLE
Force metabase to show table, not card

### ISSUE THREAD

**Issue by lp-lima** [metabase/metabase#9447]
Hi there, people!
I've created a post in the community about this, and now I'm filing an issue. 
The problem happens when I try to filter any table by an entity key column - in that scenario, the results are shown as card, even if I select many values for the column. Check this example using the sample dataset:

![image](https://user-images.githubusercontent.com/22321989/53013632-01320380-3425-11e9-88ec-685a602ddf37.png)

I select IDs 1 and 3, and I expected to see a table containing those two rows. Instead, I get a card showing data only about (the first) of them.

I think it would also be helpful if, even when selecting one single value, the user had the option to see the result as a view or as a table.

- Browser Chrome 72.0
- OS: Windows 10
- DB: MySQL, Sample Database
- Metabase version: 0.31.0, 0.31.2
- Metabase hosting environment: Amazon EC2, run from jar directly
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*
According to the image, just select, from the sample database, more than one ID (ie, column defined as entity key) from any table - there will be no option to display them as a table, nor will it be possible to show more than one single card.

**Comment by flamber** [comment]
This was fixed in 0.41.0
