### ISSUE TITLE
Provide Option to Not Show Date on Time Series X-Axis

### ISSUE THREAD

**Issue by jschlegel** [metabase/metabase#9448]
We have a line chart on our dashboard which shows today's values for a specific metric that is updated at 5 minute intervals throughout the day (see attached screenshot).   Each metric update includes a ‘timestamp with time zone’ column called ‘time’ giving the time of the update. If I try to create a graph of the metric vs. time, the x-axis labels include the date + time. As a result, only two labels fit on the graph for the whole day. 

I think it would be a good idea to provide an option to not show the date under the date formatting options for time series x-axis in order to alleviate this problem.  Currently, it is possible to not show the time, but you can only select the date format.  The chart is already scoped to a specific day, so there is no need to show the date on the x-axis.  

![screen shot 2019-02-19 at 12 21 43 am](https://user-images.githubusercontent.com/1084166/53037498-5d5a4f00-3448-11e9-888d-0f06b12ba46c.jpeg)

**Comment by RomanAbashin** [comment]
<img width="396" alt="Screen Shot 2019-06-11 at 17 13 24" src="https://user-images.githubusercontent.com/14080347/59284331-5f9d1f00-8c6c-11e9-8f4d-233f4752df16.png">

It doesn't work like this?

**Comment by flamber** [comment]
@RomanAbashin I think the request is to be able to show only time on the X-axis

**Comment by jschlegel** [comment]
Yes, that’s correct.  I’d like the option to show only the time, but not the date for dashboards that are daily in scope.

**Comment by mazameli** [comment]
Closing this in favor of #11427 which is a more generally applicable proposal.
