### ISSUE TITLE
API Issue with User Creation

### ISSUE THREAD

**Issue by dizzydes** [metabase/metabase#9449]
Hey,

I'm using Postman with the API and I've been successful in sending most requests. However I'm sending a POST request to create a new user and its gets the following error:
        
`"first_name": "value must be a non-blank string."`

I've adjusted what I was sending, added login_parameters as nil, changed email_address to username etc. to no avail. My session that I send in the header is active and has worked on other requests.

Example URL:
`https://analytics.catsnatcher.com/api/user/?first_name=Hello&last_name=World&email_address=helloworld@gmail.com&login_attributes=`

**Comment by tlrobinson** [comment]
I'm pretty sure all of our `POST` endpoints expect a JSON object in the request body, not a query string.
