### ISSUE TITLE
Stagger questions' execution, part of the same dashboard, at Redshift.

### ISSUE THREAD

**Issue by shankersneh** [metabase/metabase#9456]
Currently, all questions are fired at-once at Redshift when a dashboard is opened. Can we stagger the queries, only if the database is Redshift/OLAP (not too good at handling concurrent bunch of queries). I think this isn't a problem when using a small row/transaction database - but with massive warehouse as Redshift, the issue gets amplified.

**Comment by flamber** [comment]
Hi @shankersneh 
There's an environment variable called `MB_MAX_CONCURRENT_QUERIES`, which should allow you to control the amount of connections (globally I think). Look at https://github.com/metabase/metabase/commit/6d31c7935ac6c51d62d7d25fdc8ff6c8dc0c382a to see how it works.
Related to #2172 (possibly duplicate)
