### ISSUE TITLE
type/Time field display ignoring Timezone setting

### ISSUE THREAD

**Issue by poorlymac** [metabase/metabase#9461]
Hi,

When displaying a time **only** field it seems to be using the browsers timezone. Datetimes & Dates display correctly.

![screen shot 2019-02-21 at 11 32 00](https://user-images.githubusercontent.com/16620846/53135211-7d1b7f80-35ce-11e9-9740-2110af200ac4.png)
)

Filtering using the time field also works as expected (correct result, its just the display of the time is offset to the Timezone

Downloading the data works as expected:
2018-12-03,2018-12-03T13:04:07.000Z,13:04:07.000Z

Data confirmed in Postgres view to be correct (the view just separates the datetime into date and time):
+------------------+------------------------+------------------+
| transaction_date | transaction_datetime   | transaction_time |
+------------------+------------------------+------------------+
| 2018-12-03       | 2018-12-03 13:04:07+00 | 13:04:07+00      |
+------------------+------------------------+------------------+

AWS Server is +1
Java launched with UTC
Metabase set to UTC
Browser +11 (Safari and Chrome tested)

Also note also I have tried various formatting in the DataModel->Table->Column->Formatting to no avail, which gives a Date Style setting and not just a Time Style setting as would be expected. Plus you will note from the screenshot the time is showing in the 12 hour clock with no seconds even though I set it to the 24 hour clock, and also requested HH:MM:SS. The issue may be related to the metabase_field Formatting not taking heed of the data type/Time and timetz but the fingerprint mentioning type/DateTime.

**Comment by paulrosenzweig** [comment]
Resolved by #10146
