### ISSUE TITLE
Avoid downloading analytics.js

### ISSUE THREAD

**Issue by dumoulinj** [metabase/metabase#9464]
Even if anonymous tracking is disabled, the script "analytics.js" is downloaded anyway. Wouldn't it make more sense to disable its download in this case?

I get that this script will not be called by Metabase later (since the anonymous tracking is disabled), but just its download can still represent a security concern for some companies (like mine).

See #2677 for a temporary workaround

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by camsaul** [comment]
@dumoulinj that's a good point, we'll have to look at fixing this
