### ISSUE TITLE
Metabase uses UTC to determine current week for Google Analytics query filters

### ISSUE THREAD

**Issue by SergeyKorochansky** [metabase/metabase#9467]
We are using Google Analytics integration with Metabase and it has an issue with calculating bounds of current week in some edge cases. On Saturdays at 7PM-12PM EST Metabase uses next week as a ongoing one (ignoring timezone settings), because in UTC timezone sunday already began.

Steps to reproduce:
1. Configure Metabase report timezone, instance’s timezone, and Google Analytics view timezone to `US/Eastern`.
2. Create a new Google Analytics question (e.g. on Monday).
3. Pick some view, e.g. `Users`.
4. Add `date` filter: `This week`.
5. Click on `View the native query`.
6. Wait for Saturday 7PM.
7. Click on `View the native query`.

Expected result:
The date filter in the generated query should be the same on Saturday, as on Monday.

Actual result:
On Monday Feb 18th this filter adds correct dates ( `start-date` is `2019-02-17` and `end-date` is `2019-02-24`). But on Saturday Feb 23th at 7PM `start-date` is `2019-02-24` (Sunday of the next week) and `end-date` is `2019-03-03`.

Please note, that `Current week` selects 8 days instead of 7 days. That seems to be a separate issue.

- Metabase version: 0.31.2
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres
- Metabase report timezone: `US/Eastern`
- Metabase instance’s timezone (`TZ` env var): `America/New_York`
- Google Analytics view timezone: `United States (GMT-05:00) New York Time`

**Comment by camsaul** [comment]
Related: #9476
