### ISSUE TITLE
Share Dashboard URL with "FIXED/LOCKED" Filters

### ISSUE THREAD

**Issue by Avidan561** [metabase/metabase#9473]
I'd suggest trying to shell into the container and try to connect to the database. You might also try our discussion forum http://discourse.metabase.com

**Comment by Avidan561** [comment]
When sharing a URL of a dashboard, it would be nice to have the ability to LOCK one or more of the filters on the dashboard.  example: leaving "date" unlocked, but locking the "client" or "group", so they can't see the other clients or groups figures.

**Comment by flamber** [comment]
Hi @Avidan561 
You can do that by using embedding, which you can integrate with your own security levels:
https://www.metabase.com/docs/latest/administration-guide/13-embedding.html

**Comment by salsakran** [comment]
Replaced the template text in your issue with the text of your comment for readability purposes. If there was anything removed inadvertently, please edit the issue body.

**Comment by killthekitten** [comment]
@salsakran is there plans to extend URL sharing to include locked filters the same way it is done on the embedding screen? It would make a lot of sense to unify these.
