### ISSUE TITLE
Metabase 0.32.0 can't connect MySQL 5.6.x or older

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#9483]
### Bugs
metabase 0.32.0 can't connect to mysql version 5.6.16-log
but change  mysql version into 5.7 ,it's OK.
Could you help me to solve ?
"java.sql.SQLException: Unknown system variable 'session_track_schema'"

-------
![image](https://user-images.githubusercontent.com/20455410/53283867-49d02080-3787-11e9-84a4-a2b8accaecd6.png)

**Comment by flamber** [comment]
Hi @xqwbx163 
Can you provide the Metabase logs too? Did you define the field "Database name"?
`session_track_schema` doesn't exist on 5.6 - it was introduced in 5.7.4:
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_session_track_schema

**Comment by xqwbx163** [comment]
SQLException:
 Message: Connections could not be acquired from the underlying database!
 SQLState: null
 Error Code: 0
02-26 09:01:00 ESC[1mERROR sql-jdbc.executeESC[0m :: nil
02-26 09:01:00 ESC[1mWARN sync-metadata.sync-timezoneESC[0m :: Error syncing database timezone
java.lang.Exception: Error querying database 'report' for current time
        at metabase.driver.common$current_db_time$fn__31797.invoke(common.clj:185)
        at metabase.driver.common$current_db_time.invokeStatic(common.clj:172)
        at metabase.driver.common$current_db_time.invoke(common.clj:161)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at metabase.driver.mysql$fn__60377.invokeStatic(mysql.clj:88)
        at metabase.driver.mysql$fn__60377.doInvoke(mysql.clj:87)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.sync.sync_metadata.sync_timezone$fn__45821$sync_timezone_BANG___45826$fn__45827.invoke(sync_timezone.clj:24)
        at metabase.sync.sync_metadata.sync_timezone$fn__45821$sync_timezone_BANG___45826.invoke(sync_timezone.clj:14)
        at metabase.sync.util$fn__36577$run_step_with_metadata__36582$fn__36586$fn__36588.invoke(util.clj:356)
        at metabase.sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
        at metabase.sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
        at metabase.sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)
        at metabase.sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)
        at metabase.sync.util$fn__36577$run_step_with_metadata__36582$fn__36586.invoke(util.clj:353)
        at metabase.sync.util$fn__36577$run_step_with_metadata__36582.invoke(util.clj:348)
        at metabase.sync.util$fn__36767$run_sync_operation__36772$fn__36773$fn__36774.invoke(util.clj:438)
        at clojure.core$mapv$fn__8430.invoke(core.clj:6912)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
        at clojure.core$reduce.invokeStatic(core.clj:6827)
        at clojure.core$mapv.invokeStatic(core.clj:6903)
        at clojure.core$mapv.invoke(core.clj:6903)
        at metabase.sync.util$fn__36767$run_sync_operation__36772$fn__36773.invoke(util.clj:438)
        at metabase.sync.util$fn__36767$run_sync_operation__36772.invoke(util.clj:432)
        at metabase.sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140$fn__46141.invoke(sync_metadata.clj:51)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:149)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
        at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:147)
        at metabase.sync.util$do_with_error_handling.invoke(util.clj:144)
        at clojure.core$partial$fn__5824.invoke(core.clj:2623)
        at metabase.driver$fn__17883.invokeStatic(driver.clj:614)
        at metabase.driver$fn__17883.invoke(driver.clj:614)
        at clojure.lang.MultiFn.invoke(MultiFn.java:239)
        at metabase.sync.util$sync_in_context$fn__36483.invoke(util.clj:140)
        at metabase.sync.util$with_db_logging_disabled$fn__36480.invoke(util.clj:131)
        at metabase.sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)
        at metabase.sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)
        at metabase.sync.util$with_start_and_finish_logging$fn__36469.invoke(util.clj:116)
        at metabase.sync.util$with_sync_events$fn__36464.invoke(util.clj:90)
  at metabase.sync.util$with_duplicate_ops_prevented$fn__36455.invoke(util.clj:69)
        at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:168)
        at metabase.sync.util$do_sync_operation.invoke(util.clj:165)
        at metabase.sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140.invoke(sync_metadata.clj:50)
        at metabase.sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139.invoke(sync_metadata.clj:47)
        at metabase.task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.Exception: Connections could not be acquired from the underlying database!
        at metabase.driver.sql_jdbc.execute$do_with_try_catch.invokeStatic(execute.clj:212)
        at metabase.driver.sql_jdbc.execute$do_with_try_catch.invoke(execute.clj:204)
        at metabase.driver.sql_jdbc.execute$execute_query.invokeStatic(execute.clj:272)
        at metabase.driver.sql_jdbc.execute$execute_query.invoke(execute.clj:266)
        at metabase.driver.sql_jdbc$fn__60591.invokeStatic(sql_jdbc.clj:47)
        at metabase.driver.sql_jdbc$fn__60591.invoke(sql_jdbc.clj:46)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.common$current_db_time$fn__31797$fn__31798.invoke(common.clj:178)
        at metabase.query_processor.store$do_with_new_store.invokeStatic(store.clj:35)
        at metabase.query_processor.store$do_with_new_store.invoke(store.clj:31)
        at metabase.driver.common$current_db_time$fn__31797.invoke(common.clj:175)
        ... 50 more

**Comment by flamber** [comment]
Can you include the log from when you start Metabase? It seems like it's from the middle.
And are you using master/head version or stable version like 0.31.2? Docker or jar-file?
Which OS are MySQL and Metabase on?

**Comment by xqwbx163** [comment]
OS:centos7.2
Mysql :Ali RDS mysql 5.6.16-log
using master/head version 0.32
I planned to use the stable version  0.31.2 , but I found  that this version has a big problem with the use of druid database, and my pro environment has a druid data source, so I can only give up the 0.31.2 version, using the latest version 0.32.
 0.32 fix Druid some issues, but can't connect to mysql version 5.6.16-log

**Comment by flamber** [comment]
Okay, it looks like the driver was changed from `mysql-connector-java 5.1.45` to `mariadb-java-client 2.3.0` in #9285 
But looking at the MariaDB knowledge base, it should be compatible with MySQL >=5.5.3
https://mariadb.com/kb/en/library/about-mariadb-connector-j/#choosing-a-version

I found this in the driver, which leads me to think that you can add the connection attribute `CLIENT_SESSION_TRACK=0` to your Metabase setting and it would skip over that part in the driver.
https://github.com/MariaDB/mariadb-connector-j/blob/5811d2683f3f6711593eef17cef54ba378f122e7/src/main/java/org/mariadb/jdbc/internal/protocol/AbstractConnectProtocol.java#L496
If that doesn't work, then I would say you should try modifying the Metabase source, so you're including the older driver and compile it.

@camsaul 0.32-head looks to be incompatible with RDS MySQL 5.6 because of `session_track_schema`

**Comment by xqwbx163** [comment]
i can't modify the MariaDB driver jar ,so try to modify the metabase source ,use the older mysql driver,but compile many times ,not success.

**Comment by camsaul** [comment]
@xqwbx163 include `CLIENT_SESSION_TRACK=0` as one of the additional connection options

**Comment by xqwbx163** [comment]
what should i do ?

**Comment by flamber** [comment]
@xqwbx163 
Have you tried to add the connection option, as suggested a couple of times?
![image](https://user-images.githubusercontent.com/1447303/55231790-4c3ff300-51e9-11e9-9ab7-a7aa0df11c25.png)
By the way, 0.32.0 was just released.

**Comment by xqwbx163** [comment]
i try to write client_session_track=0  or session_track_schema=0 , it not work .
the log :
03-29 22:18:01 ESC[1mDEBUG middleware.logESC[0m :: ESC[32mGET /api/database 200 (4 ms) (3 DB calls). Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (54 total active threads)ESC[0m
03-29 22:19:45 ESC[1mDEBUG middleware.logESC[0m :: ESC[31mPUT /api/database/11 400 (269 ms) (1 DB calls).ESC[0m
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}

03-29 22:19:45 ESC[1mDEBUG middleware.logESC[0m :: ESC[32mGET /api/database 200 (4 ms) (3 DB calls). Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (52 total active threads)ESC[0m
03-29 22:21:49 ESC[1mDEBUG middleware.logESC[0m :: ESC[31mPUT /api/database/11 400 (181 ms) (1 DB calls).ESC[0m
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}

03-29 22:21:49 ESC[1mDEBUG middleware.logESC[0m :: ESC[32mGET /api/database 200 (4 ms) (3 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued) (53 total active threads)ESC[0m
03-29 22:22:12 ESC[1mDEBUG middleware.logESC[0m :: ESC[31mPUT /api/database/11 400 (126 ms) (1 DB calls).ESC[0m
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}

03-29 22:22:12 ESC[1mDEBUG middleware.logESC[0m :: ESC[32mGET /api/database 200 (3 ms) (3 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued) (54 total active threads)ESC[0m
03-29 22:22:14 ESC[1mDEBUG middleware.logESC[0m :: ESC[31mPUT /api/database/11 400 (100 ms) (1 DB calls).ESC[0m
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}

03-29 22:22:14 ESC[1mDEBUG middleware.logESC[0m :: ESC[32mGET /api/database 200 (3 ms) (3 DB calls). Jetty threads: 8/50 (4 busy, 4 idle, 0 queued) (54 total active threads)ESC[0m

**Comment by flamber** [comment]
@xqwbx163 Try using the exact case `CLIENT_SESSION_TRACK=0`, not `client_session_track=0`

**Comment by xqwbx163** [comment]
@flamber   
I understand, I just write like that, but still does not work
![image](https://user-images.githubusercontent.com/20455410/55236216-679f1280-526a-11e9-9026-74cb8046c402.png)

**Comment by xqwbx163** [comment]
I have been submitting this question for a long time, and I am also an old user of metabase。
It is easy to install and use，i like it very much .
I always recommend my colleagues to use this system. But recently the new version has not solved the basic connection problem, which is very distressing.

**Comment by skeleton9** [comment]
I have came into the same problme. Looking for a solution.

**Comment by cyrusj89** [comment]
I am running into this as well. How to i revert back to the older version?

**Comment by camsaul** [comment]
Hey, can you try updating to a newer version of MySQL? 5.7 came out over 3 years ago, and I'm pretty confident that's working correctly -- that's the version we test against. I'm not sure the new MariaDB JDBC driver we're using supports MySQL 5.6.x

**Comment by flamber** [comment]
@camsaul 

The MariaDB [knowledge base](https://mariadb.com/kb/en/library/about-mariadb-connector-j/) says:
> MariaDB Connector/J is compatible with all MariaDB and MySQL server versions 5.5.3 and later.

Could there be an issue with setting session variables via additional parameters?
Someone in the forum [reported issue](https://discourse.metabase.com/t/java-sql-sqlsyntaxerrorexception-variable-sql-mode-cant-be-set-to-the-value-of-allow-invalid-dates/5883) with `sql_mode` today.

**Comment by xqwbx163** [comment]
MariaDB connector/J, it compatibility is still not good, my tidb3.0 is mysql5.7 version(#9548), but metabase is still unable to get the table field when identifying.

**Comment by camsaul** [comment]
Oh. If this is a session variable then you would need to set it like

```
sessionVariables=CLIENT_SESSION_TRACK=0
```

I'm not sure this would work since we're also setting `sessionVariables` in Metabase 0.32.0-0.32.2, in Metabase 0.32.3 (coming soon) this should work

**Comment by flamber** [comment]
Tested MySQL 5.6.24 (earliest version available) via Docker and can connect to it with Metabase 0.32.3, so either some of the changes in 0.32 have fixed it, or maybe it's a specific setup configuration.

**Comment by camsaul** [comment]
Ok, I think the fix I made in #9731 also fixed support for MySQL 5.6.x.

We've officially only supported and tested against MySQL 5.7.x+ for a while now. 5.7 came out ~3.5 years ago and Oracle EOL'ed 5.6 on macOS in October 2018 (not sure about other platforms). 

Hopefully 5.6.x will continue to work and I'll try to fix things if they're brought to my attention but I would recommend planning on upgrading to a newer version at some point in the future as  I can't promise we'll have the bandwidth to actively support it in the future.

**Comment by salsakran** [comment]
according to https://en.wikipedia.org/wiki/MySQL#Release_history
EOL for 5.6 isn't until 2021 =(

**Comment by camsaul** [comment]
I mean we *could* start officially supporting 5.6.x, but we've been testing against 5.7.x+ for a years now. Also like I said 5.6.x is EOL'ed on macOS so it's a little harder to run locally for dev purposes for the majority of the team

**Comment by xqwbx163** [comment]
@camsaul  
I use metabase 0.32.3 but can't connect  mysql5.6 and Tidb3.0 can not get table columns.
the log: 

04-10 23:34:06 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
04-10 23:34:08 INFO metabase.driver :: Registered abstract driver :sql  🚚
04-10 23:34:10 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-10 23:34:10 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

**04-10 23:34:10 INFO metabase.core :: Starting Metabase version v0.32.3 ( ) ...**
04-10 23:34:10 INFO metabase.core :: System timezone is 'Asia/Chongqing' ...
04-10 23:34:10 INFO metabase.plugins :: Loading plugins in /home/xieqing/plugins...
Extract file /modules/sparksql.metabase-driver.jar -> /home/xieqing/plugins/sparksql.metabase-driver.jar took 335 ms
Extract file /modules/bigquery.metabase-driver.jar -> /home/xieqing/plugins/bigquery.metabase-driver.jar took 2 ms
Extract file /modules/sqlserver.metabase-driver.jar -> /home/xieqing/plugins/sqlserver.metabase-driver.jar took 6 ms
Extract file /modules/sqlite.metabase-driver.jar -> /home/xieqing/plugins/sqlite.metabase-driver.jar took 14 ms
Extract file /modules/vertica.metabase-driver.jar -> /home/xieqing/plugins/vertica.metabase-driver.jar took 369 µs
Extract file /modules/redshift.metabase-driver.jar -> /home/xieqing/plugins/redshift.metabase-driver.jar took 12 ms
Extract file /modules/presto.metabase-driver.jar -> /home/xieqing/plugins/presto.metabase-driver.jar took 851 µs
Extract file /modules/druid.metabase-driver.jar -> /home/xieqing/plugins/druid.metabase-driver.jar took 2 ms
Extract file /modules/mongo.metabase-driver.jar -> /home/xieqing/plugins/mongo.metabase-driver.jar took 33 ms
Extract file /modules/google.metabase-driver.jar -> /home/xieqing/plugins/google.metabase-driver.jar took 16 ms
Extract file /modules/oracle.metabase-driver.jar -> /home/xieqing/plugins/oracle.metabase-driver.jar took 495 µs
Extract file /modules/snowflake.metabase-driver.jar -> /home/xieqing/plugins/snowflake.metabase-driver.jar took 78 ms
Extract file /modules/googleanalytics.metabase-driver.jar -> /home/xieqing/plugins/googleanalytics.metabase-driver.jar took 3 ms
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
04-10 23:34:11 DEBUG plugins.classloader :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@3082b46a...
04-10 23:34:11 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: :sql) 🚚
Load driver :sql-jdbc took 29 ms
04-10 23:34:11 INFO metabase.driver :: Registered driver :snowflake (parents: #{:sql-jdbc}) 🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
04-10 23:34:11 INFO metabase.driver :: Registered driver :presto (parents: #{:sql}) 🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
04-10 23:34:11 INFO metabase.driver :: Registered driver :mongo  🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
04-10 23:34:11 INFO metabase.driver :: Registered driver :druid  🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
04-10 23:34:11 INFO metabase.driver :: Registered driver :postgres (parents: :sql-jdbc) 🚚
Load driver :postgres took 13 ms
04-10 23:34:11 INFO metabase.driver :: Registered driver :redshift (parents: #{:postgres}) 🚚
04-10 23:34:11 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-10 23:34:11 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
04-10 23:34:11 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver"]
04-10 23:34:11 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

04-10 23:34:11 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
04-10 23:34:11 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Google Analytics Driver"]
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
04-10 23:34:11 INFO metabase.driver :: Registered driver :sqlserver (parents: #{:sql-jdbc}) 🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
04-10 23:34:11 INFO metabase.driver :: Registered driver :sqlite (parents: #{:sql-jdbc}) 🚚
04-10 23:34:11 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

04-10 23:34:11 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
04-10 23:34:11 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver" "Metabase Google Analytics Driver"]
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
04-10 23:34:11 INFO metabase.driver :: Registered abstract driver :google  🚚
04-10 23:34:11 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-10 23:34:11 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver"]
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
04-10 23:34:11 INFO metabase.driver :: Registered driver :googleanalytics (parents: #{:google}) 🚚
04-10 23:34:11 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-10 23:34:11 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
04-10 23:34:11 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google}) 🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
04-10 23:34:11 INFO metabase.driver :: Registered abstract driver :hive-like (parents: #{:sql-jdbc}) 🚚
04-10 23:34:11 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
04-10 23:34:11 INFO metabase.driver :: Registered driver :sparksql (parents: #{:hive-like}) 🚚
04-10 23:34:11 INFO metabase.driver :: Registered driver :mysql (parents: :sql-jdbc) 🚚
Load driver :mysql took 15 ms
04-10 23:34:11 INFO metabase.driver :: Registered driver :h2 (parents: :sql-jdbc) 🚚
Load driver :h2 took 11 ms
04-10 23:34:11 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-10 23:34:11 INFO metabase.db :: Verifying mysql Database Connection ...
04-10 23:34:11 INFO metabase.driver :: Initializing driver :sql...
04-10 23:34:11 INFO metabase.driver :: Initializing driver :sql-jdbc...
04-10 23:34:11 INFO metabase.driver :: Initializing driver :mysql...
04-10 23:34:11 INFO metabase.db :: Verify Database Connection ...  ✅
04-10 23:34:11 INFO metabase.db :: Running Database Migrations...
04-10 23:34:11 INFO metabase.db :: Setting up Liquibase...
04-10 23:34:11 INFO metabase.db :: Liquibase is ready.
04-10 23:34:11 INFO metabase.db :: Checking if Database has unrun migrations...
04-10 23:34:12 INFO metabase.db :: Database Migrations Current ...  ✅
04-10 23:34:12 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
04-10 23:34:12 INFO db.migrations :: Finished running data migrations.
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
04-10 23:34:12 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
04-10 23:34:12 INFO metabase.task :: Initializing task SyncDatabases 📆
04-10 23:34:13 DEBUG sync.util :: Sync operations in flight: {:sync-metadata #{7}}
04-10 23:34:13 INFO sync.util :: STARTING: Sync metadata for mysql Database 7 '资本报表'
04-10 23:34:13 DEBUG sync.util :: STARTING: step 'sync-timezone' for mysql Database 7 '资本报表'
04-10 23:34:13 INFO metabase.task :: Initializing task CheckForNewVersions 📆
04-10 23:34:13 INFO metabase.task :: Initializing task SendAnonymousUsageStats 📆
04-10 23:34:13 INFO metabase.task :: Initializing task SendAbandomentEmails 📆
04-10 23:34:13 INFO metabase.task :: Initializing task SendPulses 📆
04-10 23:34:13 INFO metabase.task :: Initializing task SendFollowUpEmails 📆
04-10 23:34:13 INFO metabase.task :: Initializing task TaskHistoryCleanup 📆
04-10 23:34:13 INFO metabase.core :: Metabase Initialization COMPLETE
04-10 23:34:23 INFO driver.mysql :: You may need to add trustServerCertificate=true to the additional connection options to connect with SSL.
04-10 23:34:23 DEBUG middleware.log :: POST /api/database 400 169 ms (0 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (47 total active threads)
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}

04-10 23:34:24 DEBUG middleware.log :: GET /api/database 200 19 ms (4 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (47 total active threads)
04-10 23:34:27 DEBUG middleware.log :: GET /api/session/properties 200 3 ms (1 DB calls) Jetty threads: 8/50 (7 busy, 1 idle, 0 queued) (48 total active threads)
04-10 23:34:27 DEBUG middleware.log :: GET /api/user/current 200 146 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)
04-10 23:34:28 DEBUG middleware.log :: GET /api/user/current 200 5 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)
04-10 23:34:28 DEBUG middleware.log :: GET /api/database 200 5 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)
04-10 23:34:28 DEBUG middleware.log :: GET /api/setting 200 4 ms (0 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)
04-10 23:34:59 INFO driver.mysql :: You may need to add trustServerCertificate=true to the additional connection options to connect with SSL.
**04-10 23:34:59 DEBUG middleware.log :: POST /api/database 400 168 ms (0 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)
{:valid false, :dbname "java.sql.SQLException: Unknown system variable 'session_track_schema'", :message "java.sql.SQLException: Unknown system variable 'session_track_schema'"}**

04-10 23:34:59 DEBUG middleware.log :: GET /api/database 200 4 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (48 total active threads)

**Comment by RMMSecurity** [comment]
Tested and working on multiple 5.6x installs. Some of the database connection strings in metabase had been modified where it had SSL set to true. 

After changing that we were good!

**Comment by haochihaokan** [comment]
This might be a bug of Aliyun RDS on the 5.6 version. 
I use Dremio and failed to connect to RDS MySQL and it seems it has similar problems.

[https://community.dremio.com/t/failed-to-connect-to-cloud-based-mysql-compatiable-service/2953.](url)

**Comment by flamber** [comment]
@haochihaokan Follow #11266 - seems like a driver upgrade might make it work
