### ISSUE TITLE
Postgres: When Metabase scans the schema it leaves the attributes in lowercase

### ISSUE THREAD

**Issue by facundofarias** [metabase/metabase#9487]
------
- Your databases: Postgres 9.6.11
- Metabase version: 0.30.3
- Metabase hosting environment: AWS
- Metabase internal database: Postgres

The Postgres database has tables defined with CapitalLetters, such as *Users*. Metabase, when doing the mapping it does not respect the first upper case letter, and so, when going to "Ask a question" -> "Custom", then clicking in the table produces the following error:
![screen shot 2019-02-25 at 5 21 48 pm](https://user-images.githubusercontent.com/2700564/53351836-fe05ae80-3921-11e9-9b8f-4bfd13d69670.png)

Of course, writing the SQL and respecting the first upper character it works (for example `select * from Users;`)

Any idea? How can we solve this?
Thanks.

-------

**Comment by flamber** [comment]
Hi @facundofarias 
I cannot reproduce your issue on 0.31.2 with Postgres 11.2
I've created a schema called "SampleData", with table "Users", with column "Test" and it works in Query Browser and SQL.
![image](https://user-images.githubusercontent.com/1447303/53358327-99345f00-38f5-11e9-8bbe-32cbe382e695.png)
```SQL
SELECT "SampleData"."Users"."Test" AS "Test", count(*) AS "count"
FROM "SampleData"."Users"
WHERE "SampleData"."Users"."Test" = 2
GROUP BY "SampleData"."Users"."Test"
ORDER BY "SampleData"."Users"."Test" ASC
```
But it looks like Postgres really likes to have it's structure in lowercase:
https://stackoverflow.com/questions/43111996/why-postgresql-does-not-like-uppercase-table-names

**Comment by facundofarias** [comment]
No, I am not using Redshift. Metabase it's in a Ubuntu host (AWS) and the database it's Postgres.
Will try updating to the latest metabase (0.31.2), but I don't think it will solve the problem. Maybe the fact that you have used Postgres 11.2 it's the key. 

Thanks a lot @flamber!

**Comment by facundofarias** [comment]
Right.

I've tested out again with PSQL 11.2 and it's seems to be working. I've also tried with PSQL 9.6, and locally it's seems to be working as well. Will try updating Metabase.

Thanks a lot @flamber, I think we can close the issue.
