### ISSUE TITLE
FK Remapping Doesn't Work On Lists Of Values

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9490]
Foreign key remapping does not work on lists of values. As a user I would like to be able to search on the mapped value of a field. Instead I can only punch in an ID. If the field is a search field it works as expected. Using a list of values is desired because we want to have a concrete set of values a user can select from without having to know the first letter of what to search for.

Concrete use case:
We have a table T with records that refer to another table representing an environment. We would like to present the user with a list of possible environments to filter on when using the FK field in T. If a search box is used there is no discrete list presented to the user. If a list is used the FK is not remapped so only ID's show up.

This could be tricky to implement which may be why it was skipped when FK remapping was added.

Steps to Reproduce:
1) Change Order > User to a list of values in the sample data
2) Attempt to set up a filter on the value

**Expected (image from using a search box on user)**
![image](https://user-images.githubusercontent.com/17504314/46293193-bfc9b600-c560-11e8-8ff5-aca7fee92f2c.png)

**Actual (make Order > User a list of values)**
![image](https://user-images.githubusercontent.com/17504314/46293079-74afa300-c560-11e8-9c1c-352c559f8055.png)

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Things have changed, so closing in favor of #13235, which is the reversed problem, but more problematic.
