### ISSUE TITLE
Unable to display neither x-ray nor raw data in docker 

### ISSUE THREAD

**Issue by sleepywhiskey** [metabase/metabase#9493]
I run my docker container by : 
`sudo docker run -d -p 3000:3000 --name metabase metabase/metabase`
following by:
`sudo docker start metabase`.
these commands are executed in the same ubuntu server that contains the postgreSQL through an ssh tunnel. 
after I connect to the Metabase server from my Mac, when I select my database, Metabase doesn't show neither x-ray nor any raw data, pro raw data it returns `Table 'TABLE' has no Fields associated with it.` for each table while I can run sql queries in `Ask me a Question` section with no problem. however I have a separate Metabase running locally on my Mac and connecting to database server which, and it works fine. any digger internet for hours but yet I have no solution for this.
Metabase version : 0.31.2.1
any help or suggestion?

**Comment by flamber** [comment]
Hi @sleepywhiskey 
Do you see anything in the Metabase logs?
What happens if you manually run Settings > Admin > Database > (db) > Sync database schema now ?

**Comment by salsakran** [comment]
@sleepywhiskey what's happening is that the metabase server is not able to connect to your database from within the container. I'd suggest trying to shell into the container and try to connect to the database. You might also try our discussion forum http://discourse.metabase.com

Closing as tiguring out what's going on is beyond the scope of the issue tracker.
