### ISSUE TITLE
Add documentation for MAX_SESSION_AGE

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#9495]
We don't refer to it anywhere in the docs I believe, and it's something that would be useful to document.

**Comment by lindsay-stevens** [comment]
Here's a draft. Not sure how it works with non-local / SSO auth (LDAP/JWT/SAML) - does an unattended timeout trigger a logout (i.e., backend sends it no matter what), or is it only when someone manually logs out (i.e. client has to trigger it)? Is there any way to set an idle timeout for Metabase?


## Configuring Session Timeout

Once a user logs in to Metabase, their session is generally ended one of two ways: the user logs out, or a certain number of minutes has elapsed. The latter can be configured with the setting `MAX_SESSION_AGE`, which by default is 20160 minutes (two weeks).

For example, to make this four weeks (40320 minutes), set the custom value in an environment variable before starting Metabase:

```
export MAX_SESSION_AGE=40320
java -jar metabase.jar
```

Beware that this setting is *not* an idle / inactivity time-out. If you set this to 15 minutes, your users have to log in (or re-authenticate) again every 15 minutes.

**Comment by camsaul** [comment]
Implemented in #12475
