### ISSUE TITLE
Build From Source Code

### ISSUE THREAD

**Issue by ltfi** [metabase/metabase#9496]
I'm trying to add metabase to my project so I want know how can I build this project from source code. And also I want to increase the csv download limit. Can I change this 1M row limit from source code ?

**Comment by flamber** [comment]
Hi @ltfi 

You can see how to compile in the documentation:
https://www.metabase.com/docs/latest/developers-guide.html

I can find references to the limit these two places, but I don't understand Clojure that well:
https://github.com/metabase/metabase/blob/4550244dd74d1677ef7a6b54bf9a991837e25805/src/metabase/mbql/util.clj#L480
https://github.com/metabase/metabase/blob/4550244dd74d1677ef7a6b54bf9a991837e25805/src/metabase/query_processor/middleware/limit.clj

**Comment by ltfi** [comment]
Thanks for the links and quick answer. 👍
