### ISSUE TITLE
Sharing Questions from personal collections

### ISSUE THREAD

**Issue by k2xl** [metabase/metabase#9505]
It seems way more difficult with the new UI/UX to share questions. The most common use case for our team members is creating questions and sharing them with others. But it seems that when questions are created they go into the Personal Collection for the user and the questions are private by default. Causing a lot of frustration for team members since they have to remember to move questions to a public folder.

Is there a way to make personal collections public? There's no lock icon available to edit permissions.

**Comment by tlrobinson** [comment]
The user can also select which collection to put the question into when they first save it.

**Comment by flamber** [comment]
Related #8406

**Comment by cparaskeva** [comment]
Guys any update on that issue?
