### ISSUE TITLE
Map doesn't support joins

### ISSUE THREAD

**Issue by kelsen** [metabase/metabase#9506]
As you can see from post http://discourse.metabase.com/t/map-wont-display-values/5271 I can't make Map works when the aggregate field is a column from a joined table, map won't display values.

-browser and the version: Google Chrome Versão 72.0.3626.119 (Versão oficial) 64 bits
- Your operating system: Windows 10 Pro
- Your databases: MySQL 5.6.33
- Metabase version: 0.31.2
- Metabase hosting environment: Ubuntu 16.04.5 LTS
- Metabase internal database: MySQL 5.7.25

- *Repeatable steps to reproduce the issue*
Sum fato_pedidovenda.VL_SOLICITADO and group by dim_pessoa.UF, change display to Map.
Expected result: Map painted with values from VL_SOLICITADO
Result: Map greyed out

`CREATE TABLE `fato_pedidovenda` (
  `CD_EMPRESA` bigint(20) DEFAULT NULL,
  `CD_PEDIDO` bigint(20) DEFAULT NULL,
  `CD_PRODUTO` bigint(20) DEFAULT NULL,
  `DT_CHEGADA` datetime DEFAULT NULL,
  `CD_CLIENTE` bigint(20) DEFAULT NULL,
  `CD_REPRESENTANTE` bigint(20) DEFAULT NULL,
  `DT_PREVBAIXA` datetime DEFAULT NULL,
  `QT_SOLICITADA` bigint(20) DEFAULT NULL,
  `QT_EXTRA` bigint(20) DEFAULT NULL,
  `QT_ATENDIDA` bigint(20) DEFAULT NULL,
  `QT_CANCELADA` bigint(20) DEFAULT NULL,
  `QT_PENDENTE` bigint(20) DEFAULT NULL,
  `VL_SOLICITADO` double DEFAULT NULL,
  `VL_EXTRA` bigint(20) DEFAULT NULL,
  `VL_ATENDIDO` double DEFAULT NULL,
  `VL_CANCELADO` double DEFAULT NULL,
  `VL_PENDENTE` bigint(20) DEFAULT NULL,
  `VL_DESCONTO` bigint(20) DEFAULT NULL,
  `DT_ATUALIZACAO` datetime DEFAULT NULL,
  UNIQUE KEY `idx_fato_pedidovenda_lookup` (`CD_EMPRESA`,`CD_PEDIDO`,`CD_PRODUTO`),
  KEY `CD_PRODUTO` (`CD_PRODUTO`),
  KEY `CD_CLIENTE` (`CD_CLIENTE`),
  KEY `CD_EMPRESA` (`CD_EMPRESA`),
  CONSTRAINT `fato_pedidovenda_ibfk_1` FOREIGN KEY (`CD_EMPRESA`) REFERENCES `dim_empresa` (`CD_EMPRESA`),
  CONSTRAINT `fato_pedidovenda_ibfk_2` FOREIGN KEY (`CD_PRODUTO`) REFERENCES `dim_produto` (`CD_PRODUTO`),
  CONSTRAINT `fato_pedidovenda_ibfk_3` FOREIGN KEY (`CD_CLIENTE`) REFERENCES `dim_pessoa` (`CD_PESSOA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1`

 CREATE TABLE `dim_pessoa` (
  `CD_PESSOA` bigint(20) NOT NULL DEFAULT '0',
  `NOME` varchar(60) DEFAULT NULL,
  `SITUACAO` varchar(7) DEFAULT NULL,
  `DT_CADASTRO` datetime DEFAULT NULL,
  `DT_ATUALIZACAO` datetime DEFAULT NULL,
  `TP_PESSOA` varchar(8) DEFAULT NULL,
  `SIGLA` varchar(19) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `COMPLEMENTO` varchar(65) DEFAULT NULL,
  `BAIRRO` varchar(65) DEFAULT NULL,
  `MUNICIPIO` varchar(40) DEFAULT NULL,
  `UF` varchar(11) DEFAULT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `PAÍS` varchar(30) DEFAULT NULL,
  `NUMERO` bigint(20) DEFAULT NULL,
  `IN_CLIENTE` varchar(6) DEFAULT NULL,
  `IN_FORNECEDOR` varchar(3) DEFAULT NULL,
  `IN_FUNCIONARIO` varchar(3) DEFAULT NULL,
  `IN_PROSPECT` varchar(3) DEFAULT NULL,
  `IN_GUIA` varchar(3) DEFAULT NULL,
  `IN_FIADOR` varchar(3) DEFAULT NULL,
  `IN_COLABORADOR` varchar(3) DEFAULT NULL,
  `IN_CONCORRENTE` varchar(3) DEFAULT NULL,
  `IN_REPRESENTANTE` varchar(3) DEFAULT NULL,
  `IN_FABRICANTE` varchar(3) DEFAULT NULL,
  `IN_TRANSPORTADORA` varchar(3) DEFAULT NULL,
  `CPFCNPJ` varchar(18) DEFAULT NULL,
  PRIMARY KEY (`CD_PESSOA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

**Comment by flamber** [comment]
Hi @kelsen 
I'm trying to reproduce by using the Sample Data, where I select `ORDERS` with View `Sum of TOTAL` and Grouped By `USER_ID -> STATE`
![image](https://user-images.githubusercontent.com/1447303/53658757-53da9f00-3c1f-11e9-98fd-2eed3247aff6.png)
Could it be a problem only when using the custom map?
Have you defined all the types (Entity Key and Foreign Key and ...) in the Data Model?

**Comment by kelsen** [comment]
I've `dim_pessoa.cd_pessoa` defined as Entity Key and `fato_pedidovenda.cd_cliente` as Foreign Key.
`dim_pessoa.uf` is defined as category.
I'm using https://raw.githubusercontent.com/fititnt/gis-dataset-brasil/master/uf/geojson/uf.json as custom map and `dim_pessoa.uf` does match with map identifier.

**Comment by kelsen** [comment]
I've found the culprit.
Changing field length did the trick.
From:
``UF` varchar(11) DEFAULT NULL`
To:
``UF` varchar(2) DEFAULT NULL`

**Comment by flamber** [comment]
@kelsen Great that you found the solution! Please close this issue.
