### ISSUE TITLE
Heroku In place Upgrade Succeeds but Does Not increment Actual Version

### ISSUE THREAD

**Issue by uhrohraggy** [metabase/metabase#9507]
### Bugs

- Your browser and the version: Version 71.0.3578.98 (Official Build) (64-bit)
- Your operating system: macOS Mojave v0.14 (18A391)
- Your databases: MySQL
- Metabase version: 0.29.0-RC1 => upgrading to 0.31.2 
- Metabase hosting environment: Heroku Enterprise
- Metabase internal database: Postgres

## *Repeatable steps to reproduce the issue*

- Have 0.29 RC 1 version installed
- Perform in-place upgrade by following https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html#deploying-new-versions-of-metabase
```
git clone https://github.com/metabase/metabase-deploy.git  
cd metabase-deploy
git remote add heroku https://git.heroku.com/your-metabase-app.git
git commit --allow-empty -m "empty commit"
git push -f heroku master
```
- Check version at /admin/settings/updates
- version is presented as `Metabase 0.31.2 is available. You're running 0.29.0-RC1`
-------

**Deploying to Heroku Logs** 
```
-----> JVM Common app detected
-----> Installing JDK 1.8... done
-----> Metabase app detected
-----> Downloading Metabase... from http://downloads.metabase.com/v0.31.2/metabase.jar to /tmp/build_ebfc9f024c14debaa610a4a415e301bf/target/uberjar/metabase.jardone
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 155.4M
-----> Launching...
       Released v21
       https://my-metabase-app.herokuapp.com/ deployed to Heroku
```

**Comment by uhrohraggy** [comment]
Is there any advice here other than to launch a brand new instance and copy the questions and dashboards from the old database manually?

**Comment by TheoMorice** [comment]
Hello, 
I have the same problem and cannot figure how to resolve this.
Eventually, you launch a brand new instance and copy the questions and dashboard from the old database manually ? 
Was it an easy process to copy questions and dashboard from the old to the new version ?
