### ISSUE TITLE
Smart numbers: configurable lag

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9510]
It would be nice to have other lag options besides 1.

Should these be freely configurable or predetermined based on unit (eg. if month you get YoY and that's it)?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by arjunbanker** [comment]
This would be really great!

**Comment by barralf** [comment]
Hi! Just wondering what is the status of this issue. Is this feature:
- in backlog
- under consideration 
- or even planned in roadmap. And if yes, when 🤩?

As a B2B SaaS co-founder, I really need this to better monitor the usage of our SaaS and send reports to our clients. 
Today, the fastest alternative has been to screenshot side to side reports for YoY (heavy and not so professional ^^). Cf. screenshot below

The best would be to choose freely the lag `X` and choose the `temporal unit` (hours/days/months/years/etc.) 
It's a good product opportunity, wondering if other competitive BI tools can do this (easily & quickly).

<img width="1339" alt="CleanShot 2022-10-05 at 18 04 44@2x" src="https://user-images.githubusercontent.com/16445278/194110840-b0cf8ba9-19ec-45ee-830d-b43f47e9f8cf.png">

Thank you in advance! Metabase rocks 🤟!
