### ISSUE TITLE
Zooming-in yields fks->join-information does not match schema

### ISSUE THREAD

**Issue by arjunbanker** [metabase/metabase#9516]
Getting a 
Output of fks->join-information does not match schema: [0;33m [nil nil {:pk-field-id (not (integer? nil))}] [0m

When zooming-in on the value of an aggregated cell using a query built by Metabase.

What additional information can I contribute to help reproduce this issue?

**Comment by flamber** [comment]
Hi @arjunbanker 
Yes, it would be helpful if you fill out all the information requested (version, datasource, etc).
And if you can reproduce it with Sample Data, then please describe the steps.
