### ISSUE TITLE
Schema information are not refreshed automatically

### ISSUE THREAD

**Issue by josteinaj** [metabase/metabase#9517]
- Your browser and the version: Chromium 72.0.3626.119
- Your operating system: Ubuntu 18.04.2 LTS
- Your databases: MariaDB Ver 15.1 Distrib 10.1.38-MariaDB
- Metabase version: v0.31.2
- Metabase hosting environment: Docker
- Metabase internal database: MariaDB Ver 15.1 Distrib 10.1.34-MariaDB

**Repeatable steps to reproduce the issue:**
- Update the schema for the database (for instance, add a new table, admin syncs schema to metabase)
- Use the question builder
- Observe that the changes in the schema are not visible (for instance, the newly created table are not visible)

**Comment by flamber** [comment]
Hi @josteinaj 
When you sync, do you see anything in the Metabase log, which could point to why it doesn't show the new table?

**Comment by josteinaj** [comment]
The tables are there now, so the logs might not give any interesting. The only error I'm getting just now when I sync is this, which is probably unrelated:

```
 SQLException:
 Message: Unknown or incorrect time zone: 'Europe/Brussels'
 SQLState: HY000
 Error Code: 1298
```

I'll check again the next time the tables disappear to see if the logs says anything new then.

**Comment by flamber** [comment]
@josteinaj 
Okay, logs would help a lot to figure out what Metabase is doing.
As for the time zone error, that's because you haven't added time zone information to MariaDB:
https://dba.stackexchange.com/questions/120945/how-do-i-resolve-this-error-error-1298-hy000-unknown-or-incorrect-time-zone

**Comment by josteinaj** [comment]
I'll have a look at the time zone error soon, thanks for the link.

Tables were missing again today. This is the log output when I synchronize the database schema now: 
[sync-when-tables-missing.txt](https://github.com/metabase/metabase/files/2940601/sync-when-tables-missing.txt)

I'm using Metabase in Norwegian so some of the log output is in Norwegian. Let me know if I need to translate anything.

Also worth noting: I have configured three databases in Metabase that connects to the same database, where I expose a different subset of the tables in each of them. I expose the tables starting with `datavarehus_` as the "Datavarehus" database in Metabase, the tables starting with `bibliofil_` as the "Bibliofil" database, and the tables starting with `dds_` as the "DDS" database. All of them are stored in MariaDB inside the `nlbdatavarehus` database. Everyone has access to the "Datavarehus" database in Metabase, but only some of us have access to the other databases.

Now that the tables are visible, this is the log output if I do another sync: 
[sync-when-tables-not-missing.txt](https://github.com/metabase/metabase/files/2940680/sync-when-tables-not-missing.txt)

The only difference between syncing when the tables are not visible vs when the tables are visible is this:

```diff
-03-07 XX:XX:XX INFO sync-metadata.tables :: Updating description for tables: (Tabell  "datavarehus_Subscription" Tabell  "datavarehus_Genre" Tabell  "datavarehus_CreativeWorkGenre" Tabell  "datavarehus_PublicationContribution" Tabell  "datavarehus_Loan" Tabell  "datavarehus_CreativeWorkSubject" Tabell  "datavarehus_PatronLibrary" Tabell  "datavarehus_Reservation" Tabell  "datavarehus_CreativeWork" Tabell  "datavarehus_CreativeWorkContribution" Tabell  "datavarehus_Order" Tabell  "datavarehus_Subject" Tabell  "datavarehus_Publication" Tabell  "datavarehus_Patron" Tabell  "datavarehus_Actor")
-03-07 XX:XX:XX DEBUG sync.util :: FINISHED: steg "sync-tables" for mysql Database 9 "Datavarehus" (5 ms)
+03-07 XX:XX:XX INFO sync-metadata.tables :: Found new tables: (Tabell  "importing_datavarehus_Subscription" Tabell  "datavarehus_Copy" Tabell  "bibliofil_Actor" Tabell  "bibliofil_Subscription" Tabell  "bibliofil_Reservation" Tabell  "bibliofil_Subject" Tabell  "datavarehus_Actor" Tabell  "importing_datavarehus_Loan" Tabell  "importing_datavarehus_Publication" Tabell  "datavarehus_PatronLibrary" Tabell  "bibliofil_Loan" Tabell  "bibliofil_Copy" Tabell  "datavarehus_Loan" Tabell  "dds_Order" Tabell  "bibliofil_PublicationContribution" Tabell  "importing_datavarehus_CreativeWork" Tabell  "datavarehus_Order" Tabell  "datavarehus_PublicationContribution" Tabell  "importing_datavarehus_Patron" Tabell  "bibliofil_CreativeWorkSubject" Tabell  "datavarehus_Patron" Tabell  "importing_datavarehus_PublicationContribution" Tabell  "datavarehus_Publication" Tabell  "bibliofil_Genre" Tabell  "importing_datavarehus_Copy" Tabell  "datavarehus_Genre" Tabell  "bibliofil_Publication" Tabell  "importing_datavarehus_Genre" Tabell  "bibliofil_Patron" Tabell  "importing_datavarehus_CreativeWorkGenre" Tabell  "importing_datavarehus_CreativeWorkContribution" Tabell  "importing_datavarehus_PatronLibrary" Tabell  "importing_datavarehus_Reservation" Tabell  "datavarehus_CreativeWorkContribution" Tabell  "importing_datavarehus_CreativeWorkSubject" Tabell  "dds_ImportLog" Tabell  "bibliofil_PatronLibrary" Tabell  "importing_datavarehus_Actor" Tabell  "bibliofil_CreativeWorkContribution" Tabell  "importing_datavarehus_Order" Tabell  "bibliofil_CreativeWorkGenre" Tabell  "datavarehus_CreativeWork" Tabell  "datavarehus_Subscription" Tabell  "importing_datavarehus_Subject" Tabell  "bibliofil_CreativeWork" Tabell  "datavarehus_Reservation" Tabell  "datavarehus_Subject" Tabell  "datavarehus_CreativeWorkSubject" Tabell  "datavarehus_CreativeWorkGenre")
+03-07 XX:XX:XX INFO sync-metadata.tables :: Updating description for tables: (Tabell  "importing_datavarehus_Genre" Tabell  "importing_datavarehus_Publication" Tabell  "bibliofil_CreativeWorkGenre" Tabell  "datavarehus_Subscription" Tabell  "bibliofil_CreativeWorkContribution" Tabell  "datavarehus_Genre" Tabell  "datavarehus_CreativeWorkGenre" Tabell  "importing_datavarehus_Loan" Tabell  "importing_datavarehus_Subscription" Tabell  "bibliofil_Copy" Tabell  "bibliofil_Loan" Tabell  "importing_datavarehus_Patron" Tabell  "importing_datavarehus_PatronLibrary" Tabell  "dds_ImportLog" Tabell  "bibliofil_CreativeWorkSubject" Tabell  "datavarehus_PublicationContribution" Tabell  "importing_datavarehus_CreativeWork" Tabell  "importing_datavarehus_Copy" Tabell  "dds_Order" Tabell  "bibliofil_Actor" Tabell  "importing_datavarehus_Reservation" Tabell  "datavarehus_Loan" Tabell  "importing_datavarehus_PublicationContribution" Tabell  "bibliofil_PatronLibrary" Tabell  "bibliofil_Patron" Tabell  "datavarehus_CreativeWorkSubject" Tabell  "bibliofil_Genre" Tabell  "bibliofil_Reservation" Tabell  "bibliofil_CreativeWork" Tabell  "datavarehus_PatronLibrary" Tabell  "datavarehus_Reservation" Tabell  "datavarehus_CreativeWork" Tabell  "datavarehus_CreativeWorkContribution" Tabell  "datavarehus_Order" Tabell  "importing_datavarehus_CreativeWorkGenre" Tabell  "datavarehus_Subject" Tabell  "bibliofil_Publication" Tabell  "importing_datavarehus_Actor" Tabell  "importing_datavarehus_Order" Tabell  "bibliofil_Subscription" Tabell  "bibliofil_Subject" Tabell  "bibliofil_PublicationContribution" Tabell  "datavarehus_Publication" Tabell  "importing_datavarehus_Subject" Tabell  "datavarehus_Copy" Tabell  "datavarehus_Patron" Tabell  "importing_datavarehus_CreativeWorkContribution" Tabell  "importing_datavarehus_CreativeWorkSubject" Tabell  "datavarehus_Actor")
+03-07 XX:XX:XX DEBUG sync.util :: FINISHED: steg "sync-tables" for mysql Database 9 "Datavarehus" (703 ms)
```

A bit more about what I do with the database outside of Metabase: I currently import data from two sources into the database (creating table names starting with `importing_`), then process them and swap them out with the existing ones (`importing_bibliofil_*` with `bibliofil_*` etc.). Then those tables are merged into `importing_datavarehus_*` and when it's done, it swaps out `importing_datavarehus_*` with `datavarehus_*`. I do it this way mainly because it's easy to avoid duplicate data from previous imports, bad references across tables etc. It may not give the best performance, but it's easier to maintain and understand, and it's good enough for our needs.

Here's all the log output between yesterday when the tables were visible, and today when the tables were not visible anymore: 
[metabase.log](https://github.com/metabase/metabase/files/2940794/metabase.log)

Metabase reports that it "Found new tables" on several occasions, when the `importing_` tables appear temporarily. Which is fine, I've marked those as hidden in the data model to avoid that they are temporarily visible to the users. But maybe this is where something happens to the main tables as well.

When it syncs, I see that it reports "Hash of … matches stored hash, skipping fields sync for table". What kind of hash does this refer to? Is it a hash of the table descriptions? If so, the hash of the `importing_datavarehus_*` tables and the hash of the `datavarehus_*` tables will be the same unless it includes the table names...

**Comment by flamber** [comment]
@josteinaj 

I don't understand "swap them out" - if you rename `importing_datavarehus_*` to `datavarehus_*`, then that's probably causing all the problems.

You can look in the internal Metabase database - check `metabase_table` to see if it constantly creates new IDs for each table, each time you import.

You can probably avoid this problem by creating a MariaDB user that only has access to the data you want to share with Metabase - or create Views - anything to limit Metabase to only see the actual data and not some temporary import stuff.

Let's see if the developers can see something in the logs.

**Comment by josteinaj** [comment]
By "swap them out" I mean that I've created a new version of the table, and then I swap out the old version with the new version. The new version is renamed to the same name as the old version.

For instance:
```sql
# 1. build the table importing_datavarehus_Publication in some way

# 2. replace the new table with the old table in a single atomic operation
RENAME TABLE datavarehus_Publication TO old_datavarehus_Publication, importing_datavarehus_Publication TO datavarehus_Publication;

# 3. delete the old version
DROP TABLE old_datavarehus_Publication;
```

Looking at the `metabase_table` as you suggest, I see there's a lot of tables with the same hash: 
[metabase_table.txt](https://github.com/metabase/metabase/files/2942229/metabase_table.txt)

**Comment by flamber** [comment]
Closing in favor of https://github.com/metabase/metabase/issues/10330#issuecomment-610900593
