### ISSUE TITLE
Add missing FK index on metabase_field.parent_id

### ISSUE THREAD

**Issue by lindsay-stevens** [metabase/metabase#9519]
- Your browser and the version: Chrome 72
- Your operating system: Windows 10
- Your databases: Postgres 10
- Metabase version: 0.28.6 (same issue in master though)
- Metabase hosting environment: CentOS 7
- Metabase internal database: Postgres

TLDR; Please add `CREATE INDEX ON metabase_field (parent_id);` to migrations.

*Repeatable steps to reproduce the issue*

- Create a database with 16 large schemas ~5000 columns each (~50 tables \* ~50-150 columns each)
- Creatively use Metabase such that each "database" is actually a schema from the same database
  - Resulting in e.g. 16\*16 = 256\*5000 = 1.28 million metabase_field records, 80k of which are visible
  - It would work fine if there was a setting for filtering schemas for a connection
  - See also issues 2086, 2591, 5500, 6622, 6833, 8045, 8083
- Discover that Metabase UI can't cope with that much metadata and easily crashes Chrome/Firefox
  - The metadata endpoints tend to return all metadata even if it's marked as hidden/cruft
  - Crash is due to exceeding JS VM memory limit
- Decide to delete most of the Metabase databases and just use SQL for most of them
- Deletion takes forever and appears to fail due to Nginx reverse proxy timeout as long as 10 mins

Even though deletion appears to fail in the UI (HTTP 504 from Ngnix), the Metabase job proceeds in the background. The root cause seems to be that during deletion metadata from `metabase_field`, batches of queries of the form `SELECT * FROM "metabase_field" WHERE "parent_id" = ?` are run. However, there's no index on `parent_id`, so these queries are all SeqScans and are thus very slow.

Deletion from `metabase_field` was proceeding at a pace of roughly 3 rows per second, but after adding an index it proceeded at more like 850 rows per second. The index was just `CREATE INDEX ON metabase_field (parent_id);`. Deletion still took about 2-5 minutes each overall though.

This index might also help with other lookups, syncs, scans, etc. It seems like in most places there's already an index for each foreign key but if you're interested I could try to find any other missing ones.

**Comment by camsaul** [comment]
Fixed by #9626
