### ISSUE TITLE
The embed background does not extend with data

### ISSUE THREAD

**Issue by Melidios** [metabase/metabase#9520]
- We embedding a dashboard into rails app, the iFrame height is smaller than dashboard height, when user scrolls the background doesn't extend all the way (this happens in Metabase preview, also).we also can see in the inspector the background is created inside of the iFrame content.
![screen shot 2019-03-06 at 10 12 54 am](https://user-images.githubusercontent.com/42850434/53892854-1436fd00-3ffb-11e9-9de6-20bae4f6c1fd.png)

-  Chrome 71.0.3578.98, Firefox 65.0
-  OS X 10.14.3
-  Postgres
- Metabase version v0.31.2
- Metabase hosting environment: Metabase.com

-------

**Comment by flamber** [comment]
Hi @Melidios 
Are you using the iFrame Resizer script?
https://www.metabase.com/docs/latest/administration-guide/13-embedding.html#resizing-dashboards-to-fit-their-content
Or do you see any errors in the browser console?

**Comment by Melidios** [comment]
We use the settings give by Metabase:  <iframe
    src="{{iframeUrl}}"
    frameborder="0"
    width="800"
    height="600"
    allowtransparency
></iframe>

**Comment by flamber** [comment]
@Melidios 
Okay, but then you've defined the height to 600px and the result would be what you see.
If you follow the link, then you can see an example of using the `onload="iFrameResize({}, this)"`

**Comment by Melidios** [comment]
Before opening the issue I did tested the height and width - but my dashboard will be changing constantly, so the background white board should be extended automatically, not manually. Thank you for iframeResizer, I have seen documentation but it wasn't clear how to use it. I figured it out eventually, it is working, thank you!

**Comment by flamber** [comment]
@Melidios So everything is working with the iFrame Resizer? If yes, then please close this issue :-)
