### ISSUE TITLE
Grab translations in POEditor

### ISSUE THREAD

**Issue by jrvidotti** [metabase/metabase#9522]
I've finished translations to portuguese for now (100%). But I see that some translations made 6 months ago by another user wasn't published to docker image that I am running.

When and how theses translations are published? How can we use the translations right now in our production deployments?

Thanks in advance!

![image](https://user-images.githubusercontent.com/5623041/53903152-55d6a080-4019-11e9-8ae3-5826f4eb87c3.png)

**Comment by tlrobinson** [comment]
@jrvidotti We only ship translations once they reach 100%.

I'm not sure where you're seeing Polish at 100%. It still says 93% in POEditor: https://poeditor.com/projects/po_edit?id_language=127&id=200535

**Comment by tlrobinson** [comment]
As far as using the translation right now, you can export the Polish translation from POEditor to the `locales` directory (https://github.com/metabase/metabase/tree/master/locales) and do a build yourself (either `./bin/build` to get a `metabase.jar` or `docker build .` to get a Docker image)

**Comment by jrvidotti** [comment]
@tlrobinson thanks for the fast response. I've did translation for portuguese (100%) not polish (93%). ;)

![image](https://user-images.githubusercontent.com/5623041/53911330-7b20da00-402c-11e9-8b48-e6f55e7154bf.png)

**Comment by tlrobinson** [comment]
@jrvidotti Oh sorry, not sure how I misread that. We have already shipped Portuguese so it should be available in the latest release. We'll continue to update it from POEditor in subsequent releases.
