### ISSUE TITLE
Docker RUN bin/build - No such file or directory

### ISSUE THREAD

**Issue by jrvidotti** [metabase/metabase#9529]
I am trying to do a simple "git clone" & "docker build .", but I am getting this error bellow. Tried to checkout to release-0.31.3 but error persists. What am I doing wrong?

 ---> 8aa8925849b4
Step 11/28 : ADD yarn.lock package.json ./
 ---> 8957d9a2b562
Step 12/28 : RUN yarn
 ---> Running in 0836ec4aaf8d
yarn install v1.12.3
$ echo $npm_execpath | grep -q yarn || echo '\033[0;33mSorry, npm is not supported. Please use Yarn (https://yarnpkg.com/).\033[0m'
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning gitbook-plugin-atoc@1.0.3: The engine "gitbook" appears to be invalid.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > grid-styled@4.1.0" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
warning " > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
[5/5] Building fresh packages...
Done in 135.89s.
Removing intermediate container 0836ec4aaf8d
 ---> 97eecfcab37b
Step 13/28 : ADD . .
 ---> ee586ce5f74e
Step 14/28 : RUN bin/build
 ---> Running in 5088ea8fecea
': No such file or directory
The command '/bin/sh -c bin/build' returned a non-zero code: 127

**Comment by flamber** [comment]
Hi @jrvidotti 
Did you build following the guide before trying to generate the docker image?
https://www.metabase.com/docs/latest/developers-guide.html
