### ISSUE TITLE
Progress chart goal bug

### ISSUE THREAD

**Issue by kelsen** [metabase/metabase#9530]
I believe there is a bug with progress charts goal, when I enter a value initiating with 1 or 2 the first digit and last currency symbols letter becomes invisible.

- browser and the version: Google Chrome Versão 72.0.3626.119 (Versão oficial) 64 bits
- Your operating system: Windows 10 Pro
- Your databases: MySQL 5.6.33
- Metabase version: 0.31.2
- Metabase hosting environment: Ubuntu 16.04.5 LTS
- Metabase internal database: MySQL 5.7.25

Select progress chart, enter meta value as 20 or 10, set currency format to symbol, meta displays "Meta R 0,00".
Expected result: "Meta R$20,00"

![progress meta bug](https://user-images.githubusercontent.com/2788238/53979687-3dd05100-40ed-11e9-9934-d603a5894c59.PNG)

**Comment by flamber** [comment]
Hi @kelsen 

I tried to reproduce this issue on 0.31.2 in English without success, but then I changed browser language to Portuguese (and French and Spanish) and then I'm seeing the same problem as you.
So something is happening to the `$` symbol, when using non-English. This is an `i18n` problem.

A workaround is to use Estilo="Normal" and use the "Adicione um prefixo" to add `R$`

**Comment by kelsen** [comment]
That is a issue only if you enter 1 or 2, 3 and above seems ok to me.

**Comment by kelsen** [comment]
Is this going to be adjusted in a new release? 
There are an workaround for 0.31.2?

**Comment by paulrosenzweig** [comment]
It looks like problem is coming from a regexp in ttag. I just opened a PR to fix it over there: https://github.com/ttag-org/ttag/pull/171
