### ISSUE TITLE
TiDB3.0 --- Error running sync step: Output of sync-fields-for-table! 

### ISSUE THREAD

**Issue by xqwbx163** [metabase/metabase#9548]
metabase 0.32.0 can't sync TiDB(dist mysql) table columns . 
OS:centos 7.2
Database :5.7.10-TiDB-v3.0.0-beta-27-g6398788

`Error syncing Fields for Table 'table568“order_info_p7”': (conn=58766) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:234)"
"org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
"org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
"org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)"
"org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:530)"
"org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:474)"
"org.mariadb.jdbc.MariaDbDatabaseMetaData.getColumns(MariaDbDatabaseMetaData.java:785)"
"com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3092)"
"--> driver.sql_jdbc.sync$describe_table_fields.invokeStatic(sync.clj:152)"
"driver.sql_jdbc.sync$describe_table_fields.doInvoke(sync.clj:145)"
"driver.sql_jdbc.sync$describe_table.invokeStatic(sync.clj:194)"
"driver.sql_jdbc.sync$describe_table.invoke(sync.clj:189)"
"driver.sql_jdbc$fn__60597.invokeStatic(sql_jdbc.clj:56)"
"driver.sql_jdbc$fn__60597.invoke(sql_jdbc.clj:55)"
"sync.fetch_metadata$fn__44622$table_metadata__44627$fn__44628.invoke(fetch_metadata.clj:18)"
"sync.fetch_metadata$fn__44622$table_metadata__44627.invoke(fetch_metadata.clj:15)"
"sync.sync_metadata.fields.fetch_metadata$fn__44944$db_metadata__44949$fn__44950.invoke(fetch_metadata.clj:82)"
"sync.sync_metadata.fields.fetch_metadata$fn__44944$db_metadata__44949.invoke(fetch_metadata.clj:78)"
"sync.sync_metadata.fields$fn__45447$sync_fields_for_table_BANG___45456$fn__45462$fn__45464.invoke(fields.clj:91)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.sync_metadata.fields$fn__45447$sync_fields_for_table_BANG___45456$fn__45462.invoke(fields.clj:90)"
"sync.sync_metadata.fields$fn__45447$sync_fields_for_table_BANG___45456.invoke(fields.clj:83)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498$iter__45499__45503$fn__45504$fn__45505.invoke(fields.clj:117)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498$iter__45499__45503$fn__45504.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497.invoke(fields.clj:111)"
"sync.util$fn__36577$run_step_with_metadata__36582$fn__36586$fn__36588.invoke(util.clj:356)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
"sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
"sync.util$fn__36577$run_step_with_metadata__36582$fn__36586.invoke(util.clj:353)"
"sync.util$fn__36577$run_step_with_metadata__36582.invoke(util.clj:348)"
"sync.util$fn__36767$run_sync_operation__36772$fn__36773$fn__36774.invoke(util.clj:438)"
"sync.util$fn__36767$run_sync_operation__36772$fn__36773.invoke(util.clj:438)"
"sync.util$fn__36767$run_sync_operation__36772.invoke(util.clj:432)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140$fn__46141.invoke(sync_metadata.clj:51)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"driver$fn__17883.invokeStatic(driver.clj:614)"
"driver$fn__17883.invoke(driver.clj:614)"
"sync.util$sync_in_context$fn__36483.invoke(util.clj:140)"
"sync.util$with_db_logging_disabled$fn__36480.invoke(util.clj:131)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__36469.invoke(util.clj:116)"
"sync.util$with_sync_events$fn__36464.invoke(util.clj:90)"
"sync.util$with_duplicate_ops_prevented$fn__36455.invoke(util.clj:69)"
"sync.util$do_sync_operation.invokeStatic(util.clj:168)"
"sync.util$do_sync_operation.invoke(util.clj:165)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140.invoke(sync_metadata.clj:50)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139.invoke(sync_metadata.clj:47)"
"api.database$fn__46802$fn__46803.invoke(database.clj:511)")

03 13 10:15:04 ERROR metabase.sync.util :: Error running sync step: Output of sync-fields-for-table! does not match schema: 

 (not (map? a-java.sql.SQLNonTransientConnectionException)) 

("--> sync.sync_metadata.fields$fn__45447$sync_fields_for_table_BANG___45456.invoke(fields.clj:83)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498$iter__45499__45503$fn__45504$fn__45505.invoke(fields.clj:117)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498$iter__45499__45503$fn__45504.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497$fn__45498.invoke(fields.clj:116)"
"sync.sync_metadata.fields$fn__45492$sync_fields_BANG___45497.invoke(fields.clj:111)"
"sync.util$fn__36577$run_step_with_metadata__36582$fn__36586$fn__36588.invoke(util.clj:356)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
"sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
"sync.util$fn__36577$run_step_with_metadata__36582$fn__36586.invoke(util.clj:353)"
"sync.util$fn__36577$run_step_with_metadata__36582.invoke(util.clj:348)"
"sync.util$fn__36767$run_sync_operation__36772$fn__36773$fn__36774.invoke(util.clj:438)"
"sync.util$fn__36767$run_sync_operation__36772$fn__36773.invoke(util.clj:438)"
"sync.util$fn__36767$run_sync_operation__36772.invoke(util.clj:432)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140$fn__46141.invoke(sync_metadata.clj:51)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"driver$fn__17883.invokeStatic(driver.clj:614)"
"driver$fn__17883.invoke(driver.clj:614)"
"sync.util$sync_in_context$fn__36483.invoke(util.clj:140)"
"sync.util$with_db_logging_disabled$fn__36480.invoke(util.clj:131)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__36469.invoke(util.clj:116)"
"sync.util$with_sync_events$fn__36464.invoke(util.clj:90)"
"sync.util$with_duplicate_ops_prevented$fn__36455.invoke(util.clj:69)"
"sync.util$do_sync_operation.invokeStatic(util.clj:168)"
"sync.util$do_sync_operation.invoke(util.clj:165)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139$fn__46140.invoke(sync_metadata.clj:50)"
"sync.sync_metadata$fn__46134$sync_db_metadata_BANG___46139.invoke(sync_metadata.clj:47)"
"api.database$fn__46802$fn__46803.invoke(database.clj:511)")`

**Comment by sbelak** [comment]
Does this happen consistently when you try to run sync (you can trigger it manually from Admin -> Databases)?

**Comment by xqwbx163** [comment]
Yes, the log  will repeat again

**Comment by flamber** [comment]
@xqwbx163 
Have you tried the new Metabase 0.32.3 release?
Looking at the log, it seems like it was the server that dropped the connection.
Do you see anything in the MySQL logs?
Do you have the same problem if you use TiDB-2.1.7 instead of TiDB-3.0.0-beta?

**Comment by xqwbx163** [comment]
Haven't tried to use Metabase 0.32.3 yet.
I think the key  is  the Mariadb driver, Mariadb driver can get the Tidb table name,but can't not get the table column
If I add new table, i only manual add the table fields in the source database of the metabase every time.

**Comment by xqwbx163** [comment]
@flamber 
i download metabase-0.32.4 ,and install centos 7.2
but still not get table column and not connect Ali RDS: mysql-5.6 

`04-15 16:39:56 DEBUG sync.util :: Sync operations in flight: {:sync-metadata #{25}}
04-15 16:39:56 INFO sync.util :: STARTING: Sync metadata for mysql Database 25 'TIDB'
04-15 16:39:56 DEBUG middleware.log :: POST /api/database/25/sync_schema 200 2 ms (1 DB calls) Jetty threads: 8/50 (4 busy, 2 idle, 0 queued) (56 total active threads)
04-15 16:39:56 DEBUG sync.util :: STARTING: step 'sync-timezone' for mysql Database 25 'TIDB'
04-15 16:39:56 DEBUG sync.util :: FINISHED: step 'sync-timezone' for mysql Database 25 'TIDB' (283 ms)
04-15 16:39:56 DEBUG sync.util :: STARTING: step 'sync-tables' for mysql Database 25 'TIDB'
04-15 16:39:56 DEBUG sync.util :: FINISHED: step 'sync-tables' for mysql Database 25 'TIDB' (104 ms)
04-15 16:39:56 DEBUG sync.util :: STARTING: step 'sync-fields' for mysql Database 25 'TIDB'
04-15 16:39:57 ERROR sync.util :: Error syncing Fields for Table 'Table 568 'order_info_p7'': (conn=45225) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:234)"
 "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
 "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
 "org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)"
 "org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:530)"
 "org.mariadb.jdbc.MariaDbDatabaseMetaData.executeQuery(MariaDbDatabaseMetaData.java:474)"
 "org.mariadb.jdbc.MariaDbDatabaseMetaData.getColumns(MariaDbDatabaseMetaData.java:785)"
 "com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getColumns(NewProxyDatabaseMetaData.java:3068)"
 "--> driver.sql_jdbc.sync$describe_table_fields.invokeStatic(sync.clj:150)"
 "driver.sql_jdbc.sync$describe_table_fields.doInvoke(sync.clj:147)"
 "driver.sql_jdbc.sync$describe_table.invokeStatic(sync.clj:196)"
 "driver.sql_jdbc.sync$describe_table.invoke(sync.clj:191)"
 "driver.sql_jdbc$fn__61798.invokeStatic(sql_jdbc.clj:57)"
 "driver.sql_jdbc$fn__61798.invoke(sql_jdbc.clj:56)"
 "sync.fetch_metadata$fn__44430$table_metadata__44435$fn__44436.invoke(fetch_metadata.clj:18)"
 "sync.fetch_metadata$fn__44430$table_metadata__44435.invoke(fetch_metadata.clj:15)"
 "sync.sync_metadata.fields.fetch_metadata$fn__44752$db_metadata__44757$fn__44758.invoke(fetch_metadata.clj:82)"
 "sync.sync_metadata.fields.fetch_metadata$fn__44752$db_metadata__44757.invoke(fetch_metadata.clj:78)"
 "sync.sync_metadata.fields$fn__45255$sync_fields_for_table_BANG___45264$fn__45270$fn__45272.invoke(fields.clj:91)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.sync_metadata.fields$fn__45255$sync_fields_for_table_BANG___45264$fn__45270.invoke(fields.clj:90)"
 "sync.sync_metadata.fields$fn__45255$sync_fields_for_table_BANG___45264.invoke(fields.clj:83)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306$iter__45307__45311$fn__45312$fn__45313.invoke(fields.clj:117)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306$iter__45307__45311$fn__45312.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305.invoke(fields.clj:111)"
 "sync.util$fn__36514$run_step_with_metadata__36519$fn__36523$fn__36525.invoke(util.clj:356)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
 "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
 "sync.util$fn__36514$run_step_with_metadata__36519$fn__36523.invoke(util.clj:353)"
 "sync.util$fn__36514$run_step_with_metadata__36519.invoke(util.clj:348)"
 "sync.util$fn__36706$run_sync_operation__36711$fn__36712$fn__36713.invoke(util.clj:441)"
 "sync.util$fn__36706$run_sync_operation__36711$fn__36712.invoke(util.clj:441)"
 "sync.util$fn__36706$run_sync_operation__36711.invoke(util.clj:435)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993$fn__45994.invoke(sync_metadata.clj:51)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "driver$fn__16646.invokeStatic(driver.clj:644)"
 "driver$fn__16646.invoke(driver.clj:644)"
 "sync.util$sync_in_context$fn__36420.invoke(util.clj:140)"
 "sync.util$with_db_logging_disabled$fn__36417.invoke(util.clj:131)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__36406.invoke(util.clj:116)"
 "sync.util$with_sync_events$fn__36401.invoke(util.clj:90)"
 "sync.util$with_duplicate_ops_prevented$fn__36392.invoke(util.clj:69)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
 "sync.util$do_sync_operation.invoke(util.clj:165)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993.invoke(sync_metadata.clj:50)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992.invoke(sync_metadata.clj:47)"
 "api.database$fn__56958$fn__56959.invoke(database.clj:511)")

04-15 16:39:57 ERROR sync.util :: Error running sync step: Output of sync-fields-for-table! does not match schema:

           (not (map? a-java.sql.SQLNonTransientConnectionException))


("--> sync.sync_metadata.fields$fn__45255$sync_fields_for_table_BANG___45264.invoke(fields.clj:83)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306$iter__45307__45311$fn__45312$fn__45313.invoke(fields.clj:117)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306$iter__45307__45311$fn__45312.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305$fn__45306.invoke(fields.clj:116)"
 "sync.sync_metadata.fields$fn__45300$sync_fields_BANG___45305.invoke(fields.clj:111)"
 "sync.util$fn__36514$run_step_with_metadata__36519$fn__36523$fn__36525.invoke(util.clj:356)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
 "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
 "sync.util$fn__36514$run_step_with_metadata__36519$fn__36523.invoke(util.clj:353)"
 "sync.util$fn__36514$run_step_with_metadata__36519.invoke(util.clj:348)"
 "sync.util$fn__36706$run_sync_operation__36711$fn__36712$fn__36713.invoke(util.clj:441)"
 "sync.util$fn__36706$run_sync_operation__36711$fn__36712.invoke(util.clj:441)"
 "sync.util$fn__36706$run_sync_operation__36711.invoke(util.clj:435)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993$fn__45994.invoke(sync_metadata.clj:51)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
 "sync.util$do_with_error_handling.invoke(util.clj:144)"
 "driver$fn__16646.invokeStatic(driver.clj:644)"
 "driver$fn__16646.invoke(driver.clj:644)"
 "sync.util$sync_in_context$fn__36420.invoke(util.clj:140)"
 "sync.util$with_db_logging_disabled$fn__36417.invoke(util.clj:131)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
 "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
 "sync.util$with_start_and_finish_logging$fn__36406.invoke(util.clj:116)"
 "sync.util$with_sync_events$fn__36401.invoke(util.clj:90)"
 "sync.util$with_duplicate_ops_prevented$fn__36392.invoke(util.clj:69)"
 "sync.util$do_sync_operation.invokeStatic(util.clj:168)"
 "sync.util$do_sync_operation.invoke(util.clj:165)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993.invoke(sync_metadata.clj:50)"
 "sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992.invoke(sync_metadata.clj:47)"
 "api.database$fn__56958$fn__56959.invoke(database.clj:511)")

04-15 16:39:57 INFO sync.util :: FINISHED: Sync metadata for mysql Database 25 'TIDB' (538 ms)
04-15 16:39:57 DEBUG sync.util :: Sync operations in flight: {:analyze #{25}}
`

**Comment by flamber** [comment]
@xqwbx163 
But the server closes the connection, so there should be something in the logs of the database server.
`socket was closed by server`
And you didn't say if you tried with TiDB-2.1.7

**Comment by xqwbx163** [comment]
Not try to the TiDB-2.17 version,
Because i used metabase0.30.4 link to tidb 3.0 ,everything run perfect

**Comment by gsunsnackv** [comment]
I have the exact same error trying to connect to Redshift

**Comment by flamber** [comment]
@gsunsnackv 
So you're also seeing the following error on 0.32.4 with Redshift?
```
Error syncing Fields for Table '...“...”': (conn=...) unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
```

**Comment by gsunsnackv** [comment]
@flamber No. I read the whole thing wrong and commented too quickly. Sorry about that

**Comment by camsaul** [comment]
> Ali RDS: mysql-5.6

Unfortunately Metabase currently only officially supports MySQL 5.7 or newer, there seems to be problems getting 5.6 to work with the MariaDB JDBC driver we started using in 0.32

**Comment by xqwbx163** [comment]
@camsaul @flamber 
i try to use metabase0.32.10 link to tidb 3.0,
sync database schema   
show error :
![image](https://user-images.githubusercontent.com/20455410/63152047-7d587d00-c03d-11e9-87e2-995538b9d1c4.png)
then i print the tidb log 
find this error sql 
![image](https://user-images.githubusercontent.com/20455410/63152451-754d0d00-c03e-11e9-8176-75c5317cb1b9.png)

execute sql on tidb  > 2013 - Lost connection to MySQL server during query
![image](https://user-images.githubusercontent.com/20455410/63157583-d8906c80-c049-11e9-80a7-4513496036ff.png)

"
SELECT
	TABLE_SCHEMA TABLE_CAT,
	NULL TABLE_SCHEM,
	TABLE_NAME,
	COLUMN_NAME,
CASE	data_type 	WHEN 'bit' THEN	- 7 WHEN 'tinyblob' THEN -3 
	WHEN 'mediumblob' THEN -4 
	WHEN 'longblob' THEN -4 
	WHEN 'blob' THEN -4 
	WHEN 'tinytext' THEN 12 
	WHEN 'mediumtext' THEN -1 
	WHEN 'longtext' THEN -1 
	WHEN 'text' THEN -1 
	WHEN 'date' THEN 91 
	WHEN 'datetime' THEN 93 
	WHEN 'decimal' THEN 3 
	WHEN 'double' THEN 8 
	WHEN 'enum' THEN 12 
	WHEN 'float' THEN 7 
	WHEN 'int' THEN IF ( COLUMN_TYPE LIKE '%unsigned%', 4, 4 ) 	
	WHEN 'bigint' THEN -5 
	WHEN 'mediumint' THEN 4 
	WHEN 'null' THEN 0 
	WHEN 'set' THEN 12 
	WHEN 'smallint' THEN IF( COLUMN_TYPE LIKE '%unsigned%', 5, 5 ) 
	WHEN 'varchar' THEN 12 
	WHEN 'varbinary' THEN -3 
	WHEN 'char' THEN 1 
	WHEN 'binary' THEN - 2 
	WHEN 'time' THEN 92 
	WHEN 'timestamp' THEN 93 
	WHEN 'tinyint' THEN IF ( COLUMN_TYPE LIKE 'tinyint(1)%',- 7,- 6 ) 
	WHEN 'year' THEN 91 ELSE 1111 
	END DATA_TYPE,
IF (COLUMN_TYPE LIKE 'tinyint(1)%','BIT',UCASE(IF(COLUMN_TYPE LIKE '%(%)%',CONCAT(SUBSTRING( COLUMN_TYPE, 1, LOCATE( '(', COLUMN_TYPE ) - 1 ),SUBSTRING( COLUMN_TYPE, 1+ locate( ')', COLUMN_TYPE ) ) ),COLUMN_TYPE ) ) ) TYPE_NAME,
CASE	DATA_TYPE 	WHEN 'time' THEN IF( DATETIME_PRECISION = 0, 10, CAST( 11 + DATETIME_PRECISION AS signed INTeger ) ) 
	WHEN 'date' THEN 10 
	WHEN 'datetime' THEN IF( DATETIME_PRECISION = 0, 19, CAST( 20 + DATETIME_PRECISION AS signed INTEGER ) ) 
	WHEN 'timestamp' THEN IF( DATETIME_PRECISION = 0, 19, CAST( 20 + DATETIME_PRECISION AS signed INTEGER ) ) ELSE IF( NUMERIC_PRECISION IS NULL, LEAST( CHARACTER_MAXIMUM_LENGTH, 2147483647 ), NUMERIC_PRECISION ) END COLUMN_SIZE,
	65535 BUFFER_LENGTH,
	CONVERT ( CASE DATA_TYPE WHEN 'year' THEN NUMERIC_SCALE WHEN 'tinyint' THEN 0 ELSE NUMERIC_SCALE END, UNSIGNED INTEGER ) DECIMAL_DIGITS,
	10 NUM_PREC_RADIX,
IF( IS_NULLABLE = 'yes', 1, 0 ) NULLABLE,
	COLUMN_COMMENT REMARKS,
	COLUMN_DEFAULT COLUMN_DEF,
	0 SQL_DATA_TYPE,
	0 SQL_DATETIME_SUB,
	LEAST( CHARACTER_OCTET_LENGTH, 2147483647 ) CHAR_OCTET_LENGTH,
	ORDINAL_POSITION,
	IS_NULLABLE,
	NULL SCOPE_CATALOG,
	NULL SCOPE_SCHEMA,
	NULL SCOPE_TABLE,
	NULL SOURCE_DATA_TYPE,
IF( EXTRA = 'auto_increment', 'YES', 'NO' ) IS_AUTOINCREMENT,
IF( EXTRA IN ( 'VIRTUAL', 'PERSISTENT', 'VIRTUAL GENERATED', 'STORED GENERATED' ), 'YES', 'NO' ) IS_GENERATEDCOLUMN 
FROM
	INFORMATION_SCHEMA.COLUMNS 
WHERE
	( ISNULL( DATABASE ( ) ) OR ( TABLE_SCHEMA = DATABASE ( ) ) ) 
and ( TABLE_NAME LIKE 'm_dim_day' ) 
and (1=1)
ORDER BY
	TABLE_CAT,
	TABLE_SCHEM,
	TABLE_NAME,
	ORDINAL_POSITION
	
"
But the same sql ,i run in mysql ,it is ok .
i guess that the second column"NULL TABLE_SCHEM," is key, TiDB doesn't handle sort by NULL correctly, 
when i remove order by TABLE_SCHEM, the sql execute is ok and get the columns,
![image](https://user-images.githubusercontent.com/20455410/63157792-56ed0e80-c04a-11e9-93ac-15439d4f1815.png)
