### ISSUE TITLE
documentation for npm shrinkwrap usage in dev

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#955]
would be nice to just have a quick primer on when we need to use it and any potential gotchas.

**Comment by camsaul** [comment]
+1

I think @tlrobinson is still the only one who 100% understands how to use this

**Comment by tlrobinson** [comment]
You need to use it every time you add/remove/change a dependency in package.json.

As for potential gotchas, unless it's the 2nd Wednesday of the month, there's a full moon, and the stars are aligned, then good luck...
