### ISSUE TITLE
Metabase getting exited after cpu usage hitting more than 200 percent

### ISSUE THREAD

**Issue by danishdshadab** [metabase/metabase#9552]
I am trying to migrate from H2 to Postgres DB through Metabase docker. I saved the old H2 db in local  directory and have been trying the below command.
However in the mid of migration state the cpu usage of metabase is getting more than 200 percent
and the metabase container is getting killed. Please suggest

Command below,
starting postgres container:-
docker run --rm --name pg-docker \
-v $HOME/MetabaseDocker-V2/newDocker/data/new:/var/lib/postgresql/data \
-e POSTGRES_USER=postgres \
-e POSTGRES_PASSWORD=docker \
-e POSTGRES_DB=metabase \
-d -p 5432:5432  postgres

docker run -p 3000:3000 --name metabase \
    -v /Users/dshadab/MetabaseDocker-V2/newDocker/data/metabase:/metabase-data \
    -e MB_DB_FILE=/metabase-data/metabase.db \
    -e MB_DB_TYPE=postgres \
    -e MB_DB_PORT=5432 \
    -e MB_DB_USER=postgres \
    -e MB_DB_PASS=docker \
    -e MB_DB_DBNAME=metabase \
    -e MB_DB_HOST=172.17.0.3 \
    -e "JAVA_TOOL_OPTIONS=-Xmx4g" \
    metabase/metabase load-from-h2

Metabase container log below:
Picked up JAVA_TOOL_OPTIONS: -Xmx4g
03-13 13:42:09 INFO metabase.util :: Loading Metabase...
03-13 13:42:09 INFO metabase.util :: Maximum memory available to JVM: 3.6 GB
03-13 13:42:17 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
 For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
03-13 13:42:29 INFO metabase.db :: Verifying postgres Database Connection ...
03-13 13:42:30 INFO metabase.db :: Verify Database Connection ...  ✅
03-13 13:42:30 INFO metabase.db :: Running Database Migrations...
03-13 13:42:30 INFO metabase.db :: Setting up Liquibase...
03-13 13:42:30 INFO metabase.db :: Liquibase is ready.
03-13 13:42:30 INFO metabase.db :: Checking if Database has unrun migrations...
03-13 13:42:33 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
03-13 13:42:33 INFO metabase.db :: Migration lock is cleared. Running migrations...
03-13 13:42:38 INFO metabase.db :: Database Migrations Current ...  ✅
Temporarily disabling DB constraints...
[OK]
Transfering 1 instances of Database....[OK]
Transfering 8 instances of User....[OK]
Transfering 19 instances of Setting....[OK]
Transfering 80 instances of Dependency....[OK]
Transfering 21 instances of Table....[OK]
Transfering 1271 instances of Field........[OK]
Transfering 467 instances of FieldValues.....[OK]
Transfering 12 instances of Segment....[OK]
Transfering 46 instances of Metric....[OK]
Transfering 618 instances of Revision......[OK]
Transfering 850 instances of ViewLog......[OK]
Transfering 157 instances of Session....[OK]
Transfering 2 instances of Dashboard....[OK]
Transfering 258 instances of Card....[OK]
Transfering 2 instances of DashboardCard....[OK]
Transfering 629 instances of Activity......[OK]
Transfering 5 instances of Pulse....[OK]
Transfering 26 instances of PulseCard....[OK]
Transfering 5 instances of PulseChannel....[OK]
Transfering 13 instances of PulseChannelRecipient....[OK]
Transfering 3 instances of PermissionsGroup....[OK]
Transfering 13 instances of PermissionsGroupMembership....[OK]
Transfering 43 instances of Permissions....[OK]
Transfering 27 instances of Collection....[OK]
Transfering 3371 instances of TaskHistory...............[OK]
Transfering 14 instances of DataMigrations....[OK]
Setting postgres sequence ids to proper values...
[OK]

Everytime the Metabase is getting killed after setting progress sequence ids.

Please suggest

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment]
Hi @danishdshadab 
Which version of Metabase?
Are you migrating and upgrading Metabase at the same time?
Have you tried using `-e MB_DB_AUTOMIGRATE=false`, and doing the migration manually? I haven't tried this, but might be an option.
https://www.metabase.com/docs/latest/operations-guide/start.html#running-metabase-database-migrations-manually

**Comment by danishdshadab** [comment]
hi @flamber 
The version of metabase is  0.31.2, which is same from old one.

I tried -e MB_DB_AUTOMIGRATE=false but the issue persist,
Postgres version i tried is 9.6 and 11.2 both. 
However in postgres log i saw the below error, and i guess that is the root cause

2019-03-13 17:35:29.754 UTC [67] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
2019-03-13 17:35:29.754 UTC [67] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock

please suggest

**Comment by flamber** [comment]
@danishdshadab 
But when you do `MB_DB_AUTOMIGRATE=false`, is the structure generated also lowercase? Don't have access to check Postgres right now, but on an instance using MariaDB, that specific table is uppercase.

**Comment by danishdshadab** [comment]
Thanks for the quick response, however i am not sure what you meant by 'is the structure generated also lowercase'. 
for reviewing purpose, please find below the log of postgres container log after i used MB_DB_AUTOMIGRATE=false, it is fairly same as before.

------------------------------------------------------------
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2019-03-13 21:51:16.535 UTC [41] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-03-13 21:51:16.641 UTC [42] LOG:  database system was shut down at 2019-03-13 21:51:11 UTC
2019-03-13 21:51:16.679 UTC [41] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2019-03-13 21:51:20.352 UTC [41] LOG:  received fast shutdown request
waiting for server to shut down...2019-03-13 21:51:20.362 UTC [41] LOG:  aborting any active transactions
2019-03-13 21:51:20.377 UTC [41] LOG:  background worker "logical replication launcher" (PID 48) exited with exit code 1
2019-03-13 21:51:20.380 UTC [43] LOG:  shutting down
.2019-03-13 21:51:20.669 UTC [41] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2019-03-13 21:51:20.743 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-03-13 21:51:20.744 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-03-13 21:51:20.750 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-03-13 21:51:20.900 UTC [59] LOG:  database system was shut down at 2019-03-13 21:51:20 UTC
2019-03-13 21:51:20.961 UTC [1] LOG:  database system is ready to accept connections
2019-03-13 21:51:53.143 UTC [67] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
2019-03-13 21:51:53.143 UTC [67] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock

please suggest.

**Comment by flamber** [comment]
@danishdshadab 
When you use `MB_DB_AUTOMIGRATE=false`, then it should print all the changes in the Metabase log, so you can review it and manually make the queries to your database.
Go to you Postgres `public` schema and see if there's a table called `DATABASECHANGELOGLOCK` because then it's probably a problem with the casing. Then try renaming it to lowercase.

**Comment by danishdshadab** [comment]
The table DATABASECHANGELOGLOCK is already in lowercase is postgres public schema.
And the select query return values as per below

postgres=# select * from databasechangeloglock;

 id | locked | lockgranted | lockedby 
----+--------+-------------+----------
  1    | f            |                        | 
(1 row)

The log from postgres container is below
2019-03-14 19:54:03.147 UTC [41] LOG:  received fast shutdown request
waiting for server to shut down...2019-03-14 19:54:03.150 UTC [41] LOG:  aborting any active transactions
2019-03-14 19:54:03.152 UTC [41] LOG:  background worker "logical replication launcher" (PID 48) exited with exit code 1
2019-03-14 19:54:03.156 UTC [43] LOG:  shutting down
.2019-03-14 19:54:03.200 UTC [41] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2019-03-14 19:54:03.287 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-03-14 19:54:03.287 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-03-14 19:54:03.293 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-03-14 19:54:03.366 UTC [50] LOG:  database system was shut down at 2019-03-14 19:54:03 UTC
2019-03-14 19:54:03.394 UTC [1] LOG:  database system is ready to accept connections
2019-03-14 19:54:56.209 UTC [58] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
2019-03-14 19:54:56.209 UTC [58] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock

Is it do something with permission..

**Comment by flamber** [comment]
It's easy to test permissions, just login with the same credentials on Postgres as Metabase uses and run the query:
```
SELECT COUNT(*) FROM public.databasechangeloglock
```
Otherwise try with a different database or install directly instead of Docker.
If that doesn't work, then I don't know what's wrong and you have to see if someone else can see the problem.

**Comment by danishdshadab** [comment]
Thanks for your help, 
I checked the permission is there as the query went through.

And i have to use docker as later i have to deploy them in EC2.

But thanks for ur help .

**Comment by danishdshadab** [comment]
The Error were occurring due to unique key constraint in postgres. For some reason the constraint were not allowing the records to be added in tables.
So the resolution (which look lame though) i figured is of two step.

1. Run the migration and let the error occur. By this time the postgres container will be killed.
login back to the container and run alter command to remove all the unique constraint.
2. run the migration again in the same volume and done. the migration is completed.
