### ISSUE TITLE
suggestion: Add timestamp to archive items

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9555]
Since archived items could have the same name, it is helpful to have a timestamp column in the archive page in case the user wants to un-archive an item.
Also be able to sort by archival time.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by tlrobinson** [comment]
We could just replace the `archived` boolean field to be a nullable `archived_at` timestamp.

**Comment by luizarakaki** [comment]
It isn't possible to edit archived items. So this timestamp is the same as `updated_at`.
We now show this in the trash.
