### ISSUE TITLE
ssl https url not working

### ISSUE THREAD

**Issue by binodsarkar** [metabase/metabase#9560]
I am using ubuntu 18.04, I have set 
`export MB_JETTY_SSL=1`
`export MB_JETTY_SSL_Port=8343`
`export MB_JETTY_SSL_Keystore="your.jks"`
`export MB_JETTY_SSL_Keystore_Password="pass"`

After running metabase showing output as 
`{:port 3000, :ssl? true, :ssl-port 8343, :keystore "your.jks"}`

Now I am able to access http url but https not working.
Please help me

**Comment by flamber** [comment]
@binodsarkar 
Which version of Metabase?
When you say "not working", what does that mean?
Have you checked if firewall is blocking?
Check what services are listening on the ports: `sudo lsof -iTCP -sTCP:LISTEN -P`
Do you see any errors in the Metabase log or browser console?

PS - you should be using the forum for questions - issues are for bugs and feature requests.
https://discourse.metabase.com/

**Comment by binodsarkar** [comment]
Sorry It was certificate issue. However metabase was not showing the exact reason for it.

**Comment by weesley** [comment]
@binodsarkar  Do you remember what you did to identify the error in the certificate? I'm having the same problem
