### ISSUE TITLE
clojure.lang.ArityException: Wrong number of args (1) passed to: metabase.middleware.misc/wrap-gzip/fn--23274

### ISSUE THREAD

**Issue by GirishKotra** [metabase/metabase#9561]
- Browser and the version: Chrome 72.0.3626.121
- Operating System: Ubuntu 18.04.2 LTS
- Database: Postgres
- Metabase version: latest_master
- Metabase hosting environment: Ubuntu 18.04.2 LTS
- Metabase internal database: H2

i'm trying to run the server via leiningen task: lein ring server

INFO metabase.db :: Verifying h2 Database Connection ...
03-14 13:40:21 INFO metabase.driver :: Initializing driver :sql...
03-14 13:40:21 INFO metabase.driver :: Initializing driver :sql-jdbc...
03-14 13:40:21 INFO metabase.driver :: Initializing driver :h2...
03-14 13:40:21 INFO metabase.db :: Verify Database Connection ...  ✅
03-14 13:40:21 INFO metabase.db :: Running Database Migrations...
03-14 13:40:21 INFO metabase.db :: Setting up Liquibase...
03-14 13:40:21 INFO metabase.db :: Liquibase is ready.
03-14 13:40:21 INFO metabase.db :: Checking if Database has unrun migrations...
03-14 13:40:23 INFO metabase.db :: Database Migrations Current ...  ✅
03-14 13:40:23 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
03-14 13:40:23 INFO db.migrations :: Finished running data migrations.
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
03-14 13:40:23 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
03-14 13:40:24 INFO metabase.task :: Initializing task SyncDatabases 📆
03-14 13:40:24 INFO metabase.task :: Initializing task CheckForNewVersions 📆
03-14 13:40:24 INFO metabase.task :: Initializing task SendAnonymousUsageStats 📆
03-14 13:40:24 INFO metabase.task :: Initializing task SendAbandomentEmails 📆
03-14 13:40:24 INFO metabase.task :: Initializing task SendPulses 📆
03-14 13:40:24 INFO metabase.task :: Initializing task SendFollowUpEmails 📆
03-14 13:40:24 INFO metabase.task :: Initializing task TaskHistoryCleanup 📆
03-14 13:40:24 INFO metabase.core :: Metabase Initialization COMPLETE
Started server on port 3000
clojure.lang.ArityException: Wrong number of args (1) passed to: metabase.middleware.misc/wrap-gzip/fn--23274
                               AFn.java:429 clojure.lang.AFn.throwArity
                                AFn.java:32 clojure.lang.AFn.invoke
                               Var.java:384 clojure.lang.Var.invoke
                              reload.clj:39 ring.middleware.reload/wrap-reload[fn]
                          stacktrace.clj:26 ring.middleware.stacktrace/wrap-stacktrace-log[fn]
                          stacktrace.clj:96 ring.middleware.stacktrace/wrap-stacktrace-web[fn]
                               jetty.clj:26 ring.adapter.jetty/proxy-handler[fn]
                           (Unknown Source) ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle
                    HandlerWrapper.java:132 org.eclipse.jetty.server.handler.HandlerWrapper.handle
                            Server.java:502 org.eclipse.jetty.server.Server.handle
                       HttpChannel.java:370 org.eclipse.jetty.server.HttpChannel.handle
                    HttpConnection.java:267 org.eclipse.jetty.server.HttpConnection.onFillable
                AbstractConnection.java:305 org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded
                      FillInterest.java:103 org.eclipse.jetty.io.FillInterest.fillable
                   ChannelEndPoint.java:117 org.eclipse.jetty.io.ChannelEndPoint$2.run
                  QueuedThreadPool.java:765 org.eclipse.jetty.util.thread.QueuedThreadPool.runJob
                  QueuedThreadPool.java:683 org.eclipse.jetty.util.thread.QueuedThreadPool$2.run
                            Thread.java:748 java.lang.Thread.run

**Comment by rplevy** [comment]
I've also been running into this, and I've pinpointed the problem to commit 502a09c9 which begins to implement changes to switch to async web server.  On the commit immediately preceding it, ba25b11c9, I can run the server normally.
