### ISSUE TITLE
Field filter with relative date not passing data.

### ISSUE THREAD

**Issue by ascialoia** [metabase/metabase#9562]
Browser  Firefox 65.0.2
Operating System: Windows 10
Database: MariaDB 10
Metabase version: 0.30.2
Metabase hosting environment: Ubuntu 14
Metabase internal database: MySQL

Hi,
i need to get the value passed by a field filter type (image 3) like i do with other filter types (images 1-2). Because i need to pass it as a parameter to a function i've written.

Image 1:
![LIKE DATE](https://user-images.githubusercontent.com/48552549/54693772-7a596f00-4b27-11e9-9c99-c6d33ed3e755.PNG)

Image 2:
![LIKE TEXT](https://user-images.githubusercontent.com/48552549/54693773-7a596f00-4b27-11e9-86d8-09b2726c57bd.PNG)

Image 3:
![ERROR](https://user-images.githubusercontent.com/48552549/54693770-79c0d880-4b27-11e9-96e3-3fde316af080.PNG)

As discussing with @flamber down here, seems not to be a bug. Could it be then possible take in consideration the idea of implementing it? 

Have a nice day,
Thank You.
Alessandro.

**Comment by flamber** [comment]
Hi @ascialoia 
Your query is wrong for Field Filters.
```SQL
SELECT * FROM `table` WHERE {{date}}
```

**Comment by ascialoia** [comment]
Hi @flamber, thank you! 
I know, but wouldn't it be useful to query the data like i'm trying?

**Comment by flamber** [comment]
@ascialoia 
So you're asking for a query to return the actual filter value? I don't get it. Please explain what you're trying to do in more details.

**Comment by ascialoia** [comment]
@flamber 
Exactly, i would use what is returned from the filter to pass it to a function as a parameter. With the others filter types, for example text filter, i can do it.

**Comment by flamber** [comment]
@ascialoia 
I guess I don't understand the use-case with that query. If this is a feature request, then you should probably edit the first post to make that more clear.

**Comment by ascialoia** [comment]
@flamber 
The query is there just to point out that the value isn't passing. At this point, yes, it's a feature request. Will edit my post, thank you!

**Comment by flamber** [comment]
@ascialoia 
Okay, then update the query to show what you're trying to do. I'm pretty sure I'm not the only one misunderstanding your issue as the typical Field Filter bad input.

**Comment by flamber** [comment]
@ascialoia 
After seeing the edited post, then it looks like very related to #4509

**Comment by flamber** [comment]
Closing in favor of #4509
