### ISSUE TITLE
Proposal: change x-ray heuristic folder structure to a namespace-like one

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9565]
Currently heuristics are organized by type (metric, table, ...) and within that hierarchal for x-rays with "in-depth". If we expect to have a lot of heuristics, perhaps even vendor-specific ones, this is far from good, as it will be a mess to add new ones and there is a high chance of name clashes. 

I propose we move to a namespace-like structure with each toplevel package having the same internal structure (similar to how we organize our driver modules). 

## Current:
<img width="290" alt="Screenshot 2019-03-14 19 45 26" src="https://user-images.githubusercontent.com/178038/54383566-a0e45980-4692-11e9-9bbd-a3a315315082.png">

## Proposed
<img width="262" alt="Screenshot 2019-03-14 19 58 58" src="https://user-images.githubusercontent.com/178038/54384026-a2625180-4693-11e9-863d-b826c47b97eb.png">

**Comment by salsakran** [comment]
seems reasonable to me in theory.

I think the trick is also having some sort of heirachy in the type system and making sure we don't have too many disparate tree structures floating around doing the same thing.

**Comment by sbelak** [comment]
The problem is our type system is global and not really extendable. What I'm leaning towards more and more is that you could define your own types & corresponding classifiers as part of the heuristics package. This does open the question whether we'll be using the richer type info in other facets of MB, but at least currently we don't (while at the same time we're paying the added complexity price).

If you look at `table` section in #9564, it's basically the same thing as what the classifier in sync does. Perhaps this should not be per-heuristic, but rather per heuristic package and would introduce both semantic field types and entity types. Aside from being conceptually cleaner, it also reduces duplication. 

If we go down this path, should the FE (data model) be aware of these types or do we in general revert to a simpler type hierarchy and have only xrays be aware of the richer (& extendable) one?

**Comment by camsaul** [comment]
Wait
What do you mean by saying it's not extendable? We already have a few places where we extend it, for example Postgres adds the `:type/PostgresUUID` type to implement UUID support but since it derives from `:type/Text` as far as everybody else is concerned they can just treat it as text

**Comment by sbelak** [comment]
Extendable in the sense of sanely handling name/concept clashes and potentially allowing things such as vendor (or even user-) extensions (Segment/Stripe/Whoever).
