### ISSUE TITLE
Metabase hung itself up somehow - Would it help if you got the logs from my server?

### ISSUE THREAD

**Issue by philippmayrth** [metabase/metabase#9569]
The system hung itself up after a couple of days of low usage. A restart of the docker container helped.

**My question:** Would it help If I provided you with some server logs, wich would you need and how do I send them to you?

Some more details:

- Your browser and the version: iOS on iPad and iPhone, macOS, Windows 7 and 10 default browsers.
- Your operating system: On the server: Ubuntu 18.04 LTS 64bit
- Your databases: MariaDB, MongoDb
- Metabase version: 0.31.2
- Metabase hosting environment: Docker (official docker image)
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*

- Install the system
- Use the system, or dont just wait a few days or weeks
- Go to the website to access metabase
- It will load for an eternity once it finally is loaded it will display some Apache Proxy error message notifying that the actual application did not respond.

Might help: I have a RPi refreshing a dashboard every 15 minutes 24/7.

_Reference in my ticket system: SER-9_

**Comment by flamber** [comment]
Hi @philippmayrth 

There's multiple things that could be the culprit. Running out of RAM, problems with Docker, or other system services - and of course, Metabase itself could have crashed.
You need to check all relevant logs - Metabase, Docker, ..., and the host itself.
You can attach log files here.

And you should really migrate to another database than H2 for production use:
https://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres

**Comment by philippmayrth** [comment]
Hi @flamber 

**To clarify what I meant:** I did get it working again. Would it be useful to you to have logs so you could improve the software?

It had to be somewhere in Metabase because I checked the server before it was fine so all I actually did was to restart that single docker container for metabase. The server also only runs two database servers and thats it so there is not much that can go wrong aside from metabase in the first place.

**Comment by flamber** [comment]
@philippmayrth 
You can attach the logs here - without the logs, there's nothing to see.

**Comment by philippmayrth** [comment]
Is there a directory containing the relevant logs? The UI (Admin -> Troubleshooting) takes way to long for me to get to the day where the problem happened.

**Comment by flamber** [comment]
@philippmayrth 
I think the logs in Docker are located in `/var/log/metabase.log` - but logs are rotated, so the crash might not be in the log anymore.

**Comment by philippmayrth** [comment]
@flamber sorry for responding a bit late. Nope, that directory is completely empty. However metabase has hung up a bunch of more times so there should be something in the logs.
Its not a problem for me now anymore because Im now just restarting the container with cron every midnight.

**Comment by flamber** [comment]
@philippmayrth 
Okay, it would be really great if you could get the logs before restarting the container next time it hangs.
Also, have you tried the new 0.32? It has a lot of backend changes and uses less memory.
Always backup before upgrading.

**Comment by salsakran** [comment]
closing as there isn't anything actionable.

@philippmayrth - we've made significant changes in 0.32 that should reduce the chances of this happening.
We've found that if you have a large number of slow queries that can tie up threadpools and result in a load balancer deciding the instance is down. 

if you see this behavior again, please chime in

**Comment by philippmayrth** [comment]
@salsakran you were right, 0.32.4 hash:da7c506e (the docker container version) did prevent this happening. It did not work to begin with it just hung and threw a bunch of nonsense error messages. I had to rollback the update. Thought you might be interested in this info.
