### ISSUE TITLE
How to add a filter field to the metabase dashboard？

### ISSUE THREAD

**Issue by AggiWang** [metabase/metabase#9570]
![Uploading image.png…]()
v0.31.2 
How to add a filter field to the metabase dashboard？

**Comment by flamber** [comment]
Hi @AggiWang 

Did you create it in the SQL question?
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#the-field-filter-variable-type
If it's not even working there, then it's a problem with your Field Type in Data Model.
Settings > Admin > Data Model > (database) > (table) > (column) :gear:

Do you see any errors? Check Metabase log and browser console.

Use the forum for questions - and maybe provide more details - and use screenshots, when it helps.
https://discourse.metabase.com/

**Comment by salsakran** [comment]
closing since this isn't the appropriate forum, as @flamber mentioned.
