### ISSUE TITLE
0.32.0 RC upgrade failed - Corrupted jar file from docker

### ISSUE THREAD

**Issue by doodlebro** [metabase/metabase#9575]
Tried upgrading to the latest in my test-env, but it won't start up. Running on a K8S cluster, connecting to a redshift database.

Only log I have from the K8S pod is:

`Error: Invalid or corrupt jarfile /app/metabase.jar`

**Comment by tlrobinson** [comment]
@doodlebro Oops, we noticed that was broken and forgot to unpublish it.

We will likely push out another RC later today. We also identified a blocking bug.

**Comment by tlrobinson** [comment]
@doodlebro FYI we published a new RC, `metabase/metabase:v0.32.0-RC1`. Thanks.
