### ISSUE TITLE
Border is missing from the end of the Calendar in Date Filter "Between"

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9576]
Your browser and the version: Firefox 65
Your operating system: Windows 10
Your databases: H2
Metabase version: 0.31.2
Metabase hosting environment: Local, Windows 10
Metabase internal database: H2
Steps to reproduce the issue: create a question on a table that has date column -> filter it using that column -> choose "Between"
![border](https://user-images.githubusercontent.com/15974735/54556155-7ede2600-4975-11e9-877f-ee65a9f0048c.png)

**Comment by mazameli** [comment]
The latest version of Metabase has an updated version of the `Between` filter widget, which fixed this issue as a side effect.

![image](https://user-images.githubusercontent.com/2223916/66604831-bad01700-eb63-11e9-938f-d16563a2d535.png)
