### ISSUE TITLE
Allow trailing comments in postgres queries

### ISSUE THREAD

**Issue by ConradIrwin** [metabase/metabase#9580]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: Chrome 73
- Your operating system: macOS 10.14.3
- Your databases: Postgres
- Metabase version: 0.31.2
- Metabase hosting environment: Kubernetes
- Metabase internal database: Postgres

- *Repeatable steps to reproduce the issue*

* Create a postgres data-source
* Click "Ask a question" -> "Native query"
* Type:
```
select 1;
-- test
```
* Hit "Get Answer"
* See error: "org.postgresql.util.PSQLException: Multiple ResultSets were returned by the query."

Interestingly, typing
```
-- test
select 1;
```
works fine.

This mostly happens to me when I'm trying to construct complicated queries in the UI and I want to temporarily comment out parts of them.

**Comment by flamber** [comment]
@ConradIrwin Looks like a duplicate of #2653

**Comment by ConradIrwin** [comment]
Agreed — I ddin't find that in my search, sorry!
