### ISSUE TITLE
Track Usage of Public Dashboard Usage (Number of Views)

### ISSUE THREAD

**Issue by orware** [metabase/metabase#9583]
This may be related to #7320 but I was writing some basic questions against the `view_logs` table which has stats for authenticated access to Questions/Dashboards it seems, but I'm not seeing any tables that track the usage of Public Dashboards in the system so that would be a request I'd like to make since that data could be useful for an organization making use of Public Dashboards on their website and wanting to get an idea for how often they may be getting viewed by the Public.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by orware** [comment]
Here are some sample queries others can take advantage of for getting some of the Questions/Dashboards stats for authenticated users out of the Metabase database currently (I have Metabase installed on a MySQL database currently):

```sql
-- Most Popular Metabase Dashboards
SELECT vl.model_id, cu.email creator_email, cu.first_name creator_first_name, cu.last_name creator_last_name, rd.name, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/dashboard/', vl.model_id) dashboard_url
FROM view_log vl
INNER JOIN
	report_dashboard rd
ON
	vl.model_id = rd.id
INNER JOIN
	core_user cu
ON
	rd.creator_id = cu.id
WHERE vl.model = 'dashboard'
GROUP BY vl.model_id
ORDER BY number_of_views DESC
```

```sql
-- Most Popular Metabase Dashboards Group By Year/Month
SELECT YEAR(vl.timestamp) view_year, CONCAT(MONTH(vl.timestamp), ' - ', MONTHNAME(vl.timestamp)) view_month, vl.model_id, cu.email creator_email, cu.first_name creator_first_name, cu.last_name creator_last_name, rd.name, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/dashboard/', vl.model_id) dashboard_url
FROM view_log vl
INNER JOIN
	report_dashboard rd
ON
	vl.model_id = rd.id
INNER JOIN
	core_user cu
ON
	rd.creator_id = cu.id
WHERE vl.model = 'dashboard'
GROUP BY YEAR(vl.timestamp), MONTH(vl.timestamp), vl.model_id
ORDER BY view_year DESC, MONTH(vl.timestamp) DESC, number_of_views DESC
```

```sql
-- Most Popular Metabase Questions
SELECT vl.model_id, cu.email creator_email, cu.first_name creator_first_name, cu.last_name creator_last_name, md.name database_name, rc.name question_name, rc.display question_display_type, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/question/', vl.model_id) question_url, rc.description question_description
FROM view_log vl
INNER JOIN
	report_card rc
ON
	vl.model_id = rc.id
INNER JOIN
	core_user cu
ON
	rc.creator_id = cu.id
INNER JOIN
	metabase_database md
ON
	rc.database_id = md.id
WHERE vl.model = 'card'
GROUP BY vl.model_id
ORDER BY number_of_views DESC
```
```sql
-- Most Popular Metabase Questions Grouped By Year/Month
SELECT YEAR(vl.timestamp) view_year, CONCAT(MONTH(vl.timestamp), ' - ', MONTHNAME(vl.timestamp)) view_month, vl.model_id, cu.email creator_email, cu.first_name creator_first_name, cu.last_name creator_last_name, rd.name, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/dashboard/', vl.model_id) dashboard_url
FROM view_log vl
INNER JOIN
	report_dashboard rd
ON
	vl.model_id = rd.id
INNER JOIN
	core_user cu
ON
	rd.creator_id = cu.id
WHERE vl.model = 'dashboard'
GROUP BY YEAR(vl.timestamp), MONTH(vl.timestamp), vl.model_id
ORDER BY view_year DESC, MONTH(vl.timestamp) DESC, number_of_views DESC
```

```sql
-- Top Dashboard Viewers:
SELECT vl.model_id, cu.email viewer_email, cu.first_name viewer_first_name, cu.last_name viewer_last_name, rd.name, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/dashboard/', vl.model_id) dashboard_url
FROM view_log vl
INNER JOIN
	report_dashboard rd
ON
	vl.model_id = rd.id
INNER JOIN
	core_user cu
ON
	vl.user_id = cu.id
WHERE vl.model = 'dashboard'
GROUP BY vl.user_id, vl.model_id
ORDER BY number_of_views DESC
```

```sql
-- Top Question Viewers
SELECT vl.model_id, cu.email viewer_email, cu.first_name viewer_first_name, cu.last_name viewer_last_name, md.name database_name, rc.name question_name, rc.display question_display_type, COUNT(vl.id) number_of_views, CONCAT('https://your-metabase-url.com/question/', vl.model_id) question_url, rc.description question_description
FROM view_log vl
INNER JOIN
	report_card rc
ON
	vl.model_id = rc.id
INNER JOIN
	core_user cu
ON
	vl.user_id = cu.id
INNER JOIN
	metabase_database md
ON
	rc.database_id = md.id
WHERE vl.model = 'card'
GROUP BY vl.user_id, vl.model_id
ORDER BY number_of_views DESC
```

**Comment by vvaezian** [comment]
As a feature request, is it feasible to store the IP address of the system who is running Metabase (e.g. add a column for IP in the table `query_execution`)? If privacy is an issue, the IP addresses can be hashed before storage in the database. This way we can see how many users we have for public dashboards and others.

**Comment by strikanov** [comment]
@orware where am I can run these snippets? in which base? I got an error "ERROR: relation "report_dashboard" does not exist" in queries to all of my databases. And I have already investigated all of the potential places where it might be run. Tell, please, more details 🙏🙏🙏

<img width="373" alt="image" src="https://user-images.githubusercontent.com/25309509/190402524-75316152-1665-4fe5-bded-040358f613d7.png">

**Comment by flamber** [comment]
@strikanov In the Metabase application database: https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by strikanov** [comment]
Is there row data of SQL snippets used in "Questions"? Could I search by all existing SQL snippets like in the repository?

**Comment by flamber** [comment]
@strikanov There's Audit functionality in the Pro/Enterprise plans: https://www.metabase.com/docs/latest/usage-and-performance-tools/audit
Otherwise you can make your own queries, have a look at: https://discourse.metabase.com/t/metabase-metadata-sql/3688
Use the forum.

**Comment by albertoperdomo** [comment]
We shipped a [usage analytics](https://www.metabase.com/docs/latest/usage-and-performance-tools/usage-analytics) in [Metabase 48](https://www.metabase.com/releases/metabase-48). This includes the capability to track anonymous views.

Anonymous views can be attributed to public links or static embeds, as neither functionality relies on Metabase user sessions. Hence, interpreting the data depends on the context.
