### ISSUE TITLE
Metabase 0.32.0 - RC1 BigQuery Bug

### ISSUE THREAD

**Issue by anandabudi** [metabase/metabase#9586]
Hi guys, 

I just tried the Metabase 0.32.0 - RC1 in my development server. Looks like there's another problem with BigQuery dataset.

This is the error

![Screen Shot 2019-03-20 at 10 15 00](https://user-images.githubusercontent.com/8414151/54656792-a52cce80-4af9-11e9-8cb8-d98409e3aba9.png)

And this is the error log
`
03-20 03:22:19 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.IllegalArgumentException,
 :error "No method in multimethod 'execute-query' for dispatch value: :bigquery",
 :stacktrace
 ("clojure.lang.MultiFn.getFn(MultiFn.java:156)"
  "clojure.lang.MultiFn.invoke(MultiFn.java:233)"
  "--> query_processor$fn__39129$execute_query__39134$fn__39135.invoke(query_processor.clj:67)"
  "query_processor$fn__39129$execute_query__39134.invoke(query_processor.clj:61)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33085.invoke(mbql_to_native.clj:36)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__31806.invoke(annotate.clj:368)"
  "query_processor.middleware.annotate$add_column_info$fn__31711.invoke(annotate.clj:303)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__32548.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.limit$limit$fn__33041.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__38996.invoke(results_metadata.clj:86)"
  "query_processor.middleware.format_rows$format_rows$fn__33029.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__19674.invoke(add_dimension_projections.clj:236)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31257.invoke(add_row_count_and_status.clj:15)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__32790.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__35966.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31986$fn__31987.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31986.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__39021$fn__39022.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
  "query_processor.store$do_with_new_store.invoke(store.clj:31)"
  "query_processor.middleware.store$initialize_store$fn__39021.invoke(store.clj:10)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__32408.invoke(cache.clj:127)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__32456.invoke(catch_exceptions.clj:63)"
  "query_processor$process_query.invokeStatic(query_processor.clj:232)"
  "query_processor$process_query.invoke(query_processor.clj:228)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:341)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:335)"
  "query_processor$fn__39209$process_query_and_save_execution_BANG___39214$fn__39215.invoke(query_processor.clj:371)"
  "query_processor$fn__39209$process_query_and_save_execution_BANG___39214.invoke(query_processor.clj:357)"
  "query_processor$fn__39235$process_query_and_save_with_max_BANG___39240$fn__39241.invoke(query_processor.clj:403)"
  "query_processor$fn__39235$process_query_and_save_with_max_BANG___39240.invoke(query_processor.clj:398)"
  "async.semaphore_channel$do_f_with_permit$f__46399.invoke(semaphore_channel.clj:81)"
  "async.util$do_on_separate_thread$fn__46234.invoke(util.clj:53)"),
`
I'm afraid that this problem is not going to be solved in the final version of this release candidate

Thanks !

**Comment by TimJuni** [comment]
We are experiencing the same issue. All queries with the query builder ("Ask a Question") seem to work but all SQL based questions are showing the 'execute-query' error.

**Comment by camsaul** [comment]
Hi @anandabudi @TimJuni, this is fixed in RC2. Please give it a try

**Comment by anandabudi** [comment]
Thanks @camsaul !
