### ISSUE TITLE
[API] Add card to dashboard with size/position data

### ISSUE THREAD

**Issue by RomainWilbert** [metabase/metabase#9588]
Is there a way with the REST API to add a card to a dashboard specifying card size and position?

I tried the following which did not work:
POST http://metabase/api/dashboard/[dashboard_id]/cards
{"cardId":[card_id],"dashboard-card":{"card_id":[card_id],"sizeX":4,"sizeY":3,"col":8,"row":0}}

**Comment by sbelak** [comment]
`PUT /api/dashboard/:id/cards` should do the trick https://github.com/metabase/metabase/blob/master/docs/api-documentation.md

**Comment by RomainWilbert** [comment]
I managed to do it in one step with the following:
```
POST http://metabase/api/dashboard/[dashboard_id]/cards
{"cardId":[card_id],"sizeX":4,"sizeY":3,"col":8,"row":0}
```
