### ISSUE TITLE
Passing username or user email as parameter in query or ask question

### ISSUE THREAD

**Issue by ktwiz** [metabase/metabase#9594]
Hi !

I'm new to metabase. I would like to install metabase to my company as BI platform. But I got a problem, can I pass user or username email as parameter to query or ask question GUI ? Please tell me how to do that. I solve a lot problem to me when building dashboard !

Thanks so much !

**Comment by flamber** [comment]
Hi @ktwiz 
I'm not sure what you're trying to do. It sounds like you're looking for Embedding, but you need to describe a bit more. Or maybe you just want to use filters on dashboards.
Please use the forum for questions: https://discourse.metabase.com/
