### ISSUE TITLE
spelling mistake on the search result site in german translation

### ISSUE THREAD

**Issue by Jaeggrono** [metabase/metabase#9596]
- Your browser and the version: (Firefox 67Beta)
- Your operating system: (Windows 10 Education)
- Your databases: (MySQL)
- Metabase version: ( v0.31.2)
- Metabase hosting environment: (XAMPP)
- Metabase internal database: (H2)

There is a spelling mistake on the search result site in german translation:
![mistake](https://user-images.githubusercontent.com/38099002/54740561-0c12bc00-4bbc-11e9-9fdb-81ce51b55adc.jpg)
The headline says "Impuse" but I think it should say "Impulse".

**Comment by salsakran** [comment]
thanks for pointing this out.

You can fix this by chiming in on https://poeditor.com/join/project/ynjQmwSsGh

Since none of us are native german speakers, we rely on the community translations. 

Closing this since it should be taken care of on poeditor
