### ISSUE TITLE
I can’t use the “date” filter on the dashboard 

### ISSUE THREAD

**Issue by rodrigoestulano** [metabase/metabase#9597]
I'm having a problem using date filter inside the dashboard.
Within the question, the date variable (date type) works normally, however within the dashboard that I added this question, the date filter does not work.
My field is a timestamp in this format "Thursday, March 21, 2019 11:38 AM".
When I add the date filter to the dashboard, the question is not compatible, so I can not select the "date" column.
What can I do to be able to filter date on my dashboard?
Ps: In the data model, this column is already set to "Date and Time".

**Comment by flamber** [comment]
@rodrigoestulano 
Only post in one place. And for questions, use the forum:
https://discourse.metabase.com/t/i-cant-use-the-date-filter-on-the-dashboard/5723
