### ISSUE TITLE
Metabase 0.32.0 RC1 - Can't add druid database

### ISSUE THREAD

**Issue by gerbal** [metabase/metabase#9601]
When attempting to add a druid database with 0.32RC1 I get the following error

```
java.lang.IllegalArgumentException: No method in multimethod 'can-connect?' for dispatch value: :druid
```

![Screenshot_2019-03-21 Databases · Admin · Metabase](https://user-images.githubusercontent.com/5278092/54783809-c0323800-4bf8-11e9-8231-7697ebe9aa0f.png)

Logs from the Metabase process: 

```
03-21 20:43:04 DEBUG middleware.log :: POST /api/database 400 (1 ms) (0 DB calls).
{:valid false,
 :dbname "java.lang.IllegalArgumentException: No method in multimethod 'can-connect?' for dispatch value: :druid",
 :message "java.lang.IllegalArgumentException: No method in multimethod 'can-connect?' for dispatch value: :druid"}
```

This database was accessible from 0.31

**Comment by camsaul** [comment]
Hi, this is a known issue, we had a problem with our build. We're shipping a new RC release later today.
