### ISSUE TITLE
Accessing the chosen option in Field Filter

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9602]
Your browser and the version: Firefox 65
Your operating system: Windows 10
Your databases: PostgreSQL
Metabase version: 0.31.2
Metabase hosting environment: Local, Windows 10
Metabase internal database: H2

I can access value of the text entered by user when variable type is set to TEXT:

![1](https://user-images.githubusercontent.com/15974735/54785195-d503d100-4be2-11e9-80be-acd32a8f560d.png)

But when I use a field filter the return value is empty string:

![2](https://user-images.githubusercontent.com/15974735/54785202-db924880-4be2-11e9-94e4-9eb69c717966.png)

How can I access the option chosen by the user in a Field Filter widget?

**Comment by flamber** [comment]
Hi @vvaezian 
Can you explain the use-case for this?
The query `select {{test}} from x limit 5`, when using Field Filter, gets converted to
```
select table.column in ("Yearly") from x limit 5
```

**Comment by vvaezian** [comment]
Hi @flamber. The use case is in CASE statements:
````SQL
SELECT CASE WHEN {{t_interval}} = 'Yearly' THEN ...
            WHEN {{t_interval}} = 'Monthly' THEN ...
            ...
       END
...
````
Based on what the chosen option is, I like to make the column be shown differently. Is there a workaround to be able to check the value of the chosen option ( e.g. `{{t_interval}} = 'Yearly'`)? This works OK with Text variables as I mentioned above. The problem is with Field Filter variables.

**Comment by flamber** [comment]
@vvaezian 
You're probably looking for #5245 or #6820
Workaround would be if the Field Filter's data comes from a table (`lookup`) that looks like this:
```
colname
-------
'Yearly'
'Monthly'
'Weekly'
'Daily'
```
Then you could do something like this:
```SQL
SELECT CASE
  WHEN (SELECT colname FROM lookup WHERE {{t_interval}}) = 'Yearly' THEN ...
  WHEN (SELECT colname FROM lookup WHERE {{t_interval}}) = 'Monthly' THEN ...
  ...
END
...
```

**Comment by vvaezian** [comment]
Great. Thanks.

**Comment by flamber** [comment]
@vvaezian If one of the issues I referenced in previous comment, looks to be similar to your request, then please close this issue and remember to upvote :+1:
