### ISSUE TITLE
jetty ssl secured issue

### ISSUE THREAD

**Issue by sumiodz** [metabase/metabase#9606]
i am using metabase compilation with lets-encrypt ssl and ngnix with jetty ssl and ssl is installed but ssl is not secure check attached screenshot 

I am having only warning no error
03-22 12:26:46 WARN SslContextFactory.config :: No Client EndPointIdentificationAlgorithm configured for SslContextFactory@9a4bb97[provider=null,keyStore=file:///var/www/html/metabase/sfdcsec.ks,trustStore=file:///var/www/html/metabase/sfdcsec.ks]

could you please help its very urgent for me .Reply asap
![Screenshot from 2019-03-22 18-00-42](https://user-images.githubusercontent.com/25523464/54823037-95b1af00-4ccc-11e9-972f-5ec4de2f3651.png)

**Comment by flamber** [comment]
Hi @sumiodz 
Questions should be asked in the forum: https://discourse.metabase.com/
If you're using Let's Encrypt on Nginx, which acts as a reverse proxy to Metabase (Jetty), then you don't need to add any SSL stuff to Jetty.
Just let Nginx do a `proxy_pass` to the non-SSL port of Jetty and let Nginx handle SSL with the end-user.

**Comment by sumiodz** [comment]
but when i will not use it work on 3000 port without ssl

**Comment by camsaul** [comment]
@sumiodz as @flamber has mentioned, these sorts of questions belong in https://discourse.metabase.com/. If you want to configure Metabase to use SSL please refer to our documentation: https://metabase.com/docs/latest/operations-guide/start.html

**Comment by sumiodz** [comment]
i already follow this quide but problem its working on ssl but connection is not secure

**Comment by camsaul** [comment]
It's working over SSL but not secure?
