### ISSUE TITLE
Conditional Formatting - Numbers [Feature Request] 

### ISSUE THREAD

**Issue by BenjaminGK** [metabase/metabase#9610]
Would it be possible to add conditional formatting for the numbers visualization?
We see many use cases for dashboards where we would wanna highlight if a number goes above a certain threshold - Ideal to also have same settings to also have a switch between negative/positive as for "Smart Numbers"

**Metabase - currently**
![image](https://user-images.githubusercontent.com/23311430/54914449-9003d580-4f27-11e9-9344-22c8feff8af4.png)

**Suggeted solution**
![image](https://user-images.githubusercontent.com/23311430/54914292-38fe0080-4f27-11e9-99b1-0168b96db255.png)

**Comment by flamber** [comment]
Hi @BenjaminGK 
This sounds very similar to #3168 - if you agree, then close this and upvote by clicking the :+1:
