### ISSUE TITLE
How to uninstall/remove Metabase on Windows?

### ISSUE THREAD

**Issue by ahdung** [metabase/metabase#9613]
Just delete metabase.jar not enough right? where are the config data?

**Comment by flamber** [comment]
Correct, the application is `metabase.jar` - so delete that.
And depending on how you configured Metabase, by default it stores the data to a H2 database-file called `metabase.db.h2.db` or `metabase.db.mv.db`, which should be located in the same directory as `metabase.jar`, but again that depends on how you configured Metabase (meaning the environment variables or the parameters used to launch `java -jar metabase.jar ...`)

**Comment by ahdung** [comment]
@flamber First thank you. I found following files:
```
C:\Users\Administrator\metabase.db.mv.db
C:\Users\Administrator\metabase.db.trace.db
```
So, delete them all, and all right?

**Comment by flamber** [comment]
@ahdung 
Yep, delete them and everything is gone :-)
Please remember to close this issue, if you feel you got all the answers.

**Comment by ahdung** [comment]
@flamber Thank you again (*^▽^*)
