### ISSUE TITLE
Fullscreen mode causes changes to font sizes which skews intended layout

### ISSUE THREAD

**Issue by johnlim** [metabase/metabase#9615]
I have a layout which looks great but when put into fullscreen mode, the text either gets hidden or if in a text card suddenly becomes too big. For example
<img width="527" alt="great" src="https://user-images.githubusercontent.com/2478187/55062569-2fa09f80-50b1-11e9-848a-9a5d6bdd2cf7.png">
<img width="519" alt="notsogreat" src="https://user-images.githubusercontent.com/2478187/55062576-35968080-50b1-11e9-988e-1edf4e1e420d.png">
<img width="875" alt="expected" src="https://user-images.githubusercontent.com/2478187/55062603-47782380-50b1-11e9-9d35-fc08106d25b1.png">
<img width="857" alt="distorted" src="https://user-images.githubusercontent.com/2478187/55062609-4a731400-50b1-11e9-804d-0b3be37701c1.png">

It seems like this is a feature though? If so, is there anyway to get night mode without having to go fullscreen? Thanks.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by uladzimirdev** [comment]
After initial investigation we found:
font-size is increased for full screen mode:
- min-width: 1280px - 1.2em
- min-width: 1540px - 1.4em

and it makes text cards look weird (actually having a scrollbar on the right). 

Proposed solution is to get rid of increased font either overall or for text cards, but it's still under discussion
