### ISSUE TITLE
Filter button option (is, contains, equal to..) hidden by a "Data" name too long

### ISSUE THREAD

**Issue by romainlaisne** [metabase/metabase#9616]
The filter button in the "Filtered by" UI does not appear if the "Data" name is too long :
![image](https://user-images.githubusercontent.com/7721517/55065430-1af5e480-507c-11e9-89cc-24860a7ad210.png)

## Possible CSS adjustements
I have tested out some CSS adjustments which seem to work :
```
.AdminSelect {
    background-color: #FFF;
}

FilterPopover div {
    max-width: none;
}

h3.ml1 {
    max-width: 150px;
    overflow: hidden;
}
```

## Environment

- Chrome 72.0
- Mac OS 10
- Metabase version: 0.30.3
- Metabase hosting environment: (Docker)

## Related issues
https://github.com/metabase/metabase/issues/6011 Not exactly the same though

**Comment by flamber** [comment]
Hi @romainlaisne 
I cannot reproduce your issue on 0.31.2 with Firefox 66 and Chromium 72.
![image](https://user-images.githubusercontent.com/1447303/55087759-35c25c00-5070-11e9-8e7d-3dc8e4c01553.png)

**Comment by exabrial** [comment]
possibly this? https://github.com/metabase/metabase/issues/9161

**Comment by flamber** [comment]
@exabrial 
Don't think they're related, since this is about the missing filter type (select-box), whereas #9161 is options within grouped by overflowing the sub-selector of date/binned types.
