### ISSUE TITLE
metabase embed please help

### ISSUE THREAD

**Issue by stemearsy76** [metabase/metabase#9617]
Hi i have a HTML web page and want to embed metabase into the index.html page but im totally lost with the part below
**Insert this code snippet in your server code to generate the signed embedding URL**

Where do i need to put this bit of code so i can use the iframe for the html?

**Comment by flamber** [comment]
Hi @stemearsy76 
Questions and troubleshooting belong in the forum: https://discourse.metabase.com/
It sounds like you should be using "Public embed", which is just the "Public link" in an iframe.
Embedding is used to integrate Metabase into other applications.

**Comment by camsaul** [comment]
@flamber thanks for the great answer. I'll second that. Please direct such questions to our Discourse page
