### ISSUE TITLE
Certain Queries stopped working

### ISSUE THREAD

**Issue by erayozer17** [metabase/metabase#9618]
We realised 9 days ago, some of our metabase queries stopped working properly.
The Response on the web-console shows us the response with all the correct information about that certain queries. But on the frontend it doesn't show us anything but the nav-bar. On the console we are having these messages:
```
Uncaught (in promise) TypeError: Cannot read property 'fields' of undefined
    at t.value (app-main.bundle.js?78262faa1c529a733077:5)
    at t.value (app-main.bundle.js?78262faa1c529a733077:5)
    at u._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js?78262faa1c529a733077:145)
    at u._renderValidatedComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at u.performInitialMount (vendor.bundle.js?78262faa1c529a733077:145)
    at u.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
    at Object.mountComponent (vendor.bundle.js?78262faa1c529a733077:83)
    at J.mountChildren (vendor.bundle.js?78262faa1c529a733077:145)
    at J._createInitialChildren (vendor.bundle.js?78262faa1c529a733077:145)
    at J.mountComponent (vendor.bundle.js?78262faa1c529a733077:145)
```

**Comment by flamber** [comment]
Hi @erayozer17 
Which version of Metabase? Which database are you connecting to?
Do you see any errors in the Metabase logs?
You say "certain queries" - is it only specific types of questions, like Custom or Native or Saved/Nested Questions? Could it be a permission issue?

**Comment by erayozer17** [comment]
Hello @flamber , thanks for reply. We use v0.31.2 and PostgreSql. We checked the logs and there is nothing unusual. All responses are 200. It can't be a permission issue because we are able to see other questions in the same category. There is no common pattern between failing questions. They are exactly the same with the working ones.

**Comment by salsakran** [comment]
@erayozer17 can you share the response coming back from Metabase for that query?

**Comment by erayozer17** [comment]
Thanks for reply @salsakran . The reason was miscommunication between us. Someone archived the card we use for those questions, therefore we were receiving a blank screen. So we cant call it an issue anymore but a warning message instead of a blank screen would be nice.

**Comment by mazameli** [comment]
Hmm so maybe this should be relabeld as a UX issue rather than a bug. @erayozer17 do you mean that the archived question was one whose results were used as the starting data for the other questions that weren't working? (A "nested query.")

As we enable more building block features like nested queries, we're going to need to think through the UX of communicating interdependencies and the consequences of archiving/moving/altering questions or results that other questions depend on.

**Comment by flamber** [comment]
I cannot reproduce this on 0.35.4.
Now the dashboard card just says `There was a problem displaying this chart.` and looking in the log, there's a stacktrace with the error `Card :id does not exist.` - #5222 covers archiving in general.
Related to #9299
