### ISSUE TITLE
Failed queries do not show SQL that was executed

### ISSUE THREAD

**Issue by on99** [metabase/metabase#9623]
### Feature requests and proposals
log every sql executed

I cannot see the sql being executed when it takes too long in question query builder. The sql being executed is the key to debug.

- Your browser and the version: Chrome
- Your operating system: OS X 
- Your databases: MySQL
- Metabase version: 0.32.0
- Metabase hosting environment: docker
- Metabase internal database: MySQL

**Comment by flamber** [comment]
Sounds like a duplicate of #6096
Have you checked the internal database tables `query` and `query_execution` ?
Or enabled `slow log` on MySQL?

**Comment by on99** [comment]
@flamber  It's a bit different from #6096. I just take `slow query` as an example, seems like the sql is also not logged if it failed to execute.

**Comment by camsaul** [comment]
Duplicate of #6096

**Comment by flamber** [comment]
I cannot reproduce on 0.41.2 - it logs failed queries too in `query`, which can be found by using `query_execution.hash`
