### ISSUE TITLE
Is it possible to add a hyperlink to a visualisation?

### ISSUE THREAD

**Issue by Nikos410** [metabase/metabase#9633]
Hey there!

I was wondering if it was possible to add hyperlinks to dashboards. In our case, we have a visualisation, that shows how many $things need attention because $field_A is not properly filled, and how many $things need attention because $field_B is not properly filled.

If a user sees this, they want to click on the number to see which individual 12 $things are that. Maybe that could link to another visualisation that just has the result shown as a table instead of showing the count as a number? 

But it would be even better to be able to configure a hyperlink to external sites as well, so we can go from the metabase dashboard to the details page inside another application, if we click on an entry. For example, we show a list of $things as a table, and want to configure that we want to go to `http://internal.tool.de/details?id={{$thing_id}}` if we click on a row.

Is something like that possible at the moment? If not, would you want to have something like that in Metabase?

**Comment by flamber** [comment]
Hi @Nikos410 
Use the forum for questions and troubleshooting: https://discourse.metabase.com/
You write links in text boxes - or use SQL to create a table row with URL with parameters.
There's a few requests for something similar, but I think this issue is related to (maybe duplicate of) #8461

**Comment by Nikos410** [comment]
Thanks! I looked around before opening this issue but did not find that one. Left a +1 there and closing this one.
