### ISSUE TITLE
Allow sql generation for incomplete queries

### ISSUE THREAD

**Issue by kyleabeauchamp** [metabase/metabase#9643]
Chrome 73.0
OSX 10.14
postgres 11.2
Metabase 32.0
Metabase docker
Metabase internal database H2

Currently, when a user asks a question using the custom builder, the raw SQL version of the query is only available upon query completion.  However, to me it might make sense to allow exporting the query to raw SQL even before execution.  This would allow users to edit the query before execution.

**Comment by flamber** [comment]
Hi @kyleabeauchamp This sounds like a duplicate of #6198

**Comment by kyleabeauchamp** [comment]
Yep, I didn't see that one.
