### ISSUE TITLE
Metabase website down?

### ISSUE THREAD

**Issue by shrike71** [metabase/metabase#9644]
Apologies if this is not the right forum for it, lads, but the main Metabase.com website is down?

**Comment by kenaniah** [comment]
@shrike71 the website (https://metabase.com/) currently does not appear to be down. Could you please confirm and close this issue, or provide more info (such as where you're accessing from, what type of error you get, etc.)?

**Comment by flamber** [comment]
@camsaul @salsakran 
www.metabase.com doesn't respond, only metabase.com works - worked fine before I went to bed.
```
# dig www.metabase.com A
www.metabase.com.	5	IN	A	52.218.208.147

# wget -v -O /dev/null https://www.metabase.com
Resolving www.metabase.com (www.metabase.com)... 52.218.217.98
Connecting to www.metabase.com (www.metabase.com)|52.218.217.98|:443... ^C
```
```
# dig metabase.com A 
metabase.com.		36	IN	A	54.192.81.109
metabase.com.		36	IN	A	54.192.81.51
metabase.com.		36	IN	A	54.192.81.250
metabase.com.		36	IN	A	54.192.81.140

# wget -v -O /dev/null https://metabase.com
Resolving metabase.com (metabase.com)... 13.35.115.121, 13.35.115.9, 13.35.115.15, ...
Connecting to metabase.com (metabase.com)|13.35.115.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

**Comment by shrike71** [comment]
You're right. https://www.metabase.com does not work but https://metabase.com does. Fell victim to that local rewrite that Firefox does  from . to www. for 2-part names. Trying from Ireland, if it helps

Shrike71

**Comment by flamber** [comment]
Looks like the DNS records has been updated, so now metabase.com and www.metabase.com works.

**Comment by salsakran** [comment]
@flamber yup, we were trying to permanently redirect www to the apex domain but something went weird.

I reverted the DNS change until we can figure out what went wrong.
Thanks for the heads up! 

Closing as this seems to be resolved, though we'll keep an eye on it once we flip back.
