### ISSUE TITLE
Doesn't work with cloudflare

### ISSUE THREAD

**Issue by elderapo** [metabase/metabase#9646]
When used with cloudflare frontend does not load:
```sh
Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://maps.google.com https://apis.google.com https://www.google-analytics.com https://*.googleapis.com *.gstatic.com ". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Temporary workaround is to turn off the `Rocket Loader`. I guess the proper fix would be [this](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-).

**Comment by flamber** [comment]
Hi @elderapo 
Since Metabase is React frontned and uses huge amounts of JavaScript, I don't think Rocket Loader will benefit anything on Metabase, but might just conflict with it.
If you want to use it, you can use a reverse proxy to modify the header `Content-Security-Policy` to allow scripts from other sources than the already defined.

**Comment by jbrooksuk** [comment]
We run Metabase behind Cloudflare just fine. As @flamber says, you'll need to disable Rocket Loader.

**Comment by elderapo** [comment]
As far as I know, it's impossible to disable rocker loader just for a single subdomain.

So in scenario with multiple services on different subtomains `metabase.aaa.com`, `frontend.aaa.com`, `api.aaa.com` it's impossible to keep rocker loader on for frontend/api.

**Comment by flamber** [comment]
@elderapo 
Looking at the documentation, it looks like you can disable Rocket Loader with Page Rules:
https://support.cloudflare.com/hc/en-us/articles/218411427
If that solves your issue, then please close this issue :+1:

**Comment by salsakran** [comment]
Practically speaking -- playing nicely with arbitrary downstream script caching is outside of the scope of the project.

Closing this because we can't support every CDN or downstream proxy and definitely won't commit to working with them for every upcoming release.

**Comment by cusco** [comment]
> Practically speaking -- playing nicely with arbitrary downstream script caching is outside of the scope of the project.
> 
> Closing this because we can't support every CDN or downstream proxy and definitely won't commit to working with them for every upcoming release.

Hello, 

I'm sorry for bringing up closed topics.. I faced this today myself. 
We're using cloudflare and like in the provided example metabase is a subdomain, and disabling for one requires disabling for all...

I understand that this is not related to metabase, but, I would suggest a possibility of setting some additional values to the current CSP header. 
This way we could allow sourcing a external javascript if we decided to.

Is this idea viable?

**Comment by flamber** [comment]
@cusco You're welcome to create your own version of Metabase with your own CSP headers or custom javascripts, or override headers with a reverse-proxy, but I doubt that it will be implemented in Metabase because of security concerns.
There's problems with a lot of systems, and it takes so long time to troubleshoot weird errors - only recommendation is disable such functionality: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

**Comment by cusco** [comment]
> @cusco You're welcome to create your own version of Metabase with your own CSP headers or custom javascripts, or override headers with a reverse-proxy, but I doubt that it will be implemented in Metabase because of security concerns.
> There's problems with a lot of systems, and it takes so long time to troubleshoot weird errors - only recommendation is disable such functionality: https://www.metabase.com/docs/latest/troubleshooting-guide/proxies.html

OK, understood. Thank you for your attention
