### ISSUE TITLE
Modular Driver - Not a bug, need info on change

### ISSUE THREAD

**Issue by wccropper** [metabase/metabase#9654]
Not  a bug. Need info. I am unable to find documentation on the new modular drivers and how to configure the directory structure.

**Comment by flamber** [comment]
Have you read the wiki? https://github.com/metabase/metabase/wiki/Writing-A-Driver
Or maybe you're looking for what issue #9348 is describing?
Otherwise, could you tell more what your problem is?

**Comment by wccropper** [comment]
Currently there is a plugins dir containing mysql and oracle jar files. Does the statement about the new modular drivers having their own directory not require a change to this structure? It is not clear.

**Comment by flamber** [comment]
I don't understand.
Are you talking about the environment variable `MB_PLUGINS_DIR`?
The JAR-file has the packaged drivers included in `modules/*.metabase-driver.jar`, which gets extracted to the path of the env variable, which Metabase then loads drivers from.

**Comment by wccropper** [comment]
Yes, the MB_PLUGINS_DIR. Is the modular driver not referring to this? I'm specifically reading this https://www.metabase.com/blog/0.32/index.html.

**Comment by flamber** [comment]
Yes, you define `MB_PLUGINS_DIR` and then Metabase loads drivers from that directory.
I don't understand what the question is.

**Comment by wccropper** [comment]
Fromt he Blog post "One of the biggest changes in 0.32 is how database drivers work. Drivers for your database of choice now live in their own directory and don’t get loaded until you actually try and do something like connect to the database or run a query. We’ve seen this change shave around 200 MB off of memory usage in tests(!)."

This makes it sound like each database driver needs to be in its own directory. Currently the jar for mysql and oracle are directly in the MB_PLUGINS_DIR.

**Comment by flamber** [comment]
Okay. No, the driver is a JAR-file (essentially a ZIP-file), which needs to be located in `MB_PLUGINS_DIR`.

**Comment by wccropper** [comment]
Thanks. I just wanted to make sure before I go upgrading our instance tomorrow. Sorry for the confusion on the back 'n forth.

**Comment by flamber** [comment]
Just make sure that you have a backup before upgrading, so you can roll back in case of problems.
