### ISSUE TITLE
Metabase Debugging

### ISSUE THREAD

**Issue by RamazanBIYIK** [metabase/metabase#9663]
I am trying to add a modal to metabase that when i click the table row a popup page will be launched wtih the table row data. I manuelly change the code and build over and over again until it is done. A build time takes app. 4 min. Is there any tool that i can debug metabase? So that i can save a lot of time and focus something else.

**Comment by exabrial** [comment]
You should be able to launch the JDK with debug enabled. Instead of `java -jar metabase.jar`, try this:

```
java -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y -jar metabase.jar
```

This will cause the JVM to wait for a debugger to connect on port 8000 before booting. You can then connect with your IDE and set breakpoints and step through the code.

**Comment by RamazanBIYIK** [comment]
@exabrial Thank for answer. It activates the debugger session. It is great. But i have an error when i tried to connect :

`Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake`

I don't have much experience on java so i have no clue and researches gone nothing .I use 3000 port for metabase. Do you have any clue for that problem?

**Comment by exabrial** [comment]
Sounds like there's something else listeningon port 8000, try a different port!

**Comment by exabrial** [comment]
If you're on Linux, do a `sudo netstat -lpn | grep 8000` to see what processes are bound to that port

**Comment by RamazanBIYIK** [comment]
Default port for metabase is 3000. So i used 3000.I check the ports with the command thanks to you. They are not used until i run jar debug. I think the debugger command is true because when i run the command i have this output:

> Listening for transport dt_socket at address: 3000

Hovewer when i try to reach localhost:3000

> Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
> Debugger failed to attach: timeout during handshake
> Debugger failed to attach: timeout during handshake

i get this error.

**Comment by exabrial** [comment]
Are you connecting with your web browser?

**Comment by RamazanBIYIK** [comment]
Yes i am trying to connect from web browser. Is there any other way to connect metabase?

**Comment by exabrial** [comment]
I assume your trying to debug the clojure code, correct?

If so, you need to connect via your IDE that has a clojure debug plug-in
running.

**Comment by RamazanBIYIK** [comment]
YESS!! Wow thanks that makes sense now.

**Comment by salsakran** [comment]
closing since this isn't really an issue with Metabase itself. 

Glad to hear you got it working though!
