### ISSUE TITLE
How to limit admin permission

### ISSUE THREAD

**Issue by wm9947** [metabase/metabase#9670]
For User permission, is there just two kind of users Admin, all user?
I'd like to give a limited group permission which can only access specific group.
Such as, I want make a group 'Marketing', which included 'group admin' & 'user'.
The 'group admin' cannot access other group, make metric, add user and so on.

Will Metabase contain this kind of function or not considering?

Thx.

**Comment by flamber** [comment]
Hi @wm9947 
Sounds like you're looking for #6799 - go and upvote by clicking :+1: and close this issue.

**Comment by wm9947** [comment]
Thx for your kind
