### ISSUE TITLE
Column Selector Broken for Postgres Joins

### ISSUE THREAD

**Issue by RobertLowe** [metabase/metabase#9672]
### Bug

- Your browser and the version: Latest Chrome, Latest Firefox
- Your operating system: OS X 10.13.6
- Your databases: Postgres, *mongo
- Metabase version: 31.2 & 3.2.1 & 3.3 snapshot affected
- Metabase hosting environment: Heroku /  MacOS / Remote Linux Server
- Metabase internal database: Postgres

Steps to reproduce:

Collection with foreign key:

![Screen Shot 2019-04-02 at 5 48 29 AM](https://user-images.githubusercontent.com/601141/55393688-bae3c000-550b-11e9-8869-b0977d0b6e43.png)

Get answer:

![Screen Shot 2019-04-02 at 5 48 41 AM](https://user-images.githubusercontent.com/601141/55393723-ca630900-550b-11e9-9ed8-046a740d2799.png)

Open column settings:
![Screen Shot 2019-04-02 at 5 48 57 AM](https://user-images.githubusercontent.com/601141/55452419-9f2cf800-55a5-11e9-97c5-bb11f794068c.png)

Add column
![Screen Shot 2019-04-02 at 5 49 15 AM](https://user-images.githubusercontent.com/601141/55452442-bec42080-55a5-11e9-94aa-c1c6928e2e66.png)

Expected: Column to be added.
Actual: Column not added.

Click reset defaults:

![Screen Shot 2019-04-02 at 5 49 26 AM](https://user-images.githubusercontent.com/601141/55452425-a9e78d00-55a5-11e9-825c-4e340722378a.png)

Expected: Columns to be reset to defaults
Actual: Previously selected columns added

Click more columns and reset again:
![Screen Shot 2019-04-02 at 5 49 50 AM](https://user-images.githubusercontent.com/601141/55452516-ffbc3500-55a5-11e9-98d1-58613bb448a3.png)

Expected: Columns to be reset to defaults
Actual: Previously selected columns added, even multiples of the same field

**Comment by flamber** [comment]
Hi @RobertLowe 
Looks like a duplicate of #9144, but you have some good details about the "Reset to defaults", so please add that as a comment - and remember to click the :+1:

**Comment by RobertLowe** [comment]
Done, thanks
