### ISSUE TITLE
Snowflake Driver: Authentication token has expired

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#9674]
Metabase v0.32.1
Driver: Snowflake

Error message: "Authentication token has expired. The user must authenticate again."

Just upgraded from a previous version where we had manually compiled snowflake support in. Now my questions fail regularly with the above error. My workaround has been to re-save the db connection with a fake change and for some reason that fixes the problem temporarily.

**Comment by schmkr** [comment]
We are experiencing the same error, after upgrading to 0.32. Connection worked fine in 0.31.x

**Comment by camsaul** [comment]
The best I can tell, this is a regression in the updated Snowflake JDBC driver we're using. Here's other reports of this issue:

https://snowflakecommunity.force.com/s/question/0D50Z00006xVtEmSAK/using-clientsessionkeepalive-in-jdbc-connection-string

It sounds like if we add `CLIENT_SESSION_KEEP_ALIVE=true` as a connection property it will resolve this issue. I'll try to repro this locally and then see if adding that change fixes it

**Comment by camsaul** [comment]
Fixed by #9700

**Comment by hansyson** [comment]
we are still experiencing this issue even on .39

**Comment by flamber** [comment]
@hansyson 
Do you mean 0.32.9? Latest release is now 0.32.10.
How are you running Metabase - JAR, Docker, ...?
If JAR, then check if you're using the latest driver - verify the timestamp of the driver in the plugins directory, which should be equal to first time you started 0.32.9
