### ISSUE TITLE
Unable to substitute : param not specified on 0.32.1

### ISSUE THREAD

**Issue by Roze** [metabase/metabase#9680]
After update to 0.32.1 (from 0.29.x) with MySQL backend and DB some of our saved queries fail with odd error:

Unable to substitute 'startDate': param not specified. Found: ("startDate" "endDate")",

Where startDate and endDate are datepicker fields.

While investigating I found out that it actually happens only when the 60 second timeout happens on MB side but instead of the "Your question took too long" error page more confusing error is returned. The moment a lower date range is picked (Mysql returns the result quicker) everything is fine.

Full backtrace:

```
04-03 12:21:58 WARN metabase.query-processor :: {:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Unable to substitute 'startDate': param not specified.\nFound: (\"startDate\" \"endDate\")",
 :stacktrace
 ("--> util.i18n$ex_info.invokeStatic(i18n.clj:102)"
  "util.i18n$ex_info.invoke(i18n.clj:98)"
  "query_processor.middleware.parameters.sql$fn__36021$parse_params_or_throw__36026$fn__36027.invoke(sql.clj:535)"
  "query_processor.middleware.parameters.sql$fn__36021$parse_params_or_throw__36026.invoke(sql.clj:530)"
  "query_processor.middleware.parameters.sql$fn__36047$parse_optional__36052$fn__36053.invoke(sql.clj:549)"
  "query_processor.middleware.parameters.sql$fn__36047$parse_optional__36052.invoke(sql.clj:544)"
  "query_processor.middleware.parameters.sql$fn__36088$parse_template__36093$fn__36094.invoke(sql.clj:559)"
  "query_processor.middleware.parameters.sql$fn__36088$parse_template__36093.invoke(sql.clj:556)"
  "query_processor.middleware.parameters.sql$fn__36112$expand_query_params__36117$fn__36121.invoke(sql.clj:569)"
  "query_processor.middleware.parameters.sql$fn__36112$expand_query_params__36117.invoke(sql.clj:567)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:585)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:580)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:43)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:49)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:46)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__33604.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__36375.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32800$fn__32801.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32800.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__39430$fn__39431.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
  "query_processor.store$do_with_new_store.invoke(store.clj:31)"
  "query_processor.middleware.store$initialize_store$fn__39430.invoke(store.clj:10)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:98)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:96)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:110)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:106)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__33222.invoke(cache.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__33270.invoke(catch_exceptions.clj:63)"
  "query_processor$process_query.invokeStatic(query_processor.clj:232)"
  "query_processor$process_query.invoke(query_processor.clj:228)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:341)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:335)"
  "query_processor$fn__39618$process_query_and_save_execution_BANG___39623$fn__39624.invoke(query_processor.clj:371)"
  "query_processor$fn__39618$process_query_and_save_execution_BANG___39623.invoke(query_processor.clj:357)"
  "async.semaphore_channel$do_f_with_permit$f__40020.invoke(semaphore_channel.clj:81)"
  "async.util$do_on_separate_thread$fn__39855.invoke(util.clj:53)"),
 :query
 {:type :native,
  :native
  {:query
   "SELECT\r\n    FROM_UNIXTIME(o.created, '%Y-%m')                     AS `order_date`,\r\n    i.technique,\r\n    v.name,\r\n    v.color,\r\n    v.size,\r\n    coalesce((select pp.value from product_prices pp where pp.variant_id=v.id and pp.currency='USD' and pp.variant_id is not null limit 1),\r\n    (select pp.value from product_prices pp where pp.variant_id is null and pp.product_id=p.id and pp.currency='USD' limit 1))   AS productStandartPrice,\r\n    i.price as itemPriceInOrderWithDiscount,\r\n    d.amount as Discount,\r\n   (select sum(pp.value) from product_prices pp where pp.type in (select itf.type from item_files itf where itf.item_id = i.id and itf.type!='mockup' and itf.type!='front'  group by itf.type) and pp.product_id=p.id and currency='USD') as printPrice,\r\n    sum(i.quantity)                                       AS `Ordered`,\r\n    sum(i.price * i.quantity)                             AS 'sum',\r\n    sum(coalesce((select pp.value from product_prices pp where pp.variant_id=v.id and pp.currency='USD' and pp.variant_id is not null limit 1),\r\n    (select pp.value from product_prices pp where pp.variant_id is null and pp.product_id=p.id and pp.currency='USD' limit 1)) * i.quantity) as expectedSum,\r\n    sum(coalesce(i.external_price, i.price) * i.quantity) AS 'retail sum',\r\n    sum(if (i.price < coalesce(v.standardPrice, p.standardPrice), d.amount, 0) * i.quantity) as totalDiscount,\r\n    v.discontinued,\r\n    v.active,\r\n    count(DISTINCT o.environment_id)                      AS customer_count,\r\n   (select group_concat(itf.type) from item_files itf where itf.item_id = i.id and itf.type!='mockup' order by itf.type) as fileTypes,\r\n   i.product_id as variantId\r\nFROM items i\r\n    JOIN variants v ON v.id = i.product_id\r\n    JOIN orders o ON o.id = i.order_id\r\n    JOIN products p ON p.id = v.parent\r\n    left join discounts d on d.product_id = p.id and d.environment_id = o.environment_id and v.id = d.variant_id and d.status=1\r\nWHERE o.created >= unix_timestamp(concat(date_format({{startDate}}, '%Y-%m-%d'), \" 00:00:00\")) \r\nAND o.created <= unix_timestamp(concat(date_format({{endDate}}, '%Y-%m-%d'), \" 23:59:59\"))\r\n    AND o.status = 'fulfilled' AND o.environment_id not in (2, 305820)\r\nGROUP BY `order_date`, i.product_id, i.price, fileTypes;",
   :template-tags
   {"startDate" {:id "064de4c4-b6bd-f846-61e6-f4b95c7fdfeb", :name "startDate", :display-name "Startdate", :type :date},
    "endDate" {:id "7ad6f172-9bec-53d0-6173-df60f5f74667", :name "endDate", :display-name "Enddate", :type :date}}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters nil,
  :middleware nil,
  :cache-ttl 3,
  :info
  {:executed-by 147,
   :context :question,
   :card-id 381,
   :dashboard-id nil,
   :query-hash [-107, -85, -40, -118, -104, 124, 96, 2, -121, 40, -6, 117, -29, -2, -95, 110, -81, 68, -1, -82, 56, -112, 9, 89, 68, 112, 71, 52, 19, 36, -26, 46],
   :query-type "native"}},
 :ex-data {:status-code 400}}

04-03 12:21:58 WARN metabase.query-processor :: Query failure
04-03 12:21:58 DEBUG async.semaphore-channel :: f finished, permit will be returned
```

Also is there a way to allow queries actually run longer than the hard 60 sec limit?
I was reading through https://github.com/metabase/metabase/issues/1749 and several other similar issues but it seems there isn't actually an option to change it (on 0.29.x somehow the long running queries usually wouldn't be killed but now with the async api threads everything above 60s dies immediately).

**Comment by flamber** [comment]
It seems related to #9667, but maybe you're on to something about the async.
There shouldn't be any timeout. Are you using Docker or JAR-file? Running a custom reverse proxy?

**Comment by Roze** [comment]
> Are you using Docker or JAR-file? Running a custom reverse proxy?

Jar file, behind nginx.

I also checked if maybe any of the nginx proxy__* timeouts are too low but it seems not to be the case since I get a json response from /api/card/381
(with all the stacktrace (commented it out)):

`
{"database_id":2,"started_at":"2019-04-03T19:37:43.591Z","json_query":{"database":2,"type":"native","native":{"query":"SELECT\r\n    FROM_UNIXTIME(o.created, '%Y-%m')                     AS `order_date`,\r\n    i.technique,\r\n    v.name,\r\n    v.color,\r\n    v.size,\r\n    coalesce((select pp.value from product_prices pp where pp.variant_id=v.id and pp.currency='USD' and pp.variant_id is not null limit 1),\r\n    (select pp.value from product_prices pp where pp.variant_id is null and pp.product_id=p.id 
`
.. 
`
o.status = 'fulfilled' AND o.environment_id not in (2, 305820)\r\nGROUP BY `order_date`, i.product_id, i.price, fileTypes;","template-tags":{"startDate":{"id":"064de4c4-b6bd-f846-61e6-f4b95c7fdfeb","name":"startDate","display-name":"Startdate","type":"date"},"endDate":{"id":"7ad6f172-9bec-53d0-6173-df60f5f74667","name":"endDate","display-name":"Enddate","type":"date"}}},"constraints":{"max-results":10000,"max-results-bare-rows":2000},"parameters":null,"middleware":null,"cache-ttl":62},"status":"failed","stacktrace":["--> util.i18n$ex_info.invokeStatic(i18n.clj:102)","util.i18n$ex_info.invoke(i18n.clj:98)","query_processor.middleware.parameters.sql$fn__36021$parse_params_or_throw__36026$fn__36027.invoke(sql.clj:535)",
`
..
`
"async.util$do_on_separate_thread$fn__39855.invoke(util.clj:53)"],"context":"question","error":"Unable to substitute 'startDate': param not specified.\nFound: (\"startDate\" \"endDate\")","row_count":0,"running_time":235,"data":{"rows":[],"cols":[],"columns":[]}}
`

For me strange looks the "running_time":235
as it's actually even shorter of those 60 sec what I initially thought to be the timeout.

![mb](https://user-images.githubusercontent.com/923731/55508683-08bf0c00-5663-11e9-90af-21ac59eaa0d6.jpg)

**Comment by camsaul** [comment]
@Roze can you try this in Metabase 0.32.2? I fixed a similar bug and I think it might be the same one as this.

**Comment by Roze** [comment]
It happens also with 0.32.2 the error is different though.

Again if I choose a shorter date range (and MySQL can return the result quickly enough) everything works fine:

Backtrace:
```
04-04 19:52:11 INFO api.card :: Question's average execution duration is 49834 ms; using 'magic' TTL of 498 seconds ?
04-04 19:52:11 DEBUG middleware.log :: POST /api/card/381/query 200 (8 ms) (4 DB calls). Jetty threads: 8/200 (6 busy, 1 idle, 0 queued) (59 total active threads)
04-04 19:52:11 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__40023@430e8823 on separate thread...
04-04 19:52:11 DEBUG async.api-response :: starting streaming response
04-04 19:52:17 INFO middleware.cache :: Query took 41555 ms to run; miminum for cache eligibility is 60000 ms
04-04 19:52:17 DEBUG async.semaphore-channel :: f finished, permit will be returned
04-04 19:52:41 INFO api.card :: Question's average execution duration is 272 ms; using 'magic' TTL of 3 seconds ?
04-04 19:52:41 DEBUG middleware.log :: POST /api/card/381/query 200 (9 ms) (4 DB calls). Jetty threads: 8/200 (6 busy, 1 idle, 0 queued) (60 total active threads)
04-04 19:52:41 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__40023@ca98f0c on separate thread...
04-04 19:52:41 DEBUG async.api-response :: starting streaming response
04-04 19:52:42 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.Exception,
 :error "'Start Date' is a required param.",
 :stacktrace
 ("--> query_processor.middleware.parameters.sql$fn__35433$default_value_for_tag__35438$fn__35442.invoke(sql.clj:199)"
  "query_processor.middleware.parameters.sql$fn__35433$default_value_for_tag__35438.invoke(sql.clj:192)"
  "query_processor.middleware.parameters.sql$fn__35587$value_for_tag__35592$fn__35593.invoke(sql.clj:282)"
  "query_processor.middleware.parameters.sql$fn__35587$value_for_tag__35592.invoke(sql.clj:276)"
  "query_processor.middleware.parameters.sql$fn__35613$query__GT_params_map__35618$fn__35624$iter__35627__35631$fn__35632.invoke(sql.clj:297)"
  "query_processor.middleware.parameters.sql$fn__35613$query__GT_params_map__35618$fn__35624.invoke(sql.clj:296)"
  "query_processor.middleware.parameters.sql$fn__35613$query__GT_params_map__35618.invoke(sql.clj:286)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:585)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:580)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:43)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:49)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:46)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__33606.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__36377.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32802$fn__32803.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__32802.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__39432$fn__39433.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
  "query_processor.store$do_with_new_store.invoke(store.clj:31)"
  "query_processor.middleware.store$initialize_store$fn__39432.invoke(store.clj:10)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invokeStatic(cache.clj:98)"
  "query_processor.middleware.cache$run_query_and_save_results_if_successful_BANG_.invoke(cache.clj:96)"
  "query_processor.middleware.cache$run_query_with_cache.invokeStatic(cache.clj:110)"
  "query_processor.middleware.cache$run_query_with_cache.invoke(cache.clj:106)"
  "query_processor.middleware.cache$maybe_return_cached_results$fn__33224.invoke(cache.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__33272.invoke(catch_exceptions.clj:63)"
  "query_processor$process_query.invokeStatic(query_processor.clj:232)"
  "query_processor$process_query.invoke(query_processor.clj:228)"
  "query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:341)"
  "query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:335)"
  "query_processor$fn__39620$process_query_and_save_execution_BANG___39625$fn__39626.invoke(query_processor.clj:371)"
  "query_processor$fn__39620$process_query_and_save_execution_BANG___39625.invoke(query_processor.clj:357)"
  "async.semaphore_channel$do_f_with_permit$f__40023.invoke(semaphore_channel.clj:81)"
  "async.util$do_on_separate_thread$fn__39858.invoke(util.clj:53)"),
 :query
 {:type :native,
  :native
  {:query
   "SELECT\r\n    FROM_UNIXTIME(o.created, '%Y-%m')                     AS `order_date`,\r\n    i.technique,\r\n    v.name,\r\n    v.color,\r\n    v.size,\r\n    coalesce((select pp.value from product_prices pp where pp.variant_id=v.id and pp.currency='USD' and pp.variant_id is not null limit 1),\r\n    (select pp.value from product_prices pp where pp.variant_id is null and pp.product_id=p.id and pp.currency='USD' limit 1))   AS productStandartPrice,\r\n    i.price as itemPriceInOrderWithDiscount,\r\n    d.amount as Discount,\r\n   (select sum(pp.value) from product_prices pp where pp.type in (select itf.type from item_files itf where itf.item_id = i.id and itf.type!='mockup' and itf.type!='front'  group by itf.type) and pp.product_id=p.id and currency='USD') as printPrice,\r\n    sum(i.quantity)                                       AS `Ordered`,\r\n    sum(i.price * i.quantity)                             AS 'sum',\r\n    sum(coalesce((select pp.value from product_prices pp where pp.variant_id=v.id and pp.currency='USD' and pp.variant_id is not null limit 1),\r\n    (select pp.value from product_prices pp where pp.variant_id is null and pp.product_id=p.id and pp.currency='USD' limit 1)) * i.quantity) as expectedSum,\r\n    sum(coalesce(i.external_price, i.price) * i.quantity) AS 'retail sum',\r\n    sum(if (i.price < coalesce(v.standardPrice, p.standardPrice), d.amount, 0) * i.quantity) as totalDiscount,\r\n    v.disabled_in_push,\r\n    v.active,\r\n    count(DISTINCT o.environment_id)                      AS customer_count,\r\n   (select group_concat(itf.type) from item_files itf where itf.item_id = i.id and itf.type!='mockup' order by itf.type) as fileTypes,\r\n   i.product_id as variantId\r\nFROM items i\r\n    JOIN variants v ON v.id = i.product_id\r\n    JOIN orders o ON o.id = i.order_id\r\n    JOIN products p ON p.id = v.parent\r\n    left join discounts d on d.product_id = p.id and d.environment_id = o.environment_id and v.id = d.variant_id and d.status=1\r\nWHERE o.created >= unix_timestamp(concat(date_format({{startDate}}, '%Y-%m-%d'), \" 00:00:00\")) \r\nAND o.created <= unix_timestamp(concat(date_format({{endDate}}, '%Y-%m-%d'), \" 23:59:59\"))\r\n    AND o.status = 'fulfilled' AND o.environment_id not in (2, 305820)\r\nGROUP BY `order_date`, i.product_id, i.price, fileTypes;",
   :template-tags
   {"startDate" {:id "421f3bbd-e499-1249-64df-4f0f3e12cbfd", :name "startDate", :display-name "Start Date", :type :date, :required true},
    "endDate" {:id "d80b721c-fa5d-9e71-c1cd-648dbfe8f886", :name "endDate", :display-name "End Date", :type :date, :required true}}},
  :constraints {:max-results 10000, :max-results-bare-rows 2000},
  :parameters nil,
  :middleware nil,
  :cache-ttl 3,
  :info
  {:executed-by 147,
   :context :question,
   :card-id 381,
   :dashboard-id nil,
   :query-hash [29, 4, 80, 126, 3, 68, 80, 102, 31, -50, 119, 113, -74, -74, -91, 55, 34, 15, -120, -125, 122, 119, -105, -103, -91, -33, -74, -59, 76, 108, -50, 126],
   :query-type "native"}}}

04-04 19:52:42 WARN metabase.query-processor :: Query failure
04-04 19:52:42 DEBUG async.semaphore-channel :: f finished, permit will be returned
```

I was looking at the backtrace and some things seems odd (or maybe it's the way it should be?):
When I push the 'Get Answer' button for some reason first POST is logged but nothing is yet returned to the client browser:
```
04-04 19:52:11 DEBUG middleware.log :: POST /api/card/381/query 200 (8 ms) (4 DB calls). Jetty threads: 8/200 (6 busy, 1 idle, 0 queued) (59 total active threads)
04-04 19:52:11 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__40023@430e8823 on separate thread...
04-04 19:52:11 DEBUG async.api-response :: starting streaming response
04-04 19:52:17 INFO middleware.cache :: Query took 41555 ms to run; miminum for cache eligibility is 60000 ms
04-04 19:52:17 DEBUG async.semaphore-channel :: f finished, permit will be returned
```

and then after ~20 seconds where the actual output comes to the browser with an error:
```
04-04 19:52:41 INFO api.card :: Question's average execution duration is 272 ms; using 'magic' TTL of 3 seconds ?
04-04 19:52:41 DEBUG middleware.log :: POST /api/card/381/query 200 (9 ms) (4 DB calls). Jetty threads: 8/200 (6 busy, 1 idle, 0 queued) (60 total active threads)
04-04 19:52:41 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__40023@ca98f0c on separate thread...
04-04 19:52:41 DEBUG async.api-response :: starting streaming response
04-04 19:52:42 WARN metabase.query-processor :: {:status :failed,
..
04-04 19:52:42 WARN metabase.query-processor :: Query failure
```

**Comment by Roze** [comment]
I reverted back to 0.31.2 (we kind of skipped 0.31.x) and everything works. So maybe there is something wrong with the new async api.

**Comment by camsaul** [comment]
Hey @Roze. This is certainly a weird error. I did find and fix a bug with the async API where it wasn't keeping long (> 60 second) requests alive the way it was supposed to be doing in certain cases. So I think this might ultimately be part of the same bug as #9693.

I'm hoping to push out a new 0.32.3 release with the fix on Monday.

**Comment by camsaul** [comment]
This should be fixed in Metabase 0.32.3. Please let me know if you continue to see it after updating

**Comment by nautilus28** [comment]
@camsaul  I am having the same bug in Metabase 0.31.2. Could you please point me to which commit you fixed the issue? Thanks

**Comment by flamber** [comment]
@nautilus28 Upgrade to 0.32.8 - there has been a few fixes for async issues, example #9704

**Comment by victoraugustolls** [comment]
I'm having this issue on 0.32.9

**Comment by flamber** [comment]
@victoraugustolls Can you provide logs, since this should have been fixed, so maybe it's another issue?

**Comment by victoraugustolls** [comment]
Sure!

`{:status :failed,
 :class clojure.lang.ExceptionInfo,
 :error "Unable to substitute 'end_date': param not specified.\nFound: (\"start_date\" \"end_date\")",
 :stacktrace
 ("--> util.i18n$ex_info.invokeStatic(i18n.clj:102)"
  "util.i18n$ex_info.invoke(i18n.clj:98)"
  "query_processor.middleware.parameters.sql$fn__38361$parse_params_or_throw__38366$fn__38367.invoke(sql.clj:534)"
  "query_processor.middleware.parameters.sql$fn__38361$parse_params_or_throw__38366.invoke(sql.clj:529)"
  "query_processor.middleware.parameters.sql$fn__38390$parse_optional_params__38395$fn__38396.invoke(sql.clj:557)"
  "query_processor.middleware.parameters.sql$fn__38390$parse_optional_params__38395.invoke(sql.clj:551)"
  "query_processor.middleware.parameters.sql$fn__38429$parse_template__38434$fn__38435.invoke(sql.clj:565)"
  "query_processor.middleware.parameters.sql$fn__38429$parse_template__38434.invoke(sql.clj:562)"
  "query_processor.middleware.parameters.sql$fn__38453$expand_query_params__38458$fn__38462.invoke(sql.clj:575)"
  "query_processor.middleware.parameters.sql$fn__38453$expand_query_params__38458.invoke(sql.clj:573)"
  "query_processor.middleware.parameters.sql$expand.invokeStatic(sql.clj:581)"
  "query_processor.middleware.parameters.sql$expand.invoke(sql.clj:577)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invokeStatic(parameters.clj:21)"
  "query_processor.middleware.parameters$expand_parameters_STAR_.invoke(parameters.clj:14)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:44)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:40)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invokeStatic(parameters.clj:50)"
  "query_processor.middleware.parameters$substitute_parameters_STAR_.invoke(parameters.clj:47)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__35460.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__38788.invoke(resolve_driver.clj:23)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__34649$fn__34650.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__34649.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__41910$fn__41911.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:41)"
  "query_processor.store$do_with_new_store.invoke(store.clj:37)"
  "query_processor.middleware.store$initialize_store$fn__41910.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__34250.invoke(async.clj:23)"
  "query_processor.middleware.async_wait$runnable$fn__34375.invoke(async_wait.clj:89)"),
 :query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :native,
  :middleware {:userland-query? true},
  :native
  {:query
   "SELECT\r\nkse.level_3_team as time_n3,\r\n  SUM(CASE WHEN kse.level_3_total_minutes <= kse.level_3_expected_minutes AND kse.type= 'sla' THEN 1.0 else 0 end)*1.0 as NUM_SLA,\r\n  SUM(CASE WHEN kse.type= 'sla' then 1.0 else 0 end)*1.0 as Den_SLA,\r\n  ROUND(SUM(CASE\r\n            WHEN kse.level_3_total_minutes <= kse.level_3_expected_minutes AND kse.type= 'sla' THEN 1.0\r\n   ELSE 0 END ) *1.0 / SUM(CASE WHEN kse.type= 'sla' then 1.0 else 0 end)*100,2 )as SLA\r\n   \r\n    \r\n    FROM\r\n        public.encantability_cases kse\r\n    \r\n\r\nWHERE   kse.solve_date >= {{start_date}}\r\n    AND kse.solve_date < {{end_date}}\r\n    AND kse.level_3_team is not null\r\n    AND kse.level_3_team <>'ilha vip'\r\n    AND kse.level_3_total_minutes is not null\r\n    \r\n\r\n    \r\n    GROUP BY time_n3\r\n    ORDER BY Den_SLA desc\r\n",
   :template-tags
   {"start_date" {:id "9f985e3f-b924-641d-65ec-778272b40b22", :name "start_date", :display-name "Start date", :type :date},
    "end_date" {:id "058ef976-37b3-d3d7-3d27-c0f4dc5b7005", :name "end_date", :display-name "End date", :type :date}}},
  :info
  {:executed-by 39,
   :context :question,
   :card-id 1282,
   :dashboard-id nil,
   :query-hash [119, 32, -84, -111, 33, -15, -118, -127, -59, 101, -93, 115, 111, 112, 95, -97, 113, -23, -58, 55, -114, 81, -1, 22, 38, -3, 102, 93, -49, -115, -86, -78]},
  :parameters [{:type "date/single", :target ["variable" ["template-tag" "start_date"]], :value "2019-07-01"}],
  :async? true,
  :cache-ttl nil},
 :ex-data {:status-code 400}}`

**Comment by victoraugustolls** [comment]
sure!

```

**Comment by flamber** [comment]
@victoraugustolls Have you redacted the actual query? From the looks of it, you're only defining the parameter/filter `start_date`, so are you remembering to use Optional Clauses around `end_date`?
```
SELECT * FROM table
WHERE 1=1
[[AND column >= {{start_date}}]]
[[AND column >= {{end_date}}]]
```

**Comment by victoraugustolls** [comment]
Yes, I redacted, but the part where the params are used are like this:

```
solve_date >= {{start_date}} AND solve_date < {{end_date}}
```

**Comment by flamber** [comment]
@victoraugustolls 
Okay, but have you entered anything into the `end_date` widget/filter? Otherwise, that's you problem and you should be using [Optional Clauses](https://metabase.com/docs/latest/users-guide/13-sql-parameters.html#optional-clauses) if you don't require input in a variable.

**Comment by victoraugustolls** [comment]
I will double check with who tried to run the query. But I do have a question, am I able to block a query if parameters are not specified?

**Comment by victoraugustolls** [comment]
Fixed the issue, it was the one who tries to run the query fault. Sorry for the inconvenience.

**Comment by flamber** [comment]
@victoraugustolls Yes, you can set a variable to be required by enabling "Required?"
![image](https://user-images.githubusercontent.com/1447303/60918748-48445800-a251-11e9-939c-d20a3440db9f.png)

**Comment by FlorRios7** [comment]
Hi I'm having the same issue with metabase 32.4, what can I do?

**Comment by flamber** [comment]
@FlorRios7 
Upgrade to 0.32.10 (or the newly 0.33.0 released yesterday, but that's a big change).
Remember to backup before upgrading.
