### ISSUE TITLE
Error rendering JSON data from MySQL column, type JSON

### ISSUE THREAD

**Issue by bm1391** [metabase/metabase#9681]
In my Mysql database, I have a column `message` that has JSON type and JSON data in it. I can query it fine within the MySQL console. But I get errors when I try to query the column in Metabase. The data that is returned looks like this:

> 0x7B216969

Where it should actually be a JSON object.

Mysql Version:

> mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

OS:

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04 LTS
> Release:	18.04
> Codename:	bionic

Metabase:

> Installed with Jar file
> Starting Metabase version v0.32.1 (0b14a7e release-0.32.0)

Errors I receive when running a query in Metabase:

> WARN driver.common :: Don't know how to map class 'class [B' to a Field base_type, falling back to :type/*.
> 04-03 17:56:07 WARN driver.common :: Don't know how to map class 'class [B' to a Field base_type, falling back to :type/*.

I went to the Admin settings and mapped the field to `JSON` and received the same error. 

And it looks like the mysql driver loads correctly

> 04-03 17:35:08 INFO metabase.driver :: Registered driver :mysql (parents: :sql-jdbc) 🚚
> Load driver :mysql took 28 ms

Thank you for any help!

**Comment by flamber** [comment]
Hi @bm1391 
Seems like you're looking for the same functionality as requested for Postgres in issue #708
Not sure if that issue should be expanded to include MySQL/MariaDB or have it's own issue.
You can create a `View` that extracts the data, so Metabase just uses that.

**Comment by bm1391** [comment]
Thanks, I created a `View` in MySQL and then queried it in MetaBase and it is the same results

**Comment by flamber** [comment]
@bm1391 You need to use `JSON_EXTRACT` in the `View`, so Metabase just sees a "regular" table.

**Comment by bm1391** [comment]
@flamber Thanks I mixed up the order.

**Comment by Crusader4Christ** [comment]
Metabase 0.31 was working fine with JSON fields, but now 0.32.4 - its broken

**Comment by stremlau** [comment]
Looks like Metabase is not able to handle quoted JSON results. Try using `JSON_UNQUOTE(JSON_EXTRACT(...))` or the short form `column->>"jsonpath"` (see https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html#operator_json-inline-path)

**Comment by Korayem** [comment]
This should be an out of the box experience
I used PowerBI before and it's natively there with no workarounds

**Comment by Korayem** [comment]
Possible duplicate https://github.com/metabase/metabase/issues/9681

**Comment by Korayem** [comment]
possible duplicate #9800
