### ISSUE TITLE
Needed to create MB_PLUGINS_DIR manaully

### ISSUE THREAD

**Issue by danilvoe** [metabase/metabase#9691]
browser and the version: Firefox 66
operating system: Linux Mint
databases: sql server
Metabase version: 0.32.2
Metabase hosting environment: Debian 8
Metabase internal database: Postgres

After updating to 0.32.1 / 0.32.2, an error appeared when accessing / creating a connection to the MS SQL Server database

```
Apr 04 13:51:23 WARN metabase.query-processor :: {:status :failed,
 :class java.lang.IllegalArgumentException,
 :error "No method in multimethod 'connection-details->spec' for dispatch value: :sqlserver",
 :stacktrace
 ("clojure.lang.MultiFn.getFn(MultiFn.java:156)"
  "clojure.lang.MultiFn.invoke(MultiFn.java:233)"
```

[full log.txt](https://github.com/metabase/metabase/files/3043116/full.log.txt)

**Comment by camsaul** [comment]
Hey @danilvoe what version did you upgrade to? Were you running Metabase from `master` at any point in the last few months?

My guess is that you have an older version of the SQL Server driver saved in the plugins directory and it's not updating it. Can you try deleting it like

```sh
rm ./plugins/sqlserver.metabase-driver.jar
```

and restarting Metabase? That should fix it

I'll have to make some tweaks so this happens automatically when Metabase is restarted

**Comment by danilvoe** [comment]
@danilvoe 

The latest version is 0.32.2.
Always updated from release versions only.
I can not find the file sqlserver.metabase-driver.jar, the search on the server also does not find it. Where should the folder be located plugs?
The installation was performed simply by downloading the metabase.jar file and launching it.

**Comment by danilvoe** [comment]
After setting the values for MB_PLUGINS_DIR in the environment variables, the necessary drivers were created in the directory (after a reboot). After that, everything worked. Ran through the documentation did not find that there was a mention about this environment variable.

**Comment by camsaul** [comment]
Hi @danilvoe, normally you shouldn't need to create an `MB_PLUGINS_DIR` directory, Metabase will create it automatically when it launches.
