### ISSUE TITLE
Additional JDBC connection string options for Redshift

### ISSUE THREAD

**Issue by jmccarthy** [metabase/metabase#9695]
I am looking to enable the additional JDBC ("additional-options") field for the Redshift driver.

Using `vertica.clj` as a template, I made the following changes -- but the UI does not reflect the expected field: https://github.com/jmccarthy/metabase/commit/d29055eaf27a1f79313d1c9a6bfa485bdfe7c910

Could someone point me in the right direction? Are there files that must be modified beyond the main driver file and the manifest?

Will convert to PR once it's working.

Thanks!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
You have to rebuild the driver 

```bash
./bin/build-driver.sh redshift
```

And then delete the one in you plugins directory 

```bash
rm ./plugins/redshift.metabase-driver.jar
```

and restart Metabase

**Comment by jmccarthy** [comment]
I had been using bin/build, which does invoke build-drivers.sh.

Field is still not present after following the above steps, including purging the jar from plugins.

Could driver heritage be a problem? The vertica driver is a child of :sql-jdbc, whereas the Redshift driver is a child of :postgres

Thanks @camsaul !

```
jmccarthy-mbp:metabase jmccarthy$ ./bin/build-driver.sh redshift
Copying /Users/jmccarthy/code/metabase/modules/drivers/redshift/target/uberjar/redshift.metabase-driver.jar -> /Users/jmccarthy/code/metabase/resources/modules/redshift.metabase-driver.jar
Verifying redshift driver...
Checking whether resources/modules/redshift.metabase-driver.jar exists....
File exists.
Checking whether driver contains main class file metabase/driver/redshift__init.class...
Main class file found.
Checking whether driver contains plugin manifest...
Plugin manifest found.
Driver verification successful.
jmccarthy-mbp:metabase jmccarthy$ rm ./plugins/redshift.metabase-driver.jar 
jmccarthy-mbp:metabase jmccarthy$ java -jar target/uberjar/metabase.jar 
```

**Comment by camsaul** [comment]
Oh sorry. I didn't realize you were running Metabase from the JAR

Try copying the Redshift driver you built into the plugins directory

```
cp ./resources/modules/redshift.metabase-driver.jar ./plugins/redshift.metabase-driver.jar
```

 and then restarting. That should do it

**Comment by jmccarthy** [comment]
Made the change you suggested to metabase-plugin.clj; copied the redshift jar as suggested above; tried to start metabase from both the uberjar and bin/start -- still not seeing the field :(

**Comment by camsaul** [comment]
Hey @jmccarthy, send me a link to your repo/branch and I'll take a look when I get a chance.

**Comment by jmccarthy** [comment]
@camsaul here you go: https://github.com/jmccarthy/metabase

Just this one commit so far: https://github.com/jmccarthy/metabase/commit/d29055eaf27a1f79313d1c9a6bfa485bdfe7c910

**Comment by jmccarthy** [comment]
Happy to take another swing at this if someone could offer a pointer on what to try next. Thanks @camsaul

**Comment by jmccarthy** [comment]
Would still love to help out with this -- is there a plugin other than Vertica that would be a better analogue to Redshift?

**Comment by jmccarthy** [comment]
Working now, PR incoming

**Comment by camsaul** [comment]
Let's leave this open until we get a PR merged to implement it
