### ISSUE TITLE
Add foreign key to title on x-ray

### ISSUE THREAD

**Issue by RobertLowe** [metabase/metabase#9696]
### Feature request
Presently for some/all of the x-ray charts the title's are generated in the format of "`<collection>` per `<key>`"

Like so:
![Screen Shot 2019-04-05 at 4 04 14 AM](https://user-images.githubusercontent.com/601141/55613434-af390900-5758-11e9-8584-1564326b0dc1.png)

I propose we include the foreign key from the parent to distinguish which information the chart is generated for.

Like so:

![Screen Shot 2019-04-05 at 4 05 11 AM](https://user-images.githubusercontent.com/601141/55613633-338b8c00-5759-11e9-800f-a181d1cb1da3.png)

This is important when you have a collection that has multiple references to a target collection (ex: `draftBookId` and` bookId`) or when the target collection's key match (ex: collection a with `chapterName`, and collection b `chapterName`)

**Comment by sbelak** [comment]
Implemented in #10731. Thanks!
