### ISSUE TITLE
Metabase Docker Starts Super Slow (10+min)

### ISSUE THREAD

**Issue by renruyi** [metabase/metabase#9698]
I started metabase in a docker container on a google cloud n1-standard-2 instance, connecting to a google cloud postgres and it takes 10+ min. 
Here are the metabase logs:

> 04-05 16:26:10 [1mINFO metabase.util[0m :: Loading Metabase...
> 04-05 16:26:10 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 1.6 GB
> 04-05 16:26:16 [1mINFO util.encryption[0m :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
>  For more information, see https://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
> 04-05 16:26:22 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :sql[0m  🚚
> 04-05 16:43:16 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
> 04-05 16:43:17 [1mINFO metabase.server[0m :: Launching Embedded Jetty Webserver with config: 
>  {:port 3000, :host "0.0.0.0"}
> 
> 04-05 16:43:17 [1mINFO metabase.core[0m :: Starting Metabase version v0.32.1 (0b14a7e release-0.32.0) ...
> 04-05 16:43:17 [1mINFO metabase.core[0m :: System timezone is 'GMT' ...
> 04-05 16:43:17 [1mINFO metabase.plugins[0m :: [35mLoading plugins in /plugins...[0m
> [32mExtract file /modules/vertica.metabase-driver.jar -> /plugins/vertica.metabase-driver.jar took 18 ms[0m
> [32mExtract file /modules/sqlserver.metabase-driver.jar -> /plugins/sqlserver.metabase-driver.jar took 48 ms[0m
> [32mExtract file /modules/sqlite.metabase-driver.jar -> /plugins/sqlite.metabase-driver.jar took 112 ms[0m
> [32mExtract file /modules/sparksql.metabase-driver.jar -> /plugins/sparksql.metabase-driver.jar took 572 ms[0m
> [32mExtract file /modules/snowflake.metabase-driver.jar -> /plugins/snowflake.metabase-driver.jar took 120 ms[0m
> [32mExtract file /modules/redshift.metabase-driver.jar -> /plugins/redshift.metabase-driver.jar took 19 ms[0m
> [32mExtract file /modules/presto.metabase-driver.jar -> /plugins/presto.metabase-driver.jar took 2 ms[0m
> [32mExtract file /modules/oracle.metabase-driver.jar -> /plugins/oracle.metabase-driver.jar took 1 ms[0m
> [32mExtract file /modules/mongo.metabase-driver.jar -> /plugins/mongo.metabase-driver.jar took 53 ms[0m
> [32mExtract file /modules/googleanalytics.metabase-driver.jar -> /plugins/googleanalytics.metabase-driver.jar took 6 ms[0m
> [32mExtract file /modules/google.metabase-driver.jar -> /plugins/google.metabase-driver.jar took 25 ms[0m
> [32mExtract file /modules/druid.metabase-driver.jar -> /plugins/druid.metabase-driver.jar took 5 ms[0m
> [32mExtract file /modules/bigquery.metabase-driver.jar -> /plugins/bigquery.metabase-driver.jar took 3 ms[0m
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :mongo...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :mongo[0m  🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sqlserver...[0m
> 04-05 16:43:18 [1mDEBUG plugins.classloader[0m :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@9a38c90...
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :sql-jdbc[0m (parents: :sql) 🚚
> [32mLoad driver :sql-jdbc took 73 ms[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :sqlserver[0m (parents: #{:sql-jdbc}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :google...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :google[0m  🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :snowflake...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :snowflake[0m (parents: #{:sql-jdbc}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :redshift...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :postgres[0m (parents: :sql-jdbc) 🚚
> [32mLoad driver :postgres took 34 ms[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :redshift[0m (parents: #{:postgres}) 🚚
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: [31mMetabase cannot initialize plugin Metabase Oracle Driver due to required dependencies.[0m Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.
> 
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: [33mPlugins with unsatisfied deps: ["Metabase Oracle Driver"][0m
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :hive-like...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered abstract driver :hive-like[0m (parents: #{:sql-jdbc}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sparksql...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :sparksql[0m (parents: #{:hive-like}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :sqlite...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :sqlite[0m (parents: #{:sql-jdbc}) 🚚
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :bigquery...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :bigquery[0m (parents: #{:sql :google}) 🚚
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: [31mMetabase cannot initialize plugin Metabase Vertica Driver due to required dependencies.[0m Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.
> 
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: [33mPlugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Oracle Driver"][0m
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
> 04-05 16:43:18 [1mINFO plugins.dependencies[0m :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :googleanalytics...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :googleanalytics[0m (parents: #{:google}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :presto...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :presto[0m (parents: #{:sql}) 🚚
> 04-05 16:43:18 [1mINFO plugins.lazy-loaded-driver[0m :: [35mRegistering lazy loading driver :druid...[0m
> 04-05 16:43:18 [1mINFO metabase.driver[0m :: [34mRegistered driver :druid[0m  🚚
> 04-05 16:43:19 [1mINFO metabase.driver[0m :: [34mRegistered driver :h2[0m (parents: :sql-jdbc) 🚚
> [32mLoad driver :h2 took 28 ms[0m
> 04-05 16:43:19 [1mINFO metabase.driver[0m :: [34mRegistered driver :mysql[0m (parents: :sql-jdbc) 🚚
> [32mLoad driver :mysql took 34 ms[0m
> 04-05 16:43:19 [1mINFO metabase.core[0m :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
> 04-05 16:43:19 [1mINFO metabase.db[0m :: [36mVerifying postgres Database Connection ...[0m
> 04-05 16:43:19 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql...[0m
> 04-05 16:43:19 [1mINFO metabase.driver[0m :: [33mInitializing driver :sql-jdbc...[0m
> 04-05 16:43:19 [1mINFO metabase.driver[0m :: [33mInitializing driver :postgres...[0m
> 04-05 16:43:19 [1mINFO metabase.db[0m :: Verify Database Connection ...  ✅
> 04-05 16:43:19 [1mINFO metabase.db[0m :: Running Database Migrations...
> 04-05 16:43:19 [1mINFO metabase.db[0m :: Setting up Liquibase...
> 04-05 16:43:20 [1mINFO metabase.db[0m :: Liquibase is ready.
> 04-05 16:43:20 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
> 04-05 16:43:22 [1mINFO metabase.db[0m :: Database Migrations Current ...  ✅
> 04-05 16:43:23 [1mINFO db.migrations[0m :: Running all necessary data migrations, this may take a minute.
> 04-05 16:43:23 [1mINFO db.migrations[0m :: Finished running data migrations.
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.activity-feed[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.dependencies[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.driver-notifications[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.last-login[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.metabot-lifecycle[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.notifications[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.revision[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.sync-database[0m 👂
> 04-05 16:43:23 [1mINFO metabase.events[0m :: Starting events listener: [34mmetabase.events.view-log[0m 👂
> 04-05 16:43:24 [1mINFO task.send-pulses[0m :: Sending scheduled pulses...
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mSyncDatabases[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mCheckForNewVersions[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mSendAnonymousUsageStats[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mSendAbandomentEmails[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mSendPulses[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mSendFollowUpEmails[0m 📆
> 04-05 16:43:24 [1mINFO metabase.task[0m :: Initializing task [32mTaskHistoryCleanup[0m 📆
> 04-05 16:43:24 [1mINFO metabase.core[0m :: Metabase Initialization COMPLETE
> 

Here is docker inspect result:
```javascript
[
    {
        "Id": "eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52",
        "Created": "2019-04-05T16:26:06.217204199Z",
        "Path": "/app/run_metabase.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 22580,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-04-05T16:26:06.78477553Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:c2fd5191f018da72bf8be40f1b49c57cd72a65fff5f54cfb960006e35bb7689c",
        "ResolvConfPath": "/var/lib/docker/containers/eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52/hostname",
        "HostsPath": "/var/lib/docker/containers/eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52/hosts",
        "LogPath": "/var/lib/docker/containers/eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52/eaacfff2d2878abe524cb5ddadf103bb3047d5edad7631ad842ac5561cdf3a52-json.log",
        "Name": "/metabase",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/ruyiscoutandcellar/metabase-data:/metabase-data"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/078d10f55c2385bd127e694866f25611cdd1a11da88acab3c975a946e98a0009-init/diff:/var/lib/docker/overlay2/e050470e1631b7ab66e83f54101cee44f48b0a56a6e66fbcbf4c36b175a0b73d/diff:/var/lib/docker/overlay2/ff068f37cfee99bd562b1880b71816b2dc466e76f16ccdf680be0cdb4f0b1275/diff:/var/lib/docker/overlay2/44eecee974909c0e4b33e1b07a9aab22db7e380957773f74eb33f9e9d8dc4bab/diff:/var/lib/docker/overlay2/ead23659f0253c43a0d7ffe4093bef379bf2349b34286568c4ca1237fc056c74/diff:/var/lib/docker/overlay2/45bc5f4462a06a5a785f51937cd6a850d43f6383e6ef97cab1f1b58709264b36/diff:/var/lib/docker/overlay2/dfdfd6604b7afb45c15f4f72491499c9df4d4865b2f4145382ee89747aea0bcb/diff:/var/lib/docker/overlay2/2e18c6260ca68ac0dba8659cbd8a3b9f4257d43ea545c64112547de5d250bde5/diff:/var/lib/docker/overlay2/f3d776afe8f235bf4eba87e254ec08d561ac59098588d06663debe6bba58e5b6/diff:/var/lib/docker/overlay2/66e247b70427e993598489a20e97279802eb5580884f60af315bac382a917d1f/diff",
                "MergedDir": "/var/lib/docker/overlay2/078d10f55c2385bd127e694866f25611cdd1a11da88acab3c975a946e98a0009/merged",
                "UpperDir": "/var/lib/docker/overlay2/078d10f55c2385bd127e694866f25611cdd1a11da88acab3c975a946e98a0009/diff",
                "WorkDir": "/var/lib/docker/overlay2/078d10f55c2385bd127e694866f25611cdd1a11da88acab3c975a946e98a0009/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/ruyiscoutandcellar/metabase-data",
                "Destination": "/metabase-data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "eaacfff2d287",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MB_DB_FILE=/metabase-data/metabase.db",
                "MB_DB_CONNECTION_URI=<redacted>",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
                "JAVA_VERSION=8u191",
                "JAVA_ALPINE_VERSION=8.191.12-r0",
                "FC_LANG=en-US",
                "LC_CTYPE=en_US.UTF-8"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "metabase/metabase",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/app/run_metabase.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "793767046b5d5505280cb9483424c86226e61693d167ee27bf5ef710ff30ec76",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/793767046b5d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "0791ca6a9705c96c49c904d24a60a9168e2c34619da2541231cfedceaf7db7e6",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "0fa12cc252fff095ab2d8e7b8082bd135c024fba482198310f76dc598a050dc3",
                    "EndpointID": "0791ca6a9705c96c49c904d24a60a9168e2c34619da2541231cfedceaf7db7e6",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

**Comment by salsakran** [comment]
`
04-05 16:26:22 �[1mINFO metabase.driver�[0m :: �[34mRegistered abstract driver :sql�[0m 🚚
04-05 16:43:16 �[1mINFO metabase.core�[0m :: Starting Metabase in STANDALONE mode
`

are the relevant lines that point out where time is being spent.

**Comment by giovannibonetti** [comment]
Same thing here. I'm running Metabase on a compute engine instance from Google Cloud and the startup time is huge even after upgrading to Metabase 0.32.6:

```
05-09 14:20:11 INFO metabase.util :: Loading Metabase...
05-09 14:20:11 INFO metabase.util :: Maximum memory available to JVM: 411.8 MB
05-09 14:20:22 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
05-09 14:20:32 INFO metabase.driver :: Registered abstract driver :sql  🚚
05-09 14:46:24 INFO metabase.core :: Starting Metabase in STANDALONE mode
```

**Comment by camsaul** [comment]
@salsakran the "registered driver" line pops up when it initiailizes the `metabase.driver.sql` namespace. In between that and the "Starting Metabase" it's loading all of our other namespaces. That's where all the time is being spent

**Comment by robguthrie** [comment]
I'm having the same problem. I did not used to be this way, I'm also seeing postgres reject connections by the time it starts, I wonder if it is related.

**Comment by robguthrie** [comment]
Are other people also finding that when it does start, it cannot connect to postgresql?

**Comment by flamber** [comment]
@robguthrie Which version of Metabase and Postgres? Can you provide the logs? Is it just a regular setup or can you provide steps-to-reproduce?

**Comment by robguthrie** [comment]
Hi, I'm running 

metabase:latest 
postgres:11.3
Docker version 18.06.1-ce
docker-compose version 1.22.0

I've noticed that it can take up to 15 minutes from the :sql driver line to the next stuff. 

```
# docker-compose logs -f
Attaching to nginx-proxy-le, nginx-proxy, metabase_postgres_1, metabase_metabase_1
postgres_1     | 2019-05-13 22:18:42.372 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
nginx-proxy    | Custom dhparam.pem file found, generation skipped
nginx-proxy    | forego     | starting dockergen.1 on port 5000
postgres_1     | 2019-05-13 22:18:42.372 UTC [1] LOG:  listening on IPv6 address "::", port 5432
nginx-proxy-le | Info: Custom Diffie-Hellman group found, generation skipped.
nginx-proxy    | forego     | starting nginx.1 on port 5100
metabase_1     | Picked up JAVA_TOOL_OPTIONS: -Xmx6g
metabase_1     | 05-13 22:18:42 INFO metabase.util :: Loading Metabase...
metabase_1     | 05-13 22:18:42 INFO metabase.util :: Maximum memory available to JVM: 5.3 GB
metabase_1     | 05-13 22:18:47 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓 
metabase_1     |  For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
metabase_1     | 05-13 22:18:50 INFO metabase.driver :: Registered abstract driver :sql  🚚
metabase_1     | 05-13 22:31:33 INFO metabase.core :: Starting Metabase in STANDALONE mode
nginx-proxy    | dockergen.1 | 2019/05/13 22:18:42 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
```

note the timestamp on the last 2 lines.

It's not the database or a network/DNS timeout issue, as I've been waiting this long each time to diagnose why it wasn't connecting (this was compounding another problem). Now I've fixed that I'm still waiting all this time for startup. Otherwise it's performing really well.

**Comment by giovannibonetti** [comment]
Running the latest version (`0.32.8`) fixed the problem here! 😀 
It now starts in a few seconds! 🚀 
```
05-14 20:42:43 INFO metabase.util :: Loading Metabase...
05-14 20:42:43 INFO metabase.util :: Maximum memory available to JVM: 411.8 MB
05-14 20:42:54 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
05-14 20:43:05 INFO metabase.driver :: Registered abstract driver :sql  🚚
05-14 20:43:14 INFO metabase.core :: Starting Metabase in STANDALONE mode
05-14 20:43:14 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

05-14 20:43:14 INFO metabase.core :: Starting Metabase version v0.32.8 (16be46d release-0.32.x) ...
05-14 20:43:14 INFO metabase.core :: System timezone is 'GMT' ...
```

**Comment by robguthrie** [comment]
yep. can confirm it's fixed for me too.

**Comment by renruyi** [comment]
fixed for me too. thanks guys!

**Comment by UsmanYasin** [comment]
Let me add my two cents for somebody who is still facing slow startup(10-60 minutes). Unfortunately, the startup is still slow after upgrading to 0.32.8 for me and shows very strange behaviour. The good news is after battling for 2 days, I have finally found the problem and the workaround.

**Environments tested:** GCE(Ubuntu 18.04)/GCE(docker)/GKE/Windows 10/Windows 10(Docker)
**Problematic Environments:** GCE(Ubuntu 18.04)/GCE(docker)/GKE
**System/VM Resources:** 4 CPU,15GB RAM / 2CPU,8GB RAM 
**Affected Versions:** v0.32.x
**Strange Startup Behaviour:** On a new vm, the first time i run metabase(v0.32.x) using jar or docker the startup is very quick(~1-2 mins). Every subsequent fresh run(running a second docker container on different port/stop existing metabase instance, delete db and plugin folder and run metabase again) takes almost 10-60 minutes to startup. On my local windows machine, this behaviour is not reproduced and everything works perfectly. On metabase(v0.31.2), this behaviour is not reproduced and everything works perfectly.
**Root Cause:** There is this dependency buddy.core.codecs referenced in [https://github.com/metabase/metabase/blob/master/src/metabase/util/embed.clj](url) which is gnerating random numbers and is using java.security.SecureRandom which relies on /dev/random and /dev/urandom on linux distros which was resulting in entropy exhaustion(cat /proc/sys/kernel/random/entropy_avail was less than 100) and was blocking the metabase application until the entropy is refilled to a certain level. Normally entropy is based on keyboard strokes, mouse movement etc. but those peripherals not being available on server can result in less entropy generation, quick depletion and slow refill.
**Workaround:** The workaround I have used for now is to install **haveged** as suggested by digitalocean [https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged](url). Since then metabase is working perfectly.

Frankly speaking, I don't consider this workaround a bad one but if there is any better solution, I'd love to help in any way possible :)(Emojis aren't turned off :p).

**Comment by ShalbafZadeh** [comment]
@UsmanYasin after pulling my hair for two days i came across your comment and fixed my issue in a blink
i can't express how much i'm grateful for you help

**Comment by tlrobinson** [comment]
@camsaul is there any way we can detect entropy exhaustion and warn the admin in the logs?

**Comment by camsaul** [comment]
Was going to reopen this to address the entropy issue but that is actually a different problem than the one originally fixed here so I'll open a new issue so we don't get things mixed up too much and confusing WRT when each issue got fixed
