### ISSUE TITLE
Can't filter on custom fields

### ISSUE THREAD

**Issue by sbelak** [metabase/metabase#9701]
Steps to repo: in Sample dataset create a custom field (eg. discount * 1.2) and try filtering on it. It will get shown in the dropdown, but nothing happens when you click on it.

**Comment by flamber** [comment]
I'm pretty sure it's a duplicate of #8382 - do you get the `TypeError: field.operator is not a function` ?

**Comment by sbelak** [comment]
Indeed. 

I'm deeply impressed by your encyclopaedic knowledge of our issues
