### ISSUE TITLE
X-Frame-Options - Subdomain

### ISSUE THREAD

**Issue by fontainio** [metabase/metabase#9709]
Related to https://github.com/metabase/metabase/issues/2721 

But in my case it's for another subdomain, which i don't think is a security issue.

Metabase is running on metabase.domain.com and i have my saas running on saas.domain.com 
Same parent domain, different subdomain.
I want to iframe metabase.domain.com in my saas.

Got an expected error : 
Refused to display 'metabase.domain.com' in a frame because it set 'X-Frame-Options' to 'deny'.

How to add a specific x-frame-options allow-from ? 

Thank you

**Comment by flamber** [comment]
Hi @octadv 

Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

`X-Frame-Options` is an outdated header. You should use `Content-Security-Policy` and specifically the `frame-ancestors` directive.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

You would have to either use a reverse proxy (Nginx, Apache, ...) to modify the CSP header or compile your own version Metabase with modified headers.

**Comment by camsaul** [comment]
@octadv @flamber One of the benefits of `X-Frame-Options` is that it's supported by lots of browsers including older ones vs the CSP `frame-ancestors` which unfortunately isn't supported by IE or Edge Mobile. 

@octadv like @flamber suggested I think the quickest route is either doing your own build or tweaking a proxy. If you do a custom build the line to change is here https://github.com/metabase/metabase/blob/master/src/metabase/middleware/security.clj#L85

**Comment by samz406** [comment]
> @octadv @flamber One of the benefits of `X-Frame-Options` is that it's supported by lots of browsers including older ones vs the CSP `frame-ancestors` which unfortunately isn't supported by IE or Edge Mobile.
> 
> @octadv like @flamber suggested I think the quickest route is either doing your own build or tweaking a proxy. If you do a custom build the line to change is here https://github.com/metabase/metabase/blob/master/src/metabase/middleware/security.clj#L85

I never use cj ，can you  give me  a example how modify it? thanks !

**Comment by flamber** [comment]
Closing, since this is available via FullApp embedding:
https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html
