### ISSUE TITLE
Outdated "Metabase does not provide automated support for migrating data from one application database to another" in docs

### ISSUE THREAD

**Issue by perrinjerome** [metabase/metabase#9713]
In [Configuring the Metabase Application Database](https://github.com/metabase/metabase/blob/da11b552b8b24a8549a59918515c1cffdb6bb2d7/docs/operations-guide/start.md) section of the operation guides, there's a note warning that migrating from H2 to Posgres needs to dump then load "manually":

https://github.com/metabase/metabase/blob/da11b552b8b24a8549a59918515c1cffdb6bb2d7/docs/operations-guide/start.md#L86

and later there's a [Migrating from using the H2 database to MySQL or Postgres](https://github.com/metabase/metabase/blob/da11b552b8b24a8549a59918515c1cffdb6bb2d7/docs/operations-guide/start.md#migrating-from-using-the-h2-database-to-mysql-or-postgres) section describing an *automated* procedure for this:

https://github.com/metabase/metabase/blob/da11b552b8b24a8549a59918515c1cffdb6bb2d7/docs/operations-guide/start.md#L145-L171

It's a bit self-contradictory, I feel the first note could have been removed when the docs were updated to introduce the new `load-from-h2` command in https://github.com/metabase/metabase/pull/1771 .

**Comment by camsaul** [comment]
Fixed by #9724
