### ISSUE TITLE
get sum data when column contain null

### ISSUE THREAD

**Issue by wm9947** [metabase/metabase#9734]
my database: postgreSQL
Metabase version: 0.31.2

My tables contain string data which imported from csv file.
I try to sum and average of the column which contain null data; these are converted data type by Data Model.

org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying * integer Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 376

Some of them, I changed value null to 0: it works sum function.
But one of the contain lots of null data which cannot modify manually.

Is there any solution such as use format option at the Data Model or by the custom expression?

Thanks

**Comment by flamber** [comment]
Hi @wm9947 
It sounds like your table structure is wrong, if you're using `character varying` for the column. You need to use a number based type.

**Comment by salsakran** [comment]
We don't support casting in the tool itself, we assume you have a mostly sensible schema. If it's char varying, we respect that.
