### ISSUE TITLE
use date formatting yyyy

### ISSUE THREAD

**Issue by wm9947** [metabase/metabase#9735]
When the date column is not fit as a full date, I think it is not possible to group by date format.

org.postgresql.util.PSQLException: ERROR: date/time field value out of range: "201801" Hint: Perhaps you need a different "datestyle" setting.

When I use normal timestamp or date data such as 20180101, it works as I want.

Is there any possible way "201801" use as a date data type?

Thanks.

**Comment by flamber** [comment]
Hi @wm9947 
You are referencing an error in Postgres. Can you please give more context.
And please use the forum for questions and troubleshooting: https://discourse.metabase.com/
