### ISSUE TITLE
Can't Update Value of Google Auth client ID

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9743]
I believe this is still a problem on 0.32.3, not 100% sure because I can't build the FE on Linux because of #9742, so mine is a little out of date (not sure exactly how out-of-date), but AFAIK this page hasn't changed in a long time

In the admin panel I set up Google Auth and put in a client ID. I wanted to test a different Client ID and put a new value in, but saving it failed: the FE client is making a bad request.

It's making this request:

```json
PUT /api/setting
{"value":"updated-token"}
```

The API is returning a 500 "the Setting 'value' does not exist" response, although it should probably be a 400 response instead. The correct way to update the Setting would be to either do:

(set one setting endpoint)
```json
PUT /api/setting/google-auth-client-id
{"value": "new-value"}
```

*or*

(set multiple settings endpoint)
```json
PUT /api/setting/
{"google-auth-client-id": "new-value"}
```

It looks like it's trying to use the former but forgetting to include the name of the Setting as part of the URL. Interestingly enough I was able to set the Setting for the first time without problem.

Another issue is the error message pops up on the top of the screen:

![image](https://user-images.githubusercontent.com/1455846/55845985-e7de3700-5af8-11e9-8250-1c02bddb7319.png)

**Comment by camsaul** [comment]
Another issue is the button changes to "Changes Saved!" implying the save were successful and is grayed out meaning I can't retry the request unless I refresh the browser.

IMO Save button should only changed to "Saved!"/be grayed out if the API request is successful, not on error responses

**Comment by salsakran** [comment]
prioritizing this highly because it makes debugging especially challenging.

**Comment by paulrosenzweig** [comment]
Looks like this is fixed on master:

![image](https://user-images.githubusercontent.com/691495/62496717-d1df3b00-b7a7-11e9-9bf1-09aaba40b1c4.png)
