### ISSUE TITLE
Need better instructions for setting up Google Auth

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9744]
Right now we just send people to a Google page telling you how to set up Google Auth for a web page as opposed to having instructions for Metabase specifically. I think the Google's instructions used to be a littler more relevant to the steps you had to take for Metabase but the page they have now really doesn't apply much to Metabase anymore so we should write up specific steps in our own docs and point people there instead.

**Comment by hodbadger** [comment]
Can someone who hasn't contributed to the project so far help? If yes, I'd like to.

**Comment by salsakran** [comment]
@hodbadger yes, please!

**Comment by hodbadger** [comment]
I'm on it.
