### ISSUE TITLE
share a map chart unauthorized

### ISSUE THREAD

**Issue by fmq2008** [metabase/metabase#9746]
I share a question with Chinese map chart . It appears unauthorized.  api/geojson , 401 Unauthorized

**Comment by camsaul** [comment]
Version?

**Comment by fmq2008** [comment]
v0.32.1

**Comment by fmq2008** [comment]
![image](https://user-images.githubusercontent.com/49466276/55849676-1c4b0500-5b84-11e9-9a01-f070deed2a3e.png)  when i share to others, it doesn't show with problem api/geojson , 401 Unauthorized

**Comment by fmq2008** [comment]
![image](https://user-images.githubusercontent.com/49466276/55849790-70ee8000-5b84-11e9-906e-e9610d9b8297.png) . And i want to show name, not code,how to do ?

**Comment by fmq2008** [comment]
i find a method  how to show name. Share problem still needs for help.

**Comment by camsaul** [comment]
Duplicate of #6593
