### ISSUE TITLE
Last month double in timeseries

### ISSUE THREAD

**Issue by DannyK85** [metabase/metabase#9752]
Since version 0.32.1 I am seeing the last month, or other date grouping, in a timeseries X-axis chart, bars - lines - etc, displayed double. When switching to ordinal it shows the correct breakdown.
![Screenshot 2019-04-09 at 16 04 53](https://user-images.githubusercontent.com/5367750/55860022-96bf5900-5b73-11e9-935a-86cef2926eb5.png)
In the screenshot you can see March displayed twice when the latter should be April.

Ordinal series:
![Screenshot 2019-04-10 at 09 35 12](https://user-images.githubusercontent.com/5367750/55860205-fddd0d80-5b73-11e9-931a-a63c30897d1c.png)

**Comment by flamber** [comment]
Hi @DannyK85 
There's a couple of issues open about very similar issue - #5916 and #5246 and #4802 
Does one of them look like a duplicate, then please close this issue and upvote the other by clicking :+1:

**Comment by DannyK85** [comment]
Seems like the platform it's happening when the timezone switched from CET to CEST (summertime).
When changing the report timezone to UTC the dates don't line up.
![Screenshot 2019-04-10 at 10 46 51](https://user-images.githubusercontent.com/5367750/55865070-f91d5700-5b7d-11e9-8933-385225732a53.png)

Upvoting #5246 and closing this issue
