### ISSUE TITLE
Field Filter variable disappears for text columns

### ISSUE THREAD

**Issue by Nikos410** [metabase/metabase#9754]
Hey there!

We just noticed that it is not possible to use a field filter for a text field with a SQLServer database. Normal text variables and field filters for fields with other datatypes like dates or numbers work fine, but if we select a text field, the input for the filter disappears: https://streamable.com/bi26w

### Information
- My browser and the version: Firefox 66.0.2
- My operating system: Windows
- My database: SQLServer
- Metabase version: 0.32.4
- Metabase hosting environment: Linux / Opensuse
- Metabase internal database: Postgres

### How to reproduce:
- Ask a new native SQL question for a SQLServer Database
- Add a variable
- Set this variable to be a field filter
- Select a text field

Expected behaviour: The input for the filter appears above the question
Actual behaviour: The input does not appear / disappears

**Comment by flamber** [comment]
Hi @Nikos410 
Notice that the Field Widget Type disappears, when you select one of the fields. That's usually caused by a wrong Field Type in your Data Model. What is the type?
Settings > Admin > Data Model > (database) > (table) > (field) :gear:

**Comment by Nikos410** [comment]
Hey, thanks for your quick response! 

We just played around a bit, and it seems re-scanning  the database schema fixed this. When we first tried, the field had no special type. Now, after re-scanning the field has the special type "Category" and we can use this field in the field filter.

Thanks!
