### ISSUE TITLE
Hidden tables show in "our data" page when it is marked as technical/cruft

### ISSUE THREAD

**Issue by joeirimpan** [metabase/metabase#9759]
Browser: Firefox Quantum (66.0.1)
OS: Linux Manjaro
Databases: Postgres 11.2
Metabase version: 31.2
Metabase hosting env: Ubuntu 18.04.1 LTS
Internal db: H2

### Steps to reproduce
1. Change visibility of a table to hidden of a data model under admin.
2. It won't appear under "Our Data" page now.
3. Change "Why hide" to technical/cruft.
4. Now, it appears in "Our Data" page.

https://github.com/metabase/metabase/pull/8831 should respect technical/cruft visibility type.

**Comment by anthonysexton** [comment]
I am using Metabase v0.32.8 and this still seems to be happening?

**Comment by flamber** [comment]
@anthonysexton It is part of 0.32.9

**Comment by anthonysexton** [comment]
Oh well that will get you. When I looked at the merge data/release I
thought it was there. Sorry.

**Comment by janethuyx** [comment]
this is still a problem even in the new version, when connecting to redshift, the hidden table does not work for "our data"

**Comment by salsakran** [comment]
@janethuyx 
I just checked our latest version, and I can't reproduce this. 

Can you confirm which version you're on? Is this a table or a view that still shows up? Also are you running Metabase in a single server or multiple-server configuration?

**Comment by janethuyx** [comment]
dev version: v0.33.0
production version: v1.1.5
both version have the problem
we are running Metabase in a single server.
These are all tables written in our AWS redshift data warehouse.
for v1.1.5: the hidden tables still show in "our data" for both "Sample H2 dataset" and "AWS Redshift".
for v0.33.0, the hidden tables do not show in "our data" for "Sample H2 dataset", but still show in "our data" for "AWS Redshift"

**Comment by RMMSecurity** [comment]
@janethuyx double check the production version you're using. Unless you're from the future I don't think we're quite at v1 yet.  😅

**Comment by flamber** [comment]
@RMMSecurity I guess @janethuyx is using the [Enterprise Edition](https://metabase.com/enterprise/) (currently at [1.1.6](https://hub.docker.com/r/metabase/metabase-enterprise/tags)) in production.

**Comment by janethuyx** [comment]
@RMMSecurity @flamber yes, I am using the Enterprise Edition 1.1.6, sorry that I did not explain the detail, thank you for clarifying!

**Comment by lindsay-stevens** [comment]
This happens in v1.34.1 for the Browse Data area and the Native Query Data Reference pane.

I think a key step for reproduction is having a database with multiple schemas. Hiding tables seems to work correctly on the Sample Dataset which only has one schema (see below image).

In all cases the API responses include the hidden tables, whether visibility_type = hidden, cruft, or technical. Browse Data gets table info from `/api/database/:id/schema/:schema`, and the Question Builders/Editor use `/api/database?include_tables=true&include_cards=true`.

![image](https://user-images.githubusercontent.com/6345269/74810679-07163980-5344-11ea-8b31-147484e921a5.png)

**Comment by flamber** [comment]
@lindsay-stevens Thank you. It was the multi-schema that did the trick.

Reproduced on stats by trying to hide a table in a multi-schema database (27). Cannot reproduce on Sample Dataset.
Not sure if #9781 might be related.

**Comment by dacort** [comment]
Bumping up the priority as it seems like we have a regression in 0.35 where this is reproducible on the sample dataset again.
