### ISSUE TITLE
how to set drop-down box single selection

### ISSUE THREAD

**Issue by fmq2008** [metabase/metabase#9760]
Metabase version: 0.32.
![image](https://user-images.githubusercontent.com/49466276/55929152-043fb800-5c4e-11e9-9224-5aafac61e83a.png)
How to set drop-down box single selection, no need multiple selection. Thanks

**Comment by flamber** [comment]
Hi @fmq2008 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Please close this issue and upvote #7605 by clicking :+1:

**Comment by mazameli** [comment]
Duplicate of #7605
