### ISSUE TITLE
dockerized app cant connect to mongodb

### ISSUE THREAD

**Issue by ajitkhatke** [metabase/metabase#9761]
when i try to connect mongo db from dockerized container , it giver connection refused error. but when i try to connect mongo server from local app it connects  fine.
the error i get is

digital_act_database_config | /app/node_modules/mongodb/lib/mongo_client.js:421
digital_act_database_config |           throw err
digital_act_database_config |           ^
digital_act_database_config | MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
digital_act_database_config |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
digital_act_database_config |     at Pool.emit (events.js:193:13)
digital_act_database_config |     at Pool.EventEmitter.emit (domain.js:481:20)
digital_act_database_config |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
digital_act_database_config |     at Object.onceWrapper (events.js:281:20)
digital_act_database_config |     at Connection.emit (events.js:193:13)
digital_act_database_config |     at Connection.EventEmitter.emit (domain.js:481:20)
digital_act_database_config |     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
digital_act_database_config |     at Object.onceWrapper (events.js:281:20)
digital_act_database_config |     at Socket.emit (events.js:193:13)
digital_act_database_config |     at Socket.EventEmitter.emit (domain.js:481:20)
digital_act_database_config |     at emitErrorNT (internal/streams/destroy.js:91:8)
digital_act_database_config |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
digital_act_database_config |     at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by flamber** [comment]
Hi @ajitkhatke 
Which version of Metabase?
That error doesn't look like it's coming from Metabase.

**Comment by ajitkhatke** [comment]
its notr a problem of metabase. the mongo server is up and running. it responds when i try to establish connection from local applications. it just denies request of docker containers. is there any kind of connection we have to esatablish to make them communicate.

**Comment by ajitkhatke** [comment]
> Hi @ajitkhatke
> Which version of Metabase?
> That error doesn't look like it's coming from Metabase.

i don't think i'm using metabase. if mongo db fetches it by default, then maybe. Actually i'm beginner with mongo db itself.

**Comment by flamber** [comment]
@ajitkhatke 
If you need help with MongoDB, then ask in their community:
https://www.mongodb.com/community-support-resources
And please close this issue :+1:
