### ISSUE TITLE
metabase 0.32.4 Dashboard with BigQuery error

### ISSUE THREAD

**Issue by attsn** [metabase/metabase#9769]
Dashboards with BigQuery database failing in Metabase 0.32.2/3/4.
Same dashboards works fine in 0.31.2

For upgrade we have just launched metabase application with latest 0.32.2/0.32.3/0.32.4 jar file.
Please let us know if we are missing something ?

error message - "Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion"

PFB the complete error message for your reference -

root@metabase-main:/apps/java# /usr/bin/java -jar /apps/java/metabase-0.32.4.jar
log4j:ERROR Could not find value for key log4j.appender.metabase
log4j:ERROR Could not instantiate appender named "metabase".
04-12 07:11:42 INFO metabase.util :: Loading Metabase...
04-12 07:11:42 INFO metabase.util :: Maximum memory available to JVM: 14.7 GB
04-12 07:11:44 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
04-12 07:11:46 INFO metabase.driver :: Registered abstract driver :sql 🚚
04-12 07:11:49 INFO metabase.core :: Starting Metabase in STANDALONE mode
04-12 07:11:49 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
{:port 3000}

04-12 07:11:49 INFO metabase.core :: Starting Metabase version v0.32.4 (f4dc152 release-0.32.0) ...
04-12 07:11:49 INFO metabase.core :: System timezone is 'Etc/UTC' ...
04-12 07:11:49 INFO metabase.plugins :: Loading plugins in /apps/java/plugins...
04-12 07:11:50 DEBUG plugins.classloader :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@6cd27d52...
04-12 07:11:50 INFO plugins.classloader :: Added URL file:/apps/java/plugins/metabase-sparksql-deps-1.2.1.spark2-standalone.jar to classpath
04-12 07:11:50 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-12 07:11:50 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
04-12 07:11:50 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
04-12 07:11:50 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

04-12 07:11:50 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
04-12 07:11:50 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver" "Metabase Oracle Driver"]
04-12 07:11:50 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-12 07:11:50 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
04-12 07:11:50 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver" "Metabase Google Analytics Driver" "Metabase Oracle Driver"]
04-12 07:11:50 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

04-12 07:11:50 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
04-12 07:11:50 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver" "Metabase Google Analytics Driver" "Metabase Oracle Driver" "Metabase Vertica Driver"]
04-12 07:11:50 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
04-12 07:11:50 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: :sql) 🚚
Load driver :sql-jdbc took 40 ms
04-12 07:11:50 INFO metabase.driver :: Registered driver :sqlserver (parents: #{:sql-jdbc}) 🚚
04-12 07:11:50 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
04-12 07:11:51 INFO metabase.driver :: Registered driver :postgres (parents: :sql-jdbc) 🚚
Load driver :postgres took 20 ms
04-12 07:11:51 INFO metabase.driver :: Registered driver :redshift (parents: #{:postgres}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
04-12 07:11:51 INFO metabase.driver :: Registered abstract driver :hive-like (parents: #{:sql-jdbc}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
04-12 07:11:51 INFO metabase.driver :: Registered driver :sparksql (parents: #{:hive-like}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
04-12 07:11:51 INFO metabase.driver :: Registered driver :sqlite (parents: #{:sql-jdbc}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
04-12 07:11:51 INFO metabase.driver :: Registered driver :mongo 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
04-12 07:11:51 INFO metabase.driver :: Registered driver :snowflake (parents: #{:sql-jdbc}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
04-12 07:11:51 INFO metabase.driver :: Registered driver :presto (parents: #{:sql}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
04-12 07:11:51 INFO metabase.driver :: Registered driver :druid 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
04-12 07:11:51 INFO metabase.driver :: Registered abstract driver :google 🚚
04-12 07:11:51 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-12 07:11:51 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-12 07:11:51 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase Google Analytics Driver" "Metabase BigQuery Driver"]
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
04-12 07:11:51 INFO metabase.driver :: Registered driver :googleanalytics (parents: #{:google}) 🚚
04-12 07:11:51 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
04-12 07:11:51 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google}) 🚚
04-12 07:11:51 INFO metabase.driver :: Registered driver :mysql (parents: :sql-jdbc) 🚚
Load driver :mysql took 20 ms
04-12 07:11:51 INFO metabase.driver :: Registered driver :h2 (parents: :sql-jdbc) 🚚
Load driver :h2 took 15 ms
04-12 07:11:51 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
04-12 07:11:51 WARN metabase.db :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. See https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres for more information.
04-12 07:11:51 INFO metabase.db :: Verifying h2 Database Connection ...
04-12 07:11:51 INFO metabase.driver :: Initializing driver :sql...
04-12 07:11:51 INFO metabase.driver :: Initializing driver :sql-jdbc...
04-12 07:11:51 INFO metabase.driver :: Initializing driver :h2...
04-12 07:11:52 INFO metabase.db :: Verify Database Connection ... ✅
04-12 07:11:52 INFO metabase.db :: Running Database Migrations...
04-12 07:11:52 INFO metabase.db :: Setting up Liquibase...
04-12 07:11:52 INFO metabase.db :: Liquibase is ready.
04-12 07:11:52 INFO metabase.db :: Checking if Database has unrun migrations...
04-12 07:11:53 INFO metabase.db :: Database Migrations Current ... ✅
04-12 07:11:53 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
04-12 07:11:54 INFO db.migrations :: Finished running data migrations.
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.notifications 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.dependencies 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.activity-feed 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.last-login 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.revision 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.sync-database 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.view-log 👂
04-12 07:11:54 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications 👂
04-12 07:11:54 INFO metabase.task :: Initializing task SyncDatabases 📆
04-12 07:11:54 INFO metabase.task :: Initializing task CheckForNewVersions 📆
04-12 07:11:54 INFO metabase.task :: Initializing task SendAnonymousUsageStats 📆
04-12 07:11:54 INFO metabase.task :: Initializing task SendAbandomentEmails 📆
04-12 07:11:54 INFO metabase.task :: Initializing task SendPulses 📆
04-12 07:11:54 INFO metabase.task :: Initializing task SendFollowUpEmails 📆
04-12 07:11:54 INFO metabase.task :: Initializing task TaskHistoryCleanup 📆
04-12 07:11:54 INFO metabase.core :: Metabase Initialization COMPLETE
04-12 07:12:38 DEBUG middleware.log :: GET /api/session/properties 200 9 ms (1 DB calls) Jetty threads: 8/50 (7 busy, 1 idle, 0 queued) (41 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/user/current 200 371 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (42 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/user/current 200 3 ms (3 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (42 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/database 200 32 ms (4 DB calls) Jetty threads: 8/50 (6 busy, 2 idle, 0 queued) (42 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/setting 200 3 ms (0 DB calls) Jetty threads: 8/50 (7 busy, 1 idle, 0 queued) (42 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/collection/root/items 200 159 ms (7 DB calls) Jetty threads: 8/50 (6 busy, 1 idle, 0 queued) (42 total active threads)
04-12 07:12:39 DEBUG middleware.log :: GET /api/collection/root 200 9 ms (2 DB calls) Jetty threads: 8/50 (6 busy, 1 idle, 0 queued) (42 total active threads)
04-12 07:12:42 DEBUG middleware.log :: GET /api/collection/root 200 4 ms (2 DB calls) Jetty threads: 8/50 (6 busy, 1 idle, 0 queued) (42 total active threads)
04-12 07:12:54 DEBUG middleware.log :: GET /api/dashboard/34 200 115 ms (11 DB calls) Jetty threads: 8/50 (6 busy, 1 idle, 0 queued) (42 total active threads)
04-12 07:12:54 DEBUG async.api-response :: starting streaming response
04-12 07:12:54 DEBUG async.api-response :: starting streaming response
04-12 07:12:54 DEBUG async.api-response :: starting streaming response
04-12 07:12:54 DEBUG async.api-response :: starting streaming response
04-12 07:12:54 DEBUG async.api-response :: starting streaming response
04-12 07:12:54 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__46608@5e92856 on separate thread...
04-12 07:12:54 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__46608@3b4844f0 on separate thread...
04-12 07:12:54 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__46608@3051781 on separate thread...
04-12 07:12:54 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__46608@3c108782 on separate thread...
04-12 07:12:54 DEBUG async.util :: Running metabase.async.semaphore_channel$do_f_with_permit$f__46608@74c8c272 on separate thread...
04-12 07:12:54 INFO metabase.driver :: Initializing driver :google...
04-12 07:12:54 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@6cd27d52...
04-12 07:12:54 INFO plugins.classloader :: Added URL file:/apps/java/plugins/google.metabase-driver.jar to classpath
04-12 07:12:54 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.google...
04-12 07:12:54 INFO metabase.driver :: Registered abstract driver :google 🚚
Load lazy loading driver :google took 199 ms
04-12 07:12:54 INFO metabase.driver :: Initializing driver :bigquery...
04-12 07:12:54 INFO plugins.classloader :: Added URL file:/apps/java/plugins/bigquery.metabase-driver.jar to classpath
04-12 07:12:54 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.bigquery...
04-12 07:12:54 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google}) 🚚
Load lazy loading driver :bigquery took 514 ms
04-12 07:12:55 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@3570c18c: null
04-12 07:12:55 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@10f1f0c8: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
04-12 07:12:55 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@7a8991a8: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
04-12 07:12:55 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@39c3e8ec: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
04-12 07:12:55 DEBUG async.api-response :: Response not ready, writing one byte & sleeping...
04-12 07:12:55 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@439ea48b: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
04-12 07:12:55 DEBUG async.api-response :: Response not ready, writing one byte & sleeping...
04-12 07:12:55 DEBUG async.api-response :: Response not ready, writing one byte & sleeping...
04-12 07:12:55 DEBUG async.api-response :: Response not ready, writing one byte & sleeping...
04-12 07:12:55 DEBUG async.api-response :: Response not ready, writing one byte & sleeping...
04-12 07:12:55 WARN metabase.query-processor :: Query failure {:status :failed,
:class java.lang.NoClassDefFoundError,
:error "Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion",
:stacktrace
("com.google.api.client.googleapis.services.AbstractGoogleClientRequest.(AbstractGoogleClientRequest.java:133)"
"com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.(AbstractGoogleJsonClientRequest.java:57)"
"com.google.api.services.bigquery.BigqueryRequest.(BigqueryRequest.java:39)"
"com.google.api.services.bigquery.Bigquery$Jobs$Query.(Bigquery.java:1909)"
"com.google.api.services.bigquery.Bigquery$Jobs.query(Bigquery.java:1883)"
"--> driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:182)"
"driver.bigquery$execute_bigquery.invoke(bigquery.clj:171)"
"driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:173)"
"driver.bigquery$execute_bigquery.invoke(bigquery.clj:171)"
"driver.bigquery$process_native_STAR_$fn__580.invoke(bigquery.clj:267)"
"util$do_with_auto_retries.invokeStatic(util.clj:428)"
"util$do_with_auto_retries.invoke(util.clj:420)"
"util$do_with_auto_retries.invokeStatic(util.clj:432)"
"util$do_with_auto_retries.invoke(util.clj:420)"
"driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:266)"
"driver.bigquery$process_native_STAR_.invoke(bigquery.clj:262)"
"driver.bigquery$eval920$fn__922.invoke(bigquery.clj:516)"
"query_processor$fn__39135$execute_query__39140$fn__39141.invoke(query_processor.clj:67)"
"query_processor$fn__39135$execute_query__39140.invoke(query_processor.clj:61)"
"query_processor.middleware.mbql_to_native$mbql__GT_native$fn__33087.invoke(mbql_to_native.clj:36)"
"query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__31808.invoke(annotate.clj:368)"
"query_processor.middleware.annotate$add_column_info$fn__31713.invoke(annotate.clj:303)"
"query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__32550.invoke(cumulative_aggregations.clj:57)"
"query_processor.middleware.limit$limit$fn__33043.invoke(limit.clj:19)"
"query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__39002.invoke(results_metadata.clj:86)"
"query_processor.middleware.format_rows$format_rows$fn__33031.invoke(format_rows.clj:26)"
"query_processor.middleware.add_dimension_projections$add_remapping$fn__19676.invoke(add_dimension_projections.clj:234)"
"query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__31259.invoke(add_row_count_and_status.clj:15)"
"query_processor.middleware.driver_specific$process_query_in_context$fn__32792.invoke(driver_specific.clj:12)"
"query_processor.middleware.resolve_driver$resolve_driver$fn__35968.invoke(resolve_driver.clj:15)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31988$fn__31989.invoke(bind_effective_timezone.clj:9)"
"util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
"util.date$call_with_effective_timezone.invoke(date.clj:77)"
"query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__31988.invoke(bind_effective_timezone.clj:8)"
"query_processor.middleware.store$initialize_store$fn__39027$fn__39028.invoke(store.clj:11)"
"query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
"query_processor.store$do_with_new_store.invoke(store.clj:31)"
"query_processor.middleware.store$initialize_store$fn__39027.invoke(store.clj:10)"
"query_processor.middleware.cache$maybe_return_cached_results$fn__32410.invoke(cache.clj:127)"
"query_processor.middleware.catch_exceptions$catch_exceptions$fn__32458.invoke(catch_exceptions.clj:63)"
"query_processor$process_query.invokeStatic(query_processor.clj:232)"
"query_processor$process_query.invoke(query_processor.clj:228)"
"query_processor$run_and_save_query_BANG_.invokeStatic(query_processor.clj:344)"
"query_processor$run_and_save_query_BANG_.invoke(query_processor.clj:338)"
"query_processor$fn__39216$process_query_and_save_execution_BANG___39221$fn__39222.invoke(query_processor.clj:371)"
"query_processor$fn__39216$process_query_and_save_execution_BANG___39221.invoke(query_processor.clj:357)"
"async.semaphore_channel$do_f_with_permit$f__46608.invoke(semaphore_channel.clj:81)"
"async.util$do_on_separate_thread$fn__42559.invoke(util.clj:53)"),
:query

**Comment by edmondo1984** [comment]
We got response not ready as well but with mySQL
