### ISSUE TITLE
Log configuration invalid

### ISSUE THREAD

**Issue by thomasLeclaire** [metabase/metabase#9771]
- Metabase version: 0.32.4

Following this commit : https://github.com/metabase/metabase/commit/ac25275ffc367c13702445883889456cbafd8737

the metabase appender was removed, therefore, we have 2 alerts into logs at each start : 

log4j:ERROR Could not find value for key log4j.appender.metabase
log4j:ERROR Could not instantiate appender named "metabase".

I suppose it just need to remove also the metabase item from rootlogger, but don't know the possible others impact on logging, and I  can't validate for now.

**Comment by camsaul** [comment]
fixed by #9923
