### ISSUE TITLE
Include dashboard filter options similar to question ("is not", "is empty", "greater than", "less than" ...)

### ISSUE THREAD

**Issue by anastasiapapa** [metabase/metabase#9776]
EDIT: Feature request

My request has to do with the general filters at the top of a dashboard where all created cards are filtered for a specific/existing value of the filter field. In this case there is no menu to choose from (like "not equal to", "greater than" etc) like there is in the filtering for individual cards, but you can just choose from the actual values of this field in the table used. 
At the moment I am mainly interested in if I could set there an empty value to filter with. Would that be possible to implement? 
Cheers

------------------------------------------------------------------------------------------
Is it possible to have the option for a filter to be empty instead of just one of the values?

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @anastasiapapa 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
There's an "Is Empty" filter, have you tried that?
![Screenshot_00000](https://user-images.githubusercontent.com/1447303/56049978-e9317e80-5d07-11e9-94e4-560458900fa3.png)
And please close this issue :+1:

**Comment by anastasiapapa** [comment]
Hey @flamber. Thank you for your fast response. What you sent me with a screen shot is the filtering part inside a certain card, but I was actually asking about the general filters at the top of a dashboard where all created cards are filtered for a specific value of this field that you choose to filter with. I should have been more accurate, apologies. In this case there is no menu to choose from (like "not equal to", "greater than" etc), but you can just choose from the actual values of this field in the table used. And I am wondering if there I can choose somehow for an empty value. Does that make sense?
* I will immediately close the issue and go to forum if after your answer on my last question can't help in the issue. Is that ok?

**Comment by flamber** [comment]
@anastasiapapa 
Okay, then you should edit the issue to indicate that it's a feature request and include details.
A workaround is that you create a native question (SQL), then you could make it into a reverse filter with a sub-query, so the values included in the filter will not be included in the result.
