### ISSUE TITLE
Keep current location in Card picker when adding multiple cards in dashboard

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9777]
When adding a card to a dashboard it would be useful to me if it kept the collection I was in when I go back to add another.

e.g. say I want to make a dashboard of stuff in a usage stats collection, I have to click `+`, then drill thru to usage stats, then select the question every time. Would be better if the second time I clicked `+` it was still on Anonymous Usage Stats.

Think about when you’re using the Select File dialogs on macOS or Windows. For example if you wanted to select a file to upload somewhere and then select another it doesn’t take you back to your home directory every time. It keeps state of where it was

**Comment by mazameli** [comment]
To add on, the modal should really default to displaying the collection that the dashboard is in, with the assumption being that the cards you'd want to add would be in there, too.
