### ISSUE TITLE
Dashboards rerun all queries when saving

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9778]
Not such a big deal for tons of smaller queries but if you have a huge number of Cards on the dashboard or the queries are very slow running it's a lot of unnecessary server and data warehouse load.

**Comment by flamber** [comment]
Isn't this a duplicate of #5332?

**Comment by flamber** [comment]
Closing in favor of #5332

**Comment by camsaul** [comment]
This happens even if your dashboard doesn't have parameters

**Comment by flamber** [comment]
@camsaul I cannot reproduce that - I can see requests `/api/dashboard/:id` on Cancel/Save of dashboard with/out filters, but no requests to `/api/card/:id/query`. Can you help reproduce?
Or do you mean #8030 ?
