### ISSUE TITLE
can I join on mysql database on mongodb database in metabase?

### ISSUE THREAD

**Issue by itcam** [metabase/metabase#9789]
I want select some data from mysql and mongodb

can I join the data on mysql data source between mongodb datasource?

**Comment by flamber** [comment]
Hi @itcam 
No, currently Metabase doesn't support join cross datasources - see #3953 - upvote by clicking the :+1: 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
And please close this issue :wink:

**Comment by mazameli** [comment]
Closing as resolved.
