### ISSUE TITLE
Show JSON fields in MySQL

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#9800]
Metabase 0.31 was working fine with JSON fields, but now 0.32.4 - its broken.
Please can you add "JSON_PRETTY(column)" for field with "Field containing JSON" type?

**Comment by Korayem** [comment]
This should be an out of the box experience
I used PowerBI before and it's natively there with no workarounds

**Comment by Korayem** [comment]
Possible duplicate https://github.com/metabase/metabase/issues/9681

**Comment by jeremybdk** [comment]
Hello @salsakran do you know if there is any plans to fix this? I really love Metabase but this bug makes it harder to use :)

Thanks

**Comment by jeremybdk** [comment]
@camsaul, @flamber this does not fix the issue with MySQL, the JSON Data are still displayed as hex with the latest update.

**Comment by flamber** [comment]
@jeremybdk Check #11289.

**Comment by mix5003** [comment]
@flamber when i try at master branch i still see some warning like 
```Don't know how to map column type 'JSON' to a Field base_type, falling back to :type/*```
but it work fines. 

i think it should add `:JSON` map to `:type/Text` to suppress this warning 
https://github.com/metabase/metabase/blob/master/src/metabase/driver/mysql.clj#L253

**Comment by HKFiliatix** [comment]
Still the same behavior.

**Comment by flamber** [comment]
@HKFiliatix Are you using Docker? If so, then expect a re-release or maybe a new version #11289
