### ISSUE TITLE
Setting the x-axis manually

### ISSUE THREAD

**Issue by inesmoskal** [metabase/metabase#9804]
I would like to make a year-to-date graph, with all of the month (from January to December) already on the x - axis, even when there is not yet all of the data available to populate them.

**Comment by flamber** [comment]
Hi @inesmoskal 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
You would have to either have a lookup table with months or create it with SQL:
https://dba.stackexchange.com/questions/203345/sequence-of-dates-months-from-january-to-december-with-sql
