### ISSUE TITLE
Sort Pivot table categories manually

### ISSUE THREAD

**Issue by EBoisseauSierra** [metabase/metabase#9805]
**Problem**
I want to be able to sort categories of my pivot table manually.
However, it is currently (`v0.32.2` built on 2019-04-03) done alphabetically and I cannot change it. (As opposed as it is the case with  the _"Visible columns"_ setting for regular tables.) 

I have seen [PR #8555 : Pivot table improvements](https://github.com/metabase/metabase/pull/8552), however, it has already been implemented in `v0.31` so obviously doesn't solve the issue.

**Example**
Say I have following table as result of my question:

| Fruit  | Metric  | Average |
|--------|---------|--------:|
| Apple  | Rating  |     4.3 |
| Apple  | Size    |      13 |
| Apple  | Weight  |     210 |
| Apple  | Rating  |     3.8 |
| Banana | Size    |      42 |
| Banana | Weight  |     113 |
| Apple  | Rating  |     4.9 |
| Cherry | Size    |       8 |
| Cherry | Weight  |      17 |

If I pivot using the column `Fruit`, I get

| Fruit | Rating |Size | Weight |
|-------|---:|---:|---:|
| Apple | 4.3 | 13 | 210|
| Banana | 3.8 | 42 | 113 |
| Cherry | 4.9 | 8 | 17 |

However, I'd like to be able to re-order the table categories manually. E.g., as following:

| Fruit  |Size | Weight | Rating |
|------- |---:|---:|-------:|
| Apple  | 13 | 210| 4.3    |
| Banana | 42 | 113 | 3.8    |
| Cherry | 8 | 17 | 4.9    |

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Closing in favor of #2339, since the problem comes from the query, which automatically adds ascending (`asc`) to columns that are grouped, which is why it becomes alphabetic by default.
