### ISSUE TITLE
Can't display settings and cross button on edit time into dashboard cart ?

### ISSUE THREAD

**Issue by parameswar59** [metabase/metabase#9811]
I have added a custom chart and when I want to add that chart into dashboard cart then on edit time that cart can't display the settings and close button. Where as other chart is displaying the both buttons on edit. 
How do I fixed this issue ?

**Comment by flamber** [comment]
Hi @parameswar59 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
Which version of Metabase? Which type of charts are you trying to combine?
