### ISSUE TITLE
Postgres database not adding on first try

### ISSUE THREAD

**Issue by kyleabeauchamp** [metabase/metabase#9812]
Chrome 73.0
OSX 10.14
postgres 11.2
Metabase 32.4
Metabase docker
Metabase internal database H2

I find that when I configure a postgres database on the latest version of metabase, the DB claims to be added successfully but actually fails to add.  I then need to go to the admin -> databases page and re-add the database.

**Comment by flamber** [comment]
Hi @kyleabeauchamp Do you see anything in the browser console or Metabase log? Both when it doesn't create it and when it actually creates it?

**Comment by salsakran** [comment]
closing since it's been 10 months, only occurred with one person and can't be reproduced
