### ISSUE TITLE
Question Alerts csv does not support utf8

### ISSUE THREAD

**Issue by guylando** [metabase/metabase#9813]
Creating an ordinary question which has chinese/arabic utf8 characters in the query results sends the email alert such that: the embedded view of the results in the email shows all characters correctly BUT the attached csv file to the email does not support utf8 and changes all utf8 characters to '?????'. Any way to configure the alert csv encoding?

Example problematic characters:
覀覀نفر

**Comment by flamber** [comment]
Hi @guylando This looks like a duplicate of #8410, if yes, then close this issue.

**Comment by guylando** [comment]
@flamber 
1. That issue talks about pulses and not alerts
2. That issue talks about file name while I talk about file content
3. I dont see that issue talking about csv

**Comment by flamber** [comment]
Okay, I misunderstood the issue then.
Can you please fill out the requested information, when creating an issue. Version, database, etc.

**Comment by guylando** [comment]
I found the problem: metabase csv export here https://github.com/metabase/metabase/blob/master/src/metabase/util/export.clj#L45
uses data.csv clojure library: https://github.com/clojure/data.csv which does not include BOM which is a file content prefix which allows excel and other readers to correctly open the csv file as stated here https://github.com/metabase/metabase/issues/1961#issuecomment-242747167. It can be solved by libraries such as https://github.com/jimpil/clj-bom
It already has an issue: https://github.com/metabase/metabase/issues/3271 and a pull request: https://github.com/metabase/metabase/pull/7029
The pull request is 2 years old..
