### ISSUE TITLE
why my metabase don't have  public sharing

### ISSUE THREAD

**Issue by linsamtw** [metabase/metabase#9819]
![image](https://user-images.githubusercontent.com/20013414/56459788-69707780-63cb-11e9-8cfa-fa77a13b1b66.png)

why my metabase don't have public sharing ?

my ip is http://139.162.97.62:3000

i use " java -jar metabase.jar " running my metabase, not docker

**Comment by flamber** [comment]
Hi @linsamtw 
Which version of Metabase?
And in the future, please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by linsamtw** [comment]
You're running Metabase 0.20.0 which is the latest and greatest!

my Metabase is 0.20.0

**Comment by flamber** [comment]
Okay, the latest version is 0.32.5 - released an hour ago.
Version 0.20.0 is from October 2016

**Comment by linsamtw** [comment]
![image](https://user-images.githubusercontent.com/20013414/56459897-f10ab600-63cc-11e9-94fb-d4f410a3e847.png)

but i have "CHECK FOR UPDATES"

how update latest version?

**Comment by flamber** [comment]
https://metabase.com/docs/latest/operations-guide/start.html#upgrading-metabase
And please close this issue :+1: and use the forum for further questions.
