### ISSUE TITLE
Getting an error java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'172.17.0.1' (using password: NO)

### ISSUE THREAD

**Issue by akemisetti** [metabase/metabase#9820]
I am getting the following error when connecting metabase to mysql using docker
java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'172.17.0.1' (using password: NO)

I am able to connect to mysql workbench successfully.
'root'@'%' has all permissions. 
I am not sure where it is picking up 172.17.0.1. I am trying to connect to localhost

relevant log entry is 

Apr 20 11:10:56 DEBUG metabase.middleware.log :: POST /api/database 400 26 ms (0 DB calls) Jetty threads: 8/50 (4 busy, 3 idle, 0 queued) (45 total active threads)  {:valid false, :dbname "java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'172.17.0.1' (using password: NO)", :message "java.sql.SQLInvalidAuthorizationSpecException: Access denied for user 'root'@'172.17.0.1' (using password: NO)"}

Here is the docker command

docker run \
--detach \
--name=db-container \
--publish 3306:3306 \
--volume=/Users/test/mySQL/DB/conf/conf.d:/etc/mysql/conf.d \
--volume=/Users/test/mySQL/DB/data:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=welcome1 \
--rm \
mysql

**Comment by flamber** [comment]
Hi @akemisetti 
Which version of Metabase? Are you using Metabase docker? Are you trying to use the MySQL for the internal metadata or as a datasource?
Did you read the documentation?
https://metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html
The important part is `using password: NO`, so it seems like you're not using a password in the Metabase configuration.
And in the future, please use the forum for questions and troubleshooting:
https://discourse.metabase.com/

**Comment by akemisetti** [comment]
I am using docker metabase metabase/metabase. I figured out that it is happening with latest mysql docker (version 8.0) when I changed to mysql 5.7 I am not facing the issue. Is mysql 8.0 supported?

**Comment by flamber** [comment]
MySQL 8 is supported, but not the new default authentication method:
https://discourse.metabase.com/t/cannot-connect-to-myql-8-using-password-no/5832/4
And if you've solved your problem, then please close this issue :+1:
