### ISSUE TITLE
Operations guide / Elastic Beanstalk setup links to 0.32.4 instead of 0.32.5

### ISSUE THREAD

**Issue by dataxpress** [metabase/metabase#9824]
On this page: [docs/v0.32.5/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase](https://metabase.com/docs/v0.32.5/operations-guide/running-metabase-on-elastic-beanstalk.html#deploying-new-versions-of-metabase) 

(As of 21 April 2019)
The download links are to `0.32.4` instead of the current latest `0.32.5`. These are filled in by a variable called `site.latest_version`, though I could not find where this is set, or else I'd send a pull request.

Thanks for everything you do!

**Comment by salsakran** [comment]
Thanks for the heads up!

This is fixed, not sure why that variable didn't get filled in.

**Comment by flamber** [comment]
@salsakran 
But now all the old docs also uses the newest version instead of whatever version they belong to.
Example the Quick Launch link:
https://metabase.com/docs/v0.30.0/operations-guide/running-metabase-on-elastic-beanstalk.html#quick-launch
