### ISSUE TITLE
new metabase.jar files do not pass signtature verification

### ISSUE THREAD

**Issue by hushfrog2** [metabase/metabase#9825]
------
Before filing an issue we'd appreciate it if you could take a moment to ensure
there isn't already an open issue or pull-request.
-----

If there's an existing issue, please add a :+1: reaction to the description of
the issue. One way we prioritize issues is by the number of :+1: reactions on
their descriptions. Please DO NOT add `+1` or :+1: comments.

### Security Disclosure

Security is very important to us. If discover any issue regarding security, please disclose the information responsibly by sending an email to security@metabase.com and not by creating a GitHub issue.

### Database support

For requests for new database drivers, please include the name
of the database and the version. Additionally, giving us a sense of how and what
you use it for, and other high-level details about the database, can help us get
a better picture of what would need to done to support it.

### Feature requests and proposals
We're excited to hear how we can make Metabase better. Please add as much detail
as you can on your use case.

### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

Thanks for being part of the Metabase project!
-------

**Comment by flamber** [comment]
Hi @hushfrog2 
Please be more descriptive or close this.
I'm getting the same checksum on all my servers as the one listed on the release page for 0.32.5:
```
$ sha256sum metabase.jar
cebd18dc7707167d2fde620da1cd905f422064ffea6b3461d4cb019646656a99  metabase.jar
```

**Comment by hushfrog2** [comment]
[root@localhost] #jarsigner -verify metabase.jar

Jar is unsigned.

Furthermore, I do not see a location on the metabase website where they advertise the  hash value you are referencing.  Even if they did, hash values are no where near as secure as actually signing the jar file.  Which older version have.  If you check metabase.jar (v0.30.2), it has a valid jar signature.

**Comment by hushfrog2** [comment]
If you are unfamiliar with jar signature verification:

https://developer.ibm.com/answers/questions/248576/how-to-verify-the-certificate-of-jar-files/
or
https://docs.oracle.com/javase/tutorial/deployment/jar/verify.html

**Comment by flamber** [comment]
Keeping the issue template and not providing any details is a good way for people to overlook the issue.

Checksums are a thing since 0.32.1 and can be found on the Github site:
https://github.com/metabase/metabase/releases

Signatures was removed for several reasons - have a look at issue #9639

**Comment by camsaul** [comment]
@hushfrog2 we stopped signing the JAR using the jarsigner tool because 

1.  It would be trivial to remove the JAR signature, and 99.9% of people would never notice
2.  It takes almost twice as long to start Metabase with a signed JAR because it spends a ton of time validating checksums for every resource contained inside the JAR.

We started providing SHA-256 checksums instead for those reasons.
