### ISSUE TITLE
Error Connection : Trying to connect with ssl, but ssl not enabled in the server

### ISSUE THREAD

**Issue by yogidup** [metabase/metabase#9826]
![Selection_216](https://user-images.githubusercontent.com/24633363/56478964-bc861f80-64dc-11e9-9578-0fa8ad6503ed.png)

Browser : Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Operating System : Linux Mint 19.1 Tessa
Database : Mariadb 10.1.24
Metabase Version : 0.32.4
Environment : Linux Mint 19.1 Tessa

This error happen when I used version 0.32.4, I already put configuration on Additional JDBC connection string options but still face the problem. For now I used previous version 0.31

**Comment by RMMSecurity** [comment]
What version of MySQL database are you using?

They somewhat dropped official support for MySQL 5.6 when they moved to the MariaDB drivers over the older MySQL drivers. So only MySQL 5.7+ works as of now

**Comment by yoginitiate** [comment]
My bad, am using Mariadb 10.1.24
![Selection_228](https://user-images.githubusercontent.com/24633363/56798227-93e58900-6840-11e9-9069-cb51d046ad61.png)

**Comment by camsaul** [comment]
Related: #9629

**Comment by flamber** [comment]
Closing, since Metabase doesn't officially support versions earlier than MySQL 5.7 and MariaDB 10.2. If you're still experiencing problems with newer versions of the latest version of Metabase, then please comment.
