### ISSUE TITLE
Can't connect to Gmail SMTP

### ISSUE THREAD

**Issue by lowercase00** [metabase/metabase#9827]
- Tested on both Firefox 68.03 and Chrome (incognito 78.0)
- Only tested on MacOS, both High Sierra and Mojave
- Currently connected to AWS RDS MySQL
- Latest version 0.32.5
- Running on Docker container in DigitalOcean Droplet

I've been trying to set up SMTP gmail to use Pulse (we don't use Slack), with no success.
Both IMAP and POP are enabled on my gmail account.
Tried all of those using both `smtp.gmail.com` and `smtp-relay.gmail.com`, results are the same.
I've tried:

With regular username (e-mail) and password (regular)
1. SSL Security on port 465
I got: `No matching clause: 535-5.7.8 Username and Password not accepted. `
2. TSL Security on port 587
I got: `No matching clause: 535-5.7.8 Username and Password not accepted. `
3. None security on port 587:
I can save the e-mail, but when trying to send a test e-mail I get: `No matching clause: 530 5.7.0 Must issue a STARTTLS command first.`
4. None security on port 465
I get: `Something went wrong`

I saw a post from a guy that suggested enabling two-step verification and creating a password for the app, so I tried that:
1. Enabled two-step verification
2. Created "App Password"
And then tried a few different combinations and got the same result.

1. SSL Security on port 465
I got: `No matching clause: 535-5.7.8 Username and Password not accepted. `
2. TSL Security on port 587
I got: `No matching clause: 535-5.7.8 Username and Password not accepted. `
3. None security on port 587:
I can save the e-mail, but when trying to send a test e-mail I get: `No matching clause: 530 5.7.0 Must issue a STARTTLS command first.`
4. None security on port 465
I get: `Something went wrong`

Any ideas on what I might be doing wrong?

**Comment by flamber** [comment]
Hi @lowercase00 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
It has nothing to do with IMAP and POP3. And `smtp-relay.gmail.com` is only relevant if you're using G-Suite and have setup "SMTP Relay" in the administration settings.
Can you send emails with other applications through the same credentials via `smtp.gmail.com`?
Did you enable "Less secure app access" ? https://myaccount.google.com/lesssecureapps

**Comment by lowercase00** [comment]
Thanks, will use the forum for further questions.
