### ISSUE TITLE
I can not use mysql as config db because of the error "Table 'raw_table' already exists"

### ISSUE THREAD

**Issue by cowcomic** [metabase/metabase#9829]
my os is win10-64
my metabase version is 
`
tag=v0.32.4
hash=f4dc152
branch=release-0.32.0
date=2019-04-09 
`
I use mysql as config db with following code
`
set MB_DB_TYPE=mysql
set MB_DB_DBNAME=metabase_config
set MB_DB_PORT=3306
set MB_DB_USER=root
set MB_DB_PASS=
set MB_DB_HOST=localhost
java -jar metabase.jar
`
i use a none password mysql

then it goes wrong
`
log4j:ERROR Could not find value for key log4j.appender.metabase
log4j:ERROR Could not instantiate appender named "metabase".
04-22 14:57:44 [1mINFO metabase.util[0m :: 正在加载Metabase……
04-22 14:57:44 [1mINFO metabase.util[0m :: Maximum memory available to JVM: 1.7 GB
04-22 14:57:47 [1mINFO util.encryption[0m :: 已存储的证书加密方式已经为这个Metabase事例禁用
 查看更多信息，看 https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
04-22 14:57:54 [1mINFO metabase.driver[0m :: Registered abstract driver :sql
04-22 14:57:58 [1mINFO metabase.core[0m :: 在脱机模式下启动Metabase
04-22 14:57:58 [1mINFO metabase.server[0m :: 用配置启动嵌入式Jetty Webserver
 {:port 3000}

04-22 14:57:59 [1mINFO metabase.core[0m :: 开始Metabase 版本v0.32.4 (f4dc152 release-0.32.0)……
04-22 14:57:59 [1mINFO metabase.core[0m :: 系统时区是“Asia/Shanghai”
04-22 14:57:59 [1mINFO metabase.plugins[0m :: Loading plugins in D:\workevn\metabase\plugins...
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :druid...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :druid
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :google...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered abstract driver :google
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-22 14:57:59 [1mDEBUG plugins.initialize[0m :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver"]
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :bigquery...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :bigquery (parents: #{:sql :google})
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :googleanalytics...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :googleanalytics (parents: #{:google})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :mongo...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :mongo
04-22 14:57:59 [1mDEBUG plugins.classloader[0m :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@6b256c04...
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Plugins with unsatisfied deps: ["Metabase Oracle Driver"]
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :presto...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :presto (parents: #{:sql})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :redshift...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered abstract driver :sql-jdbc (parents: :sql)
Load driver :sql-jdbc took 13 ms
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :postgres (parents: :sql-jdbc)
Load driver :postgres took 93 ms
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :redshift (parents: #{:postgres})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :snowflake...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :snowflake (parents: #{:sql-jdbc})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :hive-like...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered abstract driver :hive-like (parents: #{:sql-jdbc})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :sparksql...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :sparksql (parents: #{:hive-like})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :sqlite...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :sqlite (parents: #{:sql-jdbc})
04-22 14:57:59 [1mINFO plugins.lazy-loaded-driver[0m :: Registering lazy loading driver :sqlserver...
04-22 14:57:59 [1mINFO metabase.driver[0m :: Registered driver :sqlserver (parents: #{:sql-jdbc})
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
04-22 14:57:59 [1mINFO plugins.dependencies[0m :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase Vertica Driver"]
04-22 14:58:01 [1mINFO metabase.driver[0m :: Registered driver :mysql (parents: :sql-jdbc)
Load driver :mysql took 52 ms
04-22 14:58:01 [1mINFO metabase.driver[0m :: Registered driver :h2 (parents: :sql-jdbc)
Load driver :h2 took 28 ms
04-22 14:58:01 [1mINFO metabase.core[0m :: Metabse数据库设置、迁移中。坐稳了，这个可能要花一分钟……
04-22 14:58:01 [1mINFO metabase.db[0m :: Verifying mysql Database Connection ...
04-22 14:58:01 [1mINFO metabase.driver[0m :: Initializing driver :sql...
04-22 14:58:01 [1mINFO metabase.driver[0m :: Initializing driver :sql-jdbc...
04-22 14:58:01 [1mINFO metabase.driver[0m :: Initializing driver :mysql...
04-22 14:58:01 [1mINFO metabase.db[0m :: Verify Database Connection ...
04-22 14:58:01 [1mINFO metabase.db[0m :: Running Database Migrations...
04-22 14:58:01 [1mINFO metabase.db[0m :: Setting up Liquibase...
04-22 14:58:01 [1mINFO metabase.db[0m :: Liquibase is ready.
04-22 14:58:01 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mINFO metabase.db[0m :: Database has unrun migrations. Waiting for migration lock to be cleared...
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:03 [1mINFO metabase.db[0m :: Migration lock is cleared. Running migrations...
04-22 14:58:03 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:04 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:04 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:15 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::32::agilliland failed.  Error: (conn=41) Specified key was too long; max key length is 1000 bytes [Failed SQL: ALTER TABLE metabase_config.raw_table ADD CONSTRAINT uniq_raw_table_db_schema_name UNIQUE (database_id, `schema`, name)]
04-22 14:58:15 [1mWARN metabase.util[0m :: auto-retry metabase.db$run_schema_migrations_BANG_$fn__14468@7b0e39e7: Migration failed for change set migrations/000_migrations.yaml::32::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=41) Specified key was too long; max key length is 1000 bytes [Failed SQL: ALTER TABLE metabase_config.raw_table ADD CONSTRAINT uniq_raw_table_db_schema_name UNIQUE (database_id, `schema`, name)]
04-22 14:58:15 [1mINFO metabase.db[0m :: Setting up Liquibase...
04-22 14:58:15 [1mINFO metabase.db[0m :: Liquibase is ready.
04-22 14:58:15 [1mINFO metabase.db[0m :: Checking if Database has unrun migrations...
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mINFO metabase.db[0m :: Database has unrun migrations. Waiting for migration lock to be cleared...
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mINFO metabase.db[0m :: Migration lock is cleared. Running migrations...
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mWARN changelog.DatabaseChangeLog[0m :: modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
04-22 14:58:16 [1mERROR changelog.ChangeSet[0m :: Change Set migrations/000_migrations.yaml::32::agilliland failed.  Error: (conn=43) Table 'raw_table' already exists [Failed SQL: CREATE TABLE metabase_config.raw_table (id INT AUTO_INCREMENT NOT NULL, database_id INT NOT NULL, active BIT(1) NOT NULL, `schema` VARCHAR(255) NULL, name VARCHAR(255) NOT NULL, details TEXT NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, CONSTRAINT PK_RAW_TABLE PRIMARY KEY (id), CONSTRAINT fk_rawtable_ref_database FOREIGN KEY (database_id) REFERENCES metabase_config.metabase_database(id))]
04-22 14:58:16 [1mERROR metabase.core[0m :: Metabase初始化失败
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::32::agilliland:
     Reason: liquibase.exception.DatabaseException: (conn=43) Table 'raw_table' already exists [Failed SQL: CREATE TABLE metabase_config.raw_table (id INT AUTO_INCREMENT NOT NULL, database_id INT NOT NULL, active BIT(1) NOT NULL, `schema` VARCHAR(255) NULL, name VARCHAR(255) NOT NULL, details TEXT NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, CONSTRAINT PK_RAW_TABLE PRIMARY KEY (id), CONSTRAINT fk_rawtable_ref_database FOREIGN KEY (database_id) REFERENCES metabase_config.metabase_database(id))]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
        at liquibase.Liquibase.update(Liquibase.java:202)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:209)
        at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:196)
        at metabase.db$migrate_BANG_$fn__14450.invoke(db.clj:313)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
        at metabase.db$migrate_BANG_.invokeStatic(db.clj:301)
        at metabase.db$migrate_BANG_.invoke(db.clj:282)
        at metabase.db$run_schema_migrations_BANG_$fn__14468.invoke(db.clj:446)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:428)
        at metabase.util$do_with_auto_retries.invoke(util.clj:420)
        at metabase.util$do_with_auto_retries.invokeStatic(util.clj:432)
        at metabase.util$do_with_auto_retries.invoke(util.clj:420)
        at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:445)
        at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:428)
        at metabase.db$setup_db_BANG_$fn__14477.invoke(db.clj:468)
        at metabase.util$do_with_us_locale.invokeStatic(util.clj:683)
        at metabase.util$do_with_us_locale.invoke(util.clj:669)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:72)
        at metabase.core$init_BANG_.invoke(core.clj:51)
        at metabase.core$start_normally.invokeStatic(core.clj:118)
        at metabase.core$start_normally.invoke(core.clj:112)
        at metabase.core$_main.invokeStatic(core.clj:138)
        at metabase.core$_main.doInvoke(core.clj:133)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.DatabaseException: (conn=43) Table 'raw_table' already exists [Failed SQL: CREATE TABLE metabase_config.raw_table (id INT AUTO_INCREMENT NOT NULL, database_id INT NOT NULL, active BIT(1) NOT NULL, `schema` VARCHAR(255) NULL, name VARCHAR(255) NOT NULL, details TEXT NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, CONSTRAINT PK_RAW_TABLE PRIMARY KEY (id), CONSTRAINT fk_rawtable_ref_database FOREIGN KEY (database_id) REFERENCES metabase_config.metabase_database(id))]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
        ... 39 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=43) Table 'raw_table' already exists
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
        at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:407)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
        ... 44 more
Caused by: java.sql.SQLException: Table 'raw_table' already exists
Query is: CREATE TABLE metabase_config.raw_table (id INT AUTO_INCREMENT NOT NULL, database_id INT NOT NULL, active BIT(1) NOT NULL, `schema` VARCHAR(255) NULL, name VARCHAR(255) NOT NULL, details TEXT NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, CONSTRAINT PK_RAW_TABLE PRIMARY KEY (id), CONSTRAINT fk_rawtable_ref_database FOREIGN KEY (database_id) REFERENCES metabase_config.metabase_database(id))
java thread: main
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:222)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:350)
        ... 46 more
04-22 14:58:16 [1mINFO metabase.core[0m :: Metabase正在关闭……
04-22 14:58:16 [1mINFO metabase.core[0m :: Metabase关闭完成
`

**Comment by flamber** [comment]
Hi @cowcomic 
So you're trying to migrate from H2 to MySQL? Which version of MySQL?
It looks like it's having problems with the length of the index: `Specified key was too long; max key length is 1000 bytes`

**Comment by cowcomic** [comment]
> Hi @cowcomic
> So you're trying to migrate from H2 to MySQL? Which version of MySQL?
> It looks like it's having problems with the length of the index: `Specified key was too long; max key length is 1000 bytes`

My mysql version is 5.7.23
All tables auto created were MyISAM engine

**Comment by flamber** [comment]
@cowcomic 
As far as I can see `raw_table` is a very old table structure that was completely removed in 0.30.
Are you upgrading and migrating at the same time? If yes, then first upgrade, then migrate.
I would recommend InnoDB instead of MyISAM. Otherwise you might as well just use H2.

**Comment by cowcomic** [comment]
@flamber 
the table is auto created with MyISAM engine
I download the Jar from here https://metabase.com/start/jar.html with version 0.32.4
I tried different ways, only init by mysql, init by H2 then migrate to mysql, all goes wrong

**Comment by cowcomic** [comment]
problem solved
I changed mysql default engine to innodb, then init OK
but migrate from H2 still goes wrong, with error "some data can not insert into a table because of a column can not be null"

Better for metabase to create table with a specific engine

**Comment by flamber** [comment]
There's a small bug in 0.32.4's migration related to `sizeX` - you can use 0.32.5 instead:
https://downloads.metabase.com/v0.32.5/metabase.jar
MySQL 5.5.5 (mid 2010) changed default-storage-engine from MyISAM to InnoDB, so I don't think it was expected to use such an old engine by default anymore.
If the problem is solved, then please close this issue.

**Comment by cowcomic** [comment]
@flamber 
Thanks for your help.

My mysql was installed from WAMP. Maybe WAMP change the default setting
I still wander if metabase can define engine mode by created sql instead of default setting

The Issue closed
