### ISSUE TITLE
dashboard cards are responding to touch events outside edit mode, which makes scrolling difficult

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#983]

**Comment by agilliland** [comment]
@kdoh is this something that's specific to mobile?

**Comment by kdoh** [comment]
@agilliland yes. long story short is it seems like touch events with the intention of scrolling end up triggering the layout arrangement and you end up dragging a card instead of scrolling.

**Comment by tlrobinson** [comment]
Multiseries branch should partially resolves this since we don't use the grid for the mobile layout any more (assuming it hits the mobile breakout, which is probably not be a safe assumption on tablets, so we should check)

**Comment by agilliland** [comment]
Cool.  then let's remember to come back and test this specific issue once the multiseries branch is stable.

**Comment by tlrobinson** [comment]
This has been resolved with the new dashboard implementation.
