### ISSUE TITLE
metabase only use single thread？

### ISSUE THREAD

**Issue by Windsmild** [metabase/metabase#9830]
I start metabase use jar on a server with 4 core CPU. I found it only ran one core when OOM happened.
Is that right?

**Comment by Windsmild** [comment]
or I can set it to run multi core?

**Comment by camsaul** [comment]
Metabase is highly multi-threaded are you sure it’s only running on one core?

**Comment by Windsmild** [comment]
![image](https://user-images.githubusercontent.com/12582585/57211830-47563680-7014-11e9-849a-93dc9a54ae07.png)

My 4 core CPU server ran out 25% of CPU even when OOM occurred.
`
nohup /usr/lib/jvm/java-8-openjdk-amd64/bin/java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/metabase/heapdump.hprof -Xms14G -Xmx14G -server -Xss512k -XX:NewSize=2072m -XX:MaxNewSize=2072m -XX:SurvivorRatio=20 -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+ScavengeBeforeFullGC -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -Xloggc:gclog.log -XX:-OmitStackTraceInFastThrow  -jar metabase.jar &
`
Is that my  jvm option wrong?

**Comment by flamber** [comment]
This must be something in the environment that is causing this. Haven't seen this reported before. Closing, since there's not enough information to investigate.
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
