### ISSUE TITLE
Google Analytics OAuth Link Broken

### ISSUE THREAD

**Issue by morgantom93** [metabase/metabase#9836]
Just started using Metabase, looking at it for a research project for tertiary education tied in with my workplace. 
Got it connected to the PostgreSQL database no problems, now trying to link it up with the Google Analytics account work has. Got the GA Account ID, Client ID, and Client Secret but when trying to get the Auth Code, the link doesn't work.
Clicking on the link just takes me to the picture below.

![image](https://user-images.githubusercontent.com/34618411/56549380-bbd1b400-65d6-11e9-897c-71923cdbefd5.png)

Not really sure what to do from here. I tried getting the Google Analytics auth code from their end but I can't find it. I'm also not sure if this is where I should be posting about it but I couldn't see anything else.

Thanks.

**Comment by stieg** [comment]
I want to +1 to this issue.  The two input fields on the Google authentication sign-in setup page are very difficult to use.  On both Firefox and Chromium the frequently fail to save for what are cryptic reasons and often save with whitespace in there (which leads to many issues and subtle breakages).  At a minimum it would be helpful to call `trim` on those input fields post submit to get rid of leading & trailing whitespace.  Thoughts?  Need anything more?  Happy to help if we can get a response :)

**Comment by systrojan** [comment]
There are another space on client id, secret and auth code from google console. Please use manual selection to copy the code or remove the space after.

cheers :)

**Comment by mehmetalianil** [comment]
I am having this issue, without any space in the client id and secret now. 
Using the Heroku deployment. I am getting a Error 400: redirect_uri_mismatch

**Comment by mehmetalianil** [comment]
The 400 has this:
The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the WEB client type. You can create a Client ID for native application at

I had to select the WEB application, since OTHER is not an option anymore.

**Comment by mehmetalianil** [comment]
Creating the client ID and secret as a Desktop App works.

**Comment by flamber** [comment]
@mehmetalianil That's #12491

**Comment by lucascherifi** [comment]
Yes thx mehmetalianil it works with Desktop App
