### ISSUE TITLE
 fail to open webui

### ISSUE THREAD

**Issue by Geoffreysiyu** [metabase/metabase#9837]
1.  The metabase.jar I downloaded from the https://metabase.com/start/  website is version 
     0.32.4 not 0.32.5 .I need 0.32.5 to migrate from H2 to postgres
2.  When I use metabase, I often fail to open webui. When this happens, an a debug will appear in the log
      DEBUG async.api-response ::Response not ready, writing one byte & sleeping....
      DEBUG async.semaphore-channel :: f finished, permit will be returned
      DEBUG async.semaphore-channel :: f finished, permit will be returned

Not every time you can't open the web UI, the log will show this.Sometimes there is nothing appear in the log.
Thank you very much for your advice on my question！

**Comment by flamber** [comment]
You can download 0.32.5 here: https://downloads.metabase.com/v0.32.5/metabase.jar
Are you using a reverse proxy and sometimes it shows the cards and sometimes it displays an error? Then that's issue should be fixed in 0.32.5 too.
