### ISSUE TITLE
Borken link to FAQ on /enterprise/pricing page

### ISSUE THREAD

**Issue by jornh** [metabase/metabase#9838]
Just noticed clicking the `FAQ` link at the bottom of https://metabase.com/enterprise/pricing.html is missing a `.html` 

Congrats on getting that Enterprise Edition out the door BTW

**Comment by mazameli** [comment]
👋 Thanks, Jørn!

**Comment by camsaul** [comment]
@metabase/core-developers not sure who the right person to ping about fixing this in the site is

**Comment by mazameli** [comment]
I'l fix this.
