### ISSUE TITLE
MySQL: ID filter widget do not filter by name

### ISSUE THREAD

**Issue by Crusader4Christ** [metabase/metabase#9843]
- Your browser and the version: Chromium 73.0.3683.75 (Official Build) 
- Your operating system: Ubuntu
- Your databases: MySQL
- Metabase version: v0.30.4
- Metabase hosting environment: Docker
- Metabase internal database: MySQL

Before - filters only by ID
![Selection_009](https://user-images.githubusercontent.com/929827/56645494-753b9280-6686-11e9-8ebe-e2f42b4d0dc1.png)

After - filters works as expected - by name and ID
![Selection_010](https://user-images.githubusercontent.com/929827/56645540-8e444380-6686-11e9-9c91-27728ce21c6d.png)

**Comment by flamber** [comment]
I cannot reproduce on 0.35.4
