### ISSUE TITLE
redshift sync-tables fails type "e" does not exist

### ISSUE THREAD

**Issue by Rulasmur** [metabase/metabase#9844]
### Bugs
- browser and the version: Version 73.0.3683.75
- operating system: Linux Mint
- databases: Redshift
- Metabase version: 0.32.4
- Metabase hosting environment: Centos 7
- Metabase internal database: H2

It seems at some point we have lost the ability to sync-tables from our Redshift. 

```
Apr 24 08:42:18 DEBUG metabase.sync.util :: STARTING: step 'sync-tables' for redshift Database 2 'xxxxx Redshift'
Apr 24 08:42:18 ERROR metabase.sync.util :: Error running sync step: ERROR: type "e" does not exist
("org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)"
"org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)"
"org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)"
"org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)"
"org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)"
"org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)"
"org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)"
"org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)"
"org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)"
"org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1316)"
"com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:2938)"
"--> driver.sql_jdbc.sync$get_tables.invokeStatic(sync.clj:90)"
"driver.sql_jdbc.sync$get_tables.invoke(sync.clj:86)"
"driver.sql_jdbc.sync$fast_active_tables$iter__61376__61382$fn__61383.invoke(sync.clj:106)"
"driver.sql_jdbc.sync$fast_active_tables.invokeStatic(sync.clj:105)"
"driver.sql_jdbc.sync$fast_active_tables.doInvoke(sync.clj:94)"
"driver.sql_jdbc.sync$fn__61331.invokeStatic(sync.clj:35)"
"driver.sql_jdbc.sync$fn__61331.invoke(sync.clj:34)"
"driver.sql_jdbc.sync$describe_database.invokeStatic(sync.clj:189)"
"driver.sql_jdbc.sync$describe_database.invoke(sync.clj:185)"
"driver.sql_jdbc$fn__61796.invokeStatic(sql_jdbc.clj:54)"
"driver.sql_jdbc$fn__61796.invoke(sql_jdbc.clj:53)"
"sync.fetch_metadata$fn__44406$db_metadata__44411$fn__44412.invoke(fetch_metadata.clj:13)"
"sync.fetch_metadata$fn__44406$db_metadata__44411.invoke(fetch_metadata.clj:10)"
"sync.sync_metadata.tables$fn__45873$db_metadata__45878$fn__45879.invoke(tables.clj:144)"
"sync.sync_metadata.tables$fn__45873$db_metadata__45878.invoke(tables.clj:141)"
"sync.sync_metadata.tables$fn__45934$sync_tables_BANG___45939$fn__45940.invoke(tables.clj:161)"
"sync.sync_metadata.tables$fn__45934$sync_tables_BANG___45939.invoke(tables.clj:156)"
"sync.util$fn__36514$run_step_with_metadata__36519$fn__36523$fn__36525.invoke(util.clj:356)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)"
"sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)"
"sync.util$fn__36514$run_step_with_metadata__36519$fn__36523.invoke(util.clj:353)"
"sync.util$fn__36514$run_step_with_metadata__36519.invoke(util.clj:348)"
"sync.util$fn__36706$run_sync_operation__36711$fn__36712$fn__36713.invoke(util.clj:441)"
"sync.util$fn__36706$run_sync_operation__36711$fn__36712.invoke(util.clj:441)"
"sync.util$fn__36706$run_sync_operation__36711.invoke(util.clj:435)"
"sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993$fn__45994.invoke(sync_metadata.clj:51)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:149)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"sync.util$do_with_error_handling.invokeStatic(util.clj:147)"
"sync.util$do_with_error_handling.invoke(util.clj:144)"
"driver$fn__16646.invokeStatic(driver.clj:644)"
"driver$fn__16646.invoke(driver.clj:644)"
"sync.util$sync_in_context$fn__36420.invoke(util.clj:140)"
"sync.util$with_db_logging_disabled$fn__36417.invoke(util.clj:131)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)"
"sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)"
"sync.util$with_start_and_finish_logging$fn__36406.invoke(util.clj:116)"
"sync.util$with_sync_events$fn__36401.invoke(util.clj:90)"
"sync.util$with_duplicate_ops_prevented$fn__36392.invoke(util.clj:69)"
"sync.util$do_sync_operation.invokeStatic(util.clj:168)"
"sync.util$do_sync_operation.invoke(util.clj:165)"
"sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992$fn__45993.invoke(sync_metadata.clj:50)"
"sync.sync_metadata$fn__45987$sync_db_metadata_BANG___45992.invoke(sync_metadata.clj:47)"
"api.database$fn__56958$fn__56959.invoke(database.clj:511)")

Apr 24 08:42:18 INFO metabase.sync.util :: FINISHED: Sync metadata for redshift Database 2 'xxxx Redshift' (94 ms)

```

I have not been able to identify reproduction steps, as I am unsure when this issue started happening.

This seems to be working in 0.31.2

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by TrineFN** [comment]
Experiencing the same issue on version 0.32.5

**Comment by rodriguealcazar** [comment]
Same on version  0.32.8.

**Comment by mrjk05** [comment]
Issue still present in 0.32.10

```Aug 09 04:00:04 INFO metabase.sync.util :: STARTING: Sync metadata for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'sync-timezone' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 ERROR metabase.driver.sql-jdbc.execute :: Failed to set timezone:  PSQLException: Message: ERROR: keyword SESSION not supported SQLState: XX000 Error Code: 0  Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'sync-timezone' for postgres Database 7 'AWS Redshift' (20 ms) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'sync-tables' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 ERROR metabase.sync.util :: Error running sync step: ERROR: type "e" does not exist ("org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)" "org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)" "org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)" "org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)" "org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)" "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)" "org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)" "org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)" "org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)" "org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1316)" "com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:3010)" "--> driver.sql_jdbc.sync$get_tables.invokeStatic(sync.clj:90)" "driver.sql_jdbc.sync$get_tables.invoke(sync.clj:86)" "driver.sql_jdbc.sync$fast_active_tables$iter__64756__64762$fn__64763.invoke(sync.clj:106)" "driver.sql_jdbc.sync$fast_active_tables.invokeStatic(sync.clj:105)" "driver.sql_jdbc.sync$fast_active_tables.doInvoke(sync.clj:94)" "driver.sql_jdbc.sync$fn__64711.invokeStatic(sync.clj:35)" "driver.sql_jdbc.sync$fn__64711.invoke(sync.clj:34)" "driver.sql_jdbc.sync$describe_database.invokeStatic(sync.clj:189)" "driver.sql_jdbc.sync$describe_database.invoke(sync.clj:185)" "driver.sql_jdbc$fn__65183.invokeStatic(sql_jdbc.clj:50)" "driver.sql_jdbc$fn__65183.invoke(sql_jdbc.clj:49)" "sync.fetch_metadata$fn__47657$db_metadata__47662$fn__47663.invoke(fetch_metadata.clj:13)" "sync.fetch_metadata$fn__47657$db_metadata__47662.invoke(fetch_metadata.clj:10)" "sync.sync_metadata.tables$fn__49125$db_metadata__49130$fn__49131.invoke(tables.clj:144)" "sync.sync_metadata.tables$fn__49125$db_metadata__49130.invoke(tables.clj:141)" "sync.sync_metadata.tables$fn__49186$sync_tables_BANG___49191$fn__49192.invoke(tables.clj:161)" "sync.sync_metadata.tables$fn__49186$sync_tables_BANG___49191.invoke(tables.clj:156)" "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364$fn__40366.invoke(util.clj:356)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)" "sync.util$with_start_and_finish_debug_logging.invokeStatic(util.clj:121)" "sync.util$with_start_and_finish_debug_logging.invoke(util.clj:118)" "sync.util$fn__40355$run_step_with_metadata__40360$fn__40364.invoke(util.clj:353)" "sync.util$fn__40355$run_step_with_metadata__40360.invoke(util.clj:348)" "sync.util$fn__40547$run_sync_operation__40552$fn__40553$fn__40554.invoke(util.clj:441)" "sync.util$fn__40547$run_sync_operation__40552$fn__40553.invoke(util.clj:441)" "sync.util$fn__40547$run_sync_operation__40552.invoke(util.clj:435)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245$fn__49246.invoke(sync_metadata.clj:51)" "sync.util$do_with_error_handling.invokeStatic(util.clj:149)" "sync.util$do_with_error_handling.invoke(util.clj:144)" "sync.util$do_with_error_handling.invokeStatic(util.clj:147)" "sync.util$do_with_error_handling.invoke(util.clj:144)" "driver$fn__17376.invokeStatic(driver.clj:668)" "driver$fn__17376.invoke(driver.clj:668)" "sync.util$sync_in_context$fn__40261.invoke(util.clj:140)" "sync.util$with_db_logging_disabled$fn__40258.invoke(util.clj:131)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invokeStatic(util.clj:104)" "sync.util$with_start_and_finish_logging_SINGLEQUOTE_.invoke(util.clj:98)" "sync.util$with_start_and_finish_logging$fn__40247.invoke(util.clj:116)" "sync.util$with_sync_events$fn__40242.invoke(util.clj:90)" "sync.util$with_duplicate_ops_prevented$fn__40233.invoke(util.clj:69)" "sync.util$do_sync_operation.invokeStatic(util.clj:168)" "sync.util$do_sync_operation.invoke(util.clj:165)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244$fn__49245.invoke(sync_metadata.clj:50)" "sync.sync_metadata$fn__49239$sync_db_metadata_BANG___49244.invoke(sync_metadata.clj:47)" "task.sync_databases.SyncAndAnalyzeDatabase.execute(sync_databases.clj:39)")  Aug 09 04:00:04 INFO metabase.sync.util :: FINISHED: Sync metadata for postgres Database 7 'AWS Redshift' (105 ms) Aug 09 04:00:04 DEBUG metabase.sync.util :: Sync operations in flight: {:analyze #{7}} Aug 09 04:00:04 INFO metabase.sync.util :: STARTING: Analyze data for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'fingerprint-fields' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'fingerprint-fields' for postgres Database 7 'AWS Redshift' (297 µs) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'classify-fields' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'classify-fields' for postgres Database 7 'AWS Redshift' (162 µs) Aug 09 04:00:04 DEBUG metabase.sync.util :: STARTING: step 'classify-tables' for postgres Database 7 'AWS Redshift' Aug 09 04:00:04 DEBUG metabase.sync.util :: FINISHED: step 'classify-tables' for postgres Database 7 'AWS Redshift' (123 µs) Aug 09 04:00:04 DEBUG metabase.sync.util ::  ################################################################# # Completed analyze on AWS Redshift # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.695Z # Duration: 1000 µs # --------------------------------------------------------------- # Completed step 'fingerprint-fields' # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.694Z # Duration: 0 ns # Fingerprint updates attempted null, updated null, no data found null, failed null # --------------------------------------------------------------- # Completed step 'classify-fields' # Start: 2019-08-09T04:00:04.694Z # End: 2019-08-09T04:00:04.695Z # Duration: 1000 µs # Total number of fields classified 0, 0 failed # --------------------------------------------------------------- # Completed step 'classify-tables' # Start: 2019-08-09T04:00:04.695Z # End: 2019-08-09T04:00:04.695Z # Duration: 0 ns # Total number of tables classified 0, 0 updated #################################################################  Aug 09 04:00:04 INFO metabase.sync.util :: FINISHED: Analyze data for postgres Database 7 'AWS Redshift' (4 ms) Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/session/properties 200 2 ms (1 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0 Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/setting 200 375 µs (0 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0 Aug 09 04:00:27 DEBUG metabase.middleware.log :: GET /api/setup/admin_checklist 200 30 ms (11 DB calls) Jetty threads: 3/50 (4 idle, 0 queued) (119 total active threads) Queries in flight: 0```

**Comment by danburkert** [comment]
I've run into this issue.  My diagnosis is that the Postgres JDBC driver is using a [SQL syntax extension](https://www.postgresql.org/docs/9.0/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE) which Redshift does not support in the `DatabaseMetaData.getTables` call.

A workaround which I haven't tested could be to put the Redshift JDBC driver on the path so that Metabase uses it instead of the Postgres JDBC driver.  Has anyone tried this?  Is there a way to do that without requiring a custom build of metabase (I've deployed through the AWS elastic beanstalk per the docs)?

**Comment by camsaul** [comment]
@danburkert we use the Redshift JDBC driver for Redshift and the Postgres JDBC driver for PostgreSQL

**Comment by camsaul** [comment]
@mrjk05 from the logs it looks like you've added the Redshift database as a Postgres DB. It is guaranteed to use the wrong JDBC driver if you do that. Metabase has an option for "Amazon Redshift" when you connect a database and if you use that instead of Postgres it should work correctly.

**Comment by camsaul** [comment]
For the first stacktrace which is using the right database type I think whats happening is we're not initializing the lazy-loaded Redshift driver before running the sync step and the redshift impl of connection-details->spec isn't loaded yet. If thats the case it should be a simple one-line fix and will fix the related BigQuery sync error as well.

**Comment by camsaul** [comment]
@Rulasmur, did you originally save the database as `Postgres`, and then switch it to `Redshift`? If that's the case, then I can reproduce the issue and have a fix for it

**Comment by dataxpress** [comment]
I am on 0.33.4 and I am still experiencing this exact issue; seems like the commit made it in, but the problem is still happening. The logs show the exact same error despite database being set to Amazon Redshift. Should I make a new issue or can this one be re-opened?

**Comment by dataxpress** [comment]
To anyone else still seeing this, rebooting the Elastic Beanstalk App Server fixed the problem.

**Comment by bplmp** [comment]
I'm on Metabase 0.34.3 and also seeing this issue.

Our Redshift DB used to use the Redshift driver. We switched it to the Postgres driver because of other issues and then it stopped syncing the schema. Now, I've tried switching back to the Redshift driver but still it won't sync.

Here are our logs:

    03-16 16:59:32 [1mINFO sync.util[0m :: [35mSTARTING: Sync metadata for redshift Database 23 'data-dw'[0m
    03-16 16:59:32 [1mINFO sync.util[0m :: [35mSTARTING: step 'sync-timezone' for redshift Database 23 'data-dw'[0m
    03-16 16:59:32 [1mINFO sync.util[0m :: [35mSTARTING: step 'sync-tables' for redshift Database 23 'data-dw'[0m
    03-16 16:59:32 [1mINFO sync.util[0m :: [35mFINISHED: step 'sync-timezone' for redshift Database 23 'data-dw' (20.5 ms)[0m
    03-16 16:59:32 [1mINFO sync.util[0m :: [35mFINISHED: Sync metadata for redshift Database 23 'data-dw' (125.5 ms)[0m 
    03-16 16:59:32 [1mERROR sync.util[0m :: [31mError running sync step: ERROR: type "e" does not exist

**Comment by flamber** [comment]
@bplmp Did you try to restart the Metabase instance after changing the driver back to Redshift?
There hasn't been any reports of this, since it was fixed, so perhaps you should open a new issue.

**Comment by camsaul** [comment]
Metabase caches the DB type for a given database to speed up query compilation to avoid repeated lookups. I was operating under the assumption that the type of a database wouldn't change after it was created. I guess this turned out to be a bad assumption. So that's why if you're changing your Redshift DBs to Postgres ones or vice versa the behavior won't change until you restart.

Ideally I think there wouldn't be a use case for changing the type of a DB after creation but the behavior right now isn't obvious so I'll have to look at addressing that. Perhaps by only caching the DB type for the duration of the request
