### ISSUE TITLE
We should validate site-url more strictly

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9850]
Should parse it as a URL to make sure it works I was able to save 

```
https://https://<my-stie>
```

accidentally

**Comment by flamber** [comment]
Doesn't that just mean it's extra secure? Continue adding more `https://` and you'll get a [Love lock](https://en.wikipedia.org/wiki/Love_lock) :laughing: 
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Love_padlocks_on_the_Butchers%27_Bridge_%28Ljubljana%29.jpg/320px-Love_padlocks_on_the_Butchers%27_Bridge_%28Ljubljana%29.jpg)

**Comment by camsaul** [comment]
Fixed by #9873

**Comment by yannickcornaille** [comment]
I recently updated Metabase to version 0.32.8 and validation of the url is problematic. I'm using Metabase on an internal corporate network and tld is not accepted. It seems that UrlValidator uses DomainValidator and a finished list like this (http://data.iana.org/TLD/tlds-alpha-by-domain.txt) to validate. And my internal top level domain is not in it.
It's a very good thing to have made the url validation of the site stricter but I think it is too strict now.
Can we make validation more permissive easily?
