### ISSUE TITLE
Ability to view Data model (available on Admin tab) to non-admin Users

### ISSUE THREAD

**Issue by Rohith6215** [metabase/metabase#9853]
We did start using the Metabase platform and looks great.  Thanks for your contribution.

We would need ability to change Data model (available on Admin tab) to non-admin users. Since all our Metabase developers would need to change the fieldtypes of the table fields. We wouldn't want them to be given an Admin role just for this requirement. 

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by Rohith6215** [comment]
Thanks flamber. I have known about the reference section. 

However, the problem is non Admin users are not able to define any Field types on data model section making us to grant Admin role for every developer.
Looks like the data type is being fetched from the source schema. But the field types need to defined by the user

**Comment by flamber** [comment]
Okay, I just read "view" multiple times, so I thought you were just looking for Reference.

**Comment by Rohith6215** [comment]
I have edited to make it clear. Thanks

**Comment by Rohith6215** [comment]
Any update on this ? can you please tell me if there is a work around

**Comment by mazameli** [comment]
@Rohith6215 No, there is not currently a way for non-admins to change field metadata types. We would need to do something like add a different type of user role, which is something we've discussed at times.

Are there other things you would want to allow some users to do within Metabase without granting them full admin access?

**Comment by luizarakaki** [comment]
This feature is available in Pro/EE plans since 43
https://www.metabase.com/releases/2022-05-02-Metabase-0.43
