### ISSUE TITLE
SQL Server Custom query always use (lock)

### ISSUE THREAD

**Issue by philipsagala** [metabase/metabase#9854]
Hi, currently I use Metabase with SQL server. We have 80 million rows of the table and 1 million rows per days. Is there any solution to have "Ask a question" with Custom option query with (nolock) on the table? Can I use (nolock) by default so I can use full feature of the dashboard if I can use custom query.

I usually do this query on the native query, the problem is with a native query I cannot have a custom filter on the dashboard
`SELECT count(*) FROM actionTracker (nolock) where xxx = xxx`

**Comment by flamber** [comment]
Hi @philipsagala 

You would have to modify the driver to include `(nolock)` or maybe it can be work with a `View`. Or maybe set it globally: https://stackoverflow.com/questions/1035740/sql-server-how-to-set-nolock-hint-as-a-default

Why can't you have custom filters, when using SQL? Have you seen the documentation for parameters?
https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

**Comment by camsaul** [comment]
@philipsagala would there be any downside to us including `(nolock)` on every query? Since Metabase queries are read-only, the worst that could happen is the results could be in flux a bit if a write happens somewhere else why the query is running but I think the performance benefits would be worth it. Does `(nolock)` work on older versions of SQL Server?

**Comment by flamber** [comment]
There are some implications with `(nolock)`, but seems like a legitimate use for huge tables:
https://stackoverflow.com/questions/686724/what-is-with-nolock-in-sql-server

It seems like table hints has existed for a very long time - at least since SQL2008:
https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-2017

**Comment by philipsagala** [comment]
Hi All,



> Hi @philipsagala
> 
> You would have to modify the driver to include `(nolock)` or maybe it can be work with a `View`. Or maybe set it globally: https://stackoverflow.com/questions/1035740/sql-server-how-to-set-nolock-hint-as-a-default
> 
> Why can't you have custom filters, when using SQL? Have you seen the documentation for parameters?
> https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html



> Hi, currently I use Metabase with SQL server. We have 80 million rows of the table and 1 million rows per days. Is there any solution to have "Ask a question" with Custom option query with (nolock) on the table? Can I use (nolock) by default so I can use full feature of the dashboard if I can use custom query.
> 
> I usually do this query on the native query, the problem is with a native query I cannot have a custom filter on the dashboard
> `SELECT count(*) FROM actionTracker (nolock) where xxx = xxx`

**Comment by philipsagala** [comment]
> Hi @philipsagala
> 
> You would have to modify the driver to include `(nolock)` or maybe it can be work with a `View`. Or maybe set it globally: https://stackoverflow.com/questions/1035740/sql-server-how-to-set-nolock-hint-as-a-default
> 
> Why can't you have custom filters, when using SQL? Have you seen the documentation for parameters?
> https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html

The driver for metabase.jar? How to modify the driver?

**Comment by philipsagala** [comment]
Why I need to be able to do it on custom query because since the result to count came from 1 million rows to 8 million rows every time we do the query if it's locking the table it's can make our server down because the DB server cannot serve another request except my request.

Why we need this so badly:
1. Our marketing is very active updating metabase and the dashboard with custom query.
2. If they do it via custom query the can set some preset on the dashboard

**Comment by flamber** [comment]
@philipsagala You can see how to write drivers here:
https://github.com/metabase/metabase/wiki/Writing-A-Driver
But it seems like it will be considered added in future versions of Metabase, hence the 0.33 milestone.

**Comment by philipsagala** [comment]
I decide to limit our user to use the query in our operational
