### ISSUE TITLE
Metabase does not recognize data fields that have been renamed

### ISSUE THREAD

**Issue by kasanchez** [metabase/metabase#9855]
- My browser and the version:  Chrome Version 73.0.3683.103
- My operating system: (e.x. OS X 10, Windows XP, etc) OS Mojave 10.14.4
- My databases: Redshift 
- Metabase version: (e.x. 0.19.3) Metabase 0.32.5
- Metabase hosting environment: Elastic Beanstalk
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)

- *Repeatable steps to reproduce the issue*

1. In Redshift I renamed about 30 columns to a table that has already synced in Metabase. 
2. Admin Panel --> Data Model --> Schema --> Table
3. Navigate to each column --> Settings --> Click `Discard cached field values` --> Click `Rescan this field` 
4. Wait 30 minutes, create a new custom question
5. Get the error: ```[Amazon](500310) Invalid operation: column XXXX does not exist```

**Comment by flamber** [comment]
Hi @kasanchez 
You need to sync the database again, which is only done once a day normally.
Admin Settings > Databases > (database) > "Sync database schema now"
You can check the log to see the sync process.

**Comment by kasanchez** [comment]
hi @flamber I should have included that I've also done that a few times without any luck

**Comment by flamber** [comment]
Okay, but what warnings/errors do you see in the log?

**Comment by kasanchez** [comment]
hi @flamber the issue was resolved with the most recent update- version 0.32.6

**Comment by camsaul** [comment]
Hey @kasanchez if you haven't already please upgrade to 0.32.7 which was just released, it has a few critical bugfixes

**Comment by kasanchez** [comment]
hey @camsaul my account doesn't show a new update is available, but when it does I'll upgrade.
