### ISSUE TITLE
When I create a new Admin user they don't show up as admins on People page until refreshing

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9857]
On 0.32.5

1.  Go to Admin > People
2.  Add Someone 
3.  Select "Make this user an admin"
4. `Create`
5.  New user shows up on People list but their `Groups` shows up as `Default`
6. Hit refresh
7. New user `Groups` now shows up as `Admin`

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
