### ISSUE TITLE
Redirect to an ad-hoc question broken

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9858]
Someone sent me a link to

https://my-metbase-instance.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NTYxNywiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwyNzI5NDZdLDE1XV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MjV9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiZW1wbG95ZWVzIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXX0sIm9yaWdpbmFsX2NhcmRfaWQiOjY3OH0=

I wasn't logged in so I had to log in and it redirected me to

https://my-metabase-instance.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NTYxNywiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwyNzI5NDZdLDE1XV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MjV9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiZW1wbG95ZWVzIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXX0sIm9yaWdpbmFsX2NhcmRfaWQiOjY3OH0=#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NTYxNywiZmlsdGVyIjpbImFuZCIsWyI9IixbImZpZWxkLWlkIiwyNzI5NDZdLDE1XV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6MjV9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7ImdyYXBoLmRpbWVuc2lvbnMiOlsiZW1wbG95ZWVzIl0sImdyYXBoLm1ldHJpY3MiOlsiY291bnQiXX0sIm9yaWdpbmFsX2NhcmRfaWQiOjY3OH0=

(The has seems to have been duplicated)

That page is just an error page, and hitting refresh didn't fix it; the only way to actually see the question was to hunt down the original link and click it a second time.

**Comment by camsaul** [comment]
Related: #6317.

If I remember correctly #6317 was still happening in 0.31.x, and this new one started happening in 0.32.x, so when we fix this we should check and see whether #6317 is fixed as well and close them together

Or should we merge these into a single issue?

**Comment by flamber** [comment]
Just tested, this is also fixed by #12425 which fixed #6317
