### ISSUE TITLE
Deactivating an admin user requires switching them to non-admin, then refreshing page

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#9859]
To deactivate an admin user you first have to switch them to the `Default` (non-admin) group. Then because of what is probably the same issue as #9857 I have to manually refresh the page before the option to deactivate them pops up in the context menu.

There's no reason I can see why admins can't be deactivated without making them non-admin first, the only rule is you're not allowed to deactivate (or make non-admin) the last admin of the instance.

**Comment by paulrosenzweig** [comment]
> the only rule is you're not allowed to deactivate (or make non-admin) the last admin of the instance.

What about disallowing users from deactivating themselves (and making themselves non-admin)? That slightly more limiting but seems like it'd be fine in typical use.
