### ISSUE TITLE
order   of columns 

### ISSUE THREAD

**Issue by qhuiliuliu** [metabase/metabase#9864]
when i select the table ,the fields ware order by alphabet. i want to change the order by The database which the source table in . how should i do

**Comment by flamber** [comment]
Hi @qhuiliuliu 
Please only create your question in one place - and use the forum for questions and troubleshooting:
https://discourse.metabase.com/t/field-order-problem/6067

**Comment by mazameli** [comment]
I think this is an implicit request for the ability to define the default sort order of columns for tables, which is a dupe of https://github.com/metabase/metabase/issues/3720
