### ISSUE TITLE
Add "Get Answer/Refresh" Button to Dashboards as well

### ISSUE THREAD

**Issue by vvaezian** [metabase/metabase#9871]
Currently in a dashboard with filters, changing values of any filter refreshes the dashboard automatically.  
I think it is good to have the option to turn this off (e.g. at top-right section of dashboards), which should result in showing "Get Answer/Refresh" Button when filters values change (similar to Questions).

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
Hi @vvaezian 
I think you're asking for a slightly different version than #6072, but almost the same essence. Right?
Which version are you using? Queries should be cancelled, when you change filters.
On 0.32.5 I'm seeing `Output chan closed, canceling keepalive request.`, when I change filters, while cards are trying to load, and I never see the first filter result.
Slightly related to #8030 and #9778

**Comment by vvaezian** [comment]
Hi @flamber. Thanks for the comment. I edited my question.
I'm using v0.31.2 (I don't think the behavior changed in the last release). 
The thing I'm asking is basically two things:

1. Make it possible to turn off the auto-refresh when filters change (similar to the current setting for auto-refresh of the whole dashboard at top-right which defaults to "off")
2. if the above setting is set to "off", show a "Get Answer/ Refresh" button after changing filter values.

**Comment by x670** [comment]
Hello, that is great idea!
In my opinion, optimum approach is:
1. Add [refresh] button. Useful feature for pros and people, that didn't think of to refresh web page
2. On filter updating refresh only queries, that are related to this filter. Little optimization making big deal for large heavy dashboards and high-loaded databases
3. Dashboard option to turn off auto-refresh. One more optimization

**Comment by mlm603** [comment]
Being able to force users to hit a "Run" button to rerun the queries after changing filters would be a big help for my team. We have some queries that are way too intensive when they don't have filters applied. Our dashboards have default filters for this reason, but when the user wants to change the filter, they'll usually remove the initial filter which triggers a bunch of large queries and strains our database.

**Comment by Tony-metabase** [comment]
Closing as part of https://github.com/metabase/metabase/issues/29267
