### ISSUE TITLE
No results image on non-root embedded dashboards does not render

### ISSUE THREAD

**Issue by stevewritescode** [metabase/metabase#9876]
The image paths for `no_results.svg` point to a non-existent relative location for embedded dashboards that are loaded from a non-root path inside the embedding website.

From what I can tell this is similar issue to #9405, but for a different place in the app.

In the image below, see how the embedded dashboard loads correctly when the URL is input directly into metabase at the root path (left), but the same dashboard loaded through our app (right), which proxies back to metabase at a non-root location, triggers a 404 when loading `no_results.svg`

![no_results_404](https://user-images.githubusercontent.com/34346366/57023990-7aa65900-6c01-11e9-96f1-2a69993dd7b0.png)

I can repro on Firefox 66 and Chrome 74 running MacOS 10.14. Metabase v0.32.4

**Comment by stevewritescode** [comment]
From what I can tell, the image path reference in code accidentally "breaks out" of the non-root path and attempts to load the image from too far up the URL path. This seems like a similar issue to #8848

**Comment by flamber** [comment]
Hi @stevewritescode 
I'm pretty sure it's fixed by #9795, which should be included in the upcoming 0.32.6

**Comment by stevewritescode** [comment]
Thanks for the follow-up! Looking at the code I think it will - I'll close this issue and re-open if I experience any further trouble after that fix.

**Comment by camsaul** [comment]
This was fixed by #9795, but it was merged into `master`, so it will ship as part of our `0.33.0` release when that it ready.
