### ISSUE TITLE
Day granularity bar charts not rendered with druid driver

### ISSUE THREAD

**Issue by ghost** [metabase/metabase#9881]
- Your browser and the version: Chrome  74.0, Firefox 60.6.1
- Your operating system: Windows 10
- Your databases: Druid 0.14
- Metabase version: 0.32.5
- Metabase hosting environment: Linux/CentOS7.2
- Metabase internal database: H2

Hello

I have empty charts when I try to visualize bar charts with day granularity:
![day-bar-empty](https://user-images.githubusercontent.com/50138210/57064913-231ef080-6cc8-11e9-952a-c23f13161fcc.png)

The data can be visualized in raw data table or other charts except Line+bar, area, line:
![day-raw-data](https://user-images.githubusercontent.com/50138210/57064930-2a45fe80-6cc8-11e9-9100-2ce19a7e2a4c.png)

The issue is not reproduced for granularities other than day.

Druid driver has TZD info for day format:
https://github.com/metabase/metabase/blob/9aa7b4cad69fc6e3194a502d565a9ba30f11f68d/modules/drivers/druid/src/metabase/driver/druid/query_processor.clj#L715
At front end side, parsing the date fails because moment.js doesn't support anymore day format with TZD:
https://github.com/metabase/metabase/blob/9aa7b4cad69fc6e3194a502d565a9ba30f11f68d/frontend/src/metabase/lib/time.js#L49
Example of moment parsing yyyy-MM-ddZZ exception:
https://jsfiddle.net/1qfLw9rk/

Thank you

**Comment by sbelak** [comment]
Previous occurrences: #9235 and #9690. Keeping this one as it has the clearest steps to repo

**Comment by amin-amirali** [comment]
Same issue here, 0.31.0 was the last that worked OK for us.

**Comment by emetselaar** [comment]
Same issue - when I edit the query and change `yyyy-MM-ddZZ` to `yyyy-MM-dd` I can get the line and bar chart working (but loose the parametrization in dashboards)

**Comment by SagiRashish** [comment]
Any updates on this issue?

**Comment by sbelak** [comment]
Fixed in #10782
