### ISSUE TITLE
Use external library in javascript for embed graph

### ISSUE THREAD

**Issue by gmisterk** [metabase/metabase#9884]
Hi all,

I discover https://apexcharts.com and it will be very cool to use it when i embed a question or dashboard

Anybody have experience with this ?

**Comment by flamber** [comment]
@gmisterk Please only post in one place:
https://discourse.metabase.com/t/custom-charts-and-graph/6110

**Comment by salsakran** [comment]
Metabase uses DC.js under the hood. While we might revisit this and go a different direction, the probability of us support multiple charting libraries is pretty much 0.

**Comment by gmisterk** [comment]
Hi Salskran,
Thanks for your reply, so if metabase use DC.js, why it's not easy to show values in  barchart like this exemple : https://dc-js.github.io/dc.js/examples/bar-extra-line.html

**Comment by flamber** [comment]
@gmisterk Sounds like you're asking for #4788 - go and upvote by clicking :+1: on the first post
