### ISSUE TITLE
New question: filter by broken

### ISSUE THREAD

**Issue by joshhopkins** [metabase/metabase#9886]
- Your operating system: MacOS 10.14.4 (18E226)
- Your databases: Postgres, MongoDB
- Metabase version:  0.32.5.0
- Metabase hosting environment: MacOS
- Metabase internal database: H2

Menus within the New Question flow is super buggy:

- `Data` dropdown doesn't always navigate well
- `Filter By` dropdown doesn't appear at all

Completely reinstalled Metabase and its still an issue.

**Comment by mazameli** [comment]
Could you please be a bit more descriptive about what you mean by "`data` dropdown doesn't always navigate well?"

When you click on `filter by` are you saying it never opens? Do you see any errors in the JavaScript console when clicking on that button? Which web browser are you using?

**Comment by joshhopkins** [comment]
> Could you please be a bit more descriptive about what you mean by "data dropdown doesn't always navigate well?"

Sure. I mean that paging through databases (up/down levels) was only working half the time.

> When you click on `filter by` are you saying it never opens?

That's right. However, I just tested again and it appears to be working as expected (no changes since). Strange.

> Do you see any errors in the JavaScript console when clicking on that button? Which web browser are you using?

This is the MacOS app. Can't see any errors now – are these logged somewhere?

**Comment by flamber** [comment]
You can see the log in Admin Settings > Troubleshooting > Log

**Comment by mazameli** [comment]
Are you still seeing these issues in version 0.33?
