### ISSUE TITLE
Can't sync MariaDB System-Versioned tables

### ISSUE THREAD

**Issue by schlowmo** [metabase/metabase#9887]
When I try to sync a MariaDB database which contains [System-Versioned Tables](https://mariadb.com/kb/en/library/system-versioned-tables/) the sync of those tables silently fails. The log shows that Metabase is only finding tables without system-versioning.

**Steps to reproduce**
1. Use MariaDB >= 10.3.4
2. Create a new database _testDatabase_
3. Create two tables _(table1, table2)_ with the same columns
4.  Add system-versioning to _table2_ by executing `ALTER TABLE testDatabase.table2 ADD SYSTEM VERSIONING;`
5. Add _testDatabase_ to Metabase with Database type: MySQL

**Expected behaviour**
_table1_ and _table2_ get synced.

**Actual behaviour**
Only _table1_ gets synced.

**Environment**
Database: MariaDB 10.3.14
Metabase version: 0.32.5
Metabase hosting environment: Ubuntu 19.04
Metabase internal database: 10.3.14

**Comment by kurrestahlberg** [comment]
This might be fixed with https://github.com/mariadb-corporation/mariadb-connector-j/commit/5506f004a97885be9d565562bbecc9b9ea9044ea

Jira ticket here: https://jira.mariadb.org/browse/CONJ-776

**Comment by camsaul** [comment]
It seems like all we need to do here is bump the JDBC driver version and add a test

**Comment by flamber** [comment]
I've tested with 2.6.1 and it works, but didn't create a PR, since there seems to be some issue, so hoping for 2.6.2 instead.
