### ISSUE TITLE
"Group By" Everything and Stacked Chart not working

### ISSUE THREAD

**Issue by silent-film** [metabase/metabase#9894]
I have a couple of problems with a Visual Builder chart that I created that displays data about the number of disk writes that a docker container does.  (We are using an interval of ">=1m" for this chart, but I have seen the same issue with an interval of ">=5m".

![kibana_chart_issue_1](https://user-images.githubusercontent.com/50338457/57248789-e2491380-7008-11e9-8fc3-dc36eb61ca6d.png)
In this example, I am charting the maximum rate for each container and aggregating it (by summing) to display the total.  However, I say "Group By" everything and only one docker container is being displayed.  At 10:20, the value shown is 2.73, which is the "max" of one container.

![kibana_chart_issue_2](https://user-images.githubusercontent.com/50338457/57248896-305e1700-7009-11e9-84c4-fe806126be8d.png)
If I change the "Group By" to Terms and list the top x values, I can see the values being summed as I increase the "Top x" values to a correct value of 2.86 at 10:20 a.m.  Shouldn't "Everything" include all the values and be the same as the "Top 100" values?

![kibana_chart_issue_3](https://user-images.githubusercontent.com/50338457/57249183-e590cf00-7009-11e9-9bd8-4b6a915a8fe5.png)
The second issue is that when I have configuration #1 or #2 above, if I change my line type to stacked, I don't get any stacked lines. It is as if the stacked option does not work with this aggregation.

I have tested this Aggregation setup, (Max, then Series Agg Sum), and it calculates correctly if the timeline is 15 minutes (interval: 1m) or timeline 12 hours (interval: 5m) or timeline 24 hours (interval 10m).  So the interval calculation of ">=1m" is working correctly.

Browser: Firefox 67.0
OS: Windows 10, data and elasticsearch on Centos 7 server
Kibana 6.7.1 (same issue seen in 6.2.4)

**Comment by mazameli** [comment]
Hey, @silent-film, I believe you're looking for https://github.com/elastic/kibana

This is the Metabase repository. :)
