### ISSUE TITLE
Dashboards: Make adding new questions / editing question arrangement easier

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#9895]
Big dashboards can be really unwieldy to rearrange when you want to move stuff around and/or add something new.  A few ideas that could help improve things:

1. It would be really nice if attempting to move a card could make other cards "flow around" it as it's moved.  I recognize making this work in a really seamless, beautiful way might be difficult.
2. If you attempt to resize a card, allow resizing and push other things down/around as you do.
3. Allow click and drag selection or keyboard based multi selection to be able to grab a bunch of cards and move them together.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by gvisniuc** [comment]
If I may add one more thing it would be great to allow to open a question in a new tab when editing; the title of the question sometimes changes when entering edit mode and setting up filters.

**Comment by flamber** [comment]
@gvisniuc 
Opening cards in new tab is supported by using the Command/Meta-key - #8860 - not working for some specific OS/browsers.

**Comment by mazameli** [comment]
One of our customers additionally adds:

> In dashboard edit mode, if I have many cards on the top, after adding a new card at the bottom, I can't drag the new card to the top of the page as the screen doesn't scroll up. So I can't really add anything new at the top. Ideally, there should be a "move to the top" option and when you drag a card, the screen should move up to the top or bottom where there is available space.

**Comment by flamber** [comment]
@mazameli Sounds more like #5333 - updating `react-draggable` fixes it for some browsers.

**Comment by mazameli** [comment]
@flamber haha, yup, I found that issue right after posting that comment. Thanks man!

**Comment by geovanif** [comment]
news?

**Comment by bryanwinchell** [comment]
Agree, or at least a way to insert rows in the middle of the dashboard, moving everything below it down. 

Selecting multiple questions and being able to drag together would be nice too. Or Copy+Paste ability (even between dashboards) would be incredible.

**Comment by kulyk** [comment]
Hi everyone,

I'm excited to share dashboard UX improvements landed the `master` branch #16255
This issue also contains a request for multiple cards drag-n-drop which is out of scope for now. I'm about to make a separate issue for that during the day and drop it here

**Comment by kulyk** [comment]
#16290 is the new issue for tracking multiple cards moving feature
