### ISSUE TITLE
Problem with naming in a card

### ISSUE THREAD

**Issue by anastasiapapa** [metabase/metabase#9902]
<img width="1658" alt="Screenshot 2019-05-07 at 11 47 06" src="https://user-images.githubusercontent.com/43954136/57291012-e6d00380-70be-11e9-894c-aec0bb5280b8.png">
I have the above card, my table carries data for March and April and I have grouped by month (and type of what I am showing). As you can see at the bottom, I have in both parts of the graph "March, 2019", when the second one was supposed to be "April, 2019", as it shows also when I hover over the bar. Is a fix of it easy from your side? Tnx

**Comment by flamber** [comment]
Hi @anastasiapapa 
There's a couple of issues open about very similar issue - #5916 and #5246 
Does one of them look like a duplicate, then please close this issue and upvote the other by clicking :+1:

**Comment by anastasiapapa** [comment]
Hey @flamber. 
I checked the issues you suggested and I don't think it's the same situation. As I can tell from the others, it must have been a _timezone_ issue, but the date in my Postgres table is set manually and doesn't have to do with individual cases ("2019-03-01" for March and "2019-04-01" for April, for all entries in each case).
As far as if one of them is a duplicate of the other, no it is not. I am not expecting changes often in this table at all so what you see in the bars it was indeed supposed to look like that, aside from the problematic date in the bottom.

**Comment by flamber** [comment]
Sorry, there's a handful of issues that closely resembles, but I think you're seeing #7286

**Comment by anastasiapapa** [comment]
Yeah that seems to be the case with us too. But I see that the issue has been open for a year now huh?

Tnx for the info. I am closing this issue and upvoting the other one. Hoping for a fix soon
