### ISSUE TITLE
Variables in notifications

### ISSUE THREAD

**Issue by RFMVilt** [metabase/metabase#9905]
Hi guys.

I have one question that has some variables and returns a table with results. Is it possible to create a notification with specific values in the variables? or do I have to save the question with those specific values in the variables?

Best regards

**Comment by flamber** [comment]
Hi @RFMVilt 
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/
I'm not sure what you mean about notification. Are you referring to Pulses?
Pulses currently doesn't support filters - #5770 - go and upvote by clicking :+1: on the first post.
And please close this issue :)
