### ISSUE TITLE
Migrating from H2 to MySQL(Mariadb)

### ISSUE THREAD

**Issue by JanVoi** [metabase/metabase#9913]
So I am currently trying to migrate from a h2 application database to MySQL (MariaDB)
I run the following command:
java -jar metabase.jar load-from-h2 /xxx/metabase/metabase.db

So far so good it loads the config as wanted and it can verify connection to the database.
So i basicly i thought im good to go, till the following error occured:

Command failed with exception: Asser failed: Metabase can only transfer data from H2 to Postgres or MYSQL/MariaDB.
(#{:postgres :mysql} (mdb/db-type))

- Your browser and the version: Chrome 74.0.3729.131
- Your operating system: 
- Your databases: MariaDB 10.3.14
- Metabase version: 0.32.5
- Metabase hosting environment:  Linux version 4.9.0-8-amd64
- Metabase internal database: H2 

Also i have metabase running as a service, when i start metabase as service the error doesnt occure but i get a new metabase installation, so the migration kinda failed as well.

Any help?

Best regards
Jan

**Comment by flamber** [comment]
Hi @JanVoi 
You are probably missing either the environment variables or should include those as parameters.
https://www.metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres
If that fixes it for you, then please close this issue and use the forum in the future for questions and troubleshooting: https://discourse.metabase.com/

**Comment by JanVoi** [comment]
Hi @flamber 

I have the environment variables declared in the config file:

#!/bin/sh
# /etc/default/metabase
export MB_PASSWORD_COMPLEXITY=weak
export MB_PASSWORD_LENGTH=3
export MB_DB_TYPE=mysql
export MB_DB_DBNAME=metabase
export MB_DB_PORT=3306
export MB_DB_HOST=localhost
export MB_DB_USER=xx
export MB_DB_PASS=xx
export MB_PLUGINS_DIR=/xxx/metabase/plugins/
export MB_DB_FILE=/xxx/metabase/metabase.db
export MB_EMOJI_IN_LOGS=false

Then i start metabase and it loads the config file as wanted, it can connect to the database and migrats something, after running some migrations following INFO occurs.

INFO metabase.core :: Looks like this is a new Installation...

So i went in to the database to check what was migrated... he created a bunch of tables but basicly without any data in it.

Have you seen this behaviour befor?

**Comment by flamber** [comment]
I prefer using a command with the parameters, when doing a migration, since it gives me a little more control and I'm only doing it once. And then I run the command as the user who owns the H2 in the same directory. I think I used the following command a few months back:
```
java -jar -DMB_DB_TYPE=mysql -DMB_DB_DBNAME=metabase -DMB_DB_PORT=3306 -DMB_DB_USER=xx -DMB_DB_PASS=xx metabase.jar load-from-h2 ./metabase.db
```

**Comment by JanVoi** [comment]
Alright.

Using the command with parameters actually worked for me.

Thanks for the fast help, closing the issue.
