### ISSUE TITLE
Snowflake driver needs to be updated due to OCSP changes

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#9917]
See -
https://www.snowflake.com/blog/changes-to-how-snowflake-handles-ocsp/

**Comment by flamber** [comment]
Snowflake driver was updated to 3.10.2 in PR #11280, so I guess this can be closed(?).

**Comment by flamber** [comment]
Closing, since the driver was updated in 0.34.0 and haven't heard about any OCSP problems
