### ISSUE TITLE
Exit Admin link visible from non-admin section

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#993]
In a user testing video, I was able to see the "Exit Admin" link from a normal user's view in the main application. Browser was Safari.

![screen shot 2015-09-15 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/107439/9892667/dcb70b76-5bc5-11e5-9bff-00cdcc5e3fb9.png)

**Comment by agilliland** [comment]
I'm not able to reproduce this one.  @salsakran do we have any other information to go on?  i'm using safari.

**Comment by camsaul** [comment]
Is this still an issue?

**Comment by camsaul** [comment]
It looks like their UI was just generally in a weird/not-fully-loaded state. The "New Question" button isn't normally right next to that menu either. Motion to close @salsakran @agilliland

**Comment by agilliland** [comment]
yeah, we can close this.
