### ISSUE TITLE
Numeric styles don't work on smallest cards

### ISSUE THREAD

**Issue by nickcarenza** [metabase/metabase#9932]
Metabase v0.32.4

![image](https://user-images.githubusercontent.com/1222375/57469426-7b5f7080-723b-11e9-9363-8e57b0a206e6.png)

If I just expand the card to be one tile larger in each direction the expected formatting returns.

**Comment by flamber** [comment]
Hi @nickcarenza 
Reproduced on 0.32.6 - looks like a rounding issue, when you set the formatting style to Percentage.
Related to #4369
