### ISSUE TITLE
version 0.32.7 i18n cannot work

### ISSUE THREAD

**Issue by lokinell** [metabase/metabase#9938]
I use latest metabase docker image to run metabase. 
When I try to change default language as "chinese“，metabase's frontend UI cannot show as Chinese.

**Comment by lokinell** [comment]
Version 0.32.4 is OK

**Comment by pfinardi** [comment]
I have the same problem with 0.32.5 "italian". I upgrade to 0.32.7 but it is the same.

just a few sentences are translated. 


- browser: Firefox 66.0.3
- operating system: Ubuntu 18.04 LTS
- databases: Postgres
- internal database: H2 (default)
- Metabase version: 0.32.7
- Metabase hosting environment: Docker

**Comment by kdoh** [comment]
Thanks for bringing this to our attention! We'll try and look and see why this would be happening on more recent versions on 0.32

**Comment by camsaul** [comment]
@lokinell what browser are you using?

**Comment by flamber** [comment]
@camsaul 
I've just tested with language set to Spanish (es) on Chromium 73 and Firefox 66. Most of the interface is English, only a few places it's translated:
![image](https://user-images.githubusercontent.com/1447303/57571890-c9f24380-73d0-11e9-9912-2974ed896d24.png)

And `_metabaseLocalization` only looks like this:
`<script type="application/json" id="_metabaseLocalization">
  {"headers":{"language":"es","plural-forms":"nplurals=2; plural=(n != 1);"},"translations":{"":{"Metabase":{"msgid":"Metabase","msgstr":["Metabase"]}}}}
</script>`

Whereas 0.32.5 `window.MetabaseLocalization` looks like this:
`window.MetabaseLocalization = {"charset":"utf-8","headers":{"mime-version":"1.0","content-type":"text/plain; charset=UTF-8","content-transfer-encoding":"8bit","x-generator":"POEditor.com","project-id-version":"Metabase","language":"es","plural-forms":"nplurals=2; plural=(n != 1);"},"translations":{"":{"Your database has been added!":{"msgstr":["¡Tu base de datos ha sido añadida!"]},` ...cut long list of translations...

**Comment by camsaul** [comment]
Hey @flamber, thanks for helping us debug it. We should have a fix shortly as part of a 0.32.8 release tomorrow

**Comment by camsaul** [comment]
Fixed by #9956. We will be releasing this as part of 0.32.8 later today.
