### ISSUE TITLE
Date filter "between" in format D/M/Y

### ISSUE THREAD

**Issue by pfinardi** [metabase/metabase#9939]
### Feature requests and proposals

Is it possible that the date filter "between" respect the formatting settings?
So if I have D/M/YYYY in "formatting settings", the date filter "between" would ask the date in the same format.
Instead always use the format M/D/YYYY that is not so friendly in Europe.

Thanks a lot 
Paolo

- browser: Firefox 66.0.3
- operating system: Ubuntu 18.04 LTS
- databases: Postgres
- Metabase version: 0.32.7
- Metabase hosting environment: Docker
- internal database: H2 (default)

-------

**Comment by flamber** [comment]
Hi @pfinardi 
Looks like a duplicate of #9151 - go and upvote by clicking :+1: on the first post.

**Comment by pfinardi** [comment]
> Hi @pfinardi
> Looks like a duplicate of #9151 - go and upvote by clicking +1 on the first post.

thanks @flamber ... I upvote it!
