### ISSUE TITLE
postgresql error not reported anymore

### ISSUE THREAD

**Issue by thomasLeclaire** [metabase/metabase#9942]
- Your databases: (e.x. MySQL, Postgres, MongoDB, …) : PG9.6 and PG11
- Metabase version: (e.x. 0.19.3) 32.6 and 32.7. (everything ok in 32.5 and before)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12) : docker
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres) : PG9.6

- *Repeatable steps to reproduce the issue*
When i create some custom SQL request with explicit error or syntax error, I don't have anymore the PG error reported. 
I get in place a "No results" answer, like if my request was good but give no result. 

It's a huge regression.

**Comment by camsaul** [comment]
Fixed by #9958. We will be releasing this as part of 0.32.8 later today.

**Comment by lachesis** [comment]
Thanks for the fix. I suggest updating the patch notes for 0.32.8 to include this issue - the existing "i18n fixes" made me assume this update was not worth applying immediately.
