### ISSUE TITLE
Is there a ERROR/WARN entry logged to identify queries timing out?

### ISSUE THREAD

**Issue by jivagoalves** [metabase/metabase#9943]
First of all, thanks for creating Metabase!

We host a Metabase instance so that our client can build their own questions and dashboards. However, we'd like to be aware when any of their questions is timing out so that we can advise them accordingly.

Is there a way to identify questions that timed out by looking at Metabase's logs?

Thanks!

**Comment by flamber** [comment]
Hi @jivagoalves 
Timeout from where? The database, web server, reverse proxy or ?
If the reverse proxy timeout, then it will try to kill the active database query with a log.
There's no other timeouts as far as I can think of.

**Comment by jivagoalves** [comment]
@flamber I meant a Metabase timeout after the question/query took too long to be answered. I'm assuming Metabase has some default timeout to not wait forever for a question.

**Comment by flamber** [comment]
There's no timeout by Metabase on the query. The timeout, if any, is set on the database. And then Metabase would get whatever return error code your database generates.

**Comment by jivagoalves** [comment]
@flamber Thanks for clarifying. There must be something else timing out then. However, what's confusing me is what Metabase displays for a particular question.

It starts by loading as expected:
![Screenshot from 2019-05-11 11-45-52](https://user-images.githubusercontent.com/887937/57568658-86a0d080-73e2-11e9-9e34-7686fe19a8fc.png)

And then I see this message:
![Screenshot from 2019-05-11 11-44-42](https://user-images.githubusercontent.com/887937/57568667-a2a47200-73e2-11e9-8ef5-46578071628a.png)

And finally:
![Screenshot from 2019-05-11 11-45-24](https://user-images.githubusercontent.com/887937/57568669-aafcad00-73e2-11e9-892d-a65c77d2807a.png)

That led me to believe Metabase had some sort of timeout limit in order to display the messages above stating it is "taking awhile right now".

**Comment by flamber** [comment]
You haven't given any of the information requested, when creating a new issue, so it might be because you're using the Docker version, which includes a built-in Nginx reverse proxy with 60 seconds timeout - or which version, since there has been issues with async webserver, which should be fixed in 0.32.7

**Comment by jivagoalves** [comment]
@flamber Sorry, I forgot to mention we are using the docker image at https://hub.docker.com/r/metabase/metabase . By looking at the logs I see version `v0.31.2`. Thanks once again for clarifying.
