### ISSUE TITLE
Locale error on load (Version 0.32.5 > 0.32.7)

### ISSUE THREAD

**Issue by superainovacoes** [metabase/metabase#9944]
Hi guys, I upgraded my Metabase from 0.32.5 to 0.32.7 and the Portuguese version was unable to load. Now I see some words in English and others in Portuguese.
Anyone have a tip to help?
There's a error at console when I load the system
------------------------------------
05-10 10:04:01 [1mINFO metabase.core [0m :: Metabase Initialization COMPLETE
05-10 10:04:16 [1mWARN routes.index [0m :: Locale 'pt' not found.
-----------------------------
Ps. I'm running metabase by command line java.

**Comment by flamber** [comment]
Hi @superainovacoes It sounds like a duplicate of #9938

**Comment by superainovacoes** [comment]
Thanks @flamber ! I had not seen this previous call! Sorry! :)

**Comment by flamber** [comment]
Please close this issue :+1:
