### ISSUE TITLE
Dashboard Range Date Filter vs Query SQL

### ISSUE THREAD

**Issue by superainovacoes** [metabase/metabase#9945]
Hi guys, 
I have a issue about filter a question (query sql) by the the dashboard. When I apply the filter I see this error bellow.
![image](https://user-images.githubusercontent.com/16561866/57530113-ee84e780-730c-11e9-9c7a-00d94de3f5cc.png)
How can I see more information about the error to try to resolve?

At console I gotcha this error
![image](https://user-images.githubusercontent.com/16561866/57530166-078d9880-730d-11e9-8912-2c832fb13b92.png)

Thanks! :)

**Comment by flamber** [comment]
Hi @superainovacoes 
Please provide the requested information:
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
- Your operating system: (e.x. OS X 10, Windows XP, etc)
- Your databases: (e.x. MySQL, Postgres, MongoDB, …)
- Metabase version: (e.x. 0.19.3)
- Metabase hosting environment: (e.x. Mac app, Elastic Beanstalk, Docker, Heroku, Linux/Ubuntu 12)
- Metabase internal database: (e.x. H2 (default), MySQL, Postgres)
- Repeatable steps to reproduce the issue

**Comment by jianbowan** [comment]
browser and the version: (Chrome 52.1)
Your operating system: ( Windows 10)
Your databases: (Spark Sql)
Metabase version: ( 0.32.4)
Metabase hosting environment: (Centos7)
Metabase internal database: (Postgres)

This problem usually occurs when I first open the dashboard. So, I need to refresh a few times each time to display properly.

**Comment by flamber** [comment]
That's a known error that was fixed in 0.32.5 - and another fix in 0.32.6. Currently version 0.32.7 is the latest, but there are some issues with localization, so I guess we will see a 0.32.8 release very soon.

**Comment by jianbowan** [comment]
> That's a known error that was fixed in 0.32.5 - and another fix in 0.32.6. Currently version 0.32.7 is the latest, but there are some issues with localization, so I guess we will see a 0.32.8 release very soon.

Thank you very much! Can you tell me about the approximate time of the 0.32.8 online, I was preparing to upgrade to 0.32.7.

**Comment by flamber** [comment]
I don't know, but soon. And please remember to close this issue.
