### ISSUE TITLE
Support of regex in native Mongo Queries

### ISSUE THREAD

**Issue by Plaffont** [metabase/metabase#9949]
Hello,

I want to write a Mongo native query with a filter on a value not containing a string. This works fine in the visual editor, but when switching to native query the fonctionality is broken.

The `$match` generated by Metabase in the native query looks like `{"$match":{"subject":{"$not":"(?i)TEST"}}}` which is invalid for Mongo : `$not needs a regex or a document`

This is due to the fact that the Mongo native query editor only support valid JSON. But when requesting some Mongo operator require to write native regex (`$regex` can be used with a string but not `$not`).

This does not allow to use `$not` operator with his [regex usage](https://docs.mongodb.com/manual/reference/operator/query/not/index.html#not-and-regular-expressions).

For Mongo <= 4.0.6 `$not` [cannot be used](https://docs.mongodb.com/manual/reference/operator/query/regex/index.html#regex-and-not) with `$regex`, so I do not see any way to perform a `$match` with a value not contained.

This issue may be related with the issue #3653 but only if the fix is to allow non pure JSON Mongo query.

Thanks.

**Comment by LeonamMiiller** [comment]
{
    "$match":{
        
        
        "$or" : [{
            
            "$and" : [
                {"mytable.usernames": {"$regex" : "myword", "$options" : "i"}}, 
                {"mytable.usernames": {"$regex" : "anotherword", "$options" : "i"}}
            ]},
            
            {"anothertable.name" : ""}
        
		]}
},
just a exemple using " 

match { or ( ( value = value ), anothervalue ) }

**Comment by flamber** [comment]
Metabase 0.41.2 supports the format used in Mongo 4.0:
```
[
  {
    "$match": {
      "category": {
        "$not": {
          "$regex": "(?i)G"
        }
      }
    }
  },
  {
    "$count": "Count"
  }
]
```
