### ISSUE TITLE
Caching not working with MongoDB

### ISSUE THREAD

**Issue by nodesocket** [metabase/metabase#9953]
Hello,

Running the latest version of Metabase 0.32.7. I don't think query caching is working with the MongoDB driver. I have caching settings enabled and set to:

    MINIMUM QUERY DURATION: 10
    CACHE TIME-TO-LIVE (TTL) MULTIPLIER: 60
    MAX CACHE ENTRY SIZE: 2048

And running a query that averages 20-25 seconds. Running it multiple times takes the same amount of time. I would expect the first query to be slow_(ish)_, then Metabase to cache the result.

The query I am running should be static, i.e. is a fixed a date range with a group by minute.

You can see in the logs it claims to use the cache, but the requests take 27s, 26s, 25s each time run in a row. I am guessing that MongoDB is adding something unique to the query. That’s a problem as it means nothing can be cached using MongoDB driver.

    May 10 02:03:15 INFO metabase.api.card :: Question's average execution duration is 22679 ms; using 'magic' TTL of 1361 seconds 💾
     May 10 02:03:15 INFO metabase.query-processor.middleware.cache :: Returning cached results for query 💾
    May 10 02:03:15 DEBUG metabase.middleware.log :: POST /api/card/1/query 200 [ASYNC: completed] 48 ms (6 DB calls) Jetty threads: 5/50 (3 idle, 0 queued) (49 total active threads) Queries in flight: 0
    May 10 02:04:02 DEBUG metabase.middleware.log :: POST /api/dataset 200 [ASYNC: completed] 27 s (13 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (50 total active threads) Queries in flight: 0
    May 10 02:04:35 DEBUG metabase.middleware.log :: POST /api/dataset 200 [ASYNC: completed] 27 s (13 DB calls) Jetty threads: 4/50 (4 idle, 0 queued) (48 total active threads) Queries in flight: 0
     May 10 02:05:50 DEBUG metabase.middleware.log :: POST /api/dataset 200 [ASYNC: completed] 26 s (13 DB calls) Jetty threads: 4/50 (3 idle, 0 queued) (48 total active threads) Queries in flight: 0
     May 10 02:09:55 DEBUG metabase.middleware.log :: POST /api/dataset 200 [ASYNC: completed] 25 s (13 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (49 total active threads) Queries in flight: 0
     May 10 02:10:25 DEBUG metabase.middleware.log :: POST /api/dataset 200 [ASYNC: completed] 25 s (13 DB calls) Jetty threads: 4/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 0

**Comment by camsaul** [comment]
Hey @nodesocket, caching is currently only enabled when you run queries for saved Questions (e.g. the `POST /api/card/:id/query` API endpoint. Running ad-hoc queries (via the `POST /api/dataset` API endpoint) does not use the cache.

**Comment by nodesocket** [comment]
@camsaul ahhh that was it. Needed to save the question. Now seeing cached responses.
