### ISSUE TITLE
Dockerised Metabase only downloading the first 2k results after upgrading to 0.32.7

### ISSUE THREAD

**Issue by vivekaditya** [metabase/metabase#9965]
Looks like this issue is not fixed in[ v0.32.7](https://github.com/metabase/metabase/releases/tag/v0.32.7)
Anyone else having the same issue in v0.32.7 ?

We are using dockerised version of latest metabase
<img width="487" alt="Screenshot 2019-05-14 at 12 00 23 PM" src="https://user-images.githubusercontent.com/7223063/57675539-efd14f80-763f-11e9-90ea-81abdae786e2.png">

Still for queries with results exceeding 2k return with exactly 2k results.

_Originally posted by @vivekaditya in https://github.com/metabase/metabase/issues/9831#issuecomment-491767987_

**Comment by flamber** [comment]
Hi @vivekaditya 
Do you see the same issue on 0.32.8?
Do you see any errors in the logs, when you're downloading results with more than 2000 rows?
What database are you downloading from?
Is it a problem for all types, CSV, XLSX, JSON?
Are you downloading via the question, or via public sharing?

**Comment by ratheesh-kr** [comment]
Hello, I am also facing the same issue in 0.32.8.. I am connecting using PostgreSQL

**Comment by flamber** [comment]
@ratheesh-kr Unless you provide steps-to-reproduce or error logs, then we will never find the problem.

**Comment by camsaul** [comment]
@vivekaditya @ratheesh-kr limiting rows to 2000 is normal behavior for the `POST /api/card/:id/query` and `POST /api/dataset` endpoints and for Pulses; you can use `POST /api/card/:id/query/:format` or `POST /api/dataset/:format` instead (where format is one of json, csv, or xlsx to download results if you want more than the usual 2000.
