### ISSUE TITLE
"Cannot reference a legacy SQL view in a standard SQL query."  in visual builder.

### ISSUE THREAD

**Issue by dzarlax** [metabase/metabase#9969]
I'm trying to ask a question with visual query builder. 
Database: BigQuery
Metabase: v0.32.8

When submitting - getting an error:
"Cannot reference a legacy SQL view in a standard SQL query.

I know, that you switched to Standard SQL, but I see this error.

**Comment by flamber** [comment]
Closing, since the error is coming from BigQuery, which doesn't support mixing dialects.
https://stackoverflow.com/questions/54319806/standard-sql-calling-legacy-sql-usecase-for-external-application-to-big-query
