### ISSUE TITLE
Filtered filed names in the filters tab not visible. 

### ISSUE THREAD

**Issue by vabhishek6** [metabase/metabase#9972]
**Bug description**
Unable to see the filtered filed names in the filters tab .This makes it hard to see all applied filters. This also limits the ability to only delete the filter by clicking on the **X** icon.

![Screenshot from 2019-05-14 15-47-19](https://user-images.githubusercontent.com/10140218/57707464-9a0c9f80-765f-11e9-8ccd-090a6b7ae4ac.png)

**Technical details:**

- Metabase version: v0.32.7
- Operating System :Ubuntu 16.04.6 LTS
- Metabase hosting environment: Ubuntu 16 VM
- Metabase internal database: Postgres
- Databases: MySQL, Postgres
- Command used to start : java -Xmx8g -jar /home/qa/Metabase/metabase.jar &
- Browser: Chromium Version 73.0.3683.86 (Official Build)

**Repeatable steps to reproduce the issue**
Create a query with multiple filters and create a new visualization with Line + Bar graph .

**Comment by flamber** [comment]
Hi @vabhishek6 Looks like a duplicate of #8971, if yes, then please close this issue.

**Comment by vabhishek6** [comment]
@flamber yep looks like a duplicate , closing it.
