### ISSUE TITLE
Filter on metrics in Druid

### ISSUE THREAD

**Issue by avitorovic** [metabase/metabase#9979]
I am trying to filter out on a metric (Number type) in Metabase 29. The backed in Druid. This does not work - when I look into native queries, I see that the filter is simply omitted.

**Comment by flamber** [comment]
Hi @avitorovic 
Version 0.29 is almost a year old. Current version is 0.32.8.
For questions or troubleshooting, please use the forum: https://discourse.metabase.com/
And please close this issue :+1:

**Comment by avitorovic** [comment]
Thanks for the reply. Does it mean this feature should be supported in Metabase 0.32.8? If yes, we will upgrade, try it out, and report if it does not work on https://discourse.metabase.com/.

**Comment by flamber** [comment]
I do not know, since I don't have Druid. But you're asking a question about a very old version.
You use the forum for questions and troubleshooting.
And the issue tracker for detailed bugs and feature requests.
