### ISSUE TITLE
Dashboard with BigQuery database shows error for Metabase 0.32.7/8 

### ISSUE THREAD

**Issue by attsn** [metabase/metabase#9980]
Dashboards with BigQuery database are failing in Metabase 0.32.x. version.
We tried with latest version 0.32.7 and 0.32.8 as well.

Same dashboards works fine in 0.31.2.

For upgrade we have just launched metabase application with latest 0.32.x jar file.
We also checked issue #9915
Please let us know if we are missing something ?

error message - "Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion"

PFB the complete error message for your reference -

root@metabase-upgrade-test:/apps/java# /usr/bin/java -jar metabase-0.32.8.jar
05-15 09:31:37 INFO metabase.util :: Loading Metabase...
05-15 09:31:37 INFO metabase.util :: Maximum memory available to JVM: 14.7 GB
05-15 09:31:39 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. ??
 For more information, see https://metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest
05-15 09:31:41 INFO metabase.driver :: Registered abstract driver :sql  ??
05-15 09:31:44 INFO metabase.core :: Starting Metabase in STANDALONE mode
05-15 09:31:44 INFO metabase.server :: Launching Embedded Jetty Webserver with config:
 {:port 3000}

05-15 09:31:44 INFO metabase.core :: Starting Metabase version v0.32.8 (16be46d release-0.32.x) ...
05-15 09:31:44 INFO metabase.core :: System timezone is 'Etc/UTC' ...
05-15 09:31:44 INFO metabase.plugins :: Loading plugins in /apps/java/plugins...
05-15 09:31:44 DEBUG plugins.classloader :: Setting current thread context classloader to NEWLY CREATED classloader clojure.lang.DynamicClassLoader@3e898efe...
05-15 09:31:44 INFO plugins.classloader :: Added URL file:/apps/java/plugins/metabase-sparksql-deps-1.2.1.spark2-standalone.jar to classpath
05-15 09:31:44 INFO plugins.dependencies :: Plugin 'Metabase BigQuery Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
05-15 09:31:44 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
05-15 09:31:44 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase BigQuery Driver"]
05-15 09:31:45 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Oracle Driver due to required dependencies. Metabase requires the Oracle JDBC driver in order to connect to Oracle databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/oracle.html for more details.

05-15 09:31:45 INFO plugins.dependencies :: Metabase Oracle Driver dependency {:class oracle.jdbc.OracleDriver} satisfied? false
05-15 09:31:45 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Oracle Driver" "Metabase BigQuery Driver"]
05-15 09:31:45 INFO plugins.dependencies :: Plugin 'Metabase Google Analytics Driver' depends on plugin 'Metabase Google Drivers Shared Dependencies'
05-15 09:31:45 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? false
05-15 09:31:45 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Google Analytics Driver" "Metabase Oracle Driver" "Metabase BigQuery Driver"]
05-15 09:31:45 INFO plugins.dependencies :: Metabase cannot initialize plugin Metabase Vertica Driver due to required dependencies. Metabase requires the Vertica JDBC driver in order to connect to Vertica databases, but we can't ship it as part of Metabase due to licensing restrictions. See https://metabase.com/docs/latest/administration-guide/databases/vertica.html for more details.

05-15 09:31:45 INFO plugins.dependencies :: Metabase Vertica Driver dependency {:class com.vertica.jdbc.Driver} satisfied? false
05-15 09:31:45 INFO plugins.dependencies :: Plugins with unsatisfied deps: ["Metabase Vertica Driver" "Metabase Google Analytics Driver" "Metabase Oracle Driver" "Metabase BigQuery Driver"]
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlserver...
05-15 09:31:45 INFO metabase.driver :: Registered abstract driver :sql-jdbc (parents: :sql) ??
Load driver :sql-jdbc took 32 ms
05-15 09:31:45 INFO metabase.driver :: Registered driver :sqlserver (parents: #{:sql-jdbc}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :redshift...
05-15 09:31:45 INFO metabase.driver :: Registered driver :postgres (parents: :sql-jdbc) ??
Load driver :postgres took 15 ms
05-15 09:31:45 INFO metabase.driver :: Registered driver :redshift (parents: #{:postgres}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :hive-like...
05-15 09:31:45 INFO metabase.driver :: Registered abstract driver :hive-like (parents: #{:sql-jdbc}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sparksql...
05-15 09:31:45 INFO metabase.driver :: Registered driver :sparksql (parents: #{:hive-like}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sqlite...
05-15 09:31:45 INFO metabase.driver :: Registered driver :sqlite (parents: #{:sql-jdbc}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :mongo...
05-15 09:31:45 INFO metabase.driver :: Registered driver :mongo  ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :snowflake...
05-15 09:31:45 INFO metabase.driver :: Registered driver :snowflake (parents: #{:sql-jdbc}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :presto...
05-15 09:31:45 INFO metabase.driver :: Registered driver :presto (parents: #{:sql}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :druid...
05-15 09:31:45 INFO metabase.driver :: Registered driver :druid  ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :google...
05-15 09:31:45 INFO metabase.driver :: Registered abstract driver :google  ??
05-15 09:31:45 INFO plugins.dependencies :: Metabase Google Analytics Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
05-15 09:31:45 INFO plugins.dependencies :: Metabase BigQuery Driver dependency {:plugin Metabase Google Drivers Shared Dependencies} satisfied? true
05-15 09:31:45 DEBUG plugins.initialize :: Dependencies satisfied; these plugins will now be loaded: ["Metabase BigQuery Driver" "Metabase Google Analytics Driver"]
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :bigquery...
05-15 09:31:45 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google}) ??
05-15 09:31:45 INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :googleanalytics...
05-15 09:31:45 INFO metabase.driver :: Registered driver :googleanalytics (parents: #{:google}) ??
05-15 09:31:45 INFO metabase.driver :: Registered driver :h2 (parents: :sql-jdbc) ??
Load driver :h2 took 14 ms
05-15 09:31:45 INFO metabase.driver :: Registered driver :mysql (parents: :sql-jdbc) ??
Load driver :mysql took 16 ms
05-15 09:31:45 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
05-15 09:31:45 WARN metabase.db :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. See https://metabase.com/docs/latest/operations-guide/start.html#migrating-from-using-the-h2-database-to-mysql-or-postgres for more information.
05-15 09:31:45 INFO metabase.db :: Verifying h2 Database Connection ...
05-15 09:31:45 INFO metabase.driver :: Initializing driver :sql...
05-15 09:31:45 INFO metabase.driver :: Initializing driver :sql-jdbc...
05-15 09:31:45 INFO metabase.driver :: Initializing driver :h2...
05-15 09:31:45 INFO metabase.db :: Verify Database Connection ...  ?
05-15 09:31:45 INFO metabase.db :: Running Database Migrations...
05-15 09:31:45 INFO metabase.db :: Setting up Liquibase...
05-15 09:31:46 INFO metabase.db :: Liquibase is ready.
05-15 09:31:46 INFO metabase.db :: Checking if Database has unrun migrations...
05-15 09:31:47 INFO metabase.db :: Database Migrations Current ...  ?
05-15 09:31:47 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
05-15 09:31:47 INFO db.migrations :: Finished running data migrations.
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.activity-feed ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.dependencies ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.driver-notifications ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.last-login ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.metabot-lifecycle ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.notifications ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.revision ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.sync-database ??
05-15 09:31:47 INFO metabase.events :: Starting events listener: metabase.events.view-log ??
05-15 09:31:47 INFO metabase.task :: Initializing task SyncDatabases ??
05-15 09:31:47 INFO metabase.task :: Initializing task CheckForNewVersions ??
05-15 09:31:47 INFO metabase.task :: Initializing task SendAnonymousUsageStats ??
05-15 09:31:47 INFO metabase.task :: Initializing task SendAbandomentEmails ??
05-15 09:31:47 INFO metabase.task :: Initializing task SendPulses ??
05-15 09:31:47 INFO metabase.task :: Initializing task SendFollowUpEmails ??
05-15 09:31:47 INFO metabase.task :: Initializing task TaskHistoryCleanup ??
05-15 09:31:48 INFO metabase.core :: Metabase Initialization COMPLETE
05-15 09:31:52 WARN routes.index :: Locale 'en' not found.
05-15 09:31:57 DEBUG middleware.log :: GET /api/session/properties 200 7 ms (1 DB calls) Jetty threads: 7/50 (2 idle, 0 queued) (43 total active threads) Queries in flight: 0
05-15 09:31:57 DEBUG middleware.log :: GET /api/user/current 200 344 ms (3 DB calls) Jetty threads: 6/50 (3 idle, 0 queued) (44 total active threads) Queries in flight: 0
05-15 09:31:57 DEBUG middleware.log :: GET /api/user/current 200 3 ms (3 DB calls) Jetty threads: 6/50 (3 idle, 0 queued) (44 total active threads) Queries in flight: 0
05-15 09:31:58 DEBUG middleware.log :: GET /api/database 200 21 ms (4 DB calls) Jetty threads: 6/50 (3 idle, 0 queued) (44 total active threads) Queries in flight: 0
05-15 09:31:58 DEBUG middleware.log :: GET /api/setting 200 2 ms (0 DB calls) Jetty threads: 7/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0
05-15 09:31:58 DEBUG middleware.log :: GET /api/dashboard/98 200 206 ms (9 DB calls) Jetty threads: 6/50 (2 idle, 0 queued) (44 total active threads) Queries in flight: 0
05-15 09:31:58 INFO metabase.driver :: Initializing driver :google...
05-15 09:31:58 DEBUG plugins.classloader :: Setting current thread context classloader to shared classloader clojure.lang.DynamicClassLoader@3e898efe...
05-15 09:31:58 INFO plugins.classloader :: Added URL file:/apps/java/plugins/google.metabase-driver.jar to classpath
05-15 09:31:58 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.google...
05-15 09:31:58 INFO metabase.driver :: Registered abstract driver :google  ??
05-15 09:31:58 DEBUG middleware.log :: GET /api/collection/71 200 18 ms (3 DB calls) Jetty threads: 7/50 (2 idle, 0 queued) (49 total active threads) Queries in flight: 3
Load lazy loading driver :google took 163 ms
05-15 09:31:59 INFO metabase.driver :: Initializing driver :bigquery...
05-15 09:31:59 INFO plugins.classloader :: Added URL file:/apps/java/plugins/bigquery.metabase-driver.jar to classpath
05-15 09:31:59 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.bigquery...
05-15 09:31:59 INFO metabase.driver :: Registered driver :bigquery (parents: #{:sql :google}) ??
05-15 09:31:59 DEBUG middleware.log :: GET /api/database/36/metadata 200 280 ms (7 DB calls) Jetty threads: 6/50 (2 idle, 0 queued) (49 total active threads) Queries in flight: 3
Load lazy loading driver :bigquery took 457 ms
05-15 09:31:59 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@174ec51a: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
05-15 09:31:59 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@ff29b86: null
05-15 09:31:59 WARN metabase.util :: auto-retry metabase.driver.bigquery$process_native_STAR_$fn__580@3501d459: Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion
05-15 09:31:59 DEBUG middleware.log :: GET /api/field/41916 200 19 ms (7 DB calls) Jetty threads: 7/50 (2 idle, 0 queued) (49 total active threads) Queries in flight: 3
05-15 09:31:59 DEBUG middleware.log :: GET /api/field/41916/values 200 23 ms (4 DB calls) Jetty threads: 7/50 (2 idle, 0 queued) (49 total active threads) Queries in flight: 3
05-15 09:31:59 DEBUG middleware.log :: GET /api/field/41917/values 200 7 ms (4 DB calls) Jetty threads: 8/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 3
05-15 09:31:59 DEBUG middleware.log :: GET /api/field/41917 200 8 ms (6 DB calls) Jetty threads: 8/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 3
05-15 09:31:59 DEBUG middleware.log :: GET /api/field/41912 200 13 ms (6 DB calls) Jetty threads: 6/50 (2 idle, 0 queued) (50 total active threads) Queries in flight: 3
05-15 09:32:00 WARN middleware.process-userland-query :: Query failure {:status :failed,
 :class java.lang.NoClassDefFoundError,
 :error "Could not initialize class com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion",
 :stacktrace
 ("com.google.api.client.googleapis.services.AbstractGoogleClientRequest.<init>(AbstractGoogleClientRequest.java:133)"
  "com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.<init>(AbstractGoogleJsonClientRequest.java:57)"
  "com.google.api.services.bigquery.BigqueryRequest.<init>(BigqueryRequest.java:39)"
  "com.google.api.services.bigquery.Bigquery$Jobs$Query.<init>(Bigquery.java:1909)"
  "com.google.api.services.bigquery.Bigquery$Jobs.query(Bigquery.java:1883)"
  "--> driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:182)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:171)"
  "driver.bigquery$execute_bigquery.invokeStatic(bigquery.clj:173)"
  "driver.bigquery$execute_bigquery.invoke(bigquery.clj:171)"
  "driver.bigquery$process_native_STAR_$fn__580.invoke(bigquery.clj:267)"
  "util$do_with_auto_retries.invokeStatic(util.clj:431)"
  "util$do_with_auto_retries.invoke(util.clj:423)"
  "util$do_with_auto_retries.invokeStatic(util.clj:435)"
  "util$do_with_auto_retries.invoke(util.clj:423)"
  "driver.bigquery$process_native_STAR_.invokeStatic(bigquery.clj:266)"
  "driver.bigquery$process_native_STAR_.invoke(bigquery.clj:262)"
  "driver.bigquery$eval920$fn__922.invoke(bigquery.clj:516)"
  "query_processor$fn__40384$execute_query__40389$fn__40390.invoke(query_processor.clj:61)"
  "query_processor$fn__40384$execute_query__40389.invoke(query_processor.clj:55)"
  "query_processor.middleware.mbql_to_native$mbql__GT_native$fn__34664.invoke(mbql_to_native.clj:36)"
  "query_processor.middleware.annotate$result_rows_maps__GT_vectors$fn__32695.invoke(annotate.clj:368)"
  "query_processor.middleware.annotate$add_column_info$fn__32600.invoke(annotate.clj:303)"
  "query_processor.middleware.cumulative_aggregations$handle_cumulative_aggregations$fn__34144.invoke(cumulative_aggregations.clj:57)"
  "query_processor.middleware.limit$limit$fn__34637.invoke(limit.clj:19)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__40249.invoke(results_metadata.clj:86)"
  "query_processor.middleware.format_rows$format_rows$fn__34625.invoke(format_rows.clj:26)"
  "query_processor.middleware.add_dimension_projections$add_remapping$fn__31752.invoke(add_dimension_projections.clj:234)"
  "query_processor.middleware.add_row_count_and_status$add_row_count_and_status$fn__32146.invoke(add_row_count_and_status.clj:16)"
  "query_processor.middleware.driver_specific$process_query_in_context$fn__34386.invoke(driver_specific.clj:12)"
  "query_processor.middleware.resolve_driver$resolve_driver$fn__37215.invoke(resolve_driver.clj:15)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550$fn__33551.invoke(bind_effective_timezone.clj:9)"
  "util.date$call_with_effective_timezone.invokeStatic(date.clj:88)"
  "util.date$call_with_effective_timezone.invoke(date.clj:77)"
  "query_processor.middleware.bind_effective_timezone$bind_effective_timezone$fn__33550.invoke(bind_effective_timezone.clj:8)"
  "query_processor.middleware.store$initialize_store$fn__40274$fn__40275.invoke(store.clj:11)"
  "query_processor.store$do_with_new_store.invokeStatic(store.clj:35)"
  "query_processor.store$do_with_new_store.invoke(store.clj:31)"
  "query_processor.middleware.store$initialize_store$fn__40274.invoke(store.clj:10)"
  "query_processor.middleware.async$async__GT_sync$fn__33146.invoke(async.clj:19)"
  "query_processor.middleware.async_wait$runnable$fn__33277.invoke(async_wait.clj:71)"),
 :query

**Comment by Rohith6215** [comment]
@camsaul Any udpate on this issue ?

**Comment by camsaul** [comment]
Same issue as #10723 -- fixed in 0.33.2
