### ISSUE TITLE
Amazon Redshift JDBC Driver upgrade needed

### ISSUE THREAD

**Issue by cagdastulek** [metabase/metabase#9981]
We have received a notification from Amazon Redshift team with the following message (some parts redacted):
```
We have identified a potential issue related to your Amazon Redshift cluster(s). We have observed a large memory footprint resulting from a particular workload pattern when using a specific Amazon Redshift JDBC driver version 1.2.18.1036. This issue has been resolved with Amazon Redshift JDBC driver version 1.2.27.1051 or later [1]. To resolve this issue, please upgrade your Amazon Redshift JDBC driver to this version. We apologize for the inconvenience.

[1] https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html
```

We were planning to upgrade to latest minor version of Metabase but realized the master still points to `1.2.18.1036`: https://github.com/metabase/metabase/blob/master/modules/drivers/redshift/resources/metabase-plugin.yaml#L3

Hence we decided to report this as a bug.

Information about our Metabase setup:
- Amazon Redshift
- Metabase version: 0.32.4
- Metabase hosting environment: Heroku
- Metabase internal database: Postgres

**Comment by salsakran** [comment]
we updated master to the latest JDBC version - https://github.com/metabase/metabase/blob/master/modules/drivers/redshift/project.clj#L9

the version numbers you're referring to are crufty but not accurate.

We'd strongly suggest upgrading to the most recent version if you're on redshift.

**Comment by camsaul** [comment]
Sorry. I forgot to update the internal version number. The actually number is in modules/drivers/redshift/project.clj 

If you want to update the internal version number to match we will gladly accept a PR

**Comment by cagdastulek** [comment]
I would be happy to create a PR, unfortunately, I am not good at Java and Java project configuration.

**Comment by cagdastulek** [comment]
To clarify my understanding, if we upgrade to latest version of Metabase, is that problem going to be solved?

**Comment by camsaul** [comment]
@cagdastulek yes

**Comment by gloriaanthony** [comment]
Can you please help with the require steps to upgrade JDBC Driver to version  1.2.36.1060 in AWS. Thanks.

**Comment by flamber** [comment]
@gloriaanthony Redshift was upgraded in #11181 to 1.2.36.1060 and will be part of next release.
