### ISSUE TITLE
Float significant digits in auto y-axis range

### ISSUE THREAD

**Issue by vietvudanh** [metabase/metabase#9986]
Metabase: v0.32.5

When using auto y-axis value for float type, zero value is shown as: `-0.00000000018` as show in picture. 

It should be either 0 or a smaller number of digits.

![Screen Shot 2019-05-16 at 10 53 37 AM](https://user-images.githubusercontent.com/4011756/57825557-867d4800-77c9-11e9-82e3-bdd7046e2fa9.png)

**Comment by flamber** [comment]
Reproducable in 0.32.8 with this query:
```SQL
SELECT 1 AS "x", 0.7 AS "y"
UNION ALL
SELECT 2 AS "x", -0.00000000018 AS "y"
UNION ALL
SELECT 3 AS "x", -0.7 AS "y"
```
But if you change the `0.7`/`-0.7` to example `0.4`/`-0.4`, then it shows `-0.00000000018` as `0`
Related to https://discourse.metabase.com/t/don-t-show-fraction-numbers/5629
