### ISSUE TITLE
Does updating keep the current plugin?

### ISSUE THREAD

**Issue by Jflick58** [metabase/metabase#9990]
Just a quick question, I've deployed v31 with the Oracle plugin. My admin panel is notifying me to upgrade to v32, if I run that upgrade will I lose the currently installed plugin?

**Comment by RMMSecurity** [comment]
It will replace the drivers in ./plugins if the driver is newer. It shouldn't replace other drivers in there.

**Comment by flamber** [comment]
@Jflick58 If that answered your question, then please close this issue. And use the forum for questions and troubleshooting in the future: https://discourse.metabase.com/
