### ISSUE TITLE
SQL code generation for Redshift generates too much unnecessary code

### ISSUE THREAD

**Issue by Luckymethod** [metabase/metabase#9991]
This happens using Metabase 0.32.5.

When I'm using the visual query builder to get a jump start the SQL generator creates tons of unnecessary cast statements. For example this is what Metabase generates:

> SELECT date_trunc('month', CAST("lever_hire_prod"."tracks"."timestamp" AS timestamp)) AS "timestamp", count(distinct "lever_hire_prod"."tracks"."user_id") AS "count"
> FROM "lever_hire_prod"."tracks"
> WHERE CAST(extract(year from CAST("lever_hire_prod"."tracks"."timestamp" AS timestamp)) AS integer) = CAST(extract(year from CAST(getdate() AS timestamp)) AS integer)
> GROUP BY date_trunc('month', CAST("lever_hire_prod"."tracks"."timestamp" AS timestamp))
> ORDER BY date_trunc('month', CAST("lever_hire_prod"."tracks"."timestamp" AS timestamp)) ASC

and this is a much more readable and shorter version of the same query that does the same thing:

`SELECT date_trunc('month', lever_hire_prod.tracks.timestamp) AS "timestamp",
       count(distinct lever_hire_prod.tracks.user_id) AS "count"
FROM lever_hire_prod.tracks
WHERE extract(year from lever_hire_prod.tracks.timestamp) = extract(year from CAST(getdate() AS timestamp))
GROUP BY date_trunc('month', lever_hire_prod.tracks.timestamp)
ORDER BY date_trunc('month', lever_hire_prod.tracks.timestamp) ASC`

Would it be possible to tune the SQL generation code to produce leaner queries?

**Comment by jornh** [comment]
#4043 seems related

**Comment by flamber** [comment]
This was fixed for many databases in 0.33.4, while there are still an outstanding issue #11837
