### ISSUE TITLE
User-Personal Favorites

### ISSUE THREAD

**Issue by chucksense** [metabase/metabase#9992]
I'd love to be able to "favorite"/"bookmark" a dashboard, question, etc and have it show up right on my homepage, so I don't have to go looking for it every time.

But this should be specific to just me, rather than pinning it for everyone.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by SearchingforWhimsy** [comment]
Same

**Comment by kulyk** [comment]
Coming in 43 🙂
